### ISSUE TITLE
valid email rejected IPv6 only MX

### ISSUE THREAD

**Issue by zoc** [tootsuite/mastodon#10002]
When a domain MX host only have AAAA record but no A record, then the domain is considered as invalid and user cannot create account / log in.

### Expected behaviour

domain with IPv6 only MX should be considered as valid.

### Actual behaviour

domain is considered as invalid. User cannot create account.

### Steps to reproduce the problem

Try to create an account using a domain for which only IPv6 MX exists

### Specifications

Found using 2.7.1 stable release.

**Comment by zoc** [comment]
Hi,

Just to say that the fix is pretty easy, I already did it on my installation to have everything working. Also tried to create a pull request to fix it, but then saw that it breaks unit tests, which I did not expected at first time. So, I closed it.

To be honest, I'm not a Ruby/Rails developer so I don't know how to fix the tests and BTW don't have so much time to setup a full dev. env. just for a one line fix.

**Comment by nightpool** [comment]
I'm happy to look at/try to fix the test failures if you re-open the PR

**Comment by zoc** [comment]
Hi @nightpool,

Thank you for the support. As I had destroyed my fork, I cannot reopen the initial PR.

So, I've created #10009. It contains the exact same fix.

**Comment by zoc** [comment]
I finally took some time to fix the tests. It was not so hard.
