### ISSUE TITLE
List of Federated Servers for a Particular Instance

### ISSUE THREAD

**Issue by orthros** [tootsuite/mastodon#1001]
I searched the UI and other issues, but I couldn't find a good answer to the question: "what other servers is my instance federated with?". 

I can see some basic statistics about the instance
![image](https://cloud.githubusercontent.com/assets/7820716/24725567/0a0b283c-1a15-11e7-82ca-563bba9e4fa4.png)
but not the level of detail I feel would be necessary to help users with accounts across multiple instances.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Siltaar** [comment]
Would be great to be able to access the list of connected instances and browse it.
This way, each instance would be a portion of "the" list of existing instances, still working if another fails.

**Comment by ashfurrow** [comment]
Since 1.2 this has been added to the admin interface. I think that's the extent of the plan, not positive though. @wxcafe do you know if we plan to expose that list for non-admins?

**Comment by wxcafe** [comment]
I don't think so nah.

**Comment by ashfurrow** [comment]
Okie done, I'm going to close this then. @orthros if you feel this hasn't been resolved to your satisfaction, please re-open or open a new issue. Thanks!
