### ISSUE TITLE
Stop tweeting @mastodon.social on twitter

### ISSUE THREAD

**Issue by af1** [tootsuite/mastodon#1002]
My twitter username is @mastodon, and it seems like some default sharing message is using "@mastodon.social" on twitter, which is flooding my mentions as it drops the .social from the mention tag. 

I would like my twitter mentions to be useful again. 

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mastodon** [comment]
Thanks for pulling me in! I am also completely unrelated to the project! Stop mentioning my username!

You get the point :D It's probably hopeless.

**Comment by af1** [comment]
😭😂😂

**Comment by PastaGringo** [comment]
😂👌🏻

**Comment by Angristan** [comment]
Major issue, please fix @Gargron 😂

**Comment by nightpool** [comment]
I think the right repo for this is probably mastodon-bridge? I don't think there are any sharing messages built into mastodon.

**Comment by veritas06** [comment]
How is this a development issue?

**Comment by af1** [comment]
Because it's doing something it shouldn't be doing.

**Comment by nightpool** [comment]
@swaldie @af1 can you close this issue in favor of https://github.com/tootsuite/mastodon-bridge/issues/12? thanks!

**Comment by swaldie** [comment]
Related to tootsuite/mastodon-bridge#12

Please move discussion there.
