### ISSUE TITLE
Deploying to heroku error

### ISSUE THREAD

**Issue by Matrix-Guy** [tootsuite/mastodon#1003]
On deploying to heroku I receive the following error.
...
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       KeyError: key not found: "S3_REGION"
       /tmp/build_6f874e2aad363d9a1cd1675d971913b2/tootsuite-mastodon-5442083/config/initializers/paperclip.rb:16:in `fetch'
...
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

Full log here: http://slexy.org/view/s20ceG31JT
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by robjloranger** [comment]
silly question, did you set an s3 region?

**Comment by Matrix-Guy** [comment]
i did, turns out not a valid one, weird stuff going on but simply re-fetching the variables from amazon worked, should've tried that first, thanks though xD
