### ISSUE TITLE
Temporarily pause timeline updates if there's been recent mouse movement

### ISSUE THREAD

**Issue by lmorchard** [tootsuite/mastodon#1004]
One of my biggest annoyances with TweetDeck is that things will often move out from under my mouse in between when I see it and when I've moved my pointer to interact with it. So, I end up targeting messages other than what I intended.

What I'd like to do is add some code that temporarily pauses changes to the timeline if there's been recent mouse movement over it. Not sure how long "temporarily" means, but my intent would be that things don't move while I'm in the middle of an intentional interaction.

Submitting this issue, but I hope to actually submit a PR myself once I've gotten deeper into the Mastodon stack.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
How's it going @lmorchard ? Anything we can do to help follow up with this?

**Comment by lmorchard** [comment]
> How's it going @lmorchard ? Anything we can do to help follow up with this?

I haven't actually started - I wouldn't be mad if someone else tackled it. Main help would be a magic wand that gives me more free time :)

**Comment by ashfurrow** [comment]
I wish I had such a wand 😄
