### ISSUE TITLE
tootctl media remove does not free up disk space

### ISSUE THREAD

**Issue by yingziwu** [tootsuite/mastodon#10049]
### Expected behaviour

After run ``tootctl media remove``, the disk space is released.

### Actual behaviour

Disk space has not been released.

### Steps to reproduce the problem

Before ``tootctl media remove``, the size of ``public/system`` is 1055 MB.
![image](https://user-images.githubusercontent.com/22741471/52833816-c45ec780-3119-11e9-8ad7-9e73e7f1609f.png)

Run ``tootctl media remove``, remove all media files.
![image](https://user-images.githubusercontent.com/22741471/52833841-dc364b80-3119-11e9-9578-315a509aa7c3.png)
```tootctl media remove``` print ``Removed 1337 media attachments (approx, 798 MB)``

Afer ``tootctl media remove``, the size of ``public/system`` is 1099 MB.
![image](https://user-images.githubusercontent.com/22741471/52834088-ee64b980-311a-11e9-8ad5-fc4a58841dd2.png)

### Specifications

    Debian 9.7
    Mastodon 2.7.1  (28866d329bafe676ba2c45e3b449be3d1ba6e9ce)
    Ruby 2.6.0p0
    PostgreSQL 9.6.10
    Redis 3.2.6

Some of my friends have also encountered this problem, e.g.
https://sn.angry.im/@PeterCxy/101587847205765435

**Comment by yingziwu** [comment]
In addition, after running ``tootctl media remove`` I have restarted the services of mastodon.

**Comment by AstroProfundis** [comment]
I have similar issue with my instance. My storage is ~300Gb large and on a remote Minio instance, when I run `tootctl media remove` I can observe disk space been freed for x00Mb in few minutes, but then no more than that (the command has been run for over 20h and is still processing so I'm not sure about the final result yet).

Is there any document about what exactly `tootctl media remove` do? Is it deleting all remote media from storage or just those meet some specific condition? Is there any way (e.g., dry run, or log, etc.) to check / verify if it's behaving as expected? Thanks.

**Comment by yingziwu** [comment]
After upgradee to 3.1.1 , I run ``tootctl media remove-orphans`` and found the file above mentioned were removed.
