### ISSUE TITLE
Bot user that boosts top toots -- to aid discoverability for users of new/small instances.

### ISSUE THREAD

**Issue by rwhaddad** [tootsuite/mastodon#1005]
Every instance should have an easy way to enable a standardized bot user to generate boosted toots of top toots. That way new/small sites can easily follow these top-toot-bots and get a good sample stream of content. The local users can then choose to follow some of the accounts that they see from the bots.

How should the bot choose? I'm not sure. Easiest choices are things like "25 starred/boosted toots", but what is the right number? 25? 10? 50? So maybe a better approach is "top starred/boosted toot of the past X minutes" ... but possibly harder to implement.

Without something like this, new/small instances are stuck in a chicken-and-egg situation.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by voronoipotato** [comment]
This sounds like a separate project. However being able to create a "bot" account might be useful for people who want to filter bots.

**Comment by coderobe** [comment]
Yeah this should really be a separate project.

**Comment by rwhaddad** [comment]
I understand the "separate project" argument. I haven't studied the API yet to see how easily it is done from the outside. The reason to do it inside the project would be have it be a standardized feature that all instances automatically had and that all instance managers would be aware of potentially subscribing to. Although, yes, maybe you'd end up wishing to sandbox it into a separate timeline for viewing?

The second idea in this "standardized bots to aid discoverability" theme is one that announces new accounts. This would be to attack the "William Shatner couldn't find me on Mastodon." problem. http://mashable.com/2017/04/05/mastodon-wont-survive/

As a standardized bot, it could get special treatment: e.g. content more easily searchable, and retained longer (does other content "expire"?) but hidden from normal federated timelines.

**Comment by wxcafe** [comment]
This should definitely be a separate project. Closing as invalid
