### ISSUE TITLE
connecting to activity pub ??

### ISSUE THREAD

**Issue by oceatoon** [tootsuite/mastodon#10051]
Hi 
we are currently trying add AP endpoints to our activityStream filled api 
is there a clear tutorial or step by step approach ?
we got the mastodon api working
but eveything we are doing listed in the https://blog.joinmastodon.org/2018/06/how-to-implement-a-basic-activitypub-server/ is not so clear 
we are trying to test first with a REST client to see results from the api 
but we're stuck on the starting line 
please help us bootstrap 
Thanks

**Comment by m4sk1n** [comment]
What exactly is unclear in this guide? I think even I can understand this tutorial 🤣

**Comment by PierreGbx** [comment]
indeed it seems clear in the reading 
but in usage , we are not able to get it working localy 
maybe some tweaks missing , or having to install webfinger localy 
by experience it often takes me many tutorials and ways of doing things to understand 
but documentation is still scares about implementing an ActivityPub api  
again today we are blocked here 
![testrested](https://user-images.githubusercontent.com/43531294/52851208-f0387800-312e-11e9-85f3-4c6201db5afe.png)

**Comment by m4sk1n** [comment]
@PierreGbx, it’s not that you can send posts from your Mastodon account using ActivityPub server2server API

**Comment by PierreGbx** [comment]
sorry i dont understand

**Comment by m4sk1n** [comment]
@PierreGbx, sorry, my English kinda sucks
it looks like you’re trying to post something from your Mastodon instance using ActivityPub API, that’s not what it’s used for. for this, you should use (https://docs.joinmastodon.org/api/guidelines/)[Mastodon client REST API]

**Comment by PierreGbx** [comment]
do you speak french ?

**Comment by PierreGbx** [comment]
We managed to build a mastodon client , it works fine 
but we want to access and interact with mamot mastodon instance from outside using AP api now 
and later from another social network

**Comment by ThibG** [comment]
You seem to be sending a message to mamot.fr, pretending that the author is an account hosted by mamot.fr (`pierregoubeaux@mamot.fr`). This is not a scenario that Mastodon handles.

**Comment by nightpool** [comment]
Mastodon only implements the server-to-server AP protocol, it does not current implement client-to-server communication using AP

**Comment by nightpool** [comment]
We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please use one of the resources below:

 - https://discourse.joinmastodon.org
 - #mastodon on irc.freenode.net

Specifically, i've already replied to your thread on discourse.joinmastodon.org: https://discourse.joinmastodon.org/t/making-our-activity-pub-endpoints/1717

Please reply there if you still have questions!
