### ISSUE TITLE
Scrolling on desktop with touch results in grey screen

### ISSUE THREAD

**Issue by rugk** [tootsuite/mastodon#10056]
### Expected behaviour

Scrolling with touch should work the same as with your mouse.

### Actual behaviour

Grey screen, everything.
Looks like strange `transform` is set:
![image](https://user-images.githubusercontent.com/11966684/52886015-462f0f00-3173-11e9-8955-7b65036bfae8.png)

### Steps to reproduce the problem

1. Scroll in any timeline with touch.

### Specifications

social.wiuwiu.de
Firefox 65
Fedora 29, GNOME

**Comment by ThibG** [comment]
This probably does not have anything to do with the `transform`, but instead a crash somewhere in the React code.
I unfortunately don't have a touchscreen and couldn't reproduce this issue with Firefox's Responsive Design Mode either.
Can you provide the traceback that should appear in the javascript console? Thanks!

**Comment by rugk** [comment]
IIRC nothing special appeared in the console. It is 100% reproducible, though...

**Comment by ThibG** [comment]
There are errors in the console in the screenshot you sent, but they are not shown.

**Comment by rugk** [comment]
Yes, but these are there already after loading the site, the console did not change when the error happened.

**Comment by rugk** [comment]
> This probably does not have anything to do with the `transform`

BTW, it totally has, because when I remove this style that is set there, everything is shown again.

**Comment by rugk** [comment]
Okay, no, actually I found the cause. It's an add-on that sets these values, which is actually intended for zooming with touch. Reported in https://github.com/haxiomic/firefox-multi-touch-zoom/issues/33
