### ISSUE TITLE
Adding a priority option for followed users

### ISSUE THREAD

**Issue by andy5995** [tootsuite/mastodon#10066]
### Pitch

- priority categories, such as High, Normal & Low.
- people I want to follow more closely I can tag as "High"
- I can then click "High Priority" in my "home" feed to see posts from users I follow who I've tagged as high
- "Normal" would show things in my "home" feed as they appear now (toots from everyone I follow).

### Motivation

Sometimes I see many toots from a user, and instead of muting that user, I'd just like to focus on people who I want to follow more closely, but not mute the "lower priority" user.

**Comment by trwnh** [comment]
Can't this be done with Lists?

**Comment by andy5995** [comment]
Oh, I see that option now. Thank you.
