### ISSUE TITLE
No public profile (https://mydomain/@myuser) for first user.

### ISSUE THREAD

**Issue by rototom** [tootsuite/mastodon#10064]
On my instance there is a 500 error on my public profile page.
A second user created has no problems.

`web_1        | [6c44fe96-2274-468e-afab-4bd70305a392] method=GET path=/@myuser format=html controller=AccountsController action=show status=500 error='ActionView::Template::Error: No route matches {:action=>"show", :controller=>"accounts", :tag=>nil, :username=>"myuser"}, missing required keys: [:tag]' duration=1039.95 view=0.00 db=18.95
web_1        | [6c44fe96-2274-468e-afab-4bd70305a392]   
web_1        | [6c44fe96-2274-468e-afab-4bd70305a392] ActionView::Template::Error (No route matches {:action=>"show", :controller=>"accounts", :tag=>nil, :username=>"myuser"}, missing required keys: [:tag]):
web_1        | [6c44fe96-2274-468e-afab-4bd70305a392]     65: 
web_1        | [6c44fe96-2274-468e-afab-4bd70305a392]     66:     - @account.featured_tags.order(statuses_count: :desc).each do |featured_tag|
web_1        | [6c44fe96-2274-468e-afab-4bd70305a392]     67:       .directory__tag{ class: params[:tag] == featured_tag.name ? 'active' : nil }
web_1        | [6c44fe96-2274-468e-afab-4bd70305a392]     68:         = link_to short_account_tag_path(@account, featured_tag.tag) do
web_1        | [6c44fe96-2274-468e-afab-4bd70305a392]     69:           %h4
web_1        | [6c44fe96-2274-468e-afab-4bd70305a392]     70:             = fa_icon 'hashtag'
web_1        | [6c44fe96-2274-468e-afab-4bd70305a392]     71:             = featured_tag.name`

full log:https://code.okaris.de/aguqifodib.php

**Comment by ThibG** [comment]
It seems your account features a `nil` tag. I don't know how that could happen, though.
What does `/settings/featured_tags` show for this account?

**Comment by rototom** [comment]
It works now after upgrade to 2.7.2

Am 19. Februar 2019 13:25:59 MEZ schrieb ThibG <notifications@github.com>:

**Comment by ThibG** [comment]
Uh, now that you mention being on 2.7.2, I realize that this code shouldn't even be in 2.7.2 (nor 2.7.1).

**Comment by rototom** [comment]
I am facing this problem again; now with 2.8.0.

**Comment by ThibG** [comment]
Is it the same error? What does `/settings/featured_tags` show for this account?
