### ISSUE TITLE
Unable to upgrade from 2.7.1 to 2.7.2

### ISSUE THREAD

**Issue by dnegreira** [tootsuite/mastodon#10072]
### Expected behaviour

Upgrade should go smoothly

### Actual behaviour

When compiling the assets 
ActionView::Template::Error: Webpacker can't find error.js in /home/mastodon/live/public/packs/manifest.json.

### Steps to reproduce the problem

Upgrade from 2.7.1 to 2.7.1

### Specifications

f3eb99aec3c2cd596c0b32fde9eff3be4579b22a

Full log:
https://pastebin.com/gKuDTVLL

also:
https://github.com/tootsuite/mastodon/search?q=%22error.js%22&unscoped_q=%22error.js%22

**Comment by ThibG** [comment]
This is weird, it sounds like webpacker didn't even try building the assets.
Does running `RAILS_ENV=production bundle exec rails assets:clobber` then `RAILS_ENV=production bundle exec rails assets:precompile` help?

**Comment by dnegreira** [comment]
@ThibG yep that fixed the issue, thank you.
