### ISSUE TITLE
GIF upload fails on Heroku instances

### ISSUE THREAD

**Issue by ashfurrow** [tootsuite/mastodon#1007]
On my instance (mastodon.technology) served on Heroku, GIF uploading is failing. 

```
Apr 05 15:28:32 mastodon-technology app/web.1:  [c3d523c0-16c8-46ee-8298-d4408452eb3d] method=POST path=/api/v1/media format=html controller=Api::V1::MediaController action=create status=500 error='Av::UnableToDetect: Unable to detect any supported library' duration=34.06 view=0.00 db=4.01 
Apr 05 15:28:32 mastodon-technology heroku/router:  at=info method=POST path="/api/v1/media" host=mastodon.technology request_id=c3d523c0-16c8-46ee-8298-d4408452eb3d fwd="67.245.117.122" dyno=web.1 connect=1ms service=987ms status=500 bytes=1435 protocol=https 
```

Judging from [this SO answer](http://stackoverflow.com/questions/31613800/paperclip-av-transcoder-not-working-on-remote-server) my Heroku install is missing something. Any pointers would be welcome, and once I have it fixed I'll update the docs/code.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
I think you need something like a ffmpeg or libav "buildpack" from heroku

**Comment by ashfurrow** [comment]
Thanks for the quick answer! That makes sense, though so far the additional build pack has put me over Heroku's 300MB slug limit (though just _barely_). I'm looking for a solution and will send a PR when I've figured it out.

**Comment by ashfurrow** [comment]
So I had an idea that instead of adding ffmpeg to the buildpack, we could add a script to download and install ffmpeg once the instance is up. So there'd be a slight delay while the instance is doing that, that GIF upload wouldn't work. But that'd be acceptable from my perspective. Maybe a script like [this buildpack compile script](https://github.com/shunjikonishi/heroku-buildpack-ffmpeg/blob/master/bin/compile)? It's beyond my abilities at the moment but if you or @ineffyble think this approach would work, I can work on it.

**Comment by ashfurrow** [comment]
Since this is fixed as a consequence (and described in #1119) I'm going to close. Thanks again for the feedback.

**Comment by ashfurrow** [comment]
If anyone else is having trouble with slug size, check out this Heroku buildpack: https://github.com/Lostmyname/heroku-buildpack-post-build-clean

**Comment by nicolasmlv** [comment]
now there is an other solution :

`heroku buildpacks:add -i 1 https://github.com/heroku/heroku-buildpack-activestorage-preview`

There is some details by heroku here : https://blog.heroku.com/security-rails-active-storage in particular "the final static build weighed in around 30MB"

**Comment by swabeeh-ser** [comment]
ADHOLOKA-BOT
