### ISSUE TITLE
Language not listed on weblet

### ISSUE THREAD

**Issue by dxwc** [tootsuite/mastodon#10080]
I wanted to help translate it in Bengali, but it is not listed on the weblet. Can it be added ?

**Comment by Aditoo17** [comment]
1. On the Weblate dashboard, click the "Component lists" tab, then click on "Default".
![Image for Step 1](https://user-images.githubusercontent.com/42938951/53303231-54161b80-3868-11e9-89c6-993b0967987a.png)
2. Click on one of the files from the list (React and Backend are the most important)
![Image for Step 2](https://user-images.githubusercontent.com/42938951/53303246-917aa900-3868-11e9-8834-7f2f6198cfb1.png)
3. On the top of the languages page, click on the Tools button, then click on "Start new translation".
![Image for Step 3](https://user-images.githubusercontent.com/42938951/53303288-d8689e80-3868-11e9-9cc8-fdbe53ccb498.png)
4. Choose your language from the list and click on "Start new translations".
![Image for Step 4](https://user-images.githubusercontent.com/42938951/53303304-2382b180-3869-11e9-9d67-a040215653cc.png)
5. Repeat Steps 2-4 for all other files.

------------------------------------------------

You're welcome.
