### ISSUE TITLE
mountNode and props uninitialized due to <div id="mastodon"> not existing yet

### ISSUE THREAD

**Issue by espectalll** [tootsuite/mastodon#10085]
Trying to load Mastodon on various versions of Firefox and Chromium in Void Linux and Ubuntu, with both previously existing and new sessions, ends up in the whole interface crashing and all of the UI DIVs disappearing. I'm not familiar with the Mastodon codebase, but this seems to be due to some session data being loaded from a DIV with id `mastodon` at `main.js:main()` into `mountNode` when the DIV has not been created yet, which also leaves `props` empty and makes the whole thing panic at `display_name.js` since `this.props.account.get()` doesn't exist.

I have several questions.

**Comment by espectalll** [comment]
I'm busy and I wrote this ticket from my phone, I'll update the information properly later, but I hope this is illustrating enough. This is happening to me with the mstdn.io node, and began after the server was updated to 2.7.2.

**Comment by ThibG** [comment]
It would help if you could paste the stack trace from your browser's console here, but to me, it sounds like #10068

**Comment by espectalll** [comment]
Here's the log, copy-pasted from Firefox 65.0.1 on Musl Void:

```
TypeError: "undefined has no properties"

    render display_name.js:26 co12React
    d Redux Ve sounds.js:44 Ve errors.js:15 Ve loading_bar.js:23 a2Redux
    m conversations.js:50 

react-dom.production.min.js:179:186
TypeError: "t is null"

    t index.js:137 wo11React
    d Redux Ve sounds.js:44 Ve errors.js:15 Ve loading_bar.js:23 a2Redux
    m conversations.js:50 

react-dom.production.min.js:179:186

    _o12React
    d Redux Ve sounds.js:44 Ve errors.js:15 Ve loading_bar.js:23 a2Redux
    m conversations.js:50 

TypeError: "undefined has no properties"

    render display_name.js:26 co12React
    d Redux Ve sounds.js:44 Ve errors.js:15 Ve loading_bar.js:23 a2Redux
    m conversations.js:50 

alerts.js:46:4

    u alerts.js:46 Ve errors.js:11 Ve loading_bar.js:23 a2Redux
    m conversations.js:52
```

**Comment by ThibG** [comment]
Yeah, this is most likely the same bug.
Closing as it is fixed in master!
Thanks
