### ISSUE TITLE
Commit d755ce96da00cee1c8e51204cf5ede79764f4fb9 break autorefresh

### ISSUE THREAD

**Issue by Luclu7** [tootsuite/mastodon#1008]
Commit d755ce96da00cee1c8e51204cf5ede79764f4fb9 break column's autorefresh. I have a lot of attempts task in Sidekiq (cf screenshot). Downgrade to 29ffe1cad3f473c7b6c0b651d065f8ed9373d37e fix the problem.

![20170406004426798](https://cloud.githubusercontent.com/assets/11773528/24730418/d8984272-1a63-11e7-8afb-d4c886659716.png)

**Comment by Wonderfall** [comment]
I can confirm. I had to downgrade.

**Comment by valentin2105** [comment]
Is the latest build on https://hub.docker.com/r/gargron/mastodon/tags/ impacted ?

**Comment by Luclu7** [comment]
Yes, it's impacted.

**Comment by dekonnection** [comment]
Can also confirm on my server, all is working well after a downgrade to 29ffe1cad3f473c7b6c0b651d065f8ed9373d37e.

**Comment by alex73630** [comment]
Got the same issue on my instance. Everything working well after downgrade to commit 29ffe1cad3f473c7b6c0b651d065f8ed9373d37e

**Comment by krainboltgreene** [comment]
I know where this happens, I'll get a PR made quickly.

**Comment by Gargron** [comment]
You need to be on at least d13d169922c7efeb6e6c20ef6a271eeda552275f, I am not sure why you had d755ce9  since it wasn't pushed into master by itself...

**Comment by riking** [comment]
Do we need some kind of `tests-passed` branch like @Discourse does?

When a commit lands on master, it's put through an internal CI test and only when it passes is it pushed to tests-passed, which is where everyone pulls updates from.

**Comment by Gargron** [comment]
@riking That is a fantastic idea! Do you know how to setup that?

**Comment by riking** [comment]
I think it's a completion hook on a Travis job triggered on GitHub pushes. Of course, we need to have tests that will catch this kind of thing breaking.

**Comment by Technowix** [comment]
This is fixed ? We can upgrade ? :°

**Comment by mkody** [comment]
I pulled from the master branch ( from b142a2e to 51d7caa ) and restarted Mastodon, I don't have this issue on my instance.

**Comment by valentin2105** [comment]
We need confirmation before upgrade our instance !  :)  thanks you

**Comment by Angristan** [comment]
I upgraded a few hours ago and it has been fixed. :)

**Comment by krainboltgreene** [comment]
The better solution is to just adopt github squash commit merge.

**Comment by Wonderfall** [comment]
@valentin2105 Upgraded and working.

**Comment by Luclu7** [comment]
Upgraded, and it's working now.
