### ISSUE TITLE
Allow users to post small files of any type

### ISSUE THREAD

**Issue by ealgase** [tootsuite/mastodon#10099]
### Pitch

I've often wanted to share small files (for example, a program I'm working on).  It would be useful to be able to upload files up to say, 8MB, without regard for file type.

### Motivation

It would benefit people who want to share small files with others.

**Comment by Gargron** [comment]
- Mastodon is not a file sharing service
- Arbitrary files increase vectors for malware/virus attacks
- Arbitrary files increase risk of copyright violations and consequent takedowns

Sharing a file on Mastodon is as simple as uploading it on a specialized file hosting service (e.g. Dropbox, Google Drive, mega.nz) and posting the link.
