### ISSUE TITLE
Trim whitespace in username

### ISSUE THREAD

**Issue by steinbitglis** [tootsuite/mastodon#10101]
### Pitch

The username field during registration and login should allow a whitespace **postfix**.

This is important because many mobile input methods (on-screen keyboards) insert
a whitespace each time you complete a word, so sometimes a whitespace sneaks in
where it shouldn't (after your username).

The server could easily treat the string as if it didn't have a whitespace postfix.
Any user is almost guaranteed not to have meant anything by it. Whitespace is even
explicitly disallowed in usernames.

The thing is that after your keyboard has
automatically added a whitespace and you left the input field, you can't even
see that whitespace, so you will just get confused why mastodon isn't accepting
your new username.

**Comment by jiradeto** [comment]
would it be ok if I work on this?

**Comment by aurelien-reeves** [comment]
@jiradeto, do you still plan to work on it?

**Comment by Gargron** [comment]
It should be a really small change. Add a `before_validation` call to do `self.username = username.strip` on the `Account` model

**Comment by aurelien-reeves** [comment]
Indeed that is the fix I've implemented.
Actually I do not strip the username, but squish.

I just do not want to take the ownership on that if @jiradeto wanted to fix it.

**Comment by HeitorMC** [comment]
Hey guys, this issue was already solved, right? :thinking:
