### ISSUE TITLE
Implement json / xml search API

### ISSUE THREAD

**Issue by MirceaKitsune** [tootsuite/mastodon#10117]
I'd like to suggest the implementation of an xml / json API for searching posts based on tag, author, and other criteria. Various content serving websites offer this ability, and it's proven very helpful for allowing certain types of services to be possible. For example, I've coded an entire media player which relies exclusively on this type of API to fetch content from a variety of servers.

Here are two art sites which offer great examples of how this works. Note that they may contain NSFW content, be careful when clicking on image links. Their API documentations can be found at:

https://e621.net/help/show/api
https://derpibooru.org/pages/api

Here are a few examples you can try out directly in your browser: In the first I request 10 submissions for the keyword "landscape", in the second I request 5 submissions for the keyword "dragon". As you can see this returns a JSON array with all relevant information from each post.

https://e621.net/post/index.json?tags=landscape&limit=10
https://derpibooru.org/search.json?q=dragon&perpage=5

For Mastodon the URL would be something of the following form:

https://mastodon.social/search.json?tags=mastoart&limit=20

Equally important would be jsonp support, which is an extra feature for json allowing the result to be wrapped into a function and embedded as a script on your website. If you also add the parameter `&callback=my_func` the result will no longer be `{...}` but `my_func({...})`.

I don't currently see any harm to having a json API for Mastodon to allow such searches; The only danger is spam, which can easily be guarded against by imposing a request limit (eg: 10 requests per 1 second per IP address). The returned data is only plain text and thus cheap to network.

**Comment by Gargron** [comment]
https://docs.joinmastodon.org/api/rest/search/

**Comment by MirceaKitsune** [comment]
Thanks, and sorry for not noticing it earlier. It looks exactly like what I was thinking of.
