### ISSUE TITLE
The problem of /interact/ path

### ISSUE THREAD

**Issue by yingziwu** [tootsuite/mastodon#10116]
### Pitch

Add ``Disallow: /interact/`` to [robots.txt](https://github.com/tootsuite/mastodon/blob/master/public/robots.txt).

### Motivation

Today, I use ``site:bgme.me`` to search in google and I found the path of ``/interact/`` .

The problems of ``/interact/`` path  are as follow.  

[My account](https://bgme.me/@bgme) has enabled ``Opt-out of search engine indexing`` .   
Open [one toot](https://bgme.me/@bgme/101652019189115428) of my account, view the source code of page, you can find the meta tag of ``<meta content='noindex' name='robots'>``.  

But open some url of ``/interact/`` path that search from google, eg. https://bgme.me/interact/101594535014331725?type=favourite , https://bgme.me/interact/101590864098765986?type=favourite .  

![image](https://user-images.githubusercontent.com/22741471/53341403-6e262b80-3946-11e9-9566-f7400405b33f.png)  

You can browse my toots through these pages.  And on these pages, ``/interact/`` path, there is no meta tag ``<meta content='noindex' name='robots'>`` and robots.txt also allow search engine crawl these pages. So even if I enabled ``Opt-out of search engine indexing``, you can still search my toots from google.  
What's worse is, you can browse the toots posted by users on other instances through these pages with ``/interact/`` path, eg. https://bgme.me/interact/101580478936541577?type=reply .
That means even if you add ``Disallow: /interact/`` to the robots.txt of your instance, but if the instances connected to you don't add this statement, you still can be searched from google.

**Comment by Gargron** [comment]
I agree, I think the interact pages need `<meta content='noindex' name='robots'>`

**Comment by yingziwu** [comment]
> I agree, I think the interact pages need `<meta content='noindex' name='robots'>`

But how to deal with the toots posted by users on other instances?

**Comment by hook321** [comment]
> But how to deal with the toots posted by users on other instances?

Once `<meta content='noindex' name='robots'>` is added to the interact pages eventually most instances will get the fix when they update
