### ISSUE TITLE
/oauth/token is the only POST endpoint that requires parameters to be sent via the body

### ISSUE THREAD

**Issue by lukepighetti** [tootsuite/mastodon#10122]
Hi all,

I am trying to nail down auth using the `urn:ietf:wg:oauth:2.0:oob` flow and having trouble when I go to request a token using the browser provided auth code.

First I post to `/api/v1/apps`

```
      // body
      {
        "client_name": "mastodon-dart",
        "redirect_uris": "urn:ietf:wg:oauth:2.0:oob",
        "scopes": "write read follow push",
        "website": "https://myactualwebsite.com",
      }

      // headers
      { }
```
Which returns `client_id=foo` and `client_secret=bar` (actual strings withheld, but they are long alphanumeric strings)

Then I launch a browser window pointing at `/oauth/authorize` with query params (converted to URI string of course)

```
      // uri query parameters
      {
        "response_type": "code",
        "client_id": "foo",
        "client_secret": "bar",
        "redirect_uri": "urn:ietf:wg:oauth:2.0:oob",
        "scope": "write read follow push",
      }
```

The user then authorizes in the browser and the auth code is provided to copy and paste, ie `baz` (actual string withheld, but it is a long alphanumeric string)

After which I post to `/oauth/token`

```
     // uri query parameters
     {
        "client_id": "foo",
        "client_secret": "bar",
        "grant_type": "authorization_code",
        "code": "baz",
        "redirect_uri": "urn:ietf:wg:oauth:2.0:oob",
      }
```

At this point I receive a `401` error with body

```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an unsupported parameter value, or is otherwise malformed."}
```

Is the `urn:ietf:wg:oauth:2.0:oob` flow known to be working? Do I need to introduce specific headers during the submission? I cannot find any guides on using this particular auth flow for Mastodon.

Happy to make a docs PR if we can get this resolved.

**Comment by lukepighetti** [comment]
OK I found the issue, apparently every `POST` endpoint on Mastodon actually works if you put the data in URI query params, except for `/oauth/token` which needs everything to come in the body.

Not sure if this is an issue or not so if this needs to be closed please feel free to do so.

**Comment by pdrzq8** [comment]
There hasn't been an update on this in >2 weeks. Is this still an issue or should it be closed?

**Comment by lukepighetti** [comment]
Depends on what members/contributors want. If they want all the endpoints to act the same, this should be open. Otherwise, this should be closed.

**Comment by Gargron** [comment]
The endpoint is implemented by Doorkeeper. I don't know the reasoning behind this detail, but there might be a reason for it.

**Comment by lukepighetti** [comment]
Gotcha. Thanks for the guidance!
