### ISSUE TITLE
Include the last three Status replies with a Status.

### ISSUE THREAD

**Issue by lukepighetti** [tootsuite/mastodon#10135]
One of the biggest differences in UX between Twitter and Mastodon is the ability to see important Status replies in your timeline. It would be nice if Timeline responses included not only each status, but 2-3 important replies to that status.

**Comment by trwnh** [comment]
I would have to disagree. Viewing replies should be a conscious decision, and there's no good mechanism for determining which replies are more "important" than others.

**Comment by lukepighetti** [comment]
Had no idea this would be controversial. How about the two highest rated and the most recent.

**Comment by lukepighetti** [comment]
@trwnh Hey, looks like I was mistaken about how Twitter handles this. I'm going to close this. Cheers!
