### ISSUE TITLE
Removing domain block should be easy

### ISSUE THREAD

**Issue by wxcafe** [tootsuite/mastodon#1014]
Hey. So domain blocks (for admins) are a nice feature. However, it would be nice to have a solution to remove them easily. Right now, there's /no way/ to remove a domain block from the web interface. The only thing I found was using Postgres to remove a row in the `domain_block` table, and I don't actually know if that did it.

A simple X button next to each entry on the 'domain blocks' page would be totally sufficient.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
I will do it.

We simply had only a handful of instance owners just 4 days ago, so admin UI features weren't high priority. Now they definitely are :)

**Comment by wxcafe** [comment]
I totally understand, just wanted to make it known if it wasn't :) at this point i'm mainly making issues for things missing so that they'll be fixed at some point in the future, not necessarily very soon.

Tho do you know if removing the row from the Postgres table works for removing the block? It removes it from the "domain blocks" page, but idk if that's enough.

**Comment by ashfurrow** [comment]
Now that https://github.com/tootsuite/mastodon/pull/1865 has been merged, this should be resolved, so I'm going to close this issue. Please re-open if I missed something.

**Comment by phocks** [comment]
A select-all remove would be nice. I just had to remove 100+ manually ......
