### ISSUE TITLE
FetchRepliesWorker returns an error when receiving a follower-only post

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#10152]
### Actual behaviour

If the server after #10106, #10128 receives a follower-only post from another server in the same state, an error will be happen.

It also occurred in the case of DM.

```
Job: ActivityPub::FetchRepliesWorker
Argument: 101690895447145494, "https://edge.taruntarun.net/users/mayaeh/statuses/101690895434214295/replies"
Error Class: Mastodon::UnexpectedResponseError
Error Message: Mastodon::UnexpectedResponseError
```

In addition, the following error also occurred:

```
Job: ActivityPub::FetchRepliesWorker
Argument: 101690028145935562, "https://edge.taruntarun.net/users/mayaeh/statuses/101690028122371320/replies"
Error Class: ActiveRecord::RecordNotFound
Error Message: Couldn't find Status with 'id'=101690028145935562
```

### Steps to reproduce the problem

Prepare two servers equivalent to master, you can observe on the other side by posting a follower-only post on one side.

### Specifications

equivalent of Mastodon master branch 4ced609497bc736cb2b1aec921ba5ca7a23a7f53

**Comment by ThibG** [comment]
Neither issue is critical, but they both produce noise and useless jobs. I will look into it.
