### ISSUE TITLE
Allow verification for moderators and admins to prevent impersonation

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#1015]
If an instance has active mods, impersonation might become a problem. It would be handy to have something like Twitter's blue checkmarks, but for moderators. Instance-local would suffice, I think.

It would also be neat to be able to quickly find moderators (maybe when typing a keyword like "mod[erator]" or "support" in search? This is related because both features would pull from the same pool of data

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by sphinxc0re** [comment]
I this a wanted feature from the developers perspective? If so, I want to take a shot at implementing it.

**Comment by ashfurrow** [comment]
Sounds like this should be discussed in https://github.com/tootsuite/mastodon/issues/1784 .

**Comment by noiob** [comment]
Um, no, that's a separate issue.

Also, I'm talking about awoo.social moderators, who don't have any admin powers, but are supposed to help mediate issues (and escalate to admins if needed)

**Comment by ashfurrow** [comment]
Understood, thanks for clarifying!

**Comment by ChristopherWMartin** [comment]
Heres a quick mockup of an idea I was thinking about. Its not as in your face as the twitter checkmark but its still easy to quickly check.

![mod2](https://cloud.githubusercontent.com/assets/17181697/26029866/9dadc1cc-3805-11e7-890f-63c6c92d68f9.png)

**Comment by mal0ki** [comment]
@sphinxc0re Yes! This will probably go in the 1.5 Admin Love release. 
If it's something you'd want to work on (the mockup by @ChristopherWMartin is pretty neat), you are msot welcome to.

**Comment by saper** [comment]
I thought mastodon is proud of not having verification marks?

**Comment by noiob** [comment]
This is not the same as Twitter verification

**Comment by saper** [comment]
Yes, not the same, but still creates artificial distinctions between "better" and "normal" users. Some large sites, like Wikipedia, do not have such user badges at all.

**Comment by mal0ki** [comment]
I understand that concern, but it also provides a "oh this person is telling me to adhere to the guidelines because they are an admin". 
Or "Oh this person is an admin/moderator of my server, I should talk with them if I have questions or concerns". 
It is just one way of making it easier to connect with the administrative team of your server.

**Comment by ashfurrow** [comment]
Took me a minute but it looks like this was addressed in https://github.com/tootsuite/mastodon/pull/5735

When closing old issues, even dupes, it's helpful to include a link to the PR that fixed the issue.

**Comment by noiob** [comment]
#5728 fixes this, I guess
#5735 only makes it optional
