### ISSUE TITLE
http://localhost:4000/ {"error":"Error: Missing access token"}

### ISSUE THREAD

**Issue by wmydz1** [tootsuite/mastodon#1016]
{"error":"Error: Missing access token"}
what's wrong? use docker-compose

**Comment by Gargron** [comment]
This is likely not an error if you are accessing the streaming API without an access token. The web UI connects to it with an access token, obviously. You should see if that works.

**Comment by ericblade** [comment]
... and how does one connect to the Web UI?  The documentation seems to be missing some detail about that.  Also, the docker part of the documentation reads like someone intentionally put the steps out of order

**Comment by algernon** [comment]
I'm seeing this too, both on master and development, in the logs of the streaming container (I'm using docker-compose too). Nothing should be accessing that container, but the web UI... but perhaps my Apache proxying setup is wrong (for various reasons, I have to use Apache instead of Nginx, which I'd be more familiar with).

**Comment by algernon** [comment]
I have now verified that these errors come only when I view the Web UI, so something gets lost along the way, it seems. Not quite sure how to debug further.

**Comment by douardda** [comment]
Same here, fresh install (yesterday) in a home-made docker with apache as reverse proxy. I see " Error: Missing access token" in the streaming log (even if the access_token is given). Sniffing the traffic on port 4000, I see (inside the docker):
```
T 172.18.3.3:55673 -> 10.0.0.1:4000 [AP]
GET /?access_token=XXX&stream=user HTTP/1.1.
Host: social.logilab.org.
Pragma: no-cache.
Cache-Control: no-cache.
Origin: https://social.logilab.org.
Sec-WebSocket-Version: 13.
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36.
Accept-Encoding: gzip, deflate, sdch, br.
Accept-Language: fr,en-US;q=0.8,en;q=0.6.
Cookie: remember_user_token=XXX; mastodon_session=XXX
Sec-WebSocket-Key: XXX.
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits.
X-Forwarded-Proto: https.
X-Forwarded-For: 109.190.107.82.
X-Forwarded-Host: social.logilab.org.
X-Forwarded-Server: social.logilab.org.
##
T 172.18.3.3:55673 -> 10.0.0.1:4000 [AP]
Connection: Keep-Alive.
.

#
T 10.0.0.1:4000 -> 172.18.3.3:55673 [AP]
HTTP/1.1 401 Unauthorized.
X-Powered-By: Express.
X-Request-Id: XXX.
Access-Control-Allow-Origin: *.
Access-Control-Allow-Headers: Authorization, Accept, Cache-Control.
Access-Control-Allow-Methods: GET, OPTIONS.
Content-Type: application/json.
Date: Thu, 06 Apr 2017 09:13:23 GMT.
Connection: keep-alive.
Transfer-Encoding: chunked.
.
27.
{"error":"Error: Missing access token"}.
0.
.
```

**Comment by douardda** [comment]
@zoski thanks, a proper config of Apache did the trick (I was proxypass to http://xxx instead of ws://xxx) 👍

**Comment by nolanlawson** [comment]
I'm seeing a lot of these `{ [Error: Missing access token] statusCode: 401 }` errors in my logs as well, but then when I actually test the site, the WebSocket connection works fine. Maybe the access token actually just needs to be refreshed, e.g. because some users have left their browser tab open for a long time, the server was restarted, etc.?

**Comment by ashfurrow** [comment]
@nolanlawson that's what I was seeing – browsers with the tab open trying to reconnect. They died down eventually, are you still seeing that in your logs?

**Comment by nolanlawson** [comment]
I'm still seeing these errors in my logs, and lots of users complaining that they have to refresh because the streaming service doesn't work. I'll double-check my nginx config, but I'm pretty sure it's exactly the same as the one in [the production guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md) :confused:

**Comment by nolanlawson** [comment]
Ah wait I'm also seeing `error: no more connections allowed (max_client_conn)` so it may be that I just need to increase the PgBouncer connection limit.

**Comment by ashfurrow** [comment]
Let us know how it goes 👍

**Comment by nolanlawson** [comment]
OK, I am still seeing tons of these errors with missing access tokens (copied below in detail/summary), but no more pgbouncer errors.

<details>
<summary>Error: Missing access token</summary>
<pre>Error: Missing access token
Apr 26 15:54:48 tootcafe npm[9431]: ERR! <id>     at authenticationMiddleware (/home/mastodon/live/streaming/index.js:145:19)
Apr 26 15:54:48 tootcafe npm[9431]: ERR! <id>     at Layer.handle [as handle_request] (/home/mastodon/live/node_modules/express/lib/router/layer.js:95:5)
Apr 26 15:54:48 tootcafe npm[9431]: ERR! <id>     at trim_prefix (/home/mastodon/live/node_modules/express/lib/router/index.js:312:13)
Apr 26 15:54:48 tootcafe npm[9431]: ERR! <id>     at /home/mastodon/live/node_modules/express/lib/router/index.js:280:7
Apr 26 15:54:48 tootcafe npm[9431]: ERR! <id>     at Function.process_params (/home/mastodon/live/node_modules/express/lib/router/index.js:330:12)
Apr 26 15:54:48 tootcafe npm[9431]: ERR! <id>     at next (/home/mastodon/live/node_modules/express/lib/router/index.js:271:10)
Apr 26 15:54:48 tootcafe npm[9431]: ERR! <id>     at allowCrossDomain (/home/mastodon/live/streaming/index.js:96:5)
Apr 26 15:54:48 tootcafe npm[9431]: ERR! <id>     at Layer.handle [as handle_request] (/home/mastodon/live/node_modules/express/lib/router/layer.js:95:5)
Apr 26 15:54:48 tootcafe npm[9431]: ERR! <id>     at trim_prefix (/home/mastodon/live/node_modules/express/lib/router/index.js:312:13)
Apr 26 15:54:48 tootcafe npm[9431]: ERR! <id>     at /home/mastodon/live/node_modules/express/lib/router/index.js:280:7
Apr 26 15:54:48 tootcafe npm[9431]: ERR! <id>  { [Error: Missing access token] statusCode: 401 }
</pre>
</details>

I am going to go through my nginx config with a fine-toothed comb and make sure I configured everything exactly like the docs say. I also have 4 for `STREAMING_CLUSER_NUM` and PgHero and Sidekiq look pretty quiet so I'm really not sure what it could be. :confused:

**Comment by nolanlawson** [comment]
I am still seeing these, even though my Postgres/PgBouncer params are ridiculously high (1000 connections, 90 pool size, we never even get close to that with our 500 users). I have another insight into this, which is that I noticed:

    Starting stream from timeline:1 for 1
    Apr 27 02:15:02 tootcafe npm[9431]: verb (id) Ending stream for 1

The number here is always `1` whereas for other streams the number is usually 4 digits.

I checked the pgbouncer logs but the only interesting thing I occasionally see is `closing because: server lifetime over (age=3600)`. I'll try increasing that and see what happens.

**Comment by gfriloux** [comment]
Hello, i am also affected by this issue, but i havent been able to get any more informations than you already have.
Spotting same log entries on service mastodon-streaming, not seeing any errors anywhere else.

**Comment by Gargron** [comment]
It's probably fine. There's probably some crawlers trying to access these endpoints. It's not a bad error. It means anonymous (unauthorized) access attempt.

**Comment by gfriloux** [comment]
The thing is that streams doesnt seem to work well.
By restarting everything (nginx & mastodon*) i got the federated timeline to be able to update 'live'.
But the "home" column still isnt updating, i have to manually refresh the page to see new toots on this column.

This error log happenned on April 30, and the issue might have appeared the same day, or the day after (i cant guaranty but it seems pretty close).

**Comment by Gargron** [comment]
Please reopen if this issue still persists in a latest release. However, nothing like this has been reported since.
