### ISSUE TITLE
Undo announce: child object not correctly serialized.

### ISSUE THREAD

**Issue by kaniini** [tootsuite/mastodon#10176]
While reviewing my Pleroma instance's log I observed a strange activity:

```
11:59:01.546 [info] Unhandled activity
11:59:01.547 [info] {
  "type": "Undo",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "signature": {
    "type": "RsaSignature2017",
    "signatureValue": "wwK/gvRWkkkkoniSVF+Y4HaQlUPuJqz1Mj9buXayaAQzC5awqnKUfHJyT4EI7LINYZ2dfFrUSrRCMWtCQSiQcoMkGJfIS94JPTdhQmkPN0gGnD76Lqluf0Q+IlFp8EKWrA478cp4H025Pq804bXPT8+L3mVuj9LkrawnYkZK6kAd1Dis+Uwa2fMS7Y473vRC1J4Xxxz4BRnwjVOQDwXAFFMYjE0aMLbk8M7iHSZHET7wOClWhisBVz0l8Me5nW6bmBTfZ0GmU5RivE9WcQZjok8jU6LvSpkkWBRgie9YTix/ZEsJjBP0EMi+feuWzi/sc2DpD9HeOGKJepvbVMzRfQ==",
    "creator": "https://mastodon.art/users/Curator#main-key",
    "created": "2019-03-05T11:58:51Z"
  },
  "object": {
    "type": "Announce",
    "to": [
      "https://www.w3.org/ns/activitystreams#Public"
    ],
    "published": "2017-07-09T15:37:13Z",
    "object": {
      "url": "https://octodon.social/users/jdb/updates/152261",
      "type": "Note",
      "to": [
        "https://www.w3.org/ns/activitystreams#Public"
      ],
      "tag": [
        {
          "type": "Hashtag",
          "name": "#sketch",
          "href": "https://mastodon.art/tags/sketch"
        },
        {
          "type": "Hashtag",
          "name": "#charcoal",
          "href": "https://mastodon.art/tags/charcoal"
        },
        {
          "type": "Hashtag",
          "name": "#2am",
          "href": "https://mastodon.art/tags/2am"
        }
      ],
      "summary": null,
      "sensitive": false,
      "published": "2017-06-29T05:58:31Z",
      "inReplyToAtomUri": null,
      "inReplyTo": null,
      "id": "tag:octodon.social,2017-06-29:objectId=3931131:objectType=Status",
      "conversation": "tag:mastodon.art,2017-06-29:objectId=372577:objectType=Conversation",
      "contentMap": {
        "en": "<p>I'm not sleeping. <a href=\"https://octodon.social/tags/2am\" class=\"mention hashtag\" rel=\"nofollow noopener\" target=\"_blank\">#<span>2am</span></a> <a href=\"https://octodon.social/tags/charcoal\" class=\"mention hashtag\" rel=\"nofollow noopener\" target=\"_blank\">#<span>charcoal</span></a> <a href=\"https://octodon.social/tags/sketch\" class=\"mention hashtag\" rel=\"nofollow noopener\" target=\"_blank\">#<span>sketch</span></a> (who has the patience to blend in the middle of the night?)</p>"
      },
      "content": "<p>I'm not sleeping. <a href=\"https://octodon.social/tags/2am\" class=\"mention hashtag\" rel=\"nofollow noopener\" target=\"_blank\">#<span>2am</span></a> <a href=\"https://octodon.social/tags/charcoal\" class=\"mention hashtag\" rel=\"nofollow noopener\" target=\"_blank\">#<span>charcoal</span></a> <a href=\"https://octodon.social/tags/sketch\" class=\"mention hashtag\" rel=\"nofollow noopener\" target=\"_blank\">#<span>sketch</span></a> (who has the patience to blend in the middle of the night?)</p>",
      "cc": [
        "https://mastodon.art/users/jdb/followers"
      ],
      "attributedTo": "https://octodon.social/users/jdb",
      "attachment": [
        {
          "url": "https://assets.octodon.social/media_attachments/files/000/330/576/original/5dbff36e8cd3fe14.jpg",
          "type": "Document",
          "name": null,
          "mediaType": null
        }
      ],
      "atomUri": null
    },
    "id": "https://mastodon.art/users/Curator/statuses/939392/activity",
    "cc": [
      "https://octodon.social/users/jdb",
      "https://mastodon.art/users/Curator/followers"
    ],
    "atomUri": "tag:mastodon.art,2017-07-09:objectId=939392:objectType=Status",
    "actor": "https://mastodon.art/users/Curator"
  },
  "id": "https://mastodon.art/users/Curator#announces/939392/undo",
  "actor": "https://mastodon.art/users/Curator",
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "value": "schema:value",
      "toot": "http://joinmastodon.org/ns#",
      "sensitive": "as:sensitive",
      "schema": "http://schema.org#",
      "ostatus": "http://ostatus.org#",
      "movedTo": {
        "@type": "@id",
        "@id": "as:movedTo"
      },
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
      "inReplyToAtomUri": "ostatus:inReplyToAtomUri",
      "focalPoint": {
        "@id": "toot:focalPoint",
        "@container": "@list"
      },
      "featured": {
        "@type": "@id",
        "@id": "toot:featured"
      },
      "conversation": "ostatus:conversation",      "atomUri": "ostatus:atomUri",
      "alsoKnownAs": {
        "@type": "@id",
        "@id": "as:alsoKnownAs"
      },
      "PropertyValue": "schema:PropertyValue",
      "Hashtag": "as:Hashtag",
      "Emoji": "toot:Emoji"
    }
  ]
}
```

The reason why this activity is rejected is because the entire JSON-LD graph cannot be composed.

This is because the object `tag:octodon.social,2017-06-29:objectId=3931131:objectType=Status` is not known to us.

### Expected behaviour

The object ID should always be serialized consistently, for example, in this case the proper AP id of the object is: `https://octodon.social/users/jdb/updates/152261`.

### Actual behaviour

The object being unannounced is referred to using an OStatus-style ID which makes the document impossible to fully recompose.

### Steps to reproduce the problem

Unannounce objects using Mastodon.

### Specifications

Mastodon 2.7.3 on mastodon.art.

**Comment by ThibG** [comment]
This is most likely due to #9998, which has been fixed since. I did not realize it went into a release, we should definitely do a new release fixing that.

**Comment by puckipedia** [comment]
The ID used for old (pre-AP) statuses \*is\* indeed the `tag:` one. Changing the ID to the value referred to in the `<link rel="alternate" type="text/html" [...]>` would immediately break compatibility with every other picee of software (**including** Pleroma) as well as still be incorrect, as the actual ID of the status is at https://octodon.social/users/jdb/statuses/3931131

**Comment by ThibG** [comment]
Right. The bug I was talking about was the entire status being serialized (which is useless as it cannot be trusted, since it's from a remote server and no signature is stored). The id itself would still be the old pre-AP one.

**Comment by Gargron** [comment]
> I did not realize it went into a release, we should definitely do a new release fixing that.

@ThibG I do not remember putting it into a release, and cannot find it in the changelog. Is it possible the sender is just on some version of master?

**Comment by puckipedia** [comment]
@ThibG it'd be very inefficient to query the remote server for all pre-AP IDs to see what the new ID is... and there are also servers that don't have AP that still use tag IDs

**Comment by ThibG** [comment]
@puckipedia yeah, what I meant is that, when accessed over ActivityPub, older *local* toots are served with a new `id`. Which is weird, but like, the opposite of what this “bug” is about. I'm not too sure what to do about it, especially since it *has* been inconsistent for a long time already?

The bug I was initially referencing was an actually minor one that isn't directly related with the issue.

**Comment by puckipedia** [comment]
The Atom representation still uses the same ID, and has a link to the AS2 repr (which also links back to Atom) and i suspect this is the best we can do without breaking both newer and older software

**Comment by kaniini** [comment]
It doesn't really matter to me how it is fixed, either way Pleroma would continue to reject such Undos.

**Comment by puckipedia** [comment]
so your issue is with the ID inside the announce not being an HTTP url? are you *sure* it rejects those Undos? since i just unboosted a test post within pleroma and it ended up making an Undo of an Announce with a tag: url inside it. And also, you're saying these shouldn't exist?
```
pleroma_dev=# select count(*) from objects where data->>'id' like 'tag:%' and data->>'type' = 'Note';
 count
-------
     2
(1 row)
```
i'm pretty certain the reason the undo is not handled is because your server does not know the object that was unboosted, and was unable to retrieve it since it has a tag uri. I do not believe anything can (or should) be done to fix older posts being referred to by tag uri.

**Comment by Gargron** [comment]
v2.7.4 was released so should resolve the embedded-object issue. I agree with @puckipedia that there is nothing to do about old tag URIs, they are just a grandfathered remnant of an older system.
