### ISSUE TITLE
Trying to deploy. Works on http://[my-ip]:3000, but not with custom domain

### ISSUE THREAD

**Issue by raymestalez** [tootsuite/mastodon#1019]
Hello! I'm trying to deploy my own instance. I'm using DigitalOcean's Docker droplet.

After building, running migrations, etc, the instance seems to work properly on `http://[my-ip]:3000`.

Now, to use a custom domain, I want to use nginx to proxy the requests to the port 3000. I'm using these settings:

```
server {
    listen 80;
    server_name  hackertribe.io;

    location / {
            proxy_pass http://159.203.84.121:3000;
    }
}
```

But it returns the Bad Gateway 502 error.

Am I doing something wrong?

**Comment by raymestalez** [comment]
I have ended up modifying docker compose, and changing the port binding to:

```
    ports:
      - "80:3000"
```

And that works(awesome!). 

But this doesn't seem right, I'd still love to figure out how to do it right with nginx(so that I could run several instances on one droplet, and so that pulling updates wouldn't reset the settings)

**Comment by JantsoP** [comment]
You should leave the proxy_pass to just localhost, so it should just be proxy_pass http://localhost:3000; Now it's just stuck on limbo. Just follow the nginx guide from here: [https://github.com/tootsuite/mastodon/blob/master/docs/Running-Mastodon/Production-guide.md](https://github.com/tootsuite/mastodon/blob/master/docs/Running-Mastodon/Production-guide.md)

With that i got mine to work just fine. I only changed the 
  ssl_certificate     /etc/letsencrypt/live/example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
and root folder path.

**Comment by raymestalez** [comment]
Awesome, thank you!
