### ISSUE TITLE
Can not set the voting period to 5 minutes

### ISSUE THREAD

**Issue by abcang** [tootsuite/mastodon#10190]
Although the UI has a setting of 5 minutes, the validation error occurs because the lower limit of validation is 5 minutes (the lower limit is not included).

### Expected behaviour

We can set the voting period to 5 minutes.

### Actual behaviour
Validation error occurred and can not be posted. Or remove the 5 minute choice from the UI.

### Steps to reproduce the problem
Set the period to 5 minutes in the voting UI and post the status

**Comment by ThibG** [comment]
Fixed by #10186

**Comment by ThibG** [comment]
Oops, even after #10186 it is not fixed. Sorry.

**Comment by abcang** [comment]
Thank you. It is additional information.

When expires_in is set, the server converts it to expires_at. And validation checks whether the value obtained by subtracting the current time from expires_at is below the lower limit. However, since the current time advances while processing on the server, the value obtained by subtracting the current time from expires_at when expires_in is set to 5 minutes is less than the lower limit of 5 minutes.

Since `expires_at` is calculated before `current_time`, the following will occur. In other words, if it is set to 5 minutes it will result in a validation error.
```ruby
MIN_EXPIRATION   = 5.minutes.freeze
expires_at = 5.minutes.from_now
current_time = Time.now.utc
expires_at - current_time # => 299.999953
expires_at - current_time < MIN_EXPIRATION #=> true
```
