### ISSUE TITLE
Error compiling with Docker ever since Polls

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#10215]
Not sure what the issue is, but I get this error message every time I try to compile using Docker running Master

Get:76 http://archive.ubuntu.com/ubuntu bionic/universe amd64 protobuf-compiler amd64 3.0.0-9.1ubuntu1 [24.5 kB]
Fetched 37.6 MB in 6s (6662 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.2_amd64.deb  404  Not Found [IP: 91.189.88.149 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openssh/openssh-client_7.6p1-4ubuntu0.2_amd64.deb  404  Not Found [IP: 91.189.88.149 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'web' failed to build: The command 'bash -c apt -y install git libicu-dev libidn11-dev
        libpq-dev libprotobuf-dev protobuf-compiler &&     cd /opt/mastodon &&     bundle install -j$(nproc) --deployment --without development test && yarn install --pure-lockfile' returned a non-zero code: 100

**Comment by BenLubar** [comment]
Try building with `--no-cache`. #10212 will fix this for good.

**Comment by malicioustoker** [comment]
That did it, thanks!
