### ISSUE TITLE
Link headers returned by pinned statuses timeline do not contain pinned parameter.

### ISSUE THREAD

**Issue by DagAgren** [tootsuite/mastodon#10227]
When getting the pinned statuses of an account, for instance:

    curl -v https://icosahedron.website/api/v1/accounts/44/statuses?pinned=true

The Link header in the response specifies URLs that do not have the `pinned=true` parameter:

    Link: <https://icosahedron.website/api/v1/accounts/44/statuses?min_id=101723051735664635>; rel="prev"

Probably extremely low priority, but it is technically wrong.

**Comment by Gargron** [comment]
Hmm, I don't think pinned statuses are even supposed to paginate (limit is 5), the presence of the header in the first place is the mistake...

**Comment by DagAgren** [comment]
It shares an endpoint that has pagination, which may be why it's awkward.
