### ISSUE TITLE
Polls: "notify me of results" option

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#10220]
### Pitch

I think it'd be cool to have an option in the toot menus of polls that says "notify me of results" or something like that.

Then, when the poll ends, you'd get a notification showing you the results of the poll even if you are not the original poster.

### Motivation

I really like polls on Twitter, but I'm often sad when I vote because I know (especially for longer-lasting polls) that I probably won't find out the results because I'll forget the poll exists!

**Comment by trwnh** [comment]
I think this is similar to the "subscribe to a status" issue as well.

**Comment by ThibG** [comment]
Voters and poll owner are now notified when a poll closes, as of #10209

**Comment by Cassolotl** [comment]
Thank you, @ThibG ! :)
