### ISSUE TITLE
Timeline streaming stopped after #10210

### ISSUE THREAD

**Issue by kedamaDQ** [tootsuite/mastodon#10223]
### Actual behaviour
Streaming stopped because connection from node to postgresql become SSL even if DB_SSLMODE is not set. (regression from #10210)

### Steps to reproduce the problem

Start streaming service with postgresql which works non ssl connections. I got error log, and streaming stopped.

```
ERR! Error: The server does not support SSL connections
```

There is not DB_SSLMODE in my .env.production. As far as I investigate, "ssl" option of pg.Pool() of node not has "sslmode" option. Probabry, just only add "ssl" key, and even if it is empty, connection to postgresql become SSL.

### Specifications
- mastodon: master (3f4a6d4)
- My server is all-in-one that is contains web, streaming, sidekiq, redis and postgresql in single.

**Comment by kedamaDQ** [comment]
The nodejs which I use is v8.

**Comment by Gargron** [comment]
@sascha-sl

**Comment by usbsnowcrash** [comment]
Looks like y'all are all over it but it broke for me as well.
![Screenshot 2019-03-09 10 12 44](https://user-images.githubusercontent.com/882850/54073392-83f3f480-4254-11e9-808c-814afe3acb45.png)

**Comment by kedamaDQ** [comment]
yes, this issue occurs timing when probably log "verb..." if server as usual, I think.

**Comment by sascha-sl** [comment]
Ah yeah, I knew we'd be better off checking for node weirdness. The sslmode property is not actually documented but used in quite of lot of searchable code on GitHub.
