### ISSUE TITLE
Impossible to report a user after muting or blocking them

### ISSUE THREAD

**Issue by KellerFuchs** [tootsuite/mastodon#10226]
### Expected behaviour

- Block or mute user.
- Be able to report the behavior that prompted the block.

### Actual behaviour

- Block or mute user.
- UI instantly closes their profile (if it was opened in the third column), hides all their toots, and removes all mentions of their username.
- Be unable to report bad behaviour.

### Steps to reproduce the problem

See above.

### Specifications

Encountered on vulpine.club.

**Comment by ThibG** [comment]
I experience something slightly different from described: blocking an user does not close their profile.
It indeed removes statuses from every timeline, including account timelines, but subsequently loading the timeline again (which does happen when firing up the report modal) allows you to report statuses.

So I guess the only thing we should do differently is to not remove statuses from that account's timeline? We could also offer to open the report dialog after blocking the account.
