### ISSUE TITLE
Mega-issue: Special-cased Twitter interoperation

### ISSUE THREAD

**Issue by riking** [tootsuite/mastodon#1024]
(Tracking mega-issue)

Because of how big and incumbent the site is, I think it's appropriate to special-case mentioning Twitter users.

Implementation levels:

 1. Special-case twitter.com as a matching federation domain target, and replace mentions with simple links to `https://twitter.com/username`
 2. If the server admin has set up Twitter API keys, pull Twitter avatars and display names for autocomplete
 3. Single-tweet display view with favorite disabled
 4. Load a twitter user's profile when clicking on a mention of them
 5. And their tweets
 6. Following a twitter account [puts their tweets into your home timeline](https://github.com/riking/marvin/blob/master/modules/rss/twitter.go#L202)
 7. ????
 8. SEAMLESS TRANSITON
 8. World domination

* * * *

- [x] I searched or browsed the repo’s other issues, and amazingly, this is not a duplicate.

**Comment by Gargron** [comment]
- Instance admins would need to provision Twitter API keys for themselves
- Twitter could block such use at any time
- I am not too happy about sticking proprietary APIs into a FOSS code base, like it feels a bit dirty

**Comment by ePirat** [comment]
Parts of this seems to violate Twitter ToS / Developer Agreement, especially the "puts their tweets into your home timeline" is not allowed, unless you only store the Tweet ID and no content.

**Comment by ashfurrow** [comment]
It sounds like this might be better dealt with on a per-user basis, for users who _do_ want to bridge. In fact, I think a few projects already exist. What do you think @riking ?

**Comment by Gargron** [comment]
>Parts of this seems to violate Twitter ToS / Developer Agreement, especially the "puts their tweets into your home timeline" is not allowed, unless you only store the Tweet ID and no content.

Yes, sounds like that would be one more problem.
