### ISSUE TITLE
Users from a suspended instances can still @ you

### ISSUE THREAD

**Issue by SelfsameSynonym** [tootsuite/mastodon#10251]
My admin suspended mastodon.social a while ago. A user on mastodon.social was still able to @ reply me and I got a notification.

https://mastodon.starrevolution.org/@SelfsameSynonym/101741205669798766

**Comment by Gargron** [comment]
Has the suspend option has been used or is it none+reject_media? What version is Mastodon is the instance running? Is it upstream or some fork?

**Comment by ThibG** [comment]
Upon blocking a domain, every known account of that domain should be marked as suspended, and every subsequently newly-discovered account of that domain should automatically be marked as suspended.
A remote suspended user's AP queries should never be processed, and a suspended user, remote of otherwise, should never appear in your mentions.

I guess for some reason that account has not been marked as suspended. I am not sure how this could happen.

**Comment by ThibG** [comment]
The frontpage of that instance suggests they are running unmodified 2.4.5, which is quite old, but I can't remember any fix regarding domain blocks.

One possible cause would be that `UnsubscribeService` and `SuspendAccountService` are called sequentially for every account to block, so if any of those raises an error for any reason, subsequent users won't be blocked. Haven't seen any error with those, though.

**Comment by SelfsameSynonym** [comment]
I have an alt on mastodon.social and I can’t @ myself on mastodon.starrevolution.org 

The behavior following the instance suspension has been that media disappears, then accounts slowly stop showing up in timelines and search.

**Comment by SelfsameSynonym** [comment]
The account that was able to reply to mine clearly fell through a crack that shouldn’t be there, especially since it’s not some brand new account.

**Comment by ThibG** [comment]
Was `mastodon.social` blocked recently when you got that reply?

**Comment by SelfsameSynonym** [comment]
I don’t know the exact date since I’m not the admin, but the suspend was kicked off at least a month ago.

**Comment by ThibG** [comment]
Ok so the task should definitely have finished running and that account should have been marked as suspended by the time you got the reply… I'll have another look at the code, but I couldn't find anything fishy so far :/

**Comment by SelfsameSynonym** [comment]
So a user on mastodon.social just favorited a toot of mine and I got a notification. Instance has upgraded to the latest version too. https://mastodon.starrevolution.org/@SelfsameSynonym/101830753494053140

**Comment by SelfsameSynonym** [comment]
![32FADCD6-8254-42E9-9EBE-FD649F487F7C](https://user-images.githubusercontent.com/34668228/55199468-59bc9500-5177-11e9-8947-7187162d1f1e.png)

**Comment by Laurelai** [comment]
Ill try re-suspending the instance to see if running the job again will matter.

**Comment by ThibG** [comment]
Thanks, please let us know if there is any error occurring for `DomainBlockWorker` taks in the sidekiq logs.

**Comment by Laurelai** [comment]
Seems to work now *shrug*

**Comment by ThibG** [comment]
In the next version, domain blocks are going to be applied early (which means we won't be able to unblock just one user from a domain anymore, but that was finicky anyway), so whatever happened here will not be possible anymore. Closing.
