### ISSUE TITLE
Please generate IDs for flag activities

### ISSUE THREAD

**Issue by kaniini** [tootsuite/mastodon#10271]
### Pitch

Mastodon does not presently generate IDs for flag activities.  It would be nice if it did as it would allow Pleroma to better track reports from Mastodon.

### Motivation

Any ActivityPub implementation which processes messages as a proper RDF-style graph will benefit from Flag activities having IDs.

**Comment by kaniini** [comment]
as an aside, we intend to use these stable IDs in Pleroma for notifying the complainant about the disposition of their report in the future.  so that may be another nice reason to use stable IDs.

**Comment by ThibG** [comment]
Serializing an `id` for outcoming reports is something we could easily do, but I don't think we ever plan on updating them or anything, so I'm not sure how useful that would be.

Storing the identifier of incoming reports is trickier, as we don't actually have one report object per AP payload, but potentially more, if the AP payload reports multiple accounts. I guess we could do without a requirement to have the URI be unique, but it sounds very weird.
