### ISSUE TITLE
Case sensitive instance listings

### ISSUE THREAD

**Issue by nullatmidnight** [tootsuite/mastodon#1027]
I noticed there are duplicates now showing on the mastodon instance listing where the first letter is upper case or not, creating a list showing the same instances.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
Which list do you mean, this one? https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/List-of-Mastodon-instances.md

**Comment by Gargron** [comment]
If this is about instances.mastodon.xyz, it doesn't belong here.

**Comment by nullatmidnight** [comment]
This is about the instance website, which has been fixed.
