### ISSUE TITLE
Closed registrations message should be restored

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#10285]
### Pitch

Before the landing page redesign, it used to show some customizable text along with a “Sign up on another server” button. Since the landing page redesign, a disabled sign up form is displayed instead.

Previous behavior should be restored.

### Motivation

The sign-up form in itself doesn't provide any value when it is disabled.

Furthermore, the closed registration text was used for various purposes, from explaining why registrations were disabled, to providing alternative instance recommendations or links to a custom form for manual approval.

**Comment by MichaelHierweck** [comment]
We run an instance targetted at a certain audience. Interested party may aks for an invitation.
The "closed registration message" which is rather an "ask for invitation message" can hardly be read.
The button "<instance>" is not accepting new members is catastrophically misleading.

See: [geno.social](https://geno.social/about)

**Comment by Gargron** [comment]
![2395B399-BA98-450B-8BAB-55171D0056D4](https://user-images.githubusercontent.com/184731/58437400-17a5c600-80ca-11e9-9212-6d3c92fd53b9.jpeg)

This doesn't look bad to me...
