### ISSUE TITLE
Feature request: Visual indication of length of toot in character counter.

### ISSUE THREAD

**Issue by KhyKd** [tootsuite/mastodon#1028]
An idea would be to have the remaining letters counter change from green to yellow to red as you type more. Toots under 140 characters, green, 140-250 yellow, 250+ red. I appreciate the flexibility of having 500 characters when needed, but believe that this is a good way to encourage users to be succinct in their messaging.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
Hmm, interesting idea. Does Mastodon _want_ to encourage people to be succinct? I mean, we have a 500-character limit so people can be more verbose. I'm not sure. Anyone else have input?

**Comment by Gargron** [comment]
It goes red when you overstep the limit now. I do not think that adding more colors or being judgemental about the length of what people want to write is something I want to work on.
