### ISSUE TITLE
Content deletion when an instance shuts down

### ISSUE THREAD

**Issue by simon-wessel** [tootsuite/mastodon#10305]
I was wondering about what happens in the case of an expected or unexpected shutdown of an instance.

- Will the content (including images) stay available on other instances?
- Does a user have the chance to delete his distributed content if the instance is already offline?

Edit: Accidentally hit send too early

**Comment by Gargron** [comment]
> Will the content (including images) stay available on other instances?

Unless the instances sends out deletes beforehand, yes.

> Does a user have the chance to delete his distributed content if the instance is already offline?

Unfortunately, no.

There are a couple ways we are trying to deal with this in the long term. We have command-line tasks for other server admins to run which check all stored accounts for whether they still exist, and deleting them if not (`tootctl accounts cull`). It's possible that in the future such checks might become more automated and not require admin intervention.

**Comment by simon-wessel** [comment]
Thanks for the quick and informative response :+1: 

Maybe it should be considered to implement a `tootctl`-command to delete all instance accounts. Although I could see a high risk of accidental or malicious use.

**Comment by simon-wessel** [comment]
Something else I just thought of would be to allow administrators to freeze the instance. In this state users would not be able to create new content, but could delete or migrate their accounts.

**Comment by Gargron** [comment]
> Maybe it should be considered to implement a `tootctl`-command to delete all instance accounts.

Do you mean as a self-destruct or for other admins? For other admins there is `tootctl domains purge` which deletes everything stored from a given domain.

**Comment by simon-wessel** [comment]
I meant it as a self-destruct command. The `domains purge` command is also interesting, but would require manual actions from the administrators of all instances that have shared content.
As far as I understand it `purge` would have the same result as `accounts cull` (if the instance is already offline).

**Comment by Gargron** [comment]
> As far as I understand it purge would have the same result as accounts cull (if the instance is already offline).

Purge doesn't check every account for existence, just deletes, so it's faster. But even more importantly, cull does not do *anything* unless the server returns 404 or 410 for the account. If the server is broken (500) or if the domain name doesn't resolve, or if the SSL is expired, it does not do anything, because it's easy to make a mistake and remove stuff that's only temporarily offline.

**Comment by simon-wessel** [comment]
That is reasonable.

It's more of a difficult workaround for the original issue though. Because then deleting the content would depend on the administrators of every instance that federated with the instance that shut down.

**Comment by simon-wessel** [comment]
Thank you for implementing a solution.
I like the double confirmation which can't be confirmed by typing "y" or "yes" to avoid accidental usage :+1:
