### ISSUE TITLE
Searching in the emoji picker crashes the entire app

### ISSUE THREAD

**Issue by Deuchnord** [tootsuite/mastodon#10315]
### Expected behaviour

Filter the emojis while typing in the search input of the emoji picker.

### Actual behaviour

The entire page crashes and shows a mastodon playing trumpet:

![A mastodon playing trumpet on a blank page](https://user-images.githubusercontent.com/7600265/54558003-d784e180-49bc-11e9-940d-4cdeee0884f8.png)

Plus, the following logs appear in the JavaScript console:

```
TypeError: "n is undefined"
    e               nimble-emoji.js:126
    render          category.js:222
    render          category.js:219
    handleSearch    nimble-picker.js:373
    search          search.js:51
    handleChange    search.js:68
    handleChange    index.js:198 

TypeError: "t is null"
    t               index.js:137
    handleSearch    nimble-picker.js:373
    search          search.js:51
    handleChange    search.js:68
    handleChange    index.js:198
```

### Steps to reproduce the problem

1. In the new toot editor, open the emoji picker.
2. Type something in the emoji picker search box.
3. Boom.

### Specifications

- **Instance:** https://hostux.social
- **Mastodon version:** 2.7.4
- **OS:** Arch Linux
- **Browser:** Firefox 65

**Comment by Gargron** [comment]
Can reproduce this when custom emojis exist

cc @nolanlawson

**Comment by hinaloe** [comment]
It looks a little bug of emoji-mart

**Comment by nolanlawson** [comment]
I don't understand how this bug exists in Mastodon but not Pinafore, but yeah, that PR seems to fix it. I'll ask for a new emoji-mart release.

**Comment by nolanlawson** [comment]
Ah, I see, it's because Mastodon has `tooltip` enabled.

**Comment by nolanlawson** [comment]
Looks like it's because Pinafore doesn't not use `tooltip: true`.
