### ISSUE TITLE
Add markdown support to mastordon

### ISSUE THREAD

**Issue by Ravenbird** [tootsuite/mastodon#1031]
Please add markdown support to mastordon, like on github or diaspora. This has no high priority but would by a very nice feature for formating the postings.

**Comment by rhaamo** [comment]
There is already #853 about text formatting too

**Comment by nhoizey** [comment]
Duplicate of #761 IMHO

**Comment by zacanger** [comment]
If someone can confirm this is a desired feature to get in and point me to where the relevant code lives (I do React for a living but have never even seen a Rails project before) I'd be down to look this.

**Comment by krainboltgreene** [comment]
Moving to #853

**Comment by krainboltgreene** [comment]
@zacanger I agree.
