### ISSUE TITLE
Fresh Install by Documentation / CSP Error

### ISSUE THREAD

**Issue by HerrHase** [tootsuite/mastodon#10317]
Hello,

i have installed Mastodon 2.7.4, all seems to running. But after login i get a blank Site. In the Develop Tools i see this,

```bash
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
```

I have tried to set Content-Security-Policy for script-src to "unsafe-eval" and "unsafe-inline" and some other combinations in the nginx configuration, i don't get it, nothing works.

**Comment by ThibG** [comment]
Mastodon sets the CSP headers itself, you should not have to set them.
What documentation are you following?

**Comment by HerrHase** [comment]
Yes, i should not. 

I have used that,
https://docs.joinmastodon.org/administration/installation/

Instead of iptables i used ufw, i also rebuild the assets.

**Comment by ChrisWiegman** [comment]
I'm having the same issue, new install using the Digital Ocean instance as well as a 2nd install using default CSP. In both cases, on Firefox, I'm seeing the following in console:

```Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).```

Mastodon version: 2.8.0
Browser: Firefox 66.0.3 on Linux

**Comment by ThibG** [comment]
Doesn't the console show which resource it failed to load? Do you have a reverse-proxy configured? If so, how?
Is your setup public so that we can have a look?

**Comment by ChrisWiegman** [comment]
No reverse proxy, and that is the entirety of the message. While both instances are private I would be willing to setup an account to help troubleshoot if that would work for you.

Here's the whole error:
![Screenshot from 2019-04-22 10-40-06](https://user-images.githubusercontent.com/394675/56505967-1d1c5900-64eb-11e9-9938-34a25ae2076b.png)

**Comment by ThibG** [comment]
Oh, yeah, I hadn't noticed it was `script-src`. We shouldn't be using that at all.
I suspect it is one of your browser extensions injecting some JS into the page? Do you have something like that?

**Comment by ChrisWiegman** [comment]
I've tried it with all extensions disabled, so I don't think it's that. I can keep digging.

**Comment by ThibG** [comment]
Do you also experience that error when on public pages? e.g. https://mastodon.chriswiegman.com/@chris ?

**Comment by ChrisWiegman** [comment]
Good question, I do

**Comment by ThibG** [comment]
I do not, so it really seems like an issue on your browser's side.

**Comment by ChrisWiegman** [comment]
OK, fair enough. Thanks! At least I know where to look!

**Comment by mason1900** [comment]
> 
> 
> Hello,
> 
> i have installed Mastodon 2.7.4, all seems to running. But after login i get a blank Site. In the Develop Tools i see this,
> 
> ```shell
> Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
> ```
> 
> I have tried to set Content-Security-Policy for script-src to "unsafe-eval" and "unsafe-inline" and some other combinations in the nginx configuration, i don't get it, nothing works.

I encountered the same issue here. By disabling browser extensions one-by-one, I found out that it is  **Tampermonkey** that triggers the CSP block. You can just ignore the warning or disable Tampermonkey to resolve the issue.

**Comment by saper** [comment]
It can be witnessed as we speak at https://introverts.social/about with FIrefox 79.0

Also Chromium 81.0.4044.113  reports 

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://introverts.social".

    at Object../tmp/packs/locale_pl.js (locale_pl-967b165e64e0351ba3a2.chunk.js:33)
    at __webpack_require__ (common-fa75da4d469ee58c3f16.js:85)
    at checkDeferredModules (common-fa75da4d469ee58c3f16.js:46)
    at Array.webpackJsonpCallback [as push] (common-fa75da4d469ee58c3f16.js:33)
    at locale_pl-967b165e64e0351ba3a2.chunk.js:1
public-326635dbcd9beb283956.chunk.js:23 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://introverts.social".

    at Object../app/javascript/packs/public.js (public-326635dbcd9beb283956.chunk.js:23)
    at __webpack_require__ (common-fa75da4d469ee58c3f16.js:85)
    at checkDeferredModules (common-fa75da4d469ee58c3f16.js:46)
    at Array.webpackJsonpCallback [as push] (common-fa75da4d469ee58c3f16.js:33)
    at public-326635dbcd9beb283956.chunk.js:1

**Comment by ThibG** [comment]
@saper the JS packs don't look anything like they should look in production mode. Maybe `bundle exec rails assets:precompile` ran with `RAILS_ENV=development` or the webpack configuration has been customized?

**Comment by ThibG** [comment]
This last occurrence of the issue has been confirmed as a case of building development assets and running them in production. Closing.

**Comment by joshuakfarrar** [comment]
Also ran into this issue from having an old version of node installed that caused asset precompilation to fail.

**Comment by simplesunny** [comment]
Getting console error Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).

using Mastoson v4.1.1

**Comment by mikeelston** [comment]
@ClearlyClaire I have the same issue on my instance.  happens in Firefox, Safari (no extensions), Chrome.
primary domain is `kzoo.to`.  all media files hosted at `files.kzoo.to`
