### ISSUE TITLE
Keybase integration validation error, username regular expression and no contacts

### ISSUE THREAD

**Issue by noellabo** [tootsuite/mastodon#10323]
Errors may occur when performing a Config Validation following the instructions in Keybase's [Proof Integration Guide](https://keybase.io/docs/proof_integration_guide).

```bash
http GET https://mastodon.social/.well-known/keybase-proof-config > config.json
http POST "https://keybase.io/_/api/1.0/validate_proof_config.json" config="$(jq -c . < config.json)"
```

### Error in username regular expression

```json
{
    "status": {
        "code": 218,
        "desc": "Unable to parse JSON SyntaxError: Unexpected token . in JSON at position 122",
        "fields": {
            "config": "Unable to parse JSON SyntaxError: Unexpected token . in JSON at position 122"
        },
        "name": "GENERIC"
    }
}
```
`"/[a-z0-9_]+([a-z0-9_\\.-]+[a-z0-9_]+)?/i"`
(Account::USERNAME_RE.inspect in [config_serializer.rb](https://github.com/tootsuite/mastodon/blob/master/app/lib/proof_provider/keybase/config_serializer.rb#L36))

The escape part of `.` seems to be a problem.

### Required contacts have not been set up

```json
{
    "status": {
        "code": 100,
        "desc": "missing or invalid inputs {\"contact\":\"Error: wrong number in list\"}",
        "fields": {
            "config": "missing or invalid inputs {\"contact\":\"Error: wrong number in list\"}"
        },
        "name": "INPUT_ERROR"
    }
}
```

It will be an error if the contact is not set.
There are often such servers. Is there a good way?

**Comment by ThibG** [comment]
I don't have the regexp error, but yeah, not having an email contact defined causes that. Maybe we shouldn't enable the feature at all when it's not set?

**Comment by Gargron** [comment]
You might say the feature already isn't enabled when the config doesn't validate.

**Comment by ThibG** [comment]
I mean, not exposing the routes and not showing the settings page

**Comment by syui** [comment]
I have the same trouble as you have.

```sh
$ curl -X POST -d "config=`jq -c . < ./keybase-proof-config.json`" https://keybase.io/_/api/1.0/validate_proof_config.json

{"status":{"code":218,"desc":"Unable to parse JSON SyntaxError: Unexpected end of JSON input","fields":{"config":"Unable to parse JSON SyntaxError: Unexpected end of JSON input"},"name":"GENERIC"}}
```

**Comment by noellabo** [comment]
I made a pull request to fix the escape sequence.
Now passes validation via keybase.

A validation has also been implemented that requires a contact.

Now that the problem has been solved, I close the issue.
