### ISSUE TITLE
verify_credentials as username? Is that disallowed? how/where?

### ISSUE THREAD

**Issue by FremyCompany** [tootsuite/mastodon#1033]
What if an user decides to choose username verify_credentials? Is that disallowed?

> GET /api/v1/accounts/:id
> Returns an Account.

> GET /api/v1/accounts/verify_credentials
> Returns the authenticated user's Account.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
`:id` is a numeric value, so there is no overlap
