### ISSUE TITLE
Website verification without a hyperlink

### ISSUE THREAD

**Issue by emilengler** [tootsuite/mastodon#10345]
### Pitch
A way to verify your website without a hyperlink for example as a meta tag in the head

### Motivation

On my website (www.emilengler.com) my social media is not hyperlinked. It would look very weird if there is an hyperlink just to my Mastodon profile. (I know I can hide it with CSS)
My idea is too add a meta tag to the head which proofs your Mastodon profile.
For example:
`<meta rel="mastodon" href="https://mastodon.social/@emilengler">`

**Comment by Gargron** [comment]
Use `<link rel="me" href="https://mastodon.social/@emilengler" />` in the head

**Comment by unitof** [comment]
Is this documented somewhere in Mastodon? Any other types of tags it looks for?
