### ISSUE TITLE
URLs incorrectly escaped by Mastodon Web Client

### ISSUE THREAD

**Issue by Spaxe** [tootsuite/mastodon#1034]
Post this from Mastodon (I use social.tchncs.de):

```https://w3.org/&```

You get

```https://w3.org/&amp;```

This seems to only happen when `&` is included in a recognised URI.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyrias** [comment]
Same with e.g. `<https://foo/>` being entity encoded as `<https://foo/&gt;`, which is really annoying since I frequently use angle brackets to quite URLs.

**Comment by Exagone313** [comment]
#826

**Comment by Exagone313** [comment]
See #826 (no idea how to "reference" issues on GitHub).

**Comment by Spaxe** [comment]
Thanks, looks like a duplicated issue. Let's concentrate discussions there.
