### ISSUE TITLE
Show toot link in web Interface

### ISSUE THREAD

**Issue by vibhi19** [tootsuite/mastodon#10363]
When you add a link of toot in your toot it doesn't show it in multi column interface it redirect you to it Static page or whatever you say it.

Here a toot link you can visit what i mean by static page.

https://quey.org/@snder/101801338368016525

![TOOT](https://user-images.githubusercontent.com/31093426/54884046-2d142f00-4e92-11e9-9829-76a531470f17.JPG)

So instead of that redirect why dont show it in web interface it will be much faster and you dont have to leave Web interface.

**Comment by Cassolotl** [comment]
Related to *Clicking a URL of a toot should open the toot in the search area #2136*. :)

**Comment by vibhi19** [comment]
> Related to _Clicking a URL of a toot should open the toot in the search area #2136_. :)

So should i close as that will also work.
