### ISSUE TITLE
Follow request to private account results in "You don't have permission to view this page" message

### ISSUE THREAD

**Issue by elborro** [tootsuite/mastodon#10372]
I sent a follow request to user with private/locked account. This worked to other accounts with similar settings, but not to this user.

After clicking the Follow-button, I got redirected to the users /follow page, with showed the message "You don't have permission to view this page."

Both mine and the other users accounts are configured as "locked accounts" and with post-privacy set to "Followers-only". Both accounts are on the same instance. Instead of getting feedback that the follow request has been sent, I received the error message that apparently I do not have permission to sent that request.

Current version of Mastodon is 2.7.4 on Ruby 2.6.1p33 with PostgreSQL 10.5 and Redis 3.2.6.

**Comment by Gargron** [comment]
This probably means you are blocked by that person.
