### ISSUE TITLE
don’t work some menu items in the new profile column

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#10377]
### Actual behaviour

Menu items in #10337 's profile column don't seem to work properly.
Maybe, I think that don't work except "follow", "block" and "Open moderation interface".

### Steps to reproduce the problem
1. Click on any other account in the WebUI, open the profile column.
2. Click a menu item such as "Mention".
<img width="343" alt="2019-03-26 11 35 37" src="https://user-images.githubusercontent.com/766076/54968153-fb4bb700-4fbc-11e9-8746-b2179e6c3b30.png">

### Specifications

Mastodon master branch after #10337

**Comment by Gargron** [comment]
:sweat:

**Comment by mayaeh** [comment]
@Gargron I will fix it from now on
