### ISSUE TITLE
Profile column redesign is missing "incomplete profile" notice

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#10389]
The old profile column had a notice detailing that remote accounts may not be a complete view of all their activity, and had a link to open the remote profile in a new tab. The recent redesign got rid of this. It would be very useful to have it re-added.

**Comment by Gargron** [comment]
I wonder if it was effective... I was still getting "bug reports" and questions why some accounts had no statuses, or no followers that weren't local...

**Comment by trwnh** [comment]
It was a bit too muted before, and due to the low contrast, I would imagine several people missed it. It could be made a bit more clear, perhaps like so:

![image](https://user-images.githubusercontent.com/10606431/55042190-69fd3480-4ffe-11e9-87e3-410045a7cfd3.png)

![image](https://user-images.githubusercontent.com/10606431/55042204-7a151400-4ffe-11e9-86b6-fb4bacca9253.png)

![image](https://user-images.githubusercontent.com/10606431/55042218-8600d600-4ffe-11e9-83d6-11abf35b4ed1.png)

**Comment by ThibG** [comment]
I like the `fa-info-circle` version!

**Comment by Gargron** [comment]
My other idea was putting the message below the toots/accounts when you scroll to the end. So if the profile has enough items you don't get to see the message because there is little need for it.

**Comment by JonahAragon** [comment]
Personally I think that until #34 is _finally_ implemented, the message should remain displayed prominently on the profile. I like @trwnh's plain text or fa-info-circle designs.

**Comment by Gargron** [comment]
Fixed in #14031

**Comment by ThibG** [comment]
I'm not sure #14031 fully solves that: you can still have large gaps, or entirely miss all the new toots from a remote account if noone follows it, and the message would only appear when reaching the very end of the toots known by your server…
