### ISSUE TITLE
[Weblate][Report] A user (?) does harm to translations

### ISSUE THREAD

**Issue by MasterGroosha** [tootsuite/mastodon#10385]
> First of all, I'm sorry for not getting involved in Mastodon translation for some time. There wouldn't be an issue if I made some translations PRs before.

I don't see a dedicated repo or place to report issues with people on Weblate, so I'm creating an issue here.

### The problem
There's a [user](https://weblate.joinmastodon.org/user/albakham) on Mastodon's Weblate, who behaves like bot and provides machine (?) translation for strings. Not only new ones, but also for already translated. As a result, users see awful (I'm not overreacting) translation which is barely understandable. Some examples for Russian language:

* "Посты" -> "Тутс" (machine translation for "Toots", but there's no such word "Тутс")
* "Приложение, которое вы используете, чтобы зубрить будет отображаться в подробном виде ваших черепах" (some nonsense)
* " Активность счета  Все Дремлющий" (in Follows -> Last Activity, nonsense again).

If that user is a bot, could someone please disable it for RU language (can't speak for other)?
If that user is a human, could someone please restrict him from providing low-quality machine translations for languages he doesn't speak?
For now, Russian interface for Mastodon looks ugly and non-friendly to users.

Update: from what I see in his profile, account was registered on 18th March and there were 2k+ new string translations in 2.5 days. For me it looks like bot.

**Comment by Gargron** [comment]
That is very ugly. Seems like the person did it to collect a reward from OpenCollective. I might have to rethink giving out rewards to translators given the lacking quality control on submissions.

If the correct translations were previously merged to master, then we can restore them. I think weblate itself also has a history for each string, so it might be possible to fix.

**Comment by MasterGroosha** [comment]
There were some missing strings (e.g. for Polls and "Follows and Followers") which I was about to translate later (not much time recently, sorry) -> they were "machine-translated" by that user.
There were also existing strings which were edited to "machine-translated" variants, so that they became ugly.

I'm pretty sure [this](https://github.com/tootsuite/mastodon/commit/ef8b9afd1be6abdac8cfe30507adca42c38ee7c8) was the commit which made such a mess. Unfortunately, it has translations for many languages, not only Russian. 
And I'm afraid other languages might have been "spoiled" too.

**Comment by m4sk1n** [comment]
I think it's a good idea to ask from time to time users speaking particular languages about the quality of translations, could you start doing it sometimes, @Gargron?
and ban Albakham asap

**Comment by renatolond** [comment]
I got in touch with the user and he had said it was "a friend" translating stuff for ptbr. That explains it though, maybe we can comment around the translations touched so that original translators can take a look

**Comment by MasterGroosha** [comment]
@renatolond The problem is that he touched several other languages, not only Pt-Br, like Fr, It, Ru and some other, making UI much more ugly :(

**Comment by Gargron** [comment]
I created a PR that resets the locales touched by that user to their pre-merge state.

**Comment by MasterGroosha** [comment]
Thank you, @Gargron! Is it enough to `git pull` after you merge that PR to start working on new strings?

**Comment by Gargron** [comment]
I've shut down the Weblate server for now, and I don't know if I will bring it back up. The system has been eating up engineer hours by having me or another developer manually pull, normalize, fix messed up pluralalizations, messed up interpolations, remove unused strings, fix merge conflicts, then merge into master every time, then resetting Weblate because it's then out of sync. So for now I'd like to return to translators submitting pull requests directly.

**Comment by renatolond** [comment]
@MasterGroosha Ah, yeah, I understand that, I found it weird because of that, I saw that they were touching spanish and french too, but both languages were on their mastodon profile, so I assumed good faith at the time.

**Comment by jeroenpraat** [comment]
@Gargron Although I understand the reason behind this, I wish I knew earlier. I had RC1 almost completely translated in Dutch, but now it's gone! So I have to do that again, but find first what is already done.

I rather have Transifex or Crowdin (yes it's me saying that), than doing this all manually on Github. Problem with that is that the translation files always need to be in sync with the English source.

**Comment by dxwc** [comment]
@Gargron I completed react portion of the Bengali translation on weblet and have been waiting for it to be added on git. I didn't keep any backup of the translation, is that data now completely lost and must be redone ?

**Comment by Gargron** [comment]
@dxwc Weblate data is *not* deleted, so I can see about doing an import again.

**Comment by biswasab** [comment]
@dxwc  Bengali translation has issues. How does "minute" become "মাস" (month)? Please fix it.

(I cannot find the string to fix it and it's locked as well)

**Comment by LunaSquee** [comment]
Oh crap! I was just done completing the translations for Estonian on weblate (I found out about it a long time ago and then it went down) but crowdin does not have Estonian. Is all my work now useless?

**Comment by Gargron** [comment]
I've just added Estonian to Crowdin.

**Comment by Gargron** [comment]
I am importing your work from Weblate into Crowdin.
