### ISSUE TITLE
Web push notifications

### ISSUE THREAD

**Issue by stuartlangridge** [tootsuite/mastodon#1039]
Currently Mastodon provides the streaming API and mobile apps that want to use push notifications need to store the user's token on their server and listen to the streaming API and [generate push notifications themselves](https://github.com/tootsuite/mastodon/blob/master/docs/Using-the-API/Push-notifications.md). Modern browsers have now implemented [Web Push](https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/), which means that the Mastodon web app itself could send these push notifications to web browsers without having to use the company-specific APIs such as FCN. This would remove one of the major barriers to people using the Mastodon web app on their phones -- at the moment (based on a [very informal poll](https://mastodon.social/@sil/1686347)) the major piece of resistance to that is that the web doesn't do push notifications. As a data point, the [Other Place has started doing push notifications](https://lite.twitter.com/) to its web app as of today.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by gregjw** [comment]
+1

**Comment by sorin-davidoi** [comment]
In progress: #3243.

**Comment by sorin-davidoi** [comment]
@Gargron This is closed by #3243.
