### ISSUE TITLE
Mastodon does not allow remote follow on ipv6-enabled servers

### ISSUE THREAD

**Issue by Czocher** [tootsuite/mastodon#10424]
After installation of mastodon on a ipv6-enabled server everything works except remote follow (tested on multiple different remote servers).

### Expected behaviour

Should be able to remote-follow anyone I'd like.

### Actual behaviour

"Something went bad" error. No error information in logs on my instance. No errors in sidekiq nor anywhere else. 

### Steps to reproduce the problem

Set up a standard mastodon instance on a ipv6-enabled server. It has to have both a AAAA DNS record and the webserver configured to listen on the ipv6 address (as well as ipv4). Remote follow does not work. Disabling ipv6 (removing the DNS record is enough) makes the problem disappear.
It's not a problem with certificates since I used fullchain letsencrypt certificates automatically configured by caddy, which I use as my proxy server for mastodon.

### Specifications

Using the standard docker environment provided by mastodon, configured according to specs. Configured with docker-compose.

Mastodon 2.7.4 (a91349d45da18d3c85f68ae9be762dad6301c3cf)
Ruby 2.6.1p33
PostgreSQL 9.6.12
Redis 4.0.14

**Comment by nightpool** [comment]
this is almost certainly a problem with your ipv6 stack. many people have deployed mastodon successfully on ipv6, but there are also a lot of virtual hosting providers with shoddy ipv6 support. 

installation troubleshooting and support should be directed to https://discourse.joinmastodon.org or #mastodon on irc.freenode.net

**Comment by Czocher** [comment]
I'm using Ubuntu 18.04.2 LTS on a Hetzner VPS which seems to be a very generic setup. It seems like a lot of people have similar problems: #736 #960 [this](https://discourse.joinmastodon.org/t/issues-with-remote-follows-solved-solved-more-by-accident-than-design/1398/3) to name a few. I'm willing to test various solutions except turning off ipv6, which is in my opinion a very bad one.
I'd like to see some proper guide as to how to avoid surprises like those in the future. Thanks for your input, I'll move with my problem to discourse and provide a proper link to a working solution when and if I'll reach one.

**Comment by Laurelai** [comment]
Hetzner is known to have IPV6 stack issues and its one of the reasons i stopped using them.

**Comment by Czocher** [comment]
Thanks, gonna check with other projects and how people solved it. I see some information on the subject.

**Comment by Czocher** [comment]
Okay, with some help from an awesome person at https://discourse.joinmastodon.org I managed to solve the issue. It was pretty basic - a missing `1` in the AAAA DNS record. If someone has similar ipv6 problems I suggest using some online ipv6 config tester - it helped me immensely to understand what's happening, also here's the topic at discourse with lots of useful ipv6 commands: https://discourse.joinmastodon.org/t/issue-mastodon-does-not-allow-remote-follow-on-ipv6-enabled-servers/1824
