### ISSUE TITLE
Relays running pub-relay give out empty responses

### ISSUE THREAD

**Issue by IzaliaMae** [tootsuite/mastodon#10429]
### Expected behaviour

Add and relay based on pub-relay and it accepts the follow

### Actual behaviour

Relay responds with nothing and causes this error in mastodon-web

```
21:33:37 web.1     | [33622e4b-5505-464e-9715-e5f53d5eaf71] method=POST path=/inbox format=html controller=ActivityPub::InboxesController action=create status=500 error='TypeError: no implicit conversion of nil into String' duration=6.16 view=0.00 db=0.63
21:33:37 web.1     | [33622e4b-5505-464e-9715-e5f53d5eaf71]   
21:33:37 web.1     | [33622e4b-5505-464e-9715-e5f53d5eaf71] TypeError (no implicit conversion of nil into String):
21:33:37 web.1     | [33622e4b-5505-464e-9715-e5f53d5eaf71]   
21:33:37 web.1     | [33622e4b-5505-464e-9715-e5f53d5eaf71] app/controllers/concerns/signature_verification.rb:125:in `body_digest'
21:33:37 web.1     | [33622e4b-5505-464e-9715-e5f53d5eaf71] app/controllers/concerns/signature_verification.rb:107:in `block in build_signed_string'
21:33:37 web.1     | [33622e4b-5505-464e-9715-e5f53d5eaf71] app/controllers/concerns/signature_verification.rb:103:in `map'
21:33:37 web.1     | [33622e4b-5505-464e-9715-e5f53d5eaf71] app/controllers/concerns/signature_verification.rb:103:in `build_signed_string'
21:33:37 web.1     | [33622e4b-5505-464e-9715-e5f53d5eaf71] app/controllers/concerns/signature_verification.rb:61:in `signed_request_account'
21:33:37 web.1     | [33622e4b-5505-464e-9715-e5f53d5eaf71] app/controllers/activitypub/inboxes_controller.rb:12:in `create'
```

### Steps to reproduce the problem

Add a pub-relay based relay

### Specifications

This is only a problem with pub-relay and does not affect pleroma relays. I'm not sure if this issue was fixed and then broken again in later commits, but https://github.com/tootsuite/mastodon/commit/66d945209278c9344d503fe4e7a58d5c6f040e50 is the one that broke it for me

**Comment by ThibG** [comment]
I have some idea of what could be broken, but it would be broken much more frequently than that :thinking: 
Do you have one such relay I could try out?

**Comment by ThibG** [comment]
@IzaliaMae can you try this PR? https://github.com/tootsuite/mastodon/pull/10432

**Comment by IzaliaMae** [comment]
That fixed it. Thanks :3 

Btw, the pub-relay I use is yiff.social just in case you need it in the future
