### ISSUE TITLE
Make blocks work like Telegram (profile of blocker looks inactive but not deleted)

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#10437]
### Pitch

Blocking on Telegram works in a way that I like. There's no overt indication that someone has been blocked, it just looks like their account is inactive. If you know what to look for you know you've been blocked, but it's still way better than *telling* people they're blocked.

Basically, if someone blocks me, from my perspective only:
* it changes their avatar to a default image so it looks like they have no avatar.
* I can see messages that we exchanged up until the block, and if I send new messages they're marked unread forever and the blocker never receives them.
* In the "last seen" part it says "last seen a long time ago", *suggesting* that their account is inactive (ie: it's not personal).

On Mastodon obviously it is very easy to look at someone's profile to see if they are still active, but even if it only works on *some* people because they don't leave the web UI then I think it's a success.

I think for Mastodon some good additions would be:

* Impossible to like or boost each other's posts, impossible to reply to/@ each other, impossible to DM each other. (Relatedly, please please work on #9424!)
* When you block someone, your bio could look empty too, which I think would go well with the "default avatar" look.
* "You've blocked this person so we're not showing you their profile, you'll just have to open it in a new window to snoop on them."
* Not seeing the posts of someone you've blocked in Home, any public timeline, hashtag searches, etc, and them not being able to see you in those places either. (Twitter is terrible for this, I see posts by blocked people in hashtag searches all the time and it's bollocks.)

### Motivation

When someone sees a message saying "you've been blocked" it can escalate tensions, which is the opposite of what you want! They're way more likely to get angry or upset and yell about it online, possibly publicly, and/or lash out at you and find another way to harass you. If it's more subtle there's less escalation. A screenshot of an empty profile packs way less of a punch when bitching to followers than a screenshot of someone's profile saying "you've been blocked", too.

If someone gets blocked a lot and they know what blocking looks like then it might still cause escalation. But if I'm just a random internet randomer randomly messaging internet strangers, I probably just won't think about it too much or look into it, I'll just... move on. Stubborn people can still get annoyed and try to attack me in other ways, but that's not a reason to ignore this suggestion, because the majority of people getting blocked won't do that, so it saves a lot of time and emotional energy and bad feelings.

On Twitter, "you've been blocked" very much operates as part of that Outrage Machine thing.

### Emotional stuff

Yeah, not everyone has been blocked because they're a hardcore harassing trollface McNazi,  some people have been blocked for totally benign reasons! But if someone perfectly nice and okay does get blocked, I feel like we need to trust them to be able to take care of their own feelings instead of designing the feature to help them at the expense of people trying to keep themselves safe from trolls.

Like, if a perfectly nice person gets blocked and suddenly they can't see someone's profile properly in the web UI and they're not sure whether they've been blocked, that confusion is probably a slightly negative experience, and it's annoying for the devs because they have to deal with "hey developer, you have a bug, I can't see this profile in web UI", so I can definitely see that some people are mildly inconvenienced by the deliberate ambiguity. But ultimately, if a perfectly nice person gets blocked and it's unclear what's happened then they can cope emotionally and nothing bad will happen. If someone blocks me I'll just shrug and move on, I don't want anything to do with anyone who wants to block me because I don't want to make things worse!

So when people say that this change only helps harassers, I think this is what they're getting at. They mean that nice people who get blocked are not _significantly_ helped by the "you've been blocked" message, and someone doing the blocking doesn't benefit from their own profile saying "you've been blocked" to other people, **but if a troll gets blocked then seeing that "you've been blocked" message will make things worse** and contribute to the Social Media Trashfire of Outrage and Vindication.

**Comment by ThibG** [comment]
I'm tempted to close this as we decided on going in a different direction with https://github.com/tootsuite/mastodon/pull/10442

**Comment by Gargron** [comment]
Telegram profiles aren't social media profiles, i.e. you don't get a listing of all posts they've sent to anyone in the first place. The reason you keep messages you have received even after blocks is that they are copies stored in your personal inbox. On Mastodon you also have an inbox (home feed, notifications), but what we're talking about here is not those places, but the profile.

**Comment by Cassolotl** [comment]
I didn't see #10442! That's great. :) Thanks for keeping me in the loop.
