### ISSUE TITLE
Making it more visible to whom a user is actually talking to in the DMs

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#10434]
### Expected behaviour*

![image](https://user-images.githubusercontent.com/40538332/55289783-65a09500-53cb-11e9-96b5-ff7d259ac8c1.png)

### Actual behaviour*

![image](https://user-images.githubusercontent.com/40538332/55289689-f4141700-53c9-11e9-8536-1e7d43734a43.png)

*Usernames and profile pictures are pixelated for privacy reasons

### Steps to reproduce the problem

Sending someone a DM

### Specifications

Mastodon 2.7.4 (stable)
Vivaldi 2.4.1488.35 (64bit) on Arch Linux (Kernel 5.0.5)

**Comment by koyuawsmbrtn** [comment]
Closed, see https://github.com/tootsuite/mastodon/pull/9480#issuecomment-478377716

**Comment by MirceaKitsune** [comment]
Not sure if it's the exact same thing. But I've often been confused by the fact that in the DM browser, your message appears with the avatar of the person you're talking to, which is weird because it looks like your message was written by them or vice versa.

**Comment by koyuawsmbrtn** [comment]
@MirceaKitsune exactly
