### ISSUE TITLE
Thumbnail consistently uses missing.png

### ISSUE THREAD

**Issue by ValiantNinja** [tootsuite/mastodon#10438]
### Expected behaviour

To save and show the instance thumbnail.

### Actual behaviour

It uploads fine and saves, but isn't used on the homepage. Mastodon consistently shows "https://kink.town/files/original/missing.png" which is a 404. - An example of this can be seen at https://kink.town/ - Before this issue started happening, it would also error when loading the home page and stop loading entirely. To fix it, I had to set a thumbnail and since then the page has loaded and I've had this issue.

### Steps to reproduce the problem

Upload a thumbnail and check the homepage

### Specifications

Latest master commit - This is a fresh instance from the master too, not an upgrade from 2.7.x

Edit: When I reference "homepage" I mean the /about page (Sorry if there was any confusion)

**Comment by ThibG** [comment]
I can't reproduce it, and there have been very recent fixes to this. Can you update and try again? Thanks

**Comment by ValiantNinja** [comment]
Hey, I just updated and tried to reproduce and it's still there. 

Here's a log of when I saved it
```
Apr 01 12:59:29 mastodon bundle[4635]: [adf1138b-1678-4920-978b-1850f740d4bb] [paperclip] Trying to link /tmp/RackMultipart20190401-4695-x0ubbb.png to /tmp/634dd08bc9a34bbadacdb1107215f5a920190401-4695-143gj1h.png
Apr 01 12:59:29 mastodon bundle[4635]: [adf1138b-1678-4920-978b-1850f740d4bb] [paperclip] Trying to link /tmp/634dd08bc9a34bbadacdb1107215f5a920190401-4695-143gj1h.png to /tmp/634dd08bc9a34bbadacdb1107215f5a920190401-4695-woc72t.png
Apr 01 12:59:29 mastodon bundle[4635]: [adf1138b-1678-4920-978b-1850f740d4bb] Command :: file -b --mime '/tmp/634dd08bc9a34bbadacdb1107215f5a920190401-4695-woc72t.png'
Apr 01 12:59:29 mastodon bundle[4635]: [adf1138b-1678-4920-978b-1850f740d4bb] [paperclip] Trying to link /tmp/634dd08bc9a34bbadacdb1107215f5a920190401-4695-143gj1h.png to /tmp/634dd08bc9a34bbadacdb1107215f5a920190401-4695-1e32bee.png
Apr 01 12:59:29 mastodon bundle[4635]: [adf1138b-1678-4920-978b-1850f740d4bb] Command :: file -b --mime '/tmp/634dd08bc9a34bbadacdb1107215f5a920190401-4695-1e32bee.png'
Apr 01 12:59:29 mastodon bundle[4635]: [adf1138b-1678-4920-978b-1850f740d4bb] [paperclip] deleting site_uploads/files/000/000/001/original/pfp.png
Apr 01 12:59:29 mastodon bundle[4635]: [adf1138b-1678-4920-978b-1850f740d4bb] [paperclip] saving site_uploads/files/000/000/001/original/pfp.png
Apr 01 12:59:29 mastodon bundle[4635]: [adf1138b-1678-4920-978b-1850f740d4bb] method=PATCH path=/admin/settings format=html controller=Admin::SettingsController action=update status=302 duration=519.78 view=0.00 db=18.96 location=https://kink.town/admin/settings/edit
Apr 01 12:59:29 mastodon bundle[4635]: [6b60088c-9175-4f65-b9ce-4e48e3dad153] method=GET path=/admin/settings/edit format=html controller=Admin::SettingsController action=edit status=200 duration=51.35 view=34.76 db=3.43
```

I'm gonna go for the database and compare it to my working instances and get back to you. I'm honestly confused on what could cause this

**Comment by ValiantNinja** [comment]
Okay, so looking in to it more it appears it was actually confusion on my part. I started using Mastodon with 2.7 and "Thumbnail" was always considered the front page. This has since changed and the image on the front page is now the "Hero" - This is where my confusion came in. I just set a picture as the hero and it now shows. I'm sorry for wasting your time. Everything is all good!
