### ISSUE TITLE
Improve and open up the search function

### ISSUE THREAD

**Issue by matrix07012** [tootsuite/mastodon#10439]
### Pitch
Make the search function capable of searching through every public toot stored in the database and make it capable of searching only through toots that mention specified users.
Also increasing the amount of search results would fit nicely with this change.

### Motivation
The search function is extremely basic, but requires Elastic Search which is a powerful, but resource heavy search engine. Such basic search could easily be done with SQL.
Improving search would make spending on additional resources, to run Elastic Search, a worthwhile investment. It would also help users find people interested in similar topic.

**Comment by Cassolotl** [comment]
Inability to search all toots by keyword is by design to reduce harassment. See also issues like #594.

**Comment by matrix07012** [comment]
> Inability to search all toots by keyword is by design to reduce harassment. See also issues like #594.

If the search function was made basic on purpose, why does it need Elastic Search and not just use SQL?

**Comment by Cassolotl** [comment]
I think it's because you can search your own toots and toots you've boosted and favourited and stuff, on the basis that you have already seen and interacted with them? I'm not 100% sure on this, someone more knowledgeable than me might have to step in here!

**Comment by matrix07012** [comment]
I'm not sure either. Mastodon alre

**Comment by nightpool** [comment]
Elasticsearch is used to provide advanced natural language stemming and fuzzy search, which is completely orthogonal from the *scope* of the posts any individual user is allowed to search. Users are only shown search results from posts that they have previously interacted with.

Increasing the amount of search results is another separate request—the amount of results returned for a given query is only limited by the UI.

**Comment by matrix07012** [comment]
I've never used them, but I know that Postgres offers both language stemming and fuzzy search.

**Comment by nightpool** [comment]
Postgres' full text indexes are less fully featured then elasticsearch and much much more complicated to set up and maintain. this decision was discussed to death when it was made, i don't there's substantial value to be had by re-visiting it.
