### ISSUE TITLE
Remove all remote emojis

### ISSUE THREAD

**Issue by Amolith** [tootsuite/mastodon#10441]
### Pitch

It would be nice to be able to remove all remote emojis with a couple button presses (one to remove and one to confirm) or a `tootctl` command.

### Motivation

Instance admins could find it useful when "cleaning house" and deleting old stuff. Personally, I essentially just moved to a new server and removed `system/` so no images anywhere are loading. I'm having to go through and delete all the emojis one by one. It seems like it would be a fairly simple feature to implement compared to some of the *awesome* ones in 2.8.0

**Comment by BenLubar** [comment]
@Gargron this seems to delete *all* custom emoji, not just remote ones.

**Comment by Amolith** [comment]
@BenLubar That's actually what I ended up needing to do to solve my problem so *I'm* happy with it as it is (thank you for interpreting that correctly @Gargron).

It *would* be useful to be able to *only* remove remote ones though for the other reason I mentioned above. It would also make it easier to remove emojis you may not be interested in adding and make wading through the pages easier. 

I'd like to see this command kept as-is and instead maybe adding one just for remote ones?
