### ISSUE TITLE
Invite Links are unusable on mobile

### ISSUE THREAD

**Issue by joycem137** [tootsuite/mastodon#10448]
Issue with #7704 in 2.8.0rc1

### Expected behaviour

After generating a link, there should be a way to copy the link to send to others, when running mobile.

### Actual behaviour

The copy button did not work on iOS and the link text itself could not be selected to manually copy it.

### Steps to reproduce the problem

On my iPhone, I went to Settings -> Invite People, generated an invite link, and then attempted to copy.  The copy button didn't work for me, and I was unable to highlight and copy the text to send to someone. I had to go to a desktop computer to copy and send the invite link

### Specifications

iPhone iOS running Mastodon in Safari.
Mastodon 2.8.0rc1.

**Comment by ThibG** [comment]
It is apparently not possible to programmatically copy anything into the clipboard on older versions of iOS, so the copy button is *not* going to work.
There are also quirks regarding the selection. I will try to fix them.
