### ISSUE TITLE
Weblate.joinmastodon.org gives a 502

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#10462]
I hope this will reach @Gargron here, cause he didn’t respond to my toot. I also made a post on Discource to be sure.

Weblate.joinmastodon.org gives a 502 Bad Gateway for a few days now. It’s important it comes back online, cause we are near a release and I noticed not all strings were up-to-date in the RC1 (so there had to be some errors when syncing back to the Github repo).

**Comment by Aditoo17** [comment]
@Gargron intentionally closed the Weblate server: https://github.com/tootsuite/mastodon/issues/10385#issuecomment-477331393

**Comment by jeroenpraat** [comment]
@Aditoo17 OK thank you for the heads up. I will continue in that issue and close this one.
