### ISSUE TITLE
Account export / import via API

### ISSUE THREAD

**Issue by unwitting** [tootsuite/mastodon#1047]
Having looked through the API docs I can't see any endpoints for performing data export / import as provided through the interface? I may be missing it or searching for the wrong thing.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
This looks like a duplicate of https://github.com/tootsuite/mastodon/issues/177 so I'm going to close. Feel free to re-open if that's not the case. Thanks!
