### ISSUE TITLE
Don't pin the Notifications column by default

### ISSUE THREAD

**Issue by MirceaKitsune** [tootsuite/mastodon#10497]
I'd like to suggest the removal of the pinned Notifications column for new users. I believe that by default, the Home timeline should be the only column available, and if the user wants other columns they should pin them manually. Unpinning the notifications tab is the first thing I do myself after registering on a new instance, as to me it's just clutter that confuses me and gets in the way. I base my suggestion on two arguments primarily:

First of all, I periodically hear of users complaining that the multi-column layout is confusing, which is especially true for people coming from Twitter. This might be making Mastodon feel off-putting and driving new users away, especially before they learn that the extra column can be easily unpinned. I too find it confusing to work with multiple columns except temporarily. Although they're a good idea at their core, the system should be optional... meaning only one column should be there by default, the Home timeline.

On top of that, notifications aren't frequent enough to warrant their column being visible all the time. Right now I'm following 120 users on mastodon.social and engage with posts on a daily basis: I get notified of less than one reply / boost / fave per day on average... for new users this is even less and thus more useless. If the developers want multiple columns in a format that's useful, I'd rather the Home Local and Federated timelines were defaulted instead, which would make much more sense than Home and Notifications in my opinion.

For ease, here's a comparison between the current default (Home + Notifications) and how my suggested default looks like (only Home). I think most can agree the later is cleaner and looks better... which might further improve if we get customizable column width later on.

![Screenshot_20190407_164352](https://user-images.githubusercontent.com/825418/55684803-1f61ad80-5958-11e9-9ffe-b6a2af131210.png)
![Screenshot_20190407_164406](https://user-images.githubusercontent.com/825418/55684804-22f53480-5958-11e9-8a9c-db7c9067e1b3.png)

**Comment by MirceaKitsune** [comment]
For clarification: I was reminded to open this ticket by a toot Eugen posted. It reminded me of something I already believed: That multi-column can easily get confusing, and adding more than one column should be an option the user takes manually based on how they wish to arrange their layout.

https://mastodon.social/web/statuses/101882693373233483

**Comment by ealgase** [comment]
I think that only having two columns wouldn't make sense, instead, we should have another built in frontend that's more similar to Twitter (something that looks like the current web view).

**Comment by Cassolotl** [comment]
Is this resolved by the new default simple layout for new users?

**Comment by MirceaKitsune** [comment]
@Cassolotl Should be. But I'm not sure if the multi-column layout also removed it by default, which IMO would be the better route.

**Comment by ealgase** [comment]
It is, for new users.

**Comment by Cassolotl** [comment]
>But I'm not sure if the multi-column layout also removed it by default

It didn't!
