### ISSUE TITLE
Multiple layouts for Web UI

### ISSUE THREAD

**Issue by Aditoo17** [tootsuite/mastodon#10507]
### Pitch

It would be nice to choose multiple layouts for the Web UI. Other than the column layout, it can have another layout similar to the Twitter layout.

### Motivation

Some people in the replies to [this toot](https://mastodon.social/@Gargron/101882693373233483) suggested adding new UIs, explaining that the current UI may be confusing. I personally like the column layout, but I get the users who are confused.

**Comment by ealgase** [comment]
I think having a layout similar to the public view of toots (similar to the one on Twitter) would make a lot of sense (and would be *very* easy to implement, all that's needed is timeline support, as profiles and toots are already implemented).

**Comment by didnt1able** [comment]
I wish they would add PleromaFE. The pleroma UI is so much nicer and more intuitive than mastodon.

**Comment by ealgase** [comment]
I think the currently existing static UI is pretty close to PleromaFE.

**Comment by Aditoo17** [comment]
So I guess now that we have the simple layout (#10807, #10809, #10820), I can probably close this.
