### ISSUE TITLE
Toot menus are unaware of user mute/block state

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#10514]
### Steps to reproduce the problem

1. Load the "Muted users" list.
2. Load a user from the "Muted users" list.
3. Note that the 3dot menu correctly lists "Unmute user" as an option.
4. View that user's "Toots and replies" tab.
5. Open any reply by that user, or any toot that contains a reply from that user.
6. Note that the 3dot menu on the user's toot incorrectly shows "Mute user", as if they are not already muted. Alternatively, note that the user's toot is visible at all in the thread context.

### Expected behavior

- When viewing from a profile, muted/blocked state is reflected in status menus.
- When viewing from a thread, both blocked and muted users are hidden/removed.

### Actual behavior

- When viewing from a profile, muted/blocked state is not reflected in status menus.
- When viewing in a thread, blocked users are removed, but muted users are still visible until blocked. User toots remain removed even after unblocked, though.

### Specifications

mastodon.social v2.8.0rc1, unsure how far it goes back. There may be other side effects.

**Comment by trwnh** [comment]
Presumably Relationship is not cached via the api; maybe it should be?

**Comment by Gargron** [comment]
The solution should be that opening the toot dropdown would send a relationship API request. That would allow us to put "follow" option on toot dropdowns as well.

**Comment by ThibG** [comment]
Fixed by #12377
