### ISSUE TITLE
Add message field to registration approval request

### ISSUE THREAD

**Issue by joycem137** [tootsuite/mastodon#10512]
I really like the new registration approval feature. Even though our instance is relatively closed, we're really happy to have new folks come in if they know someone on the instance.  However, the account approval system doesn't have a space to add a message explaining who you are. So for a more closed server like ours, it is harder to identify who someone is who requests an account on our server.  

It'd be nice to add a field for a custom message for them to write in their justification for requesting an account "Hi, I'm XYZ's friend! Can I join your server?"

It'd also be nice to have the opportunity to post a custom message in that text.

**Comment by Cassolotl** [comment]
I'm very in favour, I've had this on various other network things and it was really helpful!
