### ISSUE TITLE
HTML parsing problem

### ISSUE THREAD

**Issue by mathiasblc** [tootsuite/mastodon#10530]
Hello,

Since 2.8.x Mastodon seems to have an HTML parsing problem. Prior to the last versions everything was fine in the configuration but now I get the following error without modifying anything:

<img width="862" alt="Screenshot 2019-04-09 at 22 49 06" src="https://user-images.githubusercontent.com/41020854/55834356-0143ab00-5b1a-11e9-9a43-a26b38e40dc1.png">

Thanks in advance,

**Comment by nightpool** [comment]
Hi, the HTML validation was introduced in version 2.8. You have a raw "&"
in "news & useful informations", which isn't allowed by strict HTML
validation. We agree that the validation is slightly annoying, but it's
hard to figure out where to draw the line—some people have accidentally
ended up with very broken layouts from incorrectly formatted custom HTML.

**Comment by mathiasblc** [comment]
Thanks, I missed it in the changelog.
