### ISSUE TITLE
Block & report dialog in another language not wide enough

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#10531]
When blocking a user, the dialog in another language (Dutch in my case) is not wide enough. See screenshot.

![Schermafdruk van 2019-04-10 00-38-59](https://user-images.githubusercontent.com/41594439/55839817-85515f00-5b29-11e9-8a1b-eb90fba06177.png)

### Specifications

Mastodon 2.8.0 RC2

Firefox 66.0.2 on Ubuntu 17.10

P.S. Steven was a test, I don't really wanted to block him. :wink:

**Comment by ThibG** [comment]
Setting `flex-shrink: 1` for `.confirmation-modal__secondary-button` would make it shrink (with an ellipsis) instead of pushing the block button away, which would be better but not completely solve the issue.

Maybe we should allow the dialog to grow wider?
