### ISSUE TITLE
Problems with html validation in site settings page

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#10532]
In 2.8.0 HTML is validated on the System Settings page. I use an unsupported html tag (details), so I can't safe these settings. Because I'm the admin, I think I should be able to override the validation. So please add somewhere (CLI is okay) to disable the validation.

**Comment by Gargron** [comment]
The only validations we really care about are unclosed HTML tags. Maybe there is a way to filter Nokogiri errors for just those...

**Comment by jeroenpraat** [comment]
the error code is:

`contains invalid HTML markup: 5:9: ERROR: Tag details invalid`

**Comment by Cassolotl** [comment]
>I use an unsupported html tag (details)

There's no link, was there meant to be one?

**Comment by jeroenpraat** [comment]
@Cassolotl 'details' is the name of the HTML tag, bot actually details ;-)

**Comment by Cassolotl** [comment]
@jeroenpraat OH oops. :D

**Comment by jeroenpraat** [comment]
Sorry @Gargron. Now he doesn't complain about the details tag anymore, but about the p tag. The p tags are unclosed correctly. Only when I remove all p tags, it accepts it, but nothing is changed on the about page. Only when I empty the site_description field, it's emptied on the about page too. Weird thing is when I put one word in it after that, it doesn; t update the about page. I think there a few things wrong here.

**Comment by jeroenpraat** [comment]
I found the reason that is not displayed on the about page. The 'Server description' and the 'Short server description' are reversed.

**Comment by jeroenpraat** [comment]
When I replace all **p** tags with **span**, it works. When I replace all **p** tags with **div**, it again says: 'contains invalid HTML markup: 4:11: ERROR: Unexpected end tag : p'

**Comment by Gargron** [comment]
Site description says: "Introductory *paragraph* on the API". Short site description says: "Describe what Mastodon is and what makes this server special in a *single paragraph*."

They have always been rendered within a `<p>` tag, but until now, there was no validation to confirm your markup wasn't broken. Block level tags are invalid within `<p>`. You can work around this by adding `</p>` before your block level tags and a final `<p>` within your markup

**Comment by jeroenpraat** [comment]
@Gargron Thanks, that works indeed for the site description. But it doesn't work for the 'Custom extended information'. If I put a </div> on the first line and a <div> on the last line, it complains about 'Unexpected end tag : div'.

**Comment by Gargron** [comment]
Custom extended information is not wrapped in anything, so all your tags are your tags. If there is an error, it means your markup is actually wrong, check if all tags are closed properly.

**Comment by jeroenpraat** [comment]
Ok, let me double check that, cause checking it manually and online gave no errors.

**Comment by jeroenpraat** [comment]
@Gargron OK I found it. It didn't like it that I enclosed lists with p tag.

I still think that admins should be able to disable html validation, but that is probably a won't fix, so I close this issue.

The problem that 'Server description' and 'Short server description' are reversed, is another problem. But you know now, not another issue is needed I presume.

**Comment by usbsnowcrash** [comment]
This change caught me by surprise.  I couldn't figure out what was causing my html to be considered invalid.  Can we loosen this maybe?

**Comment by ykzts** [comment]
@usbsnowcrash 

Gargron writes the solution in https://github.com/tootsuite/mastodon/issues/10532#issuecomment-481733644

> They have always been rendered within a `<p>` tag, but until now, there was no validation to confirm your markup wasn't broken. Block level tags are invalid within `<p>`. You can work around this by adding </p> before your block level tags and a final `<p>` within your markup

**Comment by usbsnowcrash** [comment]
The error message is extremely confusing and I’ve seen a few admin posts trying to figure out what happened. 

It might be worth investing in either better error messages, not embedding in a paragraph tag if one is already present or at least explaining in the UI that it will be treated as if it’s inside p tags.
