### ISSUE TITLE
docker healthcheck doesn't work after upgrade to v2.8.0

### ISSUE THREAD

**Issue by markusblogde** [tootsuite/mastodon#10554]
docker ps:
tootsuite/mastodon:v2.8.0    "/tini -- yarn start"    5 hours ago         Up 5 hours (unhealthy)

docker-compose.yml is original at healtcheck:
 healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --header 'x-forwarded-proto: https' --proxy off localhost:4000/api/v1/streaming/health || exit 1"]

happens on web and streaming-container.

**Comment by ykzts** [comment]
Do you solve it with #10553 ?

**Comment by markusblogde** [comment]
hi, yes this solved it. Thank you!
