### ISSUE TITLE
Problem/questions

### ISSUE THREAD

**Issue by wremy** [tootsuite/mastodon#1056]
Hey, do you plan to add the media in spoiler ?

After few tests, when I toot in "private" it's only for my followers in the SAME instance. is it normal or ?
Is it normal that the hashtag don't work before a spoiler ?

Thanks for your time

**Comment by riking** [comment]
All of these are answered already:

 For media spoiler, #1010 or use the NSFW button
Private toots go out to your federated followers as well (and, of course, are visible to those herds' admins)
Hashtags in the content warning is covered here https://github.com/tootsuite/mastodon/issues/722#issuecomment-290982644

**Comment by wremy** [comment]
Okay thanks. But I don't talk about Direct toot but Private toot (Post to followers only). When I toot in private in .social. Only my followers from .social can see the toot not my followers from others instances

**Comment by nightpool** [comment]
@wremy @riking Private status only go to the same server for privacy reasons. there have been thoughts on allowing users to opt-in to private tweet federation

**Comment by wremy** [comment]
Thanks !
