### ISSUE TITLE
Delete-and-redraft resets poll deadline to 1 day

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#10567]
### Expected behaviour

If you make a poll that has a deadline of anything other than 1 day, delete-and-redraft should retain that.

### Actual behaviour

If you make a poll that has a deadline other than 1 day, delete-and-redraft makes the deadline 1 day and you have to manually change it again.

### Steps to reproduce the problem

1. Post a post with a poll in it, making sure to set the time to 3 days or 5 minutes or something.
2. Click "delete and redraft" in the post menu.
3. Notice that the timer thing has changed back to 1 day.

### Specifications

mastodon.social, v2.8.0. Chrome on Mac 10.14.4.

**Comment by koyuawsmbrtn** [comment]
I can confirm this. @Gargron anything new on a fix?
