### ISSUE TITLE
Tags show (send) html in user description ( related to Gnu-social)

### ISSUE THREAD

**Issue by Shnoulle** [tootsuite/mastodon#1057]
Hi,

## report
I was in GNU social  1.2.0-beta5 (nightly of this morning) and user description of Mastodon user have big issue

1. Tags have a lot of html integrated => clearly tags must send in text like #tags : this is clearly a mastodon issue.
2. `&apos; ` are shown : here i'm unsure if it's a Mastodon issue or a Gnu-social issue : did HTML is allowed in protocols ? (asked at gnu-social repo)

## related bug : 
- Qvitter (closed : clearly not qvitter bug) https://git.gnu.io/h2p/Qvitter/issues/90
- Gnu-social : https://git.gnu.io/gnu/gnu-social/issues/254

## exemple 
1. hashtags
    ![capture du 2017-04-06 16-12-05](https://cloud.githubusercontent.com/assets/1439428/24759631/65140d76-1ae6-11e7-8a53-44f2bd295e71.png)
2. apos
    ![capture du 2017-04-06 16-11-54](https://cloud.githubusercontent.com/assets/1439428/24759636/6b94dcf2-1ae6-11e7-8b36-fa1a5c6bb4fa.png)

**Comment by Gargron** [comment]
Mastodon treats the text of the bios just like text of toots (i.e. rich formatting reflected in Atom representation). I think GNU social treats it like plaintext

I don't think the exact format is mandated by any spec, hence the inconsistency. The point in favour of rich formatting exchange is that while consuming instances can strip/sanitize the input as much as they like, they might not own as much information about the origin user's intent as the origin user's instance to turn plain text into rich formatting (formatting syntax etc)

**Comment by Shnoulle** [comment]
OK for HTML in description added by user , protocol is unclear.

But about all this html : `<a href="https://www.zaclys.com" rel="nofollow noopener" target="_blank"><span class="invisible">https://www.</span><span class="">zaclys.com</span><span class="invisible"></span></a>` added by Mastodon, not by user :)

**Comment by ashfurrow** [comment]
@Shnoulle any follow-up on this?

**Comment by Shnoulle** [comment]
Still an issue , and clearly not a gnusocial issue : the `<span class="invisible">https://www.</span>` or for nthe tags : `<a href="https://mamot.fr/tags/privacy" class="mention hashtag">#<span>privacy</span></a>` Added by mastodon, not by the user.

Then still an issue : see https://ostatus.shnoulle.net/shnoulle/subscriptions

**Comment by ashfurrow** [comment]
Thanks for following up.
