### ISSUE TITLE
Changing Interface language show error

### ISSUE THREAD

**Issue by vibhi19** [tootsuite/mastodon#10570]
I changed the interface language(हिंदी)  as soon as i hit save i see an error page. Its basically like a lockout any url show an error page 

I checked on other instance running 2.8.0 has same issue 

![Mastodon error](https://user-images.githubusercontent.com/31093426/56080544-ecb82900-5e1f-11e9-97fa-e3fb6cc5d4f5.JPG)

**Comment by Aditoo17** [comment]
The translation file for Hindi is empty. That's probably the cause of the problem. https://github.com/tootsuite/mastodon/blob/master/config/locales/hi.yml

**Comment by vibhi19** [comment]
Thank thank you for reply

That make sense can you tell me what i can do change interface language and set it back to english

**Comment by Aditoo17** [comment]
I'm sorry, I do not know how to set the language back.
