### ISSUE TITLE
Some posts are classified as Chinese while they are actually Japanese

### ISSUE THREAD

**Issue by carbon-twelve** [tootsuite/mastodon#10578]
### Expected behaviour
No `lang="zh"` attribute on a div element holding the toot below (see Steps to reproduce the problem)

### Actual behaviour
The div element has a `lang="zh"` attribute.

### Steps to reproduce the problem
Post "来週土曜" with Mastodon posting language set to "Automatically detect language" and the browser's language set to "ja"

(I guess "来週土曜" doesn't make sense in Chinese)

### Specifications
Mastodon version: v2.8.0
OS: macOS High Sierra
Browser: Firefox 66.0.2

I understand this behavior won't happen when the posting language is "日本語 (Japanese)".
I'd say, however, Mastodon should respect the browser's language since it seems not a few users leave their posting language as "Automatically detect language" and that the precision of the language detector is questionable.
(It's *highly* challenging to distinguish Japanese from Chinese automatically given a really short text, which is a common case for Mastodon)

**Comment by Gargron** [comment]
Unfortunately I do not know how we can use browser language to influence language detection. CLD3 does not take a "hint". Simply assuming the browser's language is the same as the language a person is going to post in might lead to a lot of wrong results (is there any data on this?). One idea would be to use CLD3's `FindTopNMostFreqLangs` function to return 3 or 4 guesses and compare them against the browser's language, however, @akihikodaki's CLD3 gem does not currently expose that CLD3 function and I personally don't even know how to return a C array into Ruby so I can't modify it.

**Comment by ykzts** [comment]
Resolved with #12124
