### ISSUE TITLE
"Load more" button in "Home" column disappears when clicked

### ISSUE THREAD

**Issue by wolfadex** [tootsuite/mastodon#1058]
"Load more" button in "Home" column disappears when clicked.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by winniehell** [comment]
Since scrolling down in the column seems to fetch new toots what is the "Load more" button for anyway? :confused:

**Comment by wolfadex** [comment]
There needs to be a way to fetch new toots when the number of toots doesn't exceed the height of the column, i.e. you can't scroll.

**Comment by ashfurrow** [comment]
@wolfadex you must have a very large monitor for the first page of toots not to scroll!

**Comment by winniehell** [comment]
> There needs to be a way to fetch new toots when the number of toots doesn't exceed the height of the column, i.e. you can't scroll.

@wolfadex That situation can be calculated: We know the height of a toot and we know the current browser window height. So even then it is possible to automatically fetch toots.

Current situation is:

- for a small number of toots there is a load more button which does nothing (only disappears)
- for a very large number of toots you never see the load more button

**Comment by ashfurrow** [comment]
Thanks for clarifying @winniehell – do you think this issue should be closed or remain open?

**Comment by winniehell** [comment]
@ashfurrow I would say let's fix this issue by removing the button and always automatically fetching toots. What do you think?

**Comment by winniehell** [comment]
> Would you be available to make a pull request?

Yes, but I can't guarantee that this will happen anytime soon. I started working on polls (#1629) and want to finish that first.

**Comment by ashfurrow** [comment]
Sounds good, no rush!

**Comment by ThibG** [comment]
Closed as it is likely resolved.
The “load more” button disappears when content is loading, and reappears back when the data has been loaded (or has failed to load).
The button is still useful in situations where loading failed, because of a network error, for instance, to let the user load new toots again.
