### ISSUE TITLE
Discussion on same Mastodon are not linked when send to GnuSocial instance

### ISSUE THREAD

**Issue by Shnoulle** [tootsuite/mastodon#1060]
## Issue

1. MastoUser1 remote_user send a toot on his mastodon instance
2. I receive the notification : OK
3. MastoUser2 answer on this toot on mastodon instance : i don't receive the notice : OK
4. MastoUser1 answer to MastoUser2 :  
      1. I receive the notice : OK
       2. But the notice didn't have the same conversation id : KO 

I'm unsure of the protocol here , but must be improved.

Related gnu-social issue : https://git.gnu.io/gnu/gnu-social/issues/253  

Example  : 
1. First notice i receive : `ostatus.shnoulle.net/conversation/572587#notice-603050`
2. Second notice : `ostatus.shnoulle.net/conversation/572596#notice-603059`
3. The conversation on Mastodon : `social.imirhil.fr/users/aeris/updates/386`

**Comment by lambadalambda** [comment]
Probably the same bug as https://github.com/tootsuite/mastodon/issues/325

**Comment by Shnoulle** [comment]
See https://github.com/tootsuite/mastodon/issues/325
