### ISSUE TITLE
Regression: 'Server description' only used for API, not landing page anymore

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#10611]
_I already told this in another bug, but I see it is still not solved, so let's make a proper bug report._

### Expected behaviour

In the admin server settings the text under 'Server description' was before v2.8.0 used on the landing page. 

Text under 'Short server description' was used on sidebars on account profiles.

### Actual behaviour

Text under 'Server description'  is not used on the landing page anymore. It is only used for the API. 

Text under 'Short server description' is now used for the profile sidebars + the landing page. 

### Desired behaviour

Please use the 'Server description' for the landing page again. Text on the landing page and account profile sidebars have a different purpose (for my instance at least). I think this is a regression.

:information_source: If this is a _won't fix_, please describe the usage of the two description fields more specific, and please move the current 'Server description' below the 'Short server description' .

**Comment by Aditoo17** [comment]
Suggestion: add the "long server description" to the `/about/more` page, maybe right under the hero image. I remember the server description used to be on that page as well before the public page redesign.

**Comment by stemy2** [comment]
You can make the description appear on the landing page by adding a server thumbnail. It worked for me.

**Comment by Phroneris** [comment]
Fixed? -> #12119
