### ISSUE TITLE
Verify SHA-512 HTTP Signatures

### ISSUE THREAD

**Issue by cjslep** [tootsuite/mastodon#10638]
### Pitch

Please consider verifying SHA-512 signatures in addition to SHA-256 ones.

### Motivation

I would simply prefer using SHA-512 to SHA-256 in my AP projects, and would like Mastodon to accept and verify them.

The limitation/requirement of SHA-256 is also not explicitly mentioned in https://blog.joinmastodon.org/2018/06/how-to-implement-a-basic-activitypub-server/ and is implicit on the code snippet. So updating the rationale for sticking to a few algorithms could also be explicitly mentioned with this excellent reference that nightpool gave me: https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by vpzomtrrfrt** [comment]
Unfortunately, there is currently no defined way to attach a signature algorithm to actor keys, though the current HTTP Signatures drafts technically require there to be one

**Comment by cjslep** [comment]
Yeah this is a very out-of-date request from back when HTTP Signatures allowed the algorithm header to be specified.
