### ISSUE TITLE
Email whitelist for self-registration only

### ISSUE THREAD

**Issue by clerie** [tootsuite/mastodon#10648]
### Pitch

We want to open the public registration form for everyone which email address matches to specific domains. But after successful confirmation, or when registering using an invite link, any email address should be allowed.

### Motivation

I'm providing an instance for people doing stuff around an university. Many of them have official email addresses from the university or other organisations. They should be allowed to self register. But we have a decent amount of users too, which haven't such email addresses, they should be able to register using an invite link. Also you have your official university email address only for the time you studying here, when you leave, you will loose it. For this, they should be allowed to freely change their address.

For now, we need to leave the self registration closed and have to send everyone their invite link manually.

**Comment by ealgase** [comment]
You could try the "open applications" method which is a bit better.

**Comment by Gargron** [comment]
I agree that e-mail whitelists/blocklists should maybe be ignored when using a valid invite link, or when updating the e-mail address after initial sign-up.
