### ISSUE TITLE
Support Collection/OrderedCollection literal for `followers`

### ISSUE THREAD

**Issue by cjslep** [tootsuite/mastodon#10643]
When Mastodon fetches my remote actor's followers, the response is:

```
{"@context":"https://www.w3.org/ns/activitystreams","id":"https://cjslep.com/user/c/followers","items":"https://mastodon.technology/users/cj","type":"Collection"}
```

### Expected behaviour

Successfully rendering the followers collection in the profile preview.

### Actual behaviour

It doesn't render

### Steps to reproduce the problem

Try to list `@cjslep@cjslep.com` (if my website is up, it is under heavy development)

Ex, a curl call:

```
$ curl --insecure -H "Accept: application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"" https://cjslep.com/user/c/followers
{"@context":"https://www.w3.org/ns/activitystreams","id":"https://cjslep.com/user/c/followers","items":"https://mastodon.technology/users/cj","type":"Collection"}
```

### Specifications

Mastodon version: Current (2.8.0 (?))

[AP Spec](https://www.w3.org/TR/activitypub/#followers) allows this kind of formulation to be valid. ActivityStreams also allows `items` to be a single literal if only 1 element.

It seems Mastodon expects followers to dereference into something like:
```
{"type":"OrderedCollection","first":"<url to first page>"}
```
And then the pagination to contain the elements:
```
{"type":"OrderedCollectionPage","items":[...],"next":"<url to next"}
```

**Comment by nightpool** [comment]
hey, just to the clear, the only information we currently use from the
followers collection is the size or number of followers. are you also
having issues updating this number?

we only show local followers when looking at the profile preview.

**Comment by cjslep** [comment]
I don't yet set "totalCount" (or w/e the specific property is called). Will be doing so in the future. That is good to know.

Does this mean there won't ever be a way for a Mastodon user to view the followers of my blog software? If so, could the focus of this bug be changed to be a feature request to permit this behavior?

**Comment by nightpool** [comment]
mastodon will show the subset of the local followers for remote users (i.e.
the followers it already knows about" through Accepted Follow activities)
materializing the entire list isn't something that has a lot of value when
people can just click through to the real profile on the remote server.
(and iterating through a potentially unbounded list and keeping it in sync
definitely has a lot of complications we're not particularly interested in
solving)

**Comment by cjslep** [comment]
Thanks. That explains why I still can't see myself, since it is based on the `Accept{Follow}` (which I still need to figure out why are getting 422'd) instead of the returned `followers` collection:

```
{"@context":"https://www.w3.org/ns/activitystreams","id":"https://cjslep.com/user/c/followers","items":"https://mastodon.technology/users/cj","totalItems":1,"type":"Collection"}
```

**Comment by nightpool** [comment]
thanks! I'm going to mark this issue as resolved, but let me know if you want to debug this 422 issue more. (maybe on a different ticket, and probably on a different forum, like the mastodon discourse or socialcg irc). I thought we decided it was a problem with the http signature algorithm you were using though?
