### ISSUE TITLE
Properly Alias "as" in "@context"

### ISSUE THREAD

**Issue by cjslep** [tootsuite/mastodon#10646]
The `@context` given by Mastodon in at least 1 instance does not alias the ActivityStreams vocabulary to be `"as"`, which is referenced in several other imports.

I believe this is non-normative in the JSON-LD spec, so I am only pointing this out in case this is something Mastodon devs care about JSON-LD parsers and the compaction/expansion algorithms, since other things in the context are being properly aliased by Mastodon.

### Expected behaviour

```
{  
   "@context":[  
      {
          "as": "https://www.w3.org/ns/activitystreams" // Alias the import with the "as" prefix.
      },
      // ...
      {  
         "manuallyApprovesFollowers":"as:manuallyApprovesFollowers", // now properly aliased
         // ...
         "alsoKnownAs":{  
            "@id":"as:alsoKnownAs",  // now properly aliased
            "@type":"@id"
         },
         "movedTo":{  
            "@id":"as:movedTo",  // now properly aliased
            "@type":"@id"
         },
         // ...
         "Hashtag":"as:Hashtag",  // now properly aliased
         // ...
      }
   ]
}
```

OR, without aliasing

```
{  
   "@context":[  
      "https://www.w3.org/ns/activitystreams" // Existing unaliased reference
      // ...
      {  
         "manuallyApprovesFollowers":"https://www.w3.org/ns/activitystreams#manuallyApprovesFollowers", // now properly qualified
         // ...
         "alsoKnownAs":{  
            "@id":"https://www.w3.org/ns/activitystreams#alsoKnownAs",  // now properly qualified
            "@type":"@id"
         },
         "movedTo":{  
            "@id":"https://www.w3.org/ns/activitystreams#movedTo",  // now properly qualified
            "@type":"@id"
         },
         // ...
         "Hashtag":"https://www.w3.org/ns/activitystreams#Hashtag",  // now properly qualified
         // ...
      }
   ]
}
```

### Actual behaviour

When I do this curl command:

```
$ curl --insecure -H "Accept: application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"" https://mastodon.technology/users/cj
```

The `@context` I get back is (note there is no `"as"` alias):

```
{  
   "@context":[  
      "https://www.w3.org/ns/activitystreams",
      "https://w3id.org/security/v1",
      {  
         "manuallyApprovesFollowers":"as:manuallyApprovesFollowers",
         "toot":"http://joinmastodon.org/ns#",
         "featured":{  
            "@id":"toot:featured",
            "@type":"@id"
         },
         "alsoKnownAs":{  
            "@id":"as:alsoKnownAs",
            "@type":"@id"
         },
         "movedTo":{  
            "@id":"as:movedTo",
            "@type":"@id"
         },
         "schema":"http://schema.org#",
         "PropertyValue":"schema:PropertyValue",
         "value":"schema:value",
         "Hashtag":"as:Hashtag",
         "Emoji":"toot:Emoji",
         "IdentityProof":"toot:IdentityProof",
         "focalPoint":{  
            "@container":"@list",
            "@id":"toot:focalPoint"
         }
      }
   ]
}
```

### Steps to reproduce the problem

Rerun the above curl command.

### Specifications

Mastodon 2.8.0

**Comment by ThibG** [comment]
`as` is defined in `https://www.w3.org/ns/activitystreams` as `https://www.w3.org/ns/activitystreams#`.

**Comment by nightpool** [comment]
thibg is correct. the first few lines of the AP context are:

```
{
  "@context": {
    "@vocab": "_:",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "as": "https://www.w3.org/ns/activitystreams#",
    "ldp": "http://www.w3.org/ns/ldp#",
    "id": "@id",
    "type": "@type",
    "Accept": "as:Accept",
```

**Comment by cjslep** [comment]
Yes I know. This is invalid JSON-LD as defined in the [context processing algorithm](https://www.w3.org/TR/json-ld-api/#context-processing-algorithm) due to the cyclical nature of the references (emphasis mine):

> Then, for every other key in local context, we update the term definition in result. Since term definitions in a local context may themselves contain terms or compact IRIs, we may need to recurse. **When doing so, we must ensure that there is no cyclical dependency, which is an error**. After we have processed any term definition dependencies, we update the current term definition, which may be a keyword alias.

And for the bare inclusion:

> If context is a string, it represents a reference to a remote context. We dereference the remote context and replace context with the value of the @context key of the top-level object in the retrieved JSON-LD document. If there's no such key, an invalid remote context has been detected. Otherwise, we process context by recursively using this algorithm **ensuring that there is no cyclical reference**.

I'll file a bug against the AS spec itself to remove this cyclical dependency, but that means that `as` will need to be defined elsewhere, which means in Mastodon's `@context` if it wants to use the `as` prefix.

**Comment by nightpool** [comment]
Not sure I understand how this is a circular dependency. Are you getting the context confused with the term definition? To be extremely pedantic, setting `{"as": "https://www.w3.org/ns/activitystreams#"}` does not reference the activitystreams context at all. (and nothing I can find in the context processing algorithm suggests it does).

**Comment by cjslep** [comment]
I suggest moving this conversation to the ActivityStreams issue. TL;DR `"@context": {"as": "https://www.w3.org/ns/activitystreams#"}` is a "term definition" of `as` and so follows through the first paragraph I quoted.
