### ISSUE TITLE
Document privacy expectations of server-to-server protocol

### ISSUE THREAD

**Issue by khimaros** [tootsuite/mastodon#10649]
It took some digging, but I finally found a comment by @Gargron on #4208 explaining how the server-to-server protocol treats subscriptions for locked accounts:

> we don't just let anyone subscribe to an Atom feed, and then push private toots to all subscribers, no. We filter subscribers such that a subscriber will only receive a toot if the author has a follower on that server. This means that if you lock your account (such as that you must approve followers before they're counted as followers), the distribution is tightly limited to servers your followers are from

It seems that the ActivityPub specification does not require any of this and in general seems to have punted on auth and privacy in general.

We should make the design choices in Mastodon clearer to the end-user. In particular, making it very clear what the privacy expectations are for each post type and which circumstances will result in the web of trust expanding to other servers.

This is my current understanding:

- when you send a direct message between two users on the same instance, you implicitly trust the owner of that instance and no others.
- when you send a direct message between two users on different instances, you implicitly trust the owner of both instances and no others.
- when you publish a followers-only post, you implicitly trust the owner of all instances hosting any of your followers and no others.
- when you publish a followers-only post with an unlocked account, anyone can follow you without approval, leaving an unbounded web of trust
- public posts are visible by anyone.

If these are approximately correct, let me know and I will wordsmith further.

**Comment by nightpool** [comment]
The post you found is very out of date and predates ActivityPub. Modern Mastodon uses [ActivityStreams audience targeting](https://www.w3.org/TR/activitystreams-vocabulary/#audienceTargeting), as [specified by ActivityPub](https://www.w3.org/TR/activitypub/#delivery), for its communications. Activities have an audience, which may include Public, and they are delivered by the server to that audience.

No-one except the origin server is allowed by ActivityPub to distribute activities (except as permitted by the [inbox forwarding section of the ActivityPub spec](https://www.w3.org/TR/activitypub/#inbox-forwarding), which always respects the authored audience)

**Comment by khimaros** [comment]
@nightpool thank you -- a deeper reading of the ActivityPub spec left me with the following impression:

The ActivityPub server-to-server protocol does not specify a mechanism by which a server can request data from the outbox of a federated actor. If I understand correctly, this means servers should never back-fill content when a new federation has been established.

However, I did not find a requirement stating that a server MUST NOT reply to another server with the contents of an actor's outbox. Further, the [authorization model](https://www.w3.org/TR/activitypub/#authorization) for outbox access is poorly defined. It would be nice to specify how Mastodon handles this undefined behavior.

Ultimately, my original request has not been addressed: we need better end-user documentation (contextual or otherwise) covering the specific privacy concerns raised in my original request.

**Comment by nightpool** [comment]
@khimaros I'm sorry, when you said "documentation" I thought you meant developer-facing specifications about ActivityPub rather then user-facing documentation about what Mastodon does. Our user facing documentation (https://docs.joinmastodon.org/usage/privacy/) does include some mention about this: 

>Do not share dangerous and sensitive information over direct messages. Mastodon is not an encrypted messaging app like Signal or Wire, the database administrators of the sender’s and recipient’s servers have access to the text. Use them with the same caution as you would use forum PMs, Discord PMs and Twitter DMs.

but i'm down to improve it if you have concrete suggestions! Note that we used to have a more long-form version of this: https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/User-guide.md#toot-privacy but it's slightly out of date—we don't send private posts to GNU Social or over OStatus any more, so there's no concern about users being unaware of privacy settings. It also mentions users boosting other user's private posts, but that's not really possible; they can boost an unauthenticated version of your post, but no other server will see that as "legit". it would just be a less effective version of taking a screenshot of a private and posting it to your own account

**Comment by nightpool** [comment]
Ultimately I think the spec is kind of a red herring here—no matter what the spec says, any server can feel free to publish whatever it wants. For example, gmail could make all of its users inboxes public tomorrow and they wouldn't be violating any "spec", but nobody considers that a flaw in SMTP. (except for the lack of e2e encryption, which is kind of an unsolved problem in one-to-many broadcast spaces like a social network)
