### ISSUE TITLE
Don’t show old toots when restoring a Mastodon tab

### ISSUE THREAD

**Issue by ariasuni** [tootsuite/mastodon#10652]
### Expected behaviour

Restoring a Mastodon tab loads the same toots that when you open a new Mastodon tab.

### Actual behaviour

The same tabs that were open before unloading the tab/closing the browser are displayed.

### Steps to reproduce the problem

Use an extension to unload tabs/use «Restore my previous session» settings in your browser and restart it.

### Specifications

Mastodon 2.8.0

**Comment by nightpool** [comment]
I don't think there's an easy way for us to fix this—it's something
chrome/firefox are doing and it's not easy for us to fix. (unless there's a
web platform feature to detect when a tab has been reloaded that I don't
know about)

>

**Comment by ThibG** [comment]
This is the browser serving cached data for the REST API requests. It appears to serve cached data even if the `Cache-Control` header is set to `no-cache` (through `expires_now`, which is not currently the case).
Using `no-store` seems to work, but Rails has no helper function for that.
