### ISSUE TITLE
Issue with precompiling assets during setup of Mastodon

### ISSUE THREAD

**Issue by phobos-dthorga** [tootsuite/mastodon#10659]
I'm trying to run the command `RAILS_ENV=production rails assets:precompile` during the last stages of the Mastodon setup, but I keep getting this error about some component called `uglifier`.

https://paste.gekkofyre.io/view/a96d62f7

I've tried Ruby versions `2.6.0`, `2.6.1`, `2.6.2`, all without luck and all with the same error as per above. I believe I'm using `nodejs` version `10.15.3` after having tried the latest stable release of `12` and then reading that Mastodon does not support any versions later than `11`.

Regarding server specifications, I’m trying to setup Mastodon on a VPS under one of our dedicated servers (we use SolusVM and a virtual machine just for this purpose), which has 6 vCPUs and 8 GB of RAM, along with 120 GB of SSD space. The dedicated server itself has 128 GB of DDR3 ECC RAM, a modern Intel Xeon CPU, etc. Basically it hosts a number of clients for our web-hosting company, GekkoFyre Networks, but still has enough spare resources for this VM instance.

This issue is occurring in the latest stable release of Mastodon at the time of writing (what that maybe I'm not sure), although I have been following installation instructions from here: https://docs.joinmastodon.org/administration/installation/

Any help on this topic would be sincerely appreciated, thank you.

**Comment by phobos-dthorga** [comment]
So I've gotten a bit further by performing the following commands:

`bundle add uglifier
bundle install --no-deployment`

But now I get this error: https://paste.gekkofyre.io/view/18264991

Again, any help on this matter would be sincerely appreciated, thank you.

**Comment by ThibG** [comment]
maybe try `RAILS_ENV=production bundle exec rails assets:precompile`?

**Comment by phobos-dthorga** [comment]
Hello @ThibG,

Thank you for your response and I apologize for making an issue out of nothing, but I was able to get things to work in the end by reinstalling everything and setting up Mastodon as a Docker instance this time around. Many thanks for your help though!
