### ISSUE TITLE
No confirmation email sending

### ISSUE THREAD

**Issue by CanftIn** [tootsuite/mastodon#10668]
Hi, I just set up a new mastodon instance: https://matrixwood.top
And I can log in with admin account normally.
But when I want to make a new account for test, the new account email does not receive the confirmation mail.
I log in admin and use administrator privileges to reset email. The new account still not receive the mail. And I confirm it not in trash can

**Comment by JamesABDL** [comment]
This would be more suitable to ask on [discourse.joinmastodon.org](https://discourse.joinmastodon.org), but did you get the test email during the setup wizard?

**Comment by CanftIn** [comment]
Then I will go to the community to add a ask.
I didn't get any email. And while I set up the .env.product, the test email option I choose NO
