### ISSUE TITLE
[Bug] Layering with the emoji picker is weird

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#10672]
### Expected behaviour

For the emoji picker to be on top of everything else while I'm picking emojis.

### Actual behaviour

I'm replying to something with a CW, which makes the new toot column quite long on my screen.

![Screenshot 2019-05-03 at 01 55 18](https://user-images.githubusercontent.com/6607512/57115404-b72f9d00-6d46-11e9-972a-25081a004726.png)

If I click reply and then scroll down in that column, the emoji picker is sandwiched between the Home column header and everything else somehow!

### Steps to reproduce the problem

0. Have a short screen, like on a laptop maybe? I'm on a MacBook Air and it has a shot wide screen.
1. Find a toot with a CW.
2. Click reply.
3. Scroll down.
4. Click the emoji picker symbol.

### Specifications

queer.party (v2.8.0 vanilla), Mac 10.14.4, Chrome (latest).

**Comment by ThibG** [comment]
Pretty sure this has been fixed. Please reopen if that's not the case.
