### ISSUE TITLE
App background image is large

### ISSUE THREAD

**Issue by pschfr** [tootsuite/mastodon#1067]
The image located in [app/assets/images/background-photo.jpeg](https://github.com/tootsuite/mastodon/blob/master/app/assets/images/background-photo.jpeg) is `874 KB` which may not seem like much, but it is `2460` by `1920` pixels which surely could be shrunk. I commonly use Photoshop's Save for Web feature, which can save a lot of size. I then use [Compress JPEG](http://compressjpeg.com/) to compress the image even further.

This image here is an example of that (and it's the same resolution), and as you can see we went from `874 KB` to `105 KB`.

![background-photo-min](https://cloud.githubusercontent.com/assets/490222/24763078/4e45bf40-1abe-11e7-8987-9f75e45e3684.jpg)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by zoski** [comment]
Why not make a pull request to include that in the project ?Here is more info about how: https://help.github.com/articles/about-pull-requests/
