### ISSUE TITLE
[Bug] Notification says a poll I voted in has ended, but I didn't vote in it - I posted it!

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#10681]
### Expected behaviour

The notification to say "a poll you posted has ended."

### Actual behaviour

It says "a poll you voted in has ended", but I'm not able to vote in my own polls so it's inaccurate.

![Screenshot 2019-05-03 at 18 01 31](https://user-images.githubusercontent.com/6607512/57153227-a118ef80-6dcd-11e9-9fe0-72cf081cd4a4.png)

### Steps to reproduce the problem

It just happens when a poll I posted closes at its expected time.

### Specifications

queer.party (v2.8.0 vanilla)

**Comment by Cassolotl** [comment]
This issue still happens in 3.0.1 vanilla, though the Glitch fork seems to have resolved it.

**Comment by grahamperrin** [comment]
> I'm not able to vote in my own polls

This surprised me; <https://github.com/mastodon/mastodon/discussions/23365#discussioncomment-11162690>.
