### ISSUE TITLE
Incorrect documentation for cleaning remote media (Docker Guide and Production Guide)

### ISSUE THREAD

**Issue by abortu** [tootsuite/mastodon#10686]
### Expected behaviour

tootctl commands should be listed in the documentation (Production and Docker) for cleaning up remote media periodically. The rake tasks don't exist anymore.

It appears the following should be the command in the documentation:
`tootctl media remove`

### Actual behaviour

Docker Guide:

`docker-compose run --rm web bundle exec rake mastodon:media:clear `
***rake task doesn't exist***

Production Guide: (for setting up cronjob)
`RAILS_ENV=production
@daily cd /home/mastodon/live && /home/mastodon/.rbenv/shims/bundle exec rake mastodon:media:remove_remote`
***rake task doesn't exist***

### Steps to reproduce the problem

N/A, documentation issue

### Specifications

v2.8.0

**Comment by NicolasCARPi** [comment]
Related closed PR during migration: https://github.com/tootsuite/documentation/pull/711/files

**Comment by Gargron** [comment]
Fixed
