### ISSUE TITLE
toots appearing out of order

### ISSUE THREAD

**Issue by each** [tootsuite/mastodon#10690]
I've just set up a new instance, mastodon v2.8.0 running on ubuntu  18.04 LTS. Several people have signed up as local users to kick the tires. Some reported seeing posts out of order in the timeline. I looked into it, and it turns out they were right - several toots are timestamped as having been posted in the future, and those keep floating to the top of the timeline, displaying "now"  until the clock catches up to them.

As far as I can tell nobody affected did anything unusual . The same users, using the same browsers, all posted other toots at around the same time that were timestamped correctly, so this doesn't look to me like a client problem. Clues welcome.

**Comment by Gargron** [comment]
I'd check the clock on your server.. Also which timezone it's configured as, I prefer UTC to avoid most problems

**Comment by each** [comment]
> I'd check the clock on your server.. Also which timezone it's configured
> as, I prefer UTC to avoid most problems 

Thanks. The server is configured to UTC. It's possible the clock has
been occasionally jumping forward and back, but I haven't seen any other
evidence of it. It's running ntpd.

Is there any logging of posts that I could turn on?  I haven't been able to
see this happen in real time, but if I could compare a toot's nominal date
to the actual clock time when it was posted, and the difference turned out
to be an integer multiple of hours, that would suggest a timezone problem.

**Comment by each** [comment]
(Update: It's not an integer multiple.  It's happened a couple of times today and it looks like the offset was roughly 2.5 hours.)

**Comment by each** [comment]
D'oh! It *was* the clock after all, I finally spotted evidence in an unrelated log file. Seems to have been a vmware issue. Thanks, never mind, closing.
