### ISSUE TITLE
localhost URLs persistent on domained instance

### ISSUE THREAD

**Issue by unwitting** [tootsuite/mastodon#1071]
I've set up a new instance at myhostname.com, but I'm seeing that some URLs once logged in and on the main app are not pointing to myhostname.com/etc, but localhost:3000. `LOCAL_DOMAIN=myhostname.com` is set, should I need to do anything else?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
It sounds like you're using Docker, in which case seeing `localhost:3000` in the logs is normal (because of how Docker works). Have things gone smoothly since opening the issue?
