### ISSUE TITLE
v2.8.2 image is not available on hub.docker.com

### ISSUE THREAD

**Issue by phil-r** [tootsuite/mastodon#10712]
### Expected behaviour

v2.8.2 image should be available dockerhub

### Actual behaviour

It's not available: https://hub.docker.com/r/tootsuite/mastodon/tags

### Steps to reproduce the problem

```sh
docker pull tootsuite/mastodon:v2.8.2
Error response from daemon: manifest for tootsuite/mastodon:v2.8.2 not found
```

**Comment by hugogameiro** [comment]
It was Docker Hub that was taking a long time doing the build. It already finished and it's available: https://hub.docker.com/r/tootsuite/mastodon/tags

**Comment by phil-r** [comment]
Yeah, it's available now! 🎉
