### ISSUE TITLE
Users can spam timeline with extremely tall posts

### ISSUE THREAD

**Issue by areyoutoo** [tootsuite/mastodon#1072]
Users can make *extremely* tall posts that spam the federated timeline.

Example screenshot:

![image](https://cloud.githubusercontent.com/assets/3433518/24765225/d0512104-1aab-11e7-98c7-35ed148ae062.png)

This post is about 250 lines tall, based on the 500-character limit. If a single user (or several users) started spamming such posts, that could start to pose a serious usability problem for many other users.

I doubt it's possible, practical, or even desirable to completely stop this behavior, but I think a "show/hide" option for very tall posts, similar to the current content warning feature, could go a long way toward mitigating the impact.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Pajn** [comment]
There is an PR open for this #658

**Comment by areyoutoo** [comment]
@Pajn Ah, good catch! I'm not sure what best practice is... should we keep this issue open, or close it and focus effort on the PR?

**Comment by fenwick67** [comment]
@areyoutoo It's probably best to close this since there's already an issue and PR to fix it.

**Comment by areyoutoo** [comment]
Closing per recommendation. Thanks all.
