### ISSUE TITLE
Suggestion: add clickable element below post avatar to expand status

### ISSUE THREAD

**Issue by joyeusenoelle** [tootsuite/mastodon#10733]
Mastodon currently suffers from a bug where if a toot contains an image but no text, the toot cannot expand the status within the web interface with a single click; the user needs to use the "..." kebab menu to expand the status, which involves an extra click and which requires the user to know that the option is in that menu. 

This suggestion would add a clickable, contentless element below the avatar of any given toot (i.e. after the `<div>` with the class `status__avatar`), which has the same events attached to it as the text of a toot. This element should have a height equal to the remaining height of the toot, less a certain amount of padding at the top, and it should not contain any visual content.

The end result is that the appearance of Mastodon's web interface would remain unchanged, but new functionality would be added to take advantage of what is currently unused space in the interface.

A user would thus be able to click on this otherwise empty space in the interface and expand the status, without needing to find or be told about the "Expand this status" menu option.

**Comment by Cassolotl** [comment]
See also #8529!

**Comment by Dar13** [comment]
See also https://github.com/tootsuite/mastodon/pull/9492 which uses the status bar rather than the avatar negative space.

**Comment by Cassolotl** [comment]
This should have been fixed with *Adds click-able div that expands status (#10733)*, right?
