### ISSUE TITLE
Show remote users on profile directory

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#10738]
It is time to make the directory more useful by also including opted-in remote users on it. Perhaps there could be "local"/"federated" tabs on it. One complication is that the opted-in-ness is not currently federated.

**Comment by mynameismonkey** [comment]
The directory is a great tool for surfacing content, discovering people to follow, and I agree it could be more effective. I like the idea of showing non-local users on my local directory but I would want some form of administrative control. 

As an instance admin, I have a set of policies I enforce on my userbase. What option would I have for removing someone from my directory if I felt they do not represent or adhere to those policies? I may not want to silence them as they may be perfectly fine people for my local users to interact with, but I may also at the same time not want that federation user representing the community in the community directory.

Separately, what control would I have as an admin of a smaller instance than many to ensure my directory doesn't become majority federation users? Having the two tabs mitigates this, but can also confound directory browsers - I would prefer a single view of the community you can participate with, local and federated. However, one of the joys of running a federated community is being able to demonstrate to potential new members the idiosyncratic style or culture of the community they are joining. If the local directory members are over-diluted by federation members, this might weaken the value proposition for new members, or effectively dilute the vertical pull of many of the relatively specific  verticals some of the instances attract.

I believe curating the directory such that not every federated connection with an opt-in would be listed, but instead include only those federation members who have interacted with toots from the instance via public boost or reply. This would demonstrate a larger, more useful and more representative directory without flooding it with federation input nor needing much input from the instance admins.

Of course, this all presumes opt-in status being federated.

**Comment by JamesABDL** [comment]
Local and federated tabs would be a must, otherwise I would want to disable this feature (which should be an option). Our user base and hashtags are very niche, but it's a useful feature for small communities to find each other.
