### ISSUE TITLE
Remove OStatus-related code

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#10740]
In 3.0, it is time to remove OStatus from Mastodon. Mastodon has not been designed as a multi-platform system and supporting a legacy platform creates messy and confusing code. Furthermore, the OStatus code has not been receiving the same performance and security improvements, in many parts because the OStatus protocol is inherently less secure in some aspects.

**Comment by ReK2Fernandez** [comment]
do this means we will break some friend connections?

**Comment by Gargron** [comment]
Pleroma, Misskey, Friendica, and Hubzilla have already switched to ActivityPub, the only software that still hasn't is GNU social. If that's where your friends are, then yes. But we can't hold off on it forever.

**Comment by ReK2Fernandez** [comment]
@Gargron no, was just curious because I run a node, so I know people will ask me eventually.

**Comment by dalmemail** [comment]
GNU social ActivityPub support is supposed to be ready in 3-4 months. Would it be so hard to wait until then?

**Comment by nightpool** [comment]
@dalmemail this is just something planned as part of the 3.0 milestone. There isn't anything imminent about this ticket.

**Comment by dalmemail** [comment]
That's good to know @nightpool :)
Thank you for the answer

**Comment by emilebosch** [comment]
What standards will remain after this? Just activitypub and webfinger which are used in mastodon?

**Comment by Gargron** [comment]
Yes, ActivityPub and Webfinger. I'm not sure why your question is worded like that but fyi OStatus never reached past the draft stage in the standardization process.

**Comment by emilebosch** [comment]
Aah sorry, didn't mean to sound that. I'm just entering the Fediverse, and by eliminating these protocols, things get simpler. Its kinda hard to grasp what is really needed in order be _fediverse_ worthy so looking at mastodon as a reference implementation. So thank you!

**Comment by kevinmarks** [comment]
Why drop WebSub and keep WebFinger?

**Comment by trwnh** [comment]
presumably to keep user@domain working, and since mastodon relies on acct: uri even more than https uri it would take a lot of refactoring to hypothetically drop webfinger
