### ISSUE TITLE
Nothing into the Federated timeline

### ISSUE THREAD

**Issue by kadiix** [tootsuite/mastodon#1075]
Hi,
I just create an instance (mastodon.brussels) and I followed some member from others instances to have interconnection. But at this moment nothing appaers in the Federated timeline..

What can I do to solve the problem ? 

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by zcdunn** [comment]
As you follow and interact with more users from other instances, your federated timeline will grow. Also, if you allow other users into your instance, their followed users and interactions will make the federated timeline grow even faster.

**Comment by ashfurrow** [comment]
@kadiix it looks like @zcdunn has answered your question (thanks!) so I'm going to close this issue. Please feel free to re-open if you'd like further clarification.
