### ISSUE TITLE
tootctl really needs progress bars

### ISSUE THREAD

**Issue by TrollDecker** [tootsuite/mastodon#10752]
Basically what I just said. Right now the only progress indicator for a number of functions are a bunch of dots and plusses, and that's... not even remotely helpful at all. What do the dots mean? What do the pluses mean? Why can't it just tell me in plain current/total numbers how far a command has progressed and how much more there is to go?

Just have it print a progress bar with counter, and at least I'd have some idea as to whether I should leave it to run overnight or if it's about to finish up about half a minute after I've left the keyboard.

**Comment by Gargron** [comment]
Fixed
