### ISSUE TITLE
Expose Keybase Verification as Profile Metadata via API

### ISSUE THREAD

**Issue by lucascantor** [tootsuite/mastodon#10777]
### Pitch

- Keybase verification is shown in the web UI along with other profile metadata
- It should also be exposed as profile metadata via the API

### Motivation

- Mastodon apps should include Keybase verification info when displaying users' profiles
- This missing profile metadata misrepresents users' identities and confuses their followers
  - Mastodon app developers are [currently unable to resolve this](https://github.com/DagAgren/toot/issues/316#issuecomment-486333698)

**Comment by Gargron** [comment]
Documentation not updated, `GET /api/v1/accounts/:id/identity_proofs` method in the API exposes this
