### ISSUE TITLE
By default, do not attach metadata that exposes which client I'm tooting from

### ISSUE THREAD

**Issue by Ragzouken** [tootsuite/mastodon#1077]
it's a small thing, but i don't want to needlessly share metadata like this - does it even serve a purpose? i assume twitter does it because 1. they have strong restrictions on their API usage, and 2. they want to analytics the heck out of it

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
That's a good question, I'm not sure.

**Comment by Gargron** [comment]
This is kinda important for things like: "Here is a weird message, I didn't say that, where did it come from? (bad app)" but also "Here is a cool app I am using" (ensuring a good 3rd party app ecosystem)

If you could disable app metadata, rogue apps would of course disable it. So, sorry, but closing!
