### ISSUE TITLE
Clarify the concept and the rules of instances

### ISSUE THREAD

**Issue by thomaskuntzz** [tootsuite/mastodon#1078]
The home page of the project does a good job at explaining briefly and clearly the aim of the project and its key features (and by the way, bravo, because, unfortunately, that's kind of *rare* to see things that neat on open source projects :+1: ).

However, *even though I'm pretty familiar with the concept of decentralized social networks*, I had to read *several articles* about Mastodon in order to understand (basic though important) things like that my username is "reserved" only on the instance I signed up on or that each instance is moderated under its own rules, and many others (as of now, I'm not even yet sure of these things...). :confused: 

I definitely think it would be a good idea to create a small section on the home page explaining and clarifying briefly all those cocepts. What are your thoughts on it? :slightly_smiling_face:

**Comment by riking** [comment]
Can you make a draft of the updates you'd like made to the https://github.com/tootsuite/mastodon/tree/master/docs/Using-Mastodon docs?

**Comment by thomaskuntzz** [comment]
Well I myself don't really understand how all that works... But I'll try to learn more and draft something ASAP

**Comment by ashfurrow** [comment]
Hey @thomaskuntzz! Thanks for opening the issue. The docs have recently been updated, and moved: https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/User-guide.md#decentralization-and-federation Do you think that, as-is, they clarifying things sufficiently? Or do you think we should keep this issue open?

**Comment by thomaskuntzz** [comment]
@ashfurrow Thanks for caring!

I saw these docs, but the purpose of this issue was more to create a *small section* explaining *succinctly* the *main lines* of how Mastodon works technically. It would be intended for people who are just discovering Mastodon and stumbled upon the website.
It would allow them to understand how Mastodon technically differs from Twitter (for instance) before signing up, so that they won't be surprised by some specificities of Mastodon.
The point is to *avoid people to get frustrated* to misunderstand why something in Mastodon works the way it works (like e.g. usernames), like many people (including me) have already got.

I really stress that it would be something really *short and clear* in order to be featured on the home page. This is why telling people who *just heard about Mastodon* and are *wondering if they should take an interest* in it to read the **documentation** just wouldn't fit...

What do you think of it? :slightly_smiling_face:

**Comment by ashfurrow** [comment]
I think it's a great idea! Something like https://github.com/tootsuite/joinmastodon ? It's still under development but I think it addresses the need you're describing. What do you think?

**Comment by thomaskuntzz** [comment]
Yeah, I didn't hear about this until now, but that looks promising!
But something key is what will it be (a separate website) and how it will be featured on the homepage (if it doesn't replace it)...

But still, while this is being developed, I think we can work on the section I suggest to add to the homepage. :slightly_smiling_face:

**Comment by ashfurrow** [comment]
Ace, sounds great 👍 I think linking to the new joinmastodon website might be better than docs, but it's not finished yet. But yeah, agreed there. Do you have time to write up what you think that might look like? No rush!

**Comment by thomaskuntzz** [comment]
I already drafted something, but it is what it is: a draft...

> Mastodon is a social network *software*. It's a bit like Twitter, but it's [open source](https://en.wikipedia.org/wiki/Open-source_model). That means anyone can take the source code and set up its own social network on a server somewhere. By doing that, he creates an **instance** of Mastodon, that is, a small Twitter-like social network.
>
> All the instances of Mastodon are *separate social networks*. They're moderated and managed according to their own rules. But they can communicate with each other. Because each instance is a separate social network, the username you use is "reserved" only on the instance you use. Each user is designated by @username@instance. Like with e-mails, there can be someusername@someemailprovider.com and someusername@anotheremailprovider.com designating two separate people (or at least accounts).

**Comment by ashfurrow** [comment]
Hmm, some of this (like fully qualified user names) is covered by the onboarding that new users are now presented with. I think we'd want to boil it down to the absolute minimum, since the landing page is already pretty information-heavy.

There's another potential solution too: instance admins can provide a _site description_. You can see it at the bottom of my instance's landing page: https://mastodon.technology I wonder if pre-populating this with info might be helpful too? Not sure.

**Comment by thomaskuntzz** [comment]
You're right, but the thing is brand new and I saw it only after writing that...

And yes, we clearly have to boil it down to the bare minimum, otherwise it will just add clutter without being useful.

Sorry but I don't understand which part you refer to as the *site description*... :sweat_smile:

**Comment by thomaskuntzz** [comment]
And by the way, do you know where the code (the content part) of the onboarding tutorial is?

**Comment by ashfurrow** [comment]
Sure sure, the site description is everything below "What is mastodon.technology?" (on my instance). There's discussion of moving it up, so this issue maybe should be merged with others talking about the landing page. 

The code for the on boarding modal is mostly at https://github.com/tootsuite/mastodon/blob/master/app/assets/javascripts/components/features/ui/components/onboarding_modal.jsx

**Comment by Cassolotl** [comment]
This is on every /about page now:

![screen shot 2018-05-26 at 11 11 50](https://user-images.githubusercontent.com/6607512/40575052-a0957f5c-60d5-11e8-950b-ae8e2f56c824.png)

Does that meet the needs described in this issue? If so, it could be closed!
