### ISSUE TITLE
Cannot close panels

### ISSUE THREAD

**Issue by thomaskuntzz** [tootsuite/mastodon#1079]
I think it would be great to be able to close the panels we don't use and re-open them later if needed.

Would allow to have a twitter-like interface where you only have one "feed" open. This way, things you're not interested in doesn't take up space and attention.

Maybe I just didn't figure out how to do that, but in this case, how I can do it has to be clearer :wink:

**Comment by slime-man** [comment]
Personally, I am against horizontal scrolling on any website, and the way mastodon seems to work right now, the content is wider than a normal-sized browser window.

**Comment by wxcafe** [comment]
duplicate of #827, which is a duplicate of #351. Closing
