### ISSUE TITLE
framapiaf.org instance not working with Tooter app on SailfishOS

### ISSUE THREAD

**Issue by glanternier** [tootsuite/mastodon#10804]
framapiaf.org instance not working with Tooter app on SailfishOS

### Expected behaviour

 Ability to authorize app to login to account hosted on frampiaf.org

### Actual behaviour

 When I click on "Authorize" on the website, I get back to previous page and the authorization did not take effect.

### Steps to reproduce the problem

 
1/ Install Tooter on SailfishOS
2/ Enter framapiaf.org URL in login page
3/ load authorization page in Browser
4/ click on Authorize

**Comment by ykzts** [comment]
This is not a issue with Mastodon.
