### ISSUE TITLE
docker-compose deleted my entire database

### ISSUE THREAD

**Issue by alexgleason** [tootsuite/mastodon#1080]
I just ran `docker-compose build` followed by `docker-compose up -d`, then `docker-compose down` and `docker-compose up -d` and it deleted the entire database for my site.

I can't find the files anywhere under /var/lib/docker/volumes. It appears to be totally gone. I'm really bummed. Does anyone know why this happened? I'm concerned it was due to the images being changed but I don't know.

**Comment by pnathan** [comment]
You have to mount a local volume for your postgres data to be retained between destroys. You can see where volumes are used elsewhere in the docker file.

https://docs.docker.com/engine/tutorials/dockervolumes/

**Comment by alexgleason** [comment]
It mounts automatically with a fingerprint. I did find the data eventually under /var/lib/docker/volumes. Now I can't log in, though...
