### ISSUE TITLE
Subscribe to Atom feeds directly

### ISSUE THREAD

**Issue by aaronpk** [tootsuite/mastodon#1081]
I should be able to enter a URL in the "search" box, and Mastodon should be able to subscribe to the Atom feed it finds there. StatusNet had this ability a while ago, which was great for adding to the number of possible people you can subscribe to.

For an example URL you can try subscribing to, enter `http://tantek.com/` in the search box. This should find the Atom feed `http://tantek.com/updates.atom`, which was previously possible to subscribe to from a StatusNet instance. Note that this feed even supports PubSubHubbub, so you can get realtime notifications of new posts as well.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kevinmarks** [comment]
This would mean I can subscribe to https://xoxo.zone/@kevinmarks by copy and paste rather than having to manually edit it to @kevinmarks@xoxo.zone. Then mastodon mungs it back into a url to call webfinger on,  to look up the @ thingy to get the URL back.

**Comment by Gargron** [comment]
You can actually enter https://xoxo.zone/@kevinmarks into the search and it will resolve your profile.

However, I do not plan on supporting Atom feeds that don't have Webfinger and Salmon (i.e. non-interactive, non-user feeds)

**Comment by aaronpk** [comment]
@Gargron Thanks for the clarification. May I ask what the reasoning behind that decision is?

**Comment by kevinmarks** [comment]
It doesn't resolve the longer profile urls though eg https://xoxo.zone/web/accounts/316

**Comment by ashfurrow** [comment]
@kevinmarks can you open an issue for not resolving the longer profile URLs? 

@aaronpk it looks like your question has been answered, so I'm going to close this issue. Feel free to re-open (or open a new issue) if you'd like further clarification.
