### ISSUE TITLE
Upgrade issue 2.4.7. to 2.8.x

### ISSUE THREAD

**Issue by mahescho** [tootsuite/mastodon#10816]
As other resources failed I post here:

I try to upgrade my 2.7.4 NON Docker instance to 2.8.1. When I do:

git checkout $(git tag -l | grep -v 'rc[0-9]*$' | sort -V | tail -n 1)
It complains that the following files have local changes:

app/lib/activitypub/activity/announce.rb
config/webpacker.yml
and then i aborts checkout. How to fix this?

**Comment by JamesABDL** [comment]
Did you make changes to these files?

Can you post the output of `git status` and `git diff`?

**Comment by mahescho** [comment]
I remember a modification of "annonce.rb" to fix the relay issue. I don't remember a modification of webpacker.yml

I think these modification could safely be rolled back. I just don't know how ...

    mastodon@mastrodon:~/live$ git status
    HEAD detached at v2.7.4
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)
    
	modified:   app/lib/activitypub/activity/announce.rb
	modified:   config/webpacker.yml
    
    no changes added to commit (use "git add" and/or "git commit -a")


    mastodon@mastrodon:~/live$ git diff
    diff --git a/app/lib/activitypub/activity/announce.rb b/app/lib/activitypub/activity/announce.rb
    index 9f8ffd9fb..41934650b 100644
    --- a/app/lib/activitypub/activity/announce.rb
    +++ b/app/lib/activitypub/activity/announce.rb
    @@ -47,6 +47,10 @@ class ActivityPub::Activity::Announce < ActivityPub::Activity
         followed_by_local_accounts? || requested_through_relay? || reblog_of_local_status?
       end
     
    +  def requested_through_relay?
    +     super || Relay.find_by(inbox_url: @account.inbox_url)&.enabled?
    +   end
    +
       def reblog_of_local_status?
         status_from_uri(object_uri)&.account&.local?
       end
    diff --git a/config/webpacker.yml b/config/webpacker.yml
    index ea814a0e6..8d8470651 100644
    --- a/config/webpacker.yml
    +++ b/config/webpacker.yml
    @@ -40,10 +40,6 @@ test:
       # Compile test packs to a separate directory
       public_output_path: packs-test
     
    -  # CircleCI precompiles packs prior to running the tests.
    -  # Also avoids race conditions in parallel_tests.
    -  compile: false
    -
     production:
       <<: *default

**Comment by Gargron** [comment]
`git reset --hard HEAD` should do the trick

**Comment by mahescho** [comment]
Fixed the problem. Thanks.
