### ISSUE TITLE
mastodon v2.8.4 image missing on docker hub

### ISSUE THREAD

**Issue by bsod-zombi** [tootsuite/mastodon#10825]
When I tried to upgrade my mastodon instance to v2.8.4 i noticed there is no image tagged as mastodon:v2.8.4 uploaded to docker hub yet. As docker is listed in the Release Notes / Upgrade instuctions I think this is not intended that way.

**Comment by Gargron** [comment]
The build on Docker Hub failed, retrying now

**Comment by Gargron** [comment]
The same build with the "latest" tag succeeded though, so likely a temporary issue of some kind

**Comment by Gargron** [comment]
It built successfully!
