### ISSUE TITLE
Keep lists/headings in sanitizer, or convert to <p>

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#10834]
Semi-related: #8474

Stripping out block-level elements like `ul`, `ol`, `li`, `h1`-`h6`, etc. can cause a breakdown in structure, since their contents will be assumed to be part of one big element and this is incorrect.

### Example remote `content` field:
```
<h1>sample heading</h1>
<p>lorem ipsum dolor sit amet nunquam et titillandus. et qua non si dolorem qui va parfait...</p>
<ul>
<li>item 1</li>
<li>item 2</li>
<li>item 3</li>
```

Current sanitization would result in this:
```
sample heading <p>lorem ipsum dolor sit amet nunquam et titillandus. et qua non si dolorem qui va parfait...</p> item 1 item 2 item 3
```

This results in a noticeable mess when multiple unsupported block-level elements are used in succession, as commonly happens in lists, but can also happen with multiple headings in a row.

![image](https://user-images.githubusercontent.com/10606431/58375064-57c14900-7f10-11e9-9df9-87dc99c6925a.png)

But preserving the elements actually doesn't look wrong, because basics.scss already contains overrides for everything:

![image](https://user-images.githubusercontent.com/10606431/58375012-4deb1600-7f0f-11e9-931e-4a976befc98d.png)

Relevant CSS from basics.scss:
```
a, abbr, acronym, address, applet, article, aside, audio, b, big, blockquote, body, canvas, caption, center, cite, code, dd, del, details, dfn, div, dl, dt, em, embed, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, html, i, iframe, img, ins, kbd, label, legend, li, mark, menu, nav, object, ol, output, p, pre, q, ruby, s, samp, section, small, span, strike, strong, sub, summary, sup, table, tbody, td, tfoot, th, thead, time, tr, tt, u, ul, var, video {
  font: inherit
}
ol, ul {
  list-style: none
}
```

Semantically, it may be undesirable to maintain certain header levels -- I don't know enough about this, but if they are a problem, converting `h1`-`h6` to `p` should look exactly the same, anyway, so there's no *visual* difference whether the element is an `h1` or a `p`.

**Comment by trwnh** [comment]
### Addendum: <pre> vs <code>

This is what `<code><pre>` wrapped looks like:
![image](https://user-images.githubusercontent.com/10606431/58375109-2301c180-7f11-11e9-8c50-0797bf56e98c.png)

This is what only `<code>` looks like:
![image](https://user-images.githubusercontent.com/10606431/58375112-4cbae880-7f11-11e9-9093-a24fc4c08e18.png)

Unless we want to manually parse whitespace and preserve it by inserting `<br/>` where appropriate, the much easier fix is to apply the following CSS:
```
pre {white-space: pre-wrap}
```

**Comment by trwnh** [comment]
### Addendum 2: Completely unsupported elements like `<marquee>`
Converting to `<p>` should work better than completely stripping out the tags.

#### Original
```
<marquee>This is an unsupported marquee tag which is very long and scrolling annoyingly!</marquee>
<marquee>This is another unsupported marquee tag which is very long and scrolling annoyingly!</marquee>
<marquee>This is a third unsupported marquee tag which is very long and scrolling annoyingly!</marquee>
```
![image](https://user-images.githubusercontent.com/10606431/58375182-ffd81180-7f12-11e9-8f02-1cf88683f843.png)

#### Stripped

![image](https://user-images.githubusercontent.com/10606431/58375199-49c0f780-7f13-11e9-9895-b6c466df1dc0.png)

#### Converted to `<p>`

![image](https://user-images.githubusercontent.com/10606431/58375204-7543e200-7f13-11e9-8aad-fa29635da3e4.png)

**Comment by nightpool** [comment]
i'm basically down for this
