### ISSUE TITLE
Unreadable text about Mastodon

### ISSUE THREAD

**Issue by thomaskuntzz** [tootsuite/mastodon#1083]
The text in the bottom right of the window is really unreadable: white text on the white envelope and gray text on gray image.

Also, would be good if we didn't have to scroll to see the whole picture: either cut it or make more room for it.

![capture du 2017-04-06 20-07-18](https://cloud.githubusercontent.com/assets/16361470/24768994/175598ce-1b05-11e7-946d-04d2f68cde18.png)

**Comment by Gargron** [comment]
We are working on an onboarding "getting started" modal instead of this text. The elephant friend will likely be there without the text in the future.

**Comment by wxcafe** [comment]
This also depends on your screen size 
![screenshot from 2017-04-10 20-58-22](https://cloud.githubusercontent.com/assets/3009327/24877692/7787d260-1e30-11e7-8711-ec2f071f0ff1.png)

**Comment by thomaskuntzz** [comment]
Looks like the problem has been solved... Any info on this ?

The image is now bellow the text regardless to the screen size, do you have the same behavior?

![capture du 2017-04-14 12-03-22](https://cloud.githubusercontent.com/assets/16361470/25040552/62c9c9b4-210a-11e7-8966-45f2bd889105.png)

**Comment by Gargron** [comment]
I think this is fixed.
