### ISSUE TITLE
«This translation is currently locked for updates.» since a few days

### ISSUE THREAD

**Issue by ariasuni** [tootsuite/mastodon#10849]
I want to complete French and Esperanto translations but I can’t right now because (at least some) Weblate translations are locked, and this has been like this for more than a few days.

**Comment by ykzts** [comment]
Weblate is temporarily shut down (see #10385). Translators need to do Pull Requests on GitHub.

**Comment by ariasuni** [comment]
Oh, I missed that. Probably should be displayed somewhere on the Weblate.
