### ISSUE TITLE
Simple web interface: scroll from anywhere

### ISSUE THREAD

**Issue by nclm** [tootsuite/mastodon#10840]
The new simple one-column interface is very nice, but after using it a little bit there is one behaviour that I found eventually annoying: scrolling is constrained to the column only. Which means that if my cursor is anywhere on the page but the column, wheeling up and down is not going to do anything.

I can see how this has evolved from the fact that it is adapted from the multi-column interface, but scrolling should probably be rethought for this one, as that behaviour is very unexpected. In other one-column feeds like Twitter, Facebook or Instagram, scrolling happens on the whole page, even if the feed itself is laid out only on a central column.

So either it should be the whole page scrolling, with the left and right parts of the interface as well as the column header being sticky, or scrolling from outside the column should be captured somehow and applied to the column.

**Edit:** By the way, this is not only about wheel scrolling, but also autoscrolling (pressing middle-click then going up and down) and keyboard scrolling (pressing up arrow, down arrow, page up, page down, page start, page end keys). They all don’t work if the cursor is not precisely on the column.

**Comment by Gargron** [comment]
This isn't going to be straightforward especially as all components would have to be updated to listen on window scroll instead of their own scroll, not to mention some design challenges

**Comment by nclm** [comment]
Yes I could well imagine that when typing the issue :/ I do think it is worth looking into at one point though, as it is behaving unlike any interface of that kind.

**Comment by nclm** [comment]
So I have been using the one-column web interface for a little while, and this is still quite annoying. Again and again and again, each time I use Mastodon, I found myself scrolling my mouse but not scrolling the feed. I think it is an important usability issue. The page should scroll whenever the user scrolls, without them having to think too much about where to put the mouse for it to work.

For now, I wrote this very rough but also simple userstyle to have the fullpage scrolling, if it can give an idea of what to look for in order to fix the issue. The only apparent shortcoming with this userstyle is that infinite scrolling is not triggered.

```
.compose-panel,
.navigation-panel {
    position: fixed !important;
}

#mastodon {
    height: auto !important;
}

body {
    background-color: #191b22 !important;
}

.columns-area__panels__main .scrollable {
    overflow-y: initial !important;
}

```

**Comment by Gargron** [comment]
> The only apparent shortcoming with this userstyle is that infinite scrolling is not triggered.

That is exactly why it's complicated to do this. It requires rewriting logic around where scrolls are detected so that it works for both columnized UI and single column UI.

**Comment by nclm** [comment]
Thanks a lot! :)
