### ISSUE TITLE
Don't know how to build task mastodon:confirm_email

### ISSUE THREAD

**Issue by adrianolucas** [tootsuite/mastodon#10858]
I've installed Mastodon (v2.8.4) on Docker using these instructions at [Linode](https://www.linode.com/docs/applications/messaging/install-mastodon-on-ubuntu-1604/#install-docker). All is runnig fine, and I get to the registration page. I then want to approve emails manually using the command:

    $docker-compose run web rails mastodon:confirm_email USER_EMAIL=email@address.com

But the above command comes back with the following error:

    Starting mastodon_db_1 ... done
    Starting mastodon_redis_1 ... done
    rake aborted!
    Don't know how to build task 'mastodon:confirm_email' (See the list of available tasks with `rake --tasks`)
    /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
    /opt/ruby/bin/bundle:23:in `load'
    /opt/ruby/bin/bundle:23:in `<main>'
    (See full trace by running task with --trace)

There is indeed no confirm_email task:

    $ docker-compose run web bundle exec rake --tasks | grep confirm_email
    Starting mastodon_db_1    ... done
    Starting mastodon_redis_1 ... done
    $

Any ideas?

Thank you.

**Comment by nightpool** [comment]
Linode's instructions are 7 months out of date. The correct invocation is
now through the tootctl command. See here:
https://docs.joinmastodon.org/administration/post-installation/ under
"Creating an admin account"

**Comment by ykzts** [comment]
`rails mastodon:confirm_email` has been obsoleted. You should use `tootctl`.

```console
$ ./bin/tootctl modify --email email@address.com --confirm
```

**Comment by adrianolucas** [comment]
For those using Docker, this is how I made a given user (myuser) admin—there may be an easier way, though (Ubuntu 16.04, Mastodon v2.8.4):

    docker~$ docker container ls | grep mastodon_web    CONTAINER ID        IMAGE                       ...
    3545a72ba4f7        tootsuite/mastodon:v2.8.4      ...       mastodon_web_1

    $ docker exec -i -t 3545a72ba4f7 /bin/bash
    mastodon@3545a72ba4f7:~$ 

    mastodon@3545a72ba4f7:~$ RAILS_ENV=production bin/tootctl accounts modify myuser --role admin
    OK
    mastodon@3545a72ba4f7:~$
