### ISSUE TITLE
WebSocket always returns 301 and causes loop

### ISSUE THREAD

**Issue by SuperSandro2000** [tootsuite/mastodon#10850]
### Expected behaviour
It should not return 301

### Actual behaviour
only return one 301 if at all

### Steps to reproduce the problem

Open /web/getting-started

### Specifications

3b9c02506d5046a66ff84b2c787098481a27bda7

Chrome 74

Docker, Traefik reverse proxy, redirect all http traffic to https.

Server log:
````

[47e263d9-d1da-4466-827b-b88ea00c7339] method=GET path=/api/v1/streaming format=html controller=Api::V1::StreamingController action=index status=301 duration=5.22 view=0.00 db=0.90 location=https://mastodon.supersandro.de/api/v1/streaming,
[78fa0daa-c7bb-42c7-871c-3efa2a2cb742] method=GET path=/api/v1/streaming format=html controller=Api::V1::StreamingController action=index status=301 duration=4.97 view=0.00 db=0.86 location=https://mastodon.supersandro.de/api/v1/streaming
````

Browser log:
````
WebSocket connection to 'wss://mastodon.supersandro.de/api/v1/streaming/?stream=user' failed: Error during WebSocket handshake: Unexpected response code: 301
````

**Comment by SuperSandro2000** [comment]
I think I forgot the streaming container. Upsi. There needs to be some doc for this sooner than later.

**Comment by albjeremias** [comment]
@SuperSandro2000 Im trying to setup mastodon with traefik... im a bit lost... I have all my infra running using traefik, but with mastodon using the port 4000 and 3000 just blasts my brain, i don't known how to even think about this... maybe ill just read a bit more about how this could work.. but it seems you already have some hints.

Thanks

**Comment by SuperSandro2000** [comment]
The redis server ip needs to be set to the name of the redis service.
So if you set it to ``mastodon_redis`` in ``docker-composer.yml`` like this
````
services:
  mastodon_redis:
````

You want to connect to ``mastodon_redis``.
Which would result in those config options you wanna set in .env.production
````
REDIS_HOST=mastodon_redis
REDIS_PORT=6379
````

**Comment by renatocron** [comment]
If someone din't get this at first (like me), you should proxy /api/v1/streaming to http://localhost:4000 instead of http://localhost:3000 when using docker.

I think mastodon should return some error instead of 301 when the web get hit, but I don't know the internal
