### ISSUE TITLE
No clear link to our profile

### ISSUE THREAD

**Issue by thomaskuntzz** [tootsuite/mastodon#1086]
There is no clear way to access our profile. The only link I found was the avatar just above the "What's on your mind" text area, but the username just next to it isn't even clickable, which I think would be the minimum. Needs fixing :slightly_frowning_face: 

![capture du 2017-04-06 20-13-01](https://cloud.githubusercontent.com/assets/16361470/24769845/3634e8aa-1b08-11e7-8bf0-acc591dbb8a8.png)

**Comment by jeepfromoil** [comment]
Idem to open user profile page.
![user profile](https://cloud.githubusercontent.com/assets/8667221/24771826/59476a8c-1b0f-11e7-872b-3587975fb038.png)

For some reasons, only the avatar links to the user profile page.

**Comment by thomaskuntzz** [comment]
Can't figure out where the piece of code I have to modify in order to change this is... Can someone help me please? :slightly_smiling_face:

**Comment by ashfurrow** [comment]
This was recently fixed in https://github.com/tootsuite/mastodon/pull/2418 and should be included in the next release of Mastodon. Thanks again for opening issues!
