### ISSUE TITLE
Toot Composer scrolling out of canvas in new simple layout

### ISSUE THREAD

**Issue by LoVicente** [tootsuite/mastodon#10886]
### Expected behaviour

In the multi-column layout, the toot composer grows vertically as one writes and that region of the UI has a vertical scrollbar to account for different screen sizes. This behavior should be replicated in the new simple layout.

### Actual behaviour

This section of the screen is not scrollable and in some screen sizes/zoom levels, the "TOOT!" button can be pushed out of the canvas. In some cases even part of the textarea can be obscured by this. See screenshot:

![image](https://user-images.githubusercontent.com/33736546/58558020-225d7980-81f6-11e9-97e3-f9178641d253.png)

### Steps to reproduce the problem

Easiest way to replicate this is by replying to an already big post and reducing the height of the window. 

### Specifications

On resolutions higher or equal to 1920x1080 this doesn't seem to be replicable at 100% zoom. I took the screenshot at home where I think I have 125% or 150% zoom set system-wide.

**Comment by noellabo** [comment]
https://github.com/tootsuite/mastodon/pull/10917 now scrolls individual UI elements without scrolling the whole. Did this fix resolve the issue?

https://github.com/tootsuite/mastodon/pull/10891 is the solution to scrolling the whole. If you like this, you can try it.

**Comment by LoVicente** [comment]
That works! thanks so much :D
