### ISSUE TITLE
Feature Request: Account Change Notification

### ISSUE THREAD

**Issue by sonololo** [tootsuite/mastodon#1091]
I'll at the moment refer to the https://github.com/tootsuite/mastodon/pull/978 and that's a commendable initiative.

But I think it can be taken further. How about the possibility of making a specific type of notification, that can be sent to all followers, and which is visible in the notifications column, with a button like "Follow On New Instance"?

Made a mockup image:

<img width="347" alt="screen shot 2017-04-07 at 07 04 47" src="https://cloud.githubusercontent.com/assets/2336487/24771213/d2662ba0-1b60-11e7-99ec-34c9552c03c7.png">

I think somewhere in the export settings there should be a button "Notify followers about your move", and after filling in new address, it should throw a notification to followers, that should go into their notification tabs. But it will need the original instance to be up and running, I don't think it will work when the server unexpectedly goes down.

Case for the notification is that a single toot is very easy to miss, and notification is much harder to miss.

I know that by nature of those things you will still lose some followers, but that's better than losing everyone in the move. Dedicated ones will still follow.

Any cons? I suspect that it may be vulnerable or be open to abuse, but I want to hear other opinions.

**Comment by jeepfromoil** [comment]
This seems more about account migration https://github.com/tootsuite/mastodon/issues/177 than toot export.

**Comment by sonololo** [comment]
No idea how I missed 177 then. Probably this issue should be closed then, and the discussion is continued at 177.

**Comment by wxcafe** [comment]
4 days ago - should be closed, closing now ( @sonololo you can close issues you open yourself if you didn't know :) )
