### ISSUE TITLE
Strange behaviour with U+00B7 MIDDLE DOT in hashtags

### ISSUE THREAD

**Issue by marrus-sh** [tootsuite/mastodon#10934]
### Expected behaviour

U+00B7 MIDDLE DOT should either be allowed any number of times in hashtags, or else disallowed completely.

### Actual behaviour

From my [informal tests](https://weirder.earth/@onethousandtwentyfour/102205959763922491), the *first* U+00B7 MIDDLE DOT to be used in a hashtag is included, but later ones are not. I canʼt imagine why this would be intentional; it is extremely confusing for a character to only *sometimes* terminate hashtags. There may be a larger bug with the hashtag detection mechanism not limited to just this character.

(For clarity, if a user enters the text `#one·two·three`, the generated hashtag is `#one·two`, stopping before the second U+00B7 MIDDLE DOT, but including the first.)

### Specifications

The above link is on an older version of Mastodon but I tested on fandom.ink (running 2.8.4) and the behaviour still seems to be present.

**Comment by Gargron** [comment]
The dot is supposed to be allowed in hashtags as long as it's not the first or last character. This sounds like a bug in the regex.
