### ISSUE TITLE
Need defensive measures against Unicode direction overrides

### ISSUE THREAD

**Issue by zackw** [tootsuite/mastodon#1095]
If you put U+202E RIGHT-TO-LEFT OVERRIDE in your display name, the effects spill out of the display name field and affect other parts of the UI, as shown here:

![screen shot of the bug described above](https://cloud.githubusercontent.com/assets/325899/24771864/3c9c0ba4-1add-11e7-95bf-d44911961005.png)

There are probably a bunch of other closely-related bugs.

(Inspired by a similar bug in Twitter found by [@0xabad1dea](https://twitter.com/0xabad1dea).)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
IMO this is not a bug, it's (at worse) funny. I've marked it enhancement for now (because the @ name should not be reversed, at least), feel free to say if you think it should considered a bug.

**Comment by zackw** [comment]
I do think this is a bug.  Not the simple case I showed, and not necessarily with the display name, but I strongly suspect there are much worse things you can do with unusual Unicode constructs.  Please research the history of UI breaks with untrusted Unicode.

**Comment by Elizafox** [comment]
The fact this is considered a feature and not a bug is worrying. It shows injection vulnerabilities aren't taken seriously in the name of "comedy."

I for one do not find **that** very funny.

**Comment by wxcafe** [comment]
... this is not an injection? It's a perfectly valid Unicode character that does what it's supposed to do and has no harmful repercussions on the users?

**Comment by awilfox** [comment]
Directional overrides are necessary for some names.  That is definitely something that should never be filtered.

Simple fuzzing with Unicode strings (valid and invalid) should be all that is necessary to prove there is either a security bug or no bug.  I suggest putting that in the test suite.

**Comment by zackw** [comment]
Directional overrides should not be filtered, but they should be contained.  For instance, a directional override within the display name should not be able to change the presentation of anything _other_ than the display name.

**Comment by wxcafe** [comment]
is it really that big a problem?

**Comment by zackw** [comment]
The specific test case I presented may not appear to be a big problem, but if you look into the history of this kind of bug, and consider _all_ of the Unicode characters with nonlocal effects and _all_ of the contexts where user-submitted arbitrary Unicode can appear within Mastodon's UI, you will realize that this is indeed a significant problem.

**Comment by gandaro** [comment]
This can be fixed by surrounding user-provided text by [`<bdi>` tags](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-bdi-element), like this:

    <bdi>&#x202E;Feli</bdi> says “hello”.

or specifying the [`dir` attribute](https://html.spec.whatwg.org/multipage/dom.html#the-dir-attribute):

    <span dir="auto">&#x202E;Feli</span> says “hello”.
