### ISSUE TITLE
ActivityPub 'Announce' sometimes not displayed correctly as 'Boost'

### ISSUE THREAD

**Issue by vitalyster** [tootsuite/mastodon#10950]
I'm sending something like this:
```json
{"type":"Announce","id":"https://domain.tld/n/2944171-0#top","actor":"https://domain.tld/u/announcer","object":{"id":"https://domain.tld/n/2944171-0","published":"2019-06-04T07:51:33.779855Z","url":"https://domain.tld/m/2944171","to":["https://www.w3.org/ns/activitystreams#Public"],"content":"<p>text</p>","attributedTo":"https://domain.tld/u/poster","cc":["https://domain.tld/u/poster/followers/toc"],"type":"Note"},"type":"Announce","@context":["https://www.w3.org/ns/activitystreams","https://w3id.org/security/v1",{"Hashtag":"as:Hashtag"}]}
```

### Expected behaviour

It should be displayed as "@announcer boosted message (@poster@domain.tld: Text)"

### Actual behaviour

Sometimes it displayed correctly (I think its when @poster is already known to mastodon instance), sometimes it displayed as @announcer's(!) post, sometimes it displayed as "@announcer boosted @announcer's(!) post"

### Specifications

I'm discovering my @announcer on mastodon.social instance, both poster and announcer are from another ActivityPub service.

**Comment by ThibG** [comment]
What is this other ActivityPub service? It seems like this could happen if the announced object is inlined and lacks an `attributedTo` attribute, which is not the case of the AP snippet you posted.

I'm not sure whether we should assume a boosted status is from the booster when no `attributedTo` attribute is present… but when that's the case, we can't attribute it at all.
