### ISSUE TITLE
French translation : change "Pouet" to another word ?

### ISSUE THREAD

**Issue by 0gust1** [tootsuite/mastodon#1099]
Hi, thanks for mastodon and all the great work here.

In english "toot" have not the same semantic field as the french translation ("pouet").

In french "pouet" is not a verb nor a noun, but an onomatopeia, expressing a trumpet / honk sound or a fart (even if farting has his own "prout"). It's somewhat awkward and less valorising than "toot".

I see 3 scenarii : 

* It's a non issue, a too difficult one or an already debated idea
* use "toot" as is
* use another word / verb

I asked for ideas / proposal on mastodon.social : 
https://mastodon.social/@0gust1/1809558 ...for now, we have a majority of farting-related suggestions... :rofl: 

What do you think ?

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mkody** [comment]
It's like the "pain au chocolat" and "chocolatine" debate all over again. People doesn't know if we should say "toot" or "pouet".

"pouet" is a fun word, but it gets confusing to have both of them. I'd suggest that we use "toot", like we keep saying "post" and "tweet" in many other places.

**Comment by wxcafe** [comment]
Since this is pretty easy to change per-instance, I'm personally voting that this is a non-issue.

**Comment by 0gust1** [comment]
@mkody : Agree. It's not an easy subject. Could lead to endless debates ^^. But it's important too.

@wxcafe : I was writing exactly that "Maybe make this configurable or overridable" :)

So, it seems to be overridable per-instance (I guess by editing or dropping a file in the right dir). Would be nice to make this more obvious.

**Comment by wxcafe** [comment]
It is, it’s just `sed`-ing a few files. I think it would be nice, but as @gargron said, admin tools were not a priority when there were only a few instances, and they’re being worked on now.

**Comment by mattjmattj** [comment]
I think pouet is getting adopted by more and more french users. Mastodon users are often even called pouettos, which is kind of fun too

**Comment by mickaelftw** [comment]
Please, keep pouet.

_- Sincerely Yours, Pouet.me_

**Comment by monnoliv** [comment]
Yes leave Pouet

**Comment by Gargron** [comment]
I don't know if this is valid french but pouet offers you merde-pouetre for "shitposting"

Anyway, this has been introduced a long time ago by @nclm and I am rather fond of it.

**Comment by tiesselune** [comment]
I must admit, pouet is cool, because it's ridiculous. Let's keep it. Let the media write articles about people going crazy in their pouets. Let people say "Haven't you seen my pouet?" or "My pouet is trending". This is great. It is.

**Comment by nclm** [comment]
Hi!

First, to give credit where it’s due, [“pouet” is @Pierrec’s idea](https://mastodon.social/@Pierrec/141973). 🙂 

Otherwise, I don’t really have an opinion on it without any alternatives besides using the original (which I would find a pity: if there’s any way to translate it, we might as well translating it). “Pouet” is actually a nicely fitting rendition of “Toot” at the end: slightly more informal maybe, but less not start to consider “Toot” as totally neutral either (I mean, [its informal usages](https://en.wiktionary.org/wiki/toot) are not particularly classier than its French counterpart). 🙄 Back in November when status started to be called toots and the “Post” button eventually became “Toot”, I think it was mostly because that was fun!

Also, since “Pouet” started to be adopted, it may be too late. But let’s keep our options open, any other ideas?

Indeed, an easy to set overriding (all languages?) setting for instances’ administrators could be a nice move, and would contribute to give each server its own identity.

**Comment by brucelane** [comment]
and fediverse sounds like fait divers in french!

**Comment by nclm** [comment]
Indeed! `toutdesuite.social` et `faitsdive.rs` would make nice francophone instances names.

**Comment by ariasuni** [comment]
It seems to me that «toot» is the English equivalent of «tut» (klaxon sound). It’s close from toot and there’s good jokes with it (for example, «tut tut les rageux» which is already a meme). It’s still funny but looks less silly in my opinion.

**Comment by brucelane** [comment]
I agree with @ariasuni  "tut" is less silly than "pouet", I would prefer... 
Quite near 'toot' and 'tweet', also.

**Comment by nclm** [comment]
« tut » makes sense indeed.

Some considerations :
* Is it recognisable in its written form? It sort of can be took for the verb « taire », and pronounced « tu ». Maybe it has an alternative spelling with diacritics (like « pouet » has): I could imagine « tût » or even « tüt », and append it with an exclamation mark, so it's clear that it's meant to be the onomatopoeia. 
* Is it ever used single, doesn't it come always by pair « tut-tut ! »?
* It's a car horn sound. It's not meant to be a pleasant sound, and is a bit agressive to send to someone. « pouet » might sound more harmless.

I'm just thinking out loud (well, not exactly out loud since I'm typing) so we don't miss any thing if we go in any other direction.

**Comment by trebmuh** [comment]
I think that "pouet" is fine and is understandable by pretty much every French speaker (even my grandma) while "tut" is an insider thing which will lowers the public able to get it right away. I'd advocate to stick with "pouet" unless one want to reduce the range of people mastodon is trying to get.

**Comment by ariasuni** [comment]
> Is it recognisable in its written form?

It’s probably as understandable as toot in English I guess. To be honest, pouet doesn’t mean anything to me except to tell I touch something (so I understand it on a button, but find it very weird to name the messages). Also, pouet seems instant, while tut can be very short or a bit longer, like the toots in Mastodon.

> Is it ever used single

Less frequently than pouet (which is often written twice too), but the meaning is obvious if it’s followed by an exclamation mark. Alternatively, the text on the button can be «tut-tut» and the message can be named a tut, maybe?

> It's a car horn sound

So is toot, right? Also, «tut» can stand for any klaxon (which includes nicer sound than car’s one).

> I think that "pouet" is fine and is understandable by pretty much every French speaker (even my grandma) while "tut" is an insider thing which will lowers the public able to get it right away.

I think it’s the contrary. Tut is not an insider thing — I think both are understandable. I also think tut is much less ridiculous while not being totally serious.

**Comment by monnoliv** [comment]
D'abord pourquoi parler en anglais alors que le sujet ici est Pouet, 
soit la traduction en Français de toot.

Pour ma part, je trouve que pouet est bien dans l'esprit du libre (open 
source), un rien d'autodérision.

**Comment by ariasuni** [comment]
Je comprends que certain·e·s préfèrent pouet, mais tut est également «rigolo». Quant à l’esprit du libre ou de l’Open Source (qui n’ont finalement pas grand chose à voir dans l’esprit justement), on s’en moque un peu. C’est plutôt la fidélité par rapport à la traduction originale ou l’intérêt pour Mastodon qui nous intéresse, non?

P.-S.: si tu pouvais faire disparaitre mon nom/prénom de ton commentaire, en fait je préfère que ça soit pas trouvable facilement sur le web.

**Comment by mkody** [comment]
Je me disais hier qu'OK, on aurait pu rester sur _pouet_, mais voilà que _tut_ arrive. :grin:   
Changer vers autre chose maintenant provoquera très probablement de la confusion et un mécontentement. Donc si on ne veux pas utiliser le même mot qu'en anglais (comme les autres langues (sauf le finlandais)), _pouet_ va donc très probablement rester.

( @ariasuni : Ton nom/prénom est dans ton profil GitHub, il sera forcément en ligne et partagé avec tout le monde )

**Comment by trebmuh** [comment]
@ariasuni : nous avons compris ta préférence à propos de pouet/tut. Tu n'es donc pas obligée de le répeter à chaque fois que quelqu'un fait mention de sa préférence au risque de pourrir ton point de vue en étant un peu trop insistante. Merci.

Pour ce qui est de ton nom/prénom, @monnoliv a répondu par courriel (d'où la petite icône à côté de son blaze), et l'inscription de ton nom/prénom a donc été faite automatiquement par l'interface github qui s'est renseigné par ton profil github.

**Comment by ariasuni** [comment]
C'était un réglage que j'avais fait y a longtemps, et j'ai pris soin de l'enlever de mon profil Github avant de publier mon commentaire…

Pour le reste, dire «pouet c'est rigolo» comme argument, ça sous-entends que tut ne l'est pas, je réagissais uniquement à ça.

Bref j'ai rien d'autre à dire sur le sujet à priori, donc je vous laisse décider. :)

**Comment by brucelane** [comment]
vaut mieux changer tant que c'est le début, non?
personnellement, je compte créer mon propre serveur mastodon et d'une manière ou d'une autre je mettrai "tut", pour son côté fun sans être un peu ridicule comme pouet.

**Comment by nclm** [comment]
@ariasuni : je viens d’éditer le message de monnoliv pour y retirer ton nom 😉 

Sinon, pour ajouter au débat, il y a une question d’usage établi : comment les utilisateurs actuels appellent les statuts et le fait d’en poster. Pouet ? Toot ? Tut ? Qu’est-ce qui prévaut actuellement ? Quelque soit la décision, il ne faudrait pas trop bouleverser les habitudes sur les instances actuelles les plus populaires (aucun problème pour de nouvelles instances ou certains plus confidentielles). Dans la presse, j’ai l’impression qu’on est équilibré entre les deux premiers (donc traduction en l’état et VO).

Aussi, on ne devrait peut-être pas en discuter tant ici que sur le réseau lui-même non ? On pourrait (re)lancer la discussion avec un plus grand nombre de mastonautes et organiser une prise de décision dans genre une semaine, sous forme de vote ?

**Comment by turb** [comment]
Mes deux centimes :

"poulet : (Désuet) Billet doux." cf. https://fr.wiktionary.org/wiki/poulet

**Comment by nd-** [comment]
C'est libre, ça permet de râler, je propose Poutoot.

![Poutoot](https://media.giphy.com/media/vCiYd6kLaP7Ec/giphy.gif)

**Comment by StefOfficiel** [comment]
> Mastodon users are often even called pouettos, which is kind of fun too

Je trouve ça tellement dégradant...

**Comment by StefOfficiel** [comment]
Excusez-moi, je vais venir aussi faire mon râleur, mais _"Pouet"_ c'est ridicule, et je trouve que _"Tut"_ l'est aussi.
Lorsque je parle avec des amis de Mastodon (et je dis Mastodon, et pas mastodonte ou éléphant ou pachyderme...) je vais dire _"J'ai posté tel ou tel truc"_, sauf que _"poster"_ quelque chose est impersonnel, ce n'est pas pour rien que les termes _"Un Tweet"_ et _"Tweeter quelque chose"_ sont apparus avec Twitter.

**Si vous voulez que Mastodon continue à avancer et prendre de l'ampleur, il faut éviter de se ridiculiser.**

Il est clairement impossible de dire en Français : 
_"J'ai Poueté une blague sur Mastodon, j'ai eu beaucoup de partage !"_...
_"T'a pas vu mon Pouet sur Mastodon ?"_...

_"J'ai Tuté une blague sur Mastodon, j'ai eu beaucoup de partage !"_
_"T'a pas vu mon Tut sur Mastodon ?"_
hum... Pas top je trouve. (Tuté = sucé)...

_"Toot"_ c'est le terme d'origine, c'est un peu bizarre à prononcer (comme _"tweeter"_ au début), mais ça passe.

_"J'ai Tooter une blague sur Mastodon, j'ai eu beaucoup de partage !"_
_"T'a pas vu mon Toot sur Mastodon ?"_

Si ça n'avait tenu qu'à moi, j'aurai utilisé le terme _"Twoot"_ : 

_"J'ai Twooter une blague sur Mastodon, j'ai eu beaucoup de partage !"_
_"T'a pas vu mon Twoot sur Mastodon ?"_

Sinon, restons neutre et habituel, _"Poster"_ ou _"Publier"_ !

**Comment by Naouak** [comment]
@StefOfficiel "Tweet" est tout aussi ridicule que "Pouet" ou "Tut". La seule différence, c'est que le premier est entré dans les moeurs à force d'usage.

**Comment by zoski** [comment]
English bellow French
Je ne sais pas si le but de cette _issue_ est de trouver un consensus sur le mot que les francophone devraient utiliser pour désigner un _toot_ dans la langue de molière. Si c'est le cas il faudrait peut être joindre le plus de francophone afin de récolter les avis du plus grand nombre.

Si ce n'est pas le but de cette conversation, il est facile de changer le _toot_ ou _pouet_ qui s'affiche sur votre instance par un mot de votre choix. Et nous devrions fermer ce "bug".

I don't know if the goal of this issue is to agree about a replacing word for the French people to use in place of toot. If so, we should open the discussion to more francophone people, to have more proposition and in the end get new word fitting to the most of us.

If it's not the aim here, it's quite easy to change _toot_ by something else on your instance. And we should ask this issue to be closed.

**Comment by wxcafe** [comment]
Imo "pouet" has already been accepted by the vast majority of users. I agree that keeping toot would have been better, but as with many things, this is the world we have to live in now. I'm in favor of keeping things like this and letting individual instance owners change the text as they see fit (as @Aldarone of witches.town did by changing it to "Jinx" in english and "Maudire" in french (I think?))

**Comment by tbouron** [comment]
I figure I would comment on this one: I'm partisan to keep `Toot` for all languages. As other comments above said, sentences like: "Tu as vu mon tweet ce matin?" or "Attends, je vais tweeter un truc" are now the norm in French so why the hell not doing the same thing for Mastodon and toot?

**Comment by StefOfficiel** [comment]
@Naouak "Tweet" tout comme "Toot" ne veut rien dire en Français, contrairement aux "Pouet" et "Tut"...

**Comment by nclm** [comment]
Ok, pour élargir nos avis je vous propose quelque chose. On relance la conversation sur Mastodon et on fait un sondage d’une semaine avec les trois propositions et la possibilité d’en proposer d’autres. Au décompte, si un grand favori se dégage, il est intégré comme traduction.

J’ai monté une première version du sondage là : **https://nclm.typeform.com/to/gvA3wQ**

Si vous voulez changer quoi que ce soit dans le texte ou la forme dites-moi, et dès que c’est prêt on peut partager.

**Comment by mkody** [comment]
Hmm, ça me semble bon si ce n'est qu'il faudra bien évidemment mettre une meilleure date de fin.  
(J'ai aussi accidentellement envoyé le formulaire blanc, my bad.)

Je serai d'accord de faire relayer le sondage avec les autres instances.

**Comment by nclm** [comment]
(mince en effet, j’ai mal regardé mon calendrier)

**Comment by trebmuh** [comment]
"il se peut qu’il officiale" -> "il se peut qu’il officialise"

"d’autant de mastonautes francophones possible" -> "d’autant de mastonautes francophones que possible"

**Comment by nclm** [comment]
Merci, j’ai corrigé :)

**Comment by mkody** [comment]
Est-ce donc bon pour envoyer ?

**Comment by nclm** [comment]
@tous : D’autres commentaires ? Ok pour le principe d’un vote ?

**Comment by mkody** [comment]
Je pense qu'on est bon pour partager le lien du questionnaire et voir les avis des utilisateurs⋅trices !

**Comment by brucelane** [comment]
ok pour un vote

**Comment by nclm** [comment]
Bon, c’est parti alors :)

**Comment by thomaskuntzz** [comment]
Je pense que le mieux est de choisir entre pouet et toot par défaut (personnellement je préfère toot) et de permettre AUX UTILISATEURS de changer ça dans les paramètres.

Ça à l'air d'être un débat très personnel, c'est pourquoi je suggère que le choix final soit laissé aux utilisateurs :slightly_smiling_face:

**Comment by my-Planet** [comment]
A la place de "pouet" je propose le mot "Corner" : Sonner, faire entendre une corne, un klaxon...
Il propose aussi une homophonie avec "Cornac" ou mahout, est à la fois le maître, le guide et le soigneur de l'éléphant.

**Comment by mkody** [comment]
> permettre AUX UTILISATEURS de changer ça dans les paramètres

Donc inclure une fonctionnalité dans Mastodon juste parce que les francophones n'arrivent pas à se mettre d'accord ? Non, je ne pense pas, ça sera à l'admin de l'instance de choisir dans ce cas.

**Comment by thomaskuntzz** [comment]
@my-Planet La seule chose à laquelle me fait penser "corner", c'est... un [corner](https://fr.wikipedia.org/wiki/Loi_17_du_football) (bien que je ne joue jamais au football)... D'ailleurs, je ne connaissais ni l’existence du verbe "corner" ni du nom "cornac" (bien que je sois français résidant en France ayant le français pour langue maternelle)... :sweat_smile:

Je pense que c'est une mauvaise idée : seulement une infime partie des gens comprendront de quoi il s'agit, et après il faut encore faire le lien avec la réelle fonction du bouton : envoyer le message. Et ni l'un ni l'autre ne sont chose aisée... Ça n'en reste pas moins bien trouvé :wink:

**Comment by thomaskuntzz** [comment]
@mkody Mouais, vous avez peut-être raison... Mais cela ne signifie-t-il pas ajouter une option dans l'interface d'admin de Mastodon (si une telle chose existe) ?

**Comment by thomaskuntzz** [comment]
Sinon, mon avis reste similaire à celui exprimé dans ce commentaire :
> I figure I would comment on this one: I'm partisan to keep Toot for all languages. As other comments above said, sentences like: "Tu as vu mon tweet ce matin?" or "Attends, je vais tweeter un truc" are now the norm in French **so why the hell not doing the same thing for Mastodon and toot**?

**Comment by mkody** [comment]
@thomaskuntzz 
> Mais cela ne signifie-t-il pas ajouter une option dans l'interface d'admin de Mastodon (si une telle chose existe) ?

Nope, on modifie tout simplement les fichiers de langue. Certaines instances ont changé le vocabulaire pour qu'il s'accorde au thème de l'instance (par exemples des termes en rapport aux sorcières ou à l'espace).

**Comment by Angristan** [comment]
> Sinon, mon avis reste similaire à celui exprimé dans ce commentaire

Totalement d'accord. La plupart d'entre nous disent déjà "toot" de toute façon.

**Comment by Cassolotl** [comment]
> In english "toot" have not the same semantic field as the french translation ("pouet").
> 
> In french "pouet" is not a verb nor a noun, but an onomatopeia, expressing a trumpet / honk sound or a fart (even if farting has his own "prout"). It's somewhat awkward and less valorising than "toot".

I am English and have no strong feelings re: pouet, but I just thought I'd chip in and say that "toot" *is* onomatopoeia in English. It's also a word for fart.

Since there are discussions about whether the word "toot" is appropriate in English Mastodon for all the same reasons, I think this is probably an *excellent* translation.

**Comment by chtixof** [comment]
C'est une question **très** importante. Mal nommer les choses, c'est ajouter au malheur du monde.
**J'aime bien "Pouët"** (avec un tréma sur le e, c'est possible ?).
Çà souligne la singularité du français qui nous a fait aussi utiliser le mot "ordinateur" plutôt que "calculateur".
Et plutôt que "re-pouët", je préfèrerais "pouët-pouët". Mais là, je chipote.
Sur ce, je m'en vais pouëter le débat dans le fediverse.

**Comment by monnoliv** [comment]
+1

**Comment by nclm** [comment]
Les résultats du vote :

> 296 réponses
>
> Note moyenne pour **« Toot » : 2.29**
> (152⋅⋅⋅/79⋅⋅/65⋅) 
>
> Note moyenne pour **« Pouet » : 2.11**
> (138⋅⋅⋅/54⋅⋅/104⋅) 
>
> Note moyenne pour **« Tut » : 1.32**
> (21⋅⋅⋅/54⋅⋅/221⋅) 

Et les contenus éventuels du champs personnalisé :

```
"Tooêt"
BARRIR / BARRISSEMENT
Bip
Bip
Burp
C'est à voir en fonction de la traduction. Quand Mastodon est en français, c'est écrit "pouet", en Anglais comme dans d'autres langues, c'est "toot"
dire
Dzoing
Envoyer
Goldorak Go
hop!
j'aime bien pouet mais je trouve que c'est mieux si c'est le même terme en anglais, je favorise donc toot, tooter, tootter… 
Message 
meuh
Miaou
moot
Non
Non
NON.
NOOT (comme le cris de pingu xD)
nope
plop
Plop
plop
Plop
poot
Pouët
Pouët (avec un tréma)
POUET POUET
Pouin
Pouit
Poutoot
prout
Prout
Prout
psst !
Publier
Publier
publier 
Publier ou Poster
Pwet
Pwet
pwet
Pwouât
Todon
Tooot
Toot en anglais, Pouet en français.
TOOT FTW
TOOT JUSTE TOOT, SCROGNEUGNEU
Touite
Touter
Treet
tut tut
tutute 
Tûût
utiliser de base Pouet mais intégrer une option pour que les admins d'instances puissent facilement changer ça à leur guise
Virtualisation !
whisper => Chuchoter
Yep
```

**Comment by franck-paul** [comment]
un babil, des babils, babiller et babillage pour l'enfilade de babils ?

**Comment by Kozlika** [comment]
Je plaide pour "toot" dans toutes les langues en tant que terme "officiel" (hors personnalisations d'instance). Il me semble préférable d'utiliser un terme… fédérateur, internationalisé. Je pense que ça facilite les échanges hors Mastodon.

**Comment by Monolecte** [comment]
I love "pouet"!
Please, keep the "pouet"

**Comment by Yharra** [comment]
Il est probable que le "pouet" vaincra car il est plus hédonique, ludique et donc mémorable. Il serait d'ailleurs préférable de le garder pour améliorer l'expérience utilisateur.

L'usage vaincra !

**Comment by Gargron** [comment]
I think the conclusion is we're keeping the pouet. 😂
