### ISSUE TITLE
Emojis custom categories

### ISSUE THREAD

**Issue by Miaourt** [tootsuite/mastodon#11009]
![image](https://user-images.githubusercontent.com/1571367/59159694-df40b780-8acd-11e9-9c18-302b8d1a5a56.png)
The custom category is used for all emojis servers adds, it quite become to be a mess when you start having a lot of them.

I suggest having the ability to give each emojos categories :

- [ ] Custom categories
- [ ] Sort custom categories the way we want
- [ ] Ability to add an emoji to a "real" category (Can be useful to add, for example, pride flags to the "flag" category)

**Comment by Phroneris** [comment]
This and my #7940 may be duplicates, but I'm glad to see my comrade.

---

By the way, you should use bulleted lists to display multiple things simply instead of task lists.

```
- cat
- dog
- bull
```

- cat
- dog
- bull

**Comment by Miaourt** [comment]
I did checkboxes because it's quite easier to update when stuff are done :)

Oh, searched trough the issues and didn't found it, it is possible for you to add my last suggestion in addition to your issue ?

**Comment by Phroneris** [comment]
Makes some sense.
Then it's up to mastodon's issue policy.

---

> it is possible for you to add my last suggestion in addition to your issue ?

OK. Let's unify them.
Make sure you declare this issue number (#11009) in your new comment on my issue.
