### ISSUE TITLE
Failed to  use streaming/user using js

### ISSUE THREAD

**Issue by dru18** [tootsuite/mastodon#11022]
I'm trying to use GET /api/v1/streaming/user

but Failed to  use streaming/user using js

### Expected behaviour

that should have Return events that are relevant to the authorized user, i.e. home timeline and notifications to me

### Actual behaviour

but gave me this error after 5 seconds of hold
https://github.com/dru18/druBot/blob/master/screenshot/error_streaming_user.png
### Steps to reproduce the problem

i'm using this code to get steaming/user
https://github.com/dru18/druBot/blob/master/druStream.js
### Specifications

i'm using
OS: Mint 18.3 sylvia

**Comment by nightpool** [comment]
it looks like this is an error in the `mastodon-api` node package, by vanita5: https://github.com/vanita5/mastodon-api

this package doesn't have anything to do with mastodon and it's not maintained by us, so I would suggest filing an issue with the author of the package

**Comment by dru18** [comment]
thanks for the suggestion
