### ISSUE TITLE
Please add my Android Mastodon client to the list!

### ISSUE THREAD

**Issue by FlorentAnders** [tootsuite/mastodon#1105]
Hi!

Please add my own Mastodon client Sera for Android to the list! Here is its Google Play page:
http://play.google.com/store/apps/details?id=com.fa.sera

Thanks!
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by AshKyd** [comment]
Hi Florent,

I had a look at your app with a test account, but I'm concerned it seems to be a clone of Tusky with advertising added.

1. What benefit does this app give users over Tusky, which has no ads? Why is this a good candidate for this list?
2. Having based this app off Tusky, you must [comply with the terms of the GPL by releasing the source code](https://github.com/Vavassor/Tusky/blob/master/LICENSE.txt). Is this available somewhere for us to audit?
3. To make it easier on the developer, you should [submit a pull request to this list yourself](https://github.com/tootsuite/mastodon/blob/master/docs/Using-Mastodon/Apps.md) and reference this issue.

**Comment by grawlinson** [comment]
This person has ripped off [Twidere](https://github.com/TwidereProject/Twidere-Android) with his own clone called [Spreadsheet](https://play.google.com/store/apps/details?id=com.fa.spreadsheet).

While [this upstream issue](https://github.com/TwidereProject/Twidere-iOS/issues/2) opened by @FlorentAnders is not definite proof, I would consider it a severe breach of the GPLv3 that there is no source available.

I assume that his other applications, no doubt available on Google Play store, are also unethical clones. Therefore I would not recommend accepting this application.

**Comment by mariotaku** [comment]
@grawlinson I've submitted a takedown notice via https://support.google.com/legal/contact/lr_dmca?&product=googleplay wish this could help.

**Comment by Vavassor** [comment]
I've also submitted a takedown. It's very transparently a modified copy of the code and they've neither provided their source nor distributed the license & attribution, so they're in violation of the terms.

**Comment by FlorentAnders** [comment]
I have just took down both apps for myself.

**Comment by FlorentAnders** [comment]
I did not know that I had to publish the source code after GPLv3, what I intended with both of those apps was to optimize the experience given by the app by modifying their look and feel in a way that felt more compelling to me. I have now published updates to both apps that stop the access, unpublished them, emptied their Play Store descriptions to the best I could and stopped ad serving on both. Please accept my sincere excuse.

**Comment by wxcafe** [comment]
Since this seems resolved, I'm closing this issue
