### ISSUE TITLE
Error 500 for special characters 

### ISSUE THREAD

**Issue by valinux** [tootsuite/mastodon#11058]
### Expected behaviour

I should be allowed to write “i’m” Or add special characters 
### Actual behaviour

I get error page returned 500
### Steps to reproduce the problem

Write English properly 
### Specifications

Latest version

Ubuntu 16.04

I think it is something to do with Postgres ? My language is en_us 

I need help figuring out if it’s a missing node environment or if it’s Postgres whose not understanding English right

**Comment by nightpool** [comment]
I can't reproduce this on master, I'm guessing it's a problem in your individual installation, not mastodon. here's a similar issue someone else ran into that might help: https://discourse.joinmastodon.org/t/during-setup-error-new-encoding-utf8-is-incompatible-with-the-encoding-of-the-template-database-sql-ascii/1987/3

we don't do troubleshooting on GitHub, if you need more help debugging or getting your server set up, I recommend asking on mastodon, irc, or our [discourse support forums](https://discourse.joinmastodon.com)

**Comment by nightpool** [comment]
I can't reproduce this on master, I'm guessing it's a problem in your individual installation, not mastodon. here's a similar issue someone else ran into that might help: https://discourse.joinmastodon.org/t/during-setup-error-new-encoding-utf8-is-incompatible-with-the-encoding-of-the-template-database-sql-ascii/1987/3

we don't do troubleshooting on GitHub, if you need more help debugging or getting your server set up, I recommend asking on mastodon, irc, or our [discourse support forums](https://discourse.joinmastodon.com)
