### ISSUE TITLE
Error 500 when uploading everything

### ISSUE THREAD

**Issue by raphgilles** [tootsuite/mastodon#11055]
Hello,

After upgrading to the 2.8.4 all my images was broken (avatars, headers, posts, emojis...) I decided to re-upload them.

But now, I can't upload anything because of an error 500.

I tried `sudo chown -R 991:991 public/system` but changed nothing.

Now I don't know how to fix that. Have you an idea ? Thanks :)

**Comment by raphgilles** [comment]
Ok. After one week, that's when I decide to post that I found the solution here : https://discourse.joinmastodon.org/t/error-500-while-uploading-pictures/1647

`chown -R mastodon:mastodon public/assets public/packs public/system`

**Comment by silvyn** [comment]
Thank you !
In my case I had to figure out to be root before apply this, so if someone is like me : 

`docker exec -it -u root containerID bash`
