### ISSUE TITLE
About page error

### ISSUE THREAD

**Issue by salvadorpla** [tootsuite/mastodon#11071]
### Expected behaviour

After a Logout, when clicking over Mastodon logo it must show about page.

### Actual behaviour

It shows error page.

### Steps to reproduce the problem

Log out of current session and click on the Mastodon logo

### Specifications

v2.9.0rc2

Using Opera 60.0.3255.160 on MacOS 10.13.6. Same issue using Firefox 67.0.2

**Comment by salvadorpla** [comment]
Seems this piece of the web.service logo can be useful:

jun 13 12:27:51 bundle[23572]: [c7a6275c-f5e2-40c6-8c5d-8f034b73e9f1] method=GET path=/ format=html controller=HomeController action=index status=302 duration=1.40 view=0.00 db=0.11 location=https://motogp.space/about
jun 13 12:27:51 bundle[23572]: [5b315ac4-f2f1-4320-ba0d-9ba22f74b23b] method=GET path=/about format=html controller=AboutController action=show status=500 error='ActionView::Template::Error: PG::UndefinedColumn: ERROR:  column accounts.suspended does not exist

**Comment by Gargron** [comment]
tootctl cache clear

**Comment by salvadorpla** [comment]
Yes!, Thanks @Gargron.
