### ISSUE TITLE
Add a meaningful message on the search results when the functionnality is disabled

### ISSUE THREAD

**Issue by DarckCrystale** [tootsuite/mastodon#11082]
### Pitch

Currently, admins can disable the search in toots and just keep the users/hashtags search.
If in the instance, the search feature is disabled, when a user looks for a word, the results list shows a message "0 results"
![a screenshot of the results column](https://user-images.githubusercontent.com/13867472/59503816-ab84d980-8ea1-11e9-8b70-3673bccb6ce2.png)

I suggest that with this message, in the column, another message warns the user that the search tool is disabled:
![a screenshot showing a message "The search in toots content is disabled by your administrator." below the results found count](https://user-images.githubusercontent.com/13867472/59504434-3d411680-8ea3-11e9-8231-09a5593e6519.png)

```html
<header class="search-results__header">
    <span aria-hidden="true" class="icon fa fa-search"></span><span>0 results</span>
    <br>
    <span style="font-style:italic;margin-top:5px;display:inline-block; font-size:12px">
        <span class="icon fa fa-info"></span>The search in toots content is disabled by your administrator.
    </span>
</header>
```

### Motivation

The fact that this is not explained is a problem because the user needs to ask to the admin why the search doesn't work to know why. Today I had to ask but it can be the same with everyone.

It's always a good thing to explain to the end user why something doesn't work, especially when it's a normal behavior of the app.

**Comment by igalic** [comment]
`s/research/search/g`

Those are words are [False friends](https://en.wikipedia.org/wiki/False_friend) between English & Frend.

**Comment by DarckCrystale** [comment]
Fixed thx
