### ISSUE TITLE
Responsive gui switching

### ISSUE THREAD

**Issue by epsilon-phase** [tootsuite/mastodon#11097]
### Pitch

So, the single column mode is nice. So is the multicolumn mode. Why can't it be easy to switch between them?

### Motivation

Sometimes I have to go half-window on my webbrowser to fit all my activities in a an acceptable space, but one doesn't naturally transition to the other. If it did, or optinally did, then it would make it far easier to use in these situations where screen-space is critical.

I think that people with too few screens/too small screens and too much on their plate would benefit significantly.

**Comment by Gargron** [comment]
The multicolumn mode transitions to the single-column mode on small screens (mobile layout)
