### ISSUE TITLE
Empty Timeline

### ISSUE THREAD

**Issue by olliware** [tootsuite/mastodon#11110]
Hey everyone,

after switching / upgrading to 2.9.0 everything went fine until today. This evening I realized that all the toots of the people I follow have been disappeared and therefore my timeline is empty. "Load more" doesn't affect this strange behaviour at all!

![Bildschirmfoto 2019-06-17 um 21 56 22](https://user-images.githubusercontent.com/42076599/59632610-e198b680-914a-11e9-81fb-87620dcc7123.jpg)

I checked the follower- and following-status, restarted the services - not change. This affects the web-version as well as Whalebird on macOS or Toot! on iOS.

Any ideas on that one? Haven't changed anything and after the update everything turned out to be fine...

BR,

Oliver

**Comment by joycem137** [comment]
Did you call `RAILS_ENV=production bin/tootctl cache clear` as mentioned in the release notes? https://github.com/tootsuite/mastodon/releases/tag/v2.9.0

Missing that step has caused issues like this for me in the past.

**Comment by olliware** [comment]
Thanks, maybe I should get used to reading the release notes instead of updating on-the-fly ;) ! Fixed this yesterday by unfollowing and following other accounts but tried your solution and it seems to work fine. Thanks a lot 👍 !

**Comment by olliware** [comment]
Error appeared again straight out of the nowhere - clearing the cache doesn't help. Indeed I have to de-follow all the people filling my timeline and re-follow them to get content again. Hadn't this issue with this past versions before...

**Comment by olliware** [comment]
Seems to have disappeared with 2.91 and 2.92, closing it for now as there aren't any answer on this topic anyway ;) !
