### ISSUE TITLE
Support of incoming Audio object activities

### ISSUE THREAD

**Issue by rhaamo** [tootsuite/mastodon#11127]
I am developping an application federating [Audio](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-audio) objects and now that some audio support have been merged (#11123) it would be great to handle them too.

An example activity is:
```json
{
    "type": "Create",
    "id": "https://xxx/outbox/10b2ab815fe82475",
    "actor": "https://xxx/user/dashie",
    "object": {
        "type": "Audio",
        "attributedTo": "https://xxx/user/dashie",
        "cc": [
            "https://xxx/user/dashie/followers"
        ],
        "to": [
            "https://www.w3.org/ns/activitystreams#Public"
        ],
        "name": "zithar test",
        "content": "description blah blah",
        "mediaType": "text/plain",
        "url": {
            "type": "Link",
            "href": "http://xxx/uploads/sounds/dashie/db9833277fc5eced72b919485066d5e1fcd622e1ebc67c6af417e7f882777b29.mp3",
            "mediaType": "audio/mp3"
        },
        "sensitive": false,
        "published": "2019-03-28T11:55:34Z",
        "id": "https://xxx/outbox/10b2ab815fe82475/activity"
    },
    "@context": [
        "https://www.w3.org/ns/activitystreams",
        "https://w3id.org/security/v1",
        {
            "Hashtag": "as:Hashtag",
            "sensitive": "as:sensitive",
            "toot": "http://joinmastodon.org/ns#",
            "featured": "toot:featured"
        }
    ],
    "to": [
        "https://www.w3.org/ns/activitystreams#Public"
    ],
    "cc": [
        "https://xxx/user/dashie/followers"
    ],
    "published": "2019-03-28T11:55:34Z"
}
```

**Comment by ealgase** [comment]
This would be cool for Funkwhale compatibility.

**Comment by trwnh** [comment]
@ealgase I don't think Funkwhale compat makes sense in Mastodon. AFAIK Funkwhale currently plans to only expose Listen activities, not Create.

**Comment by ealgase** [comment]
> @ealgase I don't think Funkwhale compat makes sense in Mastodon. AFAIK Funkwhale currently plans to only expose Listen activities, not Create.

https://dev.funkwhale.audio/funkwhale/funkwhale/issues/831

**Comment by rhaamo** [comment]
This issue is for social sharing a now-playing `Note` with probably an attachment of a picture.

Not sharing mp3.

**Comment by ealgase** [comment]
> This issue is for social sharing a now-playing `Note` with probably an attachment of a picture.
> 
> Not sharing mp3.

Did you read the comments?

**Comment by rhaamo** [comment]
Yes and I even participated on that issue.

And the first idea, and the one Eliot is preferring is the one which broadcast a Note.

The Note way doesn't requires an Audio object, and on **how** funkwhale works it is a better option than Audio.

**Comment by ealgase** [comment]
> Yes and I even participated on that issue.
> 
> And the first idea, and the one Eliot is preferring is the one which broadcast a Note.
> 
> The Note way doesn't requires an Audio object, and on **how** funkwhale works it is a better option than Audio.

Ah, you're https://dev.funkwhale.audio/dashie?  That makes sense.
