### ISSUE TITLE
Support objects without to/cc

### ISSUE THREAD

**Issue by Xanthec** [tootsuite/mastodon#11137]
Some hubzilla objects (in particular, images) federate over without an explicit audience. However, by AP spec, we should only consider the audience on the Create activity for delivery. This does leave the visibility of the object itself a little uncertain, and it makes it harder to decide on the visibility for objects that get referenced from other activities without a Create. (boosts, etc)

<details><summary>Original issue description</summary>
Support of the ActivityStreams "Create=>Image" activity

### Pitch

In order to support sharing images creation, Mastodon need to implement this ActivityPub part and understand ActivityStreams "Create=>Image" activity.

### Motivation

People shares images creation and don't understand why this doesn't shows up on Mastodon.
</details>

**Comment by Cassolotl** [comment]
What is ActivityStream's "Create=>Image" activity?

**Comment by Xanthec** [comment]
```
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {"vcard": "http://www.w3.org/2006/vcard/ns#"}
  ],
  "summary": "Sally created a note",
  "type": "Create",
  "actor": {
    "type": ["Person", "vcard:Individual"],
    "id": "http://sally.example.org",
    "name": "Sally Smith",
    "vcard:given-name": "Sally",
    "vcard:family-name": "Smith"
  },
  "object": {
    "type": "Image",
    "name": "A picture of my cat",
    "url": "http://example.org/img/cat.png"
  },
}
```

**Comment by Gargron** [comment]
Mastodon already supports these, or is supposed to. Did you find that it doesn't work in practice?

**Comment by Xanthec** [comment]
Yes, unfortunately.
Step to reproduce :
* follow a Hubzilla account from Mastodon
* create a new image in Hubzilla with a publication associated
* expect to see it in Mastodon

It shows up in other Hubzilla accounts, but not in Mastodon.

See https://z.macgirvin.com/display/b64.aHR0cHM6Ly96Lm1hY2dpcnZpbi5jb20vaXRlbS9jNmMxZDUxYS1hNTBjLTRhMjAtOTY2MC0xN2QwODExYmJlYzQ

**Comment by trwnh** [comment]
Does it even make sense in Mastodon terms to show `Create {Image}`? I know Mastodon pretty much only deals with `Create {Note}` and prefers to include media in the `attachment` field. The one exception being polls, which for some reason use `Create {Question}` (though it'd be more appropriate to serialize it as a `Note` with `Question` attached IMO).

It might be worthwhile to automatically convert unknown activities into a status, using `summary` if it exists or constructing a natural-language alternative if not (e.g. "created an image: [url]" for a `Create {Image}`). Otherwise you have to add handlers for specific cases, like how `Create {Article}` is converted using the title and url. Perhaps that could be genericized.

**Comment by nightpool** [comment]
@trwnh that's already what we do lol

**Comment by trwnh** [comment]
@nightpool afaik mastodon just ignores unknown activities that don't have special handlers... are you saying that isn't the case?

**Comment by nightpool** [comment]
no, I'm saying that specifically we do thing thing you're talking about for
Video and Image activities

**Comment by ThibG** [comment]
Do you have the URI of one such object failing to be processed by Mastodon?

**Comment by Eldarendil** [comment]
This publication didn't show up in mastodon : https://dacha.xmpp.moe/channel/caranistar/?f=&mid=https%3A%2F%2Fdacha.xmpp.moe%2Fitem%2F38c4a914-dbd0-40c7-8444-1ab8579c8019

**Comment by ThibG** [comment]
Unfortunately I can't manage to get the AP object for that…

**Comment by emaxmax** [comment]
If you want, you can add emaxmax@hub.netzgemeinde.eu (a debug account) to your mastodon contacts, and I'll post some images to test.
Could you detail us what request you do to get the AS object? I'll try to ask Hubzilla dev what they think about that.

**Comment by ThibG** [comment]
The command I tried is:
`curl -H 'Accept: application/activity+json, application/ld+json; profile="https://www.w3.org/ns/activitystreams"' 'https://dacha.xmpp.moe/photos/caranistar/image/b2eb2be3-47b2-413c-8660-85036bf4f6db'`

I have just followed you and enabled some debug output on my instance to try making sense of why the `Create` wouldn't be accepted.

**Comment by emaxmax** [comment]
@thibg I just posted https://hub.netzgemeinde.eu/channel/emaxmax/?f=&mid=https%3A%2F%2Fhub.netzgemeinde.eu%2Fitem%2F340631d2-d1c2-4ac4-97e9-a9620f850f9b

**Comment by ThibG** [comment]
It seems to me the issue is that the `Image` object lacks an audience. I *guess* the proper thing would be to fallback to the audience of the `Create` activity, but I'm not too sure? cc @Gargron

**Comment by ThibG** [comment]
The spec acknowledges there might be discrepancies:

> A mismatch between addressing of the Create activity and its object is likely to lead to confusion.

… and suggests copying the object's audience to the `Create`:

> As such, a server SHOULD copy any recipients of the Create activity to its object upon initial distribution, and likewise with copying recipients from the object to the wrapping Create activity.

It does not consider the opposite case, though. I think I would consider that as a bug in Hubzilla?

**Comment by Xanthec** [comment]
Still not fixed.

**Comment by ThibG** [comment]
My position so far is that it's a bug in Hubzilla for not giving the object an audience.

**Comment by nightpool** [comment]
@thibg why would the object have an audience? Only activities need audiences.........

**Comment by nightpool** [comment]
I've updated the ticket and description accordingly

**Comment by ThibG** [comment]
Hm yeah, that does make sense. But we do need an audience when we discover an object. Up to now it's been included in the object, and that's what we've been using.

So, I think we need to:
1. Fall back to the `Create`'s audience (or use it instead of the `object`'s altogether when possible)
2. Support fetching not only supported objects, but `Create` activities too

**Comment by trwnh** [comment]
Objects can have audiences, not just Activity. `audience` is a property of Object.

**Comment by git-marijus** [comment]
According to the ActivityStreams 2.0 specification all object properties are optional...
