### ISSUE TITLE
Boosted toot displays the wrong author

### ISSUE THREAD

**Issue by chris-martin** [tootsuite/mastodon#1114]
This is a boost of my toot:

- https://mastodon.hasameli.com/users/gorzilla/updates/1019

But on icosahedron.website it shows up like this:

![screenshot-icosahedron website-2017-04-06-18-55-58](https://cloud.githubusercontent.com/assets/399718/24778988/8f813236-1afb-11e7-8daf-14de5608bf96.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by hishamhm** [comment]
Perhaps Gordon just copied and pasted your message? Did you check for this?

**Comment by DeadSuperHero** [comment]
Seems like an attribution issue that's referencing the person who boosted, rather than the OG author?

**Comment by chris-martin** [comment]
The URL I posted above, which says it's a boost, is the one that the screenshot's time ("8 hours ago") links to.

**Comment by Dr-Syn** [comment]
@hishamhm Nope, he didn't copy/paste - I'm the admin of that instance, and if you go to that particular post, you can clearly see it's a boost and not a copy/paste; the boost metadata is there.

**Comment by chris-martin** [comment]
In case it's relevant, the person who re-boosted it into my timeline was @nathanic@isohedron.website

**Comment by chris-martin** [comment]
This is what `@gorzilla@hasameli.com`'s profile looks like from icosahedron:

![screenshot-icosahedron website-2017-04-06-19-12-14](https://cloud.githubusercontent.com/assets/399718/24779235/06093dda-1afd-11e7-99c0-741bdf6d0081.png)

The top link goes to https://mastodon.hasameli.com/users/gorzilla/updates/1019 and the bottom link goes to https://icosahedron.website/@chris_martin/202038

**Comment by chris-martin** [comment]
And this is what `@gorzilla@hasameli.com`'s profile looks like on `hasameli.com`:

![screenshot-mastodon hasameli com-2017-04-06-19-14-56](https://cloud.githubusercontent.com/assets/399718/24779290/6ec6ceaa-1afd-11e7-93ac-6d3314c80a36.png)

**Comment by nathanic** [comment]
Hi, I am `@nathanic@icosahedron.website`, booster of this toot.*  I can confirm that at the time I boosted this toot, it appeared in the timeline as authored by Gordon.  I was actually surprised to find out later it was by @chris-martin.  So whatever broke, it broke before I boosted.  It still appears as authored by Gordon on my timeline.

* Sentences I never would have expected to write before this week.

**Comment by gorzilla** [comment]
Can confirm I didn't copy paste. I was trying to do a "remote retweet" but there's no UI option for that. Attempted solution was to find the remote post via search on my local instance and RT from there. A minute later I got a notification that someone had favourited a status but I assumed it was similar to "X has liked your retweet" on Twitter.

**Comment by gorzilla** [comment]
Thinking about it, I might have RTd and then un-RTd so I could post blackspear's GNU joke ahead of it.

**Comment by Gargron** [comment]
I will investigate this.. Might have been some sort of race condition, but I will double-check the `FetchRemoteStatusService` code.

**Comment by wxcafe** [comment]
So is this fixed? The merged PR doesn't seem to mention this issue but rather #1141... But I haven't seen this bug since, so

**Comment by codl** [comment]
This just happened to me on v1.2

This post https://mastodon.potproject.net/users/potpro/updates/134, ended up being written twice to the db, and the first (misattributed to wxcafe) one ended up on the federated timeline. It appeared on my home TL as the correctly attributed one, boosted by gargron

Could it be a race when a toot is boosted from two places at once?

![2493007c-2fcd-44e2-9f3d-4ce445c57303](https://cloud.githubusercontent.com/assets/315139/25185622/1e6695b4-251e-11e7-89aa-d4d077278673.png)
![b93121cd-6232-41d4-8338-e53f6cf617c7](https://cloud.githubusercontent.com/assets/315139/25185623/1e67e388-251e-11e7-8ddc-e7a8f189d81e.png)

hope this helps

**Comment by Shutsumon** [comment]
This happened to me last night. The toot appeared correctly in the federated timeline but incorrectly in the home timeline - it was the difference in attribution side by side that caused me to click to see what was going on and discover they really were the same toot.

The Tootplanet admin advises me that it "happens when the person or original toot being boosted isn't already federated to the instance" and also "if you completely refresh the page while the bugged toot is there, it should display properly when it reloads".

I don't know if this will help with resolving the issue but I thought I'd pass it on.
