### ISSUE TITLE
Rate limit is way too low on unreblog

### ISSUE THREAD

**Issue by ealgase** [tootsuite/mastodon#11156]
### Expected behaviour

The unreblog rate limit is the same as reblog, so if I go on an intense reblogging session, I can do unreblog all of them right after.

### Actual behaviour

I get my unreblogging throttled very quickly

### Steps to reproduce the problem

Reblog a few hundred toots quickly, then try to unreblog them.

### Specifications

N/A

**Comment by Gargron** [comment]
Unreblogging is the same as deleting, and deleting requires a low rate limit because of how expensive deletes are to the network.

**Comment by ykzts** [comment]
Intended behavior
