### ISSUE TITLE
Change current "you'll be able to follow people on any Mastodon server and beyond" text

### ISSUE THREAD

**Issue by ealgase** [tootsuite/mastodon#11159]
### Pitch

Change the text from "With an account on $INSTANCE you'll be able to follow people on any Mastodon server and beyond" to "With an account on $INSTANCE you'll be able to follow people on any ActivityPub or OStatus instance that this instance does not block"

### Motivation

Advertising "any" instance is disingenuous, given that many instances block others, and can be confusing to new users.  Also, users might falsely think they can only follow Mastodon users, excluding PeerTube, Pleroma, GNU Social, Plume, etc.  Therefore, the text should be changed to be more accurate.

Ideally, it would also have a link to the instance's list of blocked instances, but it seems like that change won't be implemented, so this is a good middle ground, at least.

**Comment by Cassolotl** [comment]
That seems unnecessarily complicated. The text you're referring to is for onboarding, aimed at people who most likely aren't familiar with how the fediverse works, whereas it's mostly people who are *already on* the fediverse who care about the politics of instance-level blocks.

**Comment by ealgase** [comment]
Yes, it's for people who aren't familiar with how the fediverse works.  Someone hearing "you can follow someone on any server", trying to follow someone on a server that's blocked, and not being able to follow them is going to turn them away from the fediverse.

**Comment by Gargron** [comment]
That is statistically insignificant in my opinion because there are over 2,000 servers and maybe 10-40 are blocked on average from any given instance.

**Comment by Cassolotl** [comment]
That, and I think that reading a sentence like "With an account on $INSTANCE you'll be able to follow people on any ActivityPub or OStatus instance that this instance does not block" is likely to put off a lot of people before they even get through the door.

Maybe something like this would be less intimidating and overly complicated? "With an account on $INSTANCE you'll be able to follow people on almost any Mastodon server and beyond." But that wouldn't be accurate for instances that don't block any other instances!

**Comment by ealgase** [comment]
> But that wouldn't be accurate for instances that don't block any other instances!

Most instances, especially those that don't block others, are blocked by at least one other instance, so it would probably still be accurate, or at least, more accurate.

**Comment by Cassolotl** [comment]
Ha, true. :D
