### ISSUE TITLE
Tune Mastodon performances

### ISSUE THREAD

**Issue by valentin2105** [tootsuite/mastodon#1117]
Hi,

I'm running **Mastodon.Cloud** with more than 7K users now. 

Some people from .social say it took 20mn to receive our TooTs in their instance. 

I would like to optimize my Mastodon setup to stay in open-registration mode. 

The first think I've do is :
```
      - WEB_CONCURRENCY=4
      - MAX_THREADS=8
```
The performances in the own instance is still really correct to accept other users. 

But How to tweak the propagation to another instance ?

What's the advantage to load-balance the Streaming instance ? I can do this easily (tried in my personal instance) But what's the benefit ? 

Same for the Sidekiq one, I load balance it on dev,  It can't provoke problems ? 

I load balance Web too (in dev), there's no know problem about that ? 

Sorry for the few question, but I want to clearly understand theses things before enable Load-balancing in my production instance. 

Here is my containers in lb-mode :
```
        Name                       Command               State                Ports               
-------------------------------------------------------------------------------------------------
mastodon_db_1           docker-entrypoint.sh postgres    Up      5432/tcp                         
mastodon_redis_1        docker-entrypoint.sh redis ...   Up      6379/tcp                         
mastodon_sidekiq1_1     bundle exec sidekiq -q def ...   Up      3000/tcp, 4000/tcp               
mastodon_sidekiq_1      bundle exec sidekiq -q def ...   Up      3000/tcp, 4000/tcp               
mastodon_streaming1_1   npm run start                    Up      3000/tcp, 0.0.0.0:4001->4000/tcp 
mastodon_streaming_1    npm run start                    Up      3000/tcp, 0.0.0.0:4000->4000/tcp 
mastodon_web1_1         bundle exec rails s -p 300 ...   Up      0.0.0.0:3001->3000/tcp, 4000/tcp 
mastodon_web_1          bundle exec rails s -p 300 ...   Up      0.0.0.0:3000->3000/tcp, 4000/tcp 
```

Thanks a lot for building this Awesome social network. 

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by vielmetti** [comment]
You might want to look at ctop (http://ctop.sh) to visualize what your containers are doing in real time.

**Comment by valentin2105** [comment]
This, it's a great tool !

I'm asking these answers to understand if there is no incompatibility in the code to load-balance each Mastodon services (excluded for Redis & Postegres).

**Comment by Gargron** [comment]
Could you provide the specs of your server (CPU cores, RAM)? Or your setup if you have multiple machines?

**Comment by valentin2105** [comment]
For now,

4 vCPUs Xeon(R) CPU E3-1225 V2 @ 3.20GHz
32G RAM
2 TO SATA

**Comment by vielmetti** [comment]
Do you have ssd available to you? What are your io stats when you run
’iostat 5'?

**Comment by valentin2105** [comment]
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          11.89    0.02    2.95    0.50    0.00   84.64

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sdb              16.68         1.06       735.45     146953  101930936
sda              17.02         8.74       735.45    1211281  101930936
md2              23.94         5.89       411.50     816813   57033140
md3              12.14         3.82       304.46     529345   42197496
```

No I haven't any SSD on this server.

**Comment by vielmetti** [comment]
The other tool I'd look at for diagnosing this is `sysdig`, from http://sysdig.org , but there's no one simple command I know that would dig out a diagnosis.

**Comment by ashfurrow** [comment]
Something other instance admins have been recommending is to increase `DB_BOOL` environment variable to higher than the default of 5, like 50, and then pass `-c 50` (or whatever number) into Sidekiq. This increases the number of Sidekiq threads available to do work. 

In any case, let us know how it's going!

**Comment by valentin2105** [comment]
I have evolved a little,

Here is now my configuration :

One dedicated Postgres server with PGbouncer in front.
( Need a strong server for this)

One front server with Two web , two streaming and 8 sidekiq (with 15 DB POOL).
One second server with One web, one streaming and 8 sidekiq.
A minio server on the Frontal server too.

The load balancing work great and free up some load on the master server.

Need improvment can be added to Mastodon for high scaling, like :

- Can give a read only Postgres server for READ requests (let us enabling Master-slave postgres)
- Can use the assets in S3 (it's a bit problematic).

Otherwise, it work at glances. 

😄

**Comment by ashfurrow** [comment]
Thanks for following up! I'm sure this info will be helpful to other admins 😄

**Comment by ashfurrow** [comment]
Just a note: it would be helpful for other/prospective admins if you could add your configurations [to the documentation](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Resources-needed.md). No pressure though!

**Comment by Gargron** [comment]
There is this documentation page which may be helpful: https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Tuning.md

If you would like further support, I recommend posting on our [Discourse](https://discourse.joinmastodon.org), since this Github issue is not directly related to the code.
