### ISSUE TITLE
Can we get a helm chart for K8's deployments? 

### ISSUE THREAD

**Issue by jdbohrman** [tootsuite/mastodon#11197]
Hey everyone, first off thank you SO much for the work you do. I have been so happy with my communities here. I hope one day their is a VoiP service like this. But anyways, I was wondering if I started the work on it, could we get a Helm chart for a Mastodon deployment?

I think this would go a long way for people who want to spin up highly available instances that also have monitoring and observability. 

Helm is basically the package manager for Kubernetes and makes deploying K8's apps a breeze. I'd love to help out and maintain anything K8's and container related also if you need the help.

**Comment by Gargron** [comment]
> Helm is basically the package manager for Kubernetes and makes deploying K8's apps a breeze. I'd love to help out and maintain anything K8's and container related also if you need the help.

That would be appreciated! As far as I'm aware none of the regular contributors use K8 so it would be awkward for us to add the tooling.

**Comment by jdbohrman** [comment]
Upon looking at things a bit I realized K8's might not solve anything that docker-compose doesn't already solve.

**Comment by jdbohrman** [comment]
Just because it might be nice to have for people who like to monitor there stacks across different nodes, I'm reopening this. I don't know when I'll get to it but it's on my agenda.

**Comment by pchico83** [comment]
@Gargron I am working on a Helm chart for mastodon to be able to deploy it to Okteto Cloud.
Would you be interested in having it on this repo? or do you prefer me to keep the chart on a separate repo?

**Comment by Gargron** [comment]
@pchico83 I don't know what a Helm chart looks like. Is it a single file? A directory? If it helps plug-n-play deployment I'd like it in the repository.

**Comment by pchico83** [comment]
@Gargron It is a folder that groups the k8s manifests to deploy in Kubernetes.
This is a sample for mysql:
https://github.com/helm/charts/tree/master/stable/mysql
I will send the PR to this repo then, thanks!
