### ISSUE TITLE
When federating from Friendica, some diacritics characters in user name are mangled

### ISSUE THREAD

**Issue by fuxoft** [tootsuite/mastodon#11201]
### Expected behaviour

User name should display the same way as on user's profile on his home Friendica server. His name is (correctly) displayed as "Miroslav Prýmek" here: https://nerdica.net/profile/mprymek

### Actual behaviour

The "ý" character in user's name is mangled. The name is (incorrectly) displayed as "Miroslav PrÃ½mek" e.g. in his Mastodon comment here: https://kompost.cz/@fuxoft/102344407570452358

### Steps to reproduce the problem

Just visited the URLs above. This happens with all his comments.

### Specifications

I am running Mastodon 2.9.2 but I am not Mastodon developer and I don't have enough experience to decide if this is a problem with Mastodon or with Friendica.

Browser / operating system is not relevant, the bug is present on all platforms.

**Comment by ThibG** [comment]
I can't reproduce it. Could it have been an issue on their end that was fixed since?

**Comment by fuxoft** [comment]
> I can't reproduce it. Could it have been an issue on their end that was fixed since?

I doubt that. This is happening consistently with all his toots for several months. Or do you mean that he should try editing his name on Friendica and THEN posting again?

**Comment by ThibG** [comment]
No. I would suggest forcing a refresh of their profile by pasting its URL in Mastodon's search bar.

**Comment by mprymek** [comment]
Hello, the profile is mine but I don't control nerdica.net so I don't have any idea how I could be of any help with this problem.

If there's anything I can do, please let me know.

**Comment by fuxoft** [comment]
> No. I would suggest forcing a refresh of their profile by pasting its URL in Mastodon's search bar.

Oh, great, that worked! I had no idea it's cached like that.
