### ISSUE TITLE
Subscribe for mobile notifications from accounts to drive engagement

### ISSUE THREAD

**Issue by taoeffect** [tootsuite/mastodon#1122]
A big part of what brings me back to twitter every morning are all the notifications on my phone from twitter accounts I've subscribed to. I read them like the morning paper.

If Mastodon had this, I'd be less inclined to visit the bird site and more inclined to stay just on Mastodon.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by sguinetti** [comment]
Is good idea that notifications are easy to administrate and battery friendly.

**Comment by sorin-davidoi** [comment]
Addressed by #3243.
