### ISSUE TITLE
Feature request - preferences setting to auto-expand CW

### ISSUE THREAD

**Issue by emf** [tootsuite/mastodon#1123]
When suddenly the whole world is talking about something and hiding it behind CW, it means a million extra clicks for a user to interact with the thread.   Users should be able to decide for themselves if they want CW's to default to open or closed.

**Comment by wxcafe** [comment]
It would be nice to have a "default policy about CW'd posts" that the user can set open or closed (and that defaults to closed) and then a list of blacklist terms so that you can have it open by default except for such and such terms.

**Comment by dn3s** [comment]
the concerns i would have with a blacklist are:
- if a user isn't creative enough thinking of synonyms, they will see unwanted content (perhaps this could be addressed with either crowd-sourced list "presets", or auto-complete on the CW input and the blacklist input. I imagine this would be difficult due to the federated nature of the system though) (this isn't necessarily a damning problem; users can probably be trusted to evaluate this risk)
- The sort of things a hacker or rogue sysadmin could do with a bunch of identity-linked CW lists is a worrying thought.

(in [my (now closed) issue](https://github.com/tootsuite/mastodon/issues/4048) i proposed a messy behind-the-scenes whitelist that allows adding items by just clicking "always show" next to CW'd posts. But this is a pretty ugly solution.)

**Comment by dn3s** [comment]
I may be overthinking this. i do like @wxcafe's idea.

**Comment by Cassolotl** [comment]
I think even with the problems it's still a better system than the current lack-of-system, so I'm all for it. :)

**Comment by wxcafe** [comment]
My suggestion wasn't to have this be default-allow with a blacklist, my suggestion is to keep it default-deny like it is right now but people could set it to default-allow.

**Comment by miwilc** [comment]
@wxcafe I would like to see that, for what it's worth: +1

**Comment by ProgVal** [comment]
[Someone pointed out](https://witches.town/@morganastra/99453864059996012) that this is an accessibility issue:

> this site still needs an "expand all CWs" button huh
> this is definitely just a case of competing access needs but to me, the proliferation of CW's is an accessibility nightmare verging on making the site actually unusable to me. I don't have very good fine motor control and i also have ADHD that makes it kind of hard to focus on things and the combination of those two make it basically impossible for me to actually read things behind CW's and i often log in to see the entire page just completely covered with them. I'm definitely not saying they shouldn't exist or people shouldn't use them, but we do need a way to just turn them off by default or expand-all or something

**Comment by trwnh** [comment]
At minimum, we should be able to expand all CW in one thread. Whitelist/blacklist could get complicated pretty quickly.

**Comment by dn3s** [comment]
or expand all CWs in a thread that match the currently selected CW. That way for examlpe, a thread tagged "birthday greetings" won't expand a sub-thread tagged "extreme vore" etc

**Comment by terminationshok** [comment]
I think the client should be able to completely disable CW if they want. My needs for CW are completely different from the defaults in most places. Lacking fine-grained control, it ends up being better if nothing is hidden(from my client view)

**Comment by ocdtrekkie** [comment]
Definitely need this, I miss a lot of posts because opening a CW for each post I scroll past just isn't worth the effort. There'd be a lot less resistance to using CWs for things if people who didn't want them weren't burdened by them as much.

**Comment by rhoio** [comment]
As a temporary workaround, here are two bookmarklets for the mastodon web interace to expand and collapse all content warnings at once:
https://codepen.io/anon/pen/NLWjLj/?editors=1000

**Comment by rugk** [comment]
BTW I've described my use case here: https://github.com/tootsuite/mastodon/issues/8681#issuecomment-422972616

**Comment by Gaelan** [comment]
I came to request a CW whitelist, but found this issue. Should it be reopened, or should I open a new issue?

**Comment by ocdtrekkie** [comment]
@Gaelan Ah. IMHO, I would open a separate feature request for that specific issue, as the original goal of this issue was a setting to auto-expand CWs, and that is now done.
