### ISSUE TITLE
How can I activate Trending hashtag feature? 

### ISSUE THREAD

**Issue by JDJoe** [tootsuite/mastodon#11264]
How can I activate Trending hashtag feature in latest version? 
There is nothing in documentations and no option visible in admin interface.

**Comment by Cassolotl** [comment]
The trending hashtags are only visible to admins, I think?

**Comment by JDJoe** [comment]
I am the admin for that particular instance. 

> The trending hashtags are only visible to admins, I think?

Not sure I follow. What do you mean by "trending hashtags are only visible to admins"

**Comment by Gargron** [comment]
Trending hashtags are displayed on the admin dashboard and nowhere else. See #7702 for discussion that led to this.

**Comment by JDJoe** [comment]
> Trending hashtags are displayed on the admin dashboard and nowhere else. See #7702 for discussion that led to this.

I like to have this feature enabled for everyone. Shows trending hashtags in our instance. 
Why cant it be something admin can turn on/off? Why removed? Makes no sense at all. 

I am not a developer, so how can restore this feature?

**Comment by Cassolotl** [comment]
It was a deliberate decision in response to community concerns about trending hashtags being used to harass vulnerable groups, like on Twitter.

**Comment by JDJoe** [comment]
LOL. OK
But can it be restored? Is it something complicated? Are you willing to do it and write it so that instance members (or admin) can decide use it or not. (for a fee?)

**Comment by Gargron** [comment]
Gled's fork of Mastodon has this feature: https://github.com/gled-rs/mastodo Although it also has a bunch of other things I disagree with as features.

**Comment by JDJoe** [comment]
Thanks. I read the features list and sounds sane.  Let the users decide what features they like or not. ;) 
Cheers!

**Comment by Houdaifa18** [comment]
Good

**Comment by JDJoe** [comment]
Searching around I finally ended up here https://code.gab.com/gab/social/gab-social/commits/develop
It seems they are fixing and upgrading a lot of stuff there. Has anyone poked around in that codebase?
I am not sure it has trending tags though.
