### ISSUE TITLE
External user avatars not working.

### ISSUE THREAD

**Issue by Spunkie** [tootsuite/mastodon#1126]
I finished setting up a heroku instance today and I got s3 working for uploaded avatars but my instance is not pulling in external user avatars from other instances. The same thing is happening in my timeline so it's not just that 1 user, all external user avatars are broken.

https://social.spunkiedesign.com/users/Spunkie/following

Anyone know what I need to do to fix this?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Add `pull` to the queues the Sidekiq must listen on. (This is reflected in latest documentation and docker configs)

**Comment by Spunkie** [comment]
Is this the part of the docker documentation you are talking about?
`ExecStart=/home/mastodon/.rbenv/shims/bundle exec sidekiq -c 5 -q default -q mailers -q pull -q push` 
in  
`/etc/systemd/system/mastodon-sidekiq.service`

Sorry I'm a new to heroku and as I understand it directly editing files won't work since the changes will get thrown away and that file does not appear in the heroku deploy git repo. What is the proper way to add this for heroku? Do I just need to add the path/file to the deploy repo and push?

**Comment by Gargron** [comment]
I have changed the Procfile (which is what Heroku uses) so now it should pick up the change. You might need to re-deploy/pull from the github though

**Comment by Spunkie** [comment]
I've pushed & restarted the dynos, but the avatars are still not being fetched.  I am seeing a lot more streaming errors like https://github.com/tootsuite/mastodon/issues/1119 now though.

**Comment by mkody** [comment]
I have the same issue. I'm not running my instance with Docker or on Heroku.

**Comment by Aldarone** [comment]
Same here, running on a dedicated server with Docker.

**Comment by nlienard** [comment]
same issue, running on a dedicated server with Manual installation and frequent git pull.

**Comment by MrWazaby** [comment]
Same issue here. On a dedicated server and with manual installation too.
