### ISSUE TITLE
Incorrect scope required for /api/v1/accounts/verify_credentials

### ISSUE THREAD

**Issue by fluffy-critter** [tootsuite/mastodon#11263]
### Expected behaviour

According to [the docs](https://docs.joinmastodon.org/api/rest/accounts/#get-api-v1-accounts-verify-credentials), verify_credentials should only require the `read:accounts` scope

### Actual behaviour

When attempting to call that endpoint with a client that only has `read:accounts`, I get error 403 with response text: `{"error":"This action is outside the authorized scopes"}`

If I expand my scope to `read` I am able to use the `verified_credentials` endpoint.

### Steps to reproduce the problem

I am trying to implement federated identity in [a Python library](https://github.com/PlaidWeb/Authl) which wraps a number of different identity providers. In implementing the Mastodon handler, I ran into this issue. Current implementation is at https://github.com/PlaidWeb/Authl/blob/ff95eef2b1c3fcbcce2c498971a647ec63d905bb/authl/handlers/mastodon.py

If there is a better way to just remotely verify the identity of someone (such as a more appropriate endpoint which only provides the authorized user's URL), I'm all for it.

(This is a workaround to the lack of resolution to issue #4800.)

### Specifications

Mastodon 2.8.0 running on queer.party

**Comment by fluffy-critter** [comment]
Hmm, the code in Mastodon is correct, and it looks like the actual problem is that I'm not requesting the scope correctly. The Mastodon authorization UI shows no scopes being requested at all.

**Comment by fluffy-critter** [comment]
Okay, I solved the problem -- turns out I needed to pass the argument in as `scope` as well as `scopes`.

**Comment by MeesJ** [comment]
I'm having the same issue with the same API endpoint. Could you perhaps elaborate more how you fixed this problem on your end?

**Comment by fluffy-critter** [comment]
I ended up switching to mastodon.py which handles this for me, but my previous working implementation was at https://github.com/PlaidWeb/Authl/blob/52640e471dc9024e037244c0a4dc7758808f4a51/authl/handlers/fediverse.py

I don’t remember all the details offhand (it was a minor thing I did nearly 4 years ago) but it appears that in my implementation I had to use `scope` in one context and `scopes` in another, and it’s probably a subtle distinction as to which is which.

I’d highly recommend using someone else’s client instead, as it’s a lot easier to make it someone else’s problem to deal with the fiddly bits.

**Comment by trwnh** [comment]
to clarify: if you want to use granular scopes, you need to declare them during app registration. registering an app with `scopes`=`read` does *not* allow you to request a token with `scope`=`read:accounts`

**Comment by fluffy-critter** [comment]
I believe the problem that I was originally having wasn't that I was changing between a general and a granular scope, just that I was using `scopes` in both the app's token request and the client request, when the latter wanted the parameter to be named `scope`. I had originally used the overly-broad `read` category and at a later time I changed to `read:accounts` just to be extra-clear to the user that I was *only* requesting their account information, not their entire timeline et al.

Regardless, I later fixed it more gooder by switching to mastodon.py instead of using my own bespoke OAuth implementation, and that's generally what I'd recommend to others as well.

**Comment by fluffy-critter** [comment]
Which is to say (based on reconstituting my recollection of a thing that happened, again, nearly four years ago), in the app registration API the parameter is called `scopes` but in the OAuth API the parameter is called `scope`. This wasn't entirely clear to me, and correcting that was my fix, in the context of what @MeesJ was asking about.
