### ISSUE TITLE
Confusing documentation for OAuth scopes

### ISSUE THREAD

**Issue by fluffy-critter** [tootsuite/mastodon#11266]
### Expected behaviour

Either the OAuth API should show the correct `scope`/`scopes` parameter to use for various situations, or it should accept both parameters in both situations.

### Actual behaviour

In implementing an identity service which can use Mastodon as an authentication endpoint, I ran into an issue with requesting the `read:accounts` scope. While using an argument of `scopes="read"` worked on both `/api/v1/apps` and `/oauth/authorize`, when requesting just a scope of `read:accounts` I had to use `scopes` on `/api/v1/apps` and `scope` on `/oauth/authorize`.

Attempting to use `scope` on `/api/v1/apps` resulted in an "invalid scope" error at authentication time, and using `scopes` on `/oauth/authorize` resulted in no scopes being granted (the authentication UI even read: "It will be able to" with nothing after).

### Steps to reproduce the problem

```
GET /api/v1/apps?scope=read:accounts&...
GET /oauth/authorize?scope=read:accounts&...
```
results in "invalid scope"

```
GET /api/v1/apps?scopes=read:accounts&...
GET /oauth/authorize?scopes=read:accounts&...
```
results in no scopes granted

```
GET /api/v1/apps?scopes=read:accounts&...
GET /oauth/authorize?scope=read:accounts&...
```
works as intended.

### Specifications

2.8.0 on queer.party, 2.9.2 on mastodon.social

**Comment by Gargron** [comment]
>  While using an argument of `scopes="read"` worked on both `/api/v1/apps` and `/oauth/authorize`

It didn't work. The default scope that's assumed when none is given is "read" which is why it appeared like it worked even though the OAuth endpoint did not understand your parameter at all. This is highlighted in common gotchas in the docs:

https://docs.joinmastodon.org/api/authentication/#common-gotchas

**Comment by fluffy-critter** [comment]
Ah, that makes sense. I had read the "common gotchas" section multiple times but the default `read` scope working made that part not register, I guess.

I guess the docs are correct, but it'd be helpful if this aspect were highlighted in the auth flow portion.

Relatedly, the OAuth flow should mention the `state` parameter, since that's necessary for many client scenarios and was only implied for folks who are already experienced with OAuth.
