### ISSUE TITLE
Toots stopped showing up on remote instances

### ISSUE THREAD

**Issue by zunda** [tootsuite/mastodon#11270]
### Expected behaviour

Public toots and replies appear timelines for an account on a remote server who follows the source account.

### Actual behaviour

After merging #11249, toots no longer appears on remote servers. Local timelines are not affected.

### Steps to reproduce the problem

1. Merge #11249 and deploy it to Server A.
1. Login to Server A and post a toot to an account on a remote server, e.g., `@user-b@server-b hello`
4. Login to Server B as user-b, check the timeline

### Specifications
Versions:
- NG: 1e7187f2a8e0b9ffe4e7d6b06e9f70674c50471e
- OK: 1e7187f2a8e0b9ffe4e7d6b06e9f70674c50471e with 63c7fe8e4892b22e80c015bf0ecb04496318623b reverted

Looking through app logs, it seems that the toots are POSTed successfully to the remote server. @mayaeh [seems to have found](https://mastodon.crazynewworld.net/@hanage999/102410535013768500) that the toot is `bundle: Rejected Create activity` by the remote server receiving toots.

**Comment by mayaeh** [comment]
The following was output to server B's log:
`bundle[xxxx]: Rejected Create activity https://edge.taruntarun.net/users/mayaeh/statuses/102410160037905932/activity from https://edge.taruntarun.net/users/mayaeh`

**Comment by Gargron** [comment]
I think it is caused by serializer cache... It looks like the activity embeds itself as "object" for some reason instead of the note itself
