### ISSUE TITLE
Support hiding local timeline

### ISSUE THREAD

**Issue by kballard** [tootsuite/mastodon#1127]
I set up a single-user instance, which makes the Local Timeline pretty useless, as all it can ever show me is my own posts. I'd love an option to just hide the Local Timeline entirely, and have this exposed via the API somehow so clients like Amaroq can follow suit and also hide it.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kballard** [comment]
It occurs to me that the Federated Timeline is also pretty useless here. @wxcafe [described its behavior](https://github.com/tootsuite/mastodon/issues/1104#issuecomment-292324455) as

> The Federated Timeline is made from the toots by people that are on your instance, and the ones by people on remote instances that people on your instance follow, since they started following them.

Since I'm the only person on my instance, all it can ever show is toots by people I follow, which makes it no different than Home.

I'm not really sure what to do about this. It would be nice if I could have a timeline that shows me toots by people that are followed by people I follow (i.e. followees of followees), but I'm guessing that this isn't nearly as simple as toots by people that folks on my instance follow. And this is making me rethink the whole notion of having a single-user instance.

**Comment by mkody** [comment]
Err, can't you just ignore the local timeline? You're not forced to have it open. :smile: 

For the federated timeline, it is used. It'll get populated with toots from other instances and not only people you follow.

**Comment by zcdunn** [comment]
@mkody The federated timeline is made up of the combined following list of everybody on an instance. If there's only a single user on an instance, the federated timeline won't grow beyond that user's home timeline.

**Comment by mkody** [comment]
@zcdunn This isn't true. For example, `@pieceofthepie@mstdn.io` just appeared in the federated timeline, but that user doesn't have a single follower. I'm following and talking to people from mstdn.io, and now the toots sent in public from that instance is coming to my federated timeline.

**Comment by zcdunn** [comment]
Ok, my bad. So it doesn't just pull in users that local users follow, but also pulls in anybody they interact with.

I could still see that being unneeded for a single user instance. If the user wanted to see those posts, they could just follow those users. The federated timeline serves as a way for local users to find more users to follow/interact with, but the single user is already aware of all users in the federated timeline.

**Comment by Gargron** [comment]
I'm sorry but I do not see a lot of value in hiding the local timeline on single-user instances. You're absolutely right that it's useless, but nobody requires you to ever open it.
