### ISSUE TITLE
Video view counter

### ISSUE THREAD

**Issue by vinod-1** [tootsuite/mastodon#11281]
As of now, we do not have an option to see the number of views on any video uploaded.

### Pitch

Some really nice videos are uploaded and millions of people are viewed but there is no record as how many are being watched it. So, having a counter would help us to identify or sort based on views 
### Motivation

Many users can benefit as the post is a good one. It will also help to choose to play video or not to play. Most of the time people will click play whenever they see more views due to curiosity.

**Comment by TemporaryUsername12481** [comment]
This would probably require the `view` activity type.

**Comment by N07070** [comment]
I don't think this is a good ideal. It promotes virality based on the number of views, but don't give a clear indication about the quality of the content. 

I also think that it goes against the way replies are displayed, and to be consistent, it should work in a similar fashion.
