### ISSUE TITLE
Invalid hostname sent on SMTP helo

### ISSUE THREAD

**Issue by plinss** [tootsuite/mastodon#1130]
When sending confirmation emails, the SMTP helo (or elho) is using an invalid hostname, from my debugging logs it appears to be "unknown[&lt;actual IPv6 address&gt;]" rather than the server's hostname. This is causing email to be rejected by my Postfix's "reject_invalid_hostname" filtering rule.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by joshlbs** [comment]
Well done for logging this!
I had the same issue and, as a workaround, adding SMTP_DOMAIN=example.com to .env.production does the trick.

**Comment by plinss** [comment]
Tried that and didn't help

**Comment by wxcafe** [comment]
I'm pretty sure this is an issue with either your `/etc/hostname` or your `/etc/hosts`. Try working with these and see if that changes your outbound email domain.

**Comment by plinss** [comment]
`/etc/hostname` and `/etc/hosts` are properly setup. Running:
`hostname -f`
yields the proper fqdn.

**Comment by R0ckweb** [comment]
As joshlbs says, adding [SMTP_DOMAIN to .env.production](https://github.com/tootsuite/mastodon/blob/master/config/environments/production.rb#L101) solve this problem !

According to [the mailer documentation ](http://edgeguides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration) this config force a HELO domain.
Tested and approved.

**Comment by plinss** [comment]
Adding SMTP_DOMAIN to .env.production did not solve the problem for either of the two instances I manage

**Comment by ian-kelling** [comment]
@plinss, did you set SMTP_DOMAIN to a domain that would resolve to an ip you control, then restart mastodon? Setting SMTP_DOMAIN worked for me. What exact error message do you get?

**Comment by ineffyble** [comment]
Hey all,

Just made a pull request to fix a bug that I discovered - the SMTP domain should in theory be set from the SMTP_DOMAIN environment variable, and fallback to the LOCAL_DOMAIN variable otherwise.

The problem was, the fallback wasn't working, it was referencing an internal variable that wasn't yet set. That would explain some of the issues mentioned.

**Comment by plinss** [comment]
I was setting SMTP_DOMAIN in the .env.production file, not as an environment variable, perhaps that's why it didn't work for me. I wasn't getting an error from Mastodon, but a rejection from my smtp server due to malformed helo hostname.

Fixing the default sounds like the proper fix.
