### ISSUE TITLE
Follows and followers counts sometimes displaying wrong zero value

### ISSUE THREAD

**Issue by ichi-i** [tootsuite/mastodon#11337]
### Expected behaviour
Number of follows and followers should be the same (or at least similar) to the numbers displayed on the home instance of the user.

### Actual behaviour
Some profiles are loaded with 0 follows, 0 followers, or 0 follows and followers. The number never updates if the user receives new followers or follows new users.

All the profiles I happened to encounter this issue with are from Pleroma instances, but this issue does not necessarily affect all user profiles from the same (Pleroma) instance.

Refreshing the profiles from the admin panel does not fix the issue either.
Refetching the profiles by inputting the link to the user page (e.g. https://example.tld/users/name) in the searchbox does not fix the issue either.

This is most likely caused by Pleroma users selecting the option to hide who's following them and/or who they are following. The follow/follower count still displays a number higher than 0 on their home profiles though.

### Steps to reproduce the problem
- Follow a user from a remote instance

### Specifications
- Mastodon v2.9.2
- Devices I checked profiles with:
  - Firefox Quantum 68 on a Linux distribution and Windows 10
  - Amaroq App

**Comment by Gargron** [comment]
It doesn't sound like a Mastodon issue--we're doing all we can with the data provided by the remote server.

**Comment by ichi-i** [comment]
If that is the case I will close this issue and try to see if anything can be done by Pleroma then.
