### ISSUE TITLE
Using OAuth for other instances

### ISSUE THREAD

**Issue by wirehack7** [tootsuite/mastodon#1134]
Feature request:
Registering to ne Mastodon instance and using this account then for others via OAuth to "register" there. Might be a good idea, might be not. Let's discuss this.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
This is basically the same idea as described in #1203, so I'm closing this issue. Feel free to reopen it if that other thread doesn't answer your question.
