### ISSUE TITLE
Asset path won't change after recompile

### ISSUE THREAD

**Issue by mfa777** [tootsuite/mastodon#11367]
After new installation, I accidentally delete all the files under _public/packs/css/*_.

So I did two things:

1.  `rm -rf tmp/cache/webpacker/` 
2. `RAILS_ENV=production bundle exec rails assets:precompile`

Now there is new files come out under _public/packs/css_ . But the path on the page didn't change. It's still old files.

css file on server:

```bash
$ ls public/packs/css/
common-6d144f9e.css
...
```
path showed on the page:

`<link rel="stylesheet" media="all" href="/packs/css/common-ead4a7a7.css" />`

**Comment by Gargron** [comment]
Restart the web process

**Comment by mfa777** [comment]
I just used `RAILS_ENV=production bundle exec puma -C config/puma.rb` and `Ctrl + c` to restart puma. The path doesn't change after I tried many times.

The wired thing is after I try to use system service, just did `sudo systemctl restart mastodon-web` one time, the path was changed immediately.

What is the difference with those two ways?
