### ISSUE TITLE
Nginx web service: 502 Bad Gateway

### ISSUE THREAD

**Issue by Never2333** [tootsuite/mastodon#11370]
Cannot open the site, it shows an error.
I used Nginx, and followed by: https://lala.im/4286.html

**Comment by BNolet** [comment]
This usually means that the mastodon service isn't actually running. Please post a log (and erase any personal data from it before posting) of the Mastodon server. 

`journalctl -xe -u mastodon-*` should give you something useful

**Comment by Never2333** [comment]
[error.log](https://github.com/tootsuite/mastodon/files/3414683/error.log)
This is nginx error log.

**Comment by Never2333** [comment]
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    gzip  on;

    include /etc/nginx/conf.d/*.conf;
}


This is my nginx conf.

**Comment by BNolet** [comment]
You need to run `chown -R 991:991 public` within the `live/` directory.

**Comment by Never2333** [comment]
991?

**Comment by Never2333** [comment]
Er... Still not working....

**Comment by BenLubar** [comment]
Are you running Mastodon in Docker? Add `BIND=0.0.0.0` as an environment variable.

**Comment by Never2333** [comment]
> Are you running Mastodon in Docker? Add `BIND=0.0.0.0` as an environment variable.

No, I am using CentOS 7.4

**Comment by Gargron** [comment]
Nginx error log is not helpful. Please post error log of:

    journalctl -u mastodon-web

**Comment by Never2333** [comment]
> Nginx error log is not helpful. Please post error log of:
> 
> ```
> journalctl -u mastodon-web
> ```

[journalctl --no-pager -u mastodon-web.log](https://github.com/tootsuite/mastodon/files/3415575/journalctl.--no-pager.-u.mastodon-web.log)

**Comment by Never2333** [comment]
That's enough, I cannot wait so long.

**Comment by Gargron** [comment]
Instead of nginx configuration in the tutorial you linked make sure you use the one provided in this repository under `dist/nginx.conf`. You can also refer to this documentation as the most up-to-date: https://docs.joinmastodon.org/administration/installation/

The only unusual line in your log is `HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>` but I cannot determine what causes it except perhaps wrongly configured nginx.

At the bottom of your log is a successful request to `/`, though...

**Comment by Never2333** [comment]
> Instead of nginx configuration in the tutorial you linked make sure you use the one provided in this repository under `dist/nginx.conf`. You can also refer to this documentation as the most up-to-date: https://docs.joinmastodon.org/administration/installation/
> 
> The only unusual line in your log is `HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>` but I cannot determine what causes it except perhaps wrongly configured nginx.
> 
> At the bottom of your log is a successful request to `/`, though...

I changed a system to Ubuntu 18.04 and followed the official documentation, and I made it.
And,  please forgive me for being impolite.
