### ISSUE TITLE
Can't scroll in single-column mode with Chrome

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#11389]
### Actual behaviour

Since #11359, Google Chrome can’t scroll in single-column mode.
Reference video is [here](https://taruntarun.net/media_files/Mastodon/media_attachments/files/000/504/783/original/d49d1a07d00d99d7.mp4).

I didn’t find any errors.

It seems to work fine with Firefox and Safari.

### Specifications

My environment:
- Server:
  - Mastodon master c669bb42baa213dde27d831bb34f0ce14cfb29dc equivalent

- Client: 
  - Chrome for mac ver. 75.0.3770.142
  - Firefox for mac ver. 68.0.1
  - Safari for mac ver. 12.1.1

**Comment by ThibG** [comment]
This is because of `contain: strict` for the `scrollable` class. Changing it to `contain: content` works but I'm not sure it's correct, I do not fully understand that property.
