### ISSUE TITLE
Tab bar and column header should not scroll

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#11396]
### Expected behaviour

In single-column mode, the tabs bar and column header should remain in the viewport.

### Actual behaviour

The tabs bar and column header scroll with the rest of the page, making the tabs bar mostly useless on mobile.

### Steps to reproduce the problem

Just scroll up and down.

### Specifications

Issue introduced by #11359.

**Comment by ThibG** [comment]
I played with having them as `position: fixed` but the column headers being inside the react-swipeable div makes that impossible

**Comment by Gargron** [comment]
@ThibG I have previously achieved this but discarded the result. The way to do it is to use `position: sticky` on the column header element while taking it a nesting level outward. It just didn't seem worth it.

**Comment by ThibG** [comment]
I think it's worth it at least for the tabs bar. Otherwise, switching to another tab in mobile UI requires you to move to the top of the TL first, and that sounds like a big regression.
