### ISSUE TITLE
admin dashboard should show allocated media size

### ISSUE THREAD

**Issue by grinapo** [tootsuite/mastodon#11401]
### Pitch

Admin dashboard (and submenus) give a good overview of the instance. 
There is, for example, `SPACE USAGE`, which summarizes Psql and Redis.
However I hadto realise (testing a new instance) that 90% of the space was actually used up by `…/live/public/system/media_attachments` directory, and it's size isn't indicated anywhere I could find.

### Motivation

When the disk space is gone the admin shall be shown why. It is obvious by using console and doing a full `du` but maybe it's not optimal.

**Comment by ykzts** [comment]
It is solved to some extent by `tootctl media usage`. The display on the Dashboard is heavy.
