### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by LiohMoeller** [tootsuite/mastodon#11425]
I would like to understand the reason why the GIT repository for the docs has been frozen? Also I do not find any hints on docker based setups anymore. Maybe that's no longer the recommended way to install Mastodon? For the current docs I would be glad to know where they are rendered from? Is there a new git resource for that? I personally find them also hard to read with grey font on dark grey bg so maybe we can add a light scheme as well.

**Comment by ykzts** [comment]
https://source.joinmastodon.org/mastodon/docs

**Comment by mfa777** [comment]
Yes I guess Docker is not recommended too.

https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md this guide is already expired.  If you follow that you will encounter many trouble.

New docker installation document is needed urgently.

**Comment by Gargron** [comment]
Fixed
