### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Phyks** [tootsuite/mastodon#1142]
Hi,

I find two issues with the landing page of an instance.

* When I want to go in Mastodon, I often just type my instance's URL, not the "login" URL, which is actually different. This means that I have to find the "login" link (which is quite hidden below the signup form) and then, have to submit the login form (and maybe even the 2FA form) in order to get connected. This is long, and quite painful. Plus with time, I guess there will be more users with account than new users.

This could be solved quite easily by switching the two forms I guess. That is, having a unique form "signup or login" with email and password fields on the main page, and then either directly logging in, or redirecting to a more detailed form to continue with signup process. Or there could simply be a login form on the instance homepage :)

* Second, when I discovered Mastodon, I had never heard about it before and just came across a link to a Mastodon instance. The description on this homepage is great and gives a good idea of what Mastodon is. But then I discovered it was decentralized and each instance has some specificities. But I could not find a way to have some access to the public content of an instance, without an account.

So, I suggest that the timeline (best would be the federated timeline, but that may be technically difficult so let's just say the instance timeline for now) could be publicly browsable, such as the timeline on Twitter is accessible without account. I think this would be a great incentive for users to create an account, and would help people decide how they feel about a particular instance.

Thanks!
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jeepfromoil** [comment]
It would also be nice to list the "rules" that are enforced by the moderators/admins of the instance. E.g:

- Which content/behavior is considered unacceptable
- What's banned
- The list of instances it's connected to
- The ToS and privacy policy
- How it's being paid for: subscriptions, donations...

**Comment by mkody** [comment]
@jeepfromoil This is usually done by the instance owner in the "about this instance" page.

**Comment by forresto** [comment]
I think the instance timeline is more interesting to see what's public in other communities.

**Comment by barijaona** [comment]
@jeepfromoil : yes, the rules are generally listed in the "about this instance" page, but once you are logged in, it is not easily accessible

**Comment by James-Firth** [comment]
In addition to @jeepfromoil's idea I think it'd be good to include some of that information in an API-accessible way so services that want to list many instances have a standard way of grabbing that data. 

(Though that may be out of scope, I'll search and see if there's an issue for this idea)

**Comment by Shnoulle** [comment]
about https://github.com/tootsuite/mastodon/issues/1142#issuecomment-292522913 : it must be before create account : really : you must have a clear contract `what can you do here, and can you see all fediverse or only partial` :)

**Comment by Gargron** [comment]
Oh - we can probably close this? New landing page since 1.5 has a prominent login link, displays a preview of the timeline, and there is also more accentuation on what makes the particular instance unique.
