### ISSUE TITLE
show local timeline logged out

### ISSUE THREAD

**Issue by yukulele** [tootsuite/mastodon#1143]
It's not possible to show local timeline without be logged on an instance, I don't want to sign up on each instance to show content.

Home page should show local timeline (or, like twitter, 'trending content', or something else)

**Comment by wxcafe** [comment]
This problem is already mentionned in #1142, let's keep the discussion there if possible :)

**Comment by forresto** [comment]
@wxcafe that seems like a broader issue, I'd vote for just this part of it.

**Comment by wxcafe** [comment]
Closing since it's a duplicate of #1053
