### ISSUE TITLE
406 on user Atom feeds

### ISSUE THREAD

**Issue by fenwick67** [tootsuite/mastodon#11453]
Atom feeds were removed in https://github.com/tootsuite/mastodon/pull/11247 

The users/:username pages still reference it, and it sends a 406 status code which doesn't make sense either.

### Expected behaviour

Following the link in the page header  (`<link href="https://mastodon.social/users/Gargron.atom" rel="alternate" type="application/atom+xml">`) on https://mastodon.social/@gargron, I would expect the Atom feed to exist. Historically I have used this to make [Mastofeed](https://mastofeed.com) work.

### Actual behaviour

Visiting https://mastodon.social/users/Gargron.atom returns a HTTP 406 error. I have tried changing the Accept and Accept-Encoding headers to no avail.

### Steps to reproduce the problem

visit https://mastodon.social/users/Gargron.atom in a web browser, using Postman, or CURL.

### Specifications

Version (per page footer): v2.9.2

**Comment by Gargron** [comment]
The link still being there is a mistake but you can use the RSS version instead for the same purposes

**Comment by fenwick67** [comment]
The RSS feed has a lot of missing info (no boosts or replies or pagination), I'm probably going to read the activitypub outbox instead, unless there are reasons not to do that.

**Comment by Gargron** [comment]
Making content harder to scrape with zero information loss outside of the primary ActivityPub protocol is actually intentional. Sorry
