### ISSUE TITLE
Position should be remembered when browsing follower/following lists

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#11452]
### Steps to reproduce
1. Go to your profile in Web UI
2. Click on either "Followers" or "Following" to view who is following you / who you are following
3. Load any other profile
4. Go back

### Expected behaviour
- Position should be remembered

### Actual behaviour
- The list is forcibly scrolled to the bottom of the first page from the API

### Specifications

mastodon.social (master)

**Comment by Gargron** [comment]
Can't reproduce. Multi-column or single-column version?

**Comment by trwnh** [comment]
Multi-column, Firefox 69, Linux.

**Comment by trwnh** [comment]
Demo: https://i.imgur.com/ExlYZRC.mp4

**Comment by trwnh** [comment]
This also happens in the single column as well. I think it's a pagination thing.
