### ISSUE TITLE
CW / Pin visible in all headers, even where inapplicable

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#11467]
mastodon.social master -- can suddenly see CW reveal icon in header, even for threads that have no CW. Can also see menu icon with "pin" option, although clicking this just makes the column disappear.

![image](https://user-images.githubusercontent.com/10606431/62379562-d4723400-b50c-11e9-9b23-99529cdf294b.png)

**Comment by Cassolotl** [comment]
It would be cool if the "pin" stayed and just worked, I'd love to be able to pin a toot with a poll in it. (Related to #9920 and #7970 and #3858 maybe.)
