### ISSUE TITLE
[Feature suggestion] Anti-spam whitelist

### ISSUE THREAD

**Issue by IzaliaMae** [tootsuite/mastodon#11462]
### Pitch

Add a whitelist to the anti-spam feature for accounts that may trigger it, but you know are harmless

### Motivation

Sometimes I need to toot the same thing multiple times to test something I'm developing and I don't wanna have to turn off the anti-spam feature just to not get the account I'm using silenced. I'm sure there are other reasons, but this is the only one I can think of atm

**Comment by Gargron** [comment]
Unsilencing an account whitelists it so it never triggers the spam check again
