### ISSUE TITLE
Custom gif emojis from Pleroma are not federated

### ISSUE THREAD

**Issue by stom79** [tootsuite/mastodon#11466]
### Pitch
Pleroma uses gif for custom emoji but Mastodon only uses apng, as a result, gif emojis from Pleroma remain in full text (shortcode) instead of displaying the image.

### Motivation
This currently brings a poor UX and users think that applications are broken. It could be nice to have at least non animated images.

**Comment by trwnh** [comment]
also i think only underscores are recognized? custom emoji with dashes in their identifier will not be displayed.
