### ISSUE TITLE
Omniauthable produces invalid email addresses

### ISSUE THREAD

**Issue by SISheogorath** [tootsuite/mastodon#11472]
### Expected behaviour

When using SAML to login to a Mastodon instance, it should allow the user to sign up/login.

### Actual behaviour

When logging in your endup on a white page with an error message saying:

`ActiveRecord::RecordInvalid (Validation failed: Email The e-mail address is invalid):`

### Steps to reproduce the problem

1. Setup SAML with Mastodon
2. Have an Account with the same email address on Mastodon already
3. Try to sign in using saml that references an account with the same email address

### Specifications

Current stable release from docker hub: tootsuite/mastodon:v2.9.2

I figured out it's caused by this line which produces invalid email addresses when the user's email address already exists.

https://github.com/tootsuite/mastodon/blob/964ae8eee593687f922c873fa7b378bb6e3e39bb/app/models/concerns/omniauthable.rb#L66

Why this is not a PR? Because I'm not really sure what way you want to go to fix it.

**Comment by Gargron** [comment]
Is it supposed to allow signing in to the existing account then?

**Comment by SISheogorath** [comment]
I would say yes. SAML auth is something that a server admin configures and usually they are in control of both endpoints or at least trust the SAML endpoint. (But that would be more of a feature request than a bug report)

What I consider a bug here is the fact that the code seems to intent to produce a temporary email, when the there is already a user with the same email address. But this code fails to be successful because the temporary email address that is generated by the code, fails to be a valid email address and is therefore rejected by the DB model.
