### ISSUE TITLE
Images larger than 1280² pixels are downsized to a white image when using the Tor Browser

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#11496]
### Expected behaviour

When an user uploads an image larger than 1280² pixels it should be downsized, on Firefox, Chrome and the Tor Browser.

### Actual behaviour

When an user uploads an image larger than 1280² pixels using the Tor Browser, the image is downsized to a white image.

_Note: This is about servers on the normal web, but accessed via the Tor Browser (so not hosted as a hidden service). I didn't tested this on a Mastodon server as a hidden service._

This is tested on Todon.nl and Mastodon.social. On regular browsers like Firefox or Chrome (using the normal web) the images are uploaded fine.

### Steps to reproduce the problem

Install the most recent Tor Browser and upload a large image (e.g. 2592x1952). The image will be white.

### Specifications

- Mastodon v2.9.2 (Todon.nl + Mastodon.social)
- Tor Browser 8.5.4 on Ubuntu Linux 19.04

**Comment by ThibG** [comment]
The image being resized client-side, this would most probably be the Tor Browser disallowing reading from a `canvas` element.

I guess what we can do is add something to check whether the image read from the canvas is completely white, and if so, return the original one (so, discard the resizing result)?

**Comment by Gargron** [comment]
I found this: https://www.reddit.com/r/TOR/comments/9tmq6y/disable_tor_browsers_canvas_data_access_popup/

It seems that the Tor Browser asks you for permission to use the canvas data. And there is a config setting, off by default, that makes it auto-decline canvas usage. So it seems like it's not something we need to fix, but a misconfiguration of the browser, or failure to allow usage?

**Comment by jeroenpraat** [comment]
Thanks! Tested it and it works!
