### ISSUE TITLE
Login gives error code 422, but it was actually successful

### ISSUE THREAD

**Issue by mkody** [tootsuite/mastodon#1150]
I'm running with 4e41cd9ab8f51120d558b70528b163c98993be53

When logging in with correct credentials, we're greeted with this message:  [[image](https://cloud.githubusercontent.com/assets/843787/24799198/41009eb8-1b9a-11e7-96be-f1778760704b.png)]

But if we press back or go to the homepage, we're redirected to the app.
And yup, cookies are enabled.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by lutoma** [comment]
Same issue here, first thought it was a configuration issue, but I couldn't find anything suspcious.

**Comment by Technowix** [comment]
You can revert to https://github.com/tootsuite/mastodon/commit/624a9a7136159d460228a0c2f5df18a9ead3b7f2, temp fix :°

**Comment by lutoma** [comment]
Downgrading to that commit worked indeed, thanks!

**Comment by mkody** [comment]
Fixed with 4b62118
