### ISSUE TITLE
search API call not returning any statuses, ever.

### ISSUE THREAD

**Issue by phryk** [tootsuite/mastodon#1152]
'statuses' of the content search API call (/api/v1/search) never seems to actually return any statuses.
Hashtags and accounts are returned without problems.

Steps to reproduce: https://mastodon.social/api/v1/search/?q=e

Since "e" is the most frequently used character, we should be getting pretty much all statuses here, shouldn't we?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Not bug. Intended behaviour. `statuses` returns a status if you search for it by permalink URL (it does a network resolve). There is currently no full-text search on all statuses.

**Comment by phryk** [comment]
Would you turn this into a low-priority feature request, then?

**Comment by cphuntington97** [comment]
Adding my voice to request full text search :-)
