### ISSUE TITLE
DigitalOcean One-click installer (Intel MDS vulnerability)

### ISSUE THREAD

**Issue by JayHoltslander** [tootsuite/mastodon#11541]
> Nicholas Wade [of DigitalOcean] [commented](https://ideas.digitalocean.com/ideas/DO-I-471) 09 Jul 17:49
>
>> It looks like the [DigitalOcean] [one-click [Mastodon] app](https://marketplace.digitalocean.com/apps/mastodon) has been removed, any reason?
>
>We're awaiting a security update from the vendor of this 1-Click App after the Intel MDS vulnerability CVE recently. The vendors support forum can be found here in case you'd like to make a comment there: https://discourse.joinmastodon.org , Github here https://github.com/tootsuite/mastodon/issues

Was [told by @MatodonProject on Twitter](https://twitter.com/MastodonProject/status/1159895025716776960?s=20):
>We are aware of the issue, and it is currently being worked on. I'm afraid I can't give a timeline as to resolution, but we hope to fix the problem soon.

I searched for an existing issue here on Github that I could watch for updates on this but couldn't find one.

So I wrote this. Apologies if it's a duplicate.

**Comment by koyuawsmbrtn** [comment]
The one-click-deployment droplet is back again: https://marketplace.digitalocean.com/apps/mastodon

This ticket can be closed
