### ISSUE TITLE
Wildcard domain block

### ISSUE THREAD

**Issue by alexgleason** [tootsuite/mastodon#11558]
### Pitch

I'd like the ability to create a wildcard domain block so all subdomains on a domain can be automatically blocked. Eg, `*.4chan.icu` to block `d1m5auvb55pl.4chan.icu`, `7n9x11u5mz0ud7.4chan.icu`, etc

### Motivation

An attacker is targeting my server by generating subdomains. A wildcard block will require the attacker to have a lot of domain names, making this attack more expensive and less feasible.

**Comment by Gargron** [comment]
Blocks automatically extend to subdomains. No wildcard is necessary.
