### ISSUE TITLE
Publish valid replies in "replies" collection [JSON][ActivityPub]

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#11568]
### Pitch

Currently only self-replies are included. I propose including all valid replies.

### Motivation

The current thread construction behavior is flawed, and intersects with a lot of issues that have presented long-standing UX issues: #8565, #9409, #10916, #11503 (particularly https://github.com/tootsuite/mastodon/issues/11503#issuecomment-518748342 as it interfaces with #9409), #10865, and possibly more.

Including all valid replies is the first step to being able to query `replies` (which is needed for the above issues).

**Comment by ThibG** [comment]
I would strongly advise against using such information for determining whether a reply is accepted by the originating server, because:
1. This can't work for private replies
2. This is highly inefficient
3. You'll hit issues regarding caching and processing delays

That being said, Mastodon already epxoses that information… or rather it is supposed to. Indeed, it is supposed to list public self-replies first, then include other public replies in subsequent pages. But it seems that:
1. It is inconsistent in advertising subsequent pages
2. Subsequent pages include the internal identifier of replies instead of their URI

I will attempt fixing these issues

**Comment by trwnh** [comment]
I agree it's not a good long-term solution, but it's needed in the short term and is one of the least disruptive things that could be done. Technically we have the following options for discovery:

1. Show replies that are delivered to you
2. Show replies that are in the `replies` collection

Option 1 is what we currently do, and option 2 should be supported with #11582 presumably. Yes, it is "inefficient", but it is necessary to solve the problem of multiple authority -- by deferring to the origin server as authoritative.

I would actually argue that, for a thread where none of the ancestors are known, that fetching all the ancestors would be inefficient, yet it is done anyway. However, recursion upward or downward could be capped at a certain depth limit, just like Reddit, with the user having to explicitly request parents via "Show full context" or replies via "Show more replies". How necessary is it to always see *all* ancestors or descendants? In fact, this could be handled by the API, again similar to Reddit, by adding a parameter to request only a certain contextual depth (I think it's `?context=n` where n = depth to crawl upwards and downwards).

How could we solve the problem of multiple authority by sticking with Option 1? Well, you would need some valid token to prove that the reply was authorized, perhaps a signed Accept. Or you would make the origin server responsible for signing and redistributing replies it receives. But both of those are currently breaking changes to the way things are currently done, so it would be useless to require authorization of replies because every single current reply would be rejected.

As for private replies, yes, the parent server could leak the existence of private replies, or we could say that private replies should only be delivered. The issue with private objects is more an issue of cross-domain authorization. Perhaps you could OAuth into another instance with your current account, or perhaps you could embed something like OpenWebAuth to be able to load HTML pages with a one-time token that private statuses should be displayed.
