### ISSUE TITLE
Integrate getting media from online services (Google Photos, Amazon, OneDrive, etc.)

### ISSUE THREAD

**Issue by foomachi** [tootsuite/mastodon#11564]
Integrate getting photos from online services (Google Photos, Amazon, OneDrive, etc.)

I'm not sure what is possible using a 3rd part app, but will look into that

### Pitch

When inserting media into a toot, you are taken to a File Open dialog.  Instead (or in addition), there should be a way to browse media libraries such as PixelFed, Google Photos, Amazon Photos, OneDrive, etc.

### Motivation

Most people do not store their photos and videos on their local device, but post them to some cloud service, so it would be nice to be able to upload directly from those sources, rather than requiring that they first be downloaded locally, then inserted into a toot with the file dialog.

**Comment by trwnh** [comment]
This should be handled at a filesystem/OS level, not app level.

**Comment by foomachi** [comment]
I'm new to mastodon, so perhaps I should wait until I'm more familiar with how things work, but I was just basing my comment on the current behavior using Chrome on Windows.  When you click to add media, you get a File Open dialog, it isn't a good experience.  Windows doesn't have any built in support for accessing images from cloud services other than OneDrive (for which the File Open dialog still doesn't provide a very good experience).  I would think we could build better support in the application.

**Comment by trwnh** [comment]
Yes, but that's a problem in Windows. You can use applications such as Google Drive Sync, or ExpanDrive, or Mountain Duck, or any number of similar utilities for accessing remote storage.

**Comment by Gargron** [comment]
I'm sorry but I don't see us integrating all these commercial services into Mastodon.

**Comment by Failure404** [comment]
Being able to just insert a link to a remote picture source would be sufficient. No need to integrate all these services. It would make Mastodon a better place for content publishers.
