### ISSUE TITLE
Resizing images in web client is broken

### ISSUE THREAD

**Issue by muesli** [tootsuite/mastodon#11567]
One used to be able to drop 6000x4000px images onto the web-client and it would resize the image to an acceptable resolution for you. This isn't working anymore right now, at least on mastodon.social:

"422 - 6000x4000 images are not supported"

# Expected behaviour

Resize the image automatically, as before.

### Actual behaviour

Image gets rejected.

### Steps to reproduce the problem

Drop an image with a resolution greater than 4000sqpx onto the web client.

**Comment by nightpool** [comment]
uh oh, bad regression

**Comment by milindpatel63** [comment]
This issue is still there.
I am running mastodon in Docker.
Images larger than 6000x4000 throws error in WebUI and are not rescaled.

**Comment by hajovonta** [comment]
I had the same issue today. Tried to upload an animgif, and the server complained with the 422 error and that the image with certain resolution is not supported.
