### ISSUE TITLE
Feature request: Mute by keyword

### ISSUE THREAD

**Issue by wolfteeth** [tootsuite/mastodon#1158]
As a user I would like to pre-emptively mute toots containing certain keywords when viewing the public timelines or my personal timeline.

The purpose is to avoid toots on topics the user finds bothersome or sensitive, without muting users whose other toots they may find interesting. The blacklisted keywords would be available in a list which can be viewed and edited by the user.

Would be nice to have a per-keyword toggle to change whether toots that mention the user and a blacklisted keyword together would be muted. My intuition is the default behavior is NOT to mute mentions - if they're having a conversation they may have opted in to the topic.

**Comment by wxcafe** [comment]
You can already do this, but it only accepts regular expressions. This should *probably* be improved

**Comment by wolfteeth** [comment]
I think understanding regex is a pretty big lift for nontechnical users.

I'd like to see a persistent list of muted keywords with some kind of filtering or flagging at the API level so it follows the user onto different apps.

**Comment by wxcafe** [comment]
yeah that was my point ^^

**Comment by anon5r** [comment]
I agree to this feature.

My idea is:
1. Save muted keyword list to preferences by each users.
2. Client side load registered mute keyword list from server.
3. Client will be apply muted keywords to Local timeline and Federated timeline and  mute matched toots.

**Comment by clarcharr** [comment]
IMO there should be an option to block behind a CW instead of outright removing posts.

**Comment by sandhawke** [comment]
Yes, something like 'semi-mute', where all the matched things get shown like a CW post.

If we'd had this feature before CWs, it might be semi-muting '#nsfw' and '#spoilers' and a few other things per personal preference would work better than CWs.

**Comment by ruthtillman** [comment]
As someone who's good with Regex, I'm aware of what a struggle it is for most people to sort through. A simple keyword muting would be a good start. I like some of the semi-mute/CW ideas above, but I think what would be most useful at this point (particularly with all the newer users) is a simple filter that functionally imitates `(Thing|Thing2)`.

**Comment by Cassolotl** [comment]
Even if it stayed more or less as it is now but it said "words and phrases to block, separated by commas" that would be a big improvement.

**Comment by deutrino** [comment]
List of dupes I found of this issue:

- #694 (muting keywords from timelines)
- #1158 (muting keywords from timelines)
- #2453 (muting hashtags and keywords from timelines)
- **#3848 (muting by keywords, improve the accessibility beyond "lern2regex noob", listed as a priority for version 2.1)**
- #4081 (specifically requesting that muting by keyword work in CWs as well)
