### ISSUE TITLE
post from rss feed, poor man's bot

### ISSUE THREAD

**Issue by nikoss** [tootsuite/mastodon#11587]
How I imagine it (as a user):
+ You create a new account in mastodon.
+ You mark this account as a bot, or semi-bot.
+ A new field/option appears:

   (optional)
   Enter an RSS feed (?) [<--help link/icon]:
   _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
   Renew every |_ _| hours.

+ You enter your website's rss feed.
+ One more field appears:

   (optional)
   Enter another RSS feed:
   _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
   Renew every |_ _| hours.

+ And so on...
+
+ The stream of these rss feeds gets posted as toots, automatically.

Similar to issue #10134 (?), but somehow different.

Why? 
+ So that people can follow a website's rss feed; Like (or not), comment, etc... basically, interact with it.

+ So that people can find search results from rss feeds, as well (I think that established search engines completely ignore them).

+ So as to popularise rss feeds, both, for website publishers, as well as for visitors.

+ So I can publish my website's feed, without having any programming knowledge, root access to a server, set up of python environment (?), etc, etc.

**Comment by nightpool** [comment]
Since mastodon uses activitypub, an open protocol, it's easy for developers
to make one-off applications like this, without it needing to be supported
by mastodon proper. Someone has already built this tool for RSS feeds! you
can use it here: https://bots.tinysubversions.com/convert/

**Comment by hermann-san** [comment]
@nightpool  unfortunately the tool link death. 
The only RSS2Mastodon bot I know is this one, but it's not so easy to use. 
RSS to Mastodon https://gitlab.com/chaica/feed2toot

and a few other useful bridges
Twitter to Mastodon https://github.com/mashirozx/tweet2toot
RSS to Mastodon bot  https://birdsite.slashdev.space/
lots of apps to RSS (also via Yunohost): https://github.com/rss-bridge/rss-bridge
