### ISSUE TITLE
"Portuguese" language naming is inconsistent and potentially mean

### ISSUE THREAD

**Issue by Pizzacus** [tootsuite/mastodon#11602]
Let's look at the language picker in the settings.

![image](https://user-images.githubusercontent.com/7659613/63228077-89d00780-c1ee-11e9-9f6a-95640e77f8b2.png)

This image shows that Brazilian Portuguese is referred to as **"Português do Brasil"** (Portuguese of Brazil) whereas the Portuguese Portuguese version is just referred to as **"Português"**.

I would like to suggest to rename them to "Português (Brasil)" or "Português (Portugal)" or "Português (BR)" and "Português (PT)" respectively.

There are three reasons why I think this change should be made.

## 1. Respect

**It's pretty mean to imply that Portugal is the "default" Portuguese.**

I can understand how it may feel normal to a foreigner, after all, it is "Portugual", the country has the name of the language and that's where it's from.

However, there are more Brazilian Portuguese speakers than Portuguese Portuguese speakers. This would be comparable to a website suggesting "English (USA)" and just "English" for the UK.

By always putting the country, we avoid being opinionated altogether. And we're clearer, too.

## 2. Consistency

There's another locale that is separated in two like this. Traditional Chinese.

![image](https://user-images.githubusercontent.com/7659613/63228149-838e5b00-c1ef-11e9-863c-76e6798f8590.png)

The first one says "繁體中文（香港）", that's "Traditional Chinese (Hong Kong)". The second says, you guessed it, "繁體中文（臺灣）" which means "Traditional Chinese (Taiwan)".

Even though Taiwan is the closest descendant of ancient China of the two, it doesn't get to be the "default" Traditional Chinese.

It's probably the best to display the locales like that, putting the region in parenthesis after the locale name.

## 3. Proper language tagging

Since the locale is just called "Português", the corresponding lang tag is `pt`, while the Brazilian one uses `pt-BR`. This tag lets the browser know what language the page is in.

Without the country code for Portugal, **the browser is unable to know whether the page is written in Brazilian Portuguese or Portuguese Portuguese.** Which can confuse page readers, spell checkers, and dictionaries.

And the difference really matters. Portuguese Portuguese and Brazilian Portuguese are not like British English and American English. You can really tell at a glance which one it is as they differ significantly. They require different speech synthesis and spell checking.

Now you may say that most software that deals with languages like that can use heuristics to detect which dialect is being used. And this is true, they often do. However, the point of the `lang=` tag was to AVOID those heuristics being needed in the first place. **Relying on the language detector to figure it out is regressive.**

-------------------------------

So it should be tagged `pt-PT`and named "Português (Portugal)" instead.

**Comment by stevenroose** [comment]
I have nothing against changing `Portugues` to `Portugues (Portugal)`, but as a Flemish person (Dutch speaking Belgian), I don't agree with the offense you seem to take in this.

Portugal is where Portuguese comes from and if the language you speak in Brazil is now no longer the same as Portuguese from Portugal, doesn't mean the definition of Portuguese suddenly changes. As a Flemish, I actually much prefer our language to be called `Flemish` instead of `Dutch (Belgium)`, because even though officially the language is the same, it sounds differently.
That being said, I live in Portugal with a Portuguese girlfriend and I know that Brazilian is much more different from Portuguese than Flemish is from Dutch.

If you're proud of your language and culture, you should desire your language to be renamed to `Brazilian` instead of `Portugues do Brasil`.

**Comment by Pizzacus** [comment]
I don't want to change the "definition" of the Portuguese language.

It's just that you have two dialects, and both are just as "legitimate" as the other. So you need to distinguish them, and you can't really say that Portuguese Portuguese is the "default" Portuguese, because that would change the definition of Portuguese to Brazilian people.

Like, that's the thing, neither Portugal nor Brazil can claim to have the "real" Portuguese. So I think arbitrarily choosing one can be a bit mean.

Also, I would argue that this doesn't even change the "definition" of Portuguese. Every locale in software is associated with a certain country. But for most languages, the country associated with the locale is implied.

Take Italian for instance. You don't need to specify which country an Italian locale would be associated with. When you write "Italian", the implication is "Italian (Italy)". If Portuguese wasn't spoken in Brazil, you would just write "Portuguese" and everyone would understand this implies "Portuguese (Portugal)".

However, since it IS spoken differently in Brazil, you have to be specific. So you're not changing the definition of the language, you just have to be a bit more specific to clarify which dialect you're talking about.

------------------

And yes, maybe it would be nice if Brazilian Portuguese could be recognised as a different language. They are actually usually delt as entirely different locales most of the time. And typically different people will work on each variant. They are different languages in most pratical ways, but nope, they have the same ISO 631-1 code. They didn't even get a different ISO 631-3 code. When different German dialects got like 10 codes to distinguish them.

This is slightly frustrating, but "Portuguese (Portugal)" and "Portuguese (Brazil)" will do for now…

**Comment by Pizzacus** [comment]
Wait this doesn't fix the issue with the language code being "pt", which doesn't give any clue to the browser about what the country is.

Maybe change it too to " pt-PT"?

**Comment by allnamesaretakeningithub** [comment]
**pt-PT** (For European Portuguese) and **pt_BR** (Brazilian Portuguese) are the two quite common codes to tell them both apart.
