### ISSUE TITLE
Direct-message design

### ISSUE THREAD

**Issue by luxcem** [tootsuite/mastodon#1160]
Direct messages should look different from other messages, for example a striped background

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by pbradz** [comment]
I agree, it's sort of terrifying to see all your DMs when you look at your timeline if logged in. Maybe a grey background would be nice, so that the DMs would be visible but would recede a bit into the background.

It would also be nice to have a toggle to hide them entirely in "Settings."

**Comment by rtucker** [comment]
This was implemented awhile back -- bumping this so that it can be marked as Resolved ^^

**Comment by nightpool** [comment]
Thanks for the heads up! yeah, as of a couple months ago all direct messages have a lighter "highlighted" background.
