### ISSUE TITLE
How can I receive a feed of all posts and favorites from an instance?

### ISSUE THREAD

**Issue by raymestalez** [tootsuite/mastodon#1161]
Hi! I am writing an app for Mastodon, and I need it to receive a stream of all the posts and all the favorites from an instance, the way other instances in the federation do. 

I have tried using an API, but it only returns 40 items, and I don't think this is the right way to do things. I want to be able to communicate with instances the way they communicate between each other.

Can you help me to figure how I can accomplish this?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
This is very late and may not be useful to you at all, but just in case anyone else has the same question: Gargron is considering *Federation relays #7399*.
