### ISSUE TITLE
Desktop Client using Electron

### ISSUE THREAD

**Issue by Meadowcottage** [tootsuite/mastodon#1163]
# Desktop client using Electron?
> Been using it for a while using some other side projects and was wondering if you currently had any plans to look into [Electron](https://electron.atom.io) as a framework for creating a desktop client?
(I know you're currently VERY busy working on the platform itself and see this as in no way a priority for Mastodon)

If you don't have any plans to do so, I am happy to try and create a 3rd party client.
The only issue being at the moment with your login system, it would mean having to log in every time the app is loaded.

Just an idea I had and thought would be kinda cool for later in time 😄 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
You can create the Electron app as a real, independent app, and make it use the OAuth2 authorization flow.

**Comment by sorin-davidoi** [comment]
If #3052 and #3243 get merged, the main web app will work offline and have push notifications (the two main advantages of a web app wrapped in Electron).

**Comment by Gargron** [comment]
I suppose that there is no real benefit in having this open as an issue on this repository. Feel free to create an app like that.
