### ISSUE TITLE
Remove request to google fonts

### ISSUE THREAD

**Issue by stemy2** [tootsuite/mastodon#11636]
### Pitch

It would be a good idea remove the request to google fonts, or at least explain how can i do it myself (i searched and didn't found).

### Motivation

It is not mandatory (i know it, i block it with a browser add-on without any problem) and not privacy friendly.

**Comment by Gargron** [comment]
Mastodon does not call to Google Fonts. Where did you encounter such a request?

**Comment by stemy2** [comment]
This is really strange. I don't see the request in the developer's tools, but my umatrix add-on says that it blocked a request to google fonts.

**Comment by nightpool** [comment]
this is probably related to some customization applied by the admin of your instance. there's nothing related to google fonts in stock Mastodon
