### ISSUE TITLE
Featured collection lacks @context

### ISSUE THREAD

**Issue by marrus-sh** [tootsuite/mastodon#11649]
Loading a user's featured collection (e.g., <https://mastodon.social/users/Gargron/collections/featured>), one can see that the `@context` does not specify Mastodon's extensions, despite containing toots which might potentially use them.

I'm not sure why this is, but am assuming it is an oversight.

**Comment by nightpool** [comment]
definitely a bug, we did a thing recently where we manually pared down the contexts for different routes to avoid sending the same full extension context everywhere even if we weren't using it, looks like we overlooked this one.

**Comment by ThibG** [comment]
This is actually the case for all collections, including the outbox and replies collections

**Comment by ThibG** [comment]
From what I understand, what happens is that context extensions are supposed to be included in parent serializers thanks to the code in `config/initializers/active_model_serializer.rb`, but that only accounts for when the serializer to use is set in the association's options (so, not when it's dynamic like in that polymorphic association)
