### ISSUE TITLE
Search doesn't look into users' bios

### ISSUE THREAD

**Issue by klmr** [tootsuite/mastodon#1164]
### To reproduce:

* Go on “search”
* Enter hashtag that occurs in users’ profiles (e.g. `#rstats`)
* Hit return

### Observed result:

* 1 result is shown (“#rstats”); clicking on it leads to a result list of statuses that include the hashtag.

### Expected result:

* In addition to the above, user profiles that have the hashtag in the description should be displayed (e.g. https://mastodon.social/@klmr)

I looked through the code, and it seems that [this line](https://github.com/tootsuite/mastodon/blob/08faeedff7838e339488cfcddf02d95241557ffb/app/services/account_search_service.rb#L5) in `AccountSearchService` may be the culprit (but I’m not sure):

```ruby
return [] if query.blank? || query.start_with?('#')
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by klmr** [comment]
Oops. No idea how that happened.

**Comment by wxcafe** [comment]
Search doesn't look into users' profiles afaict, so this result is consistent.

**Comment by wxcafe** [comment]
@klmr if this answers your question, please close the issue

**Comment by klmr** [comment]
Correct, apparently it doesn’t. It would be nice to have though; or is there another way of searching peoples’ profiles?

After all, one of the primary ways of finding people to follow is by common interest, which is why people put hashtags into their profiles (on Twitter) in the first place.

**Comment by Gargron** [comment]
This has been a deliberate design choice to prevent people from search accounts to harrass by identifiers (such as LGBT for example)
