### ISSUE TITLE
Humblr.social (Bug / Error)

### ISSUE THREAD

**Issue by aandre1** [tootsuite/mastodon#11650]
I am having an error uploading videos to humblr.social Every time I upload a video it gives me either error 504 or 500. The video file size used to be 40mb then it was upgraded to 100mb and I have tried to upload videos smaller then 40mb or smaller then 100mb. It keeps giving me that same error. I tried using chrome, firefox and safari. I reset my router, (even though its a brand new month old router) Ive tried my phone, Ipad, desktop computer etc. Nothing changes, the same 504 and 500 error. Please fix this error or someone please help! Absolutely love the humblr platform but if this issue doesn't get fixed I will have to move onto a different platform, please help! This error has been happening about the past 4 days.

**Comment by nightpool** [comment]
We're not associated with humblr.social, they just happen to use mastodon, like many other servers. Please contact your instance admin for individual technical assistance.

My guess is that either humblr.social has added a custom limit to the amount of total media uploaded by an account, or the format of the video you're trying to upload isn't supported by mastodon.

**Comment by aandre1** [comment]
I tried contacting the admin 3 times and no response, I did get an email saying that my humblr account was limited, but that doesn't make any sense because when everyone left tumblr to go to humblr.social for "nsfw content" Their shouldn't be any limitations, and as for the video file I tried smaller videos, larger videos, .mp4 .mov which uploaded perfectly fine before, I tried to email back to the email I got from him and no response, hopefully he gets back otherwise I'm moving onto a different platform, thanks for getting back.

**Comment by nightpool** [comment]
This seems to be an internal Humblr moderation issue, closing and locking.
