### ISSUE TITLE
Security verification failed.

### ISSUE THREAD

**Issue by isati** [tootsuite/mastodon#1165]
I'm getting a lot of 'Security verification failed. Are you blocking cookies?' errors on my instance. Reloading the page sometimes resolves this, sometimes doesn't. I'm not sure where the problem lies - anyone else experience this and resolve it?
* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by isati** [comment]
Forgot to mention that this occurs only when logging in/out..

**Comment by davidcelis** [comment]
I'm also experiencing this issue as of today, and I'm unable to log into my instance

**Comment by alexgleason** [comment]
I had the same issue earlier. Make sure Postgres is actually doing what it's supposed to. It wasn't for me.

If you're using Docker, shell into the container first:

```
docker exec -it mastodon_db_1 /bin/bash
```

then get into postgres. you can do this directly if you're not using docker.

```
su postgres
psql
```

Then try to select your user by email address.

```
SELECT * FROM user WHERE email='myemail@example.com';
```

Did it return your user? If not, you are experiencing the same [bizairre problem](https://blog.candlewaster.co/postgres-select-not-working-wont-pull-row-by-constraint/) I faced earlier. You will need to make a postgres backup with `pg_dump`, create a new db container and import the data with `psql`.

**Comment by gitjeff2** [comment]
I have experienced this issue as well.

I signed up to <https://mastodon.technology> as a new user. When I received my verification email I got this error when I clicked the confirmation link. That said, I was eventually able to gain access. I visited my Mastodon node on a separate tab and it loaded just fine, I was fully authenticated.

**Comment by nanma80** [comment]
I see this issue now. I'm on mastodon.cloud. I see this error page on my PC and Safari on iOS. Although I can get around it by refreshing in the browsers, it blocks me on the app Amaroq because I can't refresh there.

**Comment by datagutt** [comment]
Also experiencing this issue. Tried to make a backup using ``pg_dump``, removing the db-container, recreating it using "docker-compose up -d", then restoring it like Alex did, but this doesn't seem to make any difference to me.

How are people setting up volumes for postgres in docker-compose... Maybe i configured that wrong.

**Comment by alexgleason** [comment]
@datagutt did you run the select statements and see if you were getting output?

**Comment by davidcelis** [comment]
@alexgleason You have a little typo in that query (you didn't pluralize the table name); it should be:

```sql
SELECT * FROM users WHERE email='myemail@example.com';
```

Anyway, this correctly returns my user account, but I'm still not able to log in.

**Comment by datagutt** [comment]
@alexgleason After fixing the typo in your SQL statement, it looks like i am getting the correct output.
My issue is different from yours, then. Looks like this bug can be triggered by multiple reasons :)

**Comment by Technowix** [comment]
Got this on my side too :confounded:

**Comment by Wonderfall** [comment]
I think it's coming from here : https://github.com/tootsuite/mastodon/commit/e3a3422a65901c71ec3ff4a2729309c441660d63 https://github.com/tootsuite/mastodon/commit/624a9a7136159d460228a0c2f5df18a9ead3b7f2 is not impacted.

**Comment by gitjeff2** [comment]
In case it's relevant, this issue also occurs when attempting to pair 3rd party apps, such as [Tusky](https://play.google.com/store/apps/details?id=com.keylesspalace.tusky) with a user's account on an instance. Repeated attempts to pair result in success... eventually.

**Comment by Technowix** [comment]
@Wonderfall method worked for me too :)

**Comment by mkody** [comment]
I guess I didn't give my issue a good name, lol. Related: #1150

**Comment by Rushyo** [comment]
User-side workaround for me experiencing this issue was to clear cookies after each logout.

**Comment by JantsoP** [comment]
Issue has not been solved. Did an git pull from the master and issue stays: https://puu.sh/vdbEm/8b72f81502.png

**Comment by technoboy10** [comment]
Pulling from the master branch or reverting to 624a9a7 did not work for me - I still get the "Security verification failed" error whenever I log in. (Using the Heroku deploy script fwiw)

**Comment by isati** [comment]
I've updated to master and it has mostly been resolved but I still get this error time to time but only when logging out now.

**Comment by DSAndreee** [comment]
Just pull from the master and it works now :)

**Comment by ericblade** [comment]
Confirm fixed #1150 #1236 at login. I don't see what @isati says about it happening at logout, but have only tried a few times.

**Comment by archaeme** [comment]
I think this bug has reappeared in 2.2.0rc2, though it appears that it also affects granting app permissions and editing the profile. Interestingly enough this only happens in Chrome and not Firefox.

**Comment by Technowix** [comment]
#6366 did the job

**Comment by Mennaruuk** [comment]
Still getting this error on mastodon.online. I had to delete cookies for the site to successfully log in.

**Comment by Fatima-yo** [comment]
Hello people, I am getting this same issue when trying to login using Amaroq on iPhone
Any hints will be highly appreciated

**Comment by wikigazer** [comment]
It is Thursday 10th November 2022 at 21:08 GMT. 

I am getting this "Security verification failed. Are you blocking cookies?" quite often today. 
Browser is Mozilla Firefox 106.0.5 (64bit) (most recent update) accessing https://mstdn.social/on PC running Linux.
When error happened, the URL in Firefox was showing as: "https://mstdn.social/auth/sign_out".

Google search for "Security verification failed. Are you blocking cookies?" brought me here.
screenshot: https://i.imgur.com/UWq4Pxu.png

**Comment by VityaSchel** [comment]
I stumbled upon this error when tried to login/logout/signup with Tor browser.
The solution for me was to add `skip_before_action :verify_authenticity_token` to Auth::RegistrationsController and Auth::SessionsController in app/controllers/auth directory
