### ISSUE TITLE
Unlisted custom emojis show up on autocompletion

### ISSUE THREAD

**Issue by sftblw** [tootsuite/mastodon#11669]
### Expected behaviour

Unlisted custom emojis should not be shown on autocompletion panel.

### Actual behaviour

Unlisted custom emojis shows in the emoji autocompletor.

### Steps to reproduce the problem

1. Unlist already added custom emoji.
2. Try to autocomplete it
3. It shows up

### Specifications

- tag: v2.9.3 (twingyeo.kr)

- firefox 70.0a1 (2019-08-24) (x64), Edge

I'm trying to rename non self-explanatory custom emojis to more self-explanatory one, by unlist old emojis and add new one. But after working on a few number of such emojis I relized that unlisted custom emoji shows up on the emoji autocompletion dialog.

![image](https://user-images.githubusercontent.com/5573010/63684575-3423dc80-c838-11e9-933b-baed108bf08f.png)
![image](https://user-images.githubusercontent.com/5573010/63684600-41d96200-c838-11e9-8d0e-1ab4282e7aec.png)

**Comment by Gargron** [comment]
No, they are supposed to show up. They're only supposed to not show up in the picker.

**Comment by sftblw** [comment]
So then Can I think there's no way to *rename* custom emojis while preserving compatibility of old toots?
