### ISSUE TITLE
Create a new account with my old username

### ISSUE THREAD

**Issue by Elderking1986** [tootsuite/mastodon#11660]
HI, I hope this is the right place to ask this.

A while back I deleted my account on purpose. I wasn't thinking back then and I've regretted it ever since. Earlier I tried making a new account with my old username but wasn't able to, saying its already taken. Is there anyway possible to have my old username Elderking1986 freed up so I can create a new account using my old name?  I would like to start using Mastodon again but I would like to use my old username since its a username that I use for everything else.

If you need my email I used I can provide that, or anything else to verify who I am.

Thanks.

**Comment by trwnh** [comment]
You would have to contact your old admin to manually recreate your account for you.

**Comment by ykzts** [comment]
This is the intended correct behavior, not a Mastodon issue.
