### ISSUE TITLE
Blank/malformed 404 response on user page

### ISSUE THREAD

**Issue by Kjwon15** [tootsuite/mastodon#11672]
### Expected behaviour

Shows elephant friend error page on `/@a@a.a`
![image](https://user-images.githubusercontent.com/5047683/63704238-91825280-c865-11e9-8869-220a47d42b6f.png)

### Actual behaviour

Shows blank 404 page or File not found error on browser
![image](https://user-images.githubusercontent.com/5047683/63704228-87f8ea80-c865-11e9-9562-7d0300d6d907.png)

### Steps to reproduce the problem

go to `/@username@some.tld`, even `/@a@a.a` works.
For example, https://mastodon.social/@a@a.a

### Specifications

On mastodon 2.9.3 (stable)

**Comment by Gargron** [comment]
The server responds with `Content-Type: #<Mime::NullType:0x00007feb8d2faa28>`
