### ISSUE TITLE
possibly useless CSS ??

### ISSUE THREAD

**Issue by marrus-sh** [tootsuite/mastodon#11689]
`containers.scss` gives styles for a `.static-icon-button` in lines 756–764. <https://github.com/tootsuite/mastodon/blob/fda437a02088ac114fecb69e3b1e52f495a2dd9a/app/javascript/styles/mastodon/containers.scss#L756-L764>

However, searching the code, I canʼt find anywhere where this class name is used. Is this leftover from a refactor?

**Comment by Gargron** [comment]
Yes, probably. There might be a lot of dead CSS in there...
