### ISSUE TITLE
PuSH delivery optimization

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#1168]
Assuming the presence of PubSubHubbub subscriptions to a user, every time a user toots, a `PubSubHubbub::DistributionWorker` is queued into Sidekiq with specifically that status. A XML payload is rendered, and delivery is queued for all subscribers.

Successive toots queue separate distributions. But as long as the first distribution job is *enqueued* and has not started executing yet, it would be best to *append* to it. This would minimize the number of network requests to subscribers' callback URLs.

I have looked into using the [sidekiq-merger](https://github.com/dtaniwaki/sidekiq-merger) gem for this purpose, but encountered weird errors.

**Comment by austinfromboston** [comment]
@Gargron Are you open to a solution that would use the database to store the XML payload, so the redis queue would just contain a DB id?  Or are you looking to get a performance advantage by modifying the redis queue in place?

**Comment by Gargron** [comment]
If you look at PubSubHubbub::DistributionWorker, it calls an inline render method that is normally ready to accept a list of stream entries, but in this case, it's just one.

If sidekiq-merger would actually work, it would be trivial to turn that worker's arguments into a list, and voilà, intended effect is achieved.
