### ISSUE TITLE
Animated emojis should animate by default

### ISSUE THREAD

**Issue by alkjalkja** [tootsuite/mastodon#11721]
### Expected behaviour

When opening a post's page in the browser, or without changing any settings, animated emojis should be animated.

### Actual behaviour

Animated emojis require hovering over them to be animated, ruining many posts' experience.

### Steps to reproduce the problem

1. Find/make a post with animated emojis
2. Open it in the browser (outside of the frontend)
3. Emojis aren't animated unless hovered over

### Specifications

Any

**Comment by Cassolotl** [comment]
Animated things like videos, gifs and emojis are autopaused by default for accessibility reasons.
