### ISSUE TITLE
Mastodon ignores the "Show today's trends" ("Trending now") option

### ISSUE THREAD

**Issue by KNTRO** [tootsuite/mastodon#11738]
### Expected behaviour

I should not see the _Trending now_ section at my profile

### Actual behaviour

It still displays, despite my chose

### Steps to reproduce the problem

1. Go to the Mastodon's [_Appearance_](https://mastodon.social/settings/preferences/appearance) menu > section _Discovery_ > checkbox _Show today's trends_
2. Uncheck that box
3. Click on the _SAVE CHANGES_ blue button
4. Go back to the profile and check if the _Trending now_ section appears (if not appears —which should be the right behavior—, close the web browser, run it again, open your profile again and you're likely to see it there

### Specifications

Mastodon web v2.9.2 (yep, the very same mastodon.social is still using that version… 🙄)

**Comment by Gargron** [comment]
Are you talking about the public profile page?
