### ISSUE TITLE
ZWNJ is not supported in hashtags

### ISSUE THREAD

**Issue by ahangarha** [tootsuite/mastodon#11761]
### Expected behaviour

I expect ZWNJ to be included in hashtag. I need whole of "نرم‌افزار" be a hashtag.

### Actual behaviour

By now, Hashtag only includes non-ZWNJ characters. So in the given example above, only "نرم" gets converted to link.

### Steps to reproduce the problem

You just add #نرم‌افزار and see how it only includes نرم as hashtag.

### Specifications

It is a general bug in Mastodon

**Comment by nightpool** [comment]
you're gonna have to fight this one out with @marrus-sh, i have no idea what the correct behavior should be

**Comment by trwnh** [comment]
FWIW Twitter/Instagram/etc do the same, and the general behavior of users is to use underscores between words in joined languages.

**Comment by ahangarha** [comment]
This is not correct. Both twitter and Instagram support ZWNJ in hashtag. It is needed in Persian. ِYou may check [this link from twitter](https://twitter.com/search?q=%23%D9%86%D8%B1%D9%85%E2%80%8C%D8%A7%D9%81%D8%B2%D8%A7%D8%B1_%D8%A2%D8%B2%D8%A7%D8%AF&src=typed_query).

**Comment by Gargron** [comment]
So is this just about including `\u200C` in the hashtag regex or are there more characters than that?

**Comment by ahangarha** [comment]
I believe it only only this is needed to be there.

**Comment by marrus-sh** [comment]
late reply but concur that both ZWJ and ZWNJ should be included in hashtags; it is WORD JOINER and ZWSP which should not

i know some people used ZWJ/ZWNJ as hashtag-breakers in some cases but i have always advocated use of WJ instead

**Comment by marrus-sh** [comment]
(A more lengthy response:

U+2060 WORD JOINER (WJ) and U+200B ZERO WIDTH SPACE (ZWS) [in addition to U+FEFF ZERO WIDTH NO-BREAK SPACE (BOM), but it should never be used for this purpose] are invisible format characters for controlling the **breaking** (as in, line­‑breaking) of text. Although there might conceivably be use­‑cases for controlling (preventing) line­‑breaking in hashtags, this is generally a layout concern which should be controlled through higher­‑order mechanisms (CSS) and not a linguistic issue (something inherent to the hashtagʼs meaning). As invisible layout characters, they are good candidates for things like "preventing a `#` from opening a hashtag by placing WJ after it", which is primarily a layout concern.

U+200C ZERO WIDTH NON-JOINER and U+200D ZERO WIDTH JOINER (which should probably also be added to the regex if not present @Gargron) are invisible format characters for controlling the **ligation** (how ligatures form) of text. This *does* have linguistic meaning in many scripts, including Arabic (and Persian), Devanagari, and Emoji (👩‍💻). So it *should* be allowed in hashtags and does form a significant and meaningful aspect of their value.)
