### ISSUE TITLE
Pleroma instances should be defederated

### ISSUE THREAD

**Issue by alcaapa** [tootsuite/mastodon#11816]
### Expected behaviour

Mastodon should not federate software that compromises user privacy such as Pleroma.

### Actual behaviour

Mastodon federates with Pleroma instances, putting vulnerable and LGBT users especially at risk.

### Steps to reproduce the problem

1. Install Mastodon (or join an existing instance that hasn't modified the software to make it safer)
2. Try to interact with a user/post on a Pleroma instance
3. The interaction is successful, and they can also interact with you

### Specifications

Any

**Comment by ThibG** [comment]
Any fediverse software can be modified to not respect user privacy settings, and Pleroma's defaults in that area are not significantly different from Mastodon's.

Blocking Pleroma instances would be a hack that wouldn't make anyone a service. Closing this issue.
