### ISSUE TITLE
Web interface bug on Firefox for Android

### ISSUE THREAD

**Issue by jfmcbrayer** [tootsuite/mastodon#1182]
On Firefox for Android, the web interface for Mastodon has a small display problem. Normally, on a newly opened page in FF, you have the address bar on top; when you scroll down, the address bar scrolls out of the way. In the Mastodon web app, the page does not scroll, and so the address bar will never scroll out of the way.

Furthermore, the page is apparently sized based on the size of the page *with the address bar scrolled away*. This means that the bottom of Mastodon's canvas is always off the screen on Firefox for Android.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Haven't heard anything about this from anyone else for a year, so will close, maybe it's resolved
