### ISSUE TITLE
Allow seeing the view activity of posts

### ISSUE THREAD

**Issue by MirceaKitsune** [tootsuite/mastodon#11825]
On Twitter users are able to see the number of views their posts got by clicking a View Tweet Activity button. Mastodon currently doesn't offer such a mechanic: You can see who favourited or reblodded a toot, but not how many people clicked on it or had the post load in their timeline.

If it's possible to efficiently keep track of each time a post is accessed by other users, it would be nice if a chart showing the estimated view activity on posts was implemented. This can help users better understand which content attracts the most attention or what their practical audience is.

**Comment by ThibG** [comment]
I am unconvinced by the usefulness of such a feature, and the decentralized nature of Mastodon makes it impossible to properly implement anyway.

**Comment by MirceaKitsune** [comment]
I think that as a general rule, it's useful to be able to know how many people are seeing your posts. Most systems today offer this possibility, from other social media platforms to art sites.

I'm not sure what the best approach to implementing it would be. My initial idea was: When someone accesses your post, they send a signal to the server indicating they viewed it, which causes their username to be added to a list into the post itself.

It could be similar to how favourites already work, though perhaps reversed (stored in the account of the poster rather than that of the viewer). You can already see a list of everyone who favourited or boosted a post... I figure the same system could be reused for recording views.

**Comment by trwnh** [comment]
Could be done with the View and/or Read activity, but no implementation currently supports sending or receiving them AFAIK

**Comment by ThibG** [comment]
The privacy and performance implications of making the author's instance aware of who has read their toots aren't worth it

**Comment by MirceaKitsune** [comment]
Privacy is a good point, there might be unintended side effects there. Sounds like a good thing to put up for a vote? I don't care all that much for it, just find it useful if it could be done in some form.

**Comment by Gargron** [comment]
I think as far as art goes favourites and boosts are a lot more important.
