### ISSUE TITLE
Automatically unfollow accounts that haven't been active for a given number of months

### ISSUE THREAD

**Issue by MirceaKitsune** [tootsuite/mastodon#11834]
In the relationship manager (https://instance.social/relationships) I'd like to suggest a filter based on the last active dates of accounts. Alternatively we could have a separate shortcut to unfollow every account that hasn't been active for X amount of months.

I'm suggesting this based on personal experience: There are many cases when I end up following someone, but a few months later the account silently becomes abandoned. Those dead accounts end up clogging the follower list, and going through them manually to see when they were last active can be an errand. I think it would be useful to be able to pick a number of months and unfollow every account that hasn't posted or boosted anything for that amount of time (eg: one year).

**Comment by Gargron** [comment]
The relationship manager already has these functions.

**Comment by MirceaKitsune** [comment]
Oh... it's probably not in 2.9.3 then. Sorry about that: Will check it out in the next release.

**Comment by Gargron** [comment]
![grafik](https://user-images.githubusercontent.com/184731/64906171-32389500-d6e3-11e9-8627-4c5a31908958.png)
