### ISSUE TITLE
People on other instances cannot remote follow me on my instance.

### ISSUE THREAD

**Issue by colegleason** [tootsuite/mastodon#1185]
When people from another instance (mastodon.cloud or mstdn.io) try to follow me (cmu.party), they receive "422 Remote account could not be resolved". When trying to press the button on my web profile, they get the error page. Where would I look in the logs to find this issue?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. (There are other issues about remote follow, but this seems to be the reverse issue)

**Comment by colegleason** [comment]
This might be related to #960, as I also see "Could not find the required redirect URL for your account" when trying to remote follow myself from another instance.

**Comment by mjankowski** [comment]
Are you using "@username@your.instance" or just "username@your.instance" (the latter will work, the former will probably error)?

**Comment by colegleason** [comment]
neither seem to work

**Comment by colegleason** [comment]
I replaced my nginx config with the one in the Production guide exactly and this works now. My SSL redirect may have been misconfigured.

**Comment by sys0dm1n** [comment]
I had the same issue, by removing let's Encypt location block everything worked fine:
`        location ~ /.well-known {`
`                allow all;`
`        }`
I hope this might help others with my case.

**Comment by anieto** [comment]
Sys0dm1n where exactly would find and remove the letsencrypt block? I'm having the same issues listed above and none of the suggestions have helped

**Comment by sys0dm1n** [comment]
@anieto Usually this should be in your Apache/Nginx Virtualhost configuration file under sites-enabled/ folder.
If you have used Let's Encrypt, what are the steps that you went through ?

**Comment by sincoew** [comment]
Thanks  colegleason and sys0dm1n, 
I had the same issue and fix now.

**Comment by fweng322** [comment]
@sys0dm1n provided the solution.  Also, the /.well-known/ alias for Let's Encrypt works only in http:// not in https://, so I just removed the alias in https settings and this problem is solved.  Thanks.
