### ISSUE TITLE
Touchscreen scrolling UX doesn’t work as expected

### ISSUE THREAD

**Issue by michelmcbride** [tootsuite/mastodon#11866]
Short version: Mastodon should follow the UX pattern used commonly by other website where touch-scrolling on the fixed sidebars will scroll the primary timeline.

Details:
When viewing Mastodon in desktop browsing mode, such as on a tablet or touchscreen laptop, you can only scroll the timeline by touching and scrolling on the timeline itself and not on the fixed sidebars. Standard UX for sites with a scrollable timeline and fixed sidebars (as used by Twitter, Facebook, Instagram, etc) is that touch-scrolling on the sidebars (Ie having thumbs on left or right of screen in natural holding position) will scroll the primary timeline.

The UX pattern allows for not only less effort by accommodating holding a tablet naturally and scrolling without constantly adjusting one’s hand, but prevents the hand from obscuring the content that the user wants to read as they scroll. It would Improve the browsing experience of all users of Mastodon on tablets and touchscreen laptops.

**Comment by ThibG** [comment]
I believe this is has been the behavior for single-column mode for a while in master now, or am I mistaken?

**Comment by Gargron** [comment]
Oh, this has already been changed, you just need to wait for 3.0 to come out.
