### ISSUE TITLE
API endpoint for follow requests count

### ISSUE THREAD

**Issue by nolanlawson** [tootsuite/mastodon#11870]
There is [an API endpoint to get the current follow requests](https://docs.joinmastodon.org/api/rest/follow-requests/) (for a locked account). It would be nice to also have an endpoint to just return the _count_ of follow requests (not the full list).

### Pitch

This is useful as a performance improvement for a UI that shows the unread follow request count, but doesn't need to fetch the full list. (E.g. https://github.com/nolanlawson/pinafore/pull/1493)

Something like `/api/v1/follow_requests/count` which just returns a single integer would be convenient!

### Motivation

Apps that show a follow request count would benefit from the performance improvement, especially if the account has a lot of unread follow requests (account data is pretty verbose). In addition, it could return a number greater than the limit of 40, which is useful information for the user.

**Comment by Gargron** [comment]
Fixed by #11975:

> Add `follow_requests_count` to `GET /api/v1/verify_credentials`
