### ISSUE TITLE
Community/Instance Timeline

### ISSUE THREAD

**Issue by lanodan** [tootsuite/mastodon#1189]
As there is instances with their own community, I think something like the community timeline(all public posts of a server/instance) of other fediverse software would be nice.

Also to respect privacy only fully public post should appear in it.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jeepfromoil** [comment]
Already in discussing https://github.com/tootsuite/mastodon/issues/1053

**Comment by yiskah** [comment]
This is already what the local timeline is? i'm confused

**Comment by trwnh** [comment]
@yiskah But you have to sign up for those instances before you can see the local timeline. This is likely suggesting the ability to view the local timeline while logged out... per #1053 and #1143

**Comment by wxcafe** [comment]
Closing since this is a duplicate
