### ISSUE TITLE
a way to "clean" right column's history and/or home menu link

### ISSUE THREAD

**Issue by minirop** [tootsuite/mastodon#1190]
When we click on several non-linked toots, we have to click the same number of times on the "back" link.

Maybe doing something like cleaning all history when click on in one of the other columns but keep it when clicking in the 4th one (like on the reply of a toot).

Also linked but not really, is a way to go back to the "home" on this column too (I use it for local timeline, but it's annoying to have to click "back" many times after reading a few toots).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Exagone313** [comment]
You just have to click on the buttons on top-left corner.

**Comment by wxcafe** [comment]
@minirop does the answer by @Exagone313 up there answer your question? If it does, please close this issue

**Comment by minirop** [comment]
it does, it's just that having those buttons on the other side of the page make them a little "painful" to use.

**Comment by wxcafe** [comment]
Okay then let's reopen as a UI enhancement request

**Comment by Gargron** [comment]
The column uses browser history to navigate (it changes based on URL in the address bar). Therefore, it's not possible to "reset" or "erase" the history without doing so through browser tools. You could e.g. open Mastodon in a new tab for a fresh start. I do not think this is solveable in any other way.
