### ISSUE TITLE
My account has been silenced? why?

### ISSUE THREAD

**Issue by Pixelworldnetworkofficial** [tootsuite/mastodon#11945]
We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please use one of the resources below:

- https://discourse.joinmastodon.org
- #mastodon on irc.freenode.net

Hi mastodon team,

I enquired about my account a few days ago and got a response from an admin saying to post the link to the page I was having issues with.

I responded and found my account was silenced.

I use a vpn as I use opera browser and really want my account back this may be the issue?

If not can some explain why I have been banned, silenced when I followed the terms of service and only literally posted once.

Kind regards

**Comment by trwnh** [comment]
You should contact your admin for more information. This is the issue tracker for the Mastodon software, not a support forum for individual sites.

**Comment by nightpool** [comment]
As @trwnh said, this is the issue tracker for the Mastodon software project. We're not associated with individual instances run by third-party admins except for mastodon.social, and this isn't an appropriate place to have moderation discussions either for third-party instances or mastodon.social. Please contact your individual admin to talk to them about their decision.
