### ISSUE TITLE
Index-Only Scans is not used in Status.reblogs_map

### ISSUE THREAD

**Issue by non117** [tootsuite/mastodon#11940]
### Expected behaviour

`Status.reblogs_map` uses `index_statuses_on_reblog_of_id_and_account_id`.

### Actual behaviour

When `Status.reblogs_map` is executed, not `index_statuses_on_reblog_of_id_and_account_id` but `index_statuses_20190820` is used.

### Steps to reproduce the problem

```ruby
[1] pry(main)> Status.select('reblog_of_id').where(reblog_of_id: status_ids).where(account_id: account_id).reorder(nil).explain

```

#### output

```sql
 Index Scan using index_statuses_20190820 on statuses  (cost=0.28..8.61 rows=1 width=8)
   Index Cond: (account_id = '118'::bigint)
   Filter: (reblog_of_id = ANY ('{102836162140938736,102836161542888641, ... }'::bigint[]))
(3 rows)
```

### Specifications

* commit: 50b927633
* macOS 10.14.4, psql (PostgreSQL) 11.5
* CentOS Linux release 7.7.1908, psql (PostgreSQL) 11.5

In my instance, I avoided this problem by `unscoped`.

**Comment by Gargron** [comment]
Fixed by #11982
