### ISSUE TITLE
I can't see non-pinned toots in my own instance

### ISSUE THREAD

**Issue by stemy2** [tootsuite/mastodon#11946]
### Expected behaviour

I created a new profile on my new instance and i imported some datas from another account, including the subscriptions. The expected behaviour was the ability to see all their toots.

### Actual behaviour

The only toots i can see in my instance are the ones that are pinned.

### Steps to reproduce the problem

1) Create a mastodon instance.
2) Failing unknowingly something (i still don't know what) in the config.
3) Subscribe to some users.

### Specifications

Commit: Master (installed from mastodon_ynh)
Server: Yunohost

**Comment by trwnh** [comment]
Duplicate of #34 -- your new instance doesn't know about the old statuses.

**Comment by stemy2** [comment]
OK, sorry for the pebkac.
