### ISSUE TITLE
About 'tootctl preview_cards remove' behavior. remove previewCard image only or itself?

### ISSUE THREAD

**Issue by Neustrashimy** [tootsuite/mastodon#11956]
### Pitch

In v3.0.0rc1, 'tootctl preview_cards remove' will delete PreviewCard's image only.
If repost 'image deleted' URI, Mastodon will shows text-based title and description in toot, but will not re-fetch image again.

In contrast, if delete PreviewCard itself, Mastodon will not show deleted PreviewCard in toot,
but when repost URI then  Mastodon will fetch PreviewCard again including image.

So, I want to select delete old PreviewCard's image only or itself by command-line switch.

### Motivation

It behaves differently depending on which one is deleted, recommended that admin can select it.

### Specifications

Mastodon v3.0.0rc1, Non-Docker

**Comment by Gargron** [comment]
If link was last-posted more than 14 days ago, it should be refetched (along with image). Perhaps it hasn't been 14 days since last post in your case? But we could make it re-fetch image if it's missing.
