### ISSUE TITLE
Heroku deployment fails on task DB:MIGRATE

### ISSUE THREAD

**Issue by KaSt** [tootsuite/mastodon#11952]
### Expected behaviour
I expected the Heroku deployment to work

### Actual behaviour
The deployement fails in the postdeploy task: db:migrate

Migrating to AddInReplyToAccountIdToStatuses (20161202132159)
...
-- add_column(:statuses, :in_reply_to_account_id, :integer, {:null=>true, :default=>nil})
   -> 0.0065s
Scoped order is ignored, it's forced to be batch order.
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column statuses.deleted_at does not exist
LINE 1: SELECT  "statuses".* FROM "statuses" WHERE "statuses"."delet...
                                                   ^
: SELECT  "statuses".* FROM "statuses" WHERE "statuses"."deleted_at" IS NULL AND "statuses"."in_reply_to_id" IS NOT NULL ORDER BY "statuses"."id" ASC LIMIT $1
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:677:in async_prepare
...

### Steps to reproduce the problem

Deploy to Heroku using the "Official" button

### Specifications

Commit 5034418e2c41fbd51fc85458dd3fdba72a672625

**Comment by Gargron** [comment]
Out of curiosity, are you updating an instance that was last updated before December 2016?

**Comment by KaSt** [comment]
Thanks!
