### ISSUE TITLE
Mobile layout is awkward on larger screens

### ISSUE THREAD

**Issue by daprice** [tootsuite/mastodon#1195]
I'm seeing the single-column "mobile" layout on my iPad Pro, which makes everything seem awkwardly stretched. This is a 9.7 inch screen which (at least in landscape orientation) is more like a small laptop than a phone, so I don't think the page layout I'm seeing, which looks like it was designed for phones, is ideal.

Almost every element on the screen is disproportionately wider than it is tall, and there is a lot of wasted space, as seen in the following screenshots:

So much empty space that can never be filled:
![img_0213](https://cloud.githubusercontent.com/assets/3615519/24819575/c63f4f2e-1baa-11e7-8571-08adf998377e.PNG)

The image thumbnail in the toot here is particularly egregious:
![img_0214](https://cloud.githubusercontent.com/assets/3615519/24819576/c65de56a-1baa-11e7-9798-012b16284662.PNG)

Here's the menu stretched to cover a larger screen, wasting 80% of the space:
![img_0215](https://cloud.githubusercontent.com/assets/3615519/24819577/c65e2b2e-1baa-11e7-87b9-14527ffe9fe7.PNG)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by unarist** [comment]
+1: This also occurs on the desktop when I change the browser width to <=1024.

For example, 3 columns on 980px-1280px wide and 2 columns on 780px-980px wide screen would be usable for me. I think one column layout on those widths is too wide.

**Comment by Cassolotl** [comment]
Here's how it looks for me on my iPad:

![photo_2018-02-26_22-02-57](https://user-images.githubusercontent.com/6607512/36698103-e65b4efc-1b40-11e8-8612-cbbfb62bb063.jpg)

So I think this got fixed a couple of updates ago, and this issue can probably be closed now?

**Comment by daprice** [comment]
Yeah, I’m pretty happy with the newer column based layout and don’t think I've run into anything that’s weirdly stretched since it was introduced. Closing.
