### ISSUE TITLE
If not approved as a trend tag, hashtags that do not match exactly will not appear in the search results.

### ISSUE THREAD

**Issue by orlea** [tootsuite/mastodon#11960]
I am running in the following environment.
mastodon v3.0.0rc1, no ElasticSearch

If not approved as a trend tag, hashtags that do not match exactly will not appear in the search results.
Example: When searching with #masto, only #masto is displayed in the search results.

In v2.9.3, partially matching tags were also displayed in the search results.
Example: Searching with #masto will show both #mastodon and #mastodev in the search results.

I think this is a feature that was changed in this commit.
https://github.com/tootsuite/mastodon/commit/cc0a55cf9aead00e1cb044649f84c2187e0e4a35

The trend tag feature is a good feature, but
It's painful to open the admin page every time you look for similar tags that you don't know when to come.
Ordinary users can't do anything.

I want a feature that is approved by default, or that the approval status does not affect the search results.

Mostly machine translation. Sorry for my poor English.

**Comment by Gargron** [comment]
Appearing in search results is controlled by "listable" boolean + having been reviewed. It is not strictly bound to trends, but trends is when you would be asked to review a hashtag by the system.

The reason for only showing exact matches unless they are reviewed is that it's very easy to add inappropriate/harmful hashtags.

I am open to more feedback on this.

**Comment by Kjwon15** [comment]
So, Minor tags that has not been trended are also not listed on search?
IMO, I like old behaviour.

**Comment by Gargron** [comment]
Exact matches are always returned. If you search for "ff", you get "ff", but you don't get "ff_kill_all_puppies" unless that one has been reviewed.

**Comment by Kjwon15** [comment]
But only exact match are returned, that search function is not useful. (On a smaller instance, There is no trending tags)
I think listing inappropriate hashtag on search result is harmless (unlike trending)

**Comment by Kjwon15** [comment]
> Using ElasticSearch to index hashtags with edge n-grams and score
them by usage within the last 7 days since last activity.

If I understand correctly, which means old trended hashtags(eg, `#comiccon_2014`) are not listed on search?

**Comment by orlea** [comment]
>On a smaller instance, There is no trending tags
This is really true.
So it becomes a disturbing function.
So We need a switch function of the approved tag function (whether it affects the search result at least).

**Comment by Gargron** [comment]
Once again, it is not controlled by trends (`trendable`). It is controlled by `listable` + `reviewed_at`. You can review any hashtag at any time.

But, I realize this is a lot of work. Maybe `reviewed_at` requirement should go. But the problem is very real especially with autosuggest (which uses same API as search), for example, if you type "crea" going for "creativetoots", one of the top suggestions is a R18 keyword. Perhaps the requirement should be delegated to an API param, and remove the requirement from search form, but keep it in autosuggestions.
