### ISSUE TITLE
rbenv: bundle: command not found

### ISSUE THREAD

**Issue by stemy2** [tootsuite/mastodon#11968]
### Expected behaviour

I wanted to add the full-text search feature

### Actual behaviour

It stopped with the message 
```
rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  2.6.1
```
I installed ruby and rbenv, nothing changed.
### Steps to reproduce the problem

1. Follow the steps explained [here](https://docs.joinmastodon.org/administration/optional-features/#full-text-search)
2. Type «RAILS_ENV=production bundle exec rake chewy:upgrade»

### Specifications

Branch: Master

**Comment by Gargron** [comment]
When you run the command, are you in the Mastodon directory? e.g. /home/mastodon/live

**Comment by stemy2** [comment]
No, i wasn't.
Thanks.
