### ISSUE TITLE
Deactivated account redirect to settings shouldn't happen for static pages

### ISSUE THREAD

**Issue by marrus-sh** [tootsuite/mastodon#11969]
A user used to have an account on mastodon.social, which has now been deactivated (via migration to another account). They are now on instance.example. An account appears on the instance.example federated timeline from mastodon.social which they want to check out. They click to view its static profile page.

### Expected behaviour

They are able to see the static profile page for the account. Users with deactivated accounts should be able to view the same public content as users with no accounts at all.

### Actual behaviour

They are redirected to their settings page on mastodon.social, telling them that their account is deactivated. This is highly confusing behaviour which prevents them from viewing static profile pages unless they know to sign out of their old account.

**Comment by Gargron** [comment]
This is a good catch. I think it affects unconfirmed/pending/disabled accounts as well. No reason to redirect from public pages.
