### ISSUE TITLE
Filter out "fbclid=" and other tracking paramaters from links

### ISSUE THREAD

**Issue by pezcurrel** [tootsuite/mastodon#11989]
### Pitch

I think it would be great if mastodon filtered out "fbclid=" and other tracking paramaters from the links users paste into toots.

### Motivation

Tracking is evil and facebook too :)

**Comment by Gargron** [comment]
I think it should be the responsibility of the users posting the links. We can't know all tracking parameters in advance and if the software strips out a parameter which turns out to be a false positive, thereby breaking the link, it will be impossible to correct.

**Comment by pezcurrel** [comment]
> and if the software strips out a parameter which turns out to be a false positive, thereby breaking the link, it will be impossible to correct
I agree: a site could use a "fbclid" parameter for its own internal purposes.
