### ISSUE TITLE
Featured hashtags URLs conflicting with media tab

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#12034]
Media tab URL ends with `/media`. If you feature the hashtag `#media`, the URL ends with `/tagged/media`. The media tab URL only checks the ending so it takes precedence.

**Comment by ldexterldesign** [comment]
# Unexpected

https://mastodon.social/@ldexterldesign/102885282720043381 > https://mastodon.social/@ldexterldesign/tagged/media

# Expected

https://mastodon.social/@ldexterldesign/102885293318818009 > https://mastodon.social/@ldexterldesign/tagged/

Regards
