### ISSUE TITLE
Findability of search field on mobile layout

### ISSUE THREAD

**Issue by daprice** [tootsuite/mastodon#1206]
On the mobile single-column tabbed layout, the search field is only available in the "Compose" screen. Personally that's about the last place I'd expect it to be (I was actually trying to find the search field on a mobile device and didn't even look in the Compose tab until I tried later on a desktop machine and noticed it in that column). Some places that would make sense to me would be:

* in the Home tab, especially since the text in that tab tells you to "use search to get started and meet other users"
* at the top of the local and federated timelines, since those are the things you'd be searching within
* as an option in the hamburger menu
* as its own item in the top bar, since that's how the Twitter website and a lot of native iOS apps present their search forms

My apologies if this is a duplicate of another issue, as searching Github Issues for "search" returned every issue containing the below disclaimer, whether it pertained to the search feature or not.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Fixed by #7072 and #7077
