### ISSUE TITLE
Download button on audio player (possibly video player as well)

### ISSUE THREAD

**Issue by jackwilliambell** [tootsuite/mastodon#12076]
### Pitch

I would like to have a download button on audio player to allow people to download the audio file. This can be automatic (for every file) or by selecting an option when or after the file is uploaded.

### Motivation

I am planning to upload some music I created to my Mastodon instance with a Creative Commons license. It's nice that people can play the audio and share the link, but I would like to allow them to easily download the file as well so they can add it to their music library. I believe other audio file creators would feel the same way, although some (for example podcasters) might prefer to not have downloads.

### Current State

The uploaded file is available in the HTML for the audio player, so it appears the audio player is not using some kind of re-encoding scheme. Since that is the case it wouldn't increase the server load and a scraping program (or a savvy user) can already get the audio file name and download it the hard way.

**Comment by NimaBoscarino** [comment]
This sounds like a great idea to me! In case there’s interest, I’ve made a PR for it.

**Comment by ryliejamesthomas** [comment]
I'm also really keen on it. Works fine with the default audio player, so weird to see it absent here.

**Comment by NimaBoscarino** [comment]
This has been added, so is this issue good to close?

**Comment by ykzts** [comment]
Resolve with #12179
