### ISSUE TITLE
[SOLVED] Issue with Mastodon 3.0.0/Debian 10.1 and libprotobuf.so.10

### ISSUE THREAD

**Issue by Comendatore** [tootsuite/mastodon#12081]
Hi there,

After updated Mastodon to v3.0.0, when i launch : 
`RAILS_ENV=production bin/tootctl cache clear`
or
`RAILS_ENV=production bundle exec rails db:migrate`,
it returns me an error about libprotobuf.so.10 and fails to execute command.
Error is complaining about failing to load library libprotobuf.so.10.

### Steps to reproduce the problem
`#mastodon: cd live`
`#mastodon: git pull`
`#mastodon: git checkout v3.0.0`
`#mastodon: gem install bundler`
`#mastodon: bundle install --deployment --without development test`
`#mastodon: yarn install --pure-lockfile`
`#mastodon: RAILS_ENV=production bin/tootctl cache clear`

### Specifications

Debian 10.1
Mastodon v3.0.0
Yarn 1.19.0
Ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]
rbenv 1.1.2-4-g577f046

**Comment by Comendatore** [comment]
Issue solved by installing libprotobuf10_3.0.0-9_amd64 from old debian stable repository.
`root:~# wget http://ftp.fr.debian.org/debian/pool/main/p/protobuf/libprotobuf10_3.0.0-9_amd64.deb`
`root:~# dpkg -i libprotobuf10_3.0.0-9_amd64.deb`

Then retry `RAILS_ENV=production bin/tootctl cache clear` under mastodon user, it should works ;-)

**Comment by Comendatore** [comment]
I precise that the current version of libprotobuf in Debian 10.1 (stable) is libprotobuf17.

**Comment by jeroenpraat** [comment]
@Gargron @ThibG I had the same issue after updating Debian Stretch to Debian Buster (fortunately not on Todon.nl). 

Earlier I also had to reinstall Ruby 2.6.5 with `RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install 2.6.1` cause I received an error `error while loading shared libraries: libjemalloc.so.1 …`.

**Comment by ThibG** [comment]
This isn't a bug in Mastodon. If you're updating libs the gems are linked against, you'll have to rebuild those gems as well.

To do this, run: bundle install --force

**Comment by jeroenpraat** [comment]
@ThibG Maybe it's not a bug in Mastodon, it certainly is something people will experience when updating Debian to a new release.
