### ISSUE TITLE
Disable admin e-mails for reviewing hashtags

### ISSUE THREAD

**Issue by anampses** [tootsuite/mastodon#12083]
### Pitch
Option to turn off e-mail notification for admin and moderators to review new trending hashtags, or the ability to auto-approve all.

### Motivation

As admin I do not wish to receive e-mail about having to moderate hashtags, nor do I want to trouble my staff of moderators with having to deal with them. Please consider an option to disable receiving any and all notifications about having to review trends.

**Comment by anampses** [comment]
I’m a dummy, I found in the notifications section of preferences the option to turn off sending unreviewed hashtags that are trending.

**Comment by danorton** [comment]
@anampses Pray tell, where exactly is this setting? URL path?

**Comment by danorton** [comment]
@anampses Where is this? Can you post the URL path in admin?

**Comment by esureL** [comment]
For future mods & admins trying to get rid of the e-mails. :)

If your user has a moderator or administrator role, you'll have new options pop-up in your *personal* notification settings (red border):

![image](https://user-images.githubusercontent.com/117662336/213394601-2a0878c4-4ab7-4fe8-845f-3870efac66ca.png)

So every admin and moderator can decide for themselves, if they want the e-mails (and which they want).

However, it's useful to note that the "Always send e-mail notifications" option (orange border) only seems to apply to the standard options. So if the "New report is submitted" option is enabled, you'll receive an e-mail about it regardless whether you're actively using Mastodon at the moment.

Hope that helps. :)
