### ISSUE TITLE
Breaking changes in v3.0.0 for users with language 'pt'

### ISSUE THREAD

**Issue by hugogameiro** [tootsuite/mastodon#12082]
#11799 changes the language 'pt' to 'pt-PT'

I have notice that users that have set their language to 'pt' in the past (locale in the database) do not receive notifications (possible other issues) and there a lot of errors in Sidekiq because the language doesn't exist in https://github.com/tootsuite/mastodon/blob/master/config/application.rb

If the user affected goes to Preferences->Appearance and presses the 'save' button, the database gets updated and the issue is solved.

For admins, running something like `update users set locale='pt-PT' where locale='pt';` on the database should fix the issue.

Probably this could be done in a future release automatically. Unfortunately this is way outside my knowledge of Ruby and I don't feel comfortable creating a PR that touches the database.

Also, it wouldn't be a bad idea to mention in a future release that anyone using `DEFAULT_LOCALE=pt` should change it to either `DEFAULT_LOCALE=pt-PT` or `DEFAULT_LOCALE=pt-BR`.

**Comment by noellabo** [comment]
If you write within the knowledge of rails,
```
bin/rails r "User.where(locale: 'pt').in_batches.update_all(locale: 'pt-PT')"
```

**Comment by nightpool** [comment]
We should add code that maintains the backwards compatibility, probably a
migration for existing users and some special-casing for the DEFAULT_LOCALE
case
