### ISSUE TITLE
Clean install on v3.0.0 breaks remote follows

### ISSUE THREAD

**Issue by hugogameiro** [tootsuite/mastodon#12090]
On installing new instances using v3.0.0 I am unable to follow or be followed by a remote user (404). Also, when attempting to enable a relay a 404 page is returned.

There are no errors in logs even when RAILS_LOG_LEVEL is set to debug, it only shows the page returned a 404.

It could be something with my setup but I find it really strange because I am using exactly the same setup for other instances that I upgraded from v2.9.3 to v3.0.0 and that problem is not present. 

That is in fact my work around to install new instances, I do a clean install using v2.9.3 and then upgrade to v3.0.0 and it works. 

I am using Docker, so I don't think it's something on the code but I suspect there could be something in the database schema that is missing.

If someone did a clean install using v3.0.0 and not upgrade or migrate data from a previous version, please let me know. Any feedback if the remote follows work would be helpful.

**Comment by Gargron** [comment]
Are you properly running db:seed task (which is automatically part of db:setup)? (You should not use db:migrate on a fresh install as it's much slower than db:setup)

**Comment by hugogameiro** [comment]
I am running db:schema:load because the database needs to be created before on another server (I was running into some user errors when doing db:setup) but I will look into that.

**Comment by hugogameiro** [comment]
You are correct, it's an issue on my end. Doing `db:schema:load` and after `db:seed` solved the problem. Thanks
