### ISSUE TITLE
No URL in profile

### ISSUE THREAD

**Issue by kevinmarks** [tootsuite/mastodon#121]
This means that I can't link out to my own site, and that I can't do [distributed verification](http://www.kevinmarks.com/distributed-verify.html) using Mastodon.

Bonus points for checking the rel='me' link back in Mastodon itself

**Comment by noiob** [comment]
URLs in the Bio get turned into links for me, shouldn't that suffice? Bonus of being able to put multiple links and label them.

**Comment by kevinmarks** [comment]
```
<a rel="nofollow noopener" target="_blank" href="http://kevinmarks.com">kevinmarks.com</a>
```
I would rather this had

```
<a rel="me nofollow noopener" target="_blank" href="http://kevinmarks.com">kevinmarks.com</a>
```

And ideally removed the "nofollow" if the other end linked back with rel="me" - that was the point of th distributed verification. In effect you can add verified badges by checking bidirectional links

**Comment by tantek** [comment]
@noiob re: "URLs in the Bio get turned into links for me, shouldn't that suffice?" not quite, since I may include links to other things in my bio that aren't strictly just "me", like work, or other communities I'm a part of. 

A UI to designate one (or more) of those URLs being "my site" would help address this and provide a good hook for adding rel="me" to the markup.

**Comment by mjankowski** [comment]
Is the request here to add something like a "My website" URL field to the profile (separate from the bio, a new field JUST for a URL) ... or to add potentially N new URL fields (one for each place you might want to link to) with some name description for each.

So a profile for a person might have:

- Link - name: GitHub, url: https://github.com/username
- Link - name: Twitter, url: https://twitter.com/username

...and we'd put `rel=me` on all of these which were provided via the profile settings UI?

**Comment by kevinmarks** [comment]
Multiple with names is better, yes. That's what Google profiles does. A
single one is what twitter and github do.

**Comment by wxcafe** [comment]
see also glitch-soc/mastodon#24. I think we should pull the work that's already been done over on glitch-soc and work together towards making this a thing. If we wanted to use a different format on tootsuite then maybe we should have worked on this before glitch-soc started implementing it.

right now it works like this on the web UI 

![web-ui](https://cdn.discordapp.com/attachments/303883232464601088/362025894816251908/unknown.png) 

and like this in mainline, where it's not supported.

![app-ui](https://cdn.discordapp.com/attachments/303883232464601088/362029396074299402/unknown.png)
