### ISSUE TITLE
site_description is not correctly used.

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#12114]
public page sidebar and og description use `site_short_description || site_description`.
but  `/about` use only `site_short_description`.

if I set `site_short_description`  to empty for using `site_description` , 
then `/about` show empty site_short_description.

Where is site_description should be used?

I think `/about` shall use `site_description || site_short_description `.
priority is site_description  in this place.

**Comment by Gargron** [comment]
I think that many servers use `site_description` for too much text to be readable in the `/about` design (and in the sidebars, and in OpenGraph descriptions). While the help text of the setting always described it as a "paragraph", I have seen many examples of it being used for multiple paragraphs, with headlines and YouTube embeds. Maybe `site_description` should be removed to get rid of the confusion.

**Comment by tateisu** [comment]
At least inconsistent handling should be corrected

**Comment by Phroneris** [comment]
Then, will "Server description" field also be removed from the site settings page?
v3.0.1 still have it.
