### ISSUE TITLE
Improved anti-spam behavior

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#12113]
### Pitch

I think it's better to change the anti-spam feature so that it doesn't automatically silence the person.

~~I think it is better to divide it into an optional setting to silence automatically if possible (default off).~~
EDIT: I'm sorry, I think we shouldn't do this. I think that if some servers malfunction, the overall impression of Mastodon will deteriorate.

### Motivation

Because this feature performs wrong BAN action in the following cases:

- People who repeat mentions using messages formatted for greetings
- People who repeatedly sends the same content to the same person (for example, a joke)

I think it is important to introduce a function to combat spam. I agree with it.

But even if it's spam, I think we should avoid doing BAN actions for their account automatically.
I think it should be handled manually after the admin or moderator receives the report.

**Comment by Gargron** [comment]
A silence is not BAN, though. It is a fully reversible operation that is mostly invisible to observers.

You can disable the spam check in the admin settings, though.

**Comment by noellabo** [comment]
Automatic silence is irreversible. The mention that was actually supposed to arrive is not delivered and the conversation is interrupted. It will be in a limited state until the moderator is released, but this time cannot be recovered.

The ability to report suspected spam behavior is a great assist. We don't want to turn this off. Upon receiving the report, we would like to judge ourselves.

**Comment by mayaeh** [comment]
> A silence is not BAN, though. It is a fully reversible operation that is mostly invisible to observers.

Yes, that's right.
But their posts suddenly disappear in LTL, and I think this is distrusting to the Mastodon.
I think they are using mastodon as before.

> You can disable the spam check in the admin settings, though.

Yes, this is also true.
However, so far, I think there is a lack of advance explanation for server administrators about this feature.

I hope we can prevent this feature from being disabled.
