### ISSUE TITLE
Breaking typo in upgrade instructions in release text for v3.0.0

### ISSUE THREAD

**Issue by dariusk** [tootsuite/mastodon#12121]
The [release text for v3.0.0](https://github.com/tootsuite/mastodon/releases/tag/v3.0.0) says it uses Ruby 2.6.4, but the `.ruby-version` file in the release was updated to 2.6.5 in 9e3e3fa5ee3b63506. The installation instructions should be updated.

**Comment by ykzts** [comment]
> The recommended Ruby version has been bumped to 2.6.5. You can upgrade, or you can continue using the old version by overwriting the .ruby-version file with e.g. 2.6.1 or 2.5.3 which were recommended previously

Is it already fixed?

**Comment by dariusk** [comment]
It apparently has been fixed, closing!
