### ISSUE TITLE
Transcoding gif to mp4 fail

### ISSUE THREAD

**Issue by R0ckweb** [tootsuite/mastodon#1212]
Upload gif fail with error 500

Some trace : 

> [abd06ec7-b630-42fc-adfe-b30e46063cf5] Command :: file -b --mime '/tmp/6ffed90f7ec3f8a309a672a8afbb0ce320170408-20731-10kwm4t.gif'
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] Command :: identify -format %n '/tmp/6ffed90f7ec3f8a309a672a8afbb0ce320170408-20731-ef33zq.gif'
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Found ["avconv"], using: Avconv
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Found ["avconv"], using: Avconv
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: avconv -i "/tmp/6ffed90f7ec3f8a309a672a8afbb0ce320170408-20731-ef33zq.gif" 2>&1
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [paperclip] [transcoder] Transocding supported file /tmp/6ffed90f7ec3f8a309a672a8afbb0ce320170408-20731-ef33zq.gif
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding output parameter ["acodec", "aac"]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding output parameter ["strict", "experimental"]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding output parameter ["movflags", "faststart"]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding output parameter ["pix_fmt", "yuv420p"]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding output parameter ["vf", "scale='trunc(iw/2)*2:trunc(ih/2)*2'"]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding output parameter ["vsync", "cfr"]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding output parameter ["b:v", "1300K"]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding output parameter ["maxrate", "500K"]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding output parameter ["crf", 6]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: avconv -loglevel quiet -i "/tmp/6ffed90f7ec3f8a309a672a8afbb0ce320170408-20731-ef33zq.gif" -acodec aac -strict experimental -movflags faststart -pix_fmt yuv420p -vf scale='trunc(iw/2)*2:trunc(ih/2)*2' -vsync cfr -b:v 1300K -maxrate 500K -crf 6 -y "/tmp/6ffed90f7ec3f8a309a672a8afbb0ce320170408-20731-ef33zq20170408-20731-hepmjq.mp4"
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [paperclip] [transcoder] Successfully transcoded 6ffed90f7ec3f8a309a672a8afbb0ce320170408-20731-ef33zq to #<File:0x007ff5cc893680>
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Found ["avconv"], using: Avconv
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: avconv -i "/tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v.mp4" 2>&1
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Found ["avconv"], using: Avconv
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Found ["avconv"], using: Avconv
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: avconv -i "/tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v.mp4" 2>&1
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [paperclip] [transcoder] Transocding supported file /tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v.mp4
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding output parameter ["f", "image2"]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding output parameter ["vframes", "1"]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding input parameter [:ss, 0]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Adding output parameter [:vf, "scale='min(400\\, iw):min(400\\, ih)':force_original_aspect_ratio=decrease"]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] [AV] Running command: avconv -loglevel quiet -ss 0 -i "/tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v.mp4" -f image2 -vframes 1 -vf scale='min(400\, iw):min(400\, ih)':force_original_aspect_ratio=decrease -y "/tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v20170408-20731-1ljxk6j.png"
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] method=POST path=/api/v1/media format=html controller=Api::V1::MediaController action=create status=500 error='Av::CommandError: error while running command avconv -loglevel quiet -ss 0 -i "/tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v.mp4" -f image2 -vframes 1 -vf scale='min(400\, iw):min(400\, ih)':force_original_aspect_ratio=decrease -y "/tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v20170408-20731-1ljxk6j.png": Command 'avconv -loglevel quiet -ss 0 -i "/tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v.mp4" -f image2 -vframes 1 -vf scale='min(400\, iw):min(400\, ih)':force_original_aspect_ratio=decrease -y "/tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v20170408-20731-1ljxk6j.png"' returned 1. Expected 0
> Here is the command output: STDOUT:
> 
> 
> 
> STDERR:
> 
> ' duration=247.82 view=0.00 db=2.01
> [abd06ec7-b630-42fc-adfe-b30e46063cf5]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] Av::CommandError (error while running command avconv -loglevel quiet -ss 0 -i "/tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v.mp4" -f image2 -vframes 1 -vf scale='min(400\, iw):min(400\, ih)':force_original_aspect_ratio=decrease -y "/tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v20170408-20731-1ljxk6j.png": Command 'avconv -loglevel quiet -ss 0 -i "/tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v.mp4" -f image2 -vframes 1 -vf scale='min(400\, iw):min(400\, ih)':force_original_aspect_ratio=decrease -y "/tmp/c315f6dabf07b424e92008b3458f390a20170408-20731-1o00h4v20170408-20731-1ljxk6j.png"' returned 1. Expected 0
> Here is the command output: STDOUT:
> 
> 
> 
> STDERR:
> 
> ):
> [abd06ec7-b630-42fc-adfe-b30e46063cf5]
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] lib/paperclip/video_transcoder.rb:11:in `make'
> [abd06ec7-b630-42fc-adfe-b30e46063cf5] app/controllers/api/v1/media_controller.rb:13:in `create'
>

I'v tested first logged avconv command with debug , the result is an mp4 file with only 1 frame :/

> [fps @ 0x20914c0] 1 frames in, 1 frames out; 0 frames dropped, 0 frames duplicated.

The last avconv command (error triger) log : 

> [swscaler @ 0x7ffff38ad640] [Eval @ 0x7ffff38ad340] Undefined constant or missing '(' in 'force_original_aspect_ratio=decrease'
> [swscaler @ 0x7ffff38ad640] Unable to parse option value "force_original_aspect_ratio=decrease"
> [AVFilterGraph @ 0x191ee80] Error initializing filter 'scale' with args 'min(400, iw):min(400, ih):force_original_aspect_ratio=decrease:flags=0x4'
> Error opening filters!

Any idea ?

> $ dpkg -l | grep libav-tools
> ii  libav-tools                        6:11.8-1~deb8u1

Tested gif
![tumblr_n704k6qnzh1smcbm7o1_250](https://cloud.githubusercontent.com/assets/15029076/24822617/d1c8948a-1bf6-11e7-907e-eb59b61a76ce.gif)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by R0ckweb** [comment]
Solved by remove libav-tools and install ffmpeg from deb-multimedia repository !

**Comment by wxcafe** [comment]
I believe the fact that the docs explicitely says to use ffmpeg is good enough? This should probably be closed : it's not a bug in mastodon, and it only appeared because you used something that's not supported by the documentation.

**Comment by R0ckweb** [comment]
Yes of course, it can be closed !
The point is Debian 8 default source list not provide ffmpeg package !

**Comment by asterismo** [comment]
Hi, i compiled ffmpeg from repository using this config

PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --prefix="$HOME/ffmpeg_build" --disable-sse --disable-sse2 --disable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --pkg-config-flags="--static" --extra-cflags="-I$HOME/ffmpeg_build/include" --extra-ldflags="-L$HOME/ffmpeg_build/lib" --extra-libs="-lpthread -lm" --bindir="$HOME/bin" --enable-gpl --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree

And i'm getting this error when uploading a GIF (Error 500)

Dec 13 01:38:16 mastodon bundle[24938]: [2d769531-a0e9-429f-864a-06e16731b264] [AV] Running command: if command -v ffmpeg 2>/dev/null; then ech
o "true"; else echo "false"; fi                               
Dec 13 01:38:16 mastodon bundle[24938]: [2d769531-a0e9-429f-864a-06e16731b264] method=POST path=/api/v1/media format=html controller=Api::V1::M
ediaController action=create status=500 error='Av::UnableToDetect: Unable to detect any supported library' duration=114.45 view=0.00 db=2.14
Dec 13 01:38:16 mastodon bundle[24938]: [2d769531-a0e9-429f-864a-06e16731b264]
Dec 13 01:38:16 mastodon bundle[24938]: [2d769531-a0e9-429f-864a-06e16731b264] Av::UnableToDetect (Unable to detect any supported library):
Dec 13 01:38:16 mastodon bundle[24938]: [2d769531-a0e9-429f-864a-06e16731b264]
Dec 13 01:38:16 mastodon bundle[24938]: [2d769531-a0e9-429f-864a-06e16731b264] lib/paperclip/gif_transcoder.rb:108:in `make'
Dec 13 01:38:16 mastodon bundle[24938]: [2d769531-a0e9-429f-864a-06e16731b264] app/controllers/api/v1/media_controller.rb:13:in `create'

Any ideas?

**Comment by Gargron** [comment]
> Av::UnableToDetect: Unable to detect any supported library

This probably means the ffmpeg binary is not in $PATH..?

**Comment by asterismo** [comment]
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] [paperclip] Trying to link /tmp/RackMultipart20191214-25405-1ervill.gif to /tmp/64a7e1c5695edfae2bf7a68dfc59448920191214-25405-j1skop.gif
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] Command :: file -b --mime '/tmp/64a7e1c5695edfae2bf7a68dfc59448920191214-25405-j1skop.gif'
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] [paperclip] Trying to link /tmp/64a7e1c5695edfae2bf7a68dfc59448920191214-25405-j1skop.gif to /tmp/64a7e1c5695edfae2bf7a68dfc59448920191214-25405-s45gf5.gif
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] Command :: file -b --mime '/tmp/64a7e1c5695edfae2bf7a68dfc59448920191214-25405-s45gf5.gif'
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] [AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] [AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] [AV] Found ["ffmpeg"], using: Ffmpeg
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] [AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] [AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] [AV] Found 
I compiled ffmpeg and x264 without SSE3 and SSE4 instruction sets and placed them on path, but i still having issues uploading gif

["ffmpeg"], using: Ffmpeg
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] [AV] Running command: ffmpeg -i "/tmp/64a7e1c5695edfae2bf7a68dfc59448920191214-25405-j1skop.gif" 2>&1
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] method=POST path=/api/v1/media format=html controller=Api::V1::MediaController action=create status=500 error='Cocaine::CommandNotFoundError: Cocaine::CommandNotFoundError' duration=363.26 view=0.00 db=1.64
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896]
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] Cocaine::CommandNotFoundError (Cocaine::CommandNotFoundError):
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896]
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] lib/paperclip/gif_transcoder.rb:108:in `make'
Dec 14 14:18:35 mastodon bundle[24938]: [6dfec5c5-4aab-4301-8de2-856214fec896] app/controllers/api/v1/media_controller.rb:13:in `create'

**Comment by asterismo** [comment]
error='Cocaine::CommandNotFoundError: Cocaine::CommandNotFoundError'

what is this about?
