### ISSUE TITLE
Mentions don't work for federated "Articles"

### ISSUE THREAD

**Issue by qwazix** [tootsuite/mastodon#12129]
We are trying to support sending ActivityPub mentions from [writefreely](https://github.com/writeas/writefreely) but when posting a "Create" activity with an "Article" object the mentions in that Article get ignored. 

### Expected behaviour

The mastodon user should get a notification that somebody mentioned them. (This works in pleroma and it also works if I use a custom writefreely build with the "object" type as "Note" instead of "Article" 

### Actual behaviour

Nothing happens. The mentioned users are never notified.

### Steps to reproduce the problem

You can try with the branch [activitypub-mentions](https://github.com/writeas/writefreely/pull/195) from writefreely. Changing the type to `NewNoteObject` in [posts.go#1072](https://github.com/writeas/writefreely/blob/activitypub-mentions/posts.go#L1072) shows how the feature should be working.

### Specifications

I tested with mastodon 3.0.0 on fosstodon.org. The post does federate with the instance even as nobody follows me from there but it never reaches the intended user.

----

![image](https://user-images.githubusercontent.com/1202892/66478648-86952180-eaa3-11e9-82a8-9ed0cf078fd0.png)

![image](https://user-images.githubusercontent.com/1202892/66478708-a1679600-eaa3-11e9-9c27-8b5d9f670e17.png)

**Comment by dariusk** [comment]
@qwazix Can you try mentioning `@darius@friend.camp` in a test post? My instance runs a fork that supports `Article` posts (aka doesn't convert them into a URL stub) and if for some reason the mentions work I might be able to make a PR to fix this bug.

**Comment by Gargron** [comment]
I think we process Article posts the exact same way as Note with the exception of a cosmetic change of the body of the post. Mentions are separate from the body so that should not have an effect on them. If you are implementing mentions for the first time, maybe something about the way you describe them is wrong. For example, I think we don’t notify about mentions unless the person is also addressed in to/cc

**Comment by qwazix** [comment]
I'm pretty sure that the description is correct because if I change the object type to "Note" the mentions appear in the notifications as expected. (Unless I'm thrown off by something else) The mentions also work in pleroma which is another good indicator that they are described correctly.

The persons are addressed in CC (not To though)

![image](https://user-images.githubusercontent.com/1202892/66508785-73ea0f00-eada-11e9-995f-14f5145f2a66.png)

I will post the json later if that would be helpful (I'm on another computer now)

**Comment by Gargron** [comment]
The `ActivityPub::Activity::Create` class which processes mentions makes checks against the type only for `summary` and `content`. Otherwise, the checks happen before, deciding whether to process the object as a whole or not. So unfortunately I do not see anything obvious that would make mentions not work for Articles if they work for Notes.

**Comment by qwazix** [comment]
Ok, I'm sorry for this. You are indeed correct. The issue was that the iri in the CC field needed to be 
`https://mastodon.social/users/qwazix` and not `https://mastodon.social/@qwazix/` 

Is this something you are interested in fixing? Should I open a new issue?

**Comment by Gargron** [comment]
No, I don't think that could be considered a bug. The longer version is the URI, and the shorter, prettier version is the user-facing URL, they are not the same. (Now, the Mention objects refer to the *URL* using `href` instead of the URI, which is annoying, but that's how ActivityPub was designed)

**Comment by thebaer** [comment]
Thanks for the help, @Gargron! Fixed on our end and [working really nicely](https://m.abunchtell.com/@writeas_dev/102939253282000762).
