### ISSUE TITLE
[feature request] make private messages zero knowledge

### ISSUE THREAD

**Issue by tykayn** [tootsuite/mastodon#12128]
### Pitch
Private Notes / toots should not be readably by the admins of an instance.
it is also a nice security feature to have more zero knowledge in a database.

### Motivation
We advertise for privacy, private message (direct message?) should be really private.
it is not only a matter of trust to your moderators, admins, people will feel safer if their private conversations stay private.
Even in the case of a data breach.

**Comment by thespencertupis** [comment]
Could it be possible to interface with https://keybase.io/ to provide for assymmetrically encrypting (PGP) user's private messages to one another? Or would there need to be Secure Scuttlebutt employed for multi-party encryption?

**Comment by Gargron** [comment]
Duplicate of #1093
