### ISSUE TITLE
Privacy: Replace Twitter links with Nitter & YouTube links with Invidious

### ISSUE THREAD

**Issue by filippodb** [tootsuite/mastodon#12145]
mastodon is a social that put Privacy firstly:

### Pitch

We can Replace Twitter links with a links to a Nitter instance, we can have it as an option to increase privacy, I don't want to overload nitter.net.
 And of course disable google tracking replacing YouTube links with links to  Invidious INSTANCE, also here we can set disabled by default to not overload invidio.us

### Motivation

I have a lot broken links to twitter profiles like here: 

https://mastodon.uno/@quinta/102936658786992370

and using a nitter link will increase usability other than privacy

the youtube videos on mastodon adds tracking on mastodon and mastodon should be tracking free.

also halcyon has introduced this feature that will help newbies migrating from twitter to the fediverse

**Comment by nipos** [comment]
This is a really great idea!
To prevent overloading the official instances I recommend letting the instance admins set which instance should be used.
That's how I implemented it in Halcyon and for the example config,I set some unofficial public instances.
Setting it disabled by default leads to less usage of this feature which is bad for privacy so it's not a good idea.
To make it less invasive,I made a small question popup at the first redirect but enabling it by default is still better than disabling in my opinion.

**Comment by ariasuni** [comment]
I feel like this is two totally different changes which should be handled and discussed separately.

The problem with these kind of features is that it breaks the expectations of users: one may have a Twitter and want to react to a tweet, or want to add the Youtube video to their «Watch Later» playlist. Besides, the latter could easily be done with a browser extension.

Another problem is that it would add a dependency on their service and increase (probably a lot?) their traffic. What about the reliability of the instances of this software, who is managing them, etc.? Do we think it’s acceptable for Mastodon to make these choices instead of the users through e.g. browser extensions?

One last thing I can see is that Invidious’ interface is not user-friendly would reflect badly on Mastodon. Pages are difficult to scan, some action icons do not have a label, by looking quickly at the HTML code it is not accessible at all, player’s controls are too small, options are just plain scary, etc.

**Comment by nipos** [comment]
The first thing can be solved easily by letting the user choose whether this feature should be enabled or not.
The dependency thing is the reason why I recommend letting instance admins set the instance.
Often they run their own Invidious or Nitter instance,then they're responsible and want to use this instance.
If you want a browser extension where you can set your own Invidious/Nitter instance,you could simply turn the Mastodon feature off,then the extension should do its job.
For the user interface thing I unfortunately have to agree.
The app FreeTube improves that point but unluckily it's a Electron based program which needs to be installed.
I already thought about porting it to a webapp,then we could link to this...

**Comment by filippodb** [comment]
I think both users and admins should have the possibility to disable or enable their favorite  nitter/invidious instance.
So admin can choose to have a more privacy focused invidious instance  instead of the tracking giant youtube.com
Users should have their choices too so if they don't like invidious they can switch back to youtube or viceversa.

**Comment by thespencertupis** [comment]
In addition to @filippodb's comment, how about:

- Allow a user to override the instance's default nitter/invidious setting, and
- Allow and instance admin to prevent overriding the nitter/invidious instance setting.

**Comment by splacat** [comment]
This is a good idea. Replacing any Twitter link to Nitter one is so easy by changing `twitter.com` to any desired Nitter instance like `nitter.net`:
[https://twitter.com/MastodonProject/status/1231686279756156928](https://twitter.com/MastodonProject/status/1231686279756156928)
[https://nitter.net/MastodonProject/status/1231686279756156928](https://nitter.net/MastodonProject/status/1231686279756156928)
I think could be great to allow instance admins set up and enable their favourite Nitter instance.

**Comment by Gargron** [comment]
- Users might be weirded out by an unfamiliar link being put into their posts
- I don't know who's behind nitter/invideous, they could be overwhelmed by traffic
- You're asking to hardcode special treatment for specific centralized platforms

So far we've steered clear of the latter with the exception of Keybase. I'm against this.

**Comment by splacat** [comment]
@Gargron I'm running my own Nitter instance and the users of my Mastodon server know it and even use it to share Twitter links.
Could be good to have the possibility to setup in Mastodon config my Nitter instance as default for all Twitter links. This way, my users  could continue sharing whatever they want without forcing others users to visit Twitter.

**Comment by SuperSandro2000** [comment]
> I don't know who's behind nitter/invideous, they could be overwhelmed by traffic

Thats probably the biggest concern but for a small personal instance this could be really cool option to have. Also there is [Bibliogram](https://github.com/cloudrac3r/bibliogram).

**Comment by nipos** [comment]
I don't think that traffic is a big problem as these services are open source and hosted by many different people and groups.
You only shouldn't default to the flagship instances of Invidious and Nitter for every Mastodon instance.
Bigger Mastodon instances could even run their own Invidious or Nitter,so no third-party is ever needed or overloaded.

**Comment by connyduck** [comment]
This is not something that the platform should do. If you don't want to click twitter links, get yourself a browser extension that replaces the links for you. If you don't want your followers to click them, don't post them.

I agree that it would be cool if @user@twitter.com handles would be clickable though.

**Comment by nipos** [comment]
Clickable @user@birdsite links would cause even more backlinks to the birdsite what is exactly the opposite of what I'm trying to achieve :cry:

**Comment by resynth1943** [comment]
As Mastodon seems to be all for user freedom, it might be wise to reconsider. For instance, a warning could be implemented into the UI. So when a Twitter / YouTube link is entered into the composer, it could say something like 'Hey there! This instance rewrites YouTube / Twitter links. For more info, go here (link)'.

**Comment by resynth1943** [comment]
Another question I have is: would this be implemented at the API level, or in the web interface? Hopefully the API, yes?

**Comment by Gargron** [comment]
The responses to my comment did not change my mind. "Users might be weirded out by an unfamiliar link being put into their posts" would be enough of a reason alone. Rewriting contents of someone's post would be a breach of trust, in my opinion, similar to adding the server owner's referral codes to all Amazon links and similar. Those proxy sites are also probably not allowed in the respective service's terms of service so might get DMCA'd in the long term. Sorry, I should have pressed close issue right then and there instead of making it appear like I might turn around on it.

**Comment by SuperSandro2000** [comment]
It does not need to edit the links. The alternative link could be shown under the toot or something similar and it does not need to be limited to invidious or similar but could be a simple regex replace thing.

**Comment by resynth1943** [comment]
Well, it would be easy enough to implement. Perhaps it should be left off by default, but the UI should also inform the user of it.

If the user wants it on, I heavily doubt they will be 'weirded out by an unfamiliar link'.

> You're asking to hardcode special treatment for specific centralized platforms

What is the issue with this?

*Judging by the upvotes on the original post, and the downvotes on the disappointing reply by Eugen, it seems that people actually want this. Please reconsider.*

**Comment by TheEvilSkeleton** [comment]
> Well, it would be easy enough to implement. Perhaps it should be left off by default, but the UI should also inform the user of it.
> 
> If the user wants it on, I heavily doubt they will be 'weirded out by an unfamiliar link'.
> 
> > You're asking to hardcode special treatment for specific centralized platforms
> 
> What is the issue with this?
> 
> _Judging by the upvotes on the original post, and the downvotes on the disappointing reply by Eugen, it seems that people actually want this. Please reconsider._

i second this

**Comment by splacat** [comment]
For anyone interested I have released a Python code that publish any twitter account's tweets thanks to Nitter's RSS feed:
[nitter2toot](https://gitlab.com/spla/nitter2toot) can toot any Twitter account's tweets to any Mastodon server.

**Comment by Oymate** [comment]
I think this is best if done on a client app,
And you should use UntrackMe(android) to do these convertions
