### ISSUE TITLE
Need to set "Access-Control-Allow-Origin" on manifest.json

### ISSUE THREAD

**Issue by agnelvishal** [tootsuite/mastodon#12163]
Since manifest.json might be accessed from other locations as it is a PWA, we need to set  "Access-Control-Allow-Origin" on that file.
What needs to be done for it?

**Comment by ThibG** [comment]
I see no reason to deny access to the manifest.json file, but I fail to see a situation where the PWA and the manifest.json aren't on the same origin. The only place the manifest.json is referenced is from the main WebUI page, which uses the relative path `/manifest.json`…

**Comment by agnelvishal** [comment]
Apps like https://blockstack.org need access to manifest.json to detect PWA's.

**Comment by nightpool** [comment]
The PWA specs do not require websites to allow cross-origin apps to access manifest.json. While Mastodon could set this header, you're likely to run into many other websites who do not have this header set on their manifest. Your code should handle both situations gracefully. I don't think there's a compelling reason for mastodon to make this accessible in-browser.

**Comment by agnelvishal** [comment]
Okay. Should I try this https://github.com/cyu/rack-cors for allowing cross-origin in my mastodon instance?
