### ISSUE TITLE
Docker installation recommendation

### ISSUE THREAD

**Issue by Fastidious** [tootsuite/mastodon#1217]
Mastodon is demanding. Perhaps no much as a private instance, but it is still demanding.

- I propose the `docker` approach to be made more complete, to include `nginx` and everything set in place, so that when `docker-composer up -d` (or custom command, see `Discourse` install doc) is issued, a fully functional instance results.
- Use `Discourse` install, setup, and maintenance approach. See https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md

I tried to get a `Mastodon` instance up and running three times and failed. Got one with someone's help (fourth attempt), but there were still problems, so I just scrapped it. I got `Discourse` up and running in one try, very easily. Just mentioning it for comparison.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by vielmetti** [comment]
@Fastidious  - what was the help that got you to the point that the instance was up, and what were the problems you experienced? Folks are working on Ansible and Terraform provisioning, so there's some active effort to make the new admin experience less difficult.

**Comment by maximeborges** [comment]
Personnaly, I got to check how to properly configure nginx to proxy the mastodon instance with SSL, that could be added on the README so it would be less confusing.

**Comment by Fastidious** [comment]
@vielmetti the "Running with Docker and Docker-Compose" instructions are weird, to say the least. Give it to someone not blinded by familiarity (thanks @yipdw for the phrase), and you will see the issues. Before one is able to generate the hashes (the three needed), there are other commands that need to be run (`docker-compose build` needs to be run at least once, before access to what's needed to generate the hashes is possible).

Some variables on the `.env.production.sample` file are easy to understand, but there is at least one that escapes understanding, and that is `STREAMING_API_BASE_URL=`. I did not touch the optionals, but that one isn't marked as such. What is supposed to be there? 

Again, take a look at `Discourse` install documentation and you will see the advantages. I still think Docker is the way to go (simplest), but the current process is far from smooth.

**Comment by wxcafe** [comment]
@maximeborges please add your experience with configuring the nginx reverse proxy with TLS to the doc and submit a PR :)

@Fastidious yeah that `STREAMING_API_BASE_URL` should be marked as optional. I'll do a PR for that tomorrow, but I can't write too much of the docker doc since I don't really use docker.

**Comment by Fastidious** [comment]
There is plenty of documentation around now. I realise my issue was a mix of documentation being too simple, and my lack of knowledge with Docker. Closing.
