### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by StevenPatz** [tootsuite/mastodon#1219]
So I am interested in creating a Drupal module for users to post to their Mastodon timelines.  Is there no per Mastodon user api keys available yet?  Or am I missing something?
* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by carlosjs23** [comment]
You can read this for know how-to publish user status [Statuses API Docs](https://github.com/tootsuite/mastodon/blob/master/docs/Using-the-API/API.md#statuses)

And this for authentication and get the client secret: [Authentication](https://github.com/tootsuite/mastodon/blob/master/docs/Using-the-API/Tips-for-app-developers.md)

**Comment by ineffyble** [comment]
Above info should give you everything you need - a Drupal module would ideally use the OAuth workflow to allow the user to authorize that site to toot on their behalf. 

The module would probably create an OAuth "app" for every instance it encountered, and store the key/secret. It would then use those app details to redirect a new user to the OAuth grant page, receive a callback, and request an access token, which could then be stored against that user (along with the instance domain).

**Comment by BenLeggiero** [comment]
Cool, all the links here are 404s now 👍🏽

**Comment by nightpool** [comment]
@BenLeggiero Hey, not sure where you found this issue, but the mastodon documentation has moved to https://docs.joinmastodon.org. those links specifically haven't worked in 2 years. The new documentation page is linked to prominently both from the readme and from the project page.

**Comment by BenLeggiero** [comment]
Thanks for the updated link! Whoever maintains these should read [Cool URIs don't change](https://www.w3.org/Provider/Style/URI) 😉
