### ISSUE TITLE
"Disable" (account action) should be "Disable login" or something clearer

### ISSUE THREAD

**Issue by Phroneris** [tootsuite/mastodon#12200]
### Motivation

![mod_disable](https://user-images.githubusercontent.com/9891867/67309886-99920200-f537-11e9-9ac9-eb0f5ae6bbff.png)

- `Do nothing` ← OK, absolute nothing.
- `Silence` ← Hmm, that must be a kind of term, but makes sense.
- `Suspend and irreversibly delete account data` ← Yay super clear, alone.

​
- `Disable` ← ... What am I disabling?

### Expected behaviour

- It says `Disable login` as the documentation does(\*), or something clearer.
(\* https://docs.joinmastodon.org/usage/moderation/#disable-login)

### Actual behaviour

- It just says `Disable` and doesn't tell what.

### Steps to reproduce the problem

1. Login as an admin (maybe a moderator is OK too)
2. Settings > Moderation > Accounts > (Select someone) > WARN
3. See the dropdown list of the account action

### Specifications

- Server: gensokyo.town
- Version: 3.0.1 (vanilla)

### Notes

- The string must be here:
  https://github.com/tootsuite/mastodon/blob/master/config/locales/simple_form.en.yml#L81
- The word `frozen` (freeze) can also be seen, and it seems inconsistent:
  https://github.com/tootsuite/mastodon/blob/master/config/locales/en.yml#L1185
- On this screen, adding a link to the moderation page of the documentation may help administrators and moderators.

**Comment by nileshkumar** [comment]
@Phroneris : I will try changing the string

**Comment by nileshkumar** [comment]
Please merge this branch(disable_login) :  https://github.com/nileshkumar/mastodon/tree/disable_login

**Comment by Phroneris** [comment]
memo: Fixed by #12201
