### ISSUE TITLE
Following list import, csv file is invalid 

### ISSUE THREAD

**Issue by salvadorpla** [tootsuite/mastodon#12204]
Exported following list (2023 users) from Mastodon v2.9.3 server and importing generated csv file to a new one, at v3.0.1 version
### Expected behaviour
All contacts imported

All contacts imported
### Actual behaviour
csv is invalid

csv invalid, none contacts imported. Server logs don't show any errors.
### Specifications
exporting from v2.9.3 server and importing to v3.0.1 one

**Comment by salvadorpla** [comment]
Is there a limit of how many contacts can be imported from a csv file?

**Comment by ThibG** [comment]
There is a limit, but it's higher than what you'd run into (7500 followers, or 1.1 times the amount of people following you, whichever is higher) and it would just import your followers up to that limit (and silently dropping the others, urgh), not error out

Does it say the CSV is invalid? Does it say more than that? Does the CSV look invalid to you (not going to ask you to post it, since it contains personal data)?

**Comment by salvadorpla** [comment]
@ThibG ok, so the limit is 7500. This is not the reason.
It claims "is invalid" under the button. See image.
No, it not look invalid to me.
![Captura de pantalla 2019-10-24 a les 14 52 17](https://user-images.githubusercontent.com/27005879/67487485-51293000-f66e-11e9-9a66-893a6b75b9f7.png)

**Comment by ThibG** [comment]
I cannot reproduce this… could you post the first few and last lines of the file? (I encourage you to anonymize them)

**Comment by salvadorpla** [comment]
Sure
![Captura de pantalla 2019-10-24 a les 16 00 29](https://user-images.githubusercontent.com/27005879/67494043-e4fff980-f678-11e9-8172-5c0a7e55d5e9.png)
![Captura de pantalla 2019-10-24 a les 16 00 58](https://user-images.githubusercontent.com/27005879/67494045-e5989000-f678-11e9-8690-c0d31dbe5fd5.png)

**Comment by salvadorpla** [comment]
![Captura de pantalla 2019-10-24 a les 16 00 58](https://user-images.githubusercontent.com/27005879/67494209-27293b00-f679-11e9-9759-7700cfa55741.png)

**Comment by salvadorpla** [comment]
@ThibG this log lines look normal to you?

bundle: [0eaf6d82-3abb-4e37-af35-11fe096323a9] Command :: file -b --mime '/tmp/RackMultipart20191024-4433-agsu9s.csv'
Oct 24 17:11:27 bundle: [0eaf6d82-3abb-4e37-af35-11fe096323a9] [paperclip] Trying to link /tmp/RackMultipart20191024-4433-agsu9s.csv to /tmp/86c8109f207a6432520364460861301b20191024-4433-1xtjjtc.csv
Oct 24 17:11:27 bundle: [0eaf6d82-3abb-4e37-af35-11fe096323a9] [paperclip] Trying to link /tmp/86c8109f207a6432520364460861301b20191024-4433-1xtjjtc.csv to /tmp/86c8109f207a6432520364460861301b20191024-4433-1bw4i8r.csv
Oct 24 17:11:27 bundle: [0eaf6d82-3abb-4e37-af35-11fe096323a9] Command :: file -b --mime '/tmp/86c8109f207a6432520364460861301b20191024-4433-1bw4i8r.csv'
Oct 24 17:11:27 bundle: [0eaf6d82-3abb-4e37-af35-11fe096323a9] [paperclip] Trying to link /tmp/86c8109f207a6432520364460861301b20191024-4433-1xtjjtc.csv to /tmp/86c8109f207a6432520364460861301b20191024-4433-23gv1r.csv
Oct 24 17:11:27 bundle: [0eaf6d82-3abb-4e37-af35-11fe096323a9] Command :: file -b --mime '/tmp/86c8109f207a6432520364460861301b20191024-4433-23gv1r.csv'
Oct 24 17:11:27 bundle: [0eaf6d82-3abb-4e37-af35-11fe096323a9] method=POST path=/settings/import format=html controller=Settings::ImportsController action=create status=200 duration=59.35 view=9.28 db=3.37

**Comment by ThibG** [comment]
it doesn't look fishy. What's the output of `file -b --mime the-file.csv` on that server, though?
Also, I wonder if it could get truncated for some reason?

**Comment by salvadorpla** [comment]
@ThibG file -b --mime following_accounts.csv 
text/x-c; charset=us-ascii
It not get truncated so it seems after visual inspection.

**Comment by salvadorpla** [comment]
Ok, I'm clossing this because is not related to Mastodon. This issue happens only in Centos 7 servers.

**Comment by ThibG** [comment]
Well, this could be considered a Mastodon bug, I guess. I'm not sure there is any value in checking what type `file` returns when importing the CSV files? (We're requiring either `text/plain` or `text/csv`, but it's not like CSV files have magic number to tell exactly what they are)
cc @Gargron

**Comment by salvadorpla** [comment]
Funny enough. When I get the text/x-c file back to my lap (macOS) and issue this it's "again" text/plain:
file -b --mime following_accounts.csv
text/plain; charset=us-ascii
So Centos servers believe that it's a text/x-c for some reason...

**Comment by salvadorpla** [comment]
@ThibG Found it.

- Centos 7 file version is:
file -v
file-5.11
file-5.11 believes that an csv file is a text/x-c mime type:
file -b --mime following_accounts-mime.csv 
text/x-c; charset=us-ascii

- Centos 8 file version is:
file -v
file-5.33
file-5.33 replies correctly csv file mime type:
file -b --mime following_accounts-mime.csv 
text/plain; charset=us-ascii

cc @Gargron
