### ISSUE TITLE
Reporting "comment" textbox repeatedly clears text.

### ISSUE THREAD

**Issue by bellabie** [tootsuite/mastodon#1220]
When trying to report a user for their abusive posts, I am prompted to write comments. The issue is that as I type in the comment box, the text I have written is repeatedly deleted (I'd say every second or two) making it [almost] impossible to ensure that the comments are indeed submitted in the report.

* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
https://github.com/tootsuite/mastodon/issues/774

**Comment by blackle** [comment]
I've experienced this also, I'm pretty sure it happens every time an update is pushed to the home or federated timelines

**Comment by lynnco** [comment]
I'm getting this now too, its happening when new updates come in

It's INCREDIBLY disruptive and a high priority issue IMO
