### ISSUE TITLE
libicudata.so.57: not found

### ISSUE THREAD

**Issue by Perflyst** [tootsuite/mastodon#12210]
After upgrade to from Debian 9 to Debian 10 precompile does not work anymore even if lib installed

`RAILS_ENV=production bundle exec rails assets:precompile`

```
rails aborted!
LoadError: libicudata.so.57: cannot open shared object file: No such file or directory - /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/charlock_holmes-0.7.6/lib/charlock_holmes/charlock_holmes.so
```

### Specifications

Debian 10
Ruby 2.6.5
Mastodon v3.0.1

```
# whereis libicudata
libicudata: /usr/lib/x86_64-linux-gnu/libicudata.so /usr/lib/x86_64-linux-gnu/libicudata.a
```

**Comment by Perflyst** [comment]
Seems to be fixed after rebuilding all gems

**Comment by manurevah** [comment]
I (think) I "rebuilt all the gems", yet I still have issues. (Perhaps you can explain exactly what "rebuilding gems" means, in case I missed something.)

I did the whole

```
bundle install
yarn install
RAILS_ENV=production bundle exec rails assets:precompile
```

First two steps go well, the last one gives the error:
```
rails aborted!
LoadError: libicudata.so.57: cannot open shared object file: No such file or directory - /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/charlock_holmes-0.7.7/lib/charlock_holmes/charlock_holmes.so
```
