### ISSUE TITLE
Optimize node instance (transpilers, cluster, etc)

### ISSUE THREAD

**Issue by skhameneh** [tootsuite/mastodon#1222]
I'm most interested in issue #1043 , but immediately after I'd like to help w/ this.
Once I get my own server up, perf is a major topic for me.

- [x] Run node in cluster if applicable (multiple cores available)
- [x] Use Webpack w/ Babel or another build toolchain to replace "babel-node" (also use UlgifyJS, offers some runtime optimizations as well)
- [x] Build the streaming service into a separate docker image to offer as an isolated service (this helps w/ scaling and using haproxy as a load balancer)

**Comment by krainboltgreene** [comment]
@skhameneh What's the value of using webpack with babel? The node service has no frontend.

**Comment by skhameneh** [comment]
@krainboltgreene "or another toolchain", for sake of building an optimized output.  Webpack can target node, has first party Babel support, and has UglifyJS built-in to the bundled plugins.  Tools like Rollup,  Brunch, and Gulp work as well.  I'd most like to see Webpack or Rollup used.

**Comment by krainboltgreene** [comment]
I have found very little returns from doing any sort of packing, uglifying, and or rolluping for node servers. Happy to be proven wrong though!

**Comment by skhameneh** [comment]
@krainboltgreene moving away from babel-node in prod is argument enough.  Additional optimizations don't pose significant investment and pay off at scale.

You're welcome to share your own metrics, unfortunately mine are sensitive and under NDA.

**Comment by krainboltgreene** [comment]
@skhameneh I know the official babel documentation says it's less performant, but at worst I'm only seeing a 1-2% difference in performance in my experience.

That said the documentation is very clear to avoid it and other people are running this software so yes, I would :+1: any PR that moves us from that to babel transpile + node running over just babel-node running.

@skhameneh Do you have a migration plan in mind?

**Comment by krainboltgreene** [comment]
Actually, perhaps this is worth splitting into 3 different tickets.

**Comment by skhameneh** [comment]
@krainboltgreene I'll make a PR with noninvasive changes after I get my server running how I'd like, I'm mostly interested in #1043 and waiting to hear from @gargron if he'd like to coordinate spilling the three services into separate images.  I'm imagining 4 images total could be a good route — one with the current build and an additional 3 that are split out.  That should satisfy all use cases.

**Comment by krainboltgreene** [comment]
Thanks so much for your time @skhameneh.

**Comment by Gargron** [comment]
@skhameneh Given that currently you can use the same docker image with different commands to get all 3 services running (web, sidekiq, streaming), and given that the web container needs Node/Yarn installed for asset generation anyway, what benefit do you see in splitting it in 3 different images?

**Comment by skhameneh** [comment]
@Gargron 

1. Allows each layer of the app to have a health report in Docker.
2. Each service can be load balanced and updated individually.
3. If there is a security vulnerability exposing the system, it will help isolate that layer of the app. (plus for env vars, each layer doesn't have access to potentially sensitive vars of another layer)
4. Creating additional images (rather than enforcing a split) gives architectural flexibility for deployments.
5. Each container can be resource scaled individually.

**Comment by nolanlawson** [comment]
Yeah `babel-node` is [not meant for production](https://babeljs.io/docs/usage/cli/#babel-node) according to Babel's own docs. Not sure about other suggestions here, but moving away from `babel-node` is solid.

**Comment by krainboltgreene** [comment]
As noted previously while the documentation is clear my own usage of `babel-node` has *not* impacted performance in a significant manner. At best a 5% higher memory usage, and almost no extra time spent.

**Comment by Gargron** [comment]
This has been resolved.
