### ISSUE TITLE
Remove stalebot

### ISSUE THREAD

**Issue by ryliejamesthomas** [tootsuite/mastodon#12225]
Because of stalebot I now have a shitload of pointless emails to wade through. They're either a notification that it's marked an issue, or people having to bump an issue to keep it open.

In most cases the lack of new replies on an issue is not because of any fault with the issue, it's a problem caused by lack of activity from the developers. It's targeting the wrong problem.

Death to stalebot.

**Comment by nightpool** [comment]
Stalebot was never meant to be enabled on issues, and my understanding is
that we've fixed its configuration so that its only considering PRs now.

**Comment by ryliejamesthomas** [comment]
Okay. thanks then :)
