### ISSUE TITLE
Rewrite Streaming API to use Ruby on Rails Action Cable

### ISSUE THREAD

**Issue by nsuchy** [tootsuite/mastodon#12230]
### Pitch

The streaming API is written in Nodejs while the rest of the application is Ruby on Rails or ReactJs. Ruby on Rails, a rather recent development (not sure how old the streaming API is) in Ruby on Rails is ActionCable (https://guides.rubyonrails.org/action_cable_overview.html#introduction). We might be able to replace the Nodejs Streaming API by extending the rails app to use ActionCable.

### Motivation

From a development point of view this would reduce application complexity, the streaming API might not need a separate process if it can run as part of a rails application.

This could reduce the number of modular parts of Mastodon.

More of the code is written in Ruby which may look cleaner and more organized (opinionated). It’d let Mastodon really show what Ruby on Rails can do and be a great example of ActionCable in action.

We might be able to (not sure if it’s still required because we use React) remove Nodejs as a dependency and it may make the application more lightweight.

## Counterarguments

* Rewriting an existing feature takes development time away from other projects.
* Rewriting the feature may introduce bugs and will require heavy testing to make sure everything still works as expected.
* ActionCable might require more than less resources. We don’t have a comparison of the performance at this time.

If this proposal is accepted, it might be a good first merge request for me if I worked on this?

**Comment by nightpool** [comment]
>We might be able to (not sure if it’s still required because we use React) remove Nodejs as a dependency and it may make the application more lightweight.

Node would still be required to precompile the webpack assets, yes.

**Comment by nightpool** [comment]
My understanding is that there's already an ongoing project to rewrite the streaming endpoint in Rust to better handle high load, but i'll let @codesections or @Gargron speak to that. With that in mind, I don't think it's very likely that we'll want to re-write in actioncable any time soon..

**Comment by nsuchy** [comment]
> 
> 
> My understanding is that there's already an ongoing project to rewrite the streaming endpoint in Rust to better handle high load, but i'll let @codesections or @Gargron speak to that. With that in mind, I don't think it's very likely that we'll want to re-write in actioncable any time soon.

That's cool to see an effort made in Rust. I'm not familiar with the language but pick up on things relatively quickly. Is there a branch or a repo I could contribute to on this effort?

**Comment by Gargron** [comment]
It's here! https://github.com/tootsuite/flodgatt/

**Comment by nsuchy** [comment]
> 
> 
> It's here! https://github.com/tootsuite/flodgatt/

Thanks, might check it out and see if I can contribute somehow 😄

**Comment by nsuchy** [comment]
I am closing this issue as I believe @Gargron's implementation using Rust has better potential performance wise than rewriting the code in another interpreted programming language such as Ruby.
