### ISSUE TITLE
Image Alt Text is Cut at 420 Characters when Federated

### ISSUE THREAD

**Issue by psydwannabe** [tootsuite/mastodon#12258]
### Expected behaviour
Federated versions of a toot should include the full image alt text of the original toot.

### Actual behaviour
Federated versions of a toot include only the first 420 (nice) characters, truncating anything beyond.

### Steps to reproduce the problem
1. Create a toot with an image
1. Set the alt text for that image to something longer than 420 characters
1. View that toot from another instance

### Specifications

Screenshot showing full image alt text on original toot:
![A screenshot of a toot about Bernie Sanders with a text screenshot as the image. The full text of the screenshot is shown in the alt text of the image as shown by the developer tools window to the right of the page with the HTML image tag highlighted.](https://i.imgur.com/FpMFiWF.png)

Screenshot showing boosted toot's truncated image alt text on a user profile page.
![A screenshot of a toot as viewed from the public profile page of a user from another instance who boosted the toot- the alt text is truncated at 420 characters.](https://i.imgur.com/npqsmqm.png)

**Testing Details**
We were able to reproduce the issue between the following server versions:

Originating Version | Federated Version
------------ | -------------
Mastodon 3.0.1 | Mastodon 3.0.1
Mastodon 3.0.1 | v3.0.1+glitch+vulpine-prod-20191017-02
v3.0.1+glitch+vulpine-prod-20191017-02 | Mastodon 3.0.1

We tested and verified the issue in multiple browsers:
Firefox, Waterfox, Chrome and Opera.

And on multiple (API based) clients:
Tusky, Pinafore

**Comment by ZoeBijl** [comment]
May I propose we communicate the 420 characters limit rather than allow more than 420 characters? 420 characters is a lot of text. For example, screen readers will read the entire alt text in go. Users can’t navigate it word by word. So if your image needs more than 420 characters to be described it probably requires a transcript rather than an alt text.

To prove a point: this entire comment is exactly 420 characters.

**Comment by psydwannabe** [comment]
@ZoeBijl I would recommend making your suggestion elsewhere, as this is a bug report and not a feature request where such a discussion would be warranted. 

This issue was raised to ensure the (communicated) 15000 character limit in image descriptions federates. There is a disconnect between the character limit in the image description text and the character limit in federating that image description. It appears the bug has already been fixed above, just waiting for it to be included in a release.

**Comment by ZoeBijl** [comment]
So the fix for this accessibility related bug is to make sure people can make their content less accessible? 🤔
