### ISSUE TITLE
Pronouns on user profile.

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#12261]
### Pitch
I'd like to be able to declare my pronouns and have this as a dedicated field on the profile...

### Motivation
Just a nice idea.

I figure it's a freetext field (16 char max?) as a protocol, but the webapp could have a preloaded list (and admins could add additional pronouns as required by their community)

**Comment by Shleeble** [comment]
This is an EXAMPLE usecase.. but might be a bit far (Bot accounts could have Bot)

![image](https://user-images.githubusercontent.com/17537000/67860300-716a5a80-fb58-11e9-899b-b102064d1de1.png)

**Comment by nsuchy** [comment]
I like the idea of adding it below your avatar. I'm able to add a custom field with them already using profile meta data. I'm assuming that doesn't fit your needs?
<img width="1280" alt="Screen Shot 2019-11-01 at 7 26 19 PM" src="https://user-images.githubusercontent.com/8227641/68061904-94724700-fcdd-11e9-9814-c64b22873156.png">
<img width="1280" alt="Screen Shot 2019-11-01 at 7 26 35 PM" src="https://user-images.githubusercontent.com/8227641/68061905-94724700-fcdd-11e9-821f-3b3fa9846614.png">
