### ISSUE TITLE
Placeholder for non-visible toots

### ISSUE THREAD

**Issue by BenLubar** [tootsuite/mastodon#12264]
### Pitch

If a toot cannot be displayed for any reason, a placeholder should be displayed instead.

### Motivation

There are multiple reasons why a toot cannot be displayed:

- deleted while being read
- known from reply-to but not yet fetched
- instance/user blocks
- purged by tootctl

These can all be displayed the same way (something akin to "this toot is unavailable")

**Comment by trwnh** [comment]
Possible duplicate / related to #7274 #11678

**Comment by BenLubar** [comment]
Going to close as a duplicate of both of those together.
