### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by tailot** [tootsuite/mastodon#12309]
The documentation refers to the version of ruby 2.6.1 following all the steps I get the error:
mastodon@xyz:~/live$ RAILS_ENV=production bundle exec rake mastodon:setup
rbenv: version `2.6.5' is not installed (set by /home/mastodon/live/.ruby-version)
[Exit 1]
Can you update the documentation (https://docs.joinmastodon.org/administration/installation/)?

**Comment by anirudh24seven** [comment]
Coincidentally, I ran into the same issue today and I raised a PR to update the docs here: https://source.joinmastodon.org/mastodon/docs/merge_requests/59

**Comment by Gargron** [comment]
Fixed
