### ISSUE TITLE
MigrateAccountConversations failing on an upgrade from 2.4.4 to 3.0.1.

### ISSUE THREAD

**Issue by egypturnash** [tootsuite/mastodon#12305]
I am finally getting around to updating dragon.style from 2.4.4 to 3.0.1. The database migrations worked fine on my local dev copy but they keep on failing on the actual instance.

This is a migration in the pre-deployment updates from 2.4.4 to 2.7.0, and it's failed with all four versions of the code on Github for that migration.

Garg touched this migration about a month ago: https://github.com/tootsuite/mastodon/pull/12095/commits/da9c74c3318e77bface26ffcf74fab741093db2e - I've tried reverting this migration to all of the versions in that file's history, with no joy.

### Expected behaviour

The migration should have happened.

### Actual behaviour

The migration aborts, with a massive stack dump that says it was caused by

```
PG::UndefinedColumn: ERROR:  column statuses.deleted_at does not exist
LINE 1: SELECT  "statuses".* FROM "statuses" WHERE "statuses"."delet...
```

The full error dump is here: https://gist.github.com/egypturnash/2e37706a704083b6cb27b0a021f76072

And here it is with a trace added: https://gist.github.com/egypturnash/f315d098de97962e67eebc3796d678b7

### Specifications

Mastodon 3.0.1. A database from 2.4.4 that made it through all previous migrations.

**Comment by egypturnash** [comment]
Garg found a quick fix:

> the quickest temporary fix to get this migration to run is to remove `.kept` from this line https://github.com/tootsuite/mastodon/blob/master/app/models/status.rb#L79

Resolved for me, posting this here to not be DenverCoder9. :)

**Comment by NoelDeMartin** [comment]
I just upgraded my instance and I faced this issue as well. Maybe it should be kept open until this doesn't require a manual fix?

Also, a word for others facing the same problem who use Docker. Keep in mind that in order for this  to work, you need to change the code within the container. If you were using an existing image (like I was), this means you need to either modify the file within the running container or build an image from local files.
