### ISSUE TITLE
Translation related questions

### ISSUE THREAD

**Issue by carlosjs23** [tootsuite/mastodon#1232]
I am working on updating translations into Spanish, I would like to know everyone's opinion on how to translate specific words, such as:

(X) Toot
(X) Boost
(X) Boosted

Instead of translating them into common words as they would be:

(X) Publish (Publicar)
(X) Republish (Republicar)
(X) Republished by (Republicado por)

I would like to know if we could make it more informal, like the way of "twitter" in Spanish, but keeping Mastodon's original words:

(X) Tootear
(X) Retootear
(X) Retooteado por 

If anyone has better ideas, I am open to discussing.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nclm** [comment]
Is there any usages that emerge from Spanish-speaking users already using Mastodon? The best could be to not go with something unexpected for actual users.

If not already done, you could ask the question on Mastodon itself and get more answers from users than on GitHub?
