### ISSUE TITLE
Add users we don't follow to lists

### ISSUE THREAD

**Issue by MyNameIsTroll** [tootsuite/mastodon#12325]
Currently it is impossible to add accounts that we do not follow to our lists.
However, I see some use cases where this could be useful. 

For example, I would like to follow all the newspapers that toot in my language to follow the news but I don't necessarily want to subscribe to all these newspapers because they will flood my timeline all the time.

**Comment by trwnh** [comment]
Duplicate of #6982 and #7876

**Comment by MyNameIsTroll** [comment]
Thanks @trwnh  , I hadn't seen it. I'm sorry. I close this issue.
