### ISSUE TITLE
UX: Prompt For Username Unavailability Before Account Deletion 

### ISSUE THREAD

**Issue by jessy-james** [tootsuite/mastodon#12333]
There was no option to change my username. So deleted my old account, hoping to create a new one with another username. Turns out that was taken. 

So tried to create a new account with the username that I had already gotten (and later deleted) but get a message saying "Username has already been taken". 

Read https://github.com/tootsuite/mastodon/issues/11660 this ticket to find that this is expected behaviour. In that case, **I should've received a prompt before deletion saying that this username will not be available later** or that the administrator needs to be contacted for renewing the username.

**Comment by nightpool** [comment]
hi! thanks for writing in. 

Here's a screenshot of the "delete account" page. as you can see, it does clearly state that your username will remain unavailable after deleting your account. 
![Screenshot_20191109-081309](https://user-images.githubusercontent.com/233815/68529089-d34d6180-02c8-11ea-9e07-61a0c12856e7.png)
Does that answer your question?

**Comment by jessy-james** [comment]
Sorry then

**Comment by trwnh** [comment]
From a UX perspective it's really easy to skip stuff like this. Users often expect a confirmation step with a clearer warning.

**Comment by jessy-james** [comment]
Agreed. I clearly did skip it.
