### ISSUE TITLE
Can't Verify CSRF token authenticity

### ISSUE THREAD

**Issue by ericblade** [tootsuite/mastodon#1236]
Hi! I just setup a Docker built server, and created a couple of accounts.  When I try to login with them, I get the "Do you have cookies enabled?" message, and the web container logs "Can't verify CSRF token authenticity".

So, I'm trying to figure out how to get through that problem.

Somewhat more disturbing? perhaps, is that I found a way *around* that problem -- pressing Back from that error screen to go back to the login screen, then pressing Reload on my browser, gets me through.

Any ideas?  What more info can I provide to help?

**Comment by rhaamo** [comment]
Same issue here, but without docker.

**Comment by rhaamo** [comment]
Also duplicate of #1150

**Comment by ericblade** [comment]
Per Technowix on #1150, "You can revert to 624a9a7, temp fix :°" .. which does seem to work.  It does leave me with a "streaming" module that has a LOT of logspam for "Error: Missing access token", but otherwise login and everything else seem to be working.  I'm thinking maybe not close this one as duplicate, though, since it has actual text of an error, and therefore is searchable :-D

**Comment by ronilaukkarinen** [comment]
I see this all the time. What does it mean?
