### ISSUE TITLE
Secure mode (AUTHORIZED_FETCH) breaks Keybase proofs

### ISSUE THREAD

**Issue by mlsteele** [tootsuite/mastodon#12375]
Enabling secure mode on a Mastodon instance breaks Keybase proofs for that instance, both creation and verification. This came as a surprise to at least one instance admin.

Keybase proofs are fundamentally a public statement of identity, so if a user makes a proof, it makes sense to serve the data required to verify it publicly. Imo the simplest solution would be to allow access to `api/proofs` without client authentication even secure mode for instances where keybase proofs are enabled.

`api/proofs` can also be used to check whether a user exists based on whether it 404s. I'm not clear on whether secure mode is supposed to hide user existence from public view, but if so, that's something to consider. I found these docs (https://blog.joinmastodon.org/2019/10/mastodon-3.0-in-depth/) on secure mode and wonder if there's more.

This issue probably affects 'whitelist mode' as well.

### Expected behaviour

The `/api/proofs` endpoint on mastodon should respond to requests made by keybase clients attempting to verify proofs.

For example, for the proof `stux@mstdn.social == mstdn@keybase`:
```
$ http "https://mstdn.social/api/proofs?provider=keybase&username=stux"
HTTP/1.1 200 OK
{
    "avatar": "https://cdn.mstdn.social/mstdn-social/accounts/avatars/000/005/168/original/d08b8171546cbee6.gif", 
    "signatures": [
        {
            "kb_username": "mstdn", 
            "sig_hash": "01801119a97e55d6b3a457f3702097794fb61b3ed2f2ea020bd80a1c21561a4e0f"
        }
    ]
}
```

### Actual behaviour

When secure mode was enabled on mstdn.social, `https://mstdn.social/api/proofs?provider=keybase&username=stux` returned `401 Unauthorized,`.

### Steps to reproduce the problem

Enable secure mode with AUTHORIZED_FETCH=true on an instance with a keybase proof. Try to check the proof with the keybase username `keybase id -s mstdn`.

### Specifications

What version or commit hash of Mastodon did you find this bug in?

Mastodon version 3.0.1+glitch

Thanks @mstdn for bringing this up and tracking down the cause.

**Comment by Gargron** [comment]
Fixed in #12495
