### ISSUE TITLE
Lockdown Mode

### ISSUE THREAD

**Issue by irlcatgirl** [tootsuite/mastodon#12374]
### Pitch

Add a .ENV variable to enable a "lockdown mode". When enabled it should limit federation to existing remote instances and not respond to any new instances. Alternative approaches being to "approve new instances" similar to the registration queue, you'd need to approve new instances before they appear in the federated timeline.

### Motivation

This would be a helpful security feature in the event someone creates several instances to spam the federated timeline or to harass users. Rather than blocking them all, simply not federating with any new instances.

**Comment by MirceaKitsune** [comment]
If this doesn't get enabled or suggested by default, it might be a good idea. I believe we must encourage the network to remain as open as possible... at the same time Mastodon does presently make it easy for a determined bad actor to generate dozens of accounts to harass someone if they wanted, which still worries me even if it doesn't seem to have happened yet.

**Comment by sneak** [comment]
Enabling such a feature would have the unfortunate side-effect of rendering any users on instances with which you had not previously federated entirely invisible to your local users, for example if they try to follow someone new on an instance not-previously-federated.  I think this is a pretty good argument for coming up with a different solution to spam than a fail-closed switch.
