### ISSUE TITLE
Seperate Media and Cache Buckets

### ISSUE THREAD

**Issue by irlcatgirl** [tootsuite/mastodon#12382]
### Pitch

I would like an option to store local media and cached remote media in separate S3 buckets. This would be configurable in the `.env` files.

### Motivation

This would create smaller backup sizes for new instances and make them more manager (in stages) for larger ones.

**Comment by Shleeble** [comment]
That's a wonderful idea.. Local bucket / remote bucket.

**Comment by Gargron** [comment]
This would be great. Have to figure out how to a) use dynamic paperclip options based on model attributes and b) introduce this in already live systems without losing access to old files. :thinking: 

Conceptually similar to #6675

**Comment by nsuchy** [comment]
For A) Could we do two separate Paperclip instances with a separate configuration or is it a Singleton class?

For B) We would need a special rake task to copy files over. It might be expensive for some instances.

Cordially,
Nathaniel Suchy (they/them)

**Comment by luxtiasco** [comment]
I don't think it is solved, still unable to use different s3 buckets for cache and local media.
