### ISSUE TITLE
Glossary on CrowdIn is ambiguous

### ISSUE THREAD

**Issue by ariasuni** [tootsuite/mastodon#12388]
### Expected behaviour

Glossary is easy to translate.

### Actual behaviour

Lots of words can be either nouns or verbs (or something else), so it’s hard to understand how to translate it. It should be clear upfront if a word is referring to an action, or a state/thing.

For example, in the glossary, there is: list, block, fediverse (what’s the difference with Fediverse with a capital?) and other individual words without context.

Other, like mute, have a description I can’t make sense of: «Target which activity was previously been hidden by the user or administrator (e.g. user mute → hidding any activity of the user).» To what does «target» refer to? Is it «a user mute» but when why is put in equivalence with a verb («hidding»)? The mistakes in the context doesn’t look like it has been reviewed…

**Comment by Sasha-Sorokin** [comment]
Hello. The term you are referring to was added by me and I'll remove it as soon as possible (I think it is displayed in project activity tab), I'm very sorry for the confusion its description caused and I didn't need to add it in the first place for source language. They are not reviewed and can be added or edited by anyone, so I was adding ones for the Russian and by some reason filled English description too (sleepyhead).

By the “target” I meant that it is either user or domain which activity (notifications and statuses) was previously hidden by the user (“hiding” is a little different from “blocking” as the so-called “target” can still look to user's profile and see their statuses), so it is an item in the list of “mutes”.

As far I understand, the “Glossary” is being generated by the Crowdin itself for initial establishment of terminology by the language translation team for further use in other files. You probably don't have to worry about translating it as you can use built-in Crowdin “Terms”, “Discussions board”, and for other files there will be generated “Context” right after the string (if you have struggle understanding where string belongs by looking at the “Context”, you can try searching it here on GitHub and see if any file pops up).

Hope that clears some things out.

**Comment by ariasuni** [comment]
> Hello. The term you are referring to was added by me and I'll remove it as soon as possible (I think it is displayed in project activity tab), I'm very sorry for the confusion its description caused and I didn't need to add it in the first place for source language. They are not reviewed and can be added or edited by anyone, so I was adding ones for the Russian and by some reason filled English description too (sleepyhead).

Sorry if it sounded like that, I don’t want to blame you (it’s sometimes hard to come with something understandable), but it seemed to that generally the glossary was of unequal quality in term of clarity and context (well, other translations as well but that’s another subject).

> By the “target” I meant that it is either user or domain which activity (notifications and statuses) was previously hidden by the user (“hiding” is a little different from “blocking” as the so-called “target” can still look to user's profile and see their statuses), so it is an item in the list of “mutes”.

I already understood that, but I was confused about how it appears in sentences/its relation to other words. So it’s mute like in «a user mute» so it’s «a mute», right?

Because I think that’s an important word we have to agree with when translating Mastodon.

> As far I understand, the “Glossary” is being generated by the Crowdin itself for initial establishment of terminology by the language translation team for further use in other files. You probably don't have to worry about translating it as you can use built-in Crowdin “Terms”, “Discussions board”, and for other files there will be generated “Context” right after the string (if you have struggle understanding where string belongs by looking at the “Context”, you can try searching it here on GitHub and see if any file pops up).

Since Crowdin list the Glossary as another file, it sounded like it worked differently than the glossary feature it already had, so I’ve been confused because of how Crowdin present it. But then, who’s managing the glossary? Is this another way for Crowdin to present the terms that appears in the «TERMS» tab of the right-side pane?

**Comment by Sasha-Sorokin** [comment]
> So it’s mute like in «a user mute» so it’s «a mute», right?

Correct!

> Is this another way for Crowdin to present the terms that appears in the «TERMS» tab of the right-side pane?

I think it is, because what I found out is that when I changed one string, it did automatically changed it in the “Glossary” file too (even though I have no permission to update source files).

At the first I thought this file is generated by Crowdin for any “common” words it finds in the files, but turns out it also adds translators' defined terms there too (you can try and find newly defined “Oops” word in it)!

It probably makes sense… whenever you translate string in “Glossary” file, it automatically assigns translation to the original term. At the same time feels very unnecessary, creates excessive work and confusion.

The best solution is probably to disable this “Glossary” file as none of these strings are used in Mastodon itself.

**Comment by Sasha-Sorokin** [comment]
@ariasuni no reason for closing the issue, I believe, the Glossary ‘file’ is still there and neither action, nor discussion has taken place yet.

**Comment by ariasuni** [comment]
Well, if I understand correctly it should be handled on a case-by-case basis, probably on CrowdIn directly, and I don’t think this issue would help with that.
