### ISSUE TITLE
2FA via private key file

### ISSUE THREAD

**Issue by MirceaKitsune** [tootsuite/mastodon#12392]
I figured I'd open this suggestion separately following discussion in #12363 earlier. Currently Mastodon relies on a complicated and inconvenient mechanism for providing 2FA: Two factor authentication consists of a checker image (QR?) which as of now I don't even know what I'm supposed to do with. As few instance owners have the means to setup a telephony service, 2FA via SMS login code is not an option we could easily consider.

I wanted to suggest a simpler alternative instead, which I remember seeing on a few sites in the past and believe strikes a good balance between convenience and security: Private key files. This is how it would work from my understanding:

- When you choose to enable 2FA from your account settings, you're offered and asked to download a small file containing a key (preferably encoded in binary format). For added security, this file is not emailed to you nor published elsewhere, it can only be directly downloaded from your account settings in the web interface or your Mastodon client.
- When you first login from a new device or browser which hasn't yet been registered with your account, you must upload this file from your hard drive after providing your password.
- If you ever lose your key file and can't login, you should be able to request a reset in the most secure way possible. Doing so would cause an email to be sent containing a private link available for a limited time and only usable once, which takes you to a page that asks for your password and potentially other data for extra verification. This step could also require manual review by a moderator to be even more confident it's you. If you pass every reasonable check, a new key is generated and the browser tells you to download the updated key. Once you do so you may attempt to login normally with the new key you just downloaded.

While this will require users to transfer a file on their SD card or with an USB stick, it would be more convenient for many compared to having to decode an image with specialized software. Apart from ensuring the reset procedure can't be abused in case the account's email address has also been compromised, it also feels like a secure approach: A key that you keep exclusively on your own hard drive is nearly impossible for an attacker to gain access to, unless they separately hack either the machine of the instance or your computer.

**Comment by Reverite** [comment]
I'm not sure if it can get easier than just downloading something like Authy and setting up 2FA using it? If there aren't instructions on how to set it up, there probably should be.

What you're describing seems more like a second, server-generated password, when the first password should be secure enough. Something like [a Yubikey](https://www.yubico.com/products/yubikey-hardware/) with authentication via [WebAuthn](https://webauthn.guide/) would probably be a better recommendation.

**Comment by nightpool** [comment]
Here are the current instructions for setting up 2fa:

> Scan this QR code into Google Authenticator or a similar TOTP app on your phone. From now on, that app will generate tokens that you will have to enter when logging in.

one of the benefits of 2fa is that it's time-locked—you can't use the same authentication response for two different periods of time. rolling some sort of custom "private key" solution does not have that property. Another benefit is that it leverages the inherent security/isolation of the current mobile ecosystem to enable better key management—it's much harder to malicious apps to read secrets out of protected phone storage, compared to personal computers.
