### ISSUE TITLE
Chat Rooms

### ISSUE THREAD

**Issue by irlcatgirl** [tootsuite/mastodon#12396]
### Pitch

Group DMs have a limitation to the amount of users that can be included which is equal to that of the text limit (mentions count agonist the limit, even in DMs, this is also helpful in not allowing someone to mention 1000s of users in one toot so there's a  solid case for keeping the behavior). Sometimes a larger group of people will want to chat. The current solution would be to use another chat service. What do you think about including chat rooms in Mastodon?

### Motivation

Avoids needing to switch to Discord or similar apps when you have a large group of people who need to chat at the same time.

**Comment by trwnh** [comment]
#3819
