### ISSUE TITLE
The embedded data is wrong

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#12433]
Since #12403 , the data embedded when posting a URL is incorrect.

### Expected behaviour
[This image](https://taruntarun.net/media_files/Mastodon/media_attachments/files/000/631/041/original/6f15a9982bf8ee96.png) is an embedding seen from a server that has not yet merged 12403.

### Actual behaviour
[This image](https://taruntarun.net/media_files/Mastodon/media_attachments/files/000/631/045/original/d1ab4938ba193367.png) is an embedding on the server that merged 12403.
That toot's URL is [here](https://edge.taruntarun.net/@mayaeh/103169120688963548).

### Specifications

Mastodon master branch d14e74eff52352f1a2fb4bc2053bbb28c1aa29e0 or later

**Comment by Gargron** [comment]
This is a bug because youtu.be uses youtube.com URL in the OEmbed discovery link so it doesn't get properly replaced by a placeholder by our code

**Comment by mstdn** [comment]
It is not fixed for the short version of the youtube url yet.

**Comment by mayaeh** [comment]
Probably the first post will get the wrong data even after merging to the latest master.
It looks like there is no problem after the second post.

Thank you!
