### ISSUE TITLE
API v2 search users on other instances throws 500 error

### ISSUE THREAD

**Issue by fweng322** [tootsuite/mastodon#12432]
My instance https://social.slat.org just upgraded to git tag 3.0.1 as well as upgrading Ruby to 2.6.5.  When I search for a user on another instance (e.g. @protonvpn@mastodon.social ) it ran for a few seconds and threw a 500 error.  In my nginx log I saw this line:

140.127.80.166 - - [20/Nov/2019:16:56:38 +0800] "GET /api/v2/search?q=@protonvpn@mastodon.social&resolve=true&limit=5 HTTP/2.0" 500 846 "https://social.slat.org/" "Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"

### Expected behaviour

It should be able to search without error

### Actual behaviour

It threw a 500 error

### Steps to reproduce the problem

Input '@protonvpn@mastodon.social' in the search bar and hit Enter

### Specifications

git tag 3.0.1

**Comment by ThibG** [comment]
I can't reproduce this. Can you check the puma logs? (`journalctl -u mastodon-web` depending on how you installed it)

**Comment by fweng322** [comment]
> I can't reproduce this. Can you check the puma logs? (`journalctl -u mastodon-web` depending on how you installed it)

https://pastebin.com/jGBF4TpU

What file is missing?

**Comment by ThibG** [comment]
It appears to be an issue with fetching and processing remote media. I really don't know why that fails or why it isn't properly caught though.

**Comment by fweng322** [comment]
> It appears to be an issue with fetching and processing remote media. I really don't know why that fails or why it isn't properly caught though.

seems not happen in other instances like g0v.social
I'm not sure either if it is caused by my process to upgrade to 3.0.1

**Comment by ThibG** [comment]
If the error is still occurring, can you edit `config/initializers/backtrace_silencers.rb` to uncomment `Rails.backtrace_cleaner.remove_silencers!`, restart `mastodon-web`, retry and give the full log?

**Comment by fweng322** [comment]
Please see the log here:

https://pastebin.com/j9hhRCsB

**Comment by fweng322** [comment]
This problem keeps happening when searching the same account @protonvpn@mastodon.social.  The log seems also the same: https://pastebin.com/NdDpAzWb

Besides the 500 error logged in access.log there is no any other logs or clues I could find out.  There seems to be no rules either:  at the same instance mastodon.social I could search out some accounts while some other accounts would return 500.  Same in other instance.

Is there anything I can do to dig out more?

**Comment by ThibG** [comment]
ok this is weird, you aren't using the same Paperclip version as Mastodon is supposed to (I guess this is why we never updated to the latest version). How did you run `bundle install`? Can you make sure `Gemfile` and `Gemfile.lock` are unmodified?

**Comment by fweng322** [comment]
> How did you run `bundle install`? Can you make sure `Gemfile` and `Gemfile.lock` are unmodified?

Oh, definitely modified.  When I upgraded to git tag 3.0.1 I got a lot problems when running `bundle install`.  I tried a lot without success, then I opened a new folder under ~mastodon/ to install the whole gems, and copied the generated Gemfile.lock and cache gem files to ~mastodon/live.  It worked.

Now my paperclip is 6.1.0 instead of 6.0.0.

Some days ago I tried again to revert Gemfile.lock to the version in tag 3.0.1.  It still failed to install.

**Comment by fweng322** [comment]
I have no idea why but I was forced to upgrade my gem packages version.  Here is the diff file for Gemfile.lock:

https://pastebin.com/gGNzGtwQ

**Comment by fleetside72** [comment]
Same issue. Fresh install. Proceeded to follow install instructions (https://docs.joinmastodon.org/admin/install/) until I got the `bundle install` and it said I had to upgrade. Did the upgrade and finished installation. Had various minor similar version issues but nothing glaring, this is the only problem I am experiencing currently. I'll have to check my detail logs when I get home.  It's kind of frustrating tho because unitl I fix this, I'm not sure how to follow anyone on a different server.

**Comment by ThibG** [comment]
Mastodon does not work with Paperclip 6.1.0. The `Gemfile.lock` is here for a reason, and you should not update dependencies.
I'm interested in whatever issues occurred during `bundle install` though.

**Comment by fleetside72** [comment]
well guess I should have started with some basics...mastodon-streaming isn't running due to looking for unavailable ClusterWS file cws_linux_79.
looking into that now.

**Comment by fweng322** [comment]
> Mastodon does not work with Paperclip 6.1.0. The `Gemfile.lock` is here for a reason, and you should not update dependencies.
> I'm interested in whatever issues occurred during `bundle install` though.

I started over with reverting back all the files including Gemlock.file, and removing vendor/cache.  Then follow the steps to reinstall again.  This time no complaints and Mastodon works.

So this issue was caused by wrong dependencies, though I couldn't reproduce how it went wrong.

Close this issue and thanks for your help.
