### ISSUE TITLE
Audio of video playback continues even when scrolled out of view.

### ISSUE THREAD

**Issue by anupverma20** [tootsuite/mastodon#12438]
Audio of video playback continues even when scrolled out of view.

### Pitch

I have seen an issue where it was requested to keep the audio playing for an audio playback. But, I thin it would be better to turn off the audio in case of a video playback.
### Motivation

When playing a video, audio is mostly required when user is viewing the video. When user scrolls and the video is out of view, it is unnecessary to hear the sound of video and causes discomfort.

**Comment by MirceaKitsune** [comment]
I'd just pause the video entirely when the user scrolls out of view. Just please no floating videos on the side of the screen: That drives me crazy whenever I encounter it on numerous websites.
