### ISSUE TITLE
Add all strings to language files

### ISSUE THREAD

**Issue by nclm** [tootsuite/mastodon#1244]
It seems like some strings are not exposed to translation. For instance:

```
spoiler_placeholder: { id: 'compose_form.spoiler_placeholder', defaultMessage: 'Content warning' },
```

“Content warning” is an important thing to translate, but `compose_form.spoiler_placeholder` isn’t in `en.jsx` so was never translated by contributors watching the original file.

Ideally, there has to be a way to automatically:
* Find every string from every file and put them back into the translation files.
* For strings already there, compare and display the possible difference between the `defaultMessage` and the one in the language file.

(I’m also wondering, but I don’t know enough about app development to know if it’s standard practice or not, if it’s really need to have both the default message and the line in the locale file. It seems like have the language file alone would make more sense)

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by carlosjs23** [comment]
This could be solved automatically by solving #1241

**Comment by nclm** [comment]
Yes and no. There would still be a need to complete the locales files before, since TranslateWiki or another tool would only provide an interface for editing them.

**Comment by Gargron** [comment]
`yarn run manage:translations` now keeps track of all of these, so this is no longer a problem.
