### ISSUE TITLE
domain_blocks api does not validate parameters

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#12452]
![image](https://user-images.githubusercontent.com/10606431/69476303-06e6bc00-0d9e-11ea-857f-81c662dea1eb.png)

`POST /api/v1/domain_blocks` accepts any string, allowing you to block a domain that has not been discovered by the server, does not exist, or is not a domain at all. The first two might be OK for pre-emptive blocking, but that last one maybe shouldn't be allowed?

**Comment by trwnh** [comment]
I should also add `DELETE /api/v1/suggestions` has a similar issue as `DELETE /api/v1/domain_blocks` in that it doesn't do any validation

**Comment by Gargron** [comment]
There is validation on the domain blocks API. `false`, `23879136` and `notarealsocial` are valid domain names. Mind you, they are unlikely to exist as websites, but they are possible. I suspect a domain block with a space would not work.

What does `DELETE /api/v1/suggestions` do without validation?

**Comment by trwnh** [comment]
i think i was mistaken about the suggestions, what i meant 3 days ago was that DELETE just renders an empty object even if the account/domain wasn't suggested/blocked or doesn't exist (so there's no indication if anything actually happened). but that's probably fine.

if POST of arbitrary data is not a concern then this issue can be closed
