### ISSUE TITLE
need mastodon-not-found.png in high resolution for Tusky

### ISSUE THREAD

**Issue by daycode** [tootsuite/mastodon#1245]
Need [mastodon-not-found.png](https://github.com/tootsuite/mastodon/blob/master/app/assets/images/mastodon-not-found.png) in high resolution, or the source vector image if possible to improve the display in Tusky for high resolution phones ( [Here in tusky](https://github.com/Vavassor/Tusky/issues/99) ).

Thank you.

**Comment by alerque** [comment]
The mastodon repository should probably have source vectors for all the artwork as well as a couple resolutions of the raster variants. There are a number of places even in the web interface where the current raster resources aren't right for the device. Not having the sources for any of them available makes it hard for anybody to contribute fixes in this area.

**Comment by Gargron** [comment]
I'm afraid the artist did not draw it in a vector format and he's busy until the 27th. I fully intent on commissioning him to do more (high-res) artwork for UI illustrations like this.

**Comment by wirehack7** [comment]
Nice idea. Would also be nice to have some icons as well to link them. Example: linking own account on a website via Mastodon Icon (like it already happens with Twitter and other accounts).

**Comment by DavidLibeau** [comment]
And to know if the draw is free to use (creative commons license) ?
Thanks

**Comment by elioqoshi** [comment]
I recreated it in vectors @Gargron : https://github.com/Vavassor/Tusky/issues/99#issuecomment-292805229

Let me know if I can help otherwise.

**Comment by Gargron** [comment]
@elioqoshi Thank you! 🐘 

Looks like this can be closed.
