### ISSUE TITLE
An interface for reading documentation

### ISSUE THREAD

**Issue by nclm** [tootsuite/mastodon#1247]
The documentation is currently [in the `docs` sub folder](https://github.com/tootsuite/mastodon/tree/master/docs). Which is nice to contribute, but not entirely easy to browse and read, especially the “Using” part which is destined to non-necessarily-technical persons.

Having an interface to browse and read the docs, maybe even edit them, in a nice and simple way would be a plus. [GitBook](http://gitbook.com) comes to my mind since it is great for this, but I’m not sure it’s free software (but GitHub isn’t either). We could set it up anyway, since it only reads from the git repo and do not change anything in the workflow, and look into open-source alternatives in the meantime to replace/complement it.

The docs would not have to move from here, though they might need their own repo? I understand the argument for keeping them in the main repository though.

(Something else to consider: translations of the docs?)

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by carlosjs23** [comment]
I think that many developers are familiar with the documentation is in the root of the repository, I see no major problem, what you mention may be more a problem on "How to read it more comfortable."

I've noticed that GitBooks has a free plan for open source projects, I think it's a good alternative and you do not have to move the documentation anywhere.

Let's wait and see what the maintainers think.

**Comment by ineffyble** [comment]
Back before Mastodon had a `docs/` folder I'd talked with @Gargron about options for docs. One easy thing to do would be to set up a ReadTheDocs free hosted HTML docs site, which would build automatically from `docs/` (or run our own using `mkdocs` which powers ReadTheDocs).

**Comment by SkyzohKey** [comment]
You might take a look at [PeachDocs](https://peachdocs.org/docs). :)

**Comment by wxcafe** [comment]
This thread on the mastodon-admin mailing list discusses this https://lists.ffdn.org/wws/arc/mastodon-admin/2017-04/msg00095.html

**Comment by nclm** [comment]
So, the docs are here now: https://github.com/tootsuite/documentation/

We can get them in one click on Gitbook!

PeachDocs sounds good but I get a 502 error on the link.

**Comment by carlosjs23** [comment]
@nclm +1 for get them in Gitbook

**Comment by nclm** [comment]
@Gargron Interested in this? If you create a Gitbook account and a Mastodon organisation there, you can link it to the Tootsuite one here and « make a new book » from the Docs repository, and then basically forget about it. That will set-up a simple interface to browse and read the documentation, with a link like https://mastodon.gitbooks.io/docs that we can share easily, always in sync with Github.

I was going to offer to do it but then realised that obviously I don’t have the rights on the organisations’ repo here.

**Comment by nclm** [comment]
I missed ineffyble’s suggestion for readthedocs.io, which sounds quite similar and seems perfect too. I guess we could try both, since they both just access the repo.

**Comment by nclm** [comment]
Moving to tootsuite/documentation/issues/52
