### ISSUE TITLE
Block in dropdown menu no longer working on mastodon.social

### ISSUE THREAD

**Issue by umonaca** [tootsuite/mastodon#12511]
### Expected behaviour

By clicking on the "block" in the dropdown menu of home, local, and federated timeline, it should show a dialog box prompting whether this user should be blocked.

### Actual behaviour

Nothing shows and nothing happens.

### Steps to reproduce the problem

Go to home, local, or federated timeline.
Click dropdown button next to any status to expand the dropdown menu.
Click "block".
Nothing shows up and nothing happens.

### Specifications

This happens on mastodon.social.

Browser: Chrome and Firefox. WIndows 10.

**Comment by umonaca** [comment]
No this does not fix the problem. Please reopen this issue.

**Comment by ThibG** [comment]
I am sorry, but I am unable to reproduce after that fix.
Have you recompiled the assets and restarted puma?

**Comment by Gargron** [comment]
I updated mastodon.social last night. But the bug tracker is for the software, not mastodon.social specifically. Something can be fixed or changed in the repository and not be visible on mastodon.social until I update.
