### ISSUE TITLE
Relationship seems broken if accept follow back on locked account

### ISSUE THREAD

**Issue by Kjwon15** [tootsuite/mastodon#12518]
### Expected behaviour

user A(locked account) and B(not locked) follows each other, than profile look like this:
("follows you" and "unfollow" button)
![image](https://user-images.githubusercontent.com/5047683/69933228-50a77300-1511-11ea-8176-7da8a54a9b88.png)

### Actual behaviour

It seems like there isn't any follows between A and B
![image](https://user-images.githubusercontent.com/5047683/69933143-045c3300-1511-11ea-9a2f-83665ea11de9.png)

### Steps to reproduce the problem

0. A is a locked account while B is not.
1. A follows B
2. B requests a follow back to A
3. A accept follow request from B
4. See B's profile on A's account

### Specifications

Mastodon version: v3.0.1

**Comment by Canorus** [comment]
+1

**Comment by ThibG** [comment]
Fixed by #12299 (please reopen if you can reproduce it after that merge)

**Comment by Kjwon15** [comment]
@ThibG Following is fixed but "following me" badge is not shown.
