### ISSUE TITLE
/auth/signin does not redirect back to /oauth/authorize properly anymore

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#12567]
occurs on mastodon.social latest master, with various clients like cuckoo.social and subway tooter. does not occur on an instance running 2.9.0

### steps to reproduce
- GET /oauth/authorize while not logged in, or with `force_login=true`
- you are redirected to /auth/signin in order to input email and password
- fill out details, click to advance

### expected behavior
- redirect back to /oauth/authorize so the newly logged-in user can confirm or deny the oauth request

### actual behavior
- redirect to /web and user has to exit and redo the "add account" step in their client from the beginning (without `force_login` this time)

**Comment by Aeternitaas** [comment]
Just followed up on this as of v3.0.1, the issue doesn't seem to be reproducible from the clients listed and more.

**Comment by trwnh** [comment]
Whatever code is running mastodon.social still gave me this behavior today.

**Comment by trwnh** [comment]
no longer occurs in 3.1?
