### ISSUE TITLE
If the account “Media storage” usage exceeds 2GB, “Data export” will fail

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#12572]
When the total amount of “Media storage” used by the account exceeds 2GB, “Data export” does not seem to run properly.

The backup file size is defined as `integer` in [backup.rb](https://github.com/tootsuite/mastodon/blob/master/app/models/backup.rb).
The `integer` does not seem to be able to handle more than 2GB.
See also: https://github.com/thoughtbot/paperclip/commit/34ec355e43e91c63288aab956a604f17471d4e59

What about measures to split the export file?

### Steps to reproduce the problem

I'm sorry, I haven't actually run “Data export” to confirm.
My main account disk usage is close to 5GB.
I can't try it because I think it will put a heavy load on the server.

However, I have received reports that running it on an account larger than 2GB failed.

**Comment by Gargron** [comment]
Good catch, I feel like we had a similar problem before...

**Comment by mayaeh** [comment]
Yes, I spoke about this at Discord about a year ago.
However, my misunderstanding was included at that time. And I forgot to discuss this matter.
