### ISSUE TITLE
Expanding all messages of a thread with a CW at once.

### ISSUE THREAD

**Issue by ProgVal** [tootsuite/mastodon#1258]
As #1123 pointed out, one has to click many times to view all messages in a thread with a CW.

It would be nice to be able to unfold all messages of a thread at once.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by sdukhovni** [comment]
I think a good way to implement this would be: when you click "show more" on one CW'd toot in a thread, all the toots in that thread with the *exact same* CW also open, but toots with different CWs remain closed in case the user doesn't want to see some tangential unpleasant topic that came up in the discussion.
