### ISSUE TITLE
Skip warning prompts in migrations when not in a TTY

### ISSUE THREAD

**Issue by sneak** [tootsuite/mastodon#12587]
### Pitch

First installs incur 3 different 10s delays applying initial database migrations.  It would be awesome if first installs could set an environment variable to skip these delays when deploying new instances.

**Comment by sneak** [comment]
Perhaps it could be even simpler: check to see if stdout is a tty, and skip the countdown if it is not (e.g. during migrations from a startup script).

**Comment by Gargron** [comment]
Don’t use db:migrate for first installs! db:setup is faster! It uses db:schema:load which just creates the latest schema right away instead of running migrations one by one

**Comment by sneak** [comment]
Well, it shouldn't do a 10s delay in any case even for a migration if stdout is not a tty.
