### ISSUE TITLE
proxy federated view to larger instances?

### ISSUE THREAD

**Issue by sneak** [tootsuite/mastodon#12599]
### Pitch

On a small or single-user instance, the federated TL is sparse and hurts discovery.  Many large instances have public api endpoints showing recent federated and local toots.  It would be nice if the web client fetched these and integrated them, or if the server periodically pulled them in when providing the federated timeline, to improve discoverability for new users.

### Motivation

Right now, on a small or single user instance, discoverability is hard due to the fact that the federated timeline is basically identical to the user's own timeline view.

**Comment by Cassolotl** [comment]
There's *federation relay support #7998*, which has already been merged, and a feature request for instances subscribing to specific other instances' public timelines, which I think is more like what you're asking for: *Instance-wide subscription #8082* Hopefully one of those two will help? If you think yours is a duplicate of #8082, you could close this and add your comments and 👍 reaction emoji over there?

**Comment by sneak** [comment]
You're absolutely right, thank you!  Dupe #8082.

**Comment by Cassolotl** [comment]
No worries! :) Happy to help.

**Comment by sneak** [comment]
@Cassolotl - is there any documentation anywhere about how to use a federation relay, or any public ones that are running?  It looks like the `relay.joinmastodon.org` one is gone.  This is the kind of thing that would solve my problem nicely.

**Comment by Cassolotl** [comment]
@sneak I'm afraid I don't know. @gargron might be able to tell you?

**Comment by sneak** [comment]
Did some digging.  For those searching, adding `https://relay.mastodon.host/inbox` as a federation relay in a new instance seems to work, as mastodon.host are running one and seem to approve new members within a day or so.
