### ISSUE TITLE
cannot locally boost remote mention after being blocked or defederated on remote instance

### ISSUE THREAD

**Issue by sneak** [tootsuite/mastodon#12597]
I attempted to boost an item in my mentions (on a remote server) by a user who had either blocked or de-federated me in between the mention and my attempt to boost.

### Expected behaviour

The message is boosted, as it is a local operation on my own instance

### Actual behaviour

403 error

### Steps to reproduce the problem

1. user a mentions user b
1. user a blocks user b
1. the toot remains in user b's mentions on b local instance
1. user b attempts to boost mention, boost fails despite b local instance still having a copy

### Specifications

c4118ba71ba31e408c02d289e111326ccc6f6aa2

**Comment by sneak** [comment]
Additionally this issue is the trigger for #12598 as well.

**Comment by nightpool** [comment]
#12598 *is* a bug—you shouldn't be able to view messages from users that have blocked you at all, but this isn't. you cannot interact with messages from users that have blocked you.

**Comment by sneak** [comment]
I am interested in interacting with a message that has been delivered to my instance *prior* to a block, which my instance already has in the local database.  Remote users don't get to retroactively delete things from my server without my consent.

**Comment by sneak** [comment]
The bug in #12598 is that the messages are *disappearing* after a remote block, not that they are showing up.
