### ISSUE TITLE
Option for Bookmarking/Saving Toots

### ISSUE THREAD

**Issue by thenanobel** [tootsuite/mastodon#12590]
### Pitch

I think it will be great if Toots can be bookmarked/saved on Mastodon. This feature will let users bookmark/save important and/or interesting Toots and help them find those Toots later.

### Motivation

I have been using this feature on Twitter and I have found it very helpful. I think, everyone will be helped if they can bookmark/save Toots.

**Comment by Gargron** [comment]
Already added in #7107
