### ISSUE TITLE
"Home" and "Notifications" timelines don't display/show avatars

### ISSUE THREAD

**Issue by KNTRO** [tootsuite/mastodon#12605]
### Expected behaviour

Avatar should appear normally.

### Actual behaviour

They are not shown in _Home_ and _Notifications_ feeds. Please, see red squared in the attached picture.

Nothing special.

Mastodon web 3.0.1.

Pale Moon web browser, Windows 10
![Mastodon_no_avatar](https://user-images.githubusercontent.com/2568821/70725724-a6cba180-1cdb-11ea-9263-5e9c1e280204.jpg)

**Comment by trwnh** [comment]
Most likely your instance's media provider is temporarily unavailable?

**Comment by KNTRO** [comment]
I don't know. That instance is mastodon.social. :neutral_face:

**Comment by Gargron** [comment]
> Most likely your instance's media provider is temporarily unavailable?

Yes, close enough. Recently moved from Wasabi to Exoscale, migration software didn't keep ACLs, Exoscale doesn't support bucket policies, so to make objects public-read again the entire bucket needs to be iterated, which is what I've been working on the past few days. So it's specific to mastodon.social, being worked on, and not a software issue.
