### ISSUE TITLE
Collision with word and user_setting_default_privacy select in french

### ISSUE THREAD

**Issue by ludovicl** [tootsuite/mastodon#1260]
Only when french is selected
<img width="636" alt="screen shot 2017-04-08 at 14 53 52" src="https://cloud.githubusercontent.com/assets/1071785/24829091/c4cd9332-1c6b-11e7-9cc8-4b723d468637.png">
page : settings/preferences
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Sylvhem** [comment]
@ludovicl This menu now use radio buttons. Can we close this issue?
