### ISSUE TITLE
Suggestion: polling for new toots from API of followed users on servers that choose to break AP federation

### ISSUE THREAD

**Issue by sneak** [tootsuite/mastodon#12600]
### Pitch

Some admins are unreasonable, and choose to deliberately break federation with other domains capriciously and arbitrarily, without clear criteria, sometimes based on rumor or gossip.  However, their servers are still publishing the public content of their userbase unauthenticated to the whole web.

It would be cool if one could still follow users on those servers by periodically fetching their data from the API instead of waiting for an inbox message that will never come due to an overzealous admin.

Additionally, it would be nice to still be able to search and discover those users even if the admin has suspended the federation to the instance hosting the person attempting to follow.  The data is published via the API, the reader should be able to poll it just like RSS used to work if the instance admin has disabled full AP federation.

### Motivation

Some server admins are unreasonable, and their userbase should not be punished with a reduced audience as a result of their choosing to ignore inbound federation messages from a given "bad" domain.  Servers don't have to do what the client wants with data that is *sent in*, but if they're serving *outbound data* to unauthenticated API requests (regardless of federation status with another instance), it would be nice if Mastodon could fetch and display that data.

My new personal instance was blocked today by a server admin for disagreeing with them (because apparently following other people on their server that hosts 19,300 accounts makes me a "threat" in the admin's eyes), and now I can't read any of those users' posts via my own instance&mdash;I have to go to their profile pages on the server directly.  The toot data from that site's users is still available and published to anyone on the web.  I just can't read it in my own instance.  That doesn't make sense to me when I can fetch it just fine in my browser.

**Comment by trwnh** [comment]
Browsing the public APIs can be done by some other app, but I am *strongly* against using the Mastodon API instead of ActivityPub.

**Comment by nightpool** [comment]
absolutely not. mastodon will not help you evade bans or blocks of any kind, no matter how "unreasonable" you might find an individual server owner. you don't have a right to force people to talk to you. 

what you're basically asking for is an unaccountable, invisible stalking tool, designed to violate user's boundaries. no.
