### ISSUE TITLE
Login/password for admin

### ISSUE THREAD

**Issue by aleksy91** [tootsuite/mastodon#12617]
Hello.

I install Mastodon.

What admin login/password?

**Comment by nightpool** [comment]
We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please use one of the resources below:

 - https://discourse.joinmastodon.org
 - #mastodon on irc.freenode.net

In this case, as documented in the installation guide, there's no "default" admin password, you have to create your account after installation and then give it admin permissions from the command line: https://docs.joinmastodon.org/administration/post-installation/#creating-an-admin-account
