### ISSUE TITLE
Searching for "" causes an internal server error

### ISSUE THREAD

**Issue by AtriusX** [tootsuite/mastodon#12619]
Noticed a minor issue when using the search function. Unsure if this has been reported yet or not but as far as I can tell it hasn't been.

### Expected behaviour

Searching for "" would result in an empty search

### Actual behaviour

The search causes an internal server error to occur

### Steps to reproduce the problem

1. Type "" in the search box and hit Enter

### Specifications

This bug was found on mastodon.social (3.0.1)

![error](https://user-images.githubusercontent.com/7331441/70876935-89236400-1f89-11ea-8007-c5fd8a14b187.png)

**Comment by trwnh** [comment]
Maybe #12462
