### ISSUE TITLE
Attached media from remote toot do not always carry over local copy

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#1261]
Hi,
I recently set up a single-user Mastodon instance, and while I've been able to see some toots with attached media, some others appeared on my instance with no indication they had attached media.

Here is one such toot: https://social.wxcafe.net/@Hypsoline/104187

And the logs from mastodon-sidekiq corresponding to the toot's handling on my instance: [mastodon-media-attachment.txt](https://github.com/tootsuite/mastodon/files/907466/mastodon-media-attachment.txt)

**Comment by Gargron** [comment]
The important bit here is:

```
avril 08 13:30:34 neiro bundle[3547]: [httplog] GET http://social.wxcafe.net:443/system/media_attachments/files/000/006/142/original/c76436b6ad120bcd completed with status code 200 in 0.06452989500030526 seconds
avril 08 13:30:34 neiro bundle[3547]:    (1.0ms)  BEGIN
avril 08 13:30:34 neiro bundle[3547]:    (1.4ms)  ROLLBACK
```
The rollback means the file failed to pass validation. This could have something to do with the original file not having an extension and thus not being served with the right mime type. Paperclip is very strict about content type spoofing

**Comment by Gargron** [comment]
It was probably the missing extension thing, which should now happen less often.
