### ISSUE TITLE
Cannot remove identity proof

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#12613]
### Motivation

The identity proof framework is in theory generic, but currently supports Keybase. Keybase identity proofs are immutable and not removable, so once an account is proven, it cannot be unproven (although the proof can be revoked if the private key is still accessible, or the account can be reset). However, this presents a problem on the Mastodon side of things, as it adds a UI element that cannot be removed.

The issue is that, of course, the account on either side of this proof can be compromised. It is up to Keybase if they want to deal with the implications of a proven account being compromised or not, but for Mastodon's case, it is unwise to assume a Keybase account will never be compromised (as Keybase themselves warn of when initiating an account reset).

### Pitch

- "Mark a proof as inactive" button to hide the proof from your profile.
- "Revoke a proof" button to remove it from your identity proofs.
- "Recheck proof" button to manually verify the identity proof.

**Comment by wnereiz** [comment]
Please fix this bug, thanks!

**Comment by lfuelling** [comment]
Keybase was just aquired by zoom: https://keybase.io/blog/keybase-joins-zoom

While the proof is no longer showing on my public profile, I can't remove the (no longer active) keybase proof from my profile settings.

**Comment by jeroenpraat** [comment]
Also when you remove a Keybase account the identity proof is still there and saying inactive. The expected result is that it's removed completely. The link on your profile is gone after a while.

**Comment by Krinkle** [comment]
Like many people, I had two Keybase accounts. The account I first created without a password (because it never told you to set one), and thus lost access to after a device upgrade. And the second account that I actually used.

There is no way to remove this old account from showing up on my Mastodon profile unfortunately. Its claim is still valid from the Keybase side, but that's backwards. Keybase is meant to hear from Mastodon that is valid, not the other way around. I want to remove it from my profile as I have no access to that Keybase account anymore.

**Comment by shleeable** [comment]
Jolly good. I deleted my account..

**Comment by smonff** [comment]
So the ability has been added, but the [user documentation says it's impossible](https://docs.joinmastodon.org/user/contacts/#proofs) to remove. What should I do?

**Comment by trwnh** [comment]
@smonff somewhere in settings there should be an "identity proofs" tab -- go there and you should see the new options.

**Comment by smonff** [comment]
> @smonff somewhere in settings there should be an "identity proofs" tab -- go there and you should see the new options.

Ok, thanks. My instance must not be up-to-date then.

**Comment by trwnh** [comment]
@smonff the tab only appears if you have a currently active identity proof, so that might be it too?

**Comment by smonff** [comment]
I see it but can't "delete" the proof. Anyway I festoyer the Keybase account and it automatically made the proof disappear from my public profile, so...

**Comment by ibnunowshad** [comment]
> @smonff the tab only appears if you have a currently active identity proof, so that might be it too?

I am in similar situation. I can't see any *Identify Proofs* Tabs in my Mastodon. What is my next approach here? Destroy Keybase? ;)

**Comment by Gargron** [comment]
There is no more Keybase in Mastodon

**Comment by ibnunowshad** [comment]
@Gargron 

Thanks!

I just gone through this issue [Remove all Keybase features from Mastodon #13670](https://github.com/mastodon/mastodon/issues/13670) and PR
[Remove Keybase integration #17045](https://github.com/mastodon/mastodon/pull/17045)
