### ISSUE TITLE
ERR_EMPTY_RESPONSE after Let's Encrypt installation.

### ISSUE THREAD

**Issue by stampylongr** [tootsuite/mastodon#12614]
### Expected behaviour
I should've been able to see the elephant hitting the computer screen (right after let's encrypt on the guide), but instead it gives me this page:
![image](https://user-images.githubusercontent.com/42777835/70856285-e2ff2d80-1ea6-11ea-902e-398ae0f30abb.png)

### Actual behaviour
It give me this page:
![image](https://user-images.githubusercontent.com/42777835/70856287-ef838600-1ea6-11ea-9ce9-d56788d7d730.png)

### Steps to reproduce the problem
I was following the guide.

### Specifications

I found this problem in the commit d53330f65b7dcb9f8e22244f5c72facb645213e3.

I am using the latest Opera version.

**Comment by ThibG** [comment]
This looks like an issue with your reverse-proxy (nginx?) rather than Mastodon itself

**Comment by stampylongr** [comment]
Oh. I'll take a look later today. Thanks!
