### ISSUE TITLE
trending hashtags moderation should have auto-approve

### ISSUE THREAD

**Issue by albjeremias** [tootsuite/mastodon#12650]
### Pitch
Well, right now i'm receiving many emails saying:
> "XXXX,
> 
> The hashtag #linux is trending today, but has not been previously reviewed. It will not be displayed > publicly unless you allow it to, or just save the form as it is to never hear about it again.
>
> Ver: https://domain.tld/admin/tags?pending_review=1

i'd like that instead of receiving this email, i could select an option on mastodon to auto-approve trending hashtags.. 

### Motivation
since i don't like this approach.. i think fires should be put down, instead of the approach of not using fire ignitors... It remmembers me the pre-censorship naçi.lulz infrastructure, which prevent information from passing, instead of simply blocking because it is an inappropriate hashtag.. this is how all mastodon works, i dont get why trending hashtags is different.. i guess there is lots of drama behind.

**Comment by albjeremias** [comment]
related https://github.com/tootsuite/mastodon/issues/12650

**Comment by Gargron** [comment]
Administration -> Site Settings -> Allow hashtags to trend without prior review

**Comment by albjeremias** [comment]
Can't find this.. Administration -> Site Settings.. 

I only have Administration -> Control panel & Administration -> emojis

**Comment by Gargron** [comment]
Are you sure you are using Mastodon?

**Comment by Gargron** [comment]
Does your account have admin privileges? I can only assume you are using a non-English locale where "dashboard" was translated as "control panel", because we never had a page called "control panel" in English. I think moderators can see the dashboard and custom emojis pages under Administration only.

**Comment by albjeremias** [comment]
:( u right
