### ISSUE TITLE
Icons on mobile are very small

### ISSUE THREAD

**Issue by sphinxc0re** [tootsuite/mastodon#1266]
Title says it all. This is very bad UX since it's very hard to land a click on these small buttons
<img width="400" alt="screen shot 2017-04-08 at 16 59 47" src="https://cloud.githubusercontent.com/assets/3702016/24829977/daae26d8-1c7c-11e7-944f-4a9afb0477cf.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
This seems to depend on the device, they're large enough imo on my iPhone SE (4" screen)

**Comment by ramlmn** [comment]
Think I already opened an issue about it. #1233
