### ISSUE TITLE
Broken link to elephant logo in README

### ISSUE THREAD

**Issue by johnjago** [tootsuite/mastodon#12688]
### Expected behaviour

There should be an elephant image in the [features section of the README](https://github.com/tootsuite/mastodon/blob/master/README.md#features).

### Actual behaviour

The link is broken. There is no elephant image at https://docs.joinmastodon.org/elephant.svg

### Steps to reproduce the problem

Open the README on the master branch: https://github.com/tootsuite/mastodon/blob/master/README.md#features

### Specifications

Not applicable.

**Comment by trwnh** [comment]
![image](https://user-images.githubusercontent.com/10606431/71427796-d8e8e600-2681-11ea-8421-9a09dd517f75.png)
for reference

**Comment by Gargron** [comment]
Fixed
