### ISSUE TITLE
Error on uploading audio with embedded image

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#12693]
When uploading an mp3 or oga/ogg file with an embedded image (e.g. an album cover), Mastodon gives this on screen error:

`422 Validation failed: File has contents that are not what they are reported to be`

When removing the image (with e.g. EasyTag) from the audio file, uploading is successful.

Tested it on todon.nl and mastodon.social.

### Specifications

Mastodon v3.0.1

**Comment by ThibG** [comment]
Unable to reproduce it on my install (attempted both ogg and mp3 files with embedded cover art). Do you happen to have one such file you can share?

**Comment by jeroenpraat** [comment]
@ThibG Yes I have. How do I sent it to you (it's 10MB)?

**Comment by ThibG** [comment]
What seems to occur is that some (the most recent?) versions of the `file` utility erroneously recognize some files as `application/x-font-gdos`
I'm not sure how we should work around that… the best bet seems to list all detected mime types (with the `-k` switch), and take the first that isn't `application/x-font-gdos`, but that's a rather ugly hack for an issue in `file` itself…

**Comment by jeroenpraat** [comment]
Thanks for looking into this. I'm glad you found the issue at least.

**Comment by saper** [comment]
@ThibG can you post some version details of the machine you are using to test? Which version of file/libmagic there?

**Comment by ThibG** [comment]
@saper I'm not sure. Considering the date, it was probably `file` 5.37-3 or 5.38-1 from ArchLinux. It seems to have been fixed since.

**Comment by saper** [comment]
Yes, the bug has been introduced in the 5.37 release of file (introduction of GEM GDOS font files recognition) and fixed in 5.38. 

I think we should not fix it here - it only should be clearly documented for people to find out.

5.37 contains arbitrary code execution bug https://bugs.archlinux.org/task/64430 so nobody should be running this.

**Comment by ThibG** [comment]
Closing as it's a bug in the `file` utility that should be fixed. If for some reason you cannot use a fixed version, you can look at the workaround in #12809.
