### ISSUE TITLE
Security: Enable security related HTTP headers for the frontend

### ISSUE THREAD

**Issue by fhemberger** [tootsuite/mastodon#127]
I couldn't find a proper place to add this, but you should provide some security related HTTP headers for your nginx config. It would be great if a config snippet for nginx and Apache could be included in the repository.

Disables clickjacking attacks via iframe:
```
X-Frame-Options: DENY
```

Enables XSS protection in IE:
```
X-XSS-Protection: 1; mode=block
```

Prevents IE from "sniffing" content types:
```
X-Content-Type-Options: nosniff
```

Enables [Content-Security-Policy](https://www.html5rocks.com/en/tutorials/security/content-security-policy/):

```
Content-Security-Policy: "default-src 'none'; 
  style-src 'self' https://fonts.googleapis.com/;
  font-src 'self' https://fonts.gstatic.com/;
  script-src 'self';
  connect-src 'self';
  image-src 'self';"
```

**Comment by drinkynet** [comment]
It is currently scoring a B on securityheaders.io it was a D earlier this morning, it looks like cookie flags was fixed.

CSP can be set in test mode and violations reported to an end point to help you validate a CSP before activating it. A useful explanation of testing and reporting can be found here: https://scotthelme.co.uk/content-security-policy-an-introduction/#testingapolicy

**Comment by Gargron** [comment]
I've setup all the headers except for CSP and Public Key Pinning. CSP seems complicated and I'm not sure if it'll break with React.js and its heavy use of inline styles.

**Comment by drinkynet** [comment]
Yes the CSP thing is complicated, you can explicitly allow inline styles however. A reference guide for CSP can be found here: https://content-security-policy.com

**Comment by joshtriplett** [comment]
Regarding the use of CSP, that would also need a bit of configurability; if you use a style that doesn't use remote fonts or styles (for privacy reasons), then you'd want to turn those bits off.
