### ISSUE TITLE
Upgrade Ruby 2.7 / Drop Ruby 2.4 - Notes/Problems

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#12704]
Known problems
* ~~cld3 doesn't support Ruby 2.7 - https://github.com/akihikodaki/cld3-ruby/issues/21~~
* ~~microformats doesn't support Ruby 2.7 https://github.com/microformats/microformats-ruby/issues/111~~

**Comment by catgirlsec** [comment]
Looks like it was fixed https://github.com/akihikodaki/cld3-ruby/issues/21

**Comment by Shleeble** [comment]
https://github.com/ruby-rdf/rdf/releases/tag/3.1.0 this drops supporot for ruby 2.4

**Comment by catgirlsec** [comment]
> https://github.com/ruby-rdf/rdf/releases/tag/3.1.0 this drops supporot for ruby 2.4

Why would Mastodon still need to support ruby 2.4 in its 2020 release? Ruby 2.4 was released in late 2016.

**Comment by Shleeble** [comment]
I'm waiting for Big G to push a stable before I submit housekeeping stuff to drop 2.4

**Comment by Shleeble** [comment]
It seems that 2.7 is not working beyond my ability to diagnose ATM.
#12763 is dying and needs to be investigated.
