### ISSUE TITLE
Free username "on use"

### ISSUE THREAD

**Issue by TheDavidDelta** [tootsuite/mastodon#12701]
I don't know if this is a good place for writing about this issue but I don't know where to ask bout it.

I singed up on mastodon (specifically on mastodon.social) time ago. Later in time, I deleted my account of all social media including mastodon, and now I'm trying to sign up again and it says the username is on use:

![image](https://user-images.githubusercontent.com/6679900/71537574-65173980-291e-11ea-9505-6aa4f2c47f84.png)

but, [as you can see here](https://mastodon.social/@TheDavidDelta), the profile page is invalid and doesn't exists.
I can't get my account by mail neither. That means that the account is deleted and the email is erased from database, but the username keeps being inthere, so the nick is unusable.

**Comment by nightpool** [comment]
for security and fraud reasons, mastodon does not allow you to reuse
usernames of deleted accounts

**Comment by TheDavidDelta** [comment]
Oh okey, so there's no way I get my nick even providing proofs of ownership?

**Comment by nightpool** [comment]
correct

**Comment by TheDavidDelta** [comment]
I'll look for a new nick then, thanks for your time

**Comment by trwnh** [comment]
to be more specific, you can force-reassign a username to a new account, but this is something an admin has to do manually through the [command line interface](https://docs.joinmastodon.org/admin/tootctl#tootctl-accounts-create) with `tootctl accounts create` and the `--reattach` flag.

**Comment by TheDavidDelta** [comment]
I'd be cool if someone could do it

**Comment by trwnh** [comment]
you would have to convince your old admin to do it, so contact them.

**Comment by Gargron** [comment]
> mastodon.social

Well, that admin would be me. E-mail me at staff@mastodon.social from the e-mail address you want to use with the account. I'll re-attach it.

**Comment by TheDavidDelta** [comment]
I've mailed you, tysm
