### ISSUE TITLE
Change how suspensions work

### ISSUE THREAD

**Issue by irlcatgirl** [tootsuite/mastodon#12739]
On Twitter when an account is suspended or a tweet is hidden from public view the original owner still has access. This is a request is provide that same behavior on Mastodon.

Account suspensions should still send a Delete Account Actor over federation. Accounts and Toots should have a “hidden” attribute to the postgresql table. If a moderator removes a toot it’s marked as hidden and only viewable to the author and deleted from federation, when suspended Mastodon is in a read only state, they can view their content but not create edit or delete existing content. You should be able to export your toots to take to another instance.

This will allow for users to backup their content and take it elsewhere if they disagree with a moderation decision.

Drawbacks: Attachments would have to be manually deleted when they’re illegal to host (e.g. child sexual abuse material) or all image loads would need to be authenticated (breaking caching)

**Comment by Gargron** [comment]
Oh hey I didn't see this one but you should know this was implemented in #14726
