### ISSUE TITLE
Install guide for Ubuntu

### ISSUE THREAD

**Issue by vielmetti** [tootsuite/mastodon#1273]
PR (work in progress) to do a Ubuntu install guide, for people with VPS, bare metal, amd64 and arm64 versions of Ubuntu 16.04 LTS.

There are a number of little issues that everyone is going to run into, so might as well corral them into a single descriptive document.

In particular some of these issues are addressed by the document:
* [ ] #869 Failing docker-compose build 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by savaricous** [comment]
I managed to successfully deploy mastodon with little issue following the production guide (non-docker) on an Ubuntu 16.04 LTS instance.

I tried docker and I ran into more problems than the production guide funnily enough.

I do think both guides could be improved some.

**Comment by wxcafe** [comment]
It'd be nice if accounts from admins of their experience installing mastodon on different platforms/OSes could be gathered and used to update the doc. I'll ask on https://lists.ffdn.org/wws/info/mastodon-admin

**Comment by wxcafe** [comment]
There's actually already a thread about this there and I've linked them to this issue https://lists.ffdn.org/wws/arc/mastodon-admin/2017-04/msg00095.html

**Comment by wxcafe** [comment]
There's also already an issue about this : #1247

**Comment by kyzh** [comment]
@vielmetti maybe you want to contribute to https://github.com/ummjackson/mastodon-guide/blob/master/up-and-running.md ?

**Comment by vielmetti** [comment]
Thanks @kyzh I am going to try that one out! Looks good so far.

**Comment by wxcafe** [comment]
Should this be closed then? so that discussion about documentation can continue on #1247?

**Comment by vielmetti** [comment]
This can be closed for the moment as the docs project has forked.
