### ISSUE TITLE
BARRITAR instead of TOOTear in the Spanish version/s.

### ISSUE THREAD

**Issue by mitcoes** [tootsuite/mastodon#12731]
BARRITAR instead of TOOTear in the Spanish version.

### Pitch

To TOOT in Castilian Spanish is "BARRITAR" the actual term used is TOOTear, just not translating it as if instead of translating BARRITAR by to TOOT, it would have been "to BARRIT" or similar.

### Motivation

In Spain we have the tendency of not translating because of ignorance and use the original word or something that sounds similar, historical errors are the "CANAL DE LA MANCHA" "stain channel" instead of "sleeve channel" CANAL DE LA MANGA from Canal de le manche or  English channel CANAL INGLÉS as it is said in English or PARAISO FISCAL because "tax haven" REFUGIO FISCAL was miss translated by error as if it where "tax heaven".

https://blogs.20minutos.es/yaestaellistoquetodolosabe/sabias-que-el-canal-de-la-mancha-deberia-llamarse-en-realidad-canal-de-la-manga/

PLEASE do not add ANOTHER MISTAKE to the Castilian Spanish translations that would shame the few with some culture here.

**Comment by Sasha-Sorokin** [comment]
Hi! Mastodon is primarily translated by the users themselves in [Crowdin project](https://crowdin.com/project/mastodon). Everyone can join and suggest or vote for correct translations there.

As from what I see, there are currently no votes for the translations you mention. If you suggest a few new ones, they will supersede currently used translations and will become available on the next merge (currently #12378 is pending).

[Here](https://support.crowdin.com/crowdin-intro/) you can learn more about Crowdin and how to contribute new translations.

---

*P.S. If this comment resolves your issue, you can close to help maintainers keep the tracker clean.*
