### ISSUE TITLE
Post without hashtag has ended up in the hashtag search

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#12745]
### Expected behaviour

Only posts containing searched hashtags appear in a search.

### Actual behaviour

![Screenshot 2020-01-02 at 21 46 34](https://user-images.githubusercontent.com/6607512/71695268-7ee6cf80-2da9-11ea-8d7b-2605f6d7b953.png)

![Screenshot 2020-01-02 at 21 46 44](https://user-images.githubusercontent.com/6607512/71695272-81e1c000-2da9-11ea-8f86-374597f83219.png)

[Post](https://monsterpit.net/@katnjia/103415362542407634)

### Steps to reproduce the problem

Honestly, I don't know how to help this get reproduced because not all instances have access to the same posts. Maybe if you replicate my pinned search column settings above, and search the post URL to get it into your instance? https://monsterpit.net/@katnjia/103415362542407634

### Specifications

3.0.1 vanilla.

Chrome on Mac 10.15.2.

**Comment by Gargron** [comment]
I don't know what monsterpit is doing but that post has hidden hashtags, which are visible in its JSON representation:

![grafik](https://user-images.githubusercontent.com/184731/71698175-cc1f6d00-2dba-11ea-9dc8-7dd46d81dfb2.png)

**Comment by Cassolotl** [comment]
Whoa, interesting. Thanks!
