### ISSUE TITLE
Update feeds/profile URLs from webfinger

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#1276]
Hi,
I have made a mistake when working on #1032 and incidently advertised incorrect URLs for my account in the XRD served on webfinger requests.
Therefore, the majority of the servers I'm interested in have incorrect URLs about my instance.

The current behaviour of mastodon seems to be looking up the user via webfinger, then checking if there is local information about that user. If not, local information is created with webfinger's response. Otherwise, there is no code path to update that informations, even if the URLs have changed (which is my case).

I'm not sure how to interpret the OStatus spec, but I think the local data for remote users should be updated with webfinger's reply, at least if one of the URLs errors out.

**Comment by Gargron** [comment]
:+1:
