### ISSUE TITLE
notification options to not see notifications from people you do not follow

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#1277]
this may sound insensitive or like it could hurt people, however, it has been seen to be a necessary feature on twitter, and i would very much prefer to have minute ability to customize this.

for each level of notification i would like to suggest a "except people you do not follow" option, that applies to all of the above selections.

for example, selecting "except people you do not follow" for favourites would not show people who you do not follow favoriting your toot. same for reblogs etc.

thank you for listening

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Is the difference to the already existing "block notifications from people you don't follow" the granularity by notification type?
