### ISSUE TITLE
Suggestion / Feature request: Filters > move the "ADD NEW FILTER" button

### ISSUE THREAD

**Issue by KNTRO** [tootsuite/mastodon#12790]
![Add_New_Filter](https://user-images.githubusercontent.com/2568821/71827970-256bf280-3080-11ea-96f6-296ce9a253dc.jpg)
### Pitch

I would like to suggest this: move the ADD NEW FILTER button here upwards, above the added filters.
https://mastodon.social/filters

### Motivation

The reason behind this is: the more filters I add, the more I have to scroll that page in order to add another filter, which is quite uncomfortable, as you can see in the attached picture.

**Comment by trwnh** [comment]
Duplicate of #11020
