### ISSUE TITLE
tootctl preview_cards remove: 0 files removed but 133k files remaining

### ISSUE THREAD

**Issue by angristan** [tootsuite/mastodon#12808]
### Expected behaviour

The preview_cards folder should be empty, I suppose?

### Actual behaviour

```
mastodon@mstdn ~/live> env RAILS_ENV=production bin/tootctl preview_cards remove
0/0 |=============================================================================================================================================================| Time: 00:00:00
Removed 0 preview cards (approx. 0 Bytes)
```

<img width="427" alt="Screenshot 2020-01-09 at 11 28 25" src="https://user-images.githubusercontent.com/11699655/72059925-3f514380-32d3-11ea-9f35-4f5da0d3cfcd.png">

I suspect something else is going on but there is no error...

### Specifications

v3.0.1

**Comment by Gargron** [comment]
Please check the —help output for options and their default values. The defaults don’t remove everything.

**Comment by angristan** [comment]
Thanks @Gargron, my bad :)
