### ISSUE TITLE
Make links and mentions not count in the toot character limit count.

### ISSUE THREAD

**Issue by hialvaro** [tootsuite/mastodon#12829]
## Pitch
When writing a toot, you sometimes lose a lot of characters posting a link or when replying you also lose characters with the mentions. 

## Motivation
I think not counting links and mentions in the toot character limit would be a nice way to simulate an increase of the toot length and keep consistency on how long the content you can write is. Letting admins change the character limit is a feature that has been requested several times. Also custom emojis could be counted as one character.

**Comment by Gargron** [comment]
URLs always count for 23 characters and domain names in mentions do not count at all. Usernames themselves count towards the character limit because they are visibile and to limit the amount of people that can be tagged in a single post.
