### ISSUE TITLE
Default bind address should be 127.0.0.1

### ISSUE THREAD

**Issue by plinss** [tootsuite/mastodon#1283]
The mastodon-web and mastodon-streaming services appear to be binding to 0.0.0.0 and [::] respectively, which makes them bind to all available addresses and are publicly visible, even though they are meant to be proxied through Nginx.

It would be better to bind to 127.0.0.1 (and/or [::1]) by default, making them only accessible locally. At the least, documentation of a bind address configuration option for each would be great.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by krainboltgreene** [comment]
Can you make a PR?

**Comment by Wonderfall** [comment]
Same for docker-compose : https://github.com/tootsuite/mastodon/pull/999
Apparently it was reverted? Although I prefer links (using Docker, binding like this is useless).

**Comment by Fastidious** [comment]
@plinss this is the reason my streaming never worked, I think! I wonder how come nobody noticed this before, but it really should get fixed.

**Comment by Exagone313** [comment]
I edited locally Mastodon to make this change, but I haven't made that cleanly to rely on configuration. Just have to edit the end of the streaming/index.js file and config/puma.rb.

**Comment by Fastidious** [comment]
@Exagone313 absolutely do not do that, not the right approach. A PR like #999 is the way to go.

**Comment by Exagone313** [comment]
This PR is for Docker.

**Comment by Fastidious** [comment]
@Exagone313 "A PR **like** #999 is the way to go." -- Not exactly, but like it. Make changes to main code as you did is not the right approach. If it works for you, OK, but it is not manageable.

**Comment by wxcafe** [comment]
Default bind address should definitely be 127.0.0.1 AND ::1. IPv6 should always be available, even on localhost (if only because some (many) OSes have 'localhost' resolve to ::1 by default)

**Comment by tripougnif** [comment]
Suggestion: mastodon streaming accepts a PORT env var. Could we also have HOST? For example, streaming/index.js could have:

server.listen(process.env.PORT || 4000, process.env.HOST || '::1', () => {

**Comment by Exagone313** [comment]
I would rather use `localhost` than `::1` (or `127.0.0.1`). But I don't know if Node uses both interfaces or not. `::1` may not be available.

**Comment by dracos** [comment]
The above fixed it for docker/allowed streaming to specify local binding only if you wanted (though the production guide leaves it open on all interfaces). But the web service using puma (as production guide says) still binds to 0.0.0.0. Assuming that's not wanted, I've submitted a PR.
