### ISSUE TITLE
Timed Silence

### ISSUE THREAD

**Issue by lynncyrin** [tootsuite/mastodon#1284]
As an admin it would be great to be able to do a timed silence on a user. Like, silence a user for X days / hours

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by krainboltgreene** [comment]
This involves adding a new UI, a new parameter to the silence action, and using the `perform_in` function.

Wanna contribute this @lynnco?

**Comment by lynnco** [comment]
I don't see myself having time for it, so I don't want to cookie lick.

**Comment by lynnco** [comment]
nvm I'm working on this!

**Comment by Gargron** [comment]
Do you see value in making the existing "silence" function a timed event, or is this a nomenclature clash and you're thinking more in terms of twitch chat timeouts?

**Comment by lynnco** [comment]
I'm thinking timeout. I'll rename it to "timeout" rather than "timed_silence" on my branch

**Comment by Gargron** [comment]
Alright! That definitely makes more sense, since the existing silence function is more akin to a hellban - more to guard the environment from the problem user than to re-educate the problem user.

**Comment by fsnk** [comment]
I'd like to see an optional timeout on user level (remote and local) suspend and silence, and also on instance level, since it seems like many admins are using instance level suspend and silence to deal with problems involving remote users rather than remote user suspension or silence.

**Comment by mal0ki** [comment]
@lynnco hey, wanted to check in and see if you're still working on this.

**Comment by LeeteqXV** [comment]
This is an interesting suggestion.
There is also another usage area for this, in relation to "information overload":

It would be practical to enable better focus during for example "work hours" by muting people who are for example very active but mostly with funny stuff that rarely is interesting when at work.

I think this function could be extra useful if combined with a filtering option like one or more regex rules per timeout rule, including "negatives" as in "exceptions".

For example: "Mute user X's toots between 8am-6pm, EXCEPT when he/she mentions @x, @y, or @z or uses hashtags #1, #2 or #3..."

**Comment by deutrino** [comment]
Can we clarify what we're talking about in this issue? I think @LeeteqXV is talking about a different subject than what this issue is intended to cover (see #1593).

- **silencing (the subject of this issue)** - a given user can be temporarily banned from posting, or their posts are temporarily hidden from certain areas
- **muting** - users can _ignore_ other users for a set period of time, such that toots from ignored users are collapsed or hidden in timelines, etc.

Is this correct?

**Comment by FerdiFZ** [comment]
Yes there are several different paradigms associated with silencing, muting, & blocking. _This_ issue, 1284, specifically tackles an _administration_ tool, a tool at admin-level if I may, where a misbehaving user can be frozen by an admin for a set period of time.

Meanwhile #1593 is tackling muting & blocking at the _user_ level. I think.

Kinda like how (at this moment) we have Instance-level Instance-blocking, and we _also_ have _User_-level Instance-blocking.

**Comment by lynncyrin** [comment]
FerdiFZ's comment is spot on 👍

Also, I didn't find time to tackle this one - so anyone should feel free to follow-up from here.
