### ISSUE TITLE
After #12748, changing the avatar icon or header image breaks the other

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#12849]
### Actual behaviour

After #12748, changing the avatar icon or header image will cause the other to disappear.
There is no problem if you update both the avatar icon and the header image at the same time.
Looking at the database, it seems that both file names have been updated just by updating one.

The following is a part of the result of running `Account.find()` with `rails console`:

#### 1. changing avatar icon

Before changing the account avatar icon:

    avatar_file_name: "64b397847c9444a0.png", 
    avatar_content_type: "image/png", 
    avatar_file_size: 186958, 
    avatar_updated_at: "2019-09-15 11:33:16", 
    header_file_name: "2e855ee6b57a6845.jpeg", 
    header_content_type: "image/jpeg", 
    header_file_size: 52504, 
    header_updated_at: "2019-09-15 11:33:17", 
    avatar_remote_url: "https://media-mstdn.maud.io/accounts/avatars/000/0...", 
    subscription_expires_at: nil, locked: false, 
    header_remote_url: "https://media-mstdn.maud.io/accounts/headers/000/0...", 
    last_webfingered_at: "2019-09-15 11:33:15"

After changing the account avatar icon:

    avatar_file_name: "6a3da1382290dbef.png", 
    avatar_content_type: "image/png", 
    avatar_file_size: 148970, 
    avatar_updated_at: "2020-01-13 03:30:19", 
    header_file_name: "282cb9f7a304a7fe.jpeg", 
    header_content_type: "image/jpeg", 
    header_file_size: 52504, 
    header_updated_at: "2019-09-15 11:33:17", 
    avatar_remote_url: "https://media-mstdn.maud.io/accounts/avatars/000/0...", 
    subscription_expires_at: nil, locked: false, 
    header_remote_url: "https://media-mstdn.maud.io/accounts/headers/000/0...", 
    last_webfingered_at: "2020-01-13 03:30:18"

#### 2. changing header image

Before changing the account header image:

    avatar_file_name: "7cc1618a2d34d781.png", 
    avatar_content_type: "image/png", 
    avatar_file_size: 106545, 
    avatar_updated_at: "2020-01-12 14:08:26", 
    header_file_name: "2b68cb3265caad29.png", 
    header_content_type: "image/png", 
    header_file_size: 666999, 
    header_updated_at: "2020-01-12 14:08:27", 
    avatar_remote_url: "https://s3.fedibird.com/accounts/avatars/000/014/2...", 
    subscription_expires_at: nil, locked: true, 
    header_remote_url: "https://s3.fedibird.com/accounts/headers/000/014/2...", 
    last_webfingered_at: "2020-01-12 14:08:26"

After changing the account header image:

    avatar_file_name: "1af8bd29ae405dd0.png", 
    avatar_content_type: "image/png", 
    avatar_file_size: 106545, 
    avatar_updated_at: "2020-01-12 14:08:26", 
    header_file_name: "5c8e8e6788d4297c.png", 
    header_content_type: "image/png", 
    header_file_size: 865409, 
    header_updated_at: "2020-01-13 06:38:51", 
    avatar_remote_url: "https://s3.fedibird.com/accounts/avatars/000/014/2...", 
    subscription_expires_at: nil, locked: true, 
    header_remote_url: "https://s3.fedibird.com/accounts/headers/000/014/2...", 
    last_webfingered_at: "2020-01-13 06:38:51"

### Specifications

Mastodon master branch 49b2f7c0a2aa41b1da77b652415078e19fcdcad8 or later

**Comment by Gargron** [comment]
> Looking at the database, it seems that both file names have been updated just by updating one.

Oh, oops... Yes, that's it.
