### ISSUE TITLE
Broken email validation in instances.

### ISSUE THREAD

**Issue by raisedadead** [tootsuite/mastodon#1286]
A user tried to create an account with "username@domain" missing the ".tld" part and surprisingly their account was created on my instance.

They of course now cannot create a valid account as their desired handle has been taken, suggesting that the basic email validation is broken.

On that note, any guidance on helping me edit the db at backend would be a sure help.

Thanks a lot.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
Email validation would be a pretty good thing to do. Meanwhile, you can do a `DELETE FROM accounts WHERE username='USERNAME';` in Postgres to delete their account, and they can then re-create it. Like always when you deal with a database, do a backup beforehand (`pg_dump mastodon_production` or something).

**Comment by wxcafe** [comment]
in #1131, @goingtomaine raises the point that there could be a timeout : if after some time the user hasn't confirmed their email, the username could be freed.

**Comment by raisedadead** [comment]
> if after some time the user hasn't confirmed their email, the username could be freed.

Agree, this could be very useful. Alternatively, can we add this as a feature in the admin UI? 

Of course, this may be taken up as a separate issue, because the current is scoped only to email validation in the form itself.

**Comment by wxcafe** [comment]
I created #1418 about this

**Comment by Gargron** [comment]
There are times when domains without TLDs are valid, such as on a private network. This is working as intended.
