### ISSUE TITLE
Removing @mention from toot does not update UI to reflect that it will not be a reply.

### ISSUE THREAD

**Issue by neauoire** [tootsuite/mastodon#12862]
### Expected behaviour

The replied-to toot in the compose box should disapear when removing the mention.

### Actual behaviour

See: https://merveilles.town/web/statuses/103478120240543757
Toot is sent out as a normal message, which UI indicated it as a reply.

### Steps to reproduce the problem

[video](https://merveilles.town/web/statuses/103478120240543757)

**Comment by Gargron** [comment]
It doesn’t need a mention to be a reply though

**Comment by neauoire** [comment]
Oh, I didn't realize that you could append to a thread without a mention.
I guess that makes sense, it's a bit weird, but it probably have a usecase.

I'll close the issue, thanks :wave:
