### ISSUE TITLE
Spam checker should ignore admins[/moderators]

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#12872]
I sometimes use a script to mass-DM admins of other instances, that just tripped the spam filter, which is obvs not very useful

### Specifications

v3.0.1+glitch

**Comment by Gargron** [comment]
Other instances won't be able to know or trust that you're the admin though

**Comment by nightpool** [comment]
@gargron right but if you're only DMing one person per remote instance,
then surely only the local spam filter is an issue
