### ISSUE TITLE
visually distinguish self-reply chains with no @ mentions on timelines

### ISSUE THREAD

**Issue by puphime** [tootsuite/mastodon#1287]
As in the title: there is no way to determine that a toot on a timeline is part of a chain without entering the single-toot display mode, which makes it very easy to miss that there *is* a chain.
ex. this toot is part of a chain, but I can only tell it is because of context. Lots of people have a habit of making threads without information in the post that it is a thread.
![2017-04-08_22-07-26](https://cloud.githubusercontent.com/assets/24903509/24832079/2a4df1ca-1ca8-11e7-9245-230a72dc0314.png)
(excuse my CSS)

Tweetdeck solves this by adding a "view conversation" label + an arrow (http://i.imgur.com/yvPdIVq.png) but i think an icon would be sufficient.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by hoodiek** [comment]
this can be closed now, as mastodon has implemented the double-arrow reply to button to show that it is in fact a reply to the same user
