### ISSUE TITLE
Ability To Defederate From Bluesky

### ISSUE THREAD

**Issue by LWFlouisa** [tootsuite/mastodon#12870]
With the ability to defederate from Gab instances, I thought it would be great to defederate from BlueSky instances. I find it unlikely that Twitter would align themselves with both forward thinking values and free software. 

I'm already concerned by the intrusion of Gab, and I feel like it sets a precedent farther reaching than just Gab using bits of Mastodon source code.

**Comment by mkljczk** [comment]
You can defederate from every domain you want. There is no gab-specific suspension feature in Mastodon.

**Comment by Gargron** [comment]
1. At this point it's unconfirmed what technology Bluesky will use
2. We would *prefer* if Bluesky used ActivityPub instead of creating its own proprietary protocol
3. "Defederation" works on a domain basis so you can defederate from whatever domains you want
