### ISSUE TITLE
Corrupted avatars in remote profiles

### ISSUE THREAD

**Issue by pioneer** [tootsuite/mastodon#12925]
### Steps to reproduce
Compare this profile on mastodon.social https://mastodon.social/web/accounts/886063
and the original profile https://mastodon.ml/@SiberiaBreadFactory

Also this https://mastodon.social/web/accounts/872604
and this https://barrett.dog/users/barrett

The original profile has a proper profile picture, whereas the mastodon.social one has a corrupted image. Can't find a proper duplicate of this bug, so submitting.

### Expected behaviour
Avatars should display accordingly as they are on the original instances, perhaps with applying proper resizing or so.

**Comment by Gargron** [comment]
This is a mastodon.social issue, not a software problem.

**Comment by pioneer** [comment]
Oh, good to know, I thought it may be an issue with image conversion while federating or so. Where to report this one then? Is there any tracker for mastodon.social?
