### ISSUE TITLE
The spanish translation got "trolled" 10 days ago

### ISSUE THREAD

**Issue by numeropi** [tootsuite/mastodon#12939]
Hi, the Spanish crowdin translations seems that 10 days ago a user that now appears as DELETED changed the translation for 'toot' for a non-sense word, and overwrote a 7months ago translation, not sure if he manipulated the voting system and was able to update the final import that github Mastodon has done of it here: https://github.com/tootsuite/mastodon/blob/105f83fc1e4830186e9d7cb91c5d4fda1798c602/app/javascript/mastodon/locales/es.json

Is there a way that maybe the import system to create the es.json doesn't care about the votes in each translation and takes by date the latest one?

Thanks in advance for the explanations.

![image](https://user-images.githubusercontent.com/56868560/73068693-1f617880-3eac-11ea-8db5-1ac0606b1d68.png)

**Comment by Gargron** [comment]
Fixed
