### ISSUE TITLE
Make server-signed Activity for account deletions in server-to-server negotiations

### ISSUE THREAD

**Issue by ClovisGauzy** [tootsuite/mastodon#12952]
From: Mastodon v3.0.1

### Pitch

Actual Delete:Person activity, mainly send into shared Inboxes, use the publickey of the deleted user for signing the request. But this one is obviously unreachable (410 error).

### Motivation

In my AP implementation, for speedup processing queries, I run parallel thread for verify signatures, when they don't use `digest` header. So when a deleted Actor is not fresh in my server's cache, it try to reach the key before processing request and got an error.  
I can reflow my work, it's not a problem. It just explain the way I've discovered it.

But I think it'll be more logical if servers sign byself user deletion requests for sever-to-server negotiations, mainly because "dead can't talk". :3

**Comment by ThibG** [comment]
The issue I have with this is that the instance actor would have to be considered authorized to delete actors, and it's not obvious how to describe such a fact.

The logic we had in mind (and which is implemented in Mastodon) is to skip `Delete`s from unknown accounts if the account and the target are the same object.
