### ISSUE TITLE
UI for admins to confirm users manually

### ISSUE THREAD

**Issue by ashfurrow** [tootsuite/mastodon#1297]
I've been having issues with confirmation emails getting stuck in pre-inbox spam filters (looking at you, FastMail...) and it'd be nice to be able to run a Rake command to confirm them manually. I'll take a look to see what I can do.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kballard** [comment]
FastMail is just running SpamAssassin, using a global bayesian filter by default, though users can switch to a local filter after classifying enough positive and negative messages.

For reference, once your emails finally came through to me, the one email I inspected had a spam score of 3.8 (I believe the default threshold for the Spam folder is 5.0), with the following calculation:

```
X-Spam-hits: BAYES_50 0.8, HEADER_FROM_DIFFERENT_DOMAINS 0.001, HTML_MESSAGE 0.001,
  RCVD_IN_INVALUEMENT 2, RCVD_IN_UNSUBSCOREBL 1, LANGUAGES en,
  BAYES_USED user, SA_VERSION 3.4.0
```

`RCVD_IN_INVALUEMENT` appears to be http://www.invaluement.com, and `RCVD_IN_UNSUBSCOREBL` is I think http://blacklist.lashback.com. I don't know why your emails are getting flagged from those blacklists though.

**Comment by ashfurrow** [comment]
Thanks for following up @kballard!

**Comment by wxcafe** [comment]
Can this be closed? Or do we consider that having a rake task (or any other method, maybe a UI in the admin interface) to manually confirm users is a feature we want to have? It is IMO, but I'd like to hear your thoughts

**Comment by ashfurrow** [comment]
It's a fair question! I've been doing it enough that, regardless, I'll be keeping the changes in #1300 alive in my fork.

**Comment by wxcafe** [comment]
I'm thinking having a UI in the admin interface for this would better really, but yeah, I feel like this would be a useful feature, along with maybe letting admins decide to not send emails when a user registers (that would enable instances with only manual approval of new users)

**Comment by kballard** [comment]
I agree that there should be an admin UI for this, because there will always be cases of people not getting the emails that they should. And I also agree that we should have a way for an instance to require admin approval for all new users. I'm already a member of an instance that would want that, because it's for a small social group of people who already know each other.
