### ISSUE TITLE
Hide announcement box in default when all announcement items have read

### ISSUE THREAD

**Issue by highemerly** [tootsuite/mastodon#12988]
This is the request about **announcement** feature. 

### Pitch

The key idea is:
- Restore the discard button for each announcement item (Related with #12954).
- Change the default settings of visibility:
   - Only if all active announcement item has discarded, hide `announcements__container` box (announcement box).
   - In other case, show the announcement box.

In this idea, the detailed user experience is here:
1. All user can toggle visibility settings of the announcements box in home TL, regardless the state of each item is discarded or not.
2. All user may show the new announcements in home TL.
3. The users who has read all active announcements don't need to show the announcement box in home TL.

In current master, 1. and 2. are satisfied, but 3. is not. Before #12954, 2. and 3. are satisfied, but 1. is not. In my idea,  all experience are satisfied.

### Motivation

I'm a admin of one of mastodon server. Some user says "The announcement box will hide the display area of home TL". 

Especially, the main concern of the current implementation is **the visibility state of announcement box is not saved**. Namely, even if a user turned off to hide the announcement box, after reloading the web page, the announcement box will be shown again.

In my opinion, if a user has already read all announcements, the default visibility of announcement box may be "hide". However, If at least one of the announcement item has not read yet, the default visibility may be "show". Please note that, in both cases, a user can be toggled the visibility settings of announcement box.

**Comment by tateisu** [comment]
simple boolean flag for each announcement id will not work because announcement can be edited/updated.

**Comment by ThibG** [comment]
Closing as I feel the new design for announcements (released in 3.1.1) addresses this issue.
Feel free to reopen if not.
