### ISSUE TITLE
add blurhash code for preview card thumbnail

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#13001]
It would be nice to have  blurhash code for preview card thumbnails and user can hide it.

related: https://github.com/tateisu/SubwayTooter/issues/127

**Comment by Gargron** [comment]
I think it would be nice to have blurhash for all images, like avatars and headers, as well

**Comment by trwnh** [comment]
might also pave the way for attaching `sensitive` to those images? (related: #6958, #6970, #9468, #10710)

**Comment by tateisu** [comment]
@Gargron Avatar images can be handled by muting the user. The header image will not be displayed unless user open the account details intentionally. Unlike them, we may want to hide preview cards at a different granularity.

**Comment by Gargron** [comment]
Oh, I wasn't thinking in terms of hiding. Loading on low-bandwidth networks...

**Comment by tateisu** [comment]
A button to hide thumbnails of preview cards has been added to SubwayTooter. 
The flags that are changed by user operation is re-use of NSFW. The initial state is affected by the post's sensitive flag.

I have 2 minor issues.
- preview card thumbnail has no blurhash, strange when lining just below the attached media.
- Mastodon's post UI cannot set sensitive flag without attached media.
Maybe my app users will understand and convince this situation.
