### ISSUE TITLE
Mastodon.social's Atom feed doesn't validate

### ISSUE THREAD

**Issue by KNTRO** [tootsuite/mastodon#1301]
[For instance, [this Mastodon.social's Atom feed](https://mastodon.social/users/KNTRO.atom) doesn't validate [as shown here](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fmastodon.social%2Fusers%2FKNTRO.atom) and as far as I've checked].

* * * *

- [✔️] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
It cannot validate because feed validators only know a handful of extensions/specs used here.
