### ISSUE TITLE
Remote avatars and user info updates inconsistently

### ISSUE THREAD

**Issue by kuro5hin** [tootsuite/mastodon#1303]
I see strange inconsistencies in when remote user avatars appear and when they don't. 

First example:

A remote user followed me, no avatar in the notifications column:
![screenshot 2017-04-08 19 01 50](https://cloud.githubusercontent.com/assets/3065686/24833152/7774bd54-1c8e-11e7-989b-04d666d1475e.png)

I clicked the user to open it in the right column, still no avatar:
![screenshot 2017-04-08 19 01 56](https://cloud.githubusercontent.com/assets/3065686/24833155/8e699480-1c8e-11e7-863d-85fa14539b36.png)

I clicked the user's avatar image to open their actual public url in a new tab, and they do have an avatar set:
![screenshot 2017-04-08 19 02 07](https://cloud.githubusercontent.com/assets/3065686/24833158/a776a59e-1c8e-11e7-8c59-ba5c0e424cd5.png)

But nothing I do locally makes it update for me. I still only get a default avatar in my own instance.

Second example:

I see a toot by a remote user in my federated timeline. No user avatar:
![screenshot 2017-04-08 19 02 58](https://cloud.githubusercontent.com/assets/3065686/24833171/e19cc852-1c8e-11e7-9607-6a89b8e4b256.png)

I click the avatar to open their account in the right column, and after a moment, the avatar and user info _does_ appear:
![screenshot 2017-04-08 19 03 07](https://cloud.githubusercontent.com/assets/3065686/24833175/f7304388-1c8e-11e7-95e0-aecf1b7bbc18.png)

Now when I go back to the federated timeline, the avatar remains.

This doesn't happen with everyone -- it's a relatively small proportion of accounts, but it's been quite constant. I'm currently running 470eb0042ea99e0632ccc62a0b7c01e910f70491.

* * * *

- [✅ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kuro5hin** [comment]
Update: The "ninja" one did eventually appear by itself! Others don't (unless, maybe, eventually they do???). I am happy to do any kind of digging in logs or databases or anything that would help track down whether this is just how things are or there's actually a bug somewhere.

**Comment by Gargron** [comment]
They update in the background (sidekiq) since recently. Could be reason for delays if queues are busy.

**Comment by rhaamo** [comment]
Ah ! Not the single one definitely having this issue, as my instance is single user for now it would be strange to have queue busy more than few seconds.

**Comment by maximeborges** [comment]
Same problem as I already said on Discord, my instance has only 4 members but I'm the only one active, and I really only have a few toots on my federated time line per day, and I'm not receiveing/sending more than 20 toots a day. So Sidekiq souldn't be busy at all and be able to pull the data in less than 10 hours, and it's not even the case so it would certainly be a problem on the server side...

**Comment by wxcafe** [comment]
I have the same thing happening semi-regularly. My Sidekiq queues are pretty empty too. This seems to come from somewhere else

**Comment by blakebarnett** [comment]
Seeing this also, most remote profile pictures never show up, but some do.  Queues are not busy at all (fairly new instance)

**Comment by zaksoup** [comment]
I'm seeing this as well. on b22b2cbfacdaef2441d14f401c95863d8ca2e66c

**Comment by zaksoup** [comment]
@blakebarnett @wxcafe @maximeborges @kuro5hin etc, I just noticed that my start command for the sidekiq process did not have the n ew `pull` queue. can you all double check that your start command matches what's currently in the procfile? Updating the sidekiq start command to `bundle exec sidekiq -q default -q push -q pull -q mailers` has solved this issue for me...

**Comment by wxcafe** [comment]
yeah it does for me.

**Comment by blakebarnett** [comment]
Mine didn’t at first, and I was hoping it would solve the issue as well, but it’s been properly running for 2+ days now and still avatars are quite slow to show up or never do in some cases.  Media attachments are always immediate however.

**Comment by jamesmwright** [comment]
`bundle exec sidekiq -q default -q push -q pull -q mailers`

That's what's running for me.. however, I am running into this issue on my single instance under v1.2.2. Remote folks show no toots or follow/followers, then I start to see new activity, but not past activity.

**Comment by wxcafe** [comment]
that's normal. We were talking about remote user's profile pictures never showing up, which is /not normal/

**Comment by jamesmwright** [comment]
No, it is not normal-some users I can never view their follow/followers even after we follow each other. It looks like they only have me as a follower and follows me. 

<img width="512" alt="screen shot 2017-04-20 at 2 16 06 am" src="https://cloud.githubusercontent.com/assets/25876554/25223167/74ad72de-256f-11e7-81ef-61836c7181fa.png">
<img width="319" alt="screen shot 2017-04-20 at 2 15 19 am" src="https://cloud.githubusercontent.com/assets/25876554/25223171/75f076fa-256f-11e7-8335-2abf92427b7b.png">

**Comment by wxcafe** [comment]
yes, that's because they're remote users. Hover over the "followers" count and you'll see a tooltip that says exactly this. This is expected behavior.

**Comment by jamesmwright** [comment]
I still don't agree, when I view this user remotely from mastodon.social, I see everything (and I don't even follow this person from there)...it's not expected behavior. 

I'm trying to figure out if my instance is broken or the remote (which is a great deal of them), or the code...

<img width="577" alt="screen shot 2017-04-20 at 2 23 11 am" src="https://cloud.githubusercontent.com/assets/25876554/25223479/5680bb4e-2570-11e7-8077-dc1be3200aae.png">

**Comment by jamesmwright** [comment]
Here is another example... on mastodon.social, it seems to let me explore their followers/follows verses my instance always says 1:1 for them. It's weird. The worker container I have running is:
`bundle exec sidekiq -q default -q push -q pull -q mailers`
Not sure what I'm missing, but I think others are having this same problem. 

<img width="1313" alt="screen shot 2017-04-20 at 2 33 04 am" src="https://cloud.githubusercontent.com/assets/25876554/25224070/27e2b63c-2572-11e7-89b5-f9cf7ef256ae.png">
<img width="1322" alt="screen shot 2017-04-20 at 2 35 03 am" src="https://cloud.githubusercontent.com/assets/25876554/25224071/27e374f0-2572-11e7-858f-8d0158180670.png">

**Comment by wxcafe** [comment]
Look. Each instance only has information about a remote user from when that user started federating with that specific instance, so you only see follows/toots/whatever since then. THIS **IS** EXPECTED BEHAVIOR. This issue is **NOT** the place to talk about this.

**Comment by jamesmwright** [comment]
**Thanks**

**Comment by wolfteeth** [comment]
Been having the avatar issue with a couple remote users I follow on my small instance (9 users, most not very active). It's weird that someone I actually follow doesn't have their avatar show up. Looking at their remote profile, they do have an avatar.

**Comment by Gargron** [comment]
Has this been an issue in the latest releases? It doesn't seem so, and individual troubleshooting cases are better served on discourse.joinmastodon.org, or stackoverflow

**Comment by wolfteeth** [comment]
I still see it on v1.4.1.

**Comment by Gargron** [comment]
@wolfteeth Could it be some remnant of previous failures, i.e. your server thinks it downloaded the avatar, but actually the file isn't there? And the server won't redownload the avatar unless its original URL changes. This might be resolved by adding functionality for #2848

**Comment by wolfteeth** [comment]
@Gargron that could be. I can wait and see.

**Comment by sdukhovni** [comment]
I'm still seeing this issue now on v1.4.6, with users I haven't previously looked at.

**Comment by Gargron** [comment]
Avatars are fetched in the background so first look up is gonna give empty profile.

**Comment by sdukhovni** [comment]
OK, but my sidekiq queue is empty and I'm still not seeing an avatar.

**Comment by wakest** [comment]
can anyone else confirm what @MichaelHierweck said above to be true? because that seems like something that might need to be fixed. Just ran into this problem today.

**Comment by oe4dns** [comment]
I'm also experiencing a, seemingly related, problem. Avatar Pictures from Friendica contacts are never updated at Mastodon while changes are correctly propagated to other Friendica (obviously) and Pleroma instances.

A thought that comes to mind. Could it be that Mastodon only updates a profile picture if its URL changes and not if there is a fixed reference or none at all?

**Comment by valvin1** [comment]
same as @oe4dns my friendica avatar is not updated on mastodon side.
