### ISSUE TITLE
Support FILF Image Format

### ISSUE THREAD

**Issue by Shleeble** [tootsuite/mastodon#13047]
### Pitch
https://flif.info/ it seems to be a patent free and extremely high quality image format.

### Motivation

FOSSy, high quality images and animations?

**Comment by Gargron** [comment]
What's the point if a browser can't render it?

**Comment by TheDecryptor** [comment]
No point in supporting FLIF when it's successor (FUIF) was itself used as the basis for JPEG XL, that's more likely to get browser and tooling support.
