### ISSUE TITLE
querying other instances results in 404 half way through

### ISSUE THREAD

**Issue by fleetside72** [tootsuite/mastodon#13041]
Search has never worked for me when querying other instances, but works fine for local users/hashtags. I cannot follow anyone, and no one can follow me.

If I log on to a foreign instance and query back to my local user this is what my local nginx logs give:
```
ip4_here - - [02/Feb/2020:19:59:55 -0500] "GET /.well-known/webfinger?resource=acct:user@local_domain HTTP/1.1" 200 425 "-" "http.rb/3.3.0 (Mastodon/3.0.1; +https://foreign_domain/)"
```
which returns with a 200 - all good; webfinger translated correctly and returned 200.
then the subsequent attempt to grab the user results in a 404:
```
ipv4_here - - [02/Feb/2020:19:59:55 -0500] "GET /users/me HTTP/1.1" 404 36 "-" "http.rb/3.3.0 (Mastodon/3.0.1; +https://foreign_domain/)"
```

The only issue I had installing was that bundle complained about being outdated, so I upgraded.
And then I had some version issues with node, but got that pointed to lts and everything else has run fine.

**Comment by fleetside72** [comment]
Are there any additional logging options I can use for further detail, or can someone point me to where in the project this is handled?

**Comment by Gargron** [comment]
If you don't censor which profile/instance this is about I might be able to check the responses

**Comment by fleetside72** [comment]
here's the full local nginx logs searching for myself `paul@hptrow.me` from foreign instance `https://social.linux.pizza/web/search` :
```
54.37.254.26 - - [02/Feb/2020:19:59:55 -0500] "GET /.well-known/webfinger?resource=acct:paul@hptrow.me HTTP/1.1" 200 425 "-" "http.rb/3.3.0 (Mastodon/3.0.1; +https://social.linux.pizza/)"
54.37.254.26 - - [02/Feb/2020:19:59:55 -0500] "GET /users/paul HTTP/1.1" 404 36 "-" "http.rb/3.3.0 (Mastodon/3.0.1; +https://social.linux.pizza/)"
```

**Comment by Gargron** [comment]
Weird, so I can open those URLs just fine from the browser. This makes me believe it's a HTTP-Signature-related problem, since servers authenticate themselves when fetching profiles. So the 404 may be caused by some record not being found -- it is not an expected condition, the code is supposed to only ever return 401 or 403 when something is wrong with the signature.

Have you tried with a server other than social.linux.pizza?

**Comment by fleetside72** [comment]
* I have not tried foreign->local searches elsewhere I'll have to join somewhere and try it.
* ProgVal from IRC was kind enough to join hptrow and do a search back against their instance with similar log results back on their side: hptrow successfully does a webfinder but fails after that
* I think at this point I need to do a clean install and then be more carefull with setup, then if it works I can diff back to the old directory and see what changed. I guess I'll have to diff //etc as well.

Thanks for responding!!

**Comment by fleetside72** [comment]
did a clean install on same machine. works now. ¯\_(ツ)_/¯
thanks.
