### ISSUE TITLE
Announcements glitch - disabling all announcements display all announcements?

### ISSUE THREAD

**Issue by Shleeble** [tootsuite/mastodon#13050]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/17537000/74080213-89694880-4a7c-11ea-9661-07943ad233ac.png">

<img width="59" alt="image" src="https://user-images.githubusercontent.com/17537000/74080223-aa319e00-4a7c-11ea-8ee0-05dcfd2c5ca5.png">

### Expected behaviour

Disabled Announcements should be hidden

### Actual behaviour

Both seem to be visable

### Steps to reproduce the problem

disable all announcements.

**Comment by ThibG** [comment]
I do not understand this bug report. Those announcements seem pretty much published to me, according to the screenshot?

**Comment by Shleeble** [comment]
ooooh face palm
This is me misunderstanding the UX. I assumed unpublish was the status, not an action.

I expected "Published" / "Unpublished" as a status... Sorry.
