### ISSUE TITLE
[enhancement] Markdown Support in Toot Text

### ISSUE THREAD

**Issue by gitjeff2** [tootsuite/mastodon#1305]
It would be nice if toots supported GitHub Flavored Markdown naively. This way toots could be be formatted with italics, bold, strike-through, well formatted lists, quote blocks, etc.

**Comment by krainboltgreene** [comment]
Duplicate of #761 #1031 #421.

When creating a new issue there's a checkmark that asks that you have looked for this issue in the issue list. *Please* do not ignore this when making new issues.

**Comment by gitjeff2** [comment]
Sorry about that @krainboltgreene. I did in fact search but didn't see those issues.

**Comment by krainboltgreene** [comment]
Okay, thanks for responding. If you could upvote one of those threads that would be great (or do a rough implementation).
