### ISSUE TITLE
Inconsistent custom 404

### ISSUE THREAD

**Issue by Komic** [tootsuite/mastodon#1308]
Mastodon does not throw its custom 404 when a user attempts to access _https://domain/blah.blah_ (it does work when trying to access _https://domain/blah._ or _https://domain/blah_). Also happens with (i.e.) _https://domain/sidekiq/blah.blah_.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ineffyble** [comment]
Interesting - guessing this is an issue with nginx vs rails

**Comment by Komic** [comment]
Apache behaves the same way, if that helps~

**Comment by mjankowski** [comment]
The rails router probably establishes the format of `/blah` as HTML, but does not get HTML as a format for `/blah.blah` - so the catch-all route will send both to `raise_not_found` but only the one it thinks is html will get the custom page.

I suspect that adding `format: false` to that catch-all route might help here.

**Comment by Gargron** [comment]
I am not seeing this on mastodon.social... The example nginx config (that .social also uses) contains an `error_page` directive that handles 50x and 40x errors whenever possible. Our nginx config also contains a `proxy_intercept_errors on;` directive in the proxy definition, which displays the defined `error_page` in case there is not output from the upstream server (e.g. when it responds with HEAD)

**Comment by mjankowski** [comment]
Instance hosted on Heroku for an account which doesn't exist:

- https://betterletter.io/blah - 404 status and 404 html page
- https://betterletter.io/blah.blah - 404 status but no html body
