### ISSUE TITLE
"docker-compose up --build" not working

### ISSUE THREAD

**Issue by pchico83** [tootsuite/mastodon#13087]
### Expected behaviour

I want to start to contribute to mastodon and I want to run a local development environment with docker-compose. I edited the docker-compose.yaml file to point `env_file: .env.production` to `env_file: .env.production.sample`. Then, I run `docker-compose -d up --build`. 
After a few minutes, the `web` and `sidekiq` keep failing:

```console
% docker ps -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                         PORTS                                NAMES
a0164e5d9907        tootsuite/mastodon    "/tini -- node ./str…"   7 minutes ago       Up 7 minutes (healthy)         3000/tcp, 127.0.0.1:4000->4000/tcp   mastodon_streaming_1
ca5cc0d321a7        tootsuite/mastodon    "/tini -- bundle exe…"   7 minutes ago       Restarting (1) 7 seconds ago                                        mastodon_sidekiq_1
bb6ea1f64d29        tootsuite/mastodon    "/tini -- bash -c 'r…"   7 minutes ago       Restarting (1) 3 seconds ago                                        mastodon_web_1
fef8cc8d2450        redis:5.0-alpine      "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes (healthy)                                              mastodon_redis_1
d9418b922665        postgres:9.6-alpine   "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes (healthy)  
```

Instead, mastodon should be running and accessible at localhost:3000 and localhost:4000

Also, it would be nice to have a **development guide**.

### Actual behaviour

`web` and `sidekiq` keep failing.

### Steps to reproduce the problem

- Edit the docker-compose.yaml file to point `env_file: .env.production` to `env_file: .env.production.sample`
- Rrun `docker-compose -d up --build`

### Specifications

I am running from the *master* branch in MacOS.

**Comment by Gargron** [comment]
The sample file is not viable plug-n-play configuration. It’s intended to be customized

**Comment by pchico83** [comment]
@Gargron is it documented how to customize it?

**Comment by SuperSandro2000** [comment]
This should help you https://docs.joinmastodon.org/admin/install/

**Comment by pchico83** [comment]
@SuperSandro2000 thanks!
