### ISSUE TITLE
'Disclose application used to send toot' doesn't seem to work

### ISSUE THREAD

**Issue by rodti** [tootsuite/mastodon#13091]
### Expected behaviour

Unticking the 'Disclose application used to send toot' option in a user profile and saving should suppress the client from the detailed view of future roots.

### Actual behaviour

Toots from web and native clients still show the client name in the detailed view of a toot.

### Steps to reproduce the problem

Untick 'Disclose application used to send toot' in profile. Save changes. Toot from web or native client. Look at detailed view of that toot. Raise eyebrow.

### Specifications

Tested in v3.1.1 web client, Toot and Tusky apps (as confirmed by myself and the mas.to user who initially made me aware of this issue)

**Comment by Gargron** [comment]
The author of the toot can always see what app was used, to detect app misuse

**Comment by rodti** [comment]
Ah! Thanks for explaining that.
