### ISSUE TITLE
Migrated server to linode - email has stopped working.

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#13111]
Hey, 

I'm getting Net::OpenTimeout on SMTP.. everything else seems to be working fine.

> sidekiq_1    | 2020-02-17T10:54:32.614Z 7 TID-or6mqla9r ActionMailer::DeliveryJob JID-6bd88ba81ff86b09fa7e3115 INFO: fail: 30.11 sec
sidekiq_1    | 2020-02-17T10:54:32.614Z 7 TID-or6mqla9r WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::DeliveryJob","queue":"mailers","args":[{"job_class":"ActionMailer::DeliveryJob","job_id":"730927ec-a49e-476d-913f-bf282d49b559","provider_job_id":null,"queue_name":"mailers","priority":null,"arguments":["UserMailer","confirmation_instructions","deliver_now",{"_aj_globalid":"gid://mastodon/User/948"},"VLdk71mpK4FzJWUDS_iw",{"_aj_symbol_keys":[]}],"executions":0,"locale":"en"}],"retry":true,"jid":"6bd88ba81ff86b09fa7e3115","created_at":1581936454.3939538,"enqueued_at":1581936842.5036938,"error_message":"execution expired","error_class":"Net::OpenTimeout","failed_at":1581936484.4991121,"retry_count":3,"retried_at":1581936730.6938004},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::DeliveryJob\",\"queue\":\"mailers\",\"args\":[{\"job_class\":\"ActionMailer::DeliveryJob\",\"job_id\":\"730927ec-a49e-476d-913f-bf282d49b559\",\"provider_job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"UserMailer\",\"confirmation_instructions\",\"deliver_now\",{\"_aj_globalid\":\"gid://mastodon/User/948\"},\"VLdk71mpK4FzJWUDS_iw\",{\"_aj_symbol_keys\":[]}],\"executions\":0,\"locale\":\"en\"}],\"retry\":true,\"jid\":\"6bd88ba81ff86b09fa7e3115\",\"created_at\":1581936454.3939538,\"enqueued_at\":1581936842.5036938,\"error_message\":\"execution expired\",\"error_class\":\"Net::OpenTimeout\",\"failed_at\":1581936484.4991121,\"retry_count\":3,\"retried_at\":1581936730.6938004}"}
sidekiq_1    | 2020-02-17T10:54:32.614Z 7 TID-or6mqla9r WARN: Net::OpenTimeout: execution expired
sidekiq_1    | 2020-02-17T10:54:32.614Z 7 TID-or6mqla9r WARN: /opt/ruby/lib/ruby/2.6.0/net/smtp.rb:539:in `initialize'

Any idea?

**Comment by shleeable** [comment]
<img width="271" alt="image" src="https://user-images.githubusercontent.com/17537000/74649466-92fc5a00-51ba-11ea-8eb9-b1c15bbb9367.png">
Yikes

**Comment by true-chaotic** [comment]
https://www.linode.com/community/questions/19082/i-just-created-my-first-linode-and-i-cant-send-emails-why

Here are the instructions

**Comment by shleeable** [comment]
I've lodged a ticket.
