### ISSUE TITLE
Add option to remove uploaded avatar/header image

### ISSUE THREAD

**Issue by ihavesevenlives** [tootsuite/mastodon#1315]
Add an option to remove your uploaded avatar/header image around here or somewhere better:

![removeah](https://cloud.githubusercontent.com/assets/26913497/24834933/93e3be04-1cc0-11e7-92fb-29818614c465.png)

Also, maybe add an administrative option somewhere to remove a user's avatar/header if it's offensive/illegal/instance rule breaking?

**Comment by Gargron** [comment]
Duplicate of #3220

**Comment by MasterGroosha** [comment]
So...is it implemented? #3220 doesn't contain an answer.

**Comment by Cassolotl** [comment]
@MasterGroosha If #3220 doesn't have an answer and it's still open, I think that means it hasn't been implemented yet! But if you click Subscribe on that issue you'll get notified when it *is* implemented.

**Comment by Cassolotl** [comment]
I just checked because I got notified of semente's comment, and on 2.3.3 (the current version) there's no way to remove avatars. I agree that this needs to be reopened.

**Comment by eai04191** [comment]
Any update on this?
I think I need to be able to delete server mascots as well as icons and headers.
