### ISSUE TITLE
Cannot finish setup

### ISSUE THREAD

**Issue by tolui** [tootsuite/mastodon#13158]
I am following this documentation https://docs.joinmastodon.org/admin/install/ for setup new mastodon instance on new Ubuntu 18.0.4 VPS with 2 core cpu’s and 8gb of ram. Unfortunately setup is not completed with following error

### Expected behaviour

Finish interactive setup wizard without any errors

### Actual behaviour

Cannot finis setup on CSS/JS compiling step, it said "yarn: error: no such option: --no-progress That failed! Maybe you need swap space?"

![image](https://user-images.githubusercontent.com/10773668/75363218-c5156680-58f4-11ea-9be7-efcda65e5252.png)

### Steps to reproduce the problem

Follow the documentation step by step

I exactly following this documentation step by step https://docs.joinmastodon.org/admin/install/

**Comment by ThibG** [comment]
Can you print the output of `yarn --version`?

**Comment by tolui** [comment]
@ThibG yarn version is 0.32

**Comment by tolui** [comment]
sorry it was my bad, yarn version is old, closing issue. thanks for hint
