### ISSUE TITLE
database is not properly seeded

### ISSUE THREAD

**Issue by gummipunkt** [tootsuite/mastodon#13154]
### Expected behaviour

When I try to enable a relay, i get a 404 error.

### Actual behaviour

"method=POST path=/admin/relays/1/enable format=html controller=Admin::RelaysController action=enable status=404 duration=38.96 view=1.49 db=3.02"

### Specifications
v.3.1.1

**Comment by ThibG** [comment]
Updated the title to reflect the actual cause.

Currently investigating with the reporter if there's something up with our install script.

**Comment by gummipunkt** [comment]
-- add_foreign_key("web_settings", "users", {:name=>"fk_11910667b2", :on_delete=>:cascade})
   -> 0.0022s
rails aborted!
Redis::CommandError: ERR invalid password
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:126:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:107:in `block in connect'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:306:in `with_reconnect'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:105:in `connect'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:381:in `ensure_connected'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:231:in `block in process'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:319:in `logging'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:230:in `process'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:125:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis.rb:914:in `block in get'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis.rb:913:in `get'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-store-1.5.0/lib/redis/store/interface.rb:5:in `get'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-store-1.5.0/lib/redis/store/serialization.rb:17:in `get'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-store-1.5.0/lib/redis/store/namespace.rb:23:in `block in get'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-store-1.5.0/lib/redis/store/namespace.rb:89:in `namespace'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-store-1.5.0/lib/redis/store/namespace.rb:23:in `get'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-activesupport-5.0.4/lib/active_support/cache/redis_store.rb:260:in `block in read_entry'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-activesupport-5.0.4/lib/active_support/cache/redis_store.rb:242:in `with'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/redis-activesupport-5.0.4/lib/active_support/cache/redis_store.rb:260:in `read_entry'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/cache.rb:313:in `block in fetch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/cache.rb:663:in `block in instrument'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:170:in `instrument'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/cache.rb:663:in `instrument'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/cache.rb:312:in `fetch'
/home/mastodon/live/app/models/setting.rb:26:in `[]'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rails-settings-cached-0.6.6/lib/rails-settings/settings.rb:33:in `rescue in method_missing'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rails-settings-cached-0.6.6/lib/rails-settings/settings.rb:22:in `method_missing'
/home/mastodon/live/app/validators/unreserved_username_validator.rb:20:in `reserved_username?'
/home/mastodon/live/app/validators/unreserved_username_validator.rb:8:in `validate'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `catch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `invoke_before'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:816:in `_run_validate_callbacks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.1/lib/active_model/validations.rb:409:in `run_validations!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.1/lib/active_model/validations/callbacks.rb:118:in `block in run_validations!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.1/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.1/lib/active_model/validations.rb:339:in `valid?'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/validations.rb:67:in `valid?'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/validations.rb:84:in `perform_validations'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/validations.rb:52:in `save!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:315:in `block in save!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:212:in `transaction'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:315:in `save!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/suppressor.rb:48:in `save!'
/home/mastodon/live/db/seeds.rb:5:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `block in load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/engine.rb:556:in `load_seed'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/command.rb:48:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/commands.rb:18:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'

Caused by:
NoMethodError: undefined method `reserved_usernames' for #<Class:0x0000558fdf056cb0>
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:306:in `method_missing'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:131:in `method_missing_with_attr_encrypted'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rails-settings-cached-0.6.6/lib/rails-settings/settings.rb:24:in `method_missing'
/home/mastodon/live/app/validators/unreserved_username_validator.rb:20:in `reserved_username?'
/home/mastodon/live/app/validators/unreserved_username_validator.rb:8:in `validate'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `catch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `invoke_before'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:816:in `_run_validate_callbacks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.1/lib/active_model/validations.rb:409:in `run_validations!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.1/lib/active_model/validations/callbacks.rb:118:in `block in run_validations!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.1/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.1/lib/active_model/validations.rb:339:in `valid?'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/validations.rb:67:in `valid?'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/validations.rb:84:in `perform_validations'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/validations.rb:52:in `save!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:315:in `block in save!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:212:in `transaction'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:315:in `save!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/suppressor.rb:48:in `save!'
/home/mastodon/live/db/seeds.rb:5:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `block in load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/engine.rb:556:in `load_seed'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/command.rb:48:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/commands.rb:18:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)
That failed! Perhaps your configuration is not right

**Comment by ThibG** [comment]
ok, this seems to be a user error, with the user providing a password for Redis, while Redis doesn't accept one
This fails in more surprising ways than it should, though.

The error is triggered not by a direct call to redis from Mastodon's codebase, but from the `rails-settings-cached` gem using Redis as a cache behind the scenes.

We have to check the Redis connection check works correctly, and if so, I'd argue we should abort the whole process instead of moving to database creation, so that the error doesn't end up being surprising.

We should also probably make it explicit that the redis password is that of an already-installed redis server and is likely to be unset.

**Comment by ThibG** [comment]
After investigating with the reporter, we found out this was because their redis password contained a `#`.
There are several bugs preventing this from working correctly, submitting a PR to fix them.
