### ISSUE TITLE
Passwords shouldn't be limited to 72 characters

### ISSUE THREAD

**Issue by yyyyyyyan** [tootsuite/mastodon#13152]
### Expected behaviour

Passwords shouldn't be limited to 72 characters. Yes, bcrypt has this limitation, but any serious platform solves this by using another hash function (usually SHA256) before passing it to bcrypt. [It doesn't make it any less secure](https://security.stackexchange.com/a/6627/225749). 

### Actual behaviour

An error message appears if you try to set a password longer than 72 characters.

### Steps to reproduce the problem

Try to set a password longer than 72 characters.

**Comment by Gargron** [comment]
Seems like a very marginal benefit to suit people who generate really long passwords over fiddling with Devise internals and upgrading millions of records.

**Comment by yyyyyyyan** [comment]
You're wrong and can't seem to understand there's a whole world outside the US (or doesn't even know how bcrypt works).
Bcrypt has a limit of 72 **bytes**. Considering Mastodon encodes passwords using UTF-8 before passing it to bcrypt, and UTF-8 can use up to 4 bytes per character, depending on the characters someone choose for their password, password length limit can go down to 18 characters, which is ridiculous.
What's even more ridiculous is Mastodon doesn't understand the difference between bytes and characters, and will allow anyone to set a password like "**áááááááááááááááááááááááááááááááááááááááááááááááááá**", which has less than 72 characters (50), but more than 72 bytes (100). Of course bcrypt alone doesn't accept this, so the password is actually cut down to 72 bytes, without the user even knowing.
You clearly have a problem that needs to be solved. You can either change the validation to something bizarre that will only allow 18 characters in some cases, or you can do this right and pre-hash the passwords to sha-256 (and letting everyone knows that you actually care a bit about security).

**Comment by danieljakots** [comment]
Please don't be so rude.

**Comment by yyyyyyyan** [comment]
@danieljakots sorry! English is not my first language and sometimes my words come out a bit harsher than it was supposed to be. I don't mean to be rude, sorry about that, I was just trying to be clear on why this issue is indeed important and cannot be ignored

**Comment by acoolstraw** [comment]
I think there should also be an option to change what hash you use, being able to choose between Argon2, Bcrypt, Scrypt or even add your own. Argon2 is pretty good and I'd like to use it instead.

**Comment by Gargron** [comment]
My suggestion is to approach the Devise team about this issue and see what they say.

**Comment by yyyyyyyan** [comment]
Then you should do that, @Gargron, since it affects your users' security.

**Comment by ryliejamesthomas** [comment]
> Then you should do that, @Gargron, since it affects your users' security.

I really don't think that's fair. You're the one who understands the issue, you're in the best position to remake it on their issue tracker.

**Comment by yyyyyyyan** [comment]
@ryliejamesthomas I understand where you're coming from, but I really don't think that's fair **to me**. I work at least 8-10 hours a day, including weekends, I have my own open source projects to maintain, my own blog, my own life. Yes, I'd be glad to send an issue to a tool that's not used in any of the projects I maintain (and for all I know, not even in the projects I regularly contribute to), but I'm currently too busy for that, unfortunately.

So it's a bit strange to me when you say I'm the one being unfair. Unfair to who? I opened this issue in February. @Gargron made a comment in March and just left it there until yesterday. I'm being unfair because I expect the owner of a platform to care about its users' security?

Anyway, this is already taking too much of my time. If I get a free time someday maybe I'll open an issue to the Devise team, who knows. Good luck with Mastodon. I'm too tired for this.

**Comment by rugk** [comment]
Creating this issue is faster than discussing 20 times here now who  sho9uld create one. So I just did it: https://github.com/heartcombo/devise/issues/5307 (I hope I choose the correct project.)
Only thing I encourage you is to follow/add details to that issue.

**Comment by Gargron** [comment]
Thanks @rugk
