### ISSUE TITLE
Scrollbar shows up on the audio player

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#13165]
![grafik](https://user-images.githubusercontent.com/8197071/75492852-e9d31200-59b8-11ea-846a-30bda0ae5091.png)

### Steps to reproduce the problem

When the audio player reaches the end of the file the waveform seems to get too wide and a scroll bar shows up

### Specifications

v3.1.2

confirmed to show up in Firefox on Win10 and macOS

**Comment by ThibG** [comment]
I can reproduce it, I suspect it is a wavesurfer.js bug specific to using the MediaElement backend. Using the WebAudio backend, I do not have this issue. But I think we decided using MediaElement so that the file could be played without having it to load it entirely first.

**Comment by ThibG** [comment]
This may be a Firefox issue, as playing a file directly from it, exhibits similar issues with the duration exceeding the actual file duration. I do not know what that is.

**Comment by MasterGroosha** [comment]
Can reproduce on Firefox 76.0.1 even without manual seeking.
See: https://youtu.be/PYVG-FuwYgQ

**Comment by ThibG** [comment]
Yeah, this still looks like the same issue of Firefox reporting inconsistent playback length, I don't know how we can do better as it seems we can't really get more reliable data from the browser itself :/

The related issues opened at the underlying lib (wavesurfer.js) also haven't been replied to :/

**Comment by noiob** [comment]
the music player this is about was replaced
