### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [tootsuite/mastodon#13163]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/tootsuite/mastodon)](https://www.tickgit.com/browse?repo=github.com/tootsuite/mastodon)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/tootsuite/mastodon)](https://www.tickgit.com/browse?repo=github.com/tootsuite/mastodon)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

(full disclosure, I am the creator/maintainer of `tickgit`)

**Comment by SuperSandro2000** [comment]
Shields.io can do the same thing and all of mastodons badges are already coming from there. For consistency in style and service I would prefer them if this is really something that is needed.

![GitHub issues by-label](https://img.shields.io/github/issues/tootsuite/mastodon/TODO?color=asdasd&label=TODOs)

**Comment by nightpool** [comment]
closing, we don't use TODO comments and frankly they're a bit of a codebase anti-pattern.

**Comment by nightpool** [comment]
@SuperSandro2000 the services do two different things, the original ticket is about counting the number of *comments* in a codebase that contain the string "TODO". The service you linked is counting the number of GitHub issues with the "TODOs" label. the fact that they're the same number is completely a coincidence

**Comment by patrickdevivo** [comment]
Thanks for considering regardless! FWIW, tickgit also supports a shields.io badge like so:

[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/tootsuite/mastodon)](https://www.tickgit.com/browse?repo=github.com/tootsuite/mastodon)

```
[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/tootsuite/mastodon)](https://www.tickgit.com/browse?repo=github.com/tootsuite/mastodon)
```

I switched over to badgen.net as I noticed numerous timeouts/failed requests with shields.io

The badges will also flip green when there are zero TODOs in the codebase. Regardless, I hope the project is interesting nonetheless!
