### ISSUE TITLE
[SUGGESTION] Ability to add local timelines of other instances in the web version of Mastodon. 

### ISSUE THREAD

**Issue by TheFuzzStone** [tootsuite/mastodon#13176]
### Pitch

This post will be a bit big, but I want you to understand my logic, and why I suggest you think about adding a new feature to the Mastodon web version.

My account is on [Fosstodon.org](https://fosstodon.org/), it's a really good instance dedicated to FOSS subject (and not only) with good people and administrators.

The thing is that there are other interesting FOSS communities that I would like to monitor via the Mastodon web version, for example:

* https://mastodon.technology/
* https://linuxrocks.online/
* https://social.privacytools.io/

There are also some other instances that I would like to monitor via the Mastodon **web version**. Why did I highlight exactly the web version of Mastodon? Because this feature (adding local timelines of other instances) is already implemented in [Fedilab](https://fedilab.app/) mobile app (by @stom79).

I don't know about you, but I personally spend a lot more time behind my laptop than behind my smartphone, so, to see the local timelines of other instances that interest me... The only way to do this is through Fedilab mobile app.

---

### Motivation

I think I'm not the only one interested in multiple instances at the same time. 

Someone can tell me that I can keep track of someone else through lists. As a "crutch", it can partially solve this situation, but it's not exactly what I need. For example, I'm interested in some **artist_x** from an instance for designers. I subscribed to this artist and created a list of "**Artists**" in which I put him. But in this way I can only monitor this **artist_x**, but what if another artist (**artist_y**) comes up (at the same instance) that I'm not subscribed to and that I haven't added to the list of "**Artists**"? That's right, I won't see his content, also I can't predict with which hashtags this new artist will post his works, or if he will use hashtags at all. And to find this new **artist_y** in Federated timeliene is not practical at all, and with the growth of Fediverse users it will be even more difficult.

If it was possible to monitor other instances through the web version, then I would just go to the instances that interest me several times a day and look at their local timelines and interact with their content.

I really like Fediverse and I always try to tell people about the benefits of Fediverse whenever possible. And when I first started using Mastodon, I was very surprised to see that I couldn't conveniently add other local timelines from other instances.

---

### How I see it

For example, after the "**Lists**" button, there would be the "**Other instances**" button.

![](https://i.imgur.com/Ndtr1AI.png)

After pressing the button "**Other instances**" the button "**+**" after which the user will be offered to enter/paste the link to an instance interesting to him, and also that at manual input autocomplete should work, for example, the user has entered `linux` in the line "Enter the url of instance" and the list with all instances where there is a word `linux` below appeared to him.

The list of instances can look like this (yes, you see "**Lists**" now):

![](https://i.imgur.com/Ss5Z4I2.png)

And here I propose two options:

1. A user only wants to look at **instance_1** public timeline. It clicks on **instance_1** then instead of a list of instances it sees the local timeline of **instance_1**.

2. A user wants to pin **instance_1** to see it on the home page all the time. How this works now with direct messages or other options: 

![](https://i.imgur.com/qOuD4qb.png)

---

Discussion is welcome.
I will publish a link to this issue in my profile, calling for opinions to be posted here. I want to see how many people need this feature.

**Comment by Cassolotl** [comment]
This is a complex suggestion so I don't know if it's a duplicate but it is definitely related to *[FEATURE] Follow public local timelines from other instances #6942* (almost 2 years old, 62 👍s).

**Comment by trwnh** [comment]
This sounds like a duplicate of #6942, yeah

**Comment by TheFuzzStone** [comment]
Thanks.

Closing. A duplicate of #6942.
