### ISSUE TITLE
Add API endpoint for bookmark management

### ISSUE THREAD

**Issue by joyeusenoelle** [tootsuite/mastodon#13190]
TSIA. I can't find a controller for the new Bookmarks feature in the API; unless I'm misisng it, one should be added to make bookmarks available to third-party apps. (I don't have the Ruby to be sure that I'd be doing it correctly if I did it myself.)

**Comment by trwnh** [comment]
`GET /api/v1/bookmarks` and `POST /api/v1/statuses/:id/{bookmark,unbookmark}` should be all you need, right?

**Comment by joyeusenoelle** [comment]
That looks right. Do those exist and I just can't find them?

**Comment by trwnh** [comment]
Maybe?

- https://github.com/tootsuite/mastodon/blob/master/app/controllers/api/v1/bookmarks_controller.rb
- https://github.com/tootsuite/mastodon/blob/master/app/controllers/api/v1/statuses/bookmarks_controller.rb

**Comment by joyeusenoelle** [comment]
I'm genuinely baffled. I'm 99% sure those files weren't there when I looked at https://github.com/tootsuite/mastodon/tree/master/app/controllers/api/v1 earlier. Thanks for pointing them out.
