### ISSUE TITLE
Mastodon uses four different words for the same thing: toot, status, post, message

### ISSUE THREAD

**Issue by ariasuni** [tootsuite/mastodon#13193]
– The word “toot” is used in most of the interface of Mastodon web
– The word “status” is mostly used for static pages and admin, but sometimes in Mastodon web too
– The word “post” is rarely used, in both admin and in Mastodon web
– The word “message” is even more rarely used, but there’s a few occurrences

### Expected behaviour

Mastodon should always use the same word in the same context, and shouldn’t use more than two different words.

An easy way to harmonize is to always use “toot” in Mastodon web, and “status” in admin or static pages.

### Actual behaviour

Mastodon uses “toot”, “status”, “post” across different contexts and sometimes even on the same column or page (e.g. hotkey column).

### Specifications

Mastodon 3.1.2

**Comment by ThibG** [comment]
I'd say we should use “toot” everywhere except maybe in admin/moderation pages

**Comment by ariasuni** [comment]
By the way, I forgot about “message” that’s used in a few place, a bit like “post”.

I think “status” or “message” makes sense on the `/about/*` pages, so that people not familiar with Mastodon yet can understand what the pages talk about.

**Comment by Gargron** [comment]
I think this is resolved by #16080 and #16089
