### ISSUE TITLE
Consider Keydb replacing redis

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#13204]
### Pitch
as per https://docs.keydb.dev/blog/2019/10/07/blog-post/

### Motivation
this is apparently a dropin replacement that is much faster than stock redis 5.

**Comment by shleeable** [comment]
I'm going to test this because it should be a drop in replacement.

**Comment by SuperSandro2000** [comment]
I don't think that a replacement should be done in 3.X.X as it would break every setup. Making it an optional replacement would be better for now.

**Comment by shleeable** [comment]
Why would you break? just refresh cache with tootlcli

**Comment by Gargron** [comment]
The point of a drop-in replacement is that you can just do it. We don't need to change anything. Just install Keydb instead of redis on your server and that's it.

**Comment by shleeable** [comment]
@Gargron 
1) Would you accept a PR to documentation mentioning this package as an alternative?
2) Would you accept a PR to the docker-compose to migrate to keydb image?
