### ISSUE TITLE
Emoji Selector Filtering

### ISSUE THREAD

**Issue by duckinator** [tootsuite/mastodon#1321]
It'd be neat to have a way to filter the list of emoji, so it's easier to find the one you want, similarly to how Google's Android keyboard and Twitter's emoji selector do.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Angristan** [comment]
By filter you mean search or categories ?

**Comment by wxcafe** [comment]
categories are already there, so I'm assuming search.

**Comment by halkeye** [comment]
I was poking at this too, apparently its already built into the component, just need to update to `<EmojiPicker search={true} />`. I'm going to try and setup a dev env and submit a PR at some point

**Comment by duckinator** [comment]
yeah, I meant search.

**Comment by halkeye** [comment]
![image](https://cloud.githubusercontent.com/assets/110087/24843828/32c81958-1d5b-11e7-8a0b-5b9dc16bf900.png)

Adding `search={true}` adds the search box
