### ISSUE TITLE
Pinning a column makes my browser go back out of Mastodon and fails to pin it

### ISSUE THREAD

**Issue by Phroneris** [tootsuite/mastodon#13216]
### Expected behaviour

- When pressing "Pin" (the rightmost column > "Show settings"), the column is pinned to left
- Mastodon remembers this setting

### Actual behaviour

- When pressing "Pin", the browser brings me back to the previous page... out of Mastodon
- After that, when I go forward to the Mastodon page, the column isn't pinned

### Steps to reproduce the problem

1. Login to Mastodon and enable advanced web interface
1. Show the bookmark bar of your browser and make a bookmark of a pinnable column of Mastodon there
1. Visit YouTube and watch your favorite movie (for example)
1. Go to Mastodon from the bookmark bar on the current browser tab
1. The rightmost column > "Show settings" > "Pin"

### Ways to avoid it (for users)

- If the previous page is also a web UI of Mastodon, it succeeds.
- If the previous page doesn't exist because a pinnable column was opened in a new tab, it succeeds.

### Specifications

- Browser: Google Chrome 64-bit `v80.0.3987.132`
- Server (Instance): mastodon.cloud `v3.1.1`, mastodon.social `v3.1.2`
- Note: Unpinning is OK.

**Comment by ThibG** [comment]
Basically:
1. when pinning a column, Mastodon goes back in the browser history to recall the column that was loaded before that newly-pinned column
2. when deciding whether to go back in the browser history or not, it looks at the length of the browser history, but that isn't a boundary for navigating within the WebUI: that still allows going back to the settings page, for instance
3. pinned columns are part of the settings that are not saved immediately after a change

glitch-soc addresses issues 2 by looking at whether the current location item has a custom state or not, as custom states can only be set through calls of the history API (but `replaceState` can change that too, and iirc there are a few in Mastodon itself)

issue 3. can probably be solved by saving pending settings changes in `onBeforeUpload` if needed

**Comment by Gargron** [comment]
I thought we switched to the getting started column upon pinning, evidently we don't, but that would be a good solution for this problem.
