### ISSUE TITLE
follow request recieved despite account not being locked down

### ISSUE THREAD

**Issue by DressedInBlack** [tootsuite/mastodon#13215]
#Expected behaviour
My account isn't locked down, people should just be able to follow me without me approving them

### Actual behaviour

I recieved a follow request and could approve it

### Steps to reproduce the problem

Make sure locked account is disabled, see if it actually is with another account

### Specifications

 (couldn't find in readme/contributing.md/documentation. how to do that) request was sent 6.3, approved 7.3
Win 10, Firefox

**Comment by Gargron** [comment]
When an account is silenced, it generates follow requests instead of being allowed to follow instantly, for the protection of people being followed.
