### ISSUE TITLE
No oEmbed/Open Graph link previews for Pixiv.net

### ISSUE THREAD

**Issue by Frederick888** [tootsuite/mastodon#13213]
### Expected behaviour
Link cards are generated for https://www.pixiv.net URLs according to oEmbed or Open Graph specifications so that previews can be shown.

### Actual behaviour
No link cards are generated for https://www.pixiv.net URLs.

### Steps to reproduce the problem
For instance, post toot:
> https://www.pixiv.net/artworks/73933387

### Specifications
Pixiv supports both oEmbed and Open Graph at the moment.

Again take the link above as an example (I removed a few irrelevant lines),
```html
<!DOCTYPE html>
<html lang="ja" xmlns:wb="http://open.weibo.com/wb">
<head>
  <meta name="generator" content="HTML Tidy for HTML5 for Linux version 5.7.16">
  <meta name="viewport" content="width=1366">
  <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="https://www.pixiv.net/favicon.ico">
  <title>#原创 rkjk - 科学のイラスト - pixiv</title>
  <link rel="canonical" href="https://www.pixiv.net/artworks/73933387">
  <link rel="alternate" hreflang="ja" href="https://www.pixiv.net/artworks/73933387">
  <link rel="alternate" hreflang="en" href="https://www.pixiv.net/en/artworks/73933387">
  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:site" content="@pixiv">
  <meta property="twitter:url" content="https://www.pixiv.net/artworks/73933387?ref=twitter_photo_card">
  <meta property="twitter:title" content="rkjk">
  <meta property="twitter:description" content="rkjk by 科学">
  <meta property="twitter:image" content="https://embed.pixiv.net/decorate.php?illust_id=73933387">
  <meta property="twitter:app:name:iphone" content="pixiv">
  <meta property="twitter:app:id:iphone" content="337248563">
  <meta property="twitter:app:url:iphone" content="pixiv://illusts/73933387">
  <meta property="twitter:app:name:ipad" content="pixiv">
  <meta property="twitter:app:id:ipad" content="337248563">
  <meta property="twitter:app:url:ipad" content="pixiv://illusts/73933387">
  <meta property="twitter:app:name:googleplay" content="pixiv">
  <meta property="twitter:app:id:googleplay" content="jp.pxv.android">
  <meta property="twitter:app:url:googleplay" content="pixiv://illusts/73933387">
  <meta property="og:site_name" content="pixiv">
  <meta property="fb:app_id" content="140810032656374">
  <meta property="og:title" content="#原创 rkjk - 科学のイラスト - pixiv">
  <meta property="og:type" content="article">
  <meta property="og:image" content="https://embed.pixiv.net/decorate.php?illust_id=73933387">
  <meta property="og:description" content="">
  <meta name="description" content="この作品 「rkjk」 は 「原创」「オリジナル」 のタグがつけられた「科学」さんのイラストです。">
  <link rel="alternate" type="application/json+oembed" href="https://www.pixiv.net/oembed/?url=https%3A%2F%2Fwww.pixiv.net%2Fartworks%2F73933387">
</head>
<body>
  <div id='root'></div>
</body>
</html>
```
For oEmbed, it's got
```html
<link rel="alternate" type="application/json+oembed" href="https://www.pixiv.net/oembed/?url=https%3A%2F%2Fwww.pixiv.net%2Fartworks%2F73933387">
```
...and the JSON returned is
```json
{
    "version": "1.0",
    "type": "photo",
    "title": "rkjk",
    "description": "rkjk by 科学",
    "url": "https://embed.pixiv.net/decorate.php?illust_id=73933387&mode=sns-automator",
    "height": 351,
    "width": 602,
    "author_name": "科学",
    "author_url": "https://www.pixiv.net/users/6054803",
    "provider_name": "pixiv",
    "provider_url": "https://www.pixiv.net/"
}
```
...in which `url` points to a valid image.

For Open Graph, it's got
```html
<meta property="og:image" content="https://embed.pixiv.net/decorate.php?illust_id=73933387">
```
...in which `content` URL works as well.

I don't code in Ruby but after having a glance at https://github.com/tootsuite/mastodon/blob/503eab1c1f101e92f163ed4f8457cac9a6193ffc/app/services/fetch_link_card_service.rb#L39-L168 and https://github.com/tootsuite/mastodon/blob/503eab1c1f101e92f163ed4f8457cac9a6193ffc/app/services/fetch_oembed_service.rb#L8-L78 it seems that there should've been previews generated based on oEmbed for these links.

I tested this on a v3.1.2 instance. Please shed some light on me, thanks!

**Comment by Gargron** [comment]
I wasn't able to reproduce this issue. If I post that link, the toot shows up with a preview. Perhaps the preview didn't appear immediately for you? Sometimes the preview isn't ready by the time the toot goes through the streaming API, but it's there later.

**Comment by shilohrehearsal** [comment]
> I wasn't able to reproduce this issue. If I post that link, the toot shows up with a preview. Perhaps the preview didn't appear immediately for you? Sometimes the preview isn't ready by the time the toot goes through the streaming API, but it's there later.





https://opencodes.space/questions/launch-the-twitter-application-using-html
