### ISSUE TITLE
Mastodon does NOT honor Freedom of Speech.

### ISSUE THREAD

**Issue by RAB-hub** [tootsuite/mastodon#13222]
### Expected behaviour

Should have honored my Freedom of Speech

### Actual behaviour

Did not honor Freedom of Speech, banned account.

### Steps to reproduce the problem

Speak freely, and see how many people try to report you for having opinions.

### Specifications

3.1.2

N/A

**Comment by shleeable** [comment]
@RAB-hub lol.

**Comment by ykzts** [comment]
For individual server questions, please ask each server administrator. This repository is for software issues only.
