### ISSUE TITLE
PostgreSQL will be overloaded if URL is included in the announcement

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#13245]
### Actual behaviour

Creating an announcement that includes a URL causes high load on the PostgreSQL.

PgHero recorded the following slow query:
![2020-03-10 18 31 50](https://user-images.githubusercontent.com/766076/76338435-074e9700-633c-11ea-91a2-e67a63d39450.png)

Probably [this](https://github.com/tootsuite/mastodon/pull/13212/files#diff-0b3dd38d3bd1723e5bf1552ef75a14f6R377) of #13212 is related.

Maybe, creating an index on `url` of the `statuses` table will solve this.
But it will greatly increase the disk usage of the database. I want to avoid if possible.

### Specifications

Mastodon master branch after aa67036b41d37935210c8b5094ac20c153a62011

This occurred when including a generic URL that was not a toot.
I don't try if it will happen even in the case of a toot URL.

**Comment by ThibG** [comment]
#13250 should address this
