### ISSUE TITLE
My own toot containing a word that used to be filtered is still filtered in a hashtag search

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#13248]
### Expected behaviour

When I post something containing a filtered word, I can still see my own post in the home feed. I would expect that to be reflected in public timelines and hashtag searches too.

When I post something containing a filtered word and it is filtered/hidden in a hashtag search, I would expect the toot to become visible in a hashtag search after I delete that filter.

### Actual behaviour

My own posts can be filtered in hashtag searches.

My own posts remain filtered even after I delete the filter.

### Steps to reproduce the problem

1) Make a filter with the term "coronavirus". Check the boxes "Home" and "Public Timelines". Save.
2) Post a post containing the term "coronavirus" and an arbitrary hashtag, let's say #hashtag. Notice that it shows up in your Home feed even though it contains the filtered term, as intended, because we need to be able to see our own posts.
3) Search for #hashtag. Notice that the post is filtered out of the #hashtag search column.
4) Go into your filter settings and delete the "coronavirus" filter. Save. Go back to the main UI.
5) Search for #hashtag. Post is still filtered.

### Specifications

Mastodon v3.1.2

Mac OS 10.15.3, Chrome Version 80.0.3987.132 (Official Build) (64-bit) (up to date)

**Comment by ThibG** [comment]
I can't reproduce this… I don't think own toots should ever be filtered from word filters…

**Comment by Cassolotl** [comment]
I'll just try again with a test. 🤔 

...

Okay, I can't reproduce this on mastodon.social or queer.party! Never mind, then. Sorry about that! :D
