### ISSUE TITLE
Allow access to Redis via Unix Socket

### ISSUE THREAD

**Issue by yeah** [tootsuite/mastodon#1325]
On some shared hosting platforms (e.g. [Uberspace](https://uberspace.de)), Redis is only available via a Unix socket, not a TCP port.

It would be awesome if the Mastodon config in `.env.production` supported specifying a Unix socket for Redis as an alternative to the current TCP access via host/port.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
I believe this should be possible with REDIS_URL now.

**Comment by gabrielelucci** [comment]
Is it actually possible? I can't seem to connect mastodon to redis with socket. 
The configuraion is set to `REDIS_URL=redis:///var/run/redis/redis.sock` but it just doesnt work.
