### ISSUE TITLE
WebUI crashes with “document.scrollingElement is undefined”

### ISSUE THREAD

**Issue by githubgnulinux** [tootsuite/mastodon#13266]
Programmers,

Please consider accessibility guidelines. Mastodon incompatible with webkit browsers and mobile browsers such as lightning

Error report using firefox:

TypeError: document.scrollingElement is undefined

t/<@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:583359
t/<@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:581740
y@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:158098
k/<@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:158466
k@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:158423
N</n.componentDidMount@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:584676
Du@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:1057479
t.unstable_runWithPriority@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:1077060
Xa@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:1001987
Fu@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:1053829
wu@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:1044148
Ja/<@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:1002278
t.unstable_runWithPriority@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:1077060
Xa@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:1001987
Ja@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:1002223
$a@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:1002158
gu@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:1040714
Co.enqueueSetState@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:1006939
_.prototype.setState@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:951563
t/</<@https://scholar.social/packs/js/common-ee9226a17a0221aba66c.js:2:274838

getScrollTop (webpack:///app/javascript/mastodon/components/scrollable_list.js:154:4)
throttle( (webpack:///app/javascript/mastodon/components/scrollable_list.js:54:24)
invokeFunc (webpack:///node_modules/lodash/debounce.js:97:13)
leadingEdge (webpack:///node_modules/lodash/debounce.js:107:21)
leadingEdge (webpack:///node_modules/lodash/debounce.js:101:2)
componentDidMount (webpack:///app/javascript/mastodon/components/scrollable_list.js:142:4)
fd (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6324:54)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:270:11)
fg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2794:9)
Yj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6105:2)
Zj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5408:6)
fg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2829:16)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:270:11)
fg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2794:9)
fg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2824:6)
jg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2814:2)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5191:91)
enqueueSetState (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:3091:4)
setState (webpack:///node_modules/react/cjs/react.production.min.js:60:2)
this.setState (webpack:///app/javascript/mastodon/features/ui/components/bundle.js:79:8)

https://validator.w3.org/nu/?doc=https%3A%2F%2Fscholar.social%2Fabout

https://jigsaw.w3.org/css-validator/validator?uri=scholar.social&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly.

Try refreshing the page. If that does not help, you may still be able to use Mastodon through a different browser or native app.

Mastodon v3.1.2 · Report issue ·

**Comment by ThibG** [comment]
Which version of Firefox did you get this report with? It should be supported since Firefox 48…
