### ISSUE TITLE
rare bug on toot reply.

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#13278]
If somebody post, you type a reply, they delete the toot and you try to Toot! the reply.. the UX will just sit there like a dork while 404s start to pool in the inspector instead of some kind of modal

so I slam the Toot! button with imputent white male rage.

I'm unable to replicate this.

**Comment by ThibG** [comment]
This may happen if the status is deleted and the web UI doesn't know it (e.g., it's a status that wouldn't appear in your TL or notifications). The lack of error message is because errors on 404 and 410 are filtered out globally. This may not be needed and I'll investigate it.

**Comment by shleeable** [comment]
Thanks.

that makes sense because I'm testing Flodgatt...
