### ISSUE TITLE
Per-user "Disable Reposts" option

### ISSUE THREAD

**Issue by markdhughes** [tootsuite/mastodon#133]
Current:
1. Follow a high-volume RTer, like Gargron.
2. Timeline fills with RTs, unable to see people I follow.

Expected:
3. Hit Gargron's profile, pick "Disable Reposts".
4. Timeline now only shows Gargron's actual posts.

**Comment by hoodiek** [comment]
this is definitely necessary

**Comment by fsnk** [comment]
Need dis.

Need dis so bad.

**Comment by naught101** [comment]
+1. It would be great if this could optionally be the default for new follows, too. I'm finding I have to unfollow people just to see a few toots I'm interested in.

**Comment by naught101** [comment]
Also, for search: boosts  retoots retweets

**Comment by fsnk** [comment]
RE: @naught101 's default setting suggestion

It would be great if that was possible (maybe as a checkbox in user preferences?)

**Comment by Gargron** [comment]
Implemented in #5762

**Comment by naught101** [comment]
Whoop! Just realised this was in. Excellent! Thank you!
