### ISSUE TITLE
An anonymous dislike button

### ISSUE THREAD

**Issue by glensimister** [tootsuite/mastodon#13314]
I have been developing a browser extension which lets people like and dislike URLs (among other things). The prototype uses gunDB, however, I recently stumbled across Mastodon, and it seems like this platform better suits my needs. After a brief scan through the API reference, I noticed that there isn't an option to dislike something (unless I've missed it). 

I would have thought that a dislike button is essential in order for a platform like this to be able to self-regulate. I regularly see content on Facebook that I dislike. What are my options? Get into a argument with a friend? I don't want to do that. I just want to dislike it. Also, I think it would be better if it was anonymous, as to not offend the poster. 

I don't know much about about ActivityPub but I see that there is a dislike ActivityStream:
https://www.w3.org/TR/activitystreams-vocabulary/#dfn-dislike

Having a like button, which pushes good content up, and a dislike button, which pushes bad content down,  would incentivize good behavior, and would improve the overall quality of the content on the platform. You could then uses the data to calculate a score, and display it in the form of stars. I would even delete content which has a score below X, as opposed to relying solely on moderators to remove inappropriate or illicit content. 

Please include an anonymous dislike command in the API! ;)

**Comment by Cassolotl** [comment]
Ugh, the upvote/downvote system and algorithms on Reddit make it such an unpleasant place to be, I am *not* into this idea!

**Comment by glensimister** [comment]
The irony

**Comment by mstdn** [comment]
I'd rather not.. Let's not make this a game of numbers please.

**Comment by shleeable** [comment]
Two points
1) There is a PR for Pleroma-style emoji reactions #13275 - so you could give a dislike or a clown emoji

2) the idea of keeping them anonymous.. Similar to the comment above. a reddit style upvote/downvote would be kind of interesting -- but I doubt the devs would want to see that feature

**Comment by experiment9123** [comment]
> Ugh, the upvote/downvote system and algorithms on Reddit make it such an unpleasant place to be, I am _not_ into this idea!

being able to vote lets you register an opinion without having to clog up the system with many similar trivial replies - and actually read the existing ones.

Surely in an open environemnt specific servers can decide to ignore or hide this information - having algorithmic recommendation could be an opt-in

I think it makes the data more valuable - and I think there should be both like and dislike, the dislike can be hidden or anonymised

**Comment by RichardBJ** [comment]
Anyone on here will be well aware of the effectiveness of up/downvotes on the likes of StackOverFlow.  Obviously you only show the sum/net, not the individual ups and down.

To prevent user humiliation (my jokes get -10 votes) you could simply just show zero or positives.  Displaying zero for a -10 and +10 for a plus 10.  
There is, as pointed out above, some irony in people happily using downvotes do indicate that downvotes is an unhelpful device.
So WHY up and downvotes:
Well for fear of re-inventing the wheel, the up/down votes in terms of opinions tend to favour the consensus views rather than the extremes.  Extremism is something I would have thought, by definition, the majority would oppose?

**Comment by maltfield** [comment]
See also https://github.com/mastodon/mastodon/issues/8072

**Comment by shodanx2** [comment]
Obviously, anonymous voting should be a thing. And the system should be smart enough to take it with a grain of salt.

And by the system, I mean this decision should be entirely up to client's content discovery algorithm and full under the informed control of the end user. (and that algorithm should be able to tell, in most instances, organic from synthetic voting. Content discovery algorithm are "needle in haystack" finders, and having more voting eyes on the problem will lead to more of the relevant content being found, it also created more dynamic range in the signal-to-noise ratio that a small voting pool of registered users only voting system brings.)

The way I see it, not having those is simply depriving us of the opinions of the lurking majority, which represent 10x more users than the actively posting users. 

By not having a voting system for them, we are just losing 10x of the crowd source content sorting and discovery power of the whole platform
