### ISSUE TITLE
Emails not working with heroku/MailGun

### ISSUE THREAD

**Issue by callumjames90** [tootsuite/mastodon#1331]
I've got my own instance set up with Heroku and have managed to get Mailgun to verify my domain, but I am unable to understand how to get the email side working correctly to setup accounts on my instance. Mailgun keeps telling me to send myself an email but looking at the documentation it shows me code in Ruby, C# etc for SMTP setup.

Am I doing something wrong? I really can't figure out how to get email settings working correctly. Sorry for the feel vague question, I am not so great with web dev.

Thanks.

**Comment by mjankowski** [comment]
You should make sure that the various `SMTP_*` config variables are set on your heroku instance. The `production.rb` from within Mastodon [uses these](https://github.com/tootsuite/mastodon/blob/master/config/environments/production.rb#L97-L101) to figure out how to send outgoing mail.

You can find these values in the mailgun dashboard, and it's pretty straightforward to map them over. Note that after you validate a domain in mailgun the values change (this is not obvious from their docs)! - so look out for that if you set them pre-validation.

**Comment by ashfurrow** [comment]
I had issues too. I had to use port 25 and the default postmaster credentials didn't work (I created new ones). Let me know if I can help.

**Comment by callumjames90** [comment]
I've decided to start over on a separate domain I own, and I've done what you have suggested and put in 25 as the port as well as creating new credentials via Mailgun. I think I missed this last time when I set up Mastodon via Heroku, what do I need to enter for the SMTP_DOMAIN and SMTP_FROM_ADDRESS config variables? I'm assuming for the From Address I need to create something in Mailgun such as contact@mydomain.com from where emails are sent, but can't figure this one out. I'm not so good at this thing...

Thanks.

**Comment by ashfurrow** [comment]
Yes, I used `admin@MY_MASTODON_DOMAIN` for the from address, and set up a catch-all route in Mailgun to forward any emails to `MY_MASTODON_DOMAIN` to my personal email address. I'm not sure what the `SMTP_DOMAIN` variable is, w here are you seeing that?

**Comment by callumjames90** [comment]
![image](https://cloud.githubusercontent.com/assets/3424869/24839668/dcd50ad2-1d56-11e7-8f9e-aa57f2b6d542.png)
Second from bottom on the Mastodon to Heroku setup page, I'm assuming leaving it blank will be fine as it says it will default to the instance domain.

**Comment by mjankowski** [comment]
I believe that the `SMTP_DOMAIN` value in your heroku config should be whatever domain you have mailgun set up to use.

**Comment by callumjames90** [comment]
Ah yes, that does seem right.

I think I've got it sorted now. I can setup new accounts on this domain and it will send a verification email to whatever email I have signed up with, which is what I was aiming for. Only a few other hiccups to look over but for now this side of the problem is working as I was hoping.

Thanks again.

**Comment by mjankowski** [comment]
Glad it's working -- if there's anything which could have been clearer in the docs, can you submit an update for that? Otherwise, close this issue?

**Comment by ineffyble** [comment]
Just made a pull request to fix a bug that I discovered - the SMTP domain should in theory be set from the SMTP_DOMAIN environment variable, and fallback to the LOCAL_DOMAIN variable otherwise.

The problem was, the fallback wasn't working, it was referencing an internal variable that wasn't yet set. So the line about 'default to instance domain if blank' was incorrect.

**Comment by ashfurrow** [comment]
@ineffyble Now that https://github.com/tootsuite/mastodon/pull/1745 has been merged, should we close this issue?

**Comment by JCBoptimumweb** [comment]
Hi All,

I had some major pains with this. A few tips

 to get the details required for below in command line 'heroku config'

in your config/environments/production.rb

`config.action_mailer.default_url_options = { :host => 'yourappname.herokuapp.com' }
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.perform_deliveries = true

  ActionMailer::Base.smtp_settings = {
      :port           => '587',
      :address        => 'smtp.mailgun.org',
      :user_name      => 'MAILGUN_SMTP_LOGIN:',
      :password       => '1MAILGUN_SMTP_password:',
      :domain         => 'yourappname.heroku.com',
      :authentication => :plain,
  }
  ActionMailer::Base.delivery_method = :smtp`

You will also need to verify your mailgun account via sms.

then you will also need to have your own domain set up in heroku.

Also this is a really great time to learn your heroku log which can be generated in command line via heroku _. your log will tell you exactly whats going on

Hope that helps.

**Comment by ashfurrow** [comment]
Thanks for following up @JCBoptimumweb – this issue's been inactive for a few weeks so I'm going to close. Please let us know if there's anything else we can follow-up on. Thanks again @callumjames90 for opening the issue.
