### ISSUE TITLE
Option to Auto-Delete Toots

### ISSUE THREAD

**Issue by kevquirk** [tootsuite/mastodon#13328]
Quite simple really. Many people on Mastodon are privacy advocates. It would be great to have an option within user preferences where they could choose to auto-delete toots older than a set time.

Default would be to keep all toots, but if enabled, the user could set the number of days/weeks/months etc that toots older than should be deleted.

From an admin perspective it could also save server resources?

**Comment by trwnh** [comment]
Duplicate of #1295
