### ISSUE TITLE
BUG | No Rate Limiting on email verification. | MAIL SPAMMING

### ISSUE THREAD

**Issue by herculeszxc** [tootsuite/mastodon#13330]
BUG | No Rate Limiting on email verification. | MAIL SPAMMING. 
Using burpsuite. 
See attached photo. 
![2](https://user-images.githubusercontent.com/62851950/77857614-1afd6700-7231-11ea-9e2f-b05b61155c98.PNG)
![Capture1](https://user-images.githubusercontent.com/62851950/77857615-1cc72a80-7231-11ea-87cd-fda254813dbf.PNG)
![Capture2](https://user-images.githubusercontent.com/62851950/77857618-20f34800-7231-11ea-8f71-9e3aee960e0b.PNG)

**Comment by Gargron** [comment]
More information: This endpoint only results in an e-mail being sent if the user exists and if the user's e-mail isn't confirmed. So the impact is limited to new accounts only. But it's still problematic, obviously.

**Comment by herculeszxc** [comment]
Yah but still issue :) If you are using limited email services this kind of attack can result you in financial lose and can slowdown your services and also the storage in your sent mails. 
Best Regards, Thankyou

**Comment by herculeszxc** [comment]
Yah but still issue :) If you are using limited email services this kind of
attack can result you in financial lose and can slowdown your services and
also the storage in your sent mails.
Best Regards, Thankyou

>

**Comment by herculeszxc** [comment]
may i know if you have bug bounty program ?
