### ISSUE TITLE
Trends don't update

### ISSUE THREAD

**Issue by angristan** [tootsuite/mastodon#13349]
As discussed [here](https://mstdn.io/@angristan/103897142957273631) trends don't refresh anymore, at least for me and a few other instances.

@Gargron said:

> So sometimes the recurring jobs in Sidekiq stop executing even though the dashboard claims they're still being run regularly. I don't know the reason but clearing out unique jobs locks has helped in the past...

> I think it could possibly be related to this issue: https://github.com/mhenrixon/sidekiq-unique-jobs/issues/418

> You can run TrendingTags.update! from rails console to make the real ones show up while the automation is stuck

I'm opening this issue to keep track of this problem and so that other admins can be aware of it.

A workaround for now is the command suggested by @Gargron above into a cron:

```
@hourly cd /home/mastodon/live && echo 'TrendingTags.update!' | RAILS_ENV=production /home/mastodon/.rbenv/shims/bundle exec rails console > /tmp/mastodon_refresh_trends.log 2>&1
```

Note: I'm not sure if this works for now haha, will report back.

**Comment by mstdn** [comment]
Manual comment in rails console does fix it indeed. Let me know if this cron also works for you :-)

**Comment by angristan** [comment]
The cron seems to work so far!

**Comment by angristan** [comment]
I still have to run `TrendingTags.update!` after v3.1.3

**Comment by Gargron** [comment]
You now have access to the locks from the sidekiq web interface. Go there and delete all locks and it should start working. I think the section at the top is called unique digests or something like that.

**Comment by angristan** [comment]
OK, I will try this 👍

**Comment by angristan** [comment]
It's all good now! Thanks @Gargron

**Comment by angristan** [comment]
FYI, I still have to delete unique digests all the time for trends to refresh, so I resorted to adding the crontab back
