### ISSUE TITLE
Are rate limits global or per app?

### ISSUE THREAD

**Issue by allo-** [tootsuite/mastodon#13359]
I cannot really see in the documentation if rate limits are global or per registered app, but when one app exceeded the rate limit (for status deletion) not even the web interface itself is able to delete any further status for the next 30 minutes.

It seems counter intuitive, that a background app and the web interface interfere with each other, but it seems that they count towards the same rate limit. Is this true, or am I doing something wrong?

**Comment by Gargron** [comment]
The limits are per-user (I think that's what you mean by global).

**Comment by Gargron** [comment]
https://docs.joinmastodon.org/api/rate-limits/

**Comment by allo-** [comment]
Thank you for the answer.

I think the linked page could be improved, as it does not make clear the distinction between rate limits like other services use them.

1. Per-IP
2. Per-App (App token only)
3. Per-App-and-User (With user token)
4. Per-User (same bucket for all authorized apps)

I think Twitter does not have (4) and Mastodon then does not have (2) and (3), when I understand you correctly.

That Mastodon uses (4) instead of (3) is not that clear when being used to other rate limit systems.
