### ISSUE TITLE
Disable Glossary ‘file’ on Crowdin

### ISSUE THREAD

**Issue by Sasha-Sorokin** [tootsuite/mastodon#13357]
### Pitch

Crowdin has a glossary feature which is very useful for translators to have, it allows to define ‘terms’ for the words or phrases with correct translation to seek consistency across the translations. It also has a feature to enable Glossary ‘file’, which is pseudo-file, containing all the terms across all the languages.

### Motivation

The ‘pseudo-file’ could have been useful on start to discuss and come up with strict set of initial terms translations. Unfortunately, it's not working for Mastodon and probably would not. As it adds terms from all the languages, it's already huge, it has no descriptions, nor contexts. It's also misleading: users might thing it's somehow important to translate and vote on, when in reality it has absolutely **nothing** to do with exported translation files.

I propose disabling this file and rely only on the terms functionality built-in in Crowdin's UI: it's much more easier, provides context and does not expose local language terms to other languages.

<p align=center>
<img src="https://user-images.githubusercontent.com/10401817/78024307-552a4e00-7382-11ea-9692-3d966cd05e4c.png" alt="Example screenshot of term ‘status’ in Russian">
</p>

### Related Issues 

- #12388 — “Glossary on CrowdIn is ambiguous”

**Comment by Gargron** [comment]
Fair point, done.

**Comment by Sasha-Sorokin** [comment]
Phew, that was quick and easy!

**Comment by KNTRO** [comment]
Hi there,

I still don't understand why you people continue to talking about Crowdin's related stuff here at GitHub. 🤔 Crowdin has its own _Discussions_ section, yo. You people take decisions on Crowdin's things and we —translators at Crowdin—  don't have a clue about what's going on. 🙄

Kinda weird…? 🤨

**Comment by Brawaru** [comment]
Hey! I think it's somewhat reasonable to report specific issues regarding the Crowdin project *setup* and *integration* here (as well as localisation as a feature of Mastodon), so they can be triaged and get needed attention.

Crowdin discussions are focused on the discussing the work done in the project itself: it's not an issue tracker per se, just like [Discussions](https://github.com/tootsuite/mastodon/discussions) tab here on GitHub, so it's not monitored as strictly. 

So no, I don't think it's really *that* weird, although I see where you going about translators not being aware of the changes.

**Comment by Brawaru** [comment]
@Gargron can you please look up into it again? The ‘glossary’ pseudo-file is back...
