### ISSUE TITLE
Support JRuby

### ISSUE THREAD

**Issue by fap-** [tootsuite/mastodon#1337]
I would like to see the possibility to run mastodon on JRuby.
I'm not sure if this would help performance but I think it's worth a try.

JRuby doesn't support gems with C extensions.
To provide JRuby support we have to define alternatives to all incompatible gems.

**Comment by fap-** [comment]
Linking issues to track progress of postgresql jdbc support for ActiveRecord 5:
https://github.com/jruby/activerecord-jdbc-adapter/issues/734
https://github.com/jruby/activerecord-jdbc-adapter/issues/708

**Comment by gouessej** [comment]
It would help a lot to reduce the attack surface on the servers already using Java. I have nothing against Ruby in particular but I won't install PHP, Python, Java and Ruby on my low power server.

@fap-  Have you ever tried to deploy Mastodon in Wildfly, TomEE or Jetty?

**Comment by fap-** [comment]
@gouessej Can you explain how this might help?
We are lacking a JRuby+AR5 compatible database adapter for postgres.

And then we would have to find a way to replace the other C extension dependent dependencies:
https://twitter.com/codinghorror/status/852313187017936896
https://twitter.com/codinghorror/status/852300775954853889

**Comment by gouessej** [comment]
I use Jetty on my own server (Olimex Lime2), it doesn't have a lot of RAM, it can't run numerous application / web servers at the same time, running Mastodon with JRuby would allow to bundle it as a WAR and deploy it as a web application with my other ones with a single JVM for Jetty itself which would have a lower memory footprint than running Jetty on one side and running something using Ruby natively on the other side.

Moreover, each "technology" might have its own flaws. If I install PHP + Python + Java + Ruby, I will be exposed to all their flaws. As far as I know, Mastodon requires Node.JS and Ruby. I expect the combination of JRuby + Java from having less flaws than Java and Ruby but maybe I'm completely wrong.

**Comment by Gargron** [comment]
It sounds like JRuby is still incompatible with Rails 5, and JRuby integration in general seems to be a PITA. I don't think we should have an open issue for it.
