### ISSUE TITLE
Sidekiq: Mastodon::UnexpectedResponseError: https://pawoo.net/inbox returned code 401

### ISSUE THREAD

**Issue by HolgerHuo** [tootsuite/mastodon#13372]
I got errors in sidekiq after deleting some of my users like this
>Mastodon::UnexpectedResponseError: https://pawoo.net/inbox returned code 401

I don't know if pawoo.net has blocked me or some problems in my server, but the problem *consists* after running tootctl purge domains pawoo.net. What is worse is that my SMTP seems down. I can't receive any notification emails like resetting passwords and there are even no error records in sidekiq.

**Comment by shleeable** [comment]
Are you using linode? You need to request for them to open SMTP ports.

**Comment by HolgerHuo** [comment]
> Are you using linode? You need to request for them to open SMTP ports.

Not actually. The smtp used to be good. And I think the trouble is probably at `Mastodon::UnexpectedResponseError: https://pawoo.net/inbox returned code 401`. I don't know how to fix this and what led this.
Anyway thanks a lot～

**Comment by HolgerHuo** [comment]
Not actually. I'm using an external SMTP server and it used to be good. I think that only happened after this error `Mastodon::UnexpectedResponseError: https://pawoo.net/inbox returned code 401`. I have purged pawoo.net domain and clear database record, also killed the retries. But right after I deleted another user, The error consisted.

**Comment by HolgerHuo** [comment]
Solved after one retry, seems there was a latency after domain removal. Thanks a lot! @shleeable 

Anyway, still wondering what happened exactly? Was I blocked by pawoo.net or was their server's mastodon version out-of-date?
