### ISSUE TITLE
remove-orphans ignores PAPERCLIP_ROOT_PATH

### ISSUE THREAD

**Issue by IzaliaMae** [tootsuite/mastodon#13371]
### Expected behaviour

`tootctl media remove-orphans` should remove orphaned media

### Actual behaviour

A 'No such file or directory' error is returned since it tries to search public/system instead of the directory set by PAPERCLIP_ROOT_PATH

**Comment by IzaliaMae** [comment]
It's checking for RAILS_ROOT_PATH instead of PAPERCLIP_ROOT_PATH. Is it supposed to be like that?

**Comment by Gargron** [comment]
Oh, that would be it.
