### ISSUE TITLE
Update failed by v3.0.1 to v3.1.0

### ISSUE THREAD

**Issue by tailot** [tootsuite/mastodon#13380]
### Expected behaviour

Upgrade successfully.

### Actual behaviour

The system cannot be updated with message:
"Bundler::GemNotFound: Could not find rake-10.3.2 in any of the sources"

### Steps to reproduce the problem

git checkout v3.1.0
bundle install

(I am following the release notes.)

### Specifications

Mastodon version v3.1.0

OS: Ubuntu 18.04

**Comment by ThibG** [comment]
I cannot reproduce this. However, 3.1.0 will fail to install because of `httplog` 1.4.1 missing, and 3.1.1 and 3.1.2 because of `sidekiq-unique-jobs-6.0.18` missing.
Hopefully we will soon have a new release fixing that dependency issue.

**Comment by ThibG** [comment]
v3.1.3 has been released, you should be able to upgrade straight to it (but please have a look at upgrade notes for intermediate versions as well), so I'm closing

**Comment by tailot** [comment]
@ThibG Thanks!!! Works well!
