### ISSUE TITLE
After upgrading to 3.1.3, much more enqueued workers.

### ISSUE THREAD

**Issue by HolgerHuo** [tootsuite/mastodon#13404]
My instance used to have a load average under 0.3 0.3 0.3 and there's hardly any CPU usage by Ruby and Bundle when nobody accessed to my site.

However, there are now many enqueued jobs in sidekiq and the CPU load is high. Is that normal after upgrading?
<img width="1194" alt="Screen Shot 2020-04-06 at 8 11 35 AM" src="https://user-images.githubusercontent.com/50446405/78513550-1ad80b00-77df-11ea-961b-48345535633c.png">
<img width="1186" alt="Screen Shot 2020-04-06 at 8 11 53 AM" src="https://user-images.githubusercontent.com/50446405/78513553-1d3a6500-77df-11ea-88ed-1fbc4b519881.png">
<img width="1202" alt="Screen Shot 2020-04-06 at 8 12 05 AM" src="https://user-images.githubusercontent.com/50446405/78513554-1dd2fb80-77df-11ea-9448-893dd7fd8b6f.png">
<img width="568" alt="Screen Shot 2020-04-06 at 8 12 32 AM" src="https://user-images.githubusercontent.com/50446405/78513556-1f042880-77df-11ea-9016-e309b55f9690.png">

**Comment by Gargron** [comment]
The upgrade cannot could have had any effect on this, it must be a coincidence. All of the displayed job types have existed in Mastodon for a very long time and the upgrade itself does not enqueue anything, only user or inter-server activity can do that.

**Comment by HolgerHuo** [comment]
I see that. But it did happen right after the upgrade and we seem unable to toot anymore, the enqueued tasks are increasing dramatically. Does it have anything to do with #13372 ?

**Comment by HolgerHuo** [comment]
#4248 I think it's quite similar to this problem but I didn't get what you mean by systemd service

**Comment by HolgerHuo** [comment]
Hi, it turned out that I was using an outdated Redis server and the problem has been solved. Thanks a lot.

**Comment by jplock** [comment]
I'm seeing this too after upgrading to 3.1.3.  Is there a specific version of Redis that is required now?  I am running 3.0.6.

**Comment by HolgerHuo** [comment]
It requires Redis 4.0.0 at least now. Just use ` yum update redis` or any other commands according to your distribution and restart mastodon-sidekiq, everything would work as usual~

**Comment by draft13** [comment]
I also had the same experience. I am running Ubuntu 16.04 and had to remove the packaged version 3.something and had to download and compile Redis 4 from source. Once that was done the queue started fresh and began to work.

**Comment by saper** [comment]
> It requires Redis 4.0.0 at least now.

If this is the case indeed, it should be a big warning in the release notes. Was that intended?

**Comment by Gargron** [comment]
I've added a warning to the release notes just now. Sorry I haven't done so earlier -- the sidekiq update went completely out of my head. If anyone has a snippet on how to update Redis on Ubuntu 16.04, I'll include that as well, as it happens, I don't actually know where you could get it from except compiling from source (which is more complicated). At the very least, official docs have been recommending Ubuntu 18.04 for a good while so hopefully a lot of people aren't affected.

**Comment by draft13** [comment]
I followed this write up: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-redis-on-ubuntu-16-04

I can vouch that the compile portion works well, I have yet to setup the systemd service. I will do that in a bit (currently it is running from the command line in a tmux session). I also tell you that doing a `do-release-upgrade` also doesn't fix the problem, as it introduced a slew of other errors. 

I ended up reverting to a snapshot I created prior to running the release upgrade, and roll with updating my own redis for a while.

**Comment by Gargron** [comment]
Yeah, upgrading 16.04 to 18.04 is a mess. Although 16.04 is nearing EOL, so don't know if I can actually recommend sticking to it longer...

**Comment by drsebro** [comment]
If anyone has a snippet on how to update Redis on Ubuntu 16.04, I'll include that as well, as it happens, I don't actually know where you could get it from except compiling from source (which is more complicated). At the very least, official docs have been recommending Ubuntu 18.04 for a good while so hopefully a lot of people aren't affected.

this could help: 

add-apt-repository ppa:chris-lea/redis-server
apt update && apt upgrade 

the reason why I have to use ubuntu 16.04 is my vserver provider, I have a chip one :)

**Comment by HolgerHuo** [comment]
Thanks a lot for all your help!
