### ISSUE TITLE
Documentation Request: Apache reverse proxy

### ISSUE THREAD

**Issue by kurobeats** [tootsuite/mastodon#1342]
I understand nginx is great but would be interested to see documentation on how to deploy mastodon with an Apache reverse proxy front end

**Comment by Komic** [comment]
Already opened a pull request [here](https://github.com/tootsuite/mastodon/pull/1018/files).

**Comment by Gargron** [comment]
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Alternatives.md#apache
