### ISSUE TITLE
[security] minimist is outdated, but dependabot cannot create the auto PR.

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#13423]
I think the minimist config is a bit funky.

<img width="757" alt="image" src="https://user-images.githubusercontent.com/17537000/78551974-37089600-7839-11ea-86d2-9ab1dbf81e6d.png">

**Comment by Sasha-Sorokin** [comment]
There's much work to do to update all the dependencies, I believe. If this one is due to eslint, then it shouldn't be as worrying — because it solely checks user's code, not any unknown input.

**Comment by Gargron** [comment]
Yeah this one doesn't affect our security at all.

**Comment by shleeable** [comment]
> There's much work to do to update all the dependencies, I believe. If this one is due to eslint, then it shouldn't be as worrying — because it solely checks user's code, not any unknown input.

I've been working on the dependencies stuff..
