### ISSUE TITLE
Timeline overlaps media detail view when using the NoScript Firefox extension

### ISSUE THREAD

**Issue by Ingo-FP-Angel** [tootsuite/mastodon#13444]
I click on an image in a toot to open a large view of it.

### Expected behaviour

The image is opened in front of the page ("lightbox" or "modal")

### Actual behaviour

The image is opened but the timeline column obscures it.

![Z-Index-Problem](https://user-images.githubusercontent.com/35199584/78981780-f0f55000-7b20-11ea-822f-35c6c1490765.png)

### Steps to reproduce the problem

Clicking on any image in a toot

### Specifications

Happens in tootsuite 3.1.3 (but not in 3.1.2)

Browser: Firefox 68.6.1 ESR
OS: Opensuse Leap 15.1 (Linux)

**Comment by ThibG** [comment]
I'm unable to reproduce this (but haven't tested Firefox 68 yet, only Firefox 72), and I really can't see what could have changed this between 3.1.2 and 3.1.3 :/

Do you by any chance use any browser extension or user style that may interfere with Mastodon?

**Comment by Ingo-FP-Angel** [comment]
The only add-ons in the browser are HTTPS Everywhere, NoScript and uBlock Origin.

I tried some more things. In Firefox 75 it does not happen.

And in 68.6.1 ESR it seems there seems to be a condition on when it happens.
I had closed the browser and started it again and the problem seemed gone. I scrolled back to the toot from above screenshot and the problem was back. It was also present in a toot which was on top of some hashtag search.
Then, after closing and re-opening the browser a second time and directly searching for the same hashtag did *not* show the problem. It still did for the old toot from the screenshot and *then* the problem also appeared for the other toot.

So my best guess at the moment how to reproduce the issue is: scroll down the timeline so that it has to fetch new entries *twice* or maybe *three times*. But only in Firefox ESR, not the latest one.

**Comment by ThibG** [comment]
I have tried with Firefox 68.7.0 but haven't been able to reproduce the issue. When that happens, could you, using the inspecter, check that:
- the path to the `img` tag is `html > body.app-body.theme-default.layout-multiple-columns.with-modals--active > div#mastodon.app-holder > div > div.ui.is-composing > div.modal-root > div > div.modal-root__container > div.modal-root__modal.media-modal > div.media-modal__closer > div > div.react-swipeable-view-container > div > div.image-loader > div.zoomable-image > img`
- `.modal-root` has a rule `z-index: 9999`
- also maybe send a screenshot of what the DOM looks with things folded like in the following screenshot
![image](https://user-images.githubusercontent.com/384364/79007576-ba88f680-7b5b-11ea-9ede-c3a3faf83b84.png)

**Comment by Ingo-FP-Angel** [comment]
* path to img tag: `html.__ns__pop2top body.app-body.theme-default.no-reduce-motion.layout-multiple-columns.__ns__pop2top.with-modals--active div#mastodon.app-holder.__ns__pop2top div.__ns__pop2top div.ui.is-composing.__ns__pop2top div.modal-root div div.modal-root__container div.modal-root__modal.media-modal div.media-modal__closer div div.react-swipeable-view-container div div.image-loader div.zoomable-image img`
* `.modal-root` is not present, just `.modal-root__modal` and `.modal-root__container`, none of which have `z-index`
![MastodonModalRoot](https://user-images.githubusercontent.com/35199584/79041953-11420f00-7bf4-11ea-8cf6-6055170996df.png)
* DOM Screenshot
![MastodonDOM](https://user-images.githubusercontent.com/35199584/79041951-06877a00-7bf4-11ea-855a-67289b759fb5.png)

On a fresh browser windows without scrolling down (image is displayed ok) the DOM looks like this
![MastodonModalRootOk](https://user-images.githubusercontent.com/35199584/79042037-8d3c5700-7bf4-11ea-9423-5938c7d3e053.png)

**Comment by Ingo-FP-Angel** [comment]
I found something in https://anilist.co/forum/thread/11050

> Add the CSS rule
> 
> .__ns__pop2top{
>     z-index: initial;
> }
> 
> (may need greater specificity or an !important, depending on the implementation)
> 
> Reasoning:
> 
> Currently, the search overlay appears behind the activity feed, for users of the popular browser extension NoScript, when a piece of media content (mostly webms) is blocked in the feeds.
> This is due to a unfortunate coincidence, simultaneously highlighting blocked items and opening the Anilist search.
> 
> This is not a bug by NoScript nor Anilist, but the CSS rule it's a simple way to ensure compatibility.

So I tried to workaround this with a Stylus custom CSS:
```
body.__ns__pop2top, div.__ns__pop2top {
    z-index: 9998 !important;
}
```

And then the modal is ok again.

**Comment by ThibG** [comment]
Thank you for your help, this is indeed NoScript messing with the z-index of various elements, in order to bring its blocked content placeholder in front of everything else.

Your suggested CSS rule seems like a decent workaround (although I'd just use `.__ns__pop2top`, NoScript will add this rule to every ancestor of the blocked elements, not just `body` and `div`s), but I'm not completely sure adding code to workaround an issue with NoScript is advisable. Also, I think the workaround would not prevent issues with parts of the document popping in front of the emoji picker and maybe dropdown menus.

**Comment by Ingo-FP-Angel** [comment]
When I only used `.__ns__pop2top` it was ignored and the one from NoScript took precedence.
By using `body` and `div` the more specific rule was used, it seems.
I'm not a CSS expert so I just took a value that was smaller than the one used for modals to see if the workaround has the desired effect in general.

**Comment by ThibG** [comment]
Yeah, `.__ns__pop2top` gets overridden by NoScript, so more specific rules are indeed required. Tweaked it a bit in #13449 and it should work properly. Again, though, I'm not completely sure how much sense it makes to include this in Mastodon, as the issue is specific to NoScript messing up with Mastodon's DOM/CSS…

**Comment by Ingo-FP-Angel** [comment]
Yes, I was also unsure whether to close the issue after finding out that NoScript causes the behaviour.

On the one hand it's the number 4 Firefox extension by number of users.
But then it seems to rarely trigger. It was the first time I noticed it myself and nobody else reported the problem so far.

If you feel the fix is a dirty hack I'd be fine to close the issue without any changes.
At least it's now kind of documented. ;-)
