### ISSUE TITLE
Documentation does not seem to indicate how to disable rate limits

### ISSUE THREAD

**Issue by sneak** [tootsuite/mastodon#13447]
### Expected behaviour

I can disable rate limits

### Actual behaviour

I either can't or can't figure out how

### Steps to reproduce the problem

My PaaS insists on using docker swarm, which invokes the stupid userspace proxy, which means that all of the incoming connections use the same source IP.  This is an L3 proxy, not an HTTP proxy, so the original source IP is lost.  (XFF contains the userspace proxy IP.)

As a result, my instance is almost unusable.  Remote follows are failing.

### Specifications

https://docs.joinmastodon.org/api/rate-limits/ versioned 5 march 2020

**Comment by SuperSandro2000** [comment]
Can you maybe try this https://github.com/moby/moby/issues/25526#issuecomment-475083415 ?

**Comment by sneak** [comment]
I'm not interested in using host-based networking for the container, nor is it an available option in my type of deployment.  I'm not interested in changing that; what I want is to be able to disable the rate limits in Mastodon.

**Comment by nightpool** [comment]
handling the PROXY protocol is outside of the scope of the mastodon app,
but you should be able to set something like this up:

https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/

you could probably modify mastodon to disable rack-attack, but that's just
going to paper over the problem and leave your logs all messed up.

**Comment by Gargron** [comment]
I don’t recommend disabling rate limits in Mastodon unless it will not be open for the public. Spam and bots will be a massive problem for you, and your server will become a hazard for the network forcing many admins to block it.

**Comment by SuperSandro2000** [comment]
> I'm not interested in using host-based networking for the container, nor is it an available option in my type of deployment. I'm not interested in changing that; what I want is to be able to disable the rate limits in Mastodon, which is why I am posting this as an issue in the applicable repo.

Then you are out of luck and need to switch your PaaS as this is not a problem with Mastodon.

**Comment by sneak** [comment]
@Gargron Got it. I understand the risks. Is it possible without patching it out, or must I do a custom fork/container?

**Comment by Gargron** [comment]
You must modify the code to do it. Rate limits are defined in config/initializers/rack_attack.rb, there's some rate limits that aren't based on IP that you should leave in at least. Or just remove the whole file.

**Comment by sneak** [comment]
Thank you! :) Be well.

**Comment by patchshorts** [comment]
This ought to be configurable so that the software can get out of the habit of guiding infrastructure design. I run this in Kubernetes, my proxy is rate limited, if that is by design, then it ought to be redesigned for versatility in contemporary production environments.
