### ISSUE TITLE
status=500 NameError: undefined local variable... 

### ISSUE THREAD

**Issue by supremesyntax** [tootsuite/mastodon#13476]
### Expected behaviour

Mastodon instance should work as expected

### Actual behaviour

When i reload the page (getting-started) i receive an error 500 internal error at the bottom left and statuses are missing

### Steps to reproduce the problem

reload start page

### Specifications

i'm on v.3.1.3

new statuses will show up but after i refresh the page (F5) they are gone and i am getting the "500 Internal Server Error"

Journalctl says:

> Apr 15 09:24:14 xxx bundle[1804]: [*id_manually_removed*] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=500 error='NameError: undefined local variable or method 'processing' for #<MediaAttachment:0x00007f03046774c0>
> Apr 15 09:24:14 xxx bundle[1804]: Did you mean?  processing_failed?' duration=213.60 view=0.00 db=20.69
> Apr 15 09:24:14 xxx bundle[1804]: [*id_manually_removed*]
> Apr 15 09:24:14 xxx bundle[1804]: [*id_manually_removed*] NameError (undefined local variable or method 'processing' for #<MediaAttachment:0x00007f03046774c0>
> Apr 15 09:24:14 xxx bundle[1804]: Did you mean?  processing_failed?):
> Apr 15 09:24:14 xxx bundle[1804]: [*id_manually_removed*]
> Apr 15 09:24:14 xxx bundle[1804]: [*id_manually_removed*] app/models/media_attachment.rb:172:in 'not_processed?'
> Apr 15 09:24:14 xxx bundle[1804]: [*id_manually_removed*] app/serializers/rest/media_attachment_serializer.rb:15:in 'url'
> Apr 15 09:24:14 xxx bundle[1804]: [*id_manually_removed*] app/controllers/api/v1/timelines/home_controller.rb:11:in 'show'

I tried to clear the media cache, remove-orphans, even remove media and previev-cards but that didn't help.
I have also restarted the mastodon processes.

Server: 
Ubuntu 18.04.4 latest patches
ruby 2.6.6
apache as webserver

**Comment by ykzts** [comment]
Did you run `rails db: migrate`?

**Comment by supremesyntax** [comment]
yes already did that after the upgrade.
but the mentioned error have occurred overnight after the wan connection dropped unexpectedly

i did that again and received:

RAILS_ENV=production bundle exec rails db:migrate
rails aborted!
ActiveRecord::DuplicateMigrationNameError: 

Multiple migrations have the name RemoveUnneededIndexes.

/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1316:in 'validate'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1185:in 'initialize'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1036:in 'new'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1036:in 'up'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/tasks/database_tasks.rb:172:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.6.2/lib/strong_migrations/database_tasks.rb:4:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/railties/databases.rake:60:in 'block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/commands/rake/rake_command.rb:23:in 'block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/commands/rake/rake_command.rb:20:in 'perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/command.rb:48:in 'invoke'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in '<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in 'require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in 'block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in 'register'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in 'require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in 'require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in 'block in require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in 'load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in 'require'
bin/rails:4:in '\<main\>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by ykzts** [comment]
@supremesyntax What about trying #13427.

**Comment by supremesyntax** [comment]
@ykzts Thanks a lot! Problem solved!
