### ISSUE TITLE
Docs don't specify whether the same user can reblog the same status more than once

### ISSUE THREAD

**Issue by marnanel** [tootsuite/mastodon#13479]
In the docs for "reblog" at https://docs.joinmastodon.org/methods/statuses/ , it doesn't say whether the user can reblog the same status more than once.

Relatedly, "unblog" doesn't specify whether one or many reblogs are undone.

**Comment by trwnh** [comment]
fwiw these issues probably would be better suited for https://github.com/tootsuite/documentation
