### ISSUE TITLE
Massive Emoji cache

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#13491]
A long time ago, I made a script to download every emoji from every instance in the fediverse.

I just remembered that lots of instances had emoji 10+MB in size and there were 1 or two hundred MB emoji.

Could I have a limit to block emoji over 1mb? considering the Mastodon has a 50kb limit

**Comment by Gargron** [comment]
I don’t think anything over 50kb is downloaded by Mastodon

**Comment by shleeable** [comment]
ooh good :)

**Comment by shleeable** [comment]
https://github.com/tootsuite/mastodon/commit/81cec35dbf1b348d23363559e3f4e6b1ec3415c5#diff-2e414bafeee4cda5189dbaa395b4dcb1R26

Seems to be true.
