### ISSUE TITLE
feature request: web ui: show username/address as a tooltip? on hover over 

### ISSUE THREAD

**Issue by ericblade** [tootsuite/mastodon#1350]
Due to the limited width of columns, it is often not possible to see the full username and address of a user in the header of their messages, and the UI seems to strip the hostname part of mentions inside messages.  

Seems like it would be a good idea to have hover over the username part of a header show a tooltip with the user's full username and address, maybe even more details if they happen to be available on the client side already.  Same with hovering over a @ mention.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ericblade** [comment]
The title for the mentions seems like it works great, I would like to extend it to other places where usernames are visible, as well.

**Comment by Cassolotl** [comment]
This seems related to *[Feature request] Show profile preview on hover #6354*.

**Comment by trwnh** [comment]
Probably a subset of #6354 -- which is for a richer profile preview, not just the username/handle.
