### ISSUE TITLE
Feature Request: Wrap selection around dropdown menu vertically with up/down key

### ISSUE THREAD

**Issue by Phroneris** [tootsuite/mastodon#13527]
### Pitch

When just after opening a dropdown menu of a toot (ellipsis icon), pressing [↓] key starts selecting menu items from the top. It's OK.
However, pressing [↑] doesn't do it from the bottom; It results in focusing on next newer toot leaving the menu of current toot open.
I hope that the beginning of menu selection can wrap-around vertically.

When selecting the menu items with [↓] key and reaching the bottom of menu, selection doesn't jump to the top by pressing the same key.
The reverse (from top to bottom with [↑]) is also impossible.
I hope that menu selection handling can wrap-around vertically.

### Motivation

For further accessibility with keyboards.

**Comment by ThibG** [comment]
There are two things here, an issue with the up arrow not working how it should, and a feature request to have the navigation wrap around. I will look into the latter, but I can't reproduce the former. Which browser (and which version) are you using? Do you use the single-column interface or the “advanced” one? Do you think you may be using any browser add-on that could interfere with that?

**Comment by ThibG** [comment]
I have submitted a PR that addresses the wrapping request, and that I believe might fix the original issue with the “up” key as well. However, since I cannot reproduce that issue, I cannot be sure it is fixed, so more information (browser version, mainly) would still be appreciated.

**Comment by ThibG** [comment]
Thanks! Managed to reproduce it and I can confirm this is fixed.
