### ISSUE TITLE
Firefox: Notification permission only possible in user-generated event handler

### ISSUE THREAD

**Issue by dadosch** [tootsuite/mastodon#13539]
Firefox has recently (?) started to only allowing notification requests in a user-generated event handler. Mastodon doesn't do this and thus the console shows
`The Notification permission  may only be requested from inside a short running user-generated event handler. `

### Expected behaviour
Mastodon should generate the notification permission request in a user-generated event handler to make sure also Firefox Users get their notification.

### Actual behaviour
Mastodon doesn't ask for the notification request, since it isn't run from a user-generated event handler. You can workaround that by setting `dom.webnotifications.requireuserinteraction = false`

### Steps to reproduce the problem

- Firefox > 72
- clear all previous notification requests in the settings
- look in Firefox' Console. There the error `The Notification permission  may only be requested from inside a short running user-generated event handler. ` appears after some time.

### Specifications
https://www.fxsitecompat.dev/en-CA/docs/2019/requesting-notification-permission-and-screen-capture-now-requires-user-interaction/

**Comment by Gargron** [comment]
That requires rethinking the UX around that. You basically need to show an in-app prompt to the user so you can request the permission from a button click event. There's no precedent for this in our UI.

**Comment by dadosch** [comment]
I think a good place to put that prompt would be in the Notifications Column. Mark the bell-icon with a red(?) circle, just like the blue circle with the announcements. Then make it clear to the user what is expected from him by using the same red on the notification enable-button.
![Screenshot_20200423_235426](https://user-images.githubusercontent.com/12801390/80153682-8b3ba600-85ad-11ea-9084-cd22a215b74f.png)

This is just a idea and needs probably more thinking :)

**Comment by SuperSandro2000** [comment]
Just show a full screen prompt which asks you if you are a robot 😆 

Jokes aside. There should definitely not be some prompt full page prompt. I think it would best fit at the top in the notification menu without expanding some setting. The notifications setting menu is already very cluttered.

**Comment by ThibG** [comment]
I'm looking into that, but note that not only do we need to ask for permission for notifications in an event handler, but we also need to register the push notification manager in an event as well…

In terms of UX, I'm considering the following:
- tie toggling settings to a permission check/prompt, display an alert if denied
- instead of the random permission check at start, have a permission check whenever one of the notification settings is enabled, and if the permission is not granted, display a red dot as @dadosch suggested, but on the Settings button instead, as clicking on the icon/title won't bring that up

**Comment by dadosch** [comment]
As this was fixed in 3.3.0rc1, this can be closed :)

Fixed by #13543
