### ISSUE TITLE
Home doesn't show toots from people I'm following

### ISSUE THREAD

**Issue by hach-que** [tootsuite/mastodon#1354]
For some reason, after coming back to mastodon.social after like 2 months, Home doesn't show toots from anyone I'm following anymore unless I unfollow and refollow them.  My account is @hq.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
@hq@mastodon.social I guess? Tagging @Gargron then

**Comment by hach-que** [comment]
Yeah, that's the one.  I just went through some of my follows and unfollowed/refollowed so Home had some content.  But at least one other person had this problem as well: https://mastodon.social/@antumbral/1588916

**Comment by Gargron** [comment]
Duplicate of solved #5634
