### ISSUE TITLE
Automatically reserve some accounts at instance creation

### ISSUE THREAD

**Issue by wxcafe** [tootsuite/mastodon#1355]
I believe some accounts (support@, help@, admin@, root@, ...) should be reserved when initializing the database (and maybe not counted in the user count?), and possibly aliased to the actual admin's account.

Please contribute if you have ideas of other @'s to reserve

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by James-Firth** [comment]
I think this is a pretty good idea to have some consistency and avoid people pretending they are the admin of a particular instance.

I would throw in:
* administrator (just to double-down on the admin idea)
* webmaster (for historical sake)

Tempted to put security@ but I think anyone reporting security issues would know how to find the email for the domain or post a bug here/message Gargron directly.

If possible the support/help accounts would also be bots to link to info pages (if help pages are compiled in the future)

**Comment by ngerakines** [comment]
Implemented in https://github.com/tootsuite/mastodon/pull/1382 .

**Comment by hikaru-light** [comment]
I suggest reserving these words "system", "host", "official", "owner", "master", "register", "staff".
At least, I added them as reserved usernames in developing another service.
Please let me know your opinions.

**Comment by Gargron** [comment]
Implemented in #3566

**Comment by dannythehacker** [comment]
i am so mad i want to set my user name to admin because i own the server how do i bypass the reserved bull shit i am so mad

**Comment by dannythehacker** [comment]
and i cant even set the username to admin in command line what the f i understand at the sign up screen

**Comment by trwnh** [comment]
edit config/settings.yml?

**Comment by dannythehacker** [comment]
okay sorry
