### ISSUE TITLE
Post statistics are not displayed on the account page

### ISSUE THREAD

**Issue by alisa23a** [tootsuite/mastodon#13572]
Post statistics are not displayed on the account page. On the page of single post statistics are displayed normally.
![011](https://user-images.githubusercontent.com/19745192/80401060-66547500-88c4-11ea-9bf0-24cc57ec22a5.png)
![021](https://user-images.githubusercontent.com/19745192/80401065-6785a200-88c4-11ea-9e42-97e6151dece6.png)

**Comment by Gargron** [comment]
Not a bug, numbers are kept out of the way to reduce stress.
