### ISSUE TITLE
Suspend an account does not delete associated statuses. 

### ISSUE THREAD

**Issue by MicroCheapFx** [tootsuite/mastodon#13588]
### Expected behaviour

I suspend a bot account spamming my instance.

I expect the associated statuses to be automatically deleted without further actions from my side.

### Actual behaviour

Associated statuses are not deleted. I have to do it manually.

### Steps to reproduce the problem

Suspend an account with statuses.

### Specifications

Mastodon 3.1.2

**Comment by Tagadda** [comment]
This should not happen.
Actual behaviour is delete associated status on account suspension.
IIRC this might take some time because this is treated by Sidekiq.

**Comment by MicroCheapFx** [comment]
I tried with some new invading bots.

If the message is signaled, it takes time, but it deletes after several minutes.
If I suspend it without signaling, status stays.

**Comment by Gargron** [comment]
What do you mean by signaling?

**Comment by MicroCheapFx** [comment]
I meant reporting.

**Comment by MicroCheapFx** [comment]
Ok. It does. It takes just a loooooooooooonger amount of time (about half an hour).

**Comment by MicroCheapFx** [comment]
Thank for your time. I hope I didn't waste it too much.
