### ISSUE TITLE
[suggestion] Twitter UI mode

### ISSUE THREAD

**Issue by Thanaen** [tootsuite/mastodon#1358]
Mastodon is inspired from the Tweetdeck UI, but I think there should be an option to switch to the classic Twitter UI, that would allow many people to switch easily from Twitter to Mastodon (at least me).

Thanks for the work already done :)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

**Comment by wxcafe** [comment]
This could be done as an app to make an alternative frontend. Or you could just use a GNUSocial instance, which federates with mastodon and look a lot like Twitter Web (https://gnusocial.net/main/all for example). Anyway, this is not something that is going to be implemented as a frontend to Mastodon any time soon afaict. If your question is answered, I'll ask you to close this issue

**Comment by Thanaen** [comment]
Thank you for the clear answer!
