### ISSUE TITLE
"tootctl upgrade storage-schema" fails to move "original" custom_emoji files to cache

### ISSUE THREAD

**Issue by Hanage999** [tootsuite/mastodon#13594]
### Expected behaviour

When you execute "tootctl upgrade storage-schema" added in https://github.com/tootsuite/mastodon/pull/12821 , remote media files cached in system/custom_emojis/images/xxx/xxx/xxx/original are moved to respective cache folders.

### Actual behaviour

"Original" custom emoji files remain where they are. "Static" files are moved as expected.

### Steps to reproduce the problem

Execute "tootctl upgrade storage-schema."

### Specifications

Found in https://github.com/tootsuite/mastodon/commit/5cff7910c2c519af2d255454b66b0bfa6cf5288c

**Comment by mashirozx** [comment]
The same issue, and I got to copy the whole "original" folder to cache folder, which result in a lot of duplicate media files instead front-end's 404 error.

**Comment by mashirozx** [comment]
I shouldn't try the `tootctl upgrade storage-schema` command when I upgrade to v3.1.4. TAT
