### ISSUE TITLE
Muting account hides from follows & followers list instead of showing muted icon

### ISSUE THREAD

**Issue by DexterHaslem** [tootsuite/mastodon#13612]
If you mute someone you follow, then view your 'following' page, the account is no longer listed.
previously it was still listed with the muted icon. This makes finding the account again non-trivial (search, open tab, etc). They also disappear from followers if they follow you

### Steps to reproduce the problem
1. click your profile and open your profile follows list (`web/accounts/<your id>/following`)
1. select a poor victim in the list, click to view profile and mute them. notification setting doesnt matter
1. go back to `web/accounts/<your id>/following` and refresh, the account disappears from list
1. if you unmute them and refresh they re-appear

### Specifications
v3.1.3
this started happening somewhere around 3.1.2

**Comment by ThibG** [comment]
Oh, nice find. This is because of the change introduced in #12733. Hiding blocked/muted users from followers/following lists is on purpose, but hiding them from your *own* lists is definitely not ok.
