### ISSUE TITLE
Scope issue with "read write follow" scoped token

### ISSUE THREAD

**Issue by jdenen** [tootsuite/mastodon#1367]
I'm trying to `POST` with Emacs and [mastodon.el](https://github.com/jdenen/mastodon.el), and when I try to `POST` a new toot, I get a `403 Forbidden` error with the message:

```json
{"error":"This action is outside the authorized scopes"}
``` 

But the app is registered with `"read write follow"` scopes [[1]](https://github.com/jdenen/mastodon.el/blob/master/lisp/mastodon-auth.el#L29), and the web UI shows the correct scopes.

<img width="745" alt="screen shot 2017-04-09 at 4 01 32 pm" src="https://cloud.githubusercontent.com/assets/4671695/24840598/db7a0f16-1d3d-11e7-8c75-e7fe53825180.png">

I get the same issue with `cURL`.

```bash
curl -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json" -S -X POST -d '{"status":"Just cURLing. Please ignore."}' https://mastodon.social/api/v1/statuses
```

The thing is, `cURL` with read access works just fine for my token. This returns a `200`:

```bash
curl --header "Authorization: Bearer ${TOKEN}" -sS https://mastodon.social/api/v1/statuses/1895661
```

So there doesn't seem to be an issue with the token itself, but the scope attached to the token. Any help would be greatly appreciated!
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Scopes need to set on initial app registration *as well as* the token request. (In the first case `scopes`, in the latter it's `scope`)

**Comment by jdenen** [comment]
Ah, that's it then. I'm only setting scope on registration. Emacs will be tooting soon then. Thanks for the help!

**Comment by wxcafe** [comment]
@jdenen is this resolved? Please close the issue if it is 🙂

**Comment by jdenen** [comment]
I knew I forgot something. Thanks.

**Comment by brucelane** [comment]
hi, I'm sorry to comment about this, but I have the same problem, I tryed several ways, I'm still confused...
So I manage to do POSTs and GETs, but not POST statuses due to this scope thingy...
I'm in javascript mode, all my POSTs use:
```
    options.headers.append('Accept', 'application/json');
    options.headers.append('Content-Type', 'application/json');
    options.headers.append('Authorization', 'Bearer ' + this.access_token);
```
Where should put this 'scope' header?
Thank you

**Comment by alexg-k** [comment]
> Scopes need to set on initial app registration _as well as_ the token request. (In the first case `scopes`, in the latter it's `scope`)

There should be a notification about this on the "Application" page. It took me weeks to find out what's wrong.
Maybe the tokens must be automatically regenerated after changes in the scope?

**Comment by danhunsaker** [comment]
Why should this be noted within Mastodon itself? It's part of the way OAuth works, AIUI.
