### ISSUE TITLE
Content Filters not applied to Content Warning title

### ISSUE THREAD

**Issue by dadosch** [tootsuite/mastodon#13696]
### Expected behaviour
When filtering specific words from timelines, it is expected that those words are also matched against the Content Warning messages.

### Actual behaviour
The Content Filters aren't matched against the CW.

### Steps to reproduce the problem

1. Add a content filter for `covid`
2. See, that toots with a CW of "covid" are not filtered.

### Specifications

Mastodon v3.1.3

**Comment by ThibG** [comment]
I cannot reproduce this, the CW is definitely tested.

**Comment by dadosch** [comment]
That is strange :confused: 

I'll investigate it a bit and reopen the issue if needed.
