### ISSUE TITLE
Can't upload avatar or cover image "new instance"

### ISSUE THREAD

**Issue by b0hem14n** [tootsuite/mastodon#13691]
Hi everyone I'm deploying new instance but I can't upload avatar,cover image or server image.
I'm getting "We're sorry, but something went wrong on our end." error everytime.

**Comment by Gargron** [comment]
Please see first point to get the error stacktrace: https://docs.joinmastodon.org/admin/troubleshooting/

**Comment by b0hem14n** [comment]
`May 09 23:20:47 localhost systemd[1]: Started mastodon-web.
May 09 23:20:52 localhost bundle[10238]: [10238] Puma starting in cluster mode...
May 09 23:20:52 localhost bundle[10238]: [10238] * Version 4.3.3 (ruby 2.6.6-p146), codename: Mysterious Traveller
May 09 23:20:52 localhost bundle[10238]: [10238] * Min threads: 5, max threads: 5
May 09 23:20:52 localhost bundle[10238]: [10238] * Environment: production
May 09 23:20:52 localhost bundle[10238]: [10238] * Process workers: 2
May 09 23:20:52 localhost bundle[10238]: [10238] * Preloading application
May 09 23:21:23 localhost bundle[10238]: [10238] * Listening on tcp://127.0.0.1:3000
May 09 23:21:23 localhost bundle[10238]: [10238] ! WARNING: Detected 2 Thread(s) started in app boot:
May 09 23:21:23 localhost bundle[10238]: [10238] ! #<Thread:0x000055a6d0617548@/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:38 sleep_forever> - /ho
May 09 23:21:23 localhost bundle[10238]: [10238] ! #<Thread:0x000055a6d1e05ee8@/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:299 sleep> - /home/ma
May 09 23:21:23 localhost bundle[10238]: [10238] Use Ctrl-C to stop
May 09 23:21:23 localhost bundle[10238]: [10238] - Worker 0 (pid: 10347) booted, phase: 0
May 09 23:21:23 localhost bundle[10238]: [10238] - Worker 1 (pid: 10360) booted, phase: 0
May 09 23:21:39 localhost bundle[10238]: [e22fb537-1a6b-4994-a95d-a64cb61111a8] Chewy request strategy is `custom_sidekiq`
May 09 23:21:39 localhost bundle[10238]: [e22fb537-1a6b-4994-a95d-a64cb61111a8] method=GET path=/ format=html controller=HomeController action=index status=302 duration=31.93 view=0.00 location=https://giveblood.me/about
May 09 23:21:43 localhost bundle[10238]: [6cb6e304-299b-4c9f-9554-b61957d9de6f] method=GET path=/about format=html controller=AboutController action=show status=200 duration=3934.57 view=3922.99 db=89.12
May 09 23:21:44 localhost bundle[10238]: [788f93ad-c8c5-4062-b6fd-7f876f2a1ea0] method=GET path=/manifest.json format=json controller=ManifestsController action=show status=200 duration=10.31 view=6.77 db=0.00
May 09 23:21:45 localhost bundle[10238]: [2b66bea6-6faa-4a4e-bb30-a97099a9c0c9] method=GET path=/index.php format=*/* controller=ApplicationController action=raise_not_found status=404 duration=25.60 view=21.16 db=0.00
May 09 23:21:58 localhost bundle[10238]: [589e28d8-4b46-4743-a70a-b5a8523b08de] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=0 duration=13.54 view=0.00 db=0.88
May 09 23:21:59 localhost bundle[10238]: [589e28d8-4b46-4743-a70a-b5a8523b08de] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=new status=200 duration=167.55 view=64.88 db=0.00
May 09 23:22:01 localhost bundle[10238]: [2f54d9f1-ade5-477e-bae9-0a8564191dbc] method=GET path=/index.php format=*/* controller=ApplicationController action=raise_not_found status=404 duration=5.59 view=2.53 db=0.00
May 09 23:22:14 localhost bundle[10238]: [5eb0baba-ecf6-4624-bb6e-09b43ea35141] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=0 duration=7.87 view=0.00 db=0.67
May 09 23:22:15 localhost bundle[10238]: [5eb0baba-ecf6-4624-bb6e-09b43ea35141] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=new status=200 duration=118.98 view=20.59 db=0.00
May 09 23:22:16 localhost bundle[10238]: [f823060a-ac72-40ba-867c-8ac2190cbe2a] method=GET path=/index.php format=*/* controller=ApplicationController action=raise_not_found status=404 duration=5.11 view=2.35 db=0.00
May 09 23:22:26 localhost bundle[10238]: [45622063-cf21-4626-b99c-2cbf4a29a212] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=302 duration=305.64 view=0.00 db=51.64 location=https://g
May 09 23:22:26 localhost bundle[10238]: [b50ee7f4-0c91-493e-b302-e0c1506f274c] method=GET path=/ format=html controller=HomeController action=index status=200 duration=162.15 view=116.60 db=25.64
May 09 23:22:27 localhost bundle[10238]: [b6176ae0-4667-40f9-83f5-51003b8ebd1c] method=GET path=/api/v1/custom_emojis format=html controller=Api::V1::CustomEmojisController action=index status=200 duration=23.96 view=3.53 db=7.77
May 09 23:22:27 localhost bundle[10238]: [e5407607-baa9-4c29-8f70-2dcf52f816cb] method=GET path=/ format=*/* controller=HomeController action=index status=200 duration=295.13 view=242.55 db=18.30
May 09 23:22:43 localhost bundle[10238]: [d84bed8d-b152-45d7-801e-85a8ae600d63] Chewy request strategy is `custom_sidekiq`
May 09 23:22:43 localhost bundle[10238]: [a63eee06-7dbc-4130-bfe3-dafef259420e] Chewy request strategy is `custom_sidekiq`
May 09 23:22:43 localhost bundle[10238]: [46497117-fb84-4611-9d2e-2ac99436d15b] Chewy request strategy is `custom_sidekiq`
May 09 23:22:43 localhost bundle[10238]: [04dc19ba-d594-4d26-b8e4-a3d1fddeaedc] Chewy request strategy is `custom_sidekiq`
May 09 23:22:43 localhost bundle[10238]: [e7ba6405-7564-484e-bd44-b1aa29aca491] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=143.15 view=1.06 db=83.71
May 09 23:22:43 localhost bundle[10238]: [069fd6c1-4052-4e71-89dd-6a84bc754c20] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=86.03 view=2.04 db=46.13
May 09 23:22:43 localhost bundle[10238]: [9c5406ad-948d-48db-ba6c-efd650abad5f] method=GET path=/api/v1/filters format=html controller=Api::V1::FiltersController action=index status=200 duration=41.77 view=11.79 db=18.94
May 09 23:22:44 localhost bundle[10238]: [04dc19ba-d594-4d26-b8e4-a3d1fddeaedc] method=GET path=/api/v1/trends format=html controller=Api::V1::TrendsController action=index status=200 duration=456.37 view=1.42 db=246.24
May 09 23:22:44 localhost bundle[10238]: [46497117-fb84-4611-9d2e-2ac99436d15b] method=GET path=/api/v1/lists format=html controller=Api::V1::ListsController action=index status=200 duration=465.69 view=12.94 db=285.71
May 09 23:22:44 localhost bundle[10238]: [a63eee06-7dbc-4130-bfe3-dafef259420e] method=GET path=/api/v1/follow_requests format=html controller=Api::V1::FollowRequestsController action=index status=200 duration=481.96 view=0.93 db=178.39
May 09 23:22:44 localhost bundle[10238]: [d84bed8d-b152-45d7-801e-85a8ae600d63] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=510.17 view=1.11 db=292.69
May 09 23:22:47 localhost bundle[10238]: [b60f5a4e-9f0d-4e24-9ca2-507b19ab465d] method=PUT path=/api/web/settings format=html controller=Api::Web::SettingsController action=update status=200 duration=51.72 view=1.45 db=17.87
May 09 23:23:03 localhost bundle[10238]: [35c96e08-86eb-475a-94c1-7958ae5eb9c6] method=GET path=/settings/preferences/appearance format=html controller=Settings::Preferences::AppearanceController action=show status=200 duration=341.39 vi
May 09 23:23:16 localhost bundle[10238]: [5a3694e4-7b56-4932-8c48-6f1971363242] method=PUT path=/settings/preferences/appearance format=html controller=Settings::Preferences::AppearanceController action=update status=302 duration=243.04
May 09 23:23:17 localhost bundle[10238]: [ec0af5a1-458b-49c7-9fd1-290b7c4275a5] method=GET path=/settings/preferences/appearance format=html controller=Settings::Preferences::AppearanceController action=show status=200 duration=240.77 vi
May 09 23:23:21 localhost bundle[10238]: [ffd2eddf-a4a5-4f3a-9702-60e12bc64be4] method=GET path=/admin/dashboard format=html controller=Admin::DashboardController action=index status=200 duration=189.02 view=109.14 db=37.06
May 09 23:23:32 localhost bundle[10238]: [48310253-2eb1-483d-b616-5f6212e60c5c] method=GET path=/admin/accounts/1 format=html controller=Admin::AccountsController action=show status=200 duration=500.80 view=372.71 db=57.34
May 09 23:23:32 localhost bundle[10238]: [8e3f71f4-b865-4eca-8591-1f5b044d3644] method=GET path=/manifest.json format=json controller=ManifestsController action=show status=200 duration=9.65 view=6.42 db=0.00
May 09 23:23:38 localhost bundle[10238]: [cc4d8b34-a9be-475b-a9dd-7dbcbec0798a] method=GET path=/ format=html controller=HomeController action=index status=200 duration=133.32 view=96.43 db=10.95
May 09 23:23:39 localhost bundle[10238]: [7dbcc88e-aaac-4206-b8de-c29d73e88be1] method=GET path=/api/v1/trends format=html controller=Api::V1::TrendsController action=index status=200 duration=149.92 view=0.94 db=140.30
May 09 23:23:39 localhost bundle[10238]: [a32984be-7cde-4faf-a45f-c9ce1e573660] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=194.17 view=1.01 db=57.08
May 09 23:23:39 localhost bundle[10238]: [be29be86-e4c7-4bf0-a026-b8e8b2a228e2] method=GET path=/api/v1/lists format=html controller=Api::V1::ListsController action=index status=200 duration=132.11 view=1.96 db=110.84
May 09 23:23:39 localhost bundle[10238]: [45d1e851-d26b-4070-a126-934f60bec0ba] method=GET path=/api/v1/follow_requests format=html controller=Api::V1::FollowRequestsController action=index status=200 duration=132.69 view=0.85 db=102.97
May 09 23:23:39 localhost bundle[10238]: [f3e3a486-46d7-41a2-a928-04bda06b3772] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=179.29 view=0.73 db=148.77
May 09 23:23:39 localhost bundle[10238]: [aa0cee37-7344-47ea-8279-962cc9db577c] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=53.98 view=1.84 db=14.20
May 09 23:23:39 localhost bundle[10238]: [156e7692-f2fc-4923-8aee-e88aa922926a] method=GET path=/api/v1/filters format=html controller=Api::V1::FiltersController action=index status=200 duration=28.79 view=8.17 db=9.51
May 09 23:23:45 localhost bundle[10238]: [a12f04b9-bc28-4438-bd8b-9967f32d6e5c] method=GET path=/settings/preferences/appearance format=html controller=Settings::Preferences::AppearanceController action=show status=200 duration=3682.51 v
May 09 23:23:58 localhost bundle[10238]: [524c4263-b671-40e3-b18f-ab1f3f65365c] method=PUT path=/settings/preferences/appearance format=html controller=Settings::Preferences::AppearanceController action=update status=302 duration=209.22
May 09 23:23:59 localhost bundle[10238]: [e826b95b-f4d1-494d-8f2c-f54848755582] method=GET path=/settings/preferences/appearance format=html controller=Settings::Preferences::AppearanceController action=show status=200 duration=89.16 vie
May 09 23:24:01 localhost bundle[10238]: [5b47de08-a8e3-4f77-be53-47b5880f6ac9] method=GET path=/ format=html controller=HomeController action=index status=200 duration=92.60 view=69.57 db=6.98
May 09 23:24:02 localhost bundle[10238]: [c3768d09-d8ad-45c4-bba2-a3ca8aa74079] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=80.51 view=1.29 db=51.11
May 09 23:24:02 localhost bundle[10238]: [58fd79b5-7b82-4602-9592-c26e835d57ae] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=94.89 view=0.82 db=46.63
`

**Comment by b0hem14n** [comment]
`Aws::S3::Errors::SignatureDoesNotMatch (The request signature we calculated does not match the signature you provided. Check your Google secret key and signin`

I think thats the problem how can i shut this feature?

**Comment by Gargron** [comment]
What object storage provider are you using? What S3-related environment variables are you using (with personal values redacted)?

**Comment by Gargron** [comment]
If you don't want to use object storage, you can just set `S3_ENABLED=false`, then it will be using local filesystem for file uploads.

**Comment by b0hem14n** [comment]
Actually im not using any of them. I accidentally enabled this feature during installation.

**Comment by b0hem14n** [comment]
> If you don't want to use object storage, you can just set `S3_ENABLED=false`, then it will be using local filesystem for file uploads.

is this command or should i change this value in system files?

**Comment by Gargron** [comment]
Your config is stored in the .env.production file within Mastodon's directory. Just edit it, save, then restart Mastodon.

**Comment by b0hem14n** [comment]
İ think i change this value in .env.production right? But i cant find file.

Thanks in advance.

**Comment by Gargron** [comment]
How did you install Mastodon? Guide, DigitalOcean 1-click-install, Docker?

In most cases the file would be in `/home/mastodon/live/.env.production`

**Comment by b0hem14n** [comment]
I used official guide in here https://docs.joinmastodon.org/admin/install/

and its not here /home/mastodon/live/.env.production 

Thank you

**Comment by b0hem14n** [comment]
Finally i found the file and change the value and restart Mastodon but still same.

**Comment by b0hem14n** [comment]
`Errno::EACCES (Permission denied @ dir_s_mkdir - /home/mastodon/live/public/system):`
