### ISSUE TITLE
docker-compose.yml should define volume for database

### ISSUE THREAD

**Issue by jemus42** [tootsuite/mastodon#1376]
As I just found out the hard way, if you don't know to assign a volume to the `db` container in the `docker-compose.yml`, you might lose your database if you `docker-compose down` on accident (*cough*) (or incidentally, if you reboot your server, presumably?).

My proposal: Either tweak the default `docker-compose.yml` to define a volume, or make a not on the setup guide that 

a) What I describe above is a risk
b) You should probably set up a volume

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
Could you do a PR with one of the proposed modifications?

**Comment by jemus42** [comment]
@wxcafe Done: https://github.com/tootsuite/mastodon/pull/1378

Please note that I'm a docker noob, and also I don't have any experience with rails/ruby, and also no idea how postgres works, and… well, you get the idea.

**Comment by wxcafe** [comment]
This seems good to me but I don't use docker a lot either, so I'd like to have someone who uses it to review this PR

**Comment by cm6051** [comment]
This PR looks good to me (I've used Docker extensively and trained large groups in it)

**Comment by wxcafe** [comment]
Looks like an upgrade mechanism needs to be taken into account before this is merged
