### ISSUE TITLE
Scrolling home timeline causes removeChild error in react

### ISSUE THREAD

**Issue by Valenoern** [tootsuite/mastodon#13814]
### Expected behaviour

Until recently, infinite scroll on the home timeline would go any length without problems.

### Actual behaviour

It seems like on all the vanilla mastodon instances I use, scrolling almost immediately causes an error. This brings up the error screen that says

> Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly

and the console says

```
react-dom.production.min.js:5058 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ls (https://floss.social/packs/js/common-6983242b038bcddfbf4f.js:2:1048640)
    at pu (https://floss.social/packs/js/common-6983242b038bcddfbf4f.js:2:1061829)
    at https://floss.social/packs/js/common-6983242b038bcddfbf4f.js:2:1082529
    at Ha (https://floss.social/packs/js/common-6983242b038bcddfbf4f.js:2:1006995)
    at du (https://floss.social/packs/js/common-6983242b038bcddfbf4f.js:2:1059689)
    at Zs (https://floss.social/packs/js/common-6983242b038bcddfbf4f.js:2:1055843)
    at https://floss.social/packs/js/common-6983242b038bcddfbf4f.js:2:1007286
    at https://floss.social/packs/js/common-6983242b038bcddfbf4f.js:2:1082529
    at Ha (https://floss.social/packs/js/common-6983242b038bcddfbf4f.js:2:1006995)
    at Va (https://floss.social/packs/js/common-6983242b038bcddfbf4f.js:2:1007231)
```

### Specifications

* devuan linux / xfce
* Brave browser - Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
  * did *not* occur on pure chromium: Version 73.0.3683.75 (Developer Build) built on Debian 9.8, running on Debian 9 (64-bit)
* mastodon 3.1.3, 3.1.4
  * tested on queer.party, floss.social

---

I tried to search if this was a duplicate issue but could not find it reported yet.  
edit: this is almost certainly tied to either > 73 chromium or Brave, but I can't test a recent chromium right now as that isn't in the devuan repos (and snaps don't work without systemd)

**Comment by ThibG** [comment]
Do you have add-ons or things like auto-translation enabled?

**Comment by Valenoern** [comment]
I tested again today in a guest window and then with most extensions disabled, and I think this is specifically a problem with the Chromoji extension badly meshing with react-dom.

I don't really know which one is at fault so I guess I'll go report it to both of them.
