### ISSUE TITLE
bin/tootctl upgrade storage-schema crashes after ~20 sec,

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#13815]
### Expected behaviour

`bin/tootctl upgrade storage-schema` should run, although it takes time.

### Actual behaviour

It crashes right after ~20 seconds. It gives a lot of output, but this seems the important one. USERNAME and DOMAIN are actually real names, but because of privacy I removed them. It is a remote domain.

```
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postg
resql_adapter.rb:611:in `exec_params': PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint
 "index_accounts_on_username_and_domain_lower" (ActiveRecord::RecordNotUnique)
DETAIL:  Key (lower(username::text), lower(domain::text))=(teslas_moustache, anticapitalist.party) already exists.
: UPDATE "accounts" SET "avatar_storage_schema_version" = 1, "header_storage_schema_version" = 1, "updated_at" = '
2020-05-18 21:29:59.079150' WHERE "accounts"."id" = 40
```
This error is produced two times. See the whole trace here: https://pad.disroot.org/p/r.bd9a91d594de3fb811dce5c5223b529c

### Steps to reproduce the problem

I can't reproduce it. I have another (smaller) Mastodon server and there it works. It is has the same specs.

### Specifications
3.1.4

I use PGBouncer, so I have `export DB_PORT=5432 `(as well as `export RAILS_ENV=production`) in .bashrc (so I never forget).

**Comment by Gargron** [comment]
This looks like a corrupted unique index / duplicate database records, not directly related to the tootctl task only in so far as the task touches the duplicate record.

**Comment by Gargron** [comment]
See possible course of action in this thread: https://github.com/tootsuite/mastodon/issues/13402#issuecomment-615233732

**Comment by jeroenpraat** [comment]
@Gargron Thank you for reply. This user has indeed two entries in the account table. Both have followers. 

I wish there was some simple method to check and fix longer used databases for issues like this or else this would becoming worse and worse. Older Mastodon servers are clearly sensitive for issues like this.
