### ISSUE TITLE
Batching of equal notification types

### ISSUE THREAD

**Issue by resynth1943** [tootsuite/mastodon#13825]
# Batching of equal notification types

(apologies for the content of the toot :stuck_out_tongue:)

<details>
  <summary>Notification screen</summary>
  <img src="https://user-images.githubusercontent.com/49915996/82700517-da80ff00-9c5d-11ea-8a61-8817905d7d03.png" />
</details>

### Pitch

If a great amount of people favourite / boost your toot, you will end up with spam in your notifications. Twitter groups like / retweet actions together so they don't waste space.

For example, the above *should* render to something like this:

```
[ Joe, Bob, Mary and 6 others favourited your toot ]
[ Bonnie, Susan, Bill and 4 others boosted your toot ]
```

### Motivation

People that get a lot of boosts / favourites?

**Comment by trwnh** [comment]
duplicate of #1483

**Comment by resynth1943** [comment]
Thanks.
