### ISSUE TITLE
Trending hashtags not refreshing

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#13840]
### Expected behaviour

The trending hashtags should be determined every night.

### Actual behaviour

The hashtags should be pulled every night, but instead nothing happens, even after adding a Sidekiq job for that manually. I looked into the admin panel, still being the same.

### Steps to reproduce the problem

Either get Mastodon to pull hashtags automatically or add a Sidekiq job for it

### Specifications

Mastodon 3.1.4 `50524d13278806573a4a685e428a6c9f3d7a74e5`
Using Elasticsearch
Running over Kubernetes

**Comment by yingziwu** [comment]
I meet the same problem.
![image](https://user-images.githubusercontent.com/22741471/83345433-9967a980-a345-11ea-9490-f333c227c91d.png)
Many Hashtag count has been 0, but these hashtag still are Trending now.

Softed by Most popular is also problematic.
![image](https://user-images.githubusercontent.com/22741471/83345427-805ef880-a345-11ea-99ed-3b1255aa97b8.png)
![image](https://user-images.githubusercontent.com/22741471/83345429-8523ac80-a345-11ea-8126-abdce213327c.png)


Besides, #13450 also reported this problem.

**Comment by koyuawsmbrtn** [comment]
The issue has been fixed in a later commit. This ticket is now closed.

**Comment by jellykells** [comment]
@koyuawsmbrtn could you specify which commit fixed the issue please?
