### ISSUE TITLE
User Profile page scrambled on mobile browser on v3.1.4

### ISSUE THREAD

**Issue by fingerprintsh** [tootsuite/mastodon#13881]
User profile page and toot lists are scrambled with text and image 

### Expected behaviour

The UI of the said page should be clean and in order 

### Actual behaviour

But It's getting almost unreadable as texts and images are overlapping .

Check Screenshot :  

[https://ibb.co/G5xBp1g](https://ibb.co/G5xBp1g)
[https://ibb.co/X482nRW](https://ibb.co/X482nRW)

OR visit

https://bong.social/explore. any profile from mobile browser.

### Steps to reproduce the problem

just try to access the page as both guest or logged in 

Upgraded to v3.1.4 from v3.1.3
Accessing on chrome and Firefox on Android 10

How to fix it or should I get back to previous version ?

**Comment by fingerprintsh** [comment]
Just an update. Found now this is also happening on desktop browsers as well.
I am on chromecase @ mac os 

visit https://bong.social/@nomoshkar.

**Comment by ykzts** [comment]
Did you run `bundle exec rails assets:precompile`?

**Comment by fingerprintsh** [comment]
had to go back to a previous snapshot and update again . now its ok. dont know what was the cause as no error were there during both update . lost 1 day posts.

**Comment by ThibG** [comment]
@fingerprintsh there are cases in which, when assets compilation fails, webpacker will think it is not necessary to rebuild them again, and will then do nothing and not error out again.

In the future, if such a case arises again, you can do something like `bundle exec rails assets:clobber` then `bundle exec rails assets:precompile`, this would make the web interface temporarily unavailable, but will spare you having to restore a previous snapshot.
