### ISSUE TITLE
option to disable slide left and right to switch tab

### ISSUE THREAD

**Issue by delata** [tootsuite/mastodon#13882]
### Pitch
option to disable slide left and right to switch tab

### Motivation
i don't like it. on low end phone it is junky.
may be other people like. so i want a option to disable it. 
it also reduce JavaScript usage.

thanks.

**Comment by ThibG** [comment]
I will look into that.

> it also reduce JavaScript usage.

I don't understand that part of your message, though?

**Comment by delata** [comment]
@ThibG how do you handle this sliding? via JavaScript. right? 
or how?

**Comment by ThibG** [comment]
We use a library called `react-swipeable-views`, which is mostly Javascript, with the actual animations being mostly CSS. But the whole app relies entirely on Javascript, everything rendered is ultimately the result of some Javascript calls, that's how React and client-side rendering work in general.
