### ISSUE TITLE
Static assets are not compressed (gzip/deflate/brotli/zopfli).

### ISSUE THREAD

**Issue by skhameneh** [tootsuite/mastodon#1388]
Some web servers will force gzipping of content, it appears the base setup does not gzip any content
The zlib works great for on-the-fly compression, zopfli is optimal for one-time (gzip) compression, and brotli is gaining support.

I can add benchmarks and a task list as necessary; it would be good to start with zopfli or zlib during asset generation; content can be forced or selectively served to clients with "Accept-Encoding: gzip, ..."  zopfli-png can also be used to optimize the internal gzip compression of PNGs.

**Comment by skhameneh** [comment]
It looks like static assets are being gzipped; some nginx settings may be configurable for this.
I am, using haproxy myself, I will report back with settings for haproxy.

For long-term, the assets server should handle some of this as well.

**Comment by Gargron** [comment]
I think this is question of reverse proxy configuration, not something Mastodon code should worry about.
