### ISSUE TITLE
Secure Chat for Mastodon over McEliece

### ISSUE THREAD

**Issue by webermike** [tootsuite/mastodon#13895]
Feature Request:
- according to NIST especially the McEliece Algo is quantum computing secure
- a crypto chat server for McEliece would be a Spot-On chat server. This could be addressed with C++ or Python Crypto Programming into Mastodon for direct chats and also for group chat (see Manual: ISBN: 9783749435067) 
- Also group chat like IRC is possible over Magnet-URIs.

**Comment by ThibG** [comment]
The McEliece Algo has been very little studied and is very little used. As we are not cryptographers, we are not comfortable with using such an algorithm in Mastodon. Furthermore, the McEliece cryptosystem also has a number of drawbacks, such as large key size and doubled cyphertext size.

Your other points go far beyond the use of just the McEliece algorithms and suggest using little-studied cryptographic and communication protocols, I am even less comfortable with that.

Please know that we are currently considering E2EE based on the protocol used by Signal, OMEMO and Matrix, which are somewhat widely-used, and have been widely studied. They use EdDSA and ECDH for their asymmetric operations, though.

**Comment by webermike** [comment]
First of all it sounds like a reasonable answer.

McEliece is available in BouncyCastle. or McNoodle Library.

McEliece has received review: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C22&as_vis=1&q=mceliece&btnG=.

Finally, start to discover and learn. :-)
