### ISSUE TITLE
Can't re-follow remote account that was deleted and re-created

### ISSUE THREAD

**Issue by mbrubeck** [tootsuite/mastodon#1390]
[This account on oulipo.social](https://oulipo.social/@mbrubck) was accidentally deleted.  (Possibly relevant: It was deleted by some sort of bug, not on purpose. mus@oulipo.social may have more details.)  After the account was deleted, I created a new account with the same username.

Now, on mastodon.social I can only see the old account, and I can't see any posts from the new account.  This remains true even after un-following and re-following the account.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
This should be fixed now that Webfinger allows periodical refreshes.

**Comment by mbrubeck** [comment]
Confirmed fixed
