### ISSUE TITLE
Parse RSS-based user feeds

### ISSUE THREAD

**Issue by singpolyma** [tootsuite/mastodon#1391]
My webfinger: `acct:singpolyma@singpolyma.net`

My feed is in RSS, and I'm pretty sure that's what's causing Mastodon to choke (it just gives me a 422 when I try to follow).

**Comment by lmorchard** [comment]
OStatus & Mastodon might benefit from a validation service someday - or at least better error messages.

RSS is one problem - it's not part of the OStatus spec, only Atom + Activity Streams. That said, Mastodon *could* support it as an option on top. 

Beyond that, it looks like you're missing a [`/.well-known/host-meta` resource](https://mastodon.social/.well-known/host-meta) to supply the URL template for WebFinger. Looks like the [Goldfinger client expects that and throws an error if it's not found](https://github.com/tootsuite/goldfinger/blob/73a44507c6bf4fb7749f60e812ec745e3f91a45b/lib/goldfinger/client.rb#L26)

**Comment by singpolyma** [comment]
GNU Social has supported my RSS for years. I'll look into the host-meta issue. Just updated my webfinger plugins and such to switch to JRD and webfinger test sites I found worked, but something may have got missed.

**Comment by lmorchard** [comment]
> GNU Social has supported my RSS for years.

Actually, yeah, I take back my comment - RSS *is* mentioned in the [OStatus spec](https://www.w3.org/community/ostatus/wiki/images/9/93/OStatus_1.0_Draft_2.pdf). Just gets Atom-specific when it gets down to "Feed Representation" discussion. Otherwise:

> In the absence of additional information, a default Atom or RSS feed without additional Activity data will be represented as with activity verb "Post" and activity object type "Note", with the Atom author as the implied activity actor.

**Comment by Gargron** [comment]
I'm sorry but I am not planning on expanding OStatus support any further to include using RSS feeds as federation mechanism.
