### ISSUE TITLE
Security of Formatter's encoding of local vs. remote content

### ISSUE THREAD

**Issue by EricR** [tootsuite/mastodon#1392]
The Formatter class's encoding of local and remote content is different. For example, the methods `format` and `simplified_format` both check if a piece of content is remote and call `reformat` if it is. This method calls Rails' sanitize method with a given whitelist of HTML tags and attributes (see https://github.com/tootsuite/mastodon/blob/master/app/lib/formatter.rb#L27). This is different than how local content is handled, which uses the htmlentities gem to encode the output and doesn't allow users to include any HTML (even whitelisted tags and attributes) in content.

I can understand why this was done, but the concern here is that it puts some amount of trust on the HTML returned from another Mastodon instance. For example, even with the given whitelist some form of UI redress attack could occur. Since div and a tags are allowed along with class and href attributes, a malicious user/instance could include an invisible clickable div (say, in their account note using the preexisting css class "modal-root__container") that takes up a large portion of the page and would redirect the user to a malicious page when clicked (think phishing, drive-by download, etc.).

Obviously this is a rather low severity security issue, but other client-side/XSS attack vectors may appear if this whitelist is ever changed, which may not be obvious due to the fact that `rubocop:disable Rails/OutputSafety` is used to disable output safety checks provided by rubocop.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
This is working as intended. Remote content comes HTML-formatted because of spec reasons. We sanitize it. Only a limited set of tags and attributes are allowed. Divs are not allowed, only p, span, br and a. I suppose something funky could be done with the CSS classes, so perhaps we should whitelist those, too? But other than that, it's intended.

**Comment by EricR** [comment]
Yeah, the CSS classes were the immediate thing I thought of as a way this
functionality could be abused. Again, it would require an instance
misbehaving by returning incorrect HTML, so pretty low risk. I'd recommend
whitelisting attribute values, along with the already whitelisted tags and
attributes, to have total control over what HTML is returned and actually
rendered from another instance.

**Comment by Gargron** [comment]
We are now using the sanitizer gem. With a very strict setup. I was confident of this approach before, but even more so now, e.g. we're not even allowing classes to be set on unexpected elements.
