### ISSUE TITLE
Easy cross-instance username copying/tagging/@ing

### ISSUE THREAD

**Issue by James-Firth** [tootsuite/mastodon#1393]
When I navigate or get linked to a user's profile and end up on a page like https://mastodon.cloud/@jamesfirth there is a display name (James) and the username (@jamesfirth).

However, if I'm from another instance and I want to talk to James, I must either take note of which instance they're from or use the auto-complete in the composition box.

The composition box seems to work fairly well so far in my experience, but I'm worried about scale.

What happens when there's over one hundred people who's names start with `@jam`? I feel at that scale the auto-complete will not work as well (unless I'm mistaken).

My feature request is that either:
* The username displayed on profile pages includes the entirety of the the username (pardon me if I have my terminology incorrect). ie `@jamesfirth@mastodon.cloud`
 OR
* Have the username be clickable, and upon clicking copy the entire username@instance (again pardon the potentially incorrect terminology here. Is there a term for that entire string?) to the clipboard.

Thoughts?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
>The username displayed on profile pages includes the entirety of the the username

Solved!
