### ISSUE TITLE
Direct message still says "Boost" in tooltip

### ISSUE THREAD

**Issue by James-Firth** [tootsuite/mastodon#1394]
Reproduction steps:
* Send Direct message
* View Direct message
* Hover over envelope Icon

Bug Result: "Boost" tooltip text should appear.

Expected Result:
Something like "Cannot boost a direct message"?
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by rtucker** [comment]
i believe this is fixed in at least one or more of the above commits; 1.3.2 does not exhibit this behavior.
