### ISSUE TITLE
Consider switching from elasticsearch to MeiliSearch

### ISSUE THREAD

**Issue by sphinxc0re** [tootsuite/mastodon#13943]
### Pitch

MeiliSearch has a much smaller memory footprint than elasticsearch. Also it doesn't require Java to run.

https://github.com/meilisearch/MeiliSearch

### Motivation

Smaller servers with slower hardware would benefit from this. It also might encourage more ppl to enable search.

**Comment by sphinxc0re** [comment]
What would it take to implement this? I don't really know enough about the current search story to start working on this (Nor do I have the time :sweat_smile: ).
Could I get a quick rundown of how ES is currently integrated into the platform?

**Comment by refi64** [comment]
I took a brief glance around, it seems like Mastodon uses Chewy, which is a higher level wrapper over ES. Not sure how much work it would be to swap out either ES or Chewy with something else (was initially looking at TypeSense).

**Comment by a-dows** [comment]
I recently had to disable full-text search on my under-30-user server because we could not afford the memory hit—ElasticSearch is just not feasible for budget servers. I would be in favor of any more lightweight solution!

**Comment by Gargron** [comment]
Sorry to disappoint but meilisearch does not do most of what we use in elasticsearch.

**Comment by andrewbanchich** [comment]
@Gargron What kinds of things do you use Elasticsearch for that are missing? If Meilisearch adds them in the future, it would be nice to revisit this.

**Comment by TheEssem** [comment]
Curious about this as well, it's been over 2 years since this was closed and Meilisearch has advanced a lot in that time. I've seen some other software that previously used Elasticsearch for similar purposes migrate to Meilisearch with few issues, maybe it's worth revisiting this?

**Comment by idc77** [comment]
Sounds like an excuse to me, "let's tell the plebs it doesn't have the features we require, so I can have "implemented Elasticsearch support in Mastodon" on my resume"

Yes I did.
