### ISSUE TITLE
show empty CWs

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#13945]
### Pitch

currently mastodon omits the CW feature entirely if the CW is empty. I'd like it to show empty CWs anyway.

### Motivation

I don't open emails with no subject, why should posts be any different?

**Comment by SuperSandro2000** [comment]
Your motivation is the exact opposite. If the CW is empty you wouldn't want to open it.

**Comment by SoniEx2** [comment]
I mean show the CW itself not the post.

**Comment by Cassolotl** [comment]
Related: *Prevent posting with CW toggled on but empty CW field #1174*
