### ISSUE TITLE
Error after updating Mastodon

### ISSUE THREAD

**Issue by ludovicchabant** [tootsuite/mastodon#1396]
This is probably more of a Rails problem than a Mastodon one, but I can't find any relevant information online so far...

I pulled the latest code from GitHub, `sudo su - mastodon`, and then `bundle install`:

```
<lots of gems>
Bundle complete! 74 Gemfile dependencies, 131 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into ./vendor/bundle.
```

Seems fine, but then, afer `RAILS_ENV=production bundle exec rails db:migrate`:

```
Could not find ox-2.4.11 in any of the sources
Run `bundle install` to install missing gems.
```

Weird. A `bundle show ox` seems to indicate it's correctly installed, though:

```
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/ox-2.4.11
```

I tried a bunch of stuff like `gem update ox` or reinstalling it but nothing worked.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by QuadPiece** [comment]
Also experiencing this. 

Tried deleting vendor/bundle and another `bundle install --deployment --without development test`

But to no avail. Issue persisted. `bundle install` output clearly says it installed ox, so did `bundle show`. But when trying to run DB migrations it still insists that it can't find ox-2.4.11

In the end I simply reverted to my backups to avoid further downtime.

**Comment by ludovicchabant** [comment]
Actually I hadn't tried completely deleting `vendor/bundle` are re-installing all the gems from scratch... I did that and it seems to have fixed it for me! _However_, in the meantime, while doing other stuff on the server, I realized my storage was near full capacity, so I also previously resized it to get more disk space... I'm not sure if it would be related, but that would sure be quite weird.

I'll leave the issue open for @QuadPiece but it's resolved on my server.

**Comment by QuadPiece** [comment]
I also managed to "fix" my issue.

"fix" meaning I just deleted the entire mastodon user and passed `--remove-all-files`. Then set it up from scratch, fetched the attachments and database from backups. And ran `db:migrate` instead of `db:setup`

Not sure if this issue should still be left open, but at least it's no longer valid for me either.

**Comment by ashfurrow** [comment]
Yikes, sorry you two had problems. It sounds like you both got things resolved, so I'm going to close this issue. Please let us know if it hasn't been resolved to your satisfaction. Thanks for following up with your solutions, too!
