### ISSUE TITLE
Resizing browser window while choosing a picture for a toot prevent adding it.

### ISSUE THREAD

**Issue by alpheb** [tootsuite/mastodon#1400]
How to reproduce:
* Set browser window size to full-screen (4 columns layout)
* Start adding a picture...
* The browser file chooser appear
* Resize browser down to the 1 column layout
* Choose a file in the browser file-chooser
* The chosen file doesn't appear in the toot

Expected result :
* The chosen file appear in the toot

Tested with :
* Firefox 52.0.1 (64 bits) Linux
* Google Chrome Version 57.0.2987.110 (64-bit) Linux

This (unusual) behaviour happens every time with a tiling window manager.

I guess that the responsive code delete the "composing toot" stuff and lose the link with the file chooser (?)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ticky** [comment]
Ah, I suspect this is actually because you end up interacting with two different compose views, one of which is being destroyed when the browser resizes.

I believe a good fix for this will also fix #1411.

**Comment by Gargron** [comment]
Yeah @ticky is absolutely right. I don't have a solution to this. Single-column and multi-column are different layouts.

**Comment by ticky** [comment]
This is probably fixable, but it requires working outside of the router a bit. It’s probably worth the effort, though!
