### ISSUE TITLE
Page styling fails after upgrade to v3.1.4

### ISSUE THREAD

**Issue by theauditor** [tootsuite/mastodon#14005]
My personal mastodon instance is causing the avatar images to be spread out through the toots area within the stream.
This happened after I completed upgrade to v3.1.4
I am unable to figure out why this has happened.

issue can be seen at https://blaisemcrowly.com/@blaise

Note: Due to a ssh copy issue while moving servers I had lost the entire /home/mastodon/live/public/system/media_attachments forder contents.  how ever I do not understand how this may have caused this issue.

**Comment by Sasha-Sorokin** [comment]
On blaisemcrowly.com, revision of `statuses.scss` is corresponding to [`b851456`](https://github.com/tootsuite/mastodon/blob/b8514561394767a10d3cf40132ada24d938c1680/app/javascript/styles/mastodon/statuses.scss) (actual is [`4850338`](https://github.com/tootsuite/mastodon/blob/v3.1.4/app/javascript/styles/mastodon/statuses.scss)).

Either something to deal with not up-to-date source files or build cache.

**Comment by theauditor** [comment]
Ok, so I tried to figure out if the file with me is an older version.
Got this.
`mastodon@Superdark:~/live$ git  log   -- '**/statuses.scss'
commit 48503384d00525fe61a038bdb8a55868fdc1db92
Author: ThibG <thib@sitedethib.com>
Date:   Wed May 13 21:20:34 2020 +0200

    Fix some account avatars on public pages having incorrect size (#13692)
    
    * Fix some account avatars on public pages having incorrect size
    
    * Remove outdated and overridden width and height attributes
    
    * Remove more hardcoded width/height attributes

commit 0e362b7678e75cb71ce207fd45dd4dc0d955fdca
Author: ThibG <thib@sitedethib.com>
Date:   Tue Apr 28 10:16:55 2020 +0200

    Fix end-user-facing uses of inline CSS (#13438)
    
    * Move some inline styles to CSS files
    
    * Move default_account_display_name span to fix useless tags with duplicate id
    
    * Change handling of public pages spoiler text from inline CSS to dataset attribute
    
    * Use the `dir` HTML attribute instead of inline CSS
    
    * Move status action bar inline CSS to CSS file
    
    * Hide logo resources from CSS file, not inline CSS
    
    Fixes #11601
    
    * Move translation prompt styling from inline CSS to CSS file
    
    * Move “invited by” styling on registration form from inline to CSS file
    
    * Use the progress tag to display poll results in JS fallback
    
    * Fix poll results JS-less fallback when the user has voted for an option
`

So it seems like the file is up to date and the checkout went well.
So should be a build cache issue right? is there any way I could flush the cache and rebuild to fix this?

**Comment by ThibG** [comment]
You may have forgotten to run `bundle exec rails assets:precompile`, or it may have failed without you noticing. Also make sure to reload `mastodon-web` once the assets are precompiled.

If `bundle exec rails assets:precompile` claims there's no work to do but the assets are still outdated, you may need to run `bundle exec rails assets:clobber` before retrying.

**Comment by theauditor** [comment]
Well, that fixed it. 
Ran
```
bundle exec rails assets:clobber
bundle exec rails assets:precompile
```

and then restarted all services.
Apparently a memory limitation was causing the build to fail which I did not notice the first time. The next time on it said no work to be done just like you said.

Thank you.
