### ISSUE TITLE
Add the Instance API Version in GET /api/v1/instance

### ISSUE THREAD

**Issue by Solido** [tootsuite/mastodon#1401]
When writing a client you need to know what are the abilities of an Instance.
All instances will not update to the last update automatically so we need to know what version is in place.

GET api/v1/instance is the first call we make and can offer instance specifications, options/plugins infos.

Ex: Build 1.1.1 is available with public URI, don't know which one are up to date.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

I saw API versioning not instance deployment version

**Comment by ashfurrow** [comment]
Now that https://github.com/tootsuite/mastodon/pull/2181 is merged, I believe this should be resolved. The version should be specified in the upcoming Mastodon release. I'm going to close this issue, but if it's not been resolved to your satisfaction, please just let us know 👍
