### ISSUE TITLE
Timeline Jumping When Pictures Expanded

### ISSUE THREAD

**Issue by wolfpurplemoon** [tootsuite/mastodon#14018]
### Expected behaviour

Usually I would expand a picture in a toot and the toot would remain in the same position on the timeline

### Actual behaviour

When I click back to the timeline after expanding a picture, the column jumps and the toot with the picture in moves to the bottom

![GIF of the issue](https://user-images.githubusercontent.com/10601382/84207732-f4b63c00-aaa9-11ea-9b9b-4437522bee9b.gif)

### Steps to reproduce the problem

Open a picture from a toot that is in middle of the home timeline column and click a picture and then click away from the picture to return to the timeline

### Specifications

Mastodon 3.1.3 on Firefox 77.0.1

**Comment by Sasha-Sorokin** [comment]
Can reproduce with Firefox 77.0 on Mastodon v3.1.4. Chrome unaffected.

Related issues: #13470. Possibly the same area of fix as with PR #13574.

**Comment by ThibG** [comment]
I can reproduce it, but not consistently… I guess “preventScroll” whould work there too, but I'm not sure how to test it since the issue doesn't appear consistent.

**Comment by wolfpurplemoon** [comment]
this is still happening

**Comment by Gargron** [comment]
Where are you checking it?

**Comment by Sasha-Sorokin** [comment]
@wolfpurplemoon I'm not sure your instance yet picked up on this change — queer.party is only 3.1.5 (which only contained a few security fixes). The change itself did not make it in any release yet (except 3.2.0 candidate). Wait for 3.2.0 to check :)

I seem to unable to reproduce this anymore on mastodon.social, but it is relatively up-to-date with `master` (iirc).

**Comment by Maffsie** [comment]
I backported the patch resolving this issue on queer.party (commit https://git.maff.scot/maff/queer.party/commit/07f76378ea85dd7971eeb1c9bc5e663694e339de) and have redeployed, so it should be fixed. @wolfpurplemoon let me know if it's still happening after a ctrl-F5 refresh!
