### ISSUE TITLE
cursor: default in statuses

### ISSUE THREAD

**Issue by lf94** [tootsuite/mastodon#14025]
### Expected behaviour

I should see a caret when hovering over text in a status.

### Actual behaviour

The default pointer is being used instead.

### Steps to reproduce the problem

Go to any user profile, https://mastodon.online/@somename,  and hover over their status text.

### Specifications

FF 76.0.1 on Debian Buster

https://github.com/tootsuite/mastodon/blob/8e96510b2528056e84cf8d0ed68d2e686e566180/app/javascript/styles/mastodon/components.scss#L995

Shows where it's happening.

Should be a quick fix!

**Comment by Gargron** [comment]
Intended to help users discover you can click to open the status.

**Comment by lf94** [comment]
Why not use `cursor: pointer`, intended to signal a piece of content is clickable?

**Comment by Sasha-Sorokin** [comment]
I perfectly agree with @lf94, in public profiles text in statuses isn't clickable, only permalink, display name and images are, therefore it makes sense to use `cursor: text` for text and `cursor: pointer` for images, or otherwise make status box to open the thread view.

**Comment by lf94** [comment]
Ah yeah, there's that too. @Gargron ?

**Comment by arielrodrigues** [comment]
I completely agree with @Sasha-Sorokin and @lf94, I also would love to get this as my first issue (:

**Comment by lf94** [comment]
@arielrodrigues you can probably just open a PR with the fix. :slightly_smiling_face:

**Comment by Gargron** [comment]
> 
> 
> I completely agree with @Sasha-Sorokin and @lf94, I also would love to get this as my first issue (:

It's a one-line fix, feel free to do it if you want.

**Comment by lf94** [comment]
Resolved. Closing.
