### ISSUE TITLE
wikipedia incorrect information regarding popularity

### ISSUE THREAD

**Issue by ikt** [tootsuite/mastodon#14029]
https://en.wikipedia.org/wiki/Mastodon_(software)

Gab, a controversial social network with a far-right user base, changed its software platform to a fork of Mastodon and became the largest Mastodon node in July 2019.[38]

Links to: https://www.vice.com/en_us/article/mb8y3x/the-nazi-free-alternative-to-twitter-is-now-home-to-the-biggest-far-right-social-network

But that's not accurate: https://www.splcenter.org/hatewatch/2019/02/14/no-way-gab-has-800000-users-web-host-says

Can someone fix this please?

**Comment by Sasha-Sorokin** [comment]
This is unrelated to Mastodon, actually, and [anyone can contribute](https://en.wikipedia.org/wiki/Wikipedia:Be_bold) to Wikipedia. If you think the link you provided is WP:RS, then go for it and [edit it in](https://en.wikipedia.org/w/index.php?title=Mastodon_(software)&action=edit), adding a reference. I'm not sure about Wikipedians stance on conflicting lines, such as “though Gab's hosting provider disproves this claim”, but this can be used to stay neutral.

**Comment by ikt** [comment]
> This is unrelated to Mastodon, actually, and [anyone can contribute](https://en.wikipedia.org/wiki/Wikipedia:Be_bold) to Wikipedia. If you think the link you provided is WP:RS, then go for it and [edit it in](https://en.wikipedia.org/w/index.php?title=Mastodon_(software)&action=edit), adding a reference. I'm not sure about Wikipedians stance on conflicting lines, such as “though Gab's hosting provider disproves this claim”, but this can be used to stay neutral.

Hello, I'm not that bad at computers aha 

Not everyone can edit Wikipedia, in my case it doesn't like my vpn:

![Screenshot_20200628-014538](https://user-images.githubusercontent.com/578520/85926215-31bf6280-b8e1-11ea-9a5b-ab8e14f1ef3e.png)

That's why I opened this issue

Thanks!

**Comment by ryliejamesthomas** [comment]
I've made a note on the talk page.

https://en.wikipedia.org/wiki/Talk:Mastodon_(software)#Size_of_Gab_'node'_is_falsified

**Comment by anjum-ahmed** [comment]
Done
