### ISSUE TITLE
Doesn't seem to work with production mode on DigitalOcean

### ISSUE THREAD

**Issue by owlg** [tootsuite/mastodon#1402]
[I've been working on setting up this project for a long time. When I tried to run it, following the Production Readme on this repository, I cannot get it working on port 3000, neither can I use NGINX to route the traffic on port 80. Is there a more detailed tutorial on the NGINX part?].

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by matunixe** [comment]
Hello, I run https://unixcorn.xyz on DigitalOcean. Everything works fine, could ya share some more infos?

**Comment by owlg** [comment]
I followed this link's instructions diligently. https://github.com/tootsuite/mastodon/blob/master/docs/Running-Mastodon/Production-guide.md
Even before setting Nginx up, I tried to access the webpage with http://[my-ip-address]:3000 after using 
sudo systemctl enable /etc/systemd/system/mastodon-*.service and sudo systemctl start mastodon-web.service mastodon-sidekiq.service mastodon-streaming.service
(without cron jobs etc.)
The server only returns connection refused. With CloudFlare, it returns a server down page. 

Nginx seems to be working as the default page shows up before I removed the default config in NGINX sites-enabled/ and replaced with the NGINX configuration file provided on the tutorial page. (mastodon_nginx.conf)

What am I doing wrong?

**Comment by dunn** [comment]
Are you running a firewall?

**Comment by dunn** [comment]
> can I use NGINX to route the traffic on port 80

Mastodon requires HTTPS, also.

**Comment by raymestalez** [comment]
Hi there! I wrote a quick guide, I hope it helps:

http://digitalmind.io/post/deploying-mastodon-on-digital-ocean

Let me know if you have any questions, I'll try to help!

**Comment by CatLover91** [comment]
I am dealing with the same issue on Linode; I do not think this is a vps provider specific issue. I followed the production guide directly (using all recommended configurations) and am dealing with 502 bad gateway. 

I am running Ubuntu 17.04 with nginx.
I installed Node through nvm, and ruby through rbenv.
I am not using docker.
Certbot is installed and running, https resolves to mastodon instance but hits the 502.

Currently my streaming service is failing and I am trying to work my way through debugging
```
$ sudo systemctl status mastodon-*.service
● mastodon-web.service - mastodon-web
   Loaded: loaded (/etc/systemd/system/mastodon-web.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-04-13 16:03:25 UTC; 1s ago
 Main PID: 19760 (bundle)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/mastodon-web.service
           └─19760 puma 3.8.2 (tcp://0.0.0.0:3000) [live]

Apr 13 16:03:25 ubuntu systemd[1]: mastodon-web.service: Service hold-off time over, scheduling restart.
Apr 13 16:03:25 ubuntu systemd[1]: Stopped mastodon-web.
Apr 13 16:03:25 ubuntu systemd[1]: Started mastodon-web.
Apr 13 16:03:26 ubuntu bundle[19760]: [19760] Puma starting in cluster mode...
Apr 13 16:03:26 ubuntu bundle[19760]: [19760] * Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
Apr 13 16:03:26 ubuntu bundle[19760]: [19760] * Min threads: 5, max threads: 5
Apr 13 16:03:26 ubuntu bundle[19760]: [19760] * Environment: production
Apr 13 16:03:26 ubuntu bundle[19760]: [19760] * Process workers: 2
Apr 13 16:03:26 ubuntu bundle[19760]: [19760] * Preloading application

● mastodon-sidekiq.service - mastodon-sidekiq
   Loaded: loaded (/etc/systemd/system/mastodon-sidekiq.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-04-13 16:03:24 UTC; 2s ago
 Main PID: 19745 (bundle)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/mastodon-sidekiq.service
           └─19745 /home/mastodon/live/vendor/bundle/ruby/2.4.0/bin/sidekiq -c 5 -q default -q mailers -q pull -q push

Apr 13 16:03:24 ubuntu systemd[1]: mastodon-sidekiq.service: Service hold-off time over, scheduling restart.
Apr 13 16:03:24 ubuntu systemd[1]: Stopped mastodon-sidekiq.
Apr 13 16:03:24 ubuntu systemd[1]: Started mastodon-sidekiq.
```

**Comment by dunn** [comment]
@CatLover91 should be more output in `journalctl -x -u mastodon-web` etc.

**Comment by CatLover91** [comment]
@dunn  when I checked journalctl i found that node was misinstalled. Seeing as how I had gone through nvm installation and uninstallation (both on mastadon user and sadly root user) I didn't want to risk messing it up further and went through a full reinstall.

I no longer have this issue, and my instance is running fine.

What caused this issue for me: improper nodejs installation messing up install later along install

What fixed it: Full OS/dependency/server reinstall following the installation directions very literally.

**Comment by ashfurrow** [comment]
@owlg did you ever figure this out?

**Comment by CatLover91** [comment]
@ashfurrow I suggest closing this issue, [it looks like the user's issue is solved and their instance is running.](https://github.com/tootsuite/documentation/commit/cecd9ff8cf2ede4b57f082ad894133b3c24b5ee7)

**Comment by ashfurrow** [comment]
Cool cool. I don't have rights to close issues though. Pinging @wxcafe

**Comment by aral** [comment]
Hmm, I’m getting the same errors on my latest installation.

**Comment by dunn** [comment]
@aral does adding `-x` give any more output?

**Comment by aral** [comment]
@dunn Aha, with that, I get this:

```
…
Jun 15 15:39:23 d25 systemd[15196]: mastodon-web.service: Failed at step USER spawning /home/ubuntu/.rbenv/shims/bundle: No such process
…
```

**Comment by dunn** [comment]
I forget if I ever got that error, but at some point I switched my `*.service` files to do
```
ExecStart=/bin/bash -lc 'bundle exec puma -C config/puma.rb'
```
instead of 
```
ExecStart=/home/mastodon/.rbenv/shims/bundle exec puma -C config/puma.rb
```
etc.  So that might be worth trying.
https://github.com/dunn/ansible-mastodon/blob/master/roles/mastodon/templates/mastodon-web.service.j2#L13

**Comment by aral** [comment]
OK, I see the problem – *doh* – I hadn’t updated the user in the .service files. It was still set as mastodon. 🤦‍♂️

```
[Service]
Type=simple
User=mastodon
```
