### ISSUE TITLE
Bundler::GemNotFound: Could not find e2mmap-0.1.0.gem for installation

### ISSUE THREAD

**Issue by hackerncoder** [tootsuite/mastodon#14024]
### Expected behaviour
bundle install --force should finish without errors

### Actual behaviour
All gems are installed until e2mmap which fails with:

`Bundler::GemNotFound: Could not find e2mmap-0.1.0.gem for installation`
`An error occurred while installing e2mmap (0.1.0), and Bundler cannot continue.`
`Make sure that "gem install e2mmap -v '0.1.0' --source 'https://rubygems.org/'" succeeds before bundling.`

### Steps to reproduce the problem

I had been trying to update my mastodon instance, running:
`RAILS_ENV=production bundle exec rails assets:precompile`
But for some reason it failed, could not find libprotobuf.so.17.

So I tried reinstalling the required packages, and sure enough there were some packages that were missing.

I still had a problem and read you were supposed to bundle install --force (Sorry, I don't know what the exact problem was and where I read it). This is where it failed.

### Specifications

commit b1484cf3ceebe1f1f083e4c06872493dc0a68511

OS: Debian. Testing (bullseye)

**Comment by hackerncoder** [comment]
All gems are supposed to be installed in _mastodonFolder_/vendor/bundle/ruby/_version_/gems/ correct?

Because if so, then I know the problem is that e2mmap is missing from there.

**Comment by resynth1943** [comment]
Try running:

```
gem install e2mmap -v '0.1.0' --source 'https://rubygems.org/'
```

**Comment by hackerncoder** [comment]
Already done.
Same output.

**Comment by hackerncoder** [comment]
Found the `bundle install --reinstall`: https://github.com/tootsuite/mastodon/issues/12081

**Comment by ThibG** [comment]
@hackerncoder did that fix it for you or do you still have this issue?

**Comment by hackerncoder** [comment]
@ThibG I reinstalled mastodon and it worked.
