### ISSUE TITLE
README.md has misleading Node.js version requirement

### ISSUE THREAD

**Issue by ckolodjski** [tootsuite/mastodon#14089]
The README specifies the following version requirements:
```md
Requirements:

    PostgreSQL 9.5+
    Redis 4+
    Ruby 2.5+
    Node.js 10.13+
```
However, the Node.js version must also be below 13, as seen below.
```
$ yarn install --pure-lockfile
yarn install v1.22.4
[1/6] Validating package.json...
error @tootsuite/mastodon@: The engine "node" is incompatible with this module. Expected version ">=10.13 <13". Got "14.3.0"
```
README.md should be edited to correctly display the acceptable range of Node.js versions.

**Comment by Gargron** [comment]
I honestly don't know why we even set an upper bound.

**Comment by angristan** [comment]
The upper bound seems to have been introduced in https://github.com/tootsuite/mastodon/pull/9166 and they subsequently bumped for each node version update in the README.
