### ISSUE TITLE
Bug: Compose Toot Pane hidden in Chrome 83

### ISSUE THREAD

**Issue by tychi-nflx** [tootsuite/mastodon#14121]
### Expected behaviour
Toot sidebar should be visible

### Actual behaviour
Toot sidebar is not visible

### Steps to reproduce the problem
Loaded both fosstodon.org and mastodon.social in Google Chrome. Issue is not present in Firefox.

gif of issue, with possible lead on solution:
![compose-error](https://user-images.githubusercontent.com/38667080/85335025-28716880-b491-11ea-8309-fe1fbfdf2b80.gif)

### Specifications

Google Chrome
Version 83.0.4103.106 (Official Build) (64-bit)

 Mac OSX 10.15.5

**Comment by Sasha-Sorokin** [comment]
Are you sure you don't have flag “Experimental Web Platform features” enabled at `chrome://flags`? It is called experimental for a reason.

Unable to reproduce on Chromium (Linux) with version 83.0.4103.97, neither on 85.0.4153.0.

**Comment by tychi-nflx** [comment]
@Sasha-Sorokin Thanks! I did have “Experimental Web Platform features” enabled, after disabling the feature the issue went away. Any insight into which feature would be causing the layout to break like that?

I'm generally pretty adept at CSS related things and that one left me stumped.

**Comment by Sasha-Sorokin** [comment]
Sorry, @tychi-nflx, I have no clue what causes this, must be a regression of some sort. You can report this issue on Chromium's issue tracker and they may triage it, and check which version caused it — folks out there seem to be pretty responsible.
