### ISSUE TITLE
Detection of incomplete loading of assets

### ISSUE THREAD

**Issue by SkyLined** [tootsuite/mastodon#1413]
When a user attempts to access mastodon.social, the main HTML page loads fine but when it attempts to load JavaScript, CSS and other resources from assets.mastodon.social, Cloudflare can return a HTML Captcha page instead if it decides the IP address you are using is suspect. Obviously, the page does not expect to get HTML instead of Javascript or CSS and fails to load. There is no error, the Capcha is never shown to the user, and the webpage remains blank: they user is completely unable to use the service.

This can happen when you are using TOR or any other form of proxy or VPN that causes you to share an IP address with many other users; some of these users may not play nice, causing Cloudflare to mark the source IP as suspect and requiring a Capcha to access any resource over HTTP.

This seems to suggest that mastodon.social is not behind Cloudflare protection, whereas assets.mastodon.social is, and that the problem could be solved by either putting everything on, or removing everything from Cloudflare, such that the Capcha is either shown immediately when the user opens the main page, or no Capcha's are shown ever.

A work around that solves the issue for me is to open "https://assets.mastodon.social" first in order to get the Cloudflare Capcha, complete it, and then load "https://mastodon.social".

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
This is a bug with a single instance of mastodon, not with the software itself. Therefore, I'm marking it as invalid, but still paging @Gargron.

**Comment by raisedadead** [comment]
Just an insight, this may not have to do with an instance or the software at all. Cloudflare can trigger false positives as correctly analyzed in the OP.

We have faced this on one of other platforms that I work on and only real world solution is to let user's know that they might have to move away from shady ISPs and networks, that trigger the captchas in the first place.

That sounds a bit smart ass, but trust me, the user would see this on most sites covered by Cloudflare protection.

**Comment by wxcafe** [comment]
I mean, yeah, but it's still not a problem with mastodon-the-software and rather with cloudflare/how admins configure their instances.

**Comment by SkyLined** [comment]
@raisedadead not sure I agree that TOR is a shady network, but would love to hear what alternative you would suggest people move to that offers the same anonymity and does not have this problem.

@wxcafe you are right, but I think I would like to split this report into two issues:
1) the specific instance (mastodon.social) is not configured correctly, which I should file there if I could only find out how.
2) the software does not detect the errors nor does it handle them gracefully. The software could try to detect if all scripts/CSS have loaded as expected and, if not, show an error and/or report back to the server. One might consider this a feature request, rather than a bug report. I'll leave that to you

**Comment by wxcafe** [comment]
Users on TOR should definitely be able to access Mastodon, imo. It's apparently pretty easy to disable captchas for users from TOR afaik (I've never used cloudlfare but I've been around TOR devs and remember the whole drama from march 2016): see the bottom of https://blog.cloudflare.com/the-trouble-with-tor/. Detecting when assets don't load and failing gracefully would be pretty handy too yeah.

**Comment by raisedadead** [comment]
@SkyLined My apologies, for the interpretation, what I meant was that as correctly noted in the OP is that some networks may result in the captcha's being thrown off.

And IMHO this is beyond the responsibility of mastodon-software as well as the instance.

That said, if the instance owners still want, they would have to check the below approach. I highly encourage **NOT** to do this, below the default settings.

Cloudflare's firewall settings have this which can be tuned:

![2017-04-11 11 38 04](https://cloud.githubusercontent.com/assets/1884376/24895011/a0a7c9a4-1eab-11e7-8748-a09ee95c9c35.gif)

or alternatively turn down the duration before captcha is shown again on the same page.

**Comment by raisedadead** [comment]
We have been able to put off most DDoS thanks to having set these at least to the defaults.

**Comment by Gargron** [comment]
This is a mastodon.social deployment issue, not Mastodon itself.
