### ISSUE TITLE
Interaction with GNU social: Link preview

### ISSUE THREAD

**Issue by hybris42** [tootsuite/mastodon#1414]
Links previews shown on GNU social timelines are not displayed in mastodon.

Basic exemple: https://social.undernet.uy/9gag :)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Pajn** [comment]
If you open the thread by clicking on the toot you will see a preview.
Personally I like that the preview isn't shown in the list, it keeps it clean.

**Comment by hybris42** [comment]
No, it's not shown either in the list (which is fine !) and when clicked (both on my private instance and mastodon.xyz)

**Comment by mkody** [comment]
Do you mean something like this?
![image](https://cloud.githubusercontent.com/assets/843787/24868694/21ddebc0-1e11-11e7-8bc6-f31158b0d521.png)

This was implemented from this issue: #463

**Comment by hybris42** [comment]
Yes, something like this but for GNU social subscription like https://social.undernet.uy/9gag

**Comment by Gargron** [comment]
Previews are generated from either OEmbed or OpenGraph tags, whichever are available on the linked page.
