### ISSUE TITLE
Never be logged out

### ISSUE THREAD

**Issue by penloy** [tootsuite/mastodon#14141]
### Pitch

Add the option to never be automatically logged out when opening mastodon in a new tab/session.

### Motivation

It's frustrating having to log in constantly on a secure machine that only I use.

**Comment by Gargron** [comment]
Mastodon already has the "remember me" option on by default. You're not logged out for a year.

**Comment by penloy** [comment]
Really? I looked all through the account settings etc, and I can't see this option on the login screen either. Am I doing something wrong?
![rememberme](https://user-images.githubusercontent.com/25794029/85888922-6e586480-b7e2-11ea-8cc9-4111fcb57a35.png)

**Comment by Gargron** [comment]
It's not an option it's always on.

**Comment by penloy** [comment]
Ah, it's working now. Wasn't yesterday. It was probably some weird thing that was happening on my end. Thanks.
