### ISSUE TITLE
Links in profile wrongly truncate www. in some cases

### ISSUE THREAD

**Issue by revk** [tootsuite/mastodon#14153]
### Expected behaviour

My profile has a link to my blog that is https://www.me.uk/
In case this does not show properly here: h t t p s : / / w w w . m e . uk /

I'd expect the profile to show a link www.me.uk

### Actual behaviour

It shows a tick and just me.uk/ having dropped the www. prefix.

My web site is not me.uk, I don't own me.uk, I own www.me.uk

### Steps to reproduce the problem

Make a link to any web site where www is actually part of the domain and not a hostname within it. E.g. www.me.uk

### Specifications

Not actually sure how to tell - built from source yesterday

Safari, but I don't think it matters.

**Comment by Gargron** [comment]
It’s a visual truncation. The link is still correct.

**Comment by revk** [comment]
Err, yes, but it is visually WRONG!

Whilst if I owned www. someispdomain.com and you truncated to someispdomain.com that would be fine, both work, both are mine and both got to the same web site.

However, truncating www.me.uk implies that the link me.uk is somehow valid and that I own me.uk somehow, which I DO NOT.

So it is wrong.

**Comment by SuperSandro2000** [comment]
The www subdomain is a relict from the past and more and more software drop it. One of the biggest examples is Chrome. So you have a general problem and not only one with mastodon. Just use https://www.revk.uk/ instead.

**Comment by revk** [comment]
Yes, a common problem, but none the less WRONG in this instance. Why should I not use my domain www.me.uk. Is this some sort of domain prejudice?

**Comment by creideiki** [comment]
Mastodon should be correct even if other software is making an effort to be wrong. The hostname `www` is not special in DNS, and there is no guarantee that any records on it have anything to do with any such records on the domain itself. Instead of "a relict from the past", I prefer to see it as "caring that the Internet is more than the web".

**Comment by revk** [comment]
Thanks, so why not show the link as typed. If I have a domain like https://revk.uk/ find, show revk.uk, but if I type https://www.revk.uk/ then show www.revk.uk, and the same if I type https://www.me.uk/ show www.me.uk.
Why mess with it if www is a relic?

**Comment by Gargron** [comment]
In the vast majority of cases www is an alias and incredibly common in hyperlinks. It helps noone to see www a million times when it makes no difference. Your case is an edge case and I’m sorry but i don’t believe there’s any reason to accommodate it given that the link takes you to the correct page.

**Comment by revk** [comment]
The people can put in links without the www, can't they.
It is simply wrong to imply I own me.uk as I don't.
There is nothing special about www. prefix, and if seeing it a lot, why not drop the .com of the end, as we also see that a lot, it is the same logic, surely?

**Comment by revk** [comment]
Just to be clear, even if not in my "special" case, it is wrong to assume that www.example.com is the same as example.com, they are different links and could, if they chose to, have totally different content. In my case me.uk is not even valid as a web site, but if it was it would have nothing to do with me. It seems odd to assume that www. prefix is special and not actually intended if types, given that someone can type a link without it if that is what they intend.

**Comment by SuperSandro2000** [comment]
> It is simply wrong to imply I own me.uk as I don't.

The fastest way to solve that is to use your redirected domain.

Also this does not imply that you won the domain. I can link anything I want there.

> There is nothing special about www. prefix

There is. 99% of all websites redirect it to their domain and treat it as the same.

> it is wrong to assume that www.example.com is the same as example.com

Not entirely if it is true for most websites.

> why not drop the .com of the end, as we also see that a lot, it is the same logic, surely?

You can't drop the tld.

**Comment by revk** [comment]
"You can't drop the tld." well, given the earlier argument, you can if it is just visual and the "link works".

Seriously, why change what is typed. If someone wants to type www.example.com why the hell not show what they actually typed. If, as is indeed common, that is the same as example.com, then they have the option to type example.com if that is what they what to show.

This is about what *I* want to show on *MY* profile. So why would you take away the choice for me to show what I want?

Even if 99% of sites are the same with www and without, why say to the 1% that are not that they are not allowed to show the link as they actually want and is actually correct?

This is deliberately removing choice and (even if only in 1% of case) showing something that is wrong.

I'd be happy if the input box suggested "do not include www. if not necessary" as a prompt, even a warning popup.

**Comment by SuperSandro2000** [comment]
> Seriously, why change what is typed.

https is also dropped because it clutters the ui.

> So why would you take away the choice for me to show what I want?

If you want it so much do a PR with it.

> This is deliberately removing choice

Not really. If we would blacklist domains like instagram does it we would remove choice. Profiles are limited in design and will always be like that or people could break the entire page easily.

> I'd be happy if the input box suggested "do not include www. if not necessary" as a prompt, even a warning popup.

This is just feature creep and clutters the UI with really not to useful features.

**Comment by revk** [comment]
Every website does have http(s):// and so I see the "reduce clutter" for that to some extent, but it is not true that every web site has www, or that www is "special" or that the www prefix is the same as without the www prefix.

Simple as that.

It is only "clutter" to show the www typed if someone actually bothers to type it, and it is clutter on their profile if they do. If they don't want clutter they can choose not to type it.

**Comment by nightpool** [comment]
is me.uk on the public suffix list? that's the way browsers solve this
problem. we could consider adding the public suffix list to mastodon,
although that might complicate the code more then it's worth

**Comment by revk** [comment]
Hi, what's the public suffix list - if there is a way to sort this so that me.uk is not treated as my domain that would help.
UK Nominet sell domains under .me.uk, .co.uk, .org.uk, (and also .uk directly).

**Comment by SuperSandro2000** [comment]
> Every website does have http(s):// and so I see the "reduce clutter" for that to some extent

There is also dat://.

> the www prefix is the same as without the www prefix.

This is true for 99% of the websites. Also this is only a display issue. Nothing is actually broken.

> although that might complicate the code more then it's worth

Depends on how we do it. If we use a gem we could upstream this isssue. Fixing it this way is the proper approach.

**Comment by SuperSandro2000** [comment]
This is the offendling line https://github.com/tootsuite/mastodon/blob/a64973aecff0595bd34a6e70393d471b8dbf1841/app/lib/formatter.rb#L291 and I found this gem which solves the problem https://simonecarletti.com/code/publicsuffix-ruby/. Going to do a PR with it cause it probably solves a bunch of other edge cases.

**Comment by SuperSandro2000** [comment]
I created #14156 to solve this problem.

**Comment by revk** [comment]
Thank you. Twitter did the same, but the chance of getting that fixed was very close to zero. So, very impressive. Good solution.

**Comment by SuperSandro2000** [comment]
Except that it does not reliable work and I know no good solution to get it working without refactoring large parts of good.
