### ISSUE TITLE
"Crop images to 16x9" setting not working

### ISSUE THREAD

**Issue by umonaca** [tootsuite/mastodon#14188]
### Expected behaviour

When "Crop images in non-expanded toots to 16x9" is **unchecked**, the images should always show in full size.

### Actual behaviour

Sometimes it shows pics in full size, sometimes it does not.

The ones that does not:
![image](https://user-images.githubusercontent.com/53662960/86117940-ee5e2300-ba9d-11ea-8cfd-8ffbc8b79764.png)

The ones that show in full size:
![image](https://user-images.githubusercontent.com/53662960/86117976-ff0e9900-ba9d-11ea-82e3-3f7bb4450448.png)

These two examples are in Gargron@mastodon.social's profile, showing on mastodon.social.

### Steps to reproduce the problem

On mastodon.social, **uncheck** "Crop images in non-expanded toots to 16x9". Save the settings. 

Open [Gargron's profile](https://mastodon.social/web/accounts/1), then you will see the examples as showing above.

### Specifications

mastodon.social and other servers using the master branch, as of commit ce9ae9aa50cab4de4db5c06f54f4f95d736d68c6

Browser: Firefox 78.0 and Chrome 83.0

**Comment by Sasha-Sorokin** [comment]
It is already reported at #14146?

**Comment by umonaca** [comment]
Not exactly the same. The example images above are all "images from some other servers" but the results are different.

**Comment by umonaca** [comment]
Agree. Will copy the details to that issue.
