### ISSUE TITLE
RSS/Atom feed link missing in "web interface" mode

### ISSUE THREAD

**Issue by Krinkle** [tootsuite/mastodon#14183]
### Pitch

Add an RSS/Atom feed link to the HTML output of profiles pages in Mastodon's "web interface" mode.

### Motivation

As someone relatively new to Mastodon, I thought for a long time that it did not support RSS feeds. The reason for this is that when you are browsing in the "web interface" mode of Mastodon, there is are no feed links in the HTML source.

Shortly after creating my profile on mastodon.technology, I got to <https://mastodon.technology/web/accounts/259460>, where I looked for an RSS feed but did not fine one. As such, I assumed this wasn't supported and didn't consider looking for it at other times, and was not able to answer "Yes" if people asked me about it.

Much later I realised that the view of profiles one sees on other instances, or locally if you click the "right" way, does in fact have it, e.g. at <https://mastodon.technology/@krinkle/>.

**Comment by Krinkle** [comment]
I suppose this ties in to some extent with a larger question of what this "Web" mode is, and why it exists. I don't mean to offend anyone with that question, but I want to note that as a beginner this was and still is confusing to me.

For example, adding an endorsed profile link seems to require use of the web interface, but it's not clear how one gets there, or why that only works when logged-in. I also can't tell then whether it is intentional or not that one is only able to endorse instance-local users (given I can't enter the web interface mode on other instances to access the button to add it).

**Comment by SuperSandro2000** [comment]
There is already a reference to it in the html ``



<link href='https://mastodon.example.com/@sandro.rss' rel='alternate' type='application/rss+xml'>
 

``

You want a visual thing like a button for that?

**Comment by ThibG** [comment]
@SuperSandro2000 if I understood correctly, what this report is about is the react Web UI (as opposed to the public page profiles) do not feature the RSS feeds in any way.

But the react Web UI is a single-page app, I am not sure changing the `type='alternate'` links dynamically makes sense and would be picked up by browser (extensions) that show the existence of such feeds.



> For example, adding an endorsed profile link seems to require use of the web interface, but it's not clear how one gets there, or one can only use that when logged-in. I also can't tell whether it is intentional or not that one is only able to endorse instance-local users (given I can't enter the web interface mode on other instances).

Ok, I am very confused by this. You can definitely endorse users from other instances, and I don't know what makes you think otherwise.

**Comment by Krinkle** [comment]
> if I understood correctly, what this report is about is the react Web UI […]
> 
> But the react Web UI is a single-page app, I am not sure changing the `type='alternate'` links dynamically makes sense and would be picked up by browser (extensions) that show the existence of such feeds.

Aha, I had no idea it was an SPA. Looking at the view source again, indeed, the lack of a feed link is not the only thing that's odd. The HTML response for <https://mastodon.technology/web/accounts/259460> isn't related to me at all.

And yeah, it's not so much about it being in the invisible DOM while on that link, but that opening view-source and fetches from crawlers and News/Feed apps find it, which would not execute javascript.

> > For example, adding an endorsed profile link seems to require use of the web interface, but it's not clear how one gets there, or one can only use that when logged-in. I also can't tell whether it is intentional or not that one is only able to endorse instance-local users (given I can't enter the web interface mode on other instances).
> 
> Ok, I am very confused by this. You can definitely endorse users from other instances, and I don't know what makes you think otherwise.

1. My own profile, informing me about using the "web inteface".

| Own profile
|--
|  <img height="150" alt="self-pub" src="https://user-images.githubusercontent.com/156867/86169317-5863e000-bb11-11ea-919f-d719b0d20228.png">

2. Journey from a friend's public page to web page:

| Public profile | Public toot | Web toot | Web profile
|--|--|--|--
| <img width="911" alt="friend-pub" src="https://user-images.githubusercontent.com/156867/86169588-c9a39300-bb11-11ea-8b3d-48319739028e.png"> | <img width="597" alt="friend-toot-pub" src="https://user-images.githubusercontent.com/156867/86169594-cb6d5680-bb11-11ea-9033-ff2b76293bab.png"> | <img width="654" alt="friend-toot-web" src="https://user-images.githubusercontent.com/156867/86169596-cb6d5680-bb11-11ea-912e-344cc5e8b25d.png"> | <img width="474" alt="frend-web" src="https://user-images.githubusercontent.com/156867/86169597-cb6d5680-bb11-11ea-99a3-dbae89d2d2cf.png">


Note that while on the Web toot page, one needs to care care to not open the link in a new tab or or copy the link because even in web mode, the profile links point to public URL, so only a direct click works.

3. OK, so that's for an instance-local user. Now let's try a user on another instance, such as <https://toot.cafe/@nolan>.

How would I go about endorsing them? Since I don't have an account there, there is no "Open in web" there. And more generally I can't log into there to approach the web mode by other means, either. Back on my own instance, I could not find anything on my profile page or under settings that would let me explicitly add add a user name@domain, either.

**Comment by ThibG** [comment]
> And yeah, it's not so much about it being in the invisible DOM while on that link, but that opening view-source and fetches from crawlers and News/Feed apps find it, which would not execute javascript.

A non-logged-in user would basically never end up on a `/web/foo` link, and even then, those links redirect non-logged-in users to the actual toot/profile, which do feature RSS feeds, so that's ok.

> How would I go about endorsing them? Since I don't have an account there, there is no "Open in web" there. And more generally I can't log into there to approach the web mode by other means, either. Back on my own instance, I could not find anything on my profile page or under settings that would let me explicitly add add a user name@domain, either.

The thing is, while logged in, most of your use would be from the Web app itself, you wouldn't normally come from an outside public profile or public toot, you'd see the toot/person directly in the Web interface (from toots, follower lists, etc., or just by searching for them with the search feature).

**Comment by Krinkle** [comment]
> > And yeah, it's not so much about it being in the invisible DOM while on that link, but that opening view-source and fetches from crawlers and News/Feed apps find it, which would not execute javascript.
> 
> A non-logged-in user would basically never end up on a `/web/foo` link, and even then, those links redirect non-logged-in users to the actual toot/profile, which do feature RSS feeds, so that's ok.

Interesting. I've definitely run into numerous of such URLs for users or toots leading to 404s when not locally logged-in. But.. I can't reproduce this now. Perhaps it was a bug fixed in months since, or perhaps a random bad instance.

Awesome, I'll keep that in mind.

> > How would I go about endorsing them? Since I don't have an account there, there is no "Open in web" there. And more generally I can't log into there to approach the web mode by other means, either. Back on my own instance, I could not find anything on my profile page or under settings that would let me explicitly add add a user name@domain, either.
> 
> The thing is, while logged in, most of your use would be from the Web app itself, you wouldn't normally come from an outside public profile or public toot, you'd see the toot/person directly in the Web interface (from toots, follower lists, etc., or just by searching for them with the search feature).

This isn't true for me. The vast majority of my interactions are not with the web interface. The exception is when I need to edit my settings. For the rest I'm either in an app (such as Pinafore), or when opening links in a new tab, it will be through the URL it provides me and the permalinks, which are the public URLs.

And despite being on Mastodon for about a year, I did not realise until just now that when I use the main web app and click on federated users that they open within that same app, on the same domain. That's interesting. And indeed, I've now figured out how to endorse a user from another instance.

I feel like there is perhaps something along this path that could be improved, but nothing concrete enough I can think of specifically related to the issue for RSS feeds or endorsing users, so I'll close this for now.

Thanks!
