### ISSUE TITLE
Bodyguard app integration

### ISSUE THREAD

**Issue by stemy2** [tootsuite/mastodon#14180]
### Pitch

[Bodyguard](https://www.bodyguard.ai/) is an app indended to fight cyberbullying. It proposes an [API](https://developers.bodyguard.ai/), so anyone can [use it](https://developers.bodyguard.ai/documentation/index.html) for his app. Currently, this exists only on french, but other language support are planned in the future.

### Motivation
It would be useful to integrate it in Mastodon to fight easier cyberbully, admins could just have to introduce their bodyguard API key to use it for their instance.

**Comment by SuperSandro2000** [comment]
Open source? Nope? 🤷

**Comment by ThibG** [comment]
Bodyguard is a non-free, opaque, centralized service, and requires sending the contents of messages to them. Furthermore, while Bodyguard seems to fare a little better than what I have seen previously, it is extremely easy to bypass by simply writing hateful messages in a “polite” way.

I'm therefore firmly opposed to direct integration with Bodyguard.

That being said, it could be useful to have some hooks or something to enable third-parties writing plugins…

**Comment by danimesq** [comment]
I think Bodyguard is more appropriate to implement in COPA sites like PokemonShowdown.
