### ISSUE TITLE
Image Accessibility Improvements

### ISSUE THREAD

**Issue by irlcatgirl** [tootsuite/mastodon#14182]
I mean this kindly but the experience provided by mobile apps for transcribing images sucks, as a result many images aren’t getting transcribed at all. I propose the following improvements.

1. Allow users to edit the alt text after posting. For example I post on my iPhone and later update it on my PC.
2. Improved mobile UI and automatic text transcription OCR on mobile (for example screenshots of other apps)
3. Community Transcriptions, other users should be able to submit a transcription of the image for other users images.

**Comment by halcy** [comment]
on the one hand, I'd love to be able to post-edit descriptions and/or add descriptions for images later, but on the other hand, the same caveats as for editing in general apply. It could be some kind of "append"-kind of thing, a special-cased reply that gets put (with attribution!) into the description - that avoids that to some degree. Not sure how abusable it would be, but you can already reply to posts, so hey.

What I think might be good as well would be drafts - let me "save as draft" to the server, edit that draft later, _then_ post it. That's a control flow that I, as a mobile user, could see myself using sometimes, when I want to post an image from my phone but I do want to add a (possibly lengthy) description. That's not only good for this particular kind of usage, it is also useful in many other scenarios.

OCR on mobile, I've been wondering - it's client side right now, and might have to be (server load), but could mobile web at least use the same code as desktop, or are there heavy compatibility issues? For apps, though, that seems like a thing that app developers should get on.

**Comment by Cassolotl** [comment]
Related issues:

* *Toot edit or undo #256*
* *Allow users to edit recently published toots #742*
* *Feature Request : Save as a Draft #13617*
