### ISSUE TITLE
Can create and organize own column

### ISSUE THREAD

**Issue by Dryusdan** [tootsuite/mastodon#1419]
I think this idea is write here, but I don't found it :/ .
Actually, the third column is miused, too much options for a little column, no really :/
So, it's cool if user can choose and organize his column, for exemple (talk with another "pouetos" https://mamot.fr/@bonob0h/142259 )
- List favorits toots
- List following and followers accounts
- List own toots
- List public toots on dedicated column
- List public world toots on dedicated column too

I think is all for me :)

**Comment by thomassth** [comment]
Or at least, can we hide the notification row? I simply don't have that many notifications to see.

**Comment by naokazuterada** [comment]
I hopefully want to change columns order too.

**Comment by Gargron** [comment]
See #3207
