### ISSUE TITLE
Communication/Federation after a wipe

### ISSUE THREAD

**Issue by Fastidious** [tootsuite/mastodon#1420]
I am stumped at my problem, and need help.

After running for two or three days my own instance (https://naganu.com/) I messed up and, to make long story short, I wiped it (destroyed VM, started a new one). Now I have a new instance up, same address, but even though I can follow, and see, the people I was following on the previous instance, they can’t see my toots at all! It is as if I am invisible.

Is there a solution for this, other than scratching the domain, and starting anew under a different one?

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
Their instances have a PubSubHubbub cache, which expires after a while (7 days seems to be the default). You'll have to ask them to clear it manually or wait for that period.

**Comment by Fastidious** [comment]
@wxcafe would it be a good idea to request that timeout to be reduced on main code? What would the negatives implications be? Thanks!

**Comment by wxcafe** [comment]
The negative implications would be more 'boilerplate' communication between instances, which increase traffic for both instances. If the number of instances increases significantly, this could become very large, which is a problem.

**Comment by Gargron** [comment]
Part of the solution to this is in #1323

**Comment by Fastidious** [comment]
@Gargron, @wxcafe what will it happen after the PubSubHubbub cache expires? Will the people see all my toots out of date on their timeline?

**Comment by Gargron** [comment]
@Fastidious There will be a gap, your new toots will start arriving, but not the ones created when the subscription didn't exist.

I propose that we create a "Troubleshooting" section in the documentation repository, walking people through cases like these. But as an issue, I am closing this.
