### ISSUE TITLE
How can i change the domain ? 

### ISSUE THREAD

**Issue by Dirdrik** [tootsuite/mastodon#1421]
Hi,

Yesterday, I've install mastodon on my server, and he was configurated with this domain social.domain1.com for test. And now I want change the domain (social.domain1.com --> social.domain2.com). I've change nginx conf and generate a new TLS, and replace the old domain by the new domain in the .env.production file, but it's don't work. 

I do not know how to do?

thx

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by raymestalez** [comment]
Did you rebuild it?

**Comment by Dirdrik** [comment]
Yes, but i don't think the problem comes from mastodon, i think is nginx the problem. I've change all social.domain1.com --> social.domain2.com in /etc/nginx/conf.d/mastodon.conf but he keep enable on the  social.domain1.com.

**Comment by Dirdrik** [comment]
i've delete all trace about social.domain1.com in conf file of nginx, and he keep alive on the wrong old-domain, you have an idea ?
