### ISSUE TITLE
Change closed register page

### ISSUE THREAD

**Issue by Dryusdan** [tootsuite/mastodon#1422]
I talk with a colleague and I present Mastodon. He would suscribe and he found "mastodon.social" BUT register is closed so he won't suscribe (because clic on other link, found instances.mastodon.xyz, not responsive... (Where source of instaces.mastodon.xyz ? :) )
So, I think is good if user can register on closed register page but it's page choose randomly (with preference uptime (more than 99%) ). After registration, a message display: "Your register on xxx.server this is your instance now"
But user can choose instance in this page with select. So select contain options : randomly, server1, server2, serverX

:)

**Comment by Lertsenem** [comment]
http://tooter.today does this, among others I can't remember the name of.

**Comment by Dryusdan** [comment]
Thank for link...
But actually all people going to mastodon.social, not good...
/me search another solution...

**Comment by wxcafe** [comment]
This is not a problem with Mastodon, the software, it's a problem with mastodon.social. Assigning @Gargron so he can discuss this but marking this question as invalid.
