### ISSUE TITLE
Scalingo setup: email setup is presented as optional but it is not optional

### ISSUE THREAD

**Issue by aral** [tootsuite/mastodon#1423]
The SMTP section of the Scalingo setup reads:

“SMTP_SERVER Hostname for SMTP server, if you want to enable email“

This makes it sound like setting up email is optional for using Mastodon. This is not the case as you cannot create an account using the web interface if email is not set up (as you will never get the confirmation email).

Suggested enhancements:

1. Update the copy: “SMTP_SERVER Hostname for SMTP server (you must enable email to set up accounts on Mastodon as it sends confirmation emails)"
2. For single account setups, forgo the email confirmation.
3. If SMTP is not set up, forgo email confirmations.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by aral** [comment]
As a workaround:

1. Install the Scalingo CLI: http://cli.scalingo.com
2. `scalingo --app <your-app-name> run -e RAILS_ENV=production bundle exec rails mastodon:confirm_email USER_EMAIL=<your@ema.il>`

These could be added to the instructions and/or docs.

**Comment by ashfurrow** [comment]
@aral would you be free to open a pull request adding this to [the documentation](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Scalingo-guide.md)?
