### ISSUE TITLE
500 Error when upload 

### ISSUE THREAD

**Issue by Vibhigupta** [tootsuite/mastodon#14243]
We Just changed S3 Bucket on our instance as we migrated from Wasabi.

It was working fine but after switching to scaleway media works and load but when someone upload it throw 500 error.

The browser console shows it failed to load a resource 
![Screenshot_2020-07-06-20-25-37-73__01](https://user-images.githubusercontent.com/51713176/86607833-4b277500-bf99-11ea-8214-c29aa9c7c7fc.png)

I don't know where to look to debug the issue require some help

**Comment by ThibG** [comment]
We would need logs from `journalctl -u mastodon-web`

**Comment by Vibhigupta** [comment]
Hello The issue is with nginx, we Just switched bucket and the new bucket name is changed so even after updating the config its still making request to older bucket name.

So how do i clear this cache? or update so it request to new bucket
