### ISSUE TITLE
Page is not displaying on mstdn.social 

### ISSUE THREAD

**Issue by ahmthekewlest** [tootsuite/mastodon#14258]
I’m not sure if anyone else is having the same problem when I login. I tried to login on mstdn.social and I get this on my page. I tried to refresh the page but it did not solve the issue.
![8ED90A56-A9BC-4BA6-811A-438B49A200A1](https://user-images.githubusercontent.com/67990440/86870600-50221c80-c09e-11ea-876d-70272b1bdcac.jpeg)

**Comment by Sasha-Sorokin** [comment]
Can you please post stacktrace here?

**Comment by ahmthekewlest** [comment]
> Can you please post stacktrace here?

TypeError: undefined is not an object (evaluating 'this.canvas.getContext')


https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:400677
https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:400322
os@https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:1016365
pu@https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:1034224
pu@[native code]
https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:1053535
du@https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:1030696
Zs@https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:1026850
Zs@[native code]
https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:978292
https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:1053535
Va@https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:978238
Ka@https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:978173
eu@https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:1026942
notify@https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:99427
https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:100068
https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:100143
[native code]
g@https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:378540
https://mstdn.social/packs/js/common-35c9753164c49e4f4e42.js?__uncache=7%2F8%2F2020%2C%201%3A20%3A10%20AM:2:131036
promiseReactionJob@[native code]

**Comment by ykzts** [comment]
Duplicate with #14257
