### ISSUE TITLE
Possible breaking change in #14253

### ISSUE THREAD

**Issue by umonaca** [tootsuite/mastodon#14265]
I am against [this feature](https://github.com/tootsuite/mastodon/pull/14253/) because:

- There are some occasions that multiple (even hundreds of) devices share the same IP behind NAT. Throttling might break user experience. 
- If the server admin misconfigures Nginx (e.g. behind Cloudflare) and the Nginx does not forward real ip , most users may be blocked from logging in.

**Comment by Gargron** [comment]
It's not a breaking change. IP-based rate limits have existed prior to the PR. The PR adds rate-limits based on target account.
