### ISSUE TITLE
Trim long usernames (visually)

### ISSUE THREAD

**Issue by Fastidious** [tootsuite/mastodon#1426]
I character limit on the showed description on a user must be set. [See](https://naganu.com/users/david/following) the overflow:

![screen shot 2017-04-10 at 08 45 38](https://cloud.githubusercontent.com/assets/8352292/24862353/4e889248-1dca-11e7-97d7-e7d09e544740.png)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mkody** [comment]
Well, the description is fine.
It's more like the full address, `@maiyannah@community.highlandarrow.com`, should be trimmed?

**Comment by Fastidious** [comment]
@mkody you can’t see how the description overflows over the line? Look again.

**Comment by mkody** [comment]
Of course, but that's because the username is too big and goes below the profile picture. So this push everything down the line.

**Comment by Fastidious** [comment]
@mkody it has nothing to do with long usernames. See: 

![screen shot 2017-04-11 at 12 03 20](https://cloud.githubusercontent.com/assets/8352292/24918608/f5a4cfc6-1eae-11e7-82c5-a436869da55d.png)

**Comment by mkody** [comment]
Well, there's two problems, now. :grin:

**Comment by expenses** [comment]
@Fastidious 

The description for 'the grugq' is trimmed, but because the font isn't monospaced, it overflows anyway.

**Comment by Fastidious** [comment]
@expenses OK, but how knowing that helps? There is still a problem.
