### ISSUE TITLE
Reduce character count for URLs to a fixed value

### ISSUE THREAD

**Issue by nizarus** [tootsuite/mastodon#1427]
Hi,
Yes we have 500 chars with Mastodon, but shorting URL can be also useful to get more effective content.
Integration of the http://ur1.ca/ service from StatusNet, as in GNUSocial, can be a good idea.
An example of toot where the link (with Arabic alphabet) takes 359 chars : https://mamot.fr/@nizarus/146709

**Comment by Fastidious** [comment]
No, do not want. It anything, making it an optional setting, perhaps. URL shorteners are bad, especially those who, due to the size or interests of the company behind, are ephemeral. 500 is plenty, if you need more, get a blog. 😊

**Comment by nizarus** [comment]
Fastidious : try to copy the link of this toot https://mamot.fr/@nizarus/146709 in a new toot to understand what I mean.

**Comment by Fastidious** [comment]
@nizarus https://goo.gl/cS1a1Y, there, how difficult is it to just do it manually? How many thousand of links like that do you send?

URL shorteners obfuscate the links, they are often short lived (the services themselves). There is plenty on the net on why they are “evil.” I am strongly against them, but, as I wrote originally, "making it an optional setting” might work (although it will further complicate Mastodon).

**Comment by wxcafe** [comment]
Another option for this would simply be not counting links in the 500 chars of the toots. That way you don't have to use URL shorteners yet you can paste as many links as you want.

**Comment by Fastidious** [comment]
@wxcafe right, so abuse like https://buy.drugs.on.this.awesome.website.please.com/ happens?

**Comment by wxcafe** [comment]
this is already possible.

**Comment by Gargron** [comment]
It might be better to just count links in the text as as like a 20 (or so) characters penalty, regardless of how long the link is. After all, visually they are shortened anyway using CSS, and from a storage perspective there is no hard limit on toot length.

**Comment by SkyzohKey** [comment]
:+1: on @Gargron solution.

**Comment by nizarus** [comment]
Yep, I agree with @Gargron idea as a good compromise.

**Comment by kensanata** [comment]
Closed by #4427
