### ISSUE TITLE
Ability to search all of one's own messages / toots

### ISSUE THREAD

**Issue by webmind** [tootsuite/mastodon#14295]
The ability to search for all of your own toots, perhaps all toots you have permission to.

### Pitch

Search currently only searches public messages, it is very useful to find your own messages however or messages you have in your inbox.

This would only be searching your own outbox and maybe inbox, only local stuff to the user.

### Motivation

When having big streams of data it's very useful to be able to find something back. A link you posted but forgot or a picture. Or maybe you really want to delete that timeline you did before. Manually going back in time takes a lot of resources, is slow and a lot of work. This would make cleaning up a lot easier and possibly save on resources when you have to go back manually.

**Comment by Gargron** [comment]
> Search currently only searches public messages

No, search does not only search public messages. In fact, search absolutely does not search public messages. Search *only* searches "all of your own toots" and "all toots you have permission to".
