### ISSUE TITLE
An error occurred while fetching the remote account

### ISSUE THREAD

**Issue by renaldofreire** [tootsuite/mastodon#14291]
### Expected behaviour
Follow  "@libreoffice@fosstodon.org"

### Actual behaviour
"Unfortunately, an error occurred while fetching the remote account"

### Steps to reproduce the problem
1. Access https://fosstodon.org/@libreoffice;
2. Click on follow;
3. When the pop-up window opens, put "@ renaldofreire @ masto.donte.com.br" to proceed to follow;
4. Error: Unfortunately, an error occurred while fetching the remote account.

### Specifications
Mastodon Release: v3.1.5
My browser: Firefox 78.0.2 (64-bit)
OS: Archlinux

**Comment by Sasha-Sorokin** [comment]
Are you sure your instance does not block [fosstodon.org](https://fosstodon.org)? I'm unable to reproduce this at [mastodon.social](https://mastodon.social).

**Comment by Sasha-Sorokin** [comment]
Apparently [masto.donte.com.br](https://masto.donte.com.br) **does** block [fosstodon.org](https://fosstodon.org). Instance administrators free to block domains as they will [with three levels](https://docs.joinmastodon.org/admin/moderation/#server-wide-moderation), and in this situation, you will not be able to exchange anything with [fosstodon.org](https://fosstodon.org) instance. You are can discuss this decision with your instance administrator and if it's critical for you, you can migrate to any other instance, [learn how here →](https://docs.joinmastodon.org/user/moving/#move)

![Screenshot of fosstodon.org domain listed in list of blocked instances](https://user-images.githubusercontent.com/10401817/87245374-fee3a580-c46e-11ea-9d7e-dd3ce99232b4.png)

**Comment by ThibG** [comment]
I *guess* we could return a specific error to end-users (on the local instances) that say that what they are looking for has been blocked. If we do that, we would have to make sure not to leak that info to users that aren't logged in, though.

**Comment by Sasha-Sorokin** [comment]
@ThibG Good idea about the user-friendly message, but I'm not sure why we need this check for only logged users, are we overprotecting once again? See, even if we care of those who afraid of being called out for blocking instances, there is nothing stopping person from another instance register on that instance to check the block. I think the better option is to show this message when instance publishes their block list. “Unable to exchange with this instance. [Review the list of blocked content](https://mstdn.social/about/more).”

**Comment by ThibG** [comment]
> See, even if we care of those who afraid of being called out for blocking instances, there is nothing stopping person from another instance register on that instance to check the block.

Only true for instances with open registrations. Not true for closed instances or approval-based ones.

> I think the better option is to show this message when instance publishes their block list. “Unable to exchange with this instance. [Review the list of blocked content](https://mstdn.social/about/more).”

Likewise, the list can be public, or only for logged-in users (or disabled altogether). But there's also the fact that this can occur for blocked individual users, which we currently do not list anywhere.

**Comment by renaldofreire** [comment]
It really is a block that came from my own Instance. Thanks for everyone's response!
