### ISSUE TITLE
Block and mute does not eliminate content from blocked/muted user

### ISSUE THREAD

**Issue by umonaca** [tootsuite/mastodon#14301]
### Expected behaviour

I am user A who follows user B, and I see user B reblogged status from user C. I block or mute user C. Then refresh the page of home timeline. I should not see any post from user C, even it was reblogged by user B.

### Actual behaviour

After refreshing the page I still see the reblogged posts from user C.

### Steps to reproduce the problem

1. On `mastodon.social`, follow Gargron,
2. Randomly block or mute anyone whose post was just reblogged by Gargron.
3. **Refresh** the page.
4. You will still see the reblogged post from the blocked/muted user on home timeline.

### Specifications

It exists not only on `mastodon.social`, but also other instances running on the master branch.

**Comment by ThibG** [comment]
Indeed, it seems that removing the blocked accounts' content from the Home Timeline is done through `FeedManager#clear_from_timeline`, which removes toots from the blocked user, but not boosts of toots by the blocked user, nor toots mentioning the blocked user… we should probably change that to be consistent with how toots are inserted in the Home TL, but it may be tricky to write that in an efficient manner.

**Comment by umonaca** [comment]
It's tricky but I think it should be useful. Sometimes you can't just unfollow your friends if they reblogged something that you don't want to see on the home TL. NSFW images, for example. And they don't have a keyword in text to be filtered.
