### ISSUE TITLE
Suggestion: minor enhancement for the Mastodon user's profile

### ISSUE THREAD

**Issue by KNTRO** [tootsuite/mastodon#1430]
[Take a look at [my profile](https://mastodon.social/@KNTRO), please. It's a little hard to read the text and I can't control colors. I suggest to outline the text, something [like this](http://www.gimpology.com/uploads/3_8_8.png), or [like this](https://lh6.googleusercontent.com/-zOWkytRZr10/U6OqTSEUExI/AAAAAAAAD6U/saCHs2MstDA/w924-h256-no/TMPro+-+Text+Outline+Drop+Shadow.JPG)].

* * * *

- [✔️] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Fastidious** [comment]
Your choice of header background image was rather poor. Pick a different one and voila!

**Comment by alexgleason** [comment]
I disagree that the user should ever have to make an optimal selection. It just won't always happen. Not to mention, differences in screen sizes could display this image differently depending on display, so optimizing things from the image standpoint probably isn't the best idea.

I suggest adding a subtle black to transparent gradient from the bottom to about 20% up the banner. This should make the text legible without having to use a text-shadow or outline. It would also not be wrong to just make the meta area have a solid gray background.

**Comment by wxcafe** [comment]
Can someone provide a PR of this? [This](https://github.com/tootsuite/mastodon/blob/6b1db5c2b202383bd22d40909a68df8cbcb20b36/app/assets/stylesheets/accounts.scss#L384) would be where you want to look

**Comment by expenses** [comment]
What about allowing the user to change the colour of the profile text?

**Comment by wxcafe** [comment]
@expenses I think this should behave correctly by default, and #1463 fixes this perfectly imo

Closing since this is resolved
