### ISSUE TITLE
Manual user confirmation is not reporting the right return code/message

### ISSUE THREAD

**Issue by AxelTerizaki** [tootsuite/mastodon#1432]
When trying to confirm users manually with this : 
```bundle exec rails mastodon:confirm_email USER_EMAIL=~foo@bar.com```

You get output like this :
```
User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1  [["email", "~foo@bar.com"]]
User ~foor@bar.com confirmed.
``` 

However, the email I just entered was wrong (the ~ shouldn't be there) yet the command returns me that the user has been confirmed.

When entering the right mail address, it shows more, and displays the same message.

```
bundle exec rails mastodon:confirm_email USER_EMAIL=toto.klein@laposte.net
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1  [["email", "foo@bar.com"]]
   (0.3ms)  BEGIN
  Account Load (0.8ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 357], ["LIMIT", 1]]
  SQL (0.4ms)  UPDATE "users" SET "confirmed_at" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["confirmed_at", 2017-04-10 14:13:25 UTC], ["updated_at", 2017-04-10 14:13:25 UTC], ["id", 62]]
   (27.8ms)  COMMIT
User foo@bar.com confirmed.
```

When given a wrong email address, the command should say it can't find the mail address in the database.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
pinging @ashfurrow since he made the PR for that rake task

**Comment by ashfurrow** [comment]
I'll take a look later today 👍

**Comment by ashfurrow** [comment]
Made the PR after testing locally ^
