### ISSUE TITLE
Wrong audio player foreground colors in light theme

### ISSUE THREAD

**Issue by Sasha-Sorokin** [tootsuite/mastodon#14337]
Recently Mastodon redesigned audio player to display covers and with new visualizer for audio output. With that, album art color extration has been added, so background color changes accordingly. Unfortunately, this has led to a weird bug, when foreground color does not respect background color in **light theme**, resulting in controls being ‘invisible’.

This is especially the case with transparent (png) covers, when most of the image being transparent, which results in miscalculation and black background color instead of color for the current theme.

### Steps to reproduce the problem

0. Have light theme enabled.
1. Open [this post](https://mastodon.technology/@bclindner/104520183848949278) in web UI

### Expected behaviour

<p align=center><img src="https://user-images.githubusercontent.com/10401817/87660550-707e6500-c789-11ea-89eb-b2a3fac0fea2.png" alt="Screenshot with fixed foreground colors"></p>
<p align=center>The colors are alright (this is a concept image!)</p>

### Actual behaviour

<p align=center><img src="https://user-images.githubusercontent.com/10401817/87660761-c81cd080-c789-11ea-89ff-59710ebc3911.png" alt="Screenshot with broken foreground colors"></p>
<p align=center>Black controls on a black background (miscalculated because of transparency),<br> resulting in controls, such as play, being completely invisible until hovered</p>

### Specifications

Reproduced on [mastodon.social](https://mastodon.social), which is presumably v3.2.0rc1.

Using Firefox 78.0.1.

**Comment by Gargron** [comment]
Audio players will not be themable, color calculation happens server-side, we can't adjust it dynamically based on light or dark theme. So, it will likely never look like your "expected" image. However, transparent color messing up the algorithm and resulting in invisible buttons is a bug and should be fixed.

**Comment by Gargron** [comment]
The fact that it looks alright on the dark theme makes me believe it has nothing to do with color detection and it's actually just the light theme overriding colors that's causing the problem:

![grafik](https://user-images.githubusercontent.com/184731/87664519-ab6ea180-c765-11ea-9bdc-cf1196f382b1.png)

**Comment by Sasha-Sorokin** [comment]
@Gargron that's unfortunate, I thought maybe if most of background is transparent, then Mastodon could fallback to theme default color instead of just black (like if server returns #00000000, fallback to theme default colors), because black box looks not-so-nice in light theme. Maybe that's for another issue.

And yes, that's something related to override, because when you hover controls, they become white, I was mislead with the color extraction because I thought Mastodon will invert colors if contrast ratio of background-foreground is bad (wait... it is according to @ThibG commit message above?). I tried to fix it it, but I was just confused because when I pass one value, it still results another one, guess I didn't check `diff.css` :facepalm:

**Comment by ThibG** [comment]
@Sasha-Sorokin we need to set the color from JS to draw in the canvas though, don't we? I guess we maybe could read a CSS rule/variable to set the default color?

**Comment by Sasha-Sorokin** [comment]
@ThibG do you mean fallback for transparent covers? Could be just `filter: invert()` in light theme for canvas if parent contains some class name, or `getComputedStyle(this.superCoolCanvas).getPropertyValue` with either `color` or `--variable` in JS.

```js
> getComputedStyle($('.audio-player__canvas')).getPropertyValue('color')
< "rgb(0, 0, 0)"
```
