### ISSUE TITLE
Autocomplete emoji names

### ISSUE THREAD

**Issue by ashyon** [tootsuite/mastodon#1433]
When typing a `:` followed by letters, there should be a dropdown similar to the one for users to suggest emoji names.

**Comment by ashyon** [comment]
Sorry, accidentally deleted the filler text. I did search for other similar issues.

**Comment by rhaamo** [comment]
As said in #949 this is being discussed in #1199.

**Comment by ashyon** [comment]
Oops, sorry. Closing.
