### ISSUE TITLE
Scalingo setup: S3 bucket cannot contain dots

### ISSUE THREAD

**Issue by aral** [tootsuite/mastodon#1435]
If your S3 bucket name has a dot in it (e.g., bucket.my.domain), it will not work with Mastodon when assets are being downloaded as the SSL certificate covers just one level of subdomain. (Uploads will still work).

We should make a note of this in the installation document.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
Can you make a PR? :)

**Comment by Gargron** [comment]
We do not suggest a specific naming scheme for buckets anywhere, I think. That seems outside the scope of this repository as it's deployment specifics (myriad different ways to set this up)
