### ISSUE TITLE
Welcome default home page : show local time line

### ISSUE THREAD

**Issue by Shnoulle** [tootsuite/mastodon#1436]
Currently : when come to a new mastodon server , have just login/create user: 

We can not really understand what is mastodon when come for the 1st time .

The first time i see mastodon user in my list : i didn't really understand it's something open, because in gnusocial : all is open : when an 'not loggued' user come to home page : see (by default) local time line.

See:
* https://quitter.no/main/public
* https://loadaverage.org/main/all ([disappearing](https://wiki.loadaverage.org/news/bye_guys))
* https://gnusocial.no/main/public

I think even the old gnusocial (2011 .... ) seems more welcoming and friendly ....

Then seems best to show : the login part + maybe : create account part, + the local time line list (according to user settings).

And : other instance user have more chance to discover remote users

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate (search with `welcome` `home page` `home`

**Comment by rhaamo** [comment]
It seems that #1142 already discuss this kind of feature.

**Comment by mkody** [comment]
See #1142, and thus #1053

**Comment by Shnoulle** [comment]
Bad search ....  `landing page` is better. Aaah this french people ....
