### ISSUE TITLE
Unavailable Content Reason always blank

### ISSUE THREAD

**Issue by kevquirk** [tootsuite/mastodon#14362]
When we moderate an instance, we always put a public reason, but that reason is always blank on the “unavailable content” section of the about page.

Example - https://fosstodon.org/about/more#unavailable-content

Is this a known bug, or am I just an idiot that is missing something obvious? 😊

**Comment by Gargron** [comment]
Hmm, there's an admin setting for who can see blocks and who can see reasons... Maybe it's set so nobody can see reasons?

**Comment by kevquirk** [comment]
Yep, that was it...so I am an idiot that was missing something obvious! 🤣🤣

Thanks Eugen.
