### ISSUE TITLE
precompile is needed after changing CDN_HOST, but it shows "Everything's up-to-date. Nothing to do"

### ISSUE THREAD

**Issue by OmmyZhang** [tootsuite/mastodon#14379]
`bundle exec rails asserts:precompile` is needed after CDN_HOST is changed/added/removed, but it shows "Everything's up-to-date. Nothing to do".

**Comment by ThibG** [comment]
Ideally, i'd like the assets to not be dependent on the environment at all…

In the meantime you can force rebuilding the assets with `bundle exec rails assets:clobber && bundle exec rails assets:precompile`

**Comment by OmmyZhang** [comment]
`__webpack_public_path__` may work.

**Comment by ThibG** [comment]
Yes, see https://github.com/tootsuite/mastodon/pull/14381
