### ISSUE TITLE
Search on hashtag doesn't return toots with images

### ISSUE THREAD

**Issue by gvenk** [tootsuite/mastodon#1437]
Search on hashtag doesn't return toots with images. Search for #ijburg only returns the toots without images, but doesn't show this one: https://mastodon.xyz/@gvenk/439858

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by blackle** [comment]
I can't reproduce this on icosahedron.website, made this post: https://icosahedron.website/@blackle/461257

and it appears in the search for hastag

also I can see it when I click on the hashtag on the public view https://mastodon.xyz/tags/ijburg

**Comment by gvenk** [comment]
But when I click (or search) on a hashtag I get this url: https://mastodon.xyz/web/timelines/tag/ijburg and not https://mastodon.xyz/tags/ijburg. 
The first one doesn't show toots with images, the second one does.

**Comment by wxcafe** [comment]
I think @blackle was saying two different things:
- when she searches for a hashtag on icosahedron.website, she can see pictures
- when she looks at the public page for the tag #ijburg on mastodon.xyz, she can see pictures

Which tends to show that your problem can't be reproduced. I personally can't either: 
<img width="268" alt="screen shot 2017-04-11 at 11 54 40" src="https://cloud.githubusercontent.com/assets/3009327/24903567/18d91052-1eae-11e7-8c6e-f524dd68b5be.png">

**Comment by gvenk** [comment]
Hmm...very strange. I did some extra testing and now the toots with images do show up in a search. It's only a few of my older toots that still don't show up in my search results, but they do show on the public page: https://mastodon.xyz/tags/ijburg

It must have been some kind of hickup. I'll close this for now.
