### ISSUE TITLE
Bug: Boosts missing from timeline.. but only for my admin account?

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#14377]
https://cdn.discordapp.com/attachments/231908446830723072/735677110105931826/bug.mov

### Expected behaviour
I want to boost public intros from my admin account.

### Actual behaviour
Boosting two new toots.. only 1 of them shows up on my admin feed (refreshing does not fix it). 
both show up on my personal account.

I've replicated this over and over.. it is the newer toot that hides

https://aus.social/@dylenbeatty/104557920074403867
https://aus.social/@cd30000/104555356728910956

### Steps to reproduce the problem

I've repeated this ten times to capture a video. Always the same.

### Specifications

3.2.0 RC1

**Comment by ThibG** [comment]
Wasn't the other toot just boosted recently enough to not be bumped again?

**Comment by shleeable** [comment]
this is the first time I've boosted it.
so you think somebody else boosted it? what's the conditions for a recently boost being ignored?

**Comment by ThibG** [comment]
Something that is already in your last 40 toots in your TL doesn't get bumped on boost, unless you've selected the option to not group boosts in your preferences.

**Comment by shleeable** [comment]
ok... I'll test that condition if this happens again.
