### ISSUE TITLE
Number of reposts/likes mentioned on my timeline is incorrect

### ISSUE THREAD

**Issue by therealadityashankar** [tootsuite/mastodon#14389]
on my timeline/feed -
![Screenshot_2020-07-24 Mastodon](https://user-images.githubusercontent.com/21975892/88420732-f4c58d80-ce04-11ea-9c10-01284f7efbf0.png)

however when checking under the post -
![Screenshot_2020-07-24 Mastodon(1)](https://user-images.githubusercontent.com/21975892/88420761-027b1300-ce05-11ea-8ed0-fd3158de6220.png)

### Specifications

bug on mastodon.social, using the latest stable build of firefox,
reloading the page does not fix the issue

probably a caching issue, don't know if it occurs for a higher like/repost count

**Comment by Gargron** [comment]
Numbers aren't shown in timeline view.

**Comment by therealadityashankar** [comment]
@Gargron then why is a `0` shown in the timeline view

**Comment by therealadityashankar** [comment]
you should probably remove that

**Comment by therealadityashankar** [comment]
I'm such an idiot, I'm half asleep, sorry for this

**Comment by SuperSandro2000** [comment]
> Numbers aren't shown in timeline view.

Not very intuitive.

**Comment by therealadityashankar** [comment]
@SuperSandro2000 true, I'm not sure showing it is a good thing though, there is a debate on how twitter and instagram are forcing their users to become "like" or "repost" centric, I actually might prefer mastodon's approach here

**Comment by SuperSandro2000** [comment]
It would be consistend if the reply count would be hidden, too.

**Comment by therealadityashankar** [comment]
agreed cautiously - something should be done about that, something to manage between reply count vs when people personally chat

**Comment by trwnh** [comment]
see #8181 and #8343 for old discussions about this
