### ISSUE TITLE
I receive an Error processing 405 when execute the tootctl media remove command,

### ISSUE THREAD

**Issue by xirikm** [tootsuite/mastodon#14398]
### Expected behaviour

No errors, everything is ok.

### Actual behaviour

I got an error: Error processing 405: undefined method `+' for nil:NilClass, as shown in the figure below.

![WmsY.png](https://img.xirikm.net/images/WmsY.png)

### Specifications

This problem appeared in v3.2.0, and the version of Ruby is 2.6.6p146.
When I use v3.1.5 everything seems to be normal, I don’t know if it’s because of something wrong with my upgrade process or a code bug.

**Comment by xirikm** [comment]
I think the problem is caused by line 236 of file lib/mastodon/media_cli.rb, so I modified it to `media_attachment.file_file_size`, and then the problem disappeared.

But the strange thing is that when I modified the file back to the original state again, there are no more errors!  
I don't know why this happens, but the code seems to be ok. It may be an occasional error in my operating environment.

I'm sorry to disturb everyone, I will close this issue.  
And finally, my English may not be very good, please forgive me if the description is not clear.

**Comment by ldidry** [comment]
Same issue here but had to edit line 34 of `lib/mastodon/media_cli.rb`, then rollback and the problem disappeared.

**Comment by xirikm** [comment]
> Same issue here but had to edit line 34 of `lib/mastodon/media_cli.rb`, then rollback and the problem disappeared.

Yeah, I just found out that I made a mistake in the number of lines, and I also modified line 34. I have just re-edited my reply.
