### ISSUE TITLE
Consider reviewing #14380 (“Add custom icon for private boosts”)

### ISSUE THREAD

**Issue by Sasha-Sorokin** [tootsuite/mastodon#14397]
### Motivation

After I saw the PR (when it was already merged) I considered polling my friends about it, and almost nobody was able to guess what “repost” icon with the lock means, **even when provided context** (like “it's your post, you have a private account, you cannot repost others' private posts” (which was the question about restricted icon that most of them were able to guess)).

I also said what it means after answers and asked to consider if that's intuitive, most of them said **it's not**.  I may agree that my friends are not a representative selection (that's only 10+ people, after all), but this already suggests there is something wrong with the change, even for the users, who aware of how regular social media works.

<p align=center><img src="https://user-images.githubusercontent.com/10401817/88502415-8ea15c00-cff8-11ea-9673-14f79b4fd29b.png" alt="Screenshot of “private boost” icon"></p>

---

#14380 was merged without any critical review and may be harmful to new users. As commented, even I was confused about what this lock means. And even now, after I've seen the PR and understand what it supposed to mean, it still draws attention due to its obscurity, while it **does not** change the meaning of the boost button at all (unlike #14373, which suggests the button is inactive).

The change was introduced from Glitch fork, and quoting @Gargron:
> Would it be a fair assumption to say that people who use glitch-soc are more familiar with the technical workings of Mastodon? That could account for the disparity in feedback.

### Pitch

I suggest reviewing and discussing this change and if it turns out to be not that good, reverting it.

Mastodon people visiting this issue, did you like the change? Do you think it is necessary? Reply in the comments below!

**Comment by renatolond** [comment]
Coming from a place where I know Mastodon internals a bit more than the average user, I think it's a nice change.
Specially in combination with #14123, I think it indicates that boosting will still keep the current visibility.

**Comment by ThibG** [comment]
This new icon indeed doesn't represent a different behavior (well, slightly: the boost will be private even if your default post privacy is public), but it is here to accommodate another UI change: up until 3.2.0, in such situation, there was no boost icon, but the lock icon instead, and boosting would require you to go through the dropdown menu, which I think was way more of an UI discrepancy than this new icon. Maybe having the normal boost icon would have been fine, but I had multiple reports of people wanting to be able to tell apart at a glance (even in the presence of the privacy icons).

**Comment by Sasha-Sorokin** [comment]
@ThibG going through the menu was a bad experience and very confusing, and it's good we got rid of it and simplified it, but now we're again making it unnecessarily harder. I understand that icon supposed to tell “this will be boosted privately”, but it reads as “locked boost” and it really stands out, drawing attention.

In **my opinion**, additional clarification is unnecessary and it should be expected behavior that YOUR private posts being boosted privately (it would be extremely dumb if you could randomly boost your private post publically). If you want to reassure — private boosts will have a different tooltip; giving separate icon is probably a job for scripts or customized forks.

**Comment by ariasuni** [comment]
Well then the problem is the meaning of the locked icon, because publishing a toot under a visibility represented by a lock doesn’t seem really different in terms of semantics than boosting with a locked icon (especially since the button is not greyed out so it’s pretty clear in my opinion that it means a kind of restricted boost).

**Comment by Sasha-Sorokin** [comment]
Okay, so far it was mostly good feedback, that's probably has to deal with experience then. Let it be the way it is now, maybe someone will come up with better and intuitive design later. I'm closing this issue for now :)

BTW I've also seen suggestion to write this down in documentation, but I'm not sure where this could be written, maybe “[Posting toots **§** Followers-only](https://docs.joinmastodon.org/user/posting/#private)”, possibly expanding “Your post cannot be boosted, except by yourself.” But in reality I think people rarely read docs nowadays…
