### ISSUE TITLE
How can I see the debug log?

### ISSUE THREAD

**Issue by raymestalez** [tootsuite/mastodon#1439]
Do you guys know how to run Mastodon in a debug mode, so that instead of 500 errors from the server, I could see the log of what's going on? 

(ideally while using docker)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by rhaamo** [comment]
They would be in journalctl, I use ```journalctl -xf -u mastodon-*``` to see them.
By default it's in debug mode IIRC.
However I don't use docker and doesn't know the command needed to run one in a container sorry.

**Comment by raymestalez** [comment]
Thank you for the reply! Yes, unfortunately this command doesn't seem to work with docker... I'll try to figure out how to run it without docker if there isn't an easier way.

**Comment by raymestalez** [comment]
Apparently there should be a ruby log file somewhere. I can attach to the web container and see log/production.log file, but it's empty...

**Comment by raymestalez** [comment]
Okay, so I got it to run without the docker, but I still can't see the logs.

I'm doing a thing, and getting an error on the frontend:

```
422 Remote account could not be resolved
```
But the file `log/production.log` is empty, and the command (that someone suggested I should run):

```
journalctl -xf | grep "status=422"
```

doesn't output anything.

**Comment by ashfurrow** [comment]
@raymestalez any update on this? Did you figure it out?

**Comment by frootmig** [comment]
I have problems, too, finding the cause for 50x errors. production.log is empty. journalctl does not show something usefull.

**Comment by ashfurrow** [comment]
@frootmig you're not using Docker are you?

**Comment by frootmig** [comment]
@ashfurrow Correct.

**Comment by ashfurrow** [comment]
To see the logs in docker, run `docker logs mastodon_web_1`.

**Comment by Gargron** [comment]
You can control log level with RAILS_LOG_LEVEL=debug|info|warn

You can view logs through journalctl or docker logs

For some exceptions, detailed stack traces are not available either way if it's an expected and caught/handled exception
