### ISSUE TITLE
DEFAULT_LOCALE=fr put the site down

### ISSUE THREAD

**Issue by mumbly58** [tootsuite/mastodon#1443]
Adding DEFAULT_LOCALE=fr (french) to .env.production turns the mastodon instance OFFLINE on https://instances.mastodon.xyz/ ??! Don't know why or how ??!
I made the test several time. Confirmed by another instance.

+ it issues an error in the User count bot :
Traceback (most recent call last):
File « usercount.py », line 98, in
current_id = int( get_between(pagecontent, « Home to« , « users »).replace(« , », «  »))
File « usercount.py », line 92, in get_between
return s[(s.index(substring1)+len(substring1)):s.index(substring2)]
ValueError: substring not found

**Comment by tcitworld** [comment]
No issues for me.

**Comment by wxcafe** [comment]
https://instances.mastodon.xyz is not run by this project. Please ping @TheKinrar@mastodon.xyz to know how that works. The User Count bot is run by this project either, please ping @jk@mastodon.social about this. I'm closing this issue since it doesn't concern this project.
