### ISSUE TITLE
duplicate key value break unique constraint "index_unavailable_domains_on_domain"

### ISSUE THREAD

**Issue by taziden** [tootsuite/mastodon#14444]
### Expected behaviour

Nothing

### Actual behaviour

Since upgrading to v3.2.0, logs are full of errors about a duplicate key breaking unique constraint index_unavailable_domains_on_domain.

juil. 27 11:03:42 master03 bundle[19417]: 2020-07-27T09:03:42.905Z pid=19417 tid=ouga1uwv5 WARN: ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « index_unavailable_domains_on_domain »
juil. 27 11:03:42 master03 bundle[19417]: DETAIL:  La clé « (domain)=(receivepublic) » existe déjà.

### Steps to reproduce the problem

Nothing

### Specifications

Issue found in v3.2.0

**Comment by Gargron** [comment]
The unavailable_domains table and index have been created in 3.1.4. What was your version before 3.2.0?

**Comment by taziden** [comment]
> The unavailable_domains table and index have been created in 3.1.4. What was your version before 3.2.0?

3.1.5

**Comment by ThibG** [comment]
I can't see any code change between 3.1.4 and 3.2.0 that could cause new occurrences of this.

However, it's very possible for this error to occur when multiple deliveries are performed in parallel for a single host that would previously be considered available.

@taziden does the error occur with multiple domains? Does it occur repeatedly with the same domain over time, or just within a minute or something?

**Comment by taziden** [comment]
I'm not sure to read the logs correctly but from what I can see it occurs for multiple domains, and not within a minute.

Oh, it seems like it's been going on since before the upgrade and I didn't notice it until today.

**Comment by taziden** [comment]
Fixed now. It was related to the upgrade of glibc to 2.28 in Debian Buster, corrupting the index and then introducing duplicate values in db.
