### ISSUE TITLE
Retoot icon with lock shows when hovering on "no retoot" icon of other's followers-only toots.

### ISSUE THREAD

**Issue by pullopen** [tootsuite/mastodon#14455]
### Expected behaviour 

A no retoot icon should be shown under "Followers-only" toots from other people after v3.2.0.

### Actual behaviour

When hovering on this icon, a retoot with lock icon shows itself. It's actually confusing since this icon shows under my own follower-only toots as well.

![gif](https://s1.ax1x.com/2020/07/28/aknkS1.gif)

### Specifications

v3.2.0

Firefox

**Comment by Sasha-Sorokin** [comment]
Related PR: #14380 (@ThibG)
