### ISSUE TITLE
New audio player has limited functionality in Safari

### ISSUE THREAD

**Issue by rodti** [tootsuite/mastodon#14462]
### Expected behaviour

Basic audio player functionality would work on all modern browsers.

### Actual behaviour

In Safari, audio loads as expected but elements of the audio player are not functioning.

Working:

- Audio
- Play/pause control
- Mute/unmute control
- Volume control

Not working:

- Progress/position control
- Visualisation
- Timecode (remains at 0:00)

In a current build of Google Chrome, the player functions as expected.

### Steps to reproduce the problem

1. Open a Mastodon instance in Safari
2. Post or view an audio file
3. Play the audio file

### Specifications

Found using:

Mastodon v3.2.0 running on mas.to
Safari v13.1.1
Chrome v84.0.4147.105

I appreciate this is likely a browser compatibility issue rather than an issue with the Mastodon codebase.

**Comment by ThibG** [comment]
Is there any error in the browser console?

**Comment by rodti** [comment]
![Screenshot 2020-07-28 at 18 28 38](https://user-images.githubusercontent.com/93992/88700135-2fc70a00-d100-11ea-8901-8bb246a5dc51.png)

Sorry, not sure how to copy/paste this as text, so a screenshot instead.

**Comment by rodti** [comment]
It appears that Safari expects `webkitAudioContext` instead of `AudioContext`.

See the accepted answer [here](https://stackoverflow.com/questions/29373563/audiocontext-on-safari).
