### ISSUE TITLE
Mechanism for detecting discrepancies and synchronizing followers

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#14480]
Over the years, there have been multiple bugs in Mastodon, Pleroma, and other software, as well as compatibility issues between those software, that may lead in good-faith instances disagreeing on who follows who.

The implications of this can range from annoying and confusing behavior (e.g., someone thinking they follow—or don't follow—someone but that not being true), to more serious implications: followers-only messages being shown to people that should not be considered followers anymore (that point would be solved by direct addressing of followers, but that wouldn't be 100% compatible with current versions of Mastodon, and has complicated performance implications).

Therefore, there should be a way for instances to detect discrepancies between their understanding of who is a follower of a remote account, and a way to automatically correct it. Unfortunately, that doesn't easily map to ActivityPub concepts.

Fundamentally, what we need is:
- a way for remote instances to notice their views on who follows who doesn't coincide.
  For instance, this could be a hash of the list of followers of an account residing on a specific instance, and this hash
  could be included in followers-only payloads to that instance.
- an endpoint listing followers residing on a given domain when queried by an account from that domain
  It would:
  * not list all followers, for both privacy and efficiency reasons
  * reply to any signed-fetch request from that domain rather than “the instance actor”.
    That makes sense, because there isn't anything specific about the “instance actor” which makes it uniquely identifiable, and we (Mastodon, but also Pleroma) already assume that the server is the only thing holding the user's private key at any point in time.

With something like that, when expanding the remote user's local followers, the receiving instance could at the same time verify the hash, and if it doesn't coincide, start a synchronization job, which would:
1. Send a signed query to the domain-followers endpoint
2. For any local followers not on that fetched list, remove it from the local followers
3. For any member of the fetched list that is not considered a follower, send an `Undo Follow`

EDIT: Note that such a mechanism would also be useful in the absence of bugs in the software. Indeed, hardware failures or migration fuckups have people occasionally revert backups. When doing so, the follower information may be out of sync across instances.
EDIT2: While it could make sense to re-use the followers endpoint for the “domain-followers” endpoint, I am not sure this is a good idea. Indeed, the purpose is slightly different, and we currently use the fact the followers collection cannot be paginated to record that this user doesn't want their known followers to be shown. Returning domain-specific followers would break that assumption.

**Comment by ThibG** [comment]
cc @lambadalambda @cwebber

**Comment by ThibG** [comment]
A more detailed—if rough—explanation of this idea would be that, upon sending a followers-only toot, Mastodon would insert a new destination-instance-specific property in the `Create` or `Announce` activity, it would look like the following:

```json
toot:followersSynchronization: [
  {
    "type": "toot:SynchronizationItem",
    "collection": "https://cybre.space/users/nightpool/followers",
    "domain": "mastodon.social",
    "hash": "...",
    "partialCollection": "https://cybre.space/users/nightool/followers?for_server=mastodon.social"
  }
]
```

Upon receiving this, the instance would go through the contents of `toot:followersSynchronization`, and for each collection, check that:
- `collection` corresponds to the sending user's followers collection (that could be later expanded to other collections i guess)
- the `domain` property corresponds to the receiving end (catching bugs before it is too late)
- that the `partialCollection` is on the same domain as the sender's other collections (avoids learning about another user's followers through tricks)

Then it would verify that the hash corresponds to what it knows about the followers collection of the remote user. If it doesn't match, it can start a synchronization job, which would:
- fetch the collection pointed at `partialCollection` (by signing the fetch with the instance actor)
- remove any local user not in that list
- for any account that *is* in the list but not considered a local follower, send an `Undo Follow`

This scheme is backwards-compatible, and with proper caching of the various hash values, the overhead should be negligible.

(Note that the vocabulary is very rough, I'm not very happy with it, and maybe there are even some properties already defined in AS that would make sense here)

**Comment by trwnh** [comment]
I can't help but think that this issue is just a symptom of a much larger issue -- that "followers-only" is a hack. Quite frankly, the authoring server should explicitly know who to deliver to. Follower calculation should happen at the origin and not at every single server that receives the message.

**Comment by ThibG** [comment]
@trwnh again, that's something (expanding at the origin server and delivering to individual followers) we could do in the future, but it's way less efficient, and also we can't currently do it correctly without breaking compatibility (if we do, some of those follower-only posts are going to be interpreted as DMs)

Furthermore, safer delivery would fix *some* of the problem, it wouldn't fix people believing they follow someone they don't actually follow, or the opposite.

**Comment by ThibG** [comment]
@trwnh the more I think about the followers collection being expanded at the origin, the more I'm uneasy with that, actually. For instance, it makes self-boosts of private toots more complicated to handle. Or, worse, I can't think how to revoke access to follower-only toots: currently, when someone stops following you (or get forcefully-removed), they lose access to all your followers-only toots in which they weren't directly mentioned. If followers-only toots were explicitly delivered to them with the followers-only collection expanded first, the receiving instance wouldn't be able to know they had access to it *because* they were a follower, so they wouldn't be able to revoke access to those toots. One might argue that it isn't that big of a deal, as one should assume that anyone receiving a message may have privately archived it anyway, but most people don't do that, so it would still make a significant difference.
