### ISSUE TITLE
500 Error when uploading media

### ISSUE THREAD

**Issue by Vibhigupta** [tootsuite/mastodon#14509]
`Aug 03 05:42:02 sinblr.com bundle[96320]: [4002c6ff-02d1-42fd-90af-e64aefb0f878] method=POST path=/api/v1/media format=*/* controller=Api::V1::MediaController action=create status=500 error='Seahorse::Client::NetworkingError: Net::ReadTimeout with #<TCPSocket:(closed)>' duration=5821.78 view=0.00 db=5.72`

i dont know how to fix this can someone point out what is the issue, everything was working but after reboot it doesnt

**Comment by Gargron** [comment]
> Seahorse::Client::NetworkingError: Net::ReadTimeout

This isn't a Mastodon issue it's an issue with your object storage provider, they're having an outage. Check their status page.

**Comment by Vibhigupta** [comment]
Im using scaleway and i have another instance that has same conifg and upload is working and there is no outage on there side

**Comment by oufmilo** [comment]
I've the same problem than you and i'm using scaleway too. I contacted scaleway and no problem for them.

**Comment by Vibhigupta** [comment]
@oufmilo Hello, There the problem was on there side and it took them three days to acknowledg that the problem is on there side. the support is shitty and doesn't respond quickly.

There is also an limit of 500k object, they said to spilit the bucket or we won't gonna provide support to you.
