### ISSUE TITLE
Emoji box background is too light

### ISSUE THREAD

**Issue by rhaamo** [tootsuite/mastodon#1451]
The background of the emoji box is pretty light making some emoji hard to differenciate the border of the emoji and the background.
I have the same issue with the integrated LCD of my laptop or external screen.
I propose to switch from ```#d9e1e8``` to something like ```#91a3b6``` (used dev-console color-picker to make an example), ex:
![emoji1](https://cloud.githubusercontent.com/assets/8625/24872722/ac672b96-1e1e-11e7-8795-884c43933950.png)![emoji2](https://cloud.githubusercontent.com/assets/8625/24872726/ae571740-1e1e-11e7-9a74-887d59789dfb.png)

What do you think ?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
Do a PR :)
