### ISSUE TITLE
WebUI crashes on  the Firefox for Android and slightly older the Firefox for Desktop

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#14511]
### Actual behaviour

#14484 or later, when you open the WebUI in Firefox for Android and a slightly older version of Firefox for Desktop, it cannot be displayed.

This happens with the latest version of Firefox for Android (v68.11.0) currently available on the Android 10 PlayStore.
However, Firefox Beta for Android (79.1.0-beta.1) and Firefox Nighty for Android (Nighty 200803 06:07), which are also published, do not have any problems.

Also, it seems that it cannot be displayed on Firefox for Desktop v77 as well.
(Current latest version is v79.0)

This issue seems to occur because those versions don't support the "Unicode property escapes (\p{...})".
ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Browser_compatibility

This is an unreleased version issue.
I think it depends on when Firefox for Android is updated.

**Comment by kedamaDQ** [comment]
I'm sorry about  I overlooked the browser compatibility of Firefox for Android.
