### ISSUE TITLE
API Follow isn't working

### ISSUE THREAD

**Issue by NicolasConstant** [tootsuite/mastodon#1454]
I'm trying to use the follow/unfollow functionality of the mastodon API, and I always get back a NotFound status code. 

I'm using the route provided in the documentation (**GET /api/v1/accounts/:id/follow**), is the documentation still updated/valid for those operations?

**Comment by mattjmattj** [comment]
The web client uses a POST request, not a GET. My guess is that the documentation is out of date/wrong

**Comment by R0ckweb** [comment]
Can you try with POST method ?

**Comment by R0ckweb** [comment]
Yes documentation is wrong.
I will update this with a pull request.

Tips : 
You can see available routes  on your instance with this commande : 
`RAILS_ENV=production bundle exec rake routes`
En maybe 
`RAILS_ENV=production bundle exec rake routes | grep "/api/v1/" `
