### ISSUE TITLE
There should be a way to disable all sounds for any notification

### ISSUE THREAD

**Issue by konomikitten** [tootsuite/mastodon#14557]
### Pitch
From what I can currently tell of Mastodon you can only suppress notification sounds (toggling the "Play sound" setting in the notifications tab) for "New followers", "New follow requests" and "Favourites". It would be far more useful to also be able to disable notification sounds entirely.

### Motivation
Personally I don't want to hear sounds for every reply, direct message or mention or any notification for that matter, I just want my usual silent desktop notification and I believe many other users would also want this to be the case.

**Comment by Cassolotl** [comment]
My notifications column has way more notification sounds than that!

![Screenshot 2020-08-11 at 07 51 02](https://user-images.githubusercontent.com/6607512/89866458-79efc700-dba7-11ea-8276-e0f89ab7d3c8.png)

**Comment by konomikitten** [comment]
> My notifications column has way more notification sounds than that!

Okay so I feel a bit silly, I didn't realise the options scroll down... I'll confirm the sounds stop and then I'll close this bug report if they do.

**Comment by Cassolotl** [comment]
>I didn't realise the options scroll down

Literally did the same thing back when I was new! :D

**Comment by konomikitten** [comment]
I haven't heard any sounds since I switched off all the sound sliders in the notifications tab, so I'm closing this bug report now. Oddly Direct Messages seem to come under Replies? That's a little strange I could see people wanting a slider for Direct Messages too.

**Comment by TerryCavanagh** [comment]
Hello 👋 

This is the first thing that pops up on google when you search "mastodon disable sounds", so I am posted this here for the next person who arrives via google. In April 2022 Mastodon makes a chirp sound whenever a notification happens. There is currently no option to disable this:

![image](https://user-images.githubusercontent.com/2874150/165091004-9622478d-03ba-46a5-8d88-02fa6fc2d050.png)

Any suggestions?

**Comment by TerryCavanagh** [comment]
Found it. For future googlers, there's a separate settings page on your notification tab:

![image](https://user-images.githubusercontent.com/2874150/165100845-44133486-fac7-4b98-8a83-b2bd9539265a.png)

**Comment by ell1e** [comment]
Maybe the Preferences > Notifications section should have an additional button that redirects you to the Notification tab preferences? This is really hard to miss and I don't think it would need to be.

**Comment by bohwaz** [comment]
Took me 3 years to figure out that:
1. it was not in the preferences page
2. you had to scroll to see more settings in a confusing list of stuff

So yeah it clearly needs to be easier to find :)

**Comment by tanepiper** [comment]
+1 - this is the top post to tell people how to turn this off - with the Twitter migration I guess lots of people will be wondering how.

**Comment by stefanct** [comment]
This should be reopened since it is actually a valid request that is not solved yet. You still have to click half a dozen buttons in a hidden menu to disable something that should never have been enabled by default. It's the single most disappointing thing I have seen in Mastodon so far that I am sure will piss off quite a lot of people if they ever try it out.

**Comment by jdaviescoates** [comment]
Moreover, I've turned all the Play Sounds sliders off, but I'm still getting sounds!

![image](https://user-images.githubusercontent.com/2113743/200078470-c53f51fe-2e72-4e77-8b0f-572dd1f6dce3.png)

So, at least for me on Ubuntu and Firefox turning the sounds off appears to not be possible :(

**Comment by chriskorosu** [comment]
> Found it. For future googlers, there's a separate settings page on your notification tab:
> 
> ![image](https://user-images.githubusercontent.com/2874150/165100845-44133486-fac7-4b98-8a83-b2bd9539265a.png)

It's not easy to figure out how to access the sound settings from the provided screenshot/description, so here are more detailed instructions:

- go to Mastodon homepage
- click the Notifications button on the right
- click the settings icon on the right of the middle frame (highlighted in the screenshot below)

![image](https://user-images.githubusercontent.com/47898552/200506501-42cd284d-9f62-4271-8408-0393e9532a82.png)

**Comment by SamStephens** [comment]
I've created #20359 to address the discoverability of notification settings, and #20360 to address how much work it is to disable all notifications. Upvote either or both issue if you care about them 😁

**Comment by jdaviescoates** [comment]
> I've created #20359 to address the discoverability of notification settings, and #20360 to address how much work it is to disable all notifications. Upvote either or both issue if you care about them grin

Thanks for those!  There is also seemingly an issue the turning all the sounds off just doesn't work on Ubuntu/ Firefox, so I guess I should create another issue for that as well...

**Comment by Mela** [comment]
> 

You're a lifesaver.
