### ISSUE TITLE
Rake action for creating a user

### ISSUE THREAD

**Issue by codl** [tootsuite/mastodon#1456]
#146 mentions manually creating user accounts in the administrative UI, which sounds very nice, but until that's done it would be nice to have a rake action to create a user and send them a password reset email, as a temporary solution for people who want to close registration and invite people manually onto their server

(I was going to do this myself but I don't know activerecord well enough & ended up spending a couple hours battling with it to no avail 😓)

**Comment by wxcafe** [comment]
If someone knows how to do rake, this should probably be very easy - it's literally two inserts in the postgres DB

**Comment by Gargron** [comment]
Fixed by #1482
