### ISSUE TITLE
Should whitelist mode also show field `outbox` in activitypub?

### ISSUE THREAD

**Issue by OmmyZhang** [tootsuite/mastodon#14569]
I can't follow/be followed by accounts on Plume from mastodon when whitelist_mode is enabled, because that there's no outbox url so that Plume can't create a remote user. (but articles can still show in the federated timeline if users on the third instance who followed by users on whitelist_mode instance commented on this article)

I'm not sure if it's a bug of Mastodon or a bug of Plume. Is there any standard in activitypub protocol related to this?
Anyway, outbox url seems not some sensitive information.

Here is the related code:
```ruby
def restrict_fields_to
    if signed_request_account.present? || public_fetch_mode?
      # Return all fields
    else
      %i(id type preferred_username inbox public_key endpoints)
    end
  end
```
What if change to this?
```ruby
def restrict_fields_to
    if signed_request_account.present? || public_fetch_mode?
      # Return all fields
    else
      %i(id type preferred_username inbox outbox public_key endpoints)
    end
  end
```

**Comment by Gargron** [comment]
> I can't follow/be followed by accounts on Plume from mastodon when whitelist_mode is enabled

Unless the Plume instance is approved this is working as intended. If it is approved then the problem would be that Plume does not sign its GET requests, otherwise Mastodon would return the full actor. For key verification, outbox is not necessary.

**Comment by OmmyZhang** [comment]
@Gargron thanks.

**Comment by ThibG** [comment]
Actually, `outbox` is required in the spec: https://www.w3.org/TR/activitypub/#actor-objects
