### ISSUE TITLE
"Boost to original audience" is worded poorly

### ISSUE THREAD

**Issue by 3n-k1** [tootsuite/mastodon#14596]
### Pitch

i believe that "Boost to original audience" is worded somewhat poorly and can be confusing to users. i suggest replacing it with something like "boost with original visibility" instead, to be more clear about what the action actually does

### Motivation

i've seen multiple users on my tl confused about the meaning of "Boost to original audience". the most recent toot i've seen regarding this is as follows (reproduced with permission):

"How does boosting follower only poste work? It says "original audience" which implies that only people who were following you at that point see it, but sometimes I see new followers reply to it, meaning they can see it, so??? What,"

a quick grep in the mastodon source code tells me that this could be changed with a quick sed command, but before sending a pr i wanted to get input on whether this was a welcome change

**Comment by 3n-k1** [comment]
hit enter too soon, gimme a sec to edit ^^"

**Comment by fuck-dot** [comment]
hell yeah that idea slaps

**Comment by 3n-k1** [comment]
@fuck-dot that's the best thing anyone's ever said about one of my ideas lol

also if anyone has any better suggestions for what to change the string to, please let me know!

**Comment by 3n-k1** [comment]
hey, we got it merged!
