### ISSUE TITLE
One toot, three views.

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#14607]
### Expected behaviour

The first should link to the third image. Keeping me in the webpage on the same tab instead of jumping to weirdo public view.
the stars should be visible in my feed

1) the star count is missing in 1/3 views
2) the link should jump straight to the "web view" instead of that weird middle "public" view for logged in users.
3) wtf does `open in web` even mean?

### Actual behaviour

My toot in the feed
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/17537000/90722397-53d7ce80-e2ed-11ea-8dfc-4a9ed7808ce2.png">

My toot clicking the link on the date
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/17537000/90721837-35bd9e80-e2ec-11ea-8851-770a1d0f9b26.png">

My toot after clicking `open in web`
<img width="944" alt="image" src="https://user-images.githubusercontent.com/17537000/90721871-4cfc8c00-e2ec-11ea-8471-6a3227b7add7.png">

### Specifications
3.2.0

**Comment by ThibG** [comment]
1. it's deliberate to only show the count on detailed view
2. what link are you talking about?
3. “web” in the context of Mastodon has always meant the WebUI. I do find it confusing though.

**Comment by shleeable** [comment]
1) Boo
2) <img width="48" alt="image" src="https://user-images.githubusercontent.com/17537000/90733599-5c390500-e2ff-11ea-8882-fbd0dfc5a790.png">

The whole clicking the toot creating a new tab in a weird view makes no sense to me.

**Comment by bluss** [comment]
I agree that the difference here is not straightforward. If the status is not local, it seems that (2) and (3) will link to different instances - (2) to the home instance of the status, and (3) is the web view on the current instance.
