### ISSUE TITLE
Import Profile settings Error 500

### ISSUE THREAD

**Issue by Happyfeet01** [tootsuite/mastodon#14617]
Hello,

today i installed successfull Mastodon on my Server, but i have two issues.
Federation search doesnt work, but Elasticsearch is enabled.

when i enter this Site https://domain.tld/settings/aliases and would migrate an existing Account from an other Server i get an Error Page.

It seems the DB has an missing table: 

`ActionView::Template::Error (PG::UndefinedTable: ERROR:  relation "user_invite_requests" does not exist`

Here is the Web log:

https://paste.dasnetzundich.de/view/992198ae

`eb_1        | [c609e19d-2c81-4d29-91b6-7fd922cf70fc] method=POST path=/settings/aliases format=html controller=Settings::AliasesController action=create status=500 error='Aws::Sigv4::Errors::MissingCredentialsError: missing credentials, provide credentials with one of the following options:
web_1        |   - :access_key_id and :secret_access_key
web_1        |   - :credentials
web_1        |   - :credentials_provider' duration=3443.70 view=0.00 db=7.29
web_1        | [c609e19d-2c81-4d29-91b6-7fd922cf70fc]  
web_1        | [c609e19d-2c81-4d29-91b6-7fd922cf70fc] Aws::Sigv4::Errors::MissingCredentialsError (missing credentials, provide credentials with one of the following options:
web_1        |   - :access_key_id and :secret_access_key
web_1        |   - :credentials
web_1        |   - :credentials_provider):`

whats wrong?

**Comment by ThibG** [comment]
The first error seems to indicate you have not properly set up your database. I don't know how you installed your instance, but maybe try running `bundle exec rails db:migrate`.

The second error seems to indicate a misconfiguration of your storage server. Do you use a S3 server? Can you check your configuration (`.env.production`)?

**Comment by Happyfeet01** [comment]
> The first error seems to indicate you have not properly set up your database. I don't know how you installed your instance, but maybe try running `bundle exec rails db:migrate`.
> 
> The second error seems to indicate a misconfiguration of your storage server. Do you use a S3 server? Can you check your configuration (`.env.production`)?

I need an external Storage Server?

**Comment by ThibG** [comment]
> I need an external Storage Server?

No you don't, but it looks like it's trying to use one. Do you have `S3_ENABLED=true` or something in your `.env.production`?

**Comment by Happyfeet01** [comment]
Okay. I set the external Drive to false and all issues are gone. I can set an alias for my account.

But the federation view is empty. Must I follow persons to fill it?

**Comment by ThibG** [comment]
The federation view is populated with public posts known to your instance. And yeah, if you don't follow/interact with anyone, your instance does not know about any public post.

**Comment by Happyfeet01** [comment]
I found the solution with the proxies
