### ISSUE TITLE
I lost my follower count but not my followers by removing some of my followers

### ISSUE THREAD

**Issue by Hund** [tootsuite/mastodon#14667]
I used to be an admin at an instance where new accounts would automatically follow the instance admins. I have since then moved to another instance (fosstodon.org) and a few days ago I decided to clean up some of my followers who has not been active for years.

I could mark whole pages and choose to delete marked accounts (using the default web interface). I can't know for sure how many I deleted, but it should have been somewhere around 500 to 1000 accounts. When I was deleting pages at the time I was suddenly met with "no followers" or whatever the exact wording was. I refreshed the page assuming it was some glitch, but no. I visited my profile and it said 0 followers, but when I clicked on my zero follower count it would still list the remaining followers that I still have.

I made a post and it did indeed show up for my followers, at least some of them, I can't confirm with every one of them.

When one of them replied they instantly started "following" me again. I at least got a notification saying say, even though the user was following me the whole time. It happened again for another person, but not for the rest who has interacted with the over the past two days or so.

What could have gone wrong here? Is there something I or the admins of the instance could do about it?

**Comment by Hund** [comment]
I guess this is not a prioritized bug.

**Comment by Gargron** [comment]
The sysadmin can run `tootctl cache recount accounts` to fix the cached number of followers.

The source of the bug remains unknown. I was not able to reproduce the conditions under which it occurs in the test environment. Ultimately, yes, if it's just the number being wrong, it is not a priority, though it would be nice to fix it.

**Comment by Hund** [comment]
Thanks! That solved it for me. :)
