### ISSUE TITLE
/settings/featured_tags is slow for an account with many toots due to "most used tags" query

### ISSUE THREAD

**Issue by akihikodaki** [tootsuite/mastodon#14661]
### Expected behaviour

`/settings/featured_tags` is fast enough regardless the number of the toots the user posted.

### Actual behaviour

`/settings/featured_tags` is slow for an account with many toots because the page queries most used tags for all the toots.

The behavior may also be suboptimal in terms of the user experience. A user is unlikely to pick a tag which the user used to include in toots a long time ago. For performance, limiting `statuses.id` is preferred, but the details of such limit can involve more considerations. I would appreciate if you share some idea or opinion.

### Steps to reproduce the problem

1. Toot many times.
2. Open `/settings/featured_tags`

### Specifications

Reproduced on 2.9.4. The code with this problem is still present at `master`. (9cadd40cf4e52a299ba828e84b6a4fddaf976afb)

**Comment by abcang** [comment]
For your reference, I've included a temporary fix in Pawoo.
https://github.com/CrossGate-Pawoo/mastodon/commit/2124dbaa55133359dc4d32c075b950182c7fb9bc

**Comment by ThibG** [comment]
> For your reference, I've included a temporary fix in Pawoo.
> [CrossGate-Pawoo@2124dba](https://github.com/CrossGate-Pawoo/mastodon/commit/2124dbaa55133359dc4d32c075b950182c7fb9bc)

I think this is fine. It probably doesn't make sense to suggest tags appearing only in very old toots anyway. Could you submit this in a PR?

**Comment by abcang** [comment]
I submitted a pull request. #14760
