### ISSUE TITLE
Block by settings.two_factor_auth

### ISSUE THREAD

**Issue by yolateng0** [tootsuite/mastodon#1466]
If you do not disable the option  settings.two_factor_auth without validating the procedure.
After you can't connect without removing this option.
thereby you can't connect to my account even with a new password.

**Comment by Gargron** [comment]
Sorry, I don't understand. What do you mean?

**Comment by wxcafe** [comment]
If you enable 2FA on the server and don't set up something to make it actually work on your phone or whatever, it will lock you out, yeah. Ask your admin to remove 2FA from your account in the database.

**Comment by yolateng0** [comment]
sorry for my english
In the preferences menu, I activated the option " Two factors -auth "without concluding the process.
So I am stuck at the login page...
Also, someone give me a possible solution. I will inquire with the system administrators of my instance Mastodon.
best regard

**Comment by yolateng0** [comment]
sorry this is the solution...in mastodon/doc :-( @Gargron 
https://github.com/tootsuite/documentation/blob/eebeee2b76f269cd26e420cbe78467ae8f824749/Using-Mastodon/2FA.md

"Warning
If you lose access to your 2-factor authentication (such as by losing your phone or performing a factory reset) and you do cannot log in, you will not be able to access your account and will need to contact an instance admin to remove 2-factor authentication from your account."
