### ISSUE TITLE
[Security] Webauthn asks for Windows Hello PIN instead of Yubikey

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#14714]
### Expected behaviour

Windows should ask for my Yubikey for Webauthn

### Actual behaviour

Windows asks for my Windows Hello PIN and doesn't give me an option to use my Yubikey instead. This is especially bad if you have multiple devices (and it probably won't check if the PIN is correct if you use another device with a different PIN making 2FA useless). Other websites like namecheap.com do this perfectly fine.

### Steps to reproduce the problem

0. Have a Windows 10 install
1. Enable 2FA and add a key

### Specifications

Mastodon version: latest `master`
OS & Browser: Google Chrome 85.0.4183.83 on Windows 10.0.19041.450

**Comment by nightpool** [comment]
This might be an issue with Chrome—browsers should give you the opportunity
to use a non-default security key, even if your OS wants you to use a
specific one

**Comment by koyuawsmbrtn** [comment]
nvm, just click abort and it will offer you to use your hardware key
