### ISSUE TITLE
Make Mastodon GDPR-Compliant

### ISSUE THREAD

**Issue by Viomi** [tootsuite/mastodon#14718]
### Pitch

Currently, Mastodon has a feature that allows instance admins to delete **all** of a user's data when they are banned. This is a violation of GDPR, as one cannot delete user data without their consent. You can _hide_ it from public view, or remove it from the public facing profile, but the data must remain accessible for the user to download, either as an archive on the site or by emailing the data to the user immediately (if this data does not make it to the user for whatever failure in E-MAIL, you will still be violating the GDPR).

I suggest that the admin-side functionality to delete a users' data is revoked entirely due to instance admins being unlikely to understand GDPR. Instead, make it so a banned user can always download their data, and then once it has been downloaded the first time the instance will automatically _then and only then_ delete the data off the server.

Yes, this does mean banned users could just never download their archive and over time instance admins will have to increase their storage space to accommodate GDPR. There is not a solution to this without violating consent of users' data rights. However, seeing as GDPR fines are expensive compared to storage costs, I'm sure people will be fine.

### Motivation

Literally anyone who uses this feature is committing a violation of GDPR and could get fined large amounts of money.

**Comment by Viomi** [comment]
https://gdpr-info.eu/issues/consent/

Specifically, Article 6:
https://gdpr-info.eu/art-6-gdpr/

Definition for 'processing', provided by Article 4:

> ‘processing’ means any operation or set of operations which is performed on personal data or on sets of personal data, whether or not by automated means, such as collection, recording, organisation, structuring, storage, adaptation or alteration, retrieval, consultation, use, disclosure by transmission, dissemination or otherwise making available, alignment or combination, restriction, erasure or destruction;

**Comment by Viomi** [comment]
@Gargron I do not wish to report your software and you + your website, mastodon.social, for violating GDPR against me at 4:45PM PST today. You should check this Issue.

**Comment by nightpool** [comment]
Hi Viomi, I'm closing this ticket for three reasons:

### 1. The Mastodon software project is not a data processor or controller

While Mastodon does provide a "delete my account" and "export my data" feature, it itself cannot satisfy or violate the GDPR on its own, only enterprises that use Mastodon can satisfy or violate the GDPR (personal and household processing is exempt from the GDPR). We provide these features as conveniences to admins that may be subject to data processing regulations (including, but not limited to, the GDPR and the CCPA) but the ultimate responsibility for satisfying legal obligations rests solely with the admin in question. Although it's true that Gargron is an admin of both this project and one of the Mastodon instances in question, the majority of the admins of this project have nothing to do with the running of https://mastodon.social and cannot respond to complaints regarding such. This Github issue tracker is an inappropriate place to raise such an issue. For questions about mastodon.social specifically, you'll need to email the staff contact listed on their about page: https://mastodon.social/about/more

If it _is_ true that the GDPR forbids businesses to delete the data of users they no longer wish to do business with, which I would be very surprised by, admins could use the "Disable login" feature to satisfy this requirement, if they believe it may apply to them.

### 2. Suspension of users does not require the user's consent

Data may be processed under the GDPR for a variety of legitimate purposes, of which consent is only one. For example, the legitimate interest of the data controller may be a ground for processing. Another grounds for processing may be the protection of the vital interests of another natural person, or for complying with legal obligations.

In this case, for the vast majority of suspensions, the Mastodon instance in question has a legitimate interest of preventing harassment, ensuring civility, ensuring its reputation, etc etc. And the GDPR, especially the recitals, is very very clear that you should destroy data you no longer expect to use, which is clearly the case in a permanent suspension. Requiring businesses to retain data on users that they no longer expect to interact with is a clear violation of the principle of Data Minimisation and Storage Limitation (Art 5).

### 3. Deletion of the data by Mastodon does not imply that instances aren't able to comply with requests for data portability

Many Mastodon instances keep backups. Although you no longer can easily log in and request an export from an instance which you've been suspended from, the data in question is possibly still accessible by the admin in question if you send them a specific request for it, satisfying the GDPR's Right of Data Portability. (As a side note, backups are generally processed under the Overriding Legitimate Interest of Network and Information Security, as outlined in recital 49)
