### ISSUE TITLE
Darker Text for "Whats on your mind" in Toot composer in High Contrast Theme mode - visibility issue

### ISSUE THREAD

**Issue by bull500** [tootsuite/mastodon#14717]
Would be a good bonus on visibility if the text in the toot composer is switched to a darker color, since the grey kinda blends into the white background and makes it difficult to read esp on laptop displays

![image](https://user-images.githubusercontent.com/8917275/91889686-d8422e00-ecab-11ea-925b-ea2385774b65.png)

**Comment by ThibG** [comment]
Hmm this seems to occur in the **High contrast** theme rather than the **Dark** theme, right?

**Comment by ThibG** [comment]
This seems to only occur with `.autosuggest-textarea__textarea::placeholder` and `.spoiler-input__input::placeholder`. The `$dark-text-color` color is a bad fit for it in the **High contrast** theme.

**Comment by bull500** [comment]
ah yes my bad. You are right @ThibG its the "Mastodon(High Contrast)" theme
