### ISSUE TITLE
Duplicate data on 2-3 instances of Mastodon to ensure backup

### ISSUE THREAD

**Issue by Dryusdan** [tootsuite/mastodon#1474]
Hi
Today, I talk with other folk (I'm too talkative :x ) and lot of ask me a question : if the instance closed inexplicaly, we lost all data no ? So, why not duplicate with blockchain / P2P / IPFS instance in other instance (with admin and user agree ?)
User know what other instance is save his data and if server is closed, user receive mail for his other instance.
For SysAdmin it's permit ensure backup :)

**Comment by wxcafe** [comment]
This is not the way federation works. It's not going to be implemented right now, and probably not ever. I'm closing this issue.
