### ISSUE TITLE
More than one scheduler job run in multi-host setups

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#14764]
### Expected behaviour

Each scheduler job, e.g. "daily user clean-up", is run once per day at a random time.

### Actual behaviour

Scheduler jobs may run more than once in setups where there is more than one Sidekiq process. Each Sidekiq process starts its own scheduler and evaluates scheduler configuration. The scheduler configuration includes randomization of hour, day, or minute, which when evaluated by different processes yields different results. So the different schedulers queue jobs at completely different times of day/week. sidekiq-unique-jobs can only guard against jobs executing at the same time.

### Steps to reproduce the problem

Run more than one Sidekiq process.

### Specifications

The bug exists in all versions of Mastodon.

**Comment by Gargron** [comment]
There are two approaches that could solve this problem:

1. Add environment variable that disables the scheduler in a given process. Recommend sysadmins to designate one Sidekiq process to contain the scheduler, and disable it in all other processes.

2. Consensus protocol that allows all running Sidekiq processes to "elect" one to be the scheduler.

**Comment by gentcys** [comment]
Another approach is using Redis [set key with NX option](https://redis.io/commands/set)

**Comment by gentcys** [comment]
What about specifying a fixed time of execution for scheduler? Then let [sidekiq](https://github.com/moove-it/sidekiq-scheduler#notes-about-running-on-multiple-hosts) do this work.

**Comment by noellabo** [comment]
I've pull-requested one solution https://github.com/tootsuite/mastodon/pull/15314 : use the sidekiq-scheduler's own functionality to select the sidekiq process that will handle the scheduled execution based on the queue to be processed.

config/sidekiq.yml
```
:scheduler:
  :listened_queues_only: true
```

Since we are introducing a new queue, we need to select or add a sidekiq process that will allow scheduled execution. Nothing needs to be done if sidekiq is a single process.

**Comment by smiba** [comment]
Does anyone know if this is still an issue in Mastodon v4.5? 

Having some discussion about this and I can't figure out a definitive answer. It seems that [sidekiq-scheduler](https://github.com/sidekiq-scheduler/sidekiq-scheduler) seems to say it's fine (with some caveats like CPU not extremely overloaded or high Redis latency), but I can't figure out a definitive answer. 

Would be nice to know as it simplifies configuration
