### ISSUE TITLE
Signup Error: "This email provider is not allowed"

### ISSUE THREAD

**Issue by marbetschar** [tootsuite/mastodon#14771]
I tried to register a new account at mastodon.online, but I'm unable to signup. Mastodon claims "This email provider is not allowed". I use my own, private domain for emailing, why is it not allowed to use such an email address?

![email-not-allowed](https://user-images.githubusercontent.com/392542/92875794-ab0f2180-f409-11ea-96df-fcf2cfc5bdb1.PNG)

**Comment by ThibG** [comment]
Have you by any chance set one of the following environment variables?
- `EMAIL_DOMAIN_DENYLIST`
- `EMAIL_DOMAIN_BLACKLIST`
- `EMAIL_DOMAIN_ALLOWLIST`
- `EMAIL_DOMAIN_WHITELIST`

**Comment by Gargron** [comment]
This is an end-user report, mastodon.online belongs to me. I have not blocked marco.betschart.name consciously, so either something is wrong with MX resolution or I have mistakenly blocked a mail service IP that this provider happens to also use.

**Comment by ThibG** [comment]
Oh, indeed, sorry about that. That domain name's mail is handled by yandex so it's likely yandex itself has been blocked.

**Comment by marbetschar** [comment]
@ThibG thats correct; the Domain is handled by Yandex. Why is it blocked?

**Comment by Gargron** [comment]
I've unblocked the MX IPs on mastodon.online

> Why is it blocked?

Well, someone else using a custom domain that pointed to those IPs was creating loads of fake accounts. I was not aware those IPs belonged to Yandex.

**Comment by marbetschar** [comment]
@Gargron thanks for the quick help response. But for some reason I'm still not able to signup with this email address at mastodon.online

The same error message still appears.

**Comment by marbetschar** [comment]
any news on this?

Sorry, if the GitHub Issue tracker is not the right spot to ask such a questions - but I can't see any support/contact possibility on mastodon.online

**Comment by Gargron** [comment]
OK, looks like the MX look-up tool I used previously didn't return *all* IPs for your domain. Now for sure all of them should be unblocked. Sorry.

**Comment by marbetschar** [comment]
@Gargron thank you very much - it worked! 🎉️👍️

**Comment by amarendra** [comment]
My email provider is https://mailbox.org. 

I am not able to use my own domain as `<email>@amarendra.net`, however I can use `<email>@mailbox.org`.
