### ISSUE TITLE
Brand Accounts

### ISSUE THREAD

**Issue by danrabbit** [tootsuite/mastodon#1478]
I'd like to give permission to other Mastodon users to tweet from my brand account so that we don't have to share passwords and constantly log out and in between the brand account and our personal accounts. This would be a killer feature over Twitter.

**Comment by rhaamo** [comment]
Is this the same issue as explained in #1405  ?

**Comment by danrabbit** [comment]
@rhaamo Ah I think you're right. I skipped past then when searching because I have no idea what "local account delegation" means :p Maybe it would be good if a bug manager can update the title to something human readable.

Closing this report as a dupe :)
