### ISSUE TITLE
Home Timeline, Notifications and incoming DMs visible after logout

### ISSUE THREAD

**Issue by clarjon1** [tootsuite/mastodon#14816]
### Expected behaviour

When a user logs out in a second tab, the user's Home timelines and notification should be stopped.

### Actual behaviour

When a user logs out in a second tab, if the user has another tab open, their regular Home timeline can be read, and notifications for boosts, favs, replies, private messages show up as if the user is still logged in.

### Steps to reproduce the problem

1. Open a Masto instance in two tabs
2. Log out of instance in one tab.
3. Have someone DM you 
4. Observe as you can read the DM in the tab left open despite the auth cookie being invalidated by logging out.

### Specifications

3.2.0 vanilla masto and previous versions

I've done testing and found that this affects glitchsoc and masto-fe/glitch-fe for pleroma. 

It may be worth looking to the pleroma-fe project for considering methods of handling this case, as repeating these steps in pleromafe results in a "Forbidden" error in the second tab, immediately stopping timeline updates and notifications: 

![image](https://user-images.githubusercontent.com/627845/93655067-582c0000-f9ef-11ea-914e-a2b2fc9d2f6c.png)

**Comment by Gargron** [comment]
I suspect that the only reason you are able to receive new content in the other tab is that you are still connected to the streaming API. The streaming API checks credentials when a connection is established, not continuously while it is alive. I'm not sure if Pleroma has a streaming API at all or if they just regularly poll a REST API, so the situation may not be comparable.

**Comment by Gargron** [comment]
I think we need to detect when an access token is no longer valid for an already established streaming API connection, but not sure of the frequency. On each incoming message could be very wasteful as they can come in very rapidly. Perhaps simply in even intervals would be enough, they don't even have to be short intervals as long as a revoked access token *eventually* kills a connection. Like maybe 5-10 minutes?

**Comment by ThibG** [comment]
An alternative might be to notify the streaming server of session invalidation with a new event?
