### ISSUE TITLE
Add an option to show DM's in the timeline

### ISSUE THREAD

**Issue by neonpixii** [tootsuite/mastodon#14814]
### Pitch

Have an option in the dropdown timeline setting menu to show DM's in the timeline the way they used to appear in earlier versions of mastodon.  masto DM's are not actually DM's, they're just posts with a very limited audience, so hiding them away in a menu that requires 3 clicks to get to is deeply annoying.

### Motivation

its the way mastodon used to work, and by hiding DM's away in a secondary menu, all you've done is make them worse and less intuitive to use, because the menu is VERY janky and extremely confusing in when and how it shows DM's

having at least the option to show them in the timeline like they used to appear would make mastodon far less confusing to use and far more internally self-consistent.

**Comment by Gargron** [comment]
DMs are back to showing in home in the master branch.
