### ISSUE TITLE
No Information available about what version of Font-Awesome is being used

### ISSUE THREAD

**Issue by attachedComposer** [tootsuite/mastodon#14820]
We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please use one of the resources below:

- https://discourse.joinmastodon.org
- #mastodon on irc.freenode.net

I've been tweaking my instance, and found out recently that both discord and patreon have font-awesome icons in Free in v5, however when calling those icons, they do not appear. 

Which version of font awesome is mastodon using, and is there a way to use v5 free?

**Comment by Gargron** [comment]
v4.7. The v5 icons don't look good in the UI at all, already tried.

**Comment by attachedComposer** [comment]
okay, still wouldn't mind to ability to modify it on my end, but if i know the version at the very least i can find replacement icons
