### ISSUE TITLE
Direct message should not show in timeline

### ISSUE THREAD

**Issue by mashirozx** [tootsuite/mastodon#14864]
### Expected behaviour

In the past Direct message won't show in TL, but in latest commit (I guess issue in 65760f59df46e388919a9f7ccba1958d967b2695 actually?) it shows in home time line. It's pretty confussing.

### Actual behaviour
![image](https://user-images.githubusercontent.com/16148054/94195821-19fa7900-fee6-11ea-9967-b882add9f0d7.png)

**Comment by ThibG** [comment]
This is a deliberate change made in #14711.

**Comment by mashirozx** [comment]
Oh, got it
