### ISSUE TITLE
Mac Keyboard Shortcut Conflict: Tilde and New Toot

### ISSUE THREAD

**Issue by benhamill** [tootsuite/mastodon#14862]
There is a conflict between the keyboard shortcut for starting a new toot (`alt-n`) and the way macOS allows users to add a tilde diacritic to characters (e.g. you can type "ñ" with `alt-n n` or "õ" with `alt-n o`). The result is that trying to type, say, the word "español" in the input box ends up with just "ñol". This seems like a big bother for localization for folks who use US keyboards, but want to type Spanish (or other languages that use this diacritical mark).

### Expected behaviour

When any text input box is focused, typing `alt-n` will append a ˜ to your existing input so you can pick a character for it to modify (standard macOS behavior).

### Actual behaviour

When the new toot text box is focused, typing `alt-n` clears the existing input before the ˜ is inserted and you can pick a character for it to modify.

### Steps to reproduce the problem

1. Begin composing a new toot.
1. Type `e s p a alt-n n o l`.
1. Observe that the characters "espa" were deleted when `alt-n` was pressed.

### Specifications

Firefox 80.0.1. MacOS Mojave 10.14.6. I expect this will happen across a wide variety of browsers and versions of macOS because `alt-n` has been the tilde shortcut for the OS for a long time. I'm not sure if there's a way for random users to get their instance's version of Mastodon, but I'm on eldritch.cafe and I think it's pretty up-to-date.

**Comment by benhamill** [comment]
As a follow-up, on macOS, alt is used in combination with a _lot_ of different keys to get a wide range of useful characters. E.g. `alt-e i` is "í", `alt-;` is "…", `alt-2` is "™" and `alt-8` is "•" just to name some of the ones I personally use very often. So I think rather than thinking of `alt-n` as a special case, it might be better to approach this from a standpoint of bypassing _all_ the alt-based keyboard shortcuts when a text box is focused so as not to interrupt typing.

**Comment by TixieBorg** [comment]
Same situation here (also on Firefox MacOS), pretty annoying.

Also if it can help, I've tried on Chromium 86 and Safari 14 and I don't have the issue, only on Firefox (83).

**Comment by miramarco** [comment]
I can confirm this behaviour on Firefox 81.0.1, also on Mojave, and on a Mastodon instance running v3.2.0.

I could find only one other documented alt-based hotkey: `alt-x`, which shows/hides the CW field, but it also corresponds to † on some macOS keyboards (I am using the Italian one). Differently from `alt-n`, the † cannot be typed in at all, whereas ˜ does show up as the first character of the new toot.

**Comment by benhamill** [comment]
Yay! Thanks, @ThibG! 💖
