### ISSUE TITLE
Toots with the '%' character do not federate

### ISSUE THREAD

**Issue by technoboy10** [tootsuite/mastodon#1489]
Toots from the API or the web client which include the '%' character do not federate across instances.

**Steps to replicate:**
* Create an account on another instance (I used adventoot @ botsin.space) and follow it on your main account (qonnyr @ mastodon.social)
* On the secondary account, toot something without the '%' character and verify that it appears in your main account timeline
* Toot something that includes the '%' character (like '100%')
  * This toot will never appear in your timeline
  * However, you *can* see the toot by going to the secondary instance and viewing that account's profile

I tested this by following connor@skobuffs.club and adventoot@botsin.space from qonnyr on .social and toots with '%' consistently failed to federate.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
It looks like creating a non-% containing one triggers them all to be read, and will pull them in.

I wonder if the instance where they live is not pinging on those for some reason, but then once one is created without a % it does ping, and then they all get pulled.

**Comment by technoboy10** [comment]
Interesting - I didn't see that behavior on the adventure bot when it would occasionally make a non-% status but it's certainly possible I could have missed something.

**Comment by Gargron** [comment]
This does not seem to be an issue anymore, closing unless it comes up again
