### ISSUE TITLE
Please add a feature to choose whether using swipable view

### ISSUE THREAD

**Issue by pullopen** [tootsuite/mastodon#14905]
### Pitch

It would be nice if we could add a feature on web UI to let the user choose whether using swipable view on mobile.

### Motivation

When using web UI on my mobile, it's very easy to accidentally swipe to another bar while scrolling down. And if I swipe back, it will automatically return to the top of the timeline.

Personally I did [these](https://github.com/pullopen/mastodon/commit/649f2f706159502c4a1ff78ff06797e1ea98ee13) to disable swipable view on my whole site, but I still wish there would be a feature to let every user choose whether to keep this. Also, what I did would also disable the picture swiping, I hope that would be kept while disable the swipable view on different bar.

**Comment by ThibG** [comment]
Duplicate of #13882, addressed by #13885

**Comment by pullopen** [comment]
Thanks.
