### ISSUE TITLE
German translation suggestion: Standardize on either "Tröt" or "Beitragen", but not "Beitrag" (nto a verb)

### ISSUE THREAD

**Issue by BenWiederhake** [tootsuite/mastodon#14912]
New bug that was not previously reported: I can't find anything in this issue tracker or on discourse.

### Expected behaviour

The German label of the button that sends a toot is labeled with something that makes grammatical sense. For example: "Tröt!" (German word for the sound "toot"), "Tröten!" (German imperative for the verb "to toot"), "Posten!" (German imperative for the verb and foreign word "to post"), "Beitragen!" (German imperative for the verb "to post"); there are probably other reasonable choices.

Furthermore, "toot" should have a consistent translation throughout the UI.

### Actual behaviour

It says "Beitrag!" which doesn't make much grammatical sense. It's like saying "The post!" in English.

![Bildschirmfoto_2020-10-02_21-21-50](https://user-images.githubusercontent.com/2690845/94962192-5a658280-04f6-11eb-90af-ade8cf69671a.png)

"Toot" already has a consistent translation throughout the UI.

### Steps to reproduce the problem

Open Mastodon, be German.

### What seems to happen

~~This seems to be rooted in the translation of "toot" as "Beitrag": https://crowdin.com/translate/mastodon/12/en-de?filter=basic&value=0#q=beitrag
That is a good translation! However, it's not a good translation for "Toot!", the imperative verb.~~

EDIT: I'm a dummy, apparently that string is referred to with the key `compose_form.publish`, and was fixed two months ago: Crowdin says "Aug 03, 04:39".

So I would like to ask you to import translations. :)

**Comment by realpixelcode** [comment]
Yeah, please change it back into "Tröt". That's such a great term.

**Comment by marians** [comment]
This button is labeled `TRÖT!` in German v3.4.0. I think this issue can be closed.

<img width="285" alt="grafik" src="https://user-images.githubusercontent.com/273727/120085119-bc9e7380-c0d5-11eb-9b76-3a995c10961a.png">
