### ISSUE TITLE
The "This page is not correct" error animation GIF won't play automatically

### ISSUE THREAD

**Issue by KNTRO** [tootsuite/mastodon#14911]
### Expected behaviour

[The **oops.gif** animation](https://mastodon.social/oops.gif) should play automatically

### Actual behaviour

It only plays when you hover over it with your mouse.

### Steps to reproduce the problem

Just wait Mastodon to be broken 😆 and hover over the mastodon picture.

### Specifications

- Version: Mastodon v3.2.0
- Operating system: Windows 10 Home, 64 bit, version 2004
- Web browser: Waterfox 2020.09 (64 bit)

**Comment by Gargron** [comment]
It's by design...  See #6060
