### ISSUE TITLE
Link previews not generated for URLs in federated toots

### ISSUE THREAD

**Issue by daprice** [tootsuite/mastodon#1494]
When someone on the local instance toots a URL, Mastodon shows a preview of the linked site when the toot is clicked on to view in detail. This does not happen for federated toots from other instances.

Some examples of toots that should have previews, but don't when viewed from a federated instance: 
https://mastodon.technology/web/statuses/96355
https://mastodon.technology/web/statuses/97578

Both of the sites linked in those toots have open graph metadata to generate the preview from, but no preview is shown because they are from a user on a different instance.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
This has been resolved.
