### ISSUE TITLE
Request: Option to use mailgun API instead of SMTP

### ISSUE THREAD

**Issue by jemus42** [tootsuite/mastodon#1497]
The mailgun ruby gem is listed [here](https://documentation.mailgun.com/libraries.html#ruby).

As of now, mails on mastodon are sent via smtp, which is fine and all as it gives users the freedom to choose their mail servers.  
However, since hosts like scaleway block smtp traffic by default, many admins experience issues with outgoing mail and require research to find out that the problem is not their server, but their host's default security group.

Giving users the option to use the mailgun API instead would circumvent this issue and should be a reasonably fast/reliable alternative to smtp.

I am aware this is not a high priority issue, but I think in the long run it would be helpful to have the option.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Mailgun is a proprietary, specific service. Using SMTP, as you say, does not lock us in with any particular provider. Using Mailgun API would do just that. I do not want us to be locked in like that.
