### ISSUE TITLE
Inconsistence in Spanish translation

### ISSUE THREAD

**Issue by otrapersona** [tootsuite/mastodon#14972]
### Expected behaviour

The UI should be consistent in its use of the second grammatical person

### Actual behaviour

Some sections have been translated using the formal and others the informal second grammatical person. It is inconsistent.

Most of the UI is written in the formal second person while, these lines, for instance, have not:

1. "Puedes recomendar a gente que sigues desde la interfaz web, y aparecerán allí."
2. "Si deseas redireccionar esta cuenta a otra distinta, puedes configurarlo aquí."
3. "Si habilitas la autenticación de dos factores, se requerirá estar en posesión de su teléfono(...)"

### Steps to reproduce the problem

Those examples can be seen in these links while using the "es" locale:

1. mastodon.social/@\<account with no recommended users\>
2. https://mastodon.social/settings/profile
3. https://mastodon.social/settings/two_factor_authentication

### Specifications

I noticed the issue on v3.2.0.
It seems like the difference is between some newer (informal) UI elements and older ones (formal). 

### Post Scriptum
While I'm on this topic, if a choice had to be made, I vote to go informal, it's not rude, it's how friends talk to each other, as opposite to kids to elders, it's not like Mastodon is linked in or business dot biz  🤷🏽

**Comment by ThibG** [comment]
I'm not qualified to tell which of the formal or informal second person should be used, but contributing to the translations is done through https://crowdin.com/translate/mastodon

**Comment by otrapersona** [comment]
It's just a matter of deciding which one should be used and changing a couple of letters here and there, if there's no official Spanish translator I could do it, otherwise I wouldn't want to step on anyone's toes.

**Comment by otrapersona** [comment]
I have been browsing Mastodon's crowdin and realized that it'd be a bigger fish to fry than I thought, I could do it but instead I'd like to emend my offer to fix the `es` translation to

Formally request the creation of `es-MX`.

I'm making an instance for the Mexican community and both `es` and `es-AR` differ from Mexican Spanish.
I can do the translation.

**Comment by ykzts** [comment]
@otrapersona 

https://crowdin.com/project/mastodon/es-MX 

Spanish, Mexico was added. You can add translations.
