### ISSUE TITLE
Integration test for notifications

### ISSUE THREAD

**Issue by riking** [tootsuite/mastodon#1499]
Write an integration test to check the functionality of the notifications column.

Prereq: Integration test framework code. Whatever gets built, this test should be easy to express in it. (Also make sure to cover federation integration tests..)

 - Reset database to integration seed state
 - :hash: Create toot to trigger notifications with
 - :a: Create window1
 - :a: Log in user1
   - Check: .drawer contains a textarea
   - Check: .navigation-bar contains `FullNameUser1`
 - :a: Input `Test toot tGNIqJBTXGw` in composer
   - Check: Characters left is 479
 - :a: Click Toot button, wait for network
   - Check: Home column contains `tGNIqJBTXGw`
 - :hash: Cause all 4 types of notifications
 - :parking: Create window2
 - :parking: Log in user2
 - :parking: Input @user1 in search box
 - :parking: Keypress ENTER, wait for network
   - Check: .search-results contains `user1`
 - :parking: Click @user1, wait for network
   - Check: .account__header contains `user1`
   - Check: .account__header contains `FullNameUser1`
   - Check: .account__header contains `.fa.fa-user-plus`
 - :parking: $1 = Find `.status__content :contains("tGNIqJBTXGw")`.firstParent(`.status`)
 - :hash: Follow
 - :parking: Follow @user1, wait for network
   - Check: .account__header contains `.fa.fa-user-times`
   - Check: .search-results contains `.fa.fa-user-times`
 - :a: Wait for network
 - :a: $2 = Find `.notification .fa.fa-user-plus`.firstParent(`.notification`)
   - Check: $2 exists
   - Check: notifications column contains `$2 .account .display-name :contains("FullNameUser2")`
 - :hash: Boost
 - :parking: Click `$1 button[aria-label="Boost"]`, wait for network (!! i18n)
 - :a: Wait for network
 - :a: $3 = Find `.notification .fa-fa-retweet`.firstParent(`.notification`)
   - Check: $3 exists
   - Check: notifications column contains `$3 .status :contains("tGNIqJBTXGw")`
 - :hash: Fav
 - :parking: Click `$1 button[aria-label="Favourite"]`, wait for network (!! i18n)
 - :a: Wait for network
 - :a: $4 = Find `.notification .fa-fa-star`.firstParent(`.notification`)
   - Check: $4 exists
   - Check: notifications column contains `$4 .status :contains("tGNIqJBTXGw")`
 - :hash: Reply
 - :parking: Click `$1 button[aria-label="Reply"]`, wait for network (!! i18n)
 - :parking: Input `@user1 NJPY81lSU7k` in composer
   - Check: Characters left is 482
 - :parking: Click Toot button, wait for network
 - :a: Wait for network
   - Check: notifications column contains `.status :contains("NJPY81lSU7k")`
 - Pass

This test is designed to prevent repeats of #1491 or anything like it that prevents local-local notifications from working.

After writing this test, I can say that for good CSS customization (and also test writing), Mastodon definitely needs more flag CSS classes (e.g. `class="notification fav"`). But that's a separate issue...

**Comment by Gargron** [comment]
If you would like to submit some sort of Capybara test, you are welcome to do so, but I do not know what to do with this Github issue.
