### ISSUE TITLE
Gemini urls

### ISSUE THREAD

**Issue by zethra** [tootsuite/mastodon#14991]
Gemini is a protocol that uses the gemini url scheme

### Expected behaviour

Gemini urls in posts are converted to hyperlinks.

### Actual behaviour

Gemini urls in posts are **not** converted to hyperlinks.

### Steps to reproduce the problem

1. Create a post with a gemini url in it (ex. gemini://drewdevault.com/2020/10/18/New-workstation.gmi )
2. Url in to a hyperlink.

### Specifications

Bug discovered in version 3.2.0
Using Firefox on Linux

**Comment by ChlorideCull** [comment]
For reference to whoever decides to implement it, [the Gemini spec is available here](https://portal.mozz.us/gemini/gemini.circumlunar.space/docs/specification.gmi).

The URI scheme is defined in 1.2 and is largely compatible with what's used for HTTP, so changing the valid_url regex and adding it to the sanitizer allowlist should be good enough.
