### ISSUE TITLE
Videos in unsupported codecs cause UI problems

### ISSUE THREAD

**Issue by daprice** [tootsuite/mastodon#1501]
Viewing a toot containing a video in a format your browser doesn't support causes usability issues with the UI:

* there is a blank space where the thumbnail would be (see the first toot in the following screenshot)
  ![img_0217](https://cloud.githubusercontent.com/assets/3615519/24889007/20c9d9b2-1e2d-11e7-8e39-643eb8d17af5.PNG)

* clicking on the space covers the screen in a lightbox, but it's empty other than a close button
  ![img_0218](https://cloud.githubusercontent.com/assets/3615519/24889014/35fcfd64-1e2d-11e7-915b-78acc6e2599a.PNG)

These screenshots were taken of a toot containing a WebM video, on iOS, which doesn't support WebM video encoding in the browser (due to lack of hardware acceleration of that format).

I understand that it's not feasible to convert every video uploaded to Mastodon to compatible formats for every device, but I'm wondering if it's possible to detect the unsupported format and either hide the thumbnail preview and/or display a message or icon indicating the format isn't supported (in any case, the link should still be clickable to download the file because another app might support it even if the browser doesn't).

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by iansltx** [comment]
If Modernizr is already included in the JS package, could use http://stackoverflow.com/a/7451727 or similar for codec detection. If not, the underlying could could be used.
