### ISSUE TITLE
Error: relation "ip_blocks" does not exist at character 566 (app/models/ip_block.rb)

### ISSUE THREAD

**Issue by JHenzi** [tootsuite/mastodon#15020]
### Expected behaviour

Server should not throw up and refuse to update?

### Actual behaviour

Server throws up and shows a fail elephant

### Steps to reproduce the problem

Boot server, see error below.

### Specifications

3.2.0 - Docker, no modifications

not a front end issue. 

### Log output from Docker.

`web_1        | => Booting Puma
web_1        | => Rails 5.2.4.4 application starting in production
web_1        | => Run `rails server -h` for more startup options
web_1        | [9] Puma starting in cluster mode...
web_1        | [9] * Version 5.0.2 (ruby 2.6.6-p146), codename: Spoony Bard
web_1        | [9] * Min threads: 5, max threads: 5
web_1        | [9] * Environment: production
web_1        | [9] * Process workers: 2
web_1        | [9] * Preloading application
web_1        | [9] * Listening on http://0.0.0.0:3000
web_1        | [9] Use Ctrl-C to stop
web_1        | [9] - Worker 0 (pid: 12) booted, phase: 0
web_1        | [9] - Worker 1 (pid: 17) booted, phase: 0
web_1        | [72dd667d-6156-42f6-b493-01f3bab41e91] Chewy request strategy is `custom_sidekiq`
db_1         | ERROR:  relation "ip_blocks" does not exist at character 566
db_1         | STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
db_1         |                       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
db_1         |                       c.collname, col_description(a.attrelid, a.attnum) AS comment
db_1         |                  FROM pg_attribute a
db_1         |                  LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
db_1         |                  LEFT JOIN pg_type t ON a.atttypid = t.oid
db_1         |                  LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
db_1         |                 WHERE a.attrelid = '"ip_blocks"'::regclass
db_1         |                   AND a.attnum > 0 AND NOT a.attisdropped
db_1         |                 ORDER BY a.attnum
db_1         |
web_1        | [72dd667d-6156-42f6-b493-01f3bab41e91]
web_1        | [72dd667d-6156-42f6-b493-01f3bab41e91] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "ip_blocks" does not exist
web_1        | LINE 8:                WHERE a.attrelid = '"ip_blocks"'::regclass
web_1        |                                           ^
web_1        | :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
web_1        |                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
web_1        |                      c.collname, col_description(a.attrelid, a.attnum) AS comment
web_1        |                 FROM pg_attribute a
web_1        |                 LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
web_1        |                 LEFT JOIN pg_type t ON a.atttypid = t.oid
web_1        |                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
web_1        |                WHERE a.attrelid = '"ip_blocks"'::regclass
web_1        |                  AND a.attnum > 0 AND NOT a.attisdropped
web_1        |                ORDER BY a.attnum
web_1        | ):
web_1        | [72dd667d-6156-42f6-b493-01f3bab41e91]
web_1        | [72dd667d-6156-42f6-b493-01f3bab41e91] app/models/ip_block.rb:31:in `block in blocked?'
web_1        | [72dd667d-6156-42f6-b493-01f3bab41e91] app/models/ip_block.rb:31:in `blocked?'
web_1        | [72dd667d-6156-42f6-b493-01f3bab41e91] config/initializers/rack_attack.rb:46:in `block in <class:Attack>'
db_1         | ERROR:  relation "ip_blocks" does not exist at character 566
db_1         | STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
db_1         |                       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
db_1         |                       c.collname, col_description(a.attrelid, a.attnum) AS comment
db_1         |                  FROM pg_attribute a
db_1         |                  LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
db_1         |                  LEFT JOIN pg_type t ON a.atttypid = t.oid
db_1         |                  LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
db_1         |                 WHERE a.attrelid = '"ip_blocks"'::regclass
db_1         |                   AND a.attnum > 0 AND NOT a.attisdropped
db_1         |                 ORDER BY a.attnum
db_1         |
web_1        | [83d1c4ff-abcb-4150-880c-01e1ed1e8803]
web_1        | [83d1c4ff-abcb-4150-880c-01e1ed1e8803] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "ip_blocks" does not exist
web_1        | LINE 8:                WHERE a.attrelid = '"ip_blocks"'::regclass
web_1        |                                           ^
web_1        | :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
web_1        |                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
web_1        |                      c.collname, col_description(a.attrelid, a.attnum) AS comment
web_1        |                 FROM pg_attribute a
web_1        |                 LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
web_1        |                 LEFT JOIN pg_type t ON a.atttypid = t.oid
web_1        |                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
web_1        |                WHERE a.attrelid = '"ip_blocks"'::regclass
web_1        |                  AND a.attnum > 0 AND NOT a.attisdropped
web_1        |                ORDER BY a.attnum
web_1        | ):
web_1        | [83d1c4ff-abcb-4150-880c-01e1ed1e8803]
web_1        | [83d1c4ff-abcb-4150-880c-01e1ed1e8803] app/models/ip_block.rb:31:in `block in blocked?'
web_1        | [83d1c4ff-abcb-4150-880c-01e1ed1e8803] app/models/ip_block.rb:31:in `blocked?'
web_1        | [83d1c4ff-abcb-4150-880c-01e1ed1e8803] config/initializers/rack_attack.rb:46:in `block in <class:Attack>'
`

**Comment by Gargron** [comment]
You're not running code from 3.2.0, you're running code from the master branch.

**Comment by JHenzi** [comment]
Gargon, I see it now! Which is embarrassing. What happened to the Docker production guide? It's missing from the official sites.
