### ISSUE TITLE
resizing browser window down breaks UI

### ISSUE THREAD

**Issue by ericblade** [tootsuite/mastodon#1503]
Start with browser not maximized, but > 1024 px width

Selected "Federated Timeline" (i think any of the others also do this)
Resize the window using the standard resizing borders (NOT a maximize/un-maximize) to small enough to trigger the change to single pane UI
Witness that the single-pane UI is utterly broken
Resize back to > 1024px
UI returns to functionality, but the "Back" button on the Federated Timeline is also broken

Can get out of this broken UI situation by reloading or by clicking the "Getting Started" button

Does not seem to be triggered, or is much more difficult to trigger when changing size in large units at a time, such as with maximize/un-maximize.

Verified using Vivaldi 1.9, Chrome 57.0, Edge 38.14393
Using Mastodon 1.1.1 + changes up to a28378646393de998663981e6660eb79e7a6375f

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mkody** [comment]
Can confirm this is happening to me as well.

**Comment by mattjmattj** [comment]
Could you update to b22b2cbfacdaef2441d14f401c95863d8ca2e66c and test again ? I'm pretty sure that the problem was due to the TypeError corrected by this commit (account.jsx)
