### ISSUE TITLE
Mute conversation not work in notifications?

### ISSUE THREAD

**Issue by mashirozx** [tootsuite/mastodon#15058]
### Expected behaviour
I think the conversation shall be hidden after clicked `Mute conversation` item.

### Actual behaviour
![image](https://user-images.githubusercontent.com/16148054/97485690-662d5300-1995-11eb-80e1-86360745ce43.png)
But the conversation still display in notification column?

### Steps to reproduce the problem
Clicked `Mute conversation` item in menu

### Specifications
latest master branch

**Comment by trwnh** [comment]
"Mute conversation" simply prevents further notifications for that thread. It does not hide the status(es).
