### ISSUE TITLE
Picture-in-Picture is blocking the compose button on mobile device

### ISSUE THREAD

**Issue by umonaca** [tootsuite/mastodon#15092]
### Expected behaviour

The Picture-in-Picture player box should at least be movable so that it won't block the compose button.

### Actual behaviour

The compose button is blocked by the Picture-in-Picture player box. Users can't write a toot unless they turn off the music.

### Steps to reproduce the problem

1. Use Chrome to simulate a view in iPhone 6/7/8.
2. Play music.
3. Scroll down timeline so that the Picture-in-Picture is automatically turned on.
4. Now you can't compose anything.

### Specifications

Any mobile phone. On master branch as of fa929d8b81002c95f729517d3ce3985f090c5980.

**Comment by pullopen** [comment]
I actually hope the Picture-in-Picture can be movable. In advanced web view it will block people's comment.

**Comment by umonaca** [comment]
PR #15157 removed PiP for mobile entirely, which is not what I wanted.
I am keeping this feature for my own instance. For anyone who still wants a PiP on mobile devices, this commit (with minimal modification to the upstream) should work:
https://github.com/umonaca/mastodon/commit/0ba1e45a798fb5fa0a2991b7b6f5b183c0bcfa75
It still blocks the compose button though, but I prefer the PiP to the compose button.

**Comment by pullopen** [comment]
> 
> 
> PR #15157 removed PiP for mobile entirely, which is not what I wanted.
> I am keeping this feature for my own instance. For anyone who still wants a PiP on mobile devices, this commit (with minimal modification to the upstream) should work:
> [umonaca@0ba1e45](https://github.com/umonaca/mastodon/commit/0ba1e45a798fb5fa0a2991b7b6f5b183c0bcfa75)
> It still blocks the compose button though, but I prefer the PiP to the compose button.

Yeah. Blocking the compose button only means I'll have to close the PiP while writing toots. But cancelling this function means I can no longer enjoy PiP at all. If I have to choose I choose to keep it.
