### ISSUE TITLE
Announcements history (/admin/announcements) should be newest-first

### ISSUE THREAD

**Issue by Phroneris** [tootsuite/mastodon#15090]
### Pitch

If you're a server administrator, you can see the list of announcements created up to now on `/admin/announcements`.
I'd like this list to have newer announcements to the upper side... like the report list or our ordinary toots.

### Motivation

Currently, announcements are in newest-last (oldest-first) order.
But, I think older ones tend to be less important.

I'm one of admin members on gensokyo.town (Mastodon v3.2.1).
This server has made many announcements for spoiler limitations so the list has many.
When I reuse/consult recent ones to make new one, I have to scroll down the page a lot for now.

**Comment by ThibG** [comment]
Would them be sorted by creation date, with the newest first, be ok? Or would it make more sense to sort them by “active” date?

**Comment by Phroneris** [comment]
Ah, I supposed only the creation date order and have forgotten the "active" one.
I just hope the opposite of current one so either is fine.
Thank you.
