### ISSUE TITLE
NoMethodError undefined method `devices_url=' 

### ISSUE THREAD

**Issue by umonaca** [tootsuite/mastodon#15105]
### Actual behaviour

> 09:00:48 web.1     | NoMethodError (undefined method `devices_url=' for #<Account:0x00007ff480ed7e58>
> 09:00:48 web.1     | Did you mean?  devices=):
> 09:00:48 web.1     |   
> 09:00:48 web.1     | app/services/activitypub/process_account_service.rb:79:in `set_immediate_attributes!'
> 09:00:48 web.1     | app/services/activitypub/process_account_service.rb:67:in `update_account'
> 09:00:48 web.1     | app/services/activitypub/process_account_service.rb:27:in `block in call'
> 09:00:48 web.1     | app/services/activitypub/process_account_service.rb:19:in `call'
> 09:00:48 web.1     | app/services/activitypub/fetch_remote_account_service.rb:31:in `call'
> 09:00:48 web.1     | app/services/activitypub/fetch_remote_key_service.rb:37:in `find_account'
> 09:00:48 web.1     | app/services/activitypub/fetch_remote_key_service.rb:24:in `call'
> 09:00:48 web.1     | app/controllers/concerns/signature_verification.rb:213:in `block in account_from_key_id'
> 09:00:48 web.1     | app/controllers/concerns/signature_verification.rb:226:in `stoplight_wrap_request'
> 09:00:48 web.1     | app/controllers/concerns/signature_verification.rb:213:in `account_from_key_id'
> 09:00:48 web.1     | app/controllers/concerns/signature_verification.rb:80:in `signed_request_account'
> 09:00:48 web.1     | app/controllers/concerns/signature_verification.rb:49:in `require_signature!'

### Steps to reproduce the problem

I think it's unrelated but I get this error when using `bin/tootct self-destruct`. The log is from the foreman window. 
I don't know a way to reliably reproduce this but probably the method is/was somewhere in the code?

### Specifications

stable-3.2 branch

**Comment by Gargron** [comment]
What's the output of `rails db:migrate:status`? You seem to have an outdated database schema

**Comment by umonaca** [comment]
Ahhh I forgot. Thanks.
