### ISSUE TITLE
Feature request: boost with commentary

### ISSUE THREAD

**Issue by jgoguen** [tootsuite/mastodon#1513]
Please add the ability to boost a toot with commentary. The intent is to allow boosting but also adding my own commentary to the boost, perhaps to point out when there's a thread to follow or to start a discussion on a single point.

* * * *

- [x] I searched or browsed, as well as I can on mobile web, the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
Duplicate of #309, closing
