### ISSUE TITLE
邮件无法发出

### ISSUE THREAD

**Issue by ouyangqr** [tootsuite/mastodon#15145]
SMTP_SERVER=smtp.qq.com
SMTP_PORT=587
SMTP_LOGIN=3545xx917@qq.com
SMTP_PASSWORD=xx
SMTP_FROM_ADDRESS=3545xx917@qq.com

This is my configuration, but I can't receive email when I register my account

**Comment by Gargron** [comment]
I'm afraid I don't know what configuration qq.com requires. While it is possible to send Mastodon e-mail over consumer-oriented services like GMail, it is not the most optimal (although free) option for reliable delivery.
