### ISSUE TITLE
uploading images result in a colored background

### ISSUE THREAD

**Issue by hansw-nlo** [tootsuite/mastodon#15178]
# Expected behaviour

showing an uploaded image

### Actual behaviour

The image is not shown, a ramdom color is shown that fills the image

### Steps to reproduce the problem

I uploaded images to 2 instances and they show the same problem:
https://qoto.org/@hansw/105222533929176573
https://mastodon.social/@hansw/105222607750838505

### Specifications

(v3.2.1).

Uploaded using firefox on Debian 10 (custom kernel). Uploading to pixelfed.social does work

**Comment by hansw-nlo** [comment]
Uploading to both pixelfed and hubzilla is not a problem

**Comment by ThibG** [comment]
can we have a look at the source image?

**Comment by hansw-nlo** [comment]
Here we go, but please see the remark that I can upload them to other sites
![b31f464e55c02ec4](https://user-images.githubusercontent.com/27645742/99436951-ae42f400-2909-11eb-94d4-042b64b0b7a0.jpg)

**Comment by hansw-nlo** [comment]
As you can see I can even upload it here

**Comment by ThibG** [comment]
Downloading your file and trying to upload it on Mastodon, I am unable to reproduce your issue. My current hunch is that a browser extension or maybe some privacy setting might be messing with the image resizing operations done on the browser side by Mastodon's Web UI.

Which exact version of Firefox are you using? Are you using some browser extension that could cause this? Can you try uploading the same image with another browser? What happens if you try uploading a picture of at most 1280×1280 pixels?

**Comment by hansw-nlo** [comment]
I am using 78.4.1esr (64-bit) on Debian. if an addon would give this trouble then I would not be able to upload to non mastodon sites. 

In chrome I am able to upload it correctly. That means Mastodon is having problems with the settings. I must state that all of the settings or addons I use hava not changed a bit and I was able to upload to it with Firefox until recently. Both mastodon.social and qoto.org are having trouble with it.

**Comment by hansw-nlo** [comment]
I tried with chrome and that is ok. When I try with firefox 78.4.1esr (64-bit) on Debian then I can upload some images when I disable addons like uBock Origin, etc... It still has problems with the dog picture, even when I disable all addons

**Comment by ThibG** [comment]
> I am using 78.4.1esr (64-bit) on Debian. if an addon would give this trouble then I would not be able to upload to non mastodon sites.

That isn't true. As I said earlier, the Mastodon Web UI does some resizing operation locally, which involves technology that could be blocked by extensions. Other websites might not do that.

> I tried with chrome and that is ok. When I try with firefox 78.4.1esr (64-bit) on Debian then I can upload some images when I disable addons like uBock Origin, etc... It still has problems with the dog picture, even when I disable all addons

I could not reproduce it with Firefox 78.4.1esr (64-bit) on Debian (testing/unstable) with the image you uploaded before. I tried without add-ons, and with uBlock Origin.

Can you check in `about:config` if you have `privacy.resistFingerprinting` and `privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompt` set?

**Comment by hansw-nlo** [comment]
It is set to true

**Comment by ThibG** [comment]
ok, I'll try coming up with a fix

**Comment by hansw-nlo** [comment]
Thank you, if you want more tests then let me know
