### ISSUE TITLE
webfinger issue with Accept header

### ISSUE THREAD

**Issue by zotlabs** [tootsuite/mastodon#1517]
Tried: If a requesting client connects to the .well-known/webfinger service with an Accept header of (asterisk)/(asterisk), a 406 error will be returned. Likewise if the Accept header contains application/jrd+json plus any other content type text (including the wildcard specification). In some combinations of multiple Accept values, an xml format is returned even if the jrd variant is specified first and/or with a higher priority. 

Expected: the default 'application/jrd+json' document should be returned if it matches any of the Accept conditions OR there is no Accept header. 

I'm not proficient in ruby but the problem seems to be centred around (master) app/controllers/xrd_controller.rb:L35, though it wasn't obvious where in the code the output is set correctly on an exact match of the string 'application/jrd+json' with no other text in the Accepts header field. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
I think I understand what you're saying, but can you provide a specific URL and a curl request or something to reproduce the issue?

**Comment by zotlabs** [comment]
Visit https://$mastodonsite/.well-known/webfinger?resource=acct:$someusername@$mastodonsite using firefox. I'm using 52.0.2 under Windows though I've seen the same issue in Firefox using Linux and Windows. The linux version is probably a bit older. 

You'll get a 406 error even though your web browser Accept header probably includes the wildcard spec \*/\* - you can view this in the inspector (the built-in firebug thing) and see that your Accept headers should match and allow the page mimetype of application/jrd+json and display the page.

In libcurl, the default Accept header is \*/\* unless you set something different. This says accept any mimetype. When fetching with just this default setting, you'll get a 406 error from the server.  

If you change the accept headers in either firefox or curl to  something else such as 'application/jrd+json, */*' you'll get an XML document. This is wrong, JSON should be the default as it is listed first. Only if you set to the exact string 'application/jrd+json' or use the debugger to remove the Accept header from the request headers will you get the json document. Also if you add &format=json to the URL but this is not compliant with RFC7033.

**Comment by mjankowski** [comment]
The browser is probably sending `text/html` as an accepted format earlier in the list than `*/*`, so Rails attempts to process as an html request, and can't, so you get that response.

When you do something like a) put json in the accepts headers earlier on, b) add `?format=json`, c) user `webfinger.json` as path - you can get Rails to process as JSON.

So the desired change is to fix what should be a default JSON response when XML is not explicitly asked for?

**Comment by zotlabs** [comment]
Again, ruby isn't my first computer language; but the way I believe the logic should work is that for webfinger, JSON should always be the default  - unless you over-ride it and specifically choose the XML representation. The spec says that it should be the default when given an empty Accept header. In fact, the webfinger spec does not offer any possibility or mechanism for using a different format.  So what they're really saying is that webfinger uses application/jrd+json - period. If there is any doubt as to the format - send that.  Sending html should never even be considered, regardless of whether it exists in the accept header. 

It seems that what is happening is that the default JSON is only set under a very narrow set of circumstances, and if those specific circumstances aren't met (empty accept header and no format argument); you end up with no default format at all and the results at least in this case are somewhat undefined and ambiguous and the http server tries to come up with its best guess - and fails. So I believe the correct fix is to set the output to 'json'. That's the default. Then over-ride this only if 'format=xml' was used. 

I can visit any other webfinger service in the fediverse (at least the 20 or so projects I'm aware of) using my web browser and get a json page. I can access them from my web applications using libcurl with the default \*/\* and get a json page. With Mastodon sites I cannot. 

Sure, I can work around this, but we're talking about a discovery service. If I don't know in advance that it is a mastodon site, I don't know if it needs a hack to get to the webfinger information. Typically when we get anything but a 2XX response, we just give up and say that the site doesn't support webfinger. There are also a number of experimental webfinger servers (think wordpress plugins, etc.) that serve up webfinger with a text/html header because their software provides this header by default; even though the content is JSON.  So I also don't wish to restrict responses to application/jrd+json only, I'm really willing to accept anything. I'll check if it's JSON and discard it it if it isn't. 
 
For the XRD controller the logic should probably be reversed and XML should be the default - unless you over-ride it with a different format. 

I'm not sure how the wrong format is being used in a couple of cases, but I think if it is sorted so that there is an actual default that problem could possibly go away.
