### ISSUE TITLE
Migrate from discontinued cws to uWebSockets.js or similar

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#15184]
### Expected behaviour

Streaming server should run on current LTS (node v14).

### Actual behaviour

As shown in #15151, the current cws module fails and is not supported. 
Streaming server is broken https://paste.ubuntu.com/p/BDpfDTSqVV/

### Steps to reproduce the problem

Run master on v14 LTS node.

### Specifications

3.2.1/Current Master

**Comment by Gargron** [comment]
Hm, the APIs are not the same at all. It will require rewriting a lot of the server...

**Comment by Gargron** [comment]
Uh-oh https://medium.com/@rockstudillo/beware-of-uwebsockets-js-b51c92cac83f

**Comment by shleeable** [comment]
Boo. Shame nobody just forked the existing cws... Gotta love node ecosystem https://www.npmjs.com/package/ws

**Comment by nanaya** [comment]
I sure wonder if all the drama from uws and co is worth switching from plain [ws](https://www.npmjs.com/package/ws).

**Comment by cortices** [comment]
It might be worth putting a note in the https://docs.joinmastodon.org/dev/setup/ page that Node v14/15 aren't supported for now.

**Comment by diegoboten** [comment]
This doesn't work on 12 either. I'm also on Ubuntu 20.4 and I've cycled through every single Node.js version. Streaming is broken on all of them. 

https://github.com/tootsuite/mastodon/issues/15898

**Comment by cortices** [comment]
Even if there is a potential workaround to the current issue on node 12 by freezing to a prior version or something, this is becoming a very high priority issue for the streaming API to continue functioning in future releases.

**Comment by ClearlyClaire** [comment]
For some background, we migrated from `ws` to `uws` with #2807 and migrated from `uws` to `cws` with #10805.
With `cws` being unmaintained, we definitely need to move back to either `ws` or `uWebSockets.js`.
Given the API changes and the overall attitude of the `uws` developer, I'd be slightly more inclined with going back to `ws`, but I wonder what the performance hit would be. It would probably be a good idea to perform actual benchmarks there.
