### ISSUE TITLE
Option to mute sound from notifications

### ISSUE THREAD

**Issue by jrmgx** [tootsuite/mastodon#1518]
When I get a notification in Mastodon a sound plays
It would be nice to let the user choose if he/she wants that sound

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by TrollDecker** [comment]
That option's already available though? If you click the icon in the top-right of the Notifications column, a list of options will come up, including sound options for each type of notification.

**Comment by wxcafe** [comment]
@jrmgx I think your questions was answered, I'm closing this issue

**Comment by jrmgx** [comment]
You are right, I was looking for this option in settings.
It is in fact on the "notification" column 
Thanks for your help

**Comment by SaraUckelman** [comment]
Oh, goodness, I was looking for this under "settings" and "preferences" too!  It would never have occurred to me to look for it under notifications.  THANK YOU for asking this so that I could find out how to turn the damn things off.

**Comment by jahed** [comment]
I had a similar experience with notification sounds. Looked in Settings for an option to switch it off. Didn't find anything, assumed it didn't exist. Decided to Google it later. Found this page.

I think it'd be useful if either the Settings page took us to where sound is configured, or if sound settings were moved/duplicated to the settings page.

**Comment by nycki93** [comment]
Yeah, this is hidden in a really weird place, it should be under Settings or else there should be a hint there that tells you where to find it.
