### ISSUE TITLE
Image uploads to .onion address are corrupted

### ISSUE THREAD

**Issue by stayinside** [tootsuite/mastodon#15215]
My instance is running both a clearnet domain and a .onion address. I am running the .onion config from the documentation. When I attempt to upload an image 1mb or larger through the onion address the image becomes corrupted (see below) and the console logs `"Blocked *address* from extracting canvas data because no user input was detected."`

Comparing the output of `journalctl -xf -u mastodon-*` through both domains indicates no issue on the back end.

![corrupted](https://user-images.githubusercontent.com/32370941/100042331-16894e00-2dc0-11eb-9ee0-0b64b217dbe1.jpg)
![original](https://user-images.githubusercontent.com/32370941/100042340-1a1cd500-2dc0-11eb-8e05-84f8a9d35e43.jpg)

**Comment by nightpool** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1600252 indicates that you should be getting a pop-up in this case. did you not do so?

**Comment by nightpool** [comment]
Unfortunately, this is a bug in either the Tor Browser or Firefox, and I don't think there's anything we can do to fix it. You'll have to report it to them.

**Comment by Gargron** [comment]
Fixed by #15180, await new release
