### ISSUE TITLE
TypeError: a.map is not a function

### ISSUE THREAD

**Issue by mashirozx** [tootsuite/mastodon#15225]
### Actual behaviour

I am not sure why this and don't know how to reproduce this error, but one of my user provided me the error info below. Seems it's relevant to #15217

Stack trace:
```
TypeError: a.map is not a function
at t.render (https://if_need_domain_plz_let_me_know.com/packs/js/common-59a1efa0fc8cbb6055db.js:2:331033)
```

Source location here: 
```
# sl -p common-59a1efa0fc8cbb6055db.js.map -l 2 -c 331033
sourcecode info:
sourceCodePath: webpack:///app/javascript/mastodon/features/ui/components/media_modal.js
line: 269
column: 26
name: map
```

https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/features/ui/components/media_modal.js#L269

### Steps to reproduce the problem

I don't know how to reproduce this error, but one of my user provided me the error info in production environment.

### Specifications

Commit hash 1e89e2ed988d2103ecd46e06476d863cb40c57c7

**Comment by Gargron** [comment]
Why close? Was it solved?

**Comment by mashirozx** [comment]
Yes, it's not the business of official code, but a mistake I made while merging upstream to my branch (I forgot to replace with the new `handleOpenMedia()` actually). Sorry for bothering you.

**Comment by noellabo** [comment]
Occurs when the search-plus icon is clicked on the media type preview card on the timeline.
Fixed at https://github.com/tootsuite/mastodon/pull/15305
