### ISSUE TITLE
«Back» link behaviour is weird

### ISSUE THREAD

**Issue by SiegfriedEhret** [tootsuite/mastodon#1522]
Hello you !

What happens: the back link goes to the browser previous page (even if it's not mastodon).

Expected: the back link should bring back the «getting started» column 

Reproduce:

- Go to https://duckduckgo.com/
- In the same page, go to https://mastodon.social/web/accounts/41911 (that's me !)
- Click on the «Back» link (in the column with the profile, or local / federated timelines)
- You are back to Duck duck go.

Maybe it's just that the label «back» is misleading...

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
If you mean the back button from the browser, that's actually expected behaviour??

**Comment by Fastidious** [comment]
@wxcafe no, OP meant “< Back” link on the Local/Federated Timelines.

**Comment by SiegfriedEhret** [comment]
Not a button, the link in the column with the opened profile or timeline (i'll update the description, thanks)

**Comment by wxcafe** [comment]
Okay this only happens with profiles, I tried with /web/timelines/public and that doesn't trigger it, but /web/accounts/<id> does.

**Comment by jeepfromoil** [comment]
Same issue as https://github.com/tootsuite/mastodon/issues/946

**Comment by SiegfriedEhret** [comment]
Thanks for noticing the duplicate @jeepfromoil !
