### ISSUE TITLE
`List selection` button on a handle's profile page.

### ISSUE THREAD

**Issue by swapnilmj** [tootsuite/mastodon#15224]
### Pitch
On a Mastodon handle's (user's) profile page, add a button or feature to easily add that handle (user) to a list. 

I feel, a button next to the `Follow` button would be nice for this purpose.

### Motivation
Lists are a really powerful feature.  This, proposed feature will make it easy to add a handle to a list, almost immediately when we `Follow` that  handle.

This will help people who try to organize their stuff. Like _James Clear_ says, "to encourage a habit, make it easy" (paraphrased).

**Comment by ThibG** [comment]
If I understand your request correctly, there's already such a button in the dropdown menu for accounts you follow. It's called “Add or Remove from lists”

**Comment by swapnilmj** [comment]
Yes, I noticed that we can see the dropdown menu when following a user on the same instance.

It would be great to have a similar feature while following a user on a different instance.

**Comment by ThibG** [comment]
oh, this works for accounts regardless of their home instance, but it only works from the web interface on the instance you're logged in.

We couldn't really do it when you're viewing a profile on a different domain, since that instance doesn't know about your lists or who you are or if you even use Mastodon, while lists management is a Mastodon-specific feature.

**Comment by swapnilmj** [comment]
That makes sense. 👍 

So, can we consider adding it on the page which we see after following a new user account, on the web interface ( i.e. at `/authorize_interaction?uri=`) ?

Page URI:
https://<home-instance>/authorize_interaction?uri=<other-instance-user-URI>

**Comment by swapnilmj** [comment]
Since this feature is available on the instance we are logged in, I feel we can close this issue.
Thanks for your time @ThibG
