### ISSUE TITLE
Add Traditional Chinese, Hong Kong translation (zh-HK)

### ISSUE THREAD

**Issue by yookoala** [tootsuite/mastodon#1524]
Hello. For zh-HK users, Mastodon is displaying Simplified Chinese interface. This is not good.

Need to improve the situation.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Fastidious** [comment]
@yookoala isn’t simplified the preferred choice? It is the new system, after all.

**Comment by yookoala** [comment]
No. Simplified Chinese is official written language in Mainland China. Not in Hong Kong.

**Comment by yookoala** [comment]
In fact, it is also not official in Taiwan. It'd be better to have a zh-TW translation.

**Comment by Fastidious** [comment]
@yookoala are you saying you can’t read and write simplified?

**Comment by yookoala** [comment]
I cannot write Simplified Chinese. I can read it. But then I can also read English and Spanish.

The issue is that it's not preferable.

**Comment by yookoala** [comment]
By default, I think Ruby is picking up language options from browser preference (request header). "zh-hk" is a perfectly legit, even common localization code. Also in the account preference screen, I see no reason why we cannot add "Traditional Chinese" into the drop list. You even have an "Esperanto" option.

If you're worrying about the labour, I can certainly provide a pull request.

**Comment by Fastidious** [comment]
@yookoala I did not realised there was **already** a drop down list for languages within *Settings*. If you submit the PR, I am sure it will get added. Go for it!
