### ISSUE TITLE
422 Error processing thumbnail for uploaded media

### ISSUE THREAD

**Issue by umonaca** [tootsuite/mastodon#15251]
### Expected behaviour

After uploading an mp3 audio file, it should work as in mastodon.online

### Actual behaviour

I am getting this error even for some mp3 files **without any embedded thumbnails** on my instance. However, I cannot reproduce it on mastodon.online as they upload successfully.
I tried looking at the logs, but it showed almost shows nothing:
```
Nov 30 09:46:28 jabberwocky bundle[16284]: [957e00c7-294e-4e59-9dd2-5c19ddf9d741] method=GET path=/api/v1/media/105298625519037973 format=html controller=Api::V1::MediaController action=show status=422 duration=7.94 view=0.71 db=1.46
```
What's making it hard to debug is that even if I am uploading the same file, the failure is not always reproducible -- it's random.  
It also always takes a long time before the Delete/Edit is shown (the progress bar always stucks at 100% for several minutes) after uploading an audio file, no matter the processing is success or not. In browser console, I am seeing lots of XHRs after the POST.  When it fails, the 422 always comes after lots of XHRs. I don't know if it's related.

BTW I am using DigitalOcean Spaces as the S3 compatible object storage provider. `S3_READ_TIMEOUT` is set to `30`.

### Specifications

master branch as of 18ca4e0e9a3f74a6f21d329882b429f8f5227b0f

**Comment by ThibG** [comment]
When using the new API (which the WebUI has been doing for a while), media uploads are processed asynchronously, which explains the multiple XHR requests and the variable delays.

This also means you may get more information in the `mastodon-sidekiq` logs rather than `mastodon-web`.

**Comment by umonaca** [comment]
I changed `S3_READ_TIMEOUT` to 15 and installed new version of `file` from source. It now seems fine but I think the cause could be the crappy connect quality to the DigitalOcean Spaces. Now I am closing this issue.
