### ISSUE TITLE
Ruby 2.7.2 Breaks install

### ISSUE THREAD

**Issue by Clay-Ferguson** [tootsuite/mastodon#15253]
Following the steps as outlined here:

https://docs.joinmastodon.org/admin/install/

And running on a brand new clean Linode instance of Ubuntu 18.04.

When you get to this step, to run the following command:
```
bundle config deployment 'true'
```
You get this error message:

```
rbenv: version `2.6.6' is not installed (set by /home/mastodon/live/.ruby-version)
```
Is the switch to Ruby 2.7.2 new, because according to my notes from just yesterday this site had 2.6.6 as the Ruby version. My guess is that somebody upgraded it to 2.7.2 in the last 24 hrs, and at least for me 2.7.2 doesn't work.

**Comment by Gargron** [comment]
Install 2.6.6

I probably shouldn't have agreed to merge the documentation update until v3.3.0 is actually released

**Comment by Clay-Ferguson** [comment]
Thanks for the quick attention to that. I'm gonna take another crack at it on a clean 18.04 instance now!
