### ISSUE TITLE
Glitch-soc profile stats view 

### ISSUE THREAD

**Issue by mstdn** [tootsuite/mastodon#15260]
Over time the profile page has been changed many time and almost always for the good! :-) In this case I want to request from the Glitch-soc source code for vanilla. 

### Pitch

Here the the vanilla(default) Mastodon profile page view. 
<img width="390" alt="vanilla" src="https://user-images.githubusercontent.com/57602062/100806618-124cd880-3431-11eb-9d23-6261432e0571.png">

And here you can see the one from Glitch-soc Mastodon source. I find this one far more clear for users to see what is clickable plus it fits perfectly with the public profile page design.
<img width="390" alt="glitch" src="https://user-images.githubusercontent.com/57602062/100806616-111bab80-3431-11eb-8a73-9b4a0f661c21.png">

Could the "Posts" "Following" and "Followers" block be implemented on the default vanilla Mastodon? 

### Motivation

Improving design together ❤️

**Comment by Gargron** [comment]
That’s our previous design

**Comment by mstdn** [comment]
> That’s our previous design #10337

I see.. What about a somewhat improved version(mobile)? 💭

**Comment by mstdn** [comment]
<img width="390" alt="in-dtuch" src="https://user-images.githubusercontent.com/57602062/100809849-68247f00-3437-11eb-9d8e-9baea83e5571.png">

This is how it looks in Dutch right now 😄

**Comment by Gargron** [comment]
Can you not have "47K" instead of "47 duizend" in Dutch? If you can, this is a translation issue.

**Comment by mstdn** [comment]
> Can you not have "47K" instead of "47 duizend" in Dutch? If you can, this is a translation issue.

Yes for sure! It was always like that before last update ;-)

**Comment by Gargron** [comment]
Looks like it was @jeroenpraat's decision. I'm interested to hear why...

**Comment by jeroenpraat** [comment]
> Looks like it was @jeroenpraat's decision. I'm interested to hear why...

Because K is an English thing, not a Dutch thing. But if other people don't care I can change it back of course.

**Comment by jeroenpraat** [comment]
On Twitter they use the full number (see screenshot). Actually, I find that cleaner and solves translation issues.

![afbeelding](https://user-images.githubusercontent.com/41594439/100941431-e5b0c380-34f9-11eb-9465-1fd4b848b346.png)

**Comment by mstdn** [comment]
> On Twitter they use the full number (see screenshot). Actually, I find that cleaner and solves translation issues.
> 
> ![afbeelding](https://user-images.githubusercontent.com/41594439/100941431-e5b0c380-34f9-11eb-9465-1fd4b848b346.png)

Thats also nice but what about big numbers? What if the title goes up and the count down?

**Comment by jeroenpraat** [comment]
10.000 and more it uses K in Dutch. And mln. for million (see screenshot). I will take a look tomorrow or Friday. Have to update the translation anyway.

![afbeelding](https://user-images.githubusercontent.com/41594439/100941710-59eb6700-34fa-11eb-9cea-593aa5d2d2e8.png)

**Comment by jeroenpraat** [comment]
@mstdn I updated the translation of K (k), M (mln.) and B (mrd.). These are official Dutch abbreviations. k is lowercase. This should actually also be changed in English to lowercase, but that's not my jurisdiction :wink: .

**Comment by mstdn** [comment]
> @mstdn I updated the translation of K (k), M (mln.) and B (mrd.). These are official Dutch abbreviations. k is lowercase. This should actually also be changed in English to lowercase, but that's not my jurisdiction 😉 .

Great job, thank you!
