### ISSUE TITLE
replies_policy naming precludes future option to show "all replies" for real

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#15278]
I mentioned in the initial PR #9205 that I would like an option to view all replies, the way Tweetdeck circa 2011 worked, or more similar to how Pleroma works by default. But currently, the `replies_policy` Enumerable uses `all_replies` to indicate showing replies to any followed user, rather than truly "all" replies. In other words, the current behavior is thus:

- `all_replies` shows to followed users
- `list_replies` shows to list members
- `no_replies` shows to no one

Ideally I'd like to see that fourth option be added, but I'm not sure what name it would take. At the risk of bikeshedding a bit, I think it would make more sense to have these options instead, with a simplified naming scheme:

- `all` shows to all users
- `followed` shows to followed users
- `list` shows to list members
- `none` shows to no one

Thought I'd mention this while 3.3.0 is still in RC phase, i.e. this change hasn't hit a stable release yet. cc @ThibG

**Comment by Gargron** [comment]
I would be okay with it, though another option is to use "unfiltered" as a level above "all".
