### ISSUE TITLE
How to make the invite request field mandatory

### ISSUE THREAD

**Issue by c-chell** [tootsuite/mastodon#15273]
Hello,

On my instance, I activate the manual approval mode for accounts.
Now I'm dealing with high amount of accounts created without the invite field (Why do you want to join?) completed.
I want to make this field mandatory/required.

(after more than hour of search)
I try to edit the file /app/views/auth/registrations/new.html.haml to change to
= invite_request_fields.input :text, as: :text, wrapper: :with_block_label, required: true
(I also run the commands RAILS_ENV=production bundle exec rails assets:precompile and restart mastodon processes after that)

But the field is not required and I can create a test account without this field.

How to make this field mandatory ?
(version 3.2.1)

Thank you.

**Comment by mashirozx** [comment]
look here
https://github.com/mashirozx/mastodon/commit/b1e4c5e59e11e7d85761874f564e5c8d5b90e83b

**Comment by c-chell** [comment]
Thank you for the link but it's not work.

With this diff :
diff --git a/app/views/about/_registration.html.haml b/app/views/about/_registration.html.haml
index af28e2174..8f313e143 100644
--- a/app/views/about/_registration.html.haml
+++ b/app/views/about/_registration.html.haml
@@ -13,7 +13,7 @@
     - if approved_registrations?
       .fields-group
         = f.simple_fields_for :invite_request do |invite_request_fields|
-          = invite_request_fields.input :text, as: :text, wrapper: :with_block_label, required: false
+          = invite_request_fields.input :text, as: :text, wrapper: :with_block_label, required: true
 
     .fields-group
       = f.input :agreement, as: :boolean, wrapper: :with_label, label: t('auth.checkbox_agreement_html', rules_path: about_more_path, terms_path: terms_path), disabled: closed_registrations?
diff --git a/app/views/auth/registrations/new.html.haml b/app/views/auth/registrations/new.html.haml
index 457bc1d23..4ff972096 100644
--- a/app/views/auth/registrations/new.html.haml
+++ b/app/views/auth/registrations/new.html.haml
@@ -28,7 +28,7 @@
   - if approved_registrations? && !@invite.present?
     .fields-group
       = f.simple_fields_for :invite_request, resource.invite_request || resource.build_invite_request do |invite_request_fields|
-        = invite_request_fields.input :text, as: :text, wrapper: :with_block_label, required: false
+        = invite_request_fields.input :text, as: :text, wrapper: :with_block_label, required: true
 
   = f.input :invite_code, as: :hidden

The field is still not required to validate the registration.

**Comment by ThibG** [comment]
This is something I had planned on working on today, I will do so.

@mashirozx's suggestion seems mostly correct to me, except it won't enforce the verification on the backend. Did you restart mastodon-web?

**Comment by c-chell** [comment]
I restart these services :
service mastodon-streaming restart
service mastodon-web restart
service mastodon-sidekiq restart

I don't know what is missing.
(Also even if I'm a developer, I'm mostly on C# and PHP and totally out of Ruby)

**Comment by mashirozx** [comment]
Seems there is no request field here:
app/views/invites/_form.html.haml

Shall we add logic of pending account with a invite link? (I think this is a bit unreasonal)

**Comment by ThibG** [comment]
@c-chell oh, if you're applying this change on top of v3.2.1, you also need to add `html: { novalidate: false }` to the `= simple_form_for(` lines in the files you edited

**Comment by mashirozx** [comment]
Invite link means user is allowed to join.
Invite request means user is not allowed temporary.
So if admin need to audit every account, it's OK just turn off invite link and users invite others just with the site URL (・・;)

**Comment by mashirozx** [comment]
uhhh, I'm misunderstanding (・・;)

**Comment by c-chell** [comment]
> @c-chell oh, if you're applying this change on top of v3.2.1, you also need to add `html: { novalidate: false }` to the `= simple_form_for(` lines in the files you edited

Thank you, now the field is required in the browser; but not on the server, I test it with using the inspector of the browser and if I remove manually the require attribute of the field the account is created.
This is the first step to block spam account creation, thank you for the information.

**Comment by c-chell** [comment]
Thank you @ThibG  for your code, I copy it on my custom branch and it's seems to work great.
(Just for my knowledge, do I need to "close" the discussion or do I need to wait the PR validated ? )

**Comment by ThibG** [comment]
The issue will automatically be closed when (if) the PR gets merged
