### ISSUE TITLE
`GET /api/v1/accounts/:id/featured_tags` returns empty array

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#15279]
### Steps to reproduce
1. Call `GET https://mastodon.social/api/v1/accounts/14715/featured_tags` (this is my account)

### Expected behavior
1. We should see the entity representation for my featured tag `#nowplaying`

### Actual behavior
`[]`

mastodon.social latest master

**Comment by Gargron** [comment]
Probably fixed by #15270
