### ISSUE TITLE
Nokogiri::XML::XPath::SyntaxError if remote instance returns empty/invalid atom feed

### ISSUE THREAD

**Issue by lutoma** [tootsuite/mastodon#1529]
Noticed this one while testing a custom (buggy) OStatus implementation:

If the remote instance returns an invalid (just tried it with a completely empty response) atom feed, Mastodon will just throw an HTTP 500.

Not sure if this is expoitable/relevant for security in any way, but I guess that error could still be caught.

```
Nokogiri::XML::XPath::SyntaxError (Undefined namespace prefix: //xmlns:link[@rel="hub"]):

app/services/follow_remote_account_service.rb:67:in `get_hubs'
app/services/follow_remote_account_service.rb:48:in `call'
app/services/account_search_service.rb:21:in `call'
app/services/search_service.rb:15:in `call'
app/controllers/api/v1/search_controller.rb:7:in `index'
app/controllers/concerns/localized.rb:24:in `block in set_locale'
app/controllers/concerns/localized.rb:23:in `set_locale'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mattjmattj** [comment]
In app/services/follow_remote_account_service.rb, all the XPaths rely on the fact that the incoming Atom feed is formatted with a global xmlns namespace on the root `<feed>` element. 
This is quite unsafe IMO. 
For example, `<atom:feed xmlns:atom="http://www.w3.org/2005/Atom"></atom:feed>` would be a valid Atom feed, but would cause the same error has the one described here.

I suggest not to rely on the namespaces names declared on the feed, and replace every
`xml.xpath('//xmlns:link[@rel="hub"]')` 
by something like
`xml.xpath('//atom:link[@rel="hub"]', 'atom' => 'http://www.w3.org/2005/Atom')`

Note: I won't make a PR on this one because I don't have a good enough environment to test it

**Comment by Gargron** [comment]
@mattjmattj Actually, most places in the code do it exactly like you suggest:

    xml.at_xpath('/xmlns:entry/xmlns:author/xmlns:name', xmlns: TagManager::XMLNS)

Where `TagManager::XMLNS` is `http://www.w3.org/2005/Atom`. If some places don't use that, they need to be patched, but XML syntax errors can still occur with completely invalid or missing XML, so the actual solution to this issue is catching that exception before it reaches the end-user.

**Comment by mattjmattj** [comment]
Agree. But I think the SyntaxError would be different then (Undefined namespace prefix). You're right anyway.

**Comment by wxcafe** [comment]
I'm getting this too when trying to follow a specific user on cybre.space 
<img width="1678" alt="screen shot 2017-04-17 at 16 50 05" src="https://cloud.githubusercontent.com/assets/3009327/25093902/d6b2f6ac-2394-11e7-826a-19d873e1a222.png">

**Comment by nightpool** [comment]
@wxcafe Interestingly, that's a remote user... how did you end up following them on cybre.space?

**Comment by wxcafe** [comment]
Sorry should have been clearer : I tried to follow someone who is on cybre.space while I'm on social.wxcafe.net

**Comment by nightpool** [comment]
@wxcafe right, but the user in your screenshot isn't a cybre.space user. They're a mastodon.cloud user

**Comment by wxcafe** [comment]
What makes you say this?

**Comment by nightpool** [comment]
@wxcafe Because when I navigate to cybre.space/web/accounts/10488, or look 10488 up in the admin panel, they're a remote user?

**Comment by wxcafe** [comment]
yeah, you should look at social.wxcafe.net/web/accounts/10488, since I'm following from social.wxcafe.net. And it *is* a user from cybre.space

**Comment by nightpool** [comment]
Ah, I see. excuse my misunderstanding.

**Comment by wxcafe** [comment]
no problems

**Comment by mdbraber** [comment]
Not sure why this is closed, I'm still receiving the exact same error as @wxcafe is receiving trying to follow a user on counter.social (from mastodon.nl):

```
[e59c66af-09aa-4801-9c09-d83f4f87376e] method=GET path=/api/v2/search format=html controller=Api::V2::SearchController action=index status=500 error='Nokogiri::XML::XPath::SyntaxError: ERROR: Undefined namespace prefix: /xmlns:feed/xmlns:author/xmlns:uri' duration=1759.26 view=0.00 db=2.10
[e59c66af-09aa-4801-9c09-d83f4f87376e]
[e59c66af-09aa-4801-9c09-d83f4f87376e] Nokogiri::XML::XPath::SyntaxError (ERROR: Undefined namespace prefix: /xmlns:feed/xmlns:author/xmlns:uri):
[e59c66af-09aa-4801-9c09-d83f4f87376e]
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/services/resolve_account_service.rb:164:in `canonical_uri'
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/services/resolve_account_service.rb:74:in `ostatus_ready?'
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/services/resolve_account_service.rb:66:in `links_missing?'
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/services/resolve_account_service.rb:40:in `call'
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/services/account_search_service.rb:21:in `search_service_results'
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/services/account_search_service.rb:12:in `call'
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/services/search_service.rb:26:in `perform_accounts_search!'
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/services/search_service.rb:16:in `block in call'
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/services/search_service.rb:12:in `tap'
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/services/search_service.rb:12:in `call'
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/controllers/api/v1/search_controller.rb:33:in `search_results'
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/controllers/api/v1/search_controller.rb:21:in `search'
[e59c66af-09aa-4801-9c09-d83f4f87376e] app/controllers/api/v2/search_controller.rb:5:in `index'
```

Any solution that was found for this?
