### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by ufo56** [tootsuite/mastodon#1531]
Log https://pastebin.com/ikRxZzyZ

Some certificate error with latest version when i try to send mail thru mailgun.

**Comment by rhaamo** [comment]
Which "latest" version ?
From comment in #1496 it should be fixed.
Also look at #1486

**Comment by ufo56** [comment]
20 minutes ago git pull

**Comment by lutoma** [comment]
I think that happens if your mail server doesn't have a valid/trusted TLS certificate now.

**Comment by ufo56** [comment]
I have tried with mailgun and sparkpost

**Comment by ufo56** [comment]
I did that trick now and it works

https://github.com/tootsuite/mastodon/pull/1486/commits/0911f124de9bf71bacfff389ac6da1d3c1a960e1

**Comment by kyzh** [comment]
@ufo56 can you put a note in the PR ?

**Comment by wxcafe** [comment]
I'm marking this as closed since #1486 fixes it and it's gonna be merged soon
