### ISSUE TITLE
Content Warning tag added unexpectedly

### ISSUE THREAD

**Issue by Altreus** [tootsuite/mastodon#1534]
A bug in the auto-CW on replies!

* Expand a toot with a CW (the one I used was in the federated timeline - this may be relevant)
* Reply to a different toot (in my case, also in the federated timeline) with no CW
* The reply has the CW of the first toot

I didn't notice this when I replied, so I didn't remove it, and now it's weirded.

Here is my reply toot https://mastodon.social/@Altreus/2241968

Unfortunately the federated timeline has gone so fast now I can't find the originals.

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Aldarone** [comment]
Confirmed on witches.town, we currently run on 11898a6
