### ISSUE TITLE
smtp customization change changes the default mail behavior

### ISSUE THREAD

**Issue by ericblade** [tootsuite/mastodon#1535]
Change 0dbbc16c69652afe63d0b3dd49c06939351e3bc6 changes the default SMTP behavior into a way that is not compatible with the previous configuration, nor does it specify what the valid values are for SMTP_AUTH_METHOD, SMTP_OPENSSL_VERIFY_MODE, SMTP_ENABLE_STARTTLS_AUTO . 

After applying that change, a previously working installation using the default options results in:

```
sidekiq_1    | 2017-04-11T13:28:05.219Z 1 TID-gtelakswk WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::DeliveryJob","queue":"mailers","args":[{"job_class":"ActionMailer::DeliveryJob","job_id":"47e86ae9-ec78-4594-ad30-64be1e032a71","queue_name":"mailers","priority":null,"arguments":["UserMailer","confirmation_instructions","deliver_now",{"_aj_globalid":"gid://mastodon/User/1"},"TDbGBLuHxTEGG2pSTr6s",{"_aj_symbol_keys":[]}],"locale":"en"}],"retry":true,"jid":"a9105c50ca96c4aca6cd24f7","created_at":1491917284.2855172,"enqueued_at":1491917284.2856731,"error_message":"SSL_connect returned=1 errno=0 state=error: certificate verify failed","error_class":"OpenSSL::SSL::SSLError","failed_at":1491917285.2191546,"retry_count":0},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::DeliveryJob\",\"queue\":\"mailers\",\"args\":[{\"job_class\":\"ActionMailer::DeliveryJob\",\"job_id\":\"47e86ae9-ec78-4594-ad30-64be1e032a71\",\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"UserMailer\",\"confirmation_instructions\",\"deliver_now\",{\"_aj_globalid\":\"gid://mastodon/User/1\"},\"TDbGBLuHxTEGG2pSTr6s\",{\"_aj_symbol_keys\":[]}],\"locale\":\"en\"}],\"retry\":true,\"jid\":\"a9105c50ca96c4aca6cd24f7\",\"created_at\":1491917284.2855172,\"enqueued_at\":1491917284.2856731}"}
sidekiq_1    | 2017-04-11T13:28:05.219Z 1 TID-gtelakswk WARN: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error:
certificate verify failed
```

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyzh** [comment]
@ericblade have a look at https://github.com/tootsuite/mastodon/pull/1486
It has a workaround if you are using the default docker based instances.

**Comment by sangfroid70** [comment]
The default option for SMTP_OPENSSL_VERIFY_MODE is 'peer', try to force with 'none'

**Comment by ericblade** [comment]
Can confirm #1486 will repair.  Cannot confirm that it's exactly the right way, due to the discussion on that thread.  Committing new options and not documenting what they can be set to, only their default options, is bad form, IMO.  There are, for example, 4 places in the code where you can see that SMTP_AUTH_METHOD is plain, and SMTP_OPENSSL_VERIFY_MODE is peer, by default, but a whole code-base search to figure out what those environment variables can be set to, and google searches, result in nothing incredibly obvious.  (so it would seem they are linked to some other piece of software, but what to search to find that?)
