### ISSUE TITLE
TLD .gay is not supported in links

### ISSUE THREAD

**Issue by Ternoc** [tootsuite/mastodon#15366]
### Expected behaviour

When creating a toot including a link to a .gay url, a link shoud be generated.

### Actual behaviour

Instead, it is displayed as plain text.
![2020 12 19 00 14 16n](https://user-images.githubusercontent.com/11840322/102669976-78ef2780-418f-11eb-88b3-df4b03747eaf.png)

Also happen in the profile metada.

### Steps to reproduce the problem

Making a toot with a link to a .gay website

### Specifications

Mastodon v3.2.1

**Comment by ThibG** [comment]
As far as I can tell, this is handled by `app/javascript/mastodon/features/compose/util/url_regex.js` (to correctly compute character count client-side, as links count for a fixed amount of characters regardless of their real length) and the `twitter-text` gem server-side. We're using a very old version of that gem, so it's likely newer versions include more TLDs.

**Comment by ellymeskin** [comment]
It looks like this was fixed
