### ISSUE TITLE
Can not open the original toot from media page on mobile

### ISSUE THREAD

**Issue by pullopen** [tootsuite/mastodon#15374]
### Pitch

In the previous version, we can open the original toot if we open a media from someone's media page on mobile.  But after v3.3.0rc1 it's gone and now we have no way to open the original toot.

### Motivation

That would help us a lot with the context of a media.

**Comment by ThibG** [comment]
Indeed, it's hidden on mobile from CSS:
https://github.com/tootsuite/mastodon/blob/c4e860277dbc391a0c6ec0311f66a8484cca862b/app/javascript/styles/mastodon/components.scss#L7203-L7205

I think it's not intentional but a side-effect of sharing the styling with the pop-out player thing.
