### ISSUE TITLE
Invite link doesn't work with require reason to join on

### ISSUE THREAD

**Issue by mashirozx** [tootsuite/mastodon#15383]
### Expected behaviour
Register via an invite link.

### Actual behaviour
Invite link does not work (registration form always throws an error but no specific error message) with <require reason to join> option on. 

### Steps to reproduce the problem
Turn on require reason for joining option, and register through an invite link.

### Specifications
 3.3.0rc2

Seems relevant to #15326

**Comment by mashirozx** [comment]
`tootctl account create` also throws an error with option on…

**Comment by ThibG** [comment]
> `tootctl account create` also throws an error with option on…

sorry :weary:

fixed in #15405

**Comment by mashirozx** [comment]
never mind，thank you 😁
