### ISSUE TITLE
Where is the documentation to install mastodon with docker

### ISSUE THREAD

**Issue by TheCapsLock** [tootsuite/mastodon#15427]
I find installation process documented [here](https://docs.joinmastodon.org/admin/install/) far too complex, too painful for the value mastodon provides to my life. Editing a config file, running docker-compose up is a common way to go in any other project and should be enough to get started

this is not just a matter of installing ; but also upgrading: upgrading should be the easiest possible (at least for small instances)

There is people who run mastodon who are not fluent with ruby universe ; so please make things simpler.

**Comment by nightpool** [comment]
Unfortunately, we found that Docker had too many common pitfalls for less experienced sysadmins, so our current recommendation is that, unless you have experience with Docker, you follow the installation guide.

If you do have experience with Docker, then the docker-compose file should be self-explanatory, and you're welcome to use it

**Comment by TheCapsLock** [comment]
Is there a list of those pitfalls ? Where can we find it ?
