### ISSUE TITLE
How to update mastodon 3.1.2 to 3.2.2?

### ISSUE THREAD

**Issue by jakesullyneytiri** [tootsuite/mastodon#15423]
So I installed mastodon through digital ocean with their pre-made build of version 3.1.2.

My question can I upgrade it to 3.2.2? Since I had try but then it just said an error occurred when I tried to revisit my mastodon website.

So is there any command or so that could download latest and update it?

/Thanks

**Comment by jakesullyneytiri** [comment]
Update: sorry it's  3.1.3 that digital ocean has got. Not 3.1.2

**Comment by Gargron** [comment]
This should help: https://docs.joinmastodon.org/admin/upgrading/

**Comment by jakesullyneytiri** [comment]
> This should help: https://docs.joinmastodon.org/admin/upgrading/

I think I tried this, but when I did the mastodon broke and kept giving something went wrong after it.

So I had to wipe whole droplet and install 3.1.3 again from digital ocean.

**Comment by jakesullyneytiri** [comment]
Update: Ran this guide and when it says follow upgrade steps from release information, i do not see any upgrade steps on release log for 3.2.2 so now my mastodon just throws "We're sorry, but something went wrong on our end." so how do i fix this?

**Comment by jakesullyneytiri** [comment]
Update2: after some struggling i ran bundle install and yarn install again due to it said so in one earlier version and then i ran start cmd and such that got it back up but! toots page throws 500 error and not profiles won't function.

Seems this upgrade method is failure when doing 3.1.3 to 3.2.2 since it breaks whole thing completely.
