### ISSUE TITLE
Show og:image in timeline

### ISSUE THREAD

**Issue by frankmeeuwsen** [tootsuite/mastodon#1542]
When you toot an URL with open graph image, it now shows the title, publication and a small preview in your toot. It would be nice to also include the og:image in this snippet. I am not sure if this should be visible in the timeline because this might lutter three column timelines, but in the detail of the toot it can be shown. 
An example is seen on https://mastodon.social/@frankmeeuwsen/2242613 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
Is this the same issue as #1494 or are you referring to non-federated toots?

**Comment by frankmeeuwsen** [comment]
No it's more of an extension of that. Just that whén tooted links are expanded in detail view, also include the og:image tag to show the accompanying image.

**Comment by wxcafe** [comment]
Alright then. Could you do a PR?

**Comment by frankmeeuwsen** [comment]
Well...since I don't design or engineer anything, I don't have any PR. This is just an idea for someone to work on?

**Comment by Gargron** [comment]
og:image tag is used
