### ISSUE TITLE
Toots won't disappear until logout and login

### ISSUE THREAD

**Issue by jakesullyneytiri** [tootsuite/mastodon#15422]
So idk if this is an issue on mastodon itself or apps.

But when I use an app such as Tusky and Twidere and a user deletes a toot, then toot remains and to get it removed on my end and everyone else end they have to log out from the app and then relogin and then toot disappears.

But other wise old toot stays and won't disappear,  so I wanna know is this any issue with mastodon when it comes to syncing issue or what exactly could be problem here? Since it would be better if the app also updated and removed toot when you pull down to update for more.

/Thanks.

**Comment by Gargron** [comment]
This seems to be an issue specific to Tusky and Twidere. I suggest asking their respective developers directly. Mobile apps usually do not connect to the streaming API to save battery and avoid mobile data traffic.

**Comment by jakesullyneytiri** [comment]
Odd part is they load new toots fast but won't update to wipe old toots.
