### ISSUE TITLE
Block direct access to media from outside mastodon

### ISSUE THREAD

**Issue by jakesullyneytiri** [tootsuite/mastodon#15431]
Is there a way to make so if some 1 shares direct link to a media on a forum or so and they click link, it would instead of showing media it would say access forbidden or would just say 404 not found.

Since I don't want people to share direct media link so Google would start grabbing it.

Secondly is there easy way to make so site won't be listed on Google with all other pages?

**Comment by yingziwu** [comment]
```nginx
location / {
    if ($http_referer !~ "http://domain.xxx/"){
            return 403;
    }
}
```

**Comment by jakesullyneytiri** [comment]
> ```nginx
> location / {
>     if ($http_referer !~ "http://domain.xxx/"){
>             return 403;
>     }
> }
> ```

Where exactly do I put t this code?

**Comment by yingziwu** [comment]
@jakesullyneytiri 
If you don't use s3 storage, change your [nginx config](https://github.com/tootsuite/mastodon/blob/master/dist/nginx.conf#L56-L58)  as follows.

```nginx
  location / {
    if ($http_referer !~ "https://example.com/"){
      return 403;
    }
    try_files $uri @proxy;
  }
```

If you use s3 storage and set a reverse proxy.
You need to add following line to the main block of reverse proxy config, eg ``location /``.
```nginx
if ($http_referer !~ "https://example.com/"){
  return 403;
}
```

**Comment by Gargron** [comment]
I believe that's going to make it impossible to show media inside apps.

**Comment by jakesullyneytiri** [comment]
> I believe that's going to make it impossible to show media inside apps.

Not really.

If you limit the media so it can only be viewed within the domain and you visit the site to see the media it will show. But if some one links the media direct to another site and you click from there. That's when error appears since you don't have rights to view media then.

**Comment by jakesullyneytiri** [comment]
> @jakesullyneytiri
> If you don't use s3 storage, change your [nginx config](https://github.com/tootsuite/mastodon/blob/master/dist/nginx.conf#L56-L58) as follows.
> 
> ```nginx
>   location / {
>     if ($http_referer !~ "https://example.com/"){
>       return 403;
>     }
>     try_files $uri @proxy;
>   }
> ```
> 
> If you use s3 storage and set a reverse proxy.
> You need to add following line to the main block of reverse proxy config, eg `location /`.
> 
> ```nginx
> if ($http_referer !~ "https://example.com/"){
>   return 403;
> }
> ```

I added the code into my config file and restarted/reloaded nginx but i can still visit media on it's direct link anyway, shouldn't this code be giving a error instead?

**Comment by nightpool** [comment]
> > I believe that's going to make it impossible to show media inside apps.
> 
> Not really.
> 
> If you limit the media so it can only be viewed within the domain and you visit the site to see the media it will show. But if some one links the media direct to another site and you click from there. That's when error appears since you don't have rights to view media then.

Gargron is talking about native apps, like Tusky or Amaroq. Since they don't generally send referrer headers, they'll be blocked

**Comment by nightpool** [comment]
or even third-party web apps like Pinafore, which are generally hosted on a separate domain

**Comment by jakesullyneytiri** [comment]
> > > I believe that's going to make it impossible to show media inside apps.
> > 
> > Not really.
> > 
> > If you limit the media so it can only be viewed within the domain and you visit the site to see the media it will show. But if some one links the media direct to another site and you click from there. That's when error appears since you don't have rights to view media then.
> 
> Gargron is talking about native apps, like Tusky or Amaroq. Since they don't generally send referrer headers, they'll be blocked 

But doesn't the app use API through domain so images are still loading as long it's being loaded from domain area after login. That shouldn't affect the reject thing att all. But now problem is this reject thing blocks api or w.e this tusky requires to work on the mastodon.

**Comment by Gargron** [comment]
Apps use the API but media files are loaded through the exact same mechanism as in a browser (HTTP). Unlike a browser, native apps don't send a referrer header, so they would get blocked. You can go through with this but keep in mind this will be a point of frustration for your users and thus will not be supported/recommended by us.
