### ISSUE TITLE
Add ability to see custom emoji before signup

### ISSUE THREAD

**Issue by ahstro** [tootsuite/mastodon#15432]
Okay, so this might be a bit of a vain thing, but for me, the custom emoji available on an instance are quite important and as of now I have not found a way to figure out which emoji are available save for signing up and trying them out. I therefore think it would be nice to have the ability to see them somewhere, maybe on the `/about/more` page or something? 

(Also, I tried searching but couldn't find anything, so maybe this has been asked before, or maybe there already is a way to do this and I just haven't been able to find it. In that case, sorry, and please point me in the right direction 🙇)

**Comment by Happyfeet01** [comment]
You can ask the Admin before sign in

**Comment by Kjwon15** [comment]
You can use https://emojos.in (in example for my instance:  https://emojos.in/qdon.space)

**Comment by ahstro** [comment]
Oh my, thank you so much @Kjwon15 🥰
