### ISSUE TITLE
Visually distinguish local timeline and federated timeline

### ISSUE THREAD

**Issue by alexgleason** [tootsuite/mastodon#1543]
I think these are very important but confusing concepts to newcomers. Something should visually distinguish the two, maybe a change in background color, to really convey the idea that the user is in a different place.

**Comment by wxcafe** [comment]
Can you make a PR for this?

**Comment by crevebedaine** [comment]
They already have different title/logo, isn't it enough?

**Comment by alexgleason** [comment]
@wxcafe Yes, would you please assign me? Thanks!

@crevebedaine I don't think so.

**Comment by Gargron** [comment]
>They already have different title/logo, isn't it enough?

I think so too!

>Yes, would you please assign me? Thanks!

If you submit something that looks nice, I won't reject it, but I am closing this issue, because I do not think this is necessary (all columns look essentially the same)
