### ISSUE TITLE
Error: Failed to faind a valid digest in the'integrity' attribute for resource

### ISSUE THREAD

**Issue by noellabo** [tootsuite/mastodon#15439]
(This is a FAQ to prevent reporting known issues.)

In Mastodon v3.3.0, when minifying css with CDN, the following error occurs.

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://fedibird.com/packs/css/common-3623162d.css' with computed SHA-256 integrity 'U9PqBsevaeDRT4Yf8NwNRAwv30fPeD5mZyG+yxLtteE='. The resource has been blocked.
```

This is because Mastodon detects resource alterations and blocks loading to prevent malicious code from getting mixed in.

Setting the CDN not to minify will solve the problem.

Mastodon resources have already been minified.

See: https://github.com/tootsuite/mastodon/pull/15096#issuecomment-724163657

**Comment by izackwu** [comment]
If you are using Cloudflare, you may want to

1. Go to `Speed -> Optimization` to turn off `Auto Minify` for CSS, JS, and HTML. 
2. Go to `Caching -> Configuration` and `Purge Everything`
