### ISSUE TITLE
Docker hub "latest" tag doesn't point to 3.3.0

### ISSUE THREAD

**Issue by sphinxc0re** [tootsuite/mastodon#15441]
### Expected behaviour

`docker-compose pull` should pull the latest stable release from docker hub.

### Actual behaviour

`docker-compose pull` currently pulls the 3.2.2 release.

### Steps to reproduce the problem

Try to update your mastodon instance using `docker-compose pull`

**Comment by Gargron** [comment]
It’s probably still building, Docker Hub is slow

**Comment by sphinxc0re** [comment]
Okay, it seems to be ready now 🤷🏼
