### ISSUE TITLE
add verified profile process & verified badge

### ISSUE THREAD

**Issue by jakesullyneytiri** [tootsuite/mastodon#15466]
It would be nice to let others users verify their identity on mastodon if they want to get verified badge like on twitter a small rounded blue icon with symbol in it showing this user is verified user and real person behind it.

Also admins shall be able to manually give and remove verified badge to/from user as well.

This way people on mastodon can find verified users if they want too :)

IDK if this has already been mentioned, if it has then i will let other user who already took this up to continue their request.

**Comment by ThibG** [comment]
Yeah, this has been discussed in the past (e.g., #8276)

There is no much point in doing that as Mastodon isn't centralized. Instead, users can have links in their profile fields, and those links can be verified to point back to the Mastodon profile.
