### ISSUE TITLE
Follow button misaligned since v3.3.0 release

### ISSUE THREAD

**Issue by Krinkle** [tootsuite/mastodon#15470]
### Actual behaviour

| https://fosstodon.org/@geotechland/105454853007942362 | https://soundcafe.nl/@timo/105097440563429235
|--|--
|<img width="375" alt="Screenshot fosstodon" src="https://user-images.githubusercontent.com/156867/103383966-922b9880-4aec-11eb-9558-154c15cae191.png">|<img width="425" alt="Screenshot soundcafe" src="https://user-images.githubusercontent.com/156867/103383955-8a6bf400-4aec-11eb-8d11-4624a8ec86a4.png">

### Expected behaviour

Vertically centered within the button.

It seems disabling the `line-height: 16px;` rule on the `.button.logo-button` CSS rule has the desired effect, although it that probably has other side-effects so it might not be quite that easy, but helps to understand the issue and the expected outcome.

**Comment by noellabo** [comment]
It's my mistake. sorry!

If you want to deal with v3.3.0 without cherry-picking the fix, please register the following contents in Administration - Site settings - Custom CSS.
```
a.button.logo-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}
```
