### ISSUE TITLE
OCR not working when clicking "Detect text from picture"

### ISSUE THREAD

**Issue by hugogameiro** [tootsuite/mastodon#15472]
After uploading an image and clicking "Detect text from picture" nothing happens and an error is logged in console: `Uncaught Error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.`

I was able to reproduce this in multiple instances running v3.3.0 (tested both local and remote storage). Also found this problem ~~, on another running v3.2.1 and~~ on Mastodon.social (although Mastodon.social also returns CORS error).

**Comment by Gargron** [comment]
Cannot reproduce on mastodon.social, do not get a CORS error and OCR works as expected. I am on Firefox.

**Comment by hugogameiro** [comment]
I have tried both Firefox and Chrome and they both return the same on mastodon.social:
`Access to fetch at 'https://static-cdn.mastodon.social//eng.traineddata.gz' from origin 'https://mastodon.social' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
and
```
createWorker.js:173 Uncaught Error: TypeError: Failed to fetch
    at createWorker.js:173
    at Worker.e.onmessage (onMessage.js:3)
```

**Comment by freemo** [comment]
@Gargron BTW this is the issue I mentioned to you on the fediverse. I can confirm both myself and at least one other user also gets the error.

**Comment by Gargron** [comment]
Hm, `https://static-cdn.mastodon.social//eng.traineddata.gz` gives me HTTP 404, maybe that's why there's no CORS headers. It's supposed to be `https://static-cdn.mastodon.social/ocr/lang-data/eng.traineddata.gz`. The thing is, even if I reset cache, I do not even see Firefox trying to fetch eng.traineddata.gz in the network requests tab, at all. It just works.

**Comment by hugogameiro** [comment]
Really strange. I am not using a VPN on this computer, I have tried accessing in private mode without any browser extensions and it shows the same to me. I even tried changing Mastodon language settings and language filters and I can't get it to work.

**Comment by hugogameiro** [comment]
I guess the path is the problem. Everywhere I test Mastodon attempts to get `./eng.traineddata.gz` and not `./ocr/lang-data/eng.traineddata.gz`. The same when using CDN it should be `hostcdn.tld/ocr/lang-data/eng.traineddata.gz` and I get `hostcdn.tld//eng.traineddata.gz`. 

Can't think of a reason for this to happen on some browsers/devices. I have even tried now on my mobile phone using mobile data and the same, OCR just hangs. Can't think what could cause a device/browser to strip the `ocr/lang-data` from the path.

**Comment by freemo** [comment]
I dont know exactly why it is working for @Gargron when it doesnt for us. But the problem is the lack of the TESSDATA_PREFIX environment variable it would seem. the error in the browser specifically mentions it. I suspect it is trying to do something like `https://static-cdn.mastodon.social/${TESSDATA_PREFIX}/eng.traineddata.gz` but since it is blank it is just turning that into `https://static-cdn.mastodon.social//eng.traineddata.gz`, though I'd expect that to show as an issue for Gargron and literally every browser.

I'm just speculating of course, but considering the browser specifically complains about that environment variable not being set it would make sense.

**Comment by hugogameiro** [comment]
I have updated the OP that the issue is only present on v3.3.0. The fork I had tested was on Master v3.2.1 and not on the Tag. I suspect that the changes introduced in #14708 and #14381 are causing the problem because they change the way the Tesseract paths are handled, just can't make sense of how this could work for some people and not for others.

**Comment by joenepraat** [comment]
I've updated four server to version 3.4.0. Two of them work as expected and two are not. This was the same on version 3.3.0. I can't think of any difference those servers. Anyhow, this issue isn't solved for me.

![afbeelding](https://user-images.githubusercontent.com/41594439/120039731-afb24f00-c005-11eb-811c-00c021c8fd9b.png)

**Comment by joenepraat** [comment]
The only (but I think unrelated) difference is that the two servers that are giving above errors, are using Pgbouncer.

**Comment by ClearlyClaire** [comment]
The servers using Pgbouncer is 100% unrelated. This is weird, #15519 should have fixed this issue. Are you sure the assets have been properly rebuilt?

**Comment by joenepraat** [comment]
> This is weird, #15519 should have fixed this issue. Are you sure the assets have been properly rebuilt?

Yes I know for sure that the precompile worked. Other 3.4.0 fixes and new features are available.

**Comment by joenepraat** [comment]
And `app/javascript/mastodon/features/ui/components/focal_point_modal.js` has the line l`angPath: `${assetHost}/ocr/lang-data/`,`

**Comment by joenepraat** [comment]
@ClearlyClaire I did:

```
RAILS_ENV=production
bundle exec rails assets:clobber && bundle exec rails assets:precompile
```

... but still the same errors. When I check the compiled assets at https://todon.eu/packs/js/common-1dc6bba39b904d4ea1a7.js I see that it's the right version.

**Comment by joenepraat** [comment]
This is odd. It works on Firefox (stable and beta) on Android 10, but it gives above errors when on Ubuntu 20.04. It doesn't matter which browser I use. I tested Firefox, Gnome Web and Chromium.

**Comment by joenepraat** [comment]
:laughing: I needed to log-out and log-in again on both sites. I had to delete the cookies and other website related stuff, and relogin. Now it works! So it was something with the session. Still odd that other browsers also had this problem, because I almost never uses those for these sites.

**Comment by hugogameiro** [comment]
Probably there is still something going on. The OCR is back failing for me and even on Mastodon.social is failing with console errors:
```
createWorker.js
Uncaught Error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at createWorker.js:173
    at Worker.e.onmessage (onMessage.js:3)

```
```
asyncToGenerator.js
Uncaught (in promise) RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
```

**Comment by hugogameiro** [comment]
OK, so after some more testing I continued to get the same errors on Mastodon.social and on one of instances I host:

> ```
> createWorker.js
> Uncaught Error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
>     at createWorker.js:173
>     at Worker.e.onmessage (onMessage.js:3)
> ```
> 
> ```
> asyncToGenerator.js
> Uncaught (in promise) RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
> ```

After clearing the browser cache, my instance is working and Mastodon.social shows the CORS error. Obviously MS issue CORS and it's not a bug but it looks like there is a situation where the browser cache breaks OCR.

**Comment by ClearlyClaire** [comment]
Hmmm… I think the only thing that isn't explicitly “versioned” is `eng.traineddata.gz`. Maybe its format changed between releases? If someone can still find a browser session that fails, it would be interesting to try and remove just that from the cache…

**Comment by hugogameiro** [comment]
I have one browser with a session that fails but looking at cache I see no reference to `eng.traineddata.gz` all I see that could be somewhat related is:
```
/packs/ocr/tesseract-core.wasm-HASH
/packs/ocr/worker.min-HASH
```

**Comment by ClearlyClaire** [comment]
ok, I don't expect any of them to be an actual issue, but try removing one from the cache to see?

**Comment by hugogameiro** [comment]
After I had tried everything from deleting all the files in the browser local cache, to deleting all the cookies, doing a login and logout and nothing worked.

Then, I found `eng.traineddata.gz` under `IndexedDB->keyval-store->keyval`:
<img width="1515" alt="eng traineddata" src="https://user-images.githubusercontent.com/2203024/121676045-10349800-caac-11eb-986e-38d864d81bba.png">

And you were right deleting that fixed the issue.

**Comment by ClearlyClaire** [comment]
Alright, what happens is that tesseract.js cached an HTML page as “eng.traineddata” (likely a 404 or 500), which is obviously not correct. I am not completely sure what should be done, but I will look into catching that error and clearing the cache, if possible.
