### ISSUE TITLE
Database still corrupt after 'tootctl maintenance fix-duplicates'

### ISSUE THREAD

**Issue by joenepraat** [tootsuite/mastodon#15475]
After the successful update to version 3.3.0 I checked if the database was still corrupt (fixed with the previous version with [this](https://github.com/tootsuite/mastodon/issues/14443#issuecomment-664511281)). I used the documentation on https://docs.joinmastodon.org/admin/troubleshooting/index-corruption/ and it still gives this output while running both query's afterwards:

```
ERROR:  high key invariant violated for index "index_accounts_on_uri"
DETAIL:  Index tid=(1847,44) points to heap tid=(2333,6) page lsn=390/6C912730.
```
I also noticed problems with migrating an account on this server to a new account on the same server. It only copied the local followers and didn't update the follower count. So that is probably related, cause on another server I maintain, migration worked without issues.

**Comment by ThibG** [comment]
oh, right, this index isn't fixed by the migration script

I kind of forgot about it because it had no unique constraint, but it being corrupted is still an issue.

I will cook up a fix, but for now you can probably safely run `REINDEX DATABASE mastodon_production;` in PostgreSQL.

**Comment by joenepraat** [comment]
Thank you @ThibG !

> you can probably safely run

What you mean with 'probably'? What are the risks if I do that?

**Comment by ThibG** [comment]
Sorry, I meant you can safely run that, and it will probably be enough.

Now that I've gone through that, I can definitely say it will be enough, except it won't fix the stats of the already-moved account.

Instead of running `REINDEX DATABASE mastodon_production` you can run the following, it will be faster:
```
REINDEX INDEX search_index;
REINDEX INDEX index_accounts_on_uri;
REINDEX INDEX index_accounts_on_url;
```

**Comment by joenepraat** [comment]
@ThibG Thanks again. I presume I need to run that as a query after connecting a _\connect mastodon_production_?

I understand about the failed migration. I already did it largely manually, so that is not needed anymore for myself.

**Comment by ThibG** [comment]
> I presume I need to run that as a query after _\connect mastodon_production_?

yes

**Comment by joenepraat** [comment]
This worked! Thank you @ThibG for fixing this. Closing now.
