### ISSUE TITLE
Links in left sidebar don't work in Safari

### ISSUE THREAD

**Issue by mthld** [tootsuite/mastodon#15499]
### Expected behaviour
The links in the left sidebar ("Invite People, Hotkeys...") should work on Safari too.

### Actual behaviour
When you hover the link you notice they aren't clickable.

### Steps to reproduce the problem
See the following screen records:

#### Safari (not working)
https://user-images.githubusercontent.com/41020854/103705349-2c875280-4fab-11eb-87d6-b41fa816b052.mov

#### Firefox (working as intended)
https://user-images.githubusercontent.com/41020854/103705421-46c13080-4fab-11eb-9156-303e8dc53b64.mov

### Specifications
- Mastodon v3.3.0
- macOS v11.1
- Safari v14.0.2
- Firefox v84.0.1

I checked the Javascript console of both web browsers and didn't find anything related to this issue. Tell me if I can provide more informations.

**Comment by noellabo** [comment]
Fixed in https://github.com/tootsuite/mastodon/pull/15496
