### ISSUE TITLE
Can tag other users from other servers

### ISSUE THREAD

**Issue by jakesullyneytiri** [tootsuite/mastodon#15492]
So i noticed i could all of sudden tag some 1 from completely another server from my own server??

I thought mastodon only would work like if you make 1 server and then add another to it, then you can tag some one else on first server from 2nd server??

But now i could tag some 1 called Marlon from following mastodon server https://loves.pizza/ and user https://loves.pizza/@marlon on my own mastodon server when this server isn't even connected with mine??

So how is this even possible?

Or is this what it should be or not?

Since now i'm confused.

**Comment by jakesullyneytiri** [comment]
Update:

Noticed out of no where 3 new federation domains where added to my mastodon??? I never added them so how on earth where they connected to my server??

**Comment by Gargron** [comment]
https://docs.joinmastodon.org/

> A Mastodon website can operate alone. Just like a traditional website, people sign up on it, post messages, upload pictures and talk to each other. Unlike a traditional website, Mastodon websites can interoperate, letting their users communicate with each other; just like you can send an email from your Gmail account to someone from Outlook, Fastmail, Protonmail, or any other email provider, as long as you know their email address, **you can mention or message anyone on any website using their address.**

**Comment by jakesullyneytiri** [comment]
But on mine I only have to do @marlon and it shows up on mine. I noticed 3 domains connected to my federation page which I'm sure they where not there before. So I still think this is a bug

**Comment by jakesullyneytiri** [comment]
> https://docs.joinmastodon.org/
> 
> > A Mastodon website can operate alone. Just like a traditional website, people sign up on it, post messages, upload pictures and talk to each other. Unlike a traditional website, Mastodon websites can interoperate, letting their users communicate with each other; just like you can send an email from your Gmail account to someone from Outlook, Fastmail, Protonmail, or any other email provider, as long as you know their email address, **you can mention or message anyone on any website using their address.**

But on mine I only have to do @marlon and it shows up on mine. I noticed 3 domains connected to my federation page which I'm sure they where not there before. So I still think this is a bug

**Comment by Gargron** [comment]
Mastodon does not require you to manually "connect" servers. In fact, servers are never "connected". When you follow someone from another server, you start receiving posts of that user from that server to your server. You can tag anyone from another server any time. That's it. The "federation" page in the admin interface represents known servers, not manually connected servers (known = at least one account discovered).
