### ISSUE TITLE
Cross-domain mentions in profile metadata should include the domain on the profile page

### ISSUE THREAD

**Issue by jilleJr** [tootsuite/mastodon#15506]
Given I'm user `@me@example.com` _(I'm not, but just for sake of argument)_ and I add the following two mentions to my profiles metadata:

Label | Content
--- | --- |
Example1 | `@someUser@example.com`
Example2 | `@Gargron@mastodon.social`

## Expected

The user profile shows

Label | Content
--- | --- |
Example1 | [@someUser](https://example.com/@someUser) _(as it's the same domain)_
Example2 | [@Gargron@mastodon.social](https://mastodon.social/@Gargron) _(as it's on a different domain)_

## Actual

The user profile shows

Label | Content
--- | --- |
Example1 | [@someUser](https://example.com/@someUser)
Example2 | [@Gargron](https://mastodon.social/@Gargron) _(this one suggests there is a user named `@Gargon` on `example.com`)_

**Comment by jilleJr** [comment]
Would the fix be as simple as just checking

- if domain == mention.domain
  - display mention.name
- else
  - display mention.nameWithDomain

..or is there potentionally more depth to this? If the former, I would like to try creating a PR on this :)

**Comment by ThibG** [comment]
I'm not sure why this should behave differently than in toots themselves?

**Comment by jilleJr** [comment]
Good point. Personally I would like to see the full domain at all times. Could maybe be better suited as a setting, though difficult to have as it will display differently as soon as you visit a Mastodon instance you don't have a login for
