### ISSUE TITLE
Administration: Send a toot to all users on my instance

### ISSUE THREAD

**Issue by Floppy** [tootsuite/mastodon#1555]
As an instance administrator, I would like to send a toot to everyone on my instance to let them know about things like maintenance, etc.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Fastidious** [comment]
@Floppy if you post a toot, all users in your instance should see it on the local timeline (and many, at home). The thing is, any toot you send will eventually make it to the federated timeline too...

**Comment by carlosjs23** [comment]
It may be better to do this as a notification rather than a toot, see #1209

**Comment by Floppy** [comment]
Notification was what I was thinking really, yes. Didn't spot #1209, reading now.

**Comment by Floppy** [comment]
OK, totally a dupe of #1209. Closing.
