### ISSUE TITLE
Muted users from blocked instance still show up in the timeline

### ISSUE THREAD

**Issue by resynth1943** [tootsuite/mastodon#15557]
![image](https://user-images.githubusercontent.com/49915996/104658964-bd50e300-56bb-11eb-9ae3-6fa11720b0a8.png)

### Expected behaviour

When I mute a user *and* block their instance, I don't expect
to see reblogs of their posts in my timeline.

This boost shows up in the Local timeline, if it makes any difference.

### Actual behaviour

When I muted the user and blocked their instance, reblogs
of their content still appeared in my timeline.

### Steps to reproduce the problem

- Mute someone and block their instance
- Have someonw you follow boost their post
- It shows up in your timeline

### Specifications

v3.3.0+koyuspace (no idea if that's an actual Mastodon version number)
/cc: @koyuawsmbrtn on that one.

**Comment by ThibG** [comment]
Boosts don't appear in the public timeline in mainline Mastodon. This may be a bug with the fork you are using, not Mastodon itself.
