### ISSUE TITLE
At sign (@) is a reserved character and should not be used in urls

### ISSUE THREAD

**Issue by zigurd** [tootsuite/mastodon#15565]
The use of at sign (@) in Mastodon urls causes embedding Mastodon content to fail in some cases, probably because of the at sign, a reserved character, in the url.

### Expected behaviour

It should be possible to embed, for example, a user's posts in a web page in Google Sites.

### Actual behaviour

On entering a Mastodon user feed url with, for example, @user in the url, an error is reported. That the feed is working can be confirmed by entering the url in the Chrome browser url bar and getting a correctly formatted result without errors.

The problem appears to be that some sites/apps/etc. filter malformed urls more strictly than others.

### Steps to reproduce the problem

Create a Google Sites site.
On the Insert tab choose "Embed."
Enter the user's feed url, as in: https://instancedomain/@username.rss
This results in an error stating that it could not be embedded due to "site permissions."
Other rss urls work correctly, e.g.: http://rss.cnn.com/rss/cnn_topstories.rss
Entering the user's rss feed url in Chrome returns apparently correct rss
Mastodon urls from the same instance, but not containing at sign, like https://instancedomain work correctly in Google Sites embedding
Some feed aggregators and other rss tools also work correctly

### Specifications

v3.3.0

**Comment by nightpool** [comment]
As you can see in the syntax production for `pchar`, "@" is [explicitly allowed as a character in paths](https://tools.ietf.org/html/rfc3986#section-3.3) by rfc3986. If Google Sites has a broken regex that's preventing valid URIs from being embedded, that's not Mastodon's problem. You can either percent encode the URL to work around this, as in `https://instance.tld/%40username`, or use the equivalent "long hand" path, `https://instance.tld/users/username`

**Comment by zigurd** [comment]
I tried the longer url. I get an unexpected result: It returns the same error. "Can't embed due to provider site permissions..."

Obviously no @ involved! But everything else is the same. Same results returned in Chrome, other rss feeds embed, other rss tools grok the Mastodon feed fine, etc.

So, yeah, it appears to be a Google Sites bug but not specific to the @. There is something it does not grok about the rss xml being returned.

**Comment by thefuturebird** [comment]
Since there is an alternative that won't break in tumblr, messages, and other places why can't that be the default? Helping people to link back to their posts would make it easier to use and less insular.

**Comment by nightpool** [comment]
@thefuturebird @robtfirefly Can you explain what you mean by this? I've never had issues linking Mastodon posts anywhere, and I link them regularly on Tumblr, messages, and other platforms. I think maybe your comment is unrelated to this issue, which was proven to be a Google site bug that had nothing to do with the @ character
