### ISSUE TITLE
status activity is still accessible without signature in authorized fetch mode

### ISSUE THREAD

**Issue by IzaliaMae** [tootsuite/mastodon#15589]
### Expected behaviour

Mastodon should respond with a 401 when accessing /users/{user}/statuses/{status}/activity when authorized fetch mode is on

### Actual behaviour

Mastodon responds with the whole activity which includes the status as an object

### Steps to reproduce the problem

Turn on authorized fetch mode and curl a status activity url

**Comment by ThibG** [comment]
Not sure about the security implications. They should be minimal since that URL is only ever the actual activity `id` for boosts.
Either way, this is a bug and I will look into it, thanks.
