### ISSUE TITLE
tags in mastodon (hastash) in instance whitout internet

### ISSUE THREAD

**Issue by AnonymousWebHacker** [tootsuite/mastodon#15588]
I have my instance in a SNET without internet access, there are more than 1000 users.

 I understand that in the mastodon footer, (where the most used #tags go) are from all instances. As my instance does not have internet access, I do not get it. 

This I could configure the mastodon to remove the tags only from the instance?

**Comment by ThibG** [comment]
Trending tags are the tags from toots known to your instance, so your instance not having internet access should not change anything.

**Comment by AnonymousWebHacker** [comment]
![nothing](https://user-images.githubusercontent.com/43164089/105112257-a4b44480-5a90-11eb-92d1-ddb6b21565db.png)

**Comment by ThibG** [comment]
Sorry, I'm not sure what this screenshot is supposed to show. Do you want trending tags or not?

If you want trending tags, by default, trending tags require review in the moderation settings before being shown (`/admin/tags`), which may be your issue.

Another possible issue is that the scheduled jobs, which hashtags depend on, do not run. Something related to that has been changed with the latest release and may require you to update your config, according to the [release notes](https://github.com/tootsuite/mastodon/releases/tag/v3.3.0):
> :warning: Scheduled tasks have been moved to a dedicated scheduler queue in Sidekiq. If you only run a single Sidekiq process with no custom queue selection, you don't need to change anything. If you customize Sidekiq processes/queues, ensure that there is exactly one Sidekiq process that runs the scheduler queue.

**Comment by AnonymousWebHacker** [comment]
Perfect, I'm going to update to the latest version of Mastodon, and check if the problem is fixed.

**Comment by AnonymousWebHacker** [comment]
![1614880166666-1211742295](https://user-images.githubusercontent.com/43164089/110006889-2500d300-7ce8-11eb-82b3-2038ebc13482.jpg)

**Comment by AnonymousWebHacker** [comment]
@gargron help here please

**Comment by AnonymousWebHacker** [comment]
![Screenshot from 2021-03-22 20-58-30](https://user-images.githubusercontent.com/43164089/112076923-bc23b280-8b51-11eb-927b-7e4717a88e45.png)
The trends #, which appear in the other instances, do not appear in my instance, no trends appear, when there are

**Comment by ClearlyClaire** [comment]
Check that:
1. trending tags are enabled: https://mastodon.azeroth.website/admin/settings/edit#form_admin_settings_trends
2. check that the scheduler tasks are running: https://mastodon.azeroth.website/sidekiq/recurring-jobs
3. make sure you actually get public posts with those hashtags: trending tags aren't exactly global, they are trending with regards to what your instance sees, trending hashtags on mastodon.social aren't the same as on your instance because both instances do not see the same content

**Comment by AnonymousWebHacker** [comment]
![Screenshot from 2021-03-23 17-57-01](https://user-images.githubusercontent.com/43164089/112224774-2ac04900-8c02-11eb-92c5-be9545b656a8.png)
![Screenshot from 2021-03-23 17-57-48](https://user-images.githubusercontent.com/43164089/112224790-30b62a00-8c02-11eb-88c5-ef3943e24cb8.png)
There are posts with comments and hastash # but there is no right hand list below.

I know they can't have the same tendencies as mastodon.social, I was just referring, that they don't come out like that that way.
@ClearlyClaire 
Remember that my instance is not connected to the internet, so it is not federated. Could it be because of that?

**Comment by ClearlyClaire** [comment]
The instance not peering with other instance does not have any influence over this feature, other than a reduced set of content to work with.

I'm inclined to think that it's simply that no hashtag is currently trending on your instance. I don't remember the exact algorithm, but I think a hashtag is considered trending if both those conditions are met:
- more than 5 people have used it today
- more people have used it today than yesterday

And out of the trending tags, only the top 3 are displayed, and only if they've been reviewed by an admin (but it seems in your case, no hashtag has ever entered the trending set).

**Comment by AnonymousWebHacker** [comment]
Fixed on https://github.com/tootsuite/mastodon/issues/16453
Thank you all
