### ISSUE TITLE
Chrome built-in translation messed up with React UI

### ISSUE THREAD

**Issue by yookoala** [tootsuite/mastodon#15609]
Originally found by a Taiwan user [here](https://g0v.social/web/statuses/105592564511603658). Since he / she is not confident in describing the situation in English, I studied the case and help created this issue on her behalf.

### Expected behaviour

* Chrome users should be able to use built-in translation on Mastodon without breaking the site; or
* Chrome users should not be able to use built-in translation on Mastodon.

### Actual behaviour

* Chrome users can use built-in translation. And when using it, React can run into errors.
* For example, after translation, scrolling down the timeline would result in an error like this:
  ```
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
      at gs (https://foobar.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1041255)
      at wu (https://foobar.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1054456)
      at https://foobar.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1074970
      at Va (https://foobar.com/packs/js/common-a34d4fc19bd4731b9983.js:2:999621)
      at _u (https://foobar.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1052316)
      at su (https://foobar.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1048470)
      at https://foobar.com/packs/js/common-a34d4fc19bd4731b9983.js:2:999912
      at https://foobar.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1074970
      at Va (https://foobar.com/packs/js/common-a34d4fc19bd4731b9983.js:2:999621)
      at Ya (https://foobar.com/packs/js/common-a34d4fc19bd4731b9983.js:2:999857)

  Ki (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5411:106)
  Mi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6363:21)
  unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
  cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
  Jj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6204:2)
  Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5895:4)
  cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2851:16)
  unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
  cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
  cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2846:6)
  ```

### Steps to reproduce the problem

1. Use Chrome to open any Mastodon site.
2. Login and open the main timeline.
3. Use Chrome't built-in translation tool and translate the site into another language.
4. Scroll down the timeline to load more toot.

### Specifications

The issue is found on Mastodon v3.3.0. But frankly I don't think that's version specific. It is most likely because of the problem described in facebook/react#11538. And if that's the case, the most straightforward "solution" would be to [declare that the page cannot be translated](https://stackoverflow.com/a/12238414/372172).

A more long term solution could be implement some translation tool (as suggested in #9690) so user won't use Chrome's translation and mess things up. For a while, Facebook provides a "[See Translation](https://www.youtube.com/watch?v=zPKuM0GHJwc)" button near a status. When used, Facebook will send the post content to [Bing Translator](https://www.bing.com/translator) and display the translation result. For our case, I think we can have options to use backend such as:

* Platform
  * [Apertium](https://www.apertium.org/)
  * Google Translate
  * Bing Translator
* Self-hosted Software
  * [OpenNMT](https://opennmt.net/)

**Comment by ThibG** [comment]
Just tried Google Chrome 88.0.4324.96 for Linux, and I couldn't reproduce the issue. It may be dependent on which components exactly are displayed on-screen, but so far I couldn't find anything that crashes the UI.

I will try something to mark the interface as untranslatable except for user-generated content (using `translate` and `notranslate` classes, the `translate` attribute does not seem to work), though.
