### ISSUE TITLE
IP Rules - Limit Access not being applied to CIDR ranges

### ISSUE THREAD

**Issue by jazmichaelking** [tootsuite/mastodon#15606]
I have IP Rules on CIDR ranges eg nnn.0.0.0/8 

Additionally I have IP Rules on specific IP addresses, but the following occurs whether or not there are competing rules for a given IP address.

### Expected behaviour

Setting the rule to `Limit Access` should require moderator approval of the account

### Actual behaviour

Accounts are Email confirmed and live without moderator approval

### Steps to reproduce the problem

Set a rule for an IP range
Attempt to register with `Block Access` enabled - Block works as intended
Attempt to register with `Limit Access` enabled - Limit Access fails and the account registers without approval

### Specifications

v3.3.0

**Comment by hugogameiro** [comment]
I can confirm that this is happening. I can block access via either single IP or a range but on limit sign-ups.

If someone creates an account using an IP that is in IP Rules with limit sign-up, the account goes to pending approval but once the user confirms the email the account is automatically approved.

**Comment by ThibG** [comment]
I can confirm, investigating.
