### ISSUE TITLE
Build instructions seem out of order in https://docs.joinmastodon.org/admin/install/

### ISSUE THREAD

**Issue by jarofgreen** [tootsuite/mastodon#15642]
### Expected behaviour

Install should work by following steps in https://docs.joinmastodon.org/admin/install/

#### Node and Yarn

The instructions say to add Node.js and Yarn ubuntu package sources - obviously cos you want the latest versions. That's fine but :

A)

After adding the Node.js package, nothing actually installs it. Don't you want a "apt-get install -y nodejs" here?

B) 

After adding the Yarn package again nothing actually installs it. Worse, in the "apt install -y " step yarn is included, so you end up with the old version of yarn.

I got the error: "yarn: error: no such option: --pure-lockfile"

To solve this I had to 
```

apt-get remove yarn
apt-get update
apt-get install yarn
```

#### Certbot

The instructions say: "Then edit /etc/nginx/sites-available/mastodon to replace example.com with your own domain name,  .... Reload nginx for the changes to take effect:"

Reloading fails with "no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/sites-enabled/mastodon:25" which is fair enough.

The certbox command then fails because of this.

To fix, I backed up /etc/nginx/sites-available/mastodon, edited it to remove the whole SSL block, ran certbot fine, then restored the backup and commented in the 2 lines pointing to the cert.

(After this, I had an odd issue where the usual nginx restart command wouldn't work because ports were already in use. I had to manually kill nginx processes and then start them.)

### Steps to reproduce the problem

Just trying to install Mastadon on my own server, using https://docs.joinmastodon.org/admin/install/

### Specifications

Ubuntu 20 LTS

v3.3.0

**Comment by trwnh** [comment]
you probably want to file this over at https://github.com/tootsuite/documentation instead

**Comment by jarofgreen** [comment]
Done - Thanks https://github.com/tootsuite/documentation/issues/857
