### ISSUE TITLE
Auto-remove unconfirmed users

### ISSUE THREAD

**Issue by Angristan** [tootsuite/mastodon#1565]
I have a lot of users that just register with some random username and email, don't confirm the account and never come back.

![screenshot_11-04-2017_b hwqfvrkf](https://cloud.githubusercontent.com/assets/11699655/24925983/5dada11a-1efa-11e7-8826-7d17aada1423.png)

![screenshot_11-04-2017_b wimylqg8](https://cloud.githubusercontent.com/assets/11699655/24925992/636ae70c-1efa-11e7-88e2-e641e045d567.png)

It's faking the user stats, taking useless space in the DB and taking usernames that may have been used by others.

It would be great to have an option to delete the users manually, or having a cron that delete them after a certain delay, 7 days for example. I believe it does not cause any problem for the federation.

**Comment by expenses** [comment]
You should be able to use cron to do the rake task now.

**Comment by Fritillaria** [comment]
Hello, I was able to register for an account, and have never been able to get a confirmation email sent to me despite trying about 50 times. If there is going to be autodelete, there should be some attention to why the process is not being finished in the first place. How many of these users gave up trying to get confirmation? Why allow a user to open an account if I can't confirm it? I'm a user, that's all, but I'm frustrated.

**Comment by Aldarone** [comment]
I'm on 8a58942 and when I tried the rake task I'm getting this exception : 

```
rails aborted!
NoMethodError: undefined method `delete_all' for #<Array:0x00564340b47998>
/mastodon/lib/tasks/mastodon.rake:85:in `block (4 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:121:in `block in find_in_batches'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:214:in `block in in_batches'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:198:in `loop'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:198:in `in_batches'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:120:in `find_in_batches'
/mastodon/lib/tasks/mastodon.rake:83:in `block (3 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => mastodon:users:clear
(See full trace by running task with --trace)
```

**Comment by Wonderfall** [comment]
I experience the same issue as @Aldarone.

**Comment by Wonderfall** [comment]
I confirm it's now fixed. Thanks for your work, @Gargron.

**Comment by Angristan** [comment]
Can we close this ? 🤔

**Comment by ashfurrow** [comment]
Yup, good idea @Angristan. Going to close.
