### ISSUE TITLE
follow and followers broken on web UI

### ISSUE THREAD

**Issue by gadgetvirtuoso** [tootsuite/mastodon#1566]
Selecting "Follow" or "Followers" from a profile on the web UI results in a "Oops. An unexpected error occurred." to appear.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by iamjamieadams** [comment]
Same issue on my instance since the last update.

**Comment by gadgetvirtuoso** [comment]
Does not occur on the iOS app Amaroq.

**Comment by mjankowski** [comment]
Can you give me a production URL where this occurs, and if possible, a log snippet of the request being made which causes the error?

**Comment by gadgetvirtuoso** [comment]
Occurring on noagendasocial.com Checking on the log snippet.

**Comment by iamjamieadams** [comment]
There's nothing in my logs - at all. Sorry.

**Comment by ericblade** [comment]
See #1491 .. seems that it's affecting people in lots of different areas.

**Comment by mjankowski** [comment]
Got it.

The error with the notifications tab causing the oops is a known issue, and possibly addressed by (not yet merged) https://github.com/tootsuite/mastodon/pull/1548
