### ISSUE TITLE
My vote isn't counted in poll

### ISSUE THREAD

**Issue by realpixelcode** [tootsuite/mastodon#15694]
I just participated in a poll and was the first one to vote. After voting the check mark appeared which indicated the option I chose. Nonetheless, my vote was not counted as 100% was displayed at the option I did not choose. Also, it said only 1 (the actual 2nd one to vote) person has participated.

![](https://user-images.githubusercontent.com/52963327/107358328-282ee780-6acb-11eb-8ea9-a3a575f9f265.png)

**Comment by Gargron** [comment]
You have refreshed before the origin server has processed your vote. Refresh again in a few minutes.

**Comment by realpixelcode** [comment]
Oh, sorry then for bothering 😬
