### ISSUE TITLE
Web interface fails to load citing Invalid sha256 hashes matching integrity attribute

### ISSUE THREAD

**Issue by booth-f** [tootsuite/mastodon#15702]
### Expected behaviour

Web interface loads up and allows a user to post and read messages.

### Actual behaviour

Page stops loading abruptly and just displays a white page with nothing else. Have to load up the developer console to see the error: "None of the “sha256” hashes in the integrity attribute match the content of the subresource."

### Steps to reproduce the problem

Website was working fine the other day. I had to take the server offline temporarily to invoke a fsck.ext4 on the drive due to errors about corruption in the filesystem. Once the server was rebooted this error occurred. I'm thinking one or more of the precompiled assets for the site got corrupted or "fixed" which resulted in the SHA256 hash for the file to no longer match. I attempted to force a regeneration of the assets using the following commands from inside the Mastodon Live directory:

RAILS_ENV=production rake webpacker:clobber 
RAILS_ENV=production rake webpacker:compile
RAILS_ENV=production bundle exec rails assets:clobber
RAILS_ENV=production bundle exec rails assets:precompile

Flushed the local browser cache, flushed Cloudflare's cache and even restarted all the mastodon-* services. Web interface still refuses to load with the same error.

### Specifications

Mastodon v3.3.0 and v3.3.0rc3. I pushed the server to rc3 from 3.3.0 in an attempt to get the interface working but didn't work.

Tried on two systems, one running Windows 10 using Google Chrome 88.0.4324.150 and Firefox 85.0.1 and the other running Gentoo Linux using the same versions.

**Comment by Gargron** [comment]
Do you use a CDN?

**Comment by booth-f** [comment]
Only Cloudflare and their caching is currently disabled / In Development mode. I didn't have this occur before I did things last night. I remember I would have a similar issue if I tried to use their RocketLoader for javascript which I already have disabled because of that reason.

**Comment by booth-f** [comment]
What makes it even more confusing is when I completely clear the browser cache and cookies I can get the page to load and let me log in, everything renders just fine. But if you then go to refresh the page or navigate off the main screen say to settings and back it will result in the white screen appearing again along with the same error messages.

**Comment by booth-f** [comment]
Oops, nevermind I get to feel like the idiot today. Apparently Adblocker Ultimate which I had in both browsers was attempting to inject code onto the site which was causing the sha256 hashes to not match. The moment I disabled it on the site and hit refresh it started working right away with no errors at all. 

Sorry about that.
