### ISSUE TITLE
Vector favicon for Safari pinned tabs

### ISSUE THREAD

**Issue by daprice** [tootsuite/mastodon#1572]
Safari on MacOS wants a single-layer, black .svg version of the favicon to show when the user “pins” a tab, along with a color to saturate the icon with on mouse hover (in the mean time, it just shows a square with the first letter of the instance’s domain, which isn’t bad, but a vector version of favicon.ico would probably be better). See [Apple’s docs on this](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html) and [this blog post with more info](http://blog.iconfactory.com/2015/11/the-new-favicon/).

I’d be happy to create this myself and add the `<link>` for it ~~if someone could point me to a vector version of the current favicon or Mastodon logo to work from~~.

Edit: just saw the SVG version linked in #962. I’ll go ahead and make a PR for this with the caveat that the logo itself might need to be updated after #962 is complete.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
SVG logo: https://github.com/tootsuite/mastodon/blob/master/app/assets/images/logo.svg

**Comment by xuv** [comment]
Just wanted to point out there is a pull request in the queue that updates the SVG logo so that it corresponds better to the actual logo being used. 

https://github.com/tootsuite/mastodon/pull/1362
