### ISSUE TITLE
Mastodon v3.3.0 return a 500 error when an inbox query does not have a Digest header

### ISSUE THREAD

**Issue by manuelleduc** [tootsuite/mastodon#15743]
### Expected behaviour

An error is returned when the Digest header is missing

### Actual behaviour

A 500 error without an actionable error message is returned to the caller

### Steps to reproduce the problem

Send a well-formed ActivityPub action to the inbox of a Mastodon v3.3.0 actor, without a Digest header.
I discovered the issue while sending a follow request.

### Specifications

Mastodon v3.3.0

**Comment by ClearlyClaire** [comment]
This indeed seems to occur when the `digest` header is explicitly set as part of the signed headers, but the actual header isn't provided in the query.
