### ISSUE TITLE
When adding an image, I get "500 Internal Server Error"

### ISSUE THREAD

**Issue by LexPendragon** [tootsuite/mastodon#15830]
I have been running v3.3.0 in Docker on my own OpenSUSE linux server, and when I try to add a picture to a toot I get an error 500 Internal Server Error.  I have searched and checked permissions, but still can't seem to find any fix for this.

In the server logs itself, I see this:
[edited slightly for readability]

`[e0a63204-b844-424c-8d81-f8ebf4f89012] [paperclip] Trying to link /tmp/f9fbb000782df3a697e52fea33ebfd3a20210303-11-jen7ey to /tmp/c046e50d585b573a8c5c6a12bd3c6b4820210303-11-h216ej
[e0a63204-b844-424c-8d81-f8ebf4f89012] [paperclip] Trying to link /tmp/78805a221a988e79ef3f42d7c5bfd41820210303-11-6wrijx.png to /tmp/be0cad2d030eb466a94ac3f177fba5cd20210303-11-l1p46v.png
[e0a63204-b844-424c-8d81-f8ebf4f89012] Command :: file -b --mime '/tmp/be0cad2d030eb466a94ac3f177fba5cd20210303-11-l1p46v.png'
[e0a63204-b844-424c-8d81-f8ebf4f89012] method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=500 error='Errno::EACCES: Permission denied @ dir_s_mkdir - /opt/mastodon/public/system/media_attachments/files/105' duration=459.89 view=0.00 db=43.00
[e0a63204-b844-424c-8d81-f8ebf4f89012]   
[e0a63204-b844-424c-8d81-f8ebf4f89012] Errno::EACCES (Permission denied @ dir_s_mkdir - /opt/mastodon/public/system/media_attachments/files/105): 
[e0a63204-b844-424c-8d81-f8ebf4f89012]   
[e0a63204-b844-424c-8d81-f8ebf4f89012] lib/paperclip/attachment_extensions.rb:51:in 'block in save' 
[e0a63204-b844-424c-8d81-f8ebf4f89012] lib/paperclip/attachment_extensions.rb:57:in 'save' 
[e0a63204-b844-424c-8d81-f8ebf4f89012] app/controllers/api/v2/media_controller.rb:5:in 'create' 
`

The specific folder reference had these permissions:
` sudo docker-compose run --rm web ls -al /opt/mastodon/public/system/media_attachments/files/
Starting mastodon_redis_1 ... done
Starting mastodon_db_1    ... done
total 0
drwxr-xr-x 2 root root  6 Mar  3 16:43 .
drwxr-xr-x 4 root root 36 Mar  3 16:43 ..
`

Any other ideas of what I can do to correct this?

**Comment by LexPendragon** [comment]
In case anyone comes across this later, I fixed it by running:
sudo docker-compose run --user=root --rm web chown -R mastodon /opt/mastodon/public/

(Sorry to waste a post, I was out of ideas until I started running those commands to get the logs to show here.)

**Comment by tuatoru** [comment]
when i try this i get a "Can't find suitable configuration file in this director or any parent. Supported file names: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml"

any suggestions?

**Comment by gabrix73** [comment]
I have a mastodon instance ruuning where i can post text and emoji but no media at all (audio, images, video) . I'm on ubuntu22lts server and nginx.
