### ISSUE TITLE
Account migration to/from our instance is broken: existing users "could not be found"

### ISSUE THREAD

**Issue by quimgil** [tootsuite/mastodon#15848]
### Expected behaviour

External users can migrate to our instance. Our users can migrate to other instances.

### Actual behaviour

We have several users who have tried to migrate to our instance, but they cannot find the account to migrate to even if it is created and enabled.

And the same happens to accounts in our instance willing to migrate somewhere else: they cannot see their old account in our instance from the destination instance.

The error message when introducing the account to Create Alias is: 

`could not be found`

even when the account does exist and is active.

Can it be something related with the fact that we are using a subdomain?  https://red.confederac.io

### Steps to reproduce the problem

1. Create an account in https://red.confederac.io (registration is invitation only; we are happy accepting test accounts.
2. Follow the standard steps to migrate to/from our instance to another account.

### Specifications

v3.3.0

**Comment by LETRA** [comment]
https://red.confederac.io

**Comment by quimgil** [comment]
(Thank you, I fixed the URL)

**Comment by ClearlyClaire** [comment]
Your instance is misconfigured, and accounts such as `@confederada@confederac.io` cannot be resolved, since `confederac.io` does not provide the correct endpoints.

`https://confederac.io/.well-known/webfinger` should redirect to or proxy `https://red.confederac.io/.well-known/webfinger`, as explained here: https://github.com/tootsuite/documentation/blob/8a60228deb726dd9915a89785500f095faeb4cf3/content/en/admin/config.md#web_domain

**Comment by LETRA** [comment]
So do I have to do this?:

```
Configuring domain.org

Now, you have Mastodon running at https://social.example.org as well as a website at https://example.org. If you recall how webfinger queries work, the first step is to query https://example.org/.well-known/host-meta, which will contain an URL template.

Therefore, the easiest way to configure domain.org is to redirect /.well-known/host-meta to social.example.org.

With nginx, it would be as simple as adding:

location = /.well-known/host-meta {
       return 301 https://social.example.org$request_uri;
}
in example.org's server block.
```

https://github.com/felx/mastodon-documentation/blob/master/Running-Mastodon/Serving_a_different_domain.md

**Comment by ClearlyClaire** [comment]
Yes.

**Comment by quimgil** [comment]
Thank you @ClearlyClaire . After following your instructions, the problem is solved.
