### ISSUE TITLE
Morty Proxy error

### ISSUE THREAD

**Issue by Happyfeet01** [tootsuite/mastodon#15866]
Hello,

On my Instance https://fulda.social I got an Morty Proxy Error. ![Screenshot_20210309_090240_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/3295104/110446523-91504d80-80bf-11eb-9a45-1b11a1aba0fa.jpg)

But only when I visit the site with an ipv6 Adress. With ipv4 it's okay and working fine.

How can I solve this error?

I setup my server with Webmin/Virtualmin on an Debian 10 Machine.

**Comment by Happyfeet01** [comment]
Has anyone an idea? I use the Apache2 example from the docs.

**Comment by 12aw** [comment]
Hi @Happyfeet01 , could you solve this problem? I have the same now and don't know why. Even when I stop morty it appears :/
