### ISSUE TITLE
Allow users to disable unread notification markers.

### ISSUE THREAD

**Issue by Kansattica** [tootsuite/mastodon#15861]
### Pitch

A recent update to Mastodon has added unread markers to individual notifications that have to be cleared by clicking a "mark all notifications as read" button or by clicking on each one. Myself and a number of other folks find this new behavior annoying and would appreciate an option to go back to the old behavior.

### Motivation

I have a decent idea of how far back I have to scroll in the notification column before I'm caught up, and I find the unread marking distracting.

**Comment by ClearlyClaire** [comment]
Duplicate of #15133, addressed by #15842 (not currently merged).
