### ISSUE TITLE
 ActiveRecord::StatementInvalid PG::InternalError: ERROR:  missing chunk number

### ISSUE THREAD

**Issue by Happyfeet01** [tootsuite/mastodon#15909]
Hello,

i would migrate the mastodon instance to an new Server, but after rsync i can´t start Mastodon correctly. 

I get following issue.

`db_1         | STATEMENT:  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2
db_1         | FATAL:  role "postgres" does not exist
db_1         | FATAL:  role "postgres" does not exist
db_1         | ERROR:  missing chunk number 0 for toast value 189255 in pg_toast_2619
db_1         | STATEMENT:  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2
db_1         | FATAL:  role "postgres" does not exist`

`eb_1        | [3f08719e-df7f-4e01-8b6d-cbabd38e5d9f] method=GET path=/ format=html controller=HomeController action=index status=500 error='ActiveRecord::StatementInvalid: PG::InternalError: ERROR:  missing chunk number 0 for toast value 189255 in pg_toast_2619
web_1        | : SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2' duration=4.74 view=0.00 db=1.94
web_1        | [3f08719e-df7f-4e01-8b6d-cbabd38e5d9f]   
web_1        | [3f08719e-df7f-4e01-8b6d-cbabd38e5d9f] ActiveRecord::StatementInvalid (PG::InternalError: ERROR:  missing chunk number 0 for toast value 189255 in pg_toast_2619
web_1        | : SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2):
web_1        | [3f08719e-df7f-4e01-8b6d-cbabd38e5d9f]   
web_1        | [3f08719e-df7f-4e01-8b6d-cbabd38e5d9f] app/models/user.rb:199:in `active_for_authentication?'
web_1        | [3f08719e-df7f-4e01-8b6d-cbabd38e5d9f] app/controllers/concerns/localized.rb:11:in `set_locale'`

What can i do?

**Comment by Gargron** [comment]
This isn’t something we are equipped to help you with. Try postgres forums/IRC.
