### ISSUE TITLE
Sign up keeps suggesting 'Invalid email'

### ISSUE THREAD

**Issue by Catshavetakenover** [tootsuite/mastodon#1592]
![screenshot-bookwitty social 2017-04-12 07-32-45](https://cloud.githubusercontent.com/assets/27322162/24938028/4120cd12-1f52-11e7-9ffa-cd7afbeb3196.jpeg)

I tried putting in different emails but all of them suggested the same thing.

**Comment by mkody** [comment]
When that happened to me, it was because I've left `EMAIL_DOMAIN_WHITELIST` uncommented in my `.env.production`. Could you take a look at it?

**Comment by Gargron** [comment]
No response from OP, closing.
