### ISSUE TITLE
All `mimemagic` versions prior to `0.3.6` have been yanked

### ISSUE THREAD

**Issue by lunaisnotaboy** [tootsuite/mastodon#15950]
All `mimemagic` versions prior to `0.3.6` have been yanked. (More at https://github.com/rails/rails/issues/41750)

### Expected behaviour

`bundle install` should run as normal.

### Actual behaviour

```bash
mastodon@robert-U56E:~/live$ bundle install -j$(getconf _NPROCESSORS_ONLN)
Fetching gem metadata from https://rubygems.org/............
Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed
sources, that means the author of mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that
hasn't been removed in order to install.
```

### Steps to reproduce the problem

Just run `bundle install`.

### Specifications

Found in https://github.com/tootsuite/mastodon/commit/f8e50eaea351d743bf80e65c2178c4ed46d65881.

**Comment by acoolstraw** [comment]
I'm following the tutorial in https://docs.joinmastodon.org/admin/install/ and it doesn't work because of this

**Comment by acoolstraw** [comment]
```
~/live$ bundle install -j$(getconf _NPROCESSORS_ONLN)
Fetching gem metadata from https://rubygems.org/............
Your bundle is locked to mimemagic (0.3.5) from rubygems repository
https://rubygems.org/ or installed locally, but that version can no longer be
found in that source. That means the author of mimemagic (0.3.5) has removed it.
You'll need to update your bundle to a version other than mimemagic (0.3.5) that
hasn't been removed in order to install.
```

**Comment by acoolstraw** [comment]
I tried editing the Gemfile to update the version, the Gemfile.lock to update the version, I tried `bundle update mimemagic` which gave me `Unable to find a spec satisfying mimemagic (~> 0.3.0) in the set. Perhaps the
lockfile is corrupted?`
