### ISSUE TITLE
Setting a secure connection with email relayhost

### ISSUE THREAD

**Issue by lhp22** [tootsuite/mastodon#15956]
Hi there,

I'm totally lost for configuring the mail parameters of my new mastodon instance. I've a relayhost at `lhp22.yaeghs.net`, and my mastodon instance is at `masto.yaeghs.net`. They are on different servers.

I wish relay through secured connections (SMTPS or StartTLS with TLSv1.2 or TLSv1.3). But, it seems to me that the default 

```
SMTP_SERVER=lhp22.yaeghs.net
SMTP_PORT=587
SMTP_LOGIN=masto@lhp22.yaeghs.net
SMTP_PASSWORD=mypasswd
SMTP_FROM_ADDRESS='Mastodon <masto@lhp22.yaeghs.net>'
```

establishes a clear connection, not a secure one.

Which flags should I enable to set up a TLS connexion ?

Thanks,

**Comment by nightpool** [comment]
Mastodon supports STARTTLS by default with no additional configuration. if you want to force SMTPS, you can set the environment variable SMTP_TLS=true

**Comment by nightpool** [comment]
See https://github.com/tootsuite/mastodon/blob/master/config/environments/production.rb#L98 and https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration for more information
