### ISSUE TITLE
bundle install mimemagic (0.3.10) still throws error

### ISSUE THREAD

**Issue by mashirozx** [tootsuite/mastodon#15977]
### Expected behaviour
Install gems via `bundle install`

### Actual behaviour

```
An error occurred while installing mimemagic (0.3.10), and Bundler cannot continue.
```

![image](https://user-images.githubusercontent.com/16148054/112811496-b7f61880-90ae-11eb-89cf-1aa3c7e559fc.png)

### Specifications
I'm working on the latest commit 479d58242b488fb303eff20871fd6994205af36b

**Comment by mashirozx** [comment]
Rails has replaced mimemagic with mini_mime (<
https://github.com/rails/rails/commit/62ac25a3648c8d54c54107554347ea99a4766be2#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731f>), maybe we can also consider do this substitution, since recall of already released package is such an irresponsible behavior.

**Comment by Gargron** [comment]
mimemagic is still required by paperclip, which is no longer maintained (but which we are stuck with). I can see that mimemagic failed to compile in your screenshot but I do not see why. It could be related to it needing to find `freedesktop.org.xml` on your system.

See: https://github.com/mimemagicrb/mimemagic/blob/0.3/ext/mimemagic/Rakefile

**Comment by dakotahp** [comment]
I got around this easily on Mac by doing `brew install shared-mime-info` and it knew where to find the library.

On Linux or other systems they have good instructions: https://github.com/mimemagicrb/mimemagic#dependencies

**Comment by mashirozx** [comment]
Thanks, that helps  a lot. I think we should upgrade our Dockerfile. I'm testing it now.

**Comment by mashirozx** [comment]
![image](https://user-images.githubusercontent.com/16148054/112920990-993e6300-913c-11eb-807e-0dbeb0e48c30.png)
Yes, it's the reason @Gargron
