### ISSUE TITLE
Yikes. Error message with big red letters!

### ISSUE THREAD

**Issue by Roddio** [tootsuite/mastodon#15984]
On Safari only; Chrome is working fine.

Error Reads:
Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly.
Try refreshing the page. If that does not help, you may still be able to use Mastodon through a different browser or native app.

TypeError: this.mediaQuery.removeEventListener is not a function. (In 'this.mediaQuery.removeEventListener("change",this.handleLayoutChange)', 'this.mediaQuery.removeEventListener' is undefined)

Stacktrace:
https://static-cdn.mastodon.social/packs/js/application-e7af47991a7040c14bd3.chunk.js:1:65751
https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1041802
ls@https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1041823
gs@https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1043657
wu@https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1057141
wu@[native code]
https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1077654
_u@https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1055001
su@https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1051155
su@[native code]
https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1002596
https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1077654
Ya@https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1002542
Xa@https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1002477
cu@https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1051328
Yu@https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:1070202
https://static-cdn.mastodon.social/packs/js/application-e7af47991a7040c14bd3.chunk.js:1:95788
r@https://static-cdn.mastodon.social/packs/js/common-98c8c79ed4d860c80a40.js:2:188541
https://static-cdn.mastodon.social/packs/js/application-e7af47991a7040c14bd3.chunk.js:1:95679
https://static-cdn.mastodon.social/packs/js/application-e7af47991a7040c14bd3.chunk.js:1:13174
promiseReactionJob@[native code]

this.node.removeEventListener (webpack:///app/javascript/mastodon/features/ui/components/columns_area.js:128:42)
Di (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5068:60)
c (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5254:57)
h (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5398:15)
g (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6363:24)
wu ([native code]::)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
Jj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6204:5)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5895:7)
su ([native code]::)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2851:16)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2846:9)
gg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2836:2)
Nj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5933:22)
Nj(function (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:7180:4)
web($|\/)/).test (webpack:///app/javascript/mastodon/main.js:25:20)
complete'].includes (webpack:///app/javascript/mastodon/ready.js:3:4)
web($|\/)/).test (webpack:///app/javascript/mastodon/main.js:21:2)
default (webpack:///app/javascript/packs/application.js:8:30)
promiseReactionJob ([native code]::)

**Comment by Gargron** [comment]
And looks like this is why:

![grafik](https://user-images.githubusercontent.com/184731/113197074-8626b280-9264-11eb-8d4c-69150f39ba22.png)
