### ISSUE TITLE
Allow grabbing posts from RSS feed

### ISSUE THREAD

**Issue by LiamDawe** [tootsuite/mastodon#160]
Something that would be useful, is to allow an account to auto-grab posts from an RSS feed.

**Comment by inmysocks** [comment]
How would you want this to be different from getting posts using the API?

**Comment by LiamDawe** [comment]
Go into settings > add RSS link > Mastodon auto grabs them for you. No messing around with an API, have a built-in option for it.

**Comment by qwertygc** [comment]
Hi ! i don't find the option on my pod (framapiaf.org).

**Comment by LiamDawe** [comment]
It doesn't exist, it's a request.

**Comment by mjankowski** [comment]
Is the idea here for a user to be able to "follow" an RSS feed via the UI ... or for a user to configure an RSS feed which should be used as an auto-posting source of content (like, when something shows up in feed, the account automatically posts it...)?

**Comment by Fil** [comment]
Both would be cool but I think this issue is about using RSS "as an auto-posting source of content". Currently one has to configure a server, set up a bot, etc. It's not user-friendly and not environmentally friendly.

**Comment by LiamDawe** [comment]
I am asking for a setting to pick an RSS feed to have our account populated from it. It's extremely useful for any kind of news site.

**Comment by Gargron** [comment]
I would prefer Mastodon to stay slim. This would require having an instance periodically poll such feeds for all users who have them configured, which might not scale very well. On the other hand, if you just use the API to do this, you push an update when you know you have it.
