### ISSUE TITLE
post from somebody not followed shows up at first column

### ISSUE THREAD

**Issue by azbulutlu** [tootsuite/mastodon#1601]
Strange bug.
https://mastodon.cloud/@eileenb/451324
this post showed up, on my timeline at mastodon.social. I don't follow the OP, no indication of a boost either visually on the timeline or at the item. It happened both on web and on tusky, so I assume it is not a temporary hiccup.

**Comment by laanwj** [comment]
Might be a timing issue; I accidentally boosted that post instead of clicking reply then un-boosted it immediately.

**Comment by azbulutlu** [comment]
commenting to add the context that I do follow @laanwj :)

**Comment by laanwj** [comment]
Hahaha yes, that's an essential part of the picture

**Comment by dstaley** [comment]
I've experienced the same issue with another tweet, displayed without the boost marker in both Tusky and on mastodon.social. Would the API have the boost info?

**Comment by nicofrand** [comment]
Same thing here : post from "Monsieur Zun" which I do not follow.

![mastodon-bug](https://cloud.githubusercontent.com/assets/3419050/25043857/61e2152e-2123-11e7-9400-c009512aaf0a.png)

**Comment by nhoizey** [comment]
Same issue here:
https://mastodon.social/@nhoizey/3248792

**Comment by Cassolotl** [comment]
If this was a boost that got unboosted, that means it's issue #770, I think!

**Comment by unarist** [comment]
Closing as duplicate, see Gargron's comment on #2817.
