### ISSUE TITLE
.charity gTLD isn't supported in profiles.

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#16015]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/17537000/114326214-4ade8a80-9b66-11eb-9ec2-51a03eddb018.png">

### Expected behaviour

.charity domain should turn into a hyperlink

### Actual behaviour

the link is shown as raw text

### Steps to reproduce the problem

Add `https://generozity.charity` to the profile

### Specifications

latest stable. 3.3.0

**Comment by ClearlyClaire** [comment]
Fixed in #15382

**Comment by shleeable** [comment]
Thsnks @ClearlyClaire
