### ISSUE TITLE
require explicit opt-out of caption when posting images and videos

### ISSUE THREAD

**Issue by Be-ing** [tootsuite/mastodon#16039]
### Pitch

Captioning images and videos is required to let users who use screenreaders understand and participate in discussions. Relatively few users caption images they post or do it inconsistently. I think if Mastodon changed the UX design to encourage captioning, far more images would get posted with captions. Currently, it's not even clear that Mastodon can caption images. To enter a caption, the user has to click a button that says "Edit" on the preview thumbnail after uploading an attachment. A simple way to change this would be to automatically show the "Edit" modal dialog when the image or video is uploaded. That would require the user to explicitly opt out of posting a caption.

### Motivation

Fediverse users (including those not using Mastodon) who use screen readers would be able to participate in social interactions more fully.

**Comment by Be-ing** [comment]
I suggest to show the Edit modal dialog when the upload starts and move the uploading progress bar into the Edit dialog.

**Comment by tfardet** [comment]
See related discussions with specific proposals:

- #5644
- #13894 (notably [this comment](https://github.com/tootsuite/mastodon/issues/13894#issuecomment-640737181))

And a PR #https://github.com/tootsuite/mastodon/pull/15590

**Comment by Be-ing** [comment]
Thanks. I'll close this because it is a duplicate of #5644.
