### ISSUE TITLE
ScheduledStatusesScheduler doesn't work or is unreliable

### ISSUE THREAD

**Issue by joenepraat** [tootsuite/mastodon#16056]
### Expected behaviour

Toots can be scheduled using the official Mastodon API. Apps like Tusky support this. In Sidekiq there's a recurring job called _Scheduler::ScheduledStatusesScheduler_ with a 5 minute interval, using the _scheduled_ queue.

### Actual behaviour

Toots are scheduled in the database and the _Scheduler::ScheduledStatusesScheduler_ is running every 5 minutes. Like below log entry shows:

`
Apr 15 00:29:32 vmi416776 bundle[23006]: 2021-04-14T22:29:32.626Z pid=23006 tid=3o6u INFO: queueing Scheduler::ScheduledStatusesScheduler (scheduled_statuses_scheduler)
`

Unfortunately two of the three of my servers are not posting the scheduled toots. They are listed in the database, but they are not picked up by the ScheduledStatusesScheduler.

The third server is unreliable. That one first worked, stopped working without any known reason, and a few days later somehow started working again without any known reason.

The _scheduled_ queue is present on all servers. And in Sidekiq all scheduled jobs are running like they should. In the logs I can't find any errors about failing scheduled toots. So it's a big mystery, but I hope someone can point me to the right direction how to debug this or better how to fix this.

### Steps to reproduce the problem

Schedule a toot in Tusky or any other API compatible app.

### Specifications

Mastodon v3.3.0
Debian 10.9
Ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

(all specifications are the same for all three servers)

**Comment by Gargron** [comment]
Recurring jobs had intermittent issues relating to unique locks for a while. In 3.3.0, a special `scheduler` queue was added, but we were still using the locking mechanism, even though it is not required when there is only one process handling recurring jobs. In main, there are no locks on recurring jobs anymore which should alleviate this problem.

**Comment by joenepraat** [comment]
@Gargron So you say that this is a known issue and is solved in master? Is there any workaround for this issue until the new stable version is released?

**Comment by Gargron** [comment]
Deleting all locks in the sidekiq UI should help

**Comment by joenepraat** [comment]
I see no locks in my Sidekiq UI. I will wait for the new version.
