### ISSUE TITLE
migrating files to diff server ... why 2 times same files?

### ISSUE THREAD

**Issue by r3k2** [tootsuite/mastodon#16083]
Hello doing a migration and moving everything inside "live/public/system/*" and there are a cache folder with what it seems exactly the same information than the root of system/* ?

```
~/live/public/system$ ls -alh
total 24K
drwxr-xr-x  6 mastodon mastodon 4.0K Apr 17 21:54 .
drwxrwxr-x 12 mastodon mastodon 4.0K Apr 17 22:21 ..
drwxr-xr-x  4 mastodon mastodon 4.0K Nov 16  2017 accounts
drwxr-xr-x  6 mastodon mastodon 4.0K Jul  3  2020 cache
drwxr-xr-x  3 mastodon mastodon 4.0K Nov 18  2017 custom_emojis
drwxr-xr-x  4 mastodon mastodon 4.0K Dec  1 16:24 media_attachments
```

and then:

```
/home/mastodon/live/public/system/cache
:~/live/public/system/cache$ ls -alh
total 24K
drwxr-xr-x 6 mastodon mastodon 4.0K Jul  3  2020 .
drwxr-xr-x 6 mastodon mastodon 4.0K Apr 17 21:54 ..
drwxr-xr-x 4 mastodon mastodon 4.0K Jul  3  2020 accounts
drwxr-xr-x 3 mastodon mastodon 4.0K Jul  3  2020 custom_emojis
drwxr-xr-x 3 mastodon mastodon 4.0K Jul  3  2020 media_attachments
drwxr-xr-x 3 mastodon mastodon 4.0K Jul  3  2020 preview_cards
```

since I have this mastodon server since when mastodon was beta way at the start I wonder if this is something old mixed with new or something.. between both is like 300G of info, we have not that many users... and everything I see is repetetive folder file names...

of course rsync is taking FOR EVER like 3 days already... so wondering if I am double copying things that we do not need any more.

thanks

**Comment by Gargron** [comment]
Hi, they have the same folder structure but different files. Cache contains files for remote resources (avatars from other servers etc), while not cache is local stuff.

**Comment by r3k2** [comment]
@Gargron Thanks for clearing that up, is odd I runned the toot control cli tool to remove all cache external files.. why are they still so many?  my second question will be. for the sake of migration speed, can I just not copy those "external" files? thanks

**Comment by Gargron** [comment]
You can skip them but some of the cached files have no refetch mechanism. So it depends on how OK you are with some remote content having broken images. `tootctl media remove` removes only post attachments, there is no mechanism for cleaning out avatars/headers/emojis.

**Comment by r3k2** [comment]
Thanks! this cleared a lot of things for me. I appreciate it
