### ISSUE TITLE
Excessive line spacing in posts due to extra paragraph marks between <p> tags

### ISSUE THREAD

**Issue by tomfhowe** [tootsuite/mastodon#1609]
Example: https://mastodon.social/users/Rushyo/updates/1800557 
Posts seem from instances on the latest version seem to be putting an extra paragraph mark in the post text between < p > tags, resulting in excessively large line spacing in most browsers. To clarify, it looks like this is happening: 
< p > paragraph 1 </ p > 

< p > paragraph 2 </ p > 

When really this should happen: 
< p > paragraph 1 </ p >
< p > paragraph 2 </ p >

See the following screenshot:
![screen shot 2017-04-12 at 10 31 56 am](https://cloud.githubusercontent.com/assets/19882099/24963047/86ca8ef2-1f6b-11e7-9329-1e5843257cb6.png)

I might also suggest lowering the margin-bottom for paragraphs in posts to 10px, but that's just my opinion. I don't know enough about how the posts are made or saved to fix this myself, unfortunately. 

* * * *

- [✅ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
Possibly related to: https://github.com/tootsuite/mastodon/blob/8ead070b940ce8d4bf2c93af99b3487129d578e2/app/assets/stylesheets/components.scss#L274

**Comment by tomfhowe** [comment]
@mjankowski Oh yeah, definitely! I didn't know about that.

**Comment by mjankowski** [comment]
I still see the issue on the above-linked status (https://mastodon.social/users/Rushyo/updates/1800557)

I think for content like this...

```text
This is a post.


With some whitespace.
```

The `white-space: pre-wrap;` makes sense and we want it ... but then with multiple `<p>` we don't want to preserve whatever space winds up between the tags.

I bet moving that rule to be on the `<p>` itself, rather than surrounding div, might fix...

**Comment by tomfhowe** [comment]
@mjankowski I see it in the post in the interface you get when you view it like that with a direct link, but in the actual web interface I don't see it anymore.
