### ISSUE TITLE
CDN domain host was blocked by Rails

### ISSUE THREAD

**Issue by mashirozx** [tootsuite/mastodon#16125]
### Expected behaviour
Load js and css files from a CDN domain

### Actual behaviour
![image](https://user-images.githubusercontent.com/16148054/116209447-825b5280-a774-11eb-8685-2efe5f594840.png)

### Steps to reproduce the problem
Setting `CDN_HOST` in `.evn.production`

**Comment by ClearlyClaire** [comment]
Looks like this would come from #16087 and #16095 but… in which circumstance would JS and CSS files go through Rails…?

**Comment by mashirozx** [comment]
well, I'm on the latest commit, and I mean this:
![Screenshot_2021-04-28-07-53-57-829_com android chrome](https://user-images.githubusercontent.com/16148054/116326428-035b2e00-a7f7-11eb-86d2-d20ef2d5fbbf.jpg)

**Comment by mashirozx** [comment]
I'm not sure why it goes through rails, maybe because I'm using a Docker stack?

**Comment by mashirozx** [comment]
The problem is the site's style was broken, and I see cors errors in console (403). Basically, I just set the CDN domain in the same tttp block in nginx  (as another server_name)

**Comment by nightpool** [comment]
The whole point of the CDN_HOST variable is that site styles are served by *another* server, like S3 or Minio. If you're serving assets through rails, unset the CDN_HOST variable.

**Comment by mashirozx** [comment]
@nightpool As the word CDN means, a CDN doesn't mean how we serve our assets but how we deliver our assets. We can store the source file in local server, but they will be delivered to users using different network from the site's main domain. For example, with Cloudflare, the assets will be delivered by their network, but the source file is till stored in our server. 

Here are `S3_ALIAS_HOST` and `CDN_HOST` options in config file, they are different.

Yes, with installation from source, the assets is reachable by Nginx etc. ,but with Docker installation, seems it's necessary to goes through Rails, since it is not really necessary to mount the public folder into the host machine.

**Comment by ClearlyClaire** [comment]
> Basically, I just set the CDN domain in the same http block in nginx (as another server_name)

Can I have a look at this `server` block?

I'm not sure we should allow `CDN_HOST` as Rails serving assets is *far* from an ideal setup, but also, I'm not sure a Mastodon update should break those setups…
