### ISSUE TITLE
Insert non-breaking space before some punctuation

### ISSUE THREAD

**Issue by Paulloz** [tootsuite/mastodon#1613]
Hi there!  
In some languages (e.g. French) people are typing a space before some punctuation marks (`:`, `;`, `!`, `?`). Those spaces should be replaced by `&nbsp;` to avoid ugly line breaks like here :
![capture](https://cloud.githubusercontent.com/assets/437025/24965788/6401dc74-1fa5-11e7-8488-2d411d8f8c26.JPG)  
It should also be done for spaces after `«` and before `»`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by gordonzola** [comment]
I really don’t think that’s a job for the platform: people can make errors, typos, and the platform let them publish what they intended to publish.

Also, inserting non-breaking spaces before double punctuation marks is typically a french typographic rule. It should really not be integrated in the software as a general rule

**Comment by wxcafe** [comment]
Imo this shouldn't be managed by the platform, yeah. I'm marking it as invalid and closing
