### ISSUE TITLE
Search for favorites

### ISSUE THREAD

**Issue by clarkenciel** [tootsuite/mastodon#1618]
It would be nice for useres to be able to search through their own favorites since they're a bit of an archive. Perhaps just a search/filter bar at the top of the panel?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by remram44** [comment]
In addition to that, and since it requires the "option" icon anyway, it would be good to be able to pin the list of favorites in the interface.

**Comment by Gargron** [comment]
Implemented in #6423
