### ISSUE TITLE
Settings page needs an obvious link back to the main site

### ISSUE THREAD

**Issue by LiamDawe** [tootsuite/mastodon#162]
It may be obvious to people who use it a lot with the logo being a link, but a standard "Back to Mastodon" link would be good too.

Keep it accessible to as many people as possible.

**Comment by Gargron** [comment]
Click on the big round logo

**Comment by LiamDawe** [comment]
Re-read what I said, this isn't about there being one, but a question of accessibility. A simple link back to the homepage which make things more visible, right now it's hidden.
