### ISSUE TITLE
Invalid references when a server erases data

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#1621]
In case of server-A reset all data ,then relayed server-B has invalid references (subscriptions, accounts), but seems it's not corrected automatically.
Is there a way to correct it from server-B or server-A ?

**Comment by wxcafe** [comment]
I believe this is fixed automatically after the PubSubHubbub subscriptions expire (after 7d)

**Comment by tateisu** [comment]
7 days have passed. seems it was resolved automatically.
