### ISSUE TITLE
[3.4.0] docker health check failing on localhost

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#16251]
### Expected behaviour
docker-compose ps should show all healthy containers.

### Actual behaviour
![image](https://user-images.githubusercontent.com/17537000/118428269-aa99f980-b701-11eb-8ef9-c2553a1799e1.png)

### Steps to reproduce the problem

`curl localhost:3000/health`

![image](https://user-images.githubusercontent.com/17537000/118428308-be456000-b701-11eb-9337-b7adeafe74a1.png)

### Specifications

3.4.0 stable

**Comment by tribela** [comment]
That's weird.. that should be fixed in #16243

**Comment by ClearlyClaire** [comment]
There's a typo in that PR, it should be `host_authorization` and not `hosts_authorization`.

**Comment by shleeable** [comment]
Thanks.

**Comment by ericlathrop** [comment]
Can someone push this as 3.4.1? I couldn't get the `3.4.0` docker image to work. Every request was failing with a 403 forbidden. The `edge` image works.

**Comment by exstral** [comment]
Yeah a release would be nice, I just spent like three hours debugging this and was about to create an issue then found this. Learned some things about ruby on rails at least.
