### ISSUE TITLE
Not receiving an email confirmation

### ISSUE THREAD

**Issue by docpop** [tootsuite/mastodon#1626]
I created an account at https://mastodon.network/ and was told that a confirmation email would be sent. I was then taken to the sign in page.

It's been an hour and no email has been received, so I clicked the "Didn't receive email notifications?" link on the sign on page and re-entered my email. Still nothing.

I've confirmed that my email and username have been registered (by attempting to re-register and getting an error message that both were taken), but can't find a way to get that confirmation email. 

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by a2** [comment]
It's possible that this is an issue with your email provider. I've heard from some people that newer TLDs aren't recognized by some email providers.

**Comment by docpop** [comment]
That's possible. I'm using my gmail account though, which I'm assuming wouldn't provide any issues. I also check the spam folder pretty regularly, and haven't seen it there.

**Comment by a2** [comment]
Ah okay. I know someone who was using a `.technology` TLD and FastMail was rejecting the emails. (Except it worked for me on FastMail so your mileage may vary 😅)

**Comment by Fritillaria** [comment]
I'm having the same problem registering for darksocial.party. This is frustrating. I'm searching through gmail to see if any emails are being turned away, but so far no luck, and I've tried confirming probably 30 times so far. I honestly don't know what to do next.

**Comment by rascallyjen** [comment]
I have the same problem using gmail. I set up my account using this name(rascallyjen) using the same network https://mastodon.network/

**Comment by Fritillaria** [comment]
I had no problem with setting up my .network account with my gmail, but definitely with darksocial.party yesterday. I can even see my new profile, followed my new profile, but I still can't get confirmation in order to log in.

**Comment by rascallyjen** [comment]
I set up today and no confirmation. I got it to resend and still no
confirmation.

**Comment by kyzh** [comment]
@docpop @rascallyjen @Fritillaria  there was an SMTP change in mastodon 1.1.1
Maybe get in touch with the instance owner and ask if they see any email going out.
The fix is in this PR #1563

**Comment by wxcafe** [comment]
This is not related to mastodon-the-software and you should contact the admin of that specific instance. Closing
