### ISSUE TITLE
reply button highlights some of the @users by mistake

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#16274]
### Expected behaviour

Click reply, type reply, hit send.

### Actual behaviour

<img width="627" alt="image" src="https://user-images.githubusercontent.com/17537000/118587994-21052d00-b7d0-11eb-93b2-57f13c4abbcd.png">

### Steps to reproduce the problem

Find a thread with multiple people in it. hit reply and type.. it might delete one or two of the @users because the text was highlighted.

Above screenshot turns to this.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/17537000/118588124-6590c880-b7d0-11eb-8c0a-b2587e29a9cc.png">

### Specifications

v3.4.0

**Comment by shleeable** [comment]
can confirm this highlights multiple @users on reply. 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/17537000/118589153-69bde580-b7d2-11eb-9fc9-cba6f5139eda.png">

**Comment by ClearlyClaire** [comment]
It's by design, to be able to easily drop mentions to everyone but the person you actually reply to.

**Comment by shleeable** [comment]
I mean... sure?

In a multiperson thread, how often would you want to reply to everybody vs one person in that thread?

Have you done any tests on this? How often are people replying to a single person in threads?

![image](https://user-images.githubusercontent.com/17537000/118631392-064bac00-b802-11eb-8b02-47ef0df6101b.png)

**Comment by ClearlyClaire** [comment]
eh, I use it sometimes to drop mentions, sometimes to put the other mentions on a new line when mainly addressing someone.

Don't know if there's been any testing, but that behavior has been here since January 2017, it's nothing new.

**Comment by shleeable** [comment]
Cool. I'm going to say, this seems like an anti-pattern that's weird for no reason.

If it's on purpose... shrugs?

**Comment by Gargron** [comment]
> This seems like an anti-pattern that's weird for no reason.
> 
> If it's on purpose... it is what it is. Add it to the "Mastodon UX" pile.

This behavior was adopted from TweetBot in #401, but I remember it from Tweetdeck as well as the original Twitter app before they butchered mentions. So it is very standard social media UX.

**Comment by shleeable** [comment]
> > This seems like an anti-pattern that's weird for no reason.
> > If it's on purpose... it is what it is. Add it to the "Mastodon UX" pile.
> 
> This behavior was adopted from TweetBot in #401, but I remember it from Tweetdeck as well as the original Twitter app before they butchered mentions. So it is very standard social media UX.

Thanks for the details.
