### ISSUE TITLE
Regression in newlines on profile page

### ISSUE THREAD

**Issue by nightpool** [tootsuite/mastodon#1628]
This is a regression caused by #1397 

The toot displays fine in the web UI:
![image](https://cloud.githubusercontent.com/assets/233815/24973216/0130a90e-1f8c-11e7-8795-68561c3f8e4c.png)

but on the permalink page, it displays with way too many newlines:

![image](https://cloud.githubusercontent.com/assets/233815/24973243/142bcd90-1f8c-11e7-8f63-08118eb904f0.png)

I think the correct move here is to remove the `whitespace: prewrap` in the CSS for statuses.

(Also, I've seen lots of users complaining about this, because they're on instances that don't remove the newline in the web UI—did we know this was a breaking change when we merged it?)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
Probably resolved by https://github.com/tootsuite/mastodon/pull/1630

**Comment by nightpool** [comment]
@mjankowski see also:

Toot:
```
test
test

test
```

in the web ui:
![image](https://cloud.githubusercontent.com/assets/233815/24973671/a134490a-1f8d-11e7-9dd9-768c75d86b7d.png)

on the profile page:
![image](https://cloud.githubusercontent.com/assets/233815/24973679/a62454e6-1f8d-11e7-8c94-5fe775710c91.png)
