### ISSUE TITLE
Allow HTML in 'Server rules'.

### ISSUE THREAD

**Issue by ryliejamesthomas** [tootsuite/mastodon#16292]
I'm trying out the new 'Server rules' feature and it seems like a good addition.

It'd be nice to be able to use some HTML in there, like we can with other parts of the about/more page. I'm missing being able to italicise, bold, and make hyperlinks.

**Comment by Gargron** [comment]
Sorry, but that's a definitive no. The reason for adding the server rules API is for easy reading and easy displaying across apps and websites, in contrast with "extended site description" which is HTML and contains a lot of extra stuff that is difficult to render.

**Comment by ryliejamesthomas** [comment]
Fair enough.
