### ISSUE TITLE
Fix W3C Validator warnings

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#16316]
### Pitch

Mastodon is not producing valid HTML output according to the W3C Validator service.

### Motivation

Producing valid HTML output is important for browsers so Mastodon looks and feels great in every browser.

### References

https://validator.w3.org/nu/?doc=https%3A%2F%2Fmastodon.online
https://validator.w3.org/nu/?doc=https%3A%2F%2Fmastodon.online%2F%40koyu

**Comment by nightpool** [comment]
Please open up individual issues for specific validation errors that you think are important, with a specific motivation for each one (making sure to establish the user impact of the error, rather then just "the validator says this")
