### ISSUE TITLE
Link verification isn't working

### ISSUE THREAD

**Issue by codinghedgehog-python** [tootsuite/mastodon#16322]
I've got React app up and running and in the navbar I've got social links. One of them is Mastodon.
after adding the attribute `rel="me"` link verification isn't showing up in the profile.

I've read in some threads that some people fixed it by removing the attribute, restarting the server and then adding the
attribute back in the tag.
Didn't help in my case.

Expected behavior:  green checkmark indicating website link ownership
Reality:  No green checkmark despite using the "me" attribute

Steps to reproduce:
I suppose what might be a factor is that it's a SPA (javascript-based app)

**Comment by ClearlyClaire** [comment]
The link back to your Mastodon profile has to be directly in HTML within the linked page, and that page has to be 1MB or less.

**Comment by codinghedgehog-python** [comment]
> The link back to your Mastodon profile has to be directly in HTML within the linked page, and that page has to be 1MB or less.

Yeah that must be it then. The navbar is being injected into DOM as a component. It's not a pure HTML.

**Comment by Gargron** [comment]
You can use `<link rel="me" href="..." />` in the page header, it doesn't have to be a rendered link. I'm not sure we could afford to execute JS in the crawler to get the final rendered DOM from React apps and so on.

**Comment by codinghedgehog-python** [comment]
> You can use `<link rel="me" href="..." />` in the page header, it doesn't have to be a rendered link. I'm not sure we could afford to execute JS in the crawler to get the final rendered DOM from React apps and so on.

I've added it to the header section and will see. I know it can take some time for it to kick in. Will report back. Thank you.

**Comment by codinghedgehog-python** [comment]
@Gargron  So far the verification hasn't kicked in. I've got this `<link rel="me" href="https://mastodon.online/@myprofile"/>` in the header of the page which I assume is correct. How often the crawler is active ?

**Comment by ClearlyClaire** [comment]
It only gets triggered when the bio field changes. Try removing the bio field and adding it back.

**Comment by codinghedgehog-python** [comment]
> It only gets triggered when the bio field changes. Try removing the bio field and adding it back.

It worked ! Thanks for that. I'm closing this now. I can now cross off "learn something new today" from my list. Cheers.

**Comment by eobet** [comment]
> It only gets triggered when the bio field changes. Try removing the bio field and adding it back.

The official documentation omits this (https://docs.joinmastodon.org/user/profile/) and it caused me quite some headache until I deliberately searched for closed issues and found this one!

It should really be mentioned on that page as well in order to avoid confusion and frustration from other users...
