### ISSUE TITLE
How to get OpenAPI spec (JSON or YAML)

### ISSUE THREAD

**Issue by QuanQuanoooooo** [tootsuite/mastodon#16328]
API specification is important for testing RESTful APIs. I could only find the description on the official website[https://docs.joinmastodon.org/api/] without related swagger or OpenAPI JSON/ YAML file to download. How could I get it? Thank you very much!

**Comment by nightpool** [comment]
We do not currently have an OpenAPI spec, and we're not currently interested in creating one.
