### ISSUE TITLE
Wrong percentage sum on a poll

### ISSUE THREAD

**Issue by filippodb** [tootsuite/mastodon#16355]
we had wrong % on a poll here: https://mastodon.uno/@informapirata/106335941817082595

### Expected behaviour

percentage sum should be 100% 

### Actual behaviour

150%

### Steps to reproduce the problem

create a poll with 3 options and 4 votes.

### Specifications

3.4

![image](https://user-images.githubusercontent.com/7091176/120665397-05667b80-c48c-11eb-887f-d8fcb4f8340e.png)

**Comment by connyduck** [comment]
Not a bug.
That is a multiple choice poll, one user can vote for multiple options, so sum > 100% is fine.

**Comment by hugogameiro** [comment]
I think that in multiple choice questions the basis of the calculation should be the number of votes and not the number of people voting. 

If you have a multiple choice poll with two choices and one single person votes, each option should return 50% and not both 100%.

**Comment by hugogameiro** [comment]
Well, it looks like probably this is not a bug and there was a debate around this exact topic here: https://mastodon.social/@Gargron/103597321980399625 

I still think that using the number of votes as the basis for a multiple choice poll makes more sense but I see that a lot of people disagree with that :)

**Comment by filippodb** [comment]
Actually some users are making fun of mastodon for having a 150% sum on a poll so I don't think it's a really good idea to keep it this way.

Also the user didn't even know it was a multiple choice poll because on browser it's like "changing circles into squares" and you have a multiple choice without any warning, it's pretty confusing.

![image](https://user-images.githubusercontent.com/7091176/120749000-0a671180-c504-11eb-91f9-970a9d925d01.png)
![image](https://user-images.githubusercontent.com/7091176/120749014-14891000-c504-11eb-809e-f4358b22f7f9.png)

**Comment by ClearlyClaire** [comment]
Not a bug. Options in multiple-choice polls are not exclusive, so it makes sense for them to be displayed as a percentage of voters.
For instance, if you were to ask people which day of the week they would prefer for an event, and everybody agrees on 3 out of the 4 days, it makes sense for those options to be 100% rather than 33% or less.

It is true that the distinction between multiple-choice and single-choice polls is not obvious, though, but that is another issue.

**Comment by hugogameiro** [comment]
Damn, you just change my mind. I didn't think this through, it does make sense.
