### ISSUE TITLE
Wrong language for succes modal

### ISSUE THREAD

**Issue by SansPseudoFix** [tootsuite/mastodon#1636]
Step to reproduce:
* set a language in settings (let's say deutsch here)
* change language in your settings (french)
* save

Success modal uses deutsch:

![wrong_language_succes_modal](https://cloud.githubusercontent.com/assets/6507951/24973843/8bcf3cc2-1fc0-11e7-8841-f9364f9effe8.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by yookoala** [comment]
Probably a duplicate for #1558

**Comment by unarist** [comment]
This should be fixed on #3232.
