### ISSUE TITLE
Update not happening 3.4.0 to 3.4.1

### ISSUE THREAD

**Issue by kdmiller45** [tootsuite/mastodon#16361]
I attempted to upgrade from 3.4.0 to 3.4.1 this morning  and performed the following

Non-Docker only:  Install dependencies: **bundle install** and **yarn install** and then
Non-Docker: RAILS_ENV=production bundle exec rails db:migrate
Non-Docker: RAILS_ENV=production bundle exec rails assets:precompile
Restart all Mastodon processes
and even restarted sever and it still shows me at 3.4.0

Ubuntu server 18.04
Mastodon ver: 3.4.0
site: https://topic-master.com

Keith

**Comment by ClearlyClaire** [comment]
This may sound stupid, but did you `git fetch && git checkout v3.4.1` before doing that?

https://docs.joinmastodon.org/admin/upgrading/

**Comment by kdmiller45** [comment]
Well that was not a stupid question I had not, might be good idea to include that in the update instructions and when I performed this command it kicked out the error
![image](https://user-images.githubusercontent.com/19610991/120902304-745ee400-c5f4-11eb-8c7a-a4435f1b5c50.png)

**Comment by ClearlyClaire** [comment]
I can't see where you've seen the instructions to run `systemctl enable mastodon-*`. I am not sure what other commands you did run, but basically, the whole thing should be something like:

```shell
git fetch
git checkout v3.4.1
RAILS_ENV=production bundle exec rails db:migrate
RAILS_ENV=production bundle exec rails assets:precompile
sudo systemctl restart mastodon-sidekiq
sudo systemctl reload mastodon-web
```

**Comment by kdmiller45** [comment]
I'm sorry am a newbie at this I did perform the commands you have given me again in the order above an still setting at 3.4.0

**Comment by ClearlyClaire** [comment]
did you perhaps encounter an error in any of those steps…?

**Comment by kdmiller45** [comment]
Here is a screen dump of the process
![image](https://user-images.githubusercontent.com/19610991/120902882-b0e00f00-c5f7-11eb-8c44-9d9b0e127656.png)

**Comment by ClearlyClaire** [comment]
`git checkout -- Gemfile.lock` before doing the `git checkout v3.4.1`

also run `bundle config --local frozen 'true'` before `bundle install` so it doesn't happen again

finally, please avoid doing any of that as root, the only moment you need root is to call `systemctl`

**Comment by kdmiller45** [comment]
I will do that, thank you very much for the patience

**Comment by kdmiller45** [comment]
BINGO
so is this pretty how you update Mastodon
git checkout -- Gemfile.lock
git fetch
git checkout v3.4.1
RAILS_ENV=production bundle exec rails db:migrate
RAILS_ENV=production bundle exec rails assets:precompile
sudo systemctl restart mastodon-sidekiq
sudo systemctl reload mastodon-web

And is it no longer necessary to perform bundle config --local frozen 'true' before running bundle install (Pretty much a one time thing)
