### ISSUE TITLE
Suggestion: Add pkg-config to Gemfile

### ISSUE THREAD

**Issue by brycied00d** [tootsuite/mastodon#1637]
Certain platforms (OpenBSD in my case) have trouble building nokogiri without the pkg-config gem. With the addition of this patch (gem) and setting `bundle config build.nokogiri --use-system-libraries --with-xml2-include=/usr/local/include/libxml2`, I'm able to `bundle install` in `--deployment` mode.

```patch
diff --git a/Gemfile b/Gemfile
index 9a17926..d7d71ce 100644
--- a/Gemfile
+++ b/Gemfile
@@ -3,6 +3,8 @@
 source 'https://rubygems.org'
 ruby '2.4.1'
 
+gem 'pkg-config', '~> 1.1.7'
+
 gem 'rails', '~> 5.0.2'
 gem 'sass-rails', '~> 5.0'
 gem 'uglifier', '>= 1.3.0'
diff --git a/Gemfile.lock b/Gemfile.lock
index f1bc988..6fcf8a5 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -266,6 +266,7 @@ GEM
     pg (0.20.0)
     pghero (1.6.4)
       activerecord
+    pkg-config (1.1.7)
     powerpack (0.1.1)
     pry (0.10.4)
       coderay (~> 1.1.0)
@@ -496,6 +497,7 @@ DEPENDENCIES
   paperclip-av-transcoder
   pg
   pghero
+  pkg-config (~> 1.1.7)
   pry-rails
   puma
   rabl
```

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
Please do a PR 👍

**Comment by brycied00d** [comment]
Ask and you shall receive, @wxcafe. 

I had not initially made this a PR since the change was so minor, it was more effort to create the PR than a simple issue.
