### ISSUE TITLE
Duplicate HSTS header: Strict-Transport-Security

### ISSUE THREAD

**Issue by datn** [tootsuite/mastodon#16379]
Recently I checked my site's HSTS compliance and found that I was sending two Strict-Transport-Security headers. I specify one in my Nginx config, so, presuming that now Mastodon itself sets one (as it also sets a CSP), I turned it off. I was left with a single STS header that lacks "preload" and thus fails compliance. However, I can't find where this header is being set outside of my own Nginx setup.

This is the rogue header:

```
strict-transport-security: max-age=63072000; includeSubDomains
```

### Expected behavior

I would be able to find and modify the header presumably being set by Mastodon to make it compliant, or turn it off and use Nginx's header.

### Actual behavior

In searching for where this header is set, I have walked through the documentation, the source code and every related file I can find to no avail. My current choices are: send two headers (non-compliant) or send a header that lacks "preload" (also non-compliant). 

### Steps to reproduce the problem

Set & unset the STS header in Nginx; testing with 
```
curl -Is https://my.site | grep -i strict-transport-security
```
### Specifications

For sure the current version, 3.4.1; I presume it's been around since before this, though.

**Comment by shleeable** [comment]
confirmed.
```
➜  ~ curl -Is https://aus.social | grep -i strict-transport-security

strict-transport-security: max-age=63072000; includeSubDomains
strict-transport-security: max-age=31536000
```

**Comment by ClearlyClaire** [comment]
This is likely the result of updating to Rails 6.1. In any case it is set by Rails. This can be disabled by changing `config.ssl_options` in `config/environments/production.rb` to include `hsts: false`, or, to add preload, add `hsts: { preload: true }`.

I am not sure whether we should disable that header, or change the default nginx config and instruct server admins to review their config. The first solution seem cleaner, but requires admin action, which isn't great.

**Comment by datn** [comment]
Thank you so much! My `config.ssl_options` now reads:

```
  config.ssl_options = {
    hsts: { preload: true },
    redirect: {
      exclude: -> request { request.path.start_with?('/health') || request.headers["Host"].end_with?('.onion') }
    }
  }
```

**Comment by edmondburnett** [comment]
For me setting the `hsts` options in the ruby config wasn't working, the settings seem to be ignored and Ruby still adds it's own default header, resulting in two `Strict-Transport-Security` headers being sent to the client.

I fixed it in nginx by first hiding the header and then re-setting it:

```
location @proxy {
  ...
  proxy_hide_header Strict-Transport-Security;
  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
}
```

Now the desired header only appears once.
