### ISSUE TITLE
Follower numbers wildly inaccurate if social graph is hidden

### ISSUE THREAD

**Issue by FediVideos** [tootsuite/mastodon#16382]
### Expected behaviour

Follow numbers viewed remotely should (roughly) correspond to how many follows an account has, especially if time has elapsed to allow federation.

### Actual behaviour

If an account hides its social graph, follow numbers are wildly inaccurate, even a long time later.

For example, PixelFed (which currently hides its social graph) has approximately 10k followers, but viewed from mastodon.online it has 188 followers. (However, viewed from older instances it appears to have 8k followers.)

Briar (@briar@fosstodon.org) is another example, it has 1.18k followers but it has hidden its graph (maybe from beginning?) and only shows a few dozen follows when viewed remotely.

It seems like remote follower numbers get stopped from federating when an account hides its social graph? It seems the numbers federate before the social graph is hidden, but after being hidden the numbers stop federating?

Perhaps this is deliberate to prevent inflated follow numbers using mass fake followers? (I guess if someone hides their social graph and they own their own instance, it would be impossible for others to detect if they start filling their follow numbers with fake accounts.)

If this is deliberate, it would be nice to have the option of hiding my own follow numbers completely. I have hidden social graph on all my accounts, and I would rather hide my numbers than show wildly inaccurate figures.

### Steps to reproduce the problem

Look at an account with hidden social graph, both on its home instance and viewed remotely from other instances.

### Specifications

Masto v3.4.1

**Comment by ClearlyClaire** [comment]
In any case, follow/follower numbers for remote accounts are never guaranteed to be anywhere close to accurate, as it only gets updated when fetching the profile data again (or receiving an `Update`), which may happen infrequently and irregularly.

> It seems like remote follower numbers get stopped from federating when an account hides its social graph? It seems the numbers federate before the social graph is hidden, but after being hidden the numbers stop federating?

You are right. For technical reasons, hiding the number when we don't have them is a little involved, and I am not sure it's worth doing those changes. However, in Mastodon's case, not federating the number wasn't intended, but is an issue I'll look into fixing.
