### ISSUE TITLE
when i click "share" page crash. (at mastodon.social)

### ISSUE THREAD

**Issue by RamazanGeven** [tootsuite/mastodon#16389]
### Actual behaviour

https://user-images.githubusercontent.com/12789059/121786166-d4422580-cbc6-11eb-991f-0755c5b147d9.mp4

### Specifications

Windows10  , opera

**Comment by ClearlyClaire** [comment]
This seems like a bug in your browser rather than a bug in Mastodon itself

**Comment by weex** [comment]
Confirmed that Chrome on Windows 10 brings up the system share dialog. Do we remove the bug label or close this?

**Comment by sprackraptor** [comment]
I use Opera and I get an identical-looking page when I click the "share" icon, with script in English:
"Page crashed
Unfortunately, something caused this page to quit. It might have been an extensions conflict or some other reason.
Try reloading the page, or navigating to another page to continue."
and the button below says "Reload this page."
when I click that button the page reloads and returns me to Mastodon.

**Comment by sprackraptor** [comment]
ah, and my admin says to also state I'm using a glitchsoc build from June 24.

**Comment by weex** [comment]
Github reports a significant number of commits to glitch-soc so might be best to submit this issue there https://github.com/glitch-soc/mastodon/issues

**Comment by ClearlyClaire** [comment]
This is a bug in Opera, not Mastodon or glitch-soc

https://forums.opera.com/topic/49648/trying-to-use-navigator-share-crashes-opera-tab
