### ISSUE TITLE
[Request] Admin auto-follow all new signups

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#16388]
### Pitch
You broke the autofollow from signup to admin - but I still want to follow these people

### Motivation
I want to see everything in my timeline.

**Comment by ClearlyClaire** [comment]
Wait, admins auto-following new users? Honestly that's creepy and I'm strongly opposed to that

**Comment by shleeable** [comment]
Look. I just want to do my job as an admin and you've broken my workflow to do that.

What do you suggest I do instead? Don't auto follow, but give me a notification on every signup then.

Because just ignoring this whole situation isn't the right thing. What's your solution and what are you going to do about? 

I just want to be more aware of signups of my instance.

**Comment by ClearlyClaire** [comment]
Being notified of new sign-ups and auto-following them are two very different things…

**Comment by shleeable** [comment]
I agree.. I think my frustration is the regression needs a solution. I look forward to seeing what you and the team come up with.

I'm just keen for a solution.
