### ISSUE TITLE
About link becomes 404 Not Found in limited federation mode

### ISSUE THREAD

**Issue by levee223** [tootsuite/mastodon#16407]
This issue is probably due to insufficient implementation of #11291.

### Expected behaviour

The About link should be hidden in limited federation mode.
Ref: https://github.com/tootsuite/mastodon/blob/main/app/views/layouts/public.html.haml#L14-L17

### Actual behaviour

![screenshot](https://user-images.githubusercontent.com/28427547/121952901-d1e2f580-cd97-11eb-902b-aa59828563a2.png)

### Steps to reproduce the problem

1. Clean install Mastodon in limited federation mode.
2. Create a user and log in.

### Specifications

* Mastodon v4.3.1 (Docker)

**Comment by weex** [comment]
whitelist_enabled isn't available to the front end, but once that's exported to initial state, these can be rendered based on that

**Comment by weex** [comment]
Created a PR for this https://github.com/tootsuite/mastodon/pull/16432
