### ISSUE TITLE
tootctl accounts cull list domains in errors, but tooctl domains purge does not purge these domains

### ISSUE THREAD

**Issue by benpro** [tootsuite/mastodon#16410]
### Expected behaviour

`tootctl accounts cull` list domains in errors.
`tootctl domains purge` on these domains should delete everything related to it. 

### Actual behaviour

`tootctl accounts cull` list domains in errors.
`tootctl domains purge` does nothing on these domains.

### Steps to reproduce the problem

```
$ DB_POOL=80 ./tootctl  accounts cull --concurrency 80                          
Error processing 435: Connect timed out after 5 seconds on https://mastodon.h-sund.nu/users/tardigrader                                                                                                                                     
Error processing 2073: SSL_connect returned=1 errno=0 state=error: certificate verify failed (Hostname mismatch) on https://social.stupid.industries/users/r0                                                                               
[...]                                                                                                                        
54488/54661 |============================================================================================================================================================================================================   |  ETA: ??:??:??
Visited 54661 accounts, removed 0
```

```
$  ./tootctl domains purge mastodon.h-sund.nu social.stupid.industries
0/0 |=======================================================================================================================================================================================================================| Time: 00:00:00
Removed 0 accounts
Removed 0 custom emojis

```

These two examples domains should be nuked! I don't want any traces of old dead instances in my database. I believe this is a bug.

Feature request that can be related: #15321

### Specifications

Mastodon 3.4.1

**Comment by benpro** [comment]
Some details:

```
mastodon_production=# select domain from accounts WHERE domain='mastodon.h-sund.nu';
(0 rows)
```
I am not sure where cull get the data :/

**Comment by benpro** [comment]
`tootctl domain purge` worked like a charm on these problematic accounts by dropping the subdomain. I wonder why some accounts seems to have wrong domains (should be FQDN)?

**Comment by ClearlyClaire** [comment]
The domain part of an `acct:` handle (webfinger) does not have to be the domain which serve the actual ActivityPub endpoints. This is not an error and this is expected. This is explained on https://docs.joinmastodon.org/admin/config/#web-domain

Now, maybe `tootctl accounts cull` should print the `domain` part on error, or `tootctl domains purge` select based on actor URI…

**Comment by benpro** [comment]
> Now, maybe `tootctl accounts cull` should print the `domain` part on error, or `tootctl domains purge` select based on actor URI…

Indeed!

**Comment by ClearlyClaire** [comment]
Interestingly, `tootctl accounts cull` is already meant to list the domains causing such failures. However it seems it does not catch the errors that were raised this time. Maybe it should do so.

**Comment by weex** [comment]
Can the uri or url field be depended upon to provide the true domain name? If so, it could be parsed for the domain.

**Comment by ClearlyClaire** [comment]
> Can the uri or url field be depended upon to provide the true domain name? If so, it could be parsed for the domain.

I'm not sure what you mean. In the context of Mastodon, an account's `domain` has always been the domain part of the webfinger handle, I'm not sure it would make sense changing that anywhere. If `HTTP::TimeoutError` and `OpenSSL::SSL::SSLError` were caught in addition to `HTTP::ConnectionError` and treated as temporary failures in `tootctl accounts cull` as they are in other parts of the code, `tootctl accounts cull` would not display those errors and instead print a summary of domains that were unavailable during `tootctl accounts pull`, with the domains being the domain part of the webfinger handles as usual. I think that would be preferable, although I'm not 100% sure.

**Comment by weex** [comment]
I was just looking at the available data on the account record. The domain in the @benpro's db record wasn't complete but complete ones could be found in uri and url. I haven't checked to see how strict Mastodon is about the uri and url but this record implies that domain doesn't always have what a script like this needs.

**Comment by ClearlyClaire** [comment]
> I was just looking at the available data on the account record. The domain in the @benpro's db record wasn't complete but complete ones could be found in uri and url.

I am not sure what you mean by “complete”. It is complete in the sense that for Mastodon's purposes, this is the domain used for grouping accounts by instance.

> I haven't checked to see how strict Mastodon is about the uri and url […]

The domain part of the webfinger `uri` and that of the ActivityPub actor `uri` do not need to have anything in common, what makes a valid `uri` and `preferredUsername@domain` couple is that both of the following conditions are met:
- querying `https://domain/.well-known/webfinger?resource=acct:preferedUsername@domain` points to `uri`
- querying `https://uri-domain/.well-known/webfinger?resource=acct:preferredUsername@uri-domain` redirects to `acct:preferredUsername@domain`

where `uri-domain` is the domain part of the `uri` field and `preferredUsername` is the field of the same name in the ActivityPub actor at `uri`.

The `url`, if it exists, and basically anything owned by the described actor, must share the same domain part as the `uri`.

> […] but this record implies that domain doesn't always have what a script like this needs.

Again, I am not sure what you mean exactly. The primary use case for `tootctl domains purge` is to forget about an instance, identified by its `domain`, which everywhere in Mastodon's interface, is the domain-part of the webfinger handle.

(I know that's a lot of words for something that could be addressed by either catching the exceptions as I described in my former comment, or providing maybe something like `--by-uri-domain` option that would use `uri` domain part, but I wanted to clear up what were “domains” in the context of Mastodon)
