### ISSUE TITLE
not everyone can view photos

### ISSUE THREAD

**Issue by Fritillaria** [tootsuite/mastodon#1642]
I'm seeing some inconsistencies in the ability to view posted photos in the last few days.

Some can't see mine, but I can see mine, my instance can see mine (according to the little feedback I've had but that might have been coincidence). I can see some others' photos, but a few I can't. Using Amaroq, I can't get to the photos at all, but at my computer, if I go all the way to the user's homepage (rather than having it come up in the right column) so far I can see them. I've spoken to one other user who noticed the problem, too.

* **

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment]
Yeah I've been seeing this problem come up too. When I open the images with Firefox I get the following:
![An image of the Firefox download prompt with an extension-less text file](https://cloud.githubusercontent.com/assets/13566135/25063250/703d5b36-2233-11e7-9425-02a283808124.png)

By comparing the headers of an image that displays and one that doesn't using cURL, the only different seems to be that the one that displays has an extension..
