### ISSUE TITLE
Infinitely-growing Sidekiq pull queue

### ISSUE THREAD

**Issue by ashfurrow** [tootsuite/mastodon#16446]
Good afternoon. Yesterday I experienced a failure on the `mastodon.technology` instance, which is running version 3.3.0. I wanted to report this for others in case they find it helpful, but I expect the issue will get closed as the problem was probably a fluke.

The server started using 100% of its available RAM and when I looked, there were over 3 million `LowPriorityDeliveryWorker` jobs in the `pull` Sidekiq queue. By the time I figured out what was going on, about 45 minutes, that grew to 4.4 million. Several thousand new jobs queued per second. The growth in queued jobs persisted even after rebooting the server, and even when I had stopped the `web` Docker container (so something in the `sidekiq` service was queuing these jobs). There was no increase of inbound network activity to suggest this was a malicious attack.

The jobs were all duplicates of each other – I regret I didn't copy the arguments (but I can retrieve them if it would be helpful). The job was was a deletion of the status at `https://friend.camp/users/tripofmice/statuses/103687506960706656` with a local user as its `source_account_id`. I sent a web request to delete the Sidekiq queue but it timed out, and I was also unsuccessful in clearing the queue from a Rails console. My solution was to stop all the Mastodon services and `mv dump.rdb` to a new filename so that when I restarted the service, the Redis store was blank and Sidekiq had no queues. I then ran `tootctl feeds build` to rebuild local feeds. We lost some toot deliveries but things have been working since.

I still have the old `dump.rdb` Redis store if it would be helpful – let me know what to examine and I'll provide whatever details I can. I looked through the Mastodon codebase for an obvious bug that would have caused this but I didn't see anything related to `LowPriorityDeliveryWorker` that would cause this kind of runaway job queuing. I should also note that the Redis store was four years old.

Thanks again and have a wonderful day!

**Comment by ClearlyClaire** [comment]
We have fixed a lot of issues regarding forwarding deletions in 3.4.0, I suspect we have fixed those issues. I am not sure what actions you can take to clean up your queue, though.

**Comment by nightpool** [comment]
you can iterate through sidekiq queues from ruby and remove jobs that match
the criteria you've created. I believe the last time I ran into this issue
I posted an example on the mastodon discord, but I don't have it handy
right now.

**Comment by ashfurrow** [comment]
Thank you both! The problem was that the server was so unresponsive that I don’t think clearing out by criteria would have been feasible, especially at the rate the jobs were growing. 

I’ll update as soon as I get the chance. Thank you again!
