### ISSUE TITLE
change treding # condicionals

### ISSUE THREAD

**Issue by AnonymousWebHacker** [tootsuite/mastodon#16453]
Is there a way to change the conditionals for trending #s?
My instance is within a SNET, that is, it is not federated in the network and I only have 500 users and there is still not a single # in trend

**Comment by Gargron** [comment]
The requirement is only 5 different users using the same hashtag on the same day for it to begin trending. Reblogs also count as uses. That seems like it should be doable with 500 users, I'm not sure how much lower the threshold can be.

**Comment by AnonymousWebHacker** [comment]
Tnks you @Gargron 
![Captura de pantalla de 2021-07-01 06-13-34](https://user-images.githubusercontent.com/43164089/124107689-7e2d0900-da33-11eb-90e5-1fc5647f69d8.png)
