### ISSUE TITLE
Scaling on a 1440p monitor in advanced mode doesn't stretch across the screen

### ISSUE THREAD

**Issue by KobyInu** [tootsuite/mastodon#16459]
### Expected behaviour

The content should be stretched across the screen, using up as much of the screen as possible

### Actual behaviour

Half of the screen is used and the other is white space

### Steps to reproduce the problem

1. FireFox Browser
2. 1440p monitor (or above)
3. Use the advanced web interface
![Capture](https://user-images.githubusercontent.com/43623495/124364911-899f5080-dc3c-11eb-8881-e0a12d3890cd.PNG)

...

### Specifications

Win 10, FireFox

**Comment by mstdn** [comment]
I think this is correct 😉 

Mastodon has a fixed column size if im right, it depends on the resolution of your screen in that case. If you would to "zoom" on the page (CTRL + + or CMD + +) you can adjust it better to your needs :) 

Another option is to add this to your custom CSS:

@media (min-width: 1200px)
  {
    .drawer {
        width: 340px;
  }

  .column
  {
    width: calc((100% - 340px) / 3);
  }
}

**Comment by KobyInu** [comment]
Works a treat! Thank you!!!
