### ISSUE TITLE
.onion address does not work anymore

### ISSUE THREAD

**Issue by mstdn** [tootsuite/mastodon#16464]
### Expected behaviour

Working over Tor (.onion)

### Actual behaviour

Error:  To allow requests to c6usaa6obkiahck7rkn2phbffb3strd375pfpxmawuexnmectjizyjad.onion, add the following to your environment configuration:  config.hosts << "c6usaa6obkiahck7rkn2phbffb3strd375pfpxmawuexnmectjizyjad.onion"

### Steps to reproduce the problem

1. Open Tor Browser (or any other with the Tor protocol)
2. Go to our mstdn.social .onion address: http://c6usaa6obkiahck7rkn2phbffb3strd375pfpxmawuexnmectjizyjad.onion/about
3. See the magical error!
...

Installation was done via the official docs -> Hidden service. 
I tried adding with "alternate_domain" but this did not work. 

Screenshot to be cool meow
<img width="1112" alt="Schermafbeelding 2021-07-04 om 23 04 36" src="https://user-images.githubusercontent.com/57602062/124399516-3ef50580-dd1c-11eb-987c-9468e288fbb5.png">

### Specifications

- Tor Browser
- Latest main code
- meow meow meow!

**Comment by ClearlyClaire** [comment]
This is weird, adding “c6usaa6obkiahck7rkn2phbffb3strd375pfpxmawuexnmectjizyjad.onion” to the `ALTERNATE_DOMAINS` environment variable should work.

**Comment by mstdn** [comment]
> c6usaa6obkiahck7rkn2phbffb3strd375pfpxmawuexnmectjizyjad.onion

I tried again! And somehow it worked this time! 😄 Ill close this
