### ISSUE TITLE
[Feature request] Ability to autopause all gifs

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#1652]
At the moment, unless someone clicks NSFW when posting to hide a gif, gifs play automatically in the timeline. This is annoying because it is misleading - gifs are not usually NSFW. I think it also puts things in the #NSFW hashtag, which is usually incorrect. And it makes the gif a black square, which means I have no hint about what it is. This is a bodge, using a function not really suited to the task in order to meet a need, and to be effective it requires every poster to mark all gifs NSFW for the benefit of a smaller proportion of users, which is not happening.

This is troublesome for me, with autistic processing stuff - if the gif is playing as soon as it appears it sort of freezes my brain up. It's also an issue for people with some forms of epilepsy and so on. I'm sure it's a big issue for lots of other neuroatypicalities, too.

I've had people tell me to install browser extensions to pause gifs, but I've tried so many. They all either don't work at all, or only sometimes work, so this isn't a solution.

There are places that have built-in features that let me handle this very well. The apps for Telegram and Twitter both have settings that autopause gifs, requiring me to click them to play them, and then click once more to pause. This makes such a huge positive difference to my experience with these apps. Here's how an autopaused gif looks in Telegram:

![c52a283c-1d78-11e7-91c7-ce30ccc937a3](https://cloud.githubusercontent.com/assets/6607512/24982214/31ef5fc6-1fd8-11e7-9021-bd978ce4f255.png)

This was mentioned in #596 and it was actually part of the request #441 - both of which were closed with the autopause-gif-avatars update, but with no mention of whether gifs in the timeline would one day be pauseable. So I'm posting it here again as an issue on its own, to let people subscribe to and show support specifically for this issue, and to get a clear answer on whether it's possible and whether it'll be done.

Thanks! :)

* * * *

- [Yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by paralithode** [comment]
Is part of the issue that all .gifs are transformed into .mp4s on upload? I seem to remember they used to be, at least. Native .mp4s don't autoplay, right? Maybe if that's the case files that start out as .gifs can be treated the same way? I guess mastodon hasn't quite cracked moving image handling in general yet.
