### ISSUE TITLE
Inline JS prevents people from setting up a safer CSP policy

### ISSUE THREAD

**Issue by Komic** [tootsuite/mastodon#1656]
More of an enhancement request than a real issue: I'm pretty sure simply defining `STREAMING_API_BASE_URL` and `INITIAL_STATE` in a different way (not inlining it in a `<script>`) would allow people to setup a CSP policy without an `unsafe-inline` directive.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by riking** [comment]
Could emit JSON in a `<div id=initial-state style="display:none"><%= json_encode(@initialstate) %></div>`

then `window.INITIAL_STATE = JSON.parse(document.getElementById('initial-state').innerHTML);`

in the app boot.

**Comment by skhameneh** [comment]
It might be ideal to accept a custom (both in value and name) header that would populate "nonce"; the value can be generated by nginx (or HAproxy in my case).  HAproxy has a rand() function, could hash that for the nonce value.

**Comment by Komic** [comment]
Meh, more of a pita to setup, and less compatible with older browsers though~

**Comment by skhameneh** [comment]
nonce is ignored by older browsers

**Comment by Komic** [comment]
Implementation example [here](https://github.com/Wonderfall/mastodon-targaryen/commit/716d715a444fdfc165fb3704538dbbc1b0112daa), (thanks @Wonderfall).

**Comment by xvilo** [comment]
For some reason I can't get @Wonderfall 's implementation working on tag V1.1.1. It won't start any more, not sure how to debug it. Maybe some one could look into this

**Comment by jviide** [comment]
Had a go trying to fix this in pull request #1806. It's based on the comment @riking made and uses a `<script type="application/json">` tag instead of a `<div>`.
