### ISSUE TITLE
 Mastodon boosts don't show up on quitter 

### ISSUE THREAD

**Issue by picsi** [tootsuite/mastodon#1659]
It's either a GNU social issue or a Mastodon issue. Posting on both issue trackers just to be sure: https://git.gnu.io/gnu/gnu-social/issues/257

Per https://quitter.se/notice/10847070

I suspect the other way around is also true.

Additionally, I think there's a related problem with favorites: they're not coming through. Compare https://quitter.se/notice/10857497 with https://mastodon.social/@Gargron/2360734

In fact, comparing @Gargron's local and remote profiles is a great way to see how these two problems are connected.

**Comment by Gargron** [comment]
Is this still an issue? I am pretty sure at least favourites do go through fine
