### ISSUE TITLE
Boosted toot duplicate from a different user shows up in timeline

### ISSUE THREAD

**Issue by eidolies** [tootsuite/mastodon#1667]
Steps to reproduce:

1. Follow only User_A.
2. User_A boosts a toot from User_C (that you're not following), so it shows up in your timeline (Home/first column).
3. Now start following User_B who, moments ago, boosted User_C's toot as well.
4. A second boost of the same toot shows in your timeline:

![dupoueticate](https://cloud.githubusercontent.com/assets/787068/24988386/f1841ee4-2005-11e7-81f1-fd7ab47e3311.jpg)

For reference: 

- My account: https://mamot.fr/@eidolies
- User_A: https://toot.cafe/@nolan
- User_B: https://mastodon.social/@GinnyMcQueen
- User_C: https://mastodon.technology/@twitter
- Boosted toot: https://mastodon.technology/users/twitter/updates/10195

- [x] I searched and browsed the repo’s hundreds of both open and closed issues to ensure this is not a duplicate

**Comment by BjarniRunar** [comment]
This was discussed briefly here, https://mastodon.xyz/@HerraBRE/754507, and I was asked to share my proposed solution in an issue. Hope this is useful to someone:

> I don't know the implementation well, so pardon me if this is silly!
>
> Could this be solved using JS at the client layer? Keep a list of say the last N toot IDs that have been displayed and just suppress duplicates?
>
> I think the backend should still serve things, as keeping track of what each and every user has seen would be unreasonably expensive server-side.

**Comment by Cassolotl** [comment]
I think this is fixed now?
