### ISSUE TITLE
JS Console Error TypeError: _httpLinkHeader2.default.parseParams is not a function

### ISSUE THREAD

**Issue by dasksting** [tootsuite/mastodon#1674]
When you open the main page (/web/getting-started). An error occurs in the console. The front line displays: Oops! An unexpected error occurred. The second day this problem, used to work well.

`TypeError: _httpLinkHeader2.default.parseParams is not a function
    at Function._httpLinkHeader2.default.parseAttrs (application-5764060….js:38)
    at Link.parse (application-5764060….js:352)
    at Function.Link.parse (application-5764060….js:352)
    at exports.getLinks (application-5764060….js:30)
    at application-5764060….js:29`

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by isati** [comment]
Also #1647

**Comment by d0p1s4m4** [comment]
maybe you forgot to upgrade dependencies with `yarn upgrade`

**Comment by dasksting** [comment]
Did not help, I did 2 commands:
`yarn install`
`yarn upgrade`

**Comment by dasksting** [comment]
Kind man [https://github.com/hnrysmth](url) found a solution. Work fine for me.

Reproducing this here on my mastodon.dev Vagrant instance too. I can see that http-link-header@0.8.0 is in node_modules with the function present and correct. I've also confirmed it's present in the VM's filesystem. But I'm still getting that parseParams is not a function error. When I look in the built .js file my instance is serving, sure enough, the function is missing and it's still the old version.

Things I've done:

`yarn install`
`yarn upgrade`
`rake assets:clean`
`rake assets:precompile`

It seems to be some kind of confusing cache invalidation thing. Even just adding a single blank line to app/assets/javascripts/components/link_header.jsx is enough to get it to serve a fresh build with the new version.
