### ISSUE TITLE
Javascript English locale file not synchronize with current code

### ISSUE THREAD

**Issue by yookoala** [tootsuite/mastodon#1675]
English locale file should be the template for other languages to follow. It is expected to be in-sync with the code. However, it is found to be out-dated. Some language keys are missing. Some are obsoleted.

That create overheads in translation. Translators need to put in extra efforts to find the missing pieces.

You may find some of the complains here:
 * Update Russian translation (#1570)
 * fix Portuguese translation (#1661)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by rkarabut** [comment]
I can get on that.

**Comment by yookoala** [comment]
@rkarabut Already done in #1676. Please help reviewing the changes.
