### ISSUE TITLE
IPFS Backend?

### ISSUE THREAD

**Issue by matthiasbeyer** [tootsuite/mastodon#1678]
Would it be possible to add a backend which uses IPFS as data storage? This would be wonderful and would make mastodon even more distributed (not federated, but really distributed)!

**Comment by Dragnucs** [comment]
Related issues: https://github.com/tootsuite/mastodon/issues/1474, https://github.com/tootsuite/mastodon/issues/477 and https://github.com/tootsuite/mastodon/issues/360.

**Comment by matthiasbeyer** [comment]
Whops, I already submitted this? I'm sorry about the duplcation. I'll close this now.
