### ISSUE TITLE
reference error on login

### ISSUE THREAD

**Issue by Magiccamera** [tootsuite/mastodon#1690]
ReferenceError: Can't find variable: en

I'm stumped. can reach the login screen but once logged in site goes blank dark grey.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by rixx** [comment]
Same thing happening here after installation straight along the lines of [the guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md) just today.
![2017-04-13-152447_1581x212_scrot](https://cloud.githubusercontent.com/assets/2657547/25006496/61a9107e-205d-11e7-9f94-6f9bdbe84091.png)

**Comment by mjankowski** [comment]
Fixed by: https://github.com/tootsuite/mastodon/pull/1689

**Comment by Magiccamera** [comment]
thanks but doesn't seem to have worked. Did git pull for the update. Will check the right file changed per your fix.

**Comment by Magiccamera** [comment]
Yep I kind of figured that. Haven't pulled your branch yet.

**Comment by Magiccamera** [comment]
kudos mjankowsk. Site loads as expected now. Thanks

**Comment by rixx** [comment]
In light of things like this, it might be advisable to provide a `stable` branch that is ff-merged with `master` occasionally.
