### ISSUE TITLE
Maximum height of retoot pop-in

### ISSUE THREAD

**Issue by lanodan** [tootsuite/mastodon#1703]
With big toots, you can’t push the retoot button, a maximum height (like 95vh) should be set, so you can scroll and/or let the width expand.

![screen](https://cloud.githubusercontent.com/assets/3816428/25013458/e82129a0-2073-11e7-9a9c-b0ace4985324.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ericblade** [comment]
fixed w/ #1710  ?

**Comment by tomfhowe** [comment]
Oh whups, I didn't see this when I made https://github.com/tootsuite/mastodon/pull/1710 or I would have mentioned this.

**Comment by lanodan** [comment]
This issue is resolved (just tested via witches.town), but I don’t see how to close this issue.
