### ISSUE TITLE
Scheduled toots

### ISSUE THREAD

**Issue by jpdevries** [tootsuite/mastodon#1707]
Sometimes you are on a toot rampage, but you don't want your audience to know what a toot rampage you are on

This feature would allow you to "Toot later". Maybe you press and hold the toot button, and the longer you hold it, the more of a delay there is. Or in some other manor you specify how long you'd like the toot to be postponed. 

This feature could also be useful for "live tooting" your own presentations.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by tomfhowe** [comment]
I imagine press and hold could be tricky for accessibility reasons. Personally, I just keep a onenote note with post ideas that I can't post right away...

**Comment by ericblade** [comment]
one nice thing is that one could write a node script to do this for you, but i'd imagine something more like tweetdeck's "Schedule Tweet" interface, if I were going to build it into the UI  (no i'm not volunteering)

**Comment by tomfhowe** [comment]
Yeah I feel more like this could make more sense priorities-wise as an external tool rather than a built-in feature. I do like the idea though.

**Comment by alexgleason** [comment]
Thinking long term, it's a nice to have for the UI since businesses and organizations may want to use the platform for outreach. The typical workflow is to have someone write out a huge list of tweets weeks in advance and schedule them to post automatically at peak hours. Twitter doesn't have this, so third-party services are needed to schedule tweets. If Mastodon could cater to this niche it may encourage them to transition. Getting organizations to switch over would be a big deal.

**Comment by tomfhowe** [comment]
@alexgleason I am very familiar with that workflow, I do it through hootsuite every day at work... It would be cool to have it built in, I'm just not sure brands/businesses/organizations are the type of user the project is currently focusing on. Not my call, though! If it's easy to build, let's do it. I don't know how though...

**Comment by jpdevries** [comment]
> I imagine press and hold could be tricky for accessibility reasons. Personally, I just keep a onenote note with post ideas that I can't post right away...

Good point&hellip;

> Yeah I feel more like this could make more sense priorities-wise as an external tool rather than a built-in feature. I do like the idea though.

I agree. Just wasn't sure if we support external tools like that. I guess it would just interface with the API?

**Comment by DavidLibeau** [comment]
I think I will build a tool in this way (see later https://github.com/DavidLibeau/mastodon-tools) :1st_place_medal:

**Comment by tomfhowe** [comment]
Cool

**Comment by wxcafe** [comment]
This is a duplicate of #340 isn't it?

**Comment by jpdevries** [comment]
@wxcafe ya it is, sorry I search but didn't find #340

**Comment by DavidLibeau** [comment]
https://scheduler.mastodon.tools/
