### ISSUE TITLE
Use landmark regions

### ISSUE THREAD

**Issue by LJWatson** [tootsuite/mastodon#1720]
The homepage is divided into columns (Home, Notifications etc.). The columns are created with ```<div>``` elements, which do not convey any useful [semantic information](http://tink.uk/understanding-semantics/) to screen readers.
```
<div class="column">
<div class="column-header ">
<i class="fa fa-fw fa-home" style="display: inline-block; margin-right: 5px;"></i>
<!-- react-text: 138 -->Home<!-- /react-text -->
</div>
...
</div>
```

Suggest adding `role="section"` to the ```<div>``` that is the parent for each column, then using `aria-labelledby` to reuse the existing text as the column's accessible name:
```
<div role="section" aria-labelledby="this" class="column">
<div class="column-header ">
<i class="fa fa-fw fa-home" style="display: inline-block; margin-right: 5px;"></i>
<span id="this"><!-- react-text: 138 -->Home<!-- /react-text --></span>
</div>
...
</div>
```

The ```<span>``` would need adding to have somewhere to set the `id`, but I'm not a React.js dev so there may be a more elegant way to do it.

The result would be that each column would become a landmark region. Screen readers have shortcut keys to make navigating between landmarks easy - and when focus moves to each column/landmark region, the name of the column would be announced automatically by the screen reader.

**Comment by jpdevries** [comment]
Good to know! @LJWatson any thoughts on if we should also use `<section role="section">` instead of a `<div role="section">`? I assume with `role="section"` there it doesn't matter much either way?

**Comment by jpdevries** [comment]
@LJWatson I just submitted PR https://github.com/tootsuite/mastodon/issues/1732 for this. One question. I went with `aria-label` on the `div.column` because it proved more difficult to generate a unique id for a span wrapper. Is that OK?
