### ISSUE TITLE
Low-resolution illustrations and graphics in web UI

### ISSUE THREAD

**Issue by daprice** [tootsuite/mastodon#1723]
Related to #1245 and #1469

These assets are pixelated/blurry on high-DPI or “retina” displays due to their low resolution:

* mastodon logo on the login screen
* mastodon-getting-started illustration in the Getting Started menu
* mastodon-not-found illustration
* oops.png on error pages

There’s already an SVG version of the logo that could be used anywhere the logo appears in the UI. From #1245 it sounds like there’s not currently a higher res or vector version of mastodon-getting-started, but @elioqoshi created an SVG version of mastodon-not-found that could be used in place of the current PNG.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by elioqoshi** [comment]
I am happy to recreate more SVG's if needed :)

**Comment by jpdevries** [comment]
I think it would be amazing if this paper plane graphic was animated SVG (maybe the Mastodon launches off a paper plane and picks up a new one each time you toot)

of course that would be a ton of work&hellip;

<details open>
<summary>Screenshot</summary>
<img src="http://j4p.us/0h323D2j3p3P/Screen%20Shot%202017-04-14%20at%2011.55.20%20PM.png" alt="Duotone illustration of Mastodon holding a paper plane in truck ready to be launched off" />
</details>

**Comment by elioqoshi** [comment]
Do we have the SVG of that?

**Comment by daprice** [comment]
@Gargron If you don’t have higher-res versions from the original artist, are there any licensing issues with people here redrawing them? I’m thinking it would be covered under the overall project’s AGPL but wanted to be sure.

**Comment by rashfael** [comment]
If somebody can clear up the licensing/copyright, I already redrew two images (with some changes, we replaced the paper plane with a rocket).
Here's the image for the bottom left corner:
https://chaos.social/packs/mastodon-fairydust-eeba674d139a1ffa5e6475009a462faf.svg
We also did a sticker based on the landingpage mastodon:
https://chaos.social/system/media_attachments/files/000/426/458/original/408be576a239b1ba.png (png here but actually svg)
I'd be happy to clean the images up some more and draw versions with the paperplane if there is interest.

**Comment by Gargron** [comment]
Implemented in #6286

**Comment by LoganDark** [comment]
@Gargron The emoji picker is still low-res.
