### ISSUE TITLE
Atom feed boosts aren't formatted

### ISSUE THREAD

**Issue by dolfinsbizou** [tootsuite/mastodon#1724]
When a toot is a boost, it's not actually formatted in the atom feed. Cf screenshot below, via https://tooting.intensifi.es/users/dolfsquare.atom, the formatted toot is one of my toots, and the buggy one is a boost.
![capture d ecran de 2017-04-13 22-32-30](https://cloud.githubusercontent.com/assets/1367493/25023191/2f898ef2-2099-11e7-96c7-1df1b0503274.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
I'm certain this has been fixed.
