### ISSUE TITLE
Scroll down to clicked toot when opening a thread

### ISSUE THREAD

**Issue by AbelToy** [tootsuite/mastodon#1725]
If there's a long thread involving many toots, clicking a toot should automatically scroll there when opening the thread, instead of just staying at the top.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment]
I generally like to read threads from the top down, even if they're quite long. Maybe an option could be implemented to automatically scroll?

**Comment by AbelToy** [comment]
yeah, but when you're clicking for a thread you've already read part of, it gets annoying

**Comment by hoodiek** [comment]
this is a duplicate of #471

advise closing.

**Comment by ashfurrow** [comment]
Agreed, going to close. Let's move discussion to https://github.com/tootsuite/mastodon/issues/471 everyone. Thanks!
