### ISSUE TITLE
GIF media uploads now animate too fast

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#1726]
https://slime.global/@hoodie/105671 here's an example post, i only discovered this due to the luck of owning a gif i use as an avatar that, when uploaded as a media attachment, animates much faster.

the conversion from gif->video is probably where this bug originates

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment]
Mastodon [uses paperclip](https://github.com/tootsuite/mastodon/blob/master/lib/paperclip/gif_transcoder.rb) for gif transcoding, so thats probably where the problem lies (or ffmpeg, which paperclip uses). Have you seen this happen to any gifs longer that 2 frames?

**Comment by hoodiek** [comment]
i havent done too much testing, especially cuz i dont happen to have all that much info about my gifs to test with. should i test with more gifs? would that help somehow?

**Comment by expenses** [comment]
@hoodiek Ok, I just did a test and can reproduce this (see [here](https://mastodon.cloud/@expenses/766782)).

Steps:
1. Make two images of equal dimensions, named `0001.png` and `0002.png`.
2. Encode a gif with `ffmpeg -r 1 -i ./%04d.png -r 1 out.gif` (`-r` determines the input and output framerate)
3. The gif should flick between each frame evenly.
4. Upload the gif to Mastodon.
5. The converted mp4 should stay on one frame longer than it stays on the second frame.

If the converted mp4 is downloaded then broken down into frames with `ffmpeg -i media.mp4 ./%04d.png`, there are 99 copies of frame A and 2 copies of frame B, therefore it has to be something to do with how the file is converted.

The next step is probably to check which command paperclip uses to convert the gif.

**Comment by Cassolotl** [comment]
Is this connected to *2-frame gifs do not respect delay on final frame #5646*?
