### ISSUE TITLE
Send users an email when they are mentioned in a toot (by default)

### ISSUE THREAD

**Issue by alexgleason** [tootsuite/mastodon#1727]
There's a setting in users' profiles which allows them to receive an email when someone mentions them. This is off by default.

In order to increase adoption of the platform and drive people back, this option should be enabled by default. Otherwise users may become disengaged and feel no reason to check back.

**Comment by jemus42** [comment]
Not sure. Every time I created new twitter accounts for bots and stuff I always had to make sure to uncheck a shitload of checkboxes to not get a bunch of spam, and I really don't want to see mastodon go that route.

(Different things, I know, but still… I'd prefer it to stay opt-in)

**Comment by joyeusenoelle** [comment]
This absolutely should remain opt-in, especially considering that a user can have an account on more than one instance. Mastodon (and software in general) should never, ever be spammy; don't fill users' inboxes with emails unless they've explicitly requested it.

**Comment by Gargron** [comment]
You can modify `config/settings.yml` to modify default preferences for your users. I do believe it's a good default though, in tandem with the less intrusive e-mail digests that you can optionally send

**Comment by wxcafe** [comment]
Yep, this would be pretty spammy imo

**Comment by alexgleason** [comment]
If Tusky notifications worked universally that could solve the underlying issue. For now it's not an option.

Matrix sends emails for unread messages, but only if the user hasn't read the messages within a certain timespan. I believe this could be a compromise.

Either way, I think there's a problem here to solve, even if my proposed solution isn't the right one.
