### ISSUE TITLE
Don't differentiate accented characters

### ISSUE THREAD

**Issue by ladistroy** [tootsuite/mastodon#1731]
Hello,

I was told to put this "issue" there so I do 
In mastodon, the result of tags with and without accent are different. For example 

https://mstdn.io/tags/solidarit%C3%A9
and
https://mstdn.io/tags/solidarite

This is not a problem in language without accent of course, but in french for instance, that means that we have to make many entries to be sure that the correct tag will be caught : #video and #vidéo, #féminisme and #feminisme, #télévision and #télevision and #telévision and #television... if the result of a tag search could be "accent-free" that would be smarter.

Have a nice day ! 

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
I believe we could just use the correct spelling in french? Like, vidéo is supposed to be written this way, not video, which is incorrect. Same with féminisme, not feminisme, télévision not télevision or anything else, etc.

**Comment by mskala** [comment]
Similar issues apply in other scripts.  For instance, I'd like to search for #ねこみみ and also find #ネコミミ and #猫耳, all of which are "correct" spellings for this word.  It may be difficult to do this properly in even one language, let alone all of them.

**Comment by bortzmeyer** [comment]
Even in english, it would be a problem (I tag #theater and I would like people to find it even when they use #theatre). So, I vote to drop the issue: basically unsolvable in software.

**Comment by ChameleonScales** [comment]
Although it's not a big issue since the implementation of multi-tag columns, I don't agree that it is unsolvable, at least partially.
Different spellings would certainly be too difficult to take into account but simple accents like acute, grave tilde, etc would be fairly easy to disregard in tag searches.

**Comment by ChameleonScales** [comment]
Although, I'm realizing that joining results would mix languages which may not be desirable. My stand on this depends on how languages get handled in future releases.
