### ISSUE TITLE
Can't fave/reblog on an individual status page

### ISSUE THREAD

**Issue by nevillepark** [tootsuite/mastodon#174]
A status's timestamp links to an individual page, which 1) doesn't open "in-app" and 2) doesn't have any options to fave or reblog.

![2016-11-21 20_51_12](https://cloud.githubusercontent.com/assets/16054979/20508532/3e48ece6-b030-11e6-8af8-b4ad31d7d7ba.png)

This means that if someone links directly to another status (instead of replying or reblogging), other users can't interact with it and have to find it again another way.

![2016-11-21 20_53_39](https://cloud.githubusercontent.com/assets/16054979/20508524/37a87ea6-b030-11e6-924c-7dd5c85df5a0.png)

![2016-11-21 20_53_58](https://cloud.githubusercontent.com/assets/16054979/20508529/3b02c4b2-b030-11e6-9853-da49d22883bd.png)

It would be nice to have something like this on the status page:

![2016-11-21 20_51_12-2](https://cloud.githubusercontent.com/assets/16054979/20508688/627ff374-b031-11e6-97ae-8eb583ff9c5a.png)

**Comment by Gargron** [comment]
What if links to statuses in statuses took you to the in-UI page for the status? That's how I would expect it to work tbh. The public pages are more like a public record... although I did concede a "follow" button on the public profiles so... maybe.

**Comment by nevillepark** [comment]
Yeah, that would work too!

**Comment by swaldie** [comment]
Going to go ahead and reference #166 here.  In addition to the ability to favorite/boost a toot, users would also like to see the number of times a toot is boosted or favorited.

**Comment by Gargron** [comment]
Public status page now already displays number of favs/boosts, and contains an "open in web" link that takes you to the UI where you can interact with the status!
