### ISSUE TITLE
Question: Own List of Instances?

### ISSUE THREAD

**Issue by Gibsonion** [tootsuite/mastodon#1740]
Would there be any issues with me creating my own separate list of instances to help people find and discover instances they might be interested in? i.e. one that has more information about each instance for example?

* * * *

- [y ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jemus42** [comment]
Currently https://instances.mastodon.xyz/all is the most well-known, and an official list of instances is planned and being worked on.  
If you want to help work on an official database/list/api thingy, the people working on that would probably appreciate the help.

I don't think there's a problem with you making your own list, but keep in mind that there might be instances that prefer not to be listed publicly. Also, having multiple people creating/maintaining multiple lists might end up being confusing for new users, so I personally prefer a "one (or maybe like, two) list to rule them all" approach.

However, I'm just some guy ¯\\\_(ツ)_/¯

**Comment by Gibsonion** [comment]
Well my idea was to have a directory sort of setup that instance owners could sign up to and add their information manually, have the scores and stuff available, but maybe with a bit more information that would make instances stand out, rather than whoevers at the top of the current list getting all the new users based on what currently appears to be a fair arbitrary scoring system, I'd be focusing on creating something that was aiming to give all the services a chance of being found by the right target audience, allow instances to give information about the kind of crowd they want to attract or if they're open to anything, what their policies are etc.

**Comment by tomfhowe** [comment]
@Gibsonion @yiskah As far as I know there is an official one being built already that sounds just like what you're describing. It would probably be _much_ more helpful/productive to work on that one instead, imo.

**Comment by Gibsonion** [comment]
Where can I find details of the official one?

**Comment by tomfhowe** [comment]
@Gibsonion If you're in the discord, there's a landing-page channel which includes what I was talking about.

**Comment by Gibsonion** [comment]
I'm not in the dischord

**Comment by jemus42** [comment]
The WIP repo is https://github.com/tootsuite/joinmastodon

Maybe opening up some issues there tagged as "discussion" or something could be helpful for stuff that's planned but not yet implemented. @wxcafe
