### ISSUE TITLE
No Polish translation

### ISSUE THREAD

**Issue by genzi** [tootsuite/mastodon#1744]
Please merge Polish translation: https://github.com/tootsuite/mastodon/pull/807

**Comment by expenses** [comment]
I'd recommend checking with @Gargron to see where things are at rather than making an issue.

**Comment by rysiekpl** [comment]
Appreciate your suggestion, @expenses. I am the author of the PR and I have been pinging @Gargron and `@support` on Mastodon every day for the last week.

**Comment by hnrysmth** [comment]
Bearing in mind the high volume of issues, PRs and so on in tootsuite/mastodon right now, I'd imagine that the part of the PR's title that says "(needs more love)" might be causing it to be ignored. It's probably hard keeping up with everything, and if I was in that situation I bet I'd just skip over anything whose title made it look like it wasn't ready yet.

Dunno, I could be wrong, but might be worth a shot changing that if people feel that the PR is mergeable now? 😄

**Comment by Gargron** [comment]
@hnrysmth is exactly right, sorry I didn't realize it was ready!
