### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by nevillepark** [tootsuite/mastodon#175]
There should be a [code of conduct](https://www.ashedryden.com/blog/codes-of-conduct-101-faq)—policies regarding community standards and inappropriate behaviour.

There should be rules regarding:

- what constitutes inappropriate content/behaviour
- the consequences for inappropriate content/behaviour
- who enforces the consequences
- how the consequences are enforced
- changing the rules themselves
- under what circumstances, if any, data will be turned over to authorities

And moderation features or functions that might include:

- permissions for different levels of users
- hiding or deleting individual statuses/media
- suspension
- account banning
- shadowbanning (the user isn't banned, but no one else can see or interact with them)
- IP banning
- reporting inappropriate content/behaviour
- contacting a Mastodon instance's mods/admins/ops

Scenarios to consider:

- One user is sending another user threats, harassment, or hate speech.
- One user is inciting many people to send a user threats, harassment, or hate speech.
- Users are using the Mastodon instance to coordinate a harassment campaign on another instance or social media platform.
- A user who may or may not be a minor is posting explicit images of themselves.
- A user is posting explicit images of someone else, possibly without their consent.
- Police contact you about a user's public posts about illegal activities.
- DMCA takedown notices.
- Users are Nazis.

Hope for the best, but plan for the worst.

**Comment by unsmell** [comment]
refer to #115
naturally, terms of service should reflect the code of conduct

**Comment by ggDropbear** [comment]
The other big issue that I would have to see here is transparency of moderators and transparency of administrators (i.e. if one moderator went on a ban spree, how much could be seen by other moderators and how much damage could be fixed in a worst-case-scenario). How this is handled will probably make or break the "mastodon central" server. 

Also, interaction across servers will be another issue.

**Comment by triplefox** [comment]
Adding some COC references for other developer communities:

[Matrix.org](https://matrix.org/docs/guides/code_of_conduct.html)
[Rust language](https://www.rust-lang.org/en-US/conduct.html)

**Comment by Gargron** [comment]
There is now <https://mastodon.social/about/more> with guidelines.
