### ISSUE TITLE
I feel like private posts should go to mutuals only

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#1756]
I find it very strange that my private posts go to people following me. There is no whitelist, it doesn't go to people I've followed, but people who have decided to follow me.

I think it would make more sense if instead it went only to people I follow and who also follow me back. It would make me feel more comfortable posting private things, I think, too.

But if there is a reason for why the current system is different that's fine and I can just not use the private post thing. I'm new so I've not seen some of these decisions get made and the reasoning behind them. I'm just putting it here to see if there's any support. :)

* * * *

- [Yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
There is an option to lock your account, i.e. you get the ability to vet your followers. You should be really using that in tandem with private posts.

Do we need to display an extra warning when you're composing a private toot but your account is unlocked? Perhaps we should

**Comment by Cassolotl** [comment]
So private posts only work when you set your account to private? Or am I misunderstanding? I might just not understand what a private post is for or how it works?

**Comment by mkosler** [comment]
What Eugen is suggesting is that if you only want to talk with mutuals for private posts, then you can lock your account down so that you have to approve follow requests. That way you'll have control over who follows you and therefore who sees your private posts.

**Comment by nightpool** [comment]
@Cassolotl The idea is that private posts are equivalent to private accounts on twitter, but they're per-post. That's where the expectations about who sees them, etc. come from.

**Comment by Cassolotl** [comment]
Okay, I think I get a little better where the phrase "private post" comes from, but it still feels incongruous to me that in order to make a private post I have to autoblock everyone, and whitelist people individually. The way it was first described to me is it's like having a public twitter and a private twitter rolled into one, but this is clearly not the case!

In order to see a private post, all someone has to do is follow me - and if I want to prevent that, all my posts must be private. Am I understanding that correctly?

**Comment by nightpool** [comment]
@Cassolotl No, that's not necessary. You can have a locked account without having private posts, it's just the default.

In order to see a private post, all someone has to do is follow you. If you want to prevent that, you need to lock your account, so that you have to approve follower requests. Post privacy is independent.

**Comment by Cassolotl** [comment]
Okay, so I think I did correctly understand! And my original thought is still my current thought - it makes more sense to me for private posts to be visible to mutuals.

Alternatively, if private posts can be seen just by someone following you, they're not private unless you lock your account - at which point ALL your posts are private anyway and you have to approve follow requests. So "private" is a misnomer and it should be called "to followers".

**Comment by nightpool** [comment]
@Cassolotl here's the current copy:

![image](https://cloud.githubusercontent.com/assets/233815/25058098/12dd1d68-2144-11e7-9fce-f327ebdcb3b1.png)

Also, locking your account only changes the *default* post status (which can be changed back). By no means will "all of your posts be private anyway"

**Comment by Cassolotl** [comment]
@nightpool Thank you. Gosh I am finding all of this very unintuitive, enough that I'm inclined to ignore all of the other post types and just post everything publicly and be done with it.

I've spoken to Mastodon users in person and on Mastodon who agree with me but Github just isn't something they do or can engage with, so I feel very lone-voice here.

**Comment by nightpool** [comment]
Yeah, that's fair. I think that this is probably a good idea in general, I just wanted to clear up why it currently works the way it does

**Comment by Cassolotl** [comment]
@nightpool Thank you, I appreciate it!

**Comment by lifning** [comment]
I think there's a case to be made for having it both ways... That is, adding a "mutuals only" privacy mode in addition to what's already there. I might not want to lock my account and prevent random people who find my public posts interesting from following me such that my public posts end up in their personal timeline, but I'd still want the ability to send a private post just to people I know.

**Comment by benhamill** [comment]
FWIW, I agree a mutuals-only option would make sense.

**Comment by Cassolotl** [comment]
Just found #422 - the ideas in the first post are exactly what I want.

> public (default)
> unlisted
> mutuals
> (custom lists that are a subset of followers would follow)
> 
> this could also allow a seperate check box to make a toot unboostable. i understand this is a dramatic change, but this is a powerful one to give users.

So I'm going to close this, because I want that other thing and they said it well.
