### ISSUE TITLE
Rubocop config not matching Code Climate?

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#1758]
I've seen several reports that errors being detected by Code Climate aren't showing up when people run Rubocop locally - does the Rubocop YML need to be updated?

**Comment by Gargron** [comment]
Code Climate should be using the same rubocop config file. But Code Climate also has other checkers.. code duplication, something with JS, etc. Maybe code duplication checks should be disabled, they haven't be terribly useful.

**Comment by expenses** [comment]
I emailed codeclimate support about this and got a nice reply:

> Hi there,
>
> Thanks for reaching out and I'm sorry for the trouble you're having with those version differences for rubocop.
>
> It's definitely our goal to always stay up to date with the most recent versions that are available for our engines.
>
> I don't have an ETA on when we'll update to these versions, but I can assure you it's something that's on our roadmap. If you'd like I'd be more than happy to reach out once these newer versions are available -- in fact, I've gone ahead and flagged your email to remind me to do so once support is available.
>
> That said I'm sorry for the limitation this is causing in the meantime. Thanks for the nudge on this, and I'll be in touch as soon as I can with updates on that.
