### ISSUE TITLE
Remove authentication requirement for /api/v1/statuses/ endpoint when passed ID is of a public toot

### ISSUE THREAD

**Issue by Wack0** [tootsuite/mastodon#1760]
See title. A user wanting to programatically get a public toot from any instance currently must scrape the public /users/ page. Allowing use of the API endpoint for such activity would be cleaner.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by happycoloredbanana** [comment]
Maybe making ```https://mastodon.technology/@username/statusid.json``` work will solve the problem?
