### ISSUE TITLE
ability to view an instance/local timeline of another instance

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#1778]
there are many uses for this, especially if instances become more refined. a good example is that the new pixiv instance (pawoo.net) is full of art, which makes me want to browse that local/public timeline for the art, however, since my gf is on awoo.space i cant rly make an account there. instances having this capability (probably with the ability to be turned off by the instance admins) would be a very strong feature. i also occassionally have logged into mastodon.social purely to check the public tl when there is things i was hearing about going on there

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JantsoP** [comment]
No, you did not search for the repo for this issue: #1589

**Comment by ericblade** [comment]
I think #1589 is much less specific than this is.  This is a proposal to be able to view an instances public timeline from the web, whereas that is a proposal to subscribe to entire instances feeds from another server.

**Comment by Shnoulle** [comment]
Another example : https://creativity.cafe 

> creativity.cafe is a Mastodon instance for people who make things - artists of any kind, including visual, musical, glitch, 3d, net art, writing, sculpture, and more. Even people who don't create but are just really enthusiastic about creating are welcome! Come on down to talk shop and be around fellow creators.

I think some user on creativity.cafe must want there toot really public, and , personnnaly i want to see if i want to follow some user's on this mastodon. But the only way i have it's to hope someone follow him to.

Really public time line , default to no, can be set to yes : showing the community time line on home page or in a extra page.

**Comment by foozmeat** [comment]
I think this is an important feature to give new users a chance to get the flavor of an instance before committing to an account there. Troll instances won't enable this behavior which is a potential red flag for new users - alternatively private communities won't enable it which would be considered a feature by their users. Its no different from how current web forums work.

**Comment by foozmeat** [comment]
Thinking about implementation...a rough, incomplete, unordered todo list:

* boolean flag in admin settings
* copy and modify the public user template for rendering the timeline
* only show local, public, non-reply toots
* route it under `/public`?

**Comment by foozmeat** [comment]
Browsing further, #1053 seems like the oldest version of this request. This one should probably be closed as a dupe.

**Comment by kevinmarks** [comment]
The api is now public without auth, so I made an instance viewer eg http://www.unmung.com/mastoview?url=Creativity.cafe&view=local

**Comment by nightpool** [comment]
Closing this one in favor of #1053, since the amount of discussion on the ticket seems to be slightly higher there, and it's linked to more duplicate tickets. (So it's easier to find other discussions on the issue, and it keeps the conversation in one place)
