### ISSUE TITLE
Add a "boost" GET API route

### ISSUE THREAD

**Issue by pixocode** [tootsuite/mastodon#1787]
Example "https://[from-instance]/users/[pseudo]/remote_reblog" (as "https://[from-instance]/users/[pseudo]/remote_follow" but for "boost") 

Redirect to (by example) https://[to-instance]/authorize_boost?acct=acct%3A[pseudo]%40[from-instance]" (as "https://[to-instance]/authorize_follow?acct=acct%3A[pseudo]%40[from-instance]" but for "boost")

Next, add this link on "toot page" (ex : https://[from-instance]/users/[pseudo]/updates/[id]) for reblog when it does not appear in our instance (It happens to me often, very small instance)

Can be do the same for replies ?

(Sorry for my english :/)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by debanshuk** [comment]
I am working on this issue.

**Comment by Gargron** [comment]
Duplicate of #916
