### ISSUE TITLE
Mastodon should set the default language according to browser preference

### ISSUE THREAD

**Issue by yookoala** [tootsuite/mastodon#1788]
After v1.1.2, Mastodon is not following my browser's language preference. I have prioritized `zh-HK`. I've even tried deleting `zh` (Chinese in general) from the language list. The site is still showing Simplified Chinese. The language detection is not working correctly.

I'm not familiar with Ruby. So I can be wrong here.

It seems to me that the HTTP Accept-Language test introduced since #1166, mainly [this line](https://github.com/tootsuite/mastodon/blob/fa89deb4eb0fc3bc6a28fb78e212829f20336001/app/controllers/concerns/localized.rb#L30):

```ruby
  def default_locale
    ENV.fetch('DEFAULT_LOCALE') {
      http_accept_language.compatible_language_from(I18n.available_locales) || I18n.default_locale
    }
end
```

is using `http_accept_language.compatible_language_from()` for language detection. This seems to be origin of the problem.

According to the library's [README](https://github.com/iain/http_accept_language/blob/1d1837136eba5723132eebbd8c0176860c184e0c/README.md#available-methods), we have:

> * **preferred_language_from(languages)**: Finds the locale specifically requested by the browser
> * **compatible_language_from(languages):** Returns the first of the user_preferred_languages that is compatible with the available locales. Ignores region.

It seems that `preferred_language_from` will honour the browsers language priority settings, while `compatible_language_from` will only find the first language compatible.

I think the best way to settle is to change to `preferred_language_from(languages)`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
Looking at the options in that list, I think `language_region_compatible_from` is probably the best option: "Returns the first of the user preferred languages that is also found in available languages. Finds best fit by matching on primary language first and secondarily on region. If no matching region is found, return the first language in the group matching that primary language."

If that were in place, it would:

- Try to find exact locale+region combination if we have it
- If we don't have that, fall back to just the locale, ignoring region
- If we don't have that, fall back to the default (`en`)

Does that sound more desirable?

**Comment by yookoala** [comment]
@mjankowski: Thanks!
