### ISSUE TITLE
Add logo to 2FA when using Authy

### ISSUE THREAD

**Issue by mahtin** [tootsuite/mastodon#1795]
When enabling 2FA (at least with [Authy](https://www.authy.com/developers/)) there's no default logo for Mastodon and it's not mentioned in [2FA.md](https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/2FA.md).

Can this be added?

**Comment by mjankowski** [comment]
I think that needs to be done by Authy on their side, unless I'm not understanding the request...

https://www.authy.com/blog/your-favorite-2fa-app-just-got-way-better/

**Comment by mahtin** [comment]
Thanks @mjankowski for the pointer. 

> ABOUT CUSTOM ICONS
> Many of you have asked for a way to create custom icons – uploading your preferred image or logo based on your Authy activity. We agree that it would be super helpful, and we are working on a solution. Custom logos are coming, but as of yet we have not been provided with an ETA from our dev team. Please keep your eyes and ears on our social channels for a forthcoming announcement on user-customization.

... and that was back in October/2016. I will await an update from Authy

**Comment by mjankowski** [comment]
Another thing to consider is that "Adding mastodon" might be sort of impossible, because it would mean adding thousands of instances!

**Comment by mahtin** [comment]
Correct. However, it Authy provided a solution that an end-user (of an system requiring authentication) could follow; then it's up to each mastodon instance to "pretty up" their 2FA setup on Authy. Some will; most won't.
