### ISSUE TITLE
'Mastodon' and 'Toot' names aren't serious enough

### ISSUE THREAD

**Issue by 16bitBlues** [tootsuite/mastodon#1808]
(yes the pun in the title was intended)

I'm certainly not the only one who has mentioned this, but I haven't seen an actual issue be opened on it. The name `mastodon` is, in all honesty, not a good name for a social networking platform. It works for an animal, and for a metal band, but it just seems so out of place for social networking. This would be a rather large change obviously and not to be taken lightly, but I thought I would at least get a discussion going on the topic.

The other terminology is the `toot`. Again, I'm not the only one who has expressed a bit of frustration with the chosen term. I understand mastodons were a distant relative of elephants, and since elephants have trunks, I can kinda see how the term was chosen. But again, it really just doesn't work and is rather awkward to say out loud (e.g. "You were tooting a ton yesterday").

I don't mean this to sound like I'm trying to be critical of the platform. In fact, I so very want this platform to catch on and become the next big thing because its unique implementation/technology I think is perfect for social networking. However the only thing I can see holding back this platform is the terminology. I understand how shallow that may sound, but names and terms really do matter. And in order to see this grow to the size of its similar platforms, I just think more catchier terminology would help. 

If you agree, let us know why! If you disagree, let us know why!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by zcdunn** [comment]
Twitter is named after the sound a bird makes. Tweet is also another word for bird noises. I don't think the terminology is an issue. 

Additionally, instance admins can change the local terminology, which many have done.

**Comment by jemus42** [comment]
I agree with @zcdunn. Also, this terminology is what makes Mastodon quite charming for a lot of new users who try to escape the "be a serious business personality"-cliché from other social networks. 

Also, nothing stops admins to set up serious-business-instances named after dead economists and terminology derived from 18th-century Russian literature. ¯\\\_(ツ)_/¯

**Comment by rainyday** [comment]
I think the biggest problem is that, at least in American English, the most common meaning for `toot` by far refers to a bodily function. Not particularly good branding IMO.

**Comment by expenses** [comment]
Given that the people I think we should be caring about are the ones _already using the platform_, I think its worth checking with them to see how they find the names. Personally, I haven't seen much complaint though.

**Comment by rainyday** [comment]
No it'd more be about people who don't join because they're turned off by the current branding

**Comment by expenses** [comment]
@rainyday I dunno, I kinda feel like we should ideally cater to both crowds, but the ones already using Mastodon are more important by far..

**Comment by wavebeem** [comment]
I could *possibly* see changing the word toot, but "Mastodon" already has huge name recognition and seems totally awful to change at this point…

**Comment by ericblade** [comment]
I think it's more that it appears as a parody of Twitter, is more of a "this is not serious software" seed planter.  Whether it actually is a parody of Twitter is irrelevant, but "toot" vs "tweet" makes me feel like it's like what you'd find in the version of Twitter that the people inside the world of Grand Theft Auto use. :-D

Frankly, I don't care one way or the other, I'm working to adapt it more for use of a small network of people, who will think it's funny, and don't care how serious it is.  That's not everyone, though.

**Comment by tomfhowe** [comment]
Personally, as someone with a bit of a branding/marketing background, I think that:

1. It's very important to stick with the name "Mastodon" for now, because we got a lot of press with that name recently - but **we're not yet big enough of a deal that we would get press about us changing the name**. Assuming we think continued growth is important, we don't want to lose the momentum we have, which is almost entirely due to articles referring to us as "Mastodon." It would be bad to lose that brand recognition.

2. **If we want to change the default terminology for making a post, we have to make sure that we use something unique.** Currently "toot" gives us a unique and interesting identity, since nothing else uses that word. If we just make it say "post" by default, that won't get mentioned in articles or talked about. Personally I think most adults are mature enough to either not think of toot as meaning fart but rather like tooting a horn (or find it funny that it could be interpreted either way). Also it is important to keep in mind that many instances have changed this term to improve their own identity.

If we do want to change the default post button term, my personal suggestion would be "Trumpet" - since that's a descriptor of a noise that an elephant makes (presumably mastodons made that noise as well). 

 Also, have you seen how cute pixiv's mastodon mascot art is? We can't get rid of that...

**Comment by Ragzouken** [comment]
if you call it trumpet it will get shortened to trump which also means fart

**Comment by tomfhowe** [comment]
Ohh nooo I didn't think of that. Well, my actual points stand though.

**Comment by Ragzouken** [comment]
i think we just need to head them off at the pass and rename toot directly to fart

**Comment by Gargron** [comment]
I'm sorry, but this is definitely a wontfix. There is a culture and history to both words, it gives the software a distinct vibe, I don't care if Lance Ulanoff finds it silly.

**Comment by Leadwerks** [comment]
> Twitter is named after the sound a bird makes. Tweet is also another word for bird noises. I don't think the terminology is an issue.
> 
> Additionally, instance admins can change the local terminology, which many have done.


> I agree with @zcdunn. Also, this terminology is what makes Mastodon quite charming for a lot of new users who try to escape the "be a serious business personality"-cliché from other social networks.
> 
> Also, nothing stops admins to set up serious-business-instances named after dead economists and terminology derived from 18th-century Russian literature. ¯\_(ツ)_/¯

This is why programmers should never be in charge of branding.

**Comment by mblackritter** [comment]
> If we do want to change the default post button term, my personal suggestion would be "Trumpet" - since that's a descriptor of a noise that an elephant makes (presumably mastodons made that noise as well).

Now that [Trump's Truth Social](https://en.wikipedia.org/wiki/Truth_Social#Technology), will be based on Mastodon, in retrospect, this is an amazing post! 😻 😹💦

I just hope they don't do it like Microsoft does with any standard they touch and make it incompatible, then Truth Social will finally push all that Mastodon stands for to the broad masses - ***I LOVE IT!*** ✊🏻 🥳🎉

#TruthSocial #Mastodon #Federated #Distributed #SocialMedia #Freedom #FreedomOfSpeech #Gettr #Gab #Trump  #Trump2024
(To help others with their search for the truth about Truth Social and its tech, etc.)
