### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by nex3** [tootsuite/mastodon#181]
The service seems tailor-made for mobile (cf. the mobile usage of Twitter), but the current site is nigh-unusable on a phone. I imagine a high-quality mobile-friendly web site (let alone native apps) would be a lot of work, but I'm creating this issue so I get notified once it's being worked on.

**Comment by Gargron** [comment]
Hey I'm wondering if this issue can be closed? I think we improved a lot of things since. I use the site on my phone all the time.
