### ISSUE TITLE
Sidekiq errors: can't receive confirmation email

### ISSUE THREAD

**Issue by bvanrijn** [tootsuite/mastodon#1810]
See https://gist.github.com/bvanrijn/998a7360ef0f316e24f9ee7344a65694 for the full error text.

I'm not sure how to fix it...

I'm running in Docker by the way, with NGINX as the proxy server.

(Forgive me for the short text, it's late here -- I can provide more information if needed)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ericblade** [comment]
Based on the errors provided, it looks like the network operation is timing out.  Sure you have your SMTP host configured correctly?

**Comment by bvanrijn** [comment]
Eric, thanks for your reply!

On my laptop I can access it quickly (using Python's smtplib) , but on my server, it times out. I'll have to do more testing and will get back to you!

**Comment by Gargron** [comment]
If your SMTP is localhost and you are trying to use it inside Docker, you can't - Docker has separate networking. You'll need to use some sort of public IP in the config

**Comment by bvanrijn** [comment]
@gargron No, I am using Sparkpost (`smtp.sparkpostmail.com`) on Scaleway (a VCS1 server running Ubuntu 16.04) and it seems like they're blocking outgoing connections on port 587 (i.e. SMTP), I tried connecting to `smtp.gmail.com` inside Python for debugging purposes and that also kept hanging.

**Comment by bvanrijn** [comment]
They (Sparkpost) provide an alternative port, 2525, which is not blocked. I'll change the port, try again and get back to you.

**Comment by bvanrijn** [comment]
Also, a slightly related question: if I edit the configuration, do I have to rebuild the image?

**Comment by bvanrijn** [comment]
I fixed this error by enabling SMTP in the applicable security group in the Scaleway control panel, and then rebooting the server from the web UI.
