### ISSUE TITLE
Remote boost of toot by blocking user appears on timeline as made by booster

### ISSUE THREAD

**Issue by fpiesche** [tootsuite/mastodon#1811]
This *may* be the same issue as #1114; at the very least it seems there might be overlap. However:

I have a private single-user instance as well as an account on mastodon.social (m.s for short). Due to a previous confrontation, ginnymcqueen at m.s has blocked me on both accounts. I do follow plsburydoughboy at m.s from my private instance, who in turn follows ginnymcqueen. I am logged into both my account on m.s as well as the one on my private instance.

When looking at either plsburydoughboy's user timeline or the federated timeline from my own instance, I see this:

![screenshot 2017-04-14 23 19 51](https://cloud.githubusercontent.com/assets/393620/25057679/cbd91f7c-2169-11e7-80e8-70262c77042b.png)

Note the lack of media preview which is what caught my attention. If I click the media link, I get taken to a 404 page on mastodon.social.

However, if I click the link on the post timestamp, I am taken to https://mastodon.social/users/plsburydoughboy/updates/1860407 and I can see that this is a toot by ginnymcqueen boosted by plsburydoughboy. I can also see the media.

If I visit mastodon.social/@plsburydoughboy or open the normal mastodon.social frontend and view plsburydoughboy's profile, I can also see the boosted toot appearing as it should be. Note that I am logged in on an account that ginnymcqueen has blocked.

![screenshot 2017-04-14 23 24 41](https://cloud.githubusercontent.com/assets/393620/25057717/3f85fbf2-216a-11e7-9daf-919dbd95f9f3.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
This doesn't seem to me to be the same problem as #1114, since that issue didn't mention blocks.

**Comment by fpiesche** [comment]
I'm very not sure either so I filed a separate issue, but it also seems similar enough that a fix for either could feasibly affect the other as well, so I thought I'd reference at least.

**Comment by jcalvert** [comment]
Just curious, is the issue just the misattribution or is the expectation that the boosted post wouldn't even appear on the timeline?

**Comment by wxcafe** [comment]
I'd say both

**Comment by Gargron** [comment]
This actually is the same issue as #1114, blocks play no role in it.
