### ISSUE TITLE
Non-User filtering of the "public timeline"

### ISSUE THREAD

**Issue by TheChymera** [tootsuite/mastodon#1821]
I am wondering what the ways are in which anybody else except the users may filter the information that reaches them.

* Can the owner of an instance selectively block which posts or users of other instances are relayed to the users of his instance?
* I assume the owner of an instance can decide which other instances to federate with. I guess there's nothing that can be done about that, and "filtering" entire instances will carry a significant cost for the instance doing so. If a user of an instance that as made such a decision disagrees with his information access being thus restricted, can he (easily) move his account (and all the past toots etc.) to an instance which does not restrict the public information flow?
* If e.g. instance A does not federate with instance B in an attempt to censor its users, can 
instance B still provide its users with content from instance A? (this would make sense, since the systemic penalty for censoring should be greater than the systemic penalty for having been censored)
* could governments (legally) compel instances hosted by their citizens on their territories to *not* federate with foreign instances not conforming with their laws regarding information sharing? 

* * * *

- [ X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by toqduj** [comment]
I had a thought on this: an instance community can be responsible for the content that appears in its federated timeline. 

I figured that if we know the blocklists of everyone within a given instance, we can compile stats on the blocked users. There can be a threshold within an instance of when to apply a global block to posts from users or even whole instances that rise above a threshold. 

That would make the complete instance community the arbiters of what is allowed on that instance.

**Comment by wxcafe** [comment]
Okay so I'm going to answer this with regard to the UI tools, but keep in mind everything is possible if the admin edits the database manually:

- the owner of an instance can't selectively block which posts are relayed to users of their instance: the controls here are suspend an instance, which blocks all posts and follows and followings etc from that instance, silence an instance which blocks their posts from appearing in the federated timeline, and the same things with single users.

- With the default config, the owner doesn't select which instances to federate with, they decide which instances *not* to federate with, it's the same thing as suspending the instance as I talked about earlier. It's a blacklist, not a whitelist. If a user doesn't agree with that they (right now) have no way to move easily (but this is being worked on).

- If instance A doesn't federate with (i.e. suspends) instance B, instance B won't see anything from instance A afaik. If A silences B, B can still see everything from A (and users in A can still see toots from people they follow on B).

- I have no idea and it depends on the local laws so this question has no single answer.

**Comment by TheChymera** [comment]
Thank you for your answers,

@wxcafe 
> If a user doesn't agree with that they (right now) have no way to move easily (but this is being worked on).

This certainly seems like a big issue.

> If instance A doesn't federate with (i.e. suspends) instance B, instance B won't see anything from instance A afaik.

Don't you think this is a feature with more potential for abuse than use? I guess suspending an instance in such a way could only be done to:

1) limit the outreach of one's users (sure, the user *could* just go packing then, but as you point out this is ways away, and may never be super-seamless).
2) deny another instance the capacity of offering their users otherwise public content. This point in particular I can see abused for unethical competitive purposes (e.g. larger instances ganging up on/pressuring smaller ones).

@toqduj 
Community-generated censorship may be more true-to-life and less open to abuse than owner-generated censorship, but I'm not sure this feature would actually improve information exchange especially as (the way I understand your plug-in) this would be *in addition to* and not *instead of* the user having easy tools for information filtering at his disposal. I can't see this feature offering superior protection against spam, for instance. I do however see it help create a lot of echo chambers, where the all the biases or information aversities of the majority are being cumulatively enforced on the minorities.

**Comment by wxcafe** [comment]
> This certainly seems like a big issue.
look at #177, people have thought about it before you and people are also working on it instead of just saying "it's a big issue"

> Don't you think this is a feature with more potential for abuse than use?
No. Mastodon instances are like communities. If you want to join one, you should read the rules and decide if that community is where you want to be. Admins usually block only things their community don't want to see, according to the CoC. If you want to be on an instance that doesn't block anything, you can join one, there are several.

> unethical competitive purposes
there's no competition, there's literally nothing to win in this.

> where all the biases or information aversions of the majority are being cumulatively inflicted upon the minorities.
just join one of the instances that don't filter anything. People who don't want to read what you have to say and don't want you to read what they have to say are in their own right.

**Comment by TheChymera** [comment]
> People who don't want to read what you have to say and don't want you to read what they have to say are in their own right.

You're misrepresenting my point. The issue is how *anybody else except* the user may have control over his information access and output. Clearly the admin has the power to set up barriers in communications (which as you have pointed out, the user cannot easily eschew atm), but adding to that an autoenforcement of community biases (as @toqduj suggests) I believe could fragment the federation of communities and lead to loads of confusion.

**Comment by wxcafe** [comment]
The user can run their own instance and/or go to an instance that federates with everyone. Problem solved
