### ISSUE TITLE
Tiny hitbox for focusing a toot

### ISSUE THREAD

**Issue by wavebeem** [tootsuite/mastodon#1825]
Focusing a toot involves using an incredibly tiny hitbox: just the text content of the post. All the padding on the left and bottom of the toot do nothing when clicked, which is unfortunate as they're the only reliable places to try and click.

Twitter lets you click anywhere in a tweet to focus the tweet, but the specific buttons/username still perform other actions.

![image](https://cloud.githubusercontent.com/assets/176815/25061074/b7a2cb86-2162-11e7-931f-4d1d01e12ab4.png)

Pictured: the colored box is the tiny hitbox you have to click (even harder with a touchscreen --- well below even Apple's smallest recommended button size).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment]
Yep, its a problem, see #1673.

**Comment by wavebeem** [comment]
Closing as a duplicate. My bad.
