### ISSUE TITLE
Unable to create hashtag without letters

### ISSUE THREAD

**Issue by gucksaq** [tootsuite/mastodon#1827]
Attempting to create a hashtag that consists of only numbers does not resolve into a hashtag. For instance, `#33` will not become a searchable hashtag, but `#33rd` will.

* * * *

- [y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment]
This might be intentional, but I'm not sure.

**Comment by wxcafe** [comment]
Please use backquotes (\`) when talking about hashtags like `#31453` to avoid tagging other issues btw

**Comment by Gargron** [comment]
This is intentional because `#1` is a common way of writing numbers.
