### ISSUE TITLE
Toot toolbar width

### ISSUE THREAD

**Issue by wavebeem** [tootsuite/mastodon#1829]
The current toot toolbar does not extend over the full width of the toot area, which I find visually confusing.

Suggestion: span the full width and enclose the TOOT! button and character counter.

Before: 
![image](https://cloud.githubusercontent.com/assets/176815/25061564/23ccf254-216e-11e7-97c3-100ad0fcfe24.png)

After: 
![fcab8e3b68581527](https://cloud.githubusercontent.com/assets/176815/25061566/2b2e9246-216e-11e7-9b73-79f29211aadc.png)

This is just a mockup of the final product with some minor spacing issues. Any thoughts?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by hnrysmth** [comment]
Love this! Just looks tidier.

I also really like the subtle replacement of the box-shadow with a border in that mockup.
The darker buttons look nicer too, although I wonder if having them darker than the input text might draw the eye to them and away from the actual input a little. Dunno, I really love this mockup and don't wanna bog the idea down in nitpicky little thoughts like that though!

While we're in this area, what do you think of evening out the spacing just above here? It's currently a little bit lop-sided.

![screen shot 2017-04-15 at 12 14 36](https://cloud.githubusercontent.com/assets/566159/25062872/bc589250-21d5-11e7-9d6f-5b98114265b2.png)

Looks like this if you even it out to 10px on both sides.

![screen shot 2017-04-15 at 12 18 50](https://cloud.githubusercontent.com/assets/566159/25062876/ca9e12d6-21d5-11e7-9bfe-07807fd784a8.png)

Oooh, it makes me super happy to be thinking about this type of improvements.

**Comment by thomaskuntzz** [comment]
Yeah, would be great and more coherent! :slightly_smiling_face:

**Comment by wavebeem** [comment]
Cool, I'll probably get a chance to work on this one today then 😄

**Comment by elioqoshi** [comment]
Love it! Yeah agree this should be implemented

**Comment by Gargron** [comment]
I'm sorry but when it comes to design choices I side with my own taste. In particular, the toolbar as it is now is a break from every other element being a rectangle.
