### ISSUE TITLE
Main README developer documentation

### ISSUE THREAD

**Issue by wavebeem** [tootsuite/mastodon#1830]
The main README does not seem to link to https://github.com/tootsuite/documentation/blob/master/README.md which appears to be the primary documentation at this point.

Additionally, the main README has a `Development with Vagrant` section, but the primary documentation mentions that developing with Docker is not recommended, so I think we should remove that section too.

I can say that personally this confusion cost me almost four hours of time spent in confusion before I found the real docs, after which I was up and developing locally in like 10 minutes.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by hnrysmth** [comment]
Wait, I'm confused about this one 😅 

I set up my development environment with Vagrant cos of that README entry, and it didn't involve any Docker stuff. Wait, omg, I get it: the main docs refer to the Vagrant way as an "alternative"! Didn't realise until just now that I may have set my dev instance up in a non-standard way 😮

Probably worth getting this cleared up then, yeah!

**Comment by wavebeem** [comment]
Hmm, maybe I should've used vagrant then? I'm currently running Postgres and whatnot on my actual laptop (which I'd frankly rather not have to do... I don't want DB services turning on when I boot my laptop).

**Comment by wavebeem** [comment]
It make more sense if the main README to this project was more of an overview:

1. What is Mastodon
2. Link to running locally for development
3. Link to running in production
4. Contributing
5. Extra credits

Right now the README is quite large and it seems confusing to maintain docs in two places.

**Comment by ashfurrow** [comment]
Since https://github.com/tootsuite/mastodon/pull/2026 has been merged, I'm going to close this issue. @wavebeem if this hasn't been solved to your satisfaction, please re-open. Thanks!

**Comment by wavebeem** [comment]
I think we need a link to the [development guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md) in the main README still.

**Comment by ashfurrow** [comment]
Oh, I apologize, I thought GitHub gave the person who opened the issue permissions to re-open it. Are you free to open a PR adding a link to the dev guide to the readme?

**Comment by wavebeem** [comment]
Yeah I'll try and remember to submit one tomorrow.
