### ISSUE TITLE
Even Further Interoperability (Tent, Heartbeat, others?)

### ISSUE THREAD

**Issue by heyakyra** [tootsuite/mastodon#1831]
There are other protocols and projects that might be worth collaborating with, at least exploring for research purposes: 

* [Tent protocol](https://github.com/tent/tent-status/) (https://github.com/tent/tent.io/issues/4). Example: https://cupcake.is/login
* Heartbeat: https://source.ind.ie/project/heartbeat-cocoa/issues/194
* Possibly others?

**Comment by Gargron** [comment]
ActivityPub is enough. Not interested in being cross-protocol.
