### ISSUE TITLE
About more : admin not set or displayed

### ISSUE THREAD

**Issue by svanneste** [tootsuite/mastodon#1833]
I upgraded to v1.1.2 from v1.1.1 where the About admin's information weren't set. From the v1.1.2 it seems that the admin's information aren't stored or displayed on the About more page
For information : using S3 to store the assets

![ad1](https://cloud.githubusercontent.com/assets/13098940/25062448/a6692576-21cc-11e7-9561-23b8d255bfe1.png)
![ad2](https://cloud.githubusercontent.com/assets/13098940/25062449/ac07f3e0-21cc-11e7-8d88-6fb090e6aef6.png)

* * * *

- [ X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
This didn't happen on my instance. Could you please re-run the assets precompilation task and see if that fixes it?

**Comment by mjankowski** [comment]
I think there actually is an issue displaying the site contact email (PR to follow), but the account part looks fine to me.

@svanneste - do you have any sort of view or page caching in place there? If you're comfortable with the rails console, can you confirm whether the setting is present on the backend and just not getting rendered ... or if it isn't being set in the first place?

**Comment by svanneste** [comment]
Hello,
I do apologize for the delay :
@wxcafe : I reran the assets compilation as you adviced but nothing better
What I did is 
RAILS_ENV=production bundle exec rails assets:clean
RAILS_ENV=production bundle exec rails assets:precompile
RAILS_ENV=production bundle exec rails db:migrate

@mjankowski : I have absolutely no caching in place. For instance, I can see each modification of the site's description
About RAILS, I am not too confident to do it by myself (just learning slowly). But I could type some commands if you agree to provide them.

**Comment by Gargron** [comment]
You have a @ in your admin username, that's the reason for it not finding the account

**Comment by svanneste** [comment]
@Gargron : I am sorry, removing the @ did not fix
I made many trials after having it removed including restarting, recompiling the assets
and in the same time, you do have an @ in your username at mastodon.social (or perhaps did I not well understood what you meant ?)

**Comment by svanneste** [comment]
FOUND the solution : I had an accentuated letter in the admin's username (Chicor**é**e)
removing it and all was printed

**Comment by aleksandar-todorovic** [comment]
I think that this issue should be reopened.

Here's my reasoning:

* I've created an instance.
* I've filled out admin info (both contact username and the contact email address).
* I've tried using both `@user` and `@user@instance.tld`, but my profile wasn't showing up as the administrator in both of the cases.

There was no help what so ever filling out that field. Email address was shown on the first time, but the admin user wasn't. I've searched through the open issues and couldn't find anything useful. Only after I've chased down this thread via a search engine was I able to find @Gargron's comment about the `@` in front, and removing it and placing just `user` in the relevant field worked immediately.

While @svanneste's original issue got fixed, I've skimmed through 110 open issues that included "about admin" and couldn't find a more appropriate issue already opened.

**Comment by wbnns** [comment]
In case anyone stumbles across this in the future, there's currently an issue on DigitalOcean's default marketplace image of `4.0.2` where this issue is present. Anyone who sets it up is not going to see the Administration UI on first login. Thanks to the instructions here in this thread I was able to resolve the issue. In case helpful, also dumbed it down to a blog post of what needs to be done w/ steps, [in order to fix](https://log.wbnns.com/fixing-admin-missing-in-mastodon-installation-on-digitalocean/).

Thanks you all. :handshake:

**Comment by pdrd** [comment]
@wbnns here we go! Ran into the same issue, but this was a quick fix - thanks a lot.
