### ISSUE TITLE
Display emoji for each server

### ISSUE THREAD

**Issue by syui** [tootsuite/mastodon#1836]
It is a proposal for a new function.

Do you have plans? Display emoji for each server.

At the very least it would be nice to have this discussion.

- I searched or browsed the repo’s other issues to ensure this is not a duplicate.

Example : 

> app/assets/javascripts/components/emoji.jsx 

```js
.
const url      = status.get('url');
.

- return `<img draggable="false" class="emojione" alt="${alt}" src="/${unicode}.svg" />`;
+ return `<img draggable="false" class="emojione" alt="${alt}" src="${url}/${unicode}.svg" />`;
```

**Comment by tomfhowe** [comment]
What about the instance's favicon instead?

**Comment by syui** [comment]
That's a good method.

**Comment by wxcafe** [comment]
Do you mean displaying the favicon in the UI next to usernames? Or is this about something else?

**Comment by syui** [comment]
It is another thing.

However,  it is a good idea, displaying the favicon in the UI next to usernames.

For example, I tried changing the emoticon of `:white_check_mark:`.

[@syui@mstdn.syui.cf](https://mstdn.syui.cf/@syui)

### mastodon.cloud

![](https://raw.githubusercontent.com/mba-hack/images/master/mastodon_issue_emoji_change_01.png)

### mstdn.syui.cf

![](https://raw.githubusercontent.com/mba-hack/images/master/mastodon_issue_emoji_change_02.png)

You can unify the display by using the emoji of the server to which the user belongs.

It is an advantage that the server administrator decides what emoji is used.
