### ISSUE TITLE
Prevent caching of pictures/content from some/muted instances

### ISSUE THREAD

**Issue by Technowix** [tootsuite/mastodon#1844]
Hello, I'm the admin of niu.moe, and I'm not really into whole-blocking instances.
But there is legal, and illegal things are... well, illegal, but not everyone have this kind of content illegal depending of the country.
So, I wanted to know if this is possible to prevent "caching" of the content, and only "link" to them, so my instance will won't host illegal things, but users can still be free to see them.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ProgVal** [comment]
Good idea.
I'm wondering if caching other instances' content should be the default or not.

**Comment by Technowix** [comment]
Well, it actually help little instance / prevent the need to have a fat network bandwith.
But that more a legal probleme here ^-^"

**Comment by Technowix** [comment]
So, it seem that @Gargron opened a more global issue about this [here ](https://github.com/tootsuite/mastodon/issues/1847)
