### ISSUE TITLE
Content of “Getting started”

### ISSUE THREAD

**Issue by nclm** [tootsuite/mastodon#1859]
“Getting started” was seemingly originally intended as a content screen with some tips to start using Mastodon. Its contents used to read as follow:
> You can follow people if you know their username and the domain they are on by entering an e-mail-esque address into the search form.
> If the target user is on the same domain as you, just the username will work. The same rule applies to mentioning people in statuses.

After #262 (and possibly other related threads), the screen gained a new purpose, being a navigation menu as well.

By the way, the current copy reads:
> Mastodon is open source software. You can contribute or report issues on GitHub at [tootsuite/mastodon]. [Various apps are available].

Issue #1856 has for purpose to fix the navigation logic, possibly by freeing “Getting started” from its hybrid nature, by having it being a content screen only and implementing the menu as an independent element. See also #1850 about the name of “Getting started”, which can be influenced by what will be discussed here.

This thread is therefore about the textual content of  “Getting started” (not about its role or not as a menu), what should it say, link to, etc. I’ll now write a separate message with first ideas and considerations :)

**Comment by wxcafe** [comment]
see also #1883

**Comment by Gargron** [comment]
I think I like the latest iteration.
