### ISSUE TITLE
Api compatible with twitter?

### ISSUE THREAD

**Issue by mama21mama** [tootsuite/mastodon#1862]
Why not take advantage of the compatibility of gnusocial api ?. This way you would have more clients to use Mastodon

**Comment by lambadalambda** [comment]
Gargron doesn't want it. It was suggested months ago.

**Comment by Gargron** [comment]
We have feature disparities with Twitter and I do not intend to build an emulation layer. Mastodon apps are shaping up fantasticly right now.
