### ISSUE TITLE
"Show more" control link should be a button

### ISSUE THREAD

**Issue by LJWatson** [tootsuite/mastodon#1863]
The control to "Show more" content inside a toot looks like a button, but it's based on a link.
```
<a class="status__content__spoiler-link" target="_blank" rel="noopener"><span>Show more</span></a>
```

This creates a mismatch between what the control is, what it does, and the expected user interaction.

A keyboard user expects to use the space or enter keys to activate a button. Only the enter key can be used to activate a link, so attempting to activate the "Show more" button with the space key fails.

Screen readers report the "Show more" button as a "link". This sets up the expectation that activating it will fetch another resource. Typically, links fetch resources like documents or other pages, whilst buttons invoke actions like submit forms or disclose content.

There is also no information available to screen readers about the collapse/hide state of the control. The button text provides a clue, but because a link usually fetches another page, it doesn't quite do a good enough job.

There are several ways to solve this, but the one that involves the least amount of work is to use the ```<button>``` element with the `aria-describedby` attribute to communicate the state of the control.
```
<button aria-expanded="false" class="status__content__spoiler-link" rel="noopener"><span>Show more</span></button>
```

The browser will automatically provide the keyboard interaction based on the click event attached to the button. 

The `aria-expanded` attribute is set to `false` initially to indicate the control is collapsed. When someone activates the button it should be toggled to `true`, and back to `false` when the content is hidden again.

**Comment by kevinmarks** [comment]
would a <details><summary>see more</summary>&lt;details&gt;&lt;summary&gt;</details> element work better?

**Comment by LJWatson** [comment]
@kevinmarks 
We could use ```<details``` and ```<summary>``` as a starting point, but we'd need to polyfill support for IE/Edge (which doesn't support either element AFAIK). We'd also need to polyfill accessibility support for Chrome and Safari.

There might not be much in it, in terms of work we'd need to do, depending on whether we use a ```<button>``` and ```<div>``` option, or ```<details>``` and ```<summary>``` solution. We'd need to polyfill behaviour and accessibility for some combination of browsers either way.

**Comment by Gargron** [comment]
It is a button now!
