### ISSUE TITLE
Visual feedback about search actions (running, finished…)

### ISSUE THREAD

**Issue by Siltaar** [tootsuite/mastodon#1874]
Hi,

I just moved to Mastodon. I searched a lot for my followed friends (found half of them !). I missed a feedback to know:
- if a search was started, so performing (and I should wait for answers)
- if a search was finished, with maybe no answers (and it was pointless to continue waiting, could start a new search instead)

I would have not been surprised to find a spinner somewhere indicating the performing search.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
There is a loading bar at the top of the screen! (Like on youtube and github and gitlab etc)
