### ISSUE TITLE
Federated posts make it into my instance; nothing appears to make it out

### ISSUE THREAD

**Issue by jdkruzr** [tootsuite/mastodon#1877]
Here's the instance in question: https://twinja.club

I can reg a user on it, follow users on other instances and read their posts in my federated timeline on twinja.club. However, no users on other instances can @ users on it, and no users on other instances can follow users on it or receive posts from them. Someone mentioned that certificate issues can cause problems like this, but AFAICT my certs are fine. Help?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
This looks like it's a problem related to how your specific instance is configured, please post logs/more information

**Comment by jdkruzr** [comment]
Here's my access.log from nginx. What else can I get you?
[access.txt](https://github.com/tootsuite/mastodon/files/926130/access.txt)

**Comment by wxcafe** [comment]
Probably your error.log from nginx, and the mastodon-web.service logs (`journalctl -u mastodon-web`)

**Comment by jdkruzr** [comment]
This is all I have in nginx, and it was actually in error.log.1, error.log was empty:

2017/04/16 12:47:23 [crit] 1308#1308: *1079 SSL_do_handshake() failed (SSL: error:1414F178:SSL routines:tls1_set_server_sigalgs:no shared sigature algorithms error:1408A0E2:SSL routines:ssl3_get_client_hello:clienthello tlsext) while SSL handshaking, client: 208.93.152.142, server: 0.0.0.0:443

mastodon-web service log is attached.
[log.txt](https://github.com/tootsuite/mastodon/files/930657/log.txt)

**Comment by jdkruzr** [comment]
Any idea what's going on here?

**Comment by wxcafe** [comment]
looks like your ssl setup is not working, you should probably try fixing that ^^

**Comment by jdkruzr** [comment]
OK but it is though.
![image](https://cloud.githubusercontent.com/assets/618198/25393049/732c6838-29a8-11e7-8b61-c786456c6a8b.png)

**Comment by wxcafe** [comment]
> no shared signature algorithms
you probably need to allow other signature algorithms

**Comment by jdkruzr** [comment]
What other ones? What does it expect and how are they configured?

**Comment by wxcafe** [comment]
I can't tell you what other instances expect, sorry. You can post your nginx config so we can have a look at this?

**Comment by jdkruzr** [comment]
I mean, I see SSL3 in that error, and, well: http://disablessl3.com/

From my config:
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

Er. Why do we have major instances depending on connecting to other instances via SSLv3? That can't be what's going on here, can it?

**Comment by wxcafe** [comment]
right, it looks like that means the client tried to connect with SSLv3. Please contact the owner of that instance. This isn't related to mastodon itself.

**Comment by jdkruzr** [comment]
Okay, but the original problem was that I could not contact my instance from any other instance. Also, turning SSLv3 on did not help.
