### ISSUE TITLE
Not recieving toots from followed Mastodon.social users on my instance

### ISSUE THREAD

**Issue by greenmanspirit** [tootsuite/mastodon#1882]
I have been trying to track down this issue for 4 days now with no luck. Several of the users I follow on Mastodon.social have no toots showing up on my instance. I can see their toots in the local and federated timeslines on Mastodon.social so it appears that toot privacy isn't the issue. Of the 11 users I follow, toots only show up for 4 of them. I can see in the stream output (with log level silly) that the toots from those 7 users don't show up as arriving on the server. I have also unfollowed and refollowed the users and that made no difference. I have no errors in any of my logs as well.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Are you regularly running `rake mastodon:push:refresh`?

**Comment by Lertsenem** [comment]
Same problem here, at mastodon.lertsenem.com.

I noticed it with Gargron@mastodon.social and numerama@social.numerama.com, but there may be others I'm not aware of. Still it's definitely not an instance-level issue: I see some other mastodon.social accounts updates perfectly well.

- I tried to unfollow/follow back too, with no luck.
- If someone I follow boosts a toot from the account not updating, the toot appears in the account TL –but no other.

Seeing that those two specific accounts have a (very) high number of followers, I was wondering if that could be related.

I'm running 1.1.2 with docker-compose.

**Comment by greenmanspirit** [comment]
I have that set as a cron job and haven't received a notice that the cron job has failed. What change in the data can I check to verify that the job was run?

**Comment by greenmanspirit** [comment]
Thank you cron for not notifying me of errors or showing up in the logs. I have fixed my cron job and will see if it works next time a root goes out.

**Comment by greenmanspirit** [comment]
I am getting new toots.

**Comment by Lertsenem** [comment]
Yep, looks like it's working again on my end too.

**Comment by greenmanspirit** [comment]
If it is not a bother, may I ask what the different cron jobs do? I saw in the v1.3 update that we have one to clear out unverified accounts now, which is great, so I am just curious.

**Comment by wxcafe** [comment]
You can continue this discussion but I'm closing this issue since your problem has been solved.
