### ISSUE TITLE
Suggestion: Implement lists as groups

### ISSUE THREAD

**Issue by hach-que** [tootsuite/mastodon#189]
Decided to file a separate task so I don't clutter up #188 with discussions of group / list implementations.

What do you think of implementing lists as groups internally (at least spec-wise)?  Twitter lists are kind of good, but I think if we can dual purpose them to both be a thing you can follow and a thing you can block, then we sort of get to tackle #116 at the same time?

**Comment by nex3** [comment]
Does the group model make sense for (in Twitter parlance) private lists? Or would those be implemented in some node-internal way and then exposed with similar UI to public lists?

**Comment by hach-que** [comment]
Hmm, are private lists a thing? I've only ever seen public lists which is what this was more directed at. 

I think private objects and communications need more thinking through and unless the existing specs provide anything, I think we'll need to draft a spec to support those use-cases.

**Comment by nex3** [comment]
In Twitter, private lists are basically just lists that only you can see—or, alternately, different timelines visible to the same user. Since they inherently aren't shared, I don't think they're likely to need non-local support.

**Comment by grugq** [comment]
Private lists are basically like separate timelines, and they are extremely useful for organising content. On Twitter I have a number of lists for different subjects which, if they were mixed into the main timeline, would make for too much noise. 

Having the ability to keep a few different timelines of different content in distinct categories is pretty critical (for me, at least.) So I would very much need this to switch.

**Comment by daturkel** [comment]
I have to agree that Twitter lists have great functionality, especially for TweetDeck-style multi column interfaces. Would love to see something similar.

**Comment by spectrumgomas** [comment]
private lists for the win!

**Comment by wxcafe** [comment]
Lists have been implemented, and not as groups. Closing.
