### ISSUE TITLE
Display all instances a toot has federated to

### ISSUE THREAD

**Issue by NthTensor** [tootsuite/mastodon#1896]
Feature Request: When a given toot is selected, display a list of the instances that the toot has federated to. 

This change could help clarify the functioning of the federation to new users, allow users to judge the spread of their toots, and make it easer to debug issues with instances not federating properly.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by lambadalambda** [comment]
That's only possible for the initial fan-out, after that a status can be repeated across all the fediverse without the initial instance noticing.

**Comment by Gargron** [comment]
>That's only possible for the initial fan-out, after that a status can be repeated across all the fediverse without the initial instance noticing.

On one hand, this. Of course, normally you still get a Salmon slap when your status gets shared by others, even beyond your own followers, although this is not guaranteed. However, I see a different problem here: storing such a huge list for every status will explode disk space usage.

For example, mastodon.social is origin to 2.6 mio statuses. Not every account is followed by every instance, but 2,6k instances are *known* so are potentially targets. If you multiply those two numbers you get a lot of digits.

So, while this would be *cool*, I don't consider this possible.
