### ISSUE TITLE
Follow conversation / notifications for all toot replies (incl. users I don't follow)

### ISSUE THREAD

**Issue by karelz** [tootsuite/mastodon#1899]
I see a toot I like, I would like to get notifications for all its replies (incl. people I don't follow).

It is useful to follow an interesting topic discussion on multiple forks, when I am not involved at all or involved in just one of the toot forks.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
  * For about 20 mins - if I missed a dupe, I apologize deeply

**Comment by ZiiX** [comment]
This feature is widely requested so people can enjoy & follow a public conversation. ...especially with multi-instance account people. I'm for it!

**Comment by mcrosson** [comment]
I'm with @ZiiX . This would be a really useful feature to have. There are a number of users that post great questions/ask for feedback and I'd like to be able to track the responses without a "/sub" post or similar. Gaming the response system with a generally useless reply to get notifications feels a little "dirty" to me.

My short term fix was to keep multiple tabs on my computer open to track things but now that I use my phone... I can't keep things in sync and multiple tabs only scales so far in the end.

**Comment by Gargron** [comment]
This is a thing since 1.6.0 because of ActivityPub, closing
