### ISSUE TITLE
Change instance's domain

### ISSUE THREAD

**Issue by maop** [tootsuite/mastodon#1902]
Hello,

I'm not sure where to put this question i hope this is ok, if not feel free to delete this issue.

I opened an instance for me, then my friends wanted to try it, then other people started to sign in, which is great, it seems its mainly people from my country which are new to mastodon, so i want to change my instance's subdomain to a new domain that reflects this. But i'm unsure on what needs to be changed in Mastodon Conf or DB, should i just change LOCAL_DOMAIN and that's it ? what about local/remote followers? should i keep the old subdomain AND the new domain pointing to the instance? or setup 301 redirections in the old subdomain to the new domain? what is the best approach for switching domains? should i just start from zero with the new domain?

Thank you for your time.

**Comment by Technowix** [comment]
Well, it's like changing email adress, you will lost all you followers / mess up a bit the federation

**Comment by ineffyble** [comment]
This would be a great thing to properly document, but I'm not sure what the best advice is, so tagging @Gargron

**Comment by JantsoP** [comment]
You can set the DNS records to redirect to the new domain name and make your web-server to listen the new domain. And yes, the LOCAL_DOMAIN needs to be changes as well.

**Comment by mig5** [comment]
I had a question that is sort of similar to this. I note that when I delete an instance, remote users still show that they are 'following' me on my totally-gone (not even DNS-resolvable) instance.

Does this cruft stay in their profile/instance's db meta forever?

If I were to re-provision my instance with the same name, would they automatically start to see my new posts because they 'still' follow me, or would this create havoc in the federation? I guess the question is whether instances are referenced only by domain or by some other UUID.

**Comment by Gargron** [comment]
The domain is the main reference.

You should ideally not change your domain name, because if you do, you and all your users will appear as new, different people. And yeah, the old references will basically hang around forever.

**Comment by maop** [comment]
Thanks @Gargron ... so what i'm reading is: just start from zero at the new domain ?
As for the old domain? should i just deleted it or apply 301 to the new instance? (i.e. mastodon.old.tld/@maop  -> new.tld/@maop ) 
I wish to make the less possible mess :P 

thank you all for your time, again!

**Comment by Gargron** [comment]
Sorry I forgot to reply. You may want to redirect if you expect people to use those links, but protocol-wise you can just leave it deleted.

**Comment by QuadPiece** [comment]
Would it be possible to reopen this issue now that `ALTERNATE_DOMAINS` is a valid environment variable.

This should allow domain migrations to be performed by changing `LOCAL_DOMAIN` and leaving the old domain in `ALTERNATE_DOMAINS`. However I am curious as to how the rest of the fediverse would handle this. There's also no documents saying if the alternate domains should simply point at mastodon alongside the existing ones, or if the web server should redirect them to the new domain.

1. Would domains get updated in connected servers' databases or would the old domain stay indefinitely in their DBs
2. If not, how long would the old domain need to stay
3. What issues could arise from attempting such a migration
4. If it's still not possible to perform a migration using this new env variable, why not?
