### ISSUE TITLE
Configure status.mastodon.social as an uptime page

### ISSUE THREAD

**Issue by hach-que** [tootsuite/mastodon#191]
Providing an uptime page will give users something to check rather than mashing F5 in their browser at servers which are already overloaded.

**Comment by hach-que** [comment]
Current temporary one set up by me is available at https://stats.uptimerobot.com/0RQPNfJ95

**Comment by mjankowski** [comment]
I'm going to close this on the assumption that this site is sufficient - https://instances.mastodon.xyz/

Please re-open if you wanted something more.

**Comment by LWFlouisa** [comment]
Is there actually a page to see server uptime? There are times when the site is down, even though I'm obviously not banned.
