### ISSUE TITLE
Photo cannot be viewed

### ISSUE THREAD

**Issue by azbulutlu** [tootsuite/mastodon#1912]
https://social.tchncs.de/@lrshdl/810702
the preview image is fine, when clicked, it shows a bunch of text. The image doesn't show at all on dash (only a link)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Technowix** [comment]
I have to say that the app used is Amaroq, so that might be a vector of issue :)

**Comment by wxcafe** [comment]
Was the image uploaded with Amaroq too? It looks like the image's mime type isn't detected correctly and it's interpreted as a text file instead

**Comment by fwenzel** [comment]
I downloaded the raw file (can confirm, shows up as text), and:
```
$ file 5feeeb70178d50c0                   
5feeeb70178d50c0: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, baseline, precision 8, 1279x1280, frames 3
```
So the file itself does not appear broken, per se.

**Comment by rhaamo** [comment]
Seems more an issue from the admin web server than Mastodon:
```
curl -I https://social.tchncs.de/system/media_attachments/files/000/052/214/original/5feeeb70178d50c0\?1492339319
HTTP/1.1 200 OK
Date: Sun, 16 Apr 2017 19:18:32 GMT
Content-Type: text/plain
```
The /system/ directory, in the default nginx config should be served under "root /path/to/mastodon/public" and not proxyfied by Mastodon.

**Comment by tchncs** [comment]
Hi!
I indeed had my root somewhere else - but it wasn't important to do so, so i just set it to /public.

```
HTTP/1.1 200 OK
Date: Sun, 16 Apr 2017 19:32:02 GMT
Content-Type: text/plain
Content-Length: 371267
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Sun, 16 Apr 2017 10:42:00 GMT
Strict-Transport-Security: max-age=15768000
```

**Comment by tchncs** [comment]
Well... not sure about this... i wiped my firefox's cache (nightly is used) and it stays.
Chromium works.

![2017-04-16-214547_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/25073827/2e978b90-22ef-11e7-97ac-aa3b0d7ee0e0.jpg)

**Comment by rhaamo** [comment]
Strange issue, the "don't works" one doesn't have a file extension.
I just tried with a png and jpeg on my instance (v1.1.2), with and without the extension and it... works.
I don't really know what's going on here.

**Comment by tchncs** [comment]
I [can confirm](https://social.tchncs.de/@milan/830705) that it happens as soon as the extension is missing on my instance.

**Comment by rhaamo** [comment]
I just searched and found that Nginx use a table lookup for extensions/Content-Type (/etc/nginx/mime.types).
Here we have a file without extension, so for Nginx it means "I don't know what is it so I fallback to text/plain" without doing any "in-depth" mime-type searching (like what is doing 'file' using some 'magic markers').
I don't know if there is another issue opened for this but it could be "fixed" by mastodon by rewriting the file with the extension of auto-detected mime-type.

**Comment by tchncs** [comment]
> by rewriting the file with the extension of auto-detected mime-type.

I would like it *but* it would leave the question open why it works on your instance...

**Comment by rhaamo** [comment]
> why it works on your instance...

I remembered I use S3/minio, and minio is using the "real" mime-type of the files to send a correct Content-Type, instead of just relying on the extension.

**Comment by AxelTerizaki** [comment]
I would like to add the same thing happens with an Apache configuration instead of nginx.
