### ISSUE TITLE
Vagrant : Ruby version is incorrectly read from .ruby-version

### ISSUE THREAD

**Issue by Naouak** [tootsuite/mastodon#1940]
`.ruby-version` contains a line return that is interpreted in vagrant installation. The installation of ruby fail on a new vagrant box on commit 99226aba9391535a20d3cc6dba0f45e5792c73d4.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ineffyble** [comment]
I can't see a line return in `.ruby-version`, either on current master or 99226ab

**Comment by ineffyble** [comment]
I've done a `vagrant up` on latest master, and it all appears to work. Can you do a fresh git clone/reset and try again?

```
==> default: Cloning into '/home/vagrant/.rbenv'...
==> default: make: Entering directory `/home/vagrant/.rbenv/src'
==> default: gcc -fPIC     -c -o realpath.o realpath.c
==> default: gcc -shared -Wl,-soname,../libexec/rbenv-realpath.dylib  -o ../libexec/rbenv-realpath.dylib realpath.o
==> default: make: Leaving directory `/home/vagrant/.rbenv/src'
==> default: Cloning into '/home/vagrant/.rbenv/plugins/ruby-build'...
==> default: Compiling Ruby 2.4.1: warning, this takes a while!!!
==> default: Downloading ruby-2.4.1.tar.bz2...
==> default: -> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.bz2
==> default: Installing ruby-2.4.1...```

**Comment by Naouak** [comment]
I get this at the first use of .ruby-version :

    ==> default: : warning, this takes a while!!!

**Comment by ineffyble** [comment]
Does the local `.ruby-version` have a newline when you inspect it directly? Does a `git diff` show any changes?

**Comment by Naouak** [comment]
I have a new line at the end when I checkout the file. Current master has it too (github remove it from display but states that there is 2 lines).

**Comment by Naouak** [comment]
BTW, here is the full log:

```
==> default: Cloning into '/home/vagrant/.rbenv/plugins/ruby-build'...
: warning, this takes a while!!!
==> default: ruby-build: definition not found: 2.4.1
==> default: See all available versions with `rbenv install --list'.
==> default: If the version you need is missing, try upgrading ruby-build
==> default: :
==> default:   cd /home/vagrant/.rbenv/plugins/ruby-build && git pull && cd -
' not installed
==> default: ERROR:  While executing gem ... (Errno::EACCES)
==> default:     Permission denied - /var/lib/gems
==> default: /tmp/vagrant-shell: line 43: bundle: command not found
```

**Comment by Naouak** [comment]
Changing the script to this in the Vagrant file do the trick: 
````
read RUBY_VERSION < .ruby-version
echo "Compiling Ruby $RUBY_VERSION: warning, this takes a while!!!"
rbenv install $RUBY_VERSION
rbenv global $RUBY_VERSION
````
