### ISSUE TITLE
Regex for Local and Federated timelines

### ISSUE THREAD

**Issue by OberstKrueger** [tootsuite/mastodon#1944]
Mastodon already has regex support on the Home timeline, but the ability is not there for Local and Federated timelines. This is something that could bring both timelines under a bit of control, especially on larger instances where content on the feeds can move quickly.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
This is resolved.
