### ISSUE TITLE
Language dialects and should we separate them

### ISSUE THREAD

**Issue by hugogameiro** [tootsuite/mastodon#1946]
I noticed that the [translation](https://github.com/tootsuite/documentation/blob/master/Contributing-to-Mastodon/Translating.md) documentation indicates we should use the language’s standard two-letters code ISO 639-1.

I think that language dialects are important. For example, the PR [#1917](https://github.com/tootsuite/mastodon/pull/1917) submitted to improve the Portuguese translation is great but it uses Brazilian Portuguese and most of the other translations are in European Portuguese.

This may not sound like a problem for non Portuguese speakers but both languages are very different and it gives a mixed bag with working on the translation. Yes we can mostly understand the translation, both Portuguese and Brazilians will understand it but it will not feel natural for any of us.

I don't want to complicate things and want to help out as much as I can. I easily can make a European Portuguese translation for my instance and solve this issue for me. Just wondering if this is something that could be improved. I offer to help with European Portuguese translation and can even submit a PR to separate the pt-PT and pt-BR but wanted input before working on or submitting the PR.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jack1243star** [comment]
See #1759 and #1794 for example. The Chinese variants now have their own language file, I suppose you can do the same with Portuguese?

**Comment by hishamhm** [comment]
The languages are somewhat different but they are mutually intelligible: we have a single Wikipedia for European and Brazilian Portuguese and we live with it. Having said that, lots of software have separate translations for European and Brazilian Portuguese (like they have for American and UK English), so as a pt_BR speaker I would be fine either way.

**Comment by wxcafe** [comment]
Please do a PR if you want to 👍

**Comment by hugogameiro** [comment]
PR to solve this pushed and merged to master [1966](https://github.com/tootsuite/mastodon/pull/1966)
