### ISSUE TITLE
GET /.well-known/webfinger no longer provides XML when given Accept: application/xrd+xml

### ISSUE THREAD

**Issue by yipdw** [tootsuite/mastodon#1983]
When issuing a request for `application+xrd/xml` to `GET /.well-known/webfinger` on a `v1.2` Mastodon instance, one receives JSON instead:

```
$ curl -v -H 'Accept: application/xrd+xml' 'https://sdfn-01.ninjawedding.org/.well-known/webfinger?resource=acct:ninjawedding@sdfn-01.ninjawedding.org'
< HTTP/1.1 200 OK
< Date: Mon, 17 Apr 2017 06:51:28 GMT
< Content-Type: application/jrd+json; charset=utf-8
[...headers elided...]
{"subject":"acct:ninjawedding@sdfn-01.ninjawedding.org","aliases":["https://sdfn-01.ninjawedding.org/@ninjawedding"],"links":[{"rel":
[...body elided...]
```

However, I'd expect XML.  There are some Mastodon instances (presumably running older code) that do this.  For example, as of 2017-04-17 @ 06:48:00 UTC:
```
$ curl -v -H 'Accept: application/xrd+xml' 'https://mastodon.k0rko.fr/.well-known/webfinger?resource=acct:Korko@mastodon.k0rko.fr'
< HTTP/1.1 200 OK
< Date: Mon, 17 Apr 2017 06:50:39 GMT
< Content-Type: application/xrd+xml; charset=utf-8
[...headers elided...]
<?xml version="1.0"?>
<XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
  <Subject>acct:Korko@mastodon.k0rko.fr</Subject>
  <Alias>https://mastodon.k0rko.fr/@Korko</Alias>
[...body elided...]
```

This, however, _does_ give you XML on a `v1.2` instance:

```
$ curl -v 'https://sdfn-01.ninjawedding.org/.well-known/webfinger.xml?resource=acct:ninjawedding@sdfn-01.ninjawedding.org'
< HTTP/1.1 200 OK
< Date: Mon, 17 Apr 2017 06:51:52 GMT
< Content-Type: application/xrd+xml; charset=utf-8
[...headers elided...]
<?xml version="1.0"?>
<XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
  <Subject>acct:ninjawedding@sdfn-01.ninjawedding.org</Subject>
  <Alias>https://sdfn-01.ninjawedding.org/@ninjawedding</Alias>
[...body elided...]
```

It is possible that the `format` default route parameter (introduced in b352a8e5d4f3dba4b923a2a21dc9ae5343e7e8e4) doesn't have quite the same effect that the `set_default_format_json` `before_action` did.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yipdw** [comment]
To allay any suspicion that I have modified my instance (a fair suspicion), here's a test case for `mastodon.social`:

```
$ curl -v -H 'Accept: application/xrd+xml' 'https://mastodon.social/.well-known/webfinger?resource=acct:ninjawedding@mastodon.social'
< HTTP/1.1 200 OK
< Date: Mon, 17 Apr 2017 06:58:39 GMT
< Content-Type: application/jrd+json; charset=utf-8
```

**Comment by mjankowski** [comment]
Yup, looks like regression the spec didn't catch there. Will update soon.

**Comment by yipdw** [comment]
Thanks for the quick turnaround!
