### ISSUE TITLE
Timezone of single toot display

### ISSUE THREAD

**Issue by yookoala** [tootsuite/mastodon#1990]
Example,

* https://mastodon.hk/@inmediahk/23687

The status is published at 17th April, 2017 09:13 UTC. Which is 17th April, 2017 17:13 HKT. The time displayed in timeline is (left) following the browser's timezone, while the single toot display (right) is showing UTC.

![c94852d72ba8ef66](https://cloud.githubusercontent.com/assets/91274/25086638/9bf227de-239b-11e7-86ff-79ed29404290.png) ![1ca4c553b3e5309a](https://cloud.githubusercontent.com/assets/91274/25086639/9bf39722-239b-11e7-8a30-7d64ab5a4f3a.png)

The behaviour is inconsistent. It would be easier for visitor to understand if either,

1. The time always follow the user's browser (with JS rewrite the "time" on load?); or
2. The time in single toot display also show a timezone string; or
3. Have an administrator option to set a default for the instance

Discovered by @chainsawriot in [this post](https://mastodon.hk/@chainsawriot/23728)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
We should probably publish utc times to pages, and let client js override with local/browser tz.
