### ISSUE TITLE
Trim whitespaces (at end) of toots

### ISSUE THREAD

**Issue by Sp3r4z** [tootsuite/mastodon#1992]
Some users seem to find 500 space toots very funny. Can Mastodon trim/correct whitespaces at end of toots? Maybe just limit to 5 successive spaces even into toots (not just end).

**Comment by mjankowski** [comment]
Putting aside whether we'd want to do this or not (I can see an argument in favor of preserving as close to possible whatever content someone supplied), this would have an easy work around: put dozens of newlines and spaces, and then end the post with a single `.` or something.

**Comment by kayleej** [comment]
How about hiding statuses over a certain length/with many newlines behind "show more" after a predefined cutoff while in the timeline? Wouldn't be a silver bullet but it doesn't mangle the users input and would mitigate the annoyance to a degree.

**Comment by docjkl** [comment]
I am not sure this is an issue anymore;  superfluous whitespace is removed and consecutive empty CRLF are treated as one in a823509b99eb428b1f68ed89594b88f48546253a
