### ISSUE TITLE
Show federated instances list in the admin interface

### ISSUE THREAD

**Issue by pixocode** [tootsuite/mastodon#1996]
And from this list, to can block an instance

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
This would be a unique list of every domain the instance had interacted with?

**Comment by Gargron** [comment]
Sounds like it. Distinct select on account domains, maybe with a grouped row count. Could do fancy stuff like percent of suspended accounts from domain.. Or percent of accounts blocked at least once..

**Comment by pixocode** [comment]
Yes, this would make it possible to know the instances that publish in the federated timelines.
(If I understood correctly, it is the list of instances whose users of the instance follow at least one of the users of the other instances)

(sorry for my english ^^")

**Comment by pixocode** [comment]
We could also see the number of instance users ? (To avoid displaying too big instances in the federated timeline by example)
