### ISSUE TITLE
fetch link card bot has default user agent

### ISSUE THREAD

**Issue by wilfrem** [tootsuite/mastodon#1998]
I tested the bahavior of fetch link bot and what kind of User-Agent will be sent.
As a result, the User-Agent is `http.rb/[version number]`.
Is it by design? I think it's not good.

I think put those information to User-Agent better.
* the name mastodon.
* it's bot.
* instance name
* instance supervisor's email
* and other

**Comment by Gargron** [comment]
:+1:

**Comment by Gargron** [comment]
Fixed by #2073
