### ISSUE TITLE
no <title> in the atom feed if display name not set

### ISSUE THREAD

**Issue by benasse** [tootsuite/mastodon#1999]
If the display name of a user is not set there is no <title> in the atom feed

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ericblade** [comment]
I believe this was fixed in v1.2, https://github.com/tootsuite/mastodon/pull/1875 .. are you able to confirm?

**Comment by benasse** [comment]
You are right, it works on mastodon.social
