### ISSUE TITLE
post privacy inheritance to self should act differently

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#2005]
a while back, post privacy inheritance was created for the purpose of making privacy more easy to handle for everyone involved. a certain flaw in this system comes if someone wants to make a public thread (replying to themself)

say i have my privacy at unlisted, and i post to public timelines. since i chose that privacy, it should inherit this privacy level when replying to myself. this however, does not happen, due to the lower privacy priority of my default posting level.

should be a really easy fix.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] NOT A BUG RE This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
:+1:
