### ISSUE TITLE
Is it illegal to use Google's services? (Is user tracking acceptable in mastodon culture?)

### ISSUE THREAD

**Issue by furoshiki** [tootsuite/mastodon#2007]
I'm at pawoo.net.

Improving mastodon instance, we need to use the advanced functions via SaaS. Google also provides many services which make the web safer, faster or more convenient, but their service might have **user tracking tools**.

What is violating the rules? How about Google reCAPTCHA. We do not want to know user behavior, just want to use the features provided by Google.

https://www.google.com/recaptcha/intro/invisible.html

<img width="708" alt="2017-04-17 23 26 02" src="https://cloud.githubusercontent.com/assets/4110951/25091677/572f715e-23c5-11e7-87be-054cf33b87d1.png">

If user tracking is acceptable in mastodon culture. Nothing to discuss here.

**Comment by patf** [comment]
I think there are two questions here:

The first question: Can you use Mastodon (the software) while doing something that goes against its stated goals?

IANAL, but I don't see why not. The only relevant document here is the AGPL license, and there's nothing in the AGPL that forces those particular values on you. It just forces you to release the exact code you're running on your server to your users.

There's an interesting tangent here: Whether using something like Google Analytics (which presumably is not AGPL-compatible) would be considered a modified version of Mastodon. If that's the case, I imagine you could only use AGPL-compatible code. I don't have an answer to this. It might depend on how it is included.

The second question: What policies will other instances apply to instances that don't share the same values on this topic - will they stop federating with them? Ultimately, that's going to be up to instance admins, and it's probably too early to tell how that will go. There's a good chance shared block lists (much like DNS blacklists) will be part of the solution eventually, but whether those will be relevant for this topic remains to be seen. Either way, I think the role for Mastodon (the software) here would be to build the best tooling possible for that purpose, but not to *enforce* policy (though it can certainly help shape it).

**Comment by krainboltgreene** [comment]
You're welcome to use any changes you make to your own instance. Mastodon's core repository will never ship with user tracking agents.

**Comment by Gargron** [comment]
Just to confirm: you can use whatever you want on your instance. We simply don't include that in the main project

**Comment by furoshiki** [comment]
@patf Thank you for your reply.

> The only relevant document here is the AGPL license

I'd like know Mastodon community policy, not talking about license policy.

Actually, "AGPL" can not limit our operation policy, but mastodon is not a library/framework. Mastodon is one social network, which is joined by all of instances. We would like to understand mastodon's ideals and do the best operation with everyone.

@krainboltgreene @Gargron

> You're welcome to use any changes you make to your own instance. Mastodon's core repository will never ship with user tracking agents.

> Just to confirm: you can use whatever you want on your instance. We simply don't include that in the main project

OK. I can understand mastodon operation policy. Although we make improvements that are valuable only to us, we will continue to make the greatest contribution to this repository as well.
