### ISSUE TITLE
Would you like to add an icon to the TOOT button?

### ISSUE THREAD

**Issue by usagi-f** [tootsuite/mastodon#2009]
https://github.com/tootsuite/mastodon/issues/962

Is there a little argument about the icon that imaged TOOT on this Issue?

I thought that it is desirable that the TOOT button is actually given an icon.

![image](https://cloud.githubusercontent.com/assets/9045135/25092182/7c1d7734-23c7-11e7-92c9-5531972a35b6.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
I don't believe an icon there is necessary.
