### ISSUE TITLE
Account takeout/archive download

### ISSUE THREAD

**Issue by hikari-no-yume** [tootsuite/mastodon#201]
An important feature of Twitter is that you can request to download an archive of all your tweets. This means if you delete your account (or delete much of its history) you can still retain a local copy. It also is useful for various kinds of local data-mining without overloading the server with API calls. And it gives you an important backup of your history in case the instance ever goes down.

I don't know if GNU Social or its associated protocols have any system for this yet. If not, I imagine it could be as simple as a ZIP file containing an atom feed of everything that user's posted. Ideally this would (optionally?) include media too (which Twitter doesn't do).

Twitter includes a simple static web page to help you browse your archive, but it's slow and spartan, and not a basic requirement of this feature, more a nice-to-have. If it's an atom feed, any atom feed viewer can read it, after all. So long as it's machine-readable, someone else can worry about this problem.

This is related to https://github.com/Gargron/mastodon/issues/177 and https://github.com/Gargron/mastodon/issues/109.

**Comment by nex3** [comment]
This is especially important in a federated system, since the long-term reliability of individual nodes is lower.

**Comment by rory** [comment]
EU data protection law requires that you have to give people a copy of all personal data you hold on someone if they ask. Maybe toots would count? Possibly. So someone can cause a headache for an admin by making this legal request...

**Comment by FlyMyPG** [comment]
For the impatient, [I wrote a Python script to do this](https://gist.github.com/FlyMyPG/2e9d4532453182ada0da78e74980193b).

**Comment by aka-rin** [comment]
@FlyMyPG Thanks for your effort. [I wrote a Python script too](https://gist.github.com/aka-rin/5f0e6b90836cb998c11b9178d7d90bb5), using Mastodon API V1.

**Comment by FlyMyPG** [comment]
I initially used a wrapper for the Mastodon API, but I could only get the lat 400 toots.  Has that changed?

Also, I wanted to use an auth-free public interface, to make it easy to get caught up on the toots of folks you (may) want to follow.

**Comment by Gargron** [comment]
@FlyMyPG The home timeline only stores references to at most 400 toots, but you should be using /api/v1/accounts/:id/statuses to backup a user's toots anyway.

**Comment by aka-rin** [comment]
@FlyMyPG I have tested my script with pixiv@pawoo.net and get 2600+ toots backup, so it is not a problem of Mastodon API.
