### ISSUE TITLE
TypeError: Cannot convert undefined or null to object in mastodon.jsx

### ISSUE THREAD

**Issue by kodnaplakal** [tootsuite/mastodon#2010]
Before I started fresh mastodon I'll get this errors
![2017-04-17 16 22 06](https://cloud.githubusercontent.com/assets/24268143/25092607/24f9b79a-2397-11e7-8e78-c774a96640d9.png)

**Comment by kodnaplakal** [comment]
Fix in PR #2011

**Comment by hakai-no-kami** [comment]
I updated my instance about  an hour ago, and got the same error
I applied the patch, but it wont fix.(still a blank page)
Do I need to `docker-compose run --rm web rails assets:precompile` after the patch?

**Comment by hugogameiro** [comment]
I got it working with this fix and did:
`RAILS_ENV=production bundle exec rails assets:clean
RAILS_ENV=production bundle exec rails assets:precompile
RAILS_ENV=production bundle exec rails db:migrate`

**Comment by hakai-no-kami** [comment]
Thx!!
Fixed!

**Comment by krainboltgreene** [comment]
The error is related to this code: https://github.com/tootsuite/mastodon/blob/6685106daace4c78785a3c3caacc8ed952d669b3/app/assets/javascripts/components/containers/mastodon.jsx#L73-L91
