### ISSUE TITLE
Emojis not displaying on foreign toots

### ISSUE THREAD

**Issue by Angristan** [tootsuite/mastodon#2016]
Example toot : https://mstdn.io/@angristan/476554

From my instance : 
![screenshot_17-04-2017_b hkwgl8p_](https://cloud.githubusercontent.com/assets/11699655/25094677/9a7de7d8-2398-11e7-9352-82f10ab56f2b.png)

From his : 
![screenshot_17-04-2017_b lpmjvno9](https://cloud.githubusercontent.com/assets/11699655/25094691/a034fd6a-2398-11e7-9c02-c2794086a33e.png)

And the emoji does not even show up in the HTML : 
![screenshot_17-04-2017_b zh7v448o](https://cloud.githubusercontent.com/assets/11699655/25094730/ca7b2e96-2398-11e7-8517-d8d765beea1b.png)

It's not a problem with CSP, and it happens since 1.2.

As you can see in my example toot, it happens with some instances, but not all.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tchncs** [comment]
Interesting, on my experience with social.tchncs.de -> mastodon.social it is not displayed in the stream but [on the public url](https://social.tchncs.de/users/milan/updates/50277)

**Comment by Creased** [comment]
As mentioned above, emojis aren't in the HTML content, I've also checked and it's not even returned by the API (see [screenshot][1]):

```bash
export USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0" TOKEN=YOUR_TOKEN
curl -s -X 'GET' \
    -H "User-Agent: ${USER_AGENT}" \
    -H "Authorization: Bearer ${TOKEN}" \
    --url 'https://mastodon.xyz/api/v1/statuses/900842' | python -c "import sys, json; print(json.dumps(json.load(sys.stdin), indent=4))"
```

![Emojis API response](https://cloud.githubusercontent.com/assets/8843222/25096733/cfeb5e7e-23a1-11e7-9095-081413c33d56.png)

[1]: https://cloud.githubusercontent.com/assets/8843222/25096733/cfeb5e7e-23a1-11e7-9095-081413c33d56.png "Emojis API response"

**Comment by nightpool** [comment]
I *think* this might have been solved by https://github.com/tootsuite/mastodon/pull/1988—can someone confirm?

**Comment by Wonderfall** [comment]
I'm on latest code. You can try here : https://social.targaryen.house/@wonderfall/809705
And switch between instances.

**Comment by Gargron** [comment]
Should be fixed now.
