### ISSUE TITLE
Blank page when logging in on mobile browsers

### ISSUE THREAD

**Issue by MeachamusPrime** [tootsuite/mastodon#2024]
Blank background colored page when displaying in mobile browsers (Chrome, Brave, Firefox) on updated Nexus 6P. Works in Firefox only with "Request desktop site" checked. Other browsers do not work with desktop site requested. 

(Pretty cool otherwise.)
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by krainboltgreene** [comment]
Possibly related to: #2010

**Comment by Gargron** [comment]
I don't know how to quantify this without more details. Closing.
