### ISSUE TITLE
Remote follow does not accept @user@instance

### ISSUE THREAD

**Issue by nbraud** [tootsuite/mastodon#2027]
The “remote follow” dialog doesn't accept the `@user@instance.domain` syntax that Mastodon displays everywhere, which is mildly confusing at first.

I guess I would be very easy to make it strip the initial `@` (assuming valid usernames cannot start with `@`).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by DanielGilbert** [comment]
Btw, this must have been introduced shortly, as it worked before.

**Comment by wakest** [comment]
just tried following a user on mstdn.jp from mastodon.social using my @user@instance.domain and it worked just fine. @nbraud what instance to what instance did you try from?

**Comment by ashfurrow** [comment]
Just following up on this, @nbraud would you be able to provide more details about which instance you tried from?
