### ISSUE TITLE
Direct messages are undeletable

### ISSUE THREAD

**Issue by no-boot-device** [tootsuite/mastodon#2031]
How 2 reproduce:
1. Direct message a user on another instance
2. Delete the direct message on your instance
3. The direct message will not be deleted on the other instance

I haven't checked, but it also might not delete locally for other users too due to some conversations I've had.
This seems like it miiight be something that should be high priority.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
This is *by design* and doesn't only apply to direct messages but to any toot that a user on another instance has interacted with (faved, boosted, replied to, ...). This is because once the message has federated, the remote instance has a copy of it and you're only deleting the local copy.

**Comment by Gargron** [comment]
@wxcafe isn't *quite* correct. Deletion sends out a second message, asking to delete the first one. If there's a network error or delay, it may lead to a message not being deleted on a different server. This is not unique to DMs, since DMs are just a type of toot.

**Comment by wxcafe** [comment]
hmm. I tried this for all types of toots and none of them got deleted on the remote, so this might be a bug after all
