### ISSUE TITLE
OStatus user URI verification/disambiguation

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#2032]
Currently, Mastodon will happily accept multiple remote accounts with the same account URI, which is ambiguous when interacting with remote instances: users are mentioned by their URI, and salmon requests are verified against the known public-key of a user based on its URI.

I might be wrong, but it seems OStatus does not require URIs to be “authenticated” in any way, so multiple remote users could use the same URI with no way to chose which one is entitled to use it. It could be used on a first come, first served basis, but then, different instances might have different “users” associated to the same URI, leading to “incompatible” views of the same toots, and it would block out salmon requests of one of the users.

This could have privacy implications, but I'm not completely sure which. I guess private messages should be fine, as users are locally identified by their webfinger handle, and not by their URI.

To be honest, I have a hard time believing there is such a flaw in OStatus, so I could be entirely wrong, and I'd be happy to be proven so.

I can only see one workaround, that is, only accepting the URIs that are either:
- URLs linking back to an atom feed with either:
  - an author/email tag corresponding to the initial webfinger query
  - if no author/email tag, an author/name tag corresponding to the username part of the webfinger acct, hosted at a domain corresponding to the domain part of the webfinger acct (required for quitter.no)
- webfinger “acct:” URIs that correspond to the initial query

**Comment by ThibG** [comment]
I had a chat with MMN-o in the #mastodon IRC channel about this issue.
According to MMN-o, OStatus indeed does not specify how to verify URIs, but URIs are (obviously) supposed to be unique nonetheless. Therefore, the issue of handling collisions remain, and while I stand by my proposal (that I implemented in #2172), MMN-o has some objections and alternative suggestions:
1. Verification should not depend on a central entity (even DNS, used for webfinger).
2. URIs could be arbitrary strings with no attached meaning, and we should not prevent that
3. Collisions should be handled manually by instance admins, or maybe using things like FOAF

My opinion on this is:
1. We already trust DNS for webfinger queries, as Mastodon's primary identifiers are webfinget acct: URIs and not author/actor URIs
2. I agree with that, but in practice, I have not seen any OStatus implementation using an URI that is not a profile URL
3. I think it is significantly more complicated and does not scale well. Furthermore, this would mean that the decision of which user is considered legitimate would be local to each instance, which is not desirable in my opinion.

**Comment by Gargron** [comment]
I think this is no longer relevant as ActivityPub URIs must be verifiable via HTTP/DNS.
