### ISSUE TITLE
Mastodon bridge not working at all

### ISSUE THREAD

**Issue by flopreynat** [tootsuite/mastodon#2036]
Mastodon bridge gives following error message after logging onto both services and clicking on 'check for friends':

"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

Landing page: https://mastodon-bridge.herokuapp.com/friends

No error in the console.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Wrong repository, sorry.

**Comment by flopreynat** [comment]
my bad.

**Comment by Cassolotl** [comment]
Looks like this is the right place, for folks finding this thread in the future: https://github.com/tootsuite/mastodon-bridge/issues/14
