### ISSUE TITLE
Assets are HUGE.

### ISSUE THREAD

**Issue by denysvitali** [tootsuite/mastodon#2040]
I was wondering... is there a reason on why the assets folder (compiled) is 103M, and why the js files are 9MB?

![screenshot from 2017-04-17 23-28-36](https://cloud.githubusercontent.com/assets/4939519/25105630/c43c5884-23c5-11e7-97ef-b317707a42f0.png)

![screenshot from 2017-04-17 23-29-26](https://cloud.githubusercontent.com/assets/4939519/25105641/cbe021b0-23c5-11e7-92f3-98ed3093deb1.png)

Really, WTF?!

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [v1.2.0](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
103mb is likely cache from previous compilations. 8mb is various fonts. Mind you, only a small part of the fonts is actually loaded on pages.. One of the past PRs simply included the *entire* font families into the project...

**Comment by denysvitali** [comment]
Meh, and what about the 9MB js file?
Is that really necessary? I noticed that Mastodon loads a 2MB js file every time (cached or not) which may result slow.

**Comment by Gargron** [comment]
I believe it's 1.9M compressed. I *do* wanna keep the assets size as small as possible, but the Mastodon web UI is a complex single-page application, so there isn't so much wiggle room. Also I bet a large portion of that size is the emoji list and all the localizations.

**Comment by mjankowski** [comment]
I noticed this recently as well ... the Heroku slug size for deploys is around ~250MB now, which is sort of crazy. The public assets are around ~70MB, with almost ~50MB of that coming from keeping roboto and roboto-mono fonts in the repo.

Are there alternate built-in fonts we might be able to use instead? If not, could we switch the default behavior to be linking to a CDN and provide instructions for people who want/need to self-host?

**Comment by Gargron** [comment]
We could just delete unused fonts from the repository. No CDNs!

**Comment by CapacitorSet** [comment]
This seems to be a use case where Mastodon would benefit from using [ipfs](http://ipfs.io/). Server-side, it would be trivially easy; not so sure about client-side, since it would either require something for the browser to figure out whether to connect to a gateway or to the local ipfs node, or it would require installing an ipfs gateway on the Mastodon server.

What do you think, @Gargron? Have you already taken ipfs into consideration as a distributed solution?

**Comment by nightpool** [comment]
@CapacitorSet I think installing an ipfs gateway alongside mastodon would
be super useful.

**Comment by mjankowski** [comment]
> We could just delete unused fonts from the repository.

I'll take a look at this.

> No CDNs!

I agree with that as the default policy of a new install. I'm curious about ways we can reduce a) the size of the git repo itself for development purposes, b) the size required for a deployment to a server, c) the size of assets served to clients.

**Comment by denysvitali** [comment]
Is jQuery really necessary?On Apr 18, 2017 3:03 PM, Matt Jankowski <notifications@github.com> wrote:
We could just delete unused fonts from the repository.

I'll take a look at this.

No CDNs!

I agree with that as the default policy of a new install. I'm curious about ways we can reduce a) the size of the git repo itself for development purposes, b) the size required for a deployment to a server, c) the size of assets served to clients.

**Comment by nightpool** [comment]
@denysvitali jquery minified is 34k. Thats more then three orders of *magnitude* smaller then the font in question.

**Comment by denysvitali** [comment]
Yeah, but the font isn't embedded in the js file, is it?On Apr 18, 2017 4:18 PM, nightpool <notifications@github.com> wrote:@denysvitali jquery minified is 34k. Thats more then three orders of magnitude smaller then the font in question.

**Comment by nightpool** [comment]
@denysvitali but the JS file is *nine* megabytes. jQuery is less then 4% of that.

**Comment by Gargron** [comment]
Now that assets are down to 1MB I think this is good to be closed :)

**Comment by denysvitali** [comment]
Wonderful. Good work @Gargron 👍
