### ISSUE TITLE
Boost button as disapears

### ISSUE THREAD

**Issue by celri** [tootsuite/mastodon#2041]
Hi ! On my instance (social.glados.ch - Dockers) the boost button (just the graphic, not the function) as disapears after the update to 1.12 version.

Now my instance is uptade to the 1.2 version and the button is still not here :( 

Thanks in advance!
(sorry for my english, I'm french)
![2017-04-17_23-18-14](https://cloud.githubusercontent.com/assets/26901267/25105711/20fb92e2-23c6-11e7-865b-ecef6ef00033.png)

**Comment by denysvitali** [comment]
Have you tried re-compiling the assets with `rake assets:precompile` (or `docker-compose run --rm web rails assets:precompile` if you're using docker)?

**Comment by DanielGilbert** [comment]
Also, if you are using Chrome, you can simply press F12 to open the developer tools, which might give you an idea which errors occur when trying to load the icon.
