### ISSUE TITLE
Can't see toot of followed user from muted instances

### ISSUE THREAD

**Issue by Technowix** [tootsuite/mastodon#2042]
Pretty self explaining : 
![2017-04-18 00_00_15-niu moe](https://cloud.githubusercontent.com/assets/1571367/25106560/6bc8efbe-23ca-11e7-8579-dcfc53f85d9f.png)
I'm following the user, but I can't see his toot in my timeline, his instance is muted / media aren't cached.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Please reopen if it persists but the issue is sold it might not be relevant anymore.
