### ISSUE TITLE
No Valid Credentials Available

### ISSUE THREAD

**Issue by kenyasue** [tootsuite/mastodon#2043]
So I'm using ALB in AWS. And certificate is setup in load balancer.
I'm getting this error when browser try to establish WebSocket connection.

Does anyone know how to web socket works using ALB & SSL ?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
I'm guessing ELB?

**Comment by kenyasue** [comment]
Thanks wxcafe !

It's ALB 
https://aws.amazon.com/elasticloadbalancing/applicationloadbalancer/
It has support for websocket.

But even I use ELB same thing happens.

Which I did is following

- Setup is here https://clovers.social

- LOCAL_HTTPS=false

- Setup SSL certificates in LoadBalancer ( because it's free in AWS)

- Traffic goes like this
(port 443) -> ALB -> (port 80) -> Nginx -> (localhost port 3000) -> Mastodon

- I've got error I have to use "wss" instead of "ws". So I changed to return "wss" in stream.jsx createWebSocketURL method.

Then I got this error "No valid credentials available"...
When I access via HTTP, I got error "{"error":"Error: Missing access token"}"

Hmmm. Do you have idea ?

**Comment by kenyasue** [comment]
Sorry this issue is solved...
Problem was I used ELB instead of ALB.

ALB has support for WebSocket.
https://aws.amazon.com/elasticloadbalancing/applicationloadbalancer/

Thanks WxCafe !!
