### ISSUE TITLE
Header icon for blocked users identical to the local TL

### ISSUE THREAD

**Issue by f6fvy** [tootsuite/mastodon#2051]
When the blocked users list is selected in the last column, the icon of its header is the same as the local TL, and not the icon preceding the "blocked users" title (slashed circle).

But maybe it's a deliberate choice ?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [-] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
<img width="321" alt="screen shot 2017-04-18 at 14 23 52" src="https://cloud.githubusercontent.com/assets/3009327/25130506/b3309546-2442-11e7-9686-617ec95b8aa2.png">
Happens on v1.2

**Comment by kodnaplakal** [comment]
Fixes in #2081
