### ISSUE TITLE
How to get STREAMING_API_BASE_URL from API?

### ISSUE THREAD

**Issue by kmycode** [tootsuite/mastodon#2068]
I'm API user.
Streaming API and others may be different.

for example, mstdn.jp api is
streaming api: https://streaming.mstdn.jp/api/v1/streaming
other apis: https://mstdn.jp/api/v1
https://mstdn.jp/@nullkal/308338

I would like to get STREAMING_API_BASE_URL automatically.
But, there seems no api to get in https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md

How to get it from API?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tateisu** [comment]
I have same issue.
How to know ( STREAMING_API_BASE_URL in .env.production ) via API ?

**Comment by Gargron** [comment]
This is pretty unfortunate, but the `STREAMING_API_BASE_URL` was intended for deveopment environments where you wouldn't have nginx and the streaming API could run on a random port... So we have no mechanism of communicating if this URL is non-standard. I suppose this is something that will need to be in `GET /api/v1/instance`

**Comment by clworld** [comment]
Currently, mstdn.jp does 301 redirect to https://streaming.mstdn.jp/api/v1/streaming/ when we access https://mstdn.jp/api/v1/streaming/.
So, Apps using Streaming API must deal with 301 redirect  for the time being.

**Comment by Gargron** [comment]
It is now returned from /api/v1/instance
