### ISSUE TITLE
WebSocket protocol issue in frontend

### ISSUE THREAD

**Issue by kenyasue** [tootsuite/mastodon#2070]
So I setup ssl in load balancer, Mastodon setting is "LOCAL_HTTPS=false"
Here is how traffic goes.
( HTTPS:443 ) -> LoadBalancer -> ( HTTP:80 ) -> nginx -> ( localhost:3000) Mastodon process

In this case "createWebSocketURL" method in "app/assets/javascripts/components/stream.jsx" returns "ws" as protocol in stead of "wss" and WebSocket didn't work.

I changed this line
https://github.com/tootsuite/mastodon/blob/master/app/assets/javascripts/components/stream.jsx#L8

to 

`  a.protocol = location.protocol.replace('http', 'ws');`

And it works for me...

I don't know it is proper way to correct because I tested only in Chrome v57. So I don't send PR.
Let me know should I send PR.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
If you use ssl, why did you set local_https to false?

**Comment by kenyasue** [comment]
Because Mastodon instance is working as HTTP.
SSL is setup in load balancer.

I will try to set local_https to true..

**Comment by kenyasue** [comment]
So when I change to LOCAL_HTTPS=true. I'm getting this error in browser.

`WebSocket connection to 'wss://clovers.social//api/v1/streaming/?access_token=c17e319d5528eac93bd25bb75fd9496a41ff10e82f3361a97342c9343b63f12d&stream=user' failed: HTTP Authentication failed; no valid credentials available`

**Comment by kenyasue** [comment]
Sorry please forget this. After a while, it starts working.
Seems like problem is not in Mastodon but in higher level...

So  in the end, I changed "local_https" to "true" and it works.
