### ISSUE TITLE
Icon for Getting Started on mobile is not accurate

### ISSUE THREAD

**Issue by emmanuelclement** [tootsuite/mastodon#2072]
Actually it's because the main hamburger menu (icon on top-right) is not a real open/close menu. It's an UI problem: users are accustomed to see hamburger menus open and close as they select it. On Mastodon, the hamburger menu is no more than a tabs-bar__link like the others on the tabs-bar container. One can think (as I do) it's buggy if you can't close it.

2 solutions:
1) having a real open-close menu;
2) (easier) changing the hamburger icon in order not to associate this icon to a "real" hamburger menu.
![burger-menu](https://cloud.githubusercontent.com/assets/1090219/25127965/42e43874-2438-11e7-83cc-e744ec5a6037.png)

**Comment by wxcafe** [comment]
That icon should probably be the "getting started" one, since this is the getting started menu

**Comment by wxcafe** [comment]
That icon should probably be the "getting started" one, since this is the getting started menu

**Comment by emmanuelclement** [comment]
@wxcafe Oh, yes! How couldn't see it! Here is a screenshot with the getting-started icon. I have also deleted the first item of the menu "getting started" since it's the same link/screen.
![getting-started-menu](https://cloud.githubusercontent.com/assets/1090219/25138598/3eb64800-245b-11e7-8ee3-3d39c3d701ca.png)

**Comment by emmanuelclement** [comment]
Moreover, as the 2 firsts items are already in the main menu, there's no reason to duplicate them in the "getting started menu". Here is another screenshot :
![getting-started-menu2](https://cloud.githubusercontent.com/assets/1090219/25139014/5ca4dfba-245c-11e7-89b3-e5bf5a632148.png)

**Comment by usagi-f** [comment]
@emmanuelclement 
I agree. I also felt something wrong. 😆

**Comment by ashfurrow** [comment]
I'll take a look 👍

**Comment by wxcafe** [comment]
Doesn't fix the fact that the getting-started menu shouldn't have either timelines nor the "getting started" title

**Comment by ashfurrow** [comment]
Ah, my bad. Missed that. I'll take a look tonight and remove the extraneous entries so it looks like @emmanuelclement 's screenshot. That's just on mobile, right? Keep the desktop layout as-is?

**Comment by emmanuelclement** [comment]
@ashfurrow > That's just on mobile, right? Keep the desktop layout as-is?
Yep, that's it :-) Keep it on the desktop layout.

**Comment by ashfurrow** [comment]
Here's the PR: https://github.com/tootsuite/mastodon/pull/2175 I'd love to know what you think, or if there's anything I could do to make the code more idiomatic.
