### ISSUE TITLE
WEB_DOMAIN is not used for build URI in web interface

### ISSUE THREAD

**Issue by pixocode** [tootsuite/mastodon#2074]
With `LOCAL_DOMAIN=example.com` and `WEB_DOMAIN=social.example.com`.

My username becomes @pixo@example.com instead of @pixo@social.example.com. :ok_hand: 
I can access the web interface at https://social.example.com. :ok_hand: 

But when I try to open my profile on a new tab, it takes me to https://example.com/@pixo instead of https://social.example.com/@pixo. :-1: 

This means all links to the web interface don't work, for user profiles and for toots
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a tagged release

**Comment by pixocode** [comment]
It seems to work in dev (localhost/localhost:3000) but not in prod (exemple.com/social.example.com) :/

**Comment by ThibG** [comment]
I cannot reproduce this issue. Can you describe more precisely how to trigger this issue? What are you clicking on to open your profile in a new tab?
Also, by the way, WEB_DOMAIN isn't completely usable yet as it breaks some of the remote instances' assumptions I had overlooked.

**Comment by pixocode** [comment]
A link from one of my toot or my profile and so the same for anyone who wants to access my profile or one of my toot

**Comment by ThibG** [comment]
A link displayed on your instance or someone else's? Did you ever run LOCAL_DOMAIN=example.com with another WEB_DOMAIN value beforehand?

**Comment by pixocode** [comment]
On my instance, recess. Everything is in the example...

**Comment by ThibG** [comment]
This should not happen, and I am unable to reproduce it on my instance. Can you provide your username@domain exhibiting this issue?

**Comment by pixocode** [comment]
I tested in production on my instance (social.noostache.fr), I had to go back to keep my instance usable (and not corrupt the links of my toots)
But I can temporarily make a demo of the problem if needed.

**Comment by ThibG** [comment]
Ah, changing LOCAL_DOMAIN on an already set-up instance is not advisable, as it changes the handle of already-established accounts while keeping their URIs.
Still, it should not trigger the issue you are reporting: URIs should use WEB_DOMAIN if set or LOCAL_DOMAIN otherwise. The situation you are describing should only occur if LOCAL_DOMAIN was set to noostache.fr while WEB_DOMAIN was undefined. Otherwise, all links should go to social.noostache.fr.

**Comment by pixocode** [comment]
My instance was installed before adding the WEB_DOMAIN parameter (with only LOCAL_DOMAIN)
Would that mean I could never set up this setting? It seems crazy

**Comment by ThibG** [comment]
So you switched from LOCAL_DOMAIN=noostache.fr with everything running on noostache.fr, to LOCAL_DOMAIN=noostache.fr + WEB_DOMAIN=social.noostache.fr, then to LOCAL_DOMAIN=social.noostache.fr?

The issue with changing anything now is that remote instances have info on your accounts, and most of this information is expected to never change. I am interested in having a migration path from social.example.org to example.org (with Mastodon actually running on social.example.org), but it's not quite ready yet.

**Comment by pixocode** [comment]
Nop, i switched LOCAL_DOMAIN = social.noostache.fr 
To LOCAL_DOMAIN=noostache.fr + WEB_DOMAIN=social.noostache.fr
I wanted to use this to shorten my uri from "pixo@social.noostache.fr" to "pixo@noostache.fr" ^^

Ok I see
It still causes problems on my instance, but if the change is not possible it solves the problem

**Comment by ThibG** [comment]
Ok. Still, the precise issue you reported (URLs using LOCAL_DOMAIN instead of WEB_DOMAIN) shouldn't happen, and I am unable to reproduce it :/

**Comment by pixocode** [comment]
Ah ben, in fact, it's simple, update 1.2.2 to solved the problem O_o
I just re-test and the problem does not arise
