### ISSUE TITLE
interoperability with other open source projects 

### ISSUE THREAD

**Issue by oceatoon** [tootsuite/mastodon#2076]
Hi 
we are developpers of https://github.com/pixelhumain/communecter
https://vimeo.com/133636468
an open source societal network 
I'd be glad to have a chat , to see how we can help mastodon on a territorial perspective and visualisation tools 
Best regards
Tibor

**Comment by Gargron** [comment]
Implement ActivityPub and we'll be interoperable! https://blog.joinmastodon.org/2018/06/why-activitypub-is-the-future/
