### ISSUE TITLE
Introductory walkthrough has broken div tags

### ISSUE THREAD

**Issue by justincredble** [tootsuite/mastodon#2083]
![screen shot 2017-04-18 at 09 48 04](https://cloud.githubusercontent.com/assets/8077409/25134092/acaf5002-241c-11e7-8203-16ada6dd5a47.png)

The "Federated timeline" and "Local timeline" descriptive text are merged into one div rather than in their own like beneath "Home" and "Notifications."

**Comment by wxcafe** [comment]
See https://github.com/tootsuite/mastodon/pull/1883#issuecomment-294327538
