### ISSUE TITLE
Confusing 500 error when following now-private GNU social account

### ISSUE THREAD

**Issue by pimterry** [tootsuite/mastodon#2087]
I'm attempting to follow https://quitter.no/internetofshit on toot.cafe (reproducible on mastodon.social also).

Within Mastodon, this appears like a working account, with a whole range of recent toots shown. If you follow it though, you get a 500 error. Opening the URL above directly, it's clearly private and toots are inaccessible. I think what's happening is that the account has become private, but the existing toots are all cached, so it looks accessible from the Mastodon side, and seems broken because of that.

It'd be better instead if Mastodon could tell that this account is now inaccessible, and show a proper error message to explain that, rather than trying to follow and failing.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
GNU social's private accounts are not *at all* federated. Mastodon's account/toot privacy are our own extensions to the protocols, GNU social never had that. Their "private account" feature is more like making the account not-exist for other servers/instances. So this is a wontfix on our side - nothing we can do.

**Comment by pimterry** [comment]
@Gargron That could be shown in the Mastodon UI thought, right? Right now, it appears like a totally normal account that just doesn't work. Could we add an `Unavailable` marker or ⚠️ icon or something for accounts that are now inaccessible on the remote server?

**Comment by pimterry** [comment]
That's my concern only here, to be clear. I'm definitely not expecting Mastodon to be able to actually get hold of the private content or anything like that, I'm just expecting the situation to be understandable to other Mastodon users in the UI, rather than leading people into an opaque 500.

**Comment by Gargron** [comment]
Well, it's kinda hard to tell when an account is permanently gone, rather than temporarily unavailable, especially if the server returns 500, 5xx range of errors is supposed to be temporary. If the account started returning 404 or 410, then we could make an effort to just delete it from the db. (But also - do we wanna delete it from the db if it's gone from the origin? What if it's valuable and you wanna keep a memory of it?)

**Comment by pimterry** [comment]
I'm not really familiar with the underlying protocol. Is it returning 500 for all the relevant requests?
 `https://quitter.no/api/statuses/user_timeline.json?screen_name=internetofshit` seems to get queried on that page itself for the content, and that's returning a 403, with a clear & useful message.

Not sure if we want to delete it, I think keeping it but just visibly marking it as currently unavailable is fine. You could actually just do that for all 500/404/410/whatever errors. If an instance goes away, or starts having trouble, or a user stops federating (as here) then it's useful to see that when you open the user's profile in Mastodon, rather than just forever seeing cached data with all your interactions mysteriously failing.

**Comment by Gargron** [comment]
OStatus doesn't use /api/statuses/user_timeline.json, but Webfinger + Atom feed

**Comment by pimterry** [comment]
Ok, that makes sense. Here then webfinger is gives a 500, and the atom feed gives a 404.

Seems reasonable to mark accounts as unavailable in the DB whenever one of the requests fails like this though, and to gently surface that in the UI. Does that seem reasonable?

Happy to have a go at this myself, but I'm pretty busy this week and next. If you're interested though I'd be happy to put in a PR once I have time.
