### ISSUE TITLE
feature request: add option to "save" toots privately, i.e. "star" them into a separate list for later perusal

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#209]
i don't care whether "like" is a star or a heart, but it's very useful to have separate things for indicating "i'm happy this was posted" and for "i want to keep this so i can find it later".

i guess if such a list is made, being able to search it usefully would be good too

**Comment by IBPX** [comment]
I'd like this. Reddit for example has a "save" button, that functions exactly like this.

**Comment by LogicalDash** [comment]
This could as well be part of a Moments-like, Storify-ish feature, collecting toots into stories and optionally displaying those where the rest of the world can see.

**Comment by triplefox** [comment]
Regarding search, search of one's own posts as well as these bookmarked streams would also be very handy. (UI for searching everyone is potentially too easy to abuse, and probably should be discouraged, even if we can't stop it from happening.)

**Comment by Gargron** [comment]
I remember the "collections" feature request having a separate issue. I've recently added the ability to browse your favourites, so I consider this resolved!
