### ISSUE TITLE
Language detection works quite oddly

### ISSUE THREAD

**Issue by pixocode** [tootsuite/mastodon#2091]
Some examples :  

"test"  => sv   
"rouge" => sv  
"bonjour :)" => pl  
"oui bon ok" => pl  
"Bonjour, comment va tu ?" => es  
"Ceci est un test" => it  
"maison" => it  
"La maison est rouge" => it  
"Je ne comprend pas du tout comment ça fonctionne..." => fr :+1: 
"mais d'un coté ça marche pas vraiment" => fr :+1: 
"tu devrais regarder de ce coté là" => fr :+1: 
"Beaucoup de pseudonymes courts sur mastodon, c'est vraiment sympa" => fr :+1: 

It seems to work more with sentences than with words  

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [#1.2](https://github.com/tootsuite/mastodon/releases/tag/v1.2) and not on `master` (If you're a user, don't worry about this).

**Comment by patf** [comment]
I tested an alternative language detection gem called [scylla](https://github.com/hashwin/scylla) against a [dataset of ~66k tweets](https://blog.twitter.com/2015/evaluating-language-identification-performance) that were manually categorized by language.

Results with scylla: https://gist.github.com/patf/482754e9353e8f3db1ac3c985ca4244d
Results with whatlanguage, the gem that's currently used: https://gist.github.com/patf/496c18cc4d568157803b68285c0da9b6

Overall, the accuracy with scylla is 84 % and 42 % with whatlanguage. whatlanguage lacks support for a number of languages (e.g. Japanese). Seems like a good drop-in replacement.
