### ISSUE TITLE
vanishing emoji in notifications

### ISSUE THREAD

**Issue by azbulutlu** [tootsuite/mastodon#2094]
https://social.tchncs.de/@gertdebra/923395
The emoji in this toot wasn't visible in notifications column :) 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Wonderfall** [comment]
Looks like it's a duplicate of https://github.com/tootsuite/mastodon/issues/2016

**Comment by azbulutlu** [comment]
somehow skipped over that issue when searching, sorry for the duplicate
