### ISSUE TITLE
Filename can cause image upload to fail

### ISSUE THREAD

**Issue by chris-martin** [tootsuite/mastodon#2098]
I tried to upload an image named `C9uGktdW0AAqK9N.jpg-large` and it failed with the message

> 422 Validation failed: File has contents that are not what they are reported to be

If I rename the file to `C9uGktdW0AAqK9N.jpg`, then it succeeds.

I'm pretty sure most services ignore the filename and just look at the contents. Can we do that here to prevent this error?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
Paperclip is /pretty strict/ about how it handles media files.

**Comment by Gargron** [comment]
Solved
