### ISSUE TITLE
Every animated file saved as mp4, even if uploaded as a gif.

### ISSUE THREAD

**Issue by itsukarine** [tootsuite/mastodon#2104]
This is kind of a hassle for saving, but not a big deal, but I'm curious if it can be fixed. I think it would definitely make using the media better, as in, Mastadon.

I'm on Pawoo.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. 
(I just searched gif and didn't seem find anything in the titles, sorry if this really is a dupe. It seems plausible it would be)
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
This is intended behaviour. MP4 are smaller and higher quality than GIF.
