### ISSUE TITLE
probably a good idea to move the repo into a github organization

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#211]
lemme know if i should be more detailed about this, but i figure it's probably quite obvious. :)

**Comment by Gargron** [comment]
Except making it look more official, are there any other reasons?

**Comment by wchristian** [comment]
More fine-grained control over how people can manage/contribute, better ability to separate it from your personal dev, ability to detach yourself from it entirely if needed, ability for others to usefully continue managing if you decide to step out or something happens to you.

**Comment by Gargron** [comment]
Alright I sent a support request for the username "Mastodon"

**Comment by ineffyble** [comment]
The other benefit of this is there is bound to be more than one repo for Mastodon that's 'official' or official enough to manage. Having an organisation will let you group them, and group access/permissions.

**Comment by Gargron** [comment]
It's now "tootsuite/mastodon"
