### ISSUE TITLE
embed images and other stuff from 3rd party sites

### ISSUE THREAD

**Issue by teslasmoustache** [tootsuite/mastodon#2121]
I think it would be good for both users and admins if we could embed images, videos, and audio clips from 3rd party sites.

Diaspora* (another Ruby project) uses Oembed to embed videos and audio from sites which support it. (And there are problems with this, e.g., Youtube and Vimeo supports Oembed, but Archive.org and Mediagoblin sites do not, etc. But it's something to consider.) And Markdown to embed images using the `![](*.jpg)` syntax. So that may also be something to consider.

I really hope we can at least get image embedding, because that would save storage space for admins and save hassle for users.

I think we'd all like to see html5 tags implemented for this stuff, but, again, there's stuff to consider.

**Comment by expenses** [comment]
Mastodon does support Oembed, but only for the focused toot:

![An example embedded youtube video](https://cloud.githubusercontent.com/assets/13566135/25217466/2d7e6a3a-25fb-11e7-9e64-a824a6243c88.png)

I'm not entirely sure what you mean by image embedding - do you want images hosted on other sites to be visible in the home timeline?

**Comment by teslasmoustache** [comment]
1: My preference would be to have an embedded video in Mastodon so that clicking that link doesn't open a new tab and take me to Youtube. Maybe this could be done with the CSS `display: block` thing that shows up when you click an image.

2: yes.

**Comment by 0tt** [comment]
I would like at least a thumbnail to be displayed without having to focus the toot.

**Comment by Cassolotl** [comment]
Seems related to #459. Also, yes please, more embedding of cool stuff. A new user [asked about this just today](https://mastodon.top/@brandkopf/236029).

**Comment by Gargron** [comment]
OEmbed has been implemented! YouTube, Vimeo etc are all embedded.

**Comment by dustinpaluch** [comment]
@Gargron, what about image embedding?

**Comment by JamesHealdUK** [comment]
Agree with @dustinpaluch on this, image embedding would be incredible. Imgur and gifs.com would be super nice.

**Comment by zacts** [comment]
I still don't seem to see multimedia like audio or video embedded from Mediagoblin. This would be a nice feature indeed!

**Comment by Gargron** [comment]
Anything that supports OEmbed works. Never seen mediagoblin in the wild, I'm not sure that project is still being developed.
