### ISSUE TITLE
Remove cache-busters from media URLs

### ISSUE THREAD

**Issue by riking** [tootsuite/mastodon#2123]
The media URLs in the interface have a cache-buster on them (the current time in a query string).

`https://social.wxcafe.net/system/media_attachments/files/000/025/874/original/c5cfc535c7c45c95.png?1492570810`  
specifically the **`?1492570810`**

This isn't needed in the normal case, and harms native browser caching (the image must be redownloaded every time the cache-buster is regenerated). You only need to apply cachebusters if the previous load is stale or was bad.

It also harms usability with right click -> Copy link to image, as the extra numbers are confusing.

Proposal: Don't put cache-busters on media URLs.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
These are only updated when the underlying file changes. To be fair, we used to have all files named "media.extension", so it was needed when people re-uploaded an avatar or header, but now filenames are random hashes so that shouldn't be an issue. I think we could remove these, yes.
