### ISSUE TITLE
Most Used Emoji Collected

### ISSUE THREAD

**Issue by benhamill** [tootsuite/mastodon#2125]
It would be super awesome if the Mastodon web client use local storage to track my most common 10-15 emoji and put them at the top of the picker for me. I don't think it's super critical that these persist across machines or anything. If I use more than one computer to post with any regularity, the most commonly used emoji on each of them will converge, anyway, since, let's be honest, it's gonna be :stuck_out_tongue_closed_eyes:, :sparkling_heart:, :sparkles:, :woman_shrugging: and :woman_facepalming: mostly.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by expenses** [comment]
[This PR](https://github.com/tommoor/emojione-picker/pull/55/files) would need to be implemented into `emojione-picker` first.

**Comment by benhamill** [comment]
Does #55 include the display or is it just tracking frequency of use? I don't know JS well enough to puzzle it out quickly.

**Comment by chaica** [comment]
That's a great feature. Emoji picker on the web interface is hard to use currently.

**Comment by Gargron** [comment]
Wait, we already have this..? Closing
