### ISSUE TITLE
log-in in single user mode

### ISSUE THREAD

**Issue by xsteadfastx** [tootsuite/mastodon#2129]
im running my instance in single user mode. i know there is a url for loggging in but i think it would be better if there is a link on the default profile.

thanks for this amazing software and everything it gets going right now.... its exciting times...

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
> i know there is a url for loggging in but i think it would be better if there is a link on the default profile.

...can you clarify your request here?

**Comment by archaeme** [comment]
I think he means that it would be nice to have a convenient link to log in when single-user mode is set.

**Comment by xsteadfastx** [comment]
On Wed, 19. Apr 04:30, Francis wrote:
> I think he means that it would be nice to have a convenient link to log in when
> single-user mode is set.

Exactly. I was logged in when i set my instance to single user mode...
tried to login on a different computer and had to find out the right url
first.

**Comment by ashfurrow** [comment]
Now that https://github.com/tootsuite/mastodon/issues/2129 has been merged, this issue should be resolved. It'll be included in the next release of Mastodon. Thanks again @xsteadfastx for opening!

**Comment by xsteadfastx** [comment]
❤️❤️❤️
