### ISSUE TITLE
Scratch column cannot be dismissed

### ISSUE THREAD

**Issue by psychicteeth** [tootsuite/mastodon#213]
Let's say, for the sake of argument, you've visited the hashtag #cum, at work, and then panicked and clicked on your own profile. That's great - now you've hidden the salacious hashtag, but there's a back icon that you can't get rid of. It would be good to be able to dismiss this entire column like a browser tab, allowing a new history to begin. Just in case you're backing out of a stack of profile clicks and go one step too far. Refreshing the page seems to preserve the column history, which is more useful than removing the column on refresh. So it would be nice to be able to wipe it.

**Comment by Gargron** [comment]
Can't you just click back in the first place, after navigating to such a place? Then clicking somewhere else will start a new history, just like you want.
