### ISSUE TITLE
Uses "und" as default language code for toots

### ISSUE THREAD

**Issue by Tpt** [tootsuite/mastodon#2130]
Currently the default language for Toots is "en". Mastodon should probably use "und" as it does not have any real knowledge about the tweet language.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
This behavior changed recently, and will be reflected in an upcoming release (we now default to instance locale default, not just `en`).
