### ISSUE TITLE
Boosted toots that are deleted cause misattribution

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#2140]
![screen shot 2017-04-19 at 12 59 28](https://cloud.githubusercontent.com/assets/6607512/25179022/0cd004e8-2500-11e7-848d-c84ba4769615.png)

To replicate:

1) Toot something.
2) Have someone else boost it.
3) Delete your original toot.
4) The boost of the toot then appears in the timelines to be authored by the person who boosted it, NOT the original tooter.

What should happen is, other people's boosts get deleted when you delete your original toot.

I searched for this issue and there are a lot of *similar* issues to this that may all be connected, mainly #1811 and #1114.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Thanks for the pointer! This can be replicated consistently? I'll investigate how this could happen!

**Comment by Cassolotl** [comment]
I can't replicate this between my cybre.space account and my mastodon.social account in browser. :/ This maybe only affects Amaroq, and should be reported to them instead of here?

**Comment by Cassolotl** [comment]
I will close this since it can't be replicated. :/
