### ISSUE TITLE
Privacy issue related to Image Hot-Linking

### ISSUE THREAD

**Issue by denysvitali** [tootsuite/mastodon#2142]
Apparently Mastodon loads remote images without masking the user IP address,
therefore publishing an image a malicious instance / admin can see other instances users IP addresses.

GitHub fixes this problem by caching the image and linking a camo.github* version instead (which btw won't be a good thing if we think about the loli problem we got a few days ago).

Would it be reasonable to implement an image proxing? Is this caused by a bad Referrer policy on other server's end? If so, can we discourage this bad habit?

What's your tough on this?

Masked IPs for obvious reasons
![privacy-mastodon](https://cloud.githubusercontent.com/assets/4939519/25180485/74630a8e-250e-11e7-941a-e81abd70f5ac.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [v.1.2.0](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Upcoming v1.2.1 release will rollback the hotlinking.

**Comment by denysvitali** [comment]
Looking forward to it, thank you Gargron! 👍

**Comment by wxcafe** [comment]
Since v1.2.2 has been released, I'm closing this issue
