### ISSUE TITLE
Avatars (profile pictures) don't update

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#2145]
How to replicate:

Have two accounts that don't follow each other.

1) Account A has no profile picture.
2) Account A and account B follow each other.
3) Account A uploads a profile picture.
4) New profile picture is not visible from account B. Account B can open account A's profile in a new tab and it shows the new profile picture, but viewing the profile from in Mastodon in-browser still doesn't update.

It looks like when I then open Tusky, the new profile picture is not visible there either.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
I have seen the same problem :+1:

**Comment by Cassolotl** [comment]
My latest:

![screen shot 2017-04-22 at 00 12 06](https://cloud.githubusercontent.com/assets/6607512/25298831/ce72b806-26f0-11e7-9e1e-8fad0621bbee.png)

![screen shot 2017-04-22 at 00 12 26](https://cloud.githubusercontent.com/assets/6607512/25298834/d1b2cf74-26f0-11e7-85bb-45ac674c2ace.png)

![screen shot 2017-04-22 at 00 12 16](https://cloud.githubusercontent.com/assets/6607512/25298836/d494a6cc-26f0-11e7-96aa-685452711738.png)

I'm http://cybre.space/@cassolotl and they're https://mastodon.social/@WelshPixie

I tried unfollowing and then hard-reloading the page and refollowing, but nope, no change. :(

**Comment by Cassolotl** [comment]
Update: I can now see the avatar/profile photo of Del (@welshpixie@mastodon.social)...

[Post](https://mastodon.social/users/WelshPixie/updates/2099879):

>I didn't know that apparently my avatar wasn't showing because of stuff. It should be showing now. Huzzah! :)

**Comment by Cassolotl** [comment]
I'm not sure if this is the cause of *every* missing avatar, or just this one! So I'm going to leave this open for now, until I have more information, I guess? Unless someone else knows for sure, in which case, feel free to close it if you think that's a good idea.

**Comment by Gargron** [comment]
Hard to quantify this but on the whole, this functionality seems to be working fine.
