### ISSUE TITLE
More logging for daily rake task

### ISSUE THREAD

**Issue by ashfurrow** [tootsuite/mastodon#2146]
I love the rake task output to a file, but there's currently not output. Just something to indicate what's going on. I'll take a look tonight.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
Can you paste your crontab here? It's probably because of the redirection.

**Comment by ashfurrow** [comment]
Sure! It's as follows

```
0 0 * * * cd /root/mastodon/ && docker-compose run --rm web rake mastodon:daily >> /var/log/mastodon-daily.log
```

Contents of the log are:

```
Scoped order and limit are ignored, it's forced to be batch order and batch size.
```

**Comment by wxcafe** [comment]
Try using `2>&1 >> /var/log/mastodon-daily.log`?

**Comment by ashfurrow** [comment]
Thanks, I'll do that and report back 👍

**Comment by Gargron** [comment]
A lot of the rake tasks use `Rails.logger`.. In production that should be stdout thanks to the rails_12factor gem.. So hmm

**Comment by wxcafe** [comment]
running it in the shell directly gives some output, so I thought it might go to stderr but...

**Comment by ashfurrow** [comment]
I've checked and the contents of the file are now:

```
Scoped order and limit are ignored, it's forced to be batch order and batch size.
```

I think adding logging to just the daily rake task, and not the subtasks, would be sufficient. Maybe with a timestamp. Thoughts?
