### ISSUE TITLE
Proposal to replace the default TweetDeck theme

### ISSUE THREAD

**Issue by thor-the-norseman** [tootsuite/mastodon#2157]
I know I'm not the first person to bring this up, but I can't seem to find an issue for it.

Looking like TweetDeck doesn't do Mastodon justice. I think Mastodon deserves its own unique default user interface. TweetDeck isn't the most beginner-friendly of user interfaces. The timelines can be overwhelming, presenting too much information at once. If Mastodon is to grow past Twitter, it actually needs to offer a _better_ user interface than Twitter's, not a mere copy of it.

Pretty much every service that has experienced mainstream success offers its users a minimalistic interface with only the necessities revealed to the user, at least until they begin to explore further. As Mastodon works today, I actually feel that the externally linkable user feeds offer a better experience.

I've also seen several people object to the dark blue color scheme. Subjectively, I agree. Objectively, there is actually one reason for using a light background: Dark text on a light background is easier to read than light text on a dark background. I believe there are UX studies that actually prove this. I also think it would lighten the mood a bit.

This is arguably related to #2028 but is distinct from it. The default theme is what most instances are going to start out with and perhaps stick to. It should offer a good first impression to new users.

**Comment by DanielGilbert** [comment]
> Objectively, there is actually one reason for using a light background: Dark text on a light background is easier to read than light text on a dark background. I believe there are UX studies that actually prove this. I also think it would lighten the mood a bit.

It depends.

In well lit situations, you might want to use black-on-white, but on dim conditions, you might prefer the other (compare: dark-mode of Twitter App). So it would be good to actually have some kind of choice. And yes, I normally have the dark mode of the Birdie App active, but that's just personal preference. This also applies to my coding environment - white text on dark background.

**Comment by CatLover91** [comment]
Isn't the revival of classic tweetdeck a main feature of mastodon? I assume this is something that draws users in from twitter rather than the opposite.

I personally prefer dark themes over light, but I would suggest the ability to swap in between custom themes as a compromise. If instances want to take the time to make their own themes, and users of those instances want a choice between light and dark themes, the capability for users to choose between multiple custom implemented themes sounds like a worthy compromise for all parties.

**Comment by mjankowski** [comment]
This sounds like a two-part request, where the parts aren't totally compatible with each other:

- You want to scrap the tweetdeck-style UI in favor of something else (what else?)
- You want "themes" (probably just different color scheme) for the existing UI
- You want the default theme to be a light one

Is that accurate, and which is most important?

**Comment by thor-the-norseman** [comment]
I would expect more from a theme engine than simply being able to change colors. I'm thinking themes in the WordPress sense - essentially completely different designs exposing the same functionality.

I'm not proposing conflicting solutions. I'm saying that a theme engine could be a part of a compromise solution for the "non-ideal default theme" problem, since one could then preserve the existing theme as a Mastodon Classic theme for those wanting to keep that (thanks to the theme engine) while simultaneously introducing a new default theme.

As for a light background, that's a very basic suggestion for what one might want to put in the new default theme.

I have implicated other ideas for a new theme already: Multiple timelines on screen all at once is confusing, so implicitly, I'm proposing a single-timeline-at-a-time layout for said new theme. It could perhaps be rendered as a single center column.

As I mentioned, I like the look of the externally visible user feed, the one that opens in a new browser tab when you middle-click a user's avatar...

**Comment by expenses** [comment]
I think the UI system could definitely be made more modular, but changing the default would be a pretty bad idea at this stage.

**Comment by thor-the-norseman** [comment]
I see that this issue has been labeled as low priority, but the user interface is the first thing you're exposed to as a new user. Don't first impressions matter?

If it turns out that the majority of existing users feel that this has low priority or is a bad idea, we are heading towards a similar situation to that of Twitter, where the existing mass of users really like Twitter as-is, causing Twitter to stagnate, because users who could potentially be recruited to the platform are looking for a different user experience, something Twitter is unable to give them without alienating existing users.

I hope that, at the very least, we will see a highly modular theme / user interface system at some point.

(Meta-observation: You can pretty much put most humans in one of two camps: The ones that care about aesthetics and are bothered if they aren't right, and the ones who focus more on what's underneath. There are also rare hybrids who care equally for both. The Myers-Briggs system call these two opposites "Intuitive" and "Sensing". The more scientific Big Five personality test has "Openness to experience" in place of "Intuitive". This ticket would have a high priority for some sensing people and a low priority for some intuitive people. Developers tend to be intuitive people, and typically rely on designers, sensing people, for design work.)

**Comment by DanielGilbert** [comment]
I totally agree with you - but on the other hand, there are 567 issues at the moment, so I understand that prioritizing is justified. I would also love to see a themable interface.
Maybe we should think of Mastodon as an engine, not a platform. Then we can also justify custom styles. Like good ol' forums used to be, the older might remember them.

But the hardest part of this is to actually get to know why people are not using the interface. Normally you could create some kind of survey for this, but funny enough, we cannot address the people we are looking for, because they already turned away.

Maybe there is already a template engine for RoR? And maybe some else could estimate the effort that has to be put into sth. like that? (I'm not a Ruby dev, sorry. :\ )

**Comment by thor-the-norseman** [comment]
I don't believe Ruby on Rails is heavily responsible for the appearance of Mastodon. The web app (default user interface) is written in React, a system that takes care of all page rendering. In theory, a brand new user interface could be made by any instance owner by replacing the web app with a custom one.

**Comment by DanielGilbert** [comment]
Ouch. You are right, I was somehow on the wrong track.

**Comment by sterbfly** [comment]
Would be great if there was a theme engine that would allow to create fully custom themes, like, for example, [Qvitter](https://git.gnu.io/h2p/Qvitter).

**Comment by wxcafe** [comment]
I'm pretty sure this is fixed now with the theme engine so I'm closing this

**Comment by duven87** [comment]
> I would expect more from a theme engine than simply being able to change colors. I'm thinking themes in the WordPress sense - essentially completely different designs exposing the same functionality.
> 
> I'm not proposing conflicting solutions. I'm saying that a theme engine could be a part of a compromise solution for the "non-ideal default theme" problem, since one could then preserve the existing theme as a Mastodon Classic theme for those wanting to keep that (thanks to the theme engine) while simultaneously introducing a new default theme.
> 
> As for a light background, that's a very basic suggestion for what one might want to put in the new default theme.
> 
> I have implicated other ideas for a new theme already: Multiple timelines on screen all at once is confusing, so implicitly, I'm proposing a single-timeline-at-a-time layout for said new theme. It could perhaps be rendered as a single center column.
> 
> As I mentioned, I like the look of the externally visible user feed, the one that opens in a new browser tab when you middle-click a user's avatar...

I'm totally agree with to put a new theme like a single-timeline-at-a-time layout. I like a lot how fast its developing mastodon but the appareance kill me.. Its all very strait, looks like designed for to view from a smartphone.
It should to be the option to have a appareance like GNU Social/quitter, postactiv (wider than "quitter" better), etc.
Each click that I do come a new strait columm .. :'(  At least would be good to have the possibility to widen the columns.
For this reason I'm stil in GNU social but I like the effort made everyday on mastodon. 
When the the appareance will gets better, groups works (options: follow and be private) and private messages are encrypted I won't move more from here and will install a instance too. :)
