### ISSUE TITLE
 Emoji Picker is not displayed any emoji

### ISSUE THREAD

**Issue by rin-natsume** [tootsuite/mastodon#2160]
Hello.

In My instance, Emoji Picker is not display any emoji. Like the figure below. 

![default](https://cloud.githubusercontent.com/assets/17264514/25192563/9c6e069a-256e-11e7-9c3c-416aba1748fd.PNG)

I tried recompiling the assets, but it was no effect.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
Are you sure this isn't a CSP error?

**Comment by rin-natsume** [comment]
Thank you!!
Certainly there were some errors in the CSP.
After correcting it, Emoji are now displayed.
