### ISSUE TITLE
Remote follow url formation does not comply with ostatus standard

### ISSUE THREAD

**Issue by celesteh** [tootsuite/mastodon#2177]
For remote follows, Mastodon uses the link format:  https://your.instance/authorize_follow?acct=acct:remoteuser@remote.instance

However, GNU social expects: https://your.instance/authorize_follow?acct=remoteuser@remote.instance  So therefore, Gnu Social users get sent to an error page when trying to follow Mastodon users.

Is there a reason for that extra `acct:`? Surely the `acct=` should be enough?
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
To be clear, is your concern with human-facing browsers URLs that get seen during the follow process, or with an an LRDD-supplied template URL not conforming to a spec?

I guess, can you do a little more step by step on each system and describe where the failed interop is?

**Comment by celesteh** [comment]
Looking at a user profile on a mastodon instance:
1. click remote follow
2. type in myname@my.instance
3. Click the big blue button below it
4. Get redirected to my own instance where I get some error text:

> Sorry, we could not reach that address. Please make sure that the OStatus address is like nickname@example.com or http://example.net/nickname.

Below the error is a text box, labeled 'Subscribe to' And it's pre-filled in with acct:username@remote.town

The url is https://my.instance/main/ostatussub?profile=acct%3Ausername%40remote.town

Is this helpful?
