### ISSUE TITLE
Emoji picker search does not search keywords or shortcodes

### ISSUE THREAD

**Issue by csu** [tootsuite/mastodon#2178]
It looks like the emoji picker currently only searches the emoji names and does not search through keywords or shortcodes. This causes some queries that should intuitively work to not return the expected results.

For example, searching for "wave" does not return the 👋 emoji, which has the shortcode `:wave:`. This is because the emoji is named "hand waving", so searching for "wav" returns it, but not "wave".

Relevant discussion: https://mastodon.social/@cs/3328021

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by expenses** [comment]
Mastodon uses the [`emojione-picker`](https://www.npmjs.com/package/emojione-picker) class for this, so I think you'll need to make an issue there.

**Comment by csu** [comment]
@expenses Ah, understood. Opened an issue there: tommoor/emojione-picker#66. Feel free to close this issue, if there's no plan to do this in Mastodon.

**Comment by tommoor** [comment]
I just pushed a patch update for this, updating the dependency should get it working as expected 👍

**Comment by csu** [comment]
@tommoor That was so quick! Thank you!

**Comment by expenses** [comment]
![The emoji dialog showing a hand-wave and a wave](https://cloud.githubusercontent.com/assets/13566135/25216809/70e9761e-25f8-11e7-89d4-8b4a996536bf.png)
@tommoor Excellent, thank you!

**Comment by expenses** [comment]
(Do you think you could close this PR?)

**Comment by csu** [comment]
Closed!
