### ISSUE TITLE
Auto-focus emoji picker searchbox

### ISSUE THREAD

**Issue by ashkitten** [tootsuite/mastodon#2179]
Not such a big deal, but it'd be a really nice touch to have the searchbox of the emoji picker be auto focused when you click the button.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by expenses** [comment]
See my response to #2178.

**Comment by tommoor** [comment]
The searchbox in emojione-picker is set to `autoFocus`, it could be that the click event from opening the picker is continuing to propagate which immediately unfocuses it? Definitely worth trying `ev.stopPropagation()` after the initial click is handled.

**Comment by Gargron** [comment]
It happens when I try it so seems to be resolved.
