### ISSUE TITLE
Searchable remote accounts

### ISSUE THREAD

**Issue by Chronister** [tootsuite/mastodon#2184]
In the administration panel, the "remote accounts" view (/admin/accounts) very quickly becomes nigh-impossible to navigate. The ability to search by username/domain would make it much more manageable. Additionally, the already existing feature of filtering by domain in the URL parameter ?by_domain should be exposed more explicitly as an input box in the UI.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by pixocode** [comment]
Very useful for other lists (know instances, ... reports, domain blocks, ...)

**Comment by Gargron** [comment]
It is now possible to do this.
