### ISSUE TITLE
Textarea height should be reset upon sending toot

### ISSUE THREAD

**Issue by southrop** [tootsuite/mastodon#2189]
Probably related to #2128?

After the textarea height gets resized due to a multi-line toot, the area will remain at that height until you start typing again. The textarea should reset back to the default size after the toot is sent for a consistent experience.

![chrome_2017-04-20_11-35-05](https://cloud.githubusercontent.com/assets/2568167/25211029/e4f4b1d0-25bd-11e7-8068-c073c42e41df.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kodnaplakal** [comment]
Fixes #2236

**Comment by ashfurrow** [comment]
Thanks @kodnaplakal ! Now that https://github.com/tootsuite/mastodon/pull/2236 is merged I'm going to close this issue.
