### ISSUE TITLE
Reply All icon appears in some incorrect situations

### ISSUE THREAD

**Issue by southrop** [tootsuite/mastodon#2190]
If you reply to your own toot, it appears that this gets treated as having multiple people in a conversation, and the reply icon becomes a reply-all icon.

![chrome_2017-04-20_11-40-04](https://cloud.githubusercontent.com/assets/2568167/25211109/69af54d4-25be-11e7-9f3c-12fb94eb7dd0.png)

I presume Mastodon is treating me as being in the conversation more than once? If that's the case, there should be some kind of check for duplicates on the participants.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by southrop** [comment]
Upon further investigation, "reply all" seems to appear if you reply to a reply. It works fine (Reply icon appears) if you are simply mentioned in someone else's toot.

![chrome_2017-04-20_11-54-26](https://cloud.githubusercontent.com/assets/2568167/25212664/a642a1c8-25c6-11e7-9beb-4ac17db26db3.png)

This could be explained by the fact that there are already two participants in the conversation (yourself and the other person), and so Reply All is displayed. The correct solution here is probably to ignore yourself?

**Comment by wxcafe** [comment]
This button is there to make it clear that the toot is in a thread. This can be a conversation or a reply to yourself, it's treated the same way. It's not literally a 'reply all' button, rather a 'reply to this thread' button.

**Comment by southrop** [comment]
Thanks for the clarification. Didn't think to search pull requests before, but I just did and noticed I wasn't the only one who experienced this confusion. Perhaps a better icon is in order, though it doesn't look like font awesome has any suitable ones
