### ISSUE TITLE
Links in admin account detail page should link to URL in displayed

### ISSUE THREAD

**Issue by polymerwitch** [tootsuite/mastodon#2193]
When viewing an account detail page as an admin, the links for Profile URL, Feed URL, and Salmon URL link back to the page the admin is on. This is counter-intuitive as a full URL is the text of the hyperlink and it is expected that the link itself will follow that.

These links should have an href that is identical to the URL listed in the tag body.

See photo below for links in question:
<img width="612" alt="screen shot 2017-04-19 at 9 41 28 pm" src="https://cloud.githubusercontent.com/assets/476133/25213960/46a004a4-2549-11e7-9145-8232045985d1.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
It's been fixed by #2186 already afaict
