### ISSUE TITLE
Mastodon incorrectly mangles ##blah into #

### ISSUE THREAD

**Issue by Artoria2e5** [tootsuite/mastodon#2194]
When writing some complaints about a weird person on an freenode IRC channel called ##Orz, I attempted to mention the channel's name (that is, ##Orz) directly when writing a post on mstdn.io using Mobile Chrome. However, what I see posted has ##Orz replaced by #. Mastodon may be mangling and breaking something around here.

The whole failed chain of toots is available at https://mstdn.io/@artoria2e5/625185.

* * * *

* Yes, I searched or browsed the repo’s other issues to ensure this is not a duplicate.
* Yes, this bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master`. I am using 1.2.2 on mstdn.io.

**Comment by over9001** [comment]
Hi! I isolated the problem to a string split: https://repl.it/HSi5/0
Which is just the following: 
## Mastador hashtag bug hunt!
## from https://github.com/tootsuite/mastodon/blob/70891a99a97bc1ca14a8ded13a5cd45b648b92b3/app/lib/formatter.rb
def hashtag_html(match)
    prefix, affix = match.split('#')
    "#{prefix}<a href=\"#\" class=\"mention hashtag\">#<span>#{affix}</span></a>"
end
hashtag_html("#lol")



The offending line is  prefix, affix = match.split('#'). Right?

**Comment by nightpool** [comment]
Yep, seems like instead we should be doing `prefix, *affix = match.split; affix.join("#")`

**Comment by Artoria2e5** [comment]
Some `match.split('#', 2)` can save the second join. Should I go for a PR?

**Comment by Artoria2e5** [comment]
Merged, should be fixed.
