### ISSUE TITLE
Since 1.2.2 I have CSP problem

### ISSUE THREAD

**Issue by Golgotha29** [tootsuite/mastodon#2199]
Since update 1.2.2 i have a new CSP problem.

![csp_prob](https://cloud.githubusercontent.com/assets/148720/25219560/277d6b3c-25af-11e7-9de4-a83c704caf26.png)

(Firefox 52.0.2)
* * * *

- I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by postblue** [comment]
Same on pouet.it with this NGinx config:

```nginx
add_header Content-Security-Policy "default-src 'none'; font-src 'self'; media-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; img-src 'self' data:; connect-src 'self' wss://pouet.it;";
```

**Comment by Komic** [comment]
Funnily, Chrome doesn't throw an error in the same conditions. Not sure what's triggering this.

**Comment by ToroNZ** [comment]
Same on mastodon.co.nz:
[http://i.imgur.com/hOFzsxP.png](url)

**Comment by ykzts** [comment]
Why will not anyone write in which web browser the problem occurred?

I confirmed that this problem will occur in Firefox 52.0.2. But Google Chrome is fine.

**Comment by michaeljdeeb** [comment]
jQuery is causing it. [This comment]( https://bugzilla.mozilla.org/show_bug.cgi?id=1336076#c6) points in the right direction.

**Comment by Komic** [comment]
Pretty sure we can close this, then~
