### ISSUE TITLE
Need a scrollbar for settings menu

### ISSUE THREAD

**Issue by pixocode** [tootsuite/mastodon#2201]
For the screens with a 1366x768 resolution, need a scrollbar in the settings menu
![capture du 2017-04-20 10-37-58](https://cloud.githubusercontent.com/assets/293229/25221563/cd1b2768-25b5-11e7-89dc-d91657828680.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on 1.2(https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by rhaamo** [comment]
This has been fixed in pull request #1347 which have been included in v1.2.2 release
