### ISSUE TITLE
The "URL" entry in the atom feed seems to be a random link

### ISSUE THREAD

**Issue by ploum** [tootsuite/mastodon#2204]
When to build rules on Zapier/IFTTT using the atom feed of the user's timeline ( eg : https://mamot.fr/users/ploum.atom ), it looks like the "URL" field is somewhat random (it can be a mentioned user's profile or http://activitystrea.ms/schema/1.0/person or some other things).

If there's at least one explicit URL in the toot, it would be nice to have it as a separate atom item (which can be empty if no URL) in order to build rules and, for examples, crosspost Mastodon message to Twitter or Facebook.

Later, this also can be used to have an URL thumbnail in the feed.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
I'm not sure how IFTTT is trying to grab it (maybe just grabbing the first URL-ish thing it sees?) - but the `href` value for the `link` with `rel="alternate"` is probably what you want.

Alternately - are you talking about extracting links which were referenced in the status body itself?

**Comment by ploum** [comment]
Yes, I was talking about extracting links in the content itself.

**Comment by mjankowski** [comment]
Is the request there then "it would be nice if Mastodon could proactively extract the first link, when one exists, from any status, so that services consuming the feed can access that directly instead of trying to guess/parse" ?

**Comment by Gargron** [comment]
Mastodon generates valid Atom XML. This is an issue with the IFTTT parser.
