### ISSUE TITLE
Notifications do not get fully removed when the associated post is deleted

### ISSUE THREAD

**Issue by codl** [tootsuite/mastodon#2205]
If you delete a post that has notifications, the post disappears but the "X favourited your status" or "X boosted your status" headers linger around until the page is reloaded. The same happens if the post is deleted remotely, from another browser for example.

This is on v1.2.2

![out](https://cloud.githubusercontent.com/assets/315139/25223815/cd214e34-25bc-11e7-9494-8da8392eb1ee.gif)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I noticed this. I don't know if it helps the programmers to know that reloading the page makes the last bit disappear, but I'll say it just in case.
