### ISSUE TITLE
Content warning and normal text locations and placeholders are confusing to users

### ISSUE THREAD

**Issue by Natouille** [tootsuite/mastodon#2209]
As a user, and as seen and heard by other users, the behavior of the content warning field is really confusing.
**When a user adds a CW, a field pops above the main field, and the user expects the content of this field to be the content that will be hidden.**

And it is logical : think of the human mind. 

- First you warn _("I'm gonna show you / tell you something scary / illegal / bad / nonsense / whatever")_ 
- and then you say / show it.

So it should be the same on the Mastodon UI : 

- first you type your warning _("beware")_ in the main field
- then you click the CW button
- the CW field appears **(best if BELOW the main field)** and you add your sensitive content

**Comment by feth** [comment]
A precision.
The placeholder «Avertissement» (french version) may confuse users. I'd suggest a longer but imperative «Saisissez ici des mots-clefs d'avertissement» (Here, input the warning keywords).

**Comment by Cassolotl** [comment]
I usually do it the other way round. I type something, then I'm like "hey, I should CW this" and I click the CW box, which appears and is empty. So it works for the way my mind works. I hope this option sticks around - but if I'm in the minority that's fine and I'm sure I'd get used to it if it changed!

**Comment by Natouille** [comment]
@feth on my instance, it's written in English (blame the admin ? 😄 )

**Comment by feth** [comment]
![image](https://cloud.githubusercontent.com/assets/554384/25229915/810436d6-25d2-11e7-9660-bdd6cbaa848a.png)

![maxresdefault](https://cloud.githubusercontent.com/assets/554384/25229952/a70ce936-25d2-11e7-92d2-9c41cfae7b28.jpg)

**Comment by Natouille** [comment]
![mastodon_-_parti_pirate_-_2017-04-20_14 08 07](https://cloud.githubusercontent.com/assets/2006947/25229989/cb97f2aa-25d2-11e7-8030-52d624106d86.png)

You were saying ? 🤣

**Comment by wxcafe** [comment]
We didn't find a good translation for Content Warning that was widely understood and well-known in french yet. Please feel free to do a PR on the translation file if you do. That being said, I don't think the Content Warning *text* should be what you had written in the toot box before, cause the new text field specifically says "Content Warning" and is smaller.

**Comment by averageunicorn** [comment]
For me the way it is now is more intuitive (toot goes where it always goes, CW is a separate thing), but I expected the CW box to appear _below_ the toot box, not above. Took me a few seconds to find it the first time.

**Comment by wxcafe** [comment]
That makes more sense to me

**Comment by walf443** [comment]
How about https://github.com/tootsuite/mastodon/pull/2326 ? is it fix this problem?

**Comment by Sylvhem** [comment]
The original placeholder have been recently changed from "Content warning" to "Write your warning here" in an attempt to make the field's purpose clearer (see #4313).

Regarding the original suggestion, I think it would be really confusing as it would mean that the purpose of the main field would change depending on if the CW function was set on or not.

**Comment by nightpool** [comment]
The placement of the text box for the content warning mirrors the placement
of the content warning in the timeline, detailed status view, etc. This
makes it very intuitive to use for many users, unless they haven't seen
content warnings "in the wild" much before they hit the button.

**Comment by wxcafe** [comment]
I think this issue can be closed? It makes no sense to just debate if it's more intuitive to place it on top or in the bottom except if someone with UX expertise can draw a definitive conclusion, and I don't believe anyone in here is such an expert. Since the CW placeholder is more sensible now I believe this issue is as fixed as can be.
