### ISSUE TITLE
Allow pasting images from clipboard as well as uploading image file

### ISSUE THREAD

**Issue by stuartlangridge** [tootsuite/mastodon#221]
It is useful to be able to paste an image from the clipboard to post it (most IM/chat/etc systems support this, such as Telegram, Slack, G+, and the like). Twitter doesn't allow this, and Mastodon doesn't either, which means that one has to save a grabbed image to a temporary file and then load it again to toot it. It would be handy to allow pasting in this situation.

**Comment by geckojsc** [comment]
I think it's just Tweetdeck that doesn't allow this, whereas vanilla Twitter does (tested in Firefox on Windows 10). Anyways I agree it would be very handy. :)

**Comment by seanlinsley** [comment]
It'd still be nice to do this

**Comment by seanlinsley** [comment]
https://mastodon.social/@Viss/1523942
