### ISSUE TITLE
Reserve "abuse" nick to report illegal or abusive toots to instance admin

### ISSUE THREAD

**Issue by woyczek** [tootsuite/mastodon#2211]
Goal :
- protect admin/users from abusive toots and tooters ;
- preserve them from law pursuits

A mainly used nick and way to report directly such toots would be an easier way for all to alert.

**Comment by codl** [comment]
doesn't the report feature already fill that role?

**Comment by wxcafe** [comment]
I believe that reports are enough for this yeah

**Comment by woyczek** [comment]
No, report is not enough, because we would report directly to an instance owner, not to our instance owner.

**Comment by wxcafe** [comment]
when you report, you report to your own instance owner.
