### ISSUE TITLE
Unused 'import EmbeddedStatus' statement

### ISSUE THREAD

**Issue by expenses** [tootsuite/mastodon#2216]
[Line 6 of `/app/assets/javascripts/components/features/status/index.jsx`](https://github.com/tootsuite/mastodon/blob/master/app/assets/javascripts/components/features/status/index.jsx#L6) imports `EmbeddedStatus`, but [it's not defined anywhere](https://github.com/tootsuite/mastodon/search?q=EmbeddedStatus).

I would make a PR to remove it, but I'm curious to know if it was going to be used or not.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I think this is gone now.
