### ISSUE TITLE
Emoji filter should be reset after an emoji has been picked

### ISSUE THREAD

**Issue by lutoma** [tootsuite/mastodon#2217]
If you use the search/filter field in the emoji picker, then select an emoji by clicking on it, and then open the emoji picker again, the emojis are still filtered by the previous search. Most other emoji pickers I've seen so far automatically reset the filter after picking an emoji, which I feel is probably a more useful behaviour.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by expenses** [comment]
I actually think it's more helpful this way than if it reset each time, especially if you :clap: want :clap: to :clap: do :clap: this :clap: stupid :clap: clapping :clap: thing.

**Comment by wxcafe** [comment]
I think if we get keyboard focus on the filter when the picker is opened this problem is moot : you simply have to ctrl+backspace to remove what you last searched for. Since #2179 is already open about this I think this issue can be closed
