### ISSUE TITLE
Unfollowing does not update follows count

### ISSUE THREAD

**Issue by jhauberg** [tootsuite/mastodon#222]
Unfollowing a user does not update the "Follows" count.

Before unfollowing:

![screen shot 2016-11-23 at 11 18 40](https://cloud.githubusercontent.com/assets/1360637/20558096/c461e6fe-b16e-11e6-9e44-5765e0c340d0.png)

After:

![screen shot 2016-11-23 at 11 18 50](https://cloud.githubusercontent.com/assets/1360637/20558105/cd391cd4-b16e-11e6-87f4-e5ae3c41c9cb.png)

**Comment by Gargron** [comment]
I'm pretty sure it just doesn't reload profile information. Like, if you refreshed the page you'd see the new count. I see no reason to do it automatically

**Comment by jhauberg** [comment]
The argument for updating it automatically is, obviously, to always maintain a visually correct state. That's just basic practice for good UX.
