### ISSUE TITLE
Segmentation fault (core dumped) error when trying to update

### ISSUE THREAD

**Issue by owlg** [tootsuite/mastodon#2220]
Error of Segmentation fault (core dumped) shows when trying to update with the latest commit.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by lutoma** [comment]
Could you be more specific about when this error occurs and which program/command prints it? Are you running Mastodon using Docker? Does it happen when migrating the database/precompiling the assets/running yarn/starting the systemd services/docker container?

**Comment by Gargron** [comment]
OOM?

**Comment by owlg** [comment]
The issue seems to have been fixed and I am not facing it anymore. Closing this issue.
