### ISSUE TITLE
Polish Translation Not Enabled

### ISSUE THREAD

**Issue by ashfurrow** [tootsuite/mastodon#2227]
A [user reported](https://github.com/ashfurrow/mastodon/issues/3) that the language dropdown doesn't appear to include a Polish translation, despite the translations existing. I tried adding `:pl` to the [available locales](https://github.com/tootsuite/mastodon/blob/master/config/application.rb#L27) but it didn't work locally:

<img width="451" alt="screen shot 2017-04-20 at 11 32 39 am" src="https://cloud.githubusercontent.com/assets/498212/25239097/162eca84-25bd-11e7-9d34-cd4eb52b796a.png">

If someone could point me in the right direction, I'm happy to submit a pull request to fix this.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
The blank is indeed for polish, but there's a constant that brings in the language labels, and that's missing the pl value. Look in `app/helpers/settings_helper.rb`

**Comment by ashfurrow** [comment]
Cool, thanks!

**Comment by xor256** [comment]
https://github.com/tootsuite/mastodon/issues/2662
this thanslating not appear for users
