### ISSUE TITLE
Error 500 with my notification and profile

### ISSUE THREAD

**Issue by mkody** [tootsuite/mastodon#2233]
My account (only mine for now?) suddenly started to act weird after I've been discussing with an user who just joined my instance.

My notification column (`/api/v1/notifications`), and my profile (`/api/v1/accounts/2/statuses`, `/@kdy`) are returning 500 errors.

This happens on `1.2.2` and `master`.

Here's what I get from the debug log when [opening my profile on the web](https://im-in.space/@kdy).
```
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]   #033[1m#033[36mUser Load (1.2ms)#033[0m  #033[1m#033[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2#033[0m  [["id", 2], ["LIMIT", 1]]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]   #033[1m#033[36mUser Load (1.2ms)#033[0m  #033[1m#033[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2#033[0m  [["id", 2], ["LIMIT", 1]]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]   #033[1m#033[36mAccount Load (1.1ms)#033[0m  #033[1m#033[34mSELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2#033[0m  [["id", 2], ["LIMIT", 1]]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]   #033[1m#033[36mAccount Load (1.1ms)#033[0m  #033[1m#033[34mSELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2#033[0m  [["id", 2], ["LIMIT", 1]]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]   #033[1m#033[36mAccount Load (1.4ms)#033[0m  #033[1m#033[34mSELECT  "accounts".* FROM "accounts" WHERE (lower(accounts.username) = 'kdy') AND "accounts"."domain" IS NULL LIMIT $1#033[0m  [["LIMIT", 1]]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]   #033[1m#033[36mAccount Load (1.4ms)#033[0m  #033[1m#033[34mSELECT  "accounts".* FROM "accounts" WHERE (lower(accounts.username) = 'kdy') AND "accounts"."domain" IS NULL LIMIT $1#033[0m  [["LIMIT", 1]]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]   #033[1m#033[36mAccount Exists (1.4ms)#033[0m  #033[1m#033[34mSELECT  1 AS one FROM "accounts" INNER JOIN "blocks" ON "accounts"."id" = "blocks"."target_account_id" WHERE "blocks"."account_id" = $1 AND "accounts"."id" = $2 LIMIT $3#033[0m  [["account_id", 2], ["id", 2], ["LIMIT", 1]]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]   #033[1m#033[36mAccount Exists (1.4ms)#033[0m  #033[1m#033[34mSELECT  1 AS one FROM "accounts" INNER JOIN "blocks" ON "accounts"."id" = "blocks"."target_account_id" WHERE "blocks"."account_id" = $1 AND "accounts"."id" = $2 LIMIT $3#033[0m  [["account_id", 2], ["id", 2], ["LIMIT", 1]]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]   #033[1m#033[36mStatus Load (15.1ms)#033[0m  #033[1m#033[34mSELECT  "statuses"."id", "statuses"."updated_at" FROM "statuses" WHERE "statuses"."account_id" = $1 ORDER BY id desc, "statuses"."id" DESC LIMIT $2#033[0m  [["account_id", 2], ["LIMIT", 20]]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]   #033[1m#033[36mStatus Load (15.1ms)#033[0m  #033[1m#033[34mSELECT  "statuses"."id", "statuses"."updated_at" FROM "statuses" WHERE "statuses"."account_id" = $1 ORDER BY id desc, "statuses"."id" DESC LIMIT $2#033[0m  [["account_id", 2], ["LIMIT", 20]]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]   #033[1m#033[36mAccount Load (1.5ms)#033[0m  #033[1m#033[34mSELECT "accounts".* FROM "accounts" WHERE "accounts"."id" IN (2, 9838, 2124, 8, 4262, 3420, 1142)#033[0m
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]   #033[1m#033[36mAccount Load (1.5ms)#033[0m  #033[1m#033[34mSELECT "accounts".* FROM "accounts" WHERE "accounts"."id" IN (2, 9838, 2124, 8, 4262, 3420, 1142)#033[0m
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] method=GET path=/@kdy format=html controller=AccountsController action=show status=500 error='ActionView::Template::Error: undefined method `acct' for nil:NilClass' duration=215.85 view=0.00 db=21.59
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] method=GET path=/@kdy format=html controller=AccountsController action=show status=500 error='ActionView::Template::Error: undefined method `acct' for nil:NilClass' duration=215.85 view=0.00 db=21.59
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] ActionView::Template::Error (undefined method `acct' for nil:NilClass):
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] ActionView::Template::Error (undefined method `acct' for nil:NilClass):
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     17:       %p{ style: 'margin-bottom: 0' }<
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     17:       %p{ style: 'margin-bottom: 0' }<
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     18:         %span.p-summary>= "#{status.spoiler_text} "
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     18:         %span.p-summary>= "#{status.spoiler_text} "
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     19:         %a.status__content__spoiler-link{ href: '#' }= t('statuses.show_more')
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     19:         %a.status__content__spoiler-link{ href: '#' }= t('statuses.show_more')
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     20:     %div.e-content{ style: "display: #{status.spoiler_text? ? 'none' : 'block'}; direction: #{rtl?(status.content) ? 'rtl' : 'ltr'}" }= Formatter.instance.format(status)
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     20:     %div.e-content{ style: "display: #{status.spoiler_text? ? 'none' : 'block'}; direction: #{rtl?(status.content) ? 'rtl' : 'ltr'}" }= Formatter.instance.format(status)
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     21:
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     21:
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     22:   - unless status.media_attachments.empty?
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     22:   - unless status.media_attachments.empty?
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     23:     .status__attachments
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]     23:     .status__attachments
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2]
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/lib/formatter.rb:79:in `block (2 levels) in link_mentions'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/lib/formatter.rb:79:in `block (2 levels) in link_mentions'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/lib/formatter.rb:79:in `block in link_mentions'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/lib/formatter.rb:79:in `block in link_mentions'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/lib/formatter.rb:77:in `gsub'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/lib/formatter.rb:77:in `gsub'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/lib/formatter.rb:77:in `link_mentions'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/lib/formatter.rb:77:in `link_mentions'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/lib/formatter.rb:19:in `format'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/lib/formatter.rb:19:in `format'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/views/stream_entries/_simple_status.html.haml:20:in `_app_views_stream_entries__simple_status_html_haml__3176130747480025464_70230108986900'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/views/stream_entries/_simple_status.html.haml:20:in `_app_views_stream_entries__simple_status_html_haml__3176130747480025464_70230108986900'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/views/stream_entries/_status.html.haml:29:in `_app_views_stream_entries__status_html_haml___2067982833364062459_70230108708040'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/views/stream_entries/_status.html.haml:29:in `_app_views_stream_entries__status_html_haml___2067982833364062459_70230108708040'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/views/accounts/show.html.haml:24:in `_app_views_accounts_show_html_haml__400103600230290589_47457397666860'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/views/accounts/show.html.haml:24:in `_app_views_accounts_show_html_haml__400103600230290589_47457397666860'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/controllers/concerns/localized.rb:24:in `block in set_locale'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/controllers/concerns/localized.rb:24:in `block in set_locale'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/controllers/concerns/localized.rb:23:in `set_locale'
Apr 20 17:37:23 SpaceCore bundle[11401]: [a3aceecf-0866-434d-9e8c-abfa8aa05da2] app/controllers/concerns/localized.rb:23:in `set_locale'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
Looks like some problematic status broke the mention-parsing code. It looks like it's trying to parse out the fully-qualified user name (name@instance.com) but it's failing. Do you have access to get any recent status? Anything unusual you tooted recently, especially with an @ sign?

**Comment by mkody** [comment]
Well, here's an extract of what I've got from the Postgres database coming from my id.  
The first row is the last status where I noticed the 500 errors, the last row was when it was still working fine (I was checking my profile at that time).

_(Spaces right after the `@` are mine, to not ping GitHub users.)_

|   id   | account_id |  text                                                                                                                                                                                           |         created_at         | in_reply_to_id | reblog_of_id | visibility | in_reply_to_account_id | application_id | reply | 
|--------|------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------|----------------|--------------|------------|------------------------|----------------|-------|
| 147722 |          2 |                                                                                                                                                                                                 | 2017-04-20 18:16:38.541829 |                |       147715 |          0 |                        |                | f     |
| 147716 |          2 |                                                                                                                                                                                                 | 2017-04-20 18:16:17.98282  |                |       147684 |          0 |                        |                | f     |
| 146812 |          2 | @ jansegers@ mstdn.nl Please restart your browser, everything looks fine here.                                                                                                                  | 2017-04-20 16:54:48.317363 |         146734 |              |          3 |                  10241 |              1 | t     |
| 146721 |          2 | @ jansegers@ mstdn.nl Well, now I see that the mail was actually sent (there was a weird bug before). I also made sure that Outlook emails wouldn't be blocked so that's not a problem either.  | 2017-04-20 16:46:21.975527 |         146703 |              |          3 |                  10241 |              1 | t     |
|        |            | I've enabled your account manually, you can now login.                                                                                                                                          |                            |                |              |            |                        |                |       |

**Comment by ashfurrow** [comment]
(Just gonna do some rubber duck debugging.)

So here's the code that's crashing:

```rb
  def link_mentions(html, mentions)
    html.gsub(Account::MENTION_RE) do |match|
      acct    = Account::MENTION_RE.match(match)[1]
      mention = mentions.find { |item| TagManager.instance.same_acct?(item.account.acct, acct) }

      mention.nil? ? match : mention_html(match, mention.account)
    end
  end
```

Specifically `item.account.acct` is crashing because `account` is `nil`. Hmm. So that would mean a mention has a `nil` account. Anyone know how that could happen? Looks like the most recent status is a reblog/boost of someone else, maybe that account has been deleted somehow? I'll play around locally and try to reproduce.

**Comment by mkody** [comment]
I've made a backup of my last 200 statuses and deleted the statuses made today (total of 23).
And yeah, it's back now. It's not coming from the last 10 (so it did take some time), I'll dig until I find the culprit!

**Comment by ashfurrow** [comment]
Cool! Nice solution!

**Comment by mkody** [comment]
Oh, before starting to restore anything, I see that my notification column is still broken. So I guess the toot was in my notifications too.

**Comment by mkody** [comment]
So some of my discussion with `@jansegers@mstdn.nl` (4 out of 7 toots from me) does make my profile crash. Here's the insert lines (nothing too confidential here).

```
INSERT INTO statuses (id, uri, account_id, text, created_at, updated_at, in_reply_to_id, reblog_of_id, url, sensitive, visibility, in_reply_to_account_id, application_id, spoiler_text, reply, favourites_count, reblogs_count, language) VALUES (146545, NULL, 2, '@jansegers@mstdn.nl ... You know you don''t have to use hashtags because we''re talking in direct messages, right..?', '2017-04-20 16:25:41.770407', '2017-04-20 16:25:41.770407', 146539, NULL, NULL, false, 3, 10221, 1, '', true, 0, 0, 'en');

INSERT INTO statuses (id, uri, account_id, text, created_at, updated_at, in_reply_to_id, reblog_of_id, url, sensitive, visibility, in_reply_to_account_id, application_id, spoiler_text, reply, favourites_count, reblogs_count, language) VALUES (146521, NULL, 2, '@jansegers@mstdn.nl I''m looking into why your registration didn''t work, please wait.', '2017-04-20 16:23:46.992934', '2017-04-20 16:23:46.992934', 146510, NULL, NULL, false, 1, 10221, 1, '', true, 0, 0, 'en');

INSERT INTO statuses (id, uri, account_id, text, created_at, updated_at, in_reply_to_id, reblog_of_id, url, sensitive, visibility, in_reply_to_account_id, application_id, spoiler_text, reply, favourites_count, reblogs_count, language) VALUES (146297, NULL, 2, '@jansegers@mstdn.nl Did you check the spam folder then?', '2017-04-20 16:06:24.758363', '2017-04-20 16:06:24.758363', 146293, NULL, NULL, false, 3, 10221, 1, '', true, 0, 0, 'no');

INSERT INTO statuses (id, uri, account_id, text, created_at, updated_at, in_reply_to_id, reblog_of_id, url, sensitive, visibility, in_reply_to_account_id, application_id, spoiler_text, reply, favourites_count, reblogs_count, language) VALUES (146204, NULL, 2, '@jansegers@mstdn.nl You can join the instance without any invitation.', '2017-04-20 15:57:12.318604', '2017-04-20 15:57:12.318604', 146163, NULL, NULL, false, 2, 10221, 1, '', true, 0, 0, 'en');
```

**Comment by Magiccamera** [comment]
Can you enlighten me as to how you went about checking and deleting these statuses. I'm having 500 error for all users on the instance and not sure how to properly troubleshoot it.

**Comment by ashfurrow** [comment]
Yikes, that sucks. I'm not sure what @mkody's process was, I think it may have been to delete recent toots until things started to work. (Make sure to make a back up first!)

I'm going to ping @Gargron since this sounds like a serious problem (I looked but couldn't figure out the cause of the issue).

**Comment by mkody** [comment]
If it's for all your users, this might not be related to my issue, so make a backup of your daa.
But to do that you first need to login as the postgres user `su postgres`.

Let's make a backup of the tables, here's for statuses:
`pg_dump --table=statuses --column-inserts mastodon_production > backup.sql`

Now, to access the DB: `psql mastodon_production`  
And now you can do Postgres stuff:
- To see all tables: `\dt`
- To see details about a table: `\d <TABLE>`, like `\d statuses`
- List toots from a user: `SELECT * FROM statuses WHERE account_id = <ACCOUNT ID>`
- Delete an entry `DELETE FROM statuses WHERE id = <TOOT ID>`  
  Example with date: `DELETE FROM statuses WHERE account_id = 2 AND created_at >= '2017-04-20'::date;`
- Quit with `\q`

**Comment by Magiccamera** [comment]
I'm stumped still getting 500 error and believe it has something to do with statuses.

**Comment by halest** [comment]
It seems I can confirm this issue, same happening on my instance, but I just wanted to add that interestingly Tusky displays them correctly. Just in case that's useful information.

**Comment by thor-the-norseman** [comment]
I'm also experiencing this issue, with the exact same part of the code. I can't see any of their posts in the web app, and when I view their profile at /@account_name, there's a 500 error. So far, the two accounts I've been able to track down that have this problem both seem to share the trait that they have an uppercase letter as the first character in their username.

**Comment by thor-the-norseman** [comment]
Our instance began to see this issue after a migration from a Docker container at one VPS to direct installation on another. Somehow, the Home timeline wasn't anywhere in the PostgreSQL data, and after failing to figure out where that was being stored, we just decided to wait until it had filled up again, since nothing else seemed to be gone. It may be a coincidence that we came across this issue after that migration.

**Comment by thor-the-norseman** [comment]
Another related error for another profile:

```May  6 20:20:17 snabeltann bundle[32801]: [7b340491-2953-48a0-897c-d325dc97e993] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=500 error='ActionView::Template::Error: undefined method `object_type' for nil:NilClass' duration=179.06 view=0.00 db=3.05
May  6 20:20:17 snabeltann bundle[32801]: [7b340491-2953-48a0-897c-d325dc97e993]
May  6 20:20:17 snabeltann bundle[32801]: [7b340491-2953-48a0-897c-d325dc97e993] ActionView::Template::Error (undefined method `object_type' for nil:NilClass):
May  6 20:20:17 snabeltann bundle[32801]: [81afa7c9-7c66-4d0d-af36-ce172451c2cb] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::TimelinesController action=home status=200 duration=205.41 view=145.99 db=18.46
May  6 20:20:17 snabeltann bundle[32801]: [7b340491-2953-48a0-897c-d325dc97e993]     1: collection @notifications
May  6 20:20:17 snabeltann bundle[32801]: [7b340491-2953-48a0-897c-d325dc97e993]     2: extends 'api/v1/notifications/show'
May  6 20:20:17 snabeltann bundle[32801]: [7b340491-2953-48a0-897c-d325dc97e993]
May  6 20:20:17 snabeltann bundle[32801]: [7b340491-2953-48a0-897c-d325dc97e993] app/lib/tag_manager.rb:101:in `url_for'
May  6 20:20:17 snabeltann bundle[32801]: [7b340491-2953-48a0-897c-d325dc97e993] app/views/api/v1/statuses/_mention.rabl:1:in `block in eval_source'
May  6 20:20:17 snabeltann bundle[32801]: [7b340491-2953-48a0-897c-d325dc97e993] app/views/api/v1/notifications/show.rabl:10:in `block in eval_source'
May  6 20:20:17 snabeltann bundle[32801]: [7b340491-2953-48a0-897c-d325dc97e993] app/views/api/v1/notifications/index.rabl:3:in `_app_views_api_v__notifications_index_rabl___1100746285837587180_70306780975080'```

**Comment by thor-the-norseman** [comment]
The error I had earlier:

```
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51] method=GET path=/@kvelland format=html controller=AccountsController action=show status=500 error='ActionView::Template::Error: undefined method `acct' for nil:NilClass' duration=144.72 view=0.00 db=10.95
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51]
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51] ActionView::Template::Error (undefined method `acct' for nil:NilClass):
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51]     17:       %p{ style: 'margin-bottom: 0' }<
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51]     18:         %span.p-summary>= "#{status.spoiler_text} "
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51]     19:         %a.status__content__spoiler-link{ href: '#' }= t('statuses.show_more')
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51]     20:     %div.e-content{ lang: status.language, style: "display: #{status.spoiler_text? ? 'none' : 'block'}; direction: #{rtl?(status.content) ? 'rtl' : 'ltr'}" }= Formatter.instance.format(status)
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51]     21:
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51]     22:   - unless status.media_attachments.empty?
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51]     23:     .status__attachments
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51]
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51] app/lib/formatter.rb:80:in `block (2 levels) in link_mentions'
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51] app/lib/formatter.rb:80:in `block in link_mentions'
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51] app/lib/formatter.rb:78:in `gsub'
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51] app/lib/formatter.rb:78:in `link_mentions'
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51] app/lib/formatter.rb:19:in `format'
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51] app/views/stream_entries/_simple_status.html.haml:20:in `_app_views_stream_entries__simple_status_html_haml__1934776329676169112_70306482949880'
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51] app/views/stream_entries/_status.html.haml:29:in `_app_views_stream_entries__status_html_haml___2379902386035705625_70306771188460'
May  5 21:57:18 snabeltann bundle[32801]: [8fc6876b-b2e6-4121-bc55-3916bac39c51] app/views/accounts/show.html.haml:24:in `_app_views_accounts_show_html_haml__3448706669191634009_70306781626120'
```

**Comment by vincib** [comment]
The error from "thor-the-norseman commented on May 6" above seems to be different, crashing in another location.
I have it ~4000 times per hours on mamot.fr :/ 

```
[668fead2-c680-4597-b73e-5bb6dc3f4f3a] method=GET path=/api/v1/timelines/public format=html controller=Api::V1::Timelines::PublicController action=show status=500 error='ActionView::Template::Error: undefined method `object_type' for nil:NilClass' duration=155.85 view=0.00 db=5.39
[668fead2-c680-4597-b73e-5bb6dc3f4f3a]   
[668fead2-c680-4597-b73e-5bb6dc3f4f3a] ActionView::Template::Error (undefined method `object_type' for nil:NilClass):
[668fead2-c680-4597-b73e-5bb6dc3f4f3a]     1: collection @statuses
[668fead2-c680-4597-b73e-5bb6dc3f4f3a]     2: extends('api/v1/statuses/show')
[668fead2-c680-4597-b73e-5bb6dc3f4f3a]   
[668fead2-c680-4597-b73e-5bb6dc3f4f3a] app/lib/tag_manager.rb:104:in `url_for'
[668fead2-c680-4597-b73e-5bb6dc3f4f3a] app/views/api/v1/statuses/_mention.rabl:1:in `block in eval_source'
[668fead2-c680-4597-b73e-5bb6dc3f4f3a] app/views/api/v1/timelines/base/show.rabl:3:in `_app_views_api_v__timelines_base_show_rabl___720905909789402881_47447390839340'

```

**Shall we open a new bug for this one too?**

**Comment by vincib** [comment]
ok, found the culprit for the message above (that a bot was trying to download in a loop, hence the "4000 times per hour :/"

Crash 500: https://mamot.fr/api/v1/timelines/public?max_id=539729&limit=1
OK 200: https://mamot.fr/api/v1/timelines/public?max_id=539724&limit=1

Do you want the result of 
`select * from statuses where id between 539725 and 539729`
?

**Comment by Gargron** [comment]
@vincib I'd like the result of that, sure - but most likely the problem is in some referenced entity from another table having been deleted. This is something that #3562 was meant to address

**Comment by mkody** [comment]
Closing since there's nothing new.
