### ISSUE TITLE
Prefix rails traces lines

### ISSUE THREAD

**Issue by Champomix** [tootsuite/mastodon#2238]
Is it possible to add a specific string at the beginning of each trace line to identify mastodon rails logs ?

For example [MASTODON][5287fe5d-5d9d-40fe-97fd-f73eb7c247b6] method=GET path=/api/v1/timelines/public format=html controller=Api::V1::TimelinesController action=public status=200 duration=687.98 view=524.05 db=22.63

With this feature i could archive mastodon traces more easyly with a grep on syslog file.

* * * *

**Comment by Gargron** [comment]
You can filter by systemd unit with `journalctl -u mastodon-web` (or mastodon-streaming, etc)

**Comment by Gargron** [comment]
Generally these settings are not on application level, but systemd service definition level, so up to you.

**Comment by Champomix** [comment]
Tks U, this is perfect for me :)
