### ISSUE TITLE
List of favorite hashtags/people

### ISSUE THREAD

**Issue by MaiaDereva** [tootsuite/mastodon#2239]
Hi! Thank you for this wonderful tool!
What do you think to add the possibility to manage a list of favorite hashtags and people that could appear in the first column under the toot zone? So we could easily click on those links and see the result in the 4th columns...

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sull** [comment]
I had exact same thought. That space is begging for some useful features. I would love to make it a space to install community created add-ons (widgets).

**Comment by donnerkarlson** [comment]
could be implemented with #1096

**Comment by MaiaDereva** [comment]
Oh yes @sull, widgets would be great!
OK @donnerkarlson, so I close this one.
See #1096
