### ISSUE TITLE
Automatic actions according user defined mask

### ISSUE THREAD

**Issue by Zenithar** [tootsuite/mastodon#2241]
Hello,

As a user, I could define user mask, so that default action should be applyied.

Ex:
*@pawoo.net => mute
*@mamot.fr => follow back

Thx

**Comment by raf64flo** [comment]
List of actions should be defined, but I agree. +1

**Comment by bmann** [comment]
Seems like an interesting add on, not a core feature.

**Comment by expenses** [comment]
What is a 'user mask'?

**Comment by wxcafe** [comment]
This sounds like a feature that would be great as an add-on yeah. We'd prefer if the UI and preferences menu stayed uncluttered, and this is definitely a thing that would clutter them and only be useful to a few users. As such, i'm closing this issue
