### ISSUE TITLE
Create a guide (list of localizable files) for translators

### ISSUE THREAD

**Issue by Artoria2e5** [tootsuite/mastodon#2249]
Before #1241 moves into place, it may be good to at least provide translators with a simple guide to localization. This should include:

* A list of localizable files. People keep missing things, and that is not good. Hmm, I guess searching for `fr` or `en` in GitHub's filename search can give a quick estimate for this?
* Some instruction for enabling newly localized files.
* Some tips regarding common pitfalls like plural handling.

* * * *

Yes, I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by yookoala** [comment]
I think there's already a page in the documentation repository:
https://github.com/tootsuite/documentation/blob/master/Contributing-to-Mastodon/Translating.md

But still, not everyone read it before doing translation.

**Comment by bmann** [comment]
Yep, let's close this here and discuss further in documentation.

**Comment by Artoria2e5** [comment]
Oops… didn't see that one.
