### ISSUE TITLE
Display usernames in a way that avoids character spoofing

### ISSUE THREAD

**Issue by webbedspace** [tootsuite/mastodon#225]
It's alarmingly common on Twitter for other users' account names to be spoofed by registering a similar username and changing lowercase L's to uppercase I's, e's to a's, and so forth. This hoaxing can be slightly hampered by using a fixed-width serif font for usernames at all times.

**Comment by Gargron** [comment]
Not sure if serif, maybe monospace? Since fonts made for code place a lot of emphasis on distinguishing characters. That being said I don't know how it'd look visually, will need to give it a try

**Comment by TazeTSchnitzel** [comment]
Could use a sans-serif font that's less prone to it. IIRC Verdana has bars on its capital I.

**Comment by Gargron** [comment]
We're using Roboto and we already load a monospace version of it

**Comment by Gargron** [comment]
It seems like this is not really worth the effort, the problem this would solve is really narrow and rare and exists anywhere where monospace is not used *anyway*.

**Comment by webbedspace** [comment]
I assume it's closed as "completed" because the "Closed as invalid" GitHub setting didn't exist in 2017, and it would've been used for this back then.
