### ISSUE TITLE
Toggle for boosts alongside saves and follows in Notifications filters

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#2260]
![screen shot 2017-04-21 at 14 09 45](https://cloud.githubusercontent.com/assets/6607512/25278742/45a4baf0-269c-11e7-95d5-1af88aaa64db.png)

There's toggles for notifications for saves and new followers, but nothing for boosts. I'd like to turn off boost notifications!

* * * *

- [Yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by hoodiek** [comment]
this already exists. that notification options section can be scrolled down, and boosts are at the bottom.

**Comment by Cassolotl** [comment]
Oh my gosh, I tried scrolling and it didn't work! But now it does! Augh. Thanks @hoodiek !

**Comment by hoodiek** [comment]
np @Cassolotl
