### ISSUE TITLE
"window.opener" still set for new window because of typo

### ISSUE THREAD

**Issue by hirataya** [tootsuite/mastodon#2261]
There is a typo in [detailed_status.jsx](https://github.com/tootsuite/mastodon/blob/bfbc2ca0d8dcef47f8581585b42f13b6b4c933d9/app/assets/javascripts/components/features/status/components/detailed_status.jsx#L56). Users cannot avoid setting window.opener for new window. (It should be "noopener")

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on v1.2.2 and master

**Comment by expenses** [comment]
I can't see `window.opener` in the file. Is the bug fixed?
