### ISSUE TITLE
Mandatory Dependence on the PostgreSQL is a Show-stopper

### ISSUE THREAD

**Issue by martinvahi** [tootsuite/mastodon#2262]
It seems that the dependence on the 
operating system library, the libpg, is a
[show-stopper](http://stackoverflow.com/questions/6040583/cant-find-the-libpq-fe-h-header-when-trying-to-install-pg-gem) that forbids the
building/installation of the pg gem.

    gem install pg  # tends to fail

The dependence on the **pg** gem makes
the mastodon unusable, if the **pg** gem is the mastodon's mandatory dependency.

Proposal: 

- Make the **pg** an optional dependency.

- Make the **sqlite3** gem as the default persistence provider. 

Those, who find the sqlite3 to be too slow, can later
tweak their installation by migrating to something else,
the **pg** or **rethinkdb** or whatever else the persistence 
layer of the mastodon supports, but the default
code should work "straight out of GitHub" by calling the 

    bundle install

Besides, the PostgreSQL database engine requires
that a web application is given a username and password
or may be some other means to "log in" and that is cumbersome, 
when one just wants to testrun the mastodon to take a peek, what
the application feels like.

**Comment by mjankowski** [comment]
There are a bunch of things which are coupled tightly enough to PG that it will remain a hard requirement for the foreseeable future.

Is your concern that postgres is too big a burden for developers who want to contribute, or for admins who want to operate their own instances?

If you are just wanting to try out the app, I think creating an account on an existing instance is much easier than setting it up locally as a developer.

**Comment by Gargron** [comment]
(You can also just use Docker)

**Comment by martinvahi** [comment]
@mjankowski  Not only developers, but also people, who want to expand 
the Mastodon network by installing their own instance of it 
on some more modern operating system like the [GenodeOS](https://genode.org/news/road-map-for-2016) or [Minix3](http://www.minix3.org/) or just some more esoteric 
operating system like the [GNU Hurd](https://www.debian.org/ports/hurd/). 
It just so happens that the NSA and alike lack the hacking tools for the
less popular operating systems and the GenodeOS, unlike Linux, 
uses also a totally new architecture, which ups the game at security front
even, when NSA and alike create tools for those operating systems (which they most likely will do).


@Gargron  Thank You for the recommendation, but that dirty hack is just a dirty 
workaround, not a solution. I've been [trying to get an overview](http://www.softf1.com/cgi-bin/tree1/technology/flaws/silktorrent.bash/wiki?name=List+of+Similar+Projects) 
of the various anti-1984-software projects and my observation about the projects
is that usually the projects stem from some end-user use scenario, which has 
a relatively huge amount of application components that all are exhaustive, huge, 
projects in their own right, if done properly, and then in stead of picking a narrow
task and actually creating a really fine, reusable, well crafted, component, like 
the [Tor Project](https://www.torproject.org/) has done, the dependencies of 
the anti-1984-application are met by cobbling together some "minimum_viable_products",
which actually loose their "minimum_viability" property very quickly as technology
advances, turning the anti-1984-application to a just-a-nice-user-experience-application.

For example, the [Freenet](https://freenetproject.org/) project started during a time,
when the [Tor Project](https://www.torproject.org/) was really not yet a viable option.
So the Freenet [founder](https://en.wikipedia.org/wiki/Ian_Clarke_(computer_scientist)) had to create some anonymization network implementation
himself and clearly the time that he could spend on it was 
divided between other tasks that needed to be completed to make the Freenet "boot".
Another failure of the Freenet is that it is implemented in Java, which 
is a huge security hole and a closed blob even, when source is available,
because the Java is a typical deadlines-and-corporate-processes-first-technical-quality-second
type of project, as is the Microsoft-Java-substitute, the [C#](https://dotnetfoundation.org/), 
which got created after the Sun executives used lawyers to restrict 
Microsoft from using Java. Microsoft's motivation for using Java
was pretty much the same that Google had, when they chose 
to re-implement it as the main programming language for the Android
Linux distribution: the [Java had great marketing](https://www.youtube.com/watch?v=Mk3qkQROb_k)
and many developers were well familiar with it, while the Java allowed
amateurs and sloppy developers to have less problems with the 
various C/C++ memory related problems. For historic reference I mention 
that the Google and the Microsoft could have just re-implemented 
Pascal or Delphi, just like the [Free_Pascal/Lazarus](https://www.lazarus-ide.org/) project has done later.

Summary: **most anti-1984-software projects fail due to poor planning of their dependencies
and due to the effort to create a nice end user application in stead of creating 
reusable and very carefully crafted, security wise strong, components for 
ordinary applications software programmers to reuse.**

For example, the amount of web applications that run on the 
Tor network far exceeds whatever the Freenet founder was able to 
write on his own. Tor is a really well focused, reusable, carefully crafted,
universal component that does not even try to solve some task of an 
end user application. A lesson for a social networking system might be
that in stead of trying to center everything around an end-user-application,
a social networking API and a console library should be defined, which 
has a sample implementation and which can be re-implemented by 
other developers by using programming languages and dependencies
of their choice. Some really elaborate components might be offered
by the core project, just like the Tor Project offers its tor network
implementation, but those components should then be REALLY-REALLY-PORTABLE
and clearly an approach, that take-Docker-and-run-that will not cut it for
those components.

So, thank You for reading and the Mastodon developers might
also ask themselves, how does the Mastodon differ from a 
set of RSS-enabled blogs and forums combined with RSS-readers. 

With direct, but well-wishing feedback,
M.V.
