### ISSUE TITLE
Be able to translate Emojione

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#2263]
This will probably not be possible, because I can't find any translations at https://github.com/Ranks/emojione, but I think it's necessary that at least the category descriptions, the initial hover text (insert emoji) and 'Search...' of Emojione can be translated. The shortcodes are also in English, but this will probably break a lot of stuff, so that is probably out of the question.

**Comment by expenses** [comment]
The 'insert emoji' text is already localizable, working on a PR for the 'Search' text now.

**Comment by jeroenpraat** [comment]
Wow, that is quick. Thanks a lot @expenses !
