### ISSUE TITLE
I'm seeing a toot from a user I don't follow

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#2264]
![screen shot 2017-04-21 at 15 24 18](https://cloud.githubusercontent.com/assets/6607512/25281975/01f0a732-26a7-11e7-93af-9b87fd952a36.png)

I'm @cassolotl@cybre.space - http://cybre.space/@cassolotl

The user I'm seeing that I don't follow is https://mastodon.social/@goldie_ice - and the toot I'm seeing is https://mastodon.social/users/goldie_ice/updates/2012486

I'm not seeing any more recent toots by that user.

I reloaded the page to make sure it wasn't a boost by a person I follow that they undid.

Edit 2017-04-30: Could be related to #1601.

* * * *

- [Yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by lutoma** [comment]
Apparently, if you follow someone, they toot something (which then shows up in your Home timeline), and you then unfollow them, the previous toots will remain in the home timeline. Could that have been the case here, or did you never follow that person?

**Comment by Cassolotl** [comment]
@lutoma Nope, I've never followed that person and hadn't unfollowed them recently. I didn't recognise their avatar or username at all!

**Comment by nightpool** [comment]
yikes! maybe someone boosted that toot and then you unfollowed them? or
they boosted it but then something weird happened and it bugged out?

Let us know if there's debugging information we could provide here.

**Comment by Cassolotl** [comment]
I don't remember unfollowing anyone just before the post appeared or just after or anything. I am really not sure what it's doing there! :S I guess we can't replicate it so I'll keep an eye out for if it happens again. :)

**Comment by mkosler** [comment]
I don't have anything to contribute other than saying there might be something wrong with that particular account. There was a lot of chatter from the new influx of Spanish speaking users talking about that account, so maybe they were getting a similar bug? I can only glean so much from pasting snippets into Google Translate ;P

**Comment by Cassolotl** [comment]
>There was a lot of chatter from the new influx of Spanish speaking users talking about that account, so maybe they were getting a similar bug?

Huh, interesting! That sounds like a useful contribution.

**Comment by nightpool** [comment]
Some more info! clicking on the "followers" page for the user in question in the cybre.space web ui throws a 500 error: https://cybre.space/web/accounts/433/followers

**Comment by kensoh** [comment]
Am also experiencing this. Not critical for me, just adding on the info for ease of debugging. My ID is @ken@mastodon.network. The toot is from @wegge@mastodon.technology. 1 observation is one of his follower is someone I follow @jd@soc.ialis.me.

Maybe somehow @jd@soc.ialis.me boosted but the @jd@soc.ialis.me boosted label did not show up. Maybe he boosted and unboost? Btw thank you to Mastodon maintainers and contributors! It is simply amazing a project of this scale and rapid growth is supported through an open-source community of contributors.

![sample snapshot](https://raw.githubusercontent.com/tebelorg/TA.Dump/master/mastodon-2264.png)

**Comment by Cassolotl** [comment]
I don't see how I can duplicate this and it's probably the boost-unboost known not-a-bug-honest thing, so I will close this. :)
