### ISSUE TITLE
Bio text contains html / is longer than 160 chars

### ISSUE THREAD

**Issue by celesteh** [tootsuite/mastodon#2265]
This bug raised two separate issues: https://github.com/tootsuite/mastodon/issues/2115 One of which was HTML in statuses and the other was HTML in bios.

Non-plain text bios do not play well with GNU Social, which displays them as if they are plain text, thus exposing all of the html code. Many GNU Social instances end up truncating bios, as they are too long when the HTML is included.

**Comment by Gargron** [comment]
The GNU social HTML in bios thing was resolved, length differences between instances is more of a courtesy thing.
