### ISSUE TITLE
Boolean parameters makes confusing

### ISSUE THREAD

**Issue by tsuwatch** [tootsuite/mastodon#2267]
https://github.com/tootsuite/documentation/blob/last-mastodon-state/Using-the-API/API.md#timelines

For example, https://github.com/tootsuite/mastodon/blob/2c0d756ad942ee19c4f6dd18c9769b6649c2d15f/app/models/status.rb#L127
Can not set `false` explicitly.
If set `local` parameter, it will always be true.
`'false'` is true.

I suggest using `ActiveModel::Type::Boolean.new.cast(local)`, or should be specified more detail in the document.
Otherwise, can not understand.

Any thoughts?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Fixed by #6575
