### ISSUE TITLE
"/timelines/public" endpoint leaking public account entity

### ISSUE THREAD

**Issue by DanielGilbert** [tootsuite/mastodon#2273]
Hi folks!

## Issue

I planned to work on a federated user search, so that you can find people based on the stuff they've written in their bio (to connect with the folks you are interested in and which are like-minded). For that, I'd need the `account` entity of a given user on a given instance.

I checked the accounts endpoint, and performed a test on my public account:

`https://soshl.one/api/v1/accounts/1`
```
{
	"error": "The access token is invalid"
}
```
I almost gave up when I realized that the endpoint is protected by authorization.

However, I checked the public timeline of my instance, and found the `account` entity in question:

`https://soshl.one/api/v1/timelines/public`
```
{
		"id": 1626,
		"created_at": "2017-04-21T15:59:01.427Z",
		"in_reply_to_id": null,
		"in_reply_to_account_id": null,
		"sensitive": false,
		"spoiler_text": "",
		"visibility": "public",
		"application": null,
		"account": {
			"id": 1,
			"username": "MrGilbert",
			"acct": "MrGilbert",
			"display_name": "Mr. Gilbert",
			"locked": false,
			"created_at": "2017-04-19T12:47:48.387Z",
			"followers_count": 6,
			"following_count": 32,
			"statuses_count": 37,
			"note": "¯\\_( ･ө･ )_/¯ || Unity 3D ||  .NET || Evolutionary Humanism || :flag_de: :flag_eu:  :flag_um:",
			"url": "https://soshl.one/@MrGilbert",
			"avatar": "https://soshl.one/system/accounts/avatars/000/000/001/original/e689cc23e167205f.jpg?1492626140",
			"avatar_static": "https://soshl.one/system/accounts/avatars/000/000/001/original/e689cc23e167205f.jpg?1492626140",
			"header": "https://soshl.one/headers/original/missing.png",
			"header_static": "https://soshl.one/headers/original/missing.png"
		},
		"media_attachments": [],
		"mentions": [],
		"tags": [],
		"uri": "tag:soshl.one,2017-04-21:objectId=1626:objectType=Status",
		"content": "<p>ok, and back to normal. :)</p>",
		"url": "https://soshl.one/@MrGilbert/1626",
		"reblogs_count": 0,
		"favourites_count": 0,
		"reblog": null
	},
```

So, by monitoring all instances, I could build up a quite sufficient database after 24 hours. Which would be awesome for my use-case, but I'm not sure if that's intended.

## Suggestion
It would be good to unify the endpoints at this point. For that, I've the following suggestion

- Open access to  `/api/v1/accounts/:id` route on **public**(!) profiles.
- _(Optional)_ Disallow exposing the `account` entity to non-authenticated authorities if the account is public - however, we would then need to figure out which data is actually necessary to be put into the `account` entity on the `/timelines/public` endpoint.

Any thoughts on this one? Or isn't it an issue at all, but on purpose? I would be fine with that, too.

### Disclaimer
The tests where performed on my own account, and for verification purpose also on mastodon.social

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by DanielGilbert** [comment]
I would like to add a small follow up here:

From what I can see, the OStatus feed from each user already contains the `note` part of the account. By accessing the public timeline and the corresponding atom feed of each user, I could get the information I would like to parse.

So it wouldn't be necessary to open the `account` endpoint at all, and we should rather consider limiting the information that goes into the `/timelines/public/` endpoint.

Just my 2 cents. :)

**Comment by Gargron** [comment]
It's not a leak, we just forgot to make some APIs public. For the record, most APIs are public in that you don't need an authorized user to access them, only a registered app. But the new kind of public is where you don't need any authentication at all.

**Comment by DanielGilbert** [comment]
"For the record", I just shared my observations, that's why i wrote this issue as a question. I checked the API docs, and they mentioned explicitly that the /timelines/public route doesn't require authentication, but found this note on no other route.

**Comment by happycoloredbanana** [comment]
I have fixed some issue regarding opening an API and of course forgot about updating the docs.
Will try to fix it.

Also, will prepare a PR for opening ```/api/v1/accounts```

**Comment by DanielGilbert** [comment]
Cool - thanks @happycoloredbanana \o/

**Comment by ineffyble** [comment]
Can this be closed?

**Comment by DanielGilbert** [comment]
Yes.
