### ISSUE TITLE
Higher-contrast accessibility option

### ISSUE THREAD

**Issue by citizenk** [tootsuite/mastodon#2280]
As noted on [this toot](https://computerfairi.es/users/maunzikation/updates/2884), Mastodon's default style is not accessible to all. There are technical work-arounds (userstyles and such), but they may imply the help from other people or a certain technical knowledge to be useful.

An option to a higher-contrast, higher-visible interface would be nice, especially if offered from the get-go through the welcome screens.

Reference: https://computerfairi.es/users/maunzikation/updates/2884

* * * *

- [ * ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
This should definitely be added in when there's a theme engine available (see #2028)

**Comment by expenses** [comment]
This could be added with #1587 too.

**Comment by nevillepark** [comment]
Reviving this thread to note that in the default theme, the text "Information below may reflect the user's profile incompletely. View full profile" is still too low-contrast.

![screenshot from 2017-11-16 12-53-43](https://user-images.githubusercontent.com/16054979/32907246-60a070d0-cacd-11e7-8da3-1e23ceff89c9.png)

**Comment by Gargron** [comment]
High contrast theme has been added recently in #7213
