### ISSUE TITLE
Add webapp bindings for Firefox Mobile

### ISSUE THREAD

**Issue by Fab1en** [tootsuite/mastodon#2284]
On Android, when I use the webapp on Chrome browser, I can add it to my home screen and use the app in fullscreen mode (without the browser navigation bar). This is not working on Firefox (version 53.0, tested on Android 4.4.2). When I add the home page to my home screen, I don't have the right icon, and when I start the app from the shortcut it does not go in fullscreen mode.

One solution could be to add `"fullscreen": "true"` to the manifest file (as stated in [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/Firefox_OS_apps/Building_apps_for_Firefox_OS/Manifest#fullscreen)), whereas at the moment there is only a `"display": "standalone"` directive
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by zcdunn** [comment]
*This document refers to the proprietary Firefox OS manifest format, and not the W3C manifest spec, designed for cross-browser progressive web apps.*

That field is for Firefox OS and won't work in the manifest.
