### ISSUE TITLE
Home timeline limited to 400 toots?

### ISSUE THREAD

**Issue by FlyMyPG** [tootsuite/mastodon#2301]
I'm working on a Python script that uses Mastodon.py to fetch all toots I've written on a given account/instance. I'm doing this by fetching the Home timeline, then filtering for my own toots (excluding boosts).  It works great on new accounts with few toots, but seems to always stop at 400 toots (20 calls) on older accounts:

```
    toots=[]
    t = mastodon.timeline_home()  # Gets most recent first, oldest last
    while len(t) > 0:
        toots += t
        t = mastodon.timeline_home(max_id=t[-1]['id'])
```

Any clue why the above quits after 20 calls?  Any way to go deeper?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by FlyMyPG** [comment]
While I don't (yet) speak Ruby, I cloned the repo and grepped for "400" and found the following:

`mastodon/app/lib/feed_manager.rb:  MAX_ITEMS = 400`

I don't know enough about Ruby to tell if it can be overridden, but that won't help me on the client side.

**Comment by ashfurrow** [comment]
Looks like @Gargron was the last person to [change that code](https://github.com/tootsuite/mastodon/commit/82aaedec467815c2947a11651d5216bb88ce4038). Not sure why we're limiting the feed – good question!

**Comment by FlyMyPG** [comment]
The feed for account statuses (browseable as https://some.mastodon.instance/@SomeUserName) does not appear to be limited.

**Comment by FlyMyPG** [comment]
The feed for account statuses (browseable as https://some.mastodon.instance/@SomeUserName) does not appear to be limited.

**Comment by Gargron** [comment]
The home feed is kept in memory, and when it's gone from memory, it has to be regenerated which is a long-running process. I figured nobody is likely to scroll back 400 items.

**Comment by FlyMyPG** [comment]
Sorry for not closing this sooner!

Workaround:  Go to https://[instance]/@[user] to see a full history of toots.

However, when trying to get caught up with a user's toots, it is much easier to view them in the order posted, rather than most-recent first.  The above URL does not support any other sort order than "most-recent first".

So I wrote a script: https://gist.github.com/FlyMyPG/2e9d4532453182ada0da78e74980193b

**Comment by roytam1** [comment]
> The home feed is kept in memory, and when it's gone from memory, it has to be regenerated which is a long-running process. I figured nobody is likely to scroll back 400 items.

as a heavy mastodon user, 400 toots can let me scroll back to few hours ago only, I think 10x amount may be enough for me.

**Comment by Gargron** [comment]
Maybe the limit can be dynamic. If a user scrolls past 400 items, bump their personal limit and start storing 800 items... Up to a real maximum amount.

**Comment by FlyMyPG** [comment]
Well, what started all this for me was that I wrote a novel in toots, and had trouble extracting it from Mastodon so I could turn it into an ebook.  Then I tooted a sequel, which made the situation only worse.

For some users (cough, cough) the limit should be tens of thousands of toots.  Perhaps even 100K, or 1M.  Local resources should be the only limit, not something arbitrary in the code.  My PC can handle many GB of toots: Why not let it?  (So long as the instance can support it.)

I presently have no easy way to support readers who want to read my toots in the order they were posted, AS TOOTS, on Mastodon, they way it all originally came into existence.  It's a situational thing, experiential, perhaps historical, as much as it is literary.

Mastodon was the tool that opened me to writing, making huge things possible one toot at a time.  I'd really like to keep at least one reading mode "in the original".

**Comment by Gargron** [comment]
You don't need the home timeline to retrieve your own posts, use your profile.

The limit is also not about *your* PC at all.

**Comment by Miaourt** [comment]
What's up on allowing dynamic resizing of people wanting to fetch older home timeline posts ?

**Comment by FlyMyPG** [comment]
There are so many factors affecting "make it longer" vs. "keep it short".  Some instances are on lightweight servers, and should't have to be bogged down.  Yet some users are truly prolific, and readers should be able to catch up (or review history) in chronological order, instead of newest-first reverse order.

It's almost like we want Mastodon to act more like Discord or Slack, where getting caught up in chronological order is the *main* way, not an impossible or awkward-to-reach way.

I'm still using my MastoUserScrape.py script, whose gist is posted above.  I'm not even sure if Mastodon has changed or not to make my script redundant.  Filed under: "It works for me!"
