### ISSUE TITLE
Highlight on mobile-sized tab bar does not update

### ISSUE THREAD

**Issue by codl** [tootsuite/mastodon#2304]
No matter what screen is currently shown, the blue highlight on the tab bar stays on whichever tab was loaded first

![out](https://cloud.githubusercontent.com/assets/315139/25301180/128bf780-2720-11e7-8271-eaa087a3d2a6.gif)

This is in af7d02da5d2ec014fb87765b65b23d7b3ed6c90c (and in the current master as of this writing 629d35e6f5d353d30661c1af7bbcc8aa6411e698)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
Good find! Thanks for opening an issue.

**Comment by Gargron** [comment]
I feel like i merged something that fixed this. Can anyone confirm for master?
