### ISSUE TITLE
[FR] apply regexp filter to LTL (not only Home Tab)

### ISSUE THREAD

**Issue by ryogrid** [tootsuite/mastodon#2313]
I am a Japanese user.
In several instances (ex: mastdon.cloud), some language (ex: Japanese) occupies LTL.
And some people who can't read the language don't want to read those toots.

So, please implement regexp filter for LTL.

[^\x01-\x7E] < this filter almost of Japanese :-)

**Comment by mjankowski** [comment]
Dupe of https://github.com/tootsuite/mastodon/issues/691 which is in progress in various places, and should work similar to what you described.
