### ISSUE TITLE
incorrect french translation (à ajouter)

### ISSUE THREAD

**Issue by dachary** [tootsuite/mastodon#2318]
https://mastodon.gougere.fr/media/jFpInwN4oXHcS-3mVJ0

The translation should be "a ajouté" and not "à ajouter". Where should I try to fix this ?

**Comment by SansPseudoFix** [comment]
Actually, [it's already fixed](https://github.com/tootsuite/mastodon/blob/67dea31b0f83eb711bbd49a7b893d04ca16c56fa/config/locales/fr.yml#L246).

**Comment by dachary** [comment]
\o/
