### ISSUE TITLE
bio options

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#232]
a toot-length bio section, the current length is Just Not Enough, 500 characters will always be sufficient. a readmore might be necessary for the column view, and that's fine.

on this topic, if you truly want to allow and support people, i would highly suggest a pronouns section, optional, of course, to ease that social layer of difficulty with accepting people's genders and pronouns. thank you for listening.

**Comment by marrus-sh** [comment]
A possible alternative to a dedicated pronoun section would be to have a (limited… 3–5?) number of user-configurable key-value pairs in addition to the dedicated bio, which would be displayed perhaps on their own line(s) under the bio. For example, Twitter has `Location` (which people sometimes use for pronouns), `Birthday`, etc. I don't see any reason to dictate ahead of time what kind of information people can or can't put on their profile in this manner, though. (It would also be a convenient place to list websites or other accounts!)

I feel like this is mostly an aesthetic thing and people will definitely put this kind of info in their main bio text if there's not a place for it elsewhere, but giving a privileged place to short, metric-esque information could really make it easier to learn important stuff about someone at-a-glance.

Here's a mock-up of what the Settings page might look like under this model:

<img width="518" alt="image" src="https://cloud.githubusercontent.com/assets/3212430/20589174/abc04a80-b1cf-11e6-87df-afb2a1582daa.png">

…And this is how it might appear on a user page:

<img width="720" alt="image" src="https://cloud.githubusercontent.com/assets/3212430/20589486/aafeeae6-b1d1-11e6-83f1-81ad76acb5bd.png">

(these are really rough mockups but you get the idea)

**Comment by hoodiek** [comment]
that's really wonderful, and i think that's one of the best ways possible to do that!!
thank you for adding this

**Comment by Gargron** [comment]
That's pretty elegant! Though perhaps the display of the data could be a vertical table beside the avatar/header, i feel like having two rows of columns of different width below each other looks a bit unorganized.

Did anybody check if Portable Contacts allows variable extra details besides the defined ones?

**Comment by hoodiek** [comment]
i don't quite understand the question, could you like. elaborate? i'll totally test things for you

**Comment by marrus-sh** [comment]
@Gargron From what I can gather (cursory glance at the spec) the answer is no, as Portable Contacts is designed to be interchangeable with vCard. I couldn't see where extensions were expressly allowed or disallowed but it would probably at least go against the spirit of the spec. Probably the best way to include arbitrary data would be to encode it into `note` data somehow; this would also make it visible to other GNU Social, etc. instances, albeit in a somewhat different form. Like:

```
pronouns: she/her
website: http://marrus.xyz
%%
This is my bio. I can put whatever I want here.
```

where the data before the `%%` is key-value pairs, and the data after is freeform bio data. (I'm assuming you also use `note` for bio info but haven't checked.)

**Comment by hoodiek** [comment]
pinned toots are a part of bio options, in my opinion, and thus we can combine these two threads: https://github.com/Gargron/mastodon/issues/306#issuecomment-263876617 this post by @marrus-sh has some code ideas for the thing

**Comment by hoodiek** [comment]
![image](https://cloud.githubusercontent.com/assets/23704040/22122905/9387af94-de57-11e6-98b7-aa0c85a4187d.png)
conversation from discord to keep saved in the thread that the data matters for

**Comment by hoodiek** [comment]
other things i would suggest that i believe would greatly increase artist-use cases for mastodon is column options to view only image posts, and to hide replies to people, so that in general viewing a users profile is closer to how twitter works. ideally this would also work outside of column if not logged in

**Comment by marrus-sh** [comment]
This is an old issue, but I just thought of something—is it not the case that user bios can contain HTML? In that case, additional user bio information could easily be added through `data-*` attributes; for example, my bio currently looks like this (I don't currently have any HTML in my bio):

```html
Go Shoemake; aka Margaret, Kibigo, Kibi, et al.
22// boyish girl, ᴾᴋᴹɴ Ranger, easily excitable.
MHSAU Love Interest.
Actually v sweet ❤ in love w the world.
```

But it could easily look like this:

```html
<span data-mastodon-user-info='{"website": "http://marrus.xyz"}'>
Go Shoemake; aka Margaret, Kibigo, Kibi, et al.
22// boyish girl, ᴾᴋᴹɴ Ranger, easily excitable.
MHSAU Love Interest.
Actually v sweet ❤ in love w the world.
</span>
```

…And then the frontend could easily access the information…

```javascript
//  Assume `content` is a container element for the bio
elt = content.querySelector("[data-mastodon-user-info]");
if (elt) userInfo = JSON.parse(elt.getAttribute("data-mastodon-user-info"));
```

…while instances without support wouldn't notice a difference.
