### ISSUE TITLE
Color for 4 status 

### ISSUE THREAD

**Issue by xikufrancesc** [tootsuite/mastodon#2323]
Color the four states or possible ways to publish with different tones. (Public, unlisted, private, direct)
So we know which is which, who is who, where they come from and how to respond or give preference to each one.

_Colorear los cuatro estados o formas posibles de publicar con diferentes tonos. (public, unlisted, private, direct)
Así sabemos cual es cual, quien es quien, de donde vienen y como responder o dar preferencia a cada uno._

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by expenses** [comment]
Which part of the UI is being coloured?

**Comment by xikufrancesc** [comment]
In the column of notifications, when publishing private or direct message, color for example under the avatar.

_En la columna de notificaciones, cuando publica mensaje de privado o directo, colorear por ejemplo debajo el avatar._

**Comment by exadeci** [comment]
@expenses He's suggesting to add color to messages in the notifications, based on their type, to be able to figure out which messages are direct, public or privates with different colors under the avatar.

**Comment by xikufrancesc** [comment]
effectively,
See icon of padlock or envelope is difficult, a color is easier and is detected faster, especially more secure!

- - - -- - - - - - 
efectivamente,
ver icono de candado o sobre es dificil , un color es mas facil y se detecta mas rapido, sobre todo mas seguro!

**Comment by Seebiscuit** [comment]
Is there a style guide to base the message colors of off? For example, `.primary`, `.secondary`, or some other style scheme?

**Comment by Gargron** [comment]
Direct messages now have a special color! Other than that, I don't think we need anything more.
