### ISSUE TITLE
Localization on html tag

### ISSUE THREAD

**Issue by emmanuelclement** [tootsuite/mastodon#2325]
I'm on https://mamot.fr/ (french instance) and lang attribute on HTML tag is still lang="en".
I don't know if it's a instance's bug or Mastodon one (this last one I think).

It's an accessibility issue too: when writing a new toot, all my french words are underlined in red on Firefox : wrong dictionary.

**Comment by stephenburgess8** [comment]
This was addressed two days ago in #2212 . When your instance updates to the latest code it will display the lang attribute with the appropriate localization.

**Comment by emmanuelclement** [comment]
Ok, thank you, issue closed.
