### ISSUE TITLE
Link to profile sometimes redirects to other instance

### ISSUE THREAD

**Issue by cdancette** [tootsuite/mastodon#2329]
Sometimes, instead of loading the profile of an user in the right column, it redirects to the remote instance ui.

Steps to reproduce bug:

- Click on a toot, to display it on the right column and focus on it
- On the right column, click on an other toot (with a @ link to a remote profile), to focus on it 
- click on the profile link
- It redirects to the public profile on the other instance, with the "remote follow" link

Expected behavior : Display the profile on the current instance, in the right column.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
The core of this issue is that sometimes, the remote server doesn't encode metadata like mentions or tags correctly, or the parsing server fails to parse it correctly. Without metadata, all the links in the body of the post are just standard links.

**Comment by Gargron** [comment]
^ Can't fix missing metadata, but it occurs very rarely
