### ISSUE TITLE
Comment made on Mastodon does not show up on GNU Social.

### ISSUE THREAD

**Issue by ninks** [tootsuite/mastodon#2340]
So made a couple of comments on GNU Social [shitpost.club, status.fsf.org and quitter.se] on my Mastodon account [mstdn.io], however if I go to their posts on their instances I cannot see my comments. I txt one of my mates and he said he didn't recieve it.

Is this suppost to happen, a bug or is it the instance I am using. I've contacted the admin and still waiting for a reply.

**Comment by archaeme** [comment]
I was testing something unrelated between GNU Social and Mastodon when I noticed the same issue.  It seems that someone on the GS server has to follow the Mastodon user in order to see any posts, even direct replies or mentions.

**Comment by ninks** [comment]
That's a wee bit annoying. I wonder if it's due ti limitations or is a feature.

**Comment by celesteh** [comment]
Summarising: this is a bug wherein if a mastodon user mentions a GS user in a post, the mentioned user does not get notified.

**Comment by ninks** [comment]
@celesteh Yes, pretty much.

**Comment by celesteh** [comment]
Can someone add the 'bug' and 'compatibility' tags?

**Comment by Gargron** [comment]
As somebody who often talks to GS users from my Mastodon account, I don't think this is a valid issue. This stuff works in general, but there are various cases where it can fail due to specific configuration, network issues, or even moderation.
