### ISSUE TITLE
Direct Messages are exposed via hashtag url

### ISSUE THREAD

**Issue by k0ta0uchi** [tootsuite/mastodon#2353]
There is a bug that Direct Messages are exposed via hashtag url.

Here's what I tested.
* Send a DM from @k0ta0uchi@mstdn.jp to @k0ta0uchi@friends.nico with hashtag "#qwertyuiop".
* Browse #quertyuiop from url "https://mstdn.jp/tags/qwertyuiop".
* Now I can see my message even though it's a Direct Message.

Screenshot:
![chrome_2017-04-23_18-14-07](https://cloud.githubusercontent.com/assets/1085968/25312291/b2628f5e-2850-11e7-98f6-b990faf3f72f.png)

* * * *

- [✓] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment]
Yep, I can confirm this.

**Comment by ykzts** [comment]
duplicated with #2120 . And, fixed in #2182 .

**Comment by k0ta0uchi** [comment]
I couldn't find that one, sorry.
