### ISSUE TITLE
Add following limits

### ISSUE THREAD

**Issue by siuying** [tootsuite/mastodon#2354]
Today I came across a user [mentioned he had follow 100,000+ users](https://pawoo.net/@kodam?max_id=3316759). This probably is not scalable, and if there are a number of bots doing this, it could consume massive amount of resources.

For Twitter there are certain limits on following, you can only follow at most 1000 user per day, and there are a 5000 following limit, when following exceed that limit, new following is subject to a follower-following ratio limit. ([ref](https://support.twitter.com/articles/15364#))

1. are there any interest to add such limit?
2. is adding limit a good idea?
3. what are the best default values for such limit?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
I believe there is interest in adding this feature; a very similar issue was opened yesterday: https://github.com/tootsuite/mastodon/issues/2311 Let's continue the conversation over there 👍
