### ISSUE TITLE
Scaling Public Timeline UX

### ISSUE THREAD

**Issue by triplefox** [tootsuite/mastodon#236]
The current instance population is mostly happy with public timeline velocity, but something about this feature will have to change later to preserve a similar feel without the impossible speed of seeing the whole population.

My proposal uses "Rooms" as the main new concept.

- Users can open and moderate a new room, effectively forming new public timelines(displayed as a new column). 
- Rooms should be easily discoverable if desired. One of the column views would also be what rooms are available to browse and which ones are recommended based on your social graph. For example, a new room could automatically invite everyone two degrees of separation from the originating account(followers of your followers).
- Room moderators should be able(and encouraged) to invite other rooms in to make a giant katamari room.
- Users can decide when to close the room, or to automatically close it at a specific date. This will allow "public timelines" to renew endlessly in different forms.

**Comment by minwu325** [comment]
I was thinking that some kind of filter settings could also be used to keep the public TL manageable, either by way of generalized account markers or user-created tags that could be set for your own account and muted/permitted from other accounts. Being able to opt out of seeing bots or news accounts for example could dampen the timeline speed a fair amount

**Comment by alexgleason** [comment]
Why not use hashtags for "rooms"?

**Comment by triplefox** [comment]
Additional idea I just came up with that might coexist with or replace some of the ideas of the original proposal; the convention(but not necessarily the hard rule) should be for rooms to be invite-only and viewable to either public or some number of outer rooms. The point is to demonstrate that you can fit in, before you start contributing to that space. This naturally creates a "concentric circles of knowledge" effect, where a more exclusive discussion coexists with larger ones. Large rooms near the top level might be topical, publicly viewed and not require invitations, but as you go closer to the centers more barriers are thrown up. This creates a natural group safe-spacing to any degree of granularity necessary. Defaulting to visible-not-accessible makes it possible for teachings of the inner group to reach the outer group, at a level that is only slightly beyond their grasp, rather than drastically so(as it might be if we consider something like a circle of intellectual elites broadcasted directly to the public). It creates aspiration for both the healthy behaviors allowing access to the inner group, and the radical behaviors needed to form a new inner group.

**Comment by Gargron** [comment]
This discussion is rather removed from being a specific feature request (or bug report) so if you'd like, you can continue it on our [Discourse](https://discourse.joinmastodon.org) where it may take a more specific shape. At this time I don't see myself implementing exactly this concept. Please excuse me if you believe closing this issue is a mistake. I want to close old unused issues, duplicates and abstract discussions.
