### ISSUE TITLE
display names in inline messages are display:block

### ISSUE THREAD

**Issue by nightpool** [tootsuite/mastodon#2367]
![image](https://cloud.githubusercontent.com/assets/233815/25315958/0466180e-282c-11e7-8c81-e5202eff2bc1.png)

(relayed is instance flavor for boosted)

this is a regression introduced by https://github.com/tootsuite/mastodon/pull/2338, specifically these lines:
```diff
+  .status__display-name {
+    display: block;
+    max-width: 100%;
+    padding-right: 25px;
+  }
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
Looks like this has been fixed in https://github.com/tootsuite/mastodon/pull/2368 so I'm going to close the issue. Please feel free to re-open if it's not be addressed to your satisfaction. Thanks again!

**Comment by nightpool** [comment]
Yep, this was fixed!
