### ISSUE TITLE
Remove hardcoded "last 20 toots" limit on api/v1/timelines/public?local=true

### ISSUE THREAD

**Issue by vegax87** [tootsuite/mastodon#2372]
I would like to set the value from a config file and show more than last 20 toots on the local timeline API

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
The [limit](https://github.com/tootsuite/mastodon/blob/cf845fed3824d3e3587ce9b2ad752c2b3f0a2a76/app/controllers/api/v1/timelines_controller.rb#L24) uses `DEFAULT_STATUSES_LIMIT` which is [set to `20`](https://github.com/tootsuite/mastodon/blob/cf845fed3824d3e3587ce9b2ad752c2b3f0a2a76/app/controllers/api_controller.rb#L4) but you should be able to customize this in the request. Is that not working for you?

**Comment by Gargron** [comment]
You can specify limit on the request.
