### ISSUE TITLE
Space on /about/more to show the date when the instance was launched?

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#2373]
Part of what I'd like to know when deciding which instance to join is how long it's been running for. A thing showing how long it's been running and/or when it was set up on the /about/more page would be pretty cool, I think.

* * * *

- [I did, but honestly I wasn't sure which keywords to use!] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
I think this is the responsibility of the admin(s) to write it in the about/more? I mean, having a specific field just for this wouldn't bring a lot imo, since admins could easily change it and they can manually add it to their description page.

**Comment by Gargron** [comment]
This'd be kinda hard since we don't track anything like the start date.. Or should it be just another freeform field?

**Comment by Cassolotl** [comment]
No, not a freeform field, but... Maybe you could start tracking the start date?

**Comment by Gargron** [comment]
Well, admins can put that into the extended site description field. I think it's impossible to start tracking something like that automatically in any meaningful way.
