### ISSUE TITLE
Any idea on how much space (SSD) I should have for a future mastodon instance?

### ISSUE THREAD

**Issue by Tetizeraz** [tootsuite/mastodon#2374]
I searched a little bit and couldn't find a good resource on storage. I know that a lot of instances are running on Digital Ocean with ~30 GB on SSD. It seems pretty good, but I just wanted to know if it possible to estimate how much storage does an instance need in the future.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by dariusk** [comment]
I can't give you comprehensive data but I'm running dolphin.town (180 extremely occasional users, local and not s3 storage) on a 20GB linode. Currently it's using 3.1 GB of space.

**Comment by Gargron** [comment]
The answer to this is extremely "it depends". Depends on how many local users you're gonna get, and who they're gonna follow, and what everybody chooses to post. For example an instance with a lot of interest in art or GIFs will consume a lot more storage. In short, it is impossible to give an ad hoc answer. 30GB is more than enough to get *started*, but you'll need to see how the disk usage trends and adjust accordingly.
