### ISSUE TITLE
Using WEB_DOMAIN wrong URL is returned in Webfinger for atom, salmon

### ISSUE THREAD

**Issue by kballard** [tootsuite/mastodon#2375]
I set up an instance whose public domain is eridi.us and whose WEB_DOMAIN is social.eridi.us. Using webfinger.net to look up kevin@eridi.us, I get the following:

```json
{
  "subject": "acct:kevin@eridi.us",
  "aliases": [
    "https://social.eridi.us/@kevin",
    "https://social.eridi.us/users/kevin"
  ],
  "links": [
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://social.eridi.us/@kevin"
    },
    {
      "rel": "http://schemas.google.com/g/2010#updates-from",
      "type": "application/atom+xml",
      "href": "https://eridi.us/users/kevin.atom"
    },
    {
      "rel": "salmon",
      "href": "https://eridi.us/api/salmon/1"
    },
    {
      "rel": "magic-public-key",
      "href": "data:application/magic-public-key,RSA.wek_FwrfGUhUxrmdbksDqGW-nMZM21h3kVCw5dYhE5_ln5nGTIOxySEneAJWDTMhRwsOm_TBSKfUJfW0kdt3vgwcGhPpzYjo4gYKZG54zMZ91mjc5uOmQXSmRsss17SOBQu_SlM01Bq3oar06ln94pVGd3t-NfS6DbFUgrJIkH7tL1jupGNUVEP_UvLBoegFCHusUmi6VDEjd_IpNR3OPnHCiHAjUe-Fz7j4m_POQc16Om_pHJ_5LfvNKszgQLOPGuLXqJaZfj6yZ8VhnSp_ERmiyUg1EAlAK3I16KrXT9gyMjidV8nI-R8VyHoElv0IFs4lZIPFoth7RMbeSjapmw==.AQAB"
    },
    {
      "rel": "http://ostatus.org/schema/1.0/subscribe"
    }
  ]
}
```

Note how both the Atom URL and the Salmon URL are using eridi.us instead of social.eridi.us.

* * * *

This bug happens on current `master` (ef5937da1ff2d6caca244439dd9b9b9ed85fb278).

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by dariusk** [comment]
I'm seeing something similar to this but not quite? I just set up an instance on a recent master (1801a36414ee79bd51aad23fc5ff6a90049e7270) like so:

```
LOCAL_DOMAIN=tinysubversions.com
WEB_DOMAIN=social.tinysubversions.com
```

When I use webfinger.net, it simply [can't resolve](https://client.webfinger.net/lookup?resource=darius%40tinysubversions.com) `darius@tinysubversions.com` but `darius@social.tinysubversions.com` [resolves correctly](https://client.webfinger.net/lookup?resource=darius%40social.tinysubversions.com).

**Comment by dariusk** [comment]
Okay well turns out the 404 was because I needed to tinysubversions.com itself to return the webfinger file. But my webfinger file itself actually looks okay, with social.tinysubversions.com as the domain for all the resources.

**Comment by ThibG** [comment]
webfinger.net is broken as it does not honor host-meta.
This feature lacks documentation, but you are supposed to serve https://LOCAL_DOMAIN/.well-known/host-meta to redirect webfinger queries to https://WEB_DOMAIN/.well-known/webfinger?resource={uri}
I'll have a look at @kballard's case nonetheless, as having a mixture of “good” URLs and bad ones seems weird. But I guess the issue is that you're accessing the webfinger API from LOCAL_DOMAIN and not WEB_DOMAIN.
As for @dariusk, you're missing the host-meta file entirely.

**Comment by dariusk** [comment]
@ThibG That fixed my issue, thank you! I will try and add what I learned here to the Mastodon documentation.

**Comment by kballard** [comment]
Ah hah, I didn't know about .well-known/host-meta, so I was just proxying .well-known/webfinger to social.eridi.us.

**Comment by kballard** [comment]
Ok, I just tried proxying .well-known/host-meta instead, and it's still broken. The host-meta response uses whatever domain I access it from in its link, instead of using the WEB_DOMAIN value. So if I fetch https://eridi.us/.well-known/host-meta it points me at `https://eridi.us/.well-known/webfinger?resource={uri}`, but if I fetch https://social.eridi.us/.well-known/host-meta it points me at `https://social.eridi.us/.well-known/webfinger?resource={uri}`.

I believe that's the same problem with the webfinger response directly. Two out of the 3 URLs in the webfinger response are using the domain I accessed it at instead of using the WEB_DOMAIN.

**Comment by kballard** [comment]
Putting a static file at https://eridi.us/.well-known/host-meta that contains the document I get if I fetch https://social.eridi.us/.well-known/host-meta appears to work. But that's kind of awkward. I should be able to just proxy .well-known/host-meta and let mastodon return the right document.

**Comment by ThibG** [comment]
A static copy is fine, but you could redirect (HTTP 301 for instance) host-meta instead of proxying it, it would solve your issue.
It is weird however, that some URLs use WEB_DOMAIN while others use whatever host they were contacted with.
