### ISSUE TITLE
Make confirmation modals optional

### ISSUE THREAD

**Issue by expenses** [tootsuite/mastodon#2383]
I think that the confirmation modals added in #2279 should be turned on by default, but have settings in the options to turn the on and off.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Seems to have been solved by PR but PR didn't auto-close the issue.
