### ISSUE TITLE
Bug: Two-Factor authentication setting fails when timezone does not match

### ISSUE THREAD

**Issue by imunolion** [tootsuite/mastodon#2384]
[Issue text goes here].
If your time for your phone has different timezone settings, apply two factor authentication will fail. Lets say you have PST phone and the server locates at JST.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yookoala** [comment]
That should not happen. Time issue usually happen if your phone, or the server, has a time not up-to-date with NTD servers.

What is your error message? How did you come to the conclusion that timezone is the problem?

**Comment by imunolion** [comment]
@yookoala it says "コードが間違っています。サーバー上の時間とデバイス上の時間が一致していることを確認してください。"(sorry, its localized)

I thought that because my phone uses NTP to get correct time. Then the server time is wrong?

**Comment by imunolion** [comment]
Oh, sorry my bad. I had to input my one time code here (the input area didn't look like a textarea).
