### ISSUE TITLE
Global and Local timeline won't refresh automaticaly.

### ISSUE THREAD

**Issue by Letiteuf55** [tootsuite/mastodon#2390]
Hi, i run my instance but as i see on other instance, my Global and Local Timeline doesn't show new toot unless i refresh manually my browser. Is there a file to configure to allow this?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.-
- [x] This bug happens on a tagged release and not on master (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
What is your server setup like? Is the streaming node server running?

**Comment by Letiteuf55** [comment]
My setup is a Virtual server : 2 vCores@2,4 GHz - 8 Go RAM - SSD 40 Go Running Debian8.
I follow this guide https://angristan.fr/installer-instance-mastodon-debian-8/
I check the streaming service and i'ts alive : active (running)

**Comment by DanielGilbert** [comment]
If you are using Chrome, press F12 to open up the dev tools. Now, look for any errors relating to "wss://" or "ws://" protocol. If they appear, Chrome isn't able to build a websocket connection, which is needed to refresh the timelines.

**Comment by Letiteuf55** [comment]
Oh yes... i have "Refused to connect to 'wss://mastodon.crazypanda.fr//api/v1/streaming/?access_token=*****" How can we fix this ?

**Comment by DanielGilbert** [comment]
Well - don't copy the CSP Headers of other instances.^^ Replace `wss://mstdn.io` with your host and protocol, so use `wss://mastodon.crazypanda.fr`

In theory, it should work than. :)

**Comment by Letiteuf55** [comment]
I restart nginx and seems to be ok with the wss:// issue :+1:

**Comment by DanielGilbert** [comment]
Awesome, great! :)

Don't forget to close the issue when your problem is solved. :)

**Comment by Letiteuf55** [comment]
YEEEES it's working great ! I still have some Red issues on the F12 dev tools but i think it's an other thing.
Thanks a lot !
