### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by KonomiKitten** [tootsuite/mastodon#2397]
Hi everyone, as a user of Mastdon, specifically mastodon.social instance I frequently encounter **500 Internal Server Error** (**Oops! An unexpected error occurred.** also seems go hand in hand with this error), sometimes over and over and over when using the service, and it doesn't seem to be getting any better.

I'm not sure what is causing it people on the instance itself have suggested server overload, but this seems to be affecting my ability to use Mastodon in general as I can try to post three or four times before a post goes through and it becomes worse with attachments. Can this be solved?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by JantsoP** [comment]
not actually an issue which needs an github ticket....

**Comment by KonomiKitten** [comment]
@JantsoP I'm not sure I agree, I think Mastodon could handle these errors better if they are just server load errors, also I don't see any other place to really ask about these issues besides the GitHub issues page.

**Comment by foxmajik** [comment]
I'm kind of curious why this question got one (very passive aggressive) answer and then it was closed without explanation. This seems like a legitimate question.

**Comment by nightpool** [comment]
@foxmajik Not sure I understand. 500 Internal Server Error  is a very generic error that could be caused by a large variety of issues, mostly related to server configuration. As a software project, there's very little Mastodon can do to control the environments that people deploy it into, and potential load, database, or external service issues like the one mentioned in the OP (from 5 years ago!) are mostly out of our control.

**Comment by foxmajik** [comment]
Okay, but that's no excuse for that type of treatment. Instead of shutting down someone asking for help you should encourage elaboration or suggest a proper venue for seeking help. "You're wrong, fall off a cliff" isn't conducive of a welcoming open source community. See @konomikitten comment.
