### ISSUE TITLE
What are IPs used for in Mastodon?

### ISSUE THREAD

**Issue by EmilePouget** [tootsuite/mastodon#2398]
[Issue text goes here].

As referenced in https://github.com/TootCat/mastodon/issues/25, what are IPs used for in Mastodon?
I haven't read anything of mastodon's sourcecode yet except the parts which are relevant for me as a person creating system integration packages.
A short abstract:

> As I understand from #11 there are IPs recorded in the DB of Mastodon and in nginx. For people who use tor currently, these are changing values anyway and it's hard to track. If a malicious person is banned, it happens on account names and not IPs or IP ranges?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
There is a `current_sign_in_ip` column which logs an IP address when a user signs in, controlled by the auth plugin [Devise](https://github.com/plataformatec/devise), which mastodon uses.

You are correct that much of the moderation takes place at the account and user and domain level, and not the networking/IP level.
