### ISSUE TITLE
Can't scroll New Toot column, menu options get lost under bottom of screen.

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#2401]
If I'm writing a post that's kinda longish, when I'm done and I go to choose a privacy setting, the menu gets lost under the bottom of the page and there's no scrollbar and I can't scroll.

![screen shot 2017-04-24 at 16 02 24](https://cloud.githubusercontent.com/assets/6607512/25343678/a10b3d66-2907-11e7-8530-3871dfb5d225.png)

The above is how it looks when it happens. (Mac OS X 10.12.4, Chrome latest.) I can't scroll to get to Followers Only or Direct.

Also sometimes it happens and I can't see any of the buttons like "toot" or "CW" at all, and there's no scrollbar and no scrolling so the only way I can deal with it is by shrinking the stuff in my browser with cmd + -, or by pressing enter to make the page longer and then deleting the carriage returns to get the buttons higher up again. (That's hard to describe, but I can't think of a better way to put it! I'm sorry.)

* * * *

- [Yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [I'm a user] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by stephenburgess8** [comment]
@Cassolotl I tested this on Chrome v58.0.3029.81 (64-bit) Mac OSX 10.11.6 and I could not reproduce this either locally with the latest version of the `master` branch, on social.wxcafe.net, or on mastodon.cloud. I noticed your screen cap has customized colors. It may be that the instance you are on has customized the CSS which isn't allowing for scrolling. The CSS for `.drawer__inner` class should have the following CSS, which should allow it to scroll:

```
overflow: hidden;
overflow-y: auto;
```

If that `overflow-y` value was overridden, then it's possible that could explain why you are not able to scroll.

**Comment by Cassolotl** [comment]
@stephenburgess8 Oh, it may be a style script thing, I'll test without it and see what happens...

Nope, no change when I deactivate the style thing. I will send the link to this issue to the admin of my instance and see what they say.

Thanks!

**Comment by Cassolotl** [comment]
I got a response! :)

> yeah this is our fault. It has to do with the styles that were added to
> make that column transparent. We probably need to add another wrapper or
> add some styles to the outer column to get this working.

I will go ahead and close this. Thanks for helping pin it down, @stephenburgess8 !

**Comment by nightpool** [comment]
Hey @cassolotl in the future if you find another style bug like this, feel
free to run it past me or chr first! We don't want to pollute the main
issue tracker if it ends up being our fault haha.

**Comment by Cassolotl** [comment]
@nightpool Okay, will do! :)
