### ISSUE TITLE
Pictures uploaded as .jpe not shown and extension not rewritten

### ISSUE THREAD

**Issue by rhaamo** [tootsuite/mastodon#2403]
I'm on v1.2.2.

If I rename whatever.jpg to whatever.jpe and upload it, Mastodon doesn't rewrite the extension.
It leads in an image not viewable with lot of browsers because of bad Content-Type.
It's the same issue as closed #1912 but instead of "no" extension it's "wrong one".

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by TheRealKingS** [comment]
Same error here:

File: https://toot.krinetzki.de/system/media_attachments/files/000/000/052/original/753faadb6a70b586.jpe?1493049680

Webserver is apache2, using Mastodon 1.2.2.

**Comment by kuro5hin** [comment]
I see this problem with all the images from the account https://botsin.space/@publicdomainbooks

**Comment by rhaamo** [comment]
For reference, included in v1.2.2 is #2078 which should dictate extension regardless if present or not ?

**Comment by Gargron** [comment]
File linked by @TheRealKingS displays just fine on Firefox. "jpe" is a valid extension for JPEG (which is why it's not changed). The reason why "jpe" gets picked when enforcing an extension on a file with no previous extension is that "jpe" is the first in the list of extensions for the JPEG mime type in the Ruby mime libraries. That cannot be fixed easily and given that the extension is actually valid I don't think it's worth fixing.

**Comment by tscs37** [comment]
I think this issue should be reconsidered, several applications do not properly recognize the .JPE extension, mainly android applications and non-browser applications (Pinta for example, my image editing tool, does not recognize .jpe)

I would suggest (and probably also not be wrong) if a lot more applications don't accept .jpe extensions. That the browser does may be merely an artifact of the Content-Type header.

A ruby mime library has encountered a similar error in 2014 and restored older behaviour; the first extension is the preferred one, so the most widely used one should be first. https://github.com/mime-types/ruby-mime-types/issues/71

It also looks like the mentioned library has the correct sorting of file extensions (afaict), so the bug might still be within mastodon. 

See here for the library order: https://github.com/mime-types/mime-types-data/blob/4ea7e6b9f8d49dff6cd59703dc234a0b411175e2/types/image.yaml#L112
