### ISSUE TITLE
Hashtags from GNU Social posts do not open in the far right column

### ISSUE THREAD

**Issue by celesteh** [tootsuite/mastodon#2407]
Clicking on a hastag from a GNU Social post does not open in the third column. Instead it links back to the GS instance the post came from. Additionally, hashtags from GS posts do not show up in hashtag searches on the Mastodon host, even if a tagged post is in the federated timeline.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
It may not sound like it but this issue is the same as #2329
