### ISSUE TITLE
[webui] changing default post privacy unlisted removes all indications of if a post on the TL is federated or unlisted

### ISSUE THREAD

**Issue by NireBryce** [tootsuite/mastodon#2415]
I felt that title is more descriptive of the overall problem, but an alternate/parallel title should be "setting default post settings to 'unlisted' makes all my replies start as 'unlisted', removing all of my ability to know if the initial toot was federated".   This is hard to condense, because its really three problems, but necessitated because of the default post setting.

I searched, but not knowing what to call it might mean I missed a duplicate.

if I set my toot default visibility to 'unlisted', I no longer know if the original toot I reply to is federated or unlisted. 

default behavior: I reply to a toot, check if its a globe or an unlocked lock, reply accordingly

post-as-unlisted-by-default behavior: I reply to a toot, and unless it was private or a DM, the privacy gets auto-set to unlisted, even if it the original one was federated (globe).

initial toot, notice federated: ![2017-04-24 19 03 28](https://cloud.githubusercontent.com/assets/24237095/25356293/a930c4b6-2907-11e7-8ccd-eea4bda8ed70.png)
reply toot: 
![2017-04-24 19 03 54](https://cloud.githubusercontent.com/assets/24237095/25356341/d0926db6-2907-11e7-8057-c87e3ea76c4f.png)

potential suggestion: visibility icons to the left of a user's name, where the fav/boost icon would be in a fav or a boost.  alternatively, as it mostly only matters while replying, an icon in the reply window.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
> federated or unlisted

There is no such distinction. Unlisted literally means "not listed". It's still public. It just opts out of being featured in the public timeline columns...

**Comment by Gargron** [comment]
Okay, I still don't understand what this issue was about. Hopefully not a problem anymore.
