### ISSUE TITLE
Enhance content warning markup to improve compatibility with legacy systems.

### ISSUE THREAD

**Issue by lambadalambda** [tootsuite/mastodon#2427]
Right now mastodon does the following for cw (html unescaped for readability):

```xml
  <summary xml:lang="es">Which line of music does an MRA sing?</summary>
  <content type="html" xml:lang="es">m'lody</content>
```

This is not the best use of the summary field and loses information on display in GS. I'd suggest to implement it similarly, but like this:

```xml
  <summary xml:lang="es">Which line of music does an MRA sing?</summary>
  <content type="html" xml:lang="es"><span data-type="cw">Which line of music does an MRA sing?</span> m'lody</content>
```

Instances that would understand it could strip out the cw in the content tag before displaying. This would show up completely on unmodified GS.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mal0ki** [comment]
This idea was also [pitched to postActiv](https://git.postactiv.com/postActiv/postActiv/issues/94#note_1181), to improve the talking between the Mastoverse with the wider fediverse. 
I tend to agree that this is a minor change, which would offer a lot of wellness to the wider fediverse. 

The idea we discussed (months ago), between would be something like the following, when displayed on other instances outside of Mastodon: 
> This text is shown to everyone
>nsfw (or cw) 
>This text is shown only to people who click through the spoiler (or those who have spoilers disabled)

**Comment by lambadalambda** [comment]
This one is different from the idea at postactiv, where it is actually about implementing a completely separate CW mechanism (which i think doesn't make sense).  This is just about making CWs show up properly on legacy systems that don't understand them. I think systems that are still updating / in development should implement the mastondon CW mechanism.

**Comment by mal0ki** [comment]
Yeah, sorry, I meant that it looked like you actually copied that text into that thread.
