### ISSUE TITLE
preferences set to  to wrong default language

### ISSUE THREAD

**Issue by GDog1985** [tootsuite/mastodon#2429]
default language set english 

![screenshot from 2017-04-25 03-37-23](https://cloud.githubusercontent.com/assets/1531603/25373770/ee695ae6-2968-11e7-8d66-46fe28db973e.png)

Preferences
تصویر زمینه
حریم خصوصی نوشته‌ها

    PublicEveryone can see
    UnlistedEveryone can see, but not listed on public timelines
    Followers-onlyOnly show to followers

وقتی کسی پیگیر شما شد ایمیل بفرست
وقتی کسی درخواست پیگیری کرد ایمیل بفرست
وقتی کسی نوشتهٔ شما را بازبوقید ایمیل بفرست
وقتی کسی نوشتهٔ شما پسندید ایمیل بفرست
وقتی کسی از شما نام برد ایمیل بفرست
خلاصه‌کردن چند اعلان در یک ایمیل
مسدودکردن اعلان‌های همه به جز پیگیران
مسدودکردن اعلان‌های کسانی که شما پی نمی‌گیرید
نمایش پیغام تأیید پیش از بازبوقیدن
پخش خودکار تصویرهای متحرک

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by GDog1985** [comment]
this with last git pull

**Comment by ashfurrow** [comment]
A fix for this is pending in [this pull request](https://github.com/tootsuite/mastodon/pull/2419) [here](https://github.com/tootsuite/mastodon/pull/2419/files/08b7cb9685d33f958e458aa9d568eec20a4b4a1e#diff-77c6872f038f785b5132863d8aace40b).

**Comment by jkapelus** [comment]
This also affects the placeholders in the registration and login forms.

The English language comes up with Arabic script.
![english](https://cloud.githubusercontent.com/assets/1300817/25375102/f5b50d04-299f-11e7-96e8-35e6fccfde98.png)

Esperanto comes up with some Arabic script.
![esperanto](https://cloud.githubusercontent.com/assets/1300817/25375103/f5bc378c-299f-11e7-9122-8c803464cf6a.png)

Farsi comes up with english.
![farsi](https://cloud.githubusercontent.com/assets/1300817/25375104/f5c29474-299f-11e7-8f9e-014a1297e428.png)

**Comment by ashfurrow** [comment]
Yup, it's a pretty serious bug. Sorry for the hassle, thanks for the detailed GitHub issue.

**Comment by mabkenar** [comment]
Oops! That was my fault, I'm terribly sorry! In my Persian translation (which was merged last night), I forgot to change the language label in one of the 5 translated files from `en` to `fa`.

**Comment by ashfurrow** [comment]
No worries, it's all fixed now 😄

**Comment by ashfurrow** [comment]
Fixed in https://github.com/tootsuite/mastodon/pull/2432
