### ISSUE TITLE
Unicode/Emoji rendering issue in Safari

### ISSUE THREAD

**Issue by optikfluffel** [tootsuite/mastodon#2431]
When posting a toot using ✴︎ (`'\u2734'` or 'eight pointed black star') the output gets changed into the Emoji `svg` but also is followed by some space or character that Safari (on iOS and macOS) isn't able to show correctly.

You can find [an example here](https://botsin.space/@fullofstars/54100) and I also made some screenshots:

![safari macos](https://cloud.githubusercontent.com/assets/379915/25374402/926500ee-299d-11e7-8380-21a6290ee974.png)
![safari ios](https://cloud.githubusercontent.com/assets/379915/25374401/9261fae8-299d-11e7-8ac3-971c9745cefd.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by expenses** [comment]
![screen shot 2017-04-26 at 1 07 10 pm](https://cloud.githubusercontent.com/assets/13566135/25413835/5efc822e-2a81-11e7-804d-f248544eda3d.png)
This also happens to me with Safari 10.1.

**Comment by dracos** [comment]
The extra character is U+FE0E (textual indicator for Emoji character) which Safari displays but e.g. Chrome does not (it is still there). As simple solution #8553 should skip over those characters if the preceding emoji has been converted to an image.
