### ISSUE TITLE
Change wording: "privacy" controls are actually *exposure* controls

### ISSUE THREAD

**Issue by msappir** [tootsuite/mastodon#2433]
## The Issue
The "privacy" controls on Mastodon are an excellent and important feature, but calling them "privacy" is a bit misleading:

- Rogue admins can easily circumvent the "privacy" settings and read or make public things set as private.
- If a server is breeched nothing at all protects "private" data from unauthorized access.
- If I'm not mistaken, _unlisted_ toots federate transparently with non-Mastodon instances and are treated as public there. Or at least, the API can be used to access _unlisted_ toots and display them more publically then intended.

## Proposed Solution
**Change the wording:** In the hopes that at some point, Mastodon will acquire actual encryption-backed privacy capabilities such as what [@Rushyo](https://mastodon.social/@Rushyo) is working on, and to ensure people are not misled into trusting the so-called "privacy" controls with their secrets, I propose we change the wording to call them **exposure** controls. (Or if someone has a better word, maybe that instead.)

"Exposure" better describes what these controls are for: controlling how much attention is directed to your toots.

### Resolution Checklist

- [ ] Agree on new wording
- [ ] Identify all locations in the UI where these features are located and/or referred to
- [ ] Create PR updating terminology
- [ ] Notify contributors working on localizations to update localized wording accordingly

These changes are basically all textual and do not require coding ability (the locale files that need to be edited are very light on code, basically just structured lists of textual phrases.)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
"Exposure" has sort of lewd implications in english.

Maybe "Visibility controls" or something...

I agree with your overall sentiment that we don't want to accidentally advertise the app as one with strong encryption/privacy tools for secure communication built in. I'm not sure why you'd come to a social networking tool looking for those things in the first place - but I agree that focusing on explaining what federation is, and which settings will lead to more/less of the people on your instance and elsewhere being able to see things, makes sense.

**Comment by DanielGilbert** [comment]
Just a random thought here about giving it a new name:

"Privacy settings" is a well-known term in social networks, and the consequences you mention in 1. and 2. also apply to the big players. Changing that term might add an additional level of difficulty for new users to join. Add that up to the already "strange" concept of the fediverse, and people will be even more confused. Spotting the term "Privacy settings" will give the users a "oh, I know this one!" feeling, which will make them more comfortable towards Mastodon.

Maybe, instead of changing the wording, we should rather add a section in the user settings, where the consequences of these settings are explained?

**Comment by msappir** [comment]
Other words suggested in replies to my toot about this:

- Distribution
- Audience
- Visibility

The latter two are also somewhat more familiar from other social media, I think.

**Comment by nevillepark** [comment]
On Facebook it's simply a little multiple-people icon that brings up a dropdown titled "Who should see this?" 

I think "visibility" is a good choice.

**Comment by msappir** [comment]
I agree. I've already seen it used "in the wild" to talk about these controls so.

**Comment by Gargron** [comment]
I'm gonna close this issue: I raised this concern for v1.5, but in the end people were against changing the wording. Now that stuff is safer in ActivityPub, I think this is no longer a big deal.
