### ISSUE TITLE
Opengraph preview of boosted toots shows the wrong user

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#2434]
If a boosted toot is pasted into a chat using the link from the booster, the username shown is the one of the booster, not the boostee. This might lead to misattribution.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
Hi there! Thanks for the bug report. I'm trying to reproduce this but I'm having trouble. Would you have a URL that shows the problem available?

**Comment by noiob** [comment]
sure, https://mastodon.social/users/maloki/updates/2088576

**Comment by ashfurrow** [comment]
Thank you. Very strange! I'm curious how you managed to get that URL? It's helped me reproduce the problem locally, I'm just curious.

**Comment by noiob** [comment]
I just copied the URL of a boost from my timeline using the Amaroq app. Mastodon web seems to put the original URL.

**Comment by ashfurrow** [comment]
Appears that way. I'll ping the Amoroq developer about this.

I took a look at fixing this in the meantime, but it's beyond my abilities for now I'm afraid.

**Comment by ReticentJohn** [comment]
Opened a bug on Amaroq's github, this should be an easy fix. I'll get it queued for a version update.

**Comment by Gargron** [comment]
This might be related to a different bug with reblogs but since this link actually leads to the booster's page, OpenGraph tags displaying the booster's name is not a bug in itself.

**Comment by xmgz** [comment]
is this bug the same I tried to (wrongly) report on Diaspora?
https://github.com/diaspora/diaspora/issues/7752#issue-308825234


If not, I'll open a new one report here.
Thanks
