### ISSUE TITLE
No email confirmation message sent but the others yes

### ISSUE THREAD

**Issue by svanneste** [tootsuite/mastodon#2435]
version: 1.2.2 on Debian (not docker)
DEFAULT_LOCALE=fr

Hello,
I made a fresh install on a new machine and did not noticed any error while doing the installation. But something went wrong because
1/ the confirmation email (the first one the user receives just after having created his account), seems not to be sent -> it is not counted as an error in Sidekiq but never received 
2/ if as admin I choose to reset the password, that email is received 
3/ if as the user, I choose "password forgotten" from the login screen, that one is received too
4/ any other email is received (following request, mention, etc).

Only the initial one is always missing (I tried with 10 different accounts). The missing emails are seen as having sent in Sidekiq.

Don't know if important or not, below my configuration:

SMTP_SERVER=my_exchange_domain
SMTP_PORT=587
SMTP_LOGIN=account@domain.tld
SMTP_PASSWORD=my_password
SMTP_FROM_ADDRESS=account@domain.tld
#SMTP_DOMAIN=                 # defaults to LOCAL_DOMAIN
#SMTP_DELIVERY_METHOD=smtp               # delivery method can also be sendmail
SMTP_AUTH_METHOD=**login**                   
#SMTP_OPENSSL_VERIFY_MODE=peer
SMTP_ENABLE_STARTTLS_AUTO=true

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by saggel** [comment]
Might not help, but have you checked if they end up in a spam folder?
I had the same problem: changed the IP of the mail server and it was fixed!

**Comment by svanneste** [comment]
Thanks. Of coure, I did check and they weren't in any of the spam folders. I even checked by disabling SpamAssassin. :)

**Comment by svanneste** [comment]
Adding the logs after having read some related issue: if I do correctly understand, the mail is sent. I have tried with mailgun instead of my own server and got the same behavior (mail address anonymised but correct in the logs)

**journalctl -u mastodon-sidekiq**
`avril 26 23:49:32 mstdn.paris bundle[565]: 2017-04-26T21:49:32.395Z 565 TID-othmhuqtg ActionMailer::DeliveryJob JID-2c700402c1a7974bf4ae3e93 INFO: start
avril 26 23:49:32 mstdn.paris bundle[565]: [ActiveJob] [ActionMailer::DeliveryJob] [8dcc57bd-0437-44bc-8c5b-a1e4857e6eb9] Performing ActionMailer::DeliveryJob from Sidekiq(mailers) with arguments: "UserMailer", "confirmation_instructions", "deliver_now", #<GlobalID:0x007f5cafcd2608 @uri=#<URI::GID gid://mastodon/User/7>>, "oNSjssFc1nKsqFQ_bh7y", {}
avril 26 23:49:33 mstdn.paris bundle[565]: [ActiveJob] [ActionMailer::DeliveryJob] [8dcc57bd-0437-44bc-8c5b-a1e4857e6eb9] Sent mail to mymail@domain.tld (703.7ms) 
avril 26 23:49:33 mstdn.paris bundle[565]: [ActiveJob] [ActionMailer::DeliveryJob] [8dcc57bd-0437-44bc-8c5b-a1e4857e6eb9] Performed ActionMailer::DeliveryJob from Sidekiq(mailers) in 1155.92ms
avril 26 23:49:33 mstdn.paris bundle[565]: 2017-04-26T21:49:33.607Z 565 TID-othmhuqtg ActionMailer::DeliveryJob JID-2c700402c1a7974bf4ae3e93 INFO: done: 1.212 sec
`

**Comment by svanneste** [comment]
I think I have managed to find the reason : if I comment the DEFAULT_LOCALE, the mail is delivered.
When I uncomment it, the mail is not sent.
@Gargron for information
