### ISSUE TITLE
Error on Authorized Apps tab

### ISSUE THREAD

**Issue by saggel** [tootsuite/mastodon#2439]
On the administration page, on the "Authorized Apps" tab, I get a "We're sorry, but something went wrong" error. Everything else works fine though! What could be wrong? 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [1.2.2]

**Comment by ashfurrow** [comment]
What URL is this? `/oauth/authorized_applications`?

**Comment by saggel** [comment]
Thank you for your answer - yes that's the URL
/oauth/authorized_applications

**Comment by ashfurrow** [comment]
Who is the administrator of your account? It would be helpful to have server logs to help us debug the problem.

**Comment by saggel** [comment]
I am the administrator of the instance - let me know what should I provide you with (and also how, if possible)

**Comment by ashfurrow** [comment]
Gotcha, thanks for the quick follow-up. Are you using Docker? Vagrant? You're looking for the Rails logs with something like `status=500`.

**Comment by saggel** [comment]
Not on Docker - just following the guidelines on the documentation page for the installation! I've installed it a few times already and my instance works for two days now with no problems other than this! I'll try to find the Rails logs!

**Comment by saggel** [comment]
Is it on: log/production.log
That's empty... keep looking!

**Comment by saggel** [comment]
OK - not sure what could have gone wrong - I took the instance down, updated mastodon and now the tab works!

**Comment by Gargron** [comment]
This is fixed in master and will be in the next release.
