### ISSUE TITLE
better notifications

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#244]
currently: notifications do some things a little weird. they show your username and avi for the post that someone else is favoriting. it's very worth noting that on big toots this uses A LOT of space. a bigger problem is: it shows pictures. if you post something with gifs, it will show the gifs, that can very easily slow down slower computers and if one person is popular, they will get tens unto eventually hundreds of their own gif all over again, to slow their computer down.

i would propose: simplifying what it shows for favorites and retoots. possibly only the first X characters of a toot, and also not any images from said toot.  also the ability to only show mentions, or to group other notifications together would greatly improve scalability. thank you for listening

**Comment by Gargron** [comment]
Oh yeah removing media gallery/video player on muted status components should be a thing.

**Comment by Skirmisher** [comment]
Since this is about improving notifications in general: add timestamps to actions (following, favoriting, reblogging) that appear in the notifications.

**Comment by hoodiek** [comment]
as i have come to enjoy this platform and since i have made this post, more problem have shown their heads: things like this 
the following is _a single person_ catching up on my posts. this obscures what i've been up to, and as a result for this person who i will not name, i had to block them so i can even funcitonally use my notifications column
![image](https://cloud.githubusercontent.com/assets/23704040/21025082/170c1c8e-bd55-11e6-936a-26bcea0d641b.png)


ways this could be fixed are first: the ability to filter out any of the followering: favourites, boosts, and follows, so if you filter all of them out it is only mentions. in addition to this i would propose a filter to filter all but mentions that have been replied to out

i will show the UI i imagine in a moment, after sketching it out in MSpaint since i don't particularly have any other tools for this task.

**Comment by hoodiek** [comment]
![image](https://cloud.githubusercontent.com/assets/23704040/21025572/e54d0968-bd56-11e6-96f9-fd75a9c226bb.png)

and here we go. the boxes by each icon (for follow, boost, and fav) would remove each from the column. the leftmost box out of that tetris piece shape would remove all 3. the check by the eye would hide any toots you replied to from the column

**Comment by swaldie** [comment]
As @hoodiek referenced a moment ago, issues similar to #332 will be referenced here as well for consolidation's sake.

**Comment by hoodiek** [comment]
EDIT! i noticed that #182 could also be merged, and added to my UI mockup. 
![image](https://cloud.githubusercontent.com/assets/23704040/21026232/b7365298-bd59-11e6-95b2-7dd0699e1f6d.png)

now this also encompasses the issue of managing which notifications need to go to the desktop via browser: NOTE: if you expand the desktop notifications tab, the eye would not be present

**Comment by swaldie** [comment]
See what was referenced by @hoodiek. Issues pertaining to #182 can be discussed here as well.

**Comment by hoodiek** [comment]
![image](https://cloud.githubusercontent.com/assets/23704040/21026672/b6995b6c-bd5b-11e6-9cab-d107352e6412.png)
FINAL ADDITION: merging of #274 brush image to mark as read all notifications and thus flush the column into emptiness

**Comment by hoodiek** [comment]
also worth noting despite me not being up to redrawing and organizing at this moment: if the eye was moved to the right, and properly sectioned off, then it would also allow a description of all of the things to fall on the left side of the drop down, effectively allowing easier understanding of what it all does

**Comment by hoodiek** [comment]
once settings persist, if a clear-notifications is added, and a unreplied-to-posts-only can be added, this can be closed
