### ISSUE TITLE
Hashtag timelines don't include private posts even if you are allowed to see them

### ISSUE THREAD

**Issue by saggel** [tootsuite/mastodon#2440]
When you have hashtags on private toots they don't appear in the hashtag timeline even if you follow the user who posted it. I think that might be a bug (or a feature depending how you see it).

* * * *
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Yeah, that's intentional.
