### ISSUE TITLE
Hashtag hyperlinks broken when hyphenated

### ISSUE THREAD

**Issue by daynaskully** [tootsuite/mastodon#2452]
A hashtag with a hyphen will break.

#gnu-social for example will display as [#gnu](#)-social instead of [#gnu-social](#)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
Does GNU Social work differently? I just checked Twitter and they don't allow hyphens in hashtags either.

**Comment by Artoria2e5** [comment]
It seems that they do allow hyphens in hashtags (`'/(?:^|\s)#([\pL\pN_\-\.]{1,64})/u`), cf. https://git.gnu.io/gnu/gnu-social/blob/a7043bf7/classes/Notice.php#L348.

**Comment by ashfurrow** [comment]
Thanks for looking into that. As it's not supported on GS/Twitter, I think we should close. Please feel free to re-open if this hasn't be answered to your satisfaction.
