### ISSUE TITLE
Ability to mute hashtags in local and federated timelines

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#2453]
I would really like the ability to mute posts containing particular words or hashtags that I don't want to read about, specifically in the local and federated timelines.

This is because [someone suggested setting up event-specific instances as a way to not flood the local and federated timelines with a particular event that's not of interest to everyone](https://octodon.social/users/miramarco/updates/90315), which seems to me like a lot of work for admins to do for every transient event! Also if I want to talk about one specific event a lot for like one week, I don't want to have to set up a whole new account to do that.

~

This is mentioned in #2331 but I think it would be good to implement regardless of the other requests in that post. There's no indication, as far as I can see, that anyone is going to do the things in that thread. I'm not sure if this is considered a duplicate that should be closed, so if you think I should close it, please feel free to thumbs-down (or just close it, if you've got the power!).

* * * *

- [Yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by somethingeloquent** [comment]
I would personally really enjoy a feature like this (including the home TL as well as local and federated). Aging the option to opt-out of certain types of conversation could serve to enrich the user experience without forcing them to decide to mute an entire person based off of a single thread.

**Comment by sandhawke** [comment]
Thinking about this kind of thing more, what I really want is opt-in hashtags, because I know I'm going to posting a ton about something, and I don't really want to bother people who aren't interested, but I know there will be some bunch of people who are quite interested.   (Other workaround is everyone makes another account just for talking about the other topic; that needs another instance at the moment because default mastodon code limits folks to one account per email.)

**Comment by deutrino** [comment]
List of dupes I found of this issue:

- #694 (muting keywords from timelines)
- #1158 (muting keywords from timelines)
- #2453 (muting hashtags and keywords from timelines)
- **#3848 (muting by keywords, improve the accessibility beyond "lern2regex noob", listed as a priority for version 2.1)**
- #4081 (specifically requesting that muting by keyword work in CWs as well)
