### ISSUE TITLE
Missing target="blank" in the URLs contained in the profile description

### ISSUE THREAD

**Issue by pixocode** [tootsuite/mastodon#2454]
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [1.2.2](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
It may be fixed in #2622.

**Comment by LinAGKar** [comment]
There is no reason for you to force people to open links in an new tab when they don't want to
