### ISSUE TITLE
Favorites show avatar of original author, not of user who favorited

### ISSUE THREAD

**Issue by mweinelt** [tootsuite/mastodon#2456]
When a toot is favorited we repeatedly see our own avatar instead of the one of the user favoriting it. However the primary purpose of the notification should be who favorited the toot, which is why I expect to see their avatar.

![Mastodon Favoriting](https://i.imgur.com/0NO2688.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Now another avatar is overlayed over the original one.
