### ISSUE TITLE
Version identification

### ISSUE THREAD

**Issue by vladooku** [tootsuite/mastodon#2472]
Would be nice for a version id text somewhere on the main page of the app or even in the About version we're hosting on our instances, no matter where, just for reference after we push to our servers the latest tootsuite/master branch. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
Yup yup, totally agreed. This has been fixed in https://github.com/tootsuite/mastodon/pull/2181 and will be included in the next release of Mastodon. Thanks!
