### ISSUE TITLE
"©", "®" and "™" are converted to color fixed emoji

### ISSUE THREAD

**Issue by ttrace** [tootsuite/mastodon#2475]
[Issue text goes here].
When posting toots including "©", "®" or "™", rendered HTML shows color sat emoji.
It is hard to read dark-gray emoji on dark-gray background.
<img width="298" alt="screen shot 2017-04-26 at 16 20 03" src="https://cloud.githubusercontent.com/assets/113245/25422567/3f7d1574-2a9c-11e7-9718-e6eba7b30fda.png">
[https://ostatus.taiyolab.com/web/statuses/15360](https://ostatus.taiyolab.com/web/statuses/15360)

Auto emoji converting feature is cool, but several symbol, especially "©", "®" or "™" should be stayed as standard Unicode text which allows CSS color, as below.
<img width="296" alt="screen shot 2017-04-26 at 16 28 48" src="https://cloud.githubusercontent.com/assets/113245/25422884/79518964-2a9d-11e7-9804-ab97c5f7770a.png">
* * * *

- [✓] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [✓ ] This bug happens on a `master`

**Comment by ykzts** [comment]
@ttrace see #1234

**Comment by ttrace** [comment]
thanks,
