### ISSUE TITLE
missing.png repeated

### ISSUE THREAD

**Issue by ashfurrow** [tootsuite/mastodon#2476]
`missing.png`, the default avatar, appears to be copied _per user_ instead of having one copied referenced multiple times. This is problematic because it takes up unnecessary storage space and weakens the effectiveness of [caching](https://github.com/tootsuite/mastodon/issues/1847), especially over CDNs. 

Reported here: https://computerfairi.es/@squirrel/129374

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [AFAIK] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tcitworld** [comment]
The best would also be to have a task to delete all not necessary files.

**Comment by Gargron** [comment]
1. Option one: remove avatar from Atom feeds if it's missing. Other instances will use their own missing.png for display instead
2. Option two: keep as is if you want to see the missing.png-esque picture other instances might have customized

**Comment by tcitworld** [comment]
I'm more for option two, but couldn't we know that the avatar in question is the default one? For instance another element in the atom feed ?

**Comment by maop** [comment]
Option 2.1: Keep ONE missing.png PER instance and then refer to it all the remote users from that instance without avatar.

Also for sane of sysadmins  maybe save it to `instance_fqdn/missing.png` or `missing_instance-fqdn.png` ?

**Comment by mjankowski** [comment]
I don't have a great idea for how to do this, but something at the paperclip/storage level which was like "if two files have the same name and the same size and the same md5sum, just store one copy" would be pretty useful here.

For now though, I actually think continuing to store every image maybe coupled with some "delete things we haven't needed in a while" rake task, is probably fine.

**Comment by Gargron** [comment]
The solution to both this and #2317 is to abstract MediaAttachment slighty further by having it refer to another table that would store the actual files, independently of any associated accounts, with a file fingerprint. Then periodic task to clean orphaned records.
