### ISSUE TITLE
New Domain Block help is inaccurate, refers to "accounts"

### ISSUE THREAD

**Issue by fpiesche** [tootsuite/mastodon#2479]
The help text on the Domain Blocks > Add New page on the admin backend refers to account suspensions and how "silence"/"suspend" will affect the actioned accounts. This should probably be rewritten to actually match the functionality. I would propose something along these lines.

> **Silence** will hide all posts from accounts on this instance from public timelines but not affect federation or content mirroring to your server. Users will still be able to interact with other users on the silenced domain as normal and media and posts will be mirrored to your local database.
>
> **Suspend** will remove all of the content, media, and profile data (profile pictures/banners, bio text etc.) related to any accounts on the instance and reject future data from this instance - though local accounts will still be created for users from the domain. This *will* prevent any users on your Mastodon instance from interacting with users on the suspended domain.

**Things to consider:**

- I'm not 100% certain what data a suspension removes so this should be checked and edited by someone familiar with the functionality
- If a suspension also prevents content from your instance federating out to the suspended domain, this should be added to the info

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on [tagged release](https://github.com/tootsuite/mastodon/releases) 1.2.2 and not on `master`.

**Comment by Gargron** [comment]
I mean, the way domain blocks work (and this is kinda explained on the page I think) is that it applies the very same moderation tools you can use individually, but automatically for everyone from a domain. Unless this principle changes, this explanation is still accurate.
