### ISSUE TITLE
Suspended user can't sign out

### ISSUE THREAD

**Issue by mikoim** [tootsuite/mastodon#2491]
## Suspended user can't log out

Sign out page also return 403 when the user is suspended, so they can't sign out from the instance without clearing cookie.

https://localhost/auth/sign_out

## How to reproduce
1. Logged in as victim user
2. (In another browser) Logged in as admin
3. (In another browser) Suspend the user
4. All pages return 403 also include sign out page (To sign out, clear cookie or wait session expired or unsuspend by admin)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yiskah** [comment]
once you're banned you're trapped in mastodon jail forever!! 😈 (jk)

In all seriousness, is there an issue if a suspended user can't end the session if they can't use the site anyway? Just trying to determine what priority tag I should give this
