### ISSUE TITLE
oEmbed iframe height seems to be 600 everytime

### ISSUE THREAD

**Issue by danito** [tootsuite/mastodon#2492]
I use the oembed.json api to get the embed iframe link to add them into my posts in https://github.com/Idno/Known, but UX gets broken as even for small toots, the height == 600 so plenty of white space is left after the content. Is there any way to calculate the actual height and reduce accordingly?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
It has been changed to null now. But there is of course still an issue because iframes cannot adjust to content height automatically. I think it can only be solved with JS.
