### ISSUE TITLE
Question: Replace the mastodon

### ISSUE THREAD

**Issue by saggel** [tootsuite/mastodon#2494]
The question is twofold here, first to the creators who are guiding the development of mastodon, and then an open one!

I am interested in replacing the mastodon design - I run an instance for cigar smokers so I was thinking to replace it with the same mastodon, but with a cigar in its mouth. 

1. Would that be acceptable?
2. If so, will the picture be replaced on each update?

Also, if that's fine, I was thinking about doing something similar with the mastodon logo, not far from the original of course again, how would that fit with your plans?

Hopefully you won't perceive my post insulting, just asking so that I know whether you like the idea!

Thank you in advance!
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
I can't answer the "will it be acceptable" question, but my hunch is "yes" as long as you release your changes back under open source.

As for _how_ to customize things, there's a [custom css file](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Customizing.md), and you'll only have to re-replace any assets if they get changed by the project. You can see all the customizations I've made to mastodon.technology here under the "files changed" tab: https://github.com/tootsuite/mastodon/compare/master...ashfurrow:master

**Comment by saggel** [comment]
Thank you for your quick response, @ashfurrow. I would only need to change the mastodon picture so there's no code alteration involved, I'll just redesign the existing mastodon with a cigar in its mouth (or at least that's what I have in mind). And sure not a problem of it being under open source license! Thanks for the customization advice, I'll have a look on how to keep things neat and tidy - I'm new to github!

**Comment by ashfurrow** [comment]
I've got confirmation that this is okay, totally within the bounds of the open source license and spirit. I'm going to close the issue but if it's not been answered to your satisfaction, please re-open. Thanks!

**Comment by saggel** [comment]
Thank you very much @ashfurrow
