### ISSUE TITLE
Question: Mastodon instance on subdomain

### ISSUE THREAD

**Issue by saggel** [tootsuite/mastodon#2496]
I'm interested in setting up a new instance as a subdomain of an existing website 
domain.com/mastodon or mastodon.domain.com

The mastodon server will be separate from the site server! What I would like to know is whether it'll be possible to have the users as: @user@domain.com instead of @user@mastodon.domain.com

By the way if I'm using the wrong place to post these type of questions please do let me know and sorry in advance!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mecab** [comment]
Yes, you can. Actually you can see many instances running on subdomains on https://instances.mastodon.xyz

But you cannot do like domain.com/mastodon AFAIK.

**Comment by saggel** [comment]
Thank you @mecab - so will the users have @username@domain.com affiliation or @username@subdomain.domain.com?

**Comment by mcat-ee** [comment]
@saggel the latter (: @username@subdomain.domain.tld

**Comment by mecab** [comment]
@saggel Yes, it's as @mcat-ee saids :)

**Comment by saggel** [comment]
@mecab @mcat-ee thank you

one last question then: is there a way to have it as @username@domain.tld with this implementation or should I just get over it and accept it's going to be @username@subdomain.domain.tld ?

**Comment by ThibG** [comment]
This is possible but tricky, and not properly documented yet.
See https://github.com/tootsuite/documentation/pull/149

**Comment by saggel** [comment]
Thank you @ThibG I'll have a careful look! I think it is what I was looking for!

**Comment by Gargron** [comment]
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Serving_a_different_domain.md
