### ISSUE TITLE
Feature Request: store column filters server side

### ISSUE THREAD

**Issue by mkosler** [tootsuite/mastodon#2497]
I've got limited understanding of React / Immutable.js, but it looks like the column filters are just stored in the client web app and not anywhere in the DB. That means users only get the benefits of column filtering on the website. If they switch to Tusky or another mobile app, they'll see the toots that they wanted filtered. Even if third-party apps implement the feature, those app developers would have to roll their own, and users would have to maintain their filters in multiple places.

It would be great if column filters were stored as part of a user's account information and accessible by application developers.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Done
