### ISSUE TITLE
undefined method `deep_symbolize_keys'

### ISSUE THREAD

**Issue by jdcauley** [tootsuite/mastodon#2501]
Deployed to Heroku

Screen shot of Log

http://jdcauley.com/EUIm4
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
I was seeing this in unit tests on [this pull request](https://github.com/tootsuite/mastodon/pull/2441). Are you running off master? Updating to the latest master might fix things, but running a tagged release would be best.

**Comment by jdcauley** [comment]
@ashfurrow I'm deployed using the Heroku button.

**Comment by jdcauley** [comment]
I updated to master, and it's working now
