### ISSUE TITLE
FEATURE: Serve Assets with S3/Minio 

### ISSUE THREAD

**Issue by valentin2105** [tootsuite/mastodon#2506]
Hi,

I switched to Minio one week ago for Mastodon.cloud, it work at glances.

To make Mastodon components fully stateless, it would be really great if we can host the Assets in S3 too. 

Some new environment variables like this would be really awesome : 

```
S3_ASSETS_ENABLED=
S3_ASSETS_ENDPOINT= 
```

How difficult to implement is it ? 

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by csu** [comment]
Isn't this already supported? See the S3 section of the .env config file: https://github.com/tootsuite/mastodon/blob/master/.env.production.sample#L60. Or are you asking for something different?

**Comment by valentin2105** [comment]
It's implemented for Pictures (avatars, uploads), but NOT for CSS & JS ? 

😄

**Comment by mecab** [comment]
Though I haven't try, but the variable `CDN_HOST` won't help it?

**Comment by valentin2105** [comment]
I don't really know how to use this variable, 

but if I host my assets behind a Nginx called by `CDN_HOST` for example, 

How to make my `assets:precompile` tasks update theses distant assets. 
If they could be in S3/Minio, the rail task would upgrade this directly in S3.

**Comment by ashfurrow** [comment]
The `CDN_HOST` I believe is for static assets, @valentin2105 appears to be asking about the `/assets` directory of the app (JS+CSS).

There're related discussions [here](https://github.com/tootsuite/mastodon/issues/1847) and [here](https://github.com/tootsuite/mastodon/issues/2040) if you're interested in looking up more info.

In the meantime, take a look at [this gem](https://github.com/AssetSync/asset_sync).

**Comment by Gargron** [comment]
You can upload them anywhere after precompiling and change ASSET_HOST
