### ISSUE TITLE
Help using websocket trought another port than 80/443 (Anti-DDoS)

### ISSUE THREAD

**Issue by Technowix** [tootsuite/mastodon#2509]
Following the issue I got [here](https://github.com/tootsuite/mastodon/issues/2462), I got in touch with my service provider who told me that port 80/443 are really sensible when websocket pass trought thoses two ports (80 and 443)
I'm not an expert in proxy redirect, so I'm here to get some help about how I can "pass" the streaming (right ?) trought another port to let the anti-ddos do his work without problem.
Thanks for tips :) !

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
STREAMING_API_BASE_URL can point to anywhere you want, so if you run on a different host/port you just put it there.
