### ISSUE TITLE
Sign up call-to-action could be more prominent

### ISSUE THREAD

**Issue by ccoenen** [tootsuite/mastodon#2523]
I am trying to convert people over to mastodon, to achieve that, (among other things) I often give people links to other accounts. I am using the profile page, like this one: https://chaos.social/@amenthes

I find this page great for the most part, but one thing bugs me: there is no context and nowhere to go for new users. At the very least there should be a way to get back to the instance's start page. Perhaps even a "sign up"/"create your own account" button somewhere. I mean some place more prominent than the tiny footer.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
There is an existing call-to-action to signup at the top, if you're not logged in:

<img width="734" alt="screen shot 2017-04-27 at 11 39 57 am" src="https://cloud.githubusercontent.com/assets/498212/25477567/487fe5aa-2b3e-11e7-8b31-cbb476c36a6b.png">

I agree it could be more prominent. Any ideas?

**Comment by ccoenen** [comment]
Whoops! didn't see it because i _was_ signed in. Nevermind. Thanks for taking the time to post the screenshot. I am happy with that. Feel free to close this issue (or don't close it and take it even further!)

**Comment by ashfurrow** [comment]
No problem! I think that the call-to-action could be more prominent so I'm going to rename the issue 👍
