### ISSUE TITLE
Remote follow username syntax doesn't match usernames in the main UI

### ISSUE THREAD

**Issue by alexgleason** [tootsuite/mastodon#2528]
For instance, normally my username is this:

```
@alex@animalliberation.social
```

But remote follow makes me type it like this:

```
alex@animalliberation.social
```

The latter is like an email, and the former is the Mastodon syntax we have come to expect. The remote follow UI should allow the former, and maybe even reject the latter.

**Optional tangent:** I'm not sure why this convention is used. I like how Matrix uses `@user:host.tld` since it doesn't have excess @ symbols. But then I wonder what was wrong with the email syntax to begin with... is this new way just to differentiate these names as a new thing which isn't email?

**Comment by ara4n** [comment]
fwiw, i got tripped up the first time i tried to do a remote follow and assumed it was `@user@domain` rather than `user@domain`.  The reason Matrix has its weird `@user:domain` syntax is deliberately to avoid confusion of matrix IDs with email addresses (or JIDs, or SIP URIs, or ostatus IDs...)

**Comment by nightpool** [comment]
I like the @ convention, but this bug totally tripped me up.

**Comment by mjankowski** [comment]
Would the desired improvement here be to have the remote follow page just strip off a leading `@` from the supplied username?

I think that would work ... because it's not a valid character to a URL, and not a valid character in the username portion of an `acct` string...

**Comment by Gargron** [comment]
I think I fixed this in v1.4 but forgot to tag it
