### ISSUE TITLE
Bots & Terms of Service and Privacy Policy

### ISSUE THREAD

**Issue by tdelmas** [tootsuite/mastodon#2530]
Please add a section about Bots in the "Terms of Service and Privacy Policy".
For example:
"Bots are allowed if they specify their owner in their bio."

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by tswast** [comment]
Also, it's not written anywhere that I can find that data can legally be used from the API or via federation.

The privacy policy doesn't seem to grant federated servers, mobile client software, or bots the right to download / process toots, but obviously the software works that way. It would be good to clear that up.
