### ISSUE TITLE
PhantomJS web automation with Mastodon

### ISSUE THREAD

**Issue by kensoh** [tootsuite/mastodon#2531]
Hi Developers and Users of Mastodon, may I kindly check if anyone have success logging into Mastodon and performing web interactions using PhantomJS? This is not a bug report and there isn't a duplicate issue on this question.

Someone on Mastodon has a use case to automate posting her comic posts to her Mastodon account. Source is a RSS feed. Ideally it should be done using Mastodon API. I'm more familiar with web automation so I tried doing it using a general purpose [web automation tool](https://github.com/tebelorg/TA.Gui) I made that is based on CasperJs/PhantomJS/SlimerJS.

I was able to use below script to automate posting a private toot when running through Firefox/SlimerJS. But running through PhantomJS I get a blank dark grey screen after the login step. I also tried changing User Agent to make sure it is not due to explicit blocking by Mastodon design. I would not want to use headless browser approach if app/website owner explicitly do not want to serve headless browsers.

Accessing a Mastodon status post directly without login works and image capture is alright. Copying @DavidLibeau as he is working on Mastodon status sharing to other networks which I believe going through PhantomJS for screen capture.

```
https://mastodon.social/auth/sign_in
enter user_email as your_email
enter user_password as your_password
click Log in
click Adjust status privacy
click Post to mentioned users only
enter autosuggest-textarea__textarea as Automated test message to @yourself@your_instance
click Toot
click Logout
```

**Comment by DavidLibeau** [comment]
My script use PhantomJS but I can't help you much more... It was the first time I used this thing... :confused:

**Comment by kensoh** [comment]
No probs @DavidLibeau thanks for your reply. I think your app captures directly from a status URL which is working fine for me as well. For example, https://mamot.fr/@n1k0/673330. However, if I try logging in using PhantomJS it goes into a blank screen for some reason. Logging in using SlimerJS/Firefox works.

I can use Xvfb to run Firefox headlessly, but adding that complexity will increase odds of automation failure. Hopefully someone has some experience to add on. If not it's ok too, I'm just taking a look at this for a fellow Mastodon user out of goodwill, and personal interest.

**Comment by kensoh** [comment]
Closing this issue as there is no response any PhantomJS users for 2+ weeks.

This issue's ownership should be at PhantomJS repo. I'll make an update there ;)
