### ISSUE TITLE
Rake aborted on maintenance tasks

### ISSUE THREAD

**Issue by saggel** [tootsuite/mastodon#2542]
When I run the maintenance tasks found here: https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Maintenance-Tasks.md

I get this warning:

`WARNING: Sidekiq testing API enabled, but this is not the test environment.  Your jobs will not go to Redis.`

followed by:

```
rake aborted!
NameError: uninitialized constant ActiveRecordQueryTrace
/home/mastodon/live/config/environments/development.rb:85:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:599:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:599:in `block in <class:Engine>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
/home/mastodon/live/config/environment.rb:5:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/application.rb:328:in `require_environment!'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/application.rb:448:in `block in run_tasks_blocks'
Tasks: TOP => mastodon:media:clear => environment
```

Am I doing something wrong or is this a bug?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by joyeusenoelle** [comment]
Try prepending "RAILS_ENV=production " to the commands:

RAILS_ENV=production rake mastodon:media:clear
RAILS_ENV=production rake mastodon:push:clear

etc. 

I get your error when I run the commands as written, but they run properly with RAILS_ENV set.

**Comment by saggel** [comment]
Thank you @joyeusenoelle - it worked like this!
Maybe it needs to be explained or corrected in the documentation!

**Comment by joyeusenoelle** [comment]
Glad you got it working! I've submitted a pull request to add this information. :)

**Comment by saggel** [comment]
Awesome - thank you!
