### ISSUE TITLE
I18N: Hardcoded "!" after "TOOT" button text probably not a good idea

### ISSUE THREAD

**Issue by Artoria2e5** [tootsuite/mastodon#2549]
The `compose_form.publish` key in JSX translations define the text to be used for the TOOT button, but apparently the control is not always on the translators' side: in zh-cn.jsx I placed a fullwidth exclamation mark `！` (correct for Chinese) after the translation, only to find the text now followed by two exclamation marks `！!`. This should probably get a change somehow.

* * * *

- I didn't perform careful searching.
- I am seeing this on mstdn.io, which should be running the 1.3.0 tag.

**Comment by Artoria2e5** [comment]
https://github.com/tootsuite/mastodon/blob/416c9675fc20be41ea4bbc915cf14c84170d5fe5/app/assets/javascripts/components/features/compose/components/compose_form.jsx#L130

Ah, it's a privacy indicator. Consider making that `!` translatable.

**Comment by msappir** [comment]
This isn't a very good way to mark toot visiblity anyway. Right now, private/direct toots show a lock icon on the toot button - how about generalize this indication, with a distinct icon for each level of visibility, displayed on the button no matter which is active?
