### ISSUE TITLE
Hide bulk of longer posts from different sites

### ISSUE THREAD

**Issue by unsmell** [tootsuite/mastodon#255]
earlier today I saw a post in the public timeline, 2935 characters in length, from a different instance. It covered the entire public timeline.
I propose posts >500 characters long should only be displayed in full when the user opens it

**Comment by josefkenny** [comment]
In my opinion, this should probably be implemented as a more general clientside solution to people posting toots with a very large number of lines. I.e., decide to truncate the display of posts based on the height of the `status__content` div element, or by counting `\n`s, whatever is least resource-intensive.

**Comment by unsmell** [comment]
that would help in cases where users abuse the 500 character limit and make ridiculously long posts. Such as, 
![image](https://cloud.githubusercontent.com/assets/2267475/20604366/91a41628-b255-11e6-9cf6-ecd56d54736a.png)

**Comment by msappir** [comment]
This aspect of federation can be confusing for newbies. For more transparent UX, I suggest the "read more" link in these cases, or a little question mark icon next to it, should have a tooltip explaining this. Something like:

> This toot is longer than Mastodon allows - the instance it comes from probably follows different rules. Click through to see the full toot.

**Comment by jeroenpraat** [comment]
I didn't found this one while searching.

But it is really needed. See #5477

**Comment by kr428** [comment]
Adding myself to this after having gone through some more or less rough discussion. For whatever it's worth: Would it be possible to remove the post length restriction from mastodon altogether and make this something "clients" (web application, mobile apps) should take care of? Thoughts on that:

- This restriction generally doesn't make much sense in a federated environment. There's Friendica, Diaspora or GNUSocial which allow for postings substantially longer than 500 chars.
- If you end up in an actual communication on some issue (which I definitely consider a *good* thing), a fixed limit only increases the amount of (split-up) messages as, at some point, you won't be able to write down your arguments in < 500 chars.
- Apart from this, the confortable length of posts seems to drastically differ depending upon context: At nights on my desktop, large screen and enough time for reading, it's way easier to deal with long posts than on my smartphone while commuting.

Thanks for considering this. :)

**Comment by lanodan** [comment]
[Crosspost of https://github.com/tootsuite/mastodon/issues/7973#issuecomment-413060740 as it’s a duplicate issue]
Just so that the people here are aware of it.

I made a PR(#8205) that rebases an old one (#658) fixing this long post issue.

My point on this thread would be that Tootsuite’s mastodon should be aware that the whole Fediverse doesn’t works like Toosuite wants, and that anyway even with 500 characters one can make a post that is too long for the Mastodon UI. (too much newlines for example)

**Comment by Gargron** [comment]
Fixed in #8205
