### ISSUE TITLE
Small part of NSFW-tagged images is shown on profiles and toots

### ISSUE THREAD

**Issue by corzntin** [tootsuite/mastodon#2559]
Hi,

A small part of NSFW-tagged images is shown on profiles and toots (on the "non-UI" side), on v1.3.1.

See this toot for example :

![capture](https://cloud.githubusercontent.com/assets/7571771/25509479/970b3b4a-2bb9-11e7-94e0-6ba7942e36fa.PNG)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by expenses** [comment]
What's the problem here?

**Comment by corzntin** [comment]
The black part above the grey "sensitive content" box is a part of the image, the grey box isn't hidding it all.

**Comment by expenses** [comment]
See also #2484.

**Comment by ashfurrow** [comment]
Yikes, thanks for opening an issue 👍
