### ISSUE TITLE
"Custom" translation fallback?

### ISSUE THREAD

**Issue by Artoria2e5** [tootsuite/mastodon#2560]
Mastodon's Rail part currently seems to use some basic fallback functionality provided by `config.i18n.fallbacks`, which according to [some documentation](https://github.com/svenfuchs/i18n/wiki/Fallbacks) chops away suffixes connected by `-` one by one before consulting the default locale (`en`). However, this is almost entirely useless for `zh` which always have the language codes written with country codes.

According to some other [magical writings](http://pawelgoscicki.com/archives/2015/02/enabling-i18n-locale-fallbacks-in-rails/), this same fallback mechanism can be [extended](https://github.com/svenfuchs/i18n/wiki/Fallbacks#custom-fallback-rules) to specify a few other fallback locales to look at before invoking the same tail-chopping sequence. This can be very useful for the two Chinese variants (zh-HK, zh-TW) written in the same script as well as future language additions like yue-HK to zh-HK (same script, very different phonetics).

Similar fallback behavior on the JSX side can be simulated by pouring some twigs (`||`) into `getMessagesForLocale` in [app/assets/javascripts/components/locales/index.jsx](https://github.com/tootsuite/mastodon/blob/master/app/assets/javascripts/components/locales/index.jsx).
* * * *

- Yes, I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- This issue is not quite a bug, and what it is asking for is not on any single version anyway.
- I am not sure about whether adding these fallback stuff is the right thing to do.

**Comment by Gargron** [comment]
I think what you want can be done by setting the DEFAULT_LOCALE environment variable.

**Comment by Artoria2e5** [comment]
Asking for something like a chain defined for all Masto deployments ("custom" is given relative to original Ruby facilities), so a single default locale is obviously not enough…
