### ISSUE TITLE
Release notes for v1.3 typo

### ISSUE THREAD

**Issue by djchen** [tootsuite/mastodon#2562]
> This release includes database migrations, that means you need to run RAILS_ENV=production bundle exec rails db:migrate (in Docker: docker-compose run --rm web rails db:migrate)
> This release includes changes to assets, that means you need to run RAILS_ENV=production bundle exec rails assets:precompile (in Docker: docker-compose run --rm web rails assets:precompile)

Where it says `docker-compose run --rm web`, it should say `docker-compose run --rm rake`

**Comment by mjankowski** [comment]
I think those instructions are accurate, and they are consistent with the docs: https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md

In that docker command, the `rails db:migrate` portion is what runs that task, so `rake` is not needed.

Please re-open this or submit a PR against the docs if I don't understand the issue.

**Comment by djchen** [comment]
I ran what was in the release notes and it did not do anything so I ran what is in the docs:
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md
Which is
`docker-compose run --rm web rake db:migrate`
Compared to what was in the release notes
`docker-compose run --rm web rails db:migrate`

The one from the Docker Guide is correct and correctly applied the DB updates for me.

**Comment by mjankowski** [comment]
Weird. Those commands *shoild* do the same thing, unless rake of rails are set up in a weird way.

Can you open an issue on docs repo if something there doesn't work as claimed?
