### ISSUE TITLE
public & federated timelines scroll the entire UI on safari 10.1

### ISSUE THREAD

**Issue by bunnyhero** [tootsuite/mastodon#2568]
this just started happening tonight, for me:

when the public or federated timelines are open in the 4th column, trying to scroll that column scrolls the entire window instead. i've observed this on octodon.social, mastodon.social, and awoo.space, but *not* elekk.xyz (all of their 'about' pages say they're running 1.3.0?)

here's a video of it happening: https://octodon.social/@bunnyhero/1271922

this bug does not occur on chrome or firefox, nor in safari technology preview release 28.

i'm on a macbook pro 2016 running macOS sierra 10.12.4 (16E195). safari is version 10.1 (12603.1.30.0.34)

thanks!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by expenses** [comment]
Happening here too on [mastodon.cloud](https://mastodon.cloud).

**Comment by ashfurrow** [comment]
Yikes, that's no good.

**Comment by zproc** [comment]
Same thing here since yesterday for me on mastodon.social (or witches.town) with Safari 10.1 (on OSX/macOS 10.11.6 El Capitan).

**Comment by BrodyB** [comment]
Also been noticing this lately.

Happens on latest version of Safari (10.1) but does not happen in Chrome or Firefox.

**Comment by broomweed** [comment]
My friend is experiencing this as well on toot.cat (mastodon 1.3.2, safari 10.1).

**Comment by aral** [comment]
This started happening for me with 1.3.2 with the federated timeline column.

Based on a cursory glance, it looks like `position: absolute` is not being set on the column, whereas it is (as an inline style), on the other columns when displayed.

The following fixes it for me:

`<div aria-hidden="true" class="mastodon-column-container" style="position: absolute;">`

**Comment by ashfurrow** [comment]
Good find @aral – would you be free to make a pull request fixing this?

**Comment by Gargron** [comment]
Seems fixed.
