### ISSUE TITLE
Something is broken in a way that I don't understand?!?!

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#2574]
[See this thread](https://mastodon.social/@WelshPixie/4521487)!

This is definitely not how I wrote my post!:

![screen shot 2017-04-28 at 09 41 35](https://cloud.githubusercontent.com/assets/6607512/25521318/027ea208-2bf7-11e7-841f-c2ce8caa7c0b.png)

* * * *

- [I honestly don't know what to search except "something is broken?!?!?!"] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [I'm a user] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by svanneste** [comment]
Confirmed and @Gargron already knows it

https://mastodon.social/@Gargron/4528223

**Comment by mjankowski** [comment]
Fixed in master, sorry about issue!
