### ISSUE TITLE
Unable to remote_follow on 1.3.1

### ISSUE THREAD

**Issue by nemsia** [tootsuite/mastodon#2579]
Hello,
After instance upgrade to 1.3.1, unable to remote_follow user on the instance

error on syslog server:

Apr 28 10:46:05 yunohost bundle[31842]: [7aed9f3a-a385-4d0e-b175-b0eaa63d6c77] method=GET path=/users/nemsia/remote_follow format=html controller=RemoteFollowController action=new status=500 error='ActionView::Template::Error: Missing partial authorize_follow/_card with {:locale=>[:fr, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :haml, :rabl]}. Searched in:
Apr 28 10:46:05 yunohost bundle[31842]: * "/opt/mastodon/live/app/views"
Apr 28 10:46:05 yunohost bundle[31842]: * "/opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/kaminari-core-1.0.1/app/views"
Apr 28 10:46:05 yunohost bundle[31842]: * "/opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/doorkeeper-4.2.5/app/views"
Apr 28 10:46:05 yunohost bundle[31842]: * "/opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/devise-4.2.1/app/views"
Apr 28 10:46:05 yunohost bundle[31842]: * "/opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/pghero-1.6.4/app/views"
Apr 28 10:46:05 yunohost bundle[31842]: ' duration=62.63 view=0.00 db=0.87
Apr 28 10:46:05 yunohost bundle[31842]: [7aed9f3a-a385-4d0e-b175-b0eaa63d6c77]
Apr 28 10:46:05 yunohost bundle[31842]: [7aed9f3a-a385-4d0e-b175-b0eaa63d6c77] ActionView::Template::Error (Missing partial authorize_follow/_card with {:locale=>[:fr, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :haml, :rabl]}. Searched in:
Apr 28 10:46:05 yunohost bundle[31842]: * "/opt/mastodon/live/app/views"
Apr 28 10:46:05 yunohost bundle[31842]: * "/opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/kaminari-core-1.0.1/app/views"
Apr 28 10:46:05 yunohost bundle[31842]: * "/opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/doorkeeper-4.2.5/app/views"
Apr 28 10:46:05 yunohost bundle[31842]: * "/opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/devise-4.2.1/app/views"
Apr 28 10:46:05 yunohost bundle[31842]: * "/opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/pghero-1.6.4/app/views"
Apr 28 10:46:05 yunohost bundle[31842]: ):
Apr 28 10:46:05 yunohost bundle[31842]: [7aed9f3a-a385-4d0e-b175-b0eaa63d6c77]     2:   .follow-prompt
Apr 28 10:46:05 yunohost bundle[31842]: [7aed9f3a-a385-4d0e-b175-b0eaa63d6c77]     3:     %h2= t('remote_follow.prompt')
Apr 28 10:46:05 yunohost bundle[31842]: [7aed9f3a-a385-4d0e-b175-b0eaa63d6c77]     4:
Apr 28 10:46:05 yunohost bundle[31842]: [7aed9f3a-a385-4d0e-b175-b0eaa63d6c77]     5:     = render partial: 'authorize_follow/card', locals: { account: @account }
Apr 28 10:46:05 yunohost bundle[31842]: [7aed9f3a-a385-4d0e-b175-b0eaa63d6c77]     6:
Apr 28 10:46:05 yunohost bundle[31842]: [7aed9f3a-a385-4d0e-b175-b0eaa63d6c77]     7:   = simple_form_for @remote_follow, as: :remote_follow, url: account_remote_follow_path(@account) do |f|
Apr 28 10:46:05 yunohost bundle[31842]: [7aed9f3a-a385-4d0e-b175-b0eaa63d6c77]     8:     = render 'shared/error_messages', object: @remote_follow
Apr 28 10:46:05 yunohost bundle[31842]: [7aed9f3a-a385-4d0e-b175-b0eaa63d6c77]
Apr 28 10:46:05 yunohost bundle[31842]: [7aed9f3a-a385-4d0e-b175-b0eaa63d6c77] app/views/remote_follow/new.html.haml:5:in `_app_views_remote_follow_new_html_haml___3035075543037683875_70176041955180'

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
> [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

realy? duplicated with many of issues ( #2545 , #2551 , #2567 ).

**Comment by nemsia** [comment]
Sorry ...
