### ISSUE TITLE
Instances should advertise capabilities for privacy controls.

### ISSUE THREAD

**Issue by geekylou** [tootsuite/mastodon#2580]
It would be useful if an instance (maybe via the users author section in the atom feed) could advertise what privacy options it supports.  This would enable mastodon (or other ostatus platforms) to for example warn the user before sending a direct message to a user on an instance that does not support direct messages.
Something like '<mastodon:supports-scope>direct-message</mastodon:supports-scope> could accomplish this.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wolfteeth** [comment]
+1. I wish they would have implemented this before allowing private post federation. I don't feel it's wise to update my instance to v1.3.x until this is resolved.

The software should be smart enough to see an unimplemented capabilities endpoint as "no privacy supported" and not federate to it.

This change could also enable smarter warnings for DMing or mentioning remote users in private posts if their instance doesn't report privacy supported. Big red letters: "Remote user @x@y.z is on an instance that does not support privacy settings. Your message may appear publicly on their instance."

**Comment by expenses** [comment]
See also: #669.

**Comment by Cassolotl** [comment]
My understanding is that the latest version of Mastodon doesn't federate followers-only or direct posts to instances that don't recognise that level of privacy. Does that solve your issue, @geekylou?

**Comment by Gargron** [comment]
Not relevant after switch to ActivityPub
