### ISSUE TITLE
Error occured on remote follow after update to v1.3.1 release

### ISSUE THREAD

**Issue by abouillis** [tootsuite/mastodon#2582]
Hi,

an error occured when you want to remote follow someone with this type of URL:

https://mastodon.expert/users/abouillis/remote_follow

Seen on another updated instance here:

https://diaspodon.fr/users/dada/remote_follow

**Comment by QGuLL** [comment]
I've seen the same problem since the upgrade in 1.3.1.
I see this in the logs: 

> Apr 28 11:14:48 pouet bundle[8736]: [70bf4f1e-a6b4-4023-afcf-3d0689e03ce2] ActionView::Template::Error (**Missing partial authorize_follow/_card** with {:locale=>[:fr, :en], :formats=>[:html], :variants=>[], :handle

I think it is linked to a recent rename in the API:
[commit 0618f09939b7afc607bcd983139b91e056debe4d](https://github.com/tootsuite/mastodon/commit/0618f09939b7afc607bcd983139b91e056debe4d)


On our instance, add a symlink in the app/views folder named authorize_follow pointing on authorize_follows seems to have solved the issue.

**Comment by kayleej** [comment]
Hi there,
This should now be fixed by 9736753985b28e0702baf8e41393d66fa3c71a2c, can you try updating to this ref and let us know if this issue is still around for you?

**Comment by nightpool** [comment]
@kayleej isn't the current advice to only use tagged releases? Are these fixes going to get a patch release?

**Comment by kayleej** [comment]
@nightpool Oh, so it is. My bad. Not sure on the patch release, that would be a question for the maintainers.

**Comment by QGuLL** [comment]
@kayleej By the way, does your patch prevents older versions of Mastodon (like 1.2) to call the bad API URL that has here disappeared ?
I'm not telling that this is an issue here, i don't really know, but i feel that it can be a problem.

**Comment by kayleej** [comment]
@QGuLL Not my patch but it just updates the remote follow form to call authorize_follows/card instead of authorize_follow/card.

**Comment by QGuLL** [comment]
Ok, and it seems that foreign instances call the path /remote_follow and not /authorize_follow(s), so this makes sense.

**Comment by cquest** [comment]
https://github.com/tootsuite/mastodon/commit/9736753985b28e0702baf8e41393d66fa3c71a2c fixed the issue on my instance

**Comment by wxcafe** [comment]
Does this warrant a 1.3.2 release? @Gargron

**Comment by mjankowski** [comment]
> Are these fixes going to get a patch release?

Yes, patch release soon, which will include this fix.

**Comment by fwenzel** [comment]
NB: This same error occurs when looking at `admin/reports/<number>`. Will that be fixed with the same release?

**Comment by ykzts** [comment]
@fwenzel Have you seen #2551 and #2567.

**Comment by fwenzel** [comment]
Yes thank you! It is all fixed now. I appreciate your respond!
