### ISSUE TITLE
Raw HTML displayed on some toots in web interface

### ISSUE THREAD

**Issue by wolfteeth** [tootsuite/mastodon#2592]
I saw this on a boost on mastodon.social. It is displaying raw HTML in the individual boost view.

Example: https://mastodon.social/users/Gargron/updates/2174180

![](http://i.imgur.com/8VwIzlx.jpg)

[x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
[ ] This bug happens on a tagged release and not on master (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
see #2574

**Comment by aeonofdiscord** [comment]
I've also just encountered this issue posting from icosahedron; that instance is currently running version 1.2.2.

**Comment by ykzts** [comment]
It is fixed in the master branch.

**Comment by wolfteeth** [comment]
OK, it looks like this is a dup after all. Didn't find it because the title of the original issue isn't very descriptive.

I saw this just a minute ago. Is a new tagged release coming in the next couple days? Looks like .social and other instances are still running with this interface-breaking bug.

**Comment by ykzts** [comment]
https://mastodon.social/@Gargron/4528223

> 1.3.1 was an immediate hotfix for this. Collecting bugs and fixes atm, will get a patch release tomorrow out

**Comment by wolfteeth** [comment]
If v1.3.1 fixes it, does that mean mastodon.social is not running v1.3.1? I saw this issue ~4 hours ago, viewing the individual toot above boosted on mastodon.social.

The fix needs to repair the display of affected toots in all views. I don't think leaving some toots or views broken is acceptable for users.

**Comment by Gargron** [comment]
@wolfteeth Yes, mastodon.social is not updated yet. Last night was very busy with all the feedback to the release, so I completely forgot to run an update and only noticed this now.

**Comment by wolfteeth** [comment]
Fixed by the update to v1.3.1.
