### ISSUE TITLE
Video player play button off center

### ISSUE THREAD

**Issue by mkosler** [tootsuite/mastodon#2601]
The play button is off center for videos. 

![vid_player_bug](https://cloud.githubusercontent.com/assets/1159095/25549048/3d9db98a-2c35-11e7-84ba-35b82ed6c400.PNG)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
@stephenburgess8 could this be related to #2338?
