### ISSUE TITLE
Question: Guidelines for www and non-www

### ISSUE THREAD

**Issue by saggel** [tootsuite/mastodon#2602]
The [guidelines](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md) for setting up a mastodon instance work perfectly for example.com but not for www.example.com

I'm not an nginx expert but I changed my config file and kept getting errors and warnings!
What would be the best implementation for nginx config so that both www and non-www work?

Thank you!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by gled-rs** [comment]
AFAIK you can't have both www.example.com and example.com on the same instance. Only one domain name is supported. If you want to support both, that means an instance deployed for www.example.com and another for the example.com.

You'll need to 301 redirect either www.example.com to example.com or the opposite in nginx in case you just want to setup one.

**Comment by saggel** [comment]
Thank you @gled-rs eventually what I want is to redirect the www to the non-www and keep only the non-www but I need the www to be working cause for now it gives an nasty "your connection is not private" error page. But I can't seem to make it work properly - could you possibly tell me what needs to be edited? Thanks again!

**Comment by gled-rs** [comment]
you probably forgot to declare the http endpoint for www that redirects to https

http-nonwww => redirect to https-nonwww
http-www -> redirect to https-www
https-www -> redirect to https-non-www

check that to get started: https://github.com/eustasy/bubbly

**Comment by saggel** [comment]
Maybe that's not the best/right way to do it, but I added this extra block without altering anything else and it works:

```
server {
  listen 443 ssl;
  server_name www.example.com;
  ssl_protocols TLSv1.2;
  ssl_ciphers EECDH+AESGCM:EECDH+AES;
  ssl_ecdh_curve prime256v1;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;
  ssl_certificate /etc/letsencrypt/live/www.example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/www.example.com/privkey.pem;
  return 301 https://example.com$request_uri;
}
```

**Comment by docjkl** [comment]
@saggel you are correct! i believe nginx best practices suggest alternate server_name other than the "main" name should go in a separate `server{}` block just for redirection, as you've done here.

**Comment by saggel** [comment]
Thank you @docjkl perhaps this can be added in the documentation as a comment.
