### ISSUE TITLE
Support Content Security Policy

### ISSUE THREAD

**Issue by akihikodaki** [tootsuite/mastodon#2604]
[The specification of Content Security Policy](https://www.w3.org/TR/2016/REC-CSP2-20161215/#intro)
describes as the following:

> This document defines Content Security Policy, a mechanism web applications can use to mitigate a broad class of content injection vulnerabilities, such as cross-site scripting (XSS).

I have already made 848c1c5ef69bd1371c257d9f15fb70dc4137ee60 to apply Content Security Policy. It has, however, the following problems not solved yet.

* It doesn't support CDN and S3 since I do not have such an environment.
* We need to set a nonce to `style` element appended by _react-virtualized_, a dependency of `emojione-picker`, used in the Web application. (see https://github.com/tommoor/emojione-picker/issues/68)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by akihikodaki** [comment]
Status update:
* Made a new commit a361b9146522e323d001587fcfef34a4063f9746, including more CSP coverage, better development support, specs, and CDN support.
* The change for emojione-picker was merged and it is already available (#2874)
* rQRCode needs an additional change (https://github.com/kagucho/rqrcode/commit/6702ccd87fda863e0050981da96b04c92f77a6cf).

**Comment by NARKOZ** [comment]
https://github.com/tootsuite/mastodon/blob/master/config/initializers/content_security_policy.rb

**Comment by rugk** [comment]
What's the current status?

**Comment by nolanlawson** [comment]
seems fixed by https://github.com/tootsuite/mastodon/pull/8957
