### ISSUE TITLE
Remote media toot shows URL instead of icon

### ISSUE THREAD

**Issue by wolfteeth** [tootsuite/mastodon#2610]
Minor bug from the timeline views:

- When I (or another user on my local instance) post an image, the toot contains a little icon you can click to open the image in a new tab.
<img width="202" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1330625/25552734/80c76d40-2c5e-11e7-8d86-1edae882b0fa.png">
- When a user on a remote instance posts an image, the media URL appears in the toot instead.
<img width="259" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1330625/25552735/8aaa62cc-2c5e-11e7-9834-0d6d5f975e46.png">

I think either is OK (slightly preferring the icon), but it should be consistent.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Since I can't always detect & replace the link text like that for remote toots, I decided to revert to always text links in #2970
