### ISSUE TITLE
Some public posts from followed remote users missing

### ISSUE THREAD

**Issue by wolfteeth** [tootsuite/mastodon#2613]
I just noticed this tonight while bouncing back and forth between two instances (mastodon.social and my self-run instance).

From my instance, a few public toots from people I follow over on mastodon.social were missing on my local instance, both in my home timeline and in their local (federated) profile. Other public toots from the same users as well as others (on mastodon.social and elsewhere) federated fine and appeared in my home timeline.

I don't know enough about Sidekiq to figure out if these are jobs that died or what I can/should change to revive them.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
Are the missing statuses from a time before you were following them?

If not, are they all in one big block of time, or are they spread out?

**Comment by jbbdude** [comment]
I'm seeing the same. To answer those questions, no (plus others on the instance were) and... mostly bunched together or since a certain time, but there are a few exceptions mostly based on toots or @ mentions.

**Comment by Lana-chan** [comment]
had this happen to me yesterday, there was a ~30 minute window in which all posts from someone i follow just did not come to our instance. after a while they started showing up again, but only the posts after that window are now in our instance. posts from other people in the same instance still came through. the posts were all public.

**Comment by wolfteeth** [comment]
I have been following the person in question since I started my instance, about two weeks. I just checked out their profiles both federated and remote, and it looks like I lost about four of their public toots made in the last couple days. Two of their toots did come through yesterday, but I'm missing some before and some after.

I'm a little worried that we're losing posts for other people now that I noticed this. As a small instance we're pretty dependent on federation.

**Comment by wolfteeth** [comment]
Okay, even weirder: their public toots still aren't coming through - on ANY instance I follow them from. The same toots are missing on all instances. Are unlisted public posts no longer being sent to subscribers with v1.3.x? Many of this person's public toots are unlisted.

**Comment by BrunoSpy** [comment]
I have the same issue, and I think it's a really big issue.
Just compare toots visible from mastodon.social : 
https://mastodon.social/web/accounts/60680
and the toots posted : 
https://metal.odon.space/@BrunoSpy
It's important to take into account that all the missing toots are well received with my quitter.se account : that would mean the issue do not come from the outgoing instance (metal.odon.space in this case) but from the receiving instance (mastodon.social in this example).
I do not know if it's an issue exclusive to mastodon.social.

It seems that only the toots that have received a answer and have been boosted are showing up in mastodon.social, which is really strange.

**Comment by AshKyd** [comment]
I've noticed the same thing. My system ran out of RAM and failed to process a number of jobs, but it doesn't seem to have bounced back after I fixed it.

I've also got a distinct downward trend in my sidekiq jobs which I don't know enough about to comment on. @wolfteeth are you seeing a similar trend?

![](http://i.imgur.com/QPIuh5K.png)

**Comment by wolfteeth** [comment]
@AshKyd - I am not seeing that currently. 

However, I did see it in the past with a different problem. Double-check that your maintenance task cron jobs have been running. It's possible that the rake task to renew subscriptions has not been running, and the follows expired. In my case it was because I had made a typo in my cron script.

**Comment by wolfteeth** [comment]
It looks like I spoke too soon on the sidekiq comment. My cron jobs have been running but the last couple days a bunch of people vanished from my instance's timeline, and are definitely posting on mastodon.social. Is there any way to debug this? Or force the sidekiq jobs to retry?

**Comment by wolfteeth** [comment]
Update: On my break earlier today I ran my maintenance task script manually and my feed revived. The maintenance script has been running daily (it spits some output to a log file), but running it manually seemed to resubscribe me. Didn't help with the toots that had been lost though.

I'm starting to think the PuSH subscriptions aren't kept alive by the maintenance tasks, but instead are resubscribed if they are expired. Which could happen hours later, during which remote toots from those subscriptions are lost. If this is true it seems like a huge defect.

**Comment by wolfteeth** [comment]
Ramped up the frequency of the PuSH refreshes and I'm still losing some followed mastodon.social users' public toots. So that's not it.

Some of my remote instance's public toots aren't getting to followers on mastodon.social either.

**Comment by wolfteeth** [comment]
I hadn't noticed this again with v1.3.3, but I just saw this after inspecting during some downtime for a failed update. I noticed some earlier public toots from someone I follow on Mastodon.social were again missing. They didn't fall into the downtime (though in practice it looks like Mastodon catches up on toots that occurred during downtime).
