### ISSUE TITLE
“Public timeline” link and choosing the content of the third column

### ISSUE THREAD

**Issue by nclm** [tootsuite/mastodon#262]
The “Public timeline” link is weirdly positioned, between a link to the settings area and a link to log-out (both things that have to do with account).

But “Public timeline” just opens content in the multi-purpose third column. So I think the link should be moved somewhere more significant.

There may have to be at one place, possibly in a drop-down at the top of the third column, a list of common things you can get displayed there: your favourites, your profile, the public timeline.

Maybe the default state of the third column is that list. In addition to the Back button, there will be a Clear button to go back to the initial list. Something along these lines.

**Comment by nclm** [comment]
Just adding some initial rough sketches of what I had in mind.

![mastodon-1](https://cloud.githubusercontent.com/assets/923008/20607938/f3149294-b27c-11e6-907d-88b6649c2d83.jpg)
![mastodon-2](https://cloud.githubusercontent.com/assets/923008/20607937/f30ec116-b27c-11e6-8dfe-130fe004cb3f.jpg)

**Comment by triplefox** [comment]
I'll be happy with any change that improves discoverability of public. The existing link just goes unnoticed by many users until public starts talking to them, and that in turn creeps them out.

**Comment by swaldie** [comment]
As linked here, #314 was logged to consider that the public timeline should be a default column.  I'm adding that as a suggestion here.

**Comment by alexgleason** [comment]
I've implemented that functionality on https://animalliberation.social. It works great.

I really like the ideas in the diagram above, though. I think it's a valid point that some people don't like the public timeline. I've seen people write about it before. It makes them feel anxious or something that people they don't know can see their posts? I'm not entirely sure, but maybe we should get more input on someone who feels that way.

**Comment by yiskah** [comment]
This seems to have been implemented? I think this issue could be closed @Gargron
