### ISSUE TITLE
Suggestion: Use of instance name instead of 'Mastodon' on emails

### ISSUE THREAD

**Issue by saggel** [tootsuite/mastodon#2620]
Working on a new translation and noticed that on emails "Mastodon" is used instead of <%= @instance %>. Do you think that it'd be more user-friendly if the instance name was used instead?

So, for instance, to go from this

`We're contacting you to notify you that your password on Mastodon has been changed.
`

to this:

`We're contacting you to notify you that your password on <%= @instance %> has been changed.
`

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
Good idea! Would you be open to making a pull request?

**Comment by saggel** [comment]
Thanks @ashfurrow I tried that yesterday (and was spamming you about it (@ngel) but I think I failed! I'll try that again!

**Comment by ashfurrow** [comment]
Cool, looking forward to it!

**Comment by saggel** [comment]
I see my pull ended up [here](https://github.com/saggel/mastodon/commit/f6210235bf6ba5d80f65f6fd072952e4b06c9353) I'll check what I did wrong!

**Comment by saggel** [comment]
and so did my [Greek translation ](https://github.com/saggel/mastodon/commit/741a5951342553bec30a4186e8cc9ea665666fcf)

**Comment by saggel** [comment]
Most probably didn't do it right this time again, but I think it ended up at the [right place](https://github.com/tootsuite/mastodon/pull/2641) at least
