### ISSUE TITLE
 Not following "Ask to follow" protocols properly

### ISSUE THREAD

**Issue by mitchellurgero** [tootsuite/mastodon#2625]
I did not have this issue as it was reported to me by https://gnusocial.me/blueminda

I am working on finding the exact transaction in my log files, but this is going to take some time. But the user described to me the following issue:

1.  They set their follow settings to "Ask me to follow" So she could avoid bots and such.

2. A Mastodon bot ignored this and was allowed to follow. However - It should not matter as blueminda should have been prompted first to accept the follow before the bot was returned an "OK" to finish the follow transaction.

Notice of the original complaint by the user: https://gnusocial.me/notice/85736

This seems to only happen with Mastodon users trying to follow a GNUsocial account. I am looking into this now, but wanted to make an issue about here so it is documented. Will update more as new data is found.

**Comment by Gargron** [comment]
I don't think GS accounts support "ask to follow" properly when it comes to federation, since Mastodon had to come up with that.

**Comment by mitchellurgero** [comment]
I see - I know GS follows it from one end, but not both ends (GS <-> GS) Either way. Glad you fixed this.
