### ISSUE TITLE
I can't see my own toots in thread

### ISSUE THREAD

**Issue by instajelly** [tootsuite/mastodon#2626]
I'm on Mastodon.social and when I open the thread (by clicking on someone's reply) I can't see my toots, only the others. Sometimes it shows for a moment, but disappears.

![view from outside](https://files.mastodon.social/media_attachments/files/000/372/743/original/af1a2eca76586de1.png)

![view on mastodon.social dashboard](http://i.imgur.com/MxNMek6.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Probably no longer an issue?
