### ISSUE TITLE
Can't search for local toot with their URL

### ISSUE THREAD

**Issue by Aldarone** [tootsuite/mastodon#2629]
When I paste a toot's URL in the search bar I get an error 500 in the web interface.

The log show this : 

```
web_1        | [1b13b310-68d7-477a-95c3-b6ba69ad68e9] method=GET path=/api/v1/search format=html controller=Api::V1::SearchController action=index status=500 error='TypeError: no implicit conversion of nil into String' duration=832.26 view=0.00 db=4.42
web_1        | [1b13b310-68d7-477a-95c3-b6ba69ad68e9]   
web_1        | [1b13b310-68d7-477a-95c3-b6ba69ad68e9] TypeError (no implicit conversion of nil into String):
web_1        | [1b13b310-68d7-477a-95c3-b6ba69ad68e9]   
web_1        | [1b13b310-68d7-477a-95c3-b6ba69ad68e9] app/services/fetch_remote_status_service.rb:55:in `casecmp'
web_1        | [1b13b310-68d7-477a-95c3-b6ba69ad68e9] app/services/fetch_remote_status_service.rb:55:in `confirmed_domain?'
web_1        | [1b13b310-68d7-477a-95c3-b6ba69ad68e9] app/services/fetch_remote_status_service.rb:46:in `extract_author'
web_1        | [1b13b310-68d7-477a-95c3-b6ba69ad68e9] app/services/fetch_remote_status_service.rb:24:in `process_atom'
web_1        | [1b13b310-68d7-477a-95c3-b6ba69ad68e9] app/services/fetch_remote_status_service.rb:13:in `call'
web_1        | [1b13b310-68d7-477a-95c3-b6ba69ad68e9] app/services/fetch_remote_resource_service.rb:15:in `call'
web_1        | [1b13b310-68d7-477a-95c3-b6ba69ad68e9] app/services/search_service.rb:10:in `call'
web_1        | [1b13b310-68d7-477a-95c3-b6ba69ad68e9] app/controllers/api/v1/search_controller.rb:7:in `index'
```

I'm using docker and Mastodon 1.3.2

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Aldarone** [comment]
It seems to happen only with toots from my instance.

This URL imports correctly : https://mastodon.social/@Gargron/4704735
But this one doesn't : https://witches.town/@Alda/1096586

**Comment by Aldarone** [comment]
Other instances can fetch the toot from witches.town with the search bar.

Here is a report of an instance on 1.3.1 that can't fetch their own toot : https://anticapitalist.party/users/corzntin/updates/24900

And here is a report of an instance on 1.3.2 that can fetch them : https://toot.aquilenet.fr/users/Cyphergoat/updates/3302

**Comment by Gargron** [comment]
So the problem is searching for a local toot fails, yes?

**Comment by rhaamo** [comment]
Yes, same issue with local toots in 1.3.2 here

**Comment by Aldarone** [comment]
Yep that's it! It seems to be since 1.3.0 judging by the replies to https://witches.town/@Alda/1099422

**Comment by tcitworld** [comment]
Same issue (only) with local toots here too. Version 1.3.2 too.

**Comment by tcitworld** [comment]
Related logs :
