### ISSUE TITLE
full-text search on toots (feature request)

### ISSUE THREAD

**Issue by dachary** [tootsuite/mastodon#2637]
A full text search on the status of the instance would be very useful. As my the number of toots I posted grows, I have trouble finding my own toots from some time ago ;-)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by rjeffries** [comment]
New to GitHub so this may not be appropriate, but I very much desire free text search. Huge value add. Thx.

**Comment by Gargron** [comment]
Duplicate of #594
