### ISSUE TITLE
Wider context menus 

### ISSUE THREAD

**Issue by ThomasLeister** [tootsuite/mastodon#2643]
As you can see in the screenshot, menu entries are not fully visible in some cases. In German the verb follows the object, so if the username is very long, it's hard tell which menu entry has which functionality. I had one case when only the username was visible in every entry.

![bildschirmfoto von 2017-04-30 11-48-19](https://cloud.githubusercontent.com/assets/4207956/25563354/26e0895e-2d9b-11e7-8c9c-16fbfd80c05f.png)

Maybe we could make the context menu wider and shorten the username after a certain number of characters.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by stephenburgess8** [comment]
@ThomasLeister My code change should improve the experience for long text labels. Anything else for this one?

<img width="335" alt="full_text_new" src="https://cloud.githubusercontent.com/assets/6003351/25586888/71021faa-2e6f-11e7-9406-dc99b876b070.png">
