### ISSUE TITLE
Notification/home tl toggles don't get saved

### ISSUE THREAD

**Issue by codl** [tootsuite/mastodon#2649]
The toggles to disable certain types of notifications or hide boosts and replies from the home tl get reset every time the page is refreshed. My notifications are stuck on a rather minimalist setting with only replies 😬

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
That's strange, it's working okay for me. Can I ask what instance you're on? Do you have any cookie-blocking browser add-ons?

**Comment by codl** [comment]
this happens on every instance I've tried including mastodon.social. I don't have any cookie blocking extensions (I've also tried on chrome for android, same thing) and regardless I believe this is a server side setting since it syncs across browsers

**Comment by codl** [comment]
I looked into this some more and my issue is actually that settings only get saved when closing the settings panel, when I expected that it would save immediately since it immediately changes the behaviour of the column and notificiations

**Comment by codl** [comment]
i suppose i should close this and make a new issue
