### ISSUE TITLE
Feature suggestion - "grouping" or "tagging" users

### ISSUE THREAD

**Issue by Tetizera** [tootsuite/mastodon#2658]
I tried to message Eugen to know what he thinks of it, but I guess he is too busy with development.

Anyhow, I noticed that, even though you COULD make an instance only for friends, or people that you know and trust, that's not very beginner friendly, or even cheap - the brazilian real is undervalued, meaning that even getting a simple DigitalOcean is a bit expensive.

A solution to this would be to be able to create a group of users, similar to how Facebook Group works. I'm not sure if this will bloat Mastodon, but that's the first suggestion.

The second suggestion is "tagging". It could be similar to Reddit's RES - Reddit Enhancement Suite - tagging, where you can simply click next to someone's username, give the tag a name, give it a color if you want, and bang, tagged. A new section, "Tagged Users", could group users with the same tag.

I'm not sure if this is a complicated feature, but I thought it would be neat and help organize the many users in different instances, or even in the same instance that is populated.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
Would this be kind of like twitter lists?

**Comment by Tetizera** [comment]
I'll be honest, I have no idea what is a Twitter list. I use Twitter to check some people, but don't tweet as much as I used to.

This is how tagging works with RES:

1) You click on the little flag, next to a username, and a small box appear, with the details for the user to complete.
![2017-04-30 12_29_16-desabafos](https://cloud.githubusercontent.com/assets/25991951/25565617/ccfc52c8-2da0-11e7-8131-70b778473cfe.png)

2) There's a dashboard, where you can see your tagged users. I don't tag a lot of people, as you can see, but I guess RES group people with the same tag.
![2017-04-30 12_29_58-res dashboard](https://cloud.githubusercontent.com/assets/25991951/25565616/ccfac7be-2da0-11e7-92db-575dd39fd193.png)

**Comment by cphuntington97** [comment]
This would be real nice.

**Comment by leonardoalcantara** [comment]
Yes it would be really nice to have something like Twitter lists. Something that would allow you to have separated timelines for users that are grouped by themes/contexts.

**Comment by remram44** [comment]
"Twitter lists" are coming to Mastodon, see #134. Tagging individual users might be a separate need, though. Is it still something you want if lists happen?

**Comment by Tetizera** [comment]
Nah @remram44 , feel free to close this issue. I only use it to give people on Reddit chessy titles. I think it's not on the scope for Mastodon.

Cheers!

**Comment by Cassolotl** [comment]
@Tetizera As the author of this issue you are probably best placed to close it yourself - a lot of us aren't able to close it!
