### ISSUE TITLE
Help me to DISPLAY Croatian translation 

### ISSUE THREAD

**Issue by diomed** [tootsuite/mastodon#2663]
I can't get front end of Croatian translation to show up. 
Looks like I'm missing something out, but am not sure what. 

I see settings part ok, but nothing in front end is displayed in Croatian,
yet I translated it.

Can someone troubleshoot this to find what I'm missing out?

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
Does the documentation here help at all? https://github.com/tootsuite/documentation/blob/master/Contributing-to-Mastodon/Translating.md

**Comment by diomed** [comment]
ok, this helped. I forgot one file. thanks.
