### ISSUE TITLE
sendmail in docker

### ISSUE THREAD

**Issue by haliphax** [tootsuite/mastodon#2670]
Trying to configure emails with the docker setup. I have a local SMTP server. I get a "relay access denied" error when trying to use SMTP, and sendmail attempts to connect to 127.0.0.1 and gets a "connection refused" error, because I'm guessing there's no mail server living inside the docker container for Sidekiq.

Should I point SMTP at the docker bridge? Would that appear to be local traffic for the SMTP instance, and get around the relay issue? Is there some configuration setting for telling sendmail which IP address to point to?

I suppose some more documentation about handling email within a docker setup would be helpful.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I'm not sure about the docker bridge IP, but "localhost" inside the docker is different to localhost outside of it (networking is separate). So either docker bridge IP, or public IP, something like that.

**Comment by s7b4** [comment]
Hi,
You have to find the gateway of the docker network.

```
docker network ls
docker network inspect <name>
```
IPAM > Config > Gateway is the IP of your host. It can't be local traffic, you have to allow this network in your MTA.

Regards

**Comment by kyzh** [comment]
@haliphax help to get better at documentating email is very welcome there https://github.com/tootsuite/documentation/pull/70

**Comment by haliphax** [comment]
I can't help with documenting it if I didn't know what I was doing wrong in the first place. :P That being said, it seems as though I had it halfway correct -- I was using the IP of the docker bridge for the mastodon default network, but my MTA doesn't consider that to be local traffic (as @Gargron pointed out).

What about sendmail rather than SMTP? It seems to try 127.0.0.1 regardless of my settings. Is that by design?

**Comment by haliphax** [comment]
I got it working by allowing the docker bridge's subnet in my postfix configuration. Still curious about how sendmail would work with a docker setup, but this is no longer an "issue" per se.

**Comment by ashfurrow** [comment]
@haliphax sounds like this has been resolved, anything else we can do to help?

**Comment by haliphax** [comment]
No, though I was pointed toward documentation to help contribute and it turns out that the documentation is unwanted. 😆

**Comment by ashfurrow** [comment]
Okay, well it sounds like this issue has been resolved. Personally, I encourage you to take the knowledge you gained and share it in a blog post. I'm sure it'll be useful for others, even if it's not in the docs repo. Thanks again :bow:
