### ISSUE TITLE
UI is cut off at some resolutions and horizontal scrolling does not work

### ISSUE THREAD

**Issue by csu** [tootsuite/mastodon#2671]
I just upgraded my instance to v1.3.2 and the right side of the UI gets cut off at 1200px wide and horizontal scrolling is disabled. The UI used to always be cut off at these resolutions, but horizontal scrolling used to work; now it doesn't.

It looks like this happens at resolutions down to 1025px, at which point it looks like this:

![](http://i.imgur.com/mEjyszs.png)

My instance is running v1.3.2 without modifications. I also repro'd this bug on https://glitch.social, which is running somewhere closer to `master`, but with other modifications.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
I think the cutting off bug existed before, but the failure to scroll is what's new - is that right?

**Comment by mjankowski** [comment]
Also - are you sure that's in 1.3.2 and not just master? (the change that I suspect did this was not in 1.3.2, but is in master)

**Comment by csu** [comment]
@mjankowski Ah, you're right. I had accidentally precompiled assets while still on `master` (my instance is a Docker deployment so it's sometimes hard to remember to checkout the corresponding git branch for the `:latest` docker image). Closing this as it looks like it's been fixed.
