### ISSUE TITLE
URL with characters other than Latin and Cyrillic in the path produces a broken link

### ISSUE THREAD

**Issue by happycoloredbanana** [tootsuite/mastodon#2674]
Putting a URL with path containing charactes of a RTL language (e.g., like this one: http://www.vanleer.org.il/he/publication/ידיעת-ערבית-בקרב-יהודים-בישראל) creates a link that does not contain the RTL part:

![hebrew-broken](https://cloud.githubusercontent.com/assets/16704632/25574952/994396f6-2e5b-11e7-978f-d3070f194606.png)

[Link to the post (not mine).](https://tooot.im/@Esho/261595)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by happycoloredbanana** [comment]
Looks lke the problem is in [Twitter::Extractor](https://github.com/tootsuite/mastodon/blob/v1.3.2/app/lib/formatter.rb#L57), which supports only Latin and Cyrillic characters in URLs. So not only languages with RTL scripts are affected. E.g., Georgian won't work too.

**Comment by N07070** [comment]
This bug seems to be fixed in the version that is used my mastodon.social, i.e 2.9.2

Could you confirm that this bug has been fixed on your side too ?
