### ISSUE TITLE
www subdomain wrongly hidden from URLs in toots / bio

### ISSUE THREAD

**Issue by MightyPork** [tootsuite/mastodon#2693]
I noticed URLs like `https://www.example.com` are shown without the protocol and the www part (presumably other subdomains are shown normally, but the protocol is still hidden).

The links work fine, but it shows just `example.dom`, which may not work eg. if someone sees it and tries to type it in the url bar.

As a real example, `https://www.ondrovo.com/a/20170316-esp-terminal` is shown as `ondrovo.com/a/20170316-esp-terminal`, and that doesn't work, the www piece is essential.
 
* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
www is usually non-essential, so it is not displayed. It is only hidden visually, if you click the link or even select and copypaste it, the full URL is used. I do not think this is a problem.

**Comment by ashfurrow** [comment]
Thanks for the issue @MightyPork – it sounds like this works as expected, so I'm going to close the issue. If things haven't been clarified to your satisfaction, just let us know.
