### ISSUE TITLE
Feature: Auto load image in links.

### ISSUE THREAD

**Issue by KenOokamiHoro** [tootsuite/mastodon#2701]
May user can view an image link instantly without leave mastodon web interface?

There are some ideas to ensure safety and reduce loads of origin server:
* Allow load remote images from secure origin only.
* Save remote images in local mastodon instance.

* * * *

- [x]  I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
>Save remote images in local mastodon instance.

This already happens!
