### ISSUE TITLE
Instance URL is not correctly substituted in Mastodon's user agent

### ISSUE THREAD

**Issue by staticsafe** [tootsuite/mastodon#2702]
Looking through my nginx log, I found this:
"http.rb/2.2.2 (Mastodon/1.3.2; +http://{}/)"

I believe the "{}" there should actually be the instance URL.

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by staticsafe** [comment]
Some additional context, this is the commit that add the user-agent functionality:
https://github.com/tootsuite/mastodon/commit/23ecc681c4e2b817c9694dbd465b5a7847ca38c3

**Comment by nightpool** [comment]
this is because static initializers run before Rails.application.configure, which is unsurprising. this should be a memoized class method instead

**Comment by nightpool** [comment]
here's the code, for reference
```ruby
module HttpHelper
  USER_AGENT = "#{HTTP::Request::USER_AGENT} (Mastodon/#{Mastodon::Version}; +http://#{Rails.configuration.x.local_domain}/)"

  def http_client(options = {})
    timeout = { write: 10, connect: 10, read: 10 }.merge(options)

    HTTP.headers(user_agent: USER_AGENT)
        .timeout(:per_operation, timeout)
        .follow
  end
end
```
