### ISSUE TITLE
after upgrading 500 error

### ISSUE THREAD

**Issue by Magiccamera** [tootsuite/mastodon#2705]
Just upgraded and now everything broken.

details from web console:

https://<myserver>/api/v1/timelines/public?local=trueFailed to load resource: the server responded with a status of 500 (HTTP/2.0 500)

No clue how to fix.
* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
What version did you upgrade to?

**Comment by Magiccamera** [comment]
The latest master.

**Comment by Magiccamera** [comment]
It seems to have ironed out. Ran some RAILS_ENV’s clearing feeds and refreshing.

I was too drunk last night to deal with it :D 

I do however have a persistent 500 error with one user when attempting to view his statuses. But he can view his posts fine.

Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500) <https://wellness.so/api/v1/accounts/2/statuses>
https://wellness.so/api/v1/accounts/2/statuses <https://wellness.so/api/v1/accounts/2/statuses>

Been like that for couple weeks. Everything else is fine.

Thanks.

**Comment by mjankowski** [comment]
Running latest master while also being drunk is definitely not the recommended approach here.

If you can get a more full log during that error (set log level to debug first), that would be useful!

**Comment by Magiccamera** [comment]
Indeed. Thanks Matt.
