### ISSUE TITLE
rfc2616 compliance : 202 and notice push

### ISSUE THREAD

**Issue by dachary** [tootsuite/mastodon#2706]
On behalf of Maiyannah Bishop

mastodon is returning a 202 HTTP code when a notice is pushed to the hub, this has a couple problems:

- This is done before the notice is created so it breaks the RFC - 202 is for a resource being created and should only be returned if it is, 203 Accepted is probably closer to what is intended but 200 OK is what every other software on the network uses.
- 202 Created is especially a problem because OStatus expects this to only be returned for a Subscription event so this causes earlier versions of the software (and especially the earlier GNU social instances) to think that the end point erroneously sent an ActivityVerb::SUBSCRIBE verb and not an ActivityVerb::NOTICE verb.

Note: for ethical reasons the original reporter does not use github. More information about this issue can be found at https://git.postactiv.com/postActiv/postActiv/issues/116#note_1355 and below

* * * *

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Do you mean this? https://github.com/tootsuite/mastodon/blob/master/app/controllers/api/subscriptions_controller.rb#L16 And 201 vs 200? 202 is only returned when the delivery could not be verified (i.e. it's fake)

**Comment by nightpool** [comment]
Just poured over the ostatus, psh and salmon documentation, but the language I read seems to indicate that we're matching the spec:

> The successful response from the subscriber's callback URL MUST be an HTTP [RFC2616] success (2xx) code

> If the signature does not match, subscribers MUST still return a 2xx success response to acknowledge receipt, but locally ignore the message as invalid

On the Salmon side, there is similar language:
> In each step, there is a specified error code to be used if the server wishes to inform the client about the error; the server is NOT REQUIRED to inform clients of errors and MAY simply return 202 Accepted to complete the request at any time

If Maiyannah could quote the part of the spec she believes us to be violating, then that would help a lot in getting this issue fixed. My understanding was that the original impetus for this ticket being created (large amounts of load on GNU social servers) was mitigated with some fixes we pushed a few weeks ago, but I'm having trouble finding the specific pull request, so I may be misremembering.

**Comment by Gargron** [comment]
I am okay with returning 200 (Success) on successful delivery instead of 201 (Created), as it's not really important as a distinction. 202 (Accepted) for unverified payloads was a good idea in my opinion but it sounds like

>their success response code SHOULD only indicate receipt of the message, not acknowledgment that it was successfully processed by the subscriber.

means that the code should not be different *at all* no matter what so I guess I'm changing both to 200.
