### ISSUE TITLE
Add Media + cancel causes Firefox 52.0 crash

### ISSUE THREAD

**Issue by smithfarm** [tootsuite/mastodon#2707]
I can crash Firefox 52.0 by clicking (in mastodon) on the little camera icon ("Add media") and then clicking on the "Cancel" button in the pop-up window.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by 0x1f415** [comment]
doesn't happen for me in windows 10, firefox 53 (current beta channel), live mastodon.social. might be a firefox bug?

**Comment by Gargron** [comment]
Cannot reproduce, might have been caused by something unrelated.
