### ISSUE TITLE
When starting a reply, you lose the entire edition window

### ISSUE THREAD

**Issue by bortzmeyer** [tootsuite/mastodon#2709]
[Web interface]

When I type a text in the edition window, to prepare a toot, if I click on the Reply button on another toot, my edition window is erased.

This would be a problem even with Twitter and its 140 characters but it's worse with Mastodon and its 500 characters. You may have done searches when preparing your toot and it's annoying to lose it completely.

Possible solutions: a pop-up "you cannot reply to this toot, there is unsent content in the edition window" or a dialog box "do you want to lose the unset toot?"

**Comment by Cassolotl** [comment]
On Telegram, when you type something and then click reply on a previous message, the typed text stays there.

![screen shot 2017-05-02 at 11 54 05](https://cloud.githubusercontent.com/assets/6607512/25615276/34805b18-2f2e-11e7-8f7b-e21ff3e121a1.png)

![screen shot 2017-05-02 at 11 54 36](https://cloud.githubusercontent.com/assets/6607512/25615278/3a1000e2-2f2e-11e7-9365-023647c8ae87.png)

![screen shot 2017-05-02 at 11 54 45](https://cloud.githubusercontent.com/assets/6607512/25615283/422d0446-2f2e-11e7-8618-b0431241f825.png)

If you tap/click the x, the text stays there.

This is my ideal!

**Comment by psydwannabe** [comment]
This issue can make replying to toots on a laptop with a sensitive touchpad really unpleasant, too.
![mastodon bad ux2](https://cloud.githubusercontent.com/assets/6654256/25970909/4a3498ca-364f-11e7-950e-2cc72a6fccfa.gif)

**Comment by Cassolotl** [comment]
The oldest version of this issue, I think, is #878?

**Comment by bortzmeyer** [comment]
@Cassolotl Indeed, you seems right.

**Comment by Cassolotl** [comment]
@bortzmeyer Could this issue be closed as a duplicate?

**Comment by bortzmeyer** [comment]
@Cassolotl Yes, it can.

**Comment by Cassolotl** [comment]
@bortzmeyer As the OP, you are probably best-placed to do this! :)

**Comment by bortzmeyer** [comment]
Closed since it seems a duplicate of  #878 (but still useful as it contains more information)
