### ISSUE TITLE
Notification toggles and home timeline toggles should be saved immediately

### ISSUE THREAD

**Issue by codl** [tootsuite/mastodon#2711]
When turning off or on types of notifications, or when showing or hiding boosts or replies from the home timeline, the UI immediately shows or hides those items, which leads me to expect that the setting has been taken into account and saved for future visits, but in fact the setting is only saved when the settings panel is closed. I think this is confusing and should be changed to save immediately when a setting is toggled.

See also #2649

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
They are saved immediately now.
