### ISSUE TITLE
Indicate stale accounts that are followed

### ISSUE THREAD

**Issue by pacohope** [tootsuite/mastodon#2716]
When looking at one's followers via https://[instance]/web/accounts/1/following, it would be beneficial to see how recently our instance has seen something from a given user. Something like:

| user |  | toots | last active |
| -----|--|-------|---------|
| paco @social.paco.to | [x]  | 147 | 1 hour ago |
| whatever @whatever.mastodon.whatever | [x] | 2342 | 124 days ago |
| somebody @whatever.mastodon.whatever | [x] | 62 | yesterday |
| ... | ... | ... | ...|

The goal is to enable users to see whether they're following people who aren't active any longer. It would be handy to be able to sort the list on the columns. That way one can see who they're following who (a) hasn't tooted much at all, or (b) hasn't tooted in a long time. It would be useful to indicate any sort of connection problems here, too. Like indicating if an instance hasn't been reachable recently.

In my mind it's totally cool if the numbers are from a cache of some kind and potentially a bit stale. It's meant as a coarse heuristic, not some kind of real-time indicator.

* * * *

- [x] I searched and browsed the repo’s other issues to ensure this is not a duplicate, but I still might have missed a duplicate request.

**Comment by Gargron** [comment]
Implemented in the "Follows & followers" page!
