### ISSUE TITLE
Increase React component spec coverage

### ISSUE THREAD

**Issue by stephenburgess8** [tootsuite/mastodon#2722]
The spec coverage on the React UI components is very limited. I propose that we add much more extensive UI spec coverage using enzyme, chai, mocha, and sinon. Things such as "When a user profile link is clicked, the user profile is shown on the page."

This task would be to go through the full set of React UI components, identify where specifications could describe the behavior on the page, and write tests to create much more comprehensive test coverage. I don't think it's necessary to add a spec coverage tool such as istanbul. Considering the large number of contributors to the project, having a much more extensive set of UI behavior specs would help increase confidence in PRs made from the general public.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
Yes, please do this. PRs adding coverage will be warmly embraced.

**Comment by Gargron** [comment]
I suggest waiting until #2617 is merged to avoid lots of merge conflicts.

**Comment by stephenburgess8** [comment]
Thanks @Gargron . I will watch that PR

**Comment by ashfurrow** [comment]
No pressure at all @stephenburgess8 but #2617 has been merged 🌟

**Comment by stephenburgess8** [comment]
Thanks. I couldn't get Mastodon to run locally a couple of days ago when I tried last. Will try again tonight.

**Comment by stephenburgess8** [comment]
I never found time to do this, I apologize. Adding unit tests after components are built is very difficult.
