### ISSUE TITLE
Pubsubhubbub subscription to atom feed subscribes but never gets pushed

### ISSUE THREAD

**Issue by ara4n** [tootsuite/mastodon#2726]
I've tried subscribing to users' atom feeds such as https://mastodon.social/users/Gargron.atom with both websub.rocks and npm's pubsubhubbub library. On both the subscription appears to succeed and generates a plausible looking entry in mastodon's subscriptions table (albeit with blank secret by default, unless one creates the subscription with an optional secret via pubsubhubbub library). However, mastodon never seems to publish updates to the resulting subscription.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on 1.3 [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ara4n** [comment]
@Gargron explained all at https://mastodon.social/users/Gargron/updates/2229010 - it's a feature; need to follow from that domain first before a feed pubsub will be upheld.

**Comment by clacke** [comment]
It's possible to work around, but still means that PuSH support is broken. For private messages, fine, they're not covered by OStatus or by PuSH, but limiting public followers to full OStatus implementations goes against the reasons PuSH (and other component protocols of OStatus) was used in the first place.
