### ISSUE TITLE
Bad input that causes 500 server error

### ISSUE THREAD

**Issue by MightyPork** [tootsuite/mastodon#2728]
Was trying to post random garble for a joke, and got a 500

It looks something like this:

```
Ds7Ttӝ2ZX$YbCW|%:Ep|o*E蕺Me;b*=}"XOUeV$	,ќ%|B;>"[3:iZN4~DsQ
V6#p3L?&Geo<\NEOTE
```

The string is hard to copy-paste, something may be lost in re-encoding, so here is the original, base64-encoded:

```
vLDgRH/80HP51f3Z+Dcem1SedJvp052b/jKtWqKqxc7FWIvTyM4AqSS3WWK9vMH+Q1eXfCU6HBVFDrZwHXyHb7ufz9gqRYGL6JW6yBlNGGXRO/qNGMRiKoazPX0BIljhpE9VAMFlVo2Y1xEkCZagLNGcyCUGE3xCv4s7PiKaWzO0Oo1pvVpOkzS96n5EuY2Bc6iYUQpWgYaOqDaOtCOMcB/LMw6xTKQFCNE/JpRHZW+oPFxORU9U
```

How to repro: Paste this in the console, then click in the tootbox & type & delete one character (so it notices there's some input and you can press TOOT)

```
$('div.autosuggest-textarea > textarea')[0].value 
   = atob("vLDgRH/80HP51f3Z+Dcem1SedJvp052b/jKtWqKqxc7FWIvTyM4AqSS3WWK9vMH+Q1eXfCU6HBVFDrZwHXyHb7ufz9gqRYGL6JW6yBlNGGXRO/qNGMRiKoazPX0BIljhpE9VAMFlVo2Y1xEkCZagLNGcyCUGE3xCv4s7PiKaWzO0Oo1pvVpOkzS96n5EuY2Bc6iYUQpWgYaOqDaOtCOMcB/LMw6xTKQFCNE/JpRHZW+oPFxORU9U")
```

**Comment by mjankowski** [comment]
Can you confirm which release of the software the instance you are having this issue on is?

I'm curious if it's before/after this one - https://github.com/tootsuite/mastodon/pull/1876

Maybe related, Ox has an [invalid_replace](https://github.com/ohler55/ox/blob/master/CHANGELOG.md#230---february-21-2016) option, maybe we should check out.

**Comment by MightyPork** [comment]
It's mastodon.xyz, and reproduced yesterday. I reckon it's running 1.3.2,
or at worst 1.3.1.
maybe you could get the version via some API to verify?

**Comment by ashfurrow** [comment]
The version is available via `/api/v1/instance` endpoint, like `https://mastodon.technology/api/v1/instance`. Can you verify? Thanks!

**Comment by Gargron** [comment]
@ashfurrow Version is probably irrelevant, I think this is still in the code, I haven't had time to investigate, though it probably *is* related to XML dumping

**Comment by MightyPork** [comment]
can't reproduce this on 1.4.7 anymore, I think it's fixed
