### ISSUE TITLE
Subresource Integrity not working with webpack

### ISSUE THREAD

**Issue by Wonderfall** [tootsuite/mastodon#2744]
https://www.npmjs.com/package/webpack-subresource-integrity
We can use `hashFuncNames: ['sha384']`.

**Comment by Gargron** [comment]
Opened rails/webpacker#323

**Comment by Wonderfall** [comment]
I tried but with no success. There's also this one : https://github.com/mikechau/sri-stats-webpack-plugin
But I only managed to get a mapping.json file. I don't know how to make it working with Rails, otherwise I would do it. Hope you'll manage to get something :)
