### ISSUE TITLE
Use the production build of react

### ISSUE THREAD

**Issue by serch037** [tootsuite/mastodon#2763]
Currently the react devtools extension warns that Mastodon is using the development version of react for rendering the UI, which leads to a bigger page size and slower performance.

[React -Use the Production Build](https://facebook.github.io/react/docs/optimizing-performance.html#use-the-production-build)

 * * *

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
This ought to be fixed in master thanks to #2617. You can verify on a site like glitch.social which is running a fairly recent branch; there's no React warning in the console.

**Comment by ashfurrow** [comment]
Sounds like this is resolved – safe to close the issue @serch037 ?
