### ISSUE TITLE
Stop receiving updates from remote user

### ISSUE THREAD

**Issue by asterismo** [tootsuite/mastodon#2765]
A user of my instance noticed that stopped receiving updates from a remote user in mastodon.at yesterday. I went to the admin user query and noticed this line

PuSH subscription expires 	may 02, 2017, 23:29

That time is around the time the user stopped receiving updates. I also noticed i have 4 pages of callback urls listed in the PubSubHubbub section thtat are suppose to expire in the coming days, is this related to this?

I wanted to know if is this a normal behavior of the server and what other info can i provide

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by kayleej** [comment]
AFAIK this should not expire as long as you are running the mastodon:daily rake task via cron or manually daily. Are you getting any errors in your logs?

**Comment by asterismo** [comment]
somehow i did not entered the cron line, my bad, thanks! closing...
