### ISSUE TITLE
Empty public timeline after save user preference

### ISSUE THREAD

**Issue by hinaloe** [tootsuite/mastodon#2766]
The public (local/federated) timeline API will return empty array if I save user preference with no changes.

My preference
<img width="833" alt="2017-05-04 5 26 01" src="https://cloud.githubusercontent.com/assets/5253290/25679973/3a4c3dd4-308a-11e7-81a6-74e851535d31.png">

and when I save with this setting, The user's `allowed_languages` value will be `{""}`.
<img width="195" alt="2017-05-04 5 30 42" src="https://cloud.githubusercontent.com/assets/5253290/25680171/da616754-308a-11e7-8e6b-c0b22fcc1a72.png">

And when I select Japanese:
<img width="230" alt="2017-05-04 5 28 31" src="https://cloud.githubusercontent.com/assets/5253290/25680138/c16bf7dc-308a-11e7-97be-dff3b291c1d3.png">

it may meen **Filter is enabled, but there is no much status**.

It may due to checkbox's hidden stub.
I think the empty value should be filtered.

ref https://github.com/tootsuite/mastodon/pull/2361

thank you.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
Good catch.  I think there are a few things to check here:

- We should make sure that a form with nothing checked is not setting any value
- We should make sure that a user with `""` as an option behaves the same as a null value
- We should make sure that a null value does not filter anything, and just shows all statuses

**Comment by hinaloe** [comment]
Yes!!
