### ISSUE TITLE
Firefox scrolling bars isn't proprely themed

### ISSUE THREAD

**Issue by Technowix** [tootsuite/mastodon#2770]
I think this is only a little CSS problem, but Firefox dosn't seem to follow the css of Mastodon.
![2017-05-03 17_37_53-niu moe](https://cloud.githubusercontent.com/assets/1571367/25683106/fe2af1c6-305a-11e7-85f1-52e95b595ec5.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Firefox scrolling bars cannot be styled.

**Comment by expenses** [comment]
It's a shame that they look like that. Are they any better on something like Chrome?

**Comment by Technowix** [comment]
Yeah, just searched, there is no alternatives than using Javascript-custome-made scrollbars.
That is not an option I think ?

**Comment by stephenburgess8** [comment]
This is a problem that a lot of sites have with Firefox. Firefox will likely not ever support styling scrollbars. If you'd like to have styled scrollbars I'd recommend not using Firefox. https://bugzilla.mozilla.org/show_bug.cgi?id=77790

Opting for a JS solution to make the scrollbars look the same in Firefox would be making everyone adopt an over-powered solution in order to make a stylistic change for a minority of users. I'd opt not to do it for that reason. Even if it were agreed as a good option, I think it would be prioritized fairly low due it being a purely stylistic issue and one that does not effect functionality.

**Comment by Technowix** [comment]
Well, I think if we want Mastodon to attract peoples, we have to not dump them because they use "another" browser who dosn't support that.
I don't think a JS solution would be "Overpowered", and the work seem to be already done https://github.com/malte-wessel/react-custom-scrollbars

And please, don't make a endless "Firefox < <other browsers>". 😒

**Comment by JaredLethal** [comment]
On firefox i use that plugin to skin the scrollbar: https://addons.mozilla.org/en-US/firefox/addon/overlay-scrollbars

there also is the option of hiding them completely, which is pretty efficient EXCEPT on website where you need horizontal scroll ;) https://addons.mozilla.org/en-US/firefox/addon/hidescrollbars/


But in Mastodon's case it looks pretty awesome to have no scrollbars at all :D

**Comment by Technowix** [comment]
@JaredLethal there is area where the scroll part of the mouse isn't working, would be hard for peoples to scroll down without scrollbar :x !

**Comment by JaredLethal** [comment]
@Technowix isn't scroll working anywhere on the column?? i'm pretty sure it is (was?)

but yeah the scrollbad hider is pretty extreme, but the other add-ons was my real advice ;)

**Comment by Kimik0** [comment]
Please do not resort to reimplementing the browser in Javascript that runs in the browser. If someone's scrollbars look less than perfect so be it.

**Comment by yookoala** [comment]
I am a Firefox user and a web developer. I'd prefer performance over look-and-feel.

All the JS scrollbar I've ever came-across either slows down the site or breaks in some edge cases or both.

**Comment by wavebeem** [comment]
This plugin seems to be pretty snappy… It could also optionally only be enabled for Firefox possibly if it's causing performance issues in other browsers?

http://noraesae.github.io/perfect-scrollbar/

**Comment by Gargron** [comment]
Closing because this is more of a Firefox issue.
