### ISSUE TITLE
Install Instance on Ubuntu (Can't finish install)

### ISSUE THREAD

**Issue by Zirconiumirish** [tootsuite/mastodon#2782]
[Hi Everybody, 

I'm looking for help here because I didn't find my answer with my best friend "Google".

I have a VPS with ubuntu installed on it
So I have follow this link to create my own instance of mastodon : http://zoneadmin.fr/forum/threads/installer-une-instance-mastodon-sur-ubuntu-16-04-lts.4478/

so everything is ok till "Yarn install" step and Ive got a message who told me "You have to install cmdtest" but they asked me a password for "Mastodon"  User.

But as specified in the previous step I used this command to create the user "Mastodon" without password : **adduser --disabled-password --disabled-login mastodon**

If someone could help me I'm now blocked in this step.

Thanks for your help

Michael

].

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yookoala** [comment]
Would it be asking you the password to your `ubuntu` user?

**Comment by Zirconiumirish** [comment]
Nope unfortunnately i fix it just by deleting the "--disabled-password" so they asked me to set a new one =) thanks for your time
