### ISSUE TITLE
Mastodon streaming service crash at startup

### ISSUE THREAD

**Issue by ufo56** [tootsuite/mastodon#2785]
git checkout
Your branch is behind 'origin/master' by 275 commits, and can be fast-forwarded.
(use "git pull" to update your local branch)
mastodon@mast:~/live$ git pull
Updating 7f8044d  bea117a

There was some more errors on console but these have been there before

> /live$ yarn install
> yarn install v0.22.0
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> error postcss-smart-import@0.6.12: The engine "node" is incompatible with this m                                                          odule. Expected version ">=6.0.0".
> error Found incompatible module
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this                                                           command.

npm-debug.log

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'start' ]
> 2 info using npm@2.15.11
> 3 info using node@v4.8.2
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info prestart mastodon@
> 6 info start mastodon@
> 7 verbose unsafe-perm in lifecycle true
> 8 info mastodon@ Failed to exec start script
> 9 verbose stack Error: mastodon@ start: `babel-node ./streaming/index.js --presets es2015,stage-2`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at EventEmitter.emit (events.js:172:7)
> 9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at ChildProcess.emit (events.js:172:7)
> 9 verbose stack     at maybeClose (internal/child_process.js:862:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
> 10 verbose pkgid mastodon@
> 11 verbose cwd /home/mastodon/live
> 12 error Linux 3.16.0-4-amd64
> 13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
> 14 error node v4.8.2
> 15 error npm  v2.15.11
> 16 error code ELIFECYCLE
> 17 error mastodon@ start: `babel-node ./streaming/index.js --presets es2015,stage-2`
> 17 error Exit status 1
> 18 error Failed at the mastodon@ start script 'babel-node ./streaming/index.js --presets es2015,stage-2'.
> 18 error This is most likely a problem with the mastodon package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     babel-node ./streaming/index.js --presets es2015,stage-2
> 18 error You can get information on how to open an issue for this project with:
> 18 error     npm bugs mastodon
> 18 error Or if that isn't available, you can get their info via:
> 18 error
> 18 error     npm owner ls mastodon
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]
>

**Comment by ufo56** [comment]
Interesting, after few restarts now it works...

**Comment by mjankowski** [comment]
You need node version > 6
