### ISSUE TITLE
Duplicate index on mentions_status

### ISSUE THREAD

**Issue by tcitworld** [tootsuite/mastodon#2787]
PgHero reports me a duplicate index : 

`mentions_status_id_index (status_id)`
is covered by
`index_mentions_on_status_id (status_id)`

Is it safe for me to remove one of them, and which one ?

Seems like https://github.com/tootsuite/mastodon/commit/4df26b262184ebc75344369f236e2a37e3722513 is related, but there weren't any migration to remove it.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
The  rails migration naming conventions changed at some point, and I suspect the schema.rb wound up with both of them as a side effect of that.

You can safely delete the one which was removed from schema.rb if you have the other one in place.

**Comment by tcitworld** [comment]
Thanks, will do.

**Comment by TwistedLucidity** [comment]
I am seeing this as well, unfortunately I don't understand how to resolve it. Which one do I delete and how do I delete it?

**Comment by tcitworld** [comment]
`DROP INDEX mentions_status_id_index` did the trick for me.

**Comment by TwistedLucidity** [comment]
Thanks, just wanted to be 100% sure.
