### ISSUE TITLE
Create a timeline that just covers general Mastodon UX development and news

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [tootsuite/mastodon#2798]
Title says most. A timeline for most users to follow.

We're glad the Dev' has other interests, a personal life, and a following. But some would just like to follow things of interest to most users, and feed the timeline into other places, such as i.e. Matrix rooms.

**Comment by Gargron** [comment]
Now it's [Mastodon@mastodon.social](https://mastodon.social/@Mastodon)

**Comment by rjeffries** [comment]
Will try this out. Like the idea!
