### ISSUE TITLE
Ask Matrix Dev's to Create a Timeline just for general Mastodon-Matrix Bridgin UX development and news

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [tootsuite/mastodon#2800]
A timeline for most users to follow that is not about general Matrix stuff, not like [@matrix@mastodon.matrix.org](https://mastodon.matrix.org/@matrix) .  That's too much for those who just want to follow about what's going forward for Mastodon-Matrix bridging.  

Some want to feed the timeline into other places, such as Matrix rooms that are about Mastodon, for general users.

**Comment by ashfurrow** [comment]
Thanks for opening the issue @MilkManzJourDaddy – is this something specific to your instance? Or something general to every instance?

**Comment by Gargron** [comment]
Honestly this isn't an issue that belongs into this repository at all...
