### ISSUE TITLE
Retooted item disappears from timeline

### ISSUE THREAD

**Issue by allvoxman** [tootsuite/mastodon#2814]
This happens when the timeline starts to get more loaded (50-60 items). Pressing SHIFT+retoot has the same result.

<details>
<summary>gif</summary>

![gif](https://cloud.githubusercontent.com/assets/407360/25750873/679a7db2-31b3-11e7-942f-fe6cb51e94d1.gif)
</details>
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
I think this is intentional behavior, because the toot moves to the top of
your timeline. It's pretty confusing though so this should probably be
changed.

**Comment by allvoxman** [comment]
Nah, it doesn't happen if the timeline is not that long (but long enough not to see the top). To me this looks like a bug.

**Comment by wilsonbiggs** [comment]
This happens to me as well.

**Comment by ashfurrow** [comment]
Thanks for opening the issue @allvoxman – just FYI I've modified the issue body to put the GIF behind a disclosure arrow.

**Comment by Cassolotl** [comment]
I'm fairly sure this was fixed - now, when I boost things, they don't disappear-to-the-top?
