### ISSUE TITLE
[BUG] user i do not follow in timeline without explanation

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#2817]
![2017-05-05_11-35-22](https://cloud.githubusercontent.com/assets/23704040/25752722/19a7c0be-3187-11e7-8367-4b4a517e176f.png)
![2017-05-05_11-35-17](https://cloud.githubusercontent.com/assets/23704040/25752726/1b4b1420-3187-11e7-9c4d-0541c575fd86.png)

a stranger who i do not follow just popped into my timeline for some reason 

bug occurs on 4d22d03fabc5f249fd2a93037916b980e4d3f99b

**Comment by Cassolotl** [comment]
Could be #2264 or #1601, which seem to be about similar bugs?

Triplefox says "accidental boost" - did they accidentally boost tobikame, and then unboost, somehow leaving the toot in your timeline with no indication of why? That would be #770.

**Comment by Gargron** [comment]
The explanation is right in the screenshot

I'm sorry I know this is confusing behaviour and I have described in detail why it's complicated in #147

**Comment by rixx** [comment]
@Gargron – any comment on if you're planning on changing this to a more user-friendly behaviour? IMO a toot that was not boosted (yes, boosted, then unboosted) by any of the people I'm following should not show up in my timeline. We're getting about one or two reports of this behaviour per week, so it seems to be confusing for all involved.

**Comment by Merovius** [comment]
I'd argue that if it's too computationally expensive to undo a boosting, it just shouldn't be possible (i.e. remove the UI action alltogether and continue to attach the name to it in any case). Hiding the name that did it but not the toot itself seems like a very bad option to me.

After all, the intended effect of a boost is to make it more widely seen. If that's not undone as good as possible, it also seems disingenuous to pretend it is.
