### ISSUE TITLE
Extract user_mailer translations to devise.*.yml

### ISSUE THREAD

**Issue by yookoala** [tootsuite/mastodon#2819]
The email notifications contents now reside in `app/views/user_mailer/*.erb`. This create difficulty in extract all translations to external translation service (as #1241 suggested).

Propose to properly extract all email text from erb to yml.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Solved
