### ISSUE TITLE
User preference to set all media to hidden by default

### ISSUE THREAD

**Issue by tlhall** [tootsuite/mastodon#2828]
[Feature suggestion: Add an option for users to set all images to default to hidden].

As with the "Auto-play animated GIFs" option, add an option to default all media to hidden, so it displays as "Media hidden (or whatever); Click to view" on the users's interface and the user can view the media when clicked, re-hide it when clicked again (like it does currently). 
This would act like auto-clicking the little eye on any media that shows up that's not hidden.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by bugQ** [comment]
An important use-case for this feature is that users with low bandwidth or data caps are able to benefit from reduced data usage.  Currently, media marked as sensitive doesn't load until clicked on, right?

**Comment by nolanlawson** [comment]
Hmmm how would users who have enabled this feature know that the author of a toot intended for the media to be marked as "sensitive"? We might need to make some subtle distinction between "hidden but not sensitive" vs "hidden and sensitive."

**Comment by bugQ** [comment]
We currently already have a distinction between media marked as NSFW (it says "Sensitive media") and media which the user has elected not to see (by clicking the eye symbol; it then says "Media hidden").

**Comment by hakaba-hitoyo** [comment]
This is one of the most desired feature, especially for Japan's fedeverse community. In Japan, now we face a moral panic or moral war. Some users upload _hentai_ pictures (sexual _manga_ paintings) without NSFW flags, some other users claim that such immoral users must be banned or punished. My timelines are full of these kind of flames everyday.

This feature provides a reasonable solution which recovers our peaceful fedeverse. Commits or pull requests are highly desired. Thank you for reading.

**Comment by tlhall** [comment]
I found a ![Chrome extension](https://chrome.google.com/webstore/detail/block-image/pehaalcefcjfccdpbckoablngfkfgfgj?utm_source=chrome-app-launcher-info-dialog) that sort of does this. Maybe this is available for other browsers ?
