### ISSUE TITLE
A gif avatar is in my timeline, unpaused

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#2846]
Taknamay (on Quitter) https://quitter.se/taknamay just reposted something from this Guizzy https://social.guizzyordi.info/guizzy (on Quitter), and Guizzy's avatar on my timeline is an animated gif that is moving.

Edit for clarity: Mastodon has a setting to autopause animated gif avatars, and this appears to not work for this particular person's avatar. I'm on cybre.space, which autopauses animated avatars.

* * * *

- [Yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by S-YOU** [comment]
https://superuser.com/questions/39895/pausing-a-gif-animation-in-google-chrome

**Comment by ashfurrow** [comment]
Sounds likely @patf – maybe it was a gif that got uploaded with a jpeg file extension? That might confuse things enough to have it fail to transcode with a static, non-animated version.

**Comment by S-YOU** [comment]
@ashfurrow, gif just works, that is a feature. So many profile have that. 
Why does it have to make it static?

**Comment by ashfurrow** [comment]
@S-YOU gif avatars are still until you move your mouse over them, if I recall. So when uploading a gif as an avatar, we create a static version of it too.

**Comment by S-YOU** [comment]
> gif avatars are still until you move your mouse over them.
I don't observe that behavior, where can I check that?
I have my own profile with gif, which does not need to mouse over too, and I see a lot like that.

**Comment by patf** [comment]
The default behaviour for animated GIF avatars is to show them paused in user and status lists. They auto-play when a user views an individual profile, unless the auto-play GIF setting is disabled, in which case they're hover-to-play even on a profile.

**Comment by ashfurrow** [comment]
This has been a feature since [1.1.2](https://github.com/tootsuite/mastodon/releases/tag/v1.1.2) – can you check the version of your instance? Maybe you've discovered a bug in that code?

**Comment by Cassolotl** [comment]
@ashfurrow 1.3.3. :)

**Comment by ashfurrow** [comment]
Gotcha, thanks for following up. That's very strange, sounds like a bug, maybe to do with pulling in GIFs from other non-Mastodon federated users?

**Comment by Gargron** [comment]
Have we sorted this one out?

**Comment by Cassolotl** [comment]
I've not seen an animated gif avatar in my timeline since then, so I'll close this. If I see another I'll come back and comment again.
