### ISSUE TITLE
Force re-fetch remote profile picture / header

### ISSUE THREAD

**Issue by Technowix** [tootsuite/mastodon#2848]
Hello, I'm in a problem, I was forced to silence & un-cache media for a moment on my instance, removing all avatar/header/pics.
but now I un-silenced everybody since the problem is gone.
The problem is that profile picture / header isn't here, and isn't fetched until they change it since nobody unfollowed them while I was silencing thoses.
If someone can help me force fetch thoses, thanks (or even, re-fetch everyone we federate with... )

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by clworld** [comment]
FYI: I did create rake task for re-download deleted account images. It works for me. I don't know it works for environment using S3. https://pastebin.com/Bi9AdnEm
On-demand re-download of Account images may possible by modifying avatar_remote_url and header_remote_url. (Mastodon re-downloads account images when remote_url is changed.)
I don't know how can I perform on-demand re-download for Media Attachments.
Re-download of all deleted Media Attachments can performed like I does for account images but It may be a huge task...
