### ISSUE TITLE
DreamHost SHARED: Is it possible to run Mastodon without breaking the bank? (OR TOS?)

### ISSUE THREAD

**Issue by MGageMorgan** [tootsuite/mastodon#2853]
I have a shared hosting plan and my own domain at DreamHost. I would like to know if it is possible to run this and not get kicked out. I've been wanting a personal one of these for the longest time, but it's written in Ruby and I don't know how DH handles the processes required to run Mastodon on shared servers. I don't have enough money to run with a VPS, otherwise I'd just satisfy my hunger that way.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by maop** [comment]
That's a question for Dreamhost, ask them directly :)

My assumption is that they will say not. I was a DH's customer like 10y ago and they had policies against scripts running all the time... and just a quick search at their KB: https://help.dreamhost.com/hc/en-us/articles/216540488-Why-did-procwatch-kill-processes-on-my-Shared-server- seems like is the same nowdays.

You can get a nice 2G RAM, 10G SSD VPS at OVH for 4.5 USD/mo: https://www.ovh.com/ca/en/vps/vps-ssd.xml

If you are in Europe have a look at arubacloud, starting with a 1G vps for 1€ : https://www.arubacloud.com/vps/virtual-private-server-range.aspx

GL & HF

**Comment by S-YOU** [comment]
They will suggest you to try their VPS box, there is existing question about that on their forum, I just dont remember link.

**Comment by djchen** [comment]
I don't believe Dreamhost Shared Hosting supports Redis, which is necessary for running Mastodon.
You can definitely run a Mastodon instance easily for $5 a month on a VPS using Docker.

**Comment by smaffulli** [comment]
DreamHost's DreamCompute would be a better choice to run a modern system like Mastodon. More than the resources needed, it's the packages required to run Mastodon are not available on shared hosting.

**Comment by Gargron** [comment]
Feel free to discuss such matter on our [Discourse](https://discourse.joinmastodon.org)! However, I can't do anything for this issue, so closing.
