### ISSUE TITLE
Zero-width characters (among others) aren't sanitized, allowing toots to have up to 250 empty lines

### ISSUE THREAD

**Issue by wilsonbiggs** [tootsuite/mastodon#2858]
Hey all. I was just testing out some stuff and noticed that zero-width spaces, when combined with newlines, could be used to create extremely long, blank toots. This probably isn't intended behavior, and many other websites sanitize these characters to keep this from happening (although many only sanitize the zero-width space, and not other whitespace characters like word joiners). Here's a screenshot of what I'm talking about:

![screenshot_156](https://cloud.githubusercontent.com/assets/3406010/25775983/f5d335b6-327f-11e7-86a2-2f9f012c6d6d.png)

While this isn't a high-priority issue, I figured it'd be good to bring it to your attention.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Same as #2811 - questionable need to check the infinite ways in which content could be gibberish, when the disruptive behaviour would be punished socially.
