### ISSUE TITLE
S3_CLOUDFRONT_HOST env variable name and comment are inaccurate

### ISSUE THREAD

**Issue by csu** [tootsuite/mastodon#2859]
The `S3_CLOUDFRONT_HOST` env variable is used to set an alias for S3, but the name and comment for the variable are not very accurate:

```
# Optional alias for S3 if you want to use Cloudfront or Cloudflare in front
S3_CLOUDFRONT_HOST=
```

S3 can be aliased to another domain or subdomain without the use of Cloudfront or Cloudflare. S3 can be aliased with a DNS CNAME which can be set with any DNS provider. So both the name and comment for this env variable don't quite reflect its actual purpose.

When I was trying to set a custom subdomain for my instance's uploads served from S3, it was hard to figure out this was the env variable I had to use. The name and comment did not make it obvious this was the relevant env variable, so I spent a lot of time messing with `S3_HOSTNAME` instead.

A better name and comment might be (of course, even if the name is changed, Mastodon should remain backwards compatible with the old var name):

```
# Optional alias for uploads (e.g. to serve files from S3 on a custom domain, possibly using Cloudfront or Cloudflare)
S3_ALIAS_HOST=
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by fwenzel** [comment]
Another question: Is this meant to be a full URL prefix (`https://assets.myinstance.biz/blah/`) or, in fact, a hostname (`assets.myinstance.biz`)? The latter is a lot more restrictive.

**Comment by supernovae** [comment]
> Another question: Is this meant to be a full URL prefix (`https://assets.myinstance.biz/blah/`) or, in fact, a hostname (`assets.myinstance.biz`)? The latter is a lot more restrictive.

Were you able to use a URL?  I'd like to use a URL so i can use cloudflare and get the partner level object sharing but it means i need the bucket name in the URL i do believe to work seamlessly without having to use local nginx rewrites to do the same.
