### ISSUE TITLE
Minor nitpick, branch 1.3-stable diverged

### ISSUE THREAD

**Issue by fudanchii** [tootsuite/mastodon#2868]
I just realized that branch 1.3-stable has diverged with master. in particular there are few commits that has different hash between master and 1.3-stable / v1.3.3 and this commit is not even included in master: a0f7453c6

Was wondering probably master should be versioned as 1.3-master or master-\<shorthash\> instead to avoid confusion.

Thanks

![](http://f4.fudanchii.net/shx/screenshots/chrome/2017/05/chrome_2017-05-07_09-14-38.png)  

![](http://f4.fudanchii.net/shx/screenshots/chrome/2017/05/chrome_2017-05-07_09-15-03.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
This is because 1.3-stable is a backport from master.

**Comment by fudanchii** [comment]
Ah, understood. Thanks
