### ISSUE TITLE
Answer aren't shown on home time line

### ISSUE THREAD

**Issue by Shnoulle** [tootsuite/mastodon#2876]
Didn't think it's related to https://github.com/tootsuite/mastodon/issues/2613 because i think it's the desired behaviour currently.

I follow an account on an external server, the answer are on the mastodon server (i see it if i click on the user), but didn't shown on 'Home timeline'.

This notice : https://ostatus.shnoulle.net/notice/651342 was an answer to this toot : https://mastodon.nuzgo.net/users/Armony/updates/4145 . 

The 'repeat' are shown on Home time line, but not the answer, the answer are only shown if i click on user on the local account (`web/accounts/211`). Desired behaviour or not ? Maybe an user settings available because if i follow someone i want to see interaction (answer) with other.

![capture du 2017-05-07 12-06-54](https://cloud.githubusercontent.com/assets/1439428/25779779/6d36f0d6-331e-11e7-9a6b-b9771154ff6a.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] If you're a user, don't worry about this

**Comment by Gargron** [comment]
Is the viewer following the person you replied to? If not, this is intended behaviour - replies to strangers are filtered out.

**Comment by Shnoulle** [comment]
Hi, 

1. This user `https://m.sl-network.fr/@shnoulle` (SM) follow this user : `https://ostatus.shnoulle.net/shnoulle` (SG) (and only him)
2. G follow `https://mastodon.nuzgo.net/@Armony` (A)
3. A make a pouet A-1
4. SG repeat the pouet A-1 and answer to it SM-A-1
5. SM see the A-1 (repeated) but not SM-A-1

It's easy to control for me because SG follow only SM, and instance is not big. But i see this behaviour a lot of time. And thinking it's the desired behaviour.

**Comment by Gargron** [comment]
SG follows A, but SM (the viewer) does not. So reply to A is not shown. This is intended, indeed.

**Comment by Shnoulle** [comment]
Then _ if i follow someone i want to see interaction (answer) with other_ it's not OK for you ? Maybe as a feature ?

**Comment by Shnoulle** [comment]
@Gargron sorry, but there are something really silly here. If another user Repeat : the notice is shown.

Let's explain in detail

Me connected to A and B , not with C

- C make C1
- A answer C1A1
=> I don't see C1A1
- B repeat (boost) C1A1
=> I see C1A1

Then

> SG follows A, but SM (the viewer) does not. So reply to A is not shown. This is intended, indeed.

is false . You must do the same for boost if you want to be clean :)
