### ISSUE TITLE
Rightmost column doesn't have fixed height on Safari 10.1 os x 10.12.4

### ISSUE THREAD

**Issue by kirabug** [tootsuite/mastodon#2899]
Hallo!

When using Mastodon 1.3? on https://toot.cafe/ the rightmost column scrolls past the height of the window, even though the first 3 columns do not. See attached screenshot. 

When using Mastodon 1.2.2 on https://wandering.shop all 3 columns have fixed height.

Possible regression issue?
<img width="1440" alt="screen shot 2017-05-07 at 5 59 58 pm" src="https://cloud.githubusercontent.com/assets/28521009/25788527/d02f7d62-3377-11e7-898d-40141482999e.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by stephenburgess8** [comment]
@akihikodaki This seems to have been caused by #2271 specifically applying `height: 100%;` to `.mastodon-column-container`. I tested removing this style in Firefox, Chrome, and Safari and the column scrolling and height seems to be behaving as expected. Is there some reason that this style is added that's not clear from the discussion in #2271? Any reason not to remove this style, as removing it seems to fix this bug and not cause any other bug obvious immediately?

**Comment by akihikodaki** [comment]
@stephenburgess8 Open a timeline with the single column layout in Firefox (make the window small), and you will see two scroll bars on the right side.

**Comment by ykzts** [comment]
@kirabug Can you solve this problem in #3062?

**Comment by kirabug** [comment]
I am only a reporter of issues, not a fixer. Don't have my own instance. Thanks for taking care of it!

**Comment by ttrace** [comment]
following change solved this problem.
and sorry, I' working on 1.3.3 and can't same asset for new master repository.

```
diff --git a/app/assets/stylesheets/containers.scss b/app/assets/stylesheets/containers.scss
index 6f339f9..1ba0fc5 100644
--- a/app/assets/stylesheets/containers.scss
+++ b/app/assets/stylesheets/containers.scss
@@ -11,7 +11,7 @@
 
 .mastodon-column-container {
   display: flex;
-  height: 100%;
+  height: 100vh;
   width: 100%;
```

**Comment by Gargron** [comment]
I think this shouldn't be an issue in master anymore.

**Comment by ttrace** [comment]
@Gargron , I agree not to continue this issue on current master which has changed DOM structure.

@kirabug here is workaround to solve this problem.
bookmarklet with following script and run.  Safari (and latest Chromium) will show correct height.
```
javascript:$(".mastodon-column-container").css("height","100vh");
```
