### ISSUE TITLE
List view keeps adding more DOM nodes the more you scroll

### ISSUE THREAD

**Issue by nolanlawson** [tootsuite/mastodon#2900]
As you scroll down the main list of toots, every time you reach the bottom it adds more DOM nodes, on the order of around ~500 it seems. (For comparison, Gmail has ~3000 total elements on first load on desktop.)

This quickly exhausts the available memory. You really notice it on mobile devices, where scrolling to the bottom only 5 or 6 times may cause the webapp to become sluggish or crash.

![screenshot 2017-05-07 20 03 59](https://cloud.githubusercontent.com/assets/283842/25788767/5c544dc6-3360-11e7-8d04-6ee1aec3e79d.png)

Probably the best solution would be a virtual list, i.e. a list that only renders those elements that are currently visible and then swaps new ones in and out as necessary. It seems the [InfiniteLoader component](https://github.com/bvaughn/react-virtualized/blob/master/docs/creatingAnInfiniteLoadingList.md) in `react-virtualized` would be a good candidate, especially since it's already being used by `emojione-picker` and so it's one less dependency.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Concerns:

* Dynamic row height
* Connecting clickable ColumnHeader to the underlying List for scrollToTop animations

**Comment by nolanlawson** [comment]
It will also break Ctrl-F but I feel that's a worthy tradeoff.

-----
Nolan Lawson
http://nolanlawson.com
https://github.com/nolanlawson

**Comment by nolanlawson** [comment]
Another option is to simply clear out each list item's content when it's no longer in view, using a debounced scroll listener. I.e. you wait for the element to be invisible, then you replace it with an empty DOM node with the exact same width/height. It's not as good as a virtual list, but it reduces the total number of DOM nodes at least. Unfortunately this will probably mess up React's virtual DOM diffing so I'm not sure exactly how to achieve it.

**Comment by fwenzel** [comment]
As for breaking DOM diffing, I suppose when it's out of view, one could flip a boolean on the list item component state and have it rerender itself as an empty box (and vice versa when it returns). This way React would be fully aware of what's happening.

**Comment by nolanlawson** [comment]
Yeah a buddy of mine who knows React better than I do suggested [a solution like this](https://gist.github.com/nolanlawson/29a00d7055f8e74d231cef42cb87a18c). I think this could be done performantly, as long as it doesn't read-write from the DOM in an inefficient way to get the measured `width`/`height` (i.e. layout thrashing).

**Comment by nolanlawson** [comment]
Fixed by https://github.com/tootsuite/mastodon/pull/3191! :tada:
