### ISSUE TITLE
Edit accounts and verify e-mails in admin UI

### ISSUE THREAD

**Issue by f-wong** [tootsuite/mastodon#2920]
When a new user creates an account with the wrong e-mail address, we need a way to edit the e-mail address from the admin interface and a way to re-send the verification e-mail to the new address OR provide the ability to manually confirm the user account and then let the user correct their e-mail address from their side of the user interface.

We assume that in both cases the system will check for duplicate e-mail addresses before applying the edited changes or verifying the account.

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by SansPseudoFix** [comment]
👍 for this issue. In the mean time, I face to this problem: how can I fix it? I don't see any solution in [documentation](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/List-of-Rake-tasks.md). Is there a way?

**Comment by Gargron** [comment]
Fixed in #7074
