### ISSUE TITLE
Toots from people i follow are missing

### ISSUE THREAD

**Issue by imshyuan** [tootsuite/mastodon#2925]
Hi, any reasons why toots from the people i follow no longer appearing on my home timeline as well as when visiting their profile in my Mastodon instance? I can view all the toots by poster A say within last 24 hours publicly and also in Mastodon.cloud instance but the last toot i can see from within my Mastodon instance is the toot posted two days ago. This happens before 1.3.3, even after refreshing push the toots are still missing. This happens in both of my instances. I'm a novice so i dont really know where to look into. Now my instances are on 1.3.3. Any guidance/help would be much appreciated. Thank you!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by shorty88** [comment]
Check the actual internet connection to the machine. This happened to me on my instance. Even when I did an update and refreshed push like you did it wasn't updating. I found out that somehow I had forgotten a number on my subnet mask when setting up a static IP address for my server oops 😆. For some reason it let me do downloads to update mastodon and other programs and I could also run speed test on the server so I though the internet was fine but it wasn't letting my instance update. It took troubleshooting almost everything to realize what I had done.

**Comment by imshyuan** [comment]
I was thinking could it be a problem with my cronjob. @shorty88 by any chance you can share what's in your crontab?

**Comment by imshyuan** [comment]
It was indeed cron issue. The issue seems to be fixed now!

**Comment by shorty88** [comment]
Just saw this glad you got it fixed. What was the fix to the problem if you don't mind sharing for future reference.
