### ISSUE TITLE
respond_to :json does not work

### ISSUE THREAD

**Issue by akihikodaki** [tootsuite/mastodon#2932]
Controllers for APIs such as `Api::V1::StatusesController` have `respond_to :json`, but it does not seem to make any difference. In the case of `Api::V1::StatusesController`, `curl 'http://localhost:3000/api/v1/statuses/1' -H 'Accept: application/xml'` works as well as `curl 'http://localhost:3000/api/v1/statuses/1' -H 'Accept: application/json'` does.

In my opinion, it is fine to remove `respond_to :json` anyway. But I wonder there is an intension with it.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
>But I wonder there is an intension with it.

I will admit that I am not 100% sure what Rails does with that directive, but *at least* it gives the developers an idea of what to expect from the controller ("this is a JSON API")

**Comment by Gargron** [comment]
>curl 'http://localhost:3000/api/v1/statuses/1' -H 'Accept: application/xml' works as well as curl 'http://localhost:3000/api/v1/statuses/1' -H 'Accept: application/json' does.

Wait, I think without this directive, the XML one would try to render XML, fail to find the template, and return a 409 or some such error. This way it always returns JSON. Right?

**Comment by akihikodaki** [comment]
@Gargron No, it returns XML.
```console
$ curl 'https://o.kagucho.net/api/v1/statuses/1' -H 'Accept: application/xml' 
<?xml version="1.0" encoding="UTF-8"?>
<status>
  <id type="integer">1</id>
  <created-at type="dateTime">2017-04-26T15:41:19Z</created-at>
  <in-reply-to-id nil="true"/>
  <in-reply-to-account-id nil="true"/>
  <sensitive type="boolean">false</sensitive>
  <spoiler-text></spoiler-text>
  <visibility>public</visibility>
  <language>ru</language>
  <application>
    <name>Web</name>
    <website nil="true"/>
  </application>
  <account>
    <id type="integer">1</id>
    <username>173210</username>
    <acct>173210</acct>
    <display-name></display-name>
    <locked type="boolean">false</locked>
    <created-at type="dateTime">2017-04-26T14:43:10Z</created-at>
    <followers-count type="integer">87</followers-count>
    <following-count type="integer">128</following-count>
    <statuses-count type="integer">1602</statuses-count>
    <note>&lt;p&gt;&amp;lt;p&amp;gt;ABSOLUTELY NO WARRANTY CC-BY-SA 4.0&amp;lt;/p&amp;gt;&lt;/p&gt;</note>
    <url>https://o.kagucho.net/@173210</url>
    <avatar>https://o.kagucho.net/system/accounts/avatars/000/000/001/original/923be66a73bc1924.png?1495885390</avatar>
    <avatar-static>https://o.kagucho.net/system/accounts/avatars/000/000/001/original/923be66a73bc1924.png?1495885390</avatar-static>
    <header>https://o.kagucho.net/headers/original/missing.png</header>
    <header-static>https://o.kagucho.net/headers/original/missing.png</header-static>
  </account>
  <media-attachments type="array"/>
  <mentions type="array"/>
  <tags type="array"/>
  <uri>tag:o.kagucho.net,2017-04-26:objectId=1:objectType=Status</uri>
  <content>&lt;p&gt;hello, world&lt;/p&gt;</content>
  <url>https://o.kagucho.net/@173210/1</url>
  <reblogs-count type="integer">1</reblogs-count>
  <favourites-count type="integer">0</favourites-count>
  <reblog nil="true"/>
</status>
```
