### ISSUE TITLE
RTL: emoji box hidden when screen laid out right to left

### ISSUE THREAD

**Issue by yair** [tootsuite/mastodon#2940]
For example, mastodon.social right now with the Farsi locale (Firefox on Win7):

![covered_emoji_box](https://cloud.githubusercontent.com/assets/513922/25851614/1d0c7e98-34cf-11e7-9e27-b2d8baf6a1d5.png)

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yair** [comment]
Also the arrow in the upper left corner, near where it says 'Back' now actually points forward, because the directions have flipped. Not sure if it's worth opening another issue for that.

**Comment by seefood** [comment]
Tried master today on my dev env and this seems to be fixed.

**Comment by Gargron** [comment]
Nice!
