### ISSUE TITLE
Blank page with Javascript errors attempting to login - happens at 'getting started' url

### ISSUE THREAD

**Issue by pulsecoder** [tootsuite/mastodon#2941]
Hi all. Forgive newbie/user post.

This bug just started happening. Mastodon was working perfectly for me as of a week or so ago.

Now I get a blank page on the getting_started screen on several (3) instances, including social.mastodon.com.au.

Web Developer addon console in Firefox shows 4 errors:

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create vendor-4e62c70d855e9bcf7b20.js:1:1870785

TypeError: value.keywords.includes is not a function vendor-4e62c70d855e9bcf7b20.js:1:1059968

HTTP "Content-Type" of "audio/mpeg" is not supported. Load of media resource https://social.mastodon.com.au/sounds/boop.mp3 failed. getting-started

TypeError: node is null

---

I am afraid I am a just a user and don't know what version they are running. I can ask them if you need.

I looked in the github issues here and there seemed to be some Closed issues with the same or similar result (not exactly the same) but this is currently happening to me on 3 different instances.
It may just be they all happen to be running the same pull.

If you want me to try on other sites for testing please specify which sites.

Using:
Firefox 41.0.1 on Linux. Addons disabled produces no change.

* * * *

- [* ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Firefox 41.0.1 is very old. Please use Firefox 53.0.2.

**Comment by pulsecoder** [comment]
Thanks very much for getting back, but the Firefox version cannot be the problem as Mastodon was working perfectly on the same version a short while back. Also it is obviously not an acceptable fault case if a version difference on a browser can break Javascript interpretation. You see my point.
(Incidentally I don't wish to upgrade my Firefox for various reasons to do with decisions Mozilla have made that I no longer agree with. But I acknowledge that once I have found workarounds for these then I will most likely have to upgrade to ease other issues in the future.)
Thanks again.

**Comment by ykzts** [comment]
Mastodon only supports the latest two versions of web browsers (see [`.babelrc`](https://github.com/tootsuite/mastodon/blob/682507bc3c954239c11934faddcd3ba2934a4d4d/.babelrc#L9)). Even if it is working, it is a coincidence.

It takes a lot of effort to deal with old web browsers. I would like you to be convinced.

**Comment by pulsecoder** [comment]
I'm sorry but respectfully I must disagree.
There should be nothing in Javascript functionality that should break so easily. I have written a lot of JS in my time. If Mastodon is using some kind of new binary JS API functionality that I am unaware of ... that's a different matter (and also highly browser-make dependant, and a 'slippery slope'). But I do not believe that Mastodon is doing any such thing?
Also forcing browser upgrades on users brings new problems upon them, some of which they will not be willing to tolerate. Please note that the 'opposition' system ('the bird') works fine on intermediate-age browsers (FF 41 is older, certainly, but it is not extremely old).
I'm afraid that from my point of view, at this stage this looks a lot to me like a Regression Error. I did note somebody else in another github issue thread being surprised by regressions during automated tests of recent builds.
Thank you again, but I will wait and see.

**Comment by ykzts** [comment]
@pulsecoder Perhaps because stopped the compile to ES 5 from ES 2015. Older Firefox does not support ES 2015. This was done to avoid increasing file size unnecessarily.

**Comment by pulsecoder** [comment]
Ooooh dear. That could well be it.
A great shame if so.
Thank you again for getting back.

**Comment by Gargron** [comment]
cc @nolanlawson - maybe the .babelrc change was too drastic

**Comment by ykzts** [comment]
ah... I found the cause of this problem. Emojione Picker uses ES 7 syntax with https://github.com/tommoor/emojione-picker/commit/be6ce2e76805f1cfcf9d608b07006e7d19cb15b2 .

In Mastodon It looks like there was a problem with https://github.com/tootsuite/mastodon/commit/5b6c2a1e726fbed80ec63265aba861b17c99d40c.

**Comment by ykzts** [comment]
@Gargron There are several solutions:

1. PR to Emojione Picker
2. Downgrade Emojione Picker
3. Use polyfill for `Array.prototype.includes`

**Comment by nolanlawson** [comment]
Yeah there is a Babel plugin/setting that can do all of this for us. I'll
take a look tonight.

-----
Nolan Lawson
http://nolanlawson.com
https://github.com/nolanlawson

**Comment by ykzts** [comment]
@nolanlawson I have not checked, but I think using the useBuiltIns will solve it.

**Comment by nolanlawson** [comment]
BTW that is not syntax but rather just the missing polyfill. The polyfill itself will be like 5 lines of code, no need to downgrade emojione-picker.

**Comment by nolanlawson** [comment]
Also yes Firefox 41 is very old. @gargron I believe we should clarify which browsers we support; last two versions plus IE11 and iOS 9 seem reasonable to me based on market share.
