### ISSUE TITLE
option to dismiss/hide all further warnings such as this one

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#2952]
preferably per-warning, obviously
![image](https://cloud.githubusercontent.com/assets/23704040/25868518/f31d9508-34ca-11e7-9b02-309fd806887f.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by hoodiek** [comment]
also the colors on this one are worrisome/hard to read

**Comment by Gargron** [comment]
We fixed the colors, at least!
