### ISSUE TITLE
Ressources 404'ing after an upgrade to the latest master (switch to webpack?)

### ISSUE THREAD

**Issue by Komic** [tootsuite/mastodon#2953]
Hi,
so, this is probably pretty dumb. I've just updated my personal instance to the latest master (`682507b`), bundle/yarn install, rake tasks, the whole shebang, but ended up just breaking everything, ressources are not served anymore ([example](https://from.komic.eu/about)). I can confirm Mastodon's web server is the one throwing 404s (not my proxy) thanks to the headers. I can also confirm the ressources do exist in, for example, the packs/ folder. Did something change recently, isn't puma supposed to be serving this stuff? Already tried a git clean after reading [this](https://github.com/tootsuite/mastodon/issues/2911), but as you can see, without success. I'm kind of running out of ideas. 😕

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Puma is not supposed to serve static files, nginx does that. Are you serving from the public directory?

**Comment by Komic** [comment]
So the whole public/ folder is safe to serve directly? Hey, I did say it was probably dumb.~
Something changed though, the very same proxy config did use to work just fine. Thanks, I'll tweak a few things. 👍

**Comment by Bashy** [comment]
Same problem here using docker.
Here the output from git pull && docker-compose build
https://pastebin.com/vPQEqSm9
Here the result of webpack binary  ( docker-compose run --rm -e NODE_ENV=production web ./bin/webpack > result_webpack )
https://pastebin.com/gwxdeYLL

**Comment by Komic** [comment]
Alright, since Apache doesn't have a `try_files` directive this is slightly more of a pita, but I'm back up. Thanks @Gargron.

**Comment by Bashy** [comment]
When running on docker, how should we treat the problem ?

**Comment by pvols1979** [comment]
I am running on docker as well and none of the images are loading.  All giving 404 errors.  Komic, what was the fix?

**Comment by Komic** [comment]
My setup is a bit atypical since I run Apache, but I simply excluded the static content (public/) from being proxied from Mastodon (a bunch of P`roxyPass path/ !` directives). Not sure how that'd work with ngnix, not even sure you're encountering the same bug. :/

**Comment by Gargron** [comment]
Even with Docker you are supposed to let nginx serve the public directory.

**Comment by Bashy** [comment]
Ok thanks,
@pvols1979 solved by editing nginx file, be sure `root` nginx directive point to your `public` directory
