### ISSUE TITLE
ENOSPC error

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#2956]
Not sure what happened, but with one of today's commit's, I now get this error when trying to build via docker. It states no space left on device, which is false?

[3/4] Linking dependencies...
warning "react-storybook-addon-intl@0.1.0" has incorrect peer dependency "@kadira/storybook@^1.35.1".
warning "chai-enzyme@0.6.1" has unmet peer dependency "react-addons-test-utils@^0.14.0 || ^15.0.0-0".
error Could not write file "/mastodon/yarn-error.log": "ENOSPC: no space left on device, open '/mastodon/yarn-error.log'"
error An unexpected error occurred: "ENOSPC: no space left on device, mkdir '/mastodon/node_modules/pg-pool/node_modules/object-assign'".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'streaming' failed to build: The command '/bin/sh -c bundle install --deployment --without test development  && yarn --ignore-optional --pure-lockfile' returned a non-zero code: 137

**Comment by malicioustoker** [comment]
What that said, it hangs there and never finishes

**Comment by d0p1s4m4** [comment]
your drive seems to lack of free space :/

**Comment by malicioustoker** [comment]
There's over 100Gbs free though...

**Comment by yookoala** [comment]
ENOSPC means it run out of space in the drive you put the `node_modules` folder in.

If you don't mind, can you share your `df -h` results?

**Comment by malicioustoker** [comment]
Thanks 😊 

Filesystem      Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk0s2   232Gi  152Gi   80Gi    66% 5195929 4289771350    0%   /
devfs          186Ki  186Ki    0Bi   100%     644          0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%       0          0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0          0  100%   /home
/dev/disk1s1   239Mi  219Mi   20Mi    92%     409 4294966870    0%   /Volumes/Docker


I'm not sure what changed, but it finally went through and built it, but now all the assets fail to load. I've tried building again and ran than assets:precompile. They both finish without any issues but the assets still do not load on the website

**Comment by malicioustoker** [comment]
Downgrading to 1.3.3 fixes the assets, but once I pull from master again, assets stop working

**Comment by S-YOU** [comment]
239Mi 219Mi 20Mi, you only have 20M left in your docker. I guess it is OSX one, which has limited spaces, I guess. You might need to find a .qcow2 file and expand spaces more manually.

**Comment by malicioustoker** [comment]
Thanks, that should do it for that issue :)
