### ISSUE TITLE
Assets fail to load

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#2973]
Hello, having an issue with the master (go figure right 🤷🏼‍♂️). As of yesterday, (not sure what commit caused it), the website no longer displays the assets. There are no errors while building, or running assets:precompile, but no images load up on the website. Downgrading to 1.3.3 fixes the issue and loads the assets, but updating to master breaks the assets again. Running using Docker on MacOS.

**Comment by jbalsip** [comment]
I encountered this same problem, and while I haven't had an opportunity to get to a root cause it looks to me like there is an effort to change how assets are hosted.  Bringing up the dev tools in a browser I can see the page attempt to download from localhost:8080, but I have no clue what needs to be done to get that working.  Some updated documentation on how this impacts setup and configuration would be most helpful I think.

**Comment by jbalsip** [comment]
Did a little digging and found this PR which sheds a little light on the subject.  Certainly a change with some impact.

https://github.com/tootsuite/mastodon/pull/2617

**Comment by malicioustoker** [comment]
The problem I have with that theory is that was posted 10+ days ago. I update to EVERY new commit, and this issue didn't start until yesterday 09 May

**Comment by jbalsip** [comment]
Ah yes, you're using Docker.  Well there was #2949 which may have affect that, but I can't say as I know little of Docker.  I'd also still recommend getting more information out of the browser as far as what status codes it is getting for the assets and what Url it is trying to access them through.  Could be helpful for troubleshooting.

**Comment by Gargron** [comment]
Probably something related to #2901. Make sure nginx is actually serving your public directory?

**Comment by malicioustoker** [comment]
I don't think #2901 is the issue, as when I was running that 3 days ago, it was working fine. There are no issues when it builds, so I can't really post an error log :-/ #2949 would make sense just because that's around the timeframe when it stopped loading the assets

**Comment by Gargron** [comment]
Do you properly set the environment when building assets? RAILS_ENV=production?

**Comment by malicioustoker** [comment]
I'm using Docker, isn't the only file I'm suppose to change is .env.production? I've been running Mastodon fine for about 3 weeks now :-/ it was only after a commit from May 9th that broke assets :-/.

**Comment by Gargron** [comment]
The only commit that could've touched anything related to assets on May 9th was #2901 (ef226a6f223ad3bdf662efb0ed75694b3f0bfb56). Perhaps you can try reverting to before that, see if that fixes your problem, then we can know for sure?

**Comment by malicioustoker** [comment]
Can do! Give me a few moments and I'll let you know 😊

**Comment by ykzts** [comment]
@malicioustoker What happens if you add `RAILS_SERVE_STATIC_FILES=true` to `.env.production`?

**Comment by malicioustoker** [comment]
@ykzts just add it to the top? Or any place specific?

**Comment by ykzts** [comment]
@malicioustoker There is no problem anywhere. The order is not evaluated. Please add it in the place you like.

**Comment by Gargron** [comment]
The interesting thing is that the nginx config I provided would serve static assets from the public directory. But I am now hearing for the 3rd time that people relied on Puma/Rails serving static assets. I am surprised.

**Comment by malicioustoker** [comment]
@ykzts your solution worked!!! Thank you so very much!!!!!!

**Comment by Bashy** [comment]
Seems to be related to #2953 
@Gargron The thing is it used to work in the past _as is_, then people did not look to it until it changed.
