### ISSUE TITLE
Federation Cache Issue

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#2983]
Hello, I had to wipe all my containers and all within Docker and lost all my instance information. I know I cant get it back, and I'm fine with that. My issue is that after starting the instance back up the other instances (such as mastodon.social) still show the old toots that no longer exist from before the server was wiped. Also, if a user from lets say Mastodon.Social, or any other instance follows the account on my instance - they can ONLY see posts that have others tagged in them, and not any new posts. Is there anyway to have search within other instances pull the new instance information and not the old, wiped server information?

**Comment by ashfurrow** [comment]
Sorry to hear about that – the question about whether you can update the remote instances to fetch only the post-wipe info is, I think, no. At least not at the moment. It's an interesting problem and I'm not sure about a solution.

**Comment by malicioustoker** [comment]
After ~24 hours, the issue seems to fix itself!
