### ISSUE TITLE
Option to Add Piwik integration

### ISSUE THREAD

**Issue by sys0dm1n** [tootsuite/mastodon#2990]
[Hello,

It would be nice to be able to add the tracking ID of piwik in the .env.production file without modifying the code. And/or in the admin dashboard the ability to check the pageviews.

Thank you.].

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by gled-rs** [comment]
https://github.com/tootsuite/mastodon/pull/2553
