### ISSUE TITLE
Failed update

### ISSUE THREAD

**Issue by pvols1979** [tootsuite/mastodon#2995]
Tried to update this morning and I am getting an error message about a bad tar gz file, npm-3.10.10.tgz
___
OK: 358 MiB in 119 packages
npm ERR! Linux 4.8.0-22-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "npm@3"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /tmp/npm-15-d3f5587b/registry.npmjs.org/npm/-/npm-3.10.10.tgz
npm ERR! Expected: 5b1d577e4c8869d6c8603bc89e9cd1637303e46e
npm ERR! Actual:   38de872c96888d450d30244c81a47b06da8871ca
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-3.10.10.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /mastodon/npm-debug.log
ERROR: Service 'streaming' failed to build: The command '/bin/sh -c echo "@edge https://nl.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories  && BUILD_DEPS="     postgresql-dev     libxml2-dev     libxslt-dev     python     build-base"  && apk -U upgrade && apk add     $BUILD_DEPS     nodejs@edge     nodejs-npm@edge     libpq     libxml2     libxslt     ffmpeg     file     imagemagick@edge     ca-certificates  && npm install -g npm@3 && npm install -g yarn  && bundle install --deployment --without test development  && yarn --ignore-optional  && yarn cache clean  && npm -g cache clean  && update-ca-certificates  && apk del $BUILD_DEPS  && rm -rf /tmp/* /var/cache/apk/*' returned a non-zero code: 1
mastodon@larry:~/mastodon$
___

* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
Can you try the latest tagged release of 1.3.3 and see if the error still happens?

**Comment by pvols1979** [comment]
I am running the dockerized version. Can you tell me how to do this?  I do
a pull for that tagged version, correct?  I have tried to do that but I am
getting an error about something missing in that version.

**Comment by ashfurrow** [comment]
It should work for the docker version, do a `git fetch` then a `git checkout v1.3.3` and that should do it. More info is available in the docs: https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md#updating

**Comment by pvols1979** [comment]
I followed the instructions you referenced and I am getting errors. First streaming service failed to build. Then I am getting some inflate errors decompressing libpython2.7.so.1.0

**Comment by Gargron** [comment]
>shasum check failed

Either network failure or MITM attack.

If you comment out the `build` out of the docker-compose.yml directives, leaving only the `image` in each service, you'll fetch the precompiled images from Docker Hub. However, you won't be able to customize those.
