### ISSUE TITLE
Mastodon prod is using React development version

### ISSUE THREAD

**Issue by zacanger** [tootsuite/mastodon#3000]
I did search, but if I missed an already open issue about this, sorry, please close this one!

I noticed this because the new version of the React Devtools extension yells at you if the site you're on is using the dev build. I think a solution would be adding `DefinePlugin` to [this config](https://github.com/tootsuite/mastodon/blob/master/config/webpack/production.js#L10). I can PR for this if wanted.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
duplicated with #2763. And, fixed in master.

**Comment by zacanger** [comment]
Oh right on, thanks! I'll close this, then.
