### ISSUE TITLE
Lack of description

### ISSUE THREAD

**Issue by dasisyouyu** [tootsuite/mastodon#3009]
[Issue text goes here].
Please link the installation guide to readme.md.

https://github.com/tootsuite/documentation/tree/master/Running-Mastodon

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
https://github.com/tootsuite/mastodon/blob/v1.3.3/README.md#deployment

As far as I see, there seems to be a link.

**Comment by dasisyouyu** [comment]
I'm really sorry.
