### ISSUE TITLE
Timeline errors

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#3024]
Back at it again with another strange bug. Started today, not sure of the cause, and nothing strange is showing up in the logs.

While using a browser (tested on multiple devices and browsers), randomly, the Home, Local, and Federated timeline will fail to load, and an "Oops! An unexpected error as occurred." Message pops up in the browser. Also randomly, one timeline will start working, but not the other. So the Home Timeline will randomly work while the Federatied Timeline breaks, and vise versa.

Here's where things get strange - the notifications tab still works and streams in new notifications. Also, there is no issue what so ever when using an app to display the timelines. All timelines work as they soon in app, but not in browsers.

**Comment by malicioustoker** [comment]
![img_0143](https://cloud.githubusercontent.com/assets/1431774/26012953/350448c6-370b-11e7-8c4d-b6df77b139c7.PNG)
![img_0144](https://cloud.githubusercontent.com/assets/1431774/26012954/351c5038-370b-11e7-9fd8-93274eb0bcc8.PNG)
![img_0145](https://cloud.githubusercontent.com/assets/1431774/26012955/351f3582-370b-11e7-97a9-bf6c323b5510.PNG)

**Comment by malicioustoker** [comment]
Oh yeah, and this..
![img_0146](https://cloud.githubusercontent.com/assets/1431774/26013360/dce7b78e-370c-11e7-859a-ad076b4a522f.PNG)
![img_0147](https://cloud.githubusercontent.com/assets/1431774/26013361/dcf814ee-370c-11e7-8382-411ab21988f0.PNG)

**Comment by Gargron** [comment]
You might have caught a time when your instance was under heavy load or had other deployment-related issues? This is not reoccuring behaviour... In any case - hard to work with this without any logs.

"Oops, unexpected error occured" means you can open the console (inspector) and see JavaScript errors. However, if the errors mean "HTTP error from API response", it means it's a server-side error, and the JavaScript logs are useless. Most likely, it was a temporary issue on your instance.
