### ISSUE TITLE
[API] Follow / Unfollow by name

### ISSUE THREAD

**Issue by Ulrar** [tootsuite/mastodon#3026]
Hi,

I've been looking at the API, and I'm not sure how to follow / unfollow someone.
```
POST /api/v1/accounts/:id/follow
POST /api/v1/accounts/:id/unfollow
```
Those methods seem to take an Int, I checked. How do I "convert" a full name user@instance.tld into an Int ? I assume it needs to somehow be registered on the local instance.

I imagine
```
POST /api/v1/follows
```
might be the answer, but besides the weird name what would be the equivalent for unfollow then ?
Or is the only way to unfollow to get the local account, extract it's ID, get followers from that and iterate through those, getting each accounts, to find the correct full name to unfollow ?
That seems really inconvenient, isn't there a better way I'm missing ?

Thanks

**Comment by unarist** [comment]
> How do I "convert" a full name user@instance.tld into an Int ?

You can use [`/api/v1/accounts/search`](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#searching-for-accounts) which accepts `user@instance.tld` format.

It also does lookup remotely when necessary, so it allows you to follow an account which is not yet in the local database.

**Comment by Ulrar** [comment]
Ah, yeah, I feel a bit silly for not having thought of that on my own.
Well, thanks !
