### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by jbond23** [tootsuite/mastodon#3034]
I would like to see keyboard shortcuts in the desktop web UI. the most obvious would be J K for forwards back in the main home timeline. This would scroll so the next previous to moved to the top of the display.

up,down to scroll the Home timeline
J K to scroll the home timeline to next previous toot.

There may be others.

https://mastodon.cloud/@jbond/8124959

**Comment by ykzts** [comment]
duplicated with #2102?

**Comment by jbond23** [comment]
Damn. I did a search as well but didn't spot it.
