### ISSUE TITLE
Babel / uws Streaming Crash

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#3039]
I believe ever since the Babel commit, streaming has no longer worked for me.. Heres the crash log..

streaming_1  |
web_1        | Creating scope :cache_ids. Overwriting existing method Notification.cache_ids.
sidekiq_1    | 2017-05-13T16:02:44.723Z 1 TID-gop1o00u0 INFO: Booting Sidekiq 5.0.0 with redis options {:url=>"redis://redis:6379/0"}
streaming_1  | > mastodon@ start /mastodon
web_1        | [1] Puma starting in cluster mode...
sidekiq_1    | Creating scope :cache_ids. Overwriting existing method Notification.cache_ids.
streaming_1  | > babel-node ./streaming/index.js --presets es2015,stage-2
web_1        | [1] * Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
streaming_1  |
web_1        | [1] * Min threads: 5, max threads: 5
streaming_1  | /mastodon/node_modules/uws/uws.js:38
streaming_1  |             throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
db_1         | LOG:  database system was shut down at 2017-05-13 15:58:48 UTC
web_1        | [1] * Environment: production
streaming_1  |             ^
db_1         | LOG:  MultiXact member wraparound protections are now enabled
web_1        | [1] * Process workers: 2
streaming_1  |
db_1         | LOG:  database system is ready to accept connections
streaming_1  | Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
web_1        | [1] * Preloading application
db_1         | LOG:  autovacuum launcher started
streaming_1  |     at e (/mastodon/node_modules/uws/uws.js:38:19)
web_1        | [1] * Listening on tcp://0.0.0.0:3000
web_1        | [1] Use Ctrl-C to stop
streaming_1  |     at Object.<anonymous> (/mastodon/node_modules/uws/uws.js:42:3)
web_1        | [1] - Worker 0 (pid: 17) booted, phase: 0
streaming_1  |     at Module._compile (module.js:570:32)
web_1        | [1] - Worker 1 (pid: 26) booted, phase: 0
streaming_1  |     at Module._extensions..js (module.js:579:10

streaming_1  |     at require (internal/module.js:20:19)
streaming_1  |
streaming_1  | npm ERR! Linux 4.9.27-moby
streaming_1  | npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
streaming_1  | npm ERR! node v6.10.1
streaming_1  | npm ERR! npm  v3.10.10
streaming_1  | npm ERR! code ELIFECYCLE
streaming_1  | npm ERR! mastodon@ start: `babel-node ./streaming/index.js --presets es2015,stage-2`
streaming_1  | npm ERR! Exit status 1
streaming_1  | npm ERR!
streaming_1  | npm ERR! Failed at the mastodon@ start script 'babel-node ./streaming/index.js --presets es2015,stage-2'.
streaming_1  | npm ERR! Make sure you have the latest version of node.js and npm installed.
streaming_1  | npm ERR! If you do, this is most likely a problem with the mastodon package,
streaming_1  | npm ERR! not with npm itself.
streaming_1  | npm ERR! Tell the author that this fails on your system:
streaming_1  | npm ERR!     babel-node ./streaming/index.js --presets es2015,stage-2
streaming_1  | npm ERR! You can get information on how to open an issue for this project with:
streaming_1  | npm ERR!     npm bugs mastodon
streaming_1  | npm ERR! Or if that isn't available, you can get their info via:
streaming_1  | npm ERR!     npm owner ls mastodon
streaming_1  | npm ERR! There is likely additional logging output above.
streaming_1  |
streaming_1  | npm ERR! Please include the following file with any support request:
streaming_1  | npm ERR!     /mastodon/npm-debug.log
streaming_1  |
streaming_1  | > mastodon@ start /mastodon
streaming_1  | > babel-node ./streaming/index.js --presets es2015,stage-2
streaming_1  |
streaming_1  | /mastodon/node_modules/uws/uws.js:38
streaming_1  |             throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
streaming_1  |             ^
streaming_1  |
streaming_1  | Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
streaming_1  |     at e (/mastodon/node_modules/uws/uws.js:38:19)
streaming_1  |     at Object.<anonymous> (/mastodon/node_modules/uws/uws.js:42:3)
streaming_1  |     at Module._compile (module.js:570:32)
streaming_1  |     at Module._extensions..js (module.js:579:10)
streaming_1  |     at Object.require.extensions.(anonymous function) [as .js] (/mastodon/node_modules/babel-register/lib/node.js:152:7)
streaming_1  |     at Module.load (module.js:487:32)
streaming_1  |     at tryModuleLoad (module.js:446:12)
streaming_1  |     at Function.Module._load (module.js:438:3)
streaming_1  |     at Module.require (module.js:497:17)
streaming_1  |     at require (internal/module.js:20:19)
streaming_1  |

**Comment by tjnet** [comment]
`npm rebuild uws ` might be solution.

Please refer to the following link.
[Streaming service not starting on Node 8? Due to uws. · Issue #3768 · tootsuite/mastodon](https://github.com/tootsuite/mastodon/issues/3768)
