### ISSUE TITLE
Instance doesn't send any Toots, but it sends mentions

### ISSUE THREAD

**Issue by Bloufit** [tootsuite/mastodon#3044]
**Hi there !**
I have a big problem : **My Mastodon instance doesn't send any Toots to other instances.**
But ! If I mention someone on another instance, or if I follow him, he receive it.

Mentions, and all others notifications works, but not toots with no mention.

The daily tasks seems to work good, and also the system. I have no error in "journalctl -xe".
There is no error in "syslog" if I enable "debug" mode in "config/environments/production.rb".
In the "PubSubHubbub" pannel on Administration, there are some "X" in the "Last delivery" column.
There are a lot of errors in "Sidekiq", but nothing special.

I use Ubuntu 16.04 with Apache (And without Docker).

Have you any idea ? (Is that a PubSubHubbub problem ?)
**Thanks and have a good evening !**

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Bloufit** [comment]
I think that this is just a bug, because it is solving by it self...
But one question : Is there no problem to put uppercase in the "LOCAL_DOMAIN" parameter (To make it clean on front page title) ?

_(And sorry for weird english, I try to do my best)_

**Comment by Gargron** [comment]
>Is there no problem to put uppercase in the "LOCAL_DOMAIN" parameter (To make it clean on front page title) ?

Please use lowercase. But don't change it once it's set once. It is used for *technical* purposes, the display is secondary. Go to /admin/settings/edit to change the "site title", but do not play around with LOCAL_DOMAIN or you will run into issues with other instances.
