### ISSUE TITLE
Filter tabs on profiles

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#3048]
![image](https://cloud.githubusercontent.com/assets/23704040/26029606/086e0e9e-3807-11e7-90c1-7a4dff62b292.png)

there was a disccusion in the discord on how to fit all the different filtering options that users will want into their bios, and the above is my example on how to fix it. this also adds a good use case: users who dont want to see toots when looking at a bio are not exposed to them immediately, they scroll down to see them. this is, in my opinion, always the superior option, and it was noted in the discord that a user preference for viewing any of the filter options immediately after selecting be shown; a bar at the top of the list of toots with "make default view filter? [yes][no][don't ask again]", and a drop down of options in the settings menus, for if users click don't ask me again, or select the wrong one and want to change it

**Comment by hoodiek** [comment]
OH AND WHILE IM AT IT 160 characters is way too fucking short lets make it five hundred.

just.

in my opinion. it's a toot length, it's not an absurd amount, and it fits the theme of mastodon overall by matching toot length, and being more space than twitter

**Comment by latrani** [comment]
(Hey while we're on the topic of bio content/formatting, can we also make it display newlines please. :) Especially if it's 500 characters!)

The rest of this is good too, I want to work on giving this some UX love, also possibly working in things like tabs for common post filters (Gargron made a good case for having 'media' be easily discoverable, for the sake of artists, etc)

**Comment by Gargron** [comment]
Oh hey we implemented this, coming in 1.6.0
