### ISSUE TITLE
Cannot upload the same photo again if I cancel it

### ISSUE THREAD

**Issue by Zeether** [tootsuite/mastodon#305]
I've noticed an issue where if I upload a photo and cancel the upload with the "X", it won't let me upload the same photo again unless I either refresh the page or pick another photo, cancel it, then go back to the photo I wanted to upload before.

**Comment by paralithode** [comment]
oh, yeah I had the same issue!

**Comment by hoodiek** [comment]
confirmed bug still exists.

**Comment by Gargron** [comment]
I'm not sure how to fix it but I can explain why it happens. Clicking on add attachment forwards the click to a hidden file input element, which brings up the file selection dialog. Choosing a file sets the value of the file input to that file. There is an `onChange` handler attached to that file input, i.e. when the file value changes, it triggers an upload. If you select the same file twice, the value doesn't change, therefore no upload.

**Comment by hoodiek** [comment]
couldn't the X out of adding an attachment set the file value to "" and then add a tiny exception checker to abort upload if the file string is empty?

i don't mean to be rude and tell you what to do, that's just the first things that popped into my mind

feel free to ignore if you've already tried it

**Comment by Gargron** [comment]
The file input is unlike other inputs so setting the value like that does not work, at least if I'm to believe StackOverflow answers on this. The "proper" answers involve either having a form element around it or deleting the element and creating it anew, which is in conflict with the declarative rendering approach of React.js

**Comment by hoodiek** [comment]
understood. thank you for explaining.

**Comment by marrus-sh** [comment]
Testing on Firefox and Chrome, the value is *usually* read-only for file inputs (throws a `SecurityError`) but both allow you to set the value to `null` (or `""`). Tested using the following data: URI—

```
data:text/html,<input type="file" id="inpt"></input>
```

—and typing `inpt.value=null` into the console. This is suggested by the HTML5 spec (emphasis mine):

> Throws an `InvalidStateError` exception if it is set to any value **other than the empty string** when the control is a file upload control.
> …
> On setting, **if the new value is the empty string, it must empty the list of selected files**; otherwise, it must throw an `InvalidStateError` exception. [[HTML5]](https://www.w3.org/TR/html5/forms.html#common-input-element-apis)

So I think hoodie's suggestion *should* work. (I don't know if this is a new feature; it is odd that StackOverflow wouldn't pick up on something like this.)
