### ISSUE TITLE
libcld3: undefined symbol: _ZTIN6google8protobuf11MessageLiteE

### ISSUE THREAD

**Issue by nolanlawson** [tootsuite/mastodon#3057]
Related: https://github.com/akihikodaki/cld3-ruby/issues/3

This error popped up recently (post-1.3.3) and occurs when running `bundle exec rake secret` or apparently any `bundle` command:

    libcld3.so: undefined symbol: _ZTIN6google8protobuf11MessageLiteE

<details>
<summary>click for full stacktrace</summary>
<pre>
LoadError: Could not open library '/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/cld3-3.1.1/lib/../ext/cld3/libcld3.so': /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/cld3-3.1.1/lib/../ext/cld3/libcld3.so: undefined symbol: _ZTIN6google8protobuf11MessageLiteE
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/cld3-3.1.1/lib/cld3.rb:87:in `<module:Unstable>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/cld3-3.1.1/lib/cld3.rb:84:in `<module:CLD3>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/cld3-3.1.1/lib/cld3.rb:24:in `<top (required)>'
/home/mastodon/live/config/application.rb:7:in `<top (required)>'
/home/mastodon/live/Rakefile:4:in `require'
/home/mastodon/live/Rakefile:4:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/mastodon/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/home/mastodon/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
</pre>
</details>

I repro'd this on the current master branch (0a110d07b68b68fbb4b15f1e99b62d6fc696c4a7). A clean `git clone`, then `bundle install`, then `bundle exec rake secret` should be enough to repro. I'm running Ubuntu Server 16.04.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by beatrix-bitrot** [comment]
just wanted to add that the PR for mainline is #2949 which has a lot of posts on it as well

**Comment by Gargron** [comment]
I'd like to close this in favour of the issue in the CLD3 repo, because there is nothing I can do about this personally.
