### ISSUE TITLE
Segfault after moving files

### ISSUE THREAD

**Issue by alarig** [tootsuite/mastodon#3058]
Hi,

I moved my instance files from /home/mastodon to /var/local/mastodon/ because of to few free space on /home (and to respect a bit more the linux hierarchy). I replace all the ocurrences of ' /home/mastodon' by '/var/local/mastodon/' and changed the mastodon’s user home and unit paths. Since then, I can’t restart the service. I get a segmentation fault.

```
mastodon@mammout:~$ /var/local/mastodon/.rbenv/shims/bundle exec puma -C config/puma.rb
Erreur de segmentation
mastodon@mammout:~$ strace /var/local/mastodon/.rbenv/shims/bundle exec puma -C config/puma.rb                                                                                       
execve("/var/local/mastodon/.rbenv/shims/bundle", ["/var/local/mastodon/.rbenv/shims"..., "exec", "puma", "-C", "config/puma.rb"], [/* 13 vars */]) = 0
[…]
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9971e16000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9971e15000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9971e14000
arch_prctl(ARCH_SET_FS, 0x7f9971e15680) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
+++ killed by SIGSEGV +++
Erreur de segmentation
```

**Comment by Gargron** [comment]
Mastodon doesn't know or care where exactly it's stored, this sounds like a problem from moving all the ruby-related stuff, I suggest doing a clean install of rbenv/ruby/bundler/etc in the new directory. Also sorry but this is really not a Mastodon-specific issue.
