### ISSUE TITLE
Problem creating a user when registration is closed

### ISSUE THREAD

**Issue by saggel** [tootsuite/mastodon#3059]
I used to be able to create users through ssh but now I get errors when I run this:

```
RAILS_ENV=production bundle exec rails c
account = Account.create!(username: 'username')
user = User.create!(email: 'user@mail.xyz', password: 'userpass', account: username)

> _ActiveRecord::AssociationTypeMismatch: Account(#47022503438240) expected, got String(#47022466072360)_

user.confirm

> _NoMethodError: undefined method `confirm' for nil:NilClass_

account.save!
user.save!

> _NoMethodError: undefined method `save!' for nil:NilClass_

```

Can you help me figure out what's wrong? 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
in the user.create, you have `account: username` when it should be `account: account`
