### ISSUE TITLE
account search API ignores specified instance when instance is local

### ISSUE THREAD

**Issue by brrzap** [tootsuite/mastodon#3064]
The account search API (`/api/v1/accounts/search`) seems sane for cases where (1) the query isn't in the form `user@instance` and (2) the instance in the query is remote.  But in case (3), when the instance in the query is the local instance, the instance specification is completely ignored.

This leads to bad results like querying for `bar@mastodon.social` (an account that exists) and getting a list that doesn't include `bar@mastodon.social`, and includes many accounts on remote instances.  (In this specific case, that account is included when the query is `bar`, but not included when it's `bar@mastodon.social`.)

I think the API should treat case (3) more like case (2):

- never show users on instances that do not match the query;
- if there is an exact match for the `user` portion of the query, it should be first in the list

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I cannot confirm this. If I put "halcy@mastodon.social" into the search on mastodon.social, first result is his mastodon.social account, despite also having two remote ones with the same username. So I think the code is already correct here

**Comment by brrzap** [comment]
this isn't about the webclient search bar -- this is about the account search endpoint at `/api/v1/accounts/search`.  as near as i can tell, the webclient search bar uses the general search endpoint at `/api/v1/search`, which only returns (up to) 5 account matches (and up to 5 hashtag matches).  the API documentation states it defaults to (up to) 40 matches returned for a query; you'd think an exact match would be one of the 40.

`halcy` may not be common enough for a good test case (9 total results from the account search endpoint).  try `@bar@mastodon.social` (returns the maximum 80 results.  guess where the `@bar` account is in the list?  if you guessed "not present", you win a cookie!)

![no-bar-here](https://cloud.githubusercontent.com/assets/26907735/26133007/17241aec-3a72-11e7-8b96-0b74a1313435.png)

**Comment by happycoloredbanana** [comment]
Managed to reproduce this by searching for a user with a one-letter account name.
Will try to fix.

**Comment by brrzap** [comment]
thanks very much @happycoloredbanana. search appears to be working more to expectations.  repeating the searches from the earlier comment now gets the `bar` account first in the list returned.
