### ISSUE TITLE
Following list return error

### ISSUE THREAD

**Issue by pso2club** [tootsuite/mastodon#3065]
Hi.
I'm running bot to follow local users on our instance with `api/v1/accounts/:id` and `api/v1/follows`.

If logged-in user access to bot's following(user card), occasionally errors will be shown.
and profile page is seemingly normal.

![follows](https://cloud.githubusercontent.com/assets/28266940/26053774/0d5340b0-39a5-11e7-8866-d4fad1093b30.png)

Browser console:
![devcon](https://cloud.githubusercontent.com/assets/28266940/26053840/5ee0f972-39a5-11e7-9de2-54992e2dc26e.png)

When investigating the cause, I found `follows.target_account_id` is not existing in `accounts` table, so api is returned error.

    psql=> select f.id, f.account_id, f.target_account_id, a.username from follows f 
    psql-> left join accounts a on f.target_account_id = a.id 
    psql-> where f.account_id = 9;
     id  | account_id | target_account_id |    username
    -----+------------+-------------------+----------------
     382 |          9 |                 1 | info
    ...
     520 |          9 |               131 |
     521 |          9 |               153 |
    (87 rows)

(id 131 and 153 is not found.)

This probably I think because `mastodon:users:clear` tasks will erase unconfirmed users from `accounts` and `users` table, but not erasing from `follows` table.

However, being able to send follow or searchable itself may be a problem.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I see! I didn't expect unconfirmed users to ever be followed, plus the clearing of unconfirmed users is relatively new. Sounds like we need to add some foreign keys on some of the tables to ensure integrity of the references.

**Comment by Gargron** [comment]
Foreign keys have been added, this should be resolved now.
