### ISSUE TITLE
Unminified build of React

### ISSUE THREAD

**Issue by Bichonche** [tootsuite/mastodon#3068]
It seems like you dont build/minify react for production. The site is running waay slower than it should, and probably explains [this issue](https://github.com/tootsuite/mastodon/issues/2040). 

You should probably consider minifying it befoe rolling onto production.

My apologies if that bug is currently being resolved, or if that's not a bug at all.

![unminified](https://cloud.githubusercontent.com/assets/747883/26058603/cfd2916c-397e-11e7-9753-8086234792f6.PNG)

[Some info](https://facebook.github.io/react/docs/optimizing-performance.html#use-the-production-build)
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on  [1.3.3](https://github.com/tootsuite/mastodon/releases/tag/v1.3.3)

**Comment by ykzts** [comment]
duplicated with #2763?

**Comment by Bichonche** [comment]
Indeed, i'm gonna close it, didnt fint it searching for React, nor minified, sorry.
