### ISSUE TITLE
Putting URLs of my own toots into the search causes a "500 Internal server error"

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#3075]
Usually, typing the URL of a particular toot into the search and pressing enter brings up the toot just underneath the search bar, allowing me to boost, reply, etc.

At the moment, doing this with URLs of my own toots results in "500 Internal server error". This is an example of a URL that causes this error: https://cybre.space/@cassolotl/1027576

Toots by other people are showing up normally, but I've been checking my own toot URLs and other people's toot URLs for a few minutes now and only my toots have caused the error, and other people's toots are showing up fine with a search.

* * * *

- [Yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I wasn't able to replicate this in my dev environment. I'll need an error log from the admin, otherwise I'm just gonna assume this isn't an issue in master.

**Comment by Cassolotl** [comment]
Okay, I'll talk to the admin. :) Thanks!

**Comment by Cassolotl** [comment]
Today I am able to find my own toots by URL! So, er, woo! I guess it was a temporary, local problem. :)
