### ISSUE TITLE
How about ZeroNet's decentribute using in mastodon ?

### ISSUE THREAD

**Issue by funny110** [tootsuite/mastodon#3091]
I thinnk mastodon is not a decentribute network, it very depends on instances, if I register on a instance , if it is down or blocked by China GFW, I can't use my account. But ZeroNet don't have this problem, it is a real decentribute network. It has a zite like twitter, named ZeroMe, all files are decentribute to every peers.

- https://github.com/HelloZeroNet/ZeroNet

**Comment by Gargron** [comment]
Different network types like ZeroNet are a completely different paradigm of decentralization. It's not easy to port Mastodon over to them, as it's inherently based on HTTP/TCP protocols.
