### ISSUE TITLE
error about certbot on centos7

### ISSUE THREAD

**Issue by oyosc** [tootsuite/mastodon#3095]
when i install cerbot in centos7,it is ok and no problem.but when i run certbot certificates or certbot certonly --standalone -d myHostName,it occurs     raise ImportError("'pyOpenSSL' module missing required functionality. "
ImportError: 'pyOpenSSL' module missing required functionality. Try upgrading to v0.14 or newer.

i serach some ways like yum install epel-release,yum install certbot, as i see ,it is no useful, so please tell me what can i do, or only to try ubuntu?

**Comment by archaeme** [comment]
I would try acme.sh instead, doesn't use python: https://github.com/Neilpang/acme.sh

**Comment by Gargron** [comment]
I can't really help you with certbot, it's made by Let's Encrypt, not us.
