### ISSUE TITLE
the problem of smtp

### ISSUE THREAD

**Issue by oyosc** [tootsuite/mastodon#3106]
SMTP_SERVER=smtp.mailgun.org
SMTP_PORT=587
SMTP_LOGIN=postmaster@example.com
SMTP_PASSWORD=the value of SMTP_PASSWORD
SMTP_FROM_ADDRESS=postmaster@example.com
#SMTP_DOMAIN= # defaults to LOCAL_DOMAIN
#SMTP_DELIVERY_METHOD=smtp # delivery method can also be sendmail
#SMTP_AUTH_METHOD=plain
#SMTP_OPENSSL_VERIFY_MODE=peer
#SMTP_ENABLE_STARTTLS_AUTO=true

this is my config of smtp,i want to ask whether is right,the example.com is my domain,and when i send email,the sidekiq show me these messages:

2017-05-18T03:04:02.346Z 25166 TID-svbnw ActionMailer::DeliveryJob JID-54f241ccd25dc6846d7b05f0 INFO: start
2017-05-18T03:04:03.059Z 25166 TID-svbnw ActionMailer::DeliveryJob JID-54f241ccd25dc6846d7b05f0 INFO: done: 0.712 sec

but i haven't receive any email,so is wrong with my config or others?

**Comment by nightpool** [comment]
This probably isn't the place for this issue—you might want to try asking in the mastodon admin matrix channel or on the mastodon admin email list, instead of on the development repository.

**Comment by oyosc** [comment]
maybe my question is not correct
in the backend,i run the command like bundle exec sidekiq and bundle exec rails server -b 127.0.0.1;  it is successful 
and no error; but when i register an ancount in the frontend, it saids it will  send an email to my email of account,but i haven't received!

**Comment by Gargron** [comment]
Check mailgun logs, everything works fine on mastodon end (indicated by "done")
