### ISSUE TITLE
Add support for json feed

### ISSUE THREAD

**Issue by metbril** [tootsuite/mastodon#3107]
Recently a spec was published for json feed, a json alternative for rss and stom xml.

https://jsonfeed.org/2017/05/17/announcing_json_feed

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
JSON-based representations will be available as part of #1557, but we have no interest in "json feeds". I am not aware of any software which would make use of them. Our feeds serve protocol-related purposes and rely on Atom extensions.
