### ISSUE TITLE
3rd party streaming API authentication

### ISSUE THREAD

**Issue by Lokeh** [tootsuite/mastodon#3119]
When trying to connect to `https://<host>/api/v1/streaming/user` using an `EventSource` on an external app, it declines the connection with a 401.

What is the expected way to authenticate with the streaming API? For non-streaming endpoints I was using a bearer token, however there is not a way that I am aware of sending an authorization header with an EventSource.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by happycoloredbanana** [comment]
Besides sending it in a header, it is possible to pass the token in the POST body or in an URI query parameter ([RFC 6750](https://tools.ietf.org/html/rfc6750#section-2.2)). From the security perspective it's less recommended though.

**Comment by Lokeh** [comment]
@happycoloredbanana so if I understand correctly, I should be able to create the event source by passing the access token in the URL?

e.g.: `https://<host>/api/v1/streaming/user?access_token=<token>`

I tried this using the bearer token (`Bearer <token>`) that I have been passing in to the RESTful endpoints, and I still receive a 401 response.

**Comment by happycoloredbanana** [comment]
@Lokeh Oops, my bad: forgot that streaming is completely separate code. Current implementation [supports only token provided in the  header](https://github.com/tootsuite/mastodon/blob/v1.3.3/streaming/index.js#L142).

I guess it could be changed, depending on how @Gargron feels about it.

**Comment by Lokeh** [comment]
So since the `EventSource` API in browsers does not support sending custom headers, what is the suggested way to use the streaming API? Should I try to use web sockets instead? There's no API documentation for it, but I can see the implementation in the file that you linked to.

**Comment by happycoloredbanana** [comment]
Web sockets is what the web client uses, so at least we can be sure it works ;)
In the case of web sockets the token is also [passed in the URI](https://github.com/tootsuite/mastodon/blob/v1.3.3/app/assets/javascripts/components/stream.jsx).

**Comment by happycoloredbanana** [comment]
@Lokeh I've made a small change to make the streaming API able to retrieve the token from URI. Hope it helps.

**Comment by Lokeh** [comment]
@happycoloredbanana thanks a ton! 😁
