### ISSUE TITLE
Change or reset database

### ISSUE THREAD

**Issue by bokuyami21** [tootsuite/mastodon#3126]
First thing,I'm sorry for my stupid question !
Now, My mastodon instance is working fine in local.
And i want to reset all users in database or change to new database.
Please tel me what are steps to do it ?

Thanks and looking forward your reply.
* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
http://edgeguides.rubyonrails.org/active_record_migrations.html#resetting-the-database

**Comment by bokuyami21** [comment]
@mjankowski  You saved  me a lot of time. Thank you
