### ISSUE TITLE
Replace axios with fetch

### ISSUE THREAD

**Issue by sorin-davidoi** [tootsuite/mastodon#3133]
`axios` takes `12KB`, and we only seam to use the basic features (no Node.js, no canceling, no intercepts, the transform can be easily replaced). Should we replace it with [unfetch](https://github.com/developit/unfetch)?

Pros:
- It is a polyfill, so we could only load it for browsers that need it
- It is `500B` gzipped
- Swap a library for a web standard

Cons:
- It is not a complete polyfill (hence the size) - but it supports the basic features and that is what we use
- `fetch` does not reject for statuses 400-500 like I think `axios` does, so we need to take care of this manually

This should be a fairly easy refactoring (it is only used in two files) and I am up for doing it.

**Comment by Gargron** [comment]
I really like the axios API. It's very straightforward to use.
