### ISSUE TITLE
Mastodon should use built-in rot13 for "spoilertext"

### ISSUE THREAD

**Issue by lauramichet** [tootsuite/mastodon#315]
Instead of using a spoiler-hiding toggle, Masto should have a built-in rot13 (example: [here](http://www.rot13.com/) )  function which allows you to scramble both outgoing toots, AND apply the shift to tweets you see in timelines.

Rot13 is a spoiler- or secret-hiding convention common in the communities which currently use Mastodon. It has, I think, a lot of character, and would allow us to hide and send spoiler-ized info without attaching additional data to a toot.

**Comment by IBPX** [comment]
The problem is it only works for the Latin alphabet. Any language with different letters needs a different system.

**Comment by marrus-sh** [comment]
I threw together a ROT* cypher which will work for any script, and is identical to ROT13 for ASCII Latin, which you can test here: https://marrus-sh.github.io/rotstar/

Basically, I just collected which Unicode characters were letters from `LineBreaks.txt` in the Unicode Character Database and did a `length/2` shift over each contiguous block. (For odd-lengthed blocks, the last letter in the block is left out.) Punctuation and other characters (importantly, characters regarding text direction and variation selectors) are left untouched—only letter characters are affected.

The cypher results won't necessarily make a whole lot of conceptual sense in many languages—it might be a mess of capitals and lower-case, for example, depending on how Unicode broke up the blocks—but it is functional and tweaking could always happen in the future.

I don't have a strong opinion on whether ROT13 gets implemented into Mastodon or not, but this should at least keep the option open.

**Comment by Gargron** [comment]
Resolved through content warnings
