### ISSUE TITLE
Federated timeline issue

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#3154]
Hello, this issue started today with the commits released within the past few hours. When you refresh, only local posts show up in the federated timeline. As you leave the page open, new federated posts show up, but the disappear again upon refreshing the page. This was also confirmed by @beatrix-bitrot  
![img_7706](https://cloud.githubusercontent.com/assets/1431774/26266617/f839c912-3c9a-11e7-8c26-1e9ba9ca0b8e.PNG)

**Comment by nightpool** [comment]
from dev chat: does this include commit https://github.com/tootsuite/mastodon/pull/3151? (commit https://github.com/tootsuite/mastodon/commit/f8ee136c29aa7185fe05450090229d428986e529)

**Comment by malicioustoker** [comment]
@nightpool If you're asking me - I'm not sure what commit exactly is was, but I can tell you it was one of theses for sure. 
![img_0160](https://cloud.githubusercontent.com/assets/1431774/26270003/3ded42f6-3cad-11e7-9ae4-3234266cf85d.PNG)

**Comment by beatrix-bitrot** [comment]
this should be fixed by PR #3161 

@malicioustoker can you fetch latest master if you haven't and confirm the fix is good? it seems to work on my instance.

if good, please close the issue

thanks

**Comment by malicioustoker** [comment]
It is indeed fixed, thanks 😊
