### ISSUE TITLE
I created "Mastodon Translation Team" on Slack.

### ISSUE THREAD

**Issue by LNDDYL** [tootsuite/mastodon#3162]
https://mastodon-translation.slack.com

![4a8ae28a548b7708](https://cloud.githubusercontent.com/assets/4318463/26243458/86f5bf80-3cbe-11e7-9d85-958f9f3bc896.png)

**Comment by LNDDYL** [comment]
The team's invite link: inhttps://mastodon-translation.slack.com/shared_invite/MTg2ODUwMzI4MDA2LTE0OTUzNTUzMTYtNzAyYzUzNTEzYw

**Comment by Technowix** [comment]
https://discourse.joinmastodon.org/ might be a better place.
Also, Slack is... well, if your not going to pay a bunch, not that cool.

**Comment by Gargron** [comment]
I don't think we should keep an open issue for this..? You can talk about it on [Discourse](https://discourse.joinmastodon.org), posts can be pinned there.
