### ISSUE TITLE
Change "getting started" icon in nav bar to hamburger

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#3169]
There is an unnecessary similarity in two of five icons:

![image](https://cloud.githubusercontent.com/assets/164785/26275788/79040d40-3d69-11e7-8ae5-4772c54e2ea5.png)

"Gettings started" *(1)* should a more distinctive icon compared to "Preferences" *(4)*.

**Comment by Gargron** [comment]
Oh, fixed
