### ISSUE TITLE
Incompatible?

### ISSUE THREAD

**Issue by 46neko** [tootsuite/mastodon#3193]
Mastodon did not work properly with a Japanese browser called Dolphin Browser. Thank you for your amelioration.
https://imgur.com/a/vQtTe

**Comment by yookoala** [comment]
Need help from Dolphin team. There don't seems to be remote debugging tools for the Dolphin browser. 

The Mastodon interface works with [Chrome for Mobile](https://www.google.com/chrome/browser/mobile/index.html), which like [Dolphin](dolphin.com/) is a [Webkit](https://webkit.org/) based browser. That means the problem would most likely be in Dolphin's javascript engine. Without a proper debugging tool, it is very hard for any developer to pin point the problem.

Mean while, please try using [Apps](https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/Apps.md) to access your favourite Mastodon instance.
