### ISSUE TITLE
Transparent GIF avatars are broken

### ISSUE THREAD

**Issue by no-boot-device** [tootsuite/mastodon#3199]
If you have a transparent GIF avatar, Mastodon automatically assumes you want it to crop the first frame of all transparency for some reason. Somehow, it manages to ruin the entire GIF along the way.

Reproduce:
1. Make a GIF avatar that has transparency and does not completely fill available space (specifically on the first frame)
2. Watch as Mastodon mangles it beyond recognition depending on how much space there was

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
#4547 has been reverted.
