### ISSUE TITLE
mobile view: slowdown on "Compose" tab with Firefox

### ISSUE THREAD

**Issue by abochmann** [tootsuite/mastodon#3210]
When accessing the Mastodon web UI in mobile view with Firefox (drag the FF window smaller until the UI switches from the multi-pane view to the tabbed view with Compose / Home / Notifications / Local / Federated tabs), all of the tabs except "Compose" are perfectly usable even on slower devices (think Raspberry Pi).

As soon as I switch to the "Compose" tab though, one of the Firefox threads starts using 25% to 100% CPU, and text entry in the edit field is nearly impossible (typed text needs seconds to show up). This is noticeable as a small lag even on faster systems.

Possibly related, this message shows up in the developer tools console:

`mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create application-cd143bd3c519cbb96b82996ea9786b8abc3983a3b417b533db4f41b1ad8b2191.js:1770:13090`

(The referenced file seems to contain jQuery code.)

The issue was initially noticed on an ARM device with Pale Moon (a Firefox fork), and then reproduced with Firefox ESR 45.9.0 on a Raspberry Pi 3. 

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate. (Possibly #2101)
- [X] This bug happens on a [tagged release]: v1.3.3

**Comment by sorin-davidoi** [comment]
Version `1.4` (currently in RC2) brings many performance optimisations - production build of React, bundle size drop, lazy loading the emoji picker on the compose page, less elements in the DOM. Could you try the release candidate and let us know if it improves things for you?

**Comment by abochmann** [comment]
Seems improved, but still noticeable on slow devices, in 1.4RC3 (and the message mentioned above doesn't show up anymore). Won't have time to have a closer look at things until tomorrow.

**Comment by abochmann** [comment]
This seems much better on 1.4RC3. The slowdown is now barely noticeable on a Raspberry Pi 3 (unless I open the emoji picker, but that's probably a different issue). 
Still brings slower devices to a crawl, but I lack the knowhow to add any more useful debugging information.

**Comment by abochmann** [comment]
Barely noticeable now on 1.4RC5, so I'll close the issue. Thanks!
