### ISSUE TITLE
Timelines not refreshing on 1.3.3

### ISSUE THREAD

**Issue by theophilus79** [tootsuite/mastodon#3212]
I'm running 1.3.3, and users are still complaining of this issue.

![image](https://cloud.githubusercontent.com/assets/20190320/26287976/184f7e24-3e4c-11e7-9b43-fd0b426bab0c.png)
![image](https://cloud.githubusercontent.com/assets/20190320/26287972/02a3a6e0-3e4c-11e7-870d-4f38130755cf.png)
![image](https://cloud.githubusercontent.com/assets/20190320/26287981/2e8c3088-3e4c-11e7-8c84-3b1159a80eca.png)

* * * *
All issues related have been closed as "solved", though no method of solving appears to have been shared.

**Comment by Angristan** [comment]
Same problem on 1.3.3 on mstdn.io : https://mstdn.io/@funbreaker/2326592

I did not experience this myself tough

**Comment by theophilus79** [comment]
Complaints are coming from both Chrome and Firefox users. I use Chromium on Linux and haven't personally experienced it. But it seems to be a daily complaint.

**Comment by Angristan** [comment]
Apparently deleting cookies solves the problem : https://mstdn.io/@funbreaker/2469786

**Comment by Gargron** [comment]
Is this still an issue? (Besides, there are so many reasons this could be happening! Most likely misconfigured deployment, CSP headers, or the like)
