### ISSUE TITLE
[1.4.0.2] header X-Accel-Mapping missing

### ISSUE THREAD

**Issue by Dryusdan** [tootsuite/mastodon#3221]
Hi   
After lot of problem for migration (forgot make persistance data for pack folder ><) I display mastodon logs and console show the same error : 
`X-Accel-Mapping header missing`   
But, how to configure this ? Because I don't use passenger for nginx (just proxy_pass)

Any idea ?

**Comment by malicioustoker** [comment]
I have the same issue with Caddy

**Comment by beatrix-bitrot** [comment]
I don't use nginx or docker and have this issue, would be nice to know what's going on here.

**Comment by Dryusdan** [comment]
I remove docker tag to correspond with your problem :)

**Comment by dereckson** [comment]
So, this issue indeed isn't dependant of Docker, but it's a feature of rails.

References:
  * https://mattbrictson.com/accelerated-rails-downloads
  * https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/ explains the X-Accel feature from nginx point of view

**Comment by Gargron** [comment]
Do you have `RAILS_SERVE_STATIC_FILES` set in your environment?

**Comment by malicioustoker** [comment]
I do

**Comment by Gargron** [comment]
It's a thing that happens when Puma/Rails serves static files (it is recommended to serve static files directly through nginx, because it is way faster, but it may not be possible if, for example, you're running a precompiled Docker image instead of having checked out source code available). I have not used this feature, but here is documentation on it: <https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/>

As far as I understand this message in the logs is non-breaking. Everything still works, right? Except serving files is slower than it could be directly through nginx.

**Comment by malicioustoker** [comment]
I use Caddy, not Nginx - so I just need to figure out how to convert the nginx config for that over to Caddy haha. But other than that, no, it doesn't break anything - just spams terminal 🙃

**Comment by Gargron** [comment]
<https://caddyserver.com/docs/internal>

**Comment by malicioustoker** [comment]
Thanks 😊

So would it be...

internal /mastodon/public/

**Comment by malicioustoker** [comment]
You Follow up, I turned RAILS_SERVE_STATIC_FILES off, I added

internal /mastodon/public

To my caddyfile. Everything seems to still load currently, but I'm still getting this


web_1        | X-Accel-Mapping header missing
web_1        | X-Accel-Mapping header missing
web_1        | X-Accel-Mapping header missing
web_1        | X-Accel-Mapping header missing
web_1        | X-Accel-Mapping header missing
web_1        | X-Accel-Mapping header missing
web_1        | X-Accel-Mapping header missing
web_1        | X-Accel-Mapping header missing
web_1        | X-Accel-Mapping header missing
web_1        | X-Accel-Mapping header missing
web_1        | X-Accel-Mapping header missing
web_1        | X-Accel-Mapping header missing

**Comment by Gargron** [comment]
All I can find is [this](https://github.com/discourse/discourse/commit/103e2ebba91a35cdd5b5c5c6a74583662ff8df70#diff-dcb4e4bf839548afcb76860d102bfacaR122)?

**Comment by malicioustoker** [comment]
Not sure what this has to do with Caddy 🤷🏼‍♂️ I'm really not too concerned about this though, as everything seems to work properly regardless of getting spammed with the error message lol. As far as I'm concerned- this can be closed

**Comment by Gargron** [comment]
Well basically you might have to pass another header to Puma, but I have no idea. And yeah.
