### ISSUE TITLE
"Changes successfully saved!" after changing locale should be in the new locale

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#3223]
When I changed locale to English from Japanese, "Changes successfully saved!" message was shown in Japanese. I think it should be in English.

![image](https://cloud.githubusercontent.com/assets/705555/26308032/67f2279c-3f32-11e7-84d5-e8618c206048.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
(This got fixed)
