### ISSUE TITLE
Moderator-visible notes

### ISSUE THREAD

**Issue by chriswmartin** [tootsuite/mastodon#3234]
Related to #602 "Ability to add personal note when blocking a user for easier Blocked Users list management" but would be only visible to administrators of a given instance in the admin/accounts view.

The notes could be used to keep a record of which rule a user violated or as a way to implement a “strike” system for moderation.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Implemented in #5240
