### ISSUE TITLE
Error viewing remote profiles (1.4.0.2)

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#3237]
Happens with 1.4.0.2.

When a remote* profile on a 1.4.0.2 instance is viewed outside the web-app (using https://instance.tld/@someone) the famous 'We're sorry, but something went wrong' is displayed (see screenshot). 

 \* Not logged in on the instance of the profile you like to view.

This doesn't happen with 1.3.3 instances. Profiles are normally displayed when I'm logged in (on mastodon.social in this case).

![schermafdruk van 2017-05-22 21-22-45](https://cloud.githubusercontent.com/assets/3049892/26325008/708743b2-3f35-11e7-9397-effbd5c8df3b.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
Is this happening consistently for you across many profiles ... or intermittent?

**Comment by jeroenpraat** [comment]
It happened consistently across all RC2 instances, but according Eugen it's now fixed and it should be in RC3. So I'm closing this issue for now.

**Comment by jeroenpraat** [comment]
I'm sorry to reopen this again, but also in RC3 this is still an issue.

I checked 3 instances that already upgraded to RC3 (1.4.0.3) and still an error.

https://social.targaryen.house/@wonderfall
https://niu.moe/@Technowix
https://mikumikudance.cloud/@syumari

**Comment by Gargron** [comment]
All of those links work for me. But the issue was locale-related. I went through all locales to fix it but perhaps I missed one? What is your browser's preferred locale?

**Comment by jeroenpraat** [comment]
nl_NL

**Comment by jeroenpraat** [comment]
OK, I can confirm it when I switch to 'en' locale, the profiles are displayed.

**Comment by jeroenpraat** [comment]
nl_NL stands for Dutch (Nederlands), Netherlands (Nederland)
