### ISSUE TITLE
Public profile usability and readability improvements

### ISSUE THREAD

**Issue by sophia-park** [tootsuite/mastodon#324]
Our public profiles are often the outside Internet's first look at the Mastodon users, community, and Mastodon as project.

Unfortunately as Mastodon has come into use a large number of users have public profiles that become very unwieldy: for example ten toots per page makes this profile, at time of writing, into a 98-pager:

https://mastodon.social/users/jk

I would suggest a way of displaying more information, and more relevant information, on a public profile: 25 toots per page is a great first step, but automatically loading in more toots to scroll might be ideal.

In addition the more communal Mastodon community creates public profile pages with lots and lots and lots of mentions. 

I would suggest defaulting to non-mention toots only if possible? 

If we can't filter the toots on a public profile, I would then suggest adding in some options to interact with a toot from its public permalink: you can't currently bump a toot very easily, and one's public profile seems like the best place to find their thoughts further and further back.

**Comment by marrus-sh** [comment]
An "open in timeline" button on profile pages and toots, which opens a timeline page with the given item in the "third column", would solve a lot of static page usability concerns I think. For example giving [my profile page](https://mastodon.social/users/marrus_sh) a prominent to https://mastodon.social/web/accounts/12951.

**Comment by swaldie** [comment]
The comment about non-filtering toots is the enhancement recommended in #174, which is probably worth noting.

**Comment by marrus-sh** [comment]
Adding to this discussion [@fawn@mastodon.social](https://mastodon.social/users/fawn)'s request for [a media tab](https://mastodon.social/users/fawn/updates/634343) on profile pages, to give users easier access to an artist's works. So we might have a twitter-like setup which has:

- Toots
- Toots (with replies)
- Media [only toots which contain media attachments]

I would also say that having these features available in timeline view (maybe using a similar settings toggle to the Notifications tab?) would probably be appreciated as well.

**Comment by wxcafe** [comment]
This has mostly been fixed thanks to the new profile UI, except for the neverending-scroll part. I believe this is fine, so I'm closing this. Feel free to open a new issue about the never-ending-scroll thing if you feel it warrants it.
