### ISSUE TITLE
Extended info user/toot counts stopped/skewed.

### ISSUE THREAD

**Issue by isati** [tootsuite/mastodon#3241]
Since upgrading my instance to 1.4rc/1/2/3, the counts of users/toots/connected instances has been skewed and is no longer updating. Upon upgrading to rc1 the values for each dropped marginally and now no longer update. I've checked through log files but can't see any obvious errors or warnings. I did the usual db:migrate/assets:precompile - any idea how to debug this?

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by isati** [comment]
Seemingly resolved in 1.4rc4, although not sure what changed.

**Comment by Gargron** [comment]
There was a misconfiguration with cache expiration not being set which has since been corrected.
