### ISSUE TITLE
Push Notifications not consistent

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#3244]
Hello again - I'm not really sure where the problem lies, nor do I know how to even go about tracing it - push notifications on my instance are not consistent at all. Sometimes people will receive one or two, then nothing till the next day even though they should be receiving some...

**Comment by Gargron** [comment]
Push notifications are not sent directly from Mastodon. An app's server connects to the Mastodon streaming API, listens on some events, and dispatches push notifications. Example app server: <https://github.com/Gargron/tusky-api>

So this is either a streaming API issue or (more likely) the app server's issue

**Comment by malicioustoker** [comment]
The thing is though that streaming works on the server. I've tried every all there is on the Apple side. None of them work on my server, but they work on other instances..

**Comment by malicioustoker** [comment]
Just a little bit more information - from what I've noticed, it appears that I only receive push notifications from my Instance when I'm on the same network as the server

**Comment by malicioustoker** [comment]
It was indeed an issue with the app - thanks guys!
