### ISSUE TITLE
Endpoint for all direct messages to and from a given user, or all messages in general

### ISSUE THREAD

**Issue by DagAgren** [tootsuite/mastodon#3255]
I'm working on a client, and I'd love to add a chat client like view for DMs. This would be greatly simplified if there was an endpoint where I could request all direct messages from and to a specific user.

Perhaps there could also be options to either limit it to just direct messages or all statuses referring to that user, so that you could mix in public messages too if you preferred.

This could perhaps be either a couple of options for `/api/v1/accounts/:id/statuses`, such as "include_me", "to_me_only" and "direct_only", or a separate endpoint like `/api/v1/accounts/:id/conversation`.

* * * *

- [x] I searched or browsed the repo's other issues to ensure this is not a duplicate (as far as I can tell).

**Comment by Gargron** [comment]
Thank you for opening an issue for this 👍
