### ISSUE TITLE
Update documentation to include Attachment metadata

### ISSUE THREAD

**Issue by DagAgren** [tootsuite/mastodon#3260]
~~To enable more clever layout when showing attachments, it would be wonderful if Attachment would contain width and height fields for the attached media.~~

The documentation for the Attachment object currently does not included the `meta:` field. This should be documented.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
I thought that we had this..? Maybe it's not hooked up correctly?

**Comment by DagAgren** [comment]
Actually, all I did was read the documentation which does not seem to list it. Maybe it is just not up to date?

**Comment by DagAgren** [comment]
Yup, it's there. I'll edit the issue.

**Comment by Gargron** [comment]
Done!
