### ISSUE TITLE
All gif avatars are animating by default

### ISSUE THREAD

**Issue by Ragzouken** [tootsuite/mastodon#3262]
All gif avatars are animating by default, and pause when you hover over them.

https://github.com/tootsuite/mastodon/issues/2846 seems related but seems to be only for specific avatars. For me all avatars are animating

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
It "auto play animated GIFs" option turned on or off in your preferences?

**Comment by Ragzouken** [comment]
I want animated gifs to play, just not avatars

**Comment by Ragzouken** [comment]
(this was working before)

**Comment by Gargron** [comment]
I am asking because it is "on" for me and all avatars are paused until hovered (correctly), so it's very weird.

**Comment by beatrix-bitrot** [comment]
@Gargron i can confirm i have this issue as well (for quite a while now). latest chrome on win10. i would test on FF but something about my instances CSP seems to prevent my instance for loading for me in FF at the moment...

**Comment by Ragzouken** [comment]
i have the setting off

**Comment by joyeusenoelle** [comment]
Observed in Safari 10.0.3 on Mac OS X 10.11.6 and in Chrome 58.0.3029.110 on Windows 8.

With or without the "auto-play animated gifs" toggle selected, animated avatars display the same behavior: 

1. When first loaded, an animated-gif avatar animates fully.
2. When I hover the mouse over it, it continues animating.
3. As soon as I unhover the mouse, it returns to frame 1 and stops animating.
4. Thereafter, hovering the mouse over the avatar animates it, and unhovering causes it to return to frame 1 and stop animating.

This must be done for each instance of a given avatar; for example, if I have multiple posts by https://mastodon.social/@jk on my timeline, each post's avatar will animate independently until I've hovered over it, regardless of whether I've hovered over the other posts' avatars.

My understanding is that the behavior demonstrated in point 4 is the expected and planned behavior, but that 1 is unexpected and unplanned.

**Comment by unarist** [comment]
The default value of `state.hovering` on Account component seems to be changed to `true` at https://github.com/tootsuite/mastodon/commit/2991a7cfe685ca9b42230b7030b9e7d0ece94c88#diff-50de755057c03939d93e8c516237b08a.

@ykzts Is this change intended?

**Comment by ykzts** [comment]
@unarist 

> The default value of state.hovering on Account component seems to be changed to true at 2991a7c#diff-50de755057c03939d93e8c516237b08a.
> 
> @ykzts Is this change intended?

No. This is my mistake.

**Comment by Ragzouken** [comment]
this seems to have returned
