### ISSUE TITLE
Compose window removes words prefixed with dollar sign ($)

### ISSUE THREAD

**Issue by joyeusenoelle** [tootsuite/mastodon#3270]
On instances running any version of 1.4 (for example, mastodon.social), any word composed only of English letters (not numbers, punctuation, or non-English characters) in a newly-composed toot that is prefixed with a dollar sign ($) is removed from the toot after submission but before posting. 

Examples:

|Toot|Expected|Observed|
|----|----------|---------|
|I have $one.|I have $one.|I have .|
|I have $1.|I have $1.|I have $1.|
|I have $1one.|I have $1one.|I have $1one.|
|I have $one1.|I have $one1.|I have $one1.|
|I have $öne.|I have $öne.|I have $öne.|

I suspect that some variable interpolation is occurring; if that's the case it could represent a security hole.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by DJSundog** [comment]
Upon further poking of this bug from the web ui, it seems to only be some $-prefixed words - see https://toot-lab.reclaim.technology/@djsundog/399876 as an example.

**Comment by joyeusenoelle** [comment]
In addition to $summary, I've discovered some others:

$displayname
$username
$preferredusername

In addition, I've found that whatever is doing this counts a number of symbols as word breaks:

|Input|Output|
|-----|------|
|$test-one|-one|
|$test_two|_two|
|$test–three|$test–three|
|$test=four|=four|
|$test.five|.five|
|$test?six|?six|
|$test@seven|@seven|
|$test#eight|#eight|
|$test$nine|$nine|
|$test^ten|^ten|
|$test*eleven|*eleven|
|$test(twelve|(twelve|
|$test)thirteen|)thirteen|
|$test&fourteen|&fourteen|
|$testöfifteen|$testöfifteen|
$test1sixteen|$test1sixteen|

Note line 9 in particular: $test$nine only removes `$test` and not `$nine`. The dash in line 3 is an en-dash `–`, not a standard hyphen (which is line 1). Including a number or non-English glyph mid-word (lines 15 and 16) stops the word from being removed.
