### ISSUE TITLE
[1.4rc3] Rendering issue on Chrome 53 and derivatives

### ISSUE THREAD

**Issue by Aldarone** [tootsuite/mastodon#3277]
Since rc1 I have noticed a rendering bug (on GNU/Linux at least) with browsers based on Chrome 53 (namely : Rambox and QupZilla)

The webclient displays everything fine until I scroll any column. The bottom toots are not displayed at all until I go over them with the mouse.

Here is a screencap : https://www.youtube.com/watch?v=eeEn53RkmmU

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Is this because of #3158? cc @sorin-davidoi

**Comment by Aldarone** [comment]
I think that's it. When I go in the developper tools and disable the `contain` rule, everything is fine again.

**Comment by sorin-davidoi** [comment]
I guess it's a bug in the Chrome 53 implementation? Don't really see what we could do here apart from reverting the commit, since blacklisting browsers is a path I don't really agree with.

**Comment by nolanlawson** [comment]
Hm, maybe wrap those `contain`s in a `@supports` block that will only match for later versions of Chrome? E.g. [CSS Grid shipped in Chrome 57](http://caniuse.com/#feat=css-grid), so you could use something like

```css
@supports (grid-columns: 100%) {
  // put styles here
}
```

This is definitely a hack of course.

**Comment by nolanlawson** [comment]
This seems to be affecting folks on Chrome 55 on Android 4.4.2 as well:

- https://mastodon.social/@djoerd/6913428
- https://toot.cafe/@nolan/597542
