### ISSUE TITLE
Toot only to the local timeline.

### ISSUE THREAD

**Issue by carlosjs23** [tootsuite/mastodon#3285]
Currently there is the option "Unlisted" but as expected the toots are not published in either of the two timelines and the toots are only shown to my followers in their home column, and there are times when I only want to publish in the local timeline of my community.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
This is a good idea! It's also already been suggested, so I recommend adding your +1/thumbs-up/comments to #861. :)

**Comment by carlosjs23** [comment]
Oh thanks, I was looking for the issue and I could not find it.
