### ISSUE TITLE
rimraf: not found Command failed with exit code 127.

### ISSUE THREAD

**Issue by vidarlee** [tootsuite/mastodon#3294]
I merged this [commit(#3269)](https://github.com/tootsuite/mastodon/pull/3269)，then start the mastodon service, and i got this error in my development environment:
~~~
02:44:18 stream.1  | $ rimraf ./tmp/streaming && babel ./streaming/index.js --out-dir ./tmp && node ./tmp/streaming/index.js
02:44:18 stream.1  | sh: 1: rimraf: not found
02:44:18 stream.1  | error Command failed with exit code 127.
~~~

Then, i install the rimraf by yarn and fix this problem.
~~~
$ yarn add rimraf
~~~
I think there is no rimraf in the development VM before we install it munually.
Do you guys think we should add it into yarn.lock file?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
`rimraf` was added in #3130. Also merge here.

**Comment by vidarlee** [comment]
@ykzts Thank you very much~

**Comment by jeems-master** [comment]
Good.Thank you.
