### ISSUE TITLE
Issue with WebSocket authentication

### ISSUE THREAD

**Issue by coolstar** [tootsuite/mastodon#331]
I am attempting to stream from the HTTPS websocket at https://mastodon.social/cable

However, I have noticed some issues with authentication.

1. The cable doesn't seem to accept a BEARER token, it only accepts the _mastodon_session cookie

However, this is where things start getting weird

1. When I use the cookie that's set by https://mastodon.social/oauth/token (which appears to be a 612 byte cookie), the cable accepts it and gives me a stream which I can use
2. When I use the cookie I get from any API endpoint with a BEARER token, the cable seems to set up a stream, but the stream is immediately closed

Is there any way to work around this or will this need to be fixed in Mastodon?

**Comment by Gargron** [comment]
I've researched this and found that custom headers such as the Authorization header cannot be set on websocket requests. At the moment of the Websocket connection being established, the only data it can access about the connection are the cookies (which are not used by the API).

Reading up on it, it has been suggested elsewhere to use a custom event/message to authenticate. So you'd need to send a message with the access token to the websocket and it would decide whether to accept or reject the connection. How does that sound?

**Comment by coolstar** [comment]
A message on connection to the web socket sounds like it'll work :)

**Comment by Gargron** [comment]
I have implemented a proper [streaming API](https://github.com/tootsuite/mastodon/blob/master/docs/Using-the-API/Streaming-API.md) and will soon phase out websockets from web UI once I've configured everything performs well. But as far as app developing is concerned, the streaming API can already be used!
