### ISSUE TITLE
CSS? Issue

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#3319]
Okay, like always, I'm not exactly sure what commit broke it, but it was between #3306 and #3310 within the list of recent commits, but this is the issue I have on my instance now.
![img_0176](https://cloud.githubusercontent.com/assets/1431774/26470641/4e6ed93c-4153-11e7-952a-ae8768911446.PNG)
![img_0177](https://cloud.githubusercontent.com/assets/1431774/26470642/4e7bc9bc-4153-11e7-9918-c20246f05450.PNG)

**Comment by malicioustoker** [comment]
Okay, to make things even more complicated, this issue only appears when I use social.nofftopia.com - which goes through CloudFlare. If I use social.noff.co, which bypasses CloudFlare, things load as they should

**Comment by malicioustoker** [comment]
Problem solved! Had to turn off Auto Minify for CSS on CloudFlare

**Comment by aatxe** [comment]
I also just encountered this, and I'm finding myself wondering: why does CloudFlare's CSS minification break Mastodon?

**Comment by malicioustoker** [comment]
🤷🏼‍♂️

**Comment by nullkal** [comment]
Once I saw the same issue and I figured out that Subresource Integrity(https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) matters.

**Comment by aatxe** [comment]
Ah, I did not realize that they used SRI. Neat!
