### ISSUE TITLE
Login email field is case sensitive

### ISSUE THREAD

**Issue by Southclaws** [tootsuite/mastodon#3325]
This issue made me think there was a more serious bug with password changing but it turns out it's just a UX oversight.

When logging in, email field is case sensitive, resulting in a failed login even if the credentials match. I always type my email with the first character uppercase since it's my name and that's just muscle memory. It seems like the registration process converted my registered email to lowercase (perfectly acceptable, pretty standard) but the login process did not do this and it's doing a case sensitive match so after a few password change attempts thinking the database was not updating my password I realised this letter case was causing the issue.

I'd classify this as a bug because pretty much every other service I've ever used handles emails/usernames without caring about case and it caused quite a bit of confusion while trying to log in! I can imagine this should be a super simple fix.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by saper** [comment]
According to Internet standards email address is not case sensitive (only the domain name part). The local part can use capitalization as it wishes. Lower casing the email address is a bug.
