### ISSUE TITLE
Add option to profile dropdown to directly send direct message

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#3326]
When I have someone's profile open, the easiest way to send a direct message to that person seems to be to select "mention" from the hamburger menu below their profile and then to set the privacy to "direct message".

This seems to be a bit unintuitive; it took me a while to figure it out. As a new user I would expect to directly find a "direct message" link on a profile (assuming that we follow each other etc.).
Additionally, it is very easy to first write the message and then forget to set the privacy option properly.

Therefore, I would find it preferable if one could directly select "write direct message" and would then be dropped in the compose field with the right privacy option already selected.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by cphuntington97** [comment]
It would be very easy to add "Direct" underneath "Mention" on the profile menu.

**Comment by Cassolotl** [comment]
We have this now! :)

![screen shot 2018-05-26 at 12 32 51](https://user-images.githubusercontent.com/6607512/40575668-f2657962-60e0-11e8-8440-c6fe674085e5.png)
