### ISSUE TITLE
hide sensitive content after revealing it

### ISSUE THREAD

**Issue by deckycoss** [tootsuite/mastodon#336]
currently when an image (or, presumably, video) is marked as sensitive, the user can click on the content in order to reveal it. the image/video cannot be hidden once it's revealed, except by refreshing the page. i think it should be possible to toggle hiding and revealing the content, possibly with a button in the corner of the image/video.

we could also go further and allow the same mechanism to hide content that has *not* been marked as sensitive.

**Comment by deckycoss** [comment]
one thing to consider for anyone who might implement this is how to have the hide state of the content persist between sessions. while content marked as sensitive is always hidden upon refreshing the page, keeping content _not_ marked as sensitive hidden after refreshing the page would require some back-end work.

**Comment by marrus-sh** [comment]
just adding that, if doing back-end sensitive content work is deemed worthwhile, it might also be nice to allow users to mark other *users* as sensitive (for personal display), letting people use "hide media content from this user" an alternative to outright blocking. not a priority, but it's an option to consider.
