### ISSUE TITLE
Add #Spoiler to Hide Posts Containing Spoilers

### ISSUE THREAD

**Issue by ImSeth** [tootsuite/mastodon#3372]
In addition to the #NSFW hashtag that hides potentially objectionable content, it would be great if there was a #Spoiler hashtag that could automatically hide posts that contain spoilers for recent movies, books, etc. This could help cut down on the frustration experienced by social media users when they find out the ending of a movie they haven't seen yet. Content creators would also be freed to post spoilers, knowing they won't annoy anyone by doing so.

**Comment by raingloom** [comment]
What's the problem with simply adding it to the CW?

Spoiler blocks - the kind seen on many forums - seem to make more sense, but since toots are not very long anyway, it's easier to just hide it with a CW.

**Comment by Gargron** [comment]
Have you seen the content warning function? That's a spoiler warning too.
