### ISSUE TITLE
Suggest a working configuration for nginx + X-Accel-Mapping

### ISSUE THREAD

**Issue by dereckson** [tootsuite/mastodon#3389]
Rails allow to directly serve files through the web server, to speed up the process.

To do that, there is basically two options:

- directly use a try_files directive and don't invoke rails at all
- invoke rails but then, rails can invoke back nginx

In such case, you need the application environment and the web server configured together, see for example #3221 for some context.

We should provide instruction for this kind of setup.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
>directly use a try_files directive and don't invoke rails at all

This is recommended in the production guide!

>invoke rails but then, rails can invoke back nginx

I have never used this, and it's inherently less performant than doing it through nginx directly. If you want to submit to documentation on this, feel free to! https://github.com/tootsuite/documentation
