### ISSUE TITLE
upgrade instructions for docker in v1.4.1 unclear on user

### ISSUE THREAD

**Issue by ian-kelling** [tootsuite/mastodon#3401]
Upgrade instructions say

"Existing installations will require you to change directory ownership of the uploads volume to a different UID/GID: something like `sudo chown -R 991:991 public/system` (the default UID/GID of the new in-Docker user is 991/991)"

I'm on debian jessie, using the latest stable docker-ce package directly from docker's repository, as docker recommends. I have no 991 user on my system. grep docker /etc/passwd shows nothing. I google docker non-root user, I get a bunch of things that seem unrelated to this. So, do I need to create the user or what?

* * * *

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mpatton125** [comment]
No you don't need to create a new user on the host.  The public/system directory just needs to be owned by UID 991 GID 991.

**Comment by ian-kelling** [comment]
Ash, uid namespace thing. I see.
