### ISSUE TITLE
lots of sidekiq tasks failing with HTTP::TimeoutError in SubscribeWorker

### ISSUE THREAD

**Issue by Chronister** [tootsuite/mastodon#3408]
~Since upgrading cybrespace to 1.4.1 a few hours ago, I've accumulated 690 retries and 46 dead tasks in the Sidekiq panel, most of which are failing with HTTP::TimeoutError in Pubsubhubbub::SubscribeWorker; this manifests on the instance as posts from other instances failing to show up, particularly noticeable if someone replies to a thread. In the admin panel, the users whose posts fail to appear all show as not having a PubSubHubbub subscription, despite being people who I (the logged in admin) follow (not to mention others on my instance).~

~I don't know enough about the codebase to speculate at underlying causes so I'm only able to report on the symptoms; hopefully someone who's familiar with it can figure out what's going on here. I can try to provide more information if more is needed.~

Looking at the job history it seems that the Sidekiq tasks that are failing were all created well before the 1.4 upgrade and have gone through a dozen or more retries; I'm no longer sure that the problems are related to the upgrade.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Chronister** [comment]
Not sure this is a current issue. Closing for now.

**Comment by ykzts** [comment]
Is there any possibility that other instances could not connect due to upgrade?

**Comment by nightpool** [comment]
It looks like we've had an increase in over 2,000 failed jobs since yesterday, which seems pretty bad but not *totally* out of the ordinary?

![image](https://cloud.githubusercontent.com/assets/233815/26562083/478f3832-4491-11e7-9ba7-bf5f828e3c15.png)

**Comment by wolfteeth** [comment]
I'm seeing something similar. Only really noticed it post-update but it probably started sooner. There are a ton of tasks in the retry queue, all SubscribeWorker.

I see these two errors:

- ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use
- HTTP::TimeoutError: execution expired

Perhaps related, in PubSubHubbub I see a bunch of subscriptions lit up in red, i.e. they expired. I don't actually know if this is a problem - are these other instances' subscriptions to us? Or are these our subscriptions to people we're following?

**Comment by nemobis** [comment]
Timeout issues continue at https://github.com/mastodon/mastodon/issues/8364

**Comment by Gargron** [comment]
Timeout issues will exist as long as there is a network.

**Comment by nemobis** [comment]
Il 19/04/22 14:20, Eugen Rochko ha scritto:
> Timeout issues will exist as long as there is a network.

No doubt. Personally I'm just interested in reducing the repeat 
offenders (specific domains which timeout all the time and get retried 
endlessly).

**Comment by Gargron** [comment]
They do not get retried endlessly. 7 days of failures stops future delivery attempts.

**Comment by nemobis** [comment]
Il 19/04/22 15:52, Eugen Rochko ha scritto:
> They do not get retried endlessly. 7 days of failures stops future delivery attempts.

Yes but that's for delivery attempts, not for processing of received 
updates, right? Will post an example on the other ticket.
