### ISSUE TITLE
[Question] Node Js upgrade

### ISSUE THREAD

**Issue by matunixe** [tootsuite/mastodon#3409]
Hey folks,

To upgrade Mastodon to the last stable release I need to upgrade Node Js from v4 to v6 as well. I'm like a beginner with this hipsters technologies, if somebody want to help I would be forever grateful. 🙏

My server is running on Debien 8 Jessie, Node Js is installed with the official repository: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

Should I just bump my `/etc/apt/source.list.d/nodejs.list` to the v7 version and do an `apt update && apt upgrade`, or there is another upgrade step directly related to Mastodon itself?

Thanks in advance!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by DJSundog** [comment]
> Should I just bump my /etc/apt/source.list.d/nodejs.list to the v7 version and do an apt update && apt upgrade

This is what I did on my Debian 8 Mastodon server and I did not experience any issues.

**Comment by saper** [comment]
You need to rebuild all the binary modules which are installed, since the Node API changes from release. You will run with issues with https://github.com/sass/node-sass for example. I very often just wipe the `node_modules` on a major node upgrade and make sure there is a clean re-install.

**Comment by matunixe** [comment]
Thanks everyone for your advices. It worked flawlessly!

**Comment by baskinsy** [comment]
> You need to rebuild all the binary modules which are installed, since the Node API changes from release. You will run with issues with https://github.com/sass/node-sass for example. I very often just wipe the `node_modules` on a major node upgrade and make sure there is a clean re-install.

How do you do that after upgrading nodejs from v18 to v20. I am preparing my instance for Mastodon v4.4. and want to upgrade nodejs before that. Does the running Mastodon v4.3.9 needs something additional after upgrading nodejs packages? Have searched the documentation and git issues but haven't found something certain.
