### ISSUE TITLE
Failed to build gem native extension.

### ISSUE THREAD

**Issue by Letiteuf55** [tootsuite/mastodon#3417]
Hi,
when updating mastodon, after a bundle install command, i have this error : `An error occurred while installing cld3 (3.1.2), and Bundler cannot continue.`

How can i get this ?
My instance is down :(

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Letiteuf55** [comment]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/cld3-3.1.2/ext/cld3
/home/mastodon/.rbenv/versions/2.4.1/bin/ruby -r ./siteconf20170529-1151-1z08pfr.rb extconf.rb
Failed to locate protobuf
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/mastodon/.rbenv/versions/2.4.1/bin/$(RUBY_BASE_NAME)
	--with-protobuf-config
	--without-protobuf-config
	--with-pkg-config
	--without-pkg-config

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/mastodon/live/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0-static/cld3-3.1.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/cld3-3.1.2 for inspection.
Results logged to /home/mastodon/live/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0-static/cld3-3.1.2/gem_make.out

An error occurred while installing cld3 (3.1.2), and Bundler cannot continue.
Make sure that `gem install cld3 -v '3.1.2'` succeeds before bundling.

**Comment by Gargron** [comment]
>Three additional system packages are required: `pkg-config libprotobuf-dev protobuf-compiler`

**Comment by Letiteuf55** [comment]
let me test with those packages

**Comment by Letiteuf55** [comment]
it's not easy for newbies to find how install those package....

**Comment by Letiteuf55** [comment]
ok done, lets try mastodon update

**Comment by Letiteuf55** [comment]
- This release switches the minimum supported Node.js version from 4 to 6
- Three additional system packages are required: pkg-config libprotobuf-dev protobuf-compiler

I just need to read the guidelines... thanks !
