### ISSUE TITLE
Let other sites know my preferred identity ("global cookie")

### ISSUE THREAD

**Issue by jdmansour** [tootsuite/mastodon#3420]
As you know, some functions like following and interacting with remote accounts are a bit akward in the fediverse. The reason is, if I have an account on one site and visit a remote site, the remote site has no way of knowing my identity.

I would want to set a "global cookie" upon login. Of course that is not possible in the web (and if it was, it wouldn't make sense, as every website could set that cookie).

I propose somebody set up a master domain, on which we set that global cookie. The master cookie service would present itself as an app to Mastodon, and once a user authorizes it, it would set the cookie. Javascript in other Mastodon instances could read out that cookie, and know that I am logged somewhere else.

**This would be entirely opt-in, of course.** I understand there are some privacy issues, not everybody will want every site on the planet to be able to see their fediverse ID. We could restict it such that you'd have to interact once with a site, or authorize the global server to send the magic cookie. Or, there could be a whitelist.

The following features would be enabled by this:
- Follow somebody just by clicking follow, without entering your ID
- Let the remote site see that you are a returning visitor. E.g. if you already participated in a [poll](https://github.com/tootsuite/mastodon/issues/1629), directly show the results.
- Add an [interface to interact with toots on other instances](https://github.com/tootsuite/mastodon/issues/1240)
- See who has visited your profile (again, some people will like that, some people will definitely not, that's OK because this is opt-in)
- In general, let a site know I have a prefered fediverse ID
- Tracking (as a mis-feature we should be aware of)

I'm not sure about the technical details yet. I think you could implement this via XMLHttpRequest to the central server, with CORS headers set, returning some JSON. Or just a remotely includable javascript file. Or maybe there is a more clever solution. I think it doesn't even strictly need support from the server that I have the account on (since the global service presents itself as an app), but it needs support from the remote server that will read the cookie.

Alternatives:
- To make remote following easier, there is the option of [registering a URL scheme handler](https://github.com/tootsuite/mastodon/issues/2291).
- One simple alternative is to set a cookie on the _remote instance_ once I've added somebody from there. Then, in future, it can have my ID already filled out, and can show "quick reply" buttons.
- If you just want closer integration with a handful of sites, one could add the magic cookie + JS directly to mastodon, and have the instances include each other's magic JS (instead of the global JS). Of course this doesn't scale.

**Comment by Kimik0** [comment]
A quicker way to follow a remote account is to paste the account's url into your local instance's search bar. It'll look up the user and then you can follow them with one click.

In any case, with all the restrictions necessary, it would be less of a hassle to just type your user name and instance.

**Comment by akihikodaki** [comment]
Browser extension is yet another alternative; A Web site can ask the extension for Mastodon identity, and then the extension asks the user whether it is fine to tell his identity to the site.

**Comment by zotlabs** [comment]
You should at least look at the Hubzilla implementation of this feature as it is invisible to end users and just works. That's based on a secure cookie "transfer/regenerate" between cooperating sites. Identity is passed as url parameters and this policy can be selectively blocked using plugins. It provides all the advantages you're looking for and has been in production for around five years and well debugged. The one place we got into trouble was dealing with the EFF and their Privacy Badger since this generates third-party cookies. You must honour DNT and provide a certification document on your site or the EFF is going to block you (I find the EFF blocking free and open web services quite disturbing, but they have simply never encountered somebody using third-party cookies for good rather than evil).

**Comment by Gargron** [comment]
We're going to try the #2291 way first. Global cookies are dubious, and would definitely fall under the EU cookie law, requiring various opt in mechanisms that would be annoying to implement.
