### ISSUE TITLE
ActivityPub: outbox pages contain unordered sets of activities

### ISSUE THREAD

**Issue by puckipedia** [tootsuite/mastodon#3438]
According to [the spec](https://www.w3.org/TR/activitystreams-core/#collections), `items` is a set, while `orderedItems` is an (ordered) list. This is due to the JSON-LD serialization of AS2: JSON-LD defaults to unordered sets. When using `list`, some clients may not be able to show the Activities in the right order. To fix this, the OrderedCollectionPages should contain `orderedItems` instead of `items`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by evanminto** [comment]
I'm already working on fixing this one. I made some mistakes in implementing the spec.

**Comment by Gargron** [comment]
Gonna link this up with #3844
