### ISSUE TITLE
Federated whitelist

### ISSUE THREAD

**Issue by triplefox** [tootsuite/mastodon#344]
The skeleton of whitelisting exists through the mechanics of following and the Home view, plus the existing toggles for following as a filter, but manual control over following forces all the effort onto the individual to be proactive and engage others.

A way to supplement this strategy is to allow some form of sharing of whitelists, and further, to offer a default whitelisting strategy of the 2nd degree follow - your follows plus a (periodically updated) list of your follows' follows, minus any blocking/muting you manually set(including the possibility of following without subscribing to the whitelist). This "whitelist view" would act as an alternative to the existing public timeline, and naturally self-regulate its velocity to some multiple of followed accounts. It offers a way for users who want a mostly-private experience to explore relatively safely.

This is in many ways a counterpart to the ideas of #231 and #236 but provides yet another angle for realizing their goals.

**Comment by marrus-sh** [comment]
I'm imagining a toggle in settings:

```
Show this in my public timeline:
    [ ]  Everyone
    [ ]  Second-order follows
    [ ]  Custom: [ whitelist.txt ]
```

Until/unless the "column 3" layout improves I would imagine just replacing the public timeline would be the best way of handling this.

**Comment by haniawni** [comment]
This would only be filtering *incoming* toots, not limiting who can view the user's toots, or am I mistaken?

**Comment by triplefox** [comment]
Correct, it has no impact on others viewing a toot. Whitelisting for privacy isn't part of this issue until we have an understanding of what privacy features are going to be available more generally(e.g. if we have instance-local private accounts, whitelisting might be used to influence visibility there).

**Comment by hoodiek** [comment]
i feel this can be closed, as #423 implements this exact idea, yes? and has people working on it in that thread.

**Comment by deckycoss** [comment]
i think this feels different; i filed #423 to be specifically and only about a tool for users to block/whitelist domains. this issue seems, if i understand correctly, to be about whitelisting both accounts *and* domains, and being able to share whitelists with other users.

**Comment by Gargron** [comment]
The public timelines are not personalized. By definition, they are the opposite of the home timelines, which are curated by you. They are the firehose, a look into the database, a direct SQL query, unlike the fan-out-on-write home. We've gone to great lengths to add some forms of filtering to them, in terms of weeding out blocked/muted users, blocked domains and languages. However, 2nd degree follows is too much. It's just not computationally possible to do this and still have any performance, and in any case it feels thematically counter to the idea of having a firehose to look at.
