### ISSUE TITLE
Home's style is broken

### ISSUE THREAD

**Issue by mikoim** [tootsuite/mastodon#3440]
I found the issue that breaks UI in Home since v1.4rc4. According to `git bisect`, bc39ad37c4b6372c98177f8c4fc525391c49f702 caused this problem. 

## 

- `rm -fr /foo/bar/public/{assets,packs}`
- `docker-compose build --no-cache`
- `docker-compose run --rm web rake assets:precompile`
- `docker-compose up -d`

## workaround

`git revert bc39ad37c4b6372c98177f8c4fc525391c49f702` and rebuild assets

### [Affected] Firefox 53.0.2
![](http://i.imgur.com/N0Kt1de.png)

### [Affected] Google Chrome 58.0.3029.110
Sorry, a screenshot is missing. mostly same as Firefox.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
cc @nolanlawson

**Comment by ykzts** [comment]
FYR: In my instance there was no problem.

**Comment by Naouak** [comment]
It feels like a corrupted css file.

**Comment by mikoim** [comment]
I tested with the latest master branch, and it seems to works fine. (why did it not work...)
close #3440

**Comment by mikenuko** [comment]
Sorry, but I am now facing exactly this problem. I recompiled either with the master branch or the release branch but both also yielding a broken style...
