### ISSUE TITLE
ActivityPub: Boosts of federated posts are wrong

### ISSUE THREAD

**Issue by puckipedia** [tootsuite/mastodon#3458]
When an `Announce` activity in someone's outbox points to a `Create` activity from another instance, the `id` values still use the internal server. This means that external servers that use ActivityPub to federate with Mastodon will see duplicate Activities and Posts. The `id` value should point to the single source for the activity, so towards the source server, not the current instance's local representation of the post.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Gonna link this up with #3844
