### ISSUE TITLE
Mastodon does not work on QuteBrowser

### ISSUE THREAD

**Issue by Blaveloper** [tootsuite/mastodon#3483]
I've been visiting mstdn.jp through Chromium for a while now, but now I'm preparing my switch to QuteBrowser.
But the fact Mastodon doesn't seem to work on QuteBrowser at all hinders it.

Screenshot, which shows the same site loaded on both browsers:

[http://some.very.questionable.website/mstdnworksanddoesnotworkatthesametime.png](http://some.very.questionable.website/mstdnworksanddoesnotworkatthesametime.png)

**Comment by The-Compiler** [comment]
qutebrowser developer here - I've never investigated why it fails, but it works just fine if you use QtWebKit-NG (`qt5-webkit-ng` on Manjaro, note that private browsing won't work), or QtWebEngine (based on Chromium, `qt5-webengine`, start with `--backend webengine`).

**Comment by Blaveloper** [comment]
Thanks, your solution to install at5-webkit-ng worked for me! (ﾉ´∀｀*)

**Comment by dekksh** [comment]
Can confirm the webkit way doesn't work on anything other than mastadon.brussels front page, going to login page results in a blank screen. Running backend webengine did for a  while but the renderer process crashes. I've run :report and sent it in if that'll help.

**Comment by sorin-davidoi** [comment]
@Blaveloper I guess this can be closed?

**Comment by Blaveloper** [comment]
Yes, sure thing.
