### ISSUE TITLE
[Feature request] Account creation without e-mail address (like on jabber instances)

### ISSUE THREAD

**Issue by Wikinaut** [tootsuite/mastodon#3484]
I would prefer a revised method of creating accounts. If you register a new account on e.g. jabber.ccc.de or jabber.de, it is not required to enter an e-mail address.

I suggest to modify the mastodon code so that this requirement (e-mail address) is dropped and no longer required.

**Comment by moshpirit** [comment]
What about SPAM? there's a lot of SPAM bots on Jabber trying to sell things and it's very annoying. I wonder how do you feel about this issue

**Comment by Gargron** [comment]
Requiring a verified e-mail address is an important step for weeding out spam/automated accounts, and it makes creating sockpuppets slightly more tedious. You might be interested in #942 and related issues, i.e. sourcing user accounts from a different database. However, for local sign ups, e-mail will remain a required component.

**Comment by hakaba-hitoyo** [comment]
Too late. This issue was closed. But I suppose that collecting e-mail addresses is serious privacy violation, especially if the administrator of instance is just a hobby hacker. Sign up without mail is good choice to some instances.

**Comment by Wikinaut** [comment]
@hakaba-hitoyo This ("privacy issue") is why I filed the issue.

**Comment by hakaba-hitoyo** [comment]
Hey, all we need have already been in the configuration: just rewrite one line in device.rb and restart the instance.
https://github.com/theboss/mastodon/commit/36d484d168653e25d857cb5b2507d3fdb4b4f9d8

**Comment by hakaba-hitoyo** [comment]
config.allow_unconfirmed_access_for should be 99.years by default?

**Comment by tusooa** [comment]
Whether to allow users register without email should be determined by the instance admins, not hardcoded in the software.

Not having a way to disable email requirement is the biggest reason why I no longer use Mastodon.

**Comment by Gargron** [comment]
It is up for us who write software to decide what the software does, and it is up to you to decide if you want to use it. E-mail is the centerpiece of authentication in Mastodon from day 1 and requiring e-mail confirmation is an important feature that benefits the fediverse, as any server that does not require it would become a vector for spam for everyone else in the network (see the 10minutepleroma incident). So yes, it sounds like Mastodon is not for you.
