### ISSUE TITLE
v1.4 requires write access to the code directory

### ISSUE THREAD

**Issue by ProgVal** [tootsuite/mastodon#3486]
Hi,

Version 1.4 requires write access to the code directory to work:

```
May 31 20:33:51 ruby-preprod systemd[1]: Started mastodon-streaming.
May 31 20:33:51 ruby-preprod npm[29402]: > mastodon@ start /home/mastodon-code/mastodon
May 31 20:33:51 ruby-preprod npm[29402]: > rimraf ./tmp/streaming && babel ./streaming/index.js --out-dir ./tmp && node ./tmp/streaming/index.js
May 31 20:33:52 ruby-preprod npm[29402]: Error: EACCES: permission denied, mkdir '/home/mastodon-code/mastodon/tmp/streaming'
May 31 20:33:52 ruby-preprod npm[29402]:     at Error (native)
May 31 20:33:52 ruby-preprod npm[29402]:     at Object.fs.mkdirSync (fs.js:923:18)
May 31 20:33:52 ruby-preprod npm[29402]:     at sync (/home/mastodon-code/mastodon/node_modules/mkdirp/index.js:71:13)
May 31 20:33:52 ruby-preprod npm[29402]:     at outputFileSync (/home/mastodon-code/mastodon/node_modules/output-file-sync/index.js:44:24)
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Make the tmp directory writeable

This is not a regression because we've never said that it should be read-only, in fact it already needed to be writeable for local image uploads to work

**Comment by ProgVal** [comment]
> Make the tmp directory writeable

I could, but I prefer to keep code and data apart.

> This is not a regression because we've never said that it should be read-only, in fact it already needed to be writeable for local image uploads to work

Not since #778.


(And you're supposed to be on break today. Don't overwork yourself, it's not an urgent issue :) )
