### ISSUE TITLE
"We're sorry, but something went wrong." always show in v1.4 mastodon instance

### ISSUE THREAD

**Issue by darkcl** [tootsuite/mastodon#3504]
I went to mastodon.social and mastodon.technology in Mobile Safari, Mac Safari, Mac Chrome, they all redirected to the same "We're sorry, but something went wrong." page.

I have tried clear cookies and restart browser.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by poga** [comment]
Might be related to https://github.com/tootsuite/mastodon/issues/3452. 

Since all instances on v1.4.1 are missing `zh-TW` locale file, all users using `zh-TW` will encounter a 500 error.

**Comment by darkcl** [comment]
Oh....I set the default language in Chrome and it can show the right content again......

**Comment by Gargron** [comment]
This has been resolved. Sorry for the issue.
