### ISSUE TITLE
Feeds broken in latest master

### ISSUE THREAD

**Issue by Komic** [tootsuite/mastodon#3505]
Hi!
Just updated to the latest master on my personal instance, feeds seem to be broken. When refreshing, the feed is empty, & a toast notification shows a 500 error. New toots are however showing up.

`journalctl -fx` shows this:

```
bundle[14863]: [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx] NameError (uninitialized constant ActiveModel::Type::Text):
bundle[14863]: [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx] app/controllers/application_controller.rb:76:in `cache_collection'
bundle[14863]: [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx] app/controllers/api/v1/timelines/public_controller.rb:22:in `cached_public_statuses'
bundle[14863]: [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx] app/controllers/api/v1/timelines/public_controller.rb:16:in `load_statuses'
bundle[14863]: [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx] app/controllers/api/v1/timelines/public_controller.rb:9:in `show'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Komic** [comment]
Alright what the hell, I left it sit ten minutes and it works again. I'll leave this open just in case~

**Comment by clworld** [comment]
ActiveModel stored in Rails.cache incompatible between Rails 5.0(1.4.1) and Rails 5.1(master).
So, 500 errors occurs until all Rails 5.0 cache expired.
Update all Ruby service (puma and sidekiq) and run 'Rails.cache.clear' in rails console (or wait 10 minutes) fixes problem.

**Comment by mjankowski** [comment]
> Update all Ruby service (puma and sidekiq) and run 'Rails.cache.clear' in rails console (or wait 10 minutes) fixes problem.

This is a good doc to add for upgrade notes...

**Comment by Komic** [comment]
Makes sense, thanks @clworld.
