### ISSUE TITLE
zh-* i18n: change from 赞/喜歡/喜愛 (like) to 收藏 (fav)

### ISSUE THREAD

**Issue by Artoria2e5** [tootsuite/mastodon#3511]
All of current zh translations seem to have taken bird-site‘s heartify campaign which reinterpreted "fav" as "like" as The Right Thing. As Mastodon's fav is really a private collection of favorites per https://github.com/tootsuite/mastodon/issues/2117#issuecomment-295031744, these translations should be reverted to the interpretation correct for Mastodon: "add to favorite". (Yes, you are not supposed to be able to list what someone has fav'ed.)

Pinging @yookoala for zh-HK, @shouko for zh-TW, @KenOokamiHoro and @Artoria2e5 (my very lazy self) for zh-CN. ~~To be frank I was just getting annoyed at how people are using the yellow star, and then realized that we have all gotten that translation wrong.~~

* Yes, this happens on master and all current versions with a Chinese translation for favorite.
* ~~Yes, this is part of some de-birdification agenda that follows the "嘟文" change.~~

**Comment by KenOokamiHoro** [comment]
😂 , I think it is ok. And will here add a "like" button ?

**Comment by Artoria2e5** [comment]
Whether you like something is irrelevant. If you want to show a toot to someone else, boost it.

**Comment by AstroProfundis** [comment]
IMO "like" is more public that refers to "this is good and I want to vote for it", "fav" is more like "I want to mark this thing for future reference". So considering the current behavior of this button, I'd preffer "fav" over "like".

btw, I do am interested in some "like" or sort of "list" feature that a user can make collections of toots and share to others.

**Comment by yookoala** [comment]
I think the current translation helps users from Twitter world to transit to Mastodon. That's why I didn't translate it literally. I can change the translation.

**Comment by Artoria2e5** [comment]
Twitter used to use "fav" + a yellow star for that button currently known as "like" + red heart. The transition argument applys to "like" as well.
