### ISSUE TITLE
Startup problem when using chrome "Add to desktop" feature

### ISSUE THREAD

**Issue by thomaslule** [tootsuite/mastodon#3512]
Hey all,

I use Mastodon with chrome "add to desktop" feature that opens a website in its own window as if it were a native application.

Each time I open Mastodon this way the UI is broken:
* the loading bar doesn't go all the way
* the third column has the same title as the first column and is empty
* some links don't work, the behaviour is globally broken: for example if I click on an image nothing happens, then I click a toot and the image finally appears but I can't close it

If I find a working link and refresh the page, it repairs everything.

**Context**

I use the latest chrome and this bug happens only when I open the site as an app, everything works when I go to the site the usual way, in a browser tab. I'm 80% sure this problem appeared with the 1.4 version.

**I tried to investigate a little bit:**

The javascript console gives a "Uncaught Error: Minified exception occurred".

Another user told me they experienced the very same bug using a mastodon Electron app. Another one had it too and they access the site using a bookmark to `/web/timelines/home`.

When using "add to desktop", I land on this url too. It looks like the problem comes from that.

I tried re-creating the app shortcut from different urls but it didn't fix the problem: I always land on this buggy `/web/timelines/home` url.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by zcdunn** [comment]
"the third column has the same title as the first column and is empty"
I'm pretty sure this is because the manifest.json declares the start_url as /web/timelines/home so the third column, the context column, starts on the home timeline. 

This doesn't explain why it's empty. I think that is related to the JavaScript errors.

**Comment by thomaslule** [comment]
This problem seems to have disappeared with last update. We still land at `/web/timelines/home` but it's not buggy anymore.
