### ISSUE TITLE
API: accessing "(un)mute_boosts" endpoints gives HTTP 422 and no json error

### ISSUE THREAD

**Issue by Kimik0** [tootsuite/mastodon#3513]
Trying to access either of the `accounts/:id/(un)mute_boosts` endpoints without `follow` scope authorization gives a HTTP 422 "Unprocessable Entity" status header and an empty reply. Expected behavior would be a HTTP 403 "Forbidden" status header and a proper json `{"error":"This action is outside the authorized scopes"}`.
* * * *
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
I am afraid the documentation for this has been merged before the feature was approved: #3271
