### ISSUE TITLE
API: _querying_ endpoints should not require "follow" scope authorization

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#3514]
Accessing the `blocks`, `domain_blocks`, `follow_requests` or `mutes` endpoints with a HTTP GET query without `follow` scope authorization results in a "This action is outside the authorized scopes" error.

While the `follow_requests` endpoint wouldn't be very useful to a client with only `read` or `write` scope authorization, the other three are a much quicker way for an app to check what toots and users it should show than going through the `accounts/relationships` endpoint every time a new one shows up.

Since merely querying these endpoints doesn't change anything about the account or its relationships in any case, I'd expect `read` authorization to be enough to retrieve the information.

If users having ginormous lists of blocks and mutes is a concern (which might make the `accounts/relationships` endpoint more efficient for casual use), perhaps it would be best to provide the total numbers of blocks, mutes, and domain_blocks through some endpoint (for example adding them to the information returned by `accounts/verify_credentials`). The app can then make an informed decision on how to build its internal cache.
* * * *
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
New OAuth scopes
