### ISSUE TITLE
Redirect to unexpected page

### ISSUE THREAD

**Issue by kanata2** [tootsuite/mastodon#3515]
In some cases, when you click "Back" button rendered by "column_back_button.js", it redirect to unexpected URL such as another web page, your startup page (which you saw just before).
I think that it would be better to redirect to timeline or getting-started page instead of the previous page in those cases.

---
Steps to reproduce bug:

- click on a toot or user.
- copy URL (like ~/web/accounts/123456, ~/web/statuses/123456)
- open the new tab and copy this URL
- in the user page or toot page, click "Back" button

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
  - this is probably one case of this issue: https://github.com/tootsuite/mastodon/issues/2329

**Comment by MightyPork** [comment]
Running into this bug daily.

I have a bookmarked layout with the local pinned and federated in the last column.

When I want to see the start page, I automatically go for the back button, but that closes mastodon and opens my g-mail or whatever I had open before. Quite frustrating tbh.

**Comment by Gargron** [comment]
Duplicate of #946
