### ISSUE TITLE
Access is made many times by toot including url

### ISSUE THREAD

**Issue by osapon** [tootsuite/mastodon#3518]
When toot including URL, servers does three accesses.
Can it be done just once?

https://gyazo.com/2f841d0e4a3f4273159a7726b0849e07
This screenshot is access when one toot is posted in Unlisted.
I have been accessed three times, HEAD, GET, GET, but I hope to do with a single GET.
If the first HEAD is to check the embedded cache, can it be done only once in the last two GETs?

Mastodon version 1.4.1

**Comment by clworld** [comment]
It's performed by FetchLinkCardService.
1st HEAD request is for checking URL is HTML or not.
2nd GET request is for oEmbed.
3rd GET request is for OpenGraph and scraping.
I think HEAD & GET once is necessary.
Some works are needed for reducing GET request.
Merging app/lib/provider_discovery.rb and FetchLinkCardService#attempt_opengraph will reduce GET request I think.

**Comment by Gargron** [comment]
We could also use redis to cache responses for a while. The only problem to solve with that is that redis by default does not act like a cache that removes least recently used items - it contains plenty of data that we don't want to evict. But we wouldn't want to fill it up with caches of HTML pages, either.

**Comment by osapon** [comment]
In version 2.1.0, I confirmed that it decreased to 2 accesses for HEAD and GET.
I close this issue.
Thank you for working!
