### ISSUE TITLE
Toot box not compatible with Grammarly, typo fixes reverted on submit

### ISSUE THREAD

**Issue by MightyPork** [tootsuite/mastodon#3535]
(1.4.1 and also all previous for the last two months at least, on .xyz with vanilla styles etc)

If you fix typos in your toot using Grammarly or some other spell checking extension, and then don't make a manual change to the text (eg. typing a period), upon submitting, the changes are undone.

After pressing the toot button, you can also briefly see the changes revert in the tootbox itself.

Here it's illustrated with some screenshots:

Clumsy tooter makes typos
![screenshot_20170603_163719](https://cloud.githubusercontent.com/assets/2041118/26754437/2e1bf7b2-487b-11e7-8ca0-5328988997d2.png)

Fixes them with Grammarly
![screenshot_20170603_163728](https://cloud.githubusercontent.com/assets/2041118/26754440/3d8e470e-487b-11e7-92f4-49c2363ba58b.png)

All good, let's toot!
![screenshot_20170603_163738](https://cloud.githubusercontent.com/assets/2041118/26754444/4a5e6b6c-487b-11e7-88ea-8ec3c5f4d50c.png)

Oh no!
![screenshot_20170603_163745](https://cloud.githubusercontent.com/assets/2041118/26754449/51fb1b0e-487b-11e7-98a2-d21b8dd55b19.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a

**Comment by unarist** [comment]
React handles text changing in the textarea by keyboards events. Grammarly changes text, but doesn't fire any events. So we can't handle those changes. This may be fixed by getting text on just before submitting.

For a workaround, you can avoid this by type anything (and delete if you want) after Grammarly fixes.

**Comment by sorin-davidoi** [comment]
@MightyPork Tried to take a look at this, but could not get Grammarly to check the `textarea` (latest Chrome and Firefox, latest master and latest stable version). Did you do anything special to make it work?

**Comment by MightyPork** [comment]
@sorin-davidoi The Grammarly extension I use is the latest from Chrome Web Store, 14.766.968, in Google Chrome 58.0.3029.110. It worked without anything special on my end, I just installed it.

I have a "premium" account on Grammarly, just in case that makes a difference.

**Comment by sorin-davidoi** [comment]
@MightyPork Hm, very strange. Grammarly only appears to work in the "mobile view" (when only the compose column is visible). Can you confirm this?

**Comment by MightyPork** [comment]
Know what, that's really weird.

I have this userstyle to make the columns stretch, and if I turn it off, Grammarly stops working.

```css
@media (min-width: 1000px) {
        .columns-area>div {
            width: 25%;
        }
        .columns-area>div>.column,
        .columns-area>div>.mastodon-column-container>.column {
            width: 100%;
        }
}
```
(Talking of which, why don't they stretch by default? But that's surely an open issue somewhere else)

**Comment by sorin-davidoi** [comment]
I guess that is a Grammarly bug? Regarding stretching, on master right the columns are dynamic (you can have Compose, Home, Notification, Local, Federated, Getting Started...).

**Comment by MightyPork** [comment]
Yup, appears to be a Grammarly bug of some sort (or rather React confusing it). If you toggle 'flex: 0 0 auto;' on the .column class in dev tools, it catches on.
