### ISSUE TITLE
Open content in the same column as it was clicked in

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#355]
this is a difficult topic to dip into, as opinion can be involved, but i personally have some very notable workflow issues related to UI failures, and i would like to address them here:

the order of columns left to right makes interacting with posts on smaller screens horizontally much more difficult. i tend to (in order to keep up with all the things i do) have a relatively small amount of horizontal space alotted to each window. i do NOT want to have to go full screen to interact with Mastodon effectively, and i've ended up trying to resolve these issues with CSS stylish mods, zooming out, and tampermonkey, mostly unsuccessfully.

the issue is in regards to the two different columns you use to interact with things, namely the very left most column, and the very rightmost.

if i have only three of the columns visible, which is the most i can get out of my screen space, i will be dragged back and forth over the two middle columns just to interact with a toot: viewing the context will throw me to the right, trying to reply will throw me to the left, etc etc.

this is frankly rather disorienting for the user! it does not make sense, either. why can't i view the context of a toot in the same column i chose to look at it in! this would be the most effective way to resolve the context half, but the other half would be to allow inline-replying to a toot when you are in the context view, heck, I would personally advise removing the drawer/left most column entirely except for a button that extends it to open it, at the left add a "compose toot" button and an rightmost column options button to see the search, public timeline and recently viewed hashtags, etc

this is a threefold set of changes i am suggesting to GREATLY improve everyone's workflow, in sum up, they are as follows:

view context of toots in the same column you click on them or the context button in
reply to toots in column, with an option to send the toot to the leftmost column for more options etc
and finally: make the drawer collapse to the left and seperate the options menu above a toot into it's own menu below the option to expand a toot.

as a bonus suggestion: i think it would be best to make the switch between mobile/single column view and multi column view it's own option in the expanding "options" button in the drawer, and only on mobile browsers should it automatically be it's own column.

thank you for listening

**Comment by Gargron** [comment]
Making the context stuff open in the same column where it was clicked would be ideal, though it would no longer be a case of simply using react-router, and there would be no binding to the address bar (although that's probably not a big loss).

**Comment by hoodiek** [comment]
i would personally view it as a plus to reduce the number of things that show up in the address bar. if you manage to make it so it always says mastodon.social up there that'd probably be a positive, i'd say.

it looks more professional and clean, imo.

anyway thank you for the speedy response! glad to know it's possible/has your eye on it

**Comment by marrus-sh** [comment]
If you do remove address-bar binding, implementing something pertaining to either #309 or #174 would be greatly appreciated imo, as copying the link from the address-bar right now is the only way to quote a toot and still have it show up in timeline view (where others can interact/reply to it)
