### ISSUE TITLE
Foreign keys for account_id references?

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#3550]
Quite some time ago, before Mastodon refreshed infos from webfinger, I instructed another instance's admin to manually remove information on my remote account (that is, delete rows of the “accounts” database with domain = 'mydomain'). We are still unable to communicate now, and I suspect it is actually because of the instructions I have given this admin at the time (I am able to communicate with other instances just fine).

I tried to reproduce this issue and couldn't completely. However, in the process, I manually removed a remote account (which got re-created just fine afterwards), without removing the toots referencing it, leading to runtime errors.

It appears to me that `statuses (account_id)`, `follows (account_id)`, `follows (target_account_id)` etc. should all have a `foreign key` constraint on `accounts (id)`. Is there any reason why that is not the case?

**Comment by Gargron** [comment]
>It appears to me that statuses (account_id), follows (account_id), follows (target_account_id) etc. should all have a foreign key constraint on accounts (id)

I agree!

>Is there any reason why that is not the case?

No good reason! I just didn't expect people to be deleting records through anything but the ActiveRecord `destroy` method, so this wasn't a pressing concern.
