### ISSUE TITLE
Sidekiq log size

### ISSUE THREAD

**Issue by ashfurrow** [tootsuite/mastodon#3565]
Since upgrading to 1.4.1, I'm seeing lots of logging in my Sidekiq docker container, probably as a result of https://github.com/tootsuite/mastodon/issues/3408 . My Sidekiq log has grown to gigabytes of text. I'm okay with the sidekiq failures if those are normal, but I'm at risk of running out of disk space. 

For example, the file `/var/lib/docker/containers/c239604110c5797208ed34ee57d96131f9e5356ea7d67517dec9c83ef5fbbe30/c239604110c5797208ed34ee57d96131f9e5356ea7d67517dec9c83ef5fbbe30-json.log` is nearly 4 gigabytes. I'm looking through the code and it looks like the Sidekiq logging level is set [here](https://github.com/tootsuite/mastodon/blob/defe4f9bc3407cde4d5b1918778b0754ef7f4970/config/environments/production.rb#L92) but is it safe to change that in the [`docker-compose.yml` file](https://github.com/tootsuite/mastodon/blob/defe4f9bc3407cde4d5b1918778b0754ef7f4970/docker-compose.yml#L51)?

<details>
<summary>Log file tail contents</summary>

```json
{"log":"Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/c805176a6e69bfb8492265aab10918bc20170604-120-1wwcr7t[0]' 2\u003e/dev/null\n","stream":"stdout","time":"2017-06-04T16:25:06.893205285Z"}
{"log":"Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/8e9dd97a5f2a5bd9f002a2799f342aff20170604-120-744rg4[0]' 2\u003e/dev/null\n","stream":"stdout","time":"2017-06-04T16:25:06.972059743Z"}
{"log":"[paperclip] saving /media_attachments/files/000/110/533/original/0c13526ebb297e1c.jpg\n","stream":"stdout","time":"2017-06-04T16:25:06.99543834Z"}
{"log":"[paperclip] saving /media_attachments/files/000/110/533/small/0c13526ebb297e1c.jpg\n","stream":"stdout","time":"2017-06-04T16:25:07.804872445Z"}
{"log":"Command :: file -b --mime '/tmp/8d777f385d3dfec8815d20f7496026dc20170604-120-15a3hfw.jpeg'\n","stream":"stdout","time":"2017-06-04T16:25:17.476653554Z"}
{"log":"Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/8d777f385d3dfec8815d20f7496026dc20170604-120-1hfdovc[0]' 2\u003e/dev/null\n","stream":"stdout","time":"2017-06-04T16:25:17.48168588Z"}
{"log":"Command :: identify -format %m '/tmp/8d777f385d3dfec8815d20f7496026dc20170604-120-1hfdovc[0]'\n","stream":"stdout","time":"2017-06-04T16:25:17.509880918Z"}
{"log":"Command :: convert '/tmp/8d777f385d3dfec8815d20f7496026dc20170604-120-1hfdovc[0]' -auto-orient -resize \"x120\" -crop \"120x120+60+0\" +repage -quality 80 -strip '/tmp/d68b3f14a814744077fcc97d6915000420170604-120-wr8803'\n","stream":"stdout","time":"2017-06-04T16:25:17.51869866Z"}
{"log":"Command :: file -b --mime '/tmp/0e4f7ff4b5d41ec05934a832a52754c420170604-120-9oxehr.jpg'\n","stream":"stdout","time":"2017-06-04T16:25:17.567493511Z"}
{"log":"[paperclip] saving /preview_cards/images/000/039/261/original/5137233_3_6555_nba-playgrounds_bb34d940f2b2daebac04768bfe351b94.jpg\n","stream":"stdout","time":"2017-06-04T16:25:17.574074454Z"}
```

</details>

Any quick remedies? I can look into it this week otherwise. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
"Warn" should be the least noisy but still useful logging level (almost nothing actually "warns" so it's basically same as only logging errors) - the log output you give as an example, however, looks like "debug" level and not "warn"! I don't know what's going on there, we need to investigate this

**Comment by ashfurrow** [comment]
Okay, thanks. I'll take a look around and see what I can come up with.

**Comment by ashfurrow** [comment]
Following up on this, I've opened the production Rails console and verified that both `RAILS_ENV` is `production` and `Sidekiq::Logging.logger.level` is `Logger::WARN`. I looked and my `docker-compose.yml` file specified some extra environment variables for logging (I think the defaults used to be different in an earlier version of Mastodon). I'm going to remove those lines, restart, and see if that fixes things.

**Comment by ashfurrow** [comment]
No joy – still got a verbose log level. Hmm.

**Comment by ashfurrow** [comment]
I've tried setting `:verbose: false` in the `config/sidekiq.yml` file but still no joy. I took a look at the Sidekiq source code and didn't see anything related to logging that would jump out at me. I'm surprised no one else has reported this issue, which makes me think it's something specific to my setup. I took a look at the [diff](https://github.com/tootsuite/mastodon/compare/master...ashfurrow:master) between my setup and Mastodon and nothing jumps out at me. I'll keep looking – if anyone has advice, please let me know.

**Comment by ashfurrow** [comment]
Just confirmed this is still happening on 1.4.3. I'll keep looking, if anyone has pointers please let me know. At this case, I might just modify the command to direct the logs to `/dev/null`.

**Comment by alexgleason** [comment]
This might be related, but my instance just shut down after I ran out of disk space. I discovered a log file containing this, posted about every 3 seconds:

```
{"log":"2017-06-24T18:45:33.562Z 1 TID-gqlj6vyd4 ERROR: heartbeat: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.\n","stream":"stdout","time":"2017-06-24T18:45:33.572134679Z"}
```

The file was 12GB. I just did `echo "" > $logfile` for now.

Another one is 1.6 GB. Here's an excerpt from it.

```
{"log":"[a627e520-ace0-438a-902c-d277408a733f]   \u001b[1m\u001b[36mHABTM_Tags Load (3.5ms)\u001b[0m  \u001b[1m\u001b[34mSELECT \"statuses_tags\".* FROM \"statuses_tags\" WHERE \"statuses_tags\".\"status_id\" IN (104997, 104053, 100928, 96432)\u001b[0m\n","stream":"stdout","time":"2017-06-24T18:48:45.167241822Z"}
{"log":"[a627e520-ace0-438a-902c-d277408a733f]   \u001b[1m\u001b[36mMention Load (0.4ms)\u001b[0m  \u001b[1m\u001b[34mSELECT \"mentions\".* FROM \"mentions\" WHERE \"mentions\".\"status_id\" IN (104997, 104053, 100928, 96432)\u001b[0m\n","stream":"stdout","time":"2017-06-24T18:48:45.170492605Z"}
{"log":"[a627e520-ace0-438a-902c-d277408a733f]   \u001b[1m\u001b[36mFollow Load (1.8ms)\u001b[0m  \u001b[1m\u001b[34mSELECT \"follows\".* FROM \"follows\" WHERE \"follows\".\"id\" IN (1811, 1759, 1760, 1762, 104057, 1814, 1763, 1764, 104173, 1768, 1770, 105147, 56856, 1848, 1776)\u001b[0m\n","stream":"stdout","time":"2017-06-24T18:48:45.186270249Z"}
{"log":"[a627e520-ace0-438a-902c-d277408a733f]   \u001b[1m\u001b[36mAccount Load (1.0ms)\u001b[0m  \u001b[1m\u001b[34mSELECT \"accounts\".* FROM \"accounts\" WHERE \"accounts\".\"id\" IN (8342, 8083, 5720, 8682, 8678, 8699, 8770, 8783, 8812)\u001b[0m\n","stream":"stdout","time":"2017-06-24T18:48:45.194794243Z"}
{"log":"[a627e520-ace0-438a-902c-d277408a733f]   \u001b[1m\u001b[36mStatus Load (3.2ms)\u001b[0m  \u001b[1m\u001b[34mSELECT \"statuses\".\"reblog_of_id\" FROM \"statuses\" WHERE (\"statuses\".\"reblog_of_id\" IN (104053, 105148, 104997, 100928, 96432) OR \"statuses\".\"reblog_of_id\" IS NULL) AND \"statuses\".\"account_id\" = 1 ORDER BY id desc\u001b[0m\n","stream":"stdout","time":"2017-06-24T18:48:45.468196882Z"}
{"log":"[a627e520-ace0-438a-902c-d277408a733f]   \u001b[1m\u001b[36mFavourite Load (1.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT \"favourites\".\"status_id\" FROM \"favourites\" WHERE (\"favourites\".\"status_id\" IN (104053, 105148, 104997, 100928, 96432) OR \"favourites\".\"status_id\" IS NULL) AND \"favourites\".\"account_id\" = 1\u001b[0m\n","stream":"stdout","time":"2017-06-24T18:48:45.491325392Z"}
{"log":"[a627e520-ace0-438a-902c-d277408a733f]   \u001b[1m\u001b[36mDoorkeeper::Application Load (1.4ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  \"oauth_applications\".* FROM \"oauth_applications\" WHERE \"oauth_applications\".\"id\" = $1 LIMIT $2\u001b[0m  [[\"id\", 49], [\"LIMIT\", 1]]\n","stream":"stdout","time":"2017-06-24T18:48:45.590998655Z"}
{"log":"[a627e520-ace0-438a-902c-d277408a733f]   \u001b[1m\u001b[36mDoorkeeper::Application Load (0.9ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  \"oauth_applications\".* FROM \"oauth_applications\" WHERE \"oauth_applications\".\"id\" = $1 LIMIT $2\u001b[0m  [[\"id\", 103], [\"LIMIT\", 1]]\n","stream":"stdout","time":"2017-06-24T18:48:45.659848371Z"}
{"log":"[a627e520-ace0-438a-902c-d277408a733f]   \u001b[1m\u001b[36mCACHE (0.1ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  \"oauth_applications\".* FROM \"oauth_applications\" WHERE \"oauth_applications\".\"id\" = $1 LIMIT $2\u001b[0m  [[\"id\", 49], [\"LIMIT\", 1]]\n","stream":"stdout","time":"2017-06-24T18:48:45.695353119Z"}
{"log":"[a627e520-ace0-438a-902c-d277408a733f]   \u001b[1m\u001b[36mCACHE (0.1ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  \"oauth_applications\".* FROM \"oauth_applications\" WHERE \"oauth_applications\".\"id\" = $1 LIMIT $2\u001b[0m  [[\"id\", 49], [\"LIMIT\", 1]]\n","stream":"stdout","time":"2017-06-24T18:48:45.775906543Z"}
```

Not sure what these logs represent, but wanted to share in case it helps.

**Comment by ashfurrow** [comment]
Thanks @alexgleason – the second log output looks like verbose logging, similar to the Sidekiq issue. Rails is definitely running in production mode, but maybe there's something wrong with the other containers config? I'll take a look. Thanks again 🙇

**Comment by ashfurrow** [comment]
So I havne't had a chance to look further into the root problem but I'm going to try a workaround by restarting the docker services once a week (clearing all the log files). In case this is useful for anyone else, I put this in my crontab:

```
0 4 * * 2 cd /root/mastodon ; docker-compose down ; docker-compose up -d
```
