### ISSUE TITLE
App authorization page should use scopes from app registration

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#3568]
Currently (v1.4.1), requesting authorization of an app through the oauth/authorize endpoint requires specifying the scopes to allow the app to use. This is independent from the scopes indicated when registering the app through the api/v1/apps endpoint, leading to confusion as seen in #2164.

Since the software is already looking up the app's name in a database (it is not included in the oauth/authorize query but shows on the page), it should be easy to use the scopes indicated at registration, eliminating a possible source of mistakes.

If it is intended that the user can authorize different scopes than the app requests, it would be better to add some checkboxes on the authorization page above the [ Deny ] and [ Authorize ] buttons.
* * * *
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by spaceottercode** [comment]
@Kimik0 I don't know how much this matters to the Doorkeeper devs but the Oauth 2 standard includes the following

> If the client omits the scope parameter when requesting
   authorization, the authorization server MUST either process the
   request using a pre-defined default value or fail the request
   indicating an invalid scope.  The authorization server SHOULD
   document its scope requirements and default value (if defined).


aside: Mastodon uses `read` as the default.
