### ISSUE TITLE
Add API endpoint to retrieve information about the current app

### ISSUE THREAD

**Issue by Kimik0** [tootsuite/mastodon#3569]
Currently (v1.4.1), an app's name and url are only seen when registering the app and when toots are made from it. There is no way to find out what name and url were used at registration other than by storing it offline or by creating a new toot. What scopes the app is authorized for is also only sent when registering and when getting an authorization token and never afterwards. Finding this information again would require accessing multiple API endpoints to see which are denied or allowed. It can be done, but it is quite a hassle.

I'd like to see an API endpoint that looks up the data associated with an authorized app: id, client_name, website, scopes (or "scope"? the field name seems to differ between endpoints), created_at.
* * * *
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Fixed in #5112
