### ISSUE TITLE
[Feature request] Upside down timeline order

### ISSUE THREAD

**Issue by Efimero** [tootsuite/mastodon#3571]
I would like to see the web Mastodon client have an option to switch to the reverse, where new messages appear from the bottom and older ones go to the top.
If this is possible, it would be an improvement in usability from my standpoint. The reasoning being that reading the columns becomes more natural when chronology follows reading direction.
That is all, thanks. <3

**Comment by nolanlawson** [comment]
I don't think this is something we're likely to support, but alternative clients can support this if they like.
