### ISSUE TITLE
GNU Social interoperability - paragraphs and surprise link attachments

### ISSUE THREAD

**Issue by abochmann** [tootsuite/mastodon#3573]
There is an unintended consequence of GNU Social not being able to parse the `<p> .. </p>` paragraphs being used by Mastodon: When the last word of a paragraph and the first word of the next happen to seem like a valid link, a post created on Mastodon will get a link attachment as it's received by a GNU social instance (since the paragraph start and end tags are removed entirely).

For example, a post that looks like this when written on Mastodon:

> This is a test.
>
> No surprises here...

...will have a link to `test.no` attached by GNU Social.

I'm aware of the discussion on pr #1663, and I don't want to take any sides on that issue as such. As a Mastodon user, I would nevertheless prefer if a way could be found to minimize the impact of known limitations in other software.

A simple and ugly workaround for specifically the link autocreation problem may be to just add a blank (or possibly an actual newline?) between the paragraph end and start tags (like `</p> <p>`), provided those don't get stripped for different reasons.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by yookoala** [comment]
Added an issue here:
https://git.gnu.io/gnu/gnu-social/issues/272
