### ISSUE TITLE
Web UI wastes 1/3 of the browser width

### ISSUE THREAD

**Issue by strk** [tootsuite/mastodon#3583]
From Firefox 45.3.0 on a Debian 8 box the https://mastodon.social page (after login) takes up only 2/3 of available browser width. Added to the 4 columns layout this makes the content column to be as small as 1/6 of the whole screen, rendering it really uncomfortable in reading.

Here's a screenshot:

![mastodon-ui](https://cloud.githubusercontent.com/assets/289678/26776043/f228cda8-49d7-11e7-84a2-0249cac096b7.png)

**Comment by yookoala** [comment]
The current design is of static width. So depends on your screen size, there are unfilled spaces.

What do you think is the appropriate behaviour for wider screens?

Popular choices:
1. Centralize the UI while keeping the width.
2. Have all columns to scale to 25% of the screen wider than 1290px.
3. Only scale up 1 of the columns for screen wider than 1290px.
4. Add some decorations to the empty space (like graphic of a Mastodon?)

**Comment by Gargron** [comment]
See #3207

**Comment by mtparet** [comment]
Issue does not seem to be solved, hack still needed https://github.com/tootsuite/mastodon/pull/3207#issuecomment-414684219
