### ISSUE TITLE
Error 404 when load resource on packs folder

### ISSUE THREAD

**Issue by bokuyami21** [tootsuite/mastodon#3584]
Today i upgraded my mastodon.
And I got 404 error when load resources on packs folder.
Some thing like following `image`
![Error](http://sv1.upsieutoc.com/2017/06/05/Errors.png)

I check mastodon-streaming.service and get error
```
mastodon-streaming.service stop-final-sigterm timed out. Killing.
Unit mastodon-streaming.service entered failed state.
mastodon-streaming.service failed.
```

Please help me
* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
What do you see inside the public/packs folder? Is nginx configured to serve files from the public directory?

**Comment by bokuyami21** [comment]
@Gargron
Inside pack folder have some css and js file. Files in above image are being included. 
Yes it is. It worked fine before upgrade

**Comment by bokuyami21** [comment]
It appears nginx have read permission on public folder.
I check on nginx log and see errors like this:
```
2017/06/06 12:29:12 [crit] 28119#28119: *1 stat() "/home/mastodon/live/public/packs/common-da0b8691fb2398ab5a51.css" failed (13: Permission denied)....
```

**Comment by Marsupilami23** [comment]
Did you fix this issue? I'm having the same problem? what was the solution?

**Comment by bokuyami21** [comment]
Yes i did. Maybe your nginx server and mastodon app are running on 2 user.
Soluton 1: setting for nginx running base on mastodon user.
Solution 2: setting permission read for nginx user on mastodon user's home directory
'''
chmod +x /home/mastodon
'''

**Comment by ntoonio** [comment]
chmod +x /home/mastodon

worked for me. Feels a bit wonky but at least better than running nginx as something other than www-data... right?

**Comment by keskival** [comment]
Just a note here: This can also happen if you run Mastodon in Kubernetes and have different versions of the image running in several pods. This means that some requests are routed to one pod and some to another, and they disagree on the js file names and such as they get the hash digest names in the Docket image generation as they are compiled.
