### ISSUE TITLE
Hashtag search does not find tag itself - only similar tags

### ISSUE THREAD

**Issue by ThomasLeister** [tootsuite/mastodon#3591]
If you enter a hashtag at the search bar, only similar hashtags appear as suggestions, but the tag itself is not displayed. :( 

Examle: Search for "#linux": "#linux-gaming" and "#linux-kernel" are displayed as search results and if you click them, you'll get suitable posts - but "#linux" is not displayed, so you cannot find posts tagged with just "#linux". 

![bildschirmfoto von 2017-06-05 18-02-39](https://cloud.githubusercontent.com/assets/4207956/26792213/fb446a90-4a19-11e7-89b0-5f66623e4da4.png)
![bildschirmfoto von 2017-06-05 18-02-29](https://cloud.githubusercontent.com/assets/4207956/26792214/fb4b9ffe-4a19-11e7-8d87-4e7054793cf6.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThomasLeister** [comment]
Update: This might be an instance-specific problem... :S Is anyone experiencing the same problem?

**Comment by ThomasLeister** [comment]
Update 2: Works with "#nsfw" hashtag. O_o
![bildschirmfoto von 2017-06-05 18-47-48](https://cloud.githubusercontent.com/assets/4207956/26793783/8e7febb8-4a1f-11e7-9041-dcce5c5c0c31.png)

**Comment by Alex-rtnVFRmedia** [comment]
happens on social.tchncs.de but not on glitch.social ..

**Comment by Cassolotl** [comment]
Here's cybre.space:

![screen shot 2017-06-05 at 19 15 09](https://cloud.githubusercontent.com/assets/6607512/26796995/559e9f5c-4a23-11e7-81ae-faf9663a2e7e.png)
![screen shot 2017-06-05 at 19 15 34](https://cloud.githubusercontent.com/assets/6607512/26797017/621f7c56-4a23-11e7-94c4-ab33838ab87e.png)

Tagging the cybre.space admin, @Chronister, in case it is instance-specific in some way...? :S

**Comment by ThomasLeister** [comment]
Probable error cause (in theory): Search results are limited to 5 results. If I search for "#linux", the first five unique hashtag results for "linux"  **or** "linux*" are returned from the database. If (by accident) "linux" is not part of the first 5 results returned by the DB, it will not be displayed. 

**Possible solution**: *Always* add the searched hashtag as the first search result and fill up with 4 more search results from the database, ordered by relevancy / alphabet.

**Comment by unarist** [comment]
The tag which exactly matches search term should be a first search result as a most relevant tag I think.

[Current search logic](https://github.com/tootsuite/mastodon/blob/v1.4.1/app/models/tag.rb#L24-L40) uses PostgreSQL's `ts_rank_cd()` function to calculate relevance, but the function returns **same score** for all results actually. The function is appropriate for searching words in the document, but not for calculate similarity of single word.

```
mastodon_development=# select name from tags;
   name
----------
 testhoge
 testfoo
 testbar
 testpiyo
 tester
 test
 testああ
 deleted
(8 rows)

mastodon_development=# SELECT tags.name, ts_rank_cd(to_tsvector('simple', tags.name), to_tsquery('simple', ''' test '':*')) AS rank FROM tags WHERE to_tsquery('simple', ''' test '':*')@@to_tsvector('simple', tags.name) ORDER BY rank DESC;
   name   | rank
----------+------
 testhoge |  0.1
 testfoo  |  0.1
 testbar  |  0.1
 testpiyo |  0.1
 tester   |  0.1
 test     |  0.1
 testああ |  0.1
(7 rows)

mastodon_development=# SELECT ts_rank_cd(to_tsvector('simple', tags.name), to_tsquery('simple', ''' test '':*')) AS rank, count(*) FROM tags WHERE to_tsquery('simple', ''' test '':*')@@to_tsvector('simple', tags.name) GROUP BY rank;
 rank | count
------+-------
  0.1 |     7
(1 row)
```
