### ISSUE TITLE
Avatars often not displaying

### ISSUE THREAD

**Issue by Jehops** [tootsuite/mastodon#3594]
Over time, gradually [fewer and fewer avatars have been showing up](http://ftfl.ca/misc/missing_avatars2.png), including my own.  Occasionally, when I reload the page [my own shows up again](http://ftfl.ca/misc/missing_avatars1.png).  Sometimes it shows up, but then disappears after a moment.

I only noticed the problem after 1.4.1, but I also installed/uninstalled many times while testing a Mastodon FreeBSD port/package.  I see lots of `[835bf021-0e0a-4d40-a2cf-a33c193de9e1] method=GET path=/system/accounts/avatars/000/000/155/original/2bb90117774f85af.jpg format=*/* controller=ApplicationController action=raise_not_found status=404 duration=43.08 view=0.00 db=23.65` in the logs.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by noraworld** [comment]
This bug also happens on my instance. (v1.4.1)

This also probably happens on other instances, I think.

**Comment by nolanlawson** [comment]
I've noticed this bug myself but it's hard to consistently reproduce.

**Comment by Gargron** [comment]
Fetching avatars is performed in the background, which is why the first look up of someone may return a missing avatar and other profile data. Are you sure that's not what you're seeing?

Or do you think this should be modified to download avatars in the foreground when an account is looked up for the first time?

**Comment by Jehops** [comment]
This problem seems to have resolved itself here in subsequent releases.  Also, I may have triggered issues when clearing/restoring directories when testing changes to the mastodon FreeBSD package.  I don't think an initial missing avatar is that big of a deal if it improves performance and it's downloaded soon afterwards.  In my case the avatars weren't showing up or even disappearing later.  But, as I said, that seems to have resolved itself.  I can close the issue if others also feel the issue is resolved.

**Comment by nightpool** [comment]
@gagron

**Comment by Cassolotl** [comment]
This can totally be closed!

**Comment by abejaranoh** [comment]
I am having exactly the same problem in the version 4.2.5. What can be in reason?
