### ISSUE TITLE
Invisible toots in home timeline

### ISSUE THREAD

**Issue by sdukhovni** [tootsuite/mastodon#3600]
I'm seeing a lot of blank gaps between toots in my home timeline in the web UI. If I refresh the page and scroll to the same location, I can see a toot in that spot that was previously invisible. Inspecting the page source, the invisible toots are inside tags of the form `<div data-id="123456" style="height: 142px; opacity: 0; overflow: hidden;">`. The divs contain comments like `<!-- react-text: 5805 -->` and the author and toot content in double-quotes, rather than actual formatted toots. It looks like a lot of toots outside the area I'm scrolled to have this form, but most of them get magically turned into `<div class="status">`es when I scroll to them.

I've observed this behavior in Brave Browser on Linux and in Chrome on Android.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
@nolanlawson @sorin-davidoi

**Comment by nolanlawson** [comment]
Yup this should be fixed by https://github.com/tootsuite/mastodon/pull/3525. Note that Brave has the same rendering engine as Chrome.

**Comment by nolanlawson** [comment]
Please reopen if I'm mistaken. You can test in the master branch or on malfunctioning.technology

**Comment by sdukhovni** [comment]
Awesome, thanks :)
