### ISSUE TITLE
simple HTML tag not respected (with content type="html" in atom)

### ISSUE THREAD

**Issue by Shnoulle** [tootsuite/mastodon#3621]
GnuSocial with mardown plugin allow to use markdown in notice. Then using `:100::100::100:` sended as `<code>:100::100::100:</code>` in atom (`content type="html"`).

But mastodon replace `:100:`by 💯 . 

Link of the original notice : `https://ostatus.shnoulle.net/api/statuses/show/708914.atom` , showing in mastodon like `https://framapiaf.org/users/framasky/updates/78376` or screenshot on 1.4.1 version

![capture du 2017-06-07 11-21-44](https://user-images.githubusercontent.com/1439428/26871534-d0f4b19a-4b73-11e7-9d43-a0075bdbe01b.png)

Same issue with `<em>Emphase</em>` and `<strong>Fort</strong>` : https://ostatus.shnoulle.net/api/statuses/show/708954.atom

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate (but unsure for the good word for searc)
- [x] This bug happens on a 1.4.1

**Comment by Gargron** [comment]
1. em, strong and code are stripped out by sanitization. only p, br, span and a are allowed
2. the emoji conversion happens in JS through the emojione library

**Comment by nolanlawson** [comment]
Yeah this seems like a security issue more than anything (e.g. against XSS). I'm not sure there's much value in supporting unsanitized HTML. The emoji conversion is also for the benefit of Mastodon users who use the emoji picker, which inserts e.g. `:100:`.

**Comment by Shnoulle** [comment]
What ! XSS ! with simple HTML tag ! You kidding me ? You already allowing span why not strong, pre, em and p.

And about `:100:` : maybe it's cool for mastodon user but : if i want to send `:100:` how i do it ?

The atom content must rules.
