### ISSUE TITLE
the ability to delete accounts

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#363]
deleting accounts are an important part of allowing people to maintain their information, or in some cases escape abuse and stalking.

when it comes to deleting accounts, it seems to be something able to be done, just not allowed to be done by the user, since there already was an issue where someone asked to be deleted and their information was.

as such it should not theoretically be too hard to open this to users, probably in the settings menu.
i recall when this topic came up there was worry about the issue of accounts being auto-subbed to any user who took the @, since there isnt a way to tell the feed to unsubscribe from said user. this can be remedied by saving the @ on the service, or by maintaining a waiting period to allow other services to realize the feed has been deleted.

thank you for listening.

**Comment by marrus-sh** [comment]
Allowing the deleting of accounts but reserving the address would be consistent behaviour with e.g., most email providers; because of federation i don't really foresee a situation where freeing up addresses would be necessary. It would just be a matter of replacing the account with one that is completely empty; perhaps with a message saying “this account has been deleted by the user” or some such.

**Comment by Gargron** [comment]
Yes, I've changed my mind since #109. The moderation tool "account suspension" pretty much does this already. It's just a matter of letting a user invoke that function on themselves manually.

**Comment by hoodiek** [comment]
another thought: since the @ could remain reserved to an email address, users who delete could change their mind, only at the cost of losing past posts/people they follow

**Comment by hoodiek** [comment]
this would also encourage the advent of a "clear account" option that would remove all past posts/favs too, which is something i heavily would approve of and appreciate, something twitter lacks

**Comment by gambogi** [comment]
Is it not possible to change an account's email address? If not, does that issue belong here?

**Comment by Gargron** [comment]
@gambogi It's possible. Settings -> Change password page contains e-mail as well

**Comment by yiskah** [comment]
I believe this issue can be merged with #109 yeah?

**Comment by swaldie** [comment]
Yeah we're going to merge this with #109.  Please move all discussion there.
