### ISSUE TITLE
Unneeded (and broken) RemoteProfileUpdateWorker spawns

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#3633]
In my search for more weird race conditions / uncommitted database changes issues, I have found some redundant requests/calls: `FollowRemoteAccountService` spanws a `RemoteProfileUpdateWorker` worker whenever it finds a new remote account. However, `FetchRemoteAccountService`, `FollowRemoteAccountService`'s main caller unconditionally performs the profile update work itself in a synchronous fashion. It is not a huge issue, but the spawned worker often performs duplicate works, and in rare cases silently fails (when the unknown remote account appears in a mention, the mention is processed within a `transaction` and the worker spawns before that transaction gets committed).

**Comment by Gargron** [comment]
Yeah that seems wasteful. FollowRemoteAccountService is often called outside of FetchRemoteAccountService, however, and in those contexts it does not have a pre-downloaded Atom feed to update profile data from. Perhaps this means adding an argument to the FollowRemoteAccountService to selectively disable the spawning of that worker.
