### ISSUE TITLE
Media back button behaviour

### ISSUE THREAD

**Issue by tobypinder** [tootsuite/mastodon#364]
When expanding an image on mobile there is no url change, so the lightbox fills the background and the image fills the screen but I keep hitting "back" and it just moves the stuff behind the lightbox.

Expected behavior: pressing back on a media embed results in the lightbox image being closed, and the page behind it to remain stable.

**Comment by Cassolotl** [comment]
If there was a visible X at the *bottom*-right corner of the image I might be able to learn to use it more often than going for the back button?

Gargron [said](https://github.com/tootsuite/mastodon/pull/3647#issuecomment-345130737):

>I've asked on the reactiflux discord and creating a fake history entry is what they suggested to me.

**Comment by Cassolotl** [comment]
https://github.com/tootsuite/mastodon/pull/5956#issuecomment-380851769
