### ISSUE TITLE
Provide account note in a plain text via API as opposite of update_credentials

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#3649]
`/api/v1/accounts/update_credentials` only accepts notes in a plain text, but there is no way to obtain account note in a plain text via API. So apps which want to edit profile in the app have to strip tags.

I know that providing contents in a plain text is hard for remote accounts, but it should be able to do for local accounts, especially their own accounts.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Resolved with #4075
