### ISSUE TITLE
Semicolons get attached to URLs?

### ISSUE THREAD

**Issue by marrus-sh** [tootsuite/mastodon#365]
Example: [`http://example.com;`](http://example.com;) (seen in [this toot](https://mastodon.social/users/marrus_sh/updates/508508)). Semicolons *are* valid in URLs (and are used sometimes instead of `&` in the query part) but I feel that if nothing else, semicolons which come at the end of URLs should probably be excluded.

(If nothing nothing else, they should not be allowed in TLDs lol)

**Comment by Gargron** [comment]
We're using https://github.com/tenderlove/rails_autolink to format the URLs. That's gotta be an upstream bug (or intended feature?) I do hope I don't have to make my own library again in case they aren't around to fix it 😅
