### ISSUE TITLE
Direct messages get posted on public timeline

### ISSUE THREAD

**Issue by sphinxc0re** [tootsuite/mastodon#3659]
Title says it all. I suspect direct messages are not really private conversations.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Can you give more details?

**Comment by sphinxc0re** [comment]
I'm sorry, but I'm not maintaining the instance, I'm on. I just thought that direct messages shouldn't get posted on public timelines.
<img width="804" alt="screen shot 2017-06-09 at 15 15 09" src="https://user-images.githubusercontent.com/3702016/26976971-7b2e1f3a-4d26-11e7-98a7-d15b78645715.png">
These are the messages, that I mean

**Comment by Gargron** [comment]
Are you looking at your own profile while logged in?

**Comment by sphinxc0re** [comment]
Thank you for your help @Gargron 😅
