### ISSUE TITLE
multi-column support bug: clicking a hashtag opens in all columns

### ISSUE THREAD

**Issue by cphuntington97** [tootsuite/mastodon#3665]
To reproduce:

Search multiple hashtags and pin them as columns.

Click on a hashtag. It opens in all of the pinned columns (except for Home and Notifications).

I'm not sure what the expected behavior should be. I think I'd like a clicked hashtag to open in a new column, but it shouldn't overwrite my existing pinned-hashtag columns.

**Comment by Gargron** [comment]
Oh. You're right. This reminds me there is only one store for "hashtag timeline" in Redux right now, that needs to be reworked. Good catch!

I guess we need to delay release for a while longer then. Sorry this escaped my memory :(

**Comment by cphuntington97** [comment]
No apology necessary, @Gargron. I appreciate all of the work you do!
