### ISSUE TITLE
Notification clear

### ISSUE THREAD

**Issue by triplefox** [tootsuite/mastodon#368]
Occasionally people on my timeline will ask for help clearing their notifications of something unpleasant - an upsetting remark or a favorite that you don't really need to be reminded hours later.  Ideally we could prevent all unpleasantness, but clearing the timeline is something we may quickly automate - either with a button to hide each one, or a big "clear all" at the top. As this is a minor convenience, this function could just be client-side and temporary for the session.

**Comment by hoodiek** [comment]
this is encompassed in #244

**Comment by hoodiek** [comment]
recommend closing

**Comment by yiskah** [comment]
Like hoodie said, this has been implement so this issue can be closed @Gargron
