### ISSUE TITLE
Web UI stretches videos with vertical aspect ratio

### ISSUE THREAD

**Issue by fpiesche** [tootsuite/mastodon#3683]
I've noticed a number of times in the past that videos recorded on my phone held upright (i.e. with a vertical aspect ratio) are stretched to a horizontal ratio on the Mastodon web frontend, both on individual post pages and the main column UI. This happens in Firefox and Chrome at the least.

ex.:
https://mastodon.social/@theoutrider/8612060
https://mastodon.social/@theoutrider/1038789

Mobile apps (e.g. Tusky) display the videos in these two posts in the correct vertical aspect ratio.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate
- [X] This bug happens on the live mastodon.social website

**Comment by Gargron** [comment]
If I open the file directly it looks stretched to me too, on Firefox: https://files.mastodon.social/media_attachments/files/000/658/294/original/f3ecd41e82ac0a17.webm Outside of the Mastodon UI

**Comment by fpiesche** [comment]
how peculiar. looks like the "do not rescale" option in the app I use to convert to webm still breaks stuff... though I wonder what Tusky does differently that causes it to display correctly in that.

**Comment by nolanlawson** [comment]
Those links appear broken to me… :confused:

Could you host the video somewhere else and provide steps to reproduce the issue?

**Comment by nightpool** [comment]
@nolanlawson I think the response here means that this bug can be closed—it was an issue with the video file, not mastodon.
