### ISSUE TITLE
"docker-compose build" stuck

### ISSUE THREAD

**Issue by mnn** [tootsuite/mastodon#3698]
After running `docker-compose build` it is stuck on:

```
Binary found at /mastodon/node_modules/node-sass/vendor/linux_musl-x64-48/binding.node
Testing binary
Binary is fine
node-sass@4.5.2 /mastodon/node_modules/node-sass
Done in 306.67s.
```

Waited over 10 minutes with zero IO and CPU activity on the server (it's not swapping). Any ideas?

Version I am trying is **1.4.1**.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mnn** [comment]
Nothing? I thought this quite active project :disappointed:.

**Comment by nolanlawson** [comment]
You might also try https://discourse.mastodon.org for admin support-type questions. :)

**Comment by mnn** [comment]
Thank you, I'll try it there (probably later, now the server is returning me only blank page ._.).
