### ISSUE TITLE
default posting options

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#371]
this is mainly a feature of ease of use, but the settings window could have a "default posting options" to extend the private accounts feature, and have for example, the default images be marked sensitive, the default privacy be unlisted, but still public, and thus let public accounts and private accounts alike pick said default settings

the final thing very heavily of note is making it so that whenever you hit toot, it resets to the default settings

thank you for listening.

**Comment by yiskah** [comment]
I believe this feature has been implement and this issue can be closed @Gargron
