### ISSUE TITLE
Vagrant error (1.4.1)

### ISSUE THREAD

**Issue by franck-paul** [tootsuite/mastodon#3713]
Hi,

I just tried to run a fresh VM with vagrant in **dev** mode, checkouted on **1.4.1** tag, but I can't start the server. Here are the output of the `vagrant ssh -c "cd /vagrant && foreman start"` command (done after a `vagrant destroy`, followed by a `vagrant up`) :

```
06:27:01 web.1     | started with pid 30412
06:27:01 sidekiq.1 | started with pid 30413
06:27:01 stream.1  | started with pid 30415
06:27:01 webpack.1 | started with pid 30418
06:27:02 webpack.1 | sh: 1: /vagrant/node_modules/.bin/webpack-dev-server: not found
06:27:02 stream.1  | yarn run v0.24.6
06:27:02 stream.1  | $ rimraf ./tmp/streaming && babel ./streaming/index.js --out-dir ./tmp && node ./tmp/streaming/index.js
06:27:02 stream.1  | sh: 1: rimraf: not found
06:27:02 stream.1  | error Command failed with exit code 127.
06:27:02 stream.1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
06:27:02 web.1     | [30414] Puma starting in cluster mode...
06:27:02 web.1     | [30414] * Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
06:27:02 web.1     | [30414] * Min threads: 5, max threads: 5
06:27:02 web.1     | [30414] * Environment: development
06:27:02 web.1     | [30414] * Process workers: 2
06:27:02 web.1     | [30414] * Preloading application
06:27:02 stream.1  | exited with code 1
06:27:02 system    | sending SIGTERM to all processes
06:27:02 webpack.1 | exited with code 127
06:27:03 web.1     | terminated by SIGTERM
06:27:03 sidekiq.1 | terminated by SIGTERM
Connection to 127.0.0.1 closed.
```

Any idea on what is going wrong?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by happycoloredbanana** [comment]
Cannot reproduce it.
This is what I did:
```
vagrant destroy -f
git checkout v1.4.1
vagrant up
vagrant ssh -c "cd /vagrant && foreman start"
```
Seems to be working.

Maybe try to look more closely at your ```vagrant up``` output - looks like something went wrong with ```yarn install```

**Comment by franck-paul** [comment]
You're right, probably a problem with yarn install as I got this:

```
==> default: yarn install v0.24.6
==> default: [1/4] Resolving packages...
==> default: [2/4] Fetching packages...
==> default: error https://registry.yarnpkg.com/@kadira/storybook/-/storybook-2.35.3.tgz: Bad hash. Expected "8106195e1733623baf60db6adaa678dc29285d12" but got "da39a3ee5e6b4b0d3255bfef95601890afd80709"
```

During the `vagrant up`

**Comment by happycoloredbanana** [comment]
Maybe try `vagrant ssh` to your VM and then:
```
wget https://registry.yarnpkg.com/@kadira/storybook/-/storybook-2.35.3.tgz
shasum storybook-2.35.3.tgz
```
just to see that the hash is okay.
Weird.

**Comment by franck-paul** [comment]
Yes, it's weird as the wget command returns this:

```
vagrant@mastodon:~$ wget https://registry.yarnpkg.com/@kadira/storybook/-/storybook-2.35.3.tgz
--2017-06-12 16:49:28--  https://registry.yarnpkg.com/@kadira/storybook/-/storybook-2.35.3.tgz
Resolving registry.yarnpkg.com (registry.yarnpkg.com)... failed: Name or service not known.
wget: unable to resolve host address ‘registry.yarnpkg.com’
```

So I checked with:

```
vagrant@mastodon:~$ nslookup registry.yarnpkg.com
Server:		195.68.0.1
Address:	195.68.0.1#53

** server can't find registry.yarnpkg.com: REFUSED
```

I don't know why, but every NS request, even with another domains, give me the same answer: 

REFUSED

**Comment by franck-paul** [comment]
And even after changing DNS config, testing the wget command (success), then after re-installing yarn, I get the same error `rimraf: not found`.

Unable to start the servers and I don't know why

**Comment by franck-paul** [comment]
I also opened a topic on Discourse → https://discourse.joinmastodon.org/t/vagrant-1-4-1-error/368

**Comment by franck-paul** [comment]
I did the same test with the 1.4.3 release and same result: nothing is running.

Am I the only one running a Vagrant dev VM on OSX and having such problems?

**Comment by franck-paul** [comment]
Eventually found the problem: updating vagrant from 1.9.3 to 1.9.5 (latest) and everything is running as expected \o/
