### ISSUE TITLE
Feature request: Export/import content

### ISSUE THREAD

**Issue by selfagency** [tootsuite/mastodon#3716]
Please add a feature to export and import one's content, not just follow and block lists. If I want to move to another instance, I need to be able to take my content with me.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
Your needs may or may not be reflected in #177 - "Support account migration". (Nov 2016, 150 thumbs-up.)

**Comment by selfagency** [comment]
Disappointed to see this is a conversation that's been going on for seven months and has not moved towards implementation.

**Comment by Cassolotl** [comment]
@selfagency Same. :/
