### ISSUE TITLE
Feature request: Birdsite account linking

### ISSUE THREAD

**Issue by selfagency** [tootsuite/mastodon#3717]
Please add a feature to link one's Twitter account to their Mastodon profile to search for friends and to autopost toots to Twitter. I know there are third-party apps that do this (poorly I might add), but for Mastodon to really gain mass adoption, this is essential to the core features of the app itself.

I also have a suggestion for an external linking scheme that could be quite helpful. If you want to reference someone on Twitter, just put a `@tw:` in front of their handle like `@tw:whoever`. Mastodon would then link to that user's Twitter profile automatically (target `_blank` a link to `https://twitter.com/whoever`). This could also work for other platforms like Instagram, for example: `@ig:whoever`.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
I said this on another of your discussions but it seems right to put it here too:

> #1849 might be relevant to your interests on this one? "Link @username@twitter.com to Twitter profile pages"

**Comment by M-D-M** [comment]
I think this might be a bad idea down the road.  All Mastodon needs is Twitter to say "Now with Mastodon support!  Tweet at your friends on Mastodon without leaving Twitter!" and users migrating from Twitter to Mastodon slows to a crawl.  

Even worse -- they decide to "fully support the Mastodon" API, and then you're eventually in a Microsoft-esque EEE situation.

**Comment by nolanlawson** [comment]
I believe this would violate Twitter's ToS; please reopen if I misinterpreted it: https://dev.twitter.com/overview/terms/agreement-and-policy#id30

**Comment by selfagency** [comment]
How would using Twitter's API to find your friends and linking to Twitter with tw: to autogenerate URLs service violate the rules? I'm not talking about embedding or importing tweets.

**Comment by nolanlawson** [comment]
Good point. I would leave this suggestion up to Eugen to decide whether he wants to implement or not though
