### ISSUE TITLE
Feature request: Birdsite content import

### ISSUE THREAD

**Issue by selfagency** [tootsuite/mastodon#3718]
Please add a feature to import one's Twitter content from a Twitter CSV export file.

As I mentioned in my previous feature request, I also have a suggestion for an external linking scheme that could be quite helpful. If you want to reference someone on Twitter, just put a `@tw:` in front of their handle like `@tw:whoever`. Mastodon would then link to that user's Twitter profile automatically (target `_blank` a link to `https://twitter.com/whoever`).

When importing from Twitter, automatically rewrite all `@mentions` with `@tw:` so that it creates external links to Twitter.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
#1849 might be relevant to your interests on this one?

**Comment by selfagency** [comment]
Yes it does but I do like my scheme better as it uses less space. That said, I still want a feature to import my old tweets.

**Comment by Cassolotl** [comment]
Fair nuff! :)

**Comment by nolanlawson** [comment]
I don't believe we can do this since it violates Twitter's ToS. Please reopen if I'm misinterpreting their ToS incorrectly: https://dev.twitter.com/overview/terms/agreement-and-policy#id30

**Comment by nightpool** [comment]
@nolanlawson I don't see anything in the twitter API that prevents this... Furthermore, this wouldn't be using the API, it would be using the export CSV.

**Comment by nightpool** [comment]
Not that I believe this really that useful of a feature, but just wanted to make it clear that I don't think this violates the twitter API.

**Comment by clworld** [comment]
Note: Import toot from somewhere is problematic for current Mastodon.
Because order of timeline is status id order, importing 1000 toots resulting recent 1000 toots in local timeline are fulfilled with imported toots.
