### ISSUE TITLE
Generalize "favourites" into "reactions"

### ISSUE THREAD

**Issue by LogicalDash** [tootsuite/mastodon#373]
Favourites don't serve the bookmark-like function on Mastodon that they do on Twitter. I'm fine with that; I'd prefer one way to bookmark toots and another way to express approval of them.

Assuming that'll remain the same, why not generalize that the way Github already does, and let us express an array of predefined reactions to a toot? "Favourite" would still be an option, but so would thumbs-up and -down, heart, ಠ_ಠ, and I guess whatever predefined messages the instance operator wants to put there.

I suppose these wouldn't federate? Not sure if that's a problem per se.

**Comment by Gargron** [comment]
I'm sorry that it took 18 days to say it, but I don't think that's the direction I want it to go. For more refined reactions you could just reply to the post instead of/additionally to favouriting.
