### ISSUE TITLE
Muted users appear in notifications

### ISSUE THREAD

**Issue by nullkal** [tootsuite/mastodon#3731]
It seems the muting feature currently hides toots from muted users in home/local/federated timeline, but not notifications. According to [the section describing the muting feature in Mastodon User's Guide](https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/User-guide.md#muting) it appears to be the expected behavior, but I don't know the reason why the muting feature does not hide notifications (e.g. replies, favs, boosts) which is in relation to the muted accounts.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by clworld** [comment]
FYI: maybe related: https://github.com/tootsuite/mastodon/pull/3245

**Comment by Gargron** [comment]
Block: "I don't want to ever see this person"
Mute: "I don't want to see this person's posts in the timelines"

Muting is appropriate for an annoying friend, someone you don't want to passively observe but still want to hear from if they tell *you* something

**Comment by nullkal** [comment]
Thanks, I understand now.
