### ISSUE TITLE
Some emoji won't be replaced with SVG

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#3732]
`:one: :two: :three: :four: :five: :six: :seven: :eight: :nine:`

![image](https://user-images.githubusercontent.com/705555/27085404-1a6a51c0-508a-11e7-96c3-c4330a39c739.png)

These characters seems to be missing from regex pattern in [emojione.js](https://github.com/emojione/emojione/blob/2.2.7/lib/js/emojione.js#L148) (https://github.com/emojione/emojione/issues/490), but it wouldn't be fixed on v2 since it is outdated.

Possible solutions are...

- Fork and edit regex pattern
- Update emojione to v3 (but this breaks emojione-picker, so we have to fix it)
- anything else?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment]
Change emoji pack ([discourse discussion](https://discourse.joinmastodon.org/t/emoji-and-emoji-5-0/237/3))?

**Comment by Gargron** [comment]
Should we use Twemoji (Twitter's emoji)? It seems a bit odd at best that we would resort to that...

**Comment by Komic** [comment]
I mean is there really another alternative? If EmojiOne won't release an open source, up-to-date pack, Twemoji seems like a logical solution.

**Comment by unarist** [comment]
I thought using emojione 3 js (MIT licensed even now) and emojione 2 images, but this approach seems bit complicated. So changing to another packs would be a good idea. 

(Actually, we're using twitter-text already.)

**Comment by nolanlawson** [comment]
I'd say open a PR on emojione; I've been working with them a bit and they seem open to improvements: https://github.com/emojione/emojione

**Comment by sorin-davidoi** [comment]
I think the question is if this is really worth fixing, since we need to update the emoji pack anyway (this one does not support the latest emoji), which would also fix this issue.

**Comment by unarist** [comment]
This issue was solved at #4049.
