### ISSUE TITLE
don't show subscriber

### ISSUE THREAD

**Issue by Beanux** [tootsuite/mastodon#3733]
Hello,

When checkin the subscriber of someone on an other instance, i only see member of my instance.
When checking the webpage, it show the true number.

Certainly an issue of communication of user naming between instances.

my Instance version 1.3.2
other instance version: 1.3.3,1.4.1, 1.4.2

**Comment by Cassolotl** [comment]
I think this is a duplicate of #1037!

**Comment by Beanux** [comment]
You're right, i didn't find it by searching with "subscribe" term.
sorry.

**Comment by Cassolotl** [comment]
No problem!
