### ISSUE TITLE
[query] Can identity domain and host domain be different?

### ISSUE THREAD

**Issue by kwill** [tootsuite/mastodon#3739]
**User story:** I am a service host with an existing domain, planning to run a Mastodon instance. I want to host it on a subdomain, so I can maintain it easily, but still have users addressable at the original domain, so that identities remain short and memorable.

**Example:** I run https://example.com, where I host services including XMPP and email. Users are addressable on these services with `alice@example.com`. I run Mastodon on a subdomain, https://toot.example.com [1] [2]. Alice's feed is available at https://toot.example.com/@alice, but you can address her in toots with `@alice@example.com` (not `@alice@toot.example.com`).

[1] This is because I assume it is difficult/impossible to make Mastodon accessible at the same domain as other services. Could I just set up my web server to direct `https://example.com/@<wildcard>` to Mastodon, and all other URLs to their usual locations?

[2] What about https://example.com/toot/ as the base URL for a Mastodon instance?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] ~~This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).~~ N/A

**Comment by nolanlawson** [comment]
This isn't something we can support with the current architecture (see also #3740) and also it may create security concerns given the web's per-origin storage/sandbox model.

**Comment by Gargron** [comment]
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Serving_a_different_domain.md

As Nolan mentioned it doesn't play well with private posts.
