### ISSUE TITLE
[query] Can I host each user feed at a subdomain?

### ISSUE THREAD

**Issue by kwill** [tootsuite/mastodon#3740]
**User story:** I am a service host planning on running a Mastodon instance. I want to host each user on their own subdomain, so that they have their own domain. [1]

**Example:** Alice and Bob both have accounts at the https://example.com Mastodon instance. Instead of https://example.com/@alice and https://example.com/@bob their feeds are accessible at https://alice.example.com and https://bob.example.com. They are still addressed as `@alice@example.com` and `@bob@example.com`.

[1] This would be the first step to allowing users to replace it with their own domain, much like you can create a GitHub Pages site at `project.github.io`, and make it accessible from your own domain `project.net`. The next step would be figuring out how to address such users. Would Alice be `@alice@project.net` or remain `@alice@example.com`?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] ~~This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).~~ N/A

**Comment by nolanlawson** [comment]
I don't believe this is possible given the current architecture, no. The only workaround would be to give each user their own instance on their own subdomain.

**Comment by nightpool** [comment]
@kwill my understanding is that OStatus (the protocol) supports this, but mastodon (this implementation) does not. Nothing is stopping you from hacking a solution to this though.
