### ISSUE TITLE
Bridging ICANN and OpenNIC

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#3741]
I'd like Mastodon on OpenNIC to be able to talk to ICANN-only instances and vice-versa, through the use of multiple domains. An OpenNIC instance would have an OpenNIC domain AND an ICANN domain. Both domains would be functionally equivalent. This OpenNIC-ICANN "bridge" instance would be able to talk to both ICANN-only and OpenNIC-only instances, and boost content from OpenNIC-only instances to ICANN-only instances and vice-versa. Is this possible?

(This is different from #1211 as far as "boost content from OpenNIC-only instances to ICANN-only instances and vice-versa" is concerned: Yes, you need multiple domains for that, but how would the boosting work? Technically, you'd be boosting content from either "network" onto the "bridge", then others would boost from the "bridge" onto the *other* "network", but what happens if you do?)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by bortzmeyer** [comment]
The requested kludge is a good example of why RFC 2826 was written :-) https://www.rfc-editor.org/info/rfc2826

**Comment by SoniEx2** [comment]
Ignoring a problem is not a solution.

**Comment by bortzmeyer** [comment]
@SoniEx2 Bad solutions are not solutions.

**Comment by SoniEx2** [comment]
The solution is to store all boosted data locally, and access everything through a cache. When someone boosts something, you should ask the *instance that boosted it* (not the instance it came from) for the data, and if that instance has since cleared its cache it has to re-fetch everything. This way you actually get the data to propagate across Tor, I2P, and OpenNIC, without broken images and stuff.

**Comment by nightpool** [comment]
for someone who doesn't know what OpenNIC is, it would be useful if you provided a summary in this issue about how you would expect this to work

**Comment by nightpool** [comment]
In broad strokes, the trust model of OStatus is that all statuses are verified by fetching them from the authoritative server. That means that there are pretty thorny protocol and security problems you would have to resolve to get OStatus to work across incompatible networks, and you probably wouldn't be compatible with any other instance.

**Comment by SoniEx2** [comment]
Shouldn't the authoritative server for a boost be the person that boosted it?

**Comment by nightpool** [comment]
Absolutely. But the boost will reference another post, right? So to confirm that the boosted post is real, you have to verify it with the origin server. Otherwise I (nightpool@cybre.space) could make a boost of `gargron@mastodon.social` saying `OStatus sucks!!!`—even if he never made that status.

**Comment by SoniEx2** [comment]
Then you should ask if other servers know the unknown, and use them as proxies.

**Comment by nightpool** [comment]
@SoniEx2 the problem is that there is no provision for that in the *GNU social protocol* at the moment—the entire way it's built is structured around being able to talk to freely every site in the federation. Restructuring it otherwise would be very difficult.

**Comment by SoniEx2** [comment]
How do you currently handle the case of an instance going offline?
