### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by junkyardjai** [tootsuite/mastodon#3749]
tried to post but:
<img width="516" alt="screen shot 2017-06-14 at 1 51 42 pm" src="https://user-images.githubusercontent.com/29441634/27154198-0271f09e-5109-11e7-8a6f-49f1315c491d.png">

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
If the server is having high load errors please do not make new issues for it.
