### ISSUE TITLE
Flipword causing Mastodon UI to near-disappear

### ISSUE THREAD

**Issue by creatrixtiara** [tootsuite/mastodon#3753]
I was using [Flipword](http://flipword.co)'s Google Chrome (on MacOS Sierra) extension but it made Mastodon unusable. The UI shows up, and then disappears into a thin strip like below:

<img width="1279" alt="screen shot 2017-06-13 at 18 37 27" src="https://user-images.githubusercontent.com/8474427/27162267-b6022fce-51c3-11e7-94f0-0f9ba3eb1c6a.png">

Reducing the size of the window doesn't help.

I tried disabling other extensions and it seems this is the extension that breaks it. I've sent Flipword a message but am getting the feeling they'll say it's Mastodon's problem so I'm posting it here!

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
Can you open the Chrome console (Ctrl-Shift-I/Cmd-Shift-I) to see what the error is?

**Comment by creatrixtiara** [comment]
I did and there were no errors.

**Comment by nightpool** [comment]
If there's a third party extension that's breaking the web page, I don't
really see what we can do to fix it.

**Comment by Gargron** [comment]
Honestly, we can't predict what various extensions will do to us. I see no way to deal with this but close.
