### ISSUE TITLE
shortcuts: namely, N to start a new post

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#376]
it's in the title

**Comment by marrus-sh** [comment]
adding on to this would be keyboard navigation/selection of toots; ie using the arrow keys (and then potentially shortcuts for fav/reply/expand from there). this is a much less trivial feature to add though

**Comment by Gargron** [comment]
With the compose form being always open, why do you need a shortcut? What would it do, exactly? Also, just "n" is a useful letter to be used in text input, and ctrl+n opens a new window in the browser. I don't really understand this feature request. I do understand wanting to navigate toots with the keyboard and having shortcuts to reply, boost or favourite, though.

**Comment by outofrange** [comment]
I miss good old 'n' too - the compose form may always be open, but it's often not focused, which I equally often only realise after putting both my hands on the keyboard.

**Comment by lutoma** [comment]
Another addition to @marrus-sh's request: I'd love to be able to select columns by pressing 1, 2, and so on, like in TweetDeck (in combination with the arrow keys to select individual toots).

**Comment by James-Firth** [comment]
@Gargron Likely for people who are on a desktop/laptop and don't want to move their hands away from the keyboard.

@outofrange makes a good point.

**Comment by nclm** [comment]
Keyboard shortcuts are indeed one of the main missing thing from Twitter. Also: `gf` to go to favourites, `gp` to your profile, etc.

**Comment by jeepfromoil** [comment]
The title of this request https://github.com/tootsuite/mastodon/issues/2102 seems broader.

I commented there before noticing this issue (incl. recommendation to use numbers to navigate to columns).

**Comment by jeepfromoil** [comment]
> why do you need a shortcut?

@Gargron if more keyboard shortcuts are implemented (like `?` to display their list, `b` to boost a selected toot), it might best not to auto-focus on the compose field by default.

**Comment by puphime** [comment]
@Gargron because if your hands are on the keyboard you dont wanna have to use your mouse to click the text box

**Comment by wxcafe** [comment]
👍

**Comment by Krands** [comment]
This, is a about UX, not only UI.

There are certainly people mainly using the keyboard to navigate. This would help a lot.
