### ISSUE TITLE
Searching for hashtags should be case-insensitive

### ISSUE THREAD

**Issue by sdukhovni** [tootsuite/mastodon#3761]
If I search for a hashtag in the search box, I don't get any results unless I put the hashtag's name in lowercase.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Kimik0** [comment]
Confirmed on v1.4.3. It's a UI-only bug; using the API it's properly case-insensitive.

**Comment by unarist** [comment]
No, it would be an API problem:

![image](https://user-images.githubusercontent.com/705555/27176594-21fc65f2-51fe-11e7-85b1-1d72857a6582.png)

I've changed hashtag search logic on 1.4.2 (#3611), so probably it's a cause.

**Comment by Kimik0** [comment]
Hmm, that's strange. It works here:
`> print(#masto.gethashtagtl("NsFw", 2))`
`2`
`> print(#masto.gethashtagtl("nSfW", 2))`
`2`
`> print(#masto.gethashtagtl("NSFW", 2))`
`2`
`> print(#masto.gethashtagtl("nsfw", 2))`
`2`
`> print(masto.getinstancedetails().version)`
`1.4.3`
And no, I don't convert the hashtag to lowercase. It's sent as is.

**Comment by Kimik0** [comment]
Ah, don't mind me. I was just being daft and using the worng API call (hashtag timeline instead of search). You're correct, searching doesn't work unless the hashtag is lowercase.

**Comment by ZiiX** [comment]
Yea, this just recently came up because we use #UpperAndLowerCase for hashtags but search didn't recognize the # that began with an uppercase letter so folks thought it had gone away.

**Comment by mcrosson** [comment]
I've seen this with #Photography and #Photo hash tags for searches on photog.social.

**Comment by tassoman** [comment]
Also trends are affected (v.3.5.1)

![Screenshot 2022-04-13 at 23-26-10 Mastodon Italia Social](https://user-images.githubusercontent.com/92727/163273225-528c4d9a-8e5c-4d5d-9b93-afcd0e4ab948.png)
