### ISSUE TITLE
Show only public toot in profile, show all/reply in another tab

### ISSUE THREAD

**Issue by Technowix** [tootsuite/mastodon#3764]
Could be cool if, like Twitter, we can separate our "reply toots" from the profile page, and only show here what we really "post", like this :
![2017-06-15 11_11_53-technowix technowix _ twitter - waterfox](https://user-images.githubusercontent.com/1571367/27174222-9fcdfd3a-51bb-11e7-94ec-51609b6a5673.png)
Sorry if this is a duplicate, I didn't know what to query.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Oh look we implemented this and forgot this issue 😋
