### ISSUE TITLE
Streaming service not starting on Node 8? Due to uws.

### ISSUE THREAD

**Issue by Exagone313** [tootsuite/mastodon#3768]
Hi,

Just upgraded from 1.4.1 to 1.4.3, and also Node from 7.9.0 to 8.1.1 (I didn't make that update before just in case support wouldn't be ready). I'm running ArchLinux.

When the mastodon-streaming starts, it fails with errors due to `Compilation of µWebSockets has failed and there is no pre-compiled binary`: https://gist.github.com/Exagone313/bfb77c90854d26949dd9b2b99eda6b2a

I'm not sure what I'm supposed to do to bring my instance on (I'll try to downgrade Node and its dependencies - Node itself is not ok).

Also, thanks for your help.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
>Please install a supported C++11 compiler and reinstall the module 'uws'

Could you try doing that? Perhaps you don't have a C++11 compiler installed? I think that build-tools is part of Mastodon's recommended general dependencies in the production guide, but I am not sure - perhaps someone more knowledgeable could fill in here, as I didn't have this issue. ("reinstall the module" means re-running `yarn install`, I am assuming - or maybe `npm rebuild uws`)

**Comment by Exagone313** [comment]
I do. I have gcc 7.1.1. I have relaunched yarn install to be sure, it does not installs anything.
I'm going to try `npm rebuild uws`.

**Comment by nolanlawson** [comment]
Yep, `npm rebuild uws` would be great to document, e.g. in https://github.com/tootsuite/documentation/blob/9b9d1dce810f6fe2a51dfd632fe203bc3b4b3f0d/Running-Mastodon/Production-guide.md. I believe there have been similar issues in the past with another native dependency, `node-sass`.

**Comment by nolanlawson** [comment]
Please reopen if you think closing this issue is premature! But it sounds to me like you found a workaround. :)

**Comment by Exagone313** [comment]
Looks like I have to rebuild `uws` on each update?
