### ISSUE TITLE
Please add tags to releases

### ISSUE THREAD

**Issue by NicolasCARPi** [tootsuite/mastodon#3769]
Latest tag is v1.4.1 ;)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
What do you mean?

https://github.com/tootsuite/mastodon/releases
https://github.com/tootsuite/mastodon/tags

**Comment by NicolasCARPi** [comment]
Yeah nevermind just saw that. It's the command "git tag" which doesn't show all the tags for some reason (even after a git pull origin master)…

**Comment by NicolasCARPi** [comment]
Got it now, so apparently "git pull origin master" doesn't fetch the tags; and "git pull" does…

Quircky git =)

**Comment by Gargron** [comment]
`git fetch --tags`
