### ISSUE TITLE
[Usability] Move Save button above the fold in settings

### ISSUE THREAD

**Issue by MightyPork** [tootsuite/mastodon#3770]
Currently the save button is at the bottom of the page. That was OK until language filter checkboxes were added, but now it goes offscreen and it's not at all obvious you have to scroll down and click Save to make changes apply.

Proposal:
- Move the save button to the top
- Or, add some indicator like "Unsaved changes!" to the top, after any field is changed.

Here's the page in question (but the change would probably apply to all of them)
![captur111e](https://user-images.githubusercontent.com/2041118/27181486-17027fae-51d8-11e7-9549-dfb4125b2dec.PNG)

**Comment by foxsan48** [comment]
How is this? 
![screen shot 2017-06-16 at 4 56 48 pm](https://user-images.githubusercontent.com/495512/27215496-e0c0c5e4-52b4-11e7-9235-7adac00b57fb.png)

**Comment by MightyPork** [comment]
I like it @foxsan48

**Comment by foxsan48** [comment]
Cool, it is done :) (hence the reference) @MightyPork

**Comment by nolanlawson** [comment]
Makes sense to me. :)

**Comment by Cassolotl** [comment]
This has been done, I think!
