### ISSUE TITLE
Show an indicator on threaded toots

### ISSUE THREAD

**Issue by zcdunn** [tootsuite/mastodon#3774]
It would be useful if the UI included an indicator on toots that are threads. This would hint to users that they can click on the toot to see more rather than users having to click every toot to check. I've included a mockup below.

![mockup](https://user-images.githubusercontent.com/7121969/27189026-0bc618f4-51be-11e7-9b34-909888eb5b13.PNG)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
![7f981b7bbe](https://user-images.githubusercontent.com/184731/27192804-f3fff49e-51fc-11e7-9fa8-914a301891b4.png)

This is already a (subtle) thing

**Comment by zcdunn** [comment]
Could it be made less subtle? Does this indicate there are replies or that the original poster has replied to themselves?
