### ISSUE TITLE
Starting from v1.4.2, Mastodon depends on nodejs v6.0.0

### ISSUE THREAD

**Issue by ProgVal** [tootsuite/mastodon#3777]
As it was mentioned in #3409, Mastodon now requires Nodejs v6.0.0 (because of the minor version bump of postcss-smart-import in 943775fd9071d5c9c155aa10f6bad69ec8cc8758, I believe).

This version is not yet available everywhere. In particular, it is not even in Debian Unstable (although it is in Experimental), which makes it harder to install.

Would it be acceptable to revert this version bump?

Thanks

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
I don't believe it's easy to downgrade our Node version. You can easily install Node versions 6-8 on Ubuntu/Debian using these instructions: https://github.com/nodesource/distributions#installation-instructions

**Comment by Komic** [comment]
yup, they have a package for every major distribution, upgrading should be a breeze~

**Comment by ProgVal** [comment]
I know, but I do not want to add a third-party apt repository to limit risks of installing a compromised package.

**Comment by Exagone313** [comment]
See https://github.com/creationix/nvm (I used this before, but now I run the latest mainline version for Node as available on my distribution).

**Comment by ProgVal** [comment]
@Exagone313 I would rather pin node v6.0 from Debian Experimental, it looks easier

**Comment by Exagone313** [comment]
I wouldn't recommend messing with other Debian versions repository. They could compile packages with newer libc version (or compiled against other newer versions of libraries, but this is overkill), and you could either get a broken version of node or break your complete installation.

**Comment by nolanlawson** [comment]
Node v6 is the current active LTS version of Node; Node v4 is in maintenance mode and will drop out of maintenance in less than a year: https://github.com/nodejs/LTS#readme

We tend to run the latest version of most deps, and I'm pretty comfortable saying it's too much effort to support Node v4, even though some Linux distros may be behind the curve. NodeSource is a very trusted player in the Node space and personally I'd trust their PPA.
