### ISSUE TITLE
Interfacing with Twitter

### ISSUE THREAD

**Issue by ticki** [tootsuite/mastodon#3778]
Twitter has a nice API, and it'd be wonderful if Mastodon was able to interface with it. It would certainly mean that Mastodon could easily become much more popular through the simple interfacing with Twitter.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ticki** [comment]
My exact idea is something like this: You can bind your Twitter to your Mastodon. Tweets etc. will show up on your Mastodon timeline (with a Twitter icon next to them). Any interfacing will be repeated through the twitter API, so liking or retooting will result in faving and retweeting.

**Comment by ticki** [comment]
Actually, this might be somewhat simpler: Set up a Mastodon server which serves Twitter accounts.

**Comment by nolanlawson** [comment]
There is no technical reason that I'm aware of that you couldn't set up a Mastodon instance that simply mirrored whatever was on Twitter, yes. AFAIK there are no plans to support anything other than the OStatus protocol.

**Comment by Kimik0** [comment]
Twitter prohibits using their API in that way. You could make some software that does it for individual users, but I don't think it's a good idea to build it into Mastodon.

**Comment by nolanlawson** [comment]
Yeah it sounds like this is something explicitly prohibited in Twitter's ToS: https://dev.twitter.com/overview/terms/agreement-and-policy#b-maintain-the-integrity-of-twitters-products . 

Gonna close this issue, please reopen if my interpretation of their ToS is wrong.
