### ISSUE TITLE
Internal server error and WebSocket errors in console

### ISSUE THREAD

**Issue by sphinxc0re** [tootsuite/mastodon#3780]
When visiting the web app, I'm getting the following console output:
![screen shot 2017-06-15 at 21 27 55](https://user-images.githubusercontent.com/3702016/27198289-da47173e-5211-11e7-87df-d74292368fcc.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
It appears you are using a custom Content Security Policy which disallows the `wss://` connection. You'll need to modify your `Content-Security-Policy` to allow connections to `wss://mastodon.blue`, e.g. in your Nginx config or Apache config. Or you can remove the CSP header entirely.

It also seems you have a Referrer Policy which Chrome is rejecting ("strict-origin-when-cross-origin"), although it's unrelated to this issue.

**Comment by nolanlawson** [comment]
Please reopen if I'm incorrect in my diagnosis! :)

**Comment by sphinxc0re** [comment]
@nolanlawson Thank you very much. I will notify the instance maintainer
