### ISSUE TITLE
Limit displayed content of too long publications (toot/other OStatus)

### ISSUE THREAD

**Issue by Exagone313** [tootsuite/mastodon#3784]
Hi,

It looks like OStatus does not have a limit on messages (this is cool), only Mastodon fixes a limit of 500 characters, that can be changed with a little hacking (by instance admins).
The issue is with very long (in term of displayed lines) publications in the web UI, like in timelines. It becomes harder to scroll down.
My suggestion is to show only the top of such publication and add a "View more" button.
Here is [an example](https://share.elouworld.org/@Exagone313/195324) of a very large publication (not in public timeline for convenience), with 2048 lines, you can copy its link in the search field in web UI.
This joins the issue #255 that looks dead.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Kimik0** [comment]
Something like automatically insert a CW if a toot is longer than `n` characters. The functionality is already there, all it needs is one simple check at the point new toots are added to the local database.

**Comment by nightpool** [comment]
CWs can't have hashtags, links, or other types of rich text formatting in
them, so it's not quite as simple as all that, but you're right that most
of the work is there.

also this should be done on the client-side when displaying toots, rather
then on the server-side when adding them to the database imo.

**Comment by Kimik0** [comment]
CW text should behave like other content text I think (there's an issue for it, but it's bedtime for me really).

But that's not even needed here. Just make a check (length of content > n) → (add CW). The CW appears at the top, before the long content. It's not used to cut the content in two, only to warn viewers before they unhide it.

**Comment by nightpool** [comment]
ahh, I see what you mean. Yeah, that would be pretty doable.

**Comment by Exagone313** [comment]
Length is not enough, counting LF characters is needed also.

**Comment by nolanlawson** [comment]
This could potentially be solved with out IntersectionObserver implementation; if we do do this, I'd like to make sure it's performant (e.g. could get into a trap where you're constantly checking the height of the element and thus triggering layout).

**Comment by Gargron** [comment]
Fixed in #8205
