### ISSUE TITLE
Update hashtag columns as new toots come in

### ISSUE THREAD

**Issue by sdukhovni** [tootsuite/mastodon#3787]
Currently, when I have a hashtag column open and someone sends a new toot with that hashtag, the top of the column glows blue but the new toot isn't displayed unless I reload the page. I'd like it to be easier to keep track of hashtags in real time.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sdukhovni** [comment]
It'd also be nice to have this for columns showing threads.

**Comment by Gargron** [comment]
I believe this was a bug that was fixed.
