### ISSUE TITLE
Whitelist classes for HTML elements in statuses

### ISSUE THREAD

**Issue by sdukhovni** [tootsuite/mastodon#3790]
It's currently possible for a malicious OStatus server to send statuses that spoof parts of Mastodon's UI without violating the constraints of `sanitize_config.rb`:

```
<p>lewd <a class="status__content__spoiler-link" href="http://malware.ru/">Show more</a></p>
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
Note that similar appearance can be achieved with `class` attribute on `span` element, which available before my pull request:

```
<p>lewd <a href="http://malware.ru/"><span class="status__content__spoiler-link">Show more</span></a></p>
```

So we should filter class attributes in anywhere.

**Comment by nolanlawson** [comment]
Is this also the source of the "spinning" spans? I believe I saw something like `<span class="fa fa-spin"></span>` to achieve this.

**Comment by sdukhovni** [comment]
Yes, that's also a result of allowing arbitrary classes in statuses; it takes advantage of FontAwesome's "spinning icons" functionality.

**Comment by nightpool** [comment]
I'm working on a patch for this.

**Comment by sdukhovni** [comment]
Thanks @nightpool! This patch fixes the UI spoofing, but @unarist raised a very good point about fake links which is still unaddressed. I'll open it as a separate issue.
