### ISSUE TITLE
Change "toot" to "mastobate"

### ISSUE THREAD

**Issue by ticki** [tootsuite/mastodon#3795]
"toot" is childish and unprofessional, duh

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sn0wflakes** [comment]
And so is "mastobate", issue can be closed IMHO.

**Comment by nolanlawson** [comment]
Quick note to please keep it professional and use GitHub issues for valid bugs and feature requests.
