### ISSUE TITLE
Convert account URLs to the account@domail format.

### ISSUE THREAD

**Issue by ticki** [tootsuite/mastodon#3797]
For convenience,

    https://mastodon.social/@ticki

should be converted (e.g. on client side) to:

    @ticki@mastodon.social

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
The two things are not exactly the same; clicking one shows you the profile on its own home domain as a static page, whereas clicking the second shows the profile within your home instance's UI. I don't believe this is something we should change.
