### ISSUE TITLE
Direct messages shouldn't be boost-able

### ISSUE THREAD

**Issue by ticki** [tootsuite/mastodon#3798]
Currently, you can boost direct toots. Ideally, this should be disabled altogether.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ggtea** [comment]
relly? I can not boost direct toot on Web UI.

**Comment by Kimik0** [comment]
I think that was disabled in a semi-recent release. Are you on an old version perhaps?

**Comment by ticki** [comment]
I use mastodon.social, which is operated by @Gargron.

**Comment by unarist** [comment]
If you've correctly set the toot as `direct`, boost button will be replaced with non-clickable envelope icon:

![image](https://user-images.githubusercontent.com/705555/27231425-8ba4b848-52ed-11e7-84b3-75d450bec234.png)

**Comment by nolanlawson** [comment]
I don't believe you can boost direct toots, yeah. Please reopen if you have steps to reproduce and/or a screenshot illustrating the problem.
