### ISSUE TITLE
Some specific accounts see the *home* timeline blank while after launching / pressing F5 on the browser

### ISSUE THREAD

**Issue by cj3029412** [tootsuite/mastodon#3800]
Hi, I am the admin at www.nekototon.com (currently v1.4.3), another instance of Mastodon. Our users and of course I myself are enjoying Mastodon life. But as shown in title, some specific accounts see the home timeline blank while after launching / pressing F5 on the browser:

[Screenshot](https://www.nekotodon.com/media/FuaOMdV5EbE-rxYRD2s)

- By my memory, after upgrading to some 1.4rc from 1.3.3 (I am not sure), some of  www.nekotodon.com specific accounts see the home timeline blank just after launching the browser.
- Also, while the home timeline appears and refresh automatically, if the specific users press F5, the home timeline always come back to complete blank.
- Federation and notification panes seem to keep flowing, no problem.
- I myself am one of the accounts stuck with the problem.
- I have account A (in trouble) and B (no problem).
- I tried Chrome, Firefox, Vivaldi and cleared cookies and browser cache but in vain.
- The same is when I use Pawoo app with Nexus (Android).
- What is curious is that other users have no this kind of trouble at all.
- In addition, when I log in to other instances with the same browser, no problem.

(17/6/2017, 4:30am JPT:UTC+9, edited / added below)
- In the home pane of the browser window, I noticed that the message:

> Your home feed is empty. If you have been inactive for a while, it will be regenerated for you soon.

blinks after every 18 to 20 seconds without any user operations.

(17/6/2017, 10:10am JPT:UTC+9, edited / added below)

- Not local timeline, but "home" timeline, sorry.

Regarding error.log and access.log of nginx,

- error.log: Nothing seems related to this.
- access log (1): like this where xxx.yy.zzz.aa is replaced my IP address accessing from, just after pressing F5 with the *troubled* user account:

$ sudo cat /var/log/nginx/access.log | grep xxx.yy.zzz.aa | grep home | tail -n 4
> xxx.yy.zzz.aa - - [17/Jun/2017:10:50:43 +0900] "GET /api/v1/timelines/home HTTP/2.0" 200 437 "https://www.nekotodon.com/web/getting-started" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36" "-"
xxx.yy.zzz.aa - - [17/Jun/2017:10:51:19 +0900] "GET /api/v1/timelines/home HTTP/2.0" 200 438 "https://www.nekotodon.com/web/timelines/public" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36" "-"
xxx.yy.zzz.aa - - [17/Jun/2017:10:51:24 +0900] "GET /api/v1/timelines/home HTTP/2.0" 200 438 "https://www.nekotodon.com/web/timelines/public" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36" "-"
xxx.yy.zzz.aa - - [17/Jun/2017:10:52:32 +0900] "GET /api/v1/timelines/home HTTP/2.0" 200 437 "https://www.nekotodon.com/web/timelines/public" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36" "-"

- access log (2): when accessing from *no-problem* account:

$ sudo cat /var/log/nginx/access.log | grep xxx.yy.zzz.aa | grep home | tail -n 4
> xxx.yy.zzz.aa - - [17/Jun/2017:11:08:19 +0900] "GET /api/v1/streaming/?access_token=some_nice_encrypted_string_like_ce21ef93eee51b6b1723ebf1520b&stream=user HTTP/1.1" 101 6 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36" "-"
> xxx.yy.zzz.aa - - [17/Jun/2017:11:08:20 +0900] "GET /favicon.ico HTTP/2.0" 200 1085 "https://www.nekotodon.com/web/getting-started" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36" "-"
> xxx.yy.zzz.aa - - [17/Jun/2017:11:08:20 +0900] "GET /api/v1/timelines/home HTTP/2.0" 200 6200 "https://www.nekotodon.com/web/getting-started" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36" "-"
> xxx.yy.zzz.aa - - [17/Jun/2017:11:08:21 +0900] "GET /api/v1/notifications HTTP/2.0" 200 3775 "https://www.nekotodon.com/web/getting-started" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36" "-"

They seem different each other around streaming access token. But I have no idea what to do.
Please give me some advice. Next, what server log will I need to disclose to you?

Regards,
@nekokurumihime

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Jehops** [comment]
We are seeing this as well.  This is just a wild shot in the dark, but did you unpin the Home feed before this stared?  I changed a  bunch of things around the same time, so I can't be certain, but I did notice the problem after unpinning then re-pinning the Home feed.   After a quick look at the database schema and data, I'm not clear where this is being stored, but if there is anything I can test, just let me know.

**Comment by cj3029412** [comment]
Hi Jehops, thank you for the comemnt.

> Did you unpin the Home feed before this stared?
Yes, I did unpin and re-pin (for the first time) some days before this phenomenon.
Also, this time I did:
 - Account A (mine, in trouble with this): Unpin and re-pin several times but in vain.
 - Account B (mine, no problem): Unpin and re-pin several times. It seems to keep flowing home timeline.

> if there is anything I can test, just let me know.
Please feel free to create your account at www.nekotodon.com and check it. Then you need access / error logs or tables in CSV file, I am happy to collaborate and provide such data to you and the team.

On the other hand, so far this phenomenon has been reported by only 2 users of my instance. One of them is me. Another is my friend who is kind and has other Mastodon accounts at other instances which are working well for him. So actually, in no hurry. Just wanted to make some contribution to the Mastodon community

Regards,

**Comment by cj3029412** [comment]
Hi, this time I compared Chrome web page source when logging in account A (in trouble) and B (no problem) and noticed something:

- Account A:
> <script id='initial-state' type='application/json'>{"meta":{"streaming_api_base_url":"wss://www.nekotodon.com","access_token":"some-nice-encrypted-string-such-as-96a5d165967a8ae6fa4bf25016f339f4","locale":"ja","domain":"www.nekotodon.com","me":1,"admin":1,"boost_modal":false,"delete_modal":true,"auto_play_gif":true},"compose":{"me":1,"default_privacy":"public"},"accounts":{"1":{"id":1,"username":"nekokurumihime","acct":"nekokurumihime","display_name":"nekokurumihime✅","locked":false,"created_at":"2017-06-14T10:13:02.890Z","followers_count":12,"following_count":24,"statuses_count":74,"note":"\u003cp\u003eくーちゃんです。\u003c/p\u003e","url":"https://www.nekotodon.com/@nekokurumihime","avatar":"https://www.nekotodon.com/system/accounts/avatars/000/000/001/original/1a82546326e5484a.jpeg?1497497570","avatar_static":"https://www.nekotodon.com/system/accounts/avatars/000/000/001/original/1a82546326e5484a.jpeg?1497497570","header":"https://www.nekotodon.com/headers/original/missing.png","header_static":"https://www.nekotodon.com/headers/original/missing.png"}},"media_attachments":{"accept_content_types":["image/jpeg","image/png","image/gif","video/webm","video/mp4"]},"settings":{"onboarded":true,"home":{"shows":{"reblog":true,"reply":true},"regex":{"body":""}},"notifications":{"alerts":{"follow":true,"favourite":true,"reblog":true,"mention":true},"shows":{"follow":true,"favourite":true,"reblog":true,"mention":true},"sounds":{"follow":true,"favourite":true,"reblog":true,"mention":true}},"community":{"regex":{"body":""}},"public":{"regex":{"body":""}},"columns":[{"id":"COMPOSE","uuid":"90989d1e-5250-4d20-b541-1bb555988990","params":{}},{"id":"COMMUNITY","uuid":"3c0cc0ee-9021-4d42-90fe-f26bb45f37cf","params":{}},{"id":"PUBLIC","uuid":"7fe24cee-4a93-4fb5-92fa-82808ffd6b4a","params":{}}]}}</script>

- Account B:
> <script id='initial-state' type='application/json'>{"meta":{"streaming_api_base_url":"wss://www.nekotodon.com","access_token":"some-another-nice-encrypted-string-such-as-cd2c72dc4864567c7b7a23d29d5e321b","locale":"ja","domain":"www.nekotodon.com","me":14,"admin":1,"boost_modal":false,"delete_modal":true,"auto_play_gif":true},"compose":{"me":14,"default_privacy":"public"},"accounts":{"14":{"id":14,"username":"gebokuchan","acct":"gebokuchan","display_name":"gebokuchan","locked":false,"created_at":"2017-06-14T12:29:37.562Z","followers_count":15,"following_count":24,"statuses_count":48,"note":"\u003cp\u003eくーちゃんの下僕です。写真はみーちゃんです。\u003c/p\u003e","url":"https://www.nekotodon.com/@gebokuchan","avatar":"https://www.nekotodon.com/system/accounts/avatars/000/000/014/original/f8d50a4b94075782.jpg?1497443885","avatar_static":"https://www.nekotodon.com/system/accounts/avatars/000/000/014/original/f8d50a4b94075782.jpg?1497443885","header":"https://www.nekotodon.com/headers/original/missing.png","header_static":"https://www.nekotodon.com/headers/original/missing.png"},"1":{"id":1,"username":"nekokurumihime","acct":"nekokurumihime","display_name":"nekokurumihime✅","locked":false,"created_at":"2017-06-14T10:13:02.890Z","followers_count":12,"following_count":24,"statuses_count":74,"note":"\u003cp\u003eくーちゃんです。\u003c/p\u003e","url":"https://www.nekotodon.com/@nekokurumihime","avatar":"https://www.nekotodon.com/system/accounts/avatars/000/000/001/original/1a82546326e5484a.jpeg?1497497570","avatar_static":"https://www.nekotodon.com/system/accounts/avatars/000/000/001/original/1a82546326e5484a.jpeg?1497497570","header":"https://www.nekotodon.com/headers/original/missing.png","header_static":"https://www.nekotodon.com/headers/original/missing.png"}},"media_attachments":{"accept_content_types":["image/jpeg","image/png","image/gif","video/webm","video/mp4"]},"settings":{"onboarded":true,"home":{"shows":{"reblog":true,"reply":true},"regex":{"body":""}},"notifications":{"alerts":{"follow":true,"favourite":true,"reblog":true,"mention":true},"shows":{"follow":true,"favourite":true,"reblog":true,"mention":true},"sounds":{"follow":true,"favourite":true,"reblog":true,"mention":true}},"community":{"regex":{"body":""}},"public":{"regex":{"body":""}},"columns":[{"id":"COMPOSE","uuid":"31bd758b-66f6-4758-a853-c8f037236719","params":{}},{"id":"HOME","uuid":"f3fdfee8-82bc-4db6-92c5-9dbf908344cd","params":{}},{"id":"PUBLIC","uuid":"25f9eda8-5634-4984-b23f-d59bdb0156ac","params":{}},{"id":"NOTIFICATIONS","uuid":"11642400-a46d-45eb-bc85-14d6d49175b4","params":{}}]}}</script>

I noticed that their source / script volume are different each other at a glance. Would this be a clue to solve this problem? Please kindly give some advice.

Regards,

**Comment by cj3029412** [comment]
Hi,

Yesterday one of my users, who couldn't see his home timeline flowing with his account (X), created a new account (Y).
With the new account (Y), his home timeline keeps flowing by browser reloading or pressing F5.

Regards,

**Comment by saper** [comment]
437 / 438 bytes API response seems to be less than the "correct" 1038. What is the contents of the API requests/responses?

**Comment by cj3029412** [comment]
Hi saper,

Indeed... thank you for comment.
So sorry, but I decided to make a clean installation of Mastodon and did it just yesterday.
Since then, there seems no problem.

In fact, I noticed that I had done wrong configurations of ruby, rbenv, and perhaps node.js. I had referred to some unofficial production guiding tips. That is definitely one of the reasons my instance acted in a bad way.

This time, I went along with the official Production guide with enough understandings of what fundamental components (e.g. ruby, rbenv, node.js etc. etc.) are and where they are installed.

Thank you saper, Jehops and all who looked through this thread.
Soon I am going to close this topic if you all need no info from me further.

Regards,

**Comment by cj3029412** [comment]
P.S, now running well with v1.4.7

Thank you.

**Comment by Jehops** [comment]
If you have any specific details about what you suspect changed, that would be useful.  I am still seeing this issue for one user running 1.4.7.  At one point, I also wiped everything clean, even the database, but the problem persisted.  The user with the same account, 1, had the same issue, but other users did not.

Here is a snippet of the nginx access log when I refresh the page and the entries in the timeline disappear.  Nothing stands out to me.

```
142.68.134.140 - - [05/Jul/2017:16:26:14 -0300] "GET /api/v1/streaming/?access_token=blah&stream=user HTTP/1.1" 101 2505 "-" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:26:14 -0300] "GET /web/getting-started HTTP/2.0" 200 1614 "-" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:26:14 -0300] "GET /api/v1/streaming/?access_token=blah&stream=user HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:26:15 -0300] "GET /emoji/1f602.svg HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/getting-started" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:26:15 -0300] "GET /api/v1/notifications HTTP/2.0" 200 28 "https://mastodon.ftfl.ca/web/getting-started" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:26:15 -0300] "GET /api/v1/timelines/home HTTP/2.0" 200 28 "https://mastodon.ftfl.ca/web/getting-started" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"

142.68.134.140 - - [05/Jul/2017:16:29:14 -0300] "GET /api/v1/streaming/?access_token=blah&stream=user HTTP/1.1" 101 6989 "-" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:14 -0300] "GET /api/v1/streaming/?access_token=blah&stream=public HTTP/1.1" 101 7238 "-" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:14 -0300] "GET /web/timelines/public HTTP/2.0" 200 1613 "-" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:15 -0300] "GET /emoji/1f602.svg HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:15 -0300] "GET /api/v1/notifications HTTP/2.0" 200 28 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:15 -0300] "GET /api/v1/timelines/home HTTP/2.0" 200 28 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:15 -0300] "GET /api/v1/timelines/public HTTP/2.0" 200 7350 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:15 -0300] "GET /emoji/2611.svg HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:16 -0300] "GET /emoji/2705.svg HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:16 -0300] "GET /emoji/1f43d.svg HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:16 -0300] "GET /emoji/1f618.svg HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:16 -0300] "GET /emoji/1f4e3.svg HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:16 -0300] "GET /emoji/1f4bb.svg HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:16 -0300] "GET /emoji/1f403.svg HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:16 -0300] "GET /emoji/1f427.svg HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:16 -0300] "GET /emoji/1f613.svg HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:16 -0300] "GET /emoji/1f430.svg HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
142.68.134.140 - - [05/Jul/2017:16:29:16 -0300] "GET /avatars/original/missing.png HTTP/2.0" 304 0 "https://mastodon.ftfl.ca/web/timelines/public" "Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 conkeror/1.0.3"
```

**Comment by nightpool** [comment]
glad to see things are working now!

**Comment by Jehops** [comment]
Hi @nightpool, could the issue be re-opened until we get it resolved on our end, or until we figure out what's going on?

**Comment by saper** [comment]
@jehops any way to get the contents of those API calls? Haven't tried bumping up the logging level yet

**Comment by nightpool** [comment]
@jehops sorry, didn't see your comment.

**Comment by nightpool** [comment]
@Jehops if you look in Redis, can you see timeline for this user? what about other users?

**Comment by Jehops** [comment]
@nightpool, where should I be looking, in the redis logs?

`redis.log`, didn't show much.  I just see lots of the messages below.  

```
40904:M 05 Jul 17:28:00.185 * Background saving terminated with success
40904:M 05 Jul 17:33:01.042 * 10 changes in 300 seconds. Saving...
40904:M 05 Jul 17:33:01.043 * Background saving started by pid 47737
47737:C 05 Jul 17:33:01.078 * DB saved on disk
```

After bumping the `loglevel` from `notice` to `debug`, there is a bit more.

```
48020:M 05 Jul 17:41:16.356 - DB 0: 151 keys (21 volatile) in 256 slots HT.
48020:M 05 Jul 17:41:16.357 - 9 clients connected (0 slaves), 1310768 bytes in use
48020:M 05 Jul 17:41:21.694 - DB 0: 151 keys (21 volatile) in 256 slots HT.
48020:M 05 Jul 17:41:21.694 - 9 clients connected (0 slaves), 1376480 bytes in use
48020:M 05 Jul 17:41:27.009 - DB 0: 151 keys (21 volatile) in 256 slots HT.
48020:M 05 Jul 17:41:27.009 - 9 clients connected (0 slaves), 1278000 bytes in use
48020:M 05 Jul 17:41:32.278 - DB 0: 151 keys (21 volatile) in 256 slots HT.
48020:M 05 Jul 17:41:32.279 - 9 clients connected (0 slaves), 1409248 bytes in use
48020:M 05 Jul 17:41:36.489 - Accepted 127.0.0.1:37520
48020:M 05 Jul 17:41:36.506 - Accepted 127.0.0.1:37521
48020:M 05 Jul 17:41:36.751 - Accepted 127.0.0.1:37522
48020:M 05 Jul 17:41:37.571 - DB 0: 153 keys (23 volatile) in 256 slots HT.
48020:M 05 Jul 17:41:37.571 - 12 clients connected (0 slaves), 1331064 bytes in use
48020:M 05 Jul 17:41:42.657 - Accepted 127.0.0.1:37528
48020:M 05 Jul 17:41:42.700 - Accepted 127.0.0.1:37529
48020:M 05 Jul 17:41:42.823 - DB 0: 160 keys (30 volatile) in 256 slots HT.
48020:M 05 Jul 17:41:42.823 - 14 clients connected (0 slaves), 1483688 bytes in use
48020:M 05 Jul 17:41:48.073 - DB 0: 160 keys (30 volatile) in 256 slots HT.
48020:M 05 Jul 17:41:48.074 - 14 clients connected (0 slaves), 1385384 bytes in use
48020:M 05 Jul 17:41:53.347 - DB 0: 160 keys (30 volatile) in 256 slots HT.
48020:M 05 Jul 17:41:53.347 - 14 clients connected (0 slaves), 1385384 bytes in use
48020:M 05 Jul 17:41:58.661 - DB 0: 160 keys (30 volatile) in 256 slots HT.
48020:M 05 Jul 17:41:58.661 - 14 clients connected (0 slaves), 1385384 bytes in use
48020:M 05 Jul 17:42:03.932 - DB 0: 160 keys (30 volatile) in 256 slots HT.
48020:M 05 Jul 17:42:03.932 - 14 clients connected (0 slaves), 1385384 bytes in use
48020:M 05 Jul 17:42:09.171 - DB 0: 160 keys (30 volatile) in 256 slots HT.
48020:M 05 Jul 17:42:09.171 - 14 clients connected (0 slaves), 1385384 bytes in use
48020:M 05 Jul 17:42:14.444 - DB 0: 160 keys (30 volatile) in 256 slots HT.
48020:M 05 Jul 17:42:14.445 - 14 clients connected (0 slaves), 1385416 bytes in use
```

**Comment by saper** [comment]
From the capture sniffed by @Jehops I can see the following entries sent via WebSockets:

event notification of type `notification` with the payload

````json
{
  "id": 11,
  "type": "mention",
  "created_at": "2017-07-05T20:28:34.669Z",
  "account": {
    "id": 38,
    "username": "Jehops",
    "acct": "Jehops@mastodon.social",
    "display_name": "Joseph Mingrone",
    "locked": false,
    "created_at": "2017-06-23T13:22:37.053Z",
    "followers_count": 1,
    "following_count": 0,
    "statuses_count": 6,
    "note": "<p><a href=\"https://ftfl.ca/\" rel=\"nofollow noopener\" target=\"_blank\"><span class=\"invisible\">https://</span><span class=\"\">ftfl.ca/</span><span class=\"invisible\"></span></a></p>",
    "url": "https://mastodon.social/@Jehops",
    "avatar": "https://mastodon.ftfl.ca/system/accounts/avatars/000/000/038/original/f5cc23f54d27d099.jpg?1498224157",
    "avatar_static": "https://mastodon.ftfl.ca/system/accounts/avatars/000/000/038/original/f5cc23f54d27d099.jpg?1498224157",
    "header": "https://mastodon.ftfl.ca/headers/original/missing.png",
    "header_static": "https://mastodon.ftfl.ca/headers/original/missing.png"
  },
  "status": {
    "id": 2030,
    "created_at": "2017-07-05T20:28:34.000Z",
    "in_reply_to_id": null,
    "in_reply_to_account_id": null,
    "sensitive": false,
    "spoiler_text": "",
    "visibility": "direct",
    "language": "en",
    "application": null,
    "account": {
      "id": 38,
      "username": "Jehops",
      "acct": "Jehops@mastodon.social",
      "display_name": "Joseph Mingrone",
      "locked": false,
      "created_at": "2017-06-23T13:22:37.053Z",
      "followers_count": 1,
      "following_count": 0,
      "statuses_count": 6,
      "note": "<p><a href=\"https://ftfl.ca/\" rel=\"nofollow noopener\" target=\"_blank\"><span class=\"invisible\">https://</span><span class=\"\">ftfl.ca/</span><span class=\"invisible\"></span></a></p>",
      "url": "https://mastodon.social/@Jehops",
      "avatar": "https://mastodon.ftfl.ca/system/accounts/avatars/000/000/038/original/f5cc23f54d27d099.jpg?1498224157",
      "avatar_static": "https://mastodon.ftfl.ca/system/accounts/avatars/000/000/038/original/f5cc23f54d27d099.jpg?1498224157",
      "header": "https://mastodon.ftfl.ca/headers/original/missing.png",
      "header_static": "https://mastodon.ftfl.ca/headers/original/missing.png"
    },
    "media_attachments": [],
    "mentions": [
      {
        "url": "https://mastodon.ftfl.ca/@jrm",
        "acct": "jrm",
        "id": 1,
        "username": "jrm"
      }
    ],
    "tags": [],
    "uri": "tag:mastodon.social,2017-07-05:objectId=11816247:objectType=Status",
    "content": "<p><span class=\"h-card\"><a href=\"https://mastodon.ftfl.ca/@jrm\" class=\"u-url mention\" rel=\"nofollow noopener\" target=\"_blank\">@<span>jrm</span></a></span> test4</p>",
    "url": "https://mastodon.social/users/Jehops/updates/3611805",
    "reblogs_count": 0,
    "favourites_count": 0,
    "reblog": null,
    "favourited": false,
    "reblogged": false,
    "muted": false
  }
}
````

and another one with event type `update`

````json
{
  "id": 2030,
  "created_at": "2017-07-05T20:28:34.000Z",
  "in_reply_to_id": null,
  "in_reply_to_account_id": null,
  "sensitive": false,
  "spoiler_text": "",
  "visibility": "direct",
  "language": "en",
  "application": null,
  "account": {
    "id": 38,
    "username": "Jehops",
    "acct": "Jehops@mastodon.social",
    "display_name": "Joseph Mingrone",
    "locked": false,
    "created_at": "2017-06-23T13:22:37.053Z",
    "followers_count": 1,
    "following_count": 0,
    "statuses_count": 6,
    "note": "<p><a href=\"https://ftfl.ca/\" rel=\"nofollow noopener\" target=\"_blank\"><span class=\"invisible\">https://</span><span class=\"\">ftfl.ca/</span><span class=\"invisible\"></span></a></p>",
    "url": "https://mastodon.social/@Jehops",
    "avatar": "https://mastodon.ftfl.ca/system/accounts/avatars/000/000/038/original/f5cc23f54d27d099.jpg?1498224157",
    "avatar_static": "https://mastodon.ftfl.ca/system/accounts/avatars/000/000/038/original/f5cc23f54d27d099.jpg?1498224157",
    "header": "https://mastodon.ftfl.ca/headers/original/missing.png",
    "header_static": "https://mastodon.ftfl.ca/headers/original/missing.png"
  },
  "media_attachments": [],
  "mentions": [
    {
      "url": "https://mastodon.ftfl.ca/@jrm",
      "acct": "jrm",
      "id": 1,
      "username": "jrm"
    }
  ],
  "tags": [],
  "uri": "tag:mastodon.social,2017-07-05:objectId=11816247:objectType=Status",
  "content": "<p><span class=\"h-card\"><a href=\"https://mastodon.ftfl.ca/@jrm\" class=\"u-url mention\" rel=\"nofollow noopener\" target=\"_blank\">@<span>jrm</span></a></span> test4</p>",
  "url": "https://mastodon.social/users/Jehops/updates/3611805",
  "reblogs_count": 0,
  "favourites_count": 0,
  "reblog": null,
  "favourited": false,
  "reblogged": false,
  "muted": false
}
````

**Comment by Jehops** [comment]
Another point that may be useful is that the toots that disappear from this one user's timeline after the page has been reloaded do stick around in the federated timeline.

**Comment by saper** [comment]
Timing of the requests:

| # | Address A | Port A | Address B | Port B | Packets | Bytes | Packets A → B | Bytes A → B | Packets B → A | Bytes B → A | Rel Start      | Duration  | Bits/s A → B | Bits/s B → A |
|---|-------------|----------|-------------|----------|-----------|---------|-----------------|---------------|-----------------|--------------|------------------|-------------|----------------|-----------------|
| 1 | 127.0.0.1 | 12584  | 127.0.0.1 | 4000   | 8       | 468   | 4             | 238         | 4             | 230         | 0,000000000    | 4,0032    | 475,62       | 459,63       |
| 2 | 127.0.0.1 | 61445  | 127.0.0.1 | 4000   | 243     | 15454 | 81            | 5016        | 162           | 10438       | 0,000014000    | 2402,1651 | 16,70        | 34,76        |
| 3 | 127.0.0.1 | 35956  | 127.0.0.1 | 4000   | 11      | 2424  | 7             | 1892        | 4             | 532         | 4,717309000    | 24,4090   | 620,10       | 174,36       |
| 4 | 127.0.0.1 | 52108  | 127.0.0.1 | 4000   | 20      | 7495  | 10            | 2072        | 10            | 5423        | 29,850050000   | 53,5660   | 309,45       | 809,92       |
| 5 | 127.0.0.1 | 30655  | 127.0.0.1 | 4000   | 99      | 12216 | 37            | 3728        | 62            | 8488        | 84,106958000   | 765,9658  | 38,94        | 88,65        |
| 6 | 127.0.0.1 | 37524  | 127.0.0.1 | 4000   | 9       | 2300  | 5             | 1772        | 4             | 528         | 850,265645000  | 0,0875    | 161942,95    | 48253,88     |
| 7 | 127.0.0.1 | 37530  | 127.0.0.1 | 4000   | 156     | 14229 | 56            | 4918        | 100           | 9311        | 850,894646000  | 1420,8914 | 27,69        | 52,42        |
| 8 | 127.0.0.1 | 33760  | 127.0.0.1 | 4000   | 144     | 11359 | 50            | 4495        | 94            | 6864        | 1048,425341000 | 1353,7398 | 26,56        | 40,56        |
| 9 | 127.0.0.1 | 31779  | 127.0.0.1 | 4000   | 19      | 2894  | 8             | 1964        | 11            | 930         | 2272,528827000 | 129,6363  | 121,20       | 57,39        |
| 10 | 127.0.0.1 | 37061  | 127.0.0.1 | 4000   | 11      | 2432  | 7             | 1900        | 4             | 532         | 2275,187490000 | 2,5750    | 5902,91      | 1652,81      |
| 11 | 127.0.0.1 | 22923  | 127.0.0.1 | 4000   | 19      | 2896  | 8             | 1966        | 11            | 930         | 2277,840798000 | 124,3243  | 126,51       | 59,84        |
 
Stream 4 above (29,86005000 relative start) seems to deliver the notifications.

Streams 1 .. 8 are `?stream=user` calls

Probably refresh happened between stream 8 and 9:

Stream 9 is a `?stream=user` call
Stream 10 is a `?stream=public:local` call
Stream 11 is a `?stream=public` call

**Comment by saper** [comment]
For the working user, there 4 requests (8 flows) and all of them go to the `?stream=user` endpoint.

In a response to 2 requests one notification and one update are sent, but a sequence of 3 `?stream=user`, `?stream=public:local`, `?stream=public` calls seems to be missing (after reload?)

**Comment by egypturnash** [comment]
I'm seeing this on my instance (https://dragon.style, currently running 2.0.0.rc2, I should probably update.)

This is happening to my admin account, who has unpinned and rearranged the home timeline, to a user, whose home-timeline-unpinning status is unknown, and to to a new test account I just created, who definitely hasn't done this.

Running `docker-compose run --rm web rake mastodon:feeds:build` will repopulate them, but any new toots added thereafter vanish once I hit 'reload' on the web browser.

**Comment by Gargron** [comment]
Think we fixed this one.
