### ISSUE TITLE
List direct toots, you've sent.

### ISSUE THREAD

**Issue by ticki** [tootsuite/mastodon#3801]
Tracking what's going on in DM conversation is pretty hard currently.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by rummik** [comment]
Seems like this would be resolved by #4514

**Comment by Cassolotl** [comment]
#4514 has been merged now so this can probably be closed?
