### ISSUE TITLE
if you use the API as documented, you can only set your avatar to the first image you set as your avatar using the API

### ISSUE THREAD

**Issue by tinruufu** [tootsuite/mastodon#3804]
this behaviour is pretty weird, and i'm still not 100% sure it's not something i'm doing wrong or a bug in the client library i'm using, but here are some steps to reproduce what i'm observing. there are probably cleaner ways to demonstrate it, but these are the tools i'm familiar with:

- install [`mastodon.py`](https://github.com/halcy/Mastodon.py) (`pip install mastodon.py`)
- set it up (follow the readme)
- find yourself two png images
- run something along the lines of:
```python
import base64
mastodon.account_update_credentials(
    avatar='data:image/png;base64,{}'.format(
        base64.b64encode(open('test image one.png', 'rb').read()).decode('utf-8')
    )
)
```
- observe that your avatar is changed
- run the same thing as above, but with a different image
- observe that the api call claims to succeed, but your avatar is still `test image one.png`

optional bonus step: change your avatar in the web ui, and then set your avatar to any image using the API again, and observe that it is changed back to `test image one.png`

if this is actually a mastodon bug, and not a bug in my code or Mastodon.py, this means the reason i opened #692 is still unfulfilled; [the borb](https://mastodon.social/@rowletbot) has been static since i [adopted this feature](https://github.com/tinruufu/rowletbot/commit/e44df638b8432dbd169702186fc67013870d6fb4)

----

only happens when you use base64; [this change](https://github.com/tinruufu/rowletbot/commit/ebf14f75ed3b60c648b70d739ce6b506201b209c) fixed the borb

**Comment by nightpool** [comment]
I'm guessing the problem has to do with a lack of obfuscated filenames on this field.

 - the first upload uses the auto-generated filename `data.png`, which uploads to something like https://files.mastodon.social/accounts/avatars/000/025/677/original/data.png
 - the second uses the same filename, rather then a random one, which for some reason tries to overwrite the previously uploaded file—something it can't do.

The root cause here is in the paperclip s3 adapter: we should be using hashes rather then uploaded filenames.

**Comment by Kimik0** [comment]
I just tried to test it myself, but it seems to work as it should. Even when I reuse filenames the file gets updated properly when a new image is uploaded. What doesn't immediately update is the web UI. I had to check the plain user page to see the new image some of the time.

The original filenames should really be replaced with some standardized string though for privacy reasons.

**Comment by tinruufu** [comment]
@Kimik0 are you using base64 or form upload or…?

**Comment by Kimik0** [comment]
That was multipart/form-data. The API documentation isn't very clear yet, but Gargron confirmed in https://github.com/tootsuite/documentation/issues/267#issuecomment-304332222 that both form and base64 are okay. I use curl's `--form "param=@filename"` functionality to upload files.

**Comment by wxcafe** [comment]
is this still a thing?

**Comment by NKudryavka** [comment]
Yes, reusing filename still causes not changing avatar, even using multipart/form-data upload.

In the code below, changing "Image name to upload"(= real data of image) not affects to avatar.
However, changing `avatar.options.filename` changes avatar and reusing filename results in avatar's changing to first uploaded one in the filename.
In every upload, api returns result as if upload succeeded.
```coffee
rp = require 'request-promise-native'
fs = require 'fs'
msconfig = <url and my secret token>
mastodon = rp.defaults
  baseUrl: msconfig.api_url
  auth:
    bearer: msconfig.access_token
  json: true

mastodon.patch 'accounts/update_credentials',
  formData:
    avatar:
      value: fs.readFileSync 'Image name to upload'
      options:
        filename: 'icon.png'
        contentType: 'image/png'
.then console.log
.catch console.log
```
