### ISSUE TITLE
Rename "boost" to "retoot"

### ISSUE THREAD

**Issue by ticki** [tootsuite/mastodon#3806]
There is a great deal of confusion, for understandable reasons, around this term. I think it's important to get it right once.

To mirror twitters naming convention (and observing that 80% or more will probably have used twitter), it would make more sense to use the term "retoot", which you can see through a search is already way more used than "boost".

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by SoniEx2** [comment]
Trademark laws.

**Comment by ticki** [comment]
Really? How can you trademark re-____?

**Comment by clarcharr** [comment]
If we start seeming too much like Twitter they might be willing to sue, and a FOSS project like this doesn't have the legal team to refute that.

**Comment by thepeoplesbourgeois** [comment]
The important thing to remember is context. If this weren't a social network with clear parallels to their own competing product, then Twitter would have far less ground to make the legal claim that the choice of the word was to legitimately highlight that parallel.

As it is, there's not really any way not to make the case it wouldn't be.

**Comment by Gargron** [comment]
Boost comes from "signal boost" which is what you're doing when you're sharing stuff. I'm not gonna change that. It's already well established terminology after many many months of use.

**Comment by ticki** [comment]
@Gargron Fair enough.
