### ISSUE TITLE
Increase size of avatars

### ISSUE THREAD

**Issue by clarcharr** [tootsuite/mastodon#3807]
Right now avatars are tiny compared to most social media sites at 120x120px. This ends up making avatars seem blurry on high-res displays, and in general it seems to not be enough. It'd be nice if we could increase this size in a way that doesn't create bandwidth/storage concerns.

We could also offer the option for instances to choose whether to prioritise storage or bandwidth in this situation, and potentially include multiple sizes of avatars and serve whichever one makes sense for the display.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
The permalink interface (https://cybre.space/@nightpool) displays avatars at approximately 127x127 on my display, so we should allow at least twice that to account for retina.

**Comment by clarcharr** [comment]
I should also add that halcyon uses Twitter sizes and would need 400px avatars to work on Retina.

**Comment by connyduck** [comment]
Yes, bigger avatars would also be great for Tusky.
And even better would be a possibility to optionally get the  profile picture in an even higher resolution, something like 1200x1200, so users can zoom in.
