### ISSUE TITLE
Deleting older toots

### ISSUE THREAD

**Issue by LittleEDEN** [tootsuite/mastodon#381]
One of the worst parts about Twitter is just how difficult it is to get into your archive and mass delete tweets, but currently on Mastodon you can't even load up the static profile (users/EDENBroodheart) and interact with older toots at all, only being able to interact with toots with the /web/accountnumber view
 
This is bad. Whether it's a case of changing opinions, removing vent posts on an content focused account, deleting older posts you'd rather have Private instead of Public, deleting all posts you referred to yourself as the wrong gender, name or sexuality, there is an awful lot of reasons why someone with a lot of posts might go back and clean up. 
Being able to do this is actually really important because people can and do read entire account's lifetime worth of posts. Yes, really. They do. There were multiple occasions where people told me they reached the end of my Tumblr archives.

Yes, you can't remove it from the greater GNU Social archives if any given post is there I know this, but you also can't stop anybody from saving any given public Twitter, Tumblr or Facebook post either. It's a matter of not making it easy to see posts any given user would no longer like to be publicly displayed with the rest of their content.

![github](https://cloud.githubusercontent.com/assets/24882138/21596670/bc15d7b2-d103-11e6-8557-275e36e618a8.png)
When someone is in this view of their own posts, they absolutely NEED to be able to delete the post. This is one of those things that Mastodon needs before it can be called a safe website to use.

**Comment by marrus-sh** [comment]
As a related topic of conversation, it would be nice to be able to edit the privacy of old toots; at the very least to make non-private posts private at a later time, similar concerns regarding federation notwithstanding.

Related to #324/#166 with respect to not being able to interact with toots on static profile pages.

**Comment by LittleEDEN** [comment]
With the new Open in Web feature on Static Pages, this is iffy and awkward but at least brought up to Twitter's standard for archive management. This will do, for me at least.
