### ISSUE TITLE
[refactor] Usage of DOMContentLoaded and document.readyState

### ISSUE THREAD

**Issue by yumetodo** [tootsuite/mastodon#3829]
`/app/javascript/mastodon/main.js`: introduced at #2985 by @nolanlawson 

```js
function onDomContentLoaded(callback) {
  if (document.readyState !== 'loading') {
    callback();
  } else {
    document.addEventListener('DOMContentLoaded', callback);
  }
}
```

`/app/javascript/packs/public.js`: introduced at #3652 by @ykzts 

```js
function main() {
  if (['interactive', 'complete'].includes(document.readyState)) {
    loaded();
  } else {
    document.addEventListener('DOMContentLoaded', loaded);
  }
```

Which style is prefer?@ykzts said that

>https://github.com/tootsuite/mastodon/pull/3652#discussion_r121040608
>Because want to express state explicitly.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nolanlawson** [comment]
I prefer style # 1 because it doesn't require creating an array or `Array.prototype.includes` which is ES2016 but it really doesn't matter that much.
