### ISSUE TITLE
Prevent link spoofing in federated statuses

### ISSUE THREAD

**Issue by duxovni** [tootsuite/mastodon#3830]
The sanitization process for statuses doesn't mandate any particular relationship between the text and the href of a link, so someone can send a status like

```
<a href="http://malware.ru/">mastodon.social/media/bPR7ghQ...</a>
```

that tricks users into clicking a malicious link. It seems like we want to force the link text to be either the href, or some prefix of the href (with or without the protocol) followed by "...", but we need to be careful to prevent

```
<a href="http://youtube.com.malware.ru/">youtube.com...</a>
```

How about we mandate that the prefix of the href shown in the link text needs to contain the entire domain name at a minimum (and also make sure that toots from mastodon obey this requirement)?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Friendica and potentially other software may send proper text links (e.g. "Some text" linked to some URL) so this is intended behaviour and not something we can enforce.

**Comment by sdukhovni** [comment]
I see. I feel like this is still a security issue, because mastodon has trained users to expect that the text of a link in a toot is the destination of the link, so they won't inspect carefully before clicking. Could we apply a different styling to links that violate the "prefix including full domain" constraint, like making them a different color or otherwise obviously unusual?

**Comment by sdukhovni** [comment]
Alternatively, forbid links whose text is a URL-like string that doesn't match the href, but allow non-URL-like strings?

**Comment by sdukhovni** [comment]
The latter is probably harder to do in an ironclad way, because there are a lot of ways to make strings that don't parse as URLs but look enough like URLs to fool an inattentive user; so I think the former approach is better.

**Comment by sdukhovni** [comment]
Another option would be to display the real href in the UI somewhere, such that the user will notice it before following the link.

**Comment by ticki** [comment]
@Gargron. Here's an idea:

Add a warning if the inner text appears as a link (e.g. `youtube.com`) but doesn't match the href. This warning is a simple "are you sure?" dialog which is supposed to stop such spoofing.

**Comment by clworld** [comment]
I did test how E-Mail clients deal with link.
And I amazed about GMail does not warn when clicking link which text is looked like url and links to different domain.
I'm using Thunderbird with option display all mail as plain text. and this shows link as link only when link's text are perfectly matched with href.

**Comment by Gargron** [comment]
When you hover over a link, the browser displays the URL its going to go to. I think that is sufficient.

**Comment by ticki** [comment]
@Gargron Do you really check every link you click? I don't. I know it's careless and all, but I think I share this tendency with 80% or more of the users.

**Comment by clworld** [comment]
> When you hover over a link, the browser displays the URL its going to go to.

This feature does not exists on Smartphones.

**Comment by nightpool** [comment]
@clworld on ios chrome if you long click a link, you can check where it points to

Anyway, my understanding is that we should focus on training users to evaluate pages before they enter sensitive information, rather then training them to trust links to go where we expect them to go.

Someone with more infosec experience then me can feel free to correct me here though.

**Comment by nightpool** [comment]
Hmm. I would also be up for reformatting received statuses to show inline links if they don't match a substantial substring of the content though, I think that could be a good compromise.

**Comment by clarcharr** [comment]
I personally think that for any link that doesn't have the text of the URL, we should do some sort of confirmation dialogue like we do for boots. "Hey, this link goes to <URL>; wanna go there?"

**Comment by clarcharr** [comment]
re:

> When you hover over a link, the browser displays the URL its going to go to. I think that is sufficient.

and

> Anyway, my understanding is that we should focus on training users to evaluate pages before they enter sensitive information, rather then training them to trust links to go where they expect them to go. any link on the internet may take you anywhere—mastodon is not an exception here.

This is a really poor mentality to have, and it penalises users who don't have the energy to be that vigilant. Other social media platforms put a lot of effort to avoid link spoofing and a large amount of effort in infosec right now is centred around trying to make phishing harder to impossible, not just toward training people to be vigilant.

I think that a modal will do fine for links, and personally, I think the endgame should be:

1. Whenever a user clicks a link which is either a) not the same href as its text or b) not toward a "trusted" mastodon instance (simply checking that it's federated and not blocked or silenced is enough), activate a modal before following it.
2. This should display the domain name of the link and verify that the user trusts the website. Users can whitelist domains and say "don't show me this again" but they should be able to edit this in settings to manually add or remove domains.
3. Admins should be able to add to this whitelist by default.
4. If the domain uses IDNA (i.e. is unicode), the ASCII version of the domain should also be displayed. This can help against domains that cleverly use unicode to spoof domain names.
5. The page title of the link can optionally be given; we probably already collect this information from posted links.
6. Admins should be able to add to a blacklist of domains that will specifically warn users about being malicious; this will override any whitelisting while still allowing the user to continue anyway.

Obviously, this is a lot of work and I understand that going that far is probably a low-priority issue. But it definitely would be robust enough to guard against almost all phishing attempts.

**Comment by ThibG** [comment]
> Alternatively, forbid links whose text is a URL-like string that doesn't match the href, but allow non-URL-like strings?

This is what #11426 went with. Do you think it is good enough to address this issue?

**Comment by duxovni** [comment]
Awesome, glad this has finally been addressed! This looks like a good resolution.
