### ISSUE TITLE
Remove round avatars

### ISSUE THREAD

**Issue by sorin-davidoi** [tootsuite/mastodon#3831]
It has always bugged me that in the profile page the avatar is rounded (`border-radius: 90px`, together with a hover animation), while in all the other places it is not. Should we remove this and make it consistent?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ggtea** [comment]
Let's make all avatar appearance square!

**Comment by Kimik0** [comment]
I never understood why it looks round when it obviously has the whole square image under it and then does that weird round→squareish→roundish animation when you hold the mouse cursor over it. Looks like someone learned how to make rounded corners and just had to show it off somewhere.

The profile view is where you go to take a closer look at someone's avatar. It's not so great to have that view then hide parts of it.

**Comment by sorin-davidoi** [comment]
Closing since a PR will likely not be merged.
