### ISSUE TITLE
Q: the oldest version of Ruby

### ISSUE THREAD

**Issue by matyapiro31** [tootsuite/mastodon#3835]
Which version of Ruby is the oldest version for mastodon?
Now, Ubuntu supports only up to 2.3, but mastodon recommends to use 2.4.1.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
The gemfile says 2.3 though 2.5
![image](https://user-images.githubusercontent.com/233815/27257280-8e4f44b2-539e-11e7-9032-fc5e100ee384.png)

**Comment by matyapiro31** [comment]
Thanks.
