### ISSUE TITLE
UI/UX: "Settings" v "Preferences"

### ISSUE THREAD

**Issue by fpiesche** [tootsuite/mastodon#384]
Currently, e-mail settings are hidden behind a "Preferences" link which is itself only accessible via the "Settings" link from the Compose column (which in turn is actually a link to edit your profile).

Additionally the "Preferences" page includes options to hide non-follows/followers' notifications which doesn't fit in with the email stuff at all.

Both the labelling and the distribution of options here is confusing, especially now with the added options on the Notifications column.

I would propose:

- move the "Block notifications from non-followers" and "Block notifications from people you don't follow" options from the E-mail Settings page into the Notifications column options
- Remove the "Preferences" link on the Edit Profile page
- Replace the "Settings" link with a pop-up menu with two options (or just two separate links), "Edit Profile" and "E-Mail Settings", going to the relevant pages

**Comment by fpiesche** [comment]
Between the link rename to "Edit profile" and the navigation bar I would say this is probably sorted at least on desktop?

**Comment by ineffyble** [comment]
The option to change your email is hidden under 'change password', and even on that screen, it might not be immediately apparent that the email is editable. It should be more obviously referenced somewhere.

**Comment by Gargron** [comment]
Settings area has been reworked, so I'm gonna close this!
