### ISSUE TITLE
css bug in static profile page

### ISSUE THREAD

**Issue by HLT** [tootsuite/mastodon#3856]
the white area in the "posts" section has rounded edges on top. the sections "follows" and "followers" only have rounded edges at the bottom.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
@Gargron Is this a bug? or intended behavior?

**Comment by Gargron** [comment]
@unarist A bug :weary:

**Comment by nightpool** [comment]
a similar class of bugs:

![image](https://user-images.githubusercontent.com/233815/28194566-0efbd480-6813-11e7-98a4-aaa31ebafeb7.png)

**Comment by ykzts** [comment]
@HLT Is this fixed by #4341 ?
