### ISSUE TITLE
Delete censor functionality of instances

### ISSUE THREAD

**Issue by GotExx** [tootsuite/mastodon#3859]
![screenshot](https://hostux.social/system/media_attachments/files/000/110/446/original/9b0ae279c794180f.png?1497891764)
Recently an administrator saw his instance censored because he did not go in the same ideological sense as some administrators. As a result, this administrator decides to delete his instance because the administrator of one of the biggest instance of the network (mastodon.social) to judge judicious to mutate his instance. This action has the effect of mutating the instance of the entire Mastodon network.

### I propose to remove this blocking feature which is not in keeping with the spirit of Mastodon

Translate by Google: /

**Comment by clarcharr** [comment]
It's absolutely in the spirit of Mastodon to allow silencing harmful instances. mastodon.social is never intended to be the "primary" instance, and if you disagree with their silencing of certain instances you should find another instance that suits your needs, or start another one.
