### ISSUE TITLE
Public timeline is showing content security errors

### ISSUE THREAD

**Issue by sphinxc0re** [tootsuite/mastodon#3865]
![screen shot 2017-06-20 at 11 18 32](https://user-images.githubusercontent.com/3702016/27326034-99c8e83a-55aa-11e7-9f1c-673ac081722e.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
@sphinxc0re

This is not a matter of Mastodon, it is due to misconfiguration of instance owner.

see https://github.com/tootsuite/mastodon/issues/3534#issuecomment-305977322

**Comment by wxcafe** [comment]
what @ykzts said. Closing now

**Comment by sphinxc0re** [comment]
@ykzts @wxcafe Thank you! I will tell the owner.
