### ISSUE TITLE
Conversation tracking broken across instances

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#3869]
Conversation tracking is broken across instances (replies between users of an instance will be tied to the same `Conversation`, but any reply from a remote user will be assigned a new `Conversation`).

There are two reasons for this:
- First, there is code to track conversation based on explicit conversation URIs, but no conversation is created for a remote URI (`find_or_create_conversation` never *creates* a conversation)
- Second, replies processed from remote instances are `create`ed without information on their parent toots (`thread`), so the validation code will *always* create a *new* conversation

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
>`find_or_create_conversation` never creates a conversation

Thank you for reporting! I never noticed this. Can't imagine how it slipped...

**Comment by ThibG** [comment]
So, I don't really know how we're going to fix that. We could fix `find_or_create_conversation`, but every other existing Mastodon instance will break those conversations by assigning them a new URI…

**Comment by Gargron** [comment]
The main problem is that the method does not create a conversation based on remote URI, as it should. That's the only thing that needs to be fixed.

**Comment by ThibG** [comment]
Every Mastodon instance out there is misbehaving, so they will set a new URI when they get a toot from a remote instance. It will keep breaking the conversation until every instance involved is fixed.

The second part is an issue too: if the remote software does not set the ostatus:conversation link, we will create a new conversation for every message, which is not a good thing.

**Comment by Gargron** [comment]
It can't be worse than now. Before: both sides create a new URI each time. After: One side carries over the URI correctly. And people will upgrade over time.

**Comment by beatrix-bitrot** [comment]
would be a good fix to get into the patch release for the class sanitization stuff...
