### ISSUE TITLE
Instances should be able to flag themselves as hosting personal or organization accounts

### ISSUE THREAD

**Issue by kstrauser** [tootsuite/mastodon#3873]
I believe a few things about Mastodon:

- We are growing rapidly;
- We have gotten lots of press;
- We are therefore very attractive to advertisers and other business applications;
- Lots of users would _like_ to use certain business services like a "support@example.com" account;
- Most organizations would rather host their own instances (or pay someone to host one for them) than create an account on an instance they don't control;
- A giant influx of those accounts could happen any time now; and
- We currently lack the tools to gracefully handle that situation. If 100 companies brought on 100 instances today, then several hundred individual admins would have to decide how to deal with each of them on a case-by-case basis, almost certainly angering their users by either too little response or too much.

I propose we add four things to Mastodon:

1. A per-instance setting describing it as hosting personal or organization accounts. That should be part of its description in the API.
    - Almost all current instances would be personal. Even corporate-owned instances like pawoo.net currently host (almost?) exclusively personally operated accounts.
    - Culturally, it should be the standard that corporate instances (those set to "we host organization accounts") who misrepresent themselves as personal should expected to be universally banned. That should become the rare exception, not a normal variation.
    - Culturally, it should be the standard that personal instance admins should ban corporate accounts from their instances.
1. A per-instance setting selecting how it interacts with corporate instances , with options "normal", "silence", and "block". This, too, should be surfaced in the API.
    - Normal is the state of affairs as it exists today.
1. A per-user setting that allows users to make their personal rules more strict than those of their instance.
1. Some kind of distinct styling for toots from accounts hosted on corporate instances, like a border around them or a different font for their usernames.

This would allow new users to filter for instances that matched the policies they'd like. It would allow clearly labeled commercial content _only_ to instances and users that wanted to see it. It would preserve the current behavior for every personal account and instance already in the federation.

I wrote a little more about this at https://blog.freeradical.zone/the-brand-comes-around/ .

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by npdoty** [comment]
Should this be at the instance level? I imagine many organizations might set up a support account on a prominent instance (say, mastodon.social), in much the way that they set up accounts on Twitter.

Similarly, if some company or organization sets up their own instance, and then individuals at that company/organization create accounts on that instance, do we want that instance to be flagged as "corporate" so that it can be more easily isolated/blocked? In some cases those accounts might be "@support@example.com" or "@marketing@example.com", but we also see cases of "@jane@example.com" and Jane is an individual, and I'm not sure we'd want that instance or Jane's account to look different.

Anyway, I'm interested in this topic as well, but I wonder if it might be more useful to have an account-level flag: "this account is maintained by multiple people representing an organization".

**Comment by nightpool** [comment]
I don't understand this premise:

> If 100 companies brought on 100 instances today, then several hundred individual admins would have to decide how to deal with each of them on a case-by-case basis

In what world do 100 companies suddenly unveil their mastodon instances at the exact same time, in some kind of coordinated move? The idea seems ludicrous—there's no reason to think that adoption wouldn't happen at the same scale these businesses themselves move at: slow, with a few early adopters, and most coming very late to an already established network.

without that premise I see no real reason to think this is a useful feature or something that needs to be built.

Remember of course that mastodon (and all moderation/administration decisions thereof) is a *follower based* social network, so all interactions scale relative to the numbers of users *on your instance*. If noone you know follows anybody from another server, then (barring @-mentions or follow bots) you're never going to see a commercial account unless you go looking for it.

With that in mind I don't think this is going to be as big of a "whack a mole" as you're making it out to be, and there's no reason to believe our existing moderation tools (which have proven themselves flexible and responsive against the much more toxic threat of white nationalism) won't be useful here.
