### ISSUE TITLE
/about/more link isn't obvious enough

### ISSUE THREAD

**Issue by no-boot-device** [tootsuite/mastodon#3881]
Honestly, the fact that it doesn't 

1. explicitly state that the rules are contained there
2. show up extremely visibly and not as a tiny link next to log in and not even in the footer
3. get read, ever, by a concerning amount of the people who use mastodon, it seems

is an issue. Any suggestions for making it more visible and making sure people read the rules?

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
Is there currently a link to about/more in the onboarding modal? Adding one there would be a good first step, I think.

**Comment by unarist** [comment]
The link is also on /about, but... I think it's unnoticeable.

![image](https://user-images.githubusercontent.com/705555/27432649-f7211308-578b-11e7-8d83-d32d9886a43f.png)

So many admins seem to write important notices to `Site description` instead of `Extended site description`.

**Comment by Gargron** [comment]
Funnily enough this issue stayed valid through like... 3 redesigns, but I think now the link is finally prominent ("Learn more" under "Administred by" on frontpage)
