### ISSUE TITLE
Error: gemfile syntax error?

### ISSUE THREAD

**Issue by matyapiro31** [tootsuite/mastodon#3884]
```
[!] There was an error parsing `Gemfile`: no implicit conversion of Symbol into Integer. Bundler cannot continue.

 #  from /dir/mastodon/Gemfile:4
 #  -------------------------------------------
 #  source 'https://rubygems.org'
 >  ruby '>= 2.3.0', '< 2.5.0'
 #  
 #  -------------------------------------------
```
ruby version is 2.3.1 and Ubuntu 16.04.
* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
What is the version of bundler?

**Comment by matyapiro31** [comment]
>Bundler version 1.11.2

**Comment by ykzts** [comment]
Plz run

```console
$ gem update bundler
```

**Comment by matyapiro31** [comment]
Output:
>Nothing to update

**Comment by nullkal** [comment]
It seems you are using ubuntu xenial's ruby-bundler package (https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=ruby+bundler&searchon=names).
Try uninstall bundler installed via apt and reinstall it via gem command.

**Comment by xvilo** [comment]
Same here:
```
gem update bundler
Updating installed gems
Updating bundler
Fetching: bundler-1.15.1.gem (100%)
rbenv: cannot rehash: /home/mastodon/.rbenv/shims/.rbenv-shim exists
Successfully installed bundler-1.15.1
Gems updated: bundler
```

And: ```
rails -s

[!] There was an error parsing `Gemfile`: no implicit conversion of Symbol into Integer. Bundler cannot continue.

 #  from /home/mastodon/live/Gemfile:4
 #  -------------------------------------------
 #  source 'https://rubygems.org'
 >  ruby '>= 2.3.0', '< 2.5.0'
 #  
 #  -------------------------------------------
```

**Comment by ykzts** [comment]
@xvilo Did you check https://github.com/rbenv/rbenv/issues/759 ?

**Comment by gabelula** [comment]
wow, yes. It worked for me after rbenv rehash.

**Comment by ykzts** [comment]
@matyapiro31 Have you solved this issue?

**Comment by almafeta** [comment]
I have the same issue with v1.5.0rc2 on the same platform - ruby 2.3.1, ubuntu 16.04.

**Comment by ykzts** [comment]
@almafeta 

```console
$ sudo apt-get remove ruby-bundler
$ sudo gem install bundler
```
