### ISSUE TITLE
Add option to report a user to the instance admin/mod of that user too

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#3885]
Currently you can report users and their toots to the instance admin you are on. I like to request an extra option to report a user (incl toots) to the instance admin of that specific user.

Example:

* User 5 at instance G (5@G) has a problem with toots of user 3 at instance K (3@K).
* Current situation: 5@G reports toots of 3@K to the admin/mod of instance G
* New situation: 5@G can also report the toots of 3@K to the admin/mod of instance K or it can choose to report to the instance admin/mod of instance K alone, so...

A user has three options (using a drop-down menu, with 1 (current) as default):
1. It can report to its own instance admin/mod
2. It can report to the instance admin/mod of the reported user
3. It can report to both instance admin/mods*

\* it should be made clear to both admins/mods that this report went to both admins/mods (so they have a change to consult each-other)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by JaymesKeller** [comment]
Sounds like a pretty nice idea. If anything, it might be able to reign in abusive users from other instances, since instance admins are more aware.

**Comment by nightpool** [comment]
dupe of https://github.com/tootsuite/mastodon/issues/2176

**Comment by jeroenpraat** [comment]
@nightpool Didn't found that one. I would never come up with the name 'federated reports'. Anyhow, I close this one and really do hope that this feature request is implemented ASAP.
