### ISSUE TITLE
Instance stuck in mobile

### ISSUE THREAD

**Issue by codingducks** [tootsuite/mastodon#3886]
Sorry if this is not related to Mastadon directly, and has something to do with my Computer/Browser

On my desktop, (Debian/i3wm/firefox) the instance I joined started to be displayed in mobile mode (hadnt always), and I have no idea how to switch it back, it should be really obvious how to do this

the weird thing is if I join a new instance, all is normal

I havnt been able to get on a new computer to see if its "global" or just happening on this computer, although I suspect its everywhere, because I have tried in private browsing 

EDIT: 
Solved, it was the zoom 

* * * *

- [glimpsed ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [unknown ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by jeroenpraat** [comment]
Did you maybe zoomed in? The Mastodon web-app is responsive, so if you zoom in to much it will switch to what you call mobile mode.

Solution: CTRL+0

**Comment by RaphTriesCoding** [comment]
This has nothing to do with this issue but thanks for the shortcut @jeroenpraat this f****in' pad on my laptop was starting to bother me a lot with all the zooms in

**Comment by jeroenpraat** [comment]
If that is not the issue, I can't help you. Actually you should ask these kind of questions on https://discourse.joinmastodon.org the next time.

**Comment by codingducks** [comment]
thanks, it was the zoom

**Comment by jeroenpraat** [comment]
I though my latest reply was on @codingducks, but it was for @RaphTriesCoding. I need computer glasses ;-)

**Comment by RaphTriesCoding** [comment]
Actually I think you misundertsood what I was trying to say @jeroenpraat , I was thanking you for "Solution: CTRL+0" because I didn't knew this shortcut existed.
