### ISSUE TITLE
Show local public feed without requiring login

### ISSUE THREAD

**Issue by thekyriarchy** [tootsuite/mastodon#3889]
Feature request to allow people to get a peek at public content before creating an account so they can get a feel for the instance and possibly be enticed to join

**Comment by nightpool** [comment]
thanks for taking the time to send us this suggestion! currently we're tracking this proposed change as issue #1053. You can read more discussion about the feature there and at #1778.

I'm going to close this issue, but only to keep conversation centered in one location—feel free to add your vote or comments there!
