### ISSUE TITLE
Add extension to filenames of included files

### ISSUE THREAD

**Issue by celesteh** [tootsuite/mastodon#3891]
When images do not have extensions, this causes compatibility issues with GNUSocial servers, who do not recognise it as an image and thus do not embed the image correctly. It would therefore increase compatibility if uploaded images had extensions on them.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
This should be as simple as adding the `:extension` interpolation to paperclip, I think?

**Comment by Gargron** [comment]
I'm not sure what this is about, we already have a special workaround for ensuring images have a file extension. Where have you seen otherwise?

**Comment by celesteh** [comment]
Sorry, I have taken outdated advise for !gnusocial.
