### ISSUE TITLE
Allowing instance admins to change custom CSS via the web interface

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#3894]
This would be useful for instances hosted on masto.host. It should be disabled by default if someone has access to the server via SSH for example.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
This is a great idea, and should perhaps come under #2028?

**Comment by nightpool** [comment]
@Cassolotl I considered suggesting that, but I decided that issue is almost so broad as to be useless, and it helps more to track the specific parts of it we think are useful

**Comment by Cassolotl** [comment]
@nightpool Yeah, that makes sense!
