### ISSUE TITLE
Nested CWs.

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#3899]
Some CWs need to be under a CW.

For example, say I wanna talk about breathplay. I can put CW: breathplay. But some ppl don't wanna see NSFW content, and that includes the breathplay CW. So I need to put CW: NSFW instead. And then there are ppl who are ok with NSFW but don't wanna see anything about breathplay. So I'm stuck.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Kimik0** [comment]
Something like this could be accomplished by what I proposed here: https://github.com/tootsuite/mastodon/issues/1010#issuecomment-304008535
