### ISSUE TITLE
Require re-authentication to disable 2FA

### ISSUE THREAD

**Issue by jckw** [tootsuite/mastodon#3910]
Currently, if a user is logged in they can disable 2FA without having to re-authenticate. 

It's considered best practice to force the user to re-authenticate before they can disable a security feature (with either the password, an backup access code, or by using 2FA; the choice is usability v. security).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by M-D-M** [comment]
I second this.  I haven't yet tried to disabled the 2FA I set up, but really surprised this isn't required.

**Comment by nolanlawson** [comment]
I agree, this is an important feature security-wise.
