### ISSUE TITLE
Issue with #3616

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#3915]
Not sure what happened, but after this update - I now see the fail masto while on web. The /about and login screen works fine, but once you log in, the fail masto appears. The timelines do load properly within apps though.

**Comment by malicioustoker** [comment]
Issue started with #3616

**Comment by Gargron** [comment]
It just got merged, how are you already using it? Don't run master in production. Master is for development. Check out v1.4.6

**Comment by malicioustoker** [comment]
I run every new commit on master - as with ever iOS beta and any beta that is. I enjoy reporting bugs before things go public 🙃

**Comment by malicioustoker** [comment]
I accept full responsibility for what happens while running master - only wanted to make y’all aware of the issue 🤓

**Comment by Gargron** [comment]
Well, you're probably missing a `rails db:migrate` tbh, but again, especially now that I'm done with thr 1.4.x release for the foreseeable future, I am starting to merge all the large/experimental PRs.

**Comment by malicioustoker** [comment]
@Gargron I love experimental stuff! Haha, and I’m using docker - I run the db and asset command after EVERY commit - just to be safe. So that’s not the issue :-/

**Comment by Gargron** [comment]
In that case please check logs in `docker logs mastodon_web_1`, it should contain details whenever the failephant is displayed.

**Comment by malicioustoker** [comment]
[2f144fd9-2355-444a-9f21-8e5dcc143699]
[2f144fd9-2355-444a-9f21-8e5dcc143699] app/models/user.rb:103:in `session_active?'
[2f144fd9-2355-444a-9f21-8e5dcc143699] config/initializers/devise.rb:7:in `block in <top (required)>'
[2f144fd9-2355-444a-9f21-8e5dcc143699] app/controllers/concerns/localized.rb:14:in `set_locale'
[c72a6314-c49e-430d-98b9-425aa483f99c] method=GET path=/ format=html controller=HomeController action=index status=500 error='ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "session_activations" does not exist
LINE 8:                WHERE a.attrelid = '"session_activations"'::r...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"session_activations"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
' duration=218.71 view=0.00 db=163.42
[c72a6314-c49e-430d-98b9-425aa483f99c]
[c72a6314-c49e-430d-98b9-425aa483f99c] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "session_activations" does not exist
LINE 8:                WHERE a.attrelid = '"session_activations"'::r...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"session_activations"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

**Comment by malicioustoker** [comment]
@Gargron hopefully that helps!

**Comment by Gargron** [comment]
It doesn't look like you ran the db migrations after all

**Comment by malicioustoker** [comment]
@Gargron but I do, the command is built into my shell script, but I found where the issue lies..

Turns out, I never ran the prepare_for_foreign_keys which prevented any changes happening when preforming db:migrate

Needless to say, you were right, issue has been fixed! Sorry for taking up your time
