### ISSUE TITLE
Mastodon icon?

### ISSUE THREAD

**Issue by cedewey** [tootsuite/mastodon#3919]
Is there a mastodon icon available that can be used to place on websites for people/organization's mastodon account?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nolanlawson** [comment]
The only icons I'm aware of are stored in https://github.com/tootsuite/mastodon/tree/master/public

I don't believe I've seen a canconical "share" icon, e.g. an equivalent to "share on Twitter," "post to Facebook," etc. But you're free to create one! :)

**Comment by Gargron** [comment]
I'm currently working with a designer to create such icons (and change the logo) but I have nothing to show right now.

**Comment by mikekreuzer** [comment]
Just in case anyone else is after this, the free set of [font-awesome's icons][fa] have a mastodon svg in them now.

[fa]: https://fontawesome.com
