### ISSUE TITLE
[Feature] Report Toot/User

### ISSUE THREAD

**Issue by fpiesche** [tootsuite/mastodon#392]
As it stands now, users on Mastodon instances have to externally contact the site admin to e.g. silence abusive users or spammers on the public timeline. A "Report" function on toots and account profiles could help with this, as well as help with prioritizing issues (by e.g. displaying a list of reported toots on the admin back-end, grouped by users and sorted by total number of reports).

Detailed features that would be useful here:
- users should be able to send reports anonymously, so that e.g. users worried about an abusive account can raise this without concerns about repercussions (if, say, a reported account happens to be a friend of the server admin).
- possibly have a (default-off) tickbox for the reporter to signify they are fine with being contacted about the issue by the server admin (so that e.g. a user could privately "call for help" if they're in distress but don't know where else to turn)

This would also lay a foundation for more advanced moderation functionality, e.g. allowing a list of community moderators that can examine reports and silence spammers or hide specific toots without requiring site admin access, automatically hiding toots/users with a lot of reports, categorised reports so that e.g. reports of users in distress can be prioritized over spammers, etc.

**Comment by TrevInc** [comment]
I think also, perhaps as an enhancement, the report feature should have some context with regards to specific Terms of Service or Code of Conduct violations, depending on the server -- AFAIK mastodon.social itself doesn't have either presently, but other servers are likely to, and it may be helpful for large instances or report batches to mark the specific ToS or CoC violation.

**Comment by nevillepark** [comment]
Could there perhaps be a new "Moderator" permission level (below admin, above regular users) that allows  hiding toots, flagging reported toots (e. g., spam, harassment, not against CoC, etc.), contacting the poster, contacting the reporter, and so on?

**Comment by yiskah** [comment]
I believe this issue has been resolved/can be closed with the recent update that added toot reports? @Gargron
