### ISSUE TITLE
Clicking "Favorites" from "Getting Started" column results in "Oops! An unexpected error occurred"

### ISSUE THREAD

**Issue by wolfteeth** [tootsuite/mastodon#3924]
Discovered after updating to v1.4.6. Seen also on mastodon.social, presumably also on v1.4.6.

Click "Favorites" in the "Getting Started" column in the web UI. The column never appears, and the message "Oops! An unexpected error occurred" appears in the lower left corner.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by matunixe** [comment]
Same issue here, 100% reproducible.

**Comment by Gargron** [comment]
#3906? @ykzts

**Comment by ykzts** [comment]
@Gargron oops! i was mistaken. please check #3925.
