### ISSUE TITLE
Swipe gestures on mobile web client 

### ISSUE THREAD

**Issue by DJSundog** [tootsuite/mastodon#3928]
I see that #2889 was closed for 1.4.6, yet I cannot swipe anything in Chrome on Android. 

Steps to reproduce:

* swipe left and right on feed selection tabs

Expected result:

Left swipes iterating left through columns, right swipes iterating right through columns

Actual result:

Smudges on my screen

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by DJSundog** [comment]
Looking at the commits, retested by also swiping to dismiss the media modal, which fails to have any action.

**Comment by sorin-davidoi** [comment]
It was merged after 1.4.6 was released, will be part of 1.5 I guess.

**Comment by DJSundog** [comment]
Fair enough - closing this issue.
