### ISSUE TITLE
retroactively change post visibility?

### ISSUE THREAD

**Issue by mostlyghost** [tootsuite/mastodon#3933]
It'd be really helpful to be able to change a post's privacy setting after it's been posted (such as making a public post private, or a private post public).

I'd like this option for an individual toot and/or the ability to retroactively change all previous posts to private or locked in one batch. I know it's a big ask, and I wonder if it's even possible. (With the caveat that we know we don't necessarily have control over all toots once they've been disseminated into the fediverse... but at least it can be changed for future audiences.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by joyeusenoelle** [comment]
This has a LOT of potential for abuse. (Consider the simplest case: sending harassment to someone, then marking it followers-only so they can't report it.) Let's consider the repercussions of this before we implement it.

**Comment by mostlyghost** [comment]
> This has a LOT of potential for abuse.

You're right. I'm going to rescind this request.

**Comment by zbanks** [comment]
Can I re-open this? 

- What about making posts *more public*: going from followers-only to public?
- Currently, you can delete posts (with the caveat that you don't have full control, etc.). Is there anything worse about making a public post private vs. deleting it?
