### ISSUE TITLE
feature request: add UI element to expand all content warnings in a pane

### ISSUE THREAD

**Issue by abochmann** [tootsuite/mastodon#3942]
Reading threads hidden behind content warnings is very tiresome in the current implementation. 

Consider the example screenshot at the end of the issue text, which illustrates the problem. Currently, the reader is forced to click "show more" on every post, and possibly adjust scrolling afterwards, in order to follow a conversation behind CWs.

I'm aware that content warnings are a valuable tool for parts of the Mastodon audience, and I'm not arguing against their use:  I would just like to propose adding an UI control that expands all content warnings in a pane on a single click. 

Alternatively, a global preference toggle that makes Mastodon web expand all content warnings, always, would work for me personally, too.

![mastodon cw horror](https://user-images.githubusercontent.com/9380844/27517063-834a2582-59c5-11e7-9e1e-ecd46eb5d158.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kemenaran** [comment]
It would definitely be great to be able to expand all messages behind the same CW.

A first step could be to allow `Alt+Click` on a CW label to expand all messages with the same content warning.

This would have the benefit of not requiring a new UI element. It could be made discoverable with a title-text on the CW label ("Click to reveal this message. Alt+Click to reveal all similar messages").

**Comment by Cassolotl** [comment]
I think this might be a duplicate of *Expanding all messages of a thread with a CW at once. #1258* ?

**Comment by kemenaran** [comment]
@Cassolotl yes, it looks like a duplicate indeed.

**Comment by abochmann** [comment]
Oh - I didn't find that other issue when searching for the topic. I'm closing this one then.
