### ISSUE TITLE
Command "webpack" not found when attempting to precompile assets in 1.4.6 on Scalingo

### ISSUE THREAD

**Issue by aral** [tootsuite/mastodon#3943]
After executing:

`scalingo -a <mastodon-app-name> run RAILS_ENV=production bundle exec rails assets:precompile`

I get

```
✘  ~/sandbox/mastodon  ➦ 7b13e6ef  scalingo -a mastodon-aral run RAILS_ENV=production bundle exec rails assets:precompile
-----> Connecting to container [one-off-6705]...
-----> Process 'RAILS_ENV=production bundle exec rails assets:precompile' is starting...

Webpacker is installed 🎉 🍰
Using /app/config/webpacker.yml file for setting up webpack paths
[Webpacker] Compiling assets 🎉
[Webpacker] Compilation Failed
yarn run v0.24.5
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

error Command "webpack" not found.
```

Most likely related to: https://github.com/rails/webpacker/issues/522

Server is currently giving a 500 error.

***

Update: This is odd, a little while later, I start seeing the timelines start to appear and now the instance seems to be up and running. I thought I’d seen the precompile assets stage being performed correctly during the original deployment. The direct command is still failing. But the upgrade seems to have succeeded and somehow healed itself.

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on a [1.4.6](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
Did you make sure to run `yarn install` before running assets:precompile? that seems to be the cause of the issue you linked.

**Comment by aral** [comment]
@nightpool Cool, thanks. I have a feeling in “serverless” installs that’s taken care of by the buildpack and, more than likely, we’re not supposed to run the precompile task manually either. So this could be a non-issue. Closing for now.
