### ISSUE TITLE
Favourites not working on 1.4.6

### ISSUE THREAD

**Issue by aral** [tootsuite/mastodon#3944]
The favourites view doesn’t work under 1.4.6.

Error in console:

```
[Error] TypeError: undefined is not an object (evaluating 'n.size') — status_list.js:107
	(anonymous function) (application-0e527949059f12203697.js:1:467349)
	(anonymous function) (application-0e527949059f12203697.js:1:149724)
	promiseReactionJob
```

![d25 community](https://user-images.githubusercontent.com/41798/27518058-1ae2cbae-59d7-11e7-9a82-ae9c5c407c75.png)
![d25 community](https://user-images.githubusercontent.com/41798/27518060-1d3d1472-59d7-11e7-82d9-6d1f6166c092.png)

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on a [1.4.6](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Angristan** [comment]
I'm running 1.4.6 on mstdn.io and the favs are working just fine

**Comment by staticsafe** [comment]
I can reproduce this on two instances running 1.4.6.

**Comment by aral** [comment]
@Angristan Thanks for the info. 

1. Which version did you upgrade from? (mine was 1.4.3 → 1.4.6)
2. Did you run database migrations (I didn't see instructions to do so.)
3. Could you detail any post-upgrade steps you carried out

Thanks! :)

**Comment by unarist** [comment]
This looks same issue of #3924. There are bug on 1.4.6, and it has been fixed on master.

**Comment by Angristan** [comment]
@aral I did not skip any upgrade. The last migration I did was for 1.4.2. I did nothing fancy 🤔

**Comment by aral** [comment]
Right. So this is issue #3924 and that’s fixed and in master.

The workaround (if you’re brave enough) is to: 

1. Checkout master
2. Run `RAILS_ENV=production bundle exec rails db:migrate` (there are migrations)
3. (I also ran `RAILS_ENV=production bundle exec rails assets:precompile` `bundle install` and `yarn install` as I wasn’t sure what had changed recently)
4. And don’t forget to (on source-based installs), `sudo systemctl restart mastodon-*.service`

**Comment by aral** [comment]
Actually, going to leave this issue open until 1.4.7 is out so that people who install 1.4.6 and come looking can easily find it.

**Comment by salvadorpla** [comment]
I did the update from 1.4.4 to 1.4.6 according release notes and no, favourites are not working, same error than reported by aral.

**Comment by aral** [comment]
@salvadorpla Yes, favourites are broken in 1.4.6, that's not going to change ;)

Either roll back to ~1.4.3, or checkout master (see https://github.com/tootsuite/mastodon/issues/3944#issuecomment-310915451), or cherrypick this commit: https://github.com/tootsuite/mastodon/commit/79dacea96254d8b01f9896e026b27c572401f2a8 to fix it.

Hope that helps :)

**Comment by salvadorpla** [comment]
I'm not in a hurry, my users are mostly using apps but thanks anyway ;-)

**Comment by Gargron** [comment]
Forgot to close this with 1.4.7 release
