### ISSUE TITLE
SMTP config , recompile without  infecting the productive DataBase 

### ISSUE THREAD

**Issue by qatuno** [tootsuite/mastodon#3970]
hi there.  i have the need to change the SMTP config wich is used by setup the instance. 
so . will be nice to have a admin tool to recompile just the SMTP config made while installation . 
maybe it is just posssible to do this with a new DataBase ?  more ideas? 

if there is a way to do so , would be nice

**Comment by nightpool** [comment]
You can change the SMTP config by editing the SMTP server environment variables:

https://github.com/tootsuite/mastodon/blob/master/.env.production.sample#L50
