### ISSUE TITLE
401 error due to active sessions

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#3973]
Just reporting a bug(?)

Ever since commit #3616 I have been receiving a 401 error on the Home and Notifications TL. Both Federal and local work just fine though. This issue is only in browsers, not within apps. Logging out and back in does not fix the issue.
![img_0023](https://user-images.githubusercontent.com/1431774/27600625-6cc10bac-5b21-11e7-9ee8-9d851e1cbcd3.PNG)

**Comment by Gargron** [comment]
Try running db:seed and then logging out and back in

**Comment by malicioustoker** [comment]
@Gargron as in

‘docker-compose run --rm web rails db:seed’ ?

**Comment by Gargron** [comment]
Yes!

**Comment by malicioustoker** [comment]
@Gargron is at it again with the excellent support and quick fixes - that did the trick, thank you good sir!!
