### ISSUE TITLE
Feature Request: Ability to view public toots from another users timeline

### ISSUE THREAD

**Issue by coreyfarrell** [tootsuite/mastodon#3983]
The distributed nature of mastodon makes it more difficult to find other users of similar interest, the local/federated timelines are not helpful to me as I don't share interests with other users on same instance as me.  It would be very helpful if I could view the timeline of other users.

For example I follow @nolanlawson, the list of accounts he follows is public.  Given his interest in programming I assume that he follows other accounts that would be interesting to me, but checking his followers one at a time would be very time consuming.  It would be very useful if I could just see his timeline (obviously only the public toots).  This would be an easy way to find other people I'm interested in following.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I think this might be a duplicate of *View content from a list of users #952* ?

**Comment by coreyfarrell** [comment]
Looks like it.
