### ISSUE TITLE
No PostCSS Config found in: ... mastodon/shared/node_modules/font-awesome/css when running cap production deploy

### ISSUE THREAD

**Issue by ignisf** [tootsuite/mastodon#3998]
Hello,

I'm trying to deploy mastodon (master and 1.4.*) with Capistrano with the `cap production deploy` command. Currently I'm getting the following error output: https://gist.github.com/ignisf/dc8a0bab23d9c450dea8efdc3df755b3

Is this a bug or am I doing something wrong?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ignisf** [comment]
Seems like removing `node_modules` from the `linked_dirs` list in `config/deploy.rb` resolves this issue.

**Comment by ignisf** [comment]
Hello, just FYI, unfortunately I am still getting this issue with the default Capistrano config.

**Comment by dachinat** [comment]
Hi. Is there a solution for this?

**Comment by dachinat** [comment]
So, I needed to get this working quickly, and I've changed `sass.js` to what follows:

```
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const path = require('path');
const { env } = require('../configuration.js');

const postcssConfig = path.resolve(process.cwd(), '.postcssrc.yml')

module.exports = {
  test: /\.s?css$/i,
  use: [
    MiniCssExtractPlugin.loader,
    {
      loader: 'css-loader',
      options: {
        minimize: env.NODE_ENV === 'production',
      },
    },
    {
      loader: 'postcss-loader',
      options: {
        sourceMap: true,
        config: { path: postcssConfig }
      },
    },
    'sass-loader',
  ],
};
```

Would be good to have an optimal solution from your team. Thanks.
