### ISSUE TITLE
Implement common mobile UX patterns

### ISSUE THREAD

**Issue by sorin-davidoi** [tootsuite/mastodon#4004]
As we are making progress with features that will bring Mastodon closer to native applications on mobile devices (e.g. offline support, add to home screen and push notifications), I was wondering if we could bridge the gap even further by implementing some UX patterns that people expect from native applications.

Here are some suggestions (all these apply to the mobile view).

# Drawer
Remove the getting started menu and add a "hamburger" button. Clicking it (or swiping from the left) would toggle the drawer (with a nice animation). The content could be very similar to the current getting started page, maybe with the addition of the user details.

<img src="https://cdn-standard5.discourse.org/uploads/joinmastodon/original/1X/8b5f40b11b295e799ec78ec1d2158edac3e37ccb.jpg" width=200 />

# Long tap to show options
When we show a list that has hidden actions (e.g. the list of toots), long taping would open a modal showing the hidden actions (mention, mute, block...).

Since we are code-splitting, implementing these features would have a negligible effect on the size and performance of the website.

What do you think? What features are you missing from the website that current apps (e.g. Tusky) provide?

**Comment by saper** [comment]
Despite popular belief, hamburger is not a very good user interface - it does not say anything about what is hidden behind it...
