### ISSUE TITLE
PGP Support

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#4007]
Could we have a possibility for linking PGP certificates to Mastodon accounts to allow for signatures on posts, a web of trust, and encryption?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). #

**Comment by benjamincodeWebsite** [comment]
This would also aid with #913. If this is approved, I would be happy to help with implementation.

**Comment by eebrown** [comment]
This is also discussed on #928. I support for the reasons I list there.

**Comment by nightpool** [comment]
duplicate of #928
