### ISSUE TITLE
Ability to deactivate 2FA with recovery code

### ISSUE THREAD

**Issue by denmojo** [tootsuite/mastodon#4026]
Use case: You have lost your phone or lose the account on your authenticator app and can no longer get your 2FA TOTP codes. Login using one of the backup recovery codes. When going to the Two-Factor section, you wish to disable 2FA and re-enable it in the authenticator app or a different phone, but it asks for the 2FA code to disable.

A security consideration is that anyone who has access to one's logged in browser can regenerated backup recovery codes and then disable 2FA. However, for the legitimate loss of 2FA device (or account in app), the user is forced to use recovery codes forever (having to regenerate them before using them all up).

Just as in login, a user should be able to use a recovery code to disable/reset 2FA. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
wait, does this not work? this should Just Work.

**Comment by janisz** [comment]
I've just hit into this. I changed my phone and I can't setup new authenticator app :(

**Comment by nolanlawson** [comment]
Just ran into this myself due to a bricked phone. Fairly serious issue IMO since it's possible to get permanently locked out of your account once you run out of backup codes.

**Comment by nightpool** [comment]
agreed
