### ISSUE TITLE
Old toots showing up on home timeline

### ISSUE THREAD

**Issue by sdukhovni** [tootsuite/mastodon#4030]
I'm seeing unboosted toots from several hours ago showing up near the top of my timeline among toots from a few minutes ago. This is happening on v1.4.7, don't recall noticing it on earlier versions.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
perhaps someone boosted the toot and then undid their boost? that would
look like you described (since things aren't actually removed from your
feed when they get unboosted)

**Comment by sdukhovni** [comment]
Possibly? I'm seeing a lot of these, though. And if that is what's going on, "remove things that get unboosted" might be a good feature request...

**Comment by sdukhovni** [comment]
That's definitely not what's going on; things are also showing up out-of-order in the timeline of that user's toots...

**Comment by Kimik0** [comment]
Perhaps someone is looking up toots manually? (i.e. enter the url in the search box, or use the search api) If the server pulls in a previously unknown toot, it's given a new local id, which means it appears at the top of the timelines even though it might be really old. Usually id order is (nearly) the same as timestamp order, but this is one case where it's noticeably different.

**Comment by wxcafe** [comment]
Did you find the reason this is happening? both reasons given here (plus replies pulling the original toot) are known behavior and there's work to make some of them behave more closely to how users expect them to.

**Comment by sdukhovni** [comment]
Nope, never figured out what was going on, and I'm not seeing it anymore. Probably ok to close this I guess.

**Comment by clworld** [comment]
@wxcafe FYI:
* Timeline order is id order and not canonical order. So, newly arrived/fetched toots are placed on top of timeline even if that toots is old.
* Mastodon currently does not use Snowflake. So, we can't use old id for old toot. https://github.com/tootsuite/mastodon/issues/1059
* Bug unboosted toots won't be disappear is caused by timeline structure stored in Redis and It can't be fixed easily.
See: https://github.com/tootsuite/mastodon/issues/2817#issuecomment-299501175 https://github.com/tootsuite/mastodon/issues/147

**Comment by Kimik0** [comment]
Maybe the problem of not knowing whether to remove a toot from the timeline or not when it's unboosted without going over the whole timeline again can be mitigated (not completely solved) by adding a reference counter (number of times the toot has been boosted onto the timeline). You wouldn't be able to bump it down to its proper place (previous boost) when it's unboosted, but you could keep track of when to remove it completely from the timeline (when counter reaches 0). #147
