### ISSUE TITLE
Too easy to trigger column swiping

### ISSUE THREAD

**Issue by sorin-davidoi** [tootsuite/mastodon#4035]
I find myself accidentally swiping columns when scrolling up / down. `react-swipeable` has a delta which configures how long the swipe has to be before it is considered a swipe. The default is 10px.

This issue is mostly to see if this affects other people. We can increase the `delta` if this is the case.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by kyzh** [comment]
I have an issue that sounds exactly like what you describe here.
It is really frustrating to say the least and I'm glad this could be the answer to it.

When I was trying to put words on what I was experiencing, I found 2 main behaviours:
- going laterally column wise 
- the change to happen at content/column level before the top icon.

I actively tried to swipe and the column content change before the icon at the top show the focus.
I therefore think my issue and yours is the same.

Speaking for myself, I'd love to be able to disable swiping all together as it is slower and less practical than clicking the icon at the top.
It take longer than clicking the icon at top (by an order of magnitude I'd say)

**Comment by sorin-davidoi** [comment]
We are working on making swiping columns faster - it is indeed annoying that the content and the icon at the top are not in sync for ~1 second. Thanks for commenting, will make a pull request to increase the delta - 25 / 30 pixels should do it.

**Comment by sorin-davidoi** [comment]
Regarding disabling it, this was a highly requested feature, we just need to make sure it is not triggered by accident.

**Comment by nightpool** [comment]
I think the bigger issue here is the lack of visual feedback. It's impossible to tell when you MIGHT be triggering a swipe, so it ends up coming out of nowhere when it does happen.

**Comment by jalefkowit** [comment]
I'm not sure why this issue has been closed; I still run into accidental column changes via swipe all the time on multiple devices (iPad Air 2 in Safari, Galaxy S6 in Firefox). Despite my going out of my way to try and keep my scrolling gestures perfectly vertical, it happens frequently enough to make the mobile web version of Mastodon unusable.

**Comment by nightpool** [comment]
@jalefkowit These problems were fixed in the upcoming version of Mastodon, which isn't out to most instances yet. What version is your instance using?

**Comment by jalefkowit** [comment]
@nightpool I'm on octodon.social, which as of this writing is running 1.4.7.
