### ISSUE TITLE
Content Preferences

### ISSUE THREAD

**Issue by dn3s** [tootsuite/mastodon#4048]
I think it would be beneficial for users to customize what sensitive content is shown by default. A good starting point would be a single global toggle (disabled by default), labelled something like "show sensitive content", that would expand CW'd posts unless explicitly collapsed.

Better yet would be an option to give a list of topics to automatically expand. The for example, a journalist could set posts tagged "politics" to automatically expand. This would have some non-trivial elements to it, such as figuring out what exactly constitutes a match (for example, if I choose to auto-expand "politics", and a post is tagged "politics and religion", should this count?).

One solution would be, instead of manually entering a list of topics to expand, have a button next to the "show more" button, something like "always show more", that would expand only exact matches (with case, spacing etc normalized). Then the list can be a lot longer and messier without having to worry about manually maintaining it.

**Comment by miwilc** [comment]
I don't see the point of this long term, since people will create more tags leading to neverending lists.

And people will still use the wrong tags for posts, making this pointless.

I feel that I like it as it is.

**Comment by dn3s** [comment]
if it saves me 70% of clicks, it's helpful. Also, a single toggle you can flip on and off on good or bad days would be handy too to save on clicking. I'm considering making a browser extension to do this, but it seems like a broadly useful enough feature to warrant a feature request

**Comment by miwilc** [comment]
@dn3s I think the global switch is cool, but I feel the individual ones will be too hard to handle.

**Comment by Cassolotl** [comment]
You all might be interested to see #1123 - "Feature request - preferences setting to auto-expand CW". It includes a [comment](https://github.com/tootsuite/mastodon/issues/1123#issuecomment-292480033) from @wxcafe:

>It would be nice to have a "default policy about CW'd posts" that the user can set open or closed (and that defaults to closed) and then **a list of blacklist terms so that you can have it open by default except for such and such terms.**

**Comment by dn3s** [comment]
I don't know how i missed this one! I will close this issue and move on over there. Thanks!
