### ISSUE TITLE
Federation does not seems to work

### ISSUE THREAD

**Issue by milouse** [tootsuite/mastodon#405]
Hi!

I try to install and run my own instance of mastodon. The installation procedure flows without errors and I succeded to have mastodon [apparently running](http://ublog.depar.is) (https will come when I'll renew my ssl cert or maybe sooner. But as a single user instance I'm not afraid of not secure connection for now).

However, nothing seems to work: I can post message and see them in the public timeline of my instance, but nothing else show up. I can follow people after having add them manually, but their timeline keeps quiet. No error in the web console.

Do I forgot to do something to retrieve external posts ? What can I do to begin to see content from other pods ?

Where can I look for further information ? I see no error in the logs of puma or my reverse proxy.

Thanks in advance for your help.

[edit: mismatch domain name]

**Comment by milouse** [comment]
Yes: I follow you since 9 days and nothing show up on my timeline even if you seems to be a [regular poster](https://mastodon.social/users/Gargron)

**Comment by Gargron** [comment]
I tried opening your website and it says "server not found". Possibly a DNS issue of your domain name not being resolvable?

**Comment by milouse** [comment]
Sorry, it is ublog.depar.is, I mismatch my domain name (it has always been ublog.depar.is, I just made the mistake here).

**Comment by Gargron** [comment]
Sorry for the long delay, had been busy with other things. I just tried interacting with your instance and got a SSL error.

Mastodon always tries connecting over SSL first. However, if that fails because the certificate is invalid or expired (as opposed to HTTPS not being available at all), it doesn't try to connect over HTTP, it just fails. I tried visiting your site over HTTPS, and indeed, it's available but misconfigured - your certificate is not valid for that subdomain.

**Comment by milouse** [comment]
Ok thanks for the explanation. I don't take attention to my webserver default configuration, which exposes this certificate. I'll try to add one to see if it works.

**Comment by milouse** [comment]
For your information, it does not work either with a correct certificate. As I do not have time to further investigate, I'll wait for a more stable version / rich documentation to give it a second chance.

**Comment by ineffyble** [comment]
Happy to provide further troubleshooting if you'd like - the Mastodon IRC on irc.freenode.net #mastodon is a good place for support.
