### ISSUE TITLE
is possible to setup server without name mastodont?

### ISSUE THREAD

**Issue by Ox16** [tootsuite/mastodon#4052]
I thinks the mastodont graphics and name is very nice. But my friend ask me: Is possible to using my own images and my own url name ?
I would make polish version with my own graphics and specific for polish language name.

**Comment by Cassolotl** [comment]
Yeah, lots of people buy interesting domains and change the graphics! The instance I mostly use is https://cybre.space, but https://awoo.space is another good example of an instance that's using its own name and graphics.

**Comment by wxcafe** [comment]
This is legally possible, and it's technically pretty easy to do, you can find the media files being served in the repo. Closing

**Comment by xor256** [comment]
This instances change only images not NAME mastodon
