### ISSUE TITLE
Follow/unfollow button and Back button are too close

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#4054]
On mobile devices, sometimes I touch follow/unfollow button instead of Back button accidentally. I think those buttons are too close.

![image](https://user-images.githubusercontent.com/705555/27793199-05a4df0e-6038-11e7-8fe3-685a34a4e378.png)

Some instances has replaced the button and followed status. 

![image](https://user-images.githubusercontent.com/705555/27793607-bb270860-6039-11e7-8470-1ddd75675116.png)

or, moving Back button to right side like other columns also may be good.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Habu-Kagumba** [comment]
@unarist @wxcafe 
I made a PR fixing this issue. Please review.
