### ISSUE TITLE
home timeline lost after upgrade and a force re-build timeline

### ISSUE THREAD

**Issue by rnr2001** [tootsuite/mastodon#4056]
Please excuse my English.

I upgraded instance from v1.4.3 to v1.4.7.

I launch maintenance command
RAILS_ENV=production bundle exec rake mastodon:feeds:clear_all
because some users complained about false timeline.

Since, on home timeline, can't see statuses before the upgrade and maintenance command.

But the timeline is good if consulted undirectly via a other count.

It is a bug or a normal behavior of the maintenance command?

It is possible to refind the home timeline?

Anyway, thanks for your concern.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
You'll need to rebuild feeds for your users. Open the rails console and execute:

```ruby
User.active.find_each { |u| RegenerationWorker.perform_async(u.account_id) }
```

It will rebuild in the background, but after a while, the feeds should be back.

**Comment by rnr2001** [comment]
thanks a lot for your answer but in rails console User.active don't exist

maybe User.confirmed?

**Comment by Gargron** [comment]
My bad, we had `inactive` so I thought we also had the opposite. You'll have to spell it out:

```ruby
User.where(arel_table[:current_sign_in_at].gte(ACTIVE_DURATION.ago)).find_each { |u| RegenerationWorker.perform_async(u.account_id) }
```

**Comment by rnr2001** [comment]
thanks, really, but  arel_table don' exist

NameError: undefined local variable or method `arel_table' for main:Object

**Comment by rnr2001** [comment]
Ok, I modified the app/models/user.rb and add this line : 
`  scope :active, -> { where(arel_table[:current_sign_in_at].gteq(ACTIVE_DURATION.ago)) }` 
just under inactive.(gte don't exist and I find gteq)

After, I re-execute your first command : 
`User.active.find_each { |u| RegenerationWorker.perform_async(u.account_id) }`
and the result is `=>nil`

All is Ok!

thanks a lot for your concern Gargron.

**Comment by dereckson** [comment]
For reference, User.active now exists.
