### ISSUE TITLE
Something wrong with relationships API

### ISSUE THREAD

**Issue by noraworld** [tootsuite/mastodon#4063]
I request to the endpoint `/api/v1/accounts/relationships` to get the relationships between an authenticated user and other users, but receive no response.

```sh
curl http://mastodon.dev/api/v1/accounts/relationships -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -F "id=1"
# nothing returns
```

I expect this endpoint returns a collection of the following result.

```json
{
  "id":              1,
  "following":       true,
  "followed_by":     true,
  "blocking":        false,
  "muting":          false,
  "requested":       false,
  "domain_blocking": false
}
```

Requesting to this endpoint without any query parameters, it returns an empty object, though this endpoint requires account IDs.

```sh
curl http://mastodon.dev/api/v1/accounts/relationships -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# returns []
```

I tried the query parameter of an array, but the result was same.

Am I using this endpoint by mistake, or is something wrong with it?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Does an account with id=1 exist?

**Comment by noraworld** [comment]
@Gargron Yes, exist.

**Comment by Gargron** [comment]
I don't remember what -F does, but can you try ?id=1 as part of the URL? Same result?

**Comment by noraworld** [comment]
@Gargron Sorry, I misunderstood the behavior of curl -F option. This option is used when sending a form data. So this option is invalid in this case. I tried the query parameter `?id=1`, and it worked properly.

However, a similar issue happens in [the Ruby library for the Mastodon API](https://github.com/tootsuite/mastodon-api). When I request the same endpoint using this library, an error occurs.

```ruby
require 'mastodon'
client = Mastodon::REST::Client.new(base_url: 'http://mastodon.dev', bearer_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
client.relationships(1)
```

The error message is:

```
/usr/local/lib/ruby/gems/2.4.0/gems/http-2.2.2/lib/http/mime_type.rb:37:in `[]': Unknown MIME type: text/html (HTTP::Error)
	from /usr/local/lib/ruby/gems/2.4.0/gems/http-2.2.2/lib/http/response.rb:141:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mastodon-api-1.1.0/lib/mastodon/rest/request.rb:22:in `perform'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mastodon-api-1.1.0/lib/mastodon/rest/utils.rb:10:in `perform_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mastodon-api-1.1.0/lib/mastodon/rest/utils.rb:27:in `perform_request_with_collection'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mastodon-api-1.1.0/lib/mastodon/rest/relationships.rb:13:in `relationships'
	from main.rb:5:in `<main>'
```

**Comment by Gargron** [comment]
When sending multiple IDs, are you using `?id[]=1&id[]=2` etc?

**Comment by noraworld** [comment]
@Gargron It works properly on curl.

```sh
curl --globoff "http://mastodon.dev/api/v1/accounts/relationships?id[]=1&id[]=2" -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```

But as for the Ruby library, I still have the problem. Should I close this issue and reopen at [tootsuite/mastodon-api](https://github.com/tootsuite/mastodon-api)?

**Comment by Gargron** [comment]
Seems like it's been reported: https://github.com/tootsuite/mastodon-api/issues/3

I am very sorry, I am not maintaining the ruby gem well. Cannot focus on it. If anyone wants to become its maintainer, be my guest.

**Comment by noraworld** [comment]
@Gargron May I consider this problem library specific bugs?

**Comment by Gargron** [comment]
Yes.

**Comment by noraworld** [comment]
@Gargron I see. Thank you for your help.
