### ISSUE TITLE
Introduce Basic English

### ISSUE THREAD

**Issue by m4sk1n** [tootsuite/mastodon#4069]
In my opinion adding [Basic English](https://en.wikipedia.org/wiki/Basic_English) as one of the languages available on Mastodon would improve a11y and make it easier to use in countries where English isn't popular and l10n of Mastodon isn't complete.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
~[ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).~ not a bug

**Comment by nightpool** [comment]
Are there projects other then Wikipedia that support Basic English as an option? What are the guidelines for localizing a software project into Basic English?

**Comment by m4sk1n** [comment]
@nightpool, why can't we just follow these guidelines: https://simple.wikipedia.org/wiki/Wikipedia:How_to_write_Simple_English_pages

**Comment by Gargron** [comment]
What text on mastodon is more complicated than basic english?
