### ISSUE TITLE
Retrying dead jobs in sidekiq leads to 403 Forbidden error

### ISSUE THREAD

**Issue by rtucker** [tootsuite/mastodon#4070]
This was originally issue #3189 but it was closed unresolved.

Steps to reproduce:

1) As an admin, go to Preferences -> Administration -> Sidekiq
2) Go to the Retries tab (https://hostname/sidekiq/retries)
3) Select an item then click "Retry Now" at the bottom, or simply select "Retry All" at the bottom
4) Observe the display of a "403 Forbidden" error

This also affects the Dead tab (https://hostname/sidekiq/morgue).

This has been affecting me since before 1.4, and is still present on 1.4.7.  My instance is running inside of Docker using the standard installation instructions, and my web browser is Chromium (Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 17.04 (64-bit)).

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by rtucker** [comment]
closing as the original issue was reopened

**Comment by nightpool** [comment]
Please do not open duplicate issues for things that are closed. Just ask for them to be re-opened.
