### ISSUE TITLE
Subscription model

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#4071]
I would like to use a subscription model for accounts, such that holding an account costs $5/mo.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
I'm not seeing a question here, so i'm closing the issue. Feel free to re-open it if you had a question or problem with the code.

**Comment by SoniEx2** [comment]
It's a feature request.

**Comment by nightpool** [comment]
For what, integrating payment processing into mastodon? Unfortunately that's not really something Mastodon can do—it has to be set up by the admin.

**Comment by SoniEx2** [comment]
I want my instance to require you to pay $5/mo for each account you have.

**Comment by ggtea** [comment]
You can manually create account for paid user. You can manually suspend user who stops paying.
It's maybe maximum Mastodon can provides.
Implementing automated payment is really dangerous. What can we do when it have bug with payment?

**Comment by SoniEx2** [comment]
The LICENSE includes a liability disclaimer. The admin would be the only one liable for it.
