### ISSUE TITLE
expanding this toot freezes my browser

### ISSUE THREAD

**Issue by nightpool** [tootsuite/mastodon#4073]
https://computerfairi.es/@boots/713704

I'm assuming this is because it has 500 newlines, so 500 `<br>` tags or `<p>` tags or something. Or something to do with the unicode processing involved—even loading https://computerfairi.es/users/boots/updates/22317.atom in chrome takes forever (but a normal amount of time serverside)

@no-boot-device could explain more about what's going on here specifically.

**Comment by nolanlawson** [comment]
I tested in Chrome and can confirm it takes ~35s just to do a layout (on a Macbook Air). This appears to be some kind of font issue?

**Comment by Gargron** [comment]
Couldn't reproduce on Firefox

**Comment by nolanlawson** [comment]
Cannot reproduce in Safari or Edge either. This is a Chrome bug AFAICT.

**Comment by nolanlawson** [comment]
Filed bug on Chrome: crbug.com/740144
