### ISSUE TITLE
1.4.7 mastodon-streaming.service Failure

### ISSUE THREAD

**Issue by Letiteuf55** [tootsuite/mastodon#4076]
Since i update to 1.4.7 (prev 1.4.6) i have this error : 

> ● mastodon-streaming.service - mastodon-streaming
>    Loaded: loaded (/etc/systemd/system/mastodon-streaming.service; enabled)
>    Active: failed (Result: start-limit) since mer. 2017-07-05 13:47:03 CEST; 2min 58s ago
>   Process: 931 ExecStart=/usr/bin/npm run start (code=exited, status=1/FAILURE)
>  Main PID: 931 (code=exited, status=1/FAILURE)
> 
> juil. 05 13:47:03 vps401038.ovh.net systemd[1]: Unit mastodon-streaming.service entered failed state.
> juil. 05 13:47:03 vps401038.ovh.net systemd[1]: mastodon-streaming.service holdoff time over, scheduling restart.
> juil. 05 13:47:03 vps401038.ovh.net systemd[1]: Stopping mastodon-streaming...
> juil. 05 13:47:03 vps401038.ovh.net systemd[1]: Starting mastodon-streaming...
> juil. 05 13:47:03 vps401038.ovh.net systemd[1]: mastodon-streaming.service start request repeated too quickly, refusing to start.
> juil. 05 13:47:03 vps401038.ovh.net systemd[1]: Failed to start mastodon-streaming.
> juil. 05 13:47:03 vps401038.ovh.net systemd[1]: Unit mastodon-streaming.service entered failed state.

How can i resolve this ? I reboot the server but no change...

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
We would need some sort of logs to begin helping you here. Do you see any
error logs or tracebacks anywhere?

**Comment by Letiteuf55** [comment]
Where can i find this kind of logs ?

**Comment by Letiteuf55** [comment]
i'm sort of newbie here... I'm on Debian 8 and don't know where is the log who help you...

**Comment by Letiteuf55** [comment]
Today's log

> -- Logs begin at mer. 2017-07-05 13:46:55 CEST, end at jeu. 2017-07-06 13:42:04 CEST. --
> juil. 05 13:46:56 vps401038.ovh.net systemd[1]: Starting mastodon-streaming...
> juil. 05 13:46:56 vps401038.ovh.net systemd[1]: Started mastodon-streaming.
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: > mastodon@ start /home/mastodon/live
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: > node ./streaming/index.js
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: /home/mastodon/live/streaming/index.js:30
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: [config.user, config.password] = params.auth.split(':');
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: ^
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: ReferenceError: Invalid left-hand side in assignment
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: at exports.runInThisContext (vm.js:53:16)
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: at Module._compile (module.js:373:25)
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: at Object.Module._extensions..js (module.js:416:10)
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: at Module.load (module.js:343:32)
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: at Function.Module._load (module.js:300:12)
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: at Function.Module.runMain (module.js:441:10)
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: at startup (node.js:140:18)
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: at node.js:1043:3
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! Linux 3.16.0-4-amd64
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! node v4.8.3
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! npm  v2.15.11
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! code ELIFECYCLE
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! mastodon@ start: `node ./streaming/index.js`
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! Exit status 1
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR!
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! Failed at the mastodon@ start script 'node ./streaming/index.js'.
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! This is most likely a problem with the mastodon package,
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! not with npm itself.
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! Tell the author that this fails on your system:
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR!     node ./streaming/index.js
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! You can get information on how to open an issue for this project with:
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR!     npm bugs mastodon
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! Or if that isn't available, you can get their info via:
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR!
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR!     npm owner ls mastodon
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! There is likely additional logging output above.
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! Please include the following file with any support request:
> juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR!     /home/mastodon/live/npm-debug.log
> juil. 05 13:46:58 vps401038.ovh.net systemd[1]: mastodon-streaming.service: main process exited, code=exited, status=1/FAILURE
> juil. 05 13:46:58 vps401038.ovh.net systemd[1]: Unit mastodon-streaming.service entered failed state.
> juil. 05 13:46:59 vps401038.ovh.net systemd[1]: mastodon-streaming.service holdoff time over, scheduling restart.
> juil. 05 13:46:59 vps401038.ovh.net systemd[1]: Stopping mastodon-streaming...
> juil. 05 13:46:59 vps401038.ovh.net systemd[1]: Starting mastodon-streaming...
> juil. 05 13:46:59 vps401038.ovh.net systemd[1]: Started mastodon-streaming.
> juil. 05 13:46:59 vps401038.ovh.net npm[571]: > mastodon@ start /home/mastodon/live
> juil. 05 13:46:59 vps401038.ovh.net npm[571]: > node ./streaming/index.js
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: /home/mastodon/live/streaming/index.js:30
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: [config.user, config.password] = params.auth.split(':');
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: ^
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: ReferenceError: Invalid left-hand side in assignment
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: at exports.runInThisContext (vm.js:53:16)
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: at Module._compile (module.js:373:25)
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: at Object.Module._extensions..js (module.js:416:10)
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: at Module.load (module.js:343:32)
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: at Function.Module._load (module.js:300:12)
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: at Function.Module.runMain (module.js:441:10)
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: at startup (node.js:140:18)
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: at node.js:1043:3
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! Linux 3.16.0-4-amd64
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! node v4.8.3
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! npm  v2.15.11
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! code ELIFECYCLE
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! mastodon@ start: `node ./streaming/index.js`
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! Exit status 1
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR!
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! Failed at the mastodon@ start script 'node ./streaming/index.js'.
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! This is most likely a problem with the mastodon package,
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! not with npm itself.
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! Tell the author that this fails on your system:
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR!     node ./streaming/index.js
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! You can get information on how to open an issue for this project with:
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR!     npm bugs mastodon
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! Or if that isn't available, you can get their info via:
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR!
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR!     npm owner ls mastodon
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! There is likely additional logging output above.
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR! Please include the following file with any support request:
> juil. 05 13:47:00 vps401038.ovh.net npm[571]: npm ERR!     /home/mastodon/live/npm-debug.log
> juil. 05 13:47:00 vps401038.ovh.net systemd[1]: mastodon-streaming.service: main process exited, code=exited, status=1/FAILURE
> juil. 05 13:47:00 vps401038.ovh.net systemd[1]: Unit mastodon-streaming.service entered failed state.
> juil. 05 13:47:00 vps401038.ovh.net systemd[1]: mastodon-streaming.service holdoff time over, scheduling restart.
> juil. 05 13:47:00 vps401038.ovh.net systemd[1]: Stopping mastodon-streaming...
> juil. 05 13:47:00 vps401038.ovh.net systemd[1]: Starting mastodon-streaming...
> juil. 05 13:47:00 vps401038.ovh.net systemd[1]: Started mastodon-streaming.

**Comment by ykzts** [comment]
@Letiteuf55 

> `juil. 05 13:46:58 vps401038.ovh.net npm[460]: npm ERR! node v4.8.3`

Can you update Node.js to version 6.11.0. Mastodon is required Node.js v6.x more than.

**Comment by Letiteuf55** [comment]
Let me try to do this.

**Comment by Letiteuf55** [comment]
Thanks

> ● mastodon-streaming.service - mastodon-streaming
>    Loaded: loaded (/etc/systemd/system/mastodon-streaming.service; enabled)
>    Active: active (running) since jeu. 2017-07-06 15:23:39 CEST; 19s ago

But my instance is still out.
I reinstall the latest version of Mastodon in order to complete the failed one but no lucky...

**Comment by Letiteuf55** [comment]
Ok, i just forget to follow the guidelines when i update.
for this version [https://github.com/tootsuite/mastodon/releases/tag/v1.4.2](1.4.2)

**Comment by Letiteuf55** [comment]
It's working now !
Thanks for your help 👍
