### ISSUE TITLE
feature request: mute toots by _cw text_

### ISSUE THREAD

**Issue by erisdev** [tootsuite/mastodon#4081]
as in, if the cw field specifically contains these keywords, because i'd love to be able to hide messages that are `cw`ed _for_ politics but not necessarily all messages that might _contain_ the word politics in an innocuous context.

also, as it stands, the regexp filter doesn't even look at the contents of a cw when considering a toot for filtering, which is unfortunate. to paraphrase a friend, it can be just as damaging to see a cascade of cw this cw that as it is to see the hidden contents directly.

**Comment by deutrino** [comment]
List of dupes I found of this issue:

- #694 (muting keywords from timelines)
- #1158 (muting keywords from timelines)
- #2453 (muting hashtags and keywords from timelines)
- **#3848 (muting by keywords, improve the accessibility beyond "lern2regex noob", listed as a priority for version 2.1)**
- #4081 (specifically requesting that muting by keyword work in CWs as well)

**Comment by huertanix** [comment]
I'm having trouble navigating the progress of this issue, do keyword filters take cw strings into account now?

**Comment by Gargron** [comment]
Yes, they always had.
