### ISSUE TITLE
version number and notification when a new update is available

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#409]
in the bottom of the dashboard/left-most column, a version number and "update available" link when such an update is available due to a refresh is a great plan. this would also benefit from patch notes to make everything clearer to users. once a system for this is set up, it would probably be very easy to do this, thus keeping users informed, and everything less opaque. this could help morale as well, since it means people can know when things are being updated, and what, just by clicking a link

**Comment by ashfurrow** [comment]
The version number was added to `/about/more` in https://github.com/tootsuite/mastodon/pull/2181 , so we just need to figure out  away to notify admins when an update is available. Perhaps this is best done with the mailing list? In which case we should make [the documentation](https://github.com/tootsuite/documentation/blob/04c49f4b502f576a9f722ef84399ef84c375aa43/Running-Mastodon/Administration-guide.md#mastodon-admin-mailing-list) much more apparent. Thoughts?

**Comment by hoodiek** [comment]
personally i think it being in the about/more is a bit too hidden, having it more user facing, such as the bottom left in compose column, is a much better placement for it. alongside this, i would propose each update come with a patch notes list that can be viewed by clicking the version number. a big popup warning in the settings menu for admins seems like the best case for showing when an update is available, coz they probably are already doing admin work when they enter that screen (checking reports, for example)

**Comment by nolanlawson** [comment]
This sounds like something that may be best solved with #2917. Service Worker is explicitly designed to do the thing where:

1. When the assets change at all, the `sw.js` changes
2. The browser realizes at some point that the `sw.js` has changed
3. At this point the SW can "skip waiting" and take over in place of the last SW, or (more safely) just register itself and swap itself in the next time the user refreshes
4. One of the most common UI conventions for this is to show the user a popup saying "hey, if you refresh the page you'll get the new updated version."

Note saying this _needs_ Service Worker, but it would go hand-in-hand very nicely with it.

**Comment by Gargron** [comment]
@nolanlawson The core of this feature request is a "patch notes"/changelog modal to be displayed when a new version is released.

I actually have no idea how to design that, at the moment.

**Comment by nolanlawson** [comment]
Sorry, I misunderstood the feature. You're right; it's a separate concern.

**Comment by wakest** [comment]
Still seems like there is no way to see what version mastodon is running except by going to about/more and that seems quite non-intuitive. Having the version number (linked to the release notes) in this blurb "Mastodon is open source software. You can contribute or report issues on GitHub at tootsuite/mastodon." thats displayed in on the bottom of the getting started pane makes the most sense to me.
