### ISSUE TITLE
Docker upgrade failed at [Webpacker] Compilation Failed

### ISSUE THREAD

**Issue by Elmit2015** [tootsuite/mastodon#4099]
I tried to upgrade a docker version, starting from a running 1.3.3. I constantly fail. The latest output you can see at: https://pastebin.com/eWbmpgbN

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
```
$ "/mastodon/node_modules/.bin/webpack" --config /mastodon/config/webpack/production.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 
(node:153) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
Killed
error Command failed with exit code 137.
```

Looks like Webpack process was killed due to out of memory. `assets:precompile` on 1.4.7 needs about 1.5GB free memory (see #4059).

**Comment by Elmit2015** [comment]
Thanks! I solved by adding a swapfile.
I get now no error at all. However, I still get the picture: We're sorry, but something went wrong.

How do I track this one down?

**Comment by nolanlawson** [comment]
Check if all the services are running: streaming, web, sidekiq. It sounds like the web service is not running.

**Comment by Elmit2015** [comment]
docker-compose ps
        Name                      Command               State                Ports               
------------------------------------------------------------------------------------------------
mastodon_db_1          docker-entrypoint.sh postgres    Up      5432/tcp                         
mastodon_redis_1       docker-entrypoint.sh redis ...   Up      6379/tcp                         
mastodon_sidekiq_1     /usr/local/bin/run bundle  ...   Up      3000/tcp, 4000/tcp               
mastodon_streaming_1   /usr/local/bin/run npm run ...   Up      3000/tcp, 0.0.0.0:4000->4000/tcp 
mastodon_web_1         /usr/local/bin/run bundle  ...   Up      0.0.0.0:3000->3000/tcp, 4000/tcp

**Comment by Elmit2015** [comment]
'docker-compose logs' brings a lots of lines at the end:
 db_1         | FATAL:  role "mastodon1" does not exist

 My history shows: 
  508  docker-compose build
  509  docker-compose run --rm web rails mastodon:maintenance:prepare_for_foreign_keys
  510  docker-compose run --rm web rails db:migrate
  511  docker-compose run --rm web rails assets:precompile
  512  docker-compose up -d

What am I missing?

**Comment by Gargron** [comment]
Did you modify the DB_* variables in the .env file? With docker deployments you don't need to touch those. The db user should be "postgres" and not "mastodon1"

**Comment by Elmit2015** [comment]
No, I did not modify anything.

That's what I tried to do from the beginning:
cd mastodon
git fetch
git status
git reset HEAD v1.4.7
git status
git stash
git checkout v1.4.7
git stash pop
docker 
since it still notw working, I go back in my output and found that it failed to compile Webpacker-compose build

sudo chown -R 991:991 public/system
docker-compose run --rm web rails mastodon:maintenance:prepare_for_foreign_keys
docker-compose run --rm web rails db:migrate
docker-compose run --rm web rails assets:precompile
docker-compose run --rm web rails r Rails.cache.clear

docker-compose up -d

How to fix it?

**Comment by Elmit2015** [comment]
I checked my (current) file .env.production and indeed I can remember, while I was initially setting up 1.2.3 I changed 
DB_USER=your_username
DB_NAME=your_databasename
DB_PASS=your_password
