### ISSUE TITLE
bug: right column stuck when you delete a toot you are viewing the context of

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#410]
![2017-01-05_11-51-38](https://cloud.githubusercontent.com/assets/23704040/21689115/58927fba-d33d-11e6-83ba-652cd4fab48b.png)
![2017-01-05_11-51-46](https://cloud.githubusercontent.com/assets/23704040/21689116/5a5515f6-d33d-11e6-84d5-7e3e1709a406.png)
to replicate: create a toot, view toot, then delete toot

**Comment by yiskah** [comment]
Issue #465 could be merged into this one. @Gargron
