### ISSUE TITLE
[Feature] Customisable Code of Conduct/Terms of Service page

### ISSUE THREAD

**Issue by fpiesche** [tootsuite/mastodon#411]
As per @TrevInc's comment on issue #392 it might be worth adding an optional Terms of Service/Code of Conduct page that can be edited from the server admin page for third party users who want to set up instances for their own communities. mastodon.social seems to be doing fairly well on a "don't be a jerk" policy so far but for purposes of scale something more formal might be needed in the medium term.

**Comment by ineffyble** [comment]
This was at least partially implemented in e25170f.
See https://mastodon.social/about/more - are you happy to close?

**Comment by Gargron** [comment]
The admin UI for editing this stuff is not well-polished atm but I think this can be closed.
