### ISSUE TITLE
/web/follow_requests needs a "no follow requests right now" message

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#4115]
/web/follow_requests needs a "no follow requests right now" message, for when there are no follow requests. Currently when there are no follow requests the column is just empty, which is disconcerting - you're like, "is it not loading properly or is it empty?"

![screen shot 2017-07-08 at 12 45 10](https://user-images.githubusercontent.com/6607512/27985044-4f277d3e-63db-11e7-9bfe-f2f4a8f71056.png)

* * * *

- [Yep] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by navihawk** [comment]
doesn't seem to be that big of a problem, though it could be misleading to some, thinking that the instance is having problems loading the follower requests.

**Comment by Cassolotl** [comment]
Yeah, it's not a big problem. But I didn't know we weren't allowed to post small problems here...? ;) Anyway, other columns have "there's nothing here" placeholder text when it's empty (like notifications), so it would be consistent. I get the feeling that this particular placeholder text has just been forgotten.

If it's an easy and simple thing to fix it, it could have the "suitable for beginners" tag.

**Comment by ilpianista** [comment]
This isn't only about _follow_requests_, but also _pinned_, _favourites_, _blocks_, _mutes_ and maybe others.

The technical reason is _notifications_ uses a `ScrollableList` which implements the empty message out of the box, while those pages don't.
