### ISSUE TITLE
Convert emoji shortcodes to UTF-8 in client for char-count + rendering purposes

### ISSUE THREAD

**Issue by clarcharr** [tootsuite/mastodon#4149]
Separated out from #1199 and #717 as a separate (but still important) issue. The codes should still be replaced on the server too, but there should be client support as well.

**Comment by bortzmeyer** [comment]
Why using shortcodes at all? Simply handle emojis as normal Unicode, period.

**Comment by clarcharr** [comment]
@bortzmeyer for a lot of people the shortcodes are easier to remember; it's sometimes easier to just say :smile: than to go through the emoji picker and pick the right one.

**Comment by bortzmeyer** [comment]
@clarcharr Your remark is about input. I was talking about output.
