### ISSUE TITLE
Hub does not federate

### ISSUE THREAD

**Issue by xkpd3** [tootsuite/mastodon#4154]
Hello,

My issue is probably related to my server setup. I'm asking for ideas how to troubleshoot it.

I'm hosting mastodon on mastodon.srv.hagen.coffee. It's open for registration, feel free to use it. However - even everything looks fine, it does not federate - sort of.

**Working:**
- Searching for remote accounts
- Subscribing to remote accounts
- Messages to remote accounts
- Remote accounts can find local accounts

**Not working:**
- Messages/replies from remote accounts
- The federated timeline is empty

There are no issues recorded in any log (mastodon logs, webserver logs).
There are no recently failed sidekiq tasks.

I've setup mastodon 1.4.7 (from FreeBSD ports) on FreeBSD 11-release with ruby 2.3.4p301 and postgresql95 behind an nginx reverse proxy. SSL (via letsencrypt) is terminated at the proxy end.

Mastodon runs in a jail with full outgoing internet connection. Incoming only https via reverse proxy is possible. I don't see any http errors (404/500) in the webserver logs, so I think this works fine.

Is there a debug flag or loglevel I can increase? I'm running out of ideas...

Any hint is appreciated.

Best Regards,
Stefan

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mitchellurgero** [comment]
Are you using docker by chance? Is there a way you can provide me a private login to check? (If you are uncomfortable, I can try to do the troubleshooting via skype screen sharing and SSH if you like)

Also please check my setup guide for some info on proper setup as well as some basic troubleshooting techniques. http://fediwiki.info/mastodon_install.html

**Comment by nightpool** [comment]
@michaeljdeeb i'm pretty uncomfortable with you asking admins for a login in our issue tracker, just fyi.

**Comment by nightpool** [comment]
@xkpd3 do you have webdomain and localdomain set to different values? 

you can definitely enable more thorough logging, but if you're not seeing any errors in the log files, i'm not sure how much it would help.

**Comment by mitchellurgero** [comment]
@nightpool My apologies. I will edit that comment - I have done troubleshooting like that with other instances in the past, and I am also a trusted developer for Mastodon GNUSocial and postActiv - I just wanted to help. And I will do what I can in a way that will not make anyone uncomfortable, at least, to the best of my ability.

However - the page I linked to is a tutorial and detailed write up on how to install Mastodon on Ubuntu, but should work (With some small adjustments) on FreeBSD 11 since it is a docker based install (As far as my tutorial goes.) The webdomain and localdomain variables are a good place to check as well since other instance wont be able to federate with if one of them is set to something like "localhost"

**Comment by michaeljdeeb** [comment]
@nightpool can you please edit your [comment](https://github.com/tootsuite/mastodon/issues/4154#issuecomment-314610989) as I am not involved.

**Comment by nightpool** [comment]
@michaeljdeeb my mistake—it autocompleted to your name initially.

**Comment by xkpd3** [comment]
@nightpool
- WEN_DOMAIN is not set
- LOCAL_DOMAIN is set to mastodon.srv.hagen.coffee

This is my full .env.production: [Gist Link](https://gist.github.com/5ffb7ee7f46ff274782f82635bbde236)

This is the local reverse proxy (nginx, running together with mastodon) - the file comes with the installation of mastodon in FreeBSD: [Gist Link](https://gist.github.com/deed7631d7d728c8dfd5958ffb56bb1c)

There is also an outside reverse proxy that does SSL and the vhost handling before handing the requests to the mastodon jail.

**Mastodon logs:** [Stream](https://gist.github.com/65e420467f793a548745c6399c359c2d), [Web](https://gist.github.com/3a86635dff8da39810cd19a4799d8627), [Workers](https://gist.github.com/aa12cc7a44d5f0f33aa2b0a6a970f5d3)

**Admin Area:** [Screenshots](https://seafile.srv.hagen.coffee/d/e6505a888bde43149e52/?p=/&mode=grid)

Is the PubSubHubbub supposed to be empty?

@mitchellurgero: Thanks you for the tutorial. I'll read through it. A docker install is quite different, but maybe the troubleshooting part gives me more ideas about where to look and what to try.

**Comment by xkpd3** [comment]
I think I found the issue.

Is it possible, that the remote hub is sending the message via HTTP to my hub and not via HTTPS?
If so, i'm sending an HTTP 301 request pointing to the HTTPS url.

I can see this in the log of the proxy on port 80
--
88.99.89.29 - - [12/Jul/2017:13:29:39 +0200] "POST /api/salmon/1 HTTP/1.1" 301 185 "-" "http.rb/2.2.2"
--

However, it looks like the post request does not follow the redirect. It just vanishes and will never reach the mastodon instance. Even the proxy on port 443 doesn't show the request.

**Comment by xkpd3** [comment]
Yep! That was/is the issue. I made Mastodon reachable via HTTP and now the federation works and the feed fills up with remote messages. Hoorayyy! 🎉 

The question would be why does mastodon not follow the redirect?

My nginx config concerning the redirect is a pretty standard catchall and forward: https://gist.github.com/f2ef9878e393568bc220300f3d6e6a5a

**Comment by mitchellurgero** [comment]
Well you are not redirecting properly then, because Mastodon does in fact redirect when required. (I used to run an instance this way) 

As for that nginx config you posted, how come you are not using Eugen's Nginx config file for this? it already covers redirecting, SSL, etc etc.

**Comment by xkpd3** [comment]
Did you have a look at the gist I posted? Eugens Nginx config is doing the exact same thing.

I have checked the redirect and compared it with other instances. It is identical.
```
sdk@~> curl -I http://toot.berlin
HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.1 (Ubuntu)
Date: Wed, 12 Jul 2017 12:20:33 GMT
Content-Type: text/html
Content-Length: 194
Connection: keep-alive
Location: https://toot.berlin/

sdk@~> curl -I http://mastodon.srv.hagen.coffee
HTTP/1.1 301 Moved Permanently
Server: nginx/1.12.0
Date: Wed, 12 Jul 2017 12:19:25 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: https://mastodon.srv.hagen.coffee/
```

I'll deploy Eugen's Nginx config now to the outer reverse proxy to see of this helps.

**Comment by mitchellurgero** [comment]
My apologies - I was not trying to imply the Gist you posted was wrong - but that your previous nginx config was incorrect (You posted, and I was typing a response as you posted the second post.)

**Comment by xkpd3** [comment]
I have an outer proxy which redirects everything to my jail on port 80. Inside the jail the nginx is running and distributing the request to port 3000 and 4000.

I just tried to deploy the Nginx config to the outer proxy and I stumbled over the reason why I have set it up like this. The outer proxy can not serve the content in mastodon/public directly.

In a nutshell, it looks like this:
![Mastodon Setup](https://www.hagen.coffee/img/mastodon.png)

I'll copy the files over for a test. But it's still strange that it looks like there is not even an attempt to connect after the 301.

**Comment by nightpool** [comment]
@xkpd3 yes, I'm guessing the problem is that you're advertising http urls, because you have LOCAL_HTTPS set to false. I'm not sure what the recommended configuration is for terminating SSL at an outer proxy, but still having rails advertise HTTPS urls.

the redirect is not handled because of weird spec reasons.

**Comment by mitchellurgero** [comment]
hmmm that is a strange way to do it, but if you got it working then awesome! Every server configuration is different (Unless you use the docker method to install)

**Comment by nightpool** [comment]
Okay, yeah, checked around some other issues, and the correct configuration is just to pass through the X-Forwarded-Proto header at both proxies, and make sure to set LOCAL_HTTPS to true. This is documented in the production guide, but it's not explained: https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md

here's the issue I found this from: https://github.com/tootsuite/mastodon/issues/899

If you set LOCAL_HTTPS to true and add the X-forwarded-proto header, does it work?

we should probably fix the documentation of that option a little bit.

**Comment by xkpd3** [comment]
Do I need to issue any rake command after changing the LOCAL_HTTPS variable?

**Comment by nightpool** [comment]
You'll need to re-subscribe to everyone you wanted to subscribe to. There should be a sidekiq job that does this automatically, once per day, but if you want to preempt it you can run `Scheduler::SubscriptionsScheduler.new.perform` in the console

**Comment by xkpd3** [comment]
Just setting the `X-Forwarded-Proto https;` header did not help. The behavior was the same.

I have cut out the second proxy, copied over the `/public` files and use the same nginx config I was using as inner proxy. Mastodon immediately started to work.

So, I know now that the issue is with the proxy. I will modify my setup now that the inner proxy only serves the /public files and do direct connection to the inner jail port 3000 and 4000 directly.

In case I find out how to do the double proxy properly with mastodon, I'll post it here. But for now, the issue can be closed.

Thank you @nightpool for diving into this issue.
