### ISSUE TITLE
Sessions detects Linux server as Internet Explorer on Windows 

### ISSUE THREAD

**Issue by LiamDawe** [tootsuite/mastodon#4161]
I use an auto-poster made in PHP that posts news to my Mastodon account from my website.

It's run from a CentOS 7 apache setup, but it seems Mastodon picks it up as 'Internet Explorer on Windows'.

**Comment by sorin-davidoi** [comment]
What user agent does it send?

**Comment by LiamDawe** [comment]
Ah hah, that's the ticket. Turns out the lib I use (https://github.com/TheCodingCompany/MastodonOAuthPHP) sets that!
