### ISSUE TITLE
Please submit WebSub implementation report

### ISSUE THREAD

**Issue by aaronpk** [tootsuite/mastodon#4173]
WebSub (formerly known as PubSubHubbub) is currently working its way through the standardization process at the W3C. In order to do so, we are collecting implementation reports that describe what parts of the spec have been implemented. We currently have a handful of implementation reports, but getting one from Mastodon would be very helpful as well.

Anyone can submit a report for Mastodon, so feel free to take this ticket. Basically we just need someone to answer a handful of questions about how Mastodon's WebSub implementation works. The instructions and questions [are available here](https://github.com/w3c/websub/tree/master/implementation-reports). If you want a tool to help answer the questions, you can use https://websub.rocks to work through the tests.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tantek** [comment]
Definitely preferable to have someone who is active in/on Mastodon submit a WebSub implementation report in case there are any questions / issues that require judgment calls etc. Disclosure: @aaronpk is a co-editor the WebSub spec (as well as creator of websub.rocks), and I'm a chair of the W3C Social Web Working Group that is producing/publishing WebSub. Feel free to ask any/all questions about specifics or process etc. Thanks!
(To be clear, Mastodon's existing PubSubHubbub 0.4 implementation should "just work" as WebSub with WebSub.rocks. If it doesn't, or if there are any places where you get stuck for any reasons, we want to know about it ASAP!)

**Comment by aaronpk** [comment]
@Gargron just [answered most of the questions in IRC](https://chat.indieweb.org/social/2017-07-12#t1499877019077000), so most of the work is done now. Just need a few more details answered and then someone to copy the answers to the report template.

**Comment by nightpool** [comment]
I tried running the websub tests a couple of weeks ago, but I couldn't get
any of them to work with mastodon.

**Comment by nightpool** [comment]
This is the error I'm getting:

> Error

> The content-type of the notification sent did not match the content-type of the topic URL. The hub must send a content-type header that matches the topic URL.

> Topic Content-Type: application/atom+xml; charset=utf-8
Content-Type sent:  application/atom+xml

**Comment by nightpool** [comment]
this was submitted months ago, whoops
