### ISSUE TITLE
[Feature Request] Users should be able to organize events

### ISSUE THREAD

**Issue by strand** [tootsuite/mastodon#4179]
Edited to add: **This issue is closed because the maintainers of Mastodon have tacitly indicated that this feature will not be added to it. If you are interested in a fediverse app which will have event functionality, check out [Aardwolf](https://github.com/BanjoFox/aardwolf)**, a project which has [events on its roadmap](https://github.com/BanjoFox/aardwolf/issues/105).

This is a somewhat large feature request. I'm filing this issue to determine interest from maintainers, and anticipate that completing this feature will require decomposing this request into many issues and treating this feature as a milestone.

While browsing my Mastodon instance, I came across a conversation where a tooter mentioned that a lack of an event organization feature was mentioned as a reason to not join Mastodon.

![conversation where a tooter toots, 'I tried to advertise my instance on facebook for example and people told me that if you guys had the capability to organize events they would use it, perhaps consider?'](https://user-images.githubusercontent.com/509611/28149824-44036d42-6745-11e7-87ac-04b5135637d9.PNG)

Would maintainers of Mastodon be interested in allowing tooters to create events? If so, I'd be glad to start writing user stories, developing, and otherwise collaborating. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This is a feature request ~This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).~

**Comment by mariusa** [comment]
Ease of confirmation from visitors without an account is crucial.
I want to organize an event and share a link to that. Visitors should see details, and easily signup (new mastodon account) to confirm participation.

Browsing all events in a location should also work, similar to
https://www.facebook.com/events/discovery/

**Comment by strand** [comment]
@m4sk1n Is there any chance this feature will be on the 2018 roadmap?

**Comment by m4sk1n** [comment]
@strand I don't know, @Gargron sometimes has to sleep, it's a big problem for the project… XD
https://mastodon.social/@Gargron/99079688369053501

**Comment by strand** [comment]
Is @Gargron the best person to speak to about the project's roadmap? If not, is there another person in charge I should reach out to?

**Comment by nightpool** [comment]
Yes Gargron has the final say on goals, scope, and road map. I think
there's a strong case to be made for this feature, but my first gut
reaction is it doesn't match the scope of the project—Mastodon is a
microblogging platforms, and microblogging is ephemeral by nature.

That said, I would still be open to hearing a strong argument about how
this fits into Mastodon's goals and vision.

**Comment by strand** [comment]
@Gargron Can you as benevolent dictator weigh in on whether this feature has roadmap potential OR designate a lieutenant to have a discussion/make a decision on your behalf?

I recognize how limited your time is, but there has been no feedback on this issue in almost six months. If this is a feature which aligns with the mastodon project, I'm glad to push it forward.

**Comment by jlaufersweiler** [comment]
In light of recent events, a lot of people are looking for a community-run/hosted social media option. In terms of what functionality most users actually need from such a thing, microblogging and messaging are two of the crucial uses.

The third one that comes up again and again is events. Organizing and discovering parties, concerts, demonstrations, scout meetings, etc. make up the other corner of the social-networking triangle. 

If Mastodon is going to be a microblogging platform only, it doesn't need this, though would perhaps benefit from being able to hook into other tools or providers for those services via OAuth /oEmbed/etc. 

If OTOH the mission extends to providing a platform for communities and individuals to autonomously take the reins of their social-networking needs, this is a necessity.

OpenConferenceWare is an MIT-licensed Rails tool that is geared towards academic conferences and such, perhaps a subset of its functionality could be a starting-point for similar capabilities in Mastodon.

**Comment by mbajur** [comment]
I have exact the same use case as Laurelai from a screenshot in OP - a lot of my potential users would be more than happy to drop facebook for mastodon if there were an Events feature available. That's the only thing that keeps them off.

Fingers crossed for accepting this as a feature on roadmap!

**Comment by strand** [comment]
I am taking @Gargron silence as tacit disapproval for this potential feature, and closing this issue.

**Comment by strand** [comment]
@jlaufersweiler You seem to have already poked around standards and protocols for establishing a micro-eventing service, do you think that a small, simple tool could be built just to handle it, using the fediverse ident as auth.

Ultimately, this doesn't need to be scoped into Mastodon, but it would be invaluable to have an event-organizing service that uses existing fediverse identities.

I do believe that most Mastodon admins would want this functionality… Maybe there is a way to plugin customizations into Mastodon.

I'd really appreciate any advice or guidance from folks who understand the details of fediverse protocols better than I do.

_back to the day job._

**Comment by BanjoFox** [comment]
Unfortunately I do not have a real feature list yet (its mostly in hand-written notes) but Events is one of the things we are trying to have day 1 in [Aardwolf](https://github.com/BanjoFox/aardwolf).  By that I mean version 1.0.0.  Ideally we'd have it in one of the betas, but there are SOO many moving pieces right now.

My view, is that Mastodon is supposed to be a Twitter-replacement (microblogging), which may be why these features are being ignored.  Aardwolf on the other hand is trying to be more like Facebook, which has a lot of the functionality that folks are looking for.

**Comment by strand** [comment]
Added a not to the original post indicating that further discussion should take place over at Aardwolf.

**Comment by nightpool** [comment]
I'm leaving this open because it's very highly requested, and if someone has a good idea on how to simplify it to fit into a microblogging framework it would be very welcome.

**Comment by zcdunn** [comment]
There's also [Get Together](https://github.com/GetTogetherComm/GetTogether). It's an event sharing platform. The lead developer has said he's looking for someone to implement Activity Pub.

**Comment by jlaufersweiler** [comment]
@strand, ActivityPub itself is fairly straightforward, just a class-inheritance-based JSON-style vocabulary for describing various interactions & their surrounding contexts. 

Adding such things to Mastodon would be non-trivial in so far as it doesn't currently have the data structures for all the things that are important for event organizing that simply aren't relevant for Toots or DMs. That's not to say they wouldn't be worthwhile additions, but it would require a lot of new moving parts. (If I had any Ruby skills, I'd offer to help rather than just kibbitz.)

That being said, even if Mastadon sticks to the subset of ActivityPub it implements thus far, I hope it does become capable of interacting with other federations whose hosts implement parts of the recommendation that it does not. That is to say, even if Mastodon users can't organize an event themselves, they ought to be able to receive & respond to announcements or invites for events hosted on compatible allied federations that do have that feature, and receive related notices in their stream.

The "compatible" part is a potential gotcha, insofar as many details in ActivityPub are left to implementers' discretion. It is encouraging at least in that respect to see Mastodon's mindshare as an early leader mean that its approaches are becoming something of an informal reference implementation of the basic activities among other implementers.  If they were to add event organizing to their toolset, their example would no doubt be valuable there as well.

A companion project to Mastodon that commits to API & schema compatibility with Mastodon such that it could share the same federation's back-end DB & directory resources while extending its functionality might be a worthwhile middle-ground.

**Comment by BanjoFox** [comment]
I would argue that because something is simple or easy to implement does not automatically mean that it should be done.  If the scope of Mastodon as an application is "micro-blogging service" then events, would seem to be outside of that scope.  

In my head it would be akin to adding an "Instagram-like photo-sharing" to an e-mail service.

**Comment by strand** [comment]
@nightpool I agree it would be great if this was implemented within Mastodon. However, having an open issue which isn't endorsed by @Gargron or another core contributor isn't helping anyone. It provides false hope to users and additional emotional weight for maintainers.

Closing again. _If you have ascertained buy in from maintainers_ please reopen.

**Comment by nightpool** [comment]
I am a maintainer........

**Comment by nightpool** [comment]
I mean, I'm down to leave this closed for now if you don't want it open if it's not going to be immediately addressed. But i don't think it's useful to discard the whole idea out of hand just because we haven't thought of a way to integrate it into microblogging yet.

**Comment by strand** [comment]
@nightpool No doubt. From what you said earlier in the thread I assume that @Gagron is the benevolent dictator. My assumption, based on commits and conversation is that @gagron and a handful of other contributors are empowered to drive and accept feature work.

If there was a PR related to this, would you have the authority to merge it? If so, then please reopen.

If we don't have the buy-in from the folks who can merge things to master, there's no point in having this issue, as its not on the roadmap. (Keeping the icebox clean let's folks focus on work that matters more.)

**Comment by JulianBissekkou** [comment]
Now after a few years and with the recent hype around mastodon as a twitter alternative would you guys reevaluate your decision and maybe add it to the roadmap?

**Comment by mcnesium** [comment]
@JulianBissekkou are you aware of [mobilizon](https://mobilizon.org)? we do have the fediverse. let's use it!
