### ISSUE TITLE
Link Atom IDs of other Mastodon servers to ActivityPub IDs

### ISSUE THREAD

**Issue by puckipedia** [tootsuite/mastodon#4213]
Currently, every post in Mastodon is represented in Atom by a `tag:` uri. e.g. `tag:mastodon.social,2016-03-16:objectId=1:objectType=Status`. Though, with ActivityPub support coming sometime in the near feature, these IDs would have to change, as ActivityPub IDs have to be resolvable.

One way to fix this is to change the status tag URIs to be actual IDs. This is pretty intrusive for other non-mastodon servers, or even mastodon servers that haven't been updated. Another way would be to also communicate an ActivityPub ID inside each Atom entry. Example from Kroeg:

```
<entry [snip]>
  <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
  <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
  <id>https://puckipedia.com/puck/status/6b52cbad</id>
  <author> [snip] </author>
  <link rel="alternate" type="application/json+ld; profile=&quot;https://www.w3.org/ns/activitystreams&quot;" href="https://puckipedia.com/puck/status/6b52cbad" />
  <link rel="self" type="application/atom+xml" href="https://puckipedia.com/puck/status/6b52cbad.atom" />
  <content type="html">Hello, world!</content>
  <link rel="object" type="application/ld+json; profile=&quot;https://www.w3.org/ns/activitystreams&quot;" href="https://puckipedia.com/puck/status/6b52cbad/hello-world" />
  [snip]
</entry>
```

The `rel="alternate"` points to the Create activity, and the `rel="object"` points to the object that was used in the Create. The Mastodon server could verify the object (e.g. by being on the same domain) and store it next to the uri and url it currently uses. When Mastodon then starts using ActivityPub to communicate, it can use this as the object instead of the OStatus tag when talking to other ActivityPub servers. This does mean storing another value next to each status.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Oh wow look you suggested this way before everyone else. Closed by #4815
