### ISSUE TITLE
Emoji picker can't insert multi-point emoji after PR #4202 and #4189

### ISSUE THREAD

**Issue by MightyPork** [tootsuite/mastodon#4217]
Testing on master, the emoji picker is unable to insert composite emoji, such as any of the flags, the family emojis (apart from the first one, which uses only one point), or the skin modifiers (but they didn't work before either).

In addition, the emoji inside the textarea render using the system font, which makes them look ugly and unreadable if you're not on a system with native emoji support.

Also, the emoji tooltips are gone, which was a really useful feature for deciphering hard-to-understand emojis in the timelines.

![screenshot_20170716_014206](https://user-images.githubusercontent.com/2041118/28243394-1002b338-69c8-11e7-80aa-8b2cbf6cd6bc.png)

**Comment by Gargron** [comment]
>In addition, the emoji inside the textarea render using the system font, which makes them look ugly and unreadable if you're not on a system with native emoji support.

Exactly my point too in #717

However, if you want the character counter to count emoji as one character (#776), this is sorta unavoidable - what other options do we have?

>the emoji picker is unable to insert composite emoji

I don't yet know why.

>Also, the emoji tooltips are gone, which was a really useful feature for deciphering hard-to-understand emojis in the timelines.

Yes, I agree they were nice, but they might not be worth it: https://github.com/tootsuite/mastodon/pull/4202#issuecomment-315445722

**Comment by MightyPork** [comment]
> - what other options do we have?

The only solution I see is to replace them with the emojione images online, while composing the toot, the way Twitter and Facebook do it. I'm not sure if there's a library for that, or they developed it in-house.

Example from Twitter:

![spectacle m24417](https://user-images.githubusercontent.com/2041118/28246068-d60a64fe-6a13-11e7-947e-3efa6fc2f773.png)

The images are in a separate container positioned absolutely over placeholder spans in the editor field.

**Comment by Gargron** [comment]
Okay, that means using something like Draft.js

**Comment by ekiru** [comment]
> However, if you want the character counter to count emoji as one character (#776), this is sorta unavoidable - what other options do we have?

If we are able to convert shortcodes to emoji on the client side (I'm not familiar enough with how Mastodon handles emoji to know if that's the case?) then it should be straightforward to do that. In place of

```
const text = [this.props.spoiler_text, this.props.text].join('');
```

at https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/features/compose/components/compose_form.js#L147 , do something like (assuming `emojify` converts shortcodes to corresponding emoji)

```
const text = [this.props.spoiler_text, emojify(this.props.text)].join('');
```

that `text` const then gets passed into the `CharacterCounter` component at https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/features/compose/components/compose_form.js#L201 and it will base its count on the emojify text instead.

The length check for disabling the submit button also uses the length of `text` so it'll also handle it properly.

**Comment by Gargron** [comment]
The emojify method might be slow enough to create noticeable lag when typing, or maybe it's fine, it has to be tested.
