### ISSUE TITLE
user blocking/whitelisting of entire domains

### ISSUE THREAD

**Issue by deckycoss** [tootsuite/mastodon#423]
i have a proposal for an interface that would allow individual users to control which GNU social / mastodon instances they would see posts from on the public timeline.

the interface would be a checklist, on the user settings page, of all GNU social instances that the current instance knows about. instances that are checked are whitelisted; everything else is blocked. there could be buttons for things like sorting the list and checking/unchecking all entries at once. there should also be a toggle for whether or not to automatically whitelist new instances.

it seems there's currently no way to find a list of all existing instances of GNU social or even just mastodon. however, as soon as you view an account that belongs to another instance, a reference to that account (and thus the instance it's on) is added to the current instance's database. so, populating the checklist shouldn't be hard.

if people like the sound of this then i would be willing to do the work on it. i finally have my own dev instance working outside of docker and while i'm new to rails, i feel capable of adding this feature.

see issues #231 and #344 for previous discussion on similar topics.

**Comment by krainboltgreene** [comment]
Would a "host file" like entry be a good first step?

**Comment by Gargron** [comment]
What do you mean by host file-like entry?

**Comment by krainboltgreene** [comment]
@Gargron:

``` html
<textarea />
```

**Comment by Gargron** [comment]
Oh! Hm. No I actually really like the idea of listing all known domains next to toggles. Beyond moderation it's also a pretty good tool for people to learn more about the fediverse. For reference you'd get the domains with a `Account.remote.select('distinct domain')`. I don't think the overhead of querying that and displaying a table with check boxes is that much worse than a textarea entry!

**Comment by krainboltgreene** [comment]
Got it! I'll work on this tonight if I get the ✅  from you.

**Comment by Gargron** [comment]
Alright, @deckycoss expressed interest in doing it though so just make sure you don't do the same thing twice. Also, it'll be easier to make a static version in the settings area first rather than implementing it as REST API + React.js stuff, that can be refactored into later.

**Comment by deckycoss** [comment]
actually, as i said in the first post, i would like to work on this. but if i need help from people more experienced with front-end then i'll say so

**Comment by krainboltgreene** [comment]
Sweet! Let me know.

**Comment by ineffyble** [comment]
Related: https://github.com/Gargron/mastodon/pull/302

**Comment by deckycoss** [comment]
@ineffyble oh! i didn't know anyone had already started work on this. do you plan to resume the patch? if not, maybe i could continue where you left off?

**Comment by ineffyble** [comment]
@deckycoss It's not mine, I just noticed it earlier. @hach-que - where's this at?

**Comment by hach-que** [comment]
I don't have any intention on finishing that contribution.

**Comment by hoodiek** [comment]
theoretically if the UI side filtering happens,  #231 shouldn't be so hard for the needed muting features, yeah?

**Comment by LogicalDash** [comment]
Will private posts federate to whitelisted domains? [This is a needed feature.](https://mastodon.social/web/statuses/2131341)

**Comment by KellerFuchs** [comment]
@LogicalDash Cannot see that toot, please use its public URI?

**Comment by LogicalDash** [comment]
https://mastodon.social/@pan/2131341

**Comment by coventry** [comment]
Is there an ETA on merging this? What's blocking it?

**Comment by Gargron** [comment]
Implemented in #2381, #3127
