### ISSUE TITLE
sidekiq not processing enqueued

### ISSUE THREAD

**Issue by xvilo** [tootsuite/mastodon#4248]
It seems that Sidekiq stopped processing the queue. It's just building up bit by bit. 
See: 
<img width="1337" alt="screen shot 2017-07-18 at 6 05 10 pm" src="https://user-images.githubusercontent.com/390769/28327425-aea20d78-6be3-11e7-8f63-bb20ce52d33a.png">

Also, I the instance is not federating anymore. Our toots are not seen by other instances, and we don't get any new toots. What could this be? 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Have you got a systemd service for sidekiq? It's all in the production docs I linked!

**Comment by xvilo** [comment]
ye
