### ISSUE TITLE
Remote instances not pulling my media

### ISSUE THREAD

**Issue by Komic** [tootsuite/mastodon#4257]
Hi,

as usual, this may be a really dumb issue but I'm out of ideas. Three weeks ago, remote instances started having issues with my media (avatar, header, attachments). The thing is, the problem only occurs on some instances, https://anticapitalist.party/ can't pull them, while https://octodon.social/ can for example.
Just posted [this](https://from.komic.eu/@shitpost/95204) toot: I can see remote instances requesting `https://from.komic.eu/system/media_attachments/files/000/008/022/original/da96a4d472cc81a3.png` (requests are 200ing), [here](https://anticapitalist.party/users/corzntin/updates/63895)'s the result on https://anticapitalist.party/.
Same thing with my avatar or header, as you can see (@corzntin@anticapitalist.party already tried forcing a refresh from the instance's panel, I already tried changing them).

The following stands out in ACP's logs:
`Jul 19 01:16:09 mastodon bundle[21226]: [paperclip] Content Type Spoof: Filename da96a4d472cc81a3.png (inode/x-empty from Headers, ["image/png"] from Extension), content type discovered from file command: inode/x-empty. See documentation to allow this combination.`

@vahnj@awoo.space also reports [this](https://awoo.space/users/vahnj/updates/86427).

Does anyone know what's happening here? My server does send the `image/png` content-type header, the extension is obviously correct, and a `file -b --mime da96a4d472cc81a3.png` does return `image/png` too. Pretty confusing.

Cheers.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Komic** [comment]
@Gargron saved the day: if you're encountering this, disable h2.
https://github.com/httprb/http/issues/422

**Comment by ixti** [comment]
All interested parts, please participate in discussion about switching underlying parser of http gem here: https://github.com/httprb/http/pull/433
