### ISSUE TITLE
CI builds failing due to missing translations

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#426]
As all recent builds on Travis seem to have failed due to missing localised strings, perhaps the i18n tests in rspec should be disabled for now?

**Comment by Gargron** [comment]
On one hand I wanna know when some localization is forgotten. On the other hand, I can't translate anything except English and German so these missing translations hang around forever. I dunno.

**Comment by Gargron** [comment]
Fixed by removing that test
