### ISSUE TITLE
Export toots to CSV

### ISSUE THREAD

**Issue by no-boot-device** [tootsuite/mastodon#4272]
It'd be nice if we could export our own toots for archival/searching/etc. 
However, there's currently no way to do this.
I've seen multiple people ask for it, dunno why I couldn't find an issue specifically for exporting.
Note that the export format doesn't necessarily have to be CSV.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by procedural** [comment]
+1

**Comment by procedural** [comment]
https://github.com/tootsuite/mastodon/pull/978#issuecomment-313535713

> toot export is on the backburner

Pretty import to the users tho, data loss in case of instance dropping is more important than any other feature I can imagine.

**Comment by procedural** [comment]
https://github.com/tootsuite/mastodon/issues/201

**Comment by aka-rin** [comment]
A few days ago I wrote [a simple script](https://gist.github.com/aka-rin/5f0e6b90836cb998c11b9178d7d90bb5) to export toots and media files with Mastodon API V1. 

According to the developers' replies in Github issues, there is still no consensus in exporting toots on server's side.
