### ISSUE TITLE
Conversations only show disconnected snippets when not all of the participants are in the federated TL

### ISSUE THREAD

**Issue by PubliqPhirm** [tootsuite/mastodon#4279]
# Example Setup

1. Alice, Bob, and Charlie are having a conversation where some of the toots are boosted by Daniel.  
2. You are following Daniel and your friend on your instance follows Charlie.
3. Daniel boosts one of Alice's toots from the conversation.
4. You find that toot interesting or lacking context so you click it to view the whole conversation.

# What you expect

To see the entire conversation or at least the whole of the specific thread that led up to the toot that Daniel boosted.

# What we actually see

A series of toots from Charlie with Alice's toot at the end.

This seems to be specifically notable on small instances with a slower federated timeline.  Large instances are more likely to have Alice, Bob, and Charlie all followed by at least one member.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I think this was fixed when ActivityPub happened - more toots in conversations get pulled into the expanded view now.
