### ISSUE TITLE
Update tab bar before column loading

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#4319]
When I change column by swiping, it looks like 1. swipe and dummy column appears 2. column appears 3. tab bar is updated. I think it would be nice if we update tab bar when the swipe animation completes.

![hoge](https://user-images.githubusercontent.com/705555/28500830-81360f3a-700a-11e7-9b9c-ba44c9681149.gif)

cc @sorin-davidoi

**Comment by sorin-davidoi** [comment]
The tab bar is hooked up to `react-router`, which unmounts the current component before changing the route (and the `active` attribute on the line). We could do some manual style overwrites when the animation completes.

**Comment by unarist** [comment]
I thought this might be (partially) fixed by delaying mount column, and tried reverting #4127 but not worked. Maybe it needs requestAnimationFrame or something, not only async operation using Promise.
