### ISSUE TITLE
Exclude domain from @handle character count

### ISSUE THREAD

**Issue by clarcharr** [tootsuite/mastodon#4346]
This would require some amount of extra validation to prevent against excessively long domain names. One main use case for this is bios, because linking to another account can end up using most of the character limit. Additionally, responding to a bunch of users can seriously use up the character count.

Perhaps this could add the caveat that you can't exceed two toot lengths total with the domains included, but otherwise in the global toot length count the @ domain parts aren't included, because they aren't displayed in the UI.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kensanata** [comment]
Closed by #4427, I think.
