### ISSUE TITLE
The file sw.js is not found

### ISSUE THREAD

**Issue by noraworld** [tootsuite/mastodon#4356]
I upgraded Mastodon to `v1.5.0rc1` (tagged release), but `sw.js` is not found.

https://mastodon.noraworld.jp/sw.js

I found `sw.js` on other instances, which version is `v1.5.0rc1`. I heard this is a specific problem with a deployment on Docker, which means it does not occur on non-Docker deployment. My instance is deployed with Docker.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment]
Maybe this can help? https://github.com/omanko-porn/omanko.porn/blob/master/Makefile#L23

**Comment by noraworld** [comment]
Yeah, this will probably work fine. Could this be implemented to [tootsuite/mastodon](https://github.com/tootsuite/mastodon) so `sw.js` can be generated automatically and served?

**Comment by Wonderfall** [comment]
I use Docker myself, with my own image wonderfall/mastodon, and I didn't have to mount another volume to get it working : https://social.targaryen.house/sw.js

I'll take a look later at this issue, but I see there's already 2 PR.
