### ISSUE TITLE
Push Notifications no longer working (Unauthorised)

### ISSUE THREAD

**Issue by isati** [tootsuite/mastodon#4375]
Since rebooting my server in an attempt to solve another issue, I can no seemingly no longer get the push notifications to register/authenticate.

I now get the following error from mastodon-web (master):

```
Jul 26 09:01:02  bundle[16127]: [5486ede6-1563-4d11-9b0f-1cccbfb25a0c] method=POST path=/api/web/push_subscriptions format=html controller=Api::Web::PushSubscriptionsController action=create status=500 er
Jul 26 09:01:02  bundle[16127]: body:
Jul 26 09:01:02  bundle[16127]: <HTML>
Jul 26 09:01:02  bundle[16127]: <HEAD>
Jul 26 09:01:02  bundle[16127]: <TITLE>UnauthorizedRegistration</TITLE>
Jul 26 09:01:02  bundle[16127]: </HEAD>
Jul 26 09:01:02  bundle[16127]: <BODY BGCOLOR="#FFFFFF" TEXT="#000000">
Jul 26 09:01:02  bundle[16127]: <H1>UnauthorizedRegistration</H1>
Jul 26 09:01:02  bundle[16127]: <H2>Error 400</H2>
Jul 26 09:01:02  bundle[16127]: </BODY>
Jul 26 09:01:02  bundle[16127]: </HTML>
Jul 26 09:01:02  bundle[16127]: ' duration=78.97 view=0.00 db=19.44
Jul 26 09:01:02  bundle[16127]: [5486ede6-1563-4d11-9b0f-1cccbfb25a0c]
Jul 26 09:01:02  bundle[16127]: [5486ede6-1563-4d11-9b0f-1cccbfb25a0c] Webpush::InvalidSubscription (host: fcm.googleapis.com, #<Net::HTTPBadRequest 400 UnauthorizedRegistration readbody=true>
Jul 26 09:01:02  bundle[16127]: body:
Jul 26 09:01:02  bundle[16127]: <HTML>
Jul 26 09:01:02  bundle[16127]: <HEAD>
Jul 26 09:01:02  bundle[16127]: <TITLE>UnauthorizedRegistration</TITLE>
Jul 26 09:01:02  bundle[16127]: </HEAD>
Jul 26 09:01:02  bundle[16127]: <BODY BGCOLOR="#FFFFFF" TEXT="#000000">
Jul 26 09:01:02  bundle[16127]: <H1>UnauthorizedRegistration</H1>
Jul 26 09:01:02  bundle[16127]: <H2>Error 400</H2>
Jul 26 09:01:02  bundle[16127]: </BODY>
```

I have both keys set in .env.production and changing them does not resolve this issue.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by isati** [comment]
I originally didn't change them, all I did was reboot the server and then started to get this error. I tried changing them to see if it would resolve the issue but I guess I shouldn't have.

**Comment by sorin-davidoi** [comment]
We anticipated this might happen so you just need to revisit the website and you should get a new subscription (and a warning in the console that the public key changed).

Did you notice any patterns (prior to changing the keys) regarding which subscriptions failed (e.g. only `fcm.googleapis.com` or also the Mozilla endpoint)?

**Comment by sorin-davidoi** [comment]
Also, I assume you did not start the development build by any chance?

**Comment by isati** [comment]
No this isn't on development build but production. Do you mean I just need to log out & back in to reset the subscription? I've tried that but the problem persists. This originally began after rebooting the server, I didn't change anything until after this problem arose

**Comment by sorin-davidoi** [comment]
Long shot, but is the time on the server accurate? Saw complaints from people and I also experience it during development (If I set my clock one minute back pushing fails).

**Comment by isati** [comment]
The time on the server is about 7 seconds faster than my local workstation, would that throw it out?

I get the following output from the developer console:

![image](https://user-images.githubusercontent.com/227061/28621280-54380682-7208-11e7-8493-5319d3abb549.png)

**Comment by sorin-davidoi** [comment]
I would use something like `ntp` just to rule it out. That means what it failed to send the welcome notification (most likely the unauthorised error).

**Comment by isati** [comment]
ntpd is actually setup and running on the server so I'm not sure if that is the problem or not.

I'm not seeing anything in the log that gives any indication to exactly why the subscriptions are unauthorised..

```
Jul 26 13:36:04 manx.social bundle[16127]: [6976af40-64ae-4120-b015-039bf402396f] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=526.76
Jul 26 13:36:07 manx.social bundle[16127]: [b19397c9-a5da-4998-8911-893efd930198] method=POST path=/api/web/push_subscriptions format=html controller=Api::Web::PushSubscriptionsController action=create status=500 er
Jul 26 13:36:07 manx.social bundle[16127]: body:
Jul 26 13:36:07 manx.social bundle[16127]: <HTML>
Jul 26 13:36:07 manx.social bundle[16127]: <HEAD>
Jul 26 13:36:07 manx.social bundle[16127]: <TITLE>UnauthorizedRegistration</TITLE>
Jul 26 13:36:07 manx.social bundle[16127]: </HEAD>
Jul 26 13:36:07 manx.social bundle[16127]: <BODY BGCOLOR="#FFFFFF" TEXT="#000000">
Jul 26 13:36:07 manx.social bundle[16127]: <H1>UnauthorizedRegistration</H1>
Jul 26 13:36:07 manx.social bundle[16127]: <H2>Error 400</H2>
Jul 26 13:36:07 manx.social bundle[16127]: </BODY>
Jul 26 13:36:07 manx.social bundle[16127]: </HTML>
Jul 26 13:36:07 manx.social bundle[16127]: ' duration=83.08 view=0.00 db=35.58
Jul 26 13:36:07 manx.social bundle[16127]: [b19397c9-a5da-4998-8911-893efd930198]
Jul 26 13:36:07 manx.social bundle[16127]: [b19397c9-a5da-4998-8911-893efd930198] Webpush::InvalidSubscription (host: fcm.googleapis.com, #<Net::HTTPBadRequest 400 UnauthorizedRegistration readbody=true>
Jul 26 13:36:07 manx.social bundle[16127]: body:
Jul 26 13:36:07 manx.social bundle[16127]: <HTML>
Jul 26 13:36:07 manx.social bundle[16127]: <HEAD>
Jul 26 13:36:07 manx.social bundle[16127]: <TITLE>UnauthorizedRegistration</TITLE>
Jul 26 13:36:07 manx.social bundle[16127]: </HEAD>
Jul 26 13:36:07 manx.social bundle[16127]: <BODY BGCOLOR="#FFFFFF" TEXT="#000000">
Jul 26 13:36:07 manx.social bundle[16127]: <H1>UnauthorizedRegistration</H1>
Jul 26 13:36:07 manx.social bundle[16127]: <H2>Error 400</H2>
Jul 26 13:36:07 manx.social bundle[16127]: </BODY>
Jul 26 13:36:07 manx.social bundle[16127]: </HTML>
Jul 26 13:36:07 manx.social bundle[16127]: ):
Jul 26 13:36:07 manx.social bundle[16127]: [b19397c9-a5da-4998-8911-893efd930198]
Jul 26 13:36:07 manx.social bundle[16127]: [b19397c9-a5da-4998-8911-893efd930198] app/models/web/push_subscription.rb:154:in `send_welcome_notification'
Jul 26 13:36:07 manx.social bundle[16127]: [b19397c9-a5da-4998-8911-893efd930198] app/controllers/api/web/push_subscriptions_controller.rb:31:in `create'
```

**Comment by sorin-davidoi** [comment]
You could try using Firefox, their push service has much better error codes.

**Comment by isati** [comment]
This is what output firefox has given me, I'm assuming this is related to the other issue I seem to be having regarding access tokens..

![image](https://user-images.githubusercontent.com/227061/28621906-6d9b7a26-720a-11e7-8a07-abf14d4c7c2a.png)

**Comment by isati** [comment]
If I navigate to `domain.com/api/web/push_subscriptions` I get the `The page you were looking for doesn't exist.` error. Is this intended behaviour? I'm still having difficulties identifying what the problem is here. I've double checked configuration files of nginx/mastodon, rebuilt gems/node_modules and everything seems to be correct based upon the Mastodon documentation.

**Comment by sorin-davidoi** [comment]
Yes, that is intended behavior, since that path is not a page, but an endpoint. Did you fix the access-token problems?

**Comment by isati** [comment]
No I haven't resolved the 401 access token errors yet, I have belief that it is somehow related to redis as after I changed appendonly from no to yes in redis.conf & restarting, Mastodon regenerated timelines and the issue was seemingly resolved for about 24 hours and then started occuring again. I'm completely baffled by this but I'm still looking into it and trying to get some more useful debugging output.

In regards to the push notifications, I'm not sure if the attached output from Firefox is useful or not. Perhaps you were indeed correct about the time sync on the server as the output here suggests the authorising server is > 24 hours into the future, however the server is only about 8 seconds out compared to my workstation.

![image](https://user-images.githubusercontent.com/227061/28672016-633d143c-72d6-11e7-9144-cf32cc7396fc.png)

**Comment by sorin-davidoi** [comment]
Don't really know how to debug this further. The gem we use has two open issues regarding this, but from what I can tell the problem is the server time - see [this comment](https://github.com/zaru/webpush/issues/25#issuecomment-314004754).

**Comment by isati** [comment]
Ok cheers, although if the problem is server time and the server time is correct then I've no clue how to resolve this. I've tried setting more localised time servers in ntp.conf and restarted the server but no changes.

**Comment by isati** [comment]
Closing this as it does now appear to be an issue with the time on the server, after some tinkering I got the times in sync and now the push subscription works again.
