### ISSUE TITLE
levels of posting privacy, and maintaining minimum confidentiality possible

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#440]
this is a lot of big words, but i used them because otherwise i couldnt figure out how to shorten: "minimum privacy possible in reply to private posts, and making sure that the people you are tooting to can see your post in the first place"

basically, we have 3 settings right now, Unlisted, Public, and Private.

at the unlisted level, you can toot to someone who doesn't follow you, and they can see, it

public is also the same, but, it shows up in searches for hashtags if a hashtag is in the toot. also this means anyone can see this toot by looking at your profile

private is only followers

privacy is important, and a way to help secure this is to encourage maximum possible security on replying-to-posts.

IDEALLY: private toots that reply to another private toot would only be visible when someone follows both parties but, that is not enforced currently. 

in the meantime, i suggest the following:

whenever you go to make a reply to a private toot, it defaults to private mode, if you both follow each other. if you DONT follow each other, it defaults to unlisted.

to further help with such things, a related issue is that you cannot tell when someone does not follow you without using the third column, but theoretically, you could run a check whenever there is a @ mention in the toot, and "if they follow you" it will not warn you when you try to reply to them with a private toot, but IF they do not follow you, warn, by changing the color of the reply background to red, maybe, etc. this solves all the issues, and can scale easily into the future.

if #422 comes into existence, the option for privacy level could dissappear for all reply toots, and it would automatically limit who could see the toots to only people who follow both.

other related posts i personally have made, #371, #412

**Comment by marrus-sh** [comment]
defaulting to private when replying to a private toot (and you are mutuals) would be amazing imo. if mutuals-only toots becomes a thing then it should default to mutuals-only instead, ofc.

as a possible alternate solution in the case that the person you are replying to does not follow you, it might be worthwhile to make private toots visible to anyone @-mentioned, regardless of whether they follow the tooter or not. this would also prevent people from mentioning someone without their knowledge, which could be seen as a privacy benefit (Facebook does this but Twitter does not)

**Comment by wchristian** [comment]
kind of an annoying problem with private-marked toots:

if i follow someone and can see their private toots, but they don't follow me back, i cannot usefully reply to these private toots they make as they can't see any private replies i make, and if i do a public toot i'd be leaking information about them

this stifles conversation quite a bit

**Comment by noiob** [comment]
Maybe allow people mentioned in private toots to see them no matter what? You wouldn't mention someone fi you didn't wanna let them see the toot anyways

**Comment by LittleEDEN** [comment]
I agree with changing Private toots to being visible to 'anyone who follows the poster and anyone atmentioned in the text of the toot'
While the main benefit of this is letting private conversations continue is probably situations like this 
![situationslikethis](https://cloud.githubusercontent.com/assets/24882138/22663362/e67946b8-ec71-11e6-84c3-f0f81e6a9e15.png) 
I have no idea what user hoodie said in this conversation, despite the evidence I was still tagged as the conversation evolved.
Private accounts default to posting Private posts, even as replies. It can oft be that you have a silly reply that doesn't necessarily need to be private and you just don't turn it off not realising they don't follow you. 
Of course, there's some times where I and I presume a lot of other users wish to reply to someone privately intentionally.
Private posts still have an extra functionality that they cannot be boosted as well, meaning if you want to /start/ a conversation with someone who you're not mutually following and it's content you don't want shared outside, a brand new private post with an atmention is something that becomes theoretically possible, and it has been a thing I've personally wanted.

**Comment by Gargron** [comment]
Mentioned people now see the toots even when they're private, UI defaults to the lowest privacy setting when replying.
