### ISSUE TITLE
auto-playing gifs, gif avatars, and hover-to-play

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#441]
this is a possibly niche issue, and not for the sake of performance, as i dont believe that even matters anymore, with such things.

as currently there are several ways to auto-play an animation, gif, small video of sorts, it doesnt matter, the issue has been mentioned that such things can actively be bad for some people, in regards to frightening them, or making it hard to focus.

as such, i propose an accessibility option in the settings to disable auto-playing media, and make it so that such things only autoplay when hovered over or clicked (or only play the first frame in all other cases)

EDIT: this can also help with short gifs that play quickly, and epilepsy. it's a serious matter to be considered

**Comment by tyrosinase** [comment]
As long as it plays nice with https://github.com/simonlindholm/toggle-gifs , which already handles the autoplay stuff in Firefox. (Because yeah, I really hate trying to read something while something is flapping and twitching off on another part of the screen, and not just on masto.)

**Comment by marrus-sh** [comment]
This will probably be made much easier if/once #431 is implemented. Handling GIFs hosted on other (GNU Social) instances is a non-trivial issue though. The easiest solution would be just hiding them with a sensitive content box, but ideally they should be replaced with an HTML `<canvas>` containing the first frame of the GIF, which is swapped out for the GIF itself onclick (or onhover). (This would likely require using `<img>` instead of `<a style="background: url(…)">` to show GIFs though, or alternatively generating a `data:image/png,` URI.)

**Comment by hoodiek** [comment]
https://gfycat.com/about i wonder if this is in any way helpful? i know someone made a plugin for GNUsocial to use this. i don't really know

**Comment by IreneKnapp** [comment]
Just adding my voice that this is a very big deal for epileptic users - it's a matter of safety.

I don't know how much time I'll have to code, but I can try to dig in and see how complicated it is.

**Comment by estln** [comment]
Boosting that this is a really important feature and I'd love to be able to have it. I can maybe look into it in the near future, but I'm not sure.

**Comment by alerque** [comment]
Any epileptic user to whom this is a full on issue of safety would be well advised to have animated GIF support turned of in their browser across the board. 

That being said I personally find the animated avatar trend so obnoxious I block accounts for no other reason that to get them away from my eyeballs. I would love to see this behind a preferences flag so I never have to see another one. In fact I'd advocate that it default to disabled to discourage their use while allowing anybody that thinks their cute or whatever to use and view them by turning on the preference.
