### ISSUE TITLE
Intent/share URLs

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#442]
A really good simple step for letting third-party apps/sites/etc share to Mastodon would be implementing an Intent URL (e.g. https://dev.twitter.com/web/intents ).

At the simplest, I can imagine just opening the /web of the mastodon instance, with a parameter that pre-fills the toot text?

**Comment by Gargron** [comment]
This isn't that easy - say there's a blog that has a "toot this" social media button. How does the button know what the clicker's home instance is?

**Comment by ineffyble** [comment]
There's some complications about how people get to the right URL, but having it so that an instance has a path/UI just for tooting, with parameters specified in query, would be a good first step. I'm working on a browser extension for "toot this" buttons, which has settings for the user and instances

**Comment by pixocode** [comment]
Maybe at first a way to share in a defined instance? (ex: https://instance/share?title=Hi)

**Comment by ineffyble** [comment]
That would be a good first step. A "toot this" button could always ask for the clicker's full handle including instance.

**Comment by fdavidcl** [comment]
Just as an idea: Diaspora has a "bookmarklet" feature (at https://pod/bookmarklet?url=example.org) that works as an intent URL and some external services let the user choose their instance (e.g. [sharetodiaspora](https://github.com/sharetodiaspora/sharetodiaspora) -- [example share link](http://sharetodiaspora.github.io/?url=mastodon.social&title=Mastodon)). If Mastodon implemented intent URLs it would be really easy to make a 3rd party service of this kind.

**Comment by mxmehl** [comment]
Please make this compatible to GNU Social which is using links like this: https://quitter.no/notice/new?status_textarea=This+is+where+the+text+belongs

Otherwise, already existing GNU Social share buttons (like on [fsfe.org](https://fsfe.org/contribute/contribute.html)) won't work and we would have to create extra Mastodon buttons - which would segregate the communities.

**Comment by rtvb** [comment]
The current uri for a new status is /web/statuses/new so a good solution could be to implement /web/statuses/new?status_textarea=Test+message

**Comment by mxmehl** [comment]
> The current uri for a new status is /web/statuses/new so a good solution could be to implement /web/statuses/new?status_textarea=Test+message

This again would make it necessary for websites to have separate buttons for GNU Social and Mastodon. IMHO this would weaken both networks in their public representation.

**Comment by jeroenpraat** [comment]
Is it safe to assume that bookmarklets are not (yet) possible?

**Comment by jeroenpraat** [comment]
You also have this on Firefox. The Firefox Social API: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API

It is implemented in Hubzilla as a plugin. You find the code (PHP, so it's for inspiration) here: https://github.com/redmatrix/hubzilla-addons/blob/master/firefox/firefox.php

**Comment by yookoala** [comment]
(copying my post from #1978)

Really really low priority. But I think it is a nice feature to have.

Social media sites like Twitter, Facebook provides websites with Social Plugins. Website owners can include a piece of JS / HTML embed to display a "Share to XXX" button. Visitors can share the website's like and perhaps part of the content to that social media site.

Examples,

- Twitter: [Tweet Button](https://dev.twitter.com/web/tweet-button)
- Facebook: [Share / Like Button](https://developers.facebook.com/docs/plugins/#like-share-send)

Propose to:

1. Write and host a "Share to Mastodon" script.
2. By embeding, website owner can display the "Share to Mastodon" or "Toot it" button on the site.
3. Visitor, when first use on the button in any site,
   1. Visitor will get a dialog to input the instance URL to share.
   2. Then a dialog to actually edit the post content for sharing.
   3. The dialog should have a "Toot" button to actually toot on the site.
   4. Should the visitor not login to the site, it should direct the user to additional login process.
4. The instance specified will be stored in cookie (of the script's CDN domain).
5. Later on, if a visitor use the button on any site with again,
   1. Visitor will get a dialog to actually edit the post content for sharing.
   2. This dialog also show that it will Toot to "Preferred instance", which the script memorized with cookie earlier. Visitor should have an option to specify another instance.
   3. Other behavior should be the same as the first use.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
should we consolidate this into https://github.com/tootsuite/mastodon/issues/2291? It provides a much more feasible technical implementation of this idea, in my opinion.

**Comment by ggtea** [comment]
FYI:
* Pawoo already implemented share intent and pixiv(owner of Pawoo) uses it as share button.  https://pawoo.net/intent/statuses/new?text=aaa
* https://mastoshare.net/  is 3rd party implementation of share button. It requires auth for lacking share intent feature. sad.

**Comment by akihikodaki** [comment]
The intent of Pawoo looks promising, but #2291 requires an intent to be usable for _any_ instance. For example, such a share button should be used with both of mastodon.social and pawoo.net. I have written two specifications and made a prototype for the purpose.

Specifications:
Intent Class In Activity Streams 2.0 Vocabulary
https://akihikodaki.github.io/activity-vocabulary-intent
URL Scheme for Activity Streams 2.0 (use with `registerProtocolHandler`)
https://akihikodaki.github.io/activity-vocabulary-intent/scheme

Prototype: https://github.com/tootsuite/mastodon/issues/2291#issuecomment-313302597

**Comment by Oreolek** [comment]
so how to do share buttons now?

**Comment by NickKaramoff** [comment]
Hi everyone; sorry to revive this old issue, but I figured you might find these related projects of mine useful ✨ 

- [📯 shareon](https://shareon.js.org/) is a share button library, which includes a cross-instance share button for Mastodon
- [🐘 toot](https://toot.karamoff.dev/) is a cross-instance share page for Mastodon, which shareon uses under the hood

This, obviously, doesn't work with Pleroma, GNU Social and possibly with other Fediverse platforms :/

**Comment by docum3nt** [comment]
Did an /intent/ URI ever get added? It's suddenly become more important with the migration going on. It just needs to be a URI, like the birdworld one, and it would create a draft toot in the user's executing Mastodon app or browser tab (or open a new tab onto a Mastodon server that could be an optional field in the URI.

**Comment by ineffyble** [comment]
@docum3nt Mastodon instances have a share intent URL e.g. https://mastodon.social/share?text= , but the site offering the share option needs to prompt/ask for the instance/handle first so it knows where to send them.

**Comment by docum3nt** [comment]
Thanks very much. Instance name is no problem as it's known beforehand.

**Comment by MastodonContentMover** [comment]
> @docum3nt Mastodon instances have a share intent URL e.g. https://mastodon.social/share?text=Hello%20there , but the site offering the share option needs to prompt/ask for the instance/handle first so it knows where to send them.

Thank you for sharing this. Do you know if any fields other than **`text`** are supported? I'd like to try something that adds a content warning but **`/share?text=Hello&spoiler_text=testing`** doesn't seem to work. I checked the API does and couldn't see any documentation for this feature - perhaps there's some there somewhere and I missed it?
