### ISSUE TITLE
Confusing wording on /settings/follower_domains (1.5.0rc1)

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#4428]
On /settings/follower_domains (1.5.0rc1) there is a phrase in the introduction:

>"Please mind that true privacy can only be achieved with end-to-end encryption."

"Please mind that [thing to be aware of]" is a colloquialism, so it might be better to change it to "Please be aware that" or "Please bear in mind that"?

Also, this sentence in isolation is unclear. If you're familiar with how Mastodon and encryption work, it's obvious - but if you're an average non-techy user this might not be a helpful sentence. Is Mastodon showing off that it uses end-to-end encryption and is therefore truly private? Or is it implying that Mastodon is not private? It's really quite ambiguous if you don't know the things that it assumes you know.

So maybe it could be changed to:

>"Please bear in mind that true privacy can only be achieved with end-to-end encryption, which Mastodon does not use."

* * * *

- [Y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Page removed
