### ISSUE TITLE
Navigating to https://mastodon.social/web/statuses/new shows a compose box on both sidebars

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#444]
![screencapture-mastodon-social-web-statuses-new-1483863252551](https://cloud.githubusercontent.com/assets/834880/21748339/b46e1eca-d5d6-11e6-9d2d-cb976d263076.png)

**Comment by Gargron** [comment]
That's not a bug that's navigation - every column is a component that can be mounted through a route, that's how the single-column mobile view works.
