### ISSUE TITLE
Mastodon not linkifying links it should linkify

### ISSUE THREAD

**Issue by taoeffect** [tootsuite/mastodon#4446]
Tried to toot this link: https://www.amazon.com/gp/aw/d/159315481X/

Mastodon refused to linkify it: https://mastodon.social/@taoeffect/14077128

@Gargron asked me to open this issue.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by clworld** [comment]
Testing from WebUI, it's linkifyed. https://mastodon.social/@Clworld/14105944
Is it caused by Amaroq?

**Comment by taoeffect** [comment]
Thanks @clworld, closing in favor of: https://github.com/ReticentJohn/Amaroq/issues/45
