### ISSUE TITLE
Impossible to erase images in config

### ISSUE THREAD

**Issue by somenxavier** [tootsuite/mastodon#4458]
It is impossible to erase images in avatar and header image in profile page. It applies at least to version 1.4.7

**Comment by nightpool** [comment]
Can someone confirm if this applies to 1.5?

**Comment by Cassolotl** [comment]
It's still the case in 2.2.0.

**Comment by Cassolotl** [comment]
A year and a half later, it's still a thing in 3.0.1.

**Comment by sternenseemann** [comment]
Fixed as of <https://github.com/tootsuite/mastodon/commit/679980f77c0e869d2eebbf64c18faabd8a523a13>
