### ISSUE TITLE
Notices Flash For An Instant, Then Disappear

### ISSUE THREAD

**Issue by lnxwalt** [tootsuite/mastodon#4461]
[Issue text goes here].
Only the Notifications column is unaffected. In all other columns, notices are visible for an instant after they first arrive, then are invisible.

I'm using https://mastodon.social/ ... Chromium 57 on Mageia 5 GNU+Linux. This started a day or two ago (currently 2017-07-31 02:35 UTC). Closing and reopening the browser does not change this. Thread discussion is here: https://mastodon.social/users/Gargron/updates/3932912 (turns out not to be the same as Wonderfall's issue, but we continued to discuss there). 

![mastosoc_blank_col1](https://user-images.githubusercontent.com/558836/28760930-88690d76-759a-11e7-9288-fa2ab6223194.png)
![mastosoc_blank_col2](https://user-images.githubusercontent.com/558836/28760932-8f4608d8-759a-11e7-8281-944653ad5243.png)
![mastosoc_blank_col3](https://user-images.githubusercontent.com/558836/28760940-98c473ea-759a-11e7-8839-16430efa6e56.png)
![mastosoc_blank_col5](https://user-images.githubusercontent.com/558836/28760948-a72bedaa-759a-11e7-9ef8-f82dd570cdec.png)
![chromium_about_2017-07-29](https://user-images.githubusercontent.com/558836/28760980-df2695e8-759a-11e7-9b7c-9d6d6caa4f2c.png)

* * * *
- [X] I reviewed the [guidelines for contributing](https://github.com/tootsuite/mastodon/blob/master/CONTRIBUTING.md) before submitting this issue.
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by lnxwalt** [comment]
Unchecking 'Opacity: 0' in the developer tools for each notice reveals the HTML for that notice.

**Comment by pafleming** [comment]
Experiencing the same/similar issue. Across Mastodon instances.
I'm getting only one column across the screen. Only one column at a time.

**Comment by sorin-davidoi** [comment]
@ykzts Can this be related to #4398? Cannot think of any other recent changes to this logic.

**Comment by ykzts** [comment]
@sorin-davidoi This commit contains only correspondence for IE and MS Edge. (https://github.com/WICG/IntersectionObserver/compare/5a01069...56ad58f).  I wonder.

**Comment by nightpool** [comment]
seems to also have broken mastodon on Chromium 56.0.2924.76, running on LinuxMint 18.1 (64-bit)

https://niu.moe/@isaacdls/2184786

**Comment by sorin-davidoi** [comment]
Are we sure this is the thing that broke it? Did not have time to investigate yet.

**Comment by nightpool** [comment]
Seeing as it's the exact same symptom happening on 1.5.0rc2, I think it's pretty safe to conclude that it's the same underlying issue as this ticket.

I don't know if #4398 is related or not, but it seems likely.

**Comment by ykzts** [comment]
@nightpool `intersection-observer` will not load in Chromium (and Chrome). #4398 does not matter.

**Comment by algernon** [comment]
I recently upgraded my instance from 1.4.7 to 1.5.0rc2, then to rc3, and viewing it from Mstdn (an Electron app that runs with Chrome 56.0.2924.87) produces the results described above: all toots have an opacity of 0, and changing those to 1 reveals the HTML of them.

The same instance looks fine with Chrome 59.0.3071.115, and with 1.4.7, there were no issues with an older Chrome, either.

**Comment by nightpool** [comment]
@ykzts please don't say that something "does not matter" when you haven't actually confirmed that it doesn't, in fact, not matter—it feels dismissive and like you're not interested in the problems users are actually having.

**Comment by ykzts** [comment]
@nightpool Yes of course. There was a shortage in my check.
