### ISSUE TITLE
I am afraid of required  authentication using /api/v1/statuses and /api/v1/timelines/public.

### ISSUE THREAD

**Issue by rbtnn** [tootsuite/mastodon#4466]
I am making a repositry to pick up toots between since_id and max_id without authentication. I am afraid of required  authentication using /api/v1/statuses and /api/v1/timelines/public.
How do you think about the authentication of those API?

https://rbtnn.github.io/mstdn-picker/

**Comment by nightpool** [comment]
Sorry, can you clarify what you mean by "I am afraid of"? I'm not sure how to parse this ticket—is is a feature request? a bug report?

**Comment by rbtnn** [comment]
This is not  a feature request and a bug report. I just want to know about  required authentication using /api/v1/statuses and /api/v1/timelines/public.

@nightpool Thanks you. I'll close this.
