### ISSUE TITLE
Landmark navigation for screen readers

### ISSUE THREAD

**Issue by LJWatson** [tootsuite/mastodon#4485]
shortcuts provided by the screen readers themselves.

**Comment by sorin-davidoi** [comment]
Can you give more details? What does this involve? Skip links?

**Comment by LJWatson** [comment]
Not skip links, no. The solution I outlined in my [initial comment](https://github.com/tootsuite/mastodon/issues/4485#issue-247194021) is all you need to do.

Change the ```<div>``` container for the first column to:
`aria```<div class="drawer" role="section" aria-label="Posting">...</div>```

Change the ```<div>``` container for the Home column to:
```<div class="drawer" role="section" aria-label="Home">...</div>```

Change the ```<div>``` container for the Notifications column to:
```<div class="drawer" role="section" aria-label="Notifications">...</div>```

Change the ```<div>``` container for the Timeline column to:
```<div class="drawer" role="section" aria-label="Timeline">...</div>```

**Comment by sorin-davidoi** [comment]
Cool! Can you open a pull request with these changes?
