### ISSUE TITLE
Links displaying inconsistently in feeds

### ISSUE THREAD

**Issue by Komic** [tootsuite/mastodon#4490]
![Screenshot](https://my.mixtape.moe/ijmhuq.png)

Should be easily reproducible, enter some text, line break, enter a link such as https://www.youtube.com/watch?v=WTWdP5DMdsM, try the same with a link such as https://twitter.com/radiomaru/status/891560879891693568.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
to be clear, the inconsistency here is that it sometimes overflows onto a second line, right?

**Comment by Komic** [comment]
@nightpool yup!

**Comment by nightpool** [comment]
sounds good! this is annoying, I agree.

**Comment by ykzts** [comment]
![](https://user-images.githubusercontent.com/12539/28853915-b70a4e12-776e-11e7-8f7a-191551e8cb79.png)

like this?

**Comment by Komic** [comment]
@ykzts yup, but try with https://www.youtube.com/watch?v=WTWdP5DMdsM now?
You can reproduce this by just posting the link, too:

![Screenshot](https://my.mixtape.moe/qpctcf.png)

**Comment by ykzts** [comment]
Could you tell me your web browser?

**Comment by Gargron** [comment]
This is from the visual shortening of the links using CSS. Originally it was working perfectly (for me in Firefox), but one user complained about their browser (Safari) and changed the CSS, so now it linebreaks like that sometimes.

adda642c63d01e362e0629ee956e9b3af9748644 (#520, #521)

**Comment by ykzts** [comment]
@Komic Would you check #4655 ?

**Comment by ykzts** [comment]
I think that fixed at #4655 .

**Comment by Komic** [comment]
Yup, just upgraded to master, it's gone. Thanks!
