### ISSUE TITLE
Counting message length

### ISSUE THREAD

**Issue by kensanata** [tootsuite/mastodon#4498]
I have some technical questions regarding #4427.

```javascript
export function countableText(inputText) {
  return inputText
    .replace(/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/g, urlPlaceholder)
    .replace(/(?:^|[^\/\w])@(([a-z0-9_]+)@[a-z0-9\.\-]+)/ig, '@$2');
};
```

1. Do we really want to hard-code the `www` subdomain? I have an account on `mastodon.weaponvsac.space`, for example. This domain would not be considered. What about domains with more levels? I'd like to use a better regular expression.
2. On the original issue, somebody already commented that the upper limit of 6 for the top level domain is not good and mentioned `mastodon.network` (7).
4. The `\+` needs no backslash inside a character class.
5. The `//` is one too many inside a character class.
6. When looking at mentions, we match a whitespace character in the unnumbered group this extra character gets lost in the replacement, so `␣@a@b.c` is replaced by `a` instead of by `␣a`.
7. The regular expression counts matches this: `@a@b.c-` and replaces is with `a` but the trailing minus character should not be counted. In fact, the MENTION_RE uses `/(?:^|[^\/[:word:]])@(([a-z0-9_]+)(?:@[a-z0-9\.\-]+[a-z0-9]+)?)/i` to prevent `[.-]` at the end of the match. Alternatively, we could change the regular expression such that it disallows the minus at the beginning and at the end of each label.
8. This reminds me that those backslashes for `\.\-` in MENTION_RE are also unnecessary.

I'd be happy to help writing a better regular expression if we all agree that these are issues we care about. :)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Another regular expression is used now.

https://github.com/tootsuite/mastodon/blob/v1.5.0/app/javascript/mastodon/features/compose/util/counter.js#L5

**Comment by kensanata** [comment]
Ah, cool! I missed that.
