### ISSUE TITLE
/auth/password showing very confusing "is invalid" error message

### ISSUE THREAD

**Issue by Southclaws** [tootsuite/mastodon#4502]
Did a password reset and the `/auth/password` endpoint returned this extremely unhelpful "error message".

Instance: https://mastodon.club (v1.4.1)

![image](https://user-images.githubusercontent.com/1636971/28890265-727bf7f0-77be-11e7-9bb4-3e4e68bd0f85.png)

Not really sure how to repro this one, sorry! It happened once, I tried to force a repro but it worked fine the second time around (about 10 minutes later).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
It seems like this if a mistake (or expired) reset password token is used.

### steps to reproduce

1. logout Mastodon
2. open `/auth/password/edit?reset_password_token=1`
3.  click "New password"

**Comment by ykzts** [comment]
resolved with #4506
