### ISSUE TITLE
Tiny scroll area when viewing profile on mobile

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#452]
When you view a user on a phone, you get a small window that shows a small amount of toots (two for me). It is possible to scroll down, but you have to swipe and scroll within that small window, which isn't super intuitive and limits how much you can see.

I'd suggest either making it so entire window is scrollable, and the profile can be scrolled off the page (possibly turning into a small header at top).

**Comment by Gargron** [comment]
Fixed in f21e7d6ac06556671c2663ce2879442c60230b32!
