### ISSUE TITLE
Can not see avatars since v1.5.0

### ISSUE THREAD

**Issue by Bschalck** [tootsuite/mastodon#4520]
Hello,

I use mastodon on my own instance ( https://social.devloprog.org) .
As you can see here https://social.devloprog.org/about , the avatars don't load.
I use Apache 2 configuration.
In the apache log, i can see : 

xxxxxxxx - - [04/Aug/2017:15:58:06 +0200] "GET /system/accounts/avatars/000/000/002/original/67a58864390ada84.jpeg?1491768052 HTTP/1.1" 404 800 "https://social.devloprog.org/web/getting-started" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"

the file 67a58864390ada84.jpeg does not exist on my server.

When should it be download and why does it not ? 

Thanks

**Comment by ykzts** [comment]
```console
$ ./bin/rails mastodon:media:redownload_avatars
```

Run the above command.

**Comment by Bschalck** [comment]
Well thanks for the answer .
Do I have to define some varaibles before ? 
The command failed ( running with mastodon user : )
`./bin/rails mastodon:media:redownload_avatars
NameError :  uninitialized constant Annotate`

**Comment by ykzts** [comment]
Set the value of the environment variable `RAILS_ENV` to `production`.

like `RAILS_ENV=production ./bin/rails mastodon:media:redownload_avatars`.

**Comment by Bschalck** [comment]
Thanks a lot \o/
