### ISSUE TITLE
Contact name link not functional

### ISSUE THREAD

**Issue by choosingchange** [tootsuite/mastodon#4535]
In Contact name... Phil
In Business email... Philip Johnson

Previously if I put the email address in "Business Email" the email address shows which we do not want because it is vulnerable. 

When people click on that contact link the email program is initiated and thename "Philip Johnson" is populated in the email "To" but of course no email address. 

So looks right and the Avatar appears but link not really functional. 

Not sure how to fix that. 

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
If you do not want to publish your email address, you can leave "Business email" blank.

**Comment by choosingchange** [comment]
I don't want my email visible.   
  
  
  
  
  

  
  
  
  
  
>

**Comment by ykzts** [comment]
![](https://user-images.githubusercontent.com/12539/29023158-76830180-7ba7-11e7-808a-aea64e4e5f94.png)

"Business email" blank.

**Comment by choosingchange** [comment]
Hi Yagamishi
  

  
I understand that leaving it blank. But I do want people to be able to send an enquiry.   
  

  
If I leave "Contact" blank the result on the page is "n/a".   
  

  
I'm not complaining by the way...    but I thought the code makers may be able to make this a field that hides the address.   
  

  
I have worked around it by providing a link to a contact form on my own site.   
  

  
It's a fudge and inelegant but at least reasonably functional.   
  

  
Thanks for your help.   
  

  
Regards   
  

  
Phil   
  
  
  
  
 Philip Johnson choosingchange Counselling Sydney CBD Suite 103 /147 King Street Sydney NSW 2000 1300 667 996 0448 281 251  

  
  
  
  
  
>

**Comment by choosingchange** [comment]
I'm curious to know why this issue is closed when tthere has been no fix?

**Comment by ykzts** [comment]
Oh, I'm sorry. I thought your problem was solved. What do you want?

**Comment by choosingchange** [comment]
No. The problem is not solved. I  have made a clever work-around. If you see my instance (maston.pervixi.com) and my Contact you will experience what I am talking about. Click on contact. Am I the only person with this problem?

**Comment by ykzts** [comment]
I think that it is not Mastodon's job to provide an email form. You can add a link to the mail form to "Custom extended information".

**Comment by ykzts** [comment]
FYI: `maston.pervixi.com` is https://masto.pervixi.com/about/more ?

**Comment by choosingchange** [comment]
Thanks again for your help. I'm not asking Mastodon to supply an email form. I'm suggesting Mastodon fix the link in Business email so the email address is not showing on the webpage. That makes the email vulnerable. Currently "Business email" reveals the email. I suggest it could be a hidden field.

**Comment by choosingchange** [comment]
Yes to that address. Click on Contact. That opens current email program. I have put details on there so others can paste into address bar and go to my separate contact form on www.pervixi.com.  This is not an elegant fix. That is the work around.

**Comment by nullkal** [comment]
Even if we modify mastodon so that the contact email address is not shown in /about/more, visitors can get it as long as there is a link to open the email program using inspector.

**Comment by Gargron** [comment]
An e-mail address does not have to be visible to the user to be harverstable by bots, if it's still in the HTML source. So there'd be no point leaving the link as-is but changing the text of the link, it would only make it harder for real people to see. You can obfuscate the e-mail with JavaScript (but harming visitors with disabled JavaScript), but I do not think it's worth doing; spam filters have gotten really good nowadays. Plus you can make something like webmaster@yourdomain.com forward to your real address if you want to hide it.
