### ISSUE TITLE
Please show messages or buttons on remote follow dialog even if already followed

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#4536]
On the master (#4523), remote follow dialog is like below when I try to follow whom I'm already following.

![image](https://user-images.githubusercontent.com/705555/29002768-e8b58a5c-7ae4-11e7-8fb9-450ea28809f8.png)

and I thought, "oh, there are neither buttons nor messages. Is this a bug? or am I wrong?".

How about having message like "You're already following this user", or Go to Web / Return to the profile buttons like success page?

**Comment by DavidLibeau** [comment]
+1
I just automatically clicked the log off button… but wanted to follow the account (that I was already following).
