### ISSUE TITLE
Toots hide themselves in QtWebEngine-based browsers since v1.5.0

### ISSUE THREAD

**Issue by Feufochmar** [tootsuite/mastodon#4537]
I'm using QupZilla 2.1.2 with Qt 5.9.1 on ArchLinux, and on instances running Mastodon 1.5.0, the toots automatically hide themselves in the home, local and public timelines. The columns seems to be empty while they are not, as the scroll bars are present. I can make some hidden toots appear by loading older toots on the timeline, however, new incoming toots are still hiden.
The notification timeline is not affcted by the problem, nor the timeline of a specific toot. I don't have this problem with an instance running Mastodon 1.4.7. I've seen someone complaining for another QtWebEngine-based browser (qutebrowser I think) when one of the instances I use was updated to 1.5.0rc1 (I was using a phone app when I saw the complaining toot).

According to the about page of QupZilla, Qt 5.9.1 corresponds to Chromium 56:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QupZilla/2.1.2 Chrome/56.0.2924.122 Safari/537.36

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Is it the same problem as #4461 ? This problem has already been fixed. Is your instance v1.5.0 (not rc)?

**Comment by Feufochmar** [comment]
The two instances where I have the problem are still on 1.5.0rc2. The problem does not seems to appear on mastodon.social (at least from the global timeline shown on the about page, as the problem appears there too on the other instances).
I'll see with the admins of those instances.

**Comment by Feufochmar** [comment]
One of the instances has been updated and the problem has disappeared. Seems to be the same issue as #4461, so I'm closing this one.
