### ISSUE TITLE
Favourites column does not update automatically and is inconvenient to update manually

### ISSUE THREAD

**Issue by ekiru** [tootsuite/mastodon#4539]
Although it's now possible to pin the favourites column, it doesn't seem to update automatically when one favourites new things (as tested on mastodon.social). In addition there doesn't seem to be a convenient way to manually tell it to update. It will update if the one navigates to their favourites from the getting started tab but not otherwise.

I pinned the column on one of my accounts hoping it would stay up to date when I favourited things, and pinning it seems much less useful without that updating. I'd like it to, ideally, automatically update when I favourite new things, at least from the same client, or to be able to click a button somewhere in the column header to tell it to check for new favourites.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by MightyPork** [comment]
I've implemented this in #4562, so the ticket can probably be closed
