### ISSUE TITLE
Account export/data liberation

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#454]
Users should be able to download a copy of their user data, including:
- All their toots (ideally in a CSV format, probably)
- Toot media (?)
- Following list
- Followers list

Similar to #177 but simpler and with a different end-goal in mind.

**Comment by iztoogood** [comment]
maybe an export format in xml for toots
and zip/rar/7z format for medias ...???

**Comment by Gargron** [comment]
Duplicate of #201
