### ISSUE TITLE
Sidekiq stopped processing jobs

### ISSUE THREAD

**Issue by xvilo** [tootsuite/mastodon#4542]
For some reason, sidekiq stopped processing jobs, after I did an update to 1.5.0, even after 1.5.1 it still doesn't work. We're not federating anymore :( 

What could be the cause of this?

<img width="1217" alt="screen shot 2017-08-07 at 8 56 12 am" src="https://user-images.githubusercontent.com/390769/29015498-8457e0fe-7b4e-11e7-9eb2-602b6aff9f05.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Please take screenshots on `https://#{your_instance_host}/sidekiq/busy`.

**Comment by xvilo** [comment]
@ykzts here y'a go: 
<img width="1680" alt="screen shot 2017-08-07 at 5 59 58 pm" src="https://user-images.githubusercontent.com/390769/29034959-45a03a90-7b9a-11e7-8c41-e405055703f6.png">

**Comment by Gargron** [comment]
Make sure some kinda sidekiq process is running.

**Comment by PeterCxy** [comment]
I upgraded to Mastodon 3.2.1 and this happened again. Sidekiq will run for some time and suddenly stop processing any pending job. Is there anything I could do to fix this?

**Comment by nightpool** [comment]
@PeterCxy this issue is from 8 months ago and is completely unrelated. You may be looking for #6734, if you're using docker/alpine linux. If you're not using alpine linux or you haven't upgraded your ruby version, then you should open a separate ticket, and provide the logs from your sidekiq process
