### ISSUE TITLE
emojione picker blocks render

### ISSUE THREAD

**Issue by nightpool** [tootsuite/mastodon#4551]
loading `https://cybre.space/web/timelimes/home` on simulated 3g:

![image](https://user-images.githubusercontent.com/233815/29050397-b0789a4c-7ba9-11e7-9721-6b92181d812d.png)

seems to be a regression from #4202/#4253, so tagging @sorin-davidoi in case he has any ideas. That last one says the size of emojione picker is supposed to be around 64KB, but i'm seeing 132kb, almost twice that.

Either way, it would be great if this could load *after* render, and emoji could fill in in the same way avatars and pictures currently do.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment]
It doesn't block render - we load it with `rel="preload"` so that it is already fetched when we need it -https://github.com/tootsuite/mastodon/blob/c1f201c49a007e5c0740c00651e549a7b0416b05/app/views/layouts/application.html.haml#L30.

**Comment by sorin-davidoi** [comment]
The same is true for all the other requests that have a gray bar at the beginning.

**Comment by ykzts** [comment]
I think that there is no rel attribute in the script element ([4.12.1 The script element - Content attributes](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element:concept-element-attributes)).

I think that it is better to use the async attribute.

**Comment by sorin-davidoi** [comment]
Ah, they should be `link` tags, not `script`... https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by sorin-davidoi** [comment]
This is a low-hanging fruit that would bring major performance improvements (especially on mobile). Maybe @unarist or @ykzts can take a look, would be nice for this to land in 1.6.
