### ISSUE TITLE
Add a way to be unmentioned automatically from a thread

### ISSUE THREAD

**Issue by Deuchnord** [tootsuite/mastodon#4555]
Sorry if this has already been asked, could not find in opened/closed issues.

It would be nice to have a way to be automatically removed from a thread where we don't want to be mentioned anymore (for instance because we don't participate anymore and the conversation is spamming the notifications).
I'm asking this, because sometimes, when I ask to be unmentioned, I'm accidentally kept in the conversation or my message is not seen because of the flood of toots in the thread.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Would you solve your problem at #3017?

**Comment by Deuchnord** [comment]
You're right, didn't see this option, sorry for this ^^'
