### ISSUE TITLE
Contrast of the new /about/more

### ISSUE THREAD

**Issue by ProgVal** [tootsuite/mastodon#4556]
With the 1.5 release, the /about/more page has been redesigned.

The text used to be a very light green (rgb(155, 174, 200)), and has been replaced by a much darker green (rgb(96, 105, 132))

This makes the text in the top part of the page (short description) harder to read, even for me despite my having no colour vision deficiency

This may be related to #4554, but I do not know how that PR changes the style.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
I think # 4554 is irrelevant. I also feel that the contrast of the letters is a low.

**Comment by lynlynlynx** [comment]
I'm testing increasing contrast in my instance.
Please check [about page](https://mstdn.sanin.link/about) and [about/more page](https://mstdn.sanin.link/about/more) .
Is it easier to read description than other instances?
If there are letters hard to read, please tell me 😄 

----
For developers.
I'm working on adjusting styles in landing pages better, but it takes a little more time, because about.scss becomes complicated after new landing page is launched 😅

**Comment by ProgVal** [comment]
@lynlynlynx Yes, that's better

**Comment by averageunicorn** [comment]
It's not only the top part that is hard to read. The part below the user counter is basically grey on slightly darker grey.

I don't usually have trouble with this kind of thing, but this contrast is too low even for me. And the /about/more is not something that people should be skipping.

So I suggest increasing it by a lot – not only enough to be readable for people who don't usually have issues with that. I don't know enough about this topic to suggest something specific, but for a start, [here are some guidelines on contrast ratio](https://www.w3.org/TR/WCAG20/#visual-audio-contrast).

This is related to general theme accessibility issues #2280 and #2028.

**Comment by lynlynlynx** [comment]
Thank you for your information about WCAG 2.0 guideline.
I updated pull request #4567 as increasing contrast in ALL elements in landing pages.

Many low-contrast texts still exist in mastodon UI.
I think we need
- Lighter (darker in activity-stream) $ui-* colors , especially $ui-base-lighter-color (need lighten over 42% from $ui-base-color)
- Light (high contrast) theme for logged-in pages : theme engine
