### ISSUE TITLE
Mastodon Single User App/Installation/Wizard

### ISSUE THREAD

**Issue by davidpgil** [tootsuite/mastodon#4576]
Hello. I have an idea that I believe would make Mastodon catch on even more than it already has. Possibly even reach mainstream, non-techie people.

I believe lots of the concerns people may have with hosting a Mastodon instance could be solved by just allowing individuals to host a Mastodon Instance as easily as one would host a Bittorrent node. The idea would be that the user installs and boots up the app, then while the app is on, your are able to interact with the rest of Federated Mastodon.

Optionally, if you'd like to host Mastodon via your own domain, there would be some wizard to help you do that. I believe this could be a really great way to make Mastodon more available to the masses, and this would eliminate the centralization that occurs when users decide to join someone elses instance.

Does this makes sense or am I missing something?

**Comment by ykzts** [comment]
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/tootsuite/mastodon/tree/v1.5.1)

With Heroku's deploy button you can easily install Mastodon. Is not that enough?

**Comment by davidpgil** [comment]
I don't know what that is. Does it do what I am asking?

**Comment by ykzts** [comment]
You can deploy Mastodon instances to Heroku simply by filling in the settings fields. Are you seeking more than that?

**Comment by davidpgil** [comment]
I had no idea that existed. Is it free? I thought we needed to follow the documentation. Do you know of a tutorial for installing Mastodon with Heroku?

**Comment by ykzts** [comment]
Do not think that Mastodon instance operation can be done for free. Maintaining the server is time-consuming and costly.

A manual for setting up a Mastodon instance with Heroku is in https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Heroku-guide.md

**Comment by davidpgil** [comment]
My idea is to run Mastodon from my Server Desktop in an instance with only me in it. I was asking if Heroku is free. Of course I know that I need to buy a domain name, etc. Thanks for the link to the Heroku Guide.

**Comment by nightpool** [comment]
Mastodon is federated, not decentralized. We believe that small communities of individual users work better for most people then trying to force everybody to be a sysadmin. Mastodon is very explicitly *not* meant to be run on a local desktop, or a laptop, or anything like that. At this point it's pretty difficult for a non-admin to run, but that's getting easier with a couple of PaaS offerings (heroku) and people who are working on automated mastodon deployment.

However, maintaining a server will always be time-consuming and costly, which is why the mastodon protocol is built around federation, **not** decentralization. It's not comparable to something like bitbucket, it's designed more like email. Some people host their own email servers, and that's fine. But it's not the way most people use email, nor should it be given the significant security risk of rolling your own.

**Comment by davidpgil** [comment]
On joinmastodon.org the text near the tope states:

"With thousands of interconnected communities to choose from, and the tools to make your own, Mastodon is the world’s largest free, open-source, **decentralized** microblogging network."

I think what I am asking does not require people to be system admins, especially in a single-user environment.

**Comment by nightpool** [comment]
decentralized is used there—in a non-technical sense—because it's more familiar to normal users. From a technical standpoint, all of the protocols used by mastodon are built around the idea of federation.

**Comment by davidpgil** [comment]
Why can't single users **federate** with eachother?

**Comment by nightpool** [comment]
They can, absolutely. It's just not the recommended way of using Mastodon. The heroku install, or paying someone else to manage your server for you (which is basically what heroku is) is probably about as easy as it's going to get.

**Comment by davidpgil** [comment]
I do realize that Mastodon is not originally intended to be used as a single user federated app. Howver, I am requesting that this be a feature that moves towards recommendation. My reasons are stated at the top of this topic. I think they are valid requests. I don't understand why this topic is closed to discussion. I wish @Gargron had some input on this idea, because I feel it would make Mastodon more accessible to non-technical people down the road.

**Comment by davidpgil** [comment]
Why is this issue closed?
