### ISSUE TITLE
Mistyped invalid email without domain name when registering, but was still accepted

### ISSUE THREAD

**Issue by Zylann** [tootsuite/mastodon#4584]
I tried to register to an instance by entering my email, but I noticed that I forgot to type the domain name at the end of it (like `john.doe@gmail` without `.com` at the end).
Still, the email was considered valid, and now I can't validate it (as this email won't ever exist), and can't register again with the chosen username. I contacted the admin, but thought I would write this oddity here in case it's a bug, because I thought Mastodon would have been able to detect it.

**Comment by Zylann** [comment]
Argh I found an existing issue like mine... apparently emails can have no tld on private networks... https://github.com/tootsuite/mastodon/issues/1286
I'll have to wait for the admin to notice my message then...

**Comment by nightpool** [comment]
Most instances clean up unconfirmed users every day, I think? Can't check
cause I'm on my phone. I would try again tomorrow if you don't see a reply.

**Comment by Zylann** [comment]
I tried 24 hours after I registered, but my account is still showing and the instance continues to deny my registration.

**Comment by nightpool** [comment]
I was wrong, it's every 2 days. Sorry, couldn't recall exactly w/o the code in front of me

**Comment by Zylann** [comment]
It's been 48 hours now, and it looks like my account is still there...
