### ISSUE TITLE
Haven't received a password reset email. (mastodon.rocks instance)

### ISSUE THREAD

**Issue by Shickmo** [tootsuite/mastodon#4596]
I supplied my email after following the password reset link and I have yet to receive the email. It has been hours at this point so I am doubtful it will come at all. I also confirmed that the email isn't hanging out in my spam folder and I have tried to have it set more than once at this point.

My profile page is located at https://mastodon.rocks/@shickmo in case that would be needed for anything.

**Comment by ThomasLeister** [comment]
Hi @Shickmo ,

this is most probably a specific problem if the mastodon.rocks instance and not a general issue of the Mastodon software. Please contact your server's administrator and report the issue to him/her :-) 

Your Admin is Jean B. (On Mastodon: @HackJack@mastodon.rocks)

**Comment by Shickmo** [comment]
@ThomasLeister, 

Thanks so much for your reply. I shot @HackJack@mastodon.rocks an email this morning and hope to hear from Jean soon. I am going to close this out since honestly that should be all the information I need. 

Thanks again.
