### ISSUE TITLE
Where is Bot API and example/tutorial

### ISSUE THREAD

**Issue by sp00ck** [tootsuite/mastodon#4598]
I'm looking a bot tutorial.

**Comment by Kimik0** [comment]
AFAIK there isn't one. There is the basic Mastodon and API documentation at https://github.com/tootsuite/documentation/
For interaction with that API, you'll probably want to use an existing Mastodon library for your language of choice: https://github.com/tootsuite/documentation/blob/master/Using-the-API/Libraries.md
What you do with that is up to you really. There's all kinds of bots.

**Comment by Ox16** [comment]
@Kimik0 Hm... Where is example bot? for Ruby?
 I need send information only no read status or other. Mastodon in in Ruby isint ?
