### ISSUE TITLE
Retoot/boosted status updates have strange tags.

### ISSUE THREAD

**Issue by kensanata** [tootsuite/mastodon#4610]
Here is a status that is not tagged: [web](https://kitty.town/@KevinCarson1/1099102), [JSON](https://kitty.town/api/v1/statuses/1099102). Here is the same status, on a different server: [JSON](https://octodon.social/api/v1/statuses/5488082) – but now it is tagged NSFW! When you look at it in the stream of the user doing the boosting, you don't see this tag:

![image](https://user-images.githubusercontent.com/1145712/29355435-4a0bd87c-8271-11e7-83cb-2300cf1300f7.png)

Now, from the point of view of a client looking at the toots on octodon.social, does this count as a toot tagged NSFW even though you can't see it in the web UI and even though the original toot is not tagged NSFW?

I think this is a bug and that the NSFW tag looks like random data.

I guess the alternative is that remove toots with CW are automatically tagged NSFW on remote servers and this just needs to be [better documented](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#status)?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
`sensitive` is true when `spoiler_text` is present

**Comment by kensanata** [comment]
Thanks. You didn't say anything about the `NSFW` tag, though. My main problem is that there is a toot on `kitty.town` without any tags ([JSON](https://kitty.town/api/v1/statuses/1099102)) which is boosted by a user on `octodon.social` and suddenly it is tagged `NSFW` ([JSON](https://octodon.social/api/v1/statuses/5488082)) and I think this should be impossible to do, based on the web user interface (i.e. a bug in Mastodon), or it happens automatically when boosting sensitive messages (which would be strange and undocumented).

**Comment by kensanata** [comment]
Thanks for the explanation, @ykzts.
