### ISSUE TITLE
filter server list

### ISSUE THREAD

**Issue by WannaBeFreee** [tootsuite/mastodon#4619]
How does one find a server that respects _free expression_ wherein one is free to be erroneous, "offensive", crass, evil, uncooperative,, or otherwise unconstrained?

**Comment by Cassolotl** [comment]
If the instances list doesn't give you that kind of info, I would recommend making an account on one of the bigger open instances and asking around with public toots containing a `#needhelp` hashtag. Instances get reputations and folks might be willing to advise.
