### ISSUE TITLE
Attaching an image, then video works, but not the opposite order

### ISSUE THREAD

**Issue by Vavassor** [tootsuite/mastodon#462]
So the normal behaviour on the site: when you attach a video to a toot, it greys out and disables the button. But if you attach 1-3 images first and then a video, it posts successfully. Here's [an example toot](https://mastodon.social/users/Vavassor/updates/710280) which shows 2 images, and a blank thumbnail that, when you click on it, shows the video (of a scorpion).

**Comment by Gargron** [comment]
Good find!
