### ISSUE TITLE
Preview of links using social metadata

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#463]
(Apologies if dupe, can't easily search from mobile)

Links in toots should show a preview, generated by scraping the URL and extracting Open Graph and/or Twitter Card metadata. URL metadata should be cached.

**Comment by Gargron** [comment]
From API PoV, should this be like an extra endpoint? Something like `/api/v1/statuses/:id/card` and the UI would hit it when the detailed status view is opened?

**Comment by ineffyble** [comment]
That would make sense to me. Although Twitter also shows the metadata in non-detailed view in a bunch of cases.

**Comment by ineffyble** [comment]
Thoughts:
* Probably need to have an entity for links/URLs specifically, store metadata against them. Statuses probably have a primary URL set (link_attachments?).
* Various types of metadata and various strategies. Facebook try to show a preview for every URL, pulling plain title tags and random images. Twitter on the other hand won't show a preview, even if there's a full set of Facebook metadata, unless a twitter card type is set (they also demand unique images for each URL/page).

Interesting things:
https://github.com/discourse/onebox
https://github.com/jaimeiniesta/metainspector
