### ISSUE TITLE
Conversation between followees in different API may not appears on the Home timeline

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#4635]
on the master (c7d2619), conversation between followees may not appears on the Home in below cases.

* A@master can't see replies from B@1.5.1 to C@master
(from A side, C's status has AP url, but B's status in_reply_to is tag format)
* D@1.5.1 can't see replies from E@master to F@master
(from D side, F's status has tag-format uri, but E's status in_reply_to is AP url)

We have two way for resolving in_reply_to, but...

* find_status() / status_from_uri() won't work for remote ids in different protocol
* ThreadResolveWorker works, but it wouldn't finish before DistributionWorker starts.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Maybe #4632 would resolve this?

**Comment by unarist** [comment]
No, using generic ThreadResolveWorker allows processing of OStatus feeds, but still its execution wouldn't complete before DistributionWorker. So `thread` value would be nil yet when we check it to filter statuses by replied accounts.

**Comment by Gargron** [comment]
We could try matching by url after matching by uri before queuing ThreadResolveWorker, maybe. I think OStatus processing does this, but I might have forgotten in ActivityPub?

**Comment by unarist** [comment]
Ah, looks like we can match OStatus in-reply-to by AP id, and also AP inReplyTo by...oh wait, it only has `tag:...` uri and no feed urls. Probably we need to make it object with id and url, anyway.

but current OStatus processing doesn't seem to doing that... (below code is v1.5.1 because I want to mention about backward compatibility)

https://github.com/tootsuite/mastodon/blob/41c3389d76e3f34bd77ff474dfb4298d5a390dc1/app/lib/ostatus/activity/base.rb#L38-L45

**Comment by Gargron** [comment]
Okay, I must be misremembering. Nevertheless, it feels like we should be able to at least try to retrieve `Status.find_by(url: some_href_value)` before attempting to fetch it.

In the PR I have linked, I put the URL of the status inside inReplyTo in ActivityPub, instead of the tag: URI.

**Comment by unarist** [comment]
oh, I forgot about inReplyTo fix in that PR.

Well, how about this backward incompatibility?

> * D@1.5.1 can't see replies from E@master to F@master
> (from D side, F's status has tag-format uri, but E's status in_reply_to is AP url)

though this "issue" won't happens on before 1.5.0 :p

**Comment by unarist** [comment]
Well, OStatus URL is `.../updates/123` which refers stream_entry, and we don't use that URL for ActivityPub, so simple matching won't work.

btw, I'm thinking adding `_:atomUri` into object in Delete activity:
```
{
  id: '.../statuses/123#delete'
  type: 'Delete'
  object: {
    id: '.../statuses/123'
    '_:atomUri': 'tag:example.com:objectId=123'
  }
}
```

then we can use same approach for inReplyTo, which also allows object:

```
{
  id: '.../statuses/123'
  type: 'Note'
  inReplyTo: {
    id: '.../statuses/456'
    '_:atomUri': 'tag:example.com:objectId=456'
  }
}
```

One sad thing is we haven't used `value_or_id()` for inReplyTo, so this change is incompatible with existing master instances, but still I think this solution is reasonable as we already use this for Create activity.

(also this doesn't solves "1.5.0-1.5.1 users can't see conversation between master users in home timeline")

**Comment by unarist** [comment]
I thought this issue wouldn't be a serious for Mastodon, because we've reconstructed conversation from href value by ThreadResolveWorker. However, other implementation handles differently.

Now we have detailed discussion on #4791, I will close this.
