### ISSUE TITLE
Add CODEOWNERS for translation maintainers

### ISSUE THREAD

**Issue by m4sk1n** [tootsuite/mastodon#4651]
Using [this GitHub feature](https://help.github.com/articles/about-codeowners/), Mastodon repo should have selected people that would be able to accept/reject translations for their language.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] --This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).-- (not a bug)

**Comment by nightpool** [comment]
closed by #4670
