### ISSUE TITLE
Link absent in french translation : Delete account

### ISSUE THREAD

**Issue by xakan** [tootsuite/mastodon#4656]
Hello,

It seems that in french translation, we can not delete an account because there is no link.
![capture d ecran 2017-08-21 a 21 14 49](https://user-images.githubusercontent.com/7924208/29534643-000c4b36-86b7-11e7-816d-1b03f85e6def.png)

xakan

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Guimik** [comment]
Confirmed.
If you change the langage to ENG for example, the link is present.

**Comment by ykzts** [comment]
Can you fix it with #4659 ?
