### ISSUE TITLE
Display a warning at direct messages

### ISSUE THREAD

**Issue by benediktg** [tootsuite/mastodon#4660]
I would suggest that there should be a warning if you choose to write a direct message in Mastodon because GNU social users might see the DM (similar to the warning about private toots).

(at least for now until #4208 gets implemented)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
There already is a warning, what do you mean?

**Comment by benediktg** [comment]
Private toot has a warning: ![screenshot_20170822_195033](https://user-images.githubusercontent.com/14795615/29579495-4f597c06-8773-11e7-9f14-ef7210340c8b.png)

Direct message has no warning: ![screenshot_20170822_195049](https://user-images.githubusercontent.com/14795615/29579525-637e6da4-8773-11e7-8c63-295ff88e478c.png)

**Comment by nightpool** [comment]
you have to mention a user on another server first:
![image](https://user-images.githubusercontent.com/233815/29581243-b2be97c2-8746-11e7-95b7-26e097828faa.png)
