### ISSUE TITLE
How to close my instance?

### ISSUE THREAD

**Issue by Neustrashimy** [tootsuite/mastodon#4666]
(Related to closed Issue #4636 )

I need to close one of my instances  so that other instances will not be inconvenienced.

In the related issue, @clworld wrote about the details, but how do you specifically operate it?
Could you tell me the concrete method?
(in Rails console? rake task? SQL? etc...)

thanks.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
we would prefer that you discuss follow-up questions on closed issues, rather then opening a new one.

**Comment by nightpool** [comment]
Anyway, no specific steps are needed to ""close"" a server. If you wish, you may unfollow remote users, but that's not really a huge deal since other mastodon 1.5+ instances will automatically do this after a length of inactivity.
