### ISSUE TITLE
500 Error when remote following

### ISSUE THREAD

**Issue by aron23** [tootsuite/mastodon#4676]
Successfully deployed an instance following documentation, local registrations, following etc work fine, remote following leads to a 500 error.

Instance was installed following instructions [here](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md) over the last weekend

Visiting a url like: https://myserver.example.com/authorize_follow?acct=some_user%40some.instance is what throws the 500 error.

Running sudo journalctl -xf -u mastodon-* gives the following:

>Aug 23 19:51:00 mastodon-v1 bundle[613]: [14756f58-01a8-4fb3-aa23-f67ef5d253b7] method=GET path=/authorize_follow format=html controller=AuthorizeFollowsController action=show status=500 error='NoMethodError: undefined method `n=' for #<OpenSSL::PKey::RSA:0x007f08a100e438>
>Aug 23 19:51:00 mastodon-v1 bundle[613]: Did you mean?  n' duration=1328.09 view=0.00 db=2.60
>Aug 23 19:51:00 mastodon-v1 bundle[613]: [14756f58-01a8-4fb3-aa23-f67ef5d253b7]
>Aug 23 19:51:00 mastodon-v1 bundle[613]: [14756f58-01a8-4fb3-aa23-f67ef5d253b7] NoMethodError (undefined method `n=' for #<OpenSSL::PKey::RSA:0x007f08a100e438>
>Aug 23 19:51:00 mastodon-v1 bundle[613]: Did you mean?  n):
>Aug 23 19:51:00 mastodon-v1 bundle[613]: [14756f58-01a8-4fb3-aa23-f67ef5d253b7]
>Aug 23 19:51:00 mastodon-v1 bundle[613]: [14756f58-01a8-4fb3-aa23-f67ef5d253b7] app/services/resolve_remote_account_service.rb:119:in `public_key'
>Aug 23 19:51:00 mastodon-v1 bundle[613]: [14756f58-01a8-4fb3-aa23-f67ef5d253b7] app/services/resolve_remote_account_service.rb:87:in `update_account'
>Aug 23 19:51:00 mastodon-v1 bundle[613]: [14756f58-01a8-4fb3-aa23-f67ef5d253b7] app/services/resolve_remote_account_service.rb:46:in `block in call'
>Aug 23 19:51:00 mastodon-v1 bundle[613]: [14756f58-01a8-4fb3-aa23-f67ef5d253b7] app/services/resolve_remote_account_service.rb:41:in `call'
>Aug 23 19:51:00 mastodon-v1 bundle[613]: [14756f58-01a8-4fb3-aa23-f67ef5d253b7] app/controllers/authorize_follows_controller.rb:43:in `account_from_remote_follow'
>Aug 23 19:51:00 mastodon-v1 bundle[613]: [14756f58-01a8-4fb3-aa23-f67ef5d253b7] app/controllers/authorize_follows_controller.rb:34:in `located_account'
>Aug 23 19:51:00 mastodon-v1 bundle[613]: [14756f58-01a8-4fb3-aa23-f67ef5d253b7] app/controllers/authorize_follows_controller.rb:9:in `show'

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Are you on Ruby 2.4.1?

**Comment by aron23** [comment]
I checked and `ruby -v` was reporting 2.3.3p222, re-ran the .rbenv section of production guide and found 2.4.1 was installed just not set as default.

I then ran `rbenv global 2.4.1` and `ruby -v` reported 2.4.1, restarted mastodon with: `sudo systemctl restart mastodon-*.service` but am seeing same behavior.

**Comment by aron23** [comment]
I made a new install and it is working, must have been a configuration misstep.

Thanks for your help and the awesome app!

**Comment by Gargron** [comment]
You're welcome! I'm glad it started working
