### ISSUE TITLE
Cannot update Icon, Header image on Firefox 55

### ISSUE THREAD

**Issue by asonix** [tootsuite/mastodon#4677]
Firefox 55 cannot be used to update the icon or header image on Mastodon 1.5.1 and 1.5.0rc2 (at least). This issue happens on Windows 10 (confirmed by https://mastodon.social/@Stephen_Stone) and on Linux (confirmed by me, https://mstdn.dank.software/@asonix, https://hyenas.space/@arlo)

**Comment by Komic** [comment]
Yup, works with Chromium 62.0.3167.0 but not Firefox 56.0b4.

**Comment by Gargron** [comment]
cc @ykzts might be the preview JavaScript blocking the form?

**Comment by nclm** [comment]
Ah yes I had this too, but wasn’t sure where the issue was exactly! Firefox 57 on Linux. It happens with any files uploaded through the preferences, CSV lists included too.

**Comment by ykzts** [comment]
@Gargron 

> might be the preview JavaScript blocking the form?

I think that I will not block.

Also, as long as I confirm it does not reproduce the problem (on Win 10 and on macOS 10.12). This is very strange...

**Comment by nclm** [comment]
> Ah yes I had this too, but wasn’t sure where the issue was exactly! Firefox 57 on Linux.
I tried again one week later, still 1.5.1, still Firefox 57 but from a few days after, and it’s working well again.

**Comment by asonix** [comment]
The Firefox 55.0.3 update fixes this issue.

**Comment by nightpool** [comment]
Thanks for reporting this @asonix! For completeness' sake, or in case anyone else comes looking for this issue, the root cause seems to be https://bugzilla.mozilla.org/show_bug.cgi?id=1383518
