### ISSUE TITLE
resolving the issue of emoji disparity in notifications

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#469]
for desktop notifications (on chrome, at least) the sent notifications are showing up in different emoji. this disparity can be resolved how discord does it: by changing to the colon-codes that represent each emoji in one-emoji

**Comment by Gargron** [comment]
So... they wouldn't show up as emoji at all then? The text in desktop notifications is not html, it's just plain text.

**Comment by hoodiek** [comment]
yeah, it does show emoji in the pop-ups, tho, so i think removing them from pop up notifs is better overall

**Comment by Gargron** [comment]
I disagree. A shortcode is definitely not better than a native emoji when EmojiOne is unavailable.
