### ISSUE TITLE
ATOM parser has problems with CDATA encoded data

### ISSUE THREAD

**Issue by pfefferle** [tootsuite/mastodon#4696]
When sending a toot via WordPress, Mastodon have some problems parsing the Atom Feed. It seems that Mastodon do not support CDATA correctly.

Example Feed: https://notiz.blog/author/matthias-pfefferle/feed/ostatus
Mastodon version: https://mastodon.social/web/statuses/10132687

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Closing on the grounds that OStatus is no longer our primary mechanism and will be deprecated in the future.
