### ISSUE TITLE
add an hint that a message is part of a thread

### ISSUE THREAD

**Issue by xcombelle** [tootsuite/mastodon#4716]
There is no hint that either a message is part of a thread reply or not. It lead to several disagreement and a real confusion about the meaning of a reply in the last case. the confusion eventually was solved. 

So my idea would be to add some kind of hint that a message is a reply. Actually an even better UX would be to show a part of the thread as twitter does, but I'm quite sure that this last option is a giant issue, so just an hint would be already great.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate. (as far as I could)
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). (not in mastodon.social at least)

**Comment by Cassolotl** [comment]
There is! The reply arrow is a double arrow in threads:

![screen shot 2017-08-27 at 10 25 38](https://user-images.githubusercontent.com/6607512/29748642-2b08547e-8b12-11e7-9b48-46609c73f888.png)

It is really hard to see though unless you know you're looking for it!

**Comment by xcombelle** [comment]
I was more thinking as a small font, explicit sentence on top of the post like in twitter: "In reply to @xxx, @yyyy, ...."

**Comment by Cassolotl** [comment]
If it's in reply to someone, their usernames are usually tagged at the top of the toot. But yeah, if it's a reply-to-self, its threadness is very unclear, I agree. I would like something *more* to show that it's connected. On Twitter there's usually a vertical line/bar/thing, which works.

![screen shot 2017-09-29 at 12 11 07](https://user-images.githubusercontent.com/6607512/31013734-5287b708-a50f-11e7-95ea-7f2a721b900a.png)

Putting the avatar only once and then stacking the replies like on Telegram would also work (but only with replies-to-self):

![screen shot 2017-09-29 at 12 12 31](https://user-images.githubusercontent.com/6607512/31013774-86796d90-a50f-11e7-8266-f2b4b5d3ead3.png)

I don't know. I'd really like it to be more obvious when something is a reply, especially when it's a one person thread/reply-to-self.

**Comment by xcombelle** [comment]
Actually it would be ideal if the context of the toot would be given (such as one answer from and one answer to) just as in twitter, but anyway, just a mention that it is a reply would be a huge improvement;

**Comment by jpdeplaix** [comment]
Any updates on this ?

**Comment by krinkko** [comment]
any news on this?

**Comment by trwnh** [comment]
@krinkko it was implemented years ago...?

**Comment by Cassolotl** [comment]
I have replied to this in the past acknowledging the feature, and *even I had forgotten this feature was there.* It is invisible and unintuitive. Plus, it is still only useful for any post other than the first post in a thread.
