### ISSUE TITLE
Silent mentioning

### ISSUE THREAD

**Issue by m4sk1n** [tootsuite/mastodon#4719]
When using direct messages, I should be able to mention someone without making him able to see this message. @@mentioned (or @@mentioned@instance.example.com) should be good way to do it.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
this feels like it goes against the purpose of mentioning a user.

can't you just link to their profile instead?

**Comment by Cassolotl** [comment]
@nightpool Clicking links to users and toots opens them in a new tab, which means you can't do things like boosting or following. You'd have to paste those URLs into the search bar.

Pasting into the search bar is fine, except that people don't know to do that, so folks have to explain that reasonably often. Sometimes I tell people who've been using Mastodon for weeks or even months and they've had no idea this whole time.

If a profile or toot link opened in the fourth column that would be a good solution, though!

**Comment by m4sk1n** [comment]
So, if I would make PR for it, would it get merged?

**Comment by trwnh** [comment]
Probably easiest to just take the first @ out of it. For example, turning `@user@instance.tld` to simply `user@instance.tld` in order to not include them in the DM. That makes it more obviously not a URL and not clickable, which would silently encourage users to paste it into the search bar instead of into their browser.

**Comment by Cassolotl** [comment]
I think they want to link to someone's profile without them getting notified though? Like, mentioning someone in a DM, linking, it looks tidy, and they don't get pinged?

**Comment by trwnh** [comment]
>to link to someone's profile without notifying them

I guess the cleanest way to do this would be to hyperlink `user@instance.tld` to `instance.tld/@user`, then? But that could also get confusing with emails.

Either way, I don't know if it's a good idea or if there's a good way to link to someone in the webapp without mentioning them. The simplest way to do this is simply to remove the @ sign. I don't think it's too hard to expect users to copy/paste that if they want to load a profile.

**Comment by Gargron** [comment]
Well, the whole point of always notifying the user about being mentioned is to prevent dogpiling from being organized in secret (i.e. you see a lot of hate coming in, but you don't know what the original source is). Making it necessary to open the profile through slightly more elaborate means than simply clicking on a mention is meant as deterrence. 

It's all in there with quote toots and no account search. Still possible but with increased effort, works to deter casual abuse.

So I feel like we don't need this. Closing
