### ISSUE TITLE
Opt "IN" unlisted toot's hash tags on hashtag timeline

### ISSUE THREAD

**Issue by KEINOS** [tootsuite/mastodon#4724]
I wonder if there's a way or chance to toot off-local-timeline but be listed on the tag stream?

I assumed that the simple way is to post a `visibility=unlisted` toot, but also opts out from the hashtag's timeline. 

According to @Gargron 's comment on #4497 , and the [user guide](https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/User-guide.md#toot-privacy) it seems to be a specification.

>Might it have been an unlisted post? 
>Unlisted opts out of hashtag timelines too.

>Unlisted toots are public, except that they do not appear in the public timelines or search results. 

All I want is to toot via TootBot but **without cluttering up the local timeline**, and be on the hash tag timeline.

The reason is that currently, the Bot toot's about new posts on the technical blog, and it includes hash tags about the article such as "#docker", "#ruby", etc..., so to be listed on the hashtag stream when the user clicks the hashtag link.

But since there are more than 200 posts/day, the local timeline is filled with the toot bot's toot and usual toots are buried in.

I would be happy if this might be a consideration.

* * * *

- [* ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
Tangentially related to *Hashtag timelines don't include private posts even if you are allowed to see them #2440* I think!

**Comment by KEINOS** [comment]
@Cassolotl 

Indeed, whatever the reasons are unpublic posts are unpublic. So they shouldn't be listed to KISS the system.
I'll close this issue with a hope to stronger search capabilities in the future.
