### ISSUE TITLE
Media modal with multiple images is hard to close on mobile

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#4743]
![4193d24c33c67910](https://user-images.githubusercontent.com/705555/29856211-495b586e-8d8c-11e7-84f8-8e7266683036.png)

In this case, only ways to close the modal are... (highlighted area) 

- touch small margins on top and bottom of images
- touch × button on the top right of the image

Some ideas:

- **Close on vertical swipes**
I think it's popular nowadays in mobile apps, including iOS Photo app, Twitter, Discord and others.
- **Make × button more stand out** #3660
It looks small for touchable buttons, and hard to distinguish with some images. Looks like other apps use more big and lighter button and/or place it at outside of the image. It may be a distraction, so they toggle visibility on touching images.
- **Close on back button on the browser** #3647
Opening modal which covers most of the screen also looks like transition, so closing on back button seems reasonable. Backing to previous view with keeping modal shown seems weird anyway.
- **Add more margins around the modal**
...actually, I don't think it's good for small screen of mobile devices.

also I want to hear thoughts from @sorin-davidoi @yiskah from a perspective of a11y.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yiskah** [comment]
For First one we should look at out Twitter etc. implement that
Second one should definitely happen
Third one should probably happen?

I can't say I have a lot of thoughts on this, this isn't an issue I've worked with before. So long as any focusable link explains what it is and so long as shaky hands won't struggle then it should be good.

**Comment by penduin** [comment]
Count me as a big second for letting the back button close the current modal, rather than keeping it open and re-navigating underneath.

#3647 was closed but the confusing behaviour remains.  I suppose I'm all in favor of any clear way to close modals, but the back button is my favorite, especially considering the event is already being handled, and doing something counter-intuitive.
