### ISSUE TITLE
Optional Profile/Bio Fields

### ISSUE THREAD

**Issue by cathalgarvey** [tootsuite/mastodon#4751]
An idiom from Twitter that irritates me to no end, and which I've already seen on day one using Mastodon: "Retoots are not endorsements".

It shouldn't be necessary to post these things, but evidently it's considered useful to some. Another one is statements-of-gender, such as "she/her", which seem to be self-categorisations rather than 'bio' info.

At the risk of seeing profile bloat, perhaps the option to add _up to five_ additional fields, with some preset suggestions like "retoots are:", "identity:", or more common things like "location:", "website:", would let people add some colour in a structured way, and give them a place to put the stuff they feel they *have* to include (retoots are not narwhals) and put just their bios into their bios. :)

(BTW: Thanks for Mastodon!)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by thiagomgd** [comment]
I miss a location and website field.
And yes, I know I can put them in my bio, BUT, as bio has 160 char limit, it is not ideal. Also, having a separate field for location / website would make it easier to see that info on profiles, AND, maybe later (way later, I guess), allow filter/search profiles by it.

I guess: "Location", "Birthday (or only year)/Age", "Identity/Pronoun", "Website" would be useful :)

About "Website", see also #121

**Comment by wxcafe** [comment]
let's continue this discussion in #121
