### ISSUE TITLE
IPFS backend?

### ISSUE THREAD

**Issue by matthiasbeyer** [tootsuite/mastodon#477]
Hi,

this looks awesome. I would love to get back into micro-blogging, but first I would like to ask: Would it be possible to add a IPFS backend? Where the data itself is stored in IPFS?

I've been thinking a lot about how to do such a thing, lately - still have no optimized idea, though I think it is possible.

First, one has to define a data format which is used for storing the data in IPFS. Of course this should be 

1. Plain-Text, for example YAML or JSON (I'd prefer the former, but that's bike-shedding)
2. Optimized for the properies of IPFS - so we can _never_ alter the data we put into IPFS, so we must come up with a solution that is flexible and does not leverage the constness.

I'd love to hear your opinion.

**Comment by Gargron** [comment]
IPFS is a cool sounding technology but it would require a complete re-doing of the project and re-thinking of all the protocols and technologies involved to migrate it to IPFS, so this will not be a thing.
