### ISSUE TITLE
"Sensitive Content" overlay isn't centered on Safari

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#4780]
On Safari, the "Sensitive Content" overlay is offset to the top since the 1.5.1 update. I tested this on awoo.space and mastodon.social.
<img width="333" alt="bildschirmfoto 2017-09-02 um 18 00 27" src="https://user-images.githubusercontent.com/8197071/29996994-4436cba0-9009-11e7-914b-a715d0b15255.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
ref #4570

**Comment by noiob** [comment]
woops, thank you
