### ISSUE TITLE
ActivityPub follow accept not forwarded to Web UI?

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#4794]
When issuing a follow request to a remote ActivityPub-enabled user, the Web UI displays a hourglass icon for the pending request, but does not update with the follow accept: a manual refresh of the whole Web UI is needed for it to be taken into account.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
It's true, there is no auto-update. I think the original plan was to fake an instant accept at API level during the immediate response, to make the UI show up as "following" while really you're not. That would give enough time until refresh for things to actually come through. I guess I forgot to add that..?

**Comment by ThibG** [comment]
That original plan would be weird for accounts that require manual validation of follow requests, no?

**Comment by Gargron** [comment]
@ThibG That's only for indicated-as-not-locked ones, of course. (Technically, all accounts are locked in AP)

**Comment by ThibG** [comment]
@Gargron ok, makes sense, although it would be better if it was actually updated from the accept callback, thus avoiding incorrect information

**Comment by nightpool** [comment]
Should we maybe keep this issue open to track an actual auto-update mechanism?
