### ISSUE TITLE
No easy access to own pinned toots in Web UI

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#4795]
Pinned toots are not easily accessible from within the Web UI (to be unpinned for instance), it requires manually finding the pinned toots instead. Unless I have missed something, the easiest way to do so currently is to copy the toots' URL from the public profile to the Web UI search bar, not very user-friendly.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by voidsatisfaction** [comment]
It is solved by #4817. Thank you for your suggestion!
