### ISSUE TITLE
When clicking on a toot, notification column scrolls up

### ISSUE THREAD

**Issue by Sylvhem** [tootsuite/mastodon#4797]
In Mastodon 1.6.0rc1, when I click on a toot to open it in the last column, the notification column automatically scrolls up. It happens independently of this column's position.
This seems to affect [several users](https://witches.town/web/statuses/4794178).

Steps to reproduce:
1. pin the notification column
2. scroll down the notification column
3. click on a too in any column 

Tested on Debian Stretch with Mozilla Firefox 52.3.0 (64 bits).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Do you solve with #4792?

**Comment by Sylvhem** [comment]
I'm not sure, I don't have a private instance for testing it myself.

**Comment by yiskah** [comment]
I can confirm this is happening for me as well in Firefox on windows. This is happening on cybre.space

**Comment by Lucidiot** [comment]
Same with Chromium 60.0.3112.113 on Arch Linux, hostux.social running 1.6.0rc1

**Comment by Gargron** [comment]
Of course this has been fixed as @ykzts points out but RC2 is not out yet.
