### ISSUE TITLE
Search should have some indication of in-progress/complete

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#480]
Since it can take a while to find a user on a federated network, there needs to be a visual distinction between "looking for this handle" and "couldn't find this handle".

**Comment by Gargron** [comment]
Search form needs to be re-worked for sure... The hashtag suggestion is a bit of a hack (just displays user input back as a link to a hashtag), the search only does an API call for accounts, and mixes search and resolving in one method. I don't know how I want it to work instead though.

**Comment by Gargron** [comment]
I think we have what you wanted now.
