### ISSUE TITLE
Problems when searching for handles that are a substring of another handle

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#481]
That said I've noticed a GUI bug. It seems to be impossible to search for @ti@mastodon.social now that I follow @ticky@mastodon.social (this is from another instance)

Ditto for @bunny@Mastodon.social because of @bunnylyn@mastodon.social

Ended up mentioning them in a toot just so I could follow them

**Comment by Gargron** [comment]
Probably this https://github.com/tootsuite/mastodon/blob/master/app/services/search_service.rb#L20
