### ISSUE TITLE
Allow users to post audio files

### ISSUE THREAD

**Issue by Sylvhem** [tootsuite/mastodon#4827]
It is currently possible to attach up to four pictures or one video to a toot. However, it's not possible to add an audio file to a post.

I suggest we add the possibility for users to attach audio files to their status.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by noxarivis** [comment]
this is an awesome idea!

**Comment by tlhall** [comment]
When I try to attach an audio-only webm file, I get a 500 error.

**Comment by noxarivis** [comment]
it seems to do thumbnailing or something

**Comment by rainbowmultiverse** [comment]
Audio-only webm works for me. I use Reaper for it, so maybe it's doing something different. I would still prefer to use a proper audio format. Using a video container adds unnecessary file size. Even a short ~30 second clip at 400x300 is half the size of a 3 minute MP3.

**Comment by trwnh** [comment]
Preferably post .ogg files, or transcode to .ogg. Opus codec would be best, but Vorbis could work too, maybe? Not transcoding is also an option, but that could waste a lot of space if we store lots of .wav files.

**Comment by Aldarone** [comment]
Just to bump : It has been done like this in glitch-soc : glitch-soc/mastodon#161

**Comment by koyuawsmbrtn** [comment]
It's 2018 and it's still missing. @Gargron should look into it now!

**Comment by trwnh** [comment]
per https://elekk.xyz/@Crash/100103248910629947

>Mastodon Feature Request:
>
>Ability to upload MP3 files complete with an enclosure tag added to the RSS for that account that allows anyone on Mastodon to have a podcast without needing a different service.
>
>Assuming instance settings for file upload size can tolerate this, of course...

**Comment by novadeviator** [comment]
Many musicians and sound artists would be grateful for audio upload support. I read about all the difficulties and reservations about it and I can understand them, but there's IS an urgent need for it as much as it is for video and image support. 

There are number of communities around music-making and audio and they need this feature (smusi.ch, metalhead.club, sonomu.club), folks doing podcasts, and blind people as well. 

Please make this feature happen - also, support OPUS and FLAC which are the open standards that are here to stay.

**Comment by yungslime** [comment]
as a mostly audio-centric artist, i would very much appreciate audio uploads in any way, shape or form. 

it's annoying that i have to run everything i want to upload through ffmpeg or something similar instead of just dragging a wav file into my browser.

**Comment by kyefox** [comment]
Still wanting this a year and a half later. I can always export as video in Reaper, but:

- I don't know which format will load in all browsers
- It still adds wasted space and complexity with an unnecessary video container

The usual copyright fears don't really apply since people post it anyway. It's not even consistent: I see plenty of copyright infringement with images and videos, and the people who own pixels are 9000x more sue-happy than the record labels used to be. This argument feels like it's stuck in the dark days post-Napster and pre-legal streaming when grandparents got C&D letters because their grandkids downloaded Metallica while visiting.

**Comment by flippthebunny** [comment]
Made a cool GitHub account to add my enthusiastic heck yeah!! Let's do this and let mastodon ring out with the sound of bedroom techno   🎶🎶🎶

**Comment by MirceaKitsune** [comment]
There was a pull request adding this feature, but for some reason it got closed without actually being added. I really hope it will be reopened and finished soon... I was sad that an important feature would be dropped like that even when the code is already there.

**Comment by MrAureliusR** [comment]
Please do implement this! It would be amazing for Anonradio DJs to be able to post snippets from their shows on the SDF instance, for example. And being able to share audio in general is a must for any social media platform!

**Comment by audiodude** [comment]
I post every song I record to my mastodon instance, but I always have to first upload the mp3 somewhere else and post a link. Inline audio posts would be a welcome feature!

**Comment by nikoss** [comment]
Some sort of compromise, or precaution, would be to transcode all audio to a lower bitrate. 
Something like Opus 32kbps.
See... 
https://wiki.hydrogenaud.io/index.php?title=Opus#Music_encoding_quality

I wouldn't suggest going lower than that,
for the simple reason that opus defaults to mono at bitrates lower than 32kbps.
If you know of a similar codec that goes to 24kbps but maintains stereo,
please suggest. 
I would rather loose upper and lower frequencies, than loose stereo.

This way people could share voice and speech.
And also share lower quality copies of music (more like samples).
Lower quality than FM radio.

Why we desperately need this feature... I don't think there is any need for arguing.

Why this feature might be a problem... How to "fix" this problem, or avoid it...
That's the issue, I would think.

**Comment by nikoss** [comment]
Another option, kind of brutal,
would be to introduce random beeps in the audio.
Some shareware audio software used to do that.
And, yes, it is quiet annoying.
So... not recommended.

Mastodon could enable some of these features,
experimentally,
and let administrators decide.

And we will see, how it goes...

**Comment by yungslime** [comment]
I honestly still think the whole copyright discussion is kinda ridiculous when you can easily package more than a full song in an MP4 file and upload it like that.

If that was what we're really worried about, video uploads shouldn't be possible whatsoever.

**Comment by trwnh** [comment]
IMO transcoding everything to Opus 32kbps is a fine idea, but functionally it's just an implementation detail. IIRC images/video are just uploaded directly with minimal processing, anyway.

**Comment by ldexterldesign** [comment]
👋 https://github.com/mastodon/mastodon/issues/17037
