### ISSUE TITLE
The "uri" key isn't containing URI

### ISSUE THREAD

**Issue by Sylvhem** [tootsuite/mastodon#4829]
Mastodon [1.6.0rc1](https://github.com/tootsuite/mastodon/releases/tag/v1.6.0rc1) introduced a new feature, known as "[protocol handler](https://github.com/tootsuite/mastodon/pull/4511)". Since then, Mastodon can successfully open URI starting with the `web+mastodon://` scheme.
Here are some examples of such URI:
- `web+mastodon://follow?uri=alice@example.com`
- `web+mastodon://share?text=Lorem+ipsum`

As you can see, when this kind of URI is used to follow an account, a query containing the `uri` key is necessary. Or, the value associated with this kind of key is **not** a URI but a Mastodon address.
For reference, this is how the [RFC 3986](https://tools.ietf.org/html/rfc3986) is defining URI:
> The generic URI syntax consists of a hierarchical sequence of
   components referred to as the scheme, authority, path, query, and
   fragment. […] The scheme and path components are required, though the path may be
   empty (no characters).

Even though this should not create any problem, I think that, for both clarity and accuracy's sake, it's a bad idea to use `uri` as a key's name when the associated value will not contain any kind of URI.

Since `web+mastodon://` URI haven't found their way into a main release yet, I suggest we change the name of this key to something else (fer example, `id`).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
URI stands for Unique Resource Identifier.

<https://tools.ietf.org/html/draft-ietf-appsawg-acct-uri-06>

**Comment by Sylvhem** [comment]
Oh, I see. But then don't you think we should use `acct:alice@example.com` as a value?
My point is: it's probably best if the value of the `uri` key is itself a URI.

**Comment by Aldarone** [comment]
You mean something like `web+mastodon://follow?uri=https%3A%2F%2Fwitches.town%2F%40Alda` ?

**Comment by Gargron** [comment]
A Unique Resource Identifier only needs to be unique and identify a resource. There are wildly different formats of URIs. It's perfectly fine to use username@domain just as much as acct:username@domain and http://domain/@username etc. I really don't see a reason to be picky about this.

**Comment by Sylvhem** [comment]
> A Unique Resource Identifier only needs to be unique and identify a resource.

I'm really sorry Gargron, but I don't think that's true.
As mentioned earlier, the generic syntax for an Unique Resource Identifier is described in the [RFC 3986](https://tools.ietf.org/html/rfc3986), [section 1.1.1](https://tools.ietf.org/html/rfc3986#section-1.1.1). Among other things, URI need to start by a scheme like `http`, `mailto` ou `acct`. Things like `acct:alice@example.com`, `https://example.com/@alice` and `web+mastodon://share?text=Lorem+ipsum` are URI while `alice@example.com` is not.

> I really don't see a reason to be picky about this.

Since, URI is a standardized term covered by an IETF specification, I think we shouldn't start describing as URI objects that don't match the specified syntax, even if their are unique and used to identify a resource.
I'm sorry, my purpose is not to annoy you with this, but I think it's really important to follow standards, especially with technology as well-spread as URI.
