### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by valentinp72** [tootsuite/mastodon#4831]
Hello,

I recently tried to update my instance from 1.4.7 to 1.5.1. I had troubles with permissions during the update of node modules. 
Now, I have many missing modules (offline-plugin, webpack, webpack-merge, compression-webpack-plugin, glob, extract-text-webpack-plugin, rimraf, js-yaml, ...). 
I first tried to install all these modules by hand, but there is just too many of them...
Also, when I'm installing a module by hand (with npm install <x>), I'm always seeing this warning: 

> npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none is installed. You must install peer dependencies yourself.

I tried to remove the folder ~/.npm and the node_modules folder of my instance, and start again using:
```
gem install bundler
bundle install --deployment --without development test
yarn install --pure-lockfile
```
... but the problem remains...

![capture d ecran 2017-09-06 a 14 38 36](https://user-images.githubusercontent.com/2760679/30135828-c5b0458e-935c-11e7-825c-211a69ac1818.png)

How can I re-download and reinstall every module from scratch?
I tried so many commands to do it that I can't even remember what I already tried...

Thanks in advance,

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
I'm not seeing the `yarn install --pure-lockfile` output in your screenshot. Can you paste that here? thanks.

**Comment by valentinp72** [comment]
Sorry for the long response, I didn't had internet the last few days...

Here is the `yarn install --pure-lockfile` output. Some warnings, nothing really important I guess? Should I update Yarn to 1.0.1?
![capture d ecran 2017-09-12 a 22 31 20](https://user-images.githubusercontent.com/2760679/30430370-5100885c-995b-11e7-8dd3-300f4e108bd1.png)

**Comment by valentinp72** [comment]
I don't really know how, but I tried again, but this time to update to 1.6.1, and everything worked perfectly, no missing modules! 😇
