### ISSUE TITLE
Videos should be expandable into a lightbox

### ISSUE THREAD

**Issue by marrus-sh** [tootsuite/mastodon#485]
Right now, on desktop Firefox at least, clicking play on a video keeps it within the toot instead of showing it at full size. Aside from being small and hard to see, this means the video is cropped to fit the video container. It would be nice if there was a button to expand the video without having to leave the browser window/tab.

(This is not a problem on mobile, as videos are always played in fullscreen)

**Comment by MicroJoe** [comment]
I have the same problem on Firefox 52.0.2 (Arch Linux 64bits). In my opinion there should be a button on the bottom right of the video that allows to preview it in a bigger size.
