### ISSUE TITLE
Home feed "will be regenerated soon" since a week

### ISSUE THREAD

**Issue by thomaskuntzz** [tootsuite/mastodon#4851]
I have an account on mastodon.social that I didn't use for a few months. A few days ago, I wanted to use it again, but the home feed was empty and only showed a message saying:

> Your home feed is empty. If you have been inactive for a while, it will be regenerated for you soon

I thought it would be a matter of minutes, but now it's be a little more than a week that it shows this every time I log in, so I guess that's a bug...

**Comment by Gargron** [comment]
Is there any chance that the people you're following haven't posted anything at all?

**Comment by thomaskuntzz** [comment]
Humm... Yeah, looks like no one that I follow posted anything during that time period... That might explain why 😁

**Comment by thomaskuntzz** [comment]
I tried to follow some random guy that posts stuff all the time and now stuff appears in the home feed

**Comment by thomaskuntzz** [comment]
It might still be good to tell people that nothing was posted to avoid having them believe it's a bug, like I did believe...
