### ISSUE TITLE
You can send direct messages to yourself/without mentioning anyone

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#4885]
You can send direct messages without mentioning anyone. Currently using them as markers, as a workaround for #4877.

THIS IS AMAZING! PLEASE KEEP THIS FEATURE!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
Thanks for your feedback. Is it okay if I close the issue, considering that this has already been implemented?

**Comment by SoniEx2** [comment]
I mean it's technically a bug.

**Comment by nightpool** [comment]
why would it be a bug?

**Comment by SoniEx2** [comment]
I'm pretty sure sending messages to nobody is not intended. I'm just someone who's abusing it for something actually useful that isn't just about filling the DB with garbage without anyone noticing.

**Comment by wxcafe** [comment]
I don't think this can meaningfully be used as a real attack of any sort, toots are so small in the DB that DoSing a server that way would be pretty useless. Now, posting empty DMs with large images, that might cause trouble...

🤔

**Comment by clworld** [comment]
I used this 'feature' for test posting new custom emoji. feels nice.

I heard that some users on large jp instance post lots of DM without mentions and suspended by admin some month ago.

**Comment by SoniEx2** [comment]
If this is `priority - medium`, then why's #4877 `priority - low`? Removing an useful feature for no reason other than to fix a bug isn't nice. :/

**Comment by nightpool** [comment]
This isn't a bug it shouldn't be open.

Bugs are problems that cause issues for users.

**Comment by wxcafe** [comment]
This can be used to DoS an instance tho? Like make an account, then DM yourself with images and fill the disk. I’m pretty sure this qualifies as “a problem for users”

Clément 'wxcafé' Hertling

**Comment by nightpool** [comment]
The DoS concern is valid but completely orthogonal to this ticket.

**Comment by wxcafe** [comment]
Alright, that’s fair. 

Clément 'wxcafé' Hertling
