### ISSUE TITLE
about/more in 1.6.0 causes long-running query

### ISSUE THREAD

**Issue by asonix** [tootsuite/mastodon#4888]
Counting the statuses on this instance should be fast, since there's only ~3,000, but requests time out because of it.

The first two queries in the attached image are the long-running count.

![image](https://user-images.githubusercontent.com/5304643/30255389-33deb9be-9669-11e7-915a-3ff6a329ca14.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
It sounds like they got "stuck" and you could kill them or restart Mastodon. Sometimes this happens even to requests which should be highly optimized.

**Comment by asonix** [comment]
I have restarted mastodon-web multiple times, and this issue persists.

Observations:
- This didn't seem to happen with previous versions of mastodon
- This doesn't happen all the time, but it happens enough to notice.

**Comment by KindlyFire** [comment]
I have the same problem (or similar) here (maly.io) three times in the last two days. Sidekiq fails to execute tasks because the 15 threads are blocked, waiting for SQL queries to complete. Killing all long-running queries fixes the problem and Sidekiq starts handling tasks again.

Have this problem on 1.6.0 and 1.6.1.

**Comment by KindlyFire** [comment]
I do not know if it is related to `/about/more` though.

**Comment by unstabler** [comment]
:'( 
![screenshot_20171025_123904](https://user-images.githubusercontent.com/964412/31979453-cc355cf0-b981-11e7-93b9-9dea7b553d9d.png)

**Comment by ykzts** [comment]
Resolve from #4996.
