### ISSUE TITLE
Assets compiled incorrectly during 1.6.0 upgrade

### ISSUE THREAD

**Issue by SirCmpwn** [tootsuite/mastodon#4902]
After upgrading cmpwn.com and running assets:precompile, the command exited with status code 0 but the styles on my profile page are incorrect: https://cmpwn.com/@sir

I tried compiling assets on a separate machine and rsyncing public up to the prod server, but that doesn't fix the issue.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by SirCmpwn** [comment]
After restarting mastodon-web this problem went away. I'm not sure what caused it; I checked before restarting -web and systemd showed it had been running since a time that indicates that I did *not* fail to restart it after the upgrade.

**Comment by ykzts** [comment]
Did you reload puma?

**Comment by SirCmpwn** [comment]
No. Should that be mentioned in the upgrade docs?

**Comment by ykzts** [comment]
A restart is required to reflect the code change.

Surely the upgrade docs does not contain that method.

**Comment by SirCmpwn** [comment]
See for yourself, puma is unmentioned in the release notes: https://github.com/tootsuite/mastodon/releases/tag/v1.6.0

**Comment by nightpool** [comment]
@SirCmpwn did you restart it *after* running assets:precompile? the asset location is cached by the application, so you always have to restart it after compiling assets

**Comment by SirCmpwn** [comment]
Yes, I mentioned that.
