### ISSUE TITLE
Notifications still being shown, even when logged out (cookie expired)

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#4903]
When a cookie expires, then the push notifications are still shown to the user. This is a big privacy issue when you locked your account for example. I haven't tested it out, when a user is logging out theirselves manually, but this should work as expected.

**What I did:** Letting a cookie expire and wait for notifcations
**Expected behaviour:** Notifications shouldn't be shown
**What actually happened:** Notifcations are shown even when "logged out"
**How to reproduce:** Turn on push notifcations and let the cookie expire (or clear cookies should work too)
**Where does it happen:** 1.6.0rc5

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by deutrino** [comment]
Is this still a problem?

**Comment by koyuawsmbrtn** [comment]
Yes, I can still confirm it since 2.1.0, where it did happen. I don't know if it's actually fixed now.

**Comment by koyuawsmbrtn** [comment]
The issue still persists in 2.2.0.

**Comment by Gargron** [comment]
I don't think it's possible to fix this when a cookie expires unexpectedly, because that happens on the client and not on the server. The server has no way of knowing that the cookie expired and it should stop sending notifications. Sorry.
