### ISSUE TITLE
Remote status from followers with mentions to local users processed twice

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#4905]
Status with mentions to a local user are processed twice, leading to noisy logs, with stuff like “ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_statuses_on_uri"”.

Haven't investigated in-depth yet.

**Comment by unarist** [comment]
I think this issue may happen when

* the status delivered to followers and mentioned users, or
* the status delivered to two users on the same instance.

We had tried to remove first one at #4739, but it was reverted since the implementation hadn't cared about direct posts, which won't delivered to followers.

Anyway, rechecking status existence on that error would solve this issue?

**Comment by Gargron** [comment]
It's more of a timing issue, I believe. We check for existence of status first, but it's not atomic. So the state may change between the result of that query and the INSERT.

**Comment by ThibG** [comment]
The thing is there is a first synchronous attempt at resolving the thread via StatusFinder which fails because of the local_url? thing. I'm 100% sure on that, done extensive testing.

Then, the status *might* get displayed properly if the two concurrent jobs execute in a particular order.

Can't get much more in-depth atm, quite busy where I am :)

Le 12 septembre 2017 15:08:36 GMT+02:00, Eugen Rochko <notifications@github.com> a écrit :
>It's more of a timing issue, I believe. We check for existence of
>status first, but it's not atomic. So the state may change between the
>result of that query and the INSERT.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tootsuite/mastodon/issues/4905#issuecomment-328847364

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by ThibG** [comment]
Oh sorry, this was the other issue I reported, disregard this comment please :)

Le 12 septembre 2017 15:21:27 GMT+02:00, Thibaut Girka <thib@sitedethib.com> a écrit :
>The thing is there is a first synchronous attempt at resolving the
>thread via StatusFinder which fails because of the local_url? thing.
>I'm 100% sure on that, done extensive testing.
>
>Then, the status *might* get displayed properly if the two concurrent
>jobs execute in a particular order.
>
>Can't get much more in-depth atm, quite busy where I am :)
>
>Le 12 septembre 2017 15:08:36 GMT+02:00, Eugen Rochko
><notifications@github.com> a écrit :
>>It's more of a timing issue, I believe. We check for existence of
>>status first, but it's not atomic. So the state may change between the
>>result of that query and the INSERT.
>>
>>-- 
>>You are receiving this because you authored the thread.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/tootsuite/mastodon/issues/4905#issuecomment-328847364
>
>-- 
>Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser
>ma brièveté.

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
