### ISSUE TITLE
Why is my instant example.com for sign up

### ISSUE THREAD

**Issue by cumbiame** [tootsuite/mastodon#4912]
I would really appreciate if someone can help me. 

If you go to my instance you'll see that when you are going to sign up, where you type in your username it says example.com

Why? And how can I change that from the terminal on Ubuntu 16.04.

**Comment by nightpool** [comment]
you need to set the LOCAL_DOMAIN environment variable

**Comment by cumbiame** [comment]
When I type in sudo nano .env.production it just gives me back a black page now. Can anyone help with that? Sorry, I'm a beginner, so my questions are quite basic.
