### ISSUE TITLE
API to get server constants (toot length, ...)

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#4915]
It world be nice to make API to get constants thats is used in validation.

it provides some constants to need to validate profile,toots,media attachment.
- no need to new endpoint. it may be in instance-information API.
- no need to enumerate all the possibilities. it shows some build-time constants that used in official mastodon.

Wanted attributes from app-side validations:
- max-length of toot + spoiler_text (already defined in web-app)
- max-length of user display name (already defined in web-app)
- max-length of user note (already defined in web-app)
- max-number of media attachment (already defined in web-app)
- list of mime types that acceptable for media attachment. (already defined in web-app)
- max-length of attached media bytes count. (before re-encoding, it may depends on limitation in Web front server. maybe we need to make variable in .env.production ? )

**Comment by tateisu** [comment]
As far as I know, mstdn.maud.io has modified these constants
Kanzaki-don also changes the upper limit of the number of bytes of attached media

**Comment by lambadalambda** [comment]
I'd be very interested in that too. Now that Pleroma speaks the Mastodon api, it would be good if it was possible to tell client apps how much characters they can actually use.

**Comment by wxcafe** [comment]
This is a really good idea yeah.

**Comment by unarist** [comment]
I'm thinking `limits` object in `/api/v1/instance`, for example:

```rb
{
    uri: "example.com",
    title: "example",
    description: "<p>hoge</p>",
    email: "admin@example.com",
    version: "2.1.0",
    thumbnail: "https://example.com/system/site_uploads/files/000/000/001/original/mstdn_opengraph.png"
    urls: {
      streaming_api: "wss://example.com"
    },
    stats: {
      user_count: 1,
      status_count: 1,
      domain_count: 1
    },
    limits: {
      account_display_name_length: 30,
      account_note_length: 160,
      status_length: 500,
      # 4 for images, but 1 for video?
      status_attachment_count: 4,
      # less than 8.megabytes
      attachment_size: 8.megabytes - 1,
      attachment_mime_types: ['image/jpeg', 'image/png', 'image/gif', 'video_webm', 'video/mp4'],
      attachment_extensions: ['.jpg', '.jpeg', '.png', '.gif', '.webm', '.mp4', '.m4v']
    }
  }
```

**Comment by nullkal** [comment]
How about `capability` instead of `limits`? Then, we can add information not only limitation, but also whether the instance implements features such as `pinned toots` by simply add `pinned_toots: true`.

**Comment by lambadalambda** [comment]
As far as I can tell, Gargron will block these kinds of feature requests. see https://github.com/tootsuite/mastodon/pull/5697

**Comment by unarist** [comment]
@lambadalambda I've read your PR and his comments, then I wonder if it's only *exposing* without *making configurable*.

We may change constraints in the future, even if we don't support customizations. So exposing those constraints via API is still useful for third-party clients.

**Comment by unarist** [comment]
@nullkal Hmm, should those information be in same property? Also don't clients want to know feature/endpoint versions, instead of only existence?

**Comment by tateisu** [comment]
Pleroma has "max_toot_chars" in https://pleroma.soykaf.com/api/v1/instance .

**Comment by Gargron** [comment]
Sorry it took so long to come around on this. I think @unarist is absolutely right, even if I'm against making some of these limits adjustable, we may need to change some of these values in the future (and have already adjusted file size limits and supported mime types multiple times). To be fair, I was very much against `max_toot_chars` because it's inconsistent with all other code and API language - we never used `toot` in the code (exception being the name of the CLI utility `tootctl`) and because it was just stuffed into the Instance object haphazardly. The PR I just uploaded takes a more organized approach I am content with.
