### ISSUE TITLE
Retoot count increases without reason

### ISSUE THREAD

**Issue by NFGman** [tootsuite/mastodon#4916]
I recently made a toot with one account, and retooted it from another, and was surprised to find it indicated 2 retoots already.  I checked, but mine was the only retoot.  A few hours later, that same post has 3 retoots, but still only shows one when the details are checked.

Here's the post in question:
https://nfg.zone/web/statuses/203818

Running 1.6.0

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
I saw this on cybrespace too, although I can't find the status atm.....

@NFGman were they both local accounts?

**Comment by NFGman** [comment]
Yes, both local accounts.

**Comment by Aldarone** [comment]
Happens on WitchesTown too.

- Boosting toot increases boost count.
- Faving toots increases both fav and boost count.

Only the webclient seems affected.

**Comment by NFGman** [comment]
I first noticed it using the Pawoo client, so I don't think it's limited to the Web client.

**Comment by Aldarone** [comment]
Well yes it seems chaotic, trying to reproduce while recording I have a different behavior.

https://gfycat.com/fr/gifs/detail/kindlygrosshochstettersfrog

Boosting count increases but never decreases.

![capture d ecran_2017-09-13_14-54-07](https://user-images.githubusercontent.com/2682011/30378630-282d2fec-9894-11e7-9802-9f63d8b6bf90.png)

**Comment by unarist** [comment]
```
web_1        |   Status Load (2.0ms)  SELECT  "statuses".* FROM "statuses" WHERE "statuses"."account_id" = $1 AND "statuses"."reblog_of_id" = 11000 ORDER BY "statuses"."id" DESC LIMIT $2  [["account_id", 1], ["LIMIT", 1]]
web_1        |    (0.9ms)  BEGIN
web_1        |   SQL (1.8ms)  INSERT INTO "conversations" ("created_at", "updated_at") VALUES ($1, $2) RETURNING "id"  [["created_at", "2017-10-04 23:52:34.783152"], ["updated_at", "2017-10-04 23:52:34.783152"]]
web_1        |   Status Exists (0.8ms)  SELECT  1 AS one FROM "statuses" WHERE "statuses"."reblog_of_id" = $1 AND "statuses"."account_id" = 1 LIMIT $2  [["reblog_of_id", 11000], ["LIMIT", 1]]
web_1        |   SQL (3.6ms)  INSERT INTO "statuses" ("account_id", "created_at", "updated_at", "reblog_of_id", "conversation_id", "local") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["account_id", 1], ["created_at", "2017-10-04 23:52:34.790437"], ["updated_at", "2017-10-04 23:52:34.790437"], ["reblog_of_id", 11000], ["conversation_id", 7432], ["local", "t"]]
web_1        |   SQL (1.2ms)  UPDATE "accounts" SET "statuses_count" = COALESCE("statuses_count", 0) + 1 WHERE "accounts"."id" = $1  [["id", 1]]
web_1        |   SQL (1.0ms)  UPDATE "statuses" SET "reblogs_count" = COALESCE("reblogs_count", 0) + 1 WHERE "statuses"."id" = $1  [["id", 11000]]
web_1        |   SQL (1.4ms)  INSERT INTO "stream_entries" ("account_id", "activity_id", "activity_type", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["account_id", 1], ["activity_id", 98799075686172373], ["activity_type", "Status"], ["created_at", "2017-10-04 23:52:34.826662"], ["updated_at", "2017-10-04 23:52:34.826662"]]
web_1        |   SQL (1.2ms)  UPDATE "statuses" SET "uri" = $1, "updated_at" = $2 WHERE "statuses"."id" = $3  [["uri", "https://don.otto.local/users/admin/statuses/98799075686172373/activity"], ["updated_at", "2017-10-04 23:52:34.835451"], ["id", 98799075686172373]]
web_1        |   SQL (1.3ms)  UPDATE "statuses" SET "reblogs_count" = COALESCE("reblogs_count", 0) + 1 WHERE "statuses"."id" = $1  [["id", 11000]]
web_1        |    (1.6ms)  COMMIT
```

1. insert status (reblog)
2. (it causes increment of reblogs_count)
3. update uri (we set uri for local statuses just after creation)
4. (it causes increment of reblogs_count...again!)

😕

**Comment by cacheflow** [comment]
I'll take a look at this.

**Comment by cacheflow** [comment]
Think I fixed this. https://github.com/tootsuite/mastodon/pull/5363
