### ISSUE TITLE
Statuses from suspended domains showing on federated timeline after upgrading to 1.6

### ISSUE THREAD

**Issue by rainyday** [tootsuite/mastodon#4917]
After upgrading to Mastodon 1.6 (Docker) I am now seeing now seeing messages from users on suspended domains showing up in my server's federated timeline. This includes media attachments. The domain suspension was added before upgrading to 1.6.

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Aldarone** [comment]
This is happening on WitchesTown too. My guess is that the conversation fetching code bypasses the suspension mechanisms because only toot that have a known answer or that are part of a conversation are showing up.
