### ISSUE TITLE
limits the number of Pinned toot

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#4918]
Pinned toots currently has no upper limit. 
We should limit the number of pinned toots.

From the UX perspective, this limit seems preferable 3-5.

… Also There are problems other than UX. 
When acquiring the list of pinned toot from the API, the URL returned by the Link header is incorrect. The 'pinned' query parameter is missing in that URL. Max_id in the URL returns the status_id of the last element in the list, but the order of pinned toots is not related to status_id. How can I get the continuation of pinned status correctly?
If we can get all the pinned toots in a single query, this problem will be solved.
API document says max number  of  the status in single query is 80. (but API returns 40 in real implementation) I think the limit MUST be lower or equal to query limit.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
I mean, we should fix both problems, right?
