### ISSUE TITLE
"We're sorry, but something went wrong." when trying to upload my avatar

### ISSUE THREAD

**Issue by cumbiame** [tootsuite/mastodon#4919]
Hey guys! 
I just installed an instance at cumbiame.com 

I ran into an issue. When I try to upload my avatar and I hit submit, I get sent to a page that says "We're sorry, but something went wrong." 

* * * *

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ x] This bug happens on a [newest release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by cumbiame** [comment]
This happens when I try to upload any type of picture. I get a 500 Server Error

**Comment by Gargron** [comment]
Did you install using Docker? Try `sudo chown -R 991:991 public/system`, the permissions on the uploads folder might be wrong.

**Comment by cumbiame** [comment]
Thank you so much. That fix the problem.
