### ISSUE TITLE
/app/javascript/mastodon/load_polyfills.js does not work

### ISSUE THREAD

**Issue by matyapiro31** [tootsuite/mastodon#4922]
If load_polyfills.js works well, string.prototype.includes and Promise() will work in IE11, but still in mastodon v1.6.0, they returns errors.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Mastodon does not support IE 11
