### ISSUE TITLE
Mastodon rewrites actor URL on foreign service

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#4933]
Separated from issue #4906 

The followng JSON-LD snippet was received after a Follow activity was accepted by Mastodon. The object id (https://hub.somaton.com/channel/mario#follows/24130) is not the original id and uses Mastodon assumptions and is not resolvable on our system. 

````
{
       "@context":[
         "https://www.w3.org/ns/activitystreams",
         "https://w3id.org/security/v1",
         {
           "manuallyApprovesFollowers":"as:manuallyApprovesFollowers",
           "sensitive":"as:sensitive",
           "hashtag":"as:Hashtag",
           "ostatus":"http://ostatus.org#",
           "atomUri":"ostatus:atomUri",
           "inReplyToAtomUri":"ostatus:inReplyToAtomUri",
           "conversation":"ostatus:conversation"
         }
       ],
       "id":"https://mastodon.social/users/motesting4#accepts/follows/24130",
       "type":"Accept",
       "actor":"https://mastodon.social/users/motesting4",
       "object":{
         "id":"https://hub.somaton.com/channel/mario#follows/24130",
         "type":"Follow",
         "actor":"https://hub.somaton.com/channel/mario",
         "object":"https://mastodon.social/users/motesting4"
       },
       "signature":{
         "type":"RsaSignature2017",
         "creator":"https://mastodon.social/users/motesting4#main-key",
         "created":"2017-09-12T08:17:47Z",
         "signatureValue":"qmhhtwhYdcm+J994JyocbcIViz215WrIWQnn4k9UaQg4eAarK8cTRf0DFV6MHqtC4iyRfS+6LC3AfdJ0yd00jlnAhpp5r81PMTrfYgACYQBu3JhXqIa06LByeasyLB4BOjYRnQeoYtPIiH8HBYCbQSQcqt7yFyXvsoDvMcNbv5FJdrlJDCSfXXtYmgvX2mjkjm9XRcH/t50Ndnybq4rH1ESc1dGMXQSIYnbFz52JXbkgGYGItTkybB7146R61GSQRpRdkpo6w2txKpvKB2NbDob5nNR+WR/xG7Xh/e2Pi6Er6mDe4TL7noh6WZp06WUbDFHUTeShbskAAzJHQ0SquQ=="
       }
     }
````
@Gargron is aware of the issue and indicated in #4906 that this may involve significant refactoring. I am able to work around it on the short term but providing a trackable issue to ensure the work is completed. Other ActivityPub providers may not be able to work around this.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate. See #4906)
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by lambadalambda** [comment]
Any plans on getting this fixed? Mastodon still sends made up object ids.

**Comment by Gargron** [comment]
I think this is fixed? Because we store and re-use follow IDs now
