### ISSUE TITLE
api/v1/search returns 503

### ISSUE THREAD

**Issue by matyapiro31** [tootsuite/mastodon#4939]
When you search like `mastodon.socia/l@Gargron`, not `https://mastodon.social/@Gargron`,
/api/v1/search returns 503, Service unavailable. This isn't expected action, isn't it?
it should return the same as with "https://".
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ykzts** [comment]
Supported formats are `@Gargron@mastodon.social`, `Gargron@mastodon.social` and `https://mastodon.social/@Gargron`.

**Comment by matyapiro31** [comment]
No, I wanna say is why it returns 503, not an error code.

**Comment by ykzts** [comment]
I think that you have received the message "503 Remote data could not be fetched". Is it inappropriate as a message that comes out because it was incorrectly formatted and data could not be acquired correctly?

**Comment by matyapiro31** [comment]
Error code should be returned as json, I think.

**Comment by matyapiro31** [comment]
For example, `example.com/test` is just returns 0 result, but `example.com/@test` returns 503.
