### ISSUE TITLE
Support GNU Social share URLs

### ISSUE THREAD

**Issue by steelman** [tootsuite/mastodon#4940]
GNU Social supports a less automated share functionality than Mastodon (see #4511). One needs to enter an URL of an instance to be redirected to a post composing form (you can see how it works at https://publiccode.eu/), Although the URL is different than in Mastodon: `/notice/new?status_textarea=Lorem+ipsum`, it is trivial to redirect such queries.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ykzts** [comment]
ref https://github.com/tootsuite/mastodon/pull/5967#issuecomment-374078500
