### ISSUE TITLE
Embed Format Error when viewed in Safari

### ISSUE THREAD

**Issue by ZiiX** [tootsuite/mastodon#4948]
The 'Follow Mastodon button & border' are really tall when viewed in safari vs other browsers like firefox & chrome. Attached is how it is viewed in safari.

![Pic of format error in safari](https://user-images.githubusercontent.com/2234740/30440015-3fcc471e-992a-11e7-8092-ca21a4d3b9f8.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a tagged release v1.6.0

**Comment by Gargron** [comment]
We fixed this, oops
