### ISSUE TITLE
Feature request: Two-factor authentication

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#495]
It would be great if Mastodon could support 2FA, either self-implemented or using an existing service (it would also make sense to allow login using other OAuth2 accounts etc).

https://github.com/tinfoil/devise-two-factor looks interesting

**Comment by flamsmark** [comment]
I'd love to see U2F support.

**Comment by ThomasLeister** [comment]
TOTP 2FA is supported with the latest version. :-)

**Comment by Gargron** [comment]
Yes, 2FA has been added!
