### ISSUE TITLE
Link to "previous" toots missing when browsing publicly accessible profile page

### ISSUE THREAD

**Issue by fceschmidt** [tootsuite/mastodon#4950]
Hello all,

this concerns v1.6.0 as it is currently deployed on hex.bz, I am not sure about other instances. I have attached the following screenshot to illustrate my issue:

![screenshot from 2017-09-14 19-11-18](https://user-images.githubusercontent.com/15253483/30443755-f2d9a620-9980-11e7-870f-24a43d6fef4d.png)

It is taken from https://hex.bz/@fce?max_id=2014079.

In this example I have already clicked the 'next' button more than once, so I would expect a link back to the previous page on the left-hand side, but I do not see it there. Please add this. :)

Greetings,
Fabian Schmidt

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
Not fixed in 1.6.1 nor in on master 👍
