### ISSUE TITLE
gif upload fails

### ISSUE THREAD

**Issue by drewwallace** [tootsuite/mastodon#496]
When i try to upload a gif, the bar gets stuck near the end, then eventually fails with the error below. 
This happens on all browsers i've tried (chrome, firefox, opera), using my account https://mastodon.social/users/dw
I was able to upload 2 gifs when i first made the account; it stopped working soon after.
Other image types work as expected.

![2017-01-18 11_15_05-mastodon](https://cloud.githubusercontent.com/assets/5750323/22072155/6cba49f0-dd6f-11e6-9c58-d37276762c6a.png)

![2017-01-18 11_17_26-mastodon](https://cloud.githubusercontent.com/assets/5750323/22072263/c886e892-dd6f-11e6-85d7-62483261b6e1.png)

![2017-01-18 11_17_40-mastodon](https://cloud.githubusercontent.com/assets/5750323/22072271/d080c590-dd6f-11e6-9f7c-4060333226c1.png)

**Comment by ineffyble** [comment]
Can you link/attach the GIF you're trying to upload here?

Could you sign up for an account on another instance (e.g. https://toot.zone ) and try and upload it there?

**Comment by mkosler** [comment]
Adding my voice saying this happens to me as well. Eugen has said that he thinks it might be a timeout issue when I spoke with him on the site about it.

**Comment by Ragzouken** [comment]
![004](https://cloud.githubusercontent.com/assets/527158/22853829/cf236d38-f057-11e6-9417-cdd09c91f685.gif)

consistently fail to upload this gif to masto/awoo (500 error)

**Comment by Gargron** [comment]
This was seemingly fixed after increasing the rack-timeout value
