### ISSUE TITLE
Backward compatibility on parsing text to toot ( /statuses/new?text= -> /share?text= )

### ISSUE THREAD

**Issue by KEINOS** [tootsuite/mastodon#4965]
For making a link to "share" the URL and text via toot, currently, these 2 requests do the same behavior.

`https://v1.5.x.sample.com/intent/statuses/new?text=HelloWorld`
`https://v1.6.x.sample.com/share?text=HelloWorld`

So on v1.6.x, I would like the `redirect` feature for the older type of request.
Not for long but for some time until most instances become v.1.6.x.

- Request
`https://v1.6.x.sample.com/intent/statuse/new?text=HelloWorld`
- Redirect
`https://v1.6.x.sample.com/share?text=HelloWorld`

* * * *

- [* ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
why? Share intent was implemented in v1.6.0. It does not exist in v1.5.0.

**Comment by KEINOS** [comment]
@ykzts 

> why?

Just for backward compatibility of v1.6.0 for v1.5.x, until most instances become >= v1.6.0.

I thought, redirecting these 2 forms of URLs below, to the new format ( `https://sample.com/share?text=HelloWorld` ), it would cover both the old version of Mastodon and GNU Social.

But as of #442, it seems that compatibility that drags down development is no good.
So never mind. Please close this issue（異臭）.

```
// Mastodon v1.5.x style
https://sample.com/intent/statuse/new?text=HelloWorld
// GNUSocial style
https://sample.com/notice/new?status_textarea=HelloWorld
```

**Comment by ykzts** [comment]
> `https://sample.com/intent/statuse/new?text=HelloWorld`

This URL can not be used with Mastodon v 1.5.1.

Are you misunderstood as an application that is not Mastodon?

**Comment by unarist** [comment]
> `https://sample.com/intent/statuse/new?text=HelloWorld`

That URL has been used on Pawoo and Qiitadon (and others?), but it's *instance-specific* feature. We've never implemented share intent in that URL on [tootsuite/mastodon](https://github.com/tootsuite/mastodon/).

You should ask each instance owners about those customization.

**Comment by KEINOS** [comment]
@ykzts 
> This URL can not be used with Mastodon v 1.5.1.

@unarist 
> it's instance-specific feature. 
> We've never implemented share intent in that URL

Gee, really?! I'm really sorry about that. m(_ _;)m

Since all the instances that I join, including Pawoo and Qiitadon, worked that way, I thought it was a standard feature.

Again, sorry for the disturbance and thank you for the support!
