### ISSUE TITLE
if mentioning someone I can't use the autofill with the mouse 

### ISSUE THREAD

**Issue by PaulFree14** [tootsuite/mastodon#497]
When I start typing in @ and then a name and then tryn to use the autofill with the mouse it doesn't work. 
I have to do it with pressing enter. It's not to bad that I need to do it with pressing enter....I'll just thought in the beginning the function is completly broken and was very disapointed. 
But happy that it function with just using the keyboard.

**Comment by Gargron** [comment]
Fixed in #513
