### ISSUE TITLE
Advanced Filter/ Regex Not Being Applied to Timelines

### ISSUE THREAD

**Issue by nicseve** [tootsuite/mastodon#4990]
Trying to understand why, for some reason, regular expressions are not being applied to timelines upon being entered. I'm running an instance with Docker and Nginx. 

I have found mentions of this issue from other instance admins (not on Git) encountering this problem but no following solution. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nicseve** [comment]
Any theories as to why this is happening are much appreciated.

**Comment by nightpool** [comment]
I'm assuming you figured it out?
