### ISSUE TITLE
self-untag

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#500]
unsubscribe from thread in a form that is transparent to users, by marking a thread and all posts as "untagged" or some such mark. this would probably federate as a post that requests users untag you, and would on mastodon, at least, make anyone who replies to the post automatically not add their @ to the post, to encourage allowing people to peacefully leave conversations without incident

**Comment by Gargron** [comment]
#59?

**Comment by hoodiek** [comment]
while related, i believe they are seperate issues, as this one encourages users to save space in toots and also meet the needs of that same issue
