### ISSUE TITLE
Applying Google font in custom.scss no longer working?

### ISSUE THREAD

**Issue by imshyuan** [tootsuite/mastodon#5047]
Hi,

Since I upgraded my Mastodon instance from v1.4.6 to v1.6.x, I can no longer use the old way to apply my custom Google font.

Previously, I only had to `@import` the font and add the modified CSS classes (specifically for font family) in my `custom.scss` file. Now this doesn't work anymore.

When checking the font on live site, it's always `mastodon-font-sans-serif` despite added `Rubik` Google font to the `font-family`.

Does anyone have idea what's preventing the custom Google font being applied?

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
Is this happening on a tagged release or on master?

**Comment by imshyuan** [comment]
@nightpool Tagged release. Currently on v1.6.1.

**Comment by MaciekBaron** [comment]
Applying fonts works on master.

If this is still an issue, please share your code with us so we can see how you apply it.

**Comment by imshyuan** [comment]
@MaciekBaron no longer an issue after upgrading to v2.x. It was weird though, I've always been using master versions, that particular version couldn't apply custom font. Anyway, I'll close this (totally forgot to do so) :D
