### ISSUE TITLE
Make og:image on Toot detail page optional

### ISSUE THREAD

**Issue by cooox** [tootsuite/mastodon#5050]
When linking a Toot from another service, e.g. Twitter, which crawls the Opengraph meta tags, the user's avatar is displayed as the image. This might be disturbing, if one only wants to display a Card with the title and description.

Is there a way to toggle the og:image inclusion? Maybe a setting like the existing `setting_noindex`, e.g. `setting_disable_cardavatar`, could be introduced and handled like the option in 447b8bc44eb33ae6ffdfbcc7ae52fbe0bba93ece?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Maybe we should disable avatars-as-og:image completely? That being said, that is what Twitter does for tweets, too.

**Comment by cooox** [comment]
I checked multiple solutions, but the fact that og:image is not optional according to http://ogp.me more or less resolves this issue. 

Besides, currently the Twitter card type `summary_large_image` is used, maybe `summary` is a better solution. https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary

That being said, Twitter asks to use the meta tag with `name` instead of `property`, https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started, so 
`= opengraph 'twitter:card', 'summary'` should really be `%meta{ name: 'twitter:card', content: 'summary' }` in the view: https://github.com/tootsuite/mastodon/blob/cdad7977fc94cd6a1a97841ed0f25e8504cb80d6/app/views/stream_entries/show.html.haml#L17

One thing that looked a lot more promising was using the oops.png-image in https://github.com/tootsuite/mastodon/blob/cdad7977fc94cd6a1a97841ed0f25e8504cb80d6/app/views/stream_entries/_og_image.html.haml#L21 meaning `= opengraph 'og:image', full_asset_url('/oops.png')`. 

Works better with the higher resolution - maybe there's a good Card-image that can be used with Mastodon?

**Comment by nightpool** [comment]
I don't see any difference between summary card and summary_large_image
card on the page you linked?

**Comment by cooox** [comment]
@nightpool yeah, saw that too. Might be a mistaken Card type in the Twitter docs, there are also some [broken links](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards) present (second paragraph)…

Was curious and tested the variants myself. Below you find the three versions "summary" but without an image, "summary" and "summary_large_image" both with a low-resolution image (a real Mastodon avatar). 
![comparison](https://i.imgur.com/1amDjyg.png)
Please note, there was **no og:image used**, it may not be enough to delete the "twitter:image" tag if an og:image is present. I used the Card validator at https://cards-dev.twitter.com/validator btw
