### ISSUE TITLE
Pass flash to React

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#507]
It would make sense to pass the rails `flash` to React's INITIAL_STATE, and then call showAlert on any notices.

This would out of the box have a neat little "You have signed in" notice. It would also allow controllers to redirect to /web with a notice (for example, if authorize_follow is called on someone the user is already following, redirect to their account with a "You are already following @Gargron" notice.

**Comment by Gargron** [comment]
I'd rather not interwine them any more, sorry!
