### ISSUE TITLE
Skin tone dropdown in new emoji picker broken in Chrome

### ISSUE THREAD

**Issue by MightyPork** [tootsuite/mastodon#5079]
Skin tone modifiers don't work in the new emoji picker, even though there is a selection button for them, and are not suggested by the autocomplete.

It's not something I personally find useful, but if we're removing the feature, the selecting button should  also be removed from the picker.

**Comment by Gargron** [comment]
>Skin tone modifiers don't work in the new emoji picker, even though there is a selection button for them

I cannot confirm this? I can select a skin tone and post an emoji with that skin tone.

>and are not suggested by the autocomplete.

How is that one supposed to work? Neither GitHub nor Discord show skin-tone modified emojis in autosuggestions.

**Comment by MightyPork** [comment]
I've tested it on glitch.social, running 909a6d4661fbc79419e396076467aec6251b7af4

The bug might be related to search, if you try eg search "thumb", the tone picker stops working. When you search "hand", it sometimes works but then gets stuck.

But there's no JS error in the console :(

![screenshot_20170924_154328](https://user-images.githubusercontent.com/2041118/30783220-64f2a2e6-a13f-11e7-9fd7-12123356cf75.png)

How it worked with emojione:

![screenshot_20170924_154128](https://user-images.githubusercontent.com/2041118/30783234-a998f404-a13f-11e7-89b9-adaca2b49a66.png)

**Comment by Gargron** [comment]
>The bug might be related to search, if you try eg search "thumb", the tone picker stops working. When you search "hand", it sometimes works but then gets stuck.

I am on Firefox and I still cannot confirm this, it works. Are you on Chrome or some other browser?

>How it worked with emojione:

I see. I haven't seen this because we didn't have autocomplete with emojione. I think emoji-mart's index does not make copies of emojis for each skin tone.. or maybe the search does not return them. In any case, I am not sure if that is the desired behaviour anyway? That is quite a noisy output.

**Comment by MightyPork** [comment]
Works fine in Firefox, can reliably reproduce in Chrome (61), even with all extensions and plugins disabled.
