### ISSUE TITLE
oEmbed photo card won't appear for URLs which already used for other status

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#5081]
When we implemented dedup of preview cards on #4642, we assumed `preview_cards.url` is a link URL. but actually, we've overwritten it with image URL for oEmbed (type=photo).

https://github.com/tootsuite/mastodon/blob/909a6d4661fbc79419e396076467aec6251b7af4/app/services/fetch_link_card_service.rb#L86-L89

Since that record can't be found by a link URL, it tries to create new record, but it failed due to the unique index. (also LinkCrawlWorker ignores any errors by `retry: false`)

So, new status with that URL gets neither the existing card nor a new card.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on v1.6.0 and master

**Comment by Gargron** [comment]
I think this is fixed..?
