### ISSUE TITLE
Towards a unified Chinese translation for fedverse

### ISSUE THREAD

**Issue by Artoria2e5** [tootsuite/mastodon#5086]
An issue facing Mastodon in Chinese is that we don't quite have a unified translation for Fedverse between Simplified and Traditional Chinese. While `zh-CN` translates it as 象毛世界 (elephant hair world, damn cute!), the two traditional Chineses generally ditch the -verse part and go for something like "union/federated websites" (联盟网站).

Both approaches have their shortcomings: the Simplified one priorities Mastodon over other networks, making introduction into other sites and Wikipedia problematic; the Traditional ways, on the other hand, appear to be going too far in making the name self-explanatory, resulting in things unsuitable for using as proper nouns. Can we find a name that is not specific to Mastodon yet specific enough to identify this OStatus/ActivityPub-based community? (Oh also, make it collapsible into two characters so we can align it with 本地 (local) for the timelines.)

**Comment by Artoria2e5** [comment]
The traditional Chinese approach can be modified to make it something about the union itself instead of sounding like an arbitrary collection of websites. A non-serious suggestion is to parodize UFP (星际联邦, "interstellar federation") from Star Trek into 网际联邦 ("network-wide federation").

**Comment by KenOokamiHoro** [comment]
@Chinese translators ( found in contributors in files ):
zh-CN: @leopku @lynlynlynx @vidarlee @ymmtmdk @ykzts @treby
zh-HK: @yookoala
zh-TW: @shouko
Sorry for disturb everyone 😂

**Comment by yookoala** [comment]
Some suggestions for brain storming:

* 社交聯盟 (Socializing Federation)
* 聯盟圈 (Federated Circle)

**Comment by Artoria2e5** [comment]
I think I like the "circle" one better than the "社交聯盟" one because it sounds novel enough to be specific. Well let's wait for more ideas…

**Comment by ragingscholar** [comment]
Thank you so much for opening this thread, I think we really need it.
We as a simplified chinese instance, stick to "象毛世界"(Yes, the hairy elephant world) for fediverse, "本地时间轴" for local timeline, and  "跨站时间轴" for federated timeline.

Personally I think those terms are okay, since both "象毛世界" and  "本地时间轴" are very descriptive, the only term I think may need to standardize is "跨站时间轴" since it literately means "cross-site timeline", the "federated" part lost during translation.

I like your idea of borrowing the term from interstellar federation very much since we've been using "universe" to describe the fediverse and "planets" to describe instances to new Chinese users for quite some time. 

So thumbs up for  "网际时间轴" , and let's wait for more ideas.

**Comment by hexawing** [comment]
I prefer "象宇宙" for fediverse since its more “Sci-Fi”

**Comment by outloudvi** [comment]
For "federated timeline", maybe "联合时间轴" (united timeline) is an idea.

For an descriptive one, "circle" are familiar enough to people living in mainland China, because of the popularity of WeChat. (I don't really know what other zh-hans/zh-hant users are used to.)

**Comment by 84795949** [comment]
I always encounter some problems, follow the tutorial step by step, discover or not, open my website, prompt "HTTP ERROR 500", can someone help me？

**Comment by yookoala** [comment]
@84795949 Please find support in [Mastodon Meta Discussion Board](https://discourse.joinmastodon.org/). This thread is specific to the Chinese translation issue we're talking about. Thanks.

**Comment by Artoria2e5** [comment]
@hexawing I already ruled out all elephant things. Mastodon isn't the only thing using that fedverse. Fedverse is not mastoverse.

@outloudvi Reducing the number of variations involved should ease the learning curve by a bit, which is why the two-character collapsing rule exists.

And uh, I don't know about the WeChat Moments thing. WeChat seems to be sadly making some gains outside of the jail, spreading the jail to everyone.

**Comment by outloudvi** [comment]
@Artoria2e5 Sorry if I didn't get what you said. Do you mean the "align" by keeping "本地时间轴" on the UI as long as the unified name of that (e.g. "联合时间轴")?

**Comment by Artoria2e5** [comment]
It's for the character count.

**Comment by SerCom-KC** [comment]
If talking about social networking in a narrow sense, I think I'll +1 for `联盟圈`.
[PeerTube](https://github.com/Chocobozzz/PeerTube) is also using the term to describe a network of federated services.

**Comment by Artoria2e5** [comment]
Still preferring some space-y thing due to https://mastodon.social/@b_cavello/1429836.
