### ISSUE TITLE
Subfolder installation 

### ISSUE THREAD

**Issue by ser** [tootsuite/mastodon#5089]
I need to install Mastodon in a subfolder of a domain, instead of root of the domain. 

http://example.com/mastodon/

Nginx is easy to set up, but Mastodon does not seem to have a config option for that.

**Comment by ykzts** [comment]
[WebFinger](https://webfinger.net/spec/) requests the root directory.

see [RFC 7033](https://tools.ietf.org/html/rfc7033).

**Comment by ser** [comment]
Yes and no in the same time. Rfc5785 defines a static /.well-known/ subdirectory, indeed, but it's not obvious that whole of it is reserved for web finger only. My SSL  concentrator proxies many services inside that subdir to other applications. 

I do not see any valid point in closing this case, as any concentrator, including nginx, can proxy WebFinger into a subdir.

Administrator should have a choice, taking over of "/" of the Mastodon service is an unacceptable solution.

**Comment by ggtea** [comment]
Use subdomain with SNI instead of subfolder. I think it's reasonable.
All 3rd party applications may relies on all api endpoint is on '/'.
It seems hard way move it to subfolder.

**Comment by ser** [comment]
Administrator should have a choice. My boss strictly prohibits use of subdomains as it creates mess with EV SSL and costs money. Third parties should NOT rely on static URI, but read values provided by application. I do not see any technical problems with adding a value to the config file and extending root path to everything to "/" plus that value.

**Comment by ykzts** [comment]
> #### 4. Why aren't per-directory well-known locations defined?
> 
> Allowing every URI path segment to have a well-known location (e.g., "/images/.well-known/") would increase the risks of colliding with a pre-existing URI on a site, and generally these solutions are found not to scale well, because they're too "chatty".

No, it is not explicitly defined in [RFC 5785](https://tools.ietf.org/html/rfc5785).

**Comment by ser** [comment]
Again, WebFinger is one example of use of RFC 5785. Why do you insist that you have a right to take over of whole "/.well-known/" subdir on my server?

**Comment by akihikodaki** [comment]
You can use reverse proxy like nginx.

**Comment by ser** [comment]
I do, but Mastodon for example redirects to "/" after logging in and I would have to deploy a complex sub_filter configuration to overpass it. 

Mastodon must understand that it is working in a subdir.

**Comment by akihikodaki** [comment]
I mean reverse proxy allows you to override some sub paths of `/.well-known/`. Mastodon does not necessary to take over the whole directory even if it is running on the root directory. In fact, many instances share the directory with ACME authentication for Let's Encrypt.

**Comment by thurloat** [comment]
@akihikodaki confirmed. I share a /.well-known/ for Let's Encrypt on my server as well.

**Comment by ser** [comment]
Sure, nginx is able to override everything but Mastodon. It's the problem I'm signaling in this ticket. 

You can proxy/rewrite Let's Encrypt but Mastodon.

Mastodon forces "/" and nginx without complex sub_filter (reverse engineered) rules is not able to send it back to the correct URI. We need to be able to set, in Mastodon config file, a value which can be added to that "/". Then everything will be working and everyone will be happy.

There is no technical obstructions for that coming from any RFC.

**Comment by ggtea** [comment]
I guess that redirection is caused by Devise gem and where redirect to is maintained by Rails.
I don't know how to solve it, but goole may helps you.

**Comment by akihikodaki** [comment]
So you mean you want to host Mastodon except `/.well-known` in a sub directory?

**Comment by ggtea** [comment]
It seems it isn't impossible. but I feel it's dangerous. https://github.com/ggtea/mastodon/pull/1

**Comment by jeena** [comment]
Most of the webapps I'm using nowadays got that right. I use Jenkins in a subdir by setting JENKINS_OPTS="--prefix=/jenkins" and in nginx I'm listening on location ^~ /jenkins/ {...}

The same for GitLab, which is also a Ruby on Rails application, perhaps the pull request which enabled it for them might be of help for your guys to be able to implement this too.

I'll be waiting with my installation untill then.
