### ISSUE TITLE
"Toots with replies" on profiles is ambiguous

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#5093]
"Toots with replies" on profiles is ambiguous. It sounds like it will show you a person's toots that have been replied to by others.

I think it should say "toots and replies", to be clearer!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by matt-auckland** [comment]
Done, however this only modifies the English locale. 
https://github.com/tootsuite/mastodon/pull/5648

**Comment by Cassolotl** [comment]
@matt-auckland Thank you! :)

**Comment by matt-auckland** [comment]
@Cassolotl No problem, I've just started using mastodon recently and I'm keen to do what I can to help improve it :)
