### ISSUE TITLE
Boosted toots jump to top of timeline

### ISSUE THREAD

**Issue by sdukhovni** [tootsuite/mastodon#5097]
When I boost a toot far from the top of my home timeline, it immediately disappears and moves to the top of the timeline, making it hard to interact further with the toot (eg favouriting, replying).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
This catches me out every time, and it bothers me a lot! If it needs to be at the top of the Home column, can it at least be in both places instead of moved to the top?
