### ISSUE TITLE
Web client on iOS pauses audio

### ISSUE THREAD

**Issue by sanspoint** [tootsuite/mastodon#510]
With the new notification sounds, viewing the web UI on iOS while playing audio causes it to pause, so the Mastodon web client can play audio. When using the web client as an app, the app completely takes over audio from the playing app. This is very inconvenient. There also appears to be no way to disable audio from within the mobile site. Whether this would resolve the problem, however, I don't know.

**Comment by ashfurrow** [comment]
I just tested this and it looks like it got fixed at some point. I'm going to close this issue, but if it's still happening for you please re-open. Thanks!

**Comment by sanspoint** [comment]
Just checked (I'd been using Amaroq for a while), and it is, indeed, fixed. Thanks!

**Comment by ashfurrow** [comment]
Cool! Thanks for following up 👍
