### ISSUE TITLE
image upload fails 500

### ISSUE THREAD

**Issue by GluedToTheScreen** [tootsuite/mastodon#5130]
Just noticed on https://mastodon.social and same on another instance...

Composing message and, when attach an image, it fails... small slider in lower left says 500

I assume that's http response of Internal Serve Error.

**Comment by nolanlawson** [comment]
Thanks for reporting! Yes, this happens for a variety of reasons, e.g. the server is under heavy load or the image is too big. If you can provide a screenshot of the HTTP error (e.g. in the dev tools) that would be helpful, otherwise we'll have to close this issue without more details.

**Comment by nolanlawson** [comment]
Whoops closed prematurely

**Comment by Gargron** [comment]
I'm sorry but this report is meaningless. End-users don't get exposed to the real backtrace so there's nothing you *can* report, really, and error 500 could be anything but most likely a temporary load issue rather than something in the code.

**Comment by Tryum** [comment]
I'm having the same issue on the instance I admin.... Could I provide some traces/debug log ?

I tried to check the docker-compose log for hints.... but I'm getting flooded ;)
