### ISSUE TITLE
notifications column doesn't load whether i refollowed people until i click on them

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#514]
How it looks like after an F5:

![image](https://cloud.githubusercontent.com/assets/175467/22214621/9282fd76-e198-11e6-9467-61c28b159422.png)

How it look like after i clicked on their name:

![image](https://cloud.githubusercontent.com/assets/175467/22214642/a6f5e228-e198-11e6-82b7-87cb08846c9d.png)

Would be good if it showed the correct state as in the second image immediately.

**Comment by ashfurrow** [comment]
I just tested this in 1.1.2, looks like it was fixed at some point. I'm going to close the issue, but if you're still seeing it please re-open!
