### ISSUE TITLE
Emojos in the new picker don't have tooltips

### ISSUE THREAD

**Issue by MightyPork** [tootsuite/mastodon#5144]
(I understand that's part of the new library we use, but it feels like a regression)

**Comment by nolanlawson** [comment]
It looks like in the `emoji-mart` [demo page](https://missive.github.io/emoji-mart/) that they show the shortcode in a small footer rather than as a tooltip. Perhaps this is how they intend you to do it, but yeah it would be nice if they added an option to do tooltips (`title`) instead.
