### ISSUE TITLE
Do not add trailing slash to URLs

### ISSUE THREAD

**Issue by ThomasLeister** [tootsuite/mastodon#5148]
If I enter ```https://thomas-leister.de``` into my post field and click "TOOT", Mastodon adds a trailing slash at the end of the URL. It would be nicer if there was no trailing slash and the full URL would be shown (incl. ```https://```). 

![bildschirmfoto von 2017-09-29 16-38-57](https://user-images.githubusercontent.com/4207956/31021080-0e84e0d2-a535-11e7-814d-1ff01301e1da.png)
 

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by cooox** [comment]
What version are you using? v1.6.1 introduced a [change to the formatter](https://github.com/tootsuite/mastodon/blob/4c14ff659b8a03c69123ef7b78f4db5c137deeb0/app/lib/formatter.rb#L140). I tested this version with the `encode()` function used and the trailing slashes only appear when I explicitly append it in the Toot.

**Comment by ThomasLeister** [comment]
I'm using 1.6.1. Strange, I've tried again and now the trailing slash is removed. Sooo everything seems to be fine. Sorry for the noise!
