### ISSUE TITLE
Horizontal scroll bar is too tiny

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#5157]
I keep moving my window when I mean to use the horizontal scroll bar, it is very annoying! Having extra columns is still great but I'm half-inclined to remove them because side-scrolling with the tiny scrollbar is annoying. (The vertical scrollbars I can ignore because I have a scroll wheel thing on my mouse. This whole thing is only bugging me now because my laptop is away for repairs, which means I temporarily lose my two-finger trackpad scroll!)

* * * *

- [Y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
Which browser are you using, and where are you seeing the horizontal scroll bar? Can you provide a screenshot?

**Comment by Cassolotl** [comment]
The latest version of Chrome, on a Mac. The horizontal scrollbar is at the bottom of the page, and is almost the same colour as the background.

![screen shot 2017-10-01 at 11 14 22](https://user-images.githubusercontent.com/6607512/31053627-c8d7e988-a699-11e7-87a4-fc1aa8d6dc7a.png)

**Comment by andi1984** [comment]
@Cassolotl @nolanlawson It's related to the value set here https://github.com/tootsuite/mastodon/blob/6e5471947438fc5883e72b8184663564ffadee28/app/javascript/styles/mastodon/reset.scss#L56 as height property. Could be set to a more natural, native value Chrome uses for scrollbars. What do you think?

**Comment by Cassolotl** [comment]
I'm not sure what that would be like but it sounds good, I think?

**Comment by Cassolotl** [comment]
At some point the scrollbars have been made wider, so I'll go ahead and close this. :) Thank you, whoever did that!
