### ISSUE TITLE
Images cannot be viewed using Google Storage

### ISSUE THREAD

**Issue by mikenuko** [tootsuite/mastodon#5165]
Referencing to issue #1110, I deployed a Mastodon instance of which using Google storage.

The following is some lines from my configuration file:

    S3_ENABLED=true
    S3_BUCKET=[domain.test.com]
    AWS_ACCESS_KEY_ID=[Google Storage ID]
    AWS_SECRET_ACCESS_KEY=[Google Storage Key]
    S3_ENDPOINT=https://storage.googleapis.com
    S3_REGION=asia
    S3_PROTOCOL=https
    S3_HOSTNAME=[domain.test.com]

With this configuration file, the Mastodon instance can upload images to the bucket successfully.
But the link in the toot input box is the link to the base domain and previews of the image is not working properly.   

All other images are linked to https://domain.test.com/domain.test.com/system/media_attachments/files/... and all of them cannot be loaded successfully since they are uploaded to https://domain.test.com/system/media_attachments/files/...

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
If you're expecting to serve images from a custom domain, you should set CDN_HOST to the domain you're serving from.

**Comment by mikenuko** [comment]
Thanks for pointing out this configuration item, after changing `S3_HOSTNAME` to `S3_CLOUDFRONT_HOST`, everything resumed normally.
