### ISSUE TITLE
UI touch up/making all images hideable w/o making it feel intrusive

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#517]
often times, at a glance, some images are harder to interpret due to the eye being ever-visible on that image. i would suggest making it visible only when hovering over the image, or, possibly, making it a user option whether it is always visible or visible-on-hover

also, since this is PURELY a UI thing, and not a mastodon style setting, i would suggest making this part of the main UI rather than the off-page views for Other Things as those tend to make the workflow feel weird, and the users could then get a feel for whether they want the eyes ever-visible just by toggling the button and looking around.

thank you for listening

**Comment by blackle** [comment]
I think having something small like this be a user setting might be a bit much (having too many settings can become overwhelming)
show on rollover would be good, I think the main problem here is that there is no guaranteed contrast between the eye and the image. I think giving it a drop shadow or a background would improve this

**Comment by wavebeem** [comment]
On `toot.cat` we have a modification that makes the eye much easier to see:

![image](https://cloud.githubusercontent.com/assets/176815/25061474/66b0e2bc-216c-11e7-8c28-9dec208abd65.png)

How do we feel about something like this?

**Comment by Gargron** [comment]
@wavebeem That's actually not a modification, that's how those icons look to everyone since v1.1.2

**Comment by wavebeem** [comment]
@Gargron Oh, I think I had a misunderstanding with one of the toot.cat repo collaborators. That's fantastic then.
