### ISSUE TITLE
Make external embed loaded on click

### ISSUE THREAD

**Issue by Technowix** [tootsuite/mastodon#5173]
Right now, when you link a youtube video for example, it load immediately the widget when you click on the post, it's a huge privacy issue since Youtube now know where you are / etc.

I would suggest to add a little "preview" of the player, that can be click, and then it would load the Youtube widget with autostart or whatever you can imagine, but at least don't immediately sell the user to google's eyes 👀 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
If anyone wants to do this I would start by, instead of conditionally choosing whether to get rich OEmbed data *or* OpenGraph data, get *both*, so that the thumbnail, title and description can be used in the clickable element that would mount the OEmbed html.
