### ISSUE TITLE
autogenerate keys and secrets

### ISSUE THREAD

**Issue by devkral** [tootsuite/mastodon#5179]
it would be nice if secrets and keys could automatically be generated for a standalone installation.
Here are the commands which fill the keys and secrets in .production.env with a shell script

sed -e "s/\(PAPERCLIP_SECRET=\) *$/\1$(RAILS_ENV=production bundle exec rake secret)/" -i .env.production
sed -e "s/\(SECRET_KEY_BASE=\) *$/\1$(RAILS_ENV=production bundle exec rake secret)/" -i .env.production
sed -e "s/\(OTP_SECRET=\) *$/\1$(RAILS_ENV=production bundle exec rake secret)/" -i .env.production
for i in $(RAILS_ENV=production bundle exec rake mastodon:webpush:generate_vapid_key); do 
    t=($(echo $i | sed -e "s/\([^=]\+\)=\([^=]\+\)/\1 \2/"))
    sed -e "s/\(${t[1]}=\) *$/\1${t[2]}/" -i .env.production
done

**Comment by Gargron** [comment]
Done with mastodon:setup
