### ISSUE TITLE
switching the profile "privacy" from aproval-only to public lets one loose open follower requests

### ISSUE THREAD

**Issue by ng-0** [tootsuite/mastodon#5181]
Basically what fits into the subject line.
When you switch a user profile "privacy" setting from aproval-only to public, you loose the open follower requests.

Idea for solution: Provide "Follower Requests" in "Settings".

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).
- happens on 1.5.1

**Comment by unarist** [comment]
> happens on 1.5.1

It has been fixed at 1.6.1 (649a20ab46eadf9ae3bfc30782ae62379383bd72). Those requests will be accepted automatically when you unlock the account.
