### ISSUE TITLE
local public timeline

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#519]
a good way to encourage instances to be made for certain topics/ideas/themeings etc, is a local-public-timeline, that will show anyone on that instance. this is a great way to encourage the use of instances in a federated manner and also encourages users to find a place they feel comfortable with in more ways than one.

i would suggest the public timeline have a "local" toggle for this feature, or just a seperate timeline for instance

**Comment by TrevInc** [comment]
Worth adding that Mastodon is behind other ostatus implementations in this regard -- I think with the culture differences between mastodon.social and other instances it is apparent how this could be to an instance's detriment. Not mine, but an increasingly common sentiment is "I don't care what other instances are saying"

**Comment by hoodiek** [comment]
also, worth mentioning: customization of the public timeline to include whatever instances you are interested in could easily function as a "filter-by-topic" if, say, gamedev, music, art and other instances crop up. it'd be a good way to support all sorts of users and communities

**Comment by TrevInc** [comment]
would argue that this is a separate feature request from public timeline though I do agree

**Comment by Gargron** [comment]
Implemented!
