### ISSUE TITLE
Are there any venues for designers to contribute to the project?

### ISSUE THREAD

**Issue by thedonquixotic** [tootsuite/mastodon#5190]
The project looks nice, but I feel like there's definetly room for improvement on it's design, or if nothing else it would be good to see some kind of documentation about how design choices were made and stuff. 

Is there anyway for a designer to help contribute to the project at all? (I also do front-end but I'm primarily a designer)

**Comment by ykzts** [comment]
https://discourse.joinmastodon.org/c/development/UX
