### ISSUE TITLE
Please create an API that returns a list of domain blocks that can be set by the instance administrator.

### ISSUE THREAD

**Issue by riku-shiru** [tootsuite/mastodon#5194]
[Issue text goes here].

Is not it better to create an API to find out which instance is domain-blocking the instance to which it belongs?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).
# #

**Comment by tateisu** [comment]
I feel you shall explain the use case.

**Comment by nightpool** [comment]
duplicate in spirit of https://github.com/tootsuite/mastodon/issues/3874
