### ISSUE TITLE
Do not autoplay gifs as profile headers

### ISSUE THREAD

**Issue by Siphonay** [tootsuite/mastodon#5222]

**Comment by deutrino** [comment]
Perhaps this should be tied to the existing autoplay pref(s).

**Comment by Cassolotl** [comment]
I suspect this may be a duplicate of *User backgrounds always animate #4239* ?

**Comment by Siphonay** [comment]
It is. I didn't search for the right wording before searching for similar issues, my apologies

**Comment by Siphonay** [comment]
I guess I should
