### ISSUE TITLE
Filter out same email using appending characters

### ISSUE THREAD

**Issue by Kjwon15** [tootsuite/mastodon#5233]
Many Email provider gives appending character for email addresses.
eg) Gmail has `+` character for this:
`abc@gmail.com`
`abc+1@gmail.com`
`abc+something`@gmail.com
above email addresses are all same email.

The problem is abusing.
Some users are bulling or harassing other users. When they are blocked from victim, than create new account using same email, then do that again.

So I propose to filter out same emails to prevent abusing.

To prevent this, There are some regex or something to get cleaned email address and save them next to email field.
When user wants to join, Check cleaned email field to prevent join with same email address.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). (But it is not a bug, it is enhancement)

**Comment by Cassolotl** [comment]
Argh no, I find this trick really useful for email filters! But I do understand the need to reduce harassment. So I'm curious to know whether it would work, or whether the harassers would just start making new email addresses in order to make new accounts.

**Comment by nightpool** [comment]
Maybe we should check emails against just current suspended users?

**Comment by nightpool** [comment]
@Cassolotl see #5109 for the latter case

**Comment by Cassolotl** [comment]
That sounds alright. :) It’d be easy enough to harass someone by making an account on like 500 instances with one email address but it’s still *more* work and that’s a good idea!

**Comment by tateisu** [comment]
Please don't add this function( filtering '+') as default ...

**Comment by Gargron** [comment]
1. It's not guaranteed that + addresses go to the same inbox (afaik), depends on the server
2. There are legitimate uses for multiple accounts done this way
