### ISSUE TITLE
Robots.txt should be blank by default

### ISSUE THREAD

**Issue by hook54321a** [tootsuite/mastodon#5257]
The current contents of the default robots.txt file are inaccurate, you can't ban a bot from accessing your site with robots.txt, all it does is politely asks it not to do so, which the bot could then respectfully decline.

I don't think it's necessary to make it so easy that all someone needs to do is uncomment a couple of lines, doing so could potentially prevent historically significant information from being crawled by the wayback machine, which is fine if the owner of an instance wants to do that, but they should understand the ramifications of it first.

**Comment by nolanlawson** [comment]
I dunno, I for one think it's nice for inexperienced admins who might not know what `robots.txt` is to put an explanation in there. OTOH yeah maybe "ban" isn't the most accurate word.

**Comment by Gargron** [comment]
This is a file included with Rails by default, it does nothing, I see no reason to change anything.
