### ISSUE TITLE
"GET /api/v1/blocks" Paging parameter not working

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#5268]
reproduced on 1.6.1

max_id not working.
- Blocks 90 users 
- GET /api/v1/blocks for first page
- GET /api/v1/blocks with max_id for second  page
- both returns same contents.

since_id not workling.
- GET /api/v1/blocks for first page
- blocks new user
- GET /api/v1/blocks with since_id for "new first" page
- got 0 entries.

* * * *

**Comment by Gargron** [comment]
Could it be a regression from #3167? @akihikodaki

**Comment by akihikodaki** [comment]
It is certainly a bug of the query. Somehow ActiveRecord inserts `1=0` in where clause.

**Comment by akihikodaki** [comment]
That was not a problem. I'm still investigating the issue.
