### ISSUE TITLE
refresh automatically the page when commented 

### ISSUE THREAD

**Issue by Bschalck** [tootsuite/mastodon#5286]
Hy ,

It should be nice to view our comment on a toot immediately.
When you comment a toot, you have to refresh the page to see it .

**Comment by Cassolotl** [comment]
I think this is fixed with 2.0.0, which hasn't quite been released yet.

At least, cybre.space is on a pre-release of 2.0.0 and I'm seeing my own replies to other people appear in the column on the far right when I post, *without* having to reload.
