### ISSUE TITLE
Time format in toot

### ISSUE THREAD

**Issue by JeanGauthier** [tootsuite/mastodon#5299]
Hello you all.
I'm experimenting an issue with the time format.
Under the toot the date is in English not in Occitan.
In **authorized_applications** the time format would almost be good to be under the toot, instead of 01/02/03 it should be 1/2/3, and maybe adding a dot after the month's name abbreviation.
I really don't know what to change so it shows correctly :S 
In toots
![Image](http://zupimages.net/up/17/41/gxqw.png)
In Settings / Authorized Applications
![Image](http://zupimages.net/up/17/41/3z0b.png)
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by danielcompton** [comment]
Similarly, the date on a toot in the timeline more than a few days old shows in US time format (mm/d). It would be handy to have a localised setting for this.

<img width="62" alt="screenshot of safari 5-12-17 8-00-03 pm" src="https://user-images.githubusercontent.com/811954/33594011-03fc559a-d9f7-11e7-8d43-6bd9afd41fed.png">

**Comment by ykzts** [comment]
This is not a issue of Mastodon.

Mastodon uses the [Intl API](http://www.ecma-international.org/ecma-402/1.0/#sec-8) to display the time. The Intl API is embedded in a web browser, not from Mastodon.

Many web browsers use [CLDR](http://cldr.unicode.org/) to obtain localization information. But Occitan is not included in CLDR. Unfortunately we can not do anything.

Please report it in [CLDR's Trac](http://unicode.org/cldr/trac].
