### ISSUE TITLE
Remote follow of loadaverage.org failed

### ISSUE THREAD

**Issue by syui** [tootsuite/mastodon#5307]
mastodon version : 2.0.0

Remote follow of loadaverage.org failed.

`https://loadaverage.org/main/ostatus/nickname/$user`

Do you know the cause?

Running from `https://example.com/web/accounts/$n` seems to succeed.

However, it will not be added to the follower of the other party (loadaverage).

success:

- LOCAL_DOMAIN=xxx.herokuapp.com

- LOCAL_HTTPS=false

**Comment by syui** [comment]
button click : https://loadaverage.org, user, `Subscribe` 

> Signed in as:
> 
> @syui@mastodon.social
> 
> Unfortunately, there was an error looking up the remote account

![](https://raw.githubusercontent.com/mba-hack/images/master/mastodon_follow_loadaverage.png)

**Comment by regagain** [comment]
I am getting this error on many GNU Social instances.
I am curious as to why it was closed, @syui, did you find a way to circumvent this issue?

**Comment by sorpaas** [comment]
Same error. Also wonder how @syui solved this issue?
