### ISSUE TITLE
Emoji pop-up falls off the end of the page and I can't get to it

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#5313]
cybre.space just updated to v2.0.0rc1, and I use the default Mastodon theme.

![screen shot 2017-10-11 at 09 25 49](https://user-images.githubusercontent.com/6607512/31429554-458cd5c8-ae66-11e7-92b7-ef813ee1c933.png)

You can see how the scrollbar on the emoji box is out of view - it's past the bottom of the page, and there is no way to scroll the first ("new toot") column to show the whole emoji panel like there was in the last version.

I use the latest version of Chrome on a Mac running 10.12.6.

* * * *

- [Y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by JohnD28** [comment]
It's the same problem with others pop-up, likes confidentillity menu : 

![capture du 2017-10-11 11-28-35](https://user-images.githubusercontent.com/32609514/31432648-5bb3b55e-ae77-11e7-976a-1fef3af57ae0.png)

Here on Firefox 56.

**Comment by Gargron** [comment]
Question, how did it work before?

**Comment by JohnD28** [comment]
Before, you could scroll with the mouse to bring up the rest of the pop-up.

**Comment by Cassolotl** [comment]
Yes, the column on the left would become longer so you could scroll down. Then when the pop-up disappeared the column would spring back to shorter again.

**Comment by Cassolotl** [comment]
I think it might be connected to the way menus drop off the bottom of the screen too, and when I scroll the menu stays where it is while the toot moves upwards:

![screen shot 2017-10-12 at 19 42 35](https://user-images.githubusercontent.com/6607512/31513240-a6d80968-af85-11e7-980e-536d5e25e095.png)

**Comment by Cassolotl** [comment]
Some menu stuff still a bit not working, see #5466!

**Comment by nolanlawson** [comment]
This is technically fixed because you can now scroll it into view, although indeed #5466 is valid.
