### ISSUE TITLE
Incomplete hashtag timelines

### ISSUE THREAD

**Issue by renatolond** [tootsuite/mastodon#5319]
Hi!
I'm on 1.6.1 and I'm seeing a weird behavior around hashtags. A lot of people I follow were posting about the #mastodonmemory hashtag. I can see their posts on my timeline, I can see their posts on the local timelines of their instances, and I can even see their post son the tag search results on their instances, but I cannot see their posts on the tag search results on my instance. I'm not quite sure on how to debug it, the tag search results are not entirely empty, it has some results including from some instances that are not mine.
The #mastodonmemory is just an example, it happens with basically every hashtag I see on my timeline.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by renatolond** [comment]
I'm not seeing the issue on 2.0 anymore. I consider that this can be closed.

**Comment by Cassolotl** [comment]
@renatolond You are probably the best person to close it!

**Comment by renatolond** [comment]
Good reminder, Cas! :)
