### ISSUE TITLE
Multiple notifications columns

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#5327]
I'd like to be able to have multiple pinned notifications columns - one for replies, one for boosts, one for faves, one for DMs. On my private account I'd like to have a pinnable column for follow requests too.

Thanks! :)

* * * *

- [Y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by davedelong** [comment]
+1 I would love this as well

**Comment by pawelngei** [comment]
Handled in #9399 with filters.

**Comment by Cassolotl** [comment]
The new notification column meets my needs so I will go ahead and close this. @ me if you want this reopened. :)

![Screenshot 2019-11-22 at 08 29 23](https://user-images.githubusercontent.com/6607512/69410102-36e08180-0d02-11ea-9a69-ce24072d9f3f.png)

**Comment by chylex** [comment]
Is there no way to add another notifications column then? I would like to use my screen real estate to have different types of notifications in separate columns, right now half of my screen width is empty and having to click through tabs to see each category isn't great.

**Comment by cameronneylon** [comment]
I'd be a +1 on this. It would be helpful, particularly with lots of new followers at the moment to have one column for follow requests and related and one for mentions/boosts/favourites. Ability to add another notifications column in advanced view would satisfy my use case.
