### ISSUE TITLE
Add a way to auto-fill the textarea for a toot

### ISSUE THREAD

**Issue by schiessle** [tootsuite/mastodon#5338]
I would like to add a "Share on Mastodon" button on my Blog. Therefore I need a way to redirect the user to their Mastodon instance and pre fill the text area, e.g. with a link to my blog and the title.

For example on GNU Social this is possible with following URL:

````
https://io.schiessle.org/notice/new?status_textarea=TheMessageIWantToPlaceInTheTextArea
````

On Diaspora I can do:

````
https://diasp.eu/bookmarklet?url=linkToMyBlog&title=BlogTitle
````

Is something similiar possible with Mastodon? If not, could this be added?

I think having the ability to add "Share on Mastodon" buttons to homepages, blogs, etc. would be a nice marketing boom for Mastodon.

**Comment by Gargron** [comment]
`web+mastodon://share?text=TheMessageIWantToPlaceInTheTextArea`

**Comment by schiessle** [comment]
Great, this was exactly what I was looking for!
