### ISSUE TITLE
Followers-only threads where you don't follow all shouldn't show in TL

### ISSUE THREAD

**Issue by MightyPork** [tootsuite/mastodon#5345]
This is similar to https://github.com/tootsuite/mastodon/issues/4279, but when the thread involves followers-only statuses, clicking through or opening it in the static view won't solve the problem.

When the user is also locked, you have no chance of reading the thread (without waiting a couple hours/days for them to notice the request, and that is, if they want you to follow), so it might as well not show the thread at all.

Imo it'd be sufficient to apply this check to the thread root, not all chained toots. Not seeing bits of the convo is less of a problem than not seeing the original post.

**Comment by Gargron** [comment]
It is possible to know who a toot replies to, even if it's a self-reply (we just carry on data from the latest non-self reply). But it's not possible to know further up the chain. Especially considering conversations on mastodon can thread and branch off a lot. I do not currently see a way to implement what you are asking for. If there is a solution that does not ruin performance, please reopen.
