### ISSUE TITLE
can't recover pw, can't relogin, can't fav/boost

### ISSUE THREAD

**Issue by PaulFree14** [tootsuite/mastodon#5348]
Since over 2 month I can't login at mastodon.social. 
I neither can't reset the passwort. I just doesn't resieve any e-mail. 
What I still can is using ms via an app (subwaytooter) from where I'm loged in since longer. 
Since the last update of ms I now also can't boost or fav any new toots. 
I have contacted a couple of times admins of ms, but I've been ignored. 
Maybe the reason was because my message got lost between all the others, maybe not. 

1 month ago I have also opend this issue:
https://github.com/tootsuite/mastodon/issues/4793

I know all this is done by volunteers, and that's also why I like it much, but now I can't really use it any more, and this I dislike ;-)

**Comment by PaulFree14** [comment]
if this isn't the right space for such issues, I'm happy to directed where I can adress is. 
...via mastodon it got ignored

**Comment by PaulFree14** [comment]
...ah, and my account is this one:
https://mastodon.social/@paulfree14

**Comment by wxcafe** [comment]
Alright I'm closing the older issue and paging @Gargron

**Comment by PaulFree14** [comment]
Is there anyone else I could contact to solve that issue?

**Comment by Gargron** [comment]
I looked at your account and it looks normal. Did you lose control of your e-mail address or what?

**Comment by PaulFree14** [comment]
thx gargron. :)
No I have still acsess to my e-mail. 
I have changed my e-mail adress and passwort. 
As I remember that was somewhen during an update phase. 
Just after I couldn't login from a not already loged in maschine. 
the pw recovery e-mail also doesn't reach me. 

Do you see if the pw recovery mail got send out?
Have tried it multible times.

**Comment by PaulFree14** [comment]
...ehm, still me. 
I'm a bit sad how this got handled. If there is no intererst to solve the issue that's one point, but just leaving me in the air for nearly 3 month isn't so cool. 

I don't lost the passwort. 
I can't login (beside subwaytooter I'm loged in since long I can't use it) 
I can't revover the passwort 
I can't delete my account (I actually don't want to delete it but I should have the right to choose this by myself)

I don't lost accsess to my e-mail!

On my side I can't do anything else then hoping to get a respond. 
I also don't want to spam, but I feel constantly ignored about it. And all I want is just to able to use it as everyone else. 

Possible solution:
- Thought admin could check if the e-mail bound to my account is correct (I have send Gargron via matrix a message containing my e-mail adress, in case there went something) 
- Recover the passwort for my account through the admin desk
- check if recovery mail gets send out

and me then: 
:-)

**Comment by PaulFree14** [comment]
cobaldvelfet solved the issue. 
thx. :)
