### ISSUE TITLE
Renaming/removing themes causes 500 crash

### ISSUE THREAD

**Issue by nolanlawson** [tootsuite/mastodon#5352]
Steps to repro:

1. Change `config/themes.yml` to:

```yml
default: styles/application.scss
foo: styles/foobar.scss
```

2. As a user, choose the `foo` theme
3. Change `config/themes.yml` to:

```yml
default: styles/application.scss
bar: styles/foobar.scss
```

4. Result: user gets a 500 error when trying to open the app:

![out](https://user-images.githubusercontent.com/283842/31504624-b696bac4-af27-11e7-93d7-874f739200f0.png)

I think if a theme is not found, then it should just fall back to the default theme. Unfortunately I don't understand the Ruby code enough to make this fix.

Use case: admins may want to tinker with the names of themes, or to rename "default" to "Mastodon," etc.

commit: 8e9911962d71e5f010bf5e8974dbe9ab59220185

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
Hm it seems there's another repro: create a theme with a space in the name, and it crashes if you choose that theme…

![screenshot 2017-10-12 19 33 30](https://user-images.githubusercontent.com/283842/31527745-3fe702aa-af84-11e7-8131-7f1d2691b8e3.png)

**Comment by nolanlawson** [comment]
Either that or this is caused by the é character, not sure.

**Comment by nolanlawson** [comment]
OK so it seems you need to have a `default` style, which will magically be called `Mastodon` in the UI. And if you don't have it, then you get the kinds of errors I'm seeing.

**Comment by nolanlawson** [comment]
This bug is totally wrong. I'll open a fresh one.

**Comment by Mrs-Feathers** [comment]
i'm having this same issue but not as a "default" theme needed... once a theme is added to the theme.yml and the instance is rebooted, even if its not selected, you cannot rename a theme... i've created a theme "furry_refuge_lightt" and when removing the extra t i had installed it with, it will cause ALL users connecting to have an error 500 unless i put the t back and reboot. how can i fix this?

**Comment by Mrs-Feathers** [comment]
the site's default theme and the theme i've got as my personal theme i've made sure are the default theme and NOT the ones i'm changing. so, reguardless of whether you have the theme that's being renamed enabled, it WILL cause error 500. but, i would very much like to fix my spelling error.
