### ISSUE TITLE
Emoji import by packs

### ISSUE THREAD

**Issue by wxcafe** [tootsuite/mastodon#5353]
It would be great to have a feature where admins can import "packs" of emojis. These could be a zip file containing pngs, and each would be assigned a shortcode corresponding to its name. (so for example a zip containing `[a.png, b.png, c.png]` would result in `:a:`, `:b:`, `:c:` (and would error out cause :a: and :b: already exist))

That would allow admins to share packs of emojis (Mutant Standard, for example) easily

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by halcy** [comment]
Such a feature would be very useful and would be even more useful if if was possible to import packs into their own category for the picker, i.e. have a "Mutant Standard" custom emoji tab in the picker.

**Comment by wxcafe** [comment]
👍👍👍

Clément 'wxcafé' Hertling

**Comment by Gargron** [comment]
Has this been resolved by `tootctl emoji import ARCHIVE`?
