### ISSUE TITLE
Stale content when webapp is backgrounded

### ISSUE THREAD

**Issue by nolanlawson** [tootsuite/mastodon#5354]
On Firefox for desktop:

1. Pin the tab
2. Toot something
3. Close the browser
4. Reopen the browser
5. New toot is not shown in home timeline until you refresh

Or Firefox/Chrome for Android:

1. Don't use the app for awhile
2. Open it up
3. Stale content is shown until you refresh

My suspicion is that adding page visibility listeners to wake up the websocket connection when the page is foregrounded will fix this, but it's tricky to harmonize across desktop/mobile because the events are different, and browsers have different strategies for "nerfing" background tabs (e.g. throttling timers).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Has this stopped happening in Chrome?

**Comment by tommyschnabel** [comment]
@Gargron no it hasn't

**Comment by Gargron** [comment]
I believe this was a cache headers issue on API responses so it should be gone now
