### ISSUE TITLE
CWs induce a very large gap at the start of a post

### ISSUE THREAD

**Issue by wxcafe** [tootsuite/mastodon#5356]
When one makes a toot with a CW on mastodon 2.0rc{1,2}, the CW adds a linebreak at the start of the message:

![screenshot from 2017-10-12 18-27-23](https://user-images.githubusercontent.com/3009327/31507470-11d12f52-af7b-11e7-9bdd-f638dca2a9b3.png)
![screenshot from 2017-10-12 18-27-39](https://user-images.githubusercontent.com/3009327/31507475-14a794f0-af7b-11e7-9a92-48b7c92b2130.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by MightyPork** [comment]
i can't reproduce this bug (vanilla rc2)
there is some gap from CSS, but no newline

![screenshot_20171012_214129](https://user-images.githubusercontent.com/2041118/31515651-30b26fb0-af96-11e7-8065-761324d0a125.png)

**Comment by wxcafe** [comment]
Dang, you're right, it's just a really large gap!

Still, it's a *really* large gap

**Comment by Sylvhem** [comment]
I can reproduce this bug both on https://witches.town/ and https://dev.glitch.social/. I use Firefox 52.4 on Debian 9.

![witches](https://user-images.githubusercontent.com/5222316/31538815-05eb9e16-b007-11e7-83da-fdf48ba79e0d.png)
![dev glitch](https://user-images.githubusercontent.com/5222316/31538821-09a34a9a-b007-11e7-8080-e08eaf4566e9.png)

**Comment by MightyPork** [comment]
for record, I tested it in chrome 61

**Comment by nolanlawson** [comment]
Is this a UI issue or a backend issue? Is the content of the toot actually different, or just the way it's displayed in the UI?

**Comment by nightpool** [comment]
I see a normal sized gap on RC1 
![image](https://user-images.githubusercontent.com/233815/31676371-6aa8f098-b335-11e7-99e3-5e113bc54d4a.png)

**Comment by wxcafe** [comment]
so frontend
