### ISSUE TITLE
Prevent creating emojis with an existing name

### ISSUE THREAD

**Issue by wxcafe** [tootsuite/mastodon#5358]
So I was able to create an emoji named "link"... when the default set already has one named "link".  The default one is kept when I toot, so adding the custom emoji obviously didn't work, but it still said that it did (and didn't tell me there already was an emoji with that name...)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tkbky** [comment]
I have taken a look at the emoji related implementation. So we're using [emoji-mart](https://github.com/missive/emoji-mart) on the as the emoji picker which relies on [emoji-data](https://github.com/iamcal/emoji-data) for the emoji data source. So, I guess the solution could be adding a validation in the `CustomEmoji` model. We might need to install the [ruby port for emoji-data](https://github.com/mroth/emoji_data.rb) to obtain the emoji data source for the validation. A quick implementation is as follow:

Gemfile
```ruby
gem 'emoji_data'
```

app/models/custom_emoji.rb
```ruby
require 'emoji_data'

class CustomEmoji < ApplicationRecord
...
validates :shortcode, ... , exclusion: { in: EmojiData.all.map(&:short_name) }
...
end
```

There is something to take note though, that ruby port of emoji data is not actively maintained, and the emoji-data is manually vendored as mentioned [here](https://github.com/mroth/emoji_data.rb/blob/master/vendor/emoji-data/README.md), so we might need to fork and make sure the vendor library is up-to-date.

Additionally, we need to find a way to rename custom emojis with that has the same name with one in emoji data.

@Gargron WDYT?

**Comment by nolanlawson** [comment]
You can also import the emoji data directly from

```
./node_modules/emoji-mart/dist/data/data.js
```

Unfortunately this isn't a JSON file though.

**Comment by Gargron** [comment]
Loading emoji data into Ruby will increase RAM required for every Ruby process by a few MB. I don't think it's worth it.

When you write the shortcode, the webapp suggests to replace it with a unicode character. Obviously unicode will remain unicode. If you do not choose to replace what you typed with a unicode, it will remain shortcode text, and therefore it might (pretty sure) get converted to the custom emoji.

It's a case where admins should know what they are doing imo.
