### ISSUE TITLE
"default" theme with name "Mastodon" is required

### ISSUE THREAD

**Issue by nolanlawson** [tootsuite/mastodon#5364]
it seems that `config/themes.yml` requires a theme called `default` which is called "Mastodon" in the UI. If you don't include a `default` theme, then a user can end up unable to log in:

![screenshot 2017-10-12 08 29 20](https://user-images.githubusercontent.com/283842/31528531-b1efd206-af88-11e7-9e71-8f637883d62b.png)

This is a bit confusing for e.g. instances like toot.cafe, where I would like the "Toot Café" theme to be the default, and for the "Mastodon" theme to be another option. Seems the only workaround currently is to name the custom theme `default` and to have it show up in the UI as "Mastodon."

/cc @chronister Not sure if you found a better solution.

(follow up to #5352)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
Hm I think I see what you're supposed to do: modify `locales/en.yml` to change the name from "Mastodon" (https://github.com/cybrespace/mastodon/commit/10aee9b6b389b4a92ff30a3b07cd554a42c0858b#diff-37c9b835927e3c363588f172de9bb6fa). Maybe this just needs to be documented?

**Comment by nolanlawson** [comment]
OK done, closing issue. Sorry for the noise: https://github.com/tootsuite/documentation/pull/421

**Comment by Chronister** [comment]
whoops yeah, i meant to write a PR to go in the documentation with this the day the PR was merged but my time got away from me, thanks for filling the gap!
