### ISSUE TITLE
No protocol handler was valid for the URL /api/v1/streaming/public

### ISSUE THREAD

**Issue by Bloufit** [tootsuite/mastodon#5385]
**Hi everyone !**

For almost a week, I discovered that it is impossible to access _/api/v1/streaming/public_, we get an error 500, on the instance, while everything else works normally. 

In Apache errors logs (Yes, I use Apache on Ubuntu 16.04), I have the folowing error, 2.000 times :
`AH01144: No protocol handler was valid for the URL /api/v1/streaming/public. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.`

However, the following mods are installed correctly and loaded : Proxy, Proxy_Balancer, Proxy_WSTunnel, Proxy_Http and Headers.

I asked to several other instance admins using Apache if they have the same problem, no one has.

The funny part is that I have this in my Apache config :
> ProxyPass "/api/v1/streaming" "ws://localhost:4000"
> ProxyPassReverse "/api/v1/streaming" "ws://localhost:4000"
> ProxyPass "/" "http://localhost:3000/"
> ProxyPassReverse "/" "http://localhost:3000/"

And the ProxyPass rule to the Web service works... ^^

Is anyone have a idea (Other than installing Proxy mods) ?

**Thank you and have a nice week end !**

**PS :** Sorry if my English is a bit wrong. ^^

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
Apache might not support the ws:// protocol you've specified there. Do you
know what config the other admins are using?

**Comment by Bloufit** [comment]
Eyup, they use exaclty the same thing (But with _127.0.0.1_, but I tested and it doesn't solve the problem) :
>ProxyPass "/api/v1/streaming" "ws://127.0.0.1:4000"
>roxyPassReverse "/api/v1/streaming" "ws://127.0.0.1:4000"

Or the default configuration as seen as in Mastodon's documentation.

**Comment by Bloufit** [comment]
I set debug mode on Apache, so I have some details : 

> [ssl:debug] [pid 32500] ssl_engine_kernel.c(354): [client ##.##.##.##:43480] AH02034: Initial (No.1) HTTPS request received for child 1 (server equestria.social:443)
> [authz_core:debug] [pid 32500] mod_authz_core.c(835): [client ##.##.##.##:43480] AH01628: authorization result: granted (no directives)
> [proxy:debug] [pid 32500] mod_proxy.c(1160): [client ##.##.##.##:43480] AH01143: Running scheme ws handler (attempt 0)
> [proxy_ajp:debug] [pid 32500] mod_proxy_ajp.c(738): [client ##.##.##.##:43480] AH00894: declining URL ws://127.0.0.1:4000/user
> [proxy_fcgi:debug] [pid 32500] mod_proxy_fcgi.c(879): [client ##.##.##.##:43480] AH01076: url: ws://127.0.0.1:4000/user proxyname: (null) proxyport: 0
> [proxy_fcgi:debug] [pid 32500] mod_proxy_fcgi.c(882): [client ##.##.##.##:43480] AH01077: declining URL ws://127.0.0.1:4000/user
> [proxy_http:debug] [pid 32500] mod_proxy_http.c(1943): [client ##.##.##.##:43480] AH01113: HTTP: declining URL ws://127.0.0.1:4000/user
> [proxy_wstunnel:debug] [pid 32500] mod_proxy_wstunnel.c(341): [client ##.##.##.##:43480] AH02900: declining URL ws://127.0.0.1:4000/user  (not WebSocket)
> [proxy:warn] [pid 32500] [client ##.##.##.##:43480] AH01144: No protocol handler was valid for the URL /api/v1/streaming/user. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.

**Comment by Gargron** [comment]
If you can switch to Nginx you'll have a much easier time - I've never used Apache and do not know anything about these mods.

**Comment by Bloufit** [comment]
Okay, I'll test with Nginx. ^^

BTW : I changed the port number on the ProxyPass, and I have the exact same error. I'll confirmed with Nginx if it comes from Apache or from something else.

**Comment by Bloufit** [comment]
So : I installed Nginx, and I have the same problem, here is the error : 

> [error] 6029#6029: *1 connect() failed (111: Connection refused) while connecting to upstream, client: ##.##.##.##, server: equestria.social, request: "GET /api/v1/streaming/user HTTP/2.0", upstream: "http://127.0.0.1:4000/api/v1/streaming/user", host: "equestria.social"
> [error] 6029#6029: *44 connect() failed (111: Connection refused) while connecting to upstream, client: ##.##.##.##, server: equestria.social, request: "GET /api/v1/streaming/?access_token=hanshotfirst&stream=user HTTP/1.1", upstream: "http://127.0.0.1:4000/api/v1/streaming/?access_token=hanshotfirst&stream=user", host: "equestria.social"
> [error] 6029#6029: *52 connect() failed (111: Connection refused) while connecting to upstream, client: ##.##.##.##, server: equestria.social, request: "GET /api/v1/streaming/?access_token=hanshotfirst&stream=public HTTP/1.1", upstream: "http://127.0.0.1:4000/api/v1/streaming/?access_token=hanshotfirst&stream=public", host: "equestria.social"

(I "censored" the IP adresses and the keys. ^^ )

**Comment by Bloufit** [comment]
Even with Nginx, I have the problem, but I think it's a different problem from the one I described with Apache.
Because I solved the Apache problem : In the Nginx configuration, you use HTTP for the streaming service's proxy, but with Apache, you use WebSocket (In you're documentation).
And I don't know why when I changed the Apache config from "ws://" to "http://", it works ! :D 
IE : 
> ProxyPass /api/v1/streaming/ http://localhost:4000/
> ProxyPassReverse /api/v1/streaming/ http://localhost:4000/

Maybe it could be great to say that this solution exists in Mastodon's documentation ("Alternatives.md
"). ^^

BTW, you should add...
> <Files "sw.js">
>     Header set Cache-Control "public, max-age=0"
> </Files>
... because of 1.5.0, and remove...
> ProxyPass /manifest.json !
because we get an error 404.

Thank you very much for the help and have a nice day ! :)
