### ISSUE TITLE
2.0.0rc2 - Cannot change toot visibility when replying to a long toot

### ISSUE THREAD

**Issue by Aldarone** [tootsuite/mastodon#5388]
In case the users are replying to a long toot, the visibility dropdown overflows at the bottom of the screen with no possibility to scroll.

Tested Browsers : 

- nw.js
- Chromium stable
- Firefox nightly

![image](https://user-images.githubusercontent.com/2682011/31572255-d163e932-b0a1-11e7-965c-67d8d3508be1.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by JohnD28** [comment]
I think that's the problem already reported here : #5313 

https://github.com/tootsuite/mastodon/issues/5313

**Comment by Aldarone** [comment]
You're right, sorry 😅
