### ISSUE TITLE
Sidekiq -- Push Queue preventing outbound communication

### ISSUE THREAD

**Issue by C1T7** [tootsuite/mastodon#5392]
Admin: vcity.network

I am currently on a 1.6.1 instance on a 4 CPU server with 12GB of RAM bandwidth 100 Mbit/s

Load average on server is 0.23 with 3.05G/11.7G used.

Issue began on 13 October around Noon Eastern.

I am currently the only user on my instance.

Outbound toots are intermittent, with certain instances receiving messages while others do not.

Currently messages are taking more than 15 minutes to arrive to users on instances who are verifying arrival times.

I had sidekiq set to 5 workers in first screen shot.

I set it to 50 workers in second screen shot.

At this time communication and follows with certain instances are either not going through or taking an extremely long time: (follow attempts are timing out)

toot-lab.reclaim.technology 2.0.0rc2, c0dem0mhasthephatphorx
glitch.social 2.0.0rc2
cybre.space 2.0.0rc2-cybre
witches.town 2.0.0rc2
instance.business 1.6.1

As send race using accounts on instance.business and from vCity to the toot-lab showed a 16 minute difference in arrival time with a clear queue and 50 sidekiq workers.

![image](https://user-images.githubusercontent.com/28231086/31576507-2ef353f8-b0ca-11e7-9edf-0f6057a76732.png)

![image](https://user-images.githubusercontent.com/28231086/31576710-246b7862-b0ce-11e7-9f81-202c76e0ec02.png)

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
It looks like you're seeing lots of spikey failures. Do you know what could be causing these? When you sent me the screenshot yesterday nothing looked out of the ordinary, but maybe there's different data now?

**Comment by nightpool** [comment]
Could you maybe be saturating the amount of Postgres connections with your current worker limit? What's your max_connections config setting?

**Comment by C1T7** [comment]
The issue and solution was with my server and domain registrar and not Mastodon.

I had to create a 2 glue records with Hover directing them to the ipv6 resolver of my server host.

Once the glue records propagated, I was able to test against accounts for ability to follow on:

toot-lab
witches.town
cybre.space
instance.business
dev.glitch.social

This ticket can be closed


![image](https://user-images.githubusercontent.com/28231086/31580113-b1284a1e-b114-11e7-8b89-263dff3ca0b2.png)
