### ISSUE TITLE
Home feed regeneration yields empty timeline sometimes

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#5398]
Some people who came back after >14 days of inactivity have reported seeing an empty timeline.

I have tried reproducing whether regeneration works (and added more tests), but as far as I can see, yes, regeneration happens. So the cause must be that it yields empty results?

My guess is that because it does last-mile filtering, it's possible that all results from the database are filtered out. For example, if all returned results within the limit (that happens to be just 100 items) are:

- replies to people the user is not following
- mention people the user has blocked
- reblogs of people the user has blocked
- etc

It's not impossible that this happens within just 100 items. My ideas for solving this are:

- Increase the limit from 100 to more (400?). This would *reduce* the problem, but not guarantee that it never occurs
- Accept that regenerated feeds should look different to fresh feeds, e.g. by either completely excluding all replies, or not filtering them out
- Move last-mile filtering to the SQL query, making the query slower but more accurate in returning the 100 items
- Instead of fetching 100 items from all accounts the user follows in total, split the worker into one query per account, e.g. 100 from alice, 100 from bob, which would reduce likelihood of all items getting filtered out. Splitting it into multiple workers would parallelize the process, making is potentially faster, though it could also have a negative impact on Sidekiq throughput for users who follow a lot of people

**Comment by nightpool** [comment]
I really don't think that filtering is the correct diagnosis here. Out of 100 posts by people you follow, I would be surprised if as many as 3/4 was replies to people you don't follow—and that's still 25 posts. Can we get some instrumentation here or track down someone who had this happen to them? 

Also, *is* this a problem with the regeneration worker? The regeneration worker happens as normal, but it doesn't do anything for you the very first time you log in—that's what that status DB query is supposed to do.

**Comment by Gargron** [comment]
The affected people reported that even after many hours the home feed was still empty, so it can't be just the database query fallback. Fwiw, the database query is the same for live fallback and regeneration 

And i do believe that regeneration worker happens. I also know that it works to some degree, if you simulate your absence in development environment

**Comment by nolanlawson** [comment]
When this happened to my wife, running `mastodon:feeds:build` immediately fixed it. Dunno if that helps…

**Comment by Gargron** [comment]
That rake task runs the regeneration worker. But it's possible that Nolan's problem was related to having previously moved the server. I don't know.

**Comment by nightpool** [comment]
Okay, I think it's easy to say that the regeneration worker should be maximally correct—we store an offset in the arguments, and at the end of executing the worker we increment the offset and schedule the next batch as a new sidekiq job until we've done ~14ish days of statuses.

We should try and diagnose what's going on with the page-load query though too.....

**Comment by Gargron** [comment]
Oh boy. Guess what the `order(account_id: :desc)` means

https://github.com/tootsuite/mastodon/blob/3e2f79394891bae1a0afbf8899855a0b10ef9e15/app/lib/feed_manager.rb#L103-L105

It means we get 100 items from *one single account* since most accounts have > 100 statuses.
