### ISSUE TITLE
Show join date in profile or remove it from metadata

### ISSUE THREAD

**Issue by MightyPork** [tootsuite/mastodon#5399]
I've noticed Twidere knows people's join date, while it's nowhere to be found in the web interface.

It's useful for calculating toot frequency and checking account age - useful but not indispensable.

It's additional information not everyone may want to share and they'll falsely believe it's not public from it's omission in the profile pages. Imo it should either be available on the web interface as well, or removed from both places.

**Comment by Cassolotl** [comment]
I think that kind of info is pretty cool, so I vote "put it on profiles".

**Comment by deutrino** [comment]
There's a benefit to displaying this in that it makes impersonation and purpose-specific throwaway accounts more obvious.

**Comment by charlag** [comment]
On the contrary, it can prevent people from migrating to another instance and losing their date. I think it should be possible to see that but maybe it shouldn't be super noticeable (basically the same thing we don't show counters on toots much - info may be inaccurate)

**Comment by enterprisey** [comment]
Halfway done, by the way - this has started being shown in the homepages at some point (https://mastodon.technology/@danielhglus) but not in profile columns in the web client.

**Comment by t1noo7** [comment]
smells like shoe polish around here >:)
