### ISSUE TITLE
Spoiler Content can be seen within a desktop's notification

### ISSUE THREAD

**Issue by e-Glyde** [tootsuite/mastodon#540]
The content/hidden part of a spoiler warning toot can be seen when a notification appears on desktop.

**Comment by Gargron** [comment]
Since you can only get notifications for your own content, is this actually a problem?

**Comment by blackle** [comment]
it also shows when you get a mention that's a spoiler

**Comment by Gargron** [comment]
I've made it so desktop notifs show spoiler text when it's available instead of the content.
