### ISSUE TITLE
Back button does not dismiss modal

### ISSUE THREAD

**Issue by stefanhayden** [tootsuite/mastodon#5407]
Pressing the back button should dismiss the modal. This is less of a deal in the web browser but feels especially bad when in phone app mode and press the android back button. Instead the image remains rendered and the content behind it changes with the url.

My guess is that the app just uses history state and since the modal does not get it's own history state entry the modal state is never cleared.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I suspect this is a duplicate of #3060 - what d'you reckon?

**Comment by stefanhayden** [comment]
Yup! Thanks!
