### ISSUE TITLE
Long posts blocks privacy setting options

### ISSUE THREAD

**Issue by ragingscholar** [tootsuite/mastodon#5421]
![image1](https://user-images.githubusercontent.com/18600658/31626617-0596c688-b2dd-11e7-90a4-6ee38934bfa9.jpeg)

As shown in the picture above. This happens when replying to or posting a long post, the privacy setting options get blocked.

Tested with Chrome 61.0, screen resolution 1366*768

**Comment by Cassolotl** [comment]
I think this is a duplicate of #5313?

**Comment by ragingscholar** [comment]
Looks like a duplicate, really sorry about that. I made sure that I searched open issues...

**Comment by Cassolotl** [comment]
No worries! :) I only knew about the other one because I'd already read it!
