### ISSUE TITLE
Unify usage of initial page state

### ISSUE THREAD

**Issue by nolanlawson** [tootsuite/mastodon#5426]
(Follow-up to https://github.com/tootsuite/mastodon/pull/5423)

We have lots of initial state in the web app that is unchanged after the page is loaded. Currently we're handling this a few different ways:

- separate JS files (e.g. `locale_*.js`)
- `initial-state` embedded JSON
- body classes (e.g. `system-font`, `reduce-motion`)
- Redux store (e.g. `auto_play_gif`)

I think the locales are fine as-is, and some body classes are unavoidable due to usage from CSS (e.g. `system-font)`, but in general I think we should unify this so that there's a single module that holds our initial static state, derived from the `initial-state` embedded JSON.

My reasoning:

- body classes are not ideal because you have to wait for the `DOMContentLoaded`/`ready` event, meaning you can't directly export from a module and have to create `getFoo()` functions instead (e.g. `optional_motion.js`)
- Redux store is not ideal because these values never change, and so you add overhead in Redux `connect()` HoCs because they update whenever anything in the store changes, which is wasted work. Plus you have to pass props everywhere when it's completely unnecessary to do so (e.g. `auto_play_gif`)
- We can't do inline scripts because of CSP on some instances, so inline JSON is next best thing

I also noticed that we parse our current `inline-state` three times with `JSON.parse()` when it only needs to be parsed once. So I'd like to clean this up and refactor it so it's handled in one place.

**Comment by nightpool** [comment]
>We can't do inline scripts because of CSP on some instances, so inline JSON is next best thing

does nginx have a way to set CSP nonces?

**Comment by nolanlawson** [comment]
It seems [possible but also very tricky](https://scotthelme.co.uk/csp-nonce-support-in-nginx/). Also inline JSON is really not a whole lot worse than inline JS (it's just a bit awkward), so I'm not bothered if we can't do inline scripts.
