### ISSUE TITLE
Server checks character limit overzealously

### ISSUE THREAD

**Issue by KrzysiekJ** [tootsuite/mastodon#5433]
I’ve attempted to submit the following toot:

> If we want to achieve compatibility between #web #browsers, it is important to implement #standards strictly, without non-standard error recovery. For example, someone mistyped backslashes into stylesheet URL on kobo.com. #Chrome and #Firefox convert backslashes into slashes, while #Pale_Moon displays website without any styles (correctly, I presume).
>
> BTW, on Firefox there is currently error 500, which suggests that the server acts differently depending on user agent string (another mistake).

This toot has 498 characters and this number is reported by the UI. However, when trying to submit it, I get the “422 Negatywne sprawdzenie poprawności: Text limit 500 znaków przekroczony” error saying that the character limit has been exceeded. My guess is that the server wants to convert kobo.com into an URL, which will result in a bigger number of characters. However if I wanted to make an URL, I would put protocol part in it.

The server runs Mastodon 1.6.1.

* * * *

- [×] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
Looks like the server treats `kobo.com` as an URL which should be auto-linked, and we count any those URLs as 23 characters.

However, we don't capture scheme-less URLs, so `kobo.com` should be counted as 8 characters.
