### ISSUE TITLE
Upload dialog crashes after uploading fail

### ISSUE THREAD

**Issue by Kjwon15** [tootsuite/mastodon#5446]
"Upload photo" button![image](https://user-images.githubusercontent.com/5047683/31704302-98985084-b41b-11e7-97b5-c84570030359.png) is not working after failed to upload once(eg: File size over 8MB)

When I failed to upload photo/video due to file size limit, I resize image on local, then I retry upload. But that camera icon is not working(Dialog doesn't come up), So I refresh webpage and retry.

It could be better if client can shrink file size before uploading. But first, This bug should be fixed.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
I couldn't reproduce on Windows + Chrome 62 + Mastodon 1.6.0 or latest master.

Which OS and browser are you using? Also please check if any errors appear on the JavaScript console.

**Comment by Kjwon15** [comment]
Oh sorry.. I cannot reproduce too..
I don't know why, But I close issue and re-open when this happened again.
