### ISSUE TITLE
mastodon-streaming.service down after update to v2.0.0

### ISSUE THREAD

**Issue by balamkej** [tootsuite/mastodon#5456]
After updating to v2.0.0 with no errors during setup, mastodon-streaming.service dies on startup. I can still access my instance and nothing immediately appears broken, but surely something is wrong, and so any help would be greatly appreciated. This is my /home/mastodon/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@2.15.11
3 info using node@v4.8.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart mastodon@
6 info start mastodon@
7 verbose unsafe-perm in lifecycle true
8 info mastodon@ Failed to exec start script
9 verbose stack Error: mastodon@ start: `node ./streaming/index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:862:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid mastodon@
11 verbose cwd /home/mastodon/live
12 error Linux 4.4.0-97-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
14 error node v4.8.4
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error mastodon@ start: `node ./streaming/index.js`
17 error Exit status 1
18 error Failed at the mastodon@ start script 'node ./streaming/index.js'.
18 error This is most likely a problem with the mastodon package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./streaming/index.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs mastodon
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls mastodon
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ykzts** [comment]
Please install Node.js v6.
