### ISSUE TITLE
Question: How does account suspension work on remote instances?

### ISSUE THREAD

**Issue by SerCom-KC** [tootsuite/mastodon#5460]
So, I created an account on my own instances (A), set up profile and send some toots, then remote followed this account using another account on a remote instance (B). Everything worked fine. I delete one of A's toots, and it disappeared on B's timeline immediately.
Then I suspended A, all toots got removed on my own instance, however this time nothing happened on B's timeline - account A still exists on remote instance, all toots are visible, just like nothing happened.
Is this intended, or do I have a misconfiguration somewhere?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
When you suspend local account, Mastodon notifies deletion of each toots to their remote followers, as well as when you delete specific toot. So those toots should be removed from remote (Mastodon) instances.

This process may take a while (especially if they have many toots or many remote followers), so you may want to check remaining Enqueued jobs in Sidekiq dashboard (your.instance/sidekiq/).

**Comment by SerCom-KC** [comment]
@unarist
Thanks for answering.
Actually before I suspend account A there's only one toot left, and there're no enqueued jobs in sidekiq. Almost 24 hours passed and that toot is still on remote instance. What might cause this?

**Comment by samanthaghraves** [comment]
How is Sidekiq looking? Cos it's entirely possible that you need to restart it and try the action again.

**Comment by SerCom-KC** [comment]
@samanthaghraves
Idle status, all numbers 0 except processed/failed.
Do you mean re-suspend the account? I believe that test toot is not in my local database anymore, unless suspending account only does soft-delete.

**Comment by SerCom-KC** [comment]
Seems like the problem is fixed after upgrading to v2.0.0 (I was using rc2).
Although I really should open another issue to talk about this, is it possible to add a feature for admins to send a request to delete all toots under a certain username to remote instance? Sometimes a database failure can causes some toots undeletable on remote forever :(
