### ISSUE TITLE
Mutes and blocks hide statuses even from the targets' profiles in the same session

### ISSUE THREAD

**Issue by akihikodaki** [tootsuite/mastodon#5469]
On the Web interface, a mute hides statuses from a particular user. It even hides from user timeline.
That is undesired in a situation that
* a user thinks muted person is too noisy for home timeline but
* the user is still interested in the person and want to see the statuses when it is convenient for him.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
So just to clarify - you think that "mute" should only affect home, notifications and hashtags, but when you visit someone's profile you should be able to see their toots?

That seems sensible to me, if that is indeed what you mean?

**Comment by akihikodaki** [comment]
Exactly. That what I mean.

**Comment by akihikodaki** [comment]
I think here we have a consensus, but now I also wonder whether the statuses of blocked accounts in their account page.
I'm implementing in the way making blocks consistent with mutes, so please give me your reaction if you disagree with the decision.

**Comment by akihikodaki** [comment]
@unarist pointed out that the issue happens only in the session on which blocks and mutes are performed. I changed the title accordingly.

**Comment by akihikodaki** [comment]
Changing labels; the inconsistency with the server-side implementation should be regarded as a bug.
