### ISSUE TITLE
Ability to block individual toots

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#5470]
I'm not sure but I thought I had already seen this issue (or even opened it myself??) but I can't find it.

I'd like to be able to click "hide toot" in the ... menu for a toot. I could use it to remove a reply from notifications without having to wipe the whole list, or I could use it to remove a harmful toot or two from a timeline without having to mute, block or unfollow someone.

It would work like blocking a user, but it would only affect a toot.

* * * *

- [Y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by deutrino** [comment]
Dupe of #1669?

**Comment by Cassolotl** [comment]
Yes! I've even commented on it. :D Thank you!
