### ISSUE TITLE
Update from 1.3.2 to 2.0.0

### ISSUE THREAD

**Issue by saggel** [tootsuite/mastodon#5471]
I kept my live instance on 1.3.2 cause everything was working smooth and fine.

Now I think it's a good opportunity to update to 2.0.0 once everything is stable.

Would that be possible, or should I set up a 2.0.0 instance and move the database?

I would prefer to update the current instance if possible, what would it take?

Thank you for your help in advance.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by hugogameiro** [comment]
If I were you, I would upgrade from each major release. Start to:
https://github.com/tootsuite/mastodon/releases/tag/v1.4.1
then
https://github.com/tootsuite/mastodon/releases/tag/v1.5.0
and
https://github.com/tootsuite/mastodon/releases/tag/v1.6.0
then finally upgrade to v2.0.0

Read the "Upgrade notes" for ALL releases (major and minor) and be sure to do any additional steps mentioned on minor (in between) releases on the next major one you install. Example:
On v1.4.5 https://github.com/tootsuite/mastodon/releases?after=v1.4.5 requires "Node.js version from 4 to 6" so the next major release that you will install is v1.5.0 you need to have to execute that before the upgrade.

It is a bit of work but you shouldn't have a problem by doing it this way.

**Comment by saggel** [comment]
Thanks @hugogameiro, I thought of doing something similar with every release from 1.3.3 all the way up to 2.0.0, but what you're suggesting is much better!

**Comment by nolanlawson** [comment]
The 2.0.0 release may take awhile due to a rather large database migration. @hugogameiro's suggestion of doing it one step at a time is a good one. You may also want to back up your database each time using [pg_dump](https://www.postgresql.org/docs/current/static/app-pgdump.html).
