### ISSUE TITLE
Make /settings/follower_domains searchable

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#5472]
When you've got a lot of followers, it's really hard to find anything! The list of domains and number of people following you from them isn't sorted alphabetically or numerically, and there's no way to sort by anything either.

(I tried to search the issue list to see if anyone else had requested this feature but didn't find anything - but in all honesty I wasn't 100% sure what search terms would work. Point me in the right direction if this is a duplicate!)

* * * *

- [Y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
I know we have some rules against making things searchable in order to prevent harassment, but this seems reasonable given it's only available to the user themselves and presumably wouldn't include full-text search (instead just prefix or something).

**Comment by Cassolotl** [comment]
I can't find /settings/follower_domains in 3.0.1 any more - is it gone, in favour of "Follows and followers" at /relationships?

**Comment by trwnh** [comment]
Yes, I think so

**Comment by Cassolotl** [comment]
Alright, this can be closed then. It would be resolved by *[Feature request] A way to search followers/following #10320*. :)
