### ISSUE TITLE
Links break (sometimes) when aggregating the atom feed into IFTTT

### ISSUE THREAD

**Issue by TauPan** [tootsuite/mastodon#5475]
So I have the following ifttt recipes:

- One for facebook: https://ifttt.com/applets/63330170d-if-new-feed-item-matches-fb-from-https-mastodon-technology-taupan-atom-then-create-a-status-message-on-friedrich-delgado-s-timeline

- One for twitter: https://ifttt.com/applets/53231742d-if-new-feed-item-matches-tw-from-https-mastodon-technology-taupan-atom-then-post-a-tweet-to-taupan

Here is a working example of a cross-posted toot from yesterday:
 - Toot: https://mastodon.technology/@TauPan/4254030
 - Facebook post: https://www.facebook.com/TauPan/posts/10155893648704656?pnref=story
 - Tweet: https://twitter.com/TauPan/status/920555588811190272

So it works in some cases.

This is a new one, that's broken (as suspected, with a long link):
 - Toot: https://mastodon.technology/@TauPan/4291291
 - Facebook: https://www.facebook.com/TauPan/posts/10155897658209656?pnref=story
 - Tweet: https://twitter.com/TauPan/status/921062885652090880

Hm, that was too long for twitter, so it got cut off before I even got to the http. Last time I tried, the link on twitter was broken in exactly the same way as on facebook.

The content in the ifttt  activitylog looks ok: 
```
Ingredients
EntryAuthor
(none)
EntryContent
<p>I&apos;m investigating an issue with mastodon atom feeds and ifttt, so here&apos;s a long link that will probably break: <a href="https://ifttt.com/applets/63330170d-if-new-feed-item-matches-fb-from-https-mastodon-technology-taupan-atom-then-create-a-status-message-on-friedrich-delgado-s-timeline" rel="nofollow noopener" target="_blank"><span class="invisible">https://</span><span class="ellipsis">ifttt.com/applets/63330170d-if</span><span class="invisible">-new-feed-item-matches-fb-from-https-mastodon-technology-taupan-atom-then-create-a-status-message-on-friedrich-delgado-s-timeline</span></a></p><p>!tw !fb</p>
EntryImageUrl
http://ifttt.com/images/no_image_card.png
EntryPublished
October 19, 2017 at 07:16PM
EntryTitle
New status by TauPan
EntryUrl
https://mastodon.technology/@TauPan/4291291
FeedTitle
Friedrich Delgado
FeedUrl
https://mastodon.technology/@TauPan
```

So my personal guess is that the link gets screwed up when it's passed on to the next ingredient in the recipe. So unless you say: "Oh, but this is broken on our side!", I guess I'll have to copy & paste this information to ifttt.

Kind regards
Friedel

* * * *

- [ X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ldexterldesign** [comment]
FYI

Hey @TauPan,

It was a nightmare for me to setup Mastodon > IFTTT > Twitter, notably because Mastodon uses "@" in URLs (e.g. https://mastodon.social/@ldexterldesign/ ) which Twitter obfuscates into it's [@user] syntax

Mastodon > IFTTT > Buffer > Twitter resolves things but I would love to know if there's a solution to this so I can drop Buffer?

Hope this is clear/useful

Regards

**Comment by Gargron** [comment]
Atom feeds were not designed for IFTTT consumption, that being said, they *are* valid in terms of multiple advanced specs, it's just that IFTTT is overly simplistic and can't handle them well. Nothing I can/will do about this.
