### ISSUE TITLE
Links in statuses need to have rel="nofollow" for spam prevention.

### ISSUE THREAD

**Issue by paintedsky** [tootsuite/mastodon#5480]
I noticed that there were a lot of spam accounts in Local Timeline linking to various business websites with a bunch of hashtags, seemingly for SEO benefit.

I inspected the links in Chrome DevTools and found that rel="noopener" is used but not "nofollow".

As I'm sure you are aware, this simple tweak will make those links useless from a SEO standpoint and spam of this type will probably dwindle.

Thanks!

**Comment by cooox** [comment]
Do you have an example Toot where there is no "nofollow"? 
If you look at the [formatters for links](https://github.com/tootsuite/mastodon/search?utf8=%E2%9C%93&q=noopener) you'll see that nofollow is usally appended as well. Maybe some instances tweaked the code 🔧

**Comment by paintedsky** [comment]
This is the "main" mastodon.social instance.

Here's an example (apparently it DOES have "nofollow" when viewing the single Toot when not logged in / viewing in its own tab)

[Just grabbed the first link in my TL](https://mastodon.social/@tobyalden/98880445357316746l)

If I inspect that link on my stream though, it doesn't have "nofollow". [Image](https://imgur.com/AtSTxEq)

I confess that I don't have complete SEO mastery; I don't know if having "nofollow" for public links and not for logged in users is adequate for preventing spammy links from benefitting from Masto's domain authority.

If it were enough though, why would these spammers even bother trying to post such low-effort nonsense on Masto anyways? No human is going to click those links.
