### ISSUE TITLE
minor DOS

### ISSUE THREAD

**Issue by novalis** [tootsuite/mastodon#5482]
curl -H 'Signature: keyId="http://BAD",algorithm="rsa-sha256",signature="bogus"' -v -d '' http://mastodon.example/users/testuser/inbox

This causes the mastodon instance to fetch http://BAD.  If http://BAD very quickly (in < 10 seconds, which appears to be the timeout) returns lots of content, that content will be buffered in the server's RAM, which can cause a DOS.  If BAD is 'localhost:xxxx', perhaps resources can be accessed that should not, although since it's just a GET request and the user can't see the result, maybe that's not super-useful.  

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Private addresses are now disqualified from being fetched; otherwise this behaviour is unavoidable, the 10sec timeout is the best that can be done.

**Comment by novalis** [comment]
You could put a byte limit on the fetched content.
