### ISSUE TITLE
Question: Which tool are you using to planning or project the development of mastodon  ???

### ISSUE THREAD

**Issue by marcusvinicus** [tootsuite/mastodon#5486]
Its a question!

I saw that you are not using more the project features of github, thats was prevestly used in version 1.4 and 1.5. I'd like to know what are u using to plan and project the development of the nexts versions of mastodon ?     

thanks!

**Comment by ThibG** [comment]
My guess is: nothing.
If @Gargron has a different answer, I'll let him reply, but in the meantime I'm closing this issue.

**Comment by nightpool** [comment]
we generally use GitHub issues with checklists to keep track of stuff
