### ISSUE TITLE
Full-width characters of URL included in toot are converted to half-width characters when toot is diplayed.

### ISSUE THREAD

**Issue by wakin-** [tootsuite/mastodon#5497]
Full-width characters of URL included in toot are converted to half-width characters when toot is diplayed.

example: https://shiga2.jp/%E3%81%AE%E3%81%A9%E9%BB%92%E9%A3%B4%E3%81%AE%EF%BD%83%EF%BD%8D%E3%81%A3%E3%81%A6%E5%A4%A9%E7%A5%9E%E5%B1%B1%E6%9D%BE%E9%A2%A8%E5%BA%B5%EF%BC%88%E6%BB%8B%E8%B3%80%E7%9C%8C%E5%A4%A7%E6%B4%A5%E5%B8%82/%E5%A4%A7%E6%B4%A5%E5%B8%82/

- ｃｍ　→　cm
- （　→　(

I think this cause is Addressable::URI#normalize.

**Comment by unarist** [comment]
Yes, it would be due to the Unicode normalization which shouldn't be applied. 

see https://github.com/tootsuite/mastodon/issues/4837

**Comment by wakin-** [comment]
Thank you.
I close this issue.
