### ISSUE TITLE
Link previews don't load when browsing in panes / columns

### ISSUE THREAD

**Issue by amithm7** [tootsuite/mastodon#5510]
Example :
![mr1](https://user-images.githubusercontent.com/7036770/31899049-415be8a0-b838-11e7-9c0c-93a10511919c.png)
Error in console :
![mr2](https://user-images.githubusercontent.com/7036770/31899156-8c67a190-b838-11e7-99e4-e83e9b51eac9.png)
- This happens even if the user is in the same instance.

----
- Doesn't happen if the status is opened separately in a new page.

![mr3](https://user-images.githubusercontent.com/7036770/31899406-19e65b9c-b839-11e7-8da4-25e0421b6465.png)

Browser : Google Chrome Version 62.0.3202.62 (Official Build) (64-bit)
OS : Debian GNU/Linux 9.2 (stretch) x86_64
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
@amithm7 https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
