### ISSUE TITLE
Can we use the API to know the administrator of the Instance to which I belong?

### ISSUE THREAD

**Issue by riku-shiru** [tootsuite/mastodon#5513]
I would like to use information such as API and want to know who the administrator of the instances to which I belong and other instances belongs. In order for me to know the administrator, there is no other way than visiting the administrator's profile page to see if there is "admin"? I would like you to tell me if any.

- [] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Documentation: https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#instance
