### ISSUE TITLE
Instances dont create proper Browser title tags for toot status URLs

### ISSUE THREAD

**Issue by LeeteqXV** [tootsuite/mastodon#5514]
On toot status URLs, the browser title metatag is not reflecting the content.

When on such a URL, and for example bookmarking it, the first paragraph/words of the toot should be used, along with an instance identificator (the domain name, IMO).

Example 1;
https://mastodon.technology/@LeeteqXV/98884407540260736

- gets a "title" just saying "Mastodon for Tech Folks", the instance tagline.

IMHO, it should grab and make use of the first sentence in the toot, and apply the instance URL to it.
That would mean, in this example:
"FYI: Just posted a #Mastodon #Drupal module #multiaccount #featureRequest - mastodon.technology"

Example 2, from Mastodon.social:
This toot: https://mastodon.social/@ZeniorXV/98880823783376933
- currently only gives "Mastodon" as the title, but should be something like this:

"CoinDesk: "mobile #bitcoin #wallets today send transactions to the bitcoin #blockchain - Mastodon.social"

**Comment by Cassolotl** [comment]
I think this is fixed now!
