### ISSUE TITLE
"open toot" click area is too small

### ISSUE THREAD

**Issue by thomaslule** [tootsuite/mastodon#5518]
When a toot contains nothing but an image, it's frustrating to find a place where you can click to open the toot and see the replies.

As far as I can tell you have to find the green area on this example toot (I added the color):

![image](https://user-images.githubusercontent.com/8104612/31968837-c0ddac64-b912-11e7-84a9-ddf94e42e22e.png)

I think that it would be more intuitive if we could click anywhere on the toot to open it (except on the links of course)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
I think this is a duplicate of #4314? This has been opened by users and then closed by Gargron a few times. This latest one is by me, because it bugs me a lot! There's a few links and explanations in that post, which might help make sense of it.

**Comment by thomaslule** [comment]
Whoops I don't know why it didn't came up when I searched for it :)
