### ISSUE TITLE
Deployment with docker fails

### ISSUE THREAD

**Issue by rototom** [tootsuite/mastodon#5519]
```
thomas@mail:~$ git clone git@github.com:tootsuite/mastodon.git
Cloning into 'mastodon'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
thomas@mail:~$ 


```

**Comment by ykzts** [comment]
```console
$ git clone https://github.com/tootsuite/mastodon.git
```

**Comment by nightpool** [comment]
This appears to be a github bug? If not, this issue should be re-opened against tootsuite/documentation, where the docker guide lives.

**Comment by ykzts** [comment]
To use SSH when git cloning from GitHub, you need to register the public key in GitHub ([SSH and GPG keys - Settings](https://github.com/settings/keys)). This error occurs when the SSH certificate is wrong or does not exist.

**Comment by ykzts** [comment]
@rototom [your key](https://github.com/rototom.keys) is empty.

**Comment by nightpool** [comment]
@ykzts @rototom I'll make a PR against documentation, we should just use the https url.

**Comment by Dragnucs** [comment]
@nightpool Someone has already made a PR in the doc to use the http link instead if I remember.
