### ISSUE TITLE
ActivityPub Like HTTP 422 error: "Validation failed: Username has already been taken"

### ISSUE THREAD

**Issue by snarfed** [tootsuite/mastodon#5523]
hi again! i'm getting an HTTP 422 error with body `{"error":"Validation failed: Username has already been taken"}` when i try to POST an ActivityPub Like to mastodon 2.0.0, both locally and against mastodon.social.

i originally saw this when posting a reply that didn't have `attributedTo.preferredUsername`: https://github.com/tootsuite/mastodon/issues/4906#issuecomment-333680170 . now i see it for likes even when `actor.preferredUsername` is populated.

is it maybe having trouble mapping the actor to a user@domain form? snarfed.org does serve webfinger for `acct:me@snarfed.org` - it redirects to https://fed.brid.gy/.well-known/webfinger?resource=acct:me@snarfed.org - but i'm not sure if or how mastodon would map the ActivityStreams 2 actor below to me@snarfed.org.

example POST body below. my attempts include valid HTTP Signatures, e.g. for this request corresponding to the public key in the actor object https://fed.brid.gy/snarfed.org. let me know if i can provide any more info. cc @puckipedia @nightpool. thanks in advance!

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Like",
  "id": "https://snarfed.org/2017-10-24_mastodon-for-tech-folks-5",
  "url": "https://snarfed.org/2017-10-24_mastodon-for-tech-folks-5",
  "object": "https://mastodon.social/users/chrisaldrich/statuses/98886190056547563",
  "actor": {
    "preferredUsername": "me",
    "name": "Ryan Barrett",
    "url": "https://snarfed.org/",
    "type": "Person",
    "id": "https://fed.brid.gy/snarfed.org",
    "icon": [{
        "url": "https://secure.gravatar.com/avatar/947b5f3f323da0ef785b6f02d9c265d6?s=96&d=blank&r=g",
        "type": "Image"
      }],
    "image": [{
        "url": "https://secure.gravatar.com/avatar/947b5f3f323da0ef785b6f02d9c265d6?s=96&d=blank&r=g",
        "type": "Image"
      }]
  },
  "content": " <p>likes <a class='u-like u-like-of' href='https://mastodon.technology/web/statuses/98886190090823517'>Mastodon for Tech Folks</a> <a href='https://fed.brid.gy/'></a></p> ",
  "cc": ["https://www.w3.org/ns/activitystreams#Public"],
  "tag": [{"name": "like"}],
  "published": "2017-10-24T15:59:15-07:00",
  "name": "like \n\nOctober 24, 2017 Ryan Barrett\nLeave a comment\n\n\nlikes Mastodon for Tech Folks\n\n\nStandard"
}
```

https://fed.brid.gy/snarfed.org currently serves:

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Person",
  "id": "https://fed.brid.gy/snarfed.org",
  "url": "http://snarfed.org/",
  "preferredUsername": "me",
  "name": "Ryan Barrett",
  "inbox": "https://fed.brid.gy/snarfed.org/inbox",
  "publicKey": {
    "publicKeyPem": "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDxpokNqq300ulfJEGvFRFKmx1g\ncp8GDV8cpXBEvYBN5WFbtbLU3wMSg4nf5B1HpGu9V9JCUMEvg2G+zQ4OSlH+Pp2l\nNsueDIwWq0Bu3Wj747ejXgoENfZfidyGY0bbv9oSBmVkuizE4SAuJB8jy8Qrqnxf\n0xrlT+n7M+fxk3irvQIDAQAB\n-----END PUBLIC KEY-----"
  },
  "image": [{
      "url": "http://snarfed.org/ryan_profile_square_thumb.jpg",
      "type": "Image"
    }],
  "icon": [{
      "url": "http://snarfed.org/ryan_profile_square_thumb.jpg",
      "type": "Image"
    }]
}
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by puckipedia** [comment]
If I'm reading this properly, I think preferredUsername + host of the ID of the actor form a unique couple on Mastodon, and this is used when trying to roundtrip verifications as well. You should probably set the username to something like the domain.

Alternatively, currently Mastodon verifies 'trustworthy attribution' if the actor ID is on the same domain as the activity that is created. Maybe we could define an extension to say "this server is allowed to post content", to allow for AP bridges?

**Comment by snarfed** [comment]
@puckipedia thanks! that makes sense. mastodon would currently interpret the actor here as `me@fed.brid.gy`, but it should be `me@snarfed.org`.

special casing known trusted bridges could be ok, but it'd be nice to avoid if possible. if mastodon takes the id's host before redirects, i could switch actor id to a URL on the source site that redirects to fed.brid.gy...

...but setting username to site domain may be the best approach, since mastodon already emphasizes username in rendering and de-emphasizes or hides domain altogether, even for remote instances, which makes the `me` username sub-optimal and sometimes misleading. (more background in snarfed/bridgy-fed#3.) i'll do that.

**Comment by nightpool** [comment]
Yes currently we parse the webfinger domain as the normalized host of the actor's `id` property. this is maybe sub-optimal but i'm not sure how else to define it without including an explicit webfinger_domain property. Does it make much of a difference to you?

**Comment by nightpool** [comment]
Another alternative may be to host the AP actor JSON statically on the indieweb domain, which I think I saw some people talking about maybe wanting to do.

**Comment by snarfed** [comment]
> Yes currently we parse the webfinger domain as the normalized host of the actor's id property.

yup, totally fine and reasonable. i only very recently changed our actor `id`s from the user's site to fed.brid.gy, and hadn't realized this effect.

> Another alternative may be to host the AP actor JSON statically on the indieweb domain

true! we're trying to make using the bridge require as little setup by the indieweb user as possible, though. for now i'll just switch username to site domain. i'll close this once i confirm that works.

**Comment by snarfed** [comment]
confirmed! changing username to indieweb site domain works. closing.
