### ISSUE TITLE
 why did I open my website to display only the text, no pictures

### ISSUE THREAD

**Issue by 84795949** [tootsuite/mastodon#5526]
I built Mastodon on Cenots7.2, but solved all the problems, but why did I open my website to display only the text, no pictures？
My domain name is  test.forxu.cn
Can anyone answer this question?

**Comment by rototom** [comment]
Same problem here with https://okaris.de

**Comment by 84795949** [comment]
When I looked at the page using developer tools, I found:

about:16 GET https://test.forxu.cn/packs/common-b53dca5ee3777179c45c.css net::ERR_ABORTED
about:17 GET https://test.forxu.cn/packs/default-b53dca5ee3777179c45c.css net::ERR_ABORTED
about:23 GET https://test.forxu.cn/packs/about-d0de2ea84241cc1c76b2.js net::ERR_ABORTED
about:19 GET https://test.forxu.cn/packs/locale_en-4e0b641d3e93448c7f31.js net::ERR_ABORTED
about:18 GET https://test.forxu.cn/packs/common-53f01dcfef31c6ab9166.js net::ERR_ABORTED
about:40 GET https://test.forxu.cn/packs/elephant-fren-d16fd77f9a9387e7d146b5f9d4dc1e7f.png 404 (Not Found)
about:19 GET https://test.forxu.cn/packs/locale_en-4e0b641d3e93448c7f31.js net::ERR_ABORTED
about:45 GET https://test.forxu.cn/packs/logo_full-96e7a97fe469f75a23a74852b2478fa3.svg 404 (Not Found)
about:23 GET https://test.forxu.cn/packs/about-d0de2ea84241cc1c76b2.js 404 (Not Found)
But on my server, they are normal，Why can't they load it?Who can help me？

**Comment by rototom** [comment]
I was missing some redirection rules in my apache config
