### ISSUE TITLE
when going "back" to a deleted toot the fourth column gets stuck at loading

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#553]
I had deleted one of my toots after copying out the contents so i could edit them, and then clicked on another one. When i clicked the back link, it tried to go back to my deleted toot, showed a "404 Record Not Found" toast in the bottom left, but the fourth column got stuck on loading, forbidding me from progressing further back.

Probably a good idea to have it render something with a back button there for deleted things.

**Comment by blackle** [comment]
this is covered by #465

**Comment by wchristian** [comment]
Indeed it is. :)
