### ISSUE TITLE
migration error from 1.6.1 to 2.0.0: cannot drop inherited column "account_id"

### ISSUE THREAD

**Issue by schmittlauch** [tootsuite/mastodon#5532]
When trying to upgrade from mastodon-1.6.1 to 2.0.0 (docker), I get a migration error:

```
PG::InvalidTableDefinition: ERROR:  cannot drop inherited column "account_id"
: ALTER TABLE "blocks" DROP "account_id"
```

[full log](https://www.systemli.org/paste/?8b189ce7f8aa4e48#iYrj/DDhaiHVq7YZS94aVF50/6GAto/Do8vgHS+WbHY= )

Did I forget a migration step?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
Your DB seems to have an obsoleted migration which only exists on pre-1.4 master.

You need to execute some SQLs described in https://github.com/tootsuite/mastodon/pull/2634#issuecomment-298231516.

**Comment by schmittlauch** [comment]
That seems to have fixed it, thanks.
