### ISSUE TITLE
Video uploads fail with error 422 on at least iOS 11

### ISSUE THREAD

**Issue by Wack0** [tootsuite/mastodon#5533]
I didn't run into this issue (in fact I don't even have a modern iOS device!); @_ADifferentKind@mastodon.social did.

From what I can gather, the cause could be either or both of the following: iOS 11 changed default saved video format to H.265, and iOS since at least 2012 saves videos with the .mov extension.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
Do you have an example video file that fails to upload?

**Comment by Wack0** [comment]
I think it was one that was recorded from the camera.

**Comment by nightpool** [comment]
we should probably upstream this to paperclip

**Comment by dunn** [comment]
Still happening on iOS 11.3 and Mastodon 2.3.3, fwiw, with videos created by the camera.

**Comment by willispapaya** [comment]
Yes, me too , today I met this problem also, IOS 11.4 and Mastodon 2.4.3 
![image](https://user-images.githubusercontent.com/41905280/43396800-52794c48-9435-11e8-9027-0edfa75fc5bb.png)
