### ISSUE TITLE
Bots are getting banned

### ISSUE THREAD

**Issue by raymestalez** [tootsuite/mastodon#5537]
I've made a bot account for hot products from product hunt - @ProductHuntBot, and it has been deleted. I'm trying to figure out why, it didn't break any rules as far as I know. A very similar bot, @HackerNewsBot keeps working without any problems.

I would really love to be able to subscribe to a timeline of PH updates, and maybe make similar accounts for some rss and twitter feeds I want to follow. Are there any guidelines for making bots that I should know about?

Can you guys help me find out what went wrong?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
This is something you should follow up with your server admin. This is the github repo for the software, mastodon, which runs on many, many servers that all communicate with eachother. It really solely has to do with software development and isn't monitored or tracked by the moderation team of any instance.
