### ISSUE TITLE
content warnings should not hide the @'s at the beginning of the toot

### ISSUE THREAD

**Issue by jessicahayley** [tootsuite/mastodon#554]
If you put a content warning on a reply, it'll show up in people's timelines without the @ reply in front, so there's no way for them to tell that it's not intended as a widespread tweet until they click "show more", for example:
![capture](https://cloud.githubusercontent.com/assets/1892337/22351878/b8045918-e3ce-11e6-9575-637217366d0f.PNG)
![capture2](https://cloud.githubusercontent.com/assets/1892337/22351881/b9a234e8-e3ce-11e6-8faf-75b36cd5efe7.PNG)

Someone that browses my timeline would not see that that was supposed to be a reply until they've revealed the SUPER LEWD TOOT WITHIN, which is subpar

I am of the opinion that the content warning should reveal, at the very least, any @ at the beginning of the toot, if not every subsequent @ until the start of the actual toot contents

**Comment by fontiago** [comment]
(additionally when @'s are put into a content warning label they cease to work, despite counting towards toot text)

**Comment by Gargron** [comment]
Solved in af007f2def802560f548d85f81f0f4e5039ae737
