### ISSUE TITLE
ResolveRemoteAccountService's state is not properly reset when call()ed

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#5540]
`ResolveRemoteAccountService` is stateful and its state is not properly reset (`@atom_url`, `@url` and more are not reset when called again).

I don't know if the same `ResolveRemoteAccountService` object is supposed to be callable multiple times, but it was called that way in at least one place, which my PR #5539 made worse.

**Comment by Gargron** [comment]
Service classes are not (supposed to be) callable multiple times, a new one must be instantiated.

**Comment by ThibG** [comment]
Ok, I'll fix the caller as soon as I'm done with work, then.
