### ISSUE TITLE
There is no hotkey for expanding a toot with a CW

### ISSUE THREAD

**Issue by ilianaw** [tootsuite/mastodon#5550]
Fully using Mastodon with a keyboard isn't quite usable without being able to expand a toot with a CW.

May I suggest shift+enter?

(I can hit Tab four times to focus the Show More button and hit space as a work around. That's certainly not ideal.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by claiire** [comment]
Tbh I really think this should be a higher priority thing. 

Ensuring that a website is usable with the keyboard only is an important accessibility feature, and shortcuts aren't quite complete without an expand cw shortcut.

**Comment by beatrix-bitrot** [comment]
how do you feel about space for this?

**Comment by sorin-davidoi** [comment]
It works with Enter when you focus the toggle button.

**Comment by nightpool** [comment]
I was thinking 'x'. This is really confusing for me on a daily basis

**Comment by ilianaw** [comment]
Hitting tab four times to focus toggle isn't good enough, frankly.

<kbd>x</kbd> would be reasonable to me.

**Comment by beatrix-bitrot** [comment]
x then, very well

**Comment by deutrino** [comment]
Is there anything standing in the way of merging this?

**Comment by sorin-davidoi** [comment]
There is nothing to merge yet, as no one opened a pull request fixing this.

**Comment by deutrino** [comment]
I meant from changes in glitch-soc/mastodon#232.

I can never get an answer from any of them about how changes might flow back upstream - I've asked regarding media previews, for example, and never gotten an answer.

**Comment by beatrix-bitrot** [comment]
@deutrino sorry about not getting back to you. there's a lot of reasons things don't make it back upstream. some have, most don't. here i think the change in functionality depended on refactoring some stuff, and was also done on a set of files that don't actually exist upstream, so it can't be merged into upstream and it's also not trivial to backport it. everyone has things they'd rather be doing.
