### ISSUE TITLE
Treat as:Public as https://www.w3.org/ns/activitystreams#Public

### ISSUE THREAD

**Issue by cwebber** [tootsuite/mastodon#5551]
See: https://github.com/w3c/activitypub/issues/264

Implementations which compact ActivityStreams objects to the ActivityStreams json-ld context may represent `https://www.w3.org/ns/activitystreams#Public` as simply `as:Public`.  It would be good if Mastodon would treat these as the same thing.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by cwebber** [comment]
<code>Public</code> as well.

**Comment by wmurphyrd** [comment]
Just hit this with [Immers Space](https://github.com/immers-space/immers) / [activitypub-express](https://github.com/immers-space/activitypub-express)

Object is this:

```
{
   "@context" : [
      "https://www.w3.org/ns/activitystreams",
      "https://w3id.org/security/v1",
      {
         "@context" : {
            "Model" : "is:Model",
            "avatar" : {
               "@id" : "is:avatar",
               "@type" : "@id"
            },
            "is" : "https://immers.space/ns/v1#"
         }
      }
   ],
   "attributedTo" : "https://immers.space/u/datatitian",
   "content" : "Hello federated metaverse!",
   "context" : {
      "audience" : "as:Public",
      "id" : "https://immers.space/o/immer",
      "name" : "immers.space",
      "type" : "Place",
      "url" : "https://hub.immers.space/o8ekTnA/perfect-direct-square"
   },
   "id" : "https://immers.space/o/60455b3a49ea8469ca6bf97a",
   "to" : [
      "https://immers.space/followers/datatitian",
      "as:Public"
   ],
   "type" : "Note"
}
```

Should be public, but appears as "followers only" in Mastodon

![image](https://user-images.githubusercontent.com/10034859/110259799-2f80ce00-7f6f-11eb-875b-60bca788dbf2.png)

We're using https://github.com/digitalbazaar/jsonld.js/ for JSON-LD processing which produces that `as:Public` form of the public url
