### ISSUE TITLE
Emojis in the invisible part of the URL is visible

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#5554]
```
http://example.com/web/timelines/public」text🍊🍊🍊
```

![image](https://user-images.githubusercontent.com/705555/32136232-4e840a6a-bc45-11e7-885d-e456e9939f31.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
@unarist does https://github.com/tootsuite/mastodon/pull/5567 solve this adequately in your view or should we re-open #5558? I can see arguments for both sides and am interested in hearing your opinion.

**Comment by Technowix** [comment]
fixed it on my end
