### ISSUE TITLE
Pressing 'x' on status on mobile doesn't clear or anything

### ISSUE THREAD

**Issue by zacanger** [tootsuite/mastodon#5564]
Pressing the `x` on statuses/new on Chrome Android beta doesn't clear the entered text, so after navigating to a list and coming back the previously entered text is still there. I'm not sure if this is a new issue or something I just noticed, but it doesn't feel like expected behavior. The instance I'm on is mastodon.social.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by matt-auckland** [comment]
Pretty sure this is intended behaviour (haven't looked at the code but after playing around with this on mobile that's what I feel), but this does raise the question about if the icon is too ambiguous in regard to it's function. Maybe a minimise `-` style button would be better suited?
