### ISSUE TITLE
Is there an API to lock/unlock ones account?

### ISSUE THREAD

**Issue by connyduck** [tootsuite/mastodon#5569]
Is there an API to lock/unlock ones account? I can't find it here: https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md
If not, treat this as a feature request :)

**Comment by nightpool** [comment]
what do you mean by "lock" or "unlock"? as far as I know, this isn't a feature mastodon has, so I'm not sure what such an API could do.

**Comment by connyduck** [comment]
![untitled](https://user-images.githubusercontent.com/10157047/32196820-3a55e332-bdc2-11e7-8fa9-6fd811fa8361.png)
Via `PATCH /api/v1/accounts/update_credentials` I can update display_name, note, avatar and header but not if the account is locked.

**Comment by connyduck** [comment]
Hi! I would really love to support this feature in Tusky, please help me out.
