### ISSUE TITLE
Add Nginx configuration setting to cancel oversized uploads early

### ISSUE THREAD

**Issue by ThomasLeister** [tootsuite/mastodon#5587]
As [ticky states](https://mastodon.social/@ticky/98944534853621387) Mastodon lets the user first upload a > 8 MB file and then tells the user that the file is too big. We could achieve better UX if the browser got an early "too big" response from the web server. This can be implemented via the [client_max_body_size setting in Nginx](https://stackoverflow.com/questions/15813564/checking-file-size-type-before-upload-using-paperclip-and-rails/15816368#15816368) 

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
iirc, client_max_body_size isn't exactly correlated with the size of the
stored asset which is why we don't currently do this.
