### ISSUE TITLE
Unable to disable 2FA on account if you lose your generator

### ISSUE THREAD

**Issue by toddself** [tootsuite/mastodon#5590]
You can't turn off two-factor authentication without entering a code from your app.  The problem is if your app gets deleted (or, since google auth doesn't back up the tokens, if you restore your iphone), you are unable to turn off 2FA and re-enable it, nor can you re-access your QR code to re set up 2FA.

Ideally you can turn off 2FA with one of the recovery codes generated from your account, so you can re-enable it in case you lose your generator.

(This is _not_ a request for help with my account, but rather an issue with usability.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by toddself** [comment]
Nevermind, this is a closed issue #4026, it looks like mastodon.social is running an older version of the code.

**Comment by nightpool** [comment]
Can't imagine why this would be an issue if we closed it in July.....
