### ISSUE TITLE
Question to the server architecture

### ISSUE THREAD

**Issue by WowItsDoge** [tootsuite/mastodon#5595]
Hi,
maybe someone can answer my questions  to the server architecture of mastodon.

1. If a user searches for a specific hashtag, is it searched only on the server of the user, or all servers?
2. How are the mastodon servers connected. If a new mastodon server instance is created, must the url be written in the settings of all the other servers, or can the instances self update the list of other instances?

I´m realy curious about this questions, so thanks in advances for your time ;)

**Comment by nightpool** [comment]
1. The former.

2. mastodon itself, or at least the federation code, has no concept of "instances". The network is foundationally driven by user-to-user interaction, not server-to-server interaction. What this means is that as you follow users, they send you their posts (or toots) as they make them—and conversely, when users follow you, you send them their toots. You can follow and discover any user on the network using either their full handle (type `@nightpool@cybre.space` into the search bar) or by using the remote follow button on their profile).

(this architecture is made performant by "de-duplicating", and never sending the same status multiple times to the same server. this uses the concept of a "shared inbox", which is multiple users who have the same "destination" for their posts—but that's an implementation detail and a performance optimization, not really part of the architecture)

**Comment by nightpool** [comment]
Mastodon uses the ActivityPub open standard as it's primary federation mechanism—you can read more about the server-to-server protocol used at https://activitypub.rocks/

**Comment by WowItsDoge** [comment]
Thank you for answering!

I will read the activity pub documentation, this topic seams interesting.

But one more question:
If I use the matodon api, can I querry each server about hashtags, or do I need then an account one each server?
The reason I am asking this, is because it would be a really usefull feature, like it is possible on Twitter.

**Comment by nightpool** [comment]
If you have a list of mastodon instances, you can query them for hashtag results. Mastodon itself does not have a list of such instances and is not interested in having one

**Comment by WowItsDoge** [comment]
Maybe I can use the api and build a tool to list all the hashtag query results from the mastodon instances.

I have found this server, which should be usefull to finde mastodon instance
https://instances.social/api/doc/
