### ISSUE TITLE
Idea: Memorial Pages

### ISSUE THREAD

**Issue by benhamill** [tootsuite/mastodon#5597]
I've been thinking (some of you will know why) recently about the idea of a toggle for mods that can switch an account into a sort of "memorial mode" to honor folks who have died. The simplest version would be one that just disallowed logging in as that person.

More complicated versions might put something like "in memoriam" on their profile, allow certain posts to be tagged for featuring (think, like, pinning a few different posts that exemplified the best of the person being memorialized), change the layout of the profile in some way, note their birth and/or death date, set up an `X-Clacks-Overhead` header with their name, or link to any sort of official announcement or donate-in-the-name-of sort of thing.

What do others think about this idea?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by impiaaa** [comment]
Last time I brought something like this up it resulted in the creation of #5444. Just thought I'd mention in case some ideas could cross over.

**Comment by benhamill** [comment]
Oh yeah. That's interesting. These two ideas for sure interact.

**Comment by Gargron** [comment]
I'd like to do this.

**Comment by benhamill** [comment]
Wow! That was fast! @Gargron Do you have any appetite for discussing the "more complicated" ideas I mentioned in the original post? Would it be better to start a new thread to discuss that? I envision some of that taking the form of answering what people actually would want or what it should look like, etc.

**Comment by jennifermf** [comment]
Thank you @Gargron!

I love the idea of an emergency instructions field, and I think I'd prefer that'd be visible to admin only, although I'm also thinking that there's some usefulness in the ability to name another user as someone who has permission to manage your account in the event you cannot.

This could be useful in the very sad event of someone's passing, but also in case someone's incapacitated in another way (in the hospital, loss of internet access, extended illness, etc).

-ghost@acp

**Comment by Failure404** [comment]
Wow. Is it not possible to undo memorialize? My cat jumped on the keyboard and now one of my users is memorialized.
