### ISSUE TITLE
timelines API 500 error: undefined method for a CustomEmoji

### ISSUE THREAD

**Issue by voteblake** [tootsuite/mastodon#5600]
My instance is throwing 500 errors when retrieving my user's timeline this morning:

`[4fd4ed79-8a20-4148-b854-180f5b5c3d4a] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=500 error='NoMethodError: undefined method 'visible_in_picker' for #<CustomEmoji:0x000000615bd5dba0>' duration=255.31 view=0.00 db=60.92`

I do not have any CustomEmoji on my instance, so the only thing I can think is that is from an account I'm following. I'm not familiar with how CustomEmoji work and would like pointers on how to troubleshoot from here. Long term it would be nice if these failures were limited to the affected toots rather than the whole timeline request.

I'm on tagged release 2.0.0

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
are you sure you're on tagged release 2.0.0? that method doesn't appear at
all in that release and there's nothing that could call it

**Comment by nightpool** [comment]
It sounds like you have mis-matched code and database schema, like you checked out a newer commit at some point (maybe accidentally) but didn't run migrations.

**Comment by voteblake** [comment]
I’ll look in to this. I’m running a container based on the docker compose
file included in the tagged 2.0.0 release but I suppose the container
definition may be running the application from the master branch.
