### ISSUE TITLE
Threading / replies suddenly broken.

### ISSUE THREAD

**Issue by taoeffect** [tootsuite/mastodon#5606]
I got a question from someone: https://mastodon.social/@dronegoddess/98958740241081965

And I was wondering why they were asking it. Upon investigation I discovered that threading is for some reason broken.

I had a huge thread of toots (~11 toots in total, replying to each toot), starting here: https://mastodon.social/@taoeffect/98958562738037086

And ending here: https://mastodon.social/@taoeffect/98958829787107073

Note that [my response](https://mastodon.social/@taoeffect/98958748811465863) to the questioner strangely appears in the web view, but [does not appear when looking at their toot directly](https://mastodon.social/@dronegoddess/98958740241081965), nor is their toot chained to the thread of tweets it's responding to.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
i'm guessing you got silenced by the instance admin. This isn't the place to discuss this, you have to take it up with the person moderating your server.
