### ISSUE TITLE
No confirmation when compose toot area is cleared

### ISSUE THREAD

**Issue by rakiru** [tootsuite/mastodon#5607]
Type a toot, but don't send it, then hit reply on another toot. Your unsent toot is deleted with no confirmation or way to recover it. While this _is_ as a result of a user action, it's also easy to do accidentally or absent-mindedly. A user may also intentionally do this if they're used to websites with inline replies, such as reddit.

There should be a(n optional?) confirmation along the lines of "You have an unsent toot. Are you sure you want to delete it?" if there is any text in the compose box.

(I typed out a whole introduction post, was trying to think if I was missing anything, went to reply to another toot quickly, and lost my post)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
This is a duplicate of #878 from back in April, 7 months ago. (This problem really needs fixing! Unexpectedly losing something that you typed out SUCKS. I still do it and I've been using Mastodon since April!)

**Comment by rakiru** [comment]
Oh, thanks, I must've missed that.
