### ISSUE TITLE
Issue with applications

### ISSUE THREAD

**Issue by itskiru** [tootsuite/mastodon#5609]
Hey it's should be cool if when you give access to an application, don't do it the next time and also when you for example: `Log in with a client Mastodon on Android, give access, logout, give access again into the "Application Authorized" the app is showed twice.`

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by itskiru** [comment]
Example: ![Example](https://sagiri.is-a-good-waifu.com/78c88b.png)

**Comment by Gargron** [comment]
They are two different apps with the same name because of how app registration works.
