### ISSUE TITLE
Remove most of Emoji and leave couple

### ISSUE THREAD

**Issue by Zirconiumirish** [tootsuite/mastodon#5624]
Hello, 

I would like to know if there is any way to remove most of the emoji and keep only 4 or 5.
Could you show me how to do it ?

Thanks for your help

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
Do you mean that you want to remove the emojis from the emoji picker, or that you want to make the emojis in other people's Mastodon posts invisible or text only, or something else?

**Comment by Zirconiumirish** [comment]
Yes remove from the emoji picker just leave 4 emoji

**Comment by sorin-davidoi** [comment]
There is no way to only show 4 or 5 emojis. After you use them, they will appear in the "Frequently used" section of the emoji picker.

**Comment by sorin-davidoi** [comment]
Even if you hide it through CSS, users can still post emojis (they can paste them into the input field).

**Comment by Cassolotl** [comment]
@Zirconiumirish Do you want to *prevent* users from posting with emojis even using emoji keyboards? Or do you just want to make the emoji-picker less overwhelming to users?

**Comment by Zirconiumirish** [comment]
I just want to make the emoji-picker less overwhelming to users =)

**Comment by Cassolotl** [comment]
Then I think this was closed in error. @sorin-davidoi seems to imply that they can be hidden with CSS...?
