### ISSUE TITLE
Allow users to set their own visual theme

### ISSUE THREAD

**Issue by ItchyBugReporter** [tootsuite/mastodon#5628]
I would like to see the ability for an individual to set select a visual theme that will be used after logging in. The admin could still set a default global theme that will be used when logging in or when a user first creates an account, but then the user could go into his/her settings to set a theme to be used for him/her personally after logging in.

I request this because the default "dark theme" that is used in Mastodon is very hard on my eyes, but I don't think too many admins would be willing to change it just for me.

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment]
This is already implemented (Settings -> Preferences -> Web). Available themes depend on your instance.

![image](https://user-images.githubusercontent.com/2109702/32555058-fc91db7e-c49b-11e7-8a67-14b7bba0ebb2.png)

**Comment by ItchyBugReporter** [comment]
I am in Settings -> Preferences, but I don't see a Web section and my browser's search function can't find it either.

**Comment by ItchyBugReporter** [comment]
These two screenshots show what I see in Settings -> Preferences. I am using Firefox ESR 52.4.0.



![mastodon_no_web](https://user-images.githubusercontent.com/20482407/32557671-ce39244c-c470-11e7-8687-9e421724fafd.png)
![mastodon_no_web1](https://user-images.githubusercontent.com/20482407/32557679-d24d4bf8-c470-11e7-9021-ede783b52864.png)

**Comment by sorin-davidoi** [comment]
That is because the admin has not added any themes - by default Mastodon only ships the blue-dark one.
