### ISSUE TITLE
Returning users come back to empty timelines

### ISSUE THREAD

**Issue by rainbowmultiverse** [tootsuite/mastodon#5634]
I just talked to someone who came back to an empty Home after a long time away from Mastodon. It's understandable that you'd want to clear out timelines for inactive people to save space, but it's not a great experience coming back to an empty Home.

Maybe Mastodon could invoke the new user thing where they follow admin accounts when it detects someone with an existing account and an empty timeline. Or just regenerate the timeline with a friendly "welcome back" message and some useful information about major changes since the last version they used.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sdukhovni** [comment]
This is happening to all of my users as well. Looking at the output of journalctl while inactive users log in, no `RegenerationWorker`s are being run. I also poked around at the rails console to see whether the `regenerate_feed!` method from `app/controllers/concerns/user_tracking_concern.rb` was being run at all, and it doesn't seem to be:

    # Before inactive user logs in
    > User.where(account_id: 666)[0].last_sign_in_at
    => Tue, 04 Jul 2017 14:45:56 UTC +00:00
    > User.where(account_id: 666)[0].current_sign_in_at
    => Wed, 05 Jul 2017 22:10:52 UTC +00:00
    
    # Inactive user logs in, sees empty home timeline
    > Redis.current.get("account:666:regeneration")
    => nil
    
    # I manually set the flag that should be set by regenerate_feed!
    > Redis.current.setnx("account:666:regeneration", true) == 1 && Redis.current.expire("account:666:regeneration", 86400)
    => false
    # User reloads the page
    # They're now getting their feed directly from the database and their home timeline is populated
    # I manually enqueue a RegenerationWorker
    > RegenerationWorker.perform_async(666)
    => "deadbeefdeadbeefdeadbeef"
    # The RegenerationWorker is run and finishes more or less immediately according to journalctl

**Comment by jimfenton** [comment]
This happens to me (as a returning user). Is there a workaround to get my home timeline back?

**Comment by maximevaillancourt** [comment]
This appears to be occurring today still. Didn't log into Mastodon for a few weeks, and now my timeline is empty with this message:

![2021-01-05-193244_587x659_scrot](https://user-images.githubusercontent.com/8457808/103714764-ea640e00-4fb6-11eb-8c87-978e667c5cc8.png)

("Loading... Your home feed is being prepared!")

**Comment by Cassolotl** [comment]
The home timeline is populated within a minute or two, no?

**Comment by maximevaillancourt** [comment]
> The home timeline is populated within a minute or two, no?

It took roughly 48 hours until the feed came back to normal. Not sure if it's a per-instance kind of issue, or a larger Mastodon source code issue :shrug:

**Comment by Cassolotl** [comment]
Wow, that's a lot longer than it should be! Usually if I wait about 30 seconds it comes back.
