### ISSUE TITLE
Unthemed scroll bars in Firefox

### ISSUE THREAD

**Issue by archaeme** [tootsuite/mastodon#5638]
In Firefox, the scroll bars use the system theming instead of Mastodon's.

Chrome 62:
![screenshot at 2017-11-09 00-57-46](https://user-images.githubusercontent.com/802788/32590558-045ad4d0-c4e9-11e7-8727-14f99bac4a50.png)

Firefox 56:
![screenshot at 2017-11-09 00-54-02](https://user-images.githubusercontent.com/802788/32590548-eefded84-c4e8-11e7-9599-5862e8c3d5f7.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nullkal** [comment]
Related to #5562

Unfortunately, scrollbar's style is an extension of Webkit and not the standard.

**Comment by sorin-davidoi** [comment]
Nothing we can do here until Firefox allows themed scrollbars - see the linked issue for a workaround if you want to hide them.
