### ISSUE TITLE
image-only toots don't have any space to click on to load them in the 4th column

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#564]
![image](https://cloud.githubusercontent.com/assets/175467/22397426/59a36d56-e571-11e6-97a0-08c5497fc34f.png)

**Comment by Gargron** [comment]
This became a thing in #140 - do you have any suggestions for how it should work instead?

**Comment by wchristian** [comment]
That probably deserves more input from the bulk of the users, but i think any click that falls through to the background of the toot should expand it. Maybe use an appropiate css cursor for it?

Possibly alias or row-resize?

https://css-tricks.com/almanac/properties/c/cursor/

**Comment by blackle** [comment]
the ... menu has an "expand" option which also does the job

**Comment by charliegreen** [comment]
This is also relevant for toot'd links, btw

**Comment by marrus-sh** [comment]
I think the ideal solution for this, also related to keyboard input (#376) would be for Mastodon to be aware of which column has focus (and perhaps indicate this visually—making the icon at the top glow for example). Clicking on the neutral space of a toot in a column without focus would give the column focus, while clicking on the neutral space of a toot in a column *with* focus would just open the toot. This way, a double click would always be assured to open a toot, but changing focus is still easily done with the mouse. (Ideally changing focus would also be possible with the left/right arrow keys.)

This is a prerequisite for any more advanced keyboard controls, like favouriting or boosting a status from the keyboard, imo.

**Comment by Gargron** [comment]
>the ... menu has an "expand" option which also does the job
