### ISSUE TITLE
toot visibility in public timeline inconsistent?

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#565]
This one shows up in it fine:

https://mastodon.social/users/Mithaldu/updates/944489

This one which seems superficially similar does not:

https://mastodon.social/users/Mithaldu/updates/944313

**Comment by Gargron** [comment]
Oh but the second one is a reply to slime's post. Replies don't show up in public timeline!

**Comment by wchristian** [comment]
Aha, then it is the first toot that is buggy, as it is also a reply, but shows up. The difference of course being it is a reply to myself.

**Comment by Gargron** [comment]
Replies to self don't count as replies! It's intended, so toot chains can show up on PTL, but conversations can't

**Comment by wchristian** [comment]
Huuuh. Is there a difference between replies and replies with @ stuff at the front?

**Comment by Gargron** [comment]
No! @ s are just mentions. They play no role in what "replies" are (== referring to a certain toot).

**Comment by wchristian** [comment]
Hmm, i can't tell whether that's my preconceptions from hellbird, or whether this would warrant some education at some point in the future, but for now it seems working as intended, bar some user confusion. :)
