### ISSUE TITLE
Angle brackets should delimit URLs in the body of toots

### ISSUE THREAD

**Issue by zackw** [tootsuite/mastodon#5654]
In https://mastodon.social/@zwol/98982414809236980 I wrote

> `... the UMass-Amherst Science Fiction Society <http://www.umass.edu/rso/scifi/>'s filk circle ...`

The code that scans for URLs in the body of a toot interpreted this as linking to `http://www.umass.edu/rso/scifi/%3E's`.  This Is Wrong.  `<` and `>` are the official way to delimit URLs in running text, have been ever since URLs were invented.  The URL should be understood to end just before the `>`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
That's part of Markdown syntax but we don't support Markdown. Is there any reason to even write text that way under these circumstances?

**Comment by nightpool** [comment]
@gargron markdown doesn't use angle brackets

but I'm interested in the answer nonetheless, it feels very weird to use
angle brackets to delineate urls in a toot

**Comment by Gargron** [comment]
@nightpool No, it does. There is the `[Text](url)` syntax but also `<url>` syntax. The latter performs linking, because autolinking isn't actually part of Markdown, even though it's done by most implementations anyway.

**Comment by zackw** [comment]
@nightpool @Gargron Using angle brackets to delimit URLs is not part of Markdown.  It's recommended practice according to the official syntax specification for *URLs*: [RFC 3986, Appendix C](https://tools.ietf.org/html/rfc3986#appendix-C).  It is especially useful for plain-text contexts that auto-linkify URLs but don't implement any other markup that would let you control where the URL ends, such as ... toots.

I gave an example in the original bug description of how this would be useful.

**Comment by Cassolotl** [comment]
Mastodon linkifies URLs, so why would one use triangle brackets?

**Comment by zackw** [comment]
@cassolotl Angle brackets are (would be, anyway) useful __because__ it linkifies URLs.  The entire point here is to have an explicit way to control where the linkifier thinks the URL ends. Again, see the example in the original bug description.

**Comment by Cassolotl** [comment]
I see! Thank you. :)

**Comment by trwnh** [comment]
So this essentially bypasses URL handling logic when calling a specific URL and delimiting it with <>? Although for what it's worth, Mastodon's current behavior is to treat the > as part of the URL, which ends up breaking it!

https://perishablepress.com/stop-using-unsafe-characters-in-urls/

>More about “unsafe” characters from RFC1738:

>Characters can be unsafe for a number of reasons. The space character is unsafe because significant spaces may disappear and insignificant spaces may be introduced when URLs are transcribed or typeset or subjected to the treatment of word-processing programs. The characters “<” and “>” are unsafe because they are used as the delimiters around URLs in free text; the quote mark (“"”) is used to delimit URLs in some systems.

Probably should also mention that a quote mark (") also ends up breaking the URL in Mastodon. Possibly related issues: #6701, #6031

**Comment by zackw** [comment]
> So this essentially bypasses URL handling logic when calling a specific URL and delimiting it with <>? Although for what it's worth, Mastodon's current behavior is to treat the > as part of the URL, which ends up breaking it!

I'm not sure what you mean by "bypasses URL handling logic", but the change I'm specifically asking for is to __not__ treat the `>` as part of the URL.

**Comment by trwnh** [comment]
@zackw I mean that the proposal implies that the text parser should essentially support wrapping whatever it finds inside <> in an <a href> tag -- "URL handling logic" meaning the function that Mastodon uses to determine what is and isn't a URL. It would be problematic to say that > should be explicitly disallowed in URLs, since it's only "unsafe" or "discouraged" -- it's still a valid URL in some cases.

**Comment by chrysn** [comment]
With codl's clarifying remark on `>` legality in URLs, is this at a point where a clean patch to that effect (ie. one removing `>` from the auto-linked characters set, so that `<>` terminated URIs would still be left to the auto-linker but don't swallow the `>`) be accepted?

**Comment by nightpool** [comment]
@chrysn we would probably accept such a patch, but i don't believe it would address the concerns of this issue

**Comment by nightpool** [comment]
we override the regex on this line:
https://github.com/tootsuite/mastodon/blob/master/config/initializers/twitter_regex.rb,
i believe the change required is to add > to the character class on line 5,
inside of :valid_url_path_ending_chars

**Comment by chrysn** [comment]
Without understanding all of the construction I agree it should go into the negated part of :valid_url_path_ending_chars, and probably also in the negated part of :valid_general_url_path_chars (because, as @codi pointed out, nothing with a < or > inside it is a legal URI or even IRI).
