### ISSUE TITLE
Add setting to autoplay GIF avatars again

### ISSUE THREAD

**Issue by SirCmpwn** [tootsuite/mastodon#5656]
I actually liked this behavior before.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I'm on a 2.0.0 instance and I see it on /settings/preferences:

![screen shot 2017-11-11 at 23 53 48](https://user-images.githubusercontent.com/6607512/32694575-a3aa9008-c73b-11e7-8af7-bd8ab28ac36c.png)

Do you see it? What's your instance and version number?

**Comment by SirCmpwn** [comment]
That setting doesn't apply to avatars, only to toots with gif content.

**Comment by Cassolotl** [comment]
Ohhhh I see! I'm sorry, my mistake. And yes, this could be nice as a toggle.

**Comment by Gargron** [comment]
Oh we already done this

**Comment by SirCmpwn** [comment]
Where's the setting? I don't see it.

**Comment by Gargron** [comment]
Autoplay GIF setting now affects avatars just like it was supposed to

**Comment by SirCmpwn** [comment]
Oh, sweet. Thanks!
