### ISSUE TITLE
troubles seeing all of a video

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#566]
This toot has a pretty large scale video, but when viewing it in a column it appears very small, and full-screening requires right-click, view controls, full screen click:

https://mastodon.social/users/headpats_bot/updates/944795

Also, in the single toot view there, it's cropped top and bottom.

**Comment by noiob** [comment]
I'd prefer to have the browser's controls visible when playing the video, it's also helpful with sound and stuff like pop-out video (at least in Safari)

**Comment by noiob** [comment]
possibly related to #485

**Comment by wchristian** [comment]
I like @noiob's idea. Have a click on video content enable the controls.

I think the video should also expand vertically to undo the cropping, but having the controls pop up and announce their presence would help.

**Comment by wchristian** [comment]
The video in the link above is still cropped. Is this not yet deployed?
