### ISSUE TITLE
Allow multiple image file selection when uploading

### ISSUE THREAD

**Issue by mechagrunty** [tootsuite/mastodon#5663]
A small inconvenience that I found when trying to upload 2 to 4 images to a toot: Being unable to select multiple images at once. Can only select and upload 1 image file at a time right now. Not sure if intended to be like this, but it makes the process a bit slow and frustrating, especially when browsing large collections of image files.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
Thanks @Cassolotl!

Please direct discussion to the linked issue.
