### ISSUE TITLE
Please render custom/local emojis in biographies.

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#5666]
Please render custom/local emojis in biographies.

I don't know if this is a bug or a feature request, but there are users who try to add those custom emojis to their bio and they are not rendered (resulting in unsatisfied users).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ffffluffy** [comment]
While we're at it, custom emojis are not rendered in the profile's name too.

**Comment by wxcafe** [comment]
Loads of users are asking for this yeah
