### ISSUE TITLE
css cursors on expanded user view make it hard to tell when over follow button

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#567]
In the expanded user view the user can click on the background and open a new page with user info, or follow. I suspect the follow button is used more often. However the CSS cursor for the two actions is the same, and without a clear border around the button it's hard to tell when one's actually on it.

![image](https://cloud.githubusercontent.com/assets/175467/22397746/d04c1d20-e578-11e6-972a-35b6dc467198.png)
![image](https://cloud.githubusercontent.com/assets/175467/22397752/db94b2be-e578-11e6-9791-19bd4ab5fc19.png)

**Comment by ashfurrow** [comment]
This looks resolved now, can you confirm?

**Comment by wchristian** [comment]
Yep, that's been fixed. :)
