### ISSUE TITLE
Change TOOT html text

### ISSUE THREAD

**Issue by Zirconiumirish** [tootsuite/mastodon#5672]
Hello there I would like to know which file to modifiy to change the TOOT button on compose sidebar ?

Thanks
* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by egypturnash** [comment]
config/locales/en.yml, app/javascript/locales/en.json

And to answer what is probably your next question, [this changelog](https://github.com/egypturnash/mastodon/commit/b9586c79629756dd0332b17f74a3bd13dae39a3f) is what I did to change the toot length on my own instance, as well as some additional code to force a CW on really long toots if you decide to let your users be verbose like I did. <3

**Comment by nightpool** [comment]
(please remember to close the issue if you feel it's been resolved!)
