### ISSUE TITLE
'filtered posts'? A new posting option visible only to a predefined 'group/list' of accounts–Companion to/extension of #2658

### ISSUE THREAD

**Issue by paralithode** [tootsuite/mastodon#5677]
Inspired by filtering options on platforms facebook and livejournal, this setting, on the privacy dropdown below 'direct', would allow accounts to make posts that only appear on the home timelines of a preselected list of accounts. Multiple filters could be described and named, and they could be assigned through a tagging system as described in #2658 

This is in effect similar to how direct messages work, except without what might be a preventatively-huge number of account names taking up the majority of the post. While a direct message is usually a post specifically -to- someone, a filtered post would be a message -for- a broader but limited group, like a livejournal friends filter – for instance a user's closest friends, behind the scenes talk between a creative team, or even a kind of bonus content channel patrons could subscribe to through patreon. Possibly an additional notification category could alert users of new posts their account was listed in.  

This would allow far greater privacy & agency for users over how to use their account. They could make posts knowing that they would have full control over who would see their more sensitive or private content, while still freely allowing other accounts to follow them for their regular, public content. These posts would still be visible to admin, and could still be reported for any abusive, illegal or otherwise rule-breaking content.

Thank you to devs for reading, and I'm sorry if this is impossible to do or a clone. I tried to search, like I always do but I never seem to search enough keywords to discover duplicate issues...! Filtered, group, tagged, private, list, &c didn't seem to uncover anything.
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
Afaik groups are already being worked on (cc @Gargron) so I’m closing this issue
