### ISSUE TITLE
UI scaling options for large displays

### ISSUE THREAD

**Issue by DreadnaughtSec** [tootsuite/mastodon#5678]
UI columns should be scalable by the user to provide better support for large displays such as 27+ inch or 21:9 ratio. 
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment]
> Perhaps even the addition have being able to display both local and federated timelines side by side to fill wasted real estate.

Toggle column option,  click "Pin".

**Comment by DreadnaughtSec** [comment]
> Toggle column option, click "Pin".

Didn't see that, thanks. Suggestion updated.

**Comment by wxcafe** [comment]
Closing this in favor of #5736 that has a broader scope
