### ISSUE TITLE
Let users have full-text search of their own posts

### ISSUE THREAD

**Issue by PubliqPhirm** [tootsuite/mastodon#5684]
Users should have the ability to access full-text for all the toots they authored.  Why? For finding old toots and threads that either:

1. You did not expect to become important in the future
2. You don't remember which hashtag you used and it wasn't something obvious

Toots that you boosted should be excluded from this search.

* * * *

- [y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [n/a] This bug happens in a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I think this is a really good idea! I think it's also a duplicate of #4293? "Full text search of my own posts", from July. So you're not the only one who wants it! I recommend heading over there and subscribing, adding your thumbs-up, commenting if you'd like to add anything. (And if you're comfortable that this is a duplicate you could go ahead and close it.)

**Comment by PubliqPhirm** [comment]
Closing as duplicate.

Do you want me to copy any of my text from here as a comment on the original report?

**Comment by Cassolotl** [comment]
I tend to copy over anything I've written that isn't covered in the older topic when this happens to me, if that helps? If not I just thumbs-up and subscribe. :)
