### ISSUE TITLE
Ability to change more settings in admin panel

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#5693]
I'm asking for this because basically, as Mastodon gets more popular and continues to be hard to install, people are going to be paying other people to host their instance for them more and more - and for that you don't need much technical ability, you just do everything admin-ish through admin settings. Being able to customise things like the character limit through admin settings instead of having to ask your host to do it is going to become more and more important.

Inspired by [this toot by a non-techy admin](https://queer.town/@alice/99002490323809366).

Signed, another non-techy wannabe admin.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Fiona** [comment]
My wife is the linked toot and she asked me to point out that she meant bios as well as toots

**Comment by wxcafe** [comment]
So as mentioned by @Gargron in #5697, configurable character limits are not a planned feature. Allowing more stuff to be configured from the graphical admin panel would be great tho, so I’m renaming this issue

**Comment by Gargron** [comment]
Please either add a checklist for things you think are lacking in the admin settings, or open separate issues for each setting. As-is, I do not know what this issue is asking for (character limit is not planned to be configurable)

**Comment by Cassolotl** [comment]
See also: *Let the admins easily setup the character limits #12265*
