### ISSUE TITLE
Style the scrollbars

### ISSUE THREAD

**Issue by mattcoxonline** [tootsuite/mastodon#5695]
I'm using Firefox on Mac - the latest stable and latest stable OS build - and the scrollbars look like this:

<img width="645" alt="screen shot 2017-11-14 at 13 55 11" src="https://user-images.githubusercontent.com/673542/32780969-79dfde04-c943-11e7-989e-d9a82bf4317c.png">

But it's possible to style the scrollbars so they work better with the default theme colors. Here is an example from another product:

<img width="192" alt="screen shot 2017-11-14 at 13 56 38" src="https://user-images.githubusercontent.com/673542/32781035-c7c8d2b0-c943-11e7-86f3-6a4b64bf2ba9.png">

 
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment]
There is nothing we can do about this - see #5562.

**Comment by mattcoxonline** [comment]
The product I referenced above was Microsoft Teams - but it seems they are using some sort of Javascript to accomplish what they are doing. Nevermind.
