### ISSUE TITLE
assets:precompile fails without error

### ISSUE THREAD

**Issue by almafeta** [tootsuite/mastodon#5696]
When attempting to run `RAILS_ENV=production bundle exec rails assets:precompile` as per https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md, compilation fails without any error code:

```
Webpacker is installed 
Using /home/mastodon/live/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:


```

There are multiple newlines, but no explanation as to why compilation failed, so it does not look like an OOM error or permissions error at first glance.

* * * *

- [+] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [+] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). 09d81de (v2.0.0)

**Comment by almafeta** [comment]
After about the fifth run without any changes, it finally *did* return an error - an out-of-memory error.  So this issue is not with the software, and I'm closing this issue.

Future Googlers: 1GB of memory is not enough to precompile assets!

**Comment by jgroszko** [comment]
Does anyone have any tips on how to precompile the assets on another machine, and then move them out to my server?

**Comment by oufmilo** [comment]
I have the same problem when i run assets:precompile, i never have this before...
Someone have an idea ?
Thanks

```
yarn install v1.16.0
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 22.85s.
Compiling…
Compilation failed:
```
