### ISSUE TITLE
Feature request: Foreign timeline as column (specific other instance) (dupe #1053)

### ISSUE THREAD

**Issue by NathanHawks** [tootsuite/mastodon#5698]
Please implement the ability to _add a column_ containing the _local timeline from a specific instance **other than your own_** local instance.

**Comment by Cassolotl** [comment]
This might be a duplicate of #1053 - what do you think?

**Comment by NathanHawks** [comment]
I think:

- yes
- wow people are overthinking this

Sorry for the housekeeping and thanks for routing me to the correct issue.

**Comment by NathanHawks** [comment]
Closing as dupe of https://github.com/tootsuite/mastodon/issues/1053
