### ISSUE TITLE
Edit an existing toot

### ISSUE THREAD

**Issue by mareklach** [tootsuite/mastodon#5711]
[Issue text goes here].

This suggestion is very simple. Even with old toots the user sometimes makes mistakes, or does not express themselves very well. It would be cool to have the ability to _edit existing toots_, which could be an option in the toot drop-down right above _delete_.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
This is a duplicate of an older issue that was closed a while ago: #256

I still want to be able to edit toots though. I think it would be okay if the toot could only be edited for a few minutes after posting; it's usually typos I want to fix!

**Comment by mareklach** [comment]
Oh, I see, interesting discussion on there. I did not find anything older by searching issues, but it's true that I only checked open ones. Yes, we still need this functionality and limiting for how long one could edit is definitely a fair idea. Perhaps toots that are like under a few seconds old could not be pernmently saved yet, but only present at the user-client level and editable that way...
