### ISSUE TITLE
DMs should have their own column or similar special treatment on the web UI

### ISSUE THREAD

**Issue by rtucker** [tootsuite/mastodon#5715]
Currently, DMs are only shown on Home and Notifications (as a Mention).  For folks who are fairly active, DMs are very easy to lose in the shuffle.

I propose one or more of the following:

1) Make DMs their own special notification type, separate from Mentions, so that they can be independently turned on/off in the Notifications column, selected for e-mail notifications, etc.

2) Create a Direct Messages view/column, which can be selected/pinned from the Getting Started page like the other views

3) Have some sort of visual, persistent indicator of unseen DMs (and a way to determine which DMs are unseen, and set DMs seen/unseen so the reminder can be kept around for later, for those of us who lose thoughts when context switching)

I do understand that DMs are not reliable or secure or even respected by non-Mastodon instances etc etc, but this isn't about reliable and secure messaging, this is about improving the user experience for what we do have.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by jeroenpraat** [comment]
There is a work in progress pull request here: https://github.com/tootsuite/mastodon/pull/4514

**Comment by wxcafe** [comment]
👍

**Comment by nolanlawson** [comment]
Related: #3819

**Comment by wxcafe** [comment]
let's move the discussion there yeah, closing
