### ISSUE TITLE
Regex filter behaving strangely

### ISSUE THREAD

**Issue by Felthry** [tootsuite/mastodon#5754]
The filter (\b[A-Z]{3,}\b\s*){3,} (composed by @ashkitten@dev.glitch.social), which is meant to filter out any post containing three or more consecutive all-caps words of three or more letters each, works fine on the regex testing tool https://regexr.com/ but on Mastodon itself it manages to filter out some all-lowercase posts, somehow. Some examples of posts it filters out erroneously: 
https://glitch.social/@soft_chomps/99021453204843256
https://glitch.social/@soft_chomps/99021535761032967
https://slime.global/@masklayer/99021437765713188

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
Well...Mastodon does case-insensitive match.

https://github.com/tootsuite/mastodon/blob/2bcc81700c586a543e849e222c640df89da7fcb0/app/javascript/mastodon/features/ui/containers/status_list_container.js#L18

**Comment by Felthry** [comment]
So what if someone wants to filter out all-caps posts? How would one do that?

**Comment by wxcafe** [comment]
I mean, the whole filtering system should be changed anyways. If you don't mind I'm going to close this so we can track filtering improvements in already-opened issues about that subject.
