### ISSUE TITLE
After upgrading to 2.0.0, I got only blank page after logging in

### ISSUE THREAD

**Issue by fweng322** [tootsuite/mastodon#5755]
[Issue text goes here].

I got the same problem as #3923 after upgrading from 1.6.0 to 2.0.0 (by checking out git branch v2.0.0).  Ruby was upgraded to 2.4.2, and db is migrated successfully.  The login or preferences pages were shown correctly, but after logging in the page became a grey blank.  I tried to change the default privacy option and save, but still the same.  I also made sure user mastodon have access to all the directories.

Any idea?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
* It looks like a duplicate with #3923 but the solution didn't work.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by neoresin** [comment]
@fweng322 did you end up finding out what was up with your instance with regards to the blank page? Trying to setup my instance and I'm getting a blank page as well. It's brand new, no errors in the nginx proxy I'm running in front of it or in any of the other logs for any of the docker containers brought up by docker-compose. I'm able to get into the preferences pane under https://<instance_name>/settings/, as well as the admin page, but it always loads a blank page when trying to load https://<instance_name>/web/getting-started. Does this signify anything?

**Comment by fweng322** [comment]
@neoresin  No.  I didn't find out what was up.  My final solution is to rename the whole repository and re-clone the code from git, and did upgrade steps like migrate:db , precompile assets and so on.  Finally don't forget to copy public/system/* to the new one.

After upgrading to 2.0.0 (and now 2.1.0) I got another issue #6130 but so far I can't find out why either.
