### ISSUE TITLE
http://localhost:4000/

### ISSUE THREAD

**Issue by wolfie1910** [tootsuite/mastodon#5758]
Hello!
Everytime I try to acces localhost:4000, I recieve following logs:
streaming_1  | ERR! 5396b676-d926-4366-91e4-8bb942763a84 Error: Missing access token
streaming_1  | ERR! de54c49a-c327-4533-b019-4350b4dff82d Error: Missing access token

also my browser shows me: {"error":"Error: Missing access token"}
I'm trying to create an instance, but first am testing it on localhost.
Thank You. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
The web service is on 3000, not 4000

**Comment by wolfie1910** [comment]
Ok, I understand, but now I am trying everything with a domain. I configured Nginx step by step as the production guide says, and am not able to https, help please?
