### ISSUE TITLE
content warning'd toot contents not hidden in user page

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#576]
e.g. https://mastodon.social/users/Mithaldu

**Comment by duckinator** [comment]
Also not hidden on individual toot pages. E.g., https://mastodon.social/users/pup/updates/1225909

**Comment by ashfurrow** [comment]
It looks like this is working now; I've tested both the links you two posted. I'm going to close, but if the issue hasn't been solved to your satisfaction, please re-open. Thanks!
