### ISSUE TITLE
404 Record not found when someone try to follow an account from my server.

### ISSUE THREAD

**Issue by clement-analogue** [tootsuite/mastodon#5765]
People cannot follow accounts from my server. It always returns `404 Record not found`.
`production.log` is empty.

It is something new, but I don't for how long it is like that.

If someone from another instance unfollow an account from my instance, then, it cannot be followed back again. Neither Remote follow nor follow from the web interface are working.

FYI, my instance is
https://toot.forumanalogue.fr/
and we tried with
https://framapiaf.org/
and 
https://mamot.fr/

All of them are running Mastodon v2

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by clement-analogue** [comment]
I found the solution. It turns out it is a problem because `WEB_DOMAIN` and `LOCAL_DOMAIN` are different. In this case, Webfinger failed, so I just added 
`
Redirect permanent /.well-known/host-meta https://toot.forumanalogue.fr/.well-known/host-meta
`
in the apache virtual host corresponding to `LOCAL_DOMAIN`.

**Comment by albjeremias** [comment]
@clement-analogue ... i have many redirects doing this.. but i have no idea why it stops working... can you please tell me how you found out where the bug was? I can't find anything on the logs...

**Comment by albjeremias** [comment]
I fixed it now... some misconfiguration again on my nginx.. :\

**Comment by jpfox** [comment]
My apache conf had caused same trouble. Just for infomation, I've corrected it this way :

This directive (written for letsencrypt certs renewal) :

    ProxyPass /.well-known/ !

has been replaced by this one :

    ProxyPass /.well-known/acme-challenge !

because Mastodon use this url : /.well-known/host-meta to know which url to use for webfinger. Hoping it could help other instance admins
