### ISSUE TITLE
Bug: Column settings not saving properly sometimes, I think?

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#5779]
I replied to someone else, and my reply should be showing up in my Home feed, but it's not. The privacy setting is followers-only, if that helps? (Edit: never mind, it happens with Public toots too!) I refreshed and it's still not showing up.

![screen_shot_2017-11-21_at_20_20_59](https://user-images.githubusercontent.com/6607512/33095180-a305b6ca-cefa-11e7-83cb-6e4011ca2ddf.png)

The URL of the toot that's not showing up: https://cybre.space/@cassolotl/99044265461816736

Edit: To clarify, this is happening consistently, not just with this one toot!

My instance is cybre.space, which is running on 2.0.0. I'm using Chrome on Mac.

**Resolved, kinda:** It was because I had set my "Show replies" to off in the Home feed earlier, and then I turned it on but it didn't save/stick. This isn't the first time that a setting change in one of the columns hasn't saved - I change my notifications settings fairly often and I have to wait for the loading bar to finish its thing and then reload the page several times to make sure the settings are saved properly. :S

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
>and then reload the page several times to make sure the settings are saved properly. 

Settings save is delayed by 5 seconds to ensure that subsequent settings changes don't spam the server, so if you refresh straight away after changing a setting, it won't save. This is confusing but imo under normal circumstances people have no reason to close the page sooner than 5 seconds after changing a column setting...
