### ISSUE TITLE
Display name clips into timestamp

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#578]
![image](https://cloud.githubusercontent.com/assets/834880/22405330/289497ba-e695-11e6-9ecb-0d23b17f864a.png)

**Comment by wchristian** [comment]
I think that's intentional, as the display name can be quite big, but the timestamp is of a known size. So if  the display name is too big, its overflow is hidden.

**Comment by Gargron** [comment]
This is intentional! I wish the relative times were a bit shorter (like 3m instead of "3 minutes ago") but I'm a bit constrained here - either I use the strings from react-intl, or I have to define all of the string on my own for every language.
