### ISSUE TITLE
The whitespace around a status should be clickable (not just the space around the letters

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#579]
![image](https://cloud.githubusercontent.com/assets/834880/22405428/8b44d860-e696-11e6-8ecd-ee9d09ae929c.png)
The blue part is clickable/linked, but the green (padding) should be too ideally.

**Comment by wchristian** [comment]
Related to #564

**Comment by Gargron** [comment]
Closing for the same reason as #564 (this change has been deliberately requested for a11y purposes)

**Comment by wchristian** [comment]
@Gargron Not sure i understand this right. Having the whitespace of a toot be clickable is bad for a11y? Can you refer to the comment that describes why that is so?

**Comment by Gargron** [comment]
@wchristian https://github.com/tootsuite/mastodon/issues/140#issuecomment-258791996
