### ISSUE TITLE
Get location of users

### ISSUE THREAD

**Issue by Zirconiumirish** [tootsuite/mastodon#5790]
Hi is there any way on the website to ask the location of people ?
Where could we find the results if it's possible
* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment]
There is no way to get the location of the users. What is your use case?

**Comment by Zirconiumirish** [comment]
Im using this for a professionnal application and juste need a better location than IP

**Comment by m4sk1n** [comment]
`to ask the location of people`
Just mention them and ask them, where they are now 😉
For better accuracy you can ask them for their more accurate location…
