### ISSUE TITLE
When an account on an instance is deleted by the user, completely delete, not suspend it

### ISSUE THREAD

**Issue by mareklach** [tootsuite/mastodon#5794]
##[Issue text goes here].

If an account on some Mastodon instance is deleted by the user, free their username and email up for registration again, instead of the current error message: ''The page you were looking for doesn't exist anymore.'' The current situation prevents users from creating a new profile with an old email address.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
>The current situation prevents users from creating a new profile with an old email address.

E-mail address gets deleted. *Username* does not, and this will not change. If you don't want to lose your username don't delete your account... It says so on the page:

>**This will permanently, irreversibly remove content from your account and deactivate it. Your username will remain reserved to prevent future impersonations.**

**Comment by Cassolotl** [comment]
#4614 might be of interest?
