### ISSUE TITLE
The fresh installation does not work

### ISSUE THREAD

**Issue by katedutch** [tootsuite/mastodon#5800]
ActionView::Template::Error (Name or service not known):
1: - thumbnail = @instance_presenter.thumbnail
2: = opengraph 'og:site_name', t('about.hosted_on', domain: site_hostname)
3: = opengraph 'og:url', url_for(only_path: false)
4: = opengraph 'og:type', 'website'

app/presenters/instance_presenter.rb:40:in thumbnail' app/views/shared/_og.html.haml:1:in_app_views_shared__og_html_haml___2584687245308882855_70207046943620'
app/views/about/show.html.haml:7:in block in _app_views_about_show_html_haml___4266306660868289071_47204006513080' app/views/about/show.html.haml:4:in_app_views_about_show_html_haml___4266306660868289071_47204006513080'

**Comment by coreyreichle** [comment]
Was distro and release are you using to deploy?

**Comment by Gargron** [comment]
>Name or service not known

Looks it cannot connect to Redis or PostgreSQL. Check the DB_HOST and REDIS_HOST values in `.env.production`. The defaults are for the Docker setup.

**Comment by katedutch** [comment]
>REDIS_HOST
oops, i missed it out, thank you
