### ISSUE TITLE
Fresh install displays only empty pages

### ISSUE THREAD

**Issue by Starling000** [tootsuite/mastodon#5803]
Set up a server following the standalone installation guide, all three services plus nginx are running, but when I point my browser at the URL it redirects to /about and displays an empty page (absolutely nothing there in the source viewer).

I'm not sure where these pages are even stored on the server, so I don't know how to begin fixing what's wrong.

edit: I've tried bringing down the services and bringing them back up and now I'm getting a 502 error instead.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Starling000** [comment]
This was due to not following instructions closely, I neglected to precompile assets and then start all the mastodon services as described in the production guide.

**Comment by DaveT-T** [comment]
Had same issue and pulled my hair out for days.  Reinstalled everything multiple times.

MY ISSUE was an nginx error.log full of permission denied errors.
/var/log/nginx/error.log

for my setup using standard mastodon install instructions nginx runs as 
user www-data

and user www-data was blocked from using /home/mastodon/live/public

solution was changing permissions logged in as root

chown -R www-data:www-data /home/mastodon/live/public
chown -R www-data:www-data /home/mastodon/live

after this instantly everything worked.   Was hard to come by this solution so posting here for others to find = : )
