### ISSUE TITLE
add visual indication of unseen notifications in the getting started column

### ISSUE THREAD

**Issue by chriswmartin** [tootsuite/mastodon#5809]
when the notification column is unpinned it would be useful to have a visual indication of unseen notifications. rough mockup attached.

![unpinned-note-column](https://user-images.githubusercontent.com/17181697/33225167-396c6eda-d138-11e7-8917-77f12f34d26c.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by joyeusenoelle** [comment]
Oh god, please make this optional. :)

**Comment by sorin-davidoi** [comment]
Unfortunately, as far as I know, there is no concept of "seen" notifications (at least not in the way it works with chat applications). We could work around it by in the frontend though (but it won't be stored in the backend and synced between applications).

**Comment by chriswmartin** [comment]
@joyeusenoelle absolutely agreed. I wouldn't want this to turn into facebook-like notification spam or add visual clutter. I just think it would be useful to those that want it.

**Comment by chriswmartin** [comment]
@sorin-davidoi since this would only appear for those with unpinned notification columns I was thinking that it would show the number of notifications since the column was last opened, if that makes any sense
