### ISSUE TITLE
"Upload an image" overlay won't go away if I decide not to upload something after all

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#5822]
I'm on a Mac, on Chrome, Mastodon 2.0.0 (cybre.space). This happens to me often-ish.

I picked up an image file from my desktop and went as if to drop it on Mastodon to upload it into a new toot. It did the thing, as expected:

![screen shot 2017-11-26 at 16 37 58](https://user-images.githubusercontent.com/6607512/33242161-5410bdcc-d2c8-11e7-9280-ed05420fafaa.png)

I then dropped the image back on my desktop, and didn't drop it on Mastodon. The image-upload overlay won't go away. I have to reload the page if I want to be able to use Mastodon again.

This is a problem if you've carefully written up a toot that you don't want to lose! You'd have to upload something and then delete it from your toot in order to not lose your toot.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Press Escape.

**Comment by Cassolotl** [comment]
Oh thanks. :)
