### ISSUE TITLE
[Accessibility] !bangs

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#5824]
Can we get !bangs?

!bang logic:

1. Check if user setting "enable bangs" is enabled, stop here if it's disabled.
2. Skip any @mentions
3. Check for !public, !unlisted, !private, !direct, set this as the post privacy.
4. Check for !cw, use the rest of the current line as CW text.

This is a huge accessibility feature, as it's much easier to press "home" and type in a bang vs trying to navigate the page with the "tab" and "space" keys (and let's not forget having to tab back to the CW box and tab between the CW box and the post box).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
This might clash with "support groups using bangtags #139".

**Comment by nightpool** [comment]
What is the intention here—that the mastodon API would parse these commands out, or that the web client would do so before sending to the API? the former seems like a really bad idea from a design perspective, but making a custom client with this form of interface would certainly be possible.

**Comment by SoniEx2** [comment]
The default webclient would handle this with a setting.

**Comment by SoniEx2** [comment]
$ or % or ~ could be used for groups instead. !bangs come from duckduckgo and are more useful (especially since, from what I can tell, groups aren't a huge improvement over just following hashtags).

**Comment by Cassolotl** [comment]
>$ or % or ~ could be used for groups instead.

! is already used for groups on other OStatus sites, so I think it would make sense to be consistent with them.

**Comment by zcdunn** [comment]
@SoniEx2 what is the purpose of these commands? All of the commands you listed are already available in the web UI. I don't see a reason to clash with group syntax for readily available functions. A better way to make them keyboard accessible would be to add hot keys to the menu items

**Comment by SoniEx2** [comment]
The idea is to have visual feedback and keyboard shortcuts are a pain to learn and can you give me a keyboard shortcut that replaces the CW box with the first line of the toot such that I don't need to click or move from one input box to the other?

At least !cw would be a HUGE UX benefit.

**Comment by voronoipotato** [comment]
how about $ % ~ could be used for your command instead. Honestly I'm not sure how much value this provides. Why is !cw better than ~cw?

**Comment by SoniEx2** [comment]
On my keyboard it's much easier to type ! than ~ because my ~ is a dead key.

**Comment by voronoipotato** [comment]
Respectfully I don't really understand why your specific keyboard requirements must affect nearly a million users.  Frankly I think shortcuts would be better for this request as switching between clients could cause confusion for users.

**Comment by SoniEx2** [comment]
Have you ever used duckduckgo's bangs? (especially !w and !wa)

**Comment by remram44** [comment]
What about `/cw`, like GitLab, IRC, and most video games?

But I agree this is a client issue, and there is probably no need for this to be in the API or spec.

**Comment by Dragnucs** [comment]
@SoniEx2 bangs are already used for groups in OStatus and other GNU Social software. Mastodon just did not see any benefit in having groups along side hash tags. However, a mechanism like this would mean a change in the API at some point.

If this stays as a client feature, other instances not running on mastodon browser client would see absolutely no benefit in this. If their clients should be updated to support this, then a change in the specification => API is required.

If this is implemented with a !bang then this would seriously break the federation.

**Comment by SoniEx2** [comment]
It's an accessibility feature. No need to force clients to be accessible, tho, just make the default (web)client accessible.

**Comment by Dragnucs** [comment]
Can you please elaborate?

**Comment by SoniEx2** [comment]
!bangs make it so I don't need to switch text boxes to type a CW, I don't need to remember keyboard shortcuts (I can just remember keywords instead, which are much easier), and so on. Mouse is painful.

**Comment by moggers87** [comment]
It seems a lot of people are getting hung up on @SoniEx2 's choice of prefix rather than the actual feature request (controlling privacy and content-warning via the webclient's textbox).

The issue here is that the privacy/content-warning buttons are not properly accessible - they can be selected via keyboard, but they don't offer much visual feedback. Compare with the emoji and "Toot" buttons:

1. Emoji selected:
![Emoji selected](https://user-images.githubusercontent.com/1490673/33609741-2ec8a7f0-d9c1-11e7-9609-a101a3699981.png)

2. "Toot" selected:
![Toot selected](https://user-images.githubusercontent.com/1490673/33609742-2eead2e4-d9c1-11e7-988f-34ef454c5aba.png)

3. Privacy button selected (note the limited contrast between the buttons)
![privacy button selected](https://user-images.githubusercontent.com/1490673/33609744-2f0dd6b8-d9c1-11e7-80c0-7047ce44954f.png)

For those of you unfamiliar with keyboard control in browsers: click the textbox and hit tab a bunch of times, you'll first see the emoji button selected (if you press space or enter, you'll get the emoji picker pop up). If you hit tab a few more times you'll see the "Toot" button is selected - hitting space or enter here will post your toot.

I like the idea (though I'd probably go for `/` over `!` as @remram44 suggested - it's fairly common and won't interfere with GNU Social groups), but it might be less work to fix the CSS in the webclient than implement this feature ;)

**Comment by SoniEx2** [comment]
Perhaps `\` because `/` is often used in normal text? Anyone has any experience with `\` in keyboards? I know my keyboard has it, but does anyone else?

**Comment by remram44** [comment]
`\` is a terrible choice. No one else uses it (LaTeX kinda uses it) and it is placed terribly on non-US keyboard.

**Comment by SoniEx2** [comment]
I'm on a BR keyboard, it's fine here (close to LShift).

**Comment by voronoipotato** [comment]
\ is not convention anywhere. @SoniEx2 I recommend researching what the conventions people use, and then coming back with something that isn't already used by OStatus or GnuSocial. \ Is used for escape sequences and will probably confuse the heck out of some poor programmer.

**Comment by SoniEx2** [comment]
Escape sequences and TeX.

**Comment by voronoipotato** [comment]
I don't think user configurable command prefixes would be wise. If there's no one good choice perhaps the way of doing it should be reconsidered. If the goal is ease of use, and accessibility which I think it should be, then maybe there is a better way to approach this problem. I'd be curious how the CW's work and how or if this is communicated to non-mastodon systems.

**Comment by SoniEx2** [comment]
! is available in mastodon.

even if mastodon got groups, it would have to be at the start of a post anyway, how often do you put !cw or !public/!private/etc at the start of a post?

having 2 meanings isn't a problem if there are strong rules for them. (e.g. `return x/1 // divides x by 1`)

and we could change it to !! in 3.0, if it became an actual issue. (which I don't think it will)

**Comment by remram44** [comment]
@SoniEx2: This sounds like a extremely clunky way of proceeding, with a feature that no one (but you) seems to want anyway (or definitely not with `!`). And because mentioning/tagging people in the middle of messages is done all the time, I don't see why groups wouldn't be.

**Comment by SoniEx2** [comment]
hmm ok. how about simple keyboard shortcuts to switch between CURRENT position on CW box and CURRENT position on post box?

**Comment by nightpool** [comment]
@SoniEx2 tab and shift-tab?

**Comment by SoniEx2** [comment]
that doesn't seem to keep current position on CW box. and it doesn't work if there's no CW box.

**Comment by voronoipotato** [comment]
I guess that's the root problem. CW needs to be part of the tab-list.

**Comment by SoniEx2** [comment]
I wish I could switch between them with the up and down arrow keys tbh, and even pressing left at the beginning of the post box, or right at the end of the CW box.

**Comment by Cassolotl** [comment]
This is marked "accessibility" but people who need to use keyboard commands for accessibility reasons already have ways to switch between text boxes and navigate quickly around blocks of text; they're built into browsers and OSes, I think? So, you could learn those?

**Comment by moggers87** [comment]
@Cassolotl see my comment above about the (in-)accessibility of the buttons. Maybe the accessibility issues of the toot-box as it currently is should be moved to separate issue?

**Comment by voronoipotato** [comment]
Moggers would you mind opening a specific issue about that so we can close this one?

**Comment by SoniEx2** [comment]
Ok here's an idea. You know how you can add #nsfw to a post to hide the images?

What about something similar for CWs?

<cw text> #cw <hidden text>

(and CWs with newlines :P)
