### ISSUE TITLE
resize images/videos to fit within file size limit

### ISSUE THREAD

**Issue by MirahImage** [tootsuite/mastodon#583]
Mastodon has a 4MB image size limit and an 8MB video size limit. This is quite small, especially the video size. Currently, if a user attempts to upload an image/video above the size limit, an error occurs and the file is not attached. Adding support for server-side image/video resizing would be a nice feature, especially for users on mobile devices, who cannot readily resize media files.

**Comment by ashfurrow** [comment]
Looks like a duplicate issue was opened at https://github.com/tootsuite/mastodon/issues/2252 and the discussion has taken off there. I'm going to close this issue even though it was the original. Thanks for opening! Get in touch if you have other ideas 👍
