### ISSUE TITLE
Streaming API for local toots

### ISSUE THREAD

**Issue by kensanata** [tootsuite/mastodon#5839]
The [streaming API](https://github.com/tootsuite/documentation/blob/master/Using-the-API/Streaming-API.md) offers an URL for all public statuses, but unlike [timelines](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#timelines) there is no `local` parameter to have it return only "statuses originating from this instance".

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
Well...there is `/api/v1/streaming/public/local`, while it's not documented yet.

https://github.com/tootsuite/mastodon/blob/d937a59997f60e9aa7a022d84792fc50473bf3d5/streaming/index.js#L421

**Comment by kensanata** [comment]
I'll try it and if it works, I'll submit a patch for the documentation. Thanks!
