### ISSUE TITLE
Proposal: Add published_at column and restore default usage of created_at

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#5840]
We have `created_at` and `updated_at` on all tables, but its usage on `statuses` table is different from others. We've been using `statuses.created_at` as a **published date** of post, so [published property](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-published) in ActivityStreams will be stored in that column. However, we've changed to store **received date** of statuses which received on inbox due to Snowflakes (related #5487).

While thinking about that, I realize that there is no way to know when the statuses record was created. So, I think it would be better to have `created_at` for the local record or the administrative usage and `published_at` (or something) for the display usage.

(To resolve #5487, we still need another way to force using created date for ID generation, though)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by akihikodaki** [comment]
> However, we've changed to store received date of statuses which received on inbox due to Snowflakes (related #5487).

We can revert the change of the column's usage without affecting the Snowflake IDs, can't we?

**Comment by unarist** [comment]
@akihikodaki That's what I was thinking to fix #5487. Currently we generate Snowflake ID for `created_at` on `Mastodon::Snowflake::Callbacks.around_create`, and setting created_at to nil is used for forcing to use current timestamp. So we can revert the change by force it in another way. I'm not sure what is better, but for example, add non-persistent attribute for it?

Though, what I want to ask in this issue is about previous usage (use published time as created_at).

**Comment by akihikodaki** [comment]
What about removing the callback and creating a new method named `create_inserted_at!(inserted_date, attributes)` or similar? `inserted_date` represents the date when it was virtually inserted to timelines.
This is simple and stupid enough.

**Comment by ThibG** [comment]
We went for a different solution in #7336, so I'm closing this.
Feel free to re-open it if that solution isn't satisfactory to you.
