### ISSUE TITLE
Failed Fresh Vagrant Installation - Duplicate migration 20161009120834

### ISSUE THREAD

**Issue by tkacid** [tootsuite/mastodon#5846]
Notes:
- Followed Vagrant installation for devleopment
- Cloned
- Ran Vagrant Up - vagrant up --provider virtualbox
- Tried dropping the databases and doing a db:setup again and failed with same error
- Tried Master and 2.0 tagged

`_-- add_foreign_key("web_settings", "users", {:name=>"fk_11910667b2", :on_delete=>:cascade})
   (2.4ms)  ALTER TABLE "web_settings" ADD CONSTRAINT "fk_11910667b2"
FOREIGN KEY ("user_id")
  REFERENCES "users" ("id")
 ON DELETE CASCADE
   -> 0.0030s
   (5.7ms)  CREATE TABLE "schema_migrations" ("version" character varying NOT NULL PRIMARY KEY)
   (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
   (0.7ms)  INSERT INTO "schema_migrations" (version) VALUES (20171010025614)_
**rails aborted!
Duplicate migration 20161009120834. Please renumber your migrations to resolve the conflict.
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activerecord-**5.1.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:1050:in `assume_migrated_upto_version'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/schema.rb:52:in `define'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/schema.rb:44:in `define'
/vagrant/db/schema.rb:13:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/bootsnap-1.1.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/bootsnap-1.1.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:233:in `load_schema'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:255:in `block in load_schema_current'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:304:in `block in each_current_configuration'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:303:in `each'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:303:in `each_current_configuration'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:254:in `load_schema_current'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:248:in `block (3 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:252:in `block (3 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/bootsnap-1.1.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/bootsnap-1.1.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
bin/rails:4:in `<main>'`

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tkacid** [comment]
So I,

- Deleted the db/migrate folder
- Dropped the databases (test and development)
- Ran: bundle exec rails db:environment:set RAILS_ENV=development
- Ran: bundle exec rails db:setup

It now works, keep in mind this is from a fresh vagrant devlepment install.

**Comment by thebeastgamer25** [comment]
@tkacid How did you even get it to work? Mine isn't... what platform are u on?
