### ISSUE TITLE
no "hey i'm loading stuff" indicator when reaching end of timeline

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#585]
Internet's being choppy today, so it's hard to tell when something is loading more, and when there's no more.

Please try to also add a counter for retries and some feedback for errors, and a retry button.

**Comment by wchristian** [comment]
Turns out there's a blue progress bar at the top for those, but it's so dark and tiny it's nearly invisible. (I noticed it because i inverted all the other colors.) Maybe make it brighter, and also give its "progress tip" a bigger glowy ball or something like that?

**Comment by ashfurrow** [comment]
Hey @wchristian – it's been a while but I wanted to check in on this. Has the bar been changed to be brighter or should we keep this issue open?

**Comment by wchristian** [comment]
Not sure if it's been changed, but it's still difficult to notice:

![image](https://cloud.githubusercontent.com/assets/175467/25313663/1677b56e-2833-11e7-9ffe-59d8a4039058.png)

**Comment by ashfurrow** [comment]
Hmm, agreed.

**Comment by wxcafe** [comment]
The bar is difficult to notice on purpose : it also appears when you're loading a toot, a profile, when you're posting a toot, etc... It's not supposed to be too visible.

**Comment by wchristian** [comment]
Why is that a good decision to make?

**Comment by wchristian** [comment]
To be more clear: You declare it is not supposed to be visible. However this declaration comes entirely without justification, and in fact it appears to be contra-intuitive regarding what program reactions to user input should be.

As such you should at the very least clearly document that reason for this so future people who feel like making a ticket about this will see the reason.

**Comment by wxcafe** [comment]
it's not supposed to be *very* visible, because it would otherwise distract from content. it's just a loading bar. It's exactly the same with how Firefox uses the favicon area to show that the page is loading, then hides the loading indicator. It's visible, but not too much.

**Comment by wchristian** [comment]
Thanks for answering. However i don't feel that your explanation is sufficient.

The current implementation doesn't hit "not *very* visible". Instead it hits the other end of the spectrum of "nearly invisible unless you're directly looking at it". Especially for people with bad eyesight (detail resolution, contrast) it might as well not be there.

The comparison with FF also falls flat, since the FF indicator is fairly big, square, animates on most of its surface, and is high contrast.
![image](https://user-images.githubusercontent.com/175467/30884166-d9d3ee8c-a30e-11e7-8f95-908991b2ef6a.png)

The current loading bar is also distance-separated very strongly. If a user is scrolling down, their attention will be focused on the bottom of the screen. Meanwhile the loading bar is on literally the other end of the screen, and (depending on screen size) within their peripheral vision, where acuity and resolution are degraded even further.

 Your explanation does not usefully explain its current state to my understanding.
