### ISSUE TITLE
Introduce API error codes e.g. for Throttling

### ISSUE THREAD

**Issue by ThomasLeister** [tootsuite/mastodon#5852]
If access to the API is rate limited, Mastodon just returns

```{"error":"Throttled"}```

... or

```{"error":"Du wurdest gedrosselt"}```

(here in German - Maybe in even more langages)

Unfortunately this does not allow automatic error handling from the clients side (such as waiting for a few minutes) since there is no static error code. Of course you can check if as string ```{"error":"Du wurdest gedrosselt"}``` is returned and make program flow decisions based on that, but you would have to include multiple languages ... and I think we can agree on the fact that this is not very practible from a developers perspective. (And error detection would break if translations are changed).

I'm not sure if there are error codes for other API functions, but at least for throttling this is not the case.

**Request: Add error codes to API responses to distinct error types from each other and enable better error handling**

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
The HTTP Status Code is 499. The time to retry is also included in the HTTP header.

**Comment by ThomasLeister** [comment]
thanks, @ykzts ! 

Is this also true for other errors?

**Comment by Gargron** [comment]
Every error has a non-200 HTTP code. For example, validation errors return 422.

**Comment by ThomasLeister** [comment]
Okay, I didn't know that (and honestly didn't think of checking the HTTP codes) so ... consider this bug as closed :-) Everything is fine then.
