### ISSUE TITLE
Domain blocks improvements on the user side

### ISSUE THREAD

**Issue by eramdam** [tootsuite/mastodon#5855]
I've seen this feedback floating around on the fediverse recently and it's justified IMO:

While hiding a specific domain is fairly easy in the UI, there are no (or at least no easy way) to:

- know what domain you previously muted
- unmute said domains. Currently the only way to un-hide a domain is to go on a user's profile who is on the domain you've hidden and click `Unhide <domain>`

I feel like domain hiding is a very powerful feature for users but the lack of proper UI related to it seems confusing at best and dangerous at worst.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by npdoty** [comment]
Blocked domains are also currently not included in the export/import of block lists; if they were, I could take my list of instances I don't like between different instances.
