### ISSUE TITLE
Newlines ignored in bio

### ISSUE THREAD

**Issue by charliegreen** [tootsuite/mastodon#586]
Though this is a thing many other websites do as well, I've always found it frustrating, and I think other people would also like to be able to use newlines to format their profile descriptions/bios. Thoughts? (If other people think this is a good idea I might make a pull request).

**Comment by mcat-ee** [comment]
+1 on including newlines

Although in order to avoid bio overflow maybe there should be some restrictions, for example:
- Restrict sequential newline characters, e.g. '\n\n\n...' becomes a single '\n', similarly to how Facebook handles this.

**Comment by outofrange** [comment]
In addition to sequential newlines:

* An upper limit of line breaks (5? 10?) to avoid overflowing using something
l
i
k
e
this

**Comment by kballard** [comment]
Why do we need to restrict newlines? You only see the bio when looking at a user's profile, it's not a big deal if they put a lot of blank space in there.

That said, if you do restrict it anyway, at least allow two \n\n in a row, so I can have a blank line in between paragraphs.

**Comment by mcat-ee** [comment]
@kballard it's worth restricting newlines else you'll get bio sections that have MAX_CHARACTERS newlines, distorting the entire page!

Good point on allowing two sequential newlines though. Perhaps the replacement rule should be \n\n[\n]+ -> \n\n

**Comment by kballard** [comment]
@mcat-ee 

> it's worth restricting newlines else you'll get bio sections that have MAX_CHARACTERS newlines, distorting the entire page!

Err, so what? All that means is it'll annoy people who want to look at that user's post history. But that's not a big deal. It doesn't affect other users, because bios are only displayed on the owner's profile page. Restricting newlines because a few people will be silly with them is just needlessly restrictive.

**Comment by outofrange** [comment]
Maybe a "Read more..." link for longer bios? This way, the UI can't be broken by accident when browsing other people's profiles, and users still are able to put as many new lines in their text as they want.

Another issue to think about: how will (& should) this affect other platforms?
How would Gnu.Social deal with unexpected long bios, or bios with some "Read more..." link/button?

**Comment by kballard** [comment]
You're still talking about solutions in search of a problem. Unless it's been shown that having a bunch of newlines in a profile causes issues, we shouldn't be searching for ways to "fix" a non-existant issue.

**Comment by Gargron** [comment]
I believe this has been implemented.
