### ISSUE TITLE
Permalinks visible when logged in but "The page you were looking for doesn't exist." when not logged in

### ISSUE THREAD

**Issue by akkartik** [tootsuite/mastodon#5866]
I can see https://mastodon.social/@akkartik/99097366034071978 when logged in, but on an incognito window it gives an error.

On the other hand, a random other permalink works both ways: https://mastodon.social/@federicomena/99099906580977312

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
it's probably a private post or DM. Private posts are only visible to
followers or those tagged in them, DMs are only visible to those tagged in
them. When you're logged out, they're not visible.

**Comment by akkartik** [comment]
No, the first post is mine, and I haven't ever changed visibility on any posts. Here are screenshots of my relevant settings:

![toot](https://user-images.githubusercontent.com/3161/33500862-4a1c5f22-d68f-11e7-9b8a-2a96657bacc9.png)

![settings](https://user-images.githubusercontent.com/3161/33500869-4f5c1450-d68f-11e7-8253-936d01f868cf.png)

Am I missing something?

(Aside, could you confirm that you're able to reproduce my issue? Is https://mastodon.social/@akkartik/99097366034071978 really unavailable on an incognito window?)

**Comment by Cassolotl** [comment]
I get error pages whether I open it in a normal window or an incognito window, if that helps. I'm currently logged into mastodon.social (as well as cybre.space, which is my main).

**Comment by akkartik** [comment]
Oh that's weird, I can actually see my permalink when logged in!

**Comment by ThibG** [comment]
Closing, as the toot is most likely a followers-only toot (it could happen even if you did not manually change the privacy settings, if this is a reply to a followers-only toot itself).
Please re-open if that happens with a toot that is public or unlisted.

**Comment by akkartik** [comment]
Ah, you're right. It turns out that the upstream https://social.coop/@h/99097218505206482 is followers-only. It's responding to https://mastodon.social/@akkartik/99097194286845964, which works fine on an incognito window.
