### ISSUE TITLE
Webfinger Profiles Not In Stated Format

### ISSUE THREAD

**Issue by tekktonic** [tootsuite/mastodon#5875]
Mastodon's host-meta entry says that the type of a webfinger profile by default is xrd+xml, however Mastodon serves a json profile unless an xrd+xml Accept profile is explicitly passed. The json profile format is not mentioned at all in the host-meta file.

Reproduce:
```curl https://mastodon.social/.well-known/host-meta``` Note type=application/xrd+xml.
```curl https://mastodon.social/.well-known/webfinger?resource=gargron@mastodon.social```

What happened:
Second curl command returned a profile in json format

What was expected:
Should have returned a profile in xrd+xml format

Fix:
In addition to the xrd+xml entry, include a jrd+json entry to clarify that an Accept header must be passed.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ x ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
I don't think this is technically a bug. If you're expecting a specific type, you need to request that type explicitly. Just saying that that a given resource is available with that type doesn't guarantee that it will be the default representation for that resource.

Mastodon has returned JRD by default for webfinger requests for the entire time it's been publicly available, so I would be worried about breaking existing clients by changing this now.

**Comment by Gargron** [comment]
Use `Accept: application/xrd+xml` header
