### ISSUE TITLE
Function to log out on all other instances

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#588]
After setting 2FA I noticed that there's no way to tell where I'm logged in from and activating 2FA doesn't end sessions that weren't started using 2FA. I suggest adding a button to log the user out of any other session so people can be sure their account is safe after changing their password/ activating 2FA.

**Comment by ashfurrow** [comment]
Seems related to https://github.com/tootsuite/mastodon/issues/2347 as well.

**Comment by noiob** [comment]
To some extent, this is solved by the 'Authorized Apps' settings, but not for web logins

**Comment by ashfurrow** [comment]
Agreed. Do you think that #2347 is different enough that you'd like to leave this issue open? It's up to you!

**Comment by noiob** [comment]
Yeah, definitely. #2347 is a fairly big security problem while this is just a feature that'd help people keep their accounts safe.
