### ISSUE TITLE
do you have a bookmarklet?

### ISSUE THREAD

**Issue by el3ctron** [tootsuite/mastodon#5884]
i was looking for a bookmarklet on server but could'nt find it, it would be so cool to have that feature, it speeds up when sharing interesting links! 

do you have a bookmarklet?

**Comment by ykzts** [comment]
```javascript
open(`web+mastodon://share?text=${encodeURIComponent(document.title)} ${document.URL}`, 'mastodon-intent', 'width=400,height=400,resizable=no,menubar=no,status=no,scrollbars=yes')
```

**Comment by el3ctron** [comment]
thanks for your answer! well i tried your code but does not run, anyway i do this one with some little changes and work!

`javascript:open(`mastodon.social://share?text=${encodeURIComponent(document.title)} ${document.URL}`, 'mastodon-intent', 'width=400,height=400,resizable=no,menubar=no,status=no,scrollbars=yes')
`
1. i dont know javascript but it would be sooo cool that when i select some words on page that i wanna share automatically copy on mastodon buffer, i guess is changing "document.title" seccion for any other code, but i dont know...
2. offer that bookmarklet on mastodon settings!! there is a lot of people that like to use bookmarklets on navigator!
