### ISSUE TITLE
Reply to CW posts should default to having a CW with "re: <title>"

### ISSUE THREAD

**Issue by triplefox** [tootsuite/mastodon#590]
There is a bit of a convention emerging to have some discussion threads run entirely behind CW walls, but to follow this convention takes some discipline and it's easy to miss. Email has the most obvious design for automating this reply structure since it uses the same thread/title/body model.

**Comment by triplefox** [comment]
We may also want to conventionally put the @ that we reply to in the header. (At least, this is what was first suggested - but maybe we want to hide that by default instead?)

**Comment by Gargron** [comment]
Solved in af007f2def802560f548d85f81f0f4e5039ae737
