### ISSUE TITLE
Social Scalability Planning

### ISSUE THREAD

**Issue by triplefox** [tootsuite/mastodon#591]
If the user base of an instance(today, mastodon.social, but hypothetically any instance in the future) grows too fast, here is what may happen:

1. Lower quality daily experience
2. Norm erasure ("Endless September" effect)
3. _Loss_ of support because existing contributors will grow overworked

It is possible to turn all negatives into positives. This is an overview issue that can be linked to related feature issues.

1 should be measured by running a periodic survey that focuses on direct, self-reported personal experience: Do you feel safe? Do you feel free to say what is on your mind? Are you engaging in healthy conversations? If experience quality goes down across surveys, **throttle instance growth** so that platform features and norms catch up. Throttling is a recurring theme of this proposal, as a tool that allows an instance to proceed at the pace that is right for it.

For 2, there are specific features that can/already have been proposed to diffuse the inhumane experience of a fast-moving public timeline or the equivalent problem of following too many people. Federation should be encouraged past a certain point(e.g. ease of setting up instances) so that norms may fragment without creating culture wars. Allowing a single instance to become one-size-fits-all is also a form of federation failure, and growth throttling, again, can be used to encourage federation.

3 is solved by a combination of growth throttling, improving formal administrative structures(which would be solved per instance) and features that ease recruiting and share the burden.

**Comment by Gargron** [comment]
I have considered putting some sort of list of random alternative domains on the landing page to spread the traffic to other instances. There is some risk of abuse (somehow making an offensive domain and following accounts from it to get it to show on the landing page), there is also a question of how to select domains to show (there is also no way to tell whether a domain points to a Mastodon instance or a GNU social or a Friendica or a [x] instance, or whether they have registrations open)

Suggestions invited.

**Comment by noiob** [comment]
It should be possible to add a way of asking an instance whether it's a Mastodon instance. I guess on the landing page only Mastodon instances should be shown, but it would also be interesting to see like a top-ten list of the biggest instances an instance federates with

**Comment by mitchellurgero** [comment]
OStatus supports checking server version.

**Comment by Gargron** [comment]
Please move such discussions to the [Discourse](https://discourse.joinmastodon.org), thank you!
