### ISSUE TITLE
Additional plausible deniability features

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#5930]
If I go on a profile of someone who follows me I get a "follows you" thing. I'd like a way to hide that for the purposes of plausible deniability.

[Thread](https://witches.town/@SoniEx2/99144032072868025)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
Can you describe what you mean by plausible deniability? Can you describe a scenario where you'd need that?

**Comment by SoniEx2** [comment]
Plausible deniability means I don't know when terrorists, children, nazis, etc follow me. I get to say I don't know <someone> is associated to me, in the case they go to jail and the government tries to find co-conspirators, in the case I get sued, etc. It's all about personal safety.

**Comment by moggers87** [comment]
If your account is public (i.e. you don't have to actively accept new followers) I don't see how you can be "associated" with a third party in such a way that could cause you legal issues later. I think you already have plausible deniability there.

Also, what you propose would be completely undone by someone boosting or otherwise interacting with your toots.

**Comment by SoniEx2** [comment]
If they can boost it they could just as well view it by stalking my profile without ever following me. So no, boosting doesn't defeat plausible deniability.

Interacting does, but that's the point of interacting, isn't it? If you don't want to get blocked, don't interact with 18+ toots if you're not 18+.

There's no reason why accounts themselves should be 18+, tho. My feature request just reduces liability issues, and it's always good to keep ppl who did not do anything out of prison.

**Comment by moggers87** [comment]
> There's no reason why accounts themselves should be 18+, tho. My feature request just reduces liability issues, and it's always good to keep ppl who did not do anything out of prison.

This is the bit I don't understand: how are you personally liable? If it's due to laws that prohibit minors from accessing pornography then I'm fairly certain that such laws target the service provider (the instance admin in our case), not the user. I'm not a lawyer though, so maybe I'm wrong.

**Comment by nightpool** [comment]
Mastodon won't implement this and we won't accept PRs for it, given that it has no conceivable usecase and is sketchy as hell.
