### ISSUE TITLE
Search doesn't find posts

### ISSUE THREAD

**Issue by alanpaone** [tootsuite/mastodon#594]
this may be a lot of work to implement, i have no idea, but imo a search ought to show posts and not just usernames. The only way to retrieve old posts seems to be through hashtags and nobody is that diligent about tagging

**Comment by mcat-ee** [comment]
When you think about a search function for mastodon, should the search only function on the user's current server or should it work across the linked federated servers?

**Comment by outofrange** [comment]
Regarding this topic, datapub made an important point about counter-acting harassment by only allowing hashtag & user searches: https://mastodon.social/@datapup/1470817

In my opinion, being able to search for as much as possible is quite appealing.
To still give users a tool against harrasment and avoiding surprises, I suggest a opt-out privacy option to allow own Toots to be find by such a search.

Unaffected by the decision / implementation on a global search (be it instance-local or federation-wide), a good & flexible search for own content would be great.

**Comment by Gargron** [comment]
As is, this is not a bug, but intention. The future may bring ability to search own posts, favourites, or mentions, but I can't promise when.

**Comment by phtan** [comment]
@outofrange you wrote:

> Regarding this topic, datapub made an important point about counter-acting harassment by only allowing hashtag & user searches: https://mastodon.social/@datapup/1470817

May I know what datapup said, if you remember? The URL seems to be broken now

**Comment by mcat-ee** [comment]
@phtan 
from `https://web.archive.org/web/20170809085325/https://mastodon.social/@datapup/1470817`:

> In case anyone is wondering why you can only search hashtags, this was, to a lot of us, a beneficial design decision to counter-act harassment, so that nobody can just do a search for "otherkin" or "intersectionality" and then find all the ppl they want to harass, etc. etc.
> 
> it wasn't a hard-set thing and has never been fixed in stone so it may be changing but if you're making requests for "real search" do consider the ramifications for that.

**Comment by nightpool** [comment]
mastodon does allow you to search your own posts, as well as posts that
mention you or posts you've liked or boosted. it just doesn't allow you to
search every post ever made.

**Comment by ckuttruff** [comment]
@nightpool Can you elaborate there?  I don't see this in UI and all main site searches don't seem to show anything beaides hashtag / username searches (which to my understanding was by design).

Did i miss a pref to enable?  How exactly are you currently searching your own profile?

**Comment by danhunsaker** [comment]
Your instance needs to have Elasticsearch available in order for full text search to function. If you aren't finding your own posts based on their content, either the instance admin hasn't set up Elasticsearch for your instance, or the version of Mastodon itself is from before the feature was implemented. You'll need to talk to your instance admin about this one.

**Comment by ckuttruff** [comment]
I'm my instance's admin :)
I've added elasticsearch and confirmed it's functioning as expected following this doc:
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Elasticsearch-guide.md

thanks, I missed the change that Eugen referenced.  Glad this exists!

**Comment by comatory** [comment]
I know this is a closed issue but I just wonder how a user would go about discovering stuff on Mastodon? I often search twitter for posts for topics that interest me and this way I find bunch of useful stuff.
I think most people just don't use hashtags so it's a little shame that lot of content is never discovered across instances. It'd be cool at least have some kind of tool where you could queue up search queries, maybe this wouldn't cause as much overload. I don't know, I just miss the full text search feature across instances.
