### ISSUE TITLE
Toggle gif avatar autoplay

### ISSUE THREAD

**Issue by mkosler** [tootsuite/mastodon#596]
It would be nice to have the ability to toggle gif avatar autoplay in the settings.

**Comment by chris-martin** [comment]
Or perhaps, more simply, it would suffice to have an option to disable animated avatars entirely, and just show the first frame.

**Comment by Vavassor** [comment]
So I've spotted at least a couple of users on public timelines that have party parrot avatars. It's basically a flashing rainbow dancing parrot animation and it's been used to attack folks with photosensitive epilepsy before. Also there's been other throbbing images that aren't avatars. I'd say this issue needs a boost in priority.

**Comment by elad661** [comment]
see also: issue #187 , which is basically the same thing. I guess @Gargron tried to fix it but the fix didn't work? or fixed it but then reverted the change? In any case, I think animated avatars should NOT autoplay ever.

**Comment by zaren** [comment]
Just seeing about getting this bumped up a bit in visibility. I just joined in on the fun tonight, and already found one person stating they saw a flashing gif that triggered a migraine. Autoplay gifs might not be the best idea, what with the possibility of them being weaponized now and all.

**Comment by wryk** [comment]
What about a user setting ?

Avatar animation :
* Disabled / Don't play (show only the first frame)
* On hover / Play on hover
* Enabled / Autoplay

Settings with good defaults are far better than only one fixed behavior

**Comment by fallerOfFalls** [comment]
Also/instead of playing on hover, playing on click.

**Comment by Cassolotl** [comment]
>Also/instead of playing on hover, playing on click.

I prefer playing on click!

**Comment by wxcafe** [comment]
It's important to note that Gif playback causes some people real health problems (
![screenshot from 2017-04-09 02-54-06](https://cloud.githubusercontent.com/assets/3009327/24833648/d835ef32-1ccf-11e7-8f11-4195e16abba3.png)) and it would be nice if this could be fixed. It doesn't look like it's a hard problem either.

I agree with @wryk that a user setting with these three options would be the best way to do this.

**Comment by chris-martin** [comment]
Seems like whatever happens for avatars should happen for gifs in toot content as well. It'd be great if these were two different settings. e.g. my preference would be to never animate avatars and to play tooted gifs on hover.

**Comment by lynnco** [comment]
From a harm reduction point of view, this feature needs to either have a user setting that defaults *off*, and / or only play on hover.

**Comment by wxcafe** [comment]
I'm for defaulting to only playing on hover. That allows discoverability of the fact that there are gifs and that they can be played while still being off by default, meaning people who have problem with gifs won't be bothered too much

**Comment by Cassolotl** [comment]
>I'm for defaulting to only playing on hover. That allows discoverability of the fact that there are gifs and that they can be played

Another way is freezing it, blurring it, and whacking a big play symbol on it, like Telegram does, which is my favourite - maybe because I am used to it. ;)

![screen shot 2017-04-09 at 23 03 20](https://cloud.githubusercontent.com/assets/6607512/24841274/c52a283c-1d78-11e7-91c7-ce30ccc937a3.png)

**Comment by elad661** [comment]
Thanks for working on this! Do we need to file a different issue for toggling posted gif autoplay (as this fix seems to be only for avatars)? While less annoying than avatars, posted gifs do pose a serious danger for people with epilepsy, such as in this case: https://www.theverge.com/2016/12/16/13988894/david-eichenwald-seizure-tweet-attack

**Comment by Cassolotl** [comment]
@elad661 This issue includes gifs attached to toots/posts: https://github.com/tootsuite/mastodon/issues/441 (It's been closed but it's unclear whether we can now auto-pause *all* gifs.)

**Comment by elad661** [comment]
from reading the commit that closed it, it seems to only be relevant to avatars and headers. I think @Gargron might have forgotten about the posted gif case?

**Comment by Cassolotl** [comment]
Perhaps! Let's wait and see; I'm willing to open a new issue just for animated gifs attached to posts, if this is the case. :)
