### ISSUE TITLE
Retoot button went missing since v2.0.0rc2

### ISSUE THREAD

**Issue by asterismo** [tootsuite/mastodon#5966]
The retoot button went missing sometime after upgrading to v2.0.0rc2. Today i upgraded to v2.1.0rc3 but no luck. Any ideas?

![image](https://user-images.githubusercontent.com/233815/33912082-78c05672-df62-11e7-90a6-11a11d7d58c9.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by davefp** [comment]
This is working on my instance running 2.1.

Observing the page as it loads, it looks like the boost button is loaded after the others, so it could be generated by js.

@asterismo do you see this behaviour across different browsers, and with all browser extensions turned off?

**Comment by asterismo** [comment]
I updated the node twice, and still missing. It happens in all desktop browsers. Maybe i can try to restore the image path in the server, maybe it got corrupted?

**Comment by Gargron** [comment]
The image is not in a file path, it is embedded inside the SCSS (CSS) as a base64 data URL, to allow styling it with SCSS color variables. Hm. You could right click the element and check what's inside and what the CSS rules for it are in the web inspector. Also maybe you have some CSP header that blocks inline (data URL) images?

**Comment by asterismo** [comment]
![captura de pantalla de 2018-01-21 17-45-33](https://user-images.githubusercontent.com/5679035/35198818-13e8f368-fed3-11e7-91a9-b1cbcae41838.png)

Should i upload my nginx conf?

**Comment by asterismo** [comment]
![captura de pantalla de 2018-01-21 17-48-53](https://user-images.githubusercontent.com/5679035/35198849-92127e44-fed3-11e7-801a-727da6be7911.png)

**Comment by Gargron** [comment]
The very first Content Security Policy message from the log seems to be about this.

**Comment by asterismo** [comment]
add_header Content-Security-Policy "default-src 'self' https://changelly.com/; font-src 'self'; media-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' https://authedmine.com; img-src 'self' https://info.shapeshift.io https://shapeshift.io https://changelly.com/ https://www.paypalobjects.com http://stats.mastodon.uy; connect-src 'self' wss://mastodon.uy; frame-ancestors 'none';";

**Comment by asterismo** [comment]
`add_header Content-Security-Policy "default-src 'self' https://changelly.com/; font-src 'self'; media-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' https://authedmine.com; img-src 'self' https://info.shapeshift.io https://shapeshift.io https://changelly.com/ https://www.paypalobjects.com http://stats.mastodon.uy; connect-src 'self' wss://mastodon.uy; frame-ancestors 'none';";`

**Comment by asterismo** [comment]
@Gargron should i modify something in the CSP line?

**Comment by nightpool** [comment]
img-src probably needs 'unsafe-inline', if I'm reading those logs right? it's hard because I have to guess at what the error messages are saying. (if that doesn't fix it, could you provide a translation maybe?)

**Comment by asterismo** [comment]
I'm working on that, maybe the line is not well formatted

**Comment by asterismo** [comment]
I fix it, i added "data:" bit to the img-src and it worked like a charm
`... img-src 'self' 'unsafe-inline' **data:** ...`

Closing...

**Comment by asterismo** [comment]
I fix it, i added "data:" bit to the img-src and it worked like a charm
... img-src 'self' 'unsafe-inline' data: ...

Closing...

**Comment by asterismo** [comment]
I fix it, i added "data:" bit to the img-src and it worked like a charm
`... img-src 'self' 'unsafe-inline' data: ...`

Closing...
