### ISSUE TITLE
pin private toots

### ISSUE THREAD

**Issue by dn3s** [tootsuite/mastodon#5970]
I think it would be really handy to be able to pin a private (followers-only) post, to provide introductory information that would be useful to followers but that the user doesn't necessarily want to publish.

this could also help address some aspects of #609

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Only public posts can be pinned, because pins are public. I don't want to introduce more ambiguity into that.

**Comment by dn3s** [comment]
LOL, of course pins are public. that's how they're implemented right now. i was asking if we could *change* that implementation.

**Comment by LeeteqXV** [comment]
On Tue, Apr 24, 2018, at 03:54, Alice wrote:
> LOL, of course pins are public. that's how they're implemented right 
> now. i was asking if we could *change* that implementation.
> 

Perhaps "Bookmarks" may serve better for this purpose, without having to make pinning confusing.
Example implementation: The Mastalab Android client provides local, account-specific cross-device bookmarking.
The very concept of Bookmarks is one that is interesting for Mastodon core, IMO.

Regards,
Teqleez
