### ISSUE TITLE
Force re-fetch of profile information

### ISSUE THREAD

**Issue by renatolond** [tootsuite/mastodon#5973]
Hi!

I'm on 2.1.0.rc3, but I've been seeing this issue for a while now. Some users from mastodon.social (but I don't know if only from there or if it's only because I've see more often users from there) seem to have no profile picture. Forcing an avatar update from the moderation tools have no effect. If I fetch the account information in the rails console, the avatar_remote_url is nil, which leads me to believe the issue is that the profile information is not up to date.
How can I force the profile information to be fetched again? Just searching for the user (both with user@instance and with the instance url don't seem to trigger a new fetch)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
You can re-fetch the profile of a user by putting their url (like `https://mastodon.social/@gargron`) into the search box of the instance.
