### ISSUE TITLE
Bug: JS error when searching a value with a space in it

### ISSUE THREAD

**Issue by tobypinder** [tootsuite/mastodon#599]
(Tested only in Chrome on the mastodon.social instance with and without my adblocker)

When searching a string that has multiple words I get the following exception
![untitled](https://cloud.githubusercontent.com/assets/618992/22627430/fd941baa-ebba-11e6-9e0d-6b0dadc0d617.png)

I believe this is because single word searches are interpreted as potential hashtags whereas a query string doesn't have any context menu options.

**Comment by Gargron** [comment]
Can I ask what you entered?

**Comment by tobypinder** [comment]
"Fire emblem" was my original search term but I just reproduced with "lorem ipsum".

**Comment by marrus-sh** [comment]
not sure if this is the same issue or not (I think it is) but Autosuggest seems to throw an error whenever you arrowkey down/up or press enter on a query with no suggestions (as a query with spaces will end up being). as far as i can tell this is on their end and there's nothing we can do? I'm not very well-versed on how autosuggest works though

**Comment by tobypinder** [comment]
This was the behaviour I was experiencing - the lack of a context menu causes the issue.

**Comment by Gargron** [comment]
Ah. In that case, making the `getSuggestionValue` (https://github.com/tootsuite/mastodon/blob/c424df5192f346dba5332a4b3a2de43b2f028e0c/app/assets/javascripts/components/features/compose/components/search.jsx#L12) function a bit smarter about undefined input would solve this issue.

**Comment by ashfurrow** [comment]
Hmm, I'm not seeing the error thrown anymore. Can anyone confirm this is still occurring?

**Comment by Gargron** [comment]
This whole code thing changed so I'm closing.
