### ISSUE TITLE
Can't load timeline at "/about".

### ISSUE THREAD

**Issue by kedamaDQ** [tootsuite/mastodon#5992]
Can't load timeline at "/about" with instances of v2.1.0rc3.
As far as I confirmed, this issue occures on Firefox 58.0 and Chrome 63.0.3239.84 on windows. In concrete, got error that followings:

Chrome
![2017-12-13 00_02_44-mastodon social - mastodon](https://user-images.githubusercontent.com/32974885/33892616-99a18f16-df9c-11e7-9423-25fcc5f83b02.png)

Firefox
![2017-12-13 00_03_16-mastodon social - mastodon](https://user-images.githubusercontent.com/32974885/33892628-a35b0b54-df9c-11e7-933a-20b3a4e6450a.png)

This probably happens in v2.1.0rc3, I think not happens before v2.1.0rc2.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
duplicated with #5976.
