### ISSUE TITLE
Toots retrieved by ThreadResolveWorker not pushed to timelines

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#5993]
If a toot is resolved by `ThreadResolveWorker`, it does not get pushed to public, home or lists timelines.
This also prevents those toots from being added to those timelines if they subsequently get delivered via ActivityPub or OStatus.

Such situations can arise when a server is down or has poor connectivity, causing original messages to not be delivered (or have their delivery delayed) while a reply gets delivered, triggering a call to `̀ThreadResolveWorker`.

**Comment by Gargron** [comment]
I think this is desired..?

**Comment by ThibG** [comment]
Why would it, though?
Consider the following situation: because of a temporary failure, a series of remote toots (that would have all been displayed on someone's home timeline) does not get delivered at first. Eventually, one of the replies gets delivered, and the receiving end resolves the previous toots. Because ThreadResolveWorker does not push them into the timeline, they don't appear there. Eventually, they get delivered, but aren't pushed into the timelines either as they already exist locally and processing is skipped.

**Comment by nightpool** [comment]
>This also prevents those toots from being added to those timelines if they subsequently get delivered via ActivityPub or OStatus.

I think this is probably a more tractable problem to fix. I would be very much against thread resolve worker just doing this itself. (it used to, and then it got changed if I remember correctly)

**Comment by Gargron** [comment]
I think this is fixed if discovered toot is less than 6 hours old
