### ISSUE TITLE
Feature request: Ability to add personal note when blocking a user for easier Blocked Users list management

### ISSUE THREAD

**Issue by fireh9lly** [tootsuite/mastodon#602]
Hello, floated this in [a toot](https://mastodon.social/users/fireh9lly/updates/1129351) and it was fairly popular.

Mastodon relies on blocking accounts to curate the public timeline for individual users, but there are many reasons why users may choose to block an account - perhaps because the user is abusive or annoying, or perhaps because they're temporarily tooting a lot about a subject the blocker doesn't care about. The Blocked Users tool is useful for mass unblocking, but it can be difficult to remember who's a temporary bother who can be safely unblocked, and who's an unforgiveable bellend, especially after a couple of weeks or if users have changed their icons and display names.

I suggest adding an option where, upon selecting Block, users get a short text input to add a note about why, if they choose - '_bad political opinions_', '_called me a slur_', '_unfunny bot account_', '_boring spam on evening 12th Jan_', etc. These notes would only be viewable by the individual user, as they are for their personal records alone, and display on the Blocked User list. There should also be an option to edit the note on the Blocked User screen, to allow annotation of users blocked before the feature was added (and fix typoes).

The blogging platform LiveJournal allows something similar - paid account holders can add Notes to users which appear when their userpic is hovered, preventing accidental engagement with abusive users whose names you've forgotten.

**Comment by outofrange** [comment]
I really like the idea.

This could also be an interesting thing to optionally include in exported blocking lists, so others know why I blocked somebody. The data would still be private if I _don't_ want to share it.

**Comment by mal0ki** [comment]
If we are going to attach moderator notes to blocks etc, we may as well look into doing it on the user-level too. 
Added to 1.5 for consideration.

**Comment by trwnh** [comment]
Is this still planned for v1.5? Perhaps v2.5?

**Comment by mkljczk** [comment]
So it's basically #14148 and can be closed, right?

**Comment by fireh9lly** [comment]
Yeah.
    On Sunday, 6 December 2020, 00:09:31 GMT, Marcin Mikołajczak <notifications@github.com> wrote:  
 
 


So it's basically #14148 and can be closed, right?
