### ISSUE TITLE
User-customizable timestamps

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6020]
I'd like the UI to display Unix time. I use Unix time everywhere else. Other ppl would like to choose between dd/mm and mm/dd. An strftime box would be nice to have.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment]
I don't think this is a common enough use-case to be worth including.

**Comment by SoniEx2** [comment]
Just give me an strftime box.

**Comment by tateisu** [comment]
I think you can make user script for your PC browser.
