### ISSUE TITLE
Notification column settings should scroll on smaller screens

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#604]
On my iPhone 5 I can't view all the settings for the notifications column because the screen is too small. I suggest either a more compact layout or simply scrolling.

**Comment by ashfurrow** [comment]
Just confirmed this is still happening. Thanks for opening the issue!

**Comment by unarist** [comment]
I can scroll it on both Chrome on PC and Safari on my iPhone 5s with iOS9. However, you can't scroll until the element finishes expand motion. See below gif and check when scrollbar is activated.

![gif-compressor](https://cloud.githubusercontent.com/assets/705555/25660197/275c3600-3046-11e7-92c9-9410795443d0.gif)

**Comment by noiob** [comment]
Ah, great discovery! So the issue is that it takes too long until scrolling is available
