### ISSUE TITLE
Export of my own toots to a parseable text file format

### ISSUE THREAD

**Issue by novoid** [tootsuite/mastodon#6044]
I would like to have the possibility to export my complete(!) set of toots (all kinds) into an easy to parse text file format such as JSON or CSV or at least XML.

My own motivation for this feature is to be able to include my toots in my offline time-line visualization tool https://github.com/novoid/Memacs for Life-Logging and Quantified Self purposes. Nevertheless, I can think of many different reasons why people want to be able to export their own toots in order to use them somewhere else.

This feature request is not limited to the desirable functionality of being able to export from Mastodon and import to Mastodon (optionally extension of this issue here; see also #177) back again.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
  - However, similar issues are:
    - #177 Account migration is work in progress - when there is a super-smooth process to migrate from one account to another, this might not involve being able to download my own data into JSON/CSV/whatever.
    - #4442 This does not ask for toots at all
    - #5714 The purpose behind this request is different as well and could be solved without downloading an easy to parse text file representation of the toots

**Comment by aka-rin** [comment]
Well, in server side they still have no consensus so I wrote [a simple script](https://gist.github.com/aka-rin/5f0e6b90836cb998c11b9178d7d90bb5) to export my data.

(SEO is really important 😂 )

**Comment by novoid** [comment]
Thanks @aka-rin for your great Python script. It even is able to download linked images and videos. Well done!

However, for the sake of standardization, I would love to see this functionality integrated in Mastodon so that post-processing the output format is more future-proof.

**Comment by aka-rin** [comment]
@novoid That's just what I think too. But as we all know, open source projects have no guarantee. 😂 

Many basic features in Mastodon are still unimplemented yet. Maybe they will release this functionality one day, but how many Mastodon nodes can be updated to the latest version? Maybe I'm just a little pessimistic, sorry about that.

So for your demands, a more rational choice is to use the [Accounts methods in Mastodon API V1 (needs authorization)](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#getting-an-accounts-statuses). You can specify the `since_id` with the id of your latest toot in the local database and check it at regular intervals. Another choice is to write a crawler if your toots are all public. You can use the [public status API](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#fetching-a-status) to get the accurate amount of your toots and make it works like IFTTT. 😂 

I know these solutions are not elegant, but maybe there's no better choice for now.
