### ISSUE TITLE
v2.1.0: error='NoMethodError: undefined method `disabled?' for #<User:...>

### ISSUE THREAD

**Issue by wimvanderbauwhede** [tootsuite/mastodon#6045]
I upgrated from 2.0.0 to 2.1.0 on a single-user instance.

When trying to log in I get this error:

method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=500 error='NoMethodError: undefined method `disabled?' for #<User:...> Did you mean?  disable!'

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Do you ran `./bin/rails db:migrate`?

**Comment by wimvanderbauwhede** [comment]
No, what I did was:

git pull
git checkout v2.1.0

Then I followed the production guide:

gem install bundler
bundle install --deployment --without development test
yarn install --pure-lockfile
RAILS_ENV=production bundle exec rails assets:precompile

Should I do the db:migrate as well?

**Comment by ykzts** [comment]
Yes, Yes, you should read at "Upgrade notes:" in the [Release Note](https://github.com/tootsuite/mastodon/releases/tag/v2.1.0).

> ### Upgrade notes:
> 
> Non-Docker only:
> 
> - Dependency updates: `bundle install` and `yarn install`
> 
> Both Docker and non-Docker:
> 
> - This release includes database migrations, that means you need to run RAILS_ENV=production bundle exec rails db:migrate (in Docker: docker-compose run --rm web rails db:migrate).
> - This release includes changes to assets, that means you need to run RAILS_ENV=production bundle exec rails assets:precompile (in Docker: docker-compose run --rm web rails assets:precompile)
> - This release includes changes to some preview cards, that means you need to run RAILS=production bundle exec mastodon:maintenance:migrate_photo_preview_cards immediately AFTER you updated. Note that this will queue some pull jobs for Sidekiq.

**Comment by wimvanderbauwhede** [comment]
OK, I'll try that thanks a lot!

**Comment by wimvanderbauwhede** [comment]
Thanks, that worked, but the last command is incorrect, it should be:

RAILS_ENV=production bundle exec rails  mastodon:maintenance:migrate_photo_preview_cards
