### ISSUE TITLE
Use inert polyfill

### ISSUE THREAD

**Issue by sorin-davidoi** [tootsuite/mastodon#6053]
Since https://github.com/tootsuite/mastodon/pull/4405/ we are using the `inert` attribute for accessibility reasons in the modals. However, this is currently only supported in Google Chrome.

There are two polyfills which we can use:
 - [The official one](https://github.com/WICG/inert) from WICG - may incur a performance penalty
 - [The Google one](https://github.com/GoogleChrome/inert-polyfill) - aims to be more lightweight but not 100% correct

I would prefer the official one but we need to look into the performance penalty.

**Comment by SuperSandro2000** [comment]
#12209 closed this issue.
