### ISSUE TITLE
Deleted accounts still show up as followable on search bar

### ISSUE THREAD

**Issue by kacealexander** [tootsuite/mastodon#6054]
When the new account redirect went live, it didn't allow for those of us who have deleted/suspended accounts to go back and put redirects on them. (Just delete them, y'all. Delete the followers's follow to that account, too. We moved for a reason.)

So anyway! I asked Mastodon what those of us with deleted accounts should do about the fact all the deleted accounts show up on a search bar, and the dev behind the name said it wasn't a thing that happened anymore.

Sadly, it does. Typing "kacealexander" into the search box brings up my two deleted instances and my current one. All three offer Follow buttons if you click on them.

This is hella confusing for people searching for me. Can this be resolved?

Thanks for all you do! Masto's looking great and I'm super happy to be part of it,

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by webmind** [comment]
At the moment I'm quite happy I can still search of them, because else it gets hard to unfollow them. But I agree with #6064 that they shouldn't be in my follow/follower lists. But please don't remove the search function until that is fixed or there is another way to unfollow.

**Comment by danhunsaker** [comment]
@webmind You can always go to your profile and pull up your Followed list to unfollow folks from there.

**Comment by Gargron** [comment]
- Mastodon sends appropriate delete events to announce the account is gone
- Mastodon offers command-line tools to help admins clear out gone accounts

I don't see what else can be done so closing.

**Comment by wizzwizz4** [comment]
Marking deleted accounts as unfollowable can be done.

**Comment by Gargron** [comment]
Deleted accounts are deleted. They don't even show up.
