### ISSUE TITLE
please add filters to show only media/text toots in a column

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#606]
Not much more to be said here. When checking up on what's happened in the past few hours i'd like to go through the pretty stuff first, then see if there's interesting chat happening.

**Comment by trwnh** [comment]
Per recent conversations around this: https://mastodon.social/@Gargron/99582225404194272

After being made aware of this client: http://zatnosk.dk/playground/mastogram/

It definitely is something worth revisiting. A checkbox for text-toots and a checkbox for media-toots would be the easiest way to handle this, per-column.

**Comment by Gargron** [comment]
Done for public timelines and profiles, not possible for home timeline.
