### ISSUE TITLE
Request: could the 500 page become non-blinking?

### ISSUE THREAD

**Issue by wimvanderbauwhede** [tootsuite/mastodon#6060]
I'm sorry but I find the blinking 500 page (oops.gif) extremely annoying. Could it please be replaced by a non-blinking image? Thank you!

* * * *

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by serin-delaunay** [comment]
Note: this issue was mentioned  in the pull request which added this animation (https://github.com/tootsuite/mastodon/pull/5099#issuecomment-332009129, animation at top of page), but the comment was ignored by both the author/merger and approver of the PR.

**Comment by Cassolotl** [comment]
This makes sense considering the "autoplay gifs" setting is set to "off" by default for accessibility reasons.

**Comment by nightpool** [comment]
Vestibular disorder (the main concern for motion and animation, and the
reason autoplay gifs is off) talks mainly about movement that's *not* in
focus, or out if the corner of your eye. That's not a concern here as far
as I understand it, because the blinking computer is the only thing on the
page. This was the assessment I made in dev chat when I approved the PR.

I don't think it's blinking fast enough to cause concerns about triggering
epilepsy, but if it is that should be something we address

Otherwise I don't see any reason to change the animation.

**Comment by Cassolotl** [comment]
I'm not epileptic, but it makes my brain go blaaaeeeeururrughrghrghrgrh, and not just in an "I find this annoying" way. I'm also autistic, which might be part of that? I need gifs to stop playing for reasons other than vestibular disorder, which I attribute to being autistic.

**Comment by clarcharr** [comment]
I'm also autistic and it's generally just unpleasant to have stuff moving on the page like that.

Movement like the clouds on the front page is fine; movement like this is too much and IMHO shouldn't be there, GIFs turned on or off.

**Comment by clarcharr** [comment]
I added a PR to make the animation static at #6189.

**Comment by ykzts** [comment]
You can use [Animation Policy](https://chrome.google.com/webstore/detail/animation-policy/ncigbofjfbodhkaffojakplpmnleeoee) (Google Chrome).

or, edit `image.animation_mode` to `none` (Firefox).

![image](https://user-images.githubusercontent.com/12539/34599751-4611f8d8-f237-11e7-9078-61eaf12a32cf.png)

**Comment by serin-delaunay** [comment]
I don't know about Android Firefox, but Android Chrome doesn't allow extensions or provide any other way of blocking gifs.

**Comment by moggers87** [comment]
@ykzts that would disable all animated gifs, which is not the issue here. This particular gif has only 4 frames but a lot of movement, which is really quite unpleasant for me (as with @clarcharr and @Cassolotl, I have an autism spectrum disorder).

Is there any reason this gif has so few frames? Frame 4 is almost a completely different image to the other 3 and I think this is part of the reason this animation is affecting me.

**Comment by charlag** [comment]
Hello
I totally understand that it may not seem like a problem but I believe that this is a really poor default accesibility choice.
I don't have any issues diagnosed but for me looking at the fast gif for me than two seconds is really unpleasant, I imagine it can be much worse for some people.
The thing is, you see this pic involuntary. You never opt into this. It's mostly happening when you don't expect it.

I think we should make a compromise and maybe make it animate on hover? I understand that it will require js but I think it wouldn't hurt much. It could be a nice detail, like a dinosaur in Chrome: when nothing works you can play with it by hovering-unhovering the image.

Thank you for considering this.

**Comment by nightpool** [comment]
we're currently working to make the image slower and much less flashy

**Comment by ThibG** [comment]
@nightpool any progress on that?

**Comment by nightpool** [comment]
you'll have to ask gargron, last I heard he was exploring commissioning the original animator to add a couple more frames.

**Comment by moggers87** [comment]
Would a static image taken from one of the frames of the current GIF be acceptable?

This was proposed in https://github.com/tootsuite/mastodon/pull/6189

**Comment by Gargron** [comment]
I'm very sorry; I asked the artist, the artist didn't answer, it completely slipped my mind over time.

No, a still frame is not enough (and that PR picked the worst still frame, as well). Maybe we could add a bare minimum of inline JS to make it hover-on-play after all...

**Comment by connyduck** [comment]
I recently commissioned art for [Tusky](https://github.com/tuskyapp/Tusky), two images can be used as error images. You can use them for Mastodon as well if you want. 
https://github.com/tuskyapp/artwork/blob/master/art/tusky_error.svg
https://github.com/tuskyapp/artwork/blob/master/art/tusky_offline.svg

**Comment by clarcharr** [comment]
@Gargron I would have appreciated that feedback directly in the PR, especially if it had happened in the time frame where I was actually thinking about this.

I think that using the Tusky error artwork would be very appropriate. It's quite cute, and you have permission.

**Comment by nclm** [comment]
As great as the Tusky illustrations are (love them!), I think that for visual consistency the elephants on the main Mastodon client should remain from the same illustrator. The illustration with the elephant in from of the error screen is already really nice, it should just not be an animation. As a bonus, the animation could do **one** loop at a time when and only when clicked on, which could be a little fun and playful interaction (the user themselves getting the elephant to hit the keyboard!).

**Comment by Krands** [comment]
I read the whole issue. And someone explained to me what was the problem.

In the end, the whole animated image is not necessary. If it makes people sick or in distress because of the repetitive nature of the gif play, then the image should be changed to a still one for the sake of accessibility. A still image with the mascot looking at something that broke is not removing anything from the 500 error message. This error in particular is annoying, but you are adding more distress to people having vestibular disorder and/or facilitating sensory overflow for autistic people and everything else I don't know about.

You do need to step a bit back on your own expectations if you want to have your software more a11y compliant. Thus, a still image is enough, @Gargron.

**Comment by Cassolotl** [comment]
@Gargron 

>No, a still frame is not enough

No image at all would be better than something that is actively causing problems for disabled users.

>Maybe we could add a bare minimum of inline JS to make it hover-on-play after all...

That would be better than no changes! I vote for this.

**Comment by jmfcodes** [comment]
Is adding JS really necessary? This feels like overkill and may increase load times for users on older, slower devices or users with slower connections. Is a static image really that inconvenient for people who want lots of animation?

It's frustrating that Mastodon still isn't prioritizing accessibility after all this time, not even in this case when options and improvements have been offered over the last 8 months (like @clarcharr's PR and @connyduck's commissioned art).

Please prioritize accessibility.

**Comment by theotix** [comment]
There is a `prefers-reduced-motion` media query in css, but it's not very supported (and the better solution is still to remove the animation for everybody).

**Comment by raingloom** [comment]
> I'm very sorry; I asked the artist, the artist didn't answer, it completely slipped my mind over time.
> 
> No, a still frame is not enough (and that PR picked the worst still frame, as well). Maybe we could add a bare minimum of inline JS to make it hover-on-play after all...

why not a non-auto-playing video?

**Comment by lanodan** [comment]
> There is a `prefers-reduced-motion` media query in css, but it's not very supported (and the better solution is still to remove the animation for everybody).

Maybe it would be to enable the animation only for browsers that supports it and do not have it enabled? (As seen in the WebKit demo)

**Comment by ThibG** [comment]
Is there any progress on the gentler animation?
Also, wouldn't the first frame of the current animation actually be enough?
It looks like this:
![oops](https://user-images.githubusercontent.com/384364/50057726-9f2bf800-016e-11e9-84cf-f926a40701a0.png)

**Comment by ashleyhull-versent** [comment]
I approve of changing this for inclusivity reasons, but I also really love that animation.
Could this be a toggle?
