### ISSUE TITLE
Detect and IP block users of bitcoin client

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6062]
Since bitcoin uses port 8333, it should be pretty easy to detect and block bitcoin users.

Bitcoin is harmful to the environment, while most ppl who use mastodon aim to protect the environment. It sounds reasonable to me to block bitcoin users.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by coreyreichle** [comment]
How is this harmful to Mastodon users?

**Comment by coreyreichle** [comment]
As an aside, since Freenet is known to host copius amounts of child pron, should we detect, and block users with freenet running?

**Comment by SoniEx2** [comment]
So does Tor. We don't block Tor.

It's not about content. It's not about censorship.

**Comment by coreyreichle** [comment]
So, what's it about?  Blocking users from using their own software, because they use something you don't agree with?

Should seti@home users be blocked from using Mastodon as well?
