### ISSUE TITLE
Add additional protocols to URI schemes

### ISSUE THREAD

**Issue by maiki** [tootsuite/mastodon#6072]
Posting this after [a short discussion](https://discourse.joinmastodon.org/t/add-gopher-to-uri-schemes/696?u=maiki): please create links from [gopher](https://en.wikipedia.org/wiki/Gopher_(protocol)) URLs.

[SDF](https://mastodon.sdf.org/) runs a prominent gopher server, and we share the URLs constantly, but none of them are links. We currently have `http`, `https` ~~and `ftp`~~. It would help us if `gopher` were added. ^_^

Adding a request to add `ftp` and `irc` as well.

**Comment by crcx** [comment]
I'd like to see this as well.

**Comment by jamestomasino** [comment]
Easy and welcome addition

**Comment by algernon** [comment]
For anyone interested, as far as I understand [this](https://github.com/twitter/twitter-text/blob/36e245b4e6da41c8c5e3666e01f35cd2bb0bc5b0/rb/lib/twitter-text/regex.rb#L250) is where the change would have to be made. Something like turning that `https?` into `https?|gopher`.

I have not tried it, mind you, and am not planning to (not going to touch twitter projects), but if anyone's up for it, I hope the above helps.

Might add `ftp` to that aswell, because that does not seem to be supported either (just tried on my own instance running 2.1).

**Comment by maiki** [comment]
@algernon, to clarify for my own knowledge, the Mastodon project pulls in that library to parse URLs? I don't know much about how it is built.

:bouquet: for your thoughts. ^_^

**Comment by nightpool** [comment]
yeah this would require some changes to https://github.com/twitter/twitter-text, which we use for URL extraction. Here are the relevant lines:

https://github.com/twitter/twitter-text/blob/master/rb/lib/twitter-text/regex.rb#L246-L257

**Comment by wakest** [comment]
Would be great to get dat:// URI support. I’ve already come across numerous people posting dat links that I had to manually copy and paste to access. 

and maybe ipfs:// too, though it looks like they might still be trying to figure out some details of the implementation of how their URIs work. (https://github.com/ipfs/go-ipfs/issues/1678)

**Comment by maiki** [comment]
I think `dat` and `ipfs` would be great additions, but neither are listed on the [IANA scheme list](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml). In other news, I doubt we will be able to send any additional schemes upstream to Twitter.

These observations combined leas me to think we need to do two broad things:

1. Create a replacement text parsing library
2. Arbitrarily add schemes to it (like `ipsf://`), which means maintain a list

Thoughts? :smiley: 

I am not trying to start a new project and recruit folks, just thinking about solving this particular problem. Brainstorm with me!

**Comment by gemlog** [comment]
@maiki My first thought was how difficult is it to implement those URIs that frankly are not used much outside of a small community. I looked at the linked code in the twitter-text link and it looked fairly straight-forward (I was weirded out a bit 'coz my brain thot it was reading python and I don't know ruby..).
Then I thought of some (to me) fun URIs if we had authentication down solid.
To be truly painless to extend to new URIs cheaply it would have to be reworked though vs just adding cases?

**Comment by virtadpt** [comment]
It would be nice to be able to click on a magnet URL and get some kind of response, too.  Maybe a pop-up button to copy it automatically into the local clipboard, for pasting elsewhere?

**Comment by JamesHealdUK** [comment]
@virtadpt Actually, I could have sworn that you can open magnet links that have a "open with" dialogue, in  Firefox at least iirc. That would be awesome!

But otherwise, definitely big +1 from me too.

**Comment by rysiekpl** [comment]
+1 on `magnet://`, `gopher://`, `ipfs://`, `irc://`.

Really not convinced about `ftp://` though. This [terrible Frankenstein of a protocol should have died a long time ago](http://mywiki.wooledge.org/FtpMustDie). May I suggest `sftp://` instead?

**Comment by wakest** [comment]
wait does #7810 mean you implemented this?!

**Comment by nightpool** [comment]
"Add dat, dweb, ipfs, ipns, ssb, gopher protocols to URL extractor"
