### ISSUE TITLE
Mastodon shouldn't have a built-in save UI

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6076]
We need a new browser-side bookmarks API, something that gives websites more control and the ability to autosync them.

Maybe make it so any added bookmarks are only visible if you're browsing the website that added them. (i.e. each tab would have a different bookmarks bar.) They'd go at the end of the user's bookmark bar by default, with an option for adding a "website bookmarks" menu or something.

Let's do something that benefits more websites/services, y'know?

(PS: Either github is lagging or I somehow can't post on the "save/like" issue)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment]
> We need a new browser-side bookmarks API

Out of the scope of this project.

> Let's do something that benefits more websites/services, y'know?

We can't do that. Try submitting your suggestions to [WICG](https://discourse.wicg.io/).

**Comment by SoniEx2** [comment]
You can submit it too. I suck at this stuff.
