### ISSUE TITLE
On "like and save separately"

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6086]
(aka #1178. Really tho github is being really weird with that issue)

I have made a thread for a trivial change to browsers' already existing bookmark features, which is both more manageable and more accessible than what has been suggested on that thread.

You can find it over at https://discourse.wicg.io/t/simple-bookmarks-api/2487

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I just added your comment over at #1178, so this can probably safely be closed. Not sure why it wouldn't let you post it there. :/
