### ISSUE TITLE
Implement iOS metadata tags for iMessage?

### ISSUE THREAD

**Issue by sophia-park** [tootsuite/mastodon#6095]
When I link to my toot via iMessage, it looks like this:

![c9d2cc2c-0b3e-4968-a8ed-f50ce8d67d71](https://user-images.githubusercontent.com/20846414/34329982-ce639236-e8e2-11e7-8ab5-2d763acda879.jpeg)

Compare this with linking to a tweet:

![f897f79d-16e7-44f6-927a-3885d1c76de3](https://user-images.githubusercontent.com/20846414/34329983-dc3efdaa-e8e2-11e7-9071-f9fc6b066e90.jpeg)

This rich content is supplied in iOS in its own metadata format, [annoyingly enough](https://stackoverflow.com/questions/39847269/ios-10-messages-app-url-preview). 

Presenting our toots beautifully contributes to easier outreach on a popular messaging platform for end users, but I understand it may be low priority.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by unarist** [comment]
[The post you linked](https://stackoverflow.com/questions/39847269/ios-10-messages-app-url-preview) is saying about title+domain+image card, which can be implemented with OpenGraph protocol or Twitter card. We already implemented those protocols so you can see those card if you paste an URL of the toot with an image, For example, Facebook post seems rendered like this too.

![image](https://user-images.githubusercontent.com/705555/34611535-4b9ce268-f269-11e7-854e-0f088557d326.png)

However, user+domain+icon+body(+image) card seems Twitter-specific behavior...

**Comment by Gargron** [comment]
I looked into this and didn't find anything I could do. Some apps like Discord have a special preferential treatment of Twitter links. :angry:

**Comment by dmd** [comment]
The relevant documentation is https://developer.apple.com/library/archive/technotes/tn2444/_index.html

**Comment by dmd** [comment]
@Gargron This is a trivial fix. The only thing Mastodon needs to do is put the toot into `og:title` instead of `og:description`, as described in the above documentation.

**Comment by Gargron** [comment]
Where did you see that? I only see

> Titles should be short and sufficiently specific that different pages on the same site are distinguishable. For example, product pages should indicate the product name in the title; articles should provide the title of the article.

**Comment by dmd** [comment]
Just so.  Think of a mastodon *user* as being a site, rather than the entire instance. Then, within each user, you want each individual toot page to be distinguishable; so, the `og:title` should differ between toot pages.

**Comment by dmd** [comment]
Actually, you know what, I take it back; I don't know what's going on here after all.

```
❯ # using this user agent to force Twitter to do server-side HTML generation
❯ curl -s -A "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" https://twitter.com/danieldrucker/status/1283556827003748352 | grep og:
    <meta  property="og:type" content="article">
    <meta  property="og:url" content="https://twitter.com/danieldrucker/status/1283556827003748352">
    <meta  property="og:title" content="Daniel M. Drucker on Twitter">
    <meta  property="og:image" content="https://pbs.twimg.com/profile_images/1080468725978017793/3kCLTK7n_400x400.jpg">
    <meta  property="og:description" content="“All bitcoin sent to my address will be sent back halved. If you send $2,000, I will send back $1,000! This is an unlimited time offer.”">
    <meta  property="og:site_name" content="Twitter">
```

And that's the same way Mastodon is doing it, so I don't know why Messages works in one case but not the other.

**Comment by Gargron** [comment]
It’s very likely that Apple has hardcoded a behavior specifically for twitter.com, Discord does the same. It’s a shame really.
