### ISSUE TITLE
Enhancement Idea: Bookmarks for Private Use

### ISSUE THREAD

**Issue by ZiiX** [tootsuite/mastodon#610]
I'd enjoy bookmarking posts in addition to favorites as well (and these can be shared with approved followers or not). I like how ig incorporated this feature but they're doing it to better farm us bc we would take screenshots for private.

I think a bookmark feature could be more productive to the end-user as opposed to outwardly facing. For example, someone could not only sort bookmarks later but add a reminder to follow-up or even forward?  That's the best thing about Mastodon is that the content is meant to be beneficial to our lives and not the other way around for shareholders.  It'd be great to curate some things easily. Private tags would probably be too complex in addition to the bookmarks but you see where I'm going. 

This could be a great feature for future corporate accounts too needing to manage customers from their instance to respond to: features, bugs, customer support, routing to a moderator on their instance that handles customer support, etc. The api would be a wonderful hook too for productivity into other apps like the widely used slack, etc.

Thanks for all the great work. Amazing.

**Comment by Gargron** [comment]
Fixed in #7107
