### ISSUE TITLE
When clicking "copy" on the emojo list it doesn't always stay on the same page

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#6112]
Say I'm on `/admin/custom_emojis?by_domain=cybre.space&page=4&shortcode=`, so I've used the search feature. Then I'll click on the "Copy" link next to an emojo. The only information that link retains is the page number, so I'll get a completely different list of emojos afterwards. This should be an easy fix (add `by_domain` and `shortcode` fields to the "Copy" link).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by beatrix-bitrot** [comment]
uhhhhhhh k should have a fix for this soon...
