### ISSUE TITLE
Feature request: Follow another server's federated timeline

### ISSUE THREAD

**Issue by corbindavenport** [tootsuite/mastodon#6116]
Some suggested it here: https://mastodon.social/@hq/99243972837208973

I think this would be super useful for small/private instances, where the users might not follow enough people to keep the server's federated timeline filled.

* * * *

- [✓] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
I think this is a duplicate of #1053. I think it's a good idea, and it's the second most popular issue of 784 issues! :) I recommend heading over there, adding any comments (like that link, maybe), subscribing, thumbs-up, that kinda thing. (Also closing this issue, if you're satisfied with joining in with the older issue.)

**Comment by corbindavenport** [comment]
Ah, you're right, this is a duplicate. Closing.
