### ISSUE TITLE
Pinned toots do not show up in the multi-column UI.

### ISSUE THREAD

**Issue by egypturnash** [tootsuite/mastodon#6117]
If you pin a toot, it only shows up when you visit server.name/@username in a new tab. It does not show up when you bring up a user's profile in the main web UI by clicking on their username.

I've seen this on both my own instance (which is still on 2.0.0, I need to spend a day wearing my Admin Hat) and on mastodon.social.

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by CosineP** [comment]
Here's an example I just came across if that's helpful.

Account: https://elekk.xyz/@gaymer

Status: https://elekk.xyz/@gaymer/99267281977503352

**Comment by trwnh** [comment]
Agreed. Unpinning toots is unnecessarily hard right now, and wasn't immediately apparent when I tried to do it just now. It should be much easier to do and manage.
