### ISSUE TITLE
My Mastadon account was removed without breaking any rules

### ISSUE THREAD

**Issue by StreetTeamAC** [tootsuite/mastodon#6118]
My Mastadon account was removed by the "Community Moderator Noëlle" who's page is here: https://mastodon.social/@CM_noelle

This of course was not before being berated by 2 other members who are bigoted. 

I've only been on Mastadon for less than 48 hours. So what are the guidelines for moderators who abuse their powers?

**Comment by nightpool** [comment]
This is the issue tracker for Mastodon, the software project, and is not a forum for disputing individual moderation decisions for mastodon.social, which is only one server out of many running Mastodon.

**Comment by StreetTeamAC** [comment]
So where direct this issues towards?

**Comment by nightpool** [comment]
You'd have to ask the moderation team of mastodon.social, which only has a partial overlap with people involved in maintaining the software project Mastodon. You can try emailing the owner of the server and project, Gargron, but it's very unlikely that he'll overturn the ban considering the behavior you exhibited. 

Make sure you understand mastodon.social's [Code of Conduct](https://mastodon.social/about/more) and the behavior expected of community members before appealing the ban.

Again, mastodon.social, which you got banned from, is just **one** server running the Mastodon software, and there are many other servers with less strict moderation policies that are fully interoperable. It looks from your toots (before they got deleted) that you don't agree with the code of conduct enforced by mastodon.social. I would suggest you choose another server with a different code of conduct, which you can look for here: https://instances.social/

**Comment by StreetTeamAC** [comment]
"it's very unlikely that he'll overturn the ban considering the behavior you exhibited" ~What behavior are you reffering to @nightpool ? The only behavior I exhibited has been "tooting", which isn't against the rules. So i'm confused as to why the tone of that statement assumes that i'm guilty of something. However I will contact him., I made sure to take screenshots and document everything that has taken place. So if he doesn't comply, then that will be a reflection upon Mastadon, and not me. 

Yes I will be appealing this ban. Not because I want to use this service, but because I want it to be known that I did not violate any guidelines or rules. I don't mind when rules are enforced. However when someone takes action based on emotions and not the code of conduct listed then that's another issue. So yes, I have problem with that @nightpool 

I will be emailing Gargron.

**Comment by nightpool** [comment]
I am going to be locking this issue now that you've found the proper venue for this discussion. Your aggressive and combative behavior on this issue tracker—already a wildly unfit venue which you *insist* on abusing for this discussion—is a poor reflection on you no matter what other posts you may have made before or since. If you do choose to return to the project in some fashion, I hope you can come back to it with a more open mind.
