### ISSUE TITLE
Impossible to unfollow someone who's "moved"

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#6128]
Here's one of my old accounts that I still follow from ephemeral.glitch.social, but I've set up that redirect notice:

![screen shot 2017-12-29 at 12 04 53](https://user-images.githubusercontent.com/6607512/34436743-82da91fa-ec90-11e7-9bae-1fa4be6522c5.png)

It's not possible to unfollow them, because the follow/unfollow icon has gone.

I think the icon should be there when you follow them, so that it's possible to unfollow - but when you have unfollowed them it should disappear so you can't follow them again.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
What's the use case for unfollowing a moved account?

**Comment by Cassolotl** [comment]
It makes it easier to tidy up your follows, which means it's easier to find a particular person when you need to find them by scrolling through follows. It lets you make your follower count accurate. If you dislike someone and seeing them in your follows is unpleasant but you can't unfollow them because they marked themselves as having moved they're stuck in your follows unless you block and unblock them (messy).

If I can easily unfollow an inactive account *except* when the owner has marked it inactive that seems topsy-turvy to me. If someone has a way to control whether or not you can unfollow them (even if you can bodge it by blocking and then unblocking them) that seems wonky too. I just think that I should be able to unfollow anyone, any time, for any reason.

**Comment by Cassolotl** [comment]
Someone on Mastodon just told me that they suspect that the thing that informs you on someone's profile that they've moved also does something that changes where they're following you or something? I don't fully understand it, but there's no indication that the feature does this and I'm pretty confused! Is anyone able to clarify?

**Comment by unarist** [comment]
Even if it automatically follows destination account, still following old account is useful because followers can't see past private posts without following old account. So I think anyone should be allowed to follow/unfollow them even after migration.

**Comment by espectalll** [comment]
Hey, has this been reverted recently?
