### ISSUE TITLE
Content warning field is too small to type in comfortably on mobile

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#613]
It's hard to type in a single-line-field on mobile when the content is longer than the field. Therefore, it would help if the content warning field would automatically expand to show multiple lines or something similar. (I get that it's single line to prohibit newlines, and I don't have a solution for that)

**Comment by wxcafe** [comment]
I don't think content warnings over 33 chars are typed often enough on mobile that this matters to many people, tbh. Closing.
