### ISSUE TITLE
I have one website. I used mastodon oauth service for login to my website and it works fine. Now I want to migrate users of my website to mastodon server, can anybody tell me how to do that?

### ISSUE THREAD

**Issue by amitmoralwar** [tootsuite/mastodon#6148]
[Issue text goes here].

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by m4sk1n** [comment]
Ask on discourse.joinmastodon.org and close this issue, as it’s not an issue with Mastodon in fact…

**Comment by mareklach** [comment]
You could close an issue yourself on GitHub, just change it from the green ‘open’ label, to the red ‘closed’ label in Github’s interface when you are logged in, and open the issue thread.
