### ISSUE TITLE
two factor as part of security

### ISSUE THREAD

**Issue by jonazc** [tootsuite/mastodon#6150]
Does two factor auth needs to have its own link in the settings menu? Could it not just be part of Security?

![screenshot_2018-01-02_00-05-32](https://user-images.githubusercontent.com/22523959/34471746-0d74f9e6-ef51-11e7-9fc4-6ddf01adbec4.png)

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I think it's fine as it is.
