### ISSUE TITLE
Recover 2FA with email

### ISSUE THREAD

**Issue by kpcyrd** [tootsuite/mastodon#6151]
I think it might be a good idea to have an opt-out option to reset 2FA by email. Some people would obviously want to disable this option, but it would be less scary to enable 2FA. It's very likely that people can't find their backup code after losing their phone, especially since "write down your backup code" and "lose your phone" might be multiple years apart.

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by patf** [comment]
Passwords can also be reset via email. This would make a compromised email address a single point of failure even for 2FA-enabled accounts. At the very least this should be opt-in, but I'm not a fan of adding this at all.

The 2FA flag on accounts can be toggled by admins, that's how many instance admins have handled this so far. We could add some guidance (docs) for instance admins on how to handle 2FA account recovery, and make some UI changes in the login flow that recommend contacting the instance admin for recovery. A good approach would be manual email confirmation with a waiting period, IP/GeoIP comparison and perhaps some sort of check for suspicious activity prior to the recovery request (email change or similar).

**Comment by kpcyrd** [comment]
@patf 2FA is mostly about password compromise due to reuse, not necessarily about email compromise. For the later you would just enable 2FA on your email account as well. If you're still worried you would opt-out of email recovery as well. This is somewhat common among other 2FA implementations. Changing your email adress should require 2FA confirmation anyway.

One might argue that favoring a manual process that is prone to social engineering over defaults that reduce the risk of getting locked out of your account in the first place is a worse trade-off security wise. Especially since you can't opt-out of that if it's that common for people to get locked out of their account due to 2FA.

**Comment by patf** [comment]
> 2FA is mostly about password compromise due to reuse, not necessarily about email compromise.

It's also about requiring two factors. You're reducing it to one (access to the email inbox) with this.

> This is somewhat common among other 2FA implementations. 

Could you share some examples? I've recently looked at a number of major 2FA implementations (for #6077) and do not recall any having an email fallback, at least not without a significant waiting period during which the account owner gets contacted repeatedly (i.e. 30 days for Microsoft)

> One might argue that favoring a manual process that is prone to social engineering over defaults that reduce the risk of getting locked out of your account in the first place is a worse trade-off security wise.

I'm not opposed to an automated process handling this, but I think that's not a trivial thing to implement. We could certainly start with an admin option to send users a "reset 2FA" link, perhaps with a waiting period. That would allow instance admins to perform some of the more stringent checks I mentioned.

**Comment by kpcyrd** [comment]
Kraken allows very granular configuration about how and when 2FA can be reset or changed.

A microsoft-style "notify owner and wait X days" solution would work for me. This would move the burden of identity verification from the instance administrator to the email provider, who is usually better prepared for this. Again, a user is allowed to disable this, in which case the account should remain permanently locked.

**Comment by Gargron** [comment]
I believe that this should not be automated. The 2FA screen displays a contact e-mail of the sysadmin, the sysadmin can exert judgement on whether the 2FA disable request is legitimate or not, otherwise it defeats the point of having 2FA.
