### ISSUE TITLE
Emails contain escaped special characters, e.g. &gt; rather than >

### ISSUE THREAD

**Issue by PurpleBooth** [tootsuite/mastodon#616]
![image](https://cloud.githubusercontent.com/assets/133327/22818392/e78f3f44-ef64-11e6-9e41-3dc132f45882.png)

I would expect these to be displayed as ">" rather than `&gt;`

**Comment by wxcafe** [comment]
is this still a problem?

**Comment by nightpool** [comment]
I haven't seen this.

**Comment by nightpool** [comment]
reproduced

**Comment by wxcafe** [comment]
ah frick

**Comment by nightpool** [comment]
![image](https://user-images.githubusercontent.com/233815/30840319-9433e870-a244-11e7-847b-ff5954e99e4e.png)

**Comment by nightpool** [comment]
priority high is a little much, methinks? I don't think anyone even looks at these emails anyway lol

**Comment by nightpool** [comment]
Looks like the problem is that we're sending a text/plain email but also doing HTML escaping:

![image](https://user-images.githubusercontent.com/233815/30840365-c6eac090-a244-11e7-8d02-e6c7fe0d036b.png)

**Comment by wxcafe** [comment]
I know people who only use social media through email notifications. Either way it’s a broken feature

Clément 'wxcafé' Hertling

**Comment by nightpool** [comment]
did you reply from the github email just to make a point.

anyway i don't disagree it's a bug but it feels much much less severe then
"priority high"

**Comment by wxcafe** [comment]
Nah it’s just that it’s 5:20 am so I’m in bed and GitHub mobile is shit. But yeah I get GitHub notifs via email a lot and it’s really helpful. I don’t use Mastodon emails but I know people who do and they need it.

It might be a bit too severe but tagging an issue too high isn’t that important, and it’ll ensure that it gets fixed before 2.0...

Clément 'wxcafé' Hertling

**Comment by Gargron** [comment]
Is this still an issue?

**Comment by wxcafe** [comment]
given the new email template I guess not

**Comment by wxcafe** [comment]
![screenshot from 2018-02-14 10-12-48](https://user-images.githubusercontent.com/3009327/36196011-a52c3dc2-116f-11e8-8d4a-e46831200462.png)

works fine now
