### ISSUE TITLE
Missing translation for Otter Browser user agent

### ISSUE THREAD

**Issue by m4sk1n** [tootsuite/mastodon#6165]
![screenshot_20180103-070156](https://user-images.githubusercontent.com/21127288/34510416-0d7554fa-f054-11e7-90e7-af3577ec6cf3.png)
`browser` gem can detect Otter Browser, but there’s no string for this browser in en.yml file, so it can’t even use the default one… :)

**Comment by mftaff** [comment]
@m4sk1n  Hey I am relatively new to open source contributing. Mind if I have a go at this?

**Comment by Kjwon15** [comment]
![image](https://user-images.githubusercontent.com/5047683/34851502-a0b1501e-f76d-11e7-92d4-94ec5a36f90e.png)

I have same issue with Electron.
`<span …>` should be removed or rendered correctly.
