### ISSUE TITLE
URLs and hashtags aren't turned into links when in the header of a toot with a CW

### ISSUE THREAD

**Issue by maxlath** [tootsuite/mastodon#6181]
from [this toot](https://mamot.fr/@jaxom_kaplan/99292239414381555), it seems that URLs and hashtags aren't turned into links when in the header of a toot with a CW, not sure if it's a bug or a feature :)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Jaxom99** [comment]
I'm the author of the toot, it was posted on FF57.0.3 on macOS 10.11.6. (if that helps).

**Comment by Cassolotl** [comment]
This has come up in a few closed issues, of which this is a duplicate. [Here's Gargron's final word](https://github.com/tootsuite/mastodon/issues/699#issuecomment-311999125). It was six months ago and I don't know if it's going to change, but hopefully this helps a bit!

**Comment by Jaxom99** [comment]
Thanks for referencing this ! It shall be noted as a conception choice, then, and the issue can be closed as "won't fix"... until someone with sufficient time and skill finds a way to do it 😄

**Comment by maxlath** [comment]
thanks @Cassolotl, my mistake, I only checked opened issues ><
