### ISSUE TITLE
Enable use of mastodon without javascript

### ISSUE THREAD

**Issue by WhilelM** [tootsuite/mastodon#6186]
As a matter of security, I think mastodon should be usable without javascript. May it be ?
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
I saw #3634 which is a different matter

**Comment by zcdunn** [comment]
Pretty sure this came up before and Gargron's stance is that is not a priority of the official web UI and anyone is free to build a third party UI to meet their specific requirements

**Comment by sorin-davidoi** [comment]
While technically possible, it requires extensive refactoring and introducing another layer of system-level dependencies (Node.js). Not sure what you would gain in terms of security since you already trust the server (and by default Mastodon doesn't include any third-party scripts).

**Comment by WhilelM** [comment]
@zcdunn a link to these should be usefull then

@sorin-davidoi Trusting a server with my toots and contacts is one thing, trusting it for executed code in my browser on my personal computer is another thing.

**Comment by charlag** [comment]
@WhilelM web UI uses same APIs that any other app would. As @sorin-davidoi said, nothing stops you from using another front-end.

**Comment by Gargron** [comment]
You could use a native or CLI app to use Mastodon. I will not build an extra interface. The beauty of the JavaScript-based web UI is that it reuses the same API as all other apps, so things don't need to implemented multiple times in Ruby.

**Comment by gulkily** [comment]
Often it is not just a matter of security, but also accessibility. On an older device, the Web may not be usable with JS enabled for performance reasons.

**Comment by zzo38** [comment]
Even if it cannot be used without JavaScripts, link to API documentation which is readable without JavaScripts (without trying to hide the link to make it difficult to find), and an explanation of the URL if necessary, is important to have.

**Comment by maltfield** [comment]
fyi, it appears that there is at least one alternative frontend that doesn't require javascript: brutaldon:

 * https://github.com/jfmcbrayer/brutaldon
 * https://git.carcosa.net/jmcbray/brutaldon

**Comment by zzo38** [comment]
Although alternative front-ends are possible, it would help to have a (documented) way to easily detect the use of Mastodon (from the HTML file or from HTTP response headers or both) so that you can program your computer to automatically load whatever alternative front-end you want to, regardless of what instance of Mastodon you are connected to (since there are many instances and you can easily make up your own ones, it would help to be able to automatically detect them).

**Comment by maltfield** [comment]
See also [noscript Twitter alternative without requiring javascript (JavaScript-free Mastodon)](https://softwarerecs.stackexchange.com/questions/90894/noscript-twitter-alternative-without-requiring-javascript-javascript-free-masto)

 * https://softwarerecs.stackexchange.com/questions/90894/noscript-twitter-alternative-without-requiring-javascript-javascript-free-masto
