### ISSUE TITLE
Apply #4427 to bios too

### ISSUE THREAD

**Issue by clarcharr** [tootsuite/mastodon#6191]
PR #4427 modified the character limit for posts to exclude the domain part of @mentions and shrink URL sizes, but this sadly doesn't apply to bios as well. Including multiple @mentions or a particularly long URL can fill up a bio's character count when the change made to posts should help fix this.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by clarcharr** [comment]
This should be tagged as a bug.

**Comment by Gargron** [comment]
Fixed in #9717
