### ISSUE TITLE
the dump-notifs option and how to improve it

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#620]
first: a confirm (yes/no) would be really great, or an undo option, if that's possible.
i would also suggest moving it from the column title itself into the notification options, and to make it present there in all columns

if the yes/no confirm exists, it would also be extremely useful to be able to require a confirm when boosting things. whether that be all posts or just a setting isnt a big deal to me.

**Comment by marrus-sh** [comment]
A thought regarding notification clearing is that it might be better to configure this as essentially a user setting, which internally is stored as `notifications_since_id` or similar. Pressing the clear button would set `notifications_since_id` to be the latest notification, and the web client would only pull notifications (using `since_id` in the API) which had an `id` which was greater.

This would preserve notifications internally in the Mastodon database, making notification dumping an easy process to revert (just clear `notifications_since_id`). (On the other hand, it would mean that non-Mastodon clients would have to come up with their own means of doing this.)
