### ISSUE TITLE
Update "follow" state in web UI before request completes

### ISSUE THREAD

**Issue by mjourdan** [tootsuite/mastodon#6205]
Sometimes, when I click to follow some user, nothing happens for several seconds. So I click again, and again, wondering if I did press correctly my touchpad… Then, It may happen I just followed / unfollowed the guy. The UI should immediatly show the user as followed, or at list give some acknowledgement. See for examples this article on UxPlanet.org about [Optimistic UIs](https://uxplanet.org/optimistic-1000-34d9eefe4c05).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
Perhaps a better title would be "Follow button should indicate an indeterminate state", since the real problem seems to be a lack of responsiveness when clicking the follow button.
