### ISSUE TITLE
Custom emojis in display name

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#6206]
What about custom emojis in display name?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I think someone else has already requested this feature here: #5666 Add your +1 there maybe? :) If you agree that this is a duplicate you could close your issue.

**Comment by koyuawsmbrtn** [comment]
@Cassolotl yeah, i'll add my +1 there. also i'll change the title to only in display name.
