### ISSUE TITLE
confirm dialog for boosts

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#621]
if a yes/no confirm is possible, it would be extremely useful to be able to require a confirm when boosting things. whether that be all posts or just a setting to turn on isn't a big deal to me. i've seen many complaints for this

**Comment by hoodiek** [comment]
referenced in #620

**Comment by mitchellurgero** [comment]
Agreed - I will see if I can learn ruby just for this. lol

**Comment by blackle** [comment]
fixed with referenced PR
