### ISSUE TITLE
Reset password emails do not work

### ISSUE THREAD

**Issue by Jack3113** [tootsuite/mastodon#6213]
Hi, everyone

I am the administrator of mastodon.rock and the reset password emails do not work. Many users report this problem and I reproduced it too.

The email confirmation when a new user create his account works but not the reset password email.
My instance is on a Docker and the logs seem good without any error : 

`sidekiq_1    | 2018-01-07T03:23:59.509179045Z 2018-01-07T03:23:59.508Z 10 TID-gsdpx9zm4 ActionMailer::DeliveryJob JID-05307d6a01c59d34dd17d0ae INFO: start`
`sidekiq_1    | 2018-01-07T03:23:59.678108259Z 2018-01-07T03:23:59.677Z 10 TID-gsdpx9zm4 ActionMailer::DeliveryJob JID-05307d6a01c59d34dd17d0ae INFO: done: 0.17 sec`

I checked my spam folder too.

The instance is release v2.1.0.

Thanks in advance.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by patf** [comment]
A bug affecting email confirmation links was introduced in 2.1.1 and fixed in 2.1.2 (via #6187). I'm not sure if it affected password resets too, but it's possible. I saw that your instance is now on 2.1.2, any chance the bug is gone now?

If not, is the problem that the mail is not being sent at all, or that the link is not working?

I tested this on my instance running 2.1.2 and everything worked on my end.

**Comment by Jack3113** [comment]
I updated my instance in v2.2.0rc1 and my logs is now more verbose. Here, the logs when I try to reset a password :


```
sidekiq_1    | 2018-01-21T23:54:00.338Z 100 TID-gmwsbrmkw ActionMailer::DeliveryJob JID-258dfc850f64edf9ca611979 INFO: start
sidekiq_1    | [ActiveJob] [ActionMailer::DeliveryJob] [fcadcb3f-a21f-4f59-9b6f-9b66b1bcfd22] Error performing ActionMailer::DeliveryJob (Job ID: fcadcb3f-a21f-4f59-9b6f-9b66b1bcfd22) from Sidekiq(mailers) in 15.3ms: ActionView::Template::Error (Webpacker can't find icon_lock_open.png in /mastodon/public/packs/manifest.json. Possible causes:
sidekiq_1    | 1. You want to set webpacker.yml value of compile to true for your environment
sidekiq_1    |    unless you are using the `webpack -w` or the webpack-dev-server.
sidekiq_1    | 2. Webpack has not yet re-run to reflect updates.
sidekiq_1    | 3. You have misconfigured Webpacker's config/webpacker.yml file.
sidekiq_1    | 4. Your Webpack configuration is not creating a manifest.
```

**Comment by Aguerin42** [comment]
There seems to be a problem with some instances. I tried to register on [i.write.codethat.sucks](https://i.write.codethat.sucks/about) and on [mamot.fr](https://mamot.fr/about) but I didn't receive any mail. I tried (with the same address) to register on [mastodo.top](https://mastodon.top/about) and I got the email immediately. 

-------

Il semble y avoir un problème avec certaines instances. J'ai essayé de m'inscrire sur [i.write.codethat.sucks](https://i.write.codethat.sucks/about) et sur [mamot.fr](https://mamot.fr/about) mais je n'ai reçu aucun mail. J'ai essayé (avec la même adresse) de m'inscrire sur [mastodo.top](https://mastodon.top/about) et j'ai reçu le mail immédiatement.

**Comment by s0r00t** [comment]
I just installed an instance on my personal server, but I am not receiving the registration mail, because of a similar error (missing icon_email.png instead)...

**Comment by Gargron** [comment]
@Jack3113 Your issue is #6295

@Aguerin42 Your issue is not related to software
