### ISSUE TITLE
Content warning field still accessible when the toggle is unset

### ISSUE THREAD

**Issue by marrus-sh** [tootsuite/mastodon#623]
When the content warning toggle is unset, the input is still accessible to the browser through other means. It should be disabled.

## Steps to reproduce:

1. Click into the main compose textbox
2. Type `shift+tab`
3. Accidentally type a character (`` ` ``, maybe)
4. Post your toot

## Expected result:

No content warning; the toggle is unset

## Actual Result:

Whoops there's a content warning on that there toot

**Comment by Gargron** [comment]
I think I fixed this in 677e95031e179ccdd69162002ccbfb482f396e4e by setting `display: none` on collapsible elements. Can you confirm?

**Comment by marrus-sh** [comment]
confirmed!!
