### ISSUE TITLE
We're sorry, but something went wrong on our end.

### ISSUE THREAD

**Issue by dinggangwang** [tootsuite/mastodon#6233]
[Issue text goes here].
I want to add new followers in Federated timeline, but get the message:"We're sorry, but something went wrong on our end." Please help to resolve.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
Which instance are you on?

**Comment by dinggangwang** [comment]
w3.freechinaweibo.com

2018-01-09 17:11 GMT-08:00 Cassolotl <notifications@github.com>:

**Comment by dinggangwang** [comment]
thank you so much.

2018-01-09 17:14 GMT-08:00 路德 <wdg0606@gmail.com>:

**Comment by Cassolotl** [comment]
I was going to say it seems like something I would go to my local admin about, but it looks like your instance is very new (2 users, 2 statuses) - so you're probably the admin, right? (If that is the case, I don't think I can help much here!)

**Comment by dinggangwang** [comment]
So what your meaning is you cannot help much more? Why? Please tell me how to resolve as i am a admin.

**Comment by Cassolotl** [comment]
Because I don't know enough. I'm just a volunteer, I've never set up my own instance, but there are some problems I *can* help with. I'm sorry I can't be more helpful, but I hope someone else can help more!
