### ISSUE TITLE
We're sorry, but something went wrong on our end.

### ISSUE THREAD

**Issue by dinggangwang** [tootsuite/mastodon#6234]
[Issue text goes here].
I upload the image of avatar of my website.  It has showed out "We're sorry, but something went wrong on our end. "
what is the reason, please help.
* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Are you using Docker with docker-compose? Have you updated permissions on the public/system folder? `chown -R 991:991 public/system`

**Comment by DanielnetoDotCom** [comment]
Hi @Gargron 
I am helping @dinggangwang  on installation

Yes we use Docker.
Are you talking about the dir `/home/mastodon/live/public/` ?

**Comment by DanielnetoDotCom** [comment]
Any news?

**Comment by Gargron** [comment]
`/home/mastodon/live/public/system`

**Comment by DanielnetoDotCom** [comment]
@Gargron yeah, you right thanks for the help is working now :)

**Comment by DanielnetoDotCom** [comment]
BTW, I can not close the issue
