### ISSUE TITLE
Static GIFs not displaying properly, saved as empty files

### ISSUE THREAD

**Issue by duxovni** [tootsuite/mastodon#6237]
Static GIFs (both local and federated) aren't displaying properly on my instance. Looking at the actual files saved on disk, the `small` versions of GIF attachments are fine, but the `original` versions are empty files.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by koyuawsmbrtn** [comment]
I can confirm this bug on my instance

**Comment by sdukhovni** [comment]
Still seeing this after upgrading to v2.2.0

**Comment by sdukhovni** [comment]
I'm running Debian stretch if that's relevant; @koyuawsmbrtn , are you also running something other than Ubuntu Server 16.04?

**Comment by koyuawsmbrtn** [comment]
@sdukhovni I'm running Ubuntu Server 16.04

**Comment by Hanage999** [comment]
I have the same issue. I am not sure when the problem started. It still exists on the latest master (ef12a2b). My instance runs on Ubuntu 16.04 virtual machine hosted by Parallels Desktop, and it is located behind Nginx reverse proxy. It means that proxy_pass to 127.0.0.1:3000 is changed to <ip address of a different node>:3000. I don't know if this makes any difference, though.

**Comment by Gargron** [comment]
As soon as I know I'll submit a fix, but it's not obvious to me. This happens in lib/paperclip/gif_transcoder.rb when non-animated GIF file is forwarded to the default paperclip processor.

**Comment by jeroenpraat** [comment]
@Gargron  Do you need an example?
