### ISSUE TITLE
Add localization for Bulgarian

### ISSUE THREAD

**Issue by svetlik** [tootsuite/mastodon#624]
I open this issue and volunteer to work on it.

Is it enough to just submit a PR with the translations when ready?

**Comment by Gargron** [comment]
Yes, that's fine.

**Comment by svetlik** [comment]
Thank you.

I took the liberty of creating https://github.com/tootsuite/mastodon/pull/645 beforehand, just in case anyone else shows up and wants to help out with BG translation (although it probably won't happen, and I'm planning to not take too long).
