### ISSUE TITLE
Highlight differences between replies and simple toots

### ISSUE THREAD

**Issue by jpdeplaix** [tootsuite/mastodon#6243]
Currently if you reply to yourself (for example) nobody can see the distinction between a separated toot and the reply without clicking on it.
Could there be message saying something like ```X replied``` on the top of the toot (in place of ```X boosted``` for example) ?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
This is a duplicate of *add an hint that a message is part of a thread #4716*, I think?

**Comment by jpdeplaix** [comment]
Mmh, yes it definitely is. Sorry for that.

**Comment by Cassolotl** [comment]
No worries, and thanks!
