### ISSUE TITLE
Adding a license clause, which prohibits using Mastodon's code against it's philosophies

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#6253]
Guess that's pretty self-explanatory.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ykzts** [comment]
[The Open Source Definition](https://opensource.org/docs/osd) includes "6. No Discrimination Against Fields of Endeavor" written.

If you do what you want, the Mastodon is not the Open Source.

**Comment by koyuawsmbrtn** [comment]
Ok, then case closed
