### ISSUE TITLE
Ability to register / unregister `web+mastodon` protocol handler

### ISSUE THREAD

**Issue by asamuzaK** [tootsuite/mastodon#6255]
This is a feature request.

When a user access the instance of Mastodon for the first time, you will be prompted to register the `web+mastodon` protocol handler.
Ref [#4511](https://github.com/tootsuite/mastodon/pull/4511 "Add protocol handler. Handle follow intents by Gargron · Pull Request #4511 · tootsuite/mastodon")

However, registration is urged only once, and if you refuse registration at that time, there is no way to register again later.

Another scenario is that, when accessing the same instance from a different browser, you will not be prompted to register the `web+mastodon` protocol handler even if it is the first access on that browser.

In addition, there is no way to unregister the handler.

So a UI to register / ununregister protocol handler somewhere on the user's configuration page is needed?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by rugk** [comment]
This feature is sooo hidden anyway, we really need it in the settings, so users have a chance to stumble over it again… :smile:

**Comment by trwnh** [comment]
Hasn't this feature been removed?

**Comment by rugk** [comment]
What? Why? What did I miss? Is there any information on that?

**Comment by trwnh** [comment]
#8127
