### ISSUE TITLE
Add information about translating to CONTRIBUTING file

### ISSUE THREAD

**Issue by gandaro** [tootsuite/mastodon#6259]
There should be instructions for how to start translating in `CONTRIBUTING.md`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
Fixed in 00ff8dc00a3b3bbf5334fe889c27cb8b6956ccca
