### ISSUE TITLE
TOOT's do not get removed from "home" timeline & public timeline until after page refresh

### ISSUE THREAD

**Issue by mitchellurgero** [tootsuite/mastodon#626]
TOOT's do not get removed from "home" timeline & public timeline after deleting until after page refresh:
Replicate:
With account 1 while account 2 is logged in on another browser:
1. Post toot
2. Wait about 1 minute
3. Delete toot

With account 2:
1. View toot before deleted
2. go back to public timeline
3. try to view after delete and get a 404 error, but can still see the toot.

**Comment by rmhasan** [comment]
Hi @Gargron and @mitchellurgero  PR #646 fixes this issue. Can someone please review it.
