### ISSUE TITLE
Remove invalid hashtags in ActivityPub::Create

### ISSUE THREAD

**Issue by Chocobozzz** [tootsuite/mastodon#6261]
In PeerTube we accept any characters for tags. Then we convert them in Hashtag in ActivityPub if other platforms want to use them.

Mastodon processes the Hashtags [here](https://github.com/tootsuite/mastodon/blob/master/app/lib/activitypub/activity/create.rb#L81) but does not validate them. It results in model validation exception [here](https://github.com/tootsuite/mastodon/blob/master/app/models/tag.rb#L18) and the status is not created.

Maybe Mastodon could just ignore invalid Hashtag.

Thanks

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by SoniEx2** [comment]
Or they could accept more hashtags.

`#C++`, `#non-binary`, etc.

**Comment by nightpool** [comment]
we should either catch these exceptions in the generation code (so that a failed hashtag doesn't break the entire status) or remove the server-side validation and just rely on our parsing code to only create valid hashtags.
