### ISSUE TITLE
[tests] User possible without password

### ISSUE THREAD

**Issue by devkral** [tootsuite/mastodon#6268]
While implementing PAM I found out that passwords are not required for users.
Is this a bug or a feature? For what are password less user accounts used?

**Comment by voronoipotato** [comment]
I think this may be considered a bug, without a sole user for an account there is a dangerous shared culpability by all for all actions made by the account.

**Comment by moggers87** [comment]
Is it possible to login without a password? The password submitted is hashed [here](https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/lib/devise/encryptor.rb#L16) before being compared to what's in the database, so I think blanking the password in the database would render the account unusable.

I might have missed something as I'm not too familiar with Ruby, but I'm fairly sure this issue can be closed.

**Comment by nightpool** [comment]
it is not possible to create a user without a password under normal operation.
