### ISSUE TITLE
Tag status with user class

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6270]
I think mastodon posts should have `class="mastodon_user_@name@fqdn.example"` somewhere.

Example uses include coloring posts based on user. This seems quite popular over at e.g. Tumblr.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by voronoipotato** [comment]
Curious feature request but @SoniEx2 I feel like you're opening a lot of "issues" that are really features. Could this at least have a feature request label?

**Comment by ekiru** [comment]
glitch-soc has something like this: there, each status has a data-status-by attribute that looks like `@someone@example.com`, and fave/reblog notifications have data-favourited-by/data-boosted-by

https://github.com/glitch-soc/mastodon/pull/117 was the original PR that added it there.

So userstyles can do things like

```css
[data-status-by="@somebody@example.com"] {
    color: DarkRed;
    background-color: LavenderBlush;
}
