### ISSUE TITLE
Overwritting current toot shouldn't be possible

### ISSUE THREAD

**Issue by jpdeplaix** [tootsuite/mastodon#6271]
What it does: If you are currently writing a toot and that you inadvertently click on the reply button on an other column, then what you were writing is going to erased.

What it should do: This behaviour seems not sane and a message box should appear on the screen to ask the user if they really want to erase what they were writing.

Version: 2.1.3

**Comment by SoniEx2** [comment]
I think the current toot should always carry over unless it's empty.

**Comment by Cassolotl** [comment]
This is a duplicate of #878. :)

**Comment by jpdeplaix** [comment]
Ok. Sorry I missed it.

**Comment by Cassolotl** [comment]
No worries! :)
