### ISSUE TITLE
"load more" on remote follows doesn't seem to work, and doesn't give any useful feed back either

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#628]
https://mastodon.social/web/accounts/23972

He has more toots, but clicking load more just makes it flicker and nothing happens.

![image](https://cloud.githubusercontent.com/assets/175467/22891613/3c02ee92-f210-11e6-9b7f-5f25b82f834c.png)

**Comment by unarist** [comment]
"Load more" wouldn't appears if you cannot load more toots now. Closing this as fixed.
