### ISSUE TITLE
Missing images : media_attachments/files/001*

### ISSUE THREAD

**Issue by parfish** [tootsuite/mastodon#6285]
Most images from this account have disappeared without any action from the account holder:
https://mastodon.social/@scramble

This bug happened on mastadon.social (don't know about other instances).

Clicking dead images provides the following XML: 

`<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>media_attachments/files/001/580/854/original/4e539dc35ec21a5a.jpg</Key><RequestId>4E00EEF7DCEE1CB9</RequestId><HostId>LczSLNNyWMIDT9jtcvW6+zNKntY7T93kH8RT16Nu3cJaOQhyXsx9YZJSLpufn2KGRVRJaDUjqg+N</HostId></Error>`

Yet one image has remained. Perhaps noteworthy, is that the media_attachment begins with 002 not 001 like all the missing images. 

media_attachments/files/001/*  have gone
media_attachments/files/002/*  remain

Hope that helps. Is this a bug? Media caching?

Above my pay grade. 

Thanks, 
P.

**Comment by Gargron** [comment]
Yes but this github is not for this kind of issue.

**Comment by procedural** [comment]
@Gargron Which github is for this kind of issues? My images are gone too, exactly in the way @parfish described.

**Comment by Gargron** [comment]
There is no github for mastodon.social specifically. People just message me or e-mail me (but don't do this about this issue obviously)

**Comment by parfish** [comment]
I'm confused. Does that mean a) because you;re now aware of it and you're dealing with it, or b) does that mean you don't think it's an issue?
Sorry if this is dumb it's just "but don't do this about this issue obviously" can be interpreted a few different ways.

P.

**Comment by nightpool** [comment]
I believe Eugen meant A

**Comment by procedural** [comment]
Sorry, forgot to post Eugen's reply: https://mastodon.social/web/statuses/99377252685107633

**Comment by parfish** [comment]
Thanks !
Good to know it's being dealt with.
