### ISSUE TITLE
PWA: Column on far right defaults to "Home" in multi-column layout rather than "Getting started"

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#6289]
When using the progressive web app (PWA) for Mastodon, the column on the far right is stuck on the Home column. Usually, it says Getting Started and allows you to navigate to unpinned columns. Clicking "Back" does nothing, and the second Home column remains open. https://i.imgur.com/LA2pInQ.png

This only happens when using the webapp for Mastodon, and not the standard web client. i.e., when selecting "add to desktop" in Chrome, or "add to home screen" in Chrome Mobile.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
I should also add that it's possible to pin what seems to be an endless amount of Home columns due to this. https://i.imgur.com/aZWay1b.png

**Comment by Gargron** [comment]
>I should also add that it's possible to pin what seems to be an endless amount of Home columns due to this

Yes it's possible if you want to do this.

>the column on the far right is stuck on the Home column

Probably because the PWA manifest is aimed at mobile devices which open in single-column layout where starting with home makes sense. This is tied to the URL of the page. Click on the asterisk (*) in the navigation menu to navigate to getting started menu instead.

**Comment by trwnh** [comment]
This happens on tablets, too. Clicking the * works, but upon starting the PWA, the aforementioned bug occurs. What is confusing is not being able to go "back" on first start, since there isn't a canonical "previous" state; this leads to a frozen Home column. 

Also, perhaps it's a bit confusing because you don't seem able to pin infinite Home columns on the standard web client; already-pinned columns disappear from the "Getting Started" list, which makes sense. I assumed pinning only one of each column was intended behavior.

**Comment by zcdunn** [comment]
@Gargron Instead of setting the start_url to "/web/timelines/home", couldn't you set it to some route that just checks whether the user is in single-column mode or not? And then redirect to /web/timelines/home if so or web/getting-started if not.

**Comment by trwnh** [comment]
Update: as of 2.4.0 at least, it is now possible to click back to go from "Home" to "Getting Started". The PWA still loads a second "Home" column in multi-column layout, but it's no longer permanently stuck.

**Comment by namannehra** [comment]
#7677 doesn't fix the issue. Fixing this also requires to the change the `start_url` field `manifest.json`
