### ISSUE TITLE
Webfinger requests do not contain hostname in user agent

### ISSUE THREAD

**Issue by puckipedia** [tootsuite/mastodon#6294]
As in title. they just say `http.rb/2.2.2` in the user agent. so if a webfinger fails, I will not know which instance tried to find a specific user.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
ugh. this is going to be a pain to fix. can you open an issue on https://github.com/tootsuite/goldfinger as well?

**Comment by nightpool** [comment]
looks like this may be solved by https://github.com/tootsuite/goldfinger/pull/6
