### ISSUE TITLE
Issue delivering emails

### ISSUE THREAD

**Issue by Technowix** [tootsuite/mastodon#6295]
On #7badad7797b487b411a2ab34e0f7413741974bb4

`ActionView::Template::Error: Webpacker can't find icon_email.svg in /mastodon/public/packs/manifest.json. Possible causes: 1. You want to set webpacker.yml value of compile to true for your environment...`
In sidekiq
Assets have been regerated multiple time, icon_email/reply/blabla.svg, all is in the /images and in the /manifest.json

😕 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Just as a note, in the latest versions it would complain about icon_email.png, not svg, but it's the same thing. Kind of a mystery to me because if you inspect public/packs/manifest.json, icon_email.png is definitely there.

**Comment by Gargron** [comment]
@unarist Have you experienced this on your instance too?

**Comment by lindwurm** [comment]
yes, we have same issue on our instance https://mstdn.maud.io (9b3b40df660d90fddb7563def4fab9b5cee701e9 +α )

**Comment by s0r00t** [comment]
(reposting here; posted in the wrong issue)

I experience this on my newly setup instance, disallowing me from using it, as I can't register myself.

**Comment by Technowix** [comment]
Who is using docker here? @lindwurm @s0r00t ?

**Comment by Gargron** [comment]
@s0r00t Please use a stable version of Mastodon instead of master or a release candidate.

**Comment by s0r00t** [comment]
@Technowix I'm using Docker.
@Gargron Alright, I'm going to checkout the latest release and rebuild.

**Comment by lindwurm** [comment]
@Technowix I'm using docker too. now #6348 works fine for me.

**Comment by clement-analogue** [comment]
Hello,

I'm running Mastodon v2.2.0 and I still have this issue.

**Comment by Gargron** [comment]
Look at https://github.com/tootsuite/mastodon/releases/tag/v2.2.0 -> Upgrade Notes -> Docker-only

**Comment by clement-analogue** [comment]
I am not using Docker. I have followed carefully the release notes and have already changed Ruby from 2.4.2 to 2.5.0.

**Comment by Gargron** [comment]
@clement-analogue Have you run `assets:precompile` and restarted sidekiq? And does sidekiq reside on the same machine as the rest, i.e. with access to `public/packs/manifest.json`?

**Comment by clement-analogue** [comment]
> Have you run assets:precompile and restarted sidekiq?

yes and yes

> And does sidekiq reside on the same machine as the rest, i.e. with access to public/packs/manifest.json?

yes. It is a standard standalone installation.

**Comment by dethos** [comment]
I'm also experiencing this issue in my instance. Not using docker and the sidekiq is on the same machine. Lots of Jobs failed with the following messages: 

> ActionView::Template::Error: Webpacker can't find icon_person_add.png in ...

> ActionView::Template::Error: Webpacker can't find icon_cached.png in ...

> ActionView::Template::Error: Webpacker can't find icon_grade.png in ...

All of this started when I updated to version 2.2.0, following the instructions present on the release notes.

**Comment by downeym** [comment]
Reproduced on 2.3.3. Same issues as previous/above comment. No emails successfully reaching the SMTP server. Standalone/single server instance.

**Comment by albjeremias** [comment]
I also bumped into this issue... the problem was my docker-compose... **sidekiq** was pointing the volume to the wrong place... **web** and **sidekiq** should point to the sameplace!

before:

```web:
...
    volumes:
      - ${STORAGE}/assets:/mastodon/public/assets
      - ${STORAGE}/packs:/mastodon/public/packs
      - ${STORAGE}/public/system:/mastodon/public/system
...
sidekiq:
...
    volumes:
      - ${STORAGE}/public/packs:/mastodon/public/packs
      - ${STORAGE}/public/system:/mastodon/public/system
```

after:

```web:
...
    volumes:
      - ${STORAGE}/assets:/mastodon/public/assets
      - ${STORAGE}/packs:/mastodon/public/packs
      - ${STORAGE}/public/system:/mastodon/public/system
...
sidekiq:
...
    volumes:
-      - ${STORAGE}/public/packs:/mastodon/public/packs
+      - ${STORAGE}/packs:/mastodon/public/packs
      - ${STORAGE}/public/system:/mastodon/public/system
```
