### ISSUE TITLE
Hide "random replies" from home feed

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6304]
If you follow users A and B, and an user you don't follow, C, posts something, and A replies to C, and B replies to A, you see B's reply in your home feed.

This is bad UX and should not happen.

Instead the algorithm should check if the parent is on the home feed before adding it to the home feed. Not the account being replied to.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I don't want to see posts from people I don't follow in my home timeline. :/

**Comment by SoniEx2** [comment]
You already do. They're called boosts.

**Comment by SoniEx2** [comment]
Algorithm:

```
if toot.isReply() {
  if homefeed.contains(toot.repliedTo) {
    homefeed.add(toot);
  }
} else {
  homefeed.add(toot);
}
```

**Comment by SoniEx2** [comment]
Note that, when filtering out boosts, replies to boosts are automatically removed too!

**Comment by TrollDecker** [comment]
I'm pretty sure Cas meant they would rather their home timeline remained strictly toots posted by AND boosted by users they follow, as opposed to responses showing up seemingly out of nowhere despite none of their followers actually posting or boosting it of their own accord.

And I can understand that. I really would rather not start seeing some rando's toots showing up in my home timeline out of the blue, especially if said rando is being something of a douchebag.

And to be honest, I fail to understand the original problem to begin with?

**Comment by SoniEx2** [comment]
Do I need to explicitly mention that you're following both A and C, and not B?

I thought it was implied, since from 3 users, I implied you don't follow B.

**Comment by SoniEx2** [comment]
Also, A and C may be the same user.

**Comment by TrollDecker** [comment]
That wasn't really implied all that well, because nowhere in the original post does it suggest that I would be following C. For all I was aware, C was literally any user, followed or not.

Knowing that A and C _are_ both followed users, the suggestion makes a little more sense.

**Comment by SoniEx2** [comment]
Sorry, fixed.

**Comment by Cassolotl** [comment]
>If user A (followed) boosts user B's (not followed) toot and user C (followed) replies to it, the reply should be shown.

Okay, so now that everything has been edited - isn't it already the case that replies to people that are all followed get shown in the home timeline? Like, if I follow Gargron and Chr and Bea and they all talk to each other, I see that whole conversation in my home timeline?

**Comment by SoniEx2** [comment]
@TrollDecker Yes, that's a pretty good way of putting it. Your home feed should be a live feed of your social circles, and should include things like replies-to-boosts so you can see what your friends are saying about their interests and stuff.

This would be a lot more friend-friendly/social than [redacted].

**Comment by TrollDecker** [comment]
@Cassolotl Yes, but if, say, Chr boosted a toot from a user you _didn't_ follow, and Bea responded directly to that boosted toot, that response won't appear in your timeline. I think that was what Soni was getting at. 🙂

**Comment by SoniEx2** [comment]
Something I don't like about mastodon and [redacted] is that you can have stuff like this:

```
<@a (not followed)> hello world
<@b (followed)> [reply to @a] @a hello person
<@c (followed)> [reply to @b] @b @a hi you too
```

And you see c's post, but you don't see a's and b's. A side effect of changing the "display replies when" condition from "replied to followed user" to "replied to toot on my feed" is that in this case you wouldn't see c's post, as it's not relevant to anything on your feed. (This could also be a setting, but I like the implications and I think it produces better UX.)

**Comment by Cassolotl** [comment]
>if, say, Chr boosted a toot from a user you didn't follow, and Bea responded directly to that boosted toot, that response won't appear in your timeline.

Ahhh I get you. Yes, I don't want to see Bea's reply to someone I don't follow, even if I saw a toot by them boosted into my home timeline.

**Comment by voronoipotato** [comment]
Can we have a vote to close issue. 
❌

**Comment by TrollDecker** [comment]
I vote you sit down and refrain from any further attempts at backseat moderation, okay?

BACK ON THE SUBJECT, maybe this could be an opt-in feature somehow? An additional column option perhaps?

**Comment by SoniEx2** [comment]
I'd prefer if this was opt-out, just like boosts on home feed are opt-out.

That way, you can rely on your replies being seen by default, rather than subtooting to make them seen. This also means you link your toots to the context, which is something you can't do properly with subtooting.

**Comment by voronoipotato** [comment]
@TrollDecker different projects have different approaches to issue discussion. I didn't realize there was established norms that I was violating, sorry.

**Comment by ashkitten** [comment]
My position on this is that if you want your toot to be seen, reply to the post and boost it yourself.

HOWEVER, I would like to be able to turn on replies for lists (preferably the home TL as well). In general for me, if I have someone in a list I want to see ALL of their toots.

**Comment by SoniEx2** [comment]
Oh right you can boost replies... I forget that sometimes.

Altho it doesn't work for followers-only I guess...

Also you should make a separate issue for lists.
