### ISSUE TITLE
New Confirmed UI disappeared from accounts list

### ISSUE THREAD

**Issue by cheesegrits** [tootsuite/mastodon#6310]
The new "Confirmed" column in the admin accounts list, added in this PR:

https://github.com/tootsuite/mastodon/pull/2245

... seems to have disappeared.  The new "Confirm" button in the edit page is still there, and works, but it'd be nice to still have the visual indicator in the list.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Unconfirmed users do not persist for longer than a day. It doesn't make sense to present this information in the overview table that already lacks horizontal space.

**Comment by cheesegrits** [comment]
OK, as long as it was deliberate and didn't just get lost in the shuffle.

Is there a rake task for finding unconfirmed accounts?  I've been having problems with Mailgun in the last week (some of their servers getting blacklisted) and it'd be nice to have a way of checking for problems on the Mastodon end on a daily basis.
