### ISSUE TITLE
Precompiled assets are hostname dependent

### ISSUE THREAD

**Issue by zunda** [tootsuite/mastodon#6311]
It would be the best if hostname of the [full_asset_url](https://github.com/tootsuite/mastodon/blob/v2.2.0rc1/app/helpers/routing_helper.rb#L15) doesn't depend upon the hostname. What do you folks think referring to assets from the web UI using the relative URI, i.e., `/path/to/asset.js` when `ASSET_HOST` is not defined while using the absolute URI, i.e.,m `https://example.com/path/to/asset.js` for assets included in e-mails? I actually tried to come up with a pull request but found that I don't know  much about webpacker.

At Heroku, precompiled assets maybe used on different apps in a [Pipeline](https://devcenter.heroku.com/articles/pipelines). This makes it possible to test the app in a staging app before deploying to the production. For Mastodon, this stopped working when #6301 was merged. The precompiled assets started to refer to `LOCAL_DOMAIN` environment variable from the staging app (`zundan-mastodon-experiment.herokuapp.com`) where precompile happens and  different from the production app (`mastodon.zunda.ninja`):

![54c433a8c53cabce](https://user-images.githubusercontent.com/30968/35189192-a2df48b4-fde9-11e7-8d5e-3da6500197ee.png)

For now, I could work around this with [reverting](https://github.com/zunda/mastodon/commit/8d7d60353e723c8c186220cc7461a5aca96f2153) the change to `config/webpack/configuration.js` so that webpacker doesn't care about `LOCAL_DOMAIN`. However, I feel this is not the best solution.

**Comment by Gargron** [comment]
I don't know how to make webpacker use URL with host only for mailer.css. CC @sorin-davidoi @nolanlawson

**Comment by ThibG** [comment]
I have a similar issue with the assets using `LOCAL_DOMAIN` instead of `WEB_DOMAIN`.
Ideally, all the paths in the WebUI should be relative. Failing that, the line should read:

`publicPath: formatPublicPath(env.ASSET_HOST || env.WEB_DOMAIN || env.LOCAL_DOMAIN, settings.public_output_path),`

**Comment by Gargron** [comment]
@zunda Can you set ASSET_HOST in your staging environment to circumvent this issue?

**Comment by zunda** [comment]
I believe setting `ASSET_HOST` to the staging app doubles the cost of running Mastodon because both of the environment will have to be up.

**Comment by zunda** [comment]
Instead of making URLs relative from the Web UI, I now imagine it would also be nice if webpacker and others differ determining the hostname until runtime when Web UI and e-mails are actually rendered.

**Comment by Gargron** [comment]
Hmm. String replace on CSS before it gets to Premailer? Replace `url(/` with `url(https://.../`? That could work...
