### ISSUE TITLE
regex timeline filters don't handle newlines well

### ISSUE THREAD

**Issue by MightyPork** [tootsuite/mastodon#6316]
this is an oddity I noticed when trying to block the new 

V
E
R
T
I
C
A
L

meme.

`([\r\n]+[A-Z])+` should do the trick here, but it blocks only *some* instances of the meme. I haven't figured out what's the difference between those that are and aren't caught.

**Comment by Shadow8t4** [comment]
Original toot:
https://asonix.dog/@Shadow8t4/99386609595807121

Some other examples:
https://cybre.space/@vantablack/99386741461920453
https://dev.glitch.social/@impiaaa/99386723337795653
https://awoo.space/@sc/99386723826642728
https://witches.town/@luluberlu/99386715781173051
https://cybre.space/@sireebob/99386702288437421
https://cybre.space/@weird_hell/99386682070013515
https://cybre.space/@HTHR/99386672538936631
https://cybre.space/@HTHR/99386660304331609
https://cybre.space/@bootsy/99386656815538159

I put a lot of different ones just to show how varying the meme got at its peak.
