### ISSUE TITLE
Video and column-scrolling bug

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#6330]
[Conversation](https://dev.glitch.social/@cassolotl/99395638378018981).

1. Find video while scrolling on Mastodon.
2. Click the fullscreen icon on the video and watch the video and whatnot.
3. Ensmallenate the video.

Expected result: Column is in the same place as before.

Actual result: Column has been scrolled back to the top.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment]
I cannot reproduce this. Is this still an issue?
What browser do you use? Did that affect several columns or one in particular? How far did you scroll back to the video?

**Comment by Cassolotl** [comment]
I can't reproduce it either so I guess it's been fixed! :)
