### ISSUE TITLE
Home timeline for returning users not fixed?

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#6331]
In #6251 I did a lot to fix #5634, but I got this report from a user of mastodon.social which runs 2.2.0rc1, which included the fix:

>It said the feed was empty, or something similar. It seems to have kind-of sorted itself out now, I'm seeing toots going forward, but I'm still not seeing anything going backwards past this morning
>
>Except! I can see the two new people I followed when I go backwards in my timeline. Everyone else is not showing up.

https://mastodon.social/@VirtualClint/99395232707153354

I'm kind of at the end of my wits because I have tested locally prior to the fix: Followed a bunch of accounts, made a bunch of posts from them, then removed the home timeline from redis, set my current_sign_in_at and last_sign_in_at values to long ago, and I got back a working home timeline that included everything it needed to. I don't know where and how it goes wrong.

**I would appreciate if another person tried debugging this.**

___

Some pointers:

- Home feeds are stored in redis
- They're pruned for ppl who didn't login for 2 weeks
- UserTrackingConcern is responsible for updating login times at most once a day and queueing up the RegenerationWorker if the 2 week absence is detected
- RegenerationWorker iterates over a SQL version of the home timeline and it's supposed to fill the redis timeline

**Comment by jennifermf** [comment]
in case it's helpful for whoever tackles this, I am having a similar issue: It's only in my notifications column, and it says there are no notifications despite seeing toots mentioning me in my home timeline. Occasionally I will get a notification, but it always disappears on refresh. I always receive desktop/browser notifications. I also get a 500 error every time I load/reload the page. This is happening on toot.cat, after being logged out longer than 2 weeks.

**Comment by ProgVal** [comment]
Did you try logging the status of `account:XXX:regeneration`, to see if it someone gets dropped before the regeneration actually happens?

**Comment by Gargron** [comment]
@ProgVal That key does not determine whether regeneration *happens*, it's only a marker for when it's queued (`RegenerationWorker.perform_async`) and yes there are some unit tests that confirm both that it gets queued and that the marker is set, and finally unset when it's done.

**Comment by Gargron** [comment]
@jennifermf That absolutely cannot be related to this issue. Nothing about notifications depends on your last login time. That sounds more like there's some bugged out notification among the recent ones that breaks the API request.

**Comment by ProgVal** [comment]
@Gargron I meant that it may be removed because of an external factor that only happens on production.

**Comment by Gargron** [comment]
@ProgVal The conversation you're getting me in right now is the opposite of what I'm trying to accomplish here. I've been struggling with this issue for a long time, and I'm not finding the problem. I want somebody to do a *completely independent* debug not tainted by my preconceptions.

**Comment by ProgVal** [comment]
Ok, sorry.
