### ISSUE TITLE
Join several hashtags in a search/column

### ISSUE THREAD

**Issue by renatolond** [tootsuite/mastodon#6359]
I noticed that there's multiple tags in which people add which songs they are listening to (np, nowplaying, radiotoot, tootradio, pouetradio, etc). I'd like to follow those hashtags for idea on what to listen, but for now the only way I found is to open a column for each of them and them have toots that use multiple of those appearing on several columns. I would like to be able to follow all of them in a single column.
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Letiteuf55** [comment]
Yeah, i need that too, i'm running out of space on my screen with all my # researches !

**Comment by Granitosaurus** [comment]
This is a huge issue for me as well as my 13" laptops screenspace is rather limited.   

I also proposed another feature to address the same screenspace issue: #7050 
Combination of both of these features would greatly improve user experience and screen-space effiency.

**Comment by Gargron** [comment]
Are we talking about OR, AND, or both?

**Comment by renatolond** [comment]
I'm talking about OR. I would like to see posts that contain either np, nowPlaying, radioToot or tootRadio at the same column

**Comment by nightpool** [comment]
i think or is the most useful feature considering how people use hashtags,
I wouldn't be worried about ANDs

**Comment by woj-tek** [comment]
Could I suggest making operator optional (defaulting to OR for example, though for me AND would be more natural)?
For example I would be quite often interested in narrowing search more instead of expanding them.

**Comment by roipoussiere** [comment]
Just to resume the discussion, the behavior could be:

- `#nowplaying #radiotoot` -> one of these hashtags
- `#nowplaying or #radiotoot` -> one of these hashtags
- `#cute and #cat` -> both of them

**Comment by gdpelican** [comment]
I'm thinking to have a look at this over the next wee while.

Apologies for the extremely rough mockup with hasty copy, but I was thinking something along the lines of this:
- Perform a search, and add a new hashtag column to your desktop
- Open the settings for that hashtag column
- Add the option to specify additional hashtags to include in this column
- Add the option to specify whether this is an 'AND' or an 'OR' relationship

![captura de pantalla 2018-09-13 a la s 3 49 14 p m](https://user-images.githubusercontent.com/750477/45515020-a0fbaf00-b76c-11e8-8f33-24bee4dd481f.png)

Thoughts?

**Comment by fhemberger** [comment]
I think it would be nice to have AND, OR and NOT operators, e.g.

- `#mastoart OR #creativetoots NOT #photography`
- `#mastoart #creativetoots -#photography` (as short form, defaulting to OR)

**Comment by joreg** [comment]
@gdpelican too good to be true!

**Comment by Cassolotl** [comment]
Oh this was introduced now so this issue can probably be closed?

**Comment by ChameleonScales** [comment]
I don't see it implemented. Is it for the next release?

**Comment by Cassolotl** [comment]
If it's not on your instance yet, you probably need to wait for your instance to be updated. What's your instance URL?

**Comment by ChameleonScales** [comment]
My instance is up to date (2.6.5). It's mamot.fr if you must know

**Comment by Cassolotl** [comment]
And when you pin a hashtag search, you don't see this?:

![screenshot 2018-12-04 at 19 08 17](https://user-images.githubusercontent.com/6607512/49466449-03a69900-f7f8-11e8-863d-b1e3250924a0.png)

**Comment by Cassolotl** [comment]
Ahhhh I see, and Glitch just gets it early. Cool. :) Thanks for clearing that up, knowledgeable people!
