### ISSUE TITLE
"@twitter" doesn't appear in timeline toots in Chrome

### ISSUE THREAD

**Issue by taoeffect** [tootsuite/mastodon#6364]
So, this bug seems to be specific to Chrome, and specifically to the timeline only. The word "@twitter" does appear if you view a specific toot via its link, e.g. [this one](https://mastodon.social/@taoeffect/99412993216034292).

But when I see that toot in the TL in Chrome, "@twitter" is oddly missing.

Attaching screenshot here. This is the thread where I noticed this bug: https://mastodon.social/@taoeffect/99412993216034292

![screen shot 2018-01-25 at 3 12 34 pm](https://user-images.githubusercontent.com/138706/35418480-47333b72-01e7-11e8-86e3-e289a181568b.jpg)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by renatolond** [comment]
I'm using Chromium 63.0 and I'm seeing Twitter correctly. Do you have any extensions that could be influencing it?

**Comment by taoeffect** [comment]
@renatolond How are you viewing it? You have to view in the timeline. I'm also on Chrome 63 (though not Chromium, but I doubt there's much of a difference?). To view it in the TL, go into the search, and paste [the URL](https://mastodon.social/@taoeffect/99412993216034292) into the search.

![screen shot 2018-01-26 at 8 10 55 pm](https://user-images.githubusercontent.com/138706/35468548-0f43dc6e-02d5-11e8-9ece-9a5409f043e7.jpg)

**Comment by renatolond** [comment]
![image](https://user-images.githubusercontent.com/173791/35475440-c0e6dc40-039e-11e8-8da6-391ac29c1827.png)
Yeah, I'm also seeing on the timeline, don't think there's a lot of difference between chrome and chromium either, that's why I asked about your extensions. Does it also happen if you login in an incognito window?

**Comment by taoeffect** [comment]
@renatolond Good thinking!

It's a problem caused by a poor uBlock Origin rule:

![screen shot 2018-01-27 at 3 53 28 pm](https://user-images.githubusercontent.com/138706/35477555-4e953066-037a-11e8-92aa-2a3d13f77846.jpg)

Thanks for your help figuring this out!
