### ISSUE TITLE
Sometimes logging in is a little bit buggy

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#6366]
At random times it happens, that logging in gives some errors. When I close the tab and open it again I'm actually logged in. It's just a little bit confusing logging in, but it would be a great help if someone could fix this bug.

![](https://i.koyu.space/55h1he3e.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Replace `Referrer-Policy: no-referrer` with `Referrer-Policy: same-origin`.

If `Privacy-Policy` is `no-referrer`, Google Chrome will send an `Origin` header with a value of `null`. Rails will fail validation if the Origin header does not match the request.

see https://github.com/rails/rails/issues/28299#issuecomment-335264502

**Comment by koyuawsmbrtn** [comment]
Thank you. I guess I've got that header on my instance. The problem is on niu.moe. I'll reach out to the admins there :)
