### ISSUE TITLE
Bug Fix: Home column displays reply to non-federated user

### ISSUE THREAD

**Issue by vahnj** [tootsuite/mastodon#637]
- User A is on instance 1
- User B is on instance 2
- User C follows User A on instance 3
- instance 3 has instance 2 domain blocked
- User C sees User A's reply to User A's own post, which is a reply to User B, without seeing User B's posts

Status details inside of the db: 
  - first reply's in_reply_to_account_id value is nil
  - first reply's in_reply_to_id value is nil
  - first reply's reply value is true
  - second reply's in_reply_to_account_id value is nil
  - second reply's in_reply_to_id value is the first reply's ID
  - second reply's reply value is true

**Comment by wxcafe** [comment]
is this still an issue?

**Comment by Gargron** [comment]
Replies for toots that can't be resolved are hidden by default now so should no longer be an issue
