### ISSUE TITLE
[2.2.0] Unknown Format: from show method within statuses_controller.rb .. 

### ISSUE THREAD

**Issue by jebuskrust** [tootsuite/mastodon#6380]
I rarely am on here..  However, not sure if this was just introduced.  But I'm seeing these messages in logs. 

Presently running ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]

Also, If it helps any, I was researching an issue with someone attempting to reset their password that had special characters within it, server accepted it, however wont allow the user to login.  Try to reset password, crashes with the "Something went wrong error".  

After looking at the logs, this is the only observable issue that i'm seeing. Likely unrelated to the password issue, but unsure.

```
Jan 29 14:03:46 localhost bundle[30068]: [3c23aea2-ddbd-4ca9-8958-aa07a111a559] method=GET path=/@dewb/99435373242308557 format=xml controller=StatusesController action=show status=401 duration=17.36 view=0.00 db=8.43
Jan 29 14:03:46 localhost bundle[30068]: [3c23aea2-ddbd-4ca9-8958-aa07a111a559]
Jan 29 14:03:46 localhost bundle[30068]: [3c23aea2-ddbd-4ca9-8958-aa07a111a559] ActionController::UnknownFormat (ActionController::UnknownFormat):
Jan 29 14:03:46 localhost bundle[30068]: [3c23aea2-ddbd-4ca9-8958-aa07a111a559]
Jan 29 14:03:46 localhost bundle[30068]: [3c23aea2-ddbd-4ca9-8958-aa07a111a559] **app/controllers/statuses_controller.rb:16:in `show'**
```
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by jebuskrust** [comment]
Horray for xml right?

**Comment by jebuskrust** [comment]
This was also a tag release

**Comment by Gargron** [comment]
This is not an unexpected error. That page has no xml variant, therefore requesting it as xml fails.
