### ISSUE TITLE
lost recovery codes and 2FA generator cant login

### ISSUE THREAD

**Issue by winnoryder** [tootsuite/mastodon#6383]
I can reset my password but cant turn off 2FA, there is no option to use my phone to get two-factor code,help

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by patf** [comment]
If you're still logged in, there's a workaround you can use to disable 2FA: Navigate to Settings > Two-factor Auth and click on the "Generate recovery codes" link towards the bottom. Save the codes and then navigate back to Two-factor Auth, where you can use one of the recovery codes to disable two-factor authentication completely. (If you want to, you can then setup 2FA from scratch the way you did initially.)

(Side note: This process is likely to change in future versions of Mastodon and will probably require manual intervention from instance admins.)

**Comment by nightpool** [comment]
@winnoryder you'll need to contact your instance admin and have them disable 2fa for you. Which instance did you sign up on?

**Comment by nightpool** [comment]
(closed since this isn't a problem with the software itself, just a support request)

**Comment by winnoryder** [comment]
@nightpool thanks,I sign up on mastodon.cloud,I cant log in and dont know how to contact instance admin,It happened yesterday,I really need to use my mastodon account, very hurry,help me thanks

**Comment by winnoryder** [comment]
@nightpool  OK,now I know the admin email,thanks

**Comment by Fares-sghaier** [comment]
Hello, 
Hope you are well, 

I can't access my account because I used all my recovery codes, i accidentally logged out from my account 



Could you please tell us how to get new recovery codes because i do not have 2FA.
