### ISSUE TITLE
Cookie Authentication Error (Security verification failed)

### ISSUE THREAD

**Issue by VottonDev** [tootsuite/mastodon#6385]
[Experiencing Cookie Authentication Error with new users only and after you clear your browser history.
This started happening after I updated to 2.2.0. Is there anything specific I could check as I have not touched any of the headers or such since I updated Mastodon].
Mastodon Instance: https://kyot.me

This happens when you are registering but the registration is successful if you just go back to the main page or when you are trying to change personal profile settings and admin settings.

* * * *

- [Yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [2.2.0] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by VottonDev** [comment]
It was a referrer policy issue. I had to change my referrer-policy to "same-origin".

**Comment by jmikedupont2** [comment]
Getting this error on nerdculture.com
