### ISSUE TITLE
Remove DNS

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6392]
DNS is the centralization that ties the federation together.

We should make mastodon truly decentralized. This includes changing how instances work so as to not rely on DNS, an ICANN-centralized service.

(This also includes support for non-ICANN (e.g. OpenNIC) instances. Tor/i2p support I'm not sure.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Definitely out of scope of this project

**Comment by SoniEx2** [comment]
No OpenNIC support?

**Comment by moggers87** [comment]
@SoniEx2 OpenNIC *is* DNS. It's just an alternative root and has to be configured at the OS level to work.

**Comment by SoniEx2** [comment]
Yes. It's an alternative root. Which means mastodon relying on a centralized DNS breaks it because there are *multiple different roots*. as there should be.
