### ISSUE TITLE
how to use email to turn off 2FA?

### ISSUE THREAD

**Issue by winnoryder** [tootsuite/mastodon#6393]
how to use email to turn off 2FA? 
* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
please don't open duplicate tickets for the same issue.

**Comment by nightpool** [comment]
(see https://github.com/tootsuite/mastodon/issues/6383)

**Comment by winnoryder** [comment]
ok,really sorry,problem fixed
