### ISSUE TITLE
Pinned lists vanish after page reload

### ISSUE THREAD

**Issue by sphinxc0re** [tootsuite/mastodon#6394]
On tag `v2.2.0`

Steps to reproduce:
- create list
- pin
- reload page

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Wait 5 seconds before reloading page.

**Comment by sphinxc0re** [comment]
Doesn't work. It still vainshes

**Comment by moggers87** [comment]
@sphinxc0re works for me.

Is there anything in the browser console and do you see network requests to `/api/web/settings` after you pin the column?

**Comment by sphinxc0re** [comment]
<img width="549" alt="screen shot 2018-02-01 at 10 00 34" src="https://user-images.githubusercontent.com/3702016/35669920-092a8074-0737-11e8-9bd6-4376c254a2d2.png">

**Comment by sphinxc0re** [comment]
The console doesn't log anything

**Comment by sphinxc0re** [comment]
This issue still isn't resolved but it's closed 🤷‍♂️ what's up with that?

**Comment by sphinxc0re** [comment]
This issue still isn't resolved for me. I tried restarting the docker containers several times but it didn't help, @Gargron

**Comment by sphinxc0re** [comment]
Also _unpinning_ seems to be broken as well
