### ISSUE TITLE
Activity tracker breaks in Vagrant box due to Redis version

### ISSUE THREAD

**Issue by northerner** [tootsuite/mastodon#6399]
The activity tracker is using the `pfadd` command in Redis. This command is only supported from version 2.8.9 (https://redis.io/commands/pfadd), however, the Vagrant box is using ubuntu/trusty64 which only has up to 2.8.4-2 in the official repository (https://packages.ubuntu.com/trusty/misc/redis-server).

To fix there are a few options: using an unofficial PPA (https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server), upgrading the Vagrant box to ubuntu/xenial64, building from source.

I think the best option will be an upgrade of the ubuntu box to xenial or artful. Continuing to use trusty is likely to cause other limitations going forward.

What's the preferred option?

```
21:23:04 web.1     | Completed 401 Unauthorized in 696ms (ActiveRecord: 71.3ms)
21:23:04 web.1     |
21:23:04 web.1     |
21:23:04 web.1     |
21:23:04 web.1     | Redis::CommandError (ERR unknown command 'pfadd'):
21:23:04 web.1     |
21:23:04 web.1     | app/lib/activity_tracker.rb:17:in `record'
21:23:04 web.1     | app/models/user.rb:235:in `prepare_returning_user!'
21:23:04 web.1     | app/models/user.rb:145:in `update_tracked_fields!'
21:23:04 web.1     | app/controllers/concerns/localized.rb:14:in `set_locale'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Xenial is the best option.
