### ISSUE TITLE
[Feature request] Tooltip while hovering over Sensitive Content

### ISSUE THREAD

**Issue by spaceottercode** [tootsuite/mastodon#6401]
Is it possible to add a title/tooltip to the media-spoiler button so that one can hover over the Sensitive Content box and see the alt text as one would after revealing said content...

ui enhancement low-priority

**Comment by Gargron** [comment]
There is only one spoiler button but there can be up to 4 images, each with a different alt text up to 400 characters each. That would be one hell of a tooltip

**Comment by spaceottercode** [comment]
haha yes good point @Gargron. If implement, I suppose it would only grab text from the first item, if any. Or if the code is feeling very persistent, it could grab the first text encountered (assuming an ordered list), if any.

**Comment by trwnh** [comment]
Perhaps this can be alleviated by hiding images individually, rather than all-at-once? Clicking on one would show all the images. Or perhaps, individual images can be marked sensitive, if the toot contains mixed sensitivity levels.
