### ISSUE TITLE
Report post dialogue shown in language of post I'm trying to report instead of my own.

### ISSUE THREAD

**Issue by ryliejamesthomas** [tootsuite/mastodon#6402]
Hi!

I just had an issue where I had to report some users using Russian (I think) (also that's not the reson I'm reporting them!), but when I clicked report the pop-up dialogue--the one with the three options to check--was also in Russian, instead of the language I am using Mastodon and my computer in, English.

I was using the web client.

The posts were in the same instance I was reporting from (gamemaking.social), which is hosted on masto.host, which as far as I know is up to date.

I've banned them, so it's nothing urgent. Was just trying to report them to test, and to remind myself of the specific users.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Those "options" are the toots, not options.
