### ISSUE TITLE
Reorganise menus

### ISSUE THREAD

**Issue by nclm** [tootsuite/mastodon#641]
Hello 🙂 I reopened Mastodon after months of not visiting and it’s great to see how it all evolved and grew up! The menu in the right column in addition to the icons menu in left column is a welcome addition, but there’s something inconsistent and somewhat bothering:

**The left menu icons:**
- Getting started `#` `+`
- Public `#` `+`
- Preferences `*` `+`
- Sign out `*` `+`

**The right menu items:**
- Getting started `#` `+`
- Public `#` `+`
- Preferences `*` `+`
- Favourites `#`
- Blocked users `#`
- Extended information `*`
- Sign out `*` `+`

`#` Octothorpes denote links opening content in the right column.
`*` Asterisks denote links to “external” pages.
`+` Pluses denote duplicate links.

See? I think it can all be made more nice & logical:
* No duplicates, they just take space and may be confusing.
* Things that open in the right column are to be in the right column menu.
* Things that don’t open in the right column have nothing to do in the right column menu.
* Then, left icons for everything else.
* Additionally, ‘Extended information’ can also be a text link at the end of the ‘Getting started’ copy.

I also believe that the icon menu would live better at the bottom of the left column rather than at the top. They are asides that you don’t have to see first thing when you open. It’s better to start with search and tooting, which are the main features.

Here’s a screenshot of the proposition:
![Mastodon reorganised](https://cloud.githubusercontent.com/assets/923008/23058144/d4cfded8-f4f3-11e6-9316-79cd42c87f71.png)

**Comment by nclm** [comment]
Reviving this issue since I think it’s still relevant: there’s a fundamental internal logic problem between the icon bar on the left and the right column.

Something we need too, and especially if public timelines are removed from the left (and I think they have to), is a way to get to see all the links of the right column without click back a thousand times.

I had something like this in that sketch I think (see “Menu version” and/or the “X” button):

https://github.com/tootsuite/mastodon/issues/262#issuecomment-262829923

The sketch led to the current design with the list at the top, but the version as a menu wasn’t implemented, and the “X” button neither, which makes the logic broken in a way since something is missing.

**Comment by James-Firth** [comment]
I really like your proposals in #262 as I find that fourth column is doing too much.

I often click through toots/conversations and my 'local history' gets nested very deeply so I have to keep clicking `<- Back` a lot to get to a point where I can click to view the Local or Federated timelines.

It'd be really nice to have your menu or X button versions to reset that pane (and also optionally open a new column on the desktop version of the site).

**Comment by wxcafe** [comment]
This is obsolete since we can now move columns around and both the home column and the links on top of the posting area stop showing columns that are enabled.
