### ISSUE TITLE
New user first experience

### ISSUE THREAD

**Issue by nclm** [tootsuite/mastodon#642]
This issue is opened on account of [this tweet](https://twitter.com/mattround/status/827111326828916736), criticizing legitimately what a new user first sees on Mastodon: nothing.

The minimum thing to do could be:
- In an empty Home column, add a message along the lines of _“You don’t follow anyone yet. Visit [the public timeline] or search for topics of your interest to get started and meet other users.”_
- In an empty Notifications column, add a message along the lines of “_You don’t have any notifications yet. Interact with others to start the conversation.”_

Alternatively, if not too confusing, the Home column could be replaced by the Public timeline until the first follow, with a message at the top explaining the situation, like _“Welcome around there. This is will be your own timeline once you start following other users. For now, here’s what people are talking about.”_

That can be the first steps, and more elaborate and elegant new user flows can be thought about from here.

**Comment by mitchellurgero** [comment]
I wouldnt change the home column - but instead display the public timeline by default instead. This makes more sense.
