### ISSUE TITLE
[Feature proposal] Option to show only local posts in the preview timeline

### ISSUE THREAD

**Issue by alignedleft** [tootsuite/mastodon#6422]
This is either a feature proposal or a question about whether or not this is a good idea. 🙂 

Currently, the public-facing “A look inside…” preview timeline shown to guests (users not logged in) on an instance home page shows content from the instance's *federated timeline*.

I would find it useful to have the option to show only my instance's *local timeline*, to better showcase to potential users the kinds of discussions happening within.

A toggle for setting this flag could live under *Administration > Site Settings*.

I realize (correctly, I hope) that a goal of the decentralized nature of the fediverse is to encourage cross-instance communication, so emphasizing local interactions may run counter to that. But given the proliferation of instances — especially more of them being topic-specific, like mine — a local option might better help potential account-holder-participants decide if this instance is right for them.

I would appreciate any thoughts, especially if I am missing something about the intent of the preview timeline. Thanks!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Resolved with #6292

**Comment by alignedleft** [comment]
Thanks, @Gargron and @renatolond! 👏
