### ISSUE TITLE
blank screen on login

### ISSUE THREAD

**Issue by NoNamesLeft59633** [tootsuite/mastodon#6436]
Sorry to bring this up. Normally I am able to have the timelines and everything show up when I login. Recently though when I login to this network nothing but a blank screen pops up. I apologize about this because I did come a similar issue before. That issue said it was something about corrupted privacy settings and recommended going to /settings/preferences to change them to a default option. That was enough to fix the other person's problem but no matter what I changed the settings to it still did not work. I have no idea where to go from here or how find or provide more information or what else people might need on this.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
In most cases, a blank screen on login means existence of some JavaScript errors (e.g. privacy settings thing). Could you check JavaScript console by hitting F12 and select [Console] tab or equivalent?

Example (there are some warnings but no errors):

![image](https://user-images.githubusercontent.com/705555/36009684-b197aa8e-0d90-11e8-93d2-266e936955e8.png)
