### ISSUE TITLE
API: getting a user's timeline requires you to be authenticated

### ISSUE THREAD

**Issue by maxf** [tootsuite/mastodon#6443]
User-related API calls like `GET /api/v1/accounts/:id`, `GET /api/v1/accounts/:id/statuses` aren't allowed without a valid auth token. Is there a reason it's required to be logged in?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by JMendyk** [comment]
Currently you can call `GET /api/v1/accounts/:id` without a valid auth token.
In terms of `GET /api/v1/accounts/:id/statuses`, a newer issue #7087 got some attention and a pull request #8457 was submitted. If you're still interested in this feature, you are welcome to join the discussion there.

Duplicate of #7087

**Comment by JMendyk** [comment]
Duplicate of #7087

**Comment by maxf** [comment]
This feature was implemented with #9573.
:+1:
