### ISSUE TITLE
add a DM button to Mastodon profiles

### ISSUE THREAD

**Issue by cphuntington97** [tootsuite/mastodon#6444]
When the DM button is clicked, a new direct message to that user would be opened in the composition column. 

"But if you want to DM someone, you can just click the hamburger menu, click Mention, and then in the composition column, click the privacy button, click Direct, and then click back in the composition text box to write the message."

Yes, but that's 5 clicks. This button would accomplish all of the above with a single click.

My goal is to attract and retain younger users to Mastodon who make extensive use of this functionality.

**Comment by ThisIsMissEm** [comment]
This has been implemented as of #6956
