### ISSUE TITLE
"503 Remote SSL cert could not be verified" when trying to fed with mastodon.social, but not other instances

### ISSUE THREAD

**Issue by Starling000** [tootsuite/mastodon#6449]
I am building an instance at left.community and I'm testing federation. Federating with most servers works, but when I try to @ a user on mastodon.social from left.community, no posts are loaded and a big blob of text is dumped to the system journal. When I try to @ left.community from mastodon.social, I get the error in the title: "503 Remote SSL cert could not be verified."

I don't seem to have any SSL issues when connecting to other domains, such as cybre.space. So is the issue on my server or on mastodon.social?

The error generated on my server when trying to contact mastodon.social is, frankly, enormous, so I'm uploading it in a text file.

[errorlog.txt](https://github.com/tootsuite/mastodon/files/1709028/errorlog.txt)
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Starling000** [comment]
That worked like a charm, thank you! This is my first time managing SSL certs, I appreciate the informative response.

**Comment by albjeremias** [comment]
So...
this guys from todon.nl complained they can't follow anyone on my instance... then they invited me to register on their instance.. I did it.. and I confirmed the bug.. I can't follow myself on my instance.. :(
So.. I get the error: "Remote SSL certificate could not be verified" ... and I went to investigate, but not luck the request is not sent directly to my instance, is sent to todon.nl instance.. and I get a "503 Service Unavailable".

How can I debug this further? asking todon.nl to check their logs?

**Comment by patf** [comment]
Did you run [SSL Labs](https://www.ssllabs.com/) on your instance yet? That'll reveal the most common SSL/TLS configuration issues such as the missing intermediate/chain certificate problem the OP ran into.

(If there's nothing obvious in the result, please share the instance domain for further debugging.)

**Comment by SuperSandro2000** [comment]
I am having trouble with this, too.
My instance is at mastodon.supersandro.de and sslabs reports is green.

**Comment by cyborch** [comment]
I'm seeing the same issue. my instance is activity.cyborch.com and ssl labs report is green for me too.

**Comment by Saqibm128** [comment]
I have the issue as well. Just trying to bump this. My instance is gaymedmastadon.social, and SSL labs report is also green.

**Comment by Maverynthia** [comment]
I also have this issue and I've made sure it says fullchain.pem
