### ISSUE TITLE
Suspended account seems unusual state of normal account

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#6454]
## Background

1. Suspend someone or block by domain
2. (forget about suspending them)
3. Search their account URL

![image](https://user-images.githubusercontent.com/705555/36024972-cb3e8536-0dd4-11e8-9916-398596ffdbe4.png)

It shows complete their profile except images, so I thought "images are missing somehow, but account is fetched correctly". Also, the follow button exists (though I got an 404 error by clicking it).

4. Search their post URL

![image](https://user-images.githubusercontent.com/705555/36024838-53e7049a-0dd4-11e8-9ae3-4026c36dea63.png)

Eh, 0 results? Am I wrong, or Mastodon's bug??

## Suggestion

* We shouldn't save any profile for suspended accounts, like we destroyed on suspension:
https://github.com/tootsuite/mastodon/blob/2ef9d0e1011b586099d9f9992607b03d96c8a7f8/app/services/suspend_account_service.rb#L43-L50
* How about saying "This account/domain is suspended by admin"? Then we can also hide follow button.
* Bonus stage: Return an error if searched URL is not fetchable due to account suspension

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Fixed in #7287
