### ISSUE TITLE
Is mastodon still actively maintained?

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6457]
I see a large dip in activity on the repo. Makes me wonder if it's still actively maintained.

**Comment by DJSundog** [comment]
The latest commit was literally within the last twelve hours.

**Comment by SoniEx2** [comment]
That doesn't mean it's actively maintained.

https://github.com/tootsuite/mastodon/graphs/commit-activity

What happened with that spike? Why was it just a spike? Etc.

**Comment by Cassolotl** [comment]
April 2017 was a biiiiig influx of new users. I'll bet all those new users brought feature requests, and the extra strain maybe exposed things that needed fixing or improving, and the sheer volume of people arriving and then some of them gradually or immediately leaving showed what could be changed to keep people around. Also I wonder if a bunch of new developers found out about the project and started contributing? So yeah, that's the spike - the Mastodon userbase multiplied in a big way, and that had various knock-on effects on the development of the project.

I guess if you wanted to replicate that you could do things to raise awareness of Mastodon, to get more active users and help them to stick around?

**Comment by Gargron** [comment]
Yes.
