### ISSUE TITLE
Follow buttons on another user's list of following/followers as with tw*

### ISSUE THREAD

**Issue by Epivalent** [tootsuite/mastodon#6467]
Currently it's hard to populate your account's feed from the following/followers lists of another user by pressing "follow" buttons -- mainly because they don't exist. 

So currently you have to navigate to profile pages individually and click follow from there. 

Could there be a follow button for each box per user on these list pages? 

Thanks in advance! 

@xeb@mastodon.social

**Comment by northerner** [comment]
Doesn't this already exist?
<img width="337" alt="screen shot 2018-02-17 at 13 26 18" src="https://user-images.githubusercontent.com/1578054/36341453-646ddca4-13e6-11e8-9fd3-da15882f76b5.png">
