### ISSUE TITLE
"Back button" behavior in web UI is confusing

### ISSUE THREAD

**Issue by eloquence** [tootsuite/mastodon#6468]
(tested with 2.2.0)

If I visit a page like this in an existing tab (adapt URL to an instance you're logged in on):
https://social.freeculture.org/web/timelines/public/local

and press the "Back" button the local timeline column, I end up on the previously loaded webpage in that tab, which may not be Mastodon at all. This is very confusing, as the attachment of the button to the column suggests that the "Back" button functions purely in the context of that column's contents.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by rhaamo** [comment]
is it the same issue as #3515 ?

**Comment by eloquence** [comment]
Yes! Feel free to close as duplicate, though I'd suggest re-titling #3515 for clarity.

**Comment by Cassolotl** [comment]
@eloquence You should have the ability to close it yourself, as the person who opened it!
