### ISSUE TITLE
Replies from blocked users to non-blocked users visible in thread view

### ISSUE THREAD

**Issue by fpiesche** [tootsuite/mastodon#647]
If Alex has Bobby blocked and Bobby replies to a post by Charlie, Alex can see Bobby's reply in the thread view for Charlie's posts. I think these should probably be hidden, maybe behind a "show reply" click so context for discussions can be shown if necessary (or entirely, including further replies in that thread, to avoid ending up with context-less replies by Charlie to replies by Bobby).

**Comment by ghostfromicosahedron** [comment]
i'd like to have the option to go either way. like maybe blocks never show up anywhere in any threads, and mutes can be seen in threads. in some cases, there's not much point in clicking a thread if half the conversation is hidden... maybe there's blocked folks i NEVER want to see, but muted folks i just want to avoid showing up in my regular TLs... but if I click a thread, I probably know what I'm getting into and understand i may end up seeing users I don't normally care to see.

**Comment by unarist** [comment]
The API to get conversation is supposed to filter those statuses, but it haven't work due to a bug.

This bug should be fixed at 42d11bdd3a51262fb197121aa79a11588e769fa7 (in #2381) and will be released on 1.4.

**Comment by mal0ki** [comment]
This bug should be fixed. Closing this issue.
