### ISSUE TITLE
Attempting domain block results in error when extra spaces surround domain name

### ISSUE THREAD

**Issue by joyeusenoelle** [tootsuite/mastodon#6473]
In instance moderation, when I attempt to block a domain but fail to strip extra spaces from around the domain name, Mastodon returns a generic "something went wrong" error page instead of stripping the extra spaces as expected.

Observed behaviors (using _ in place of a space character):

* `target.domain`: works correctly
* `_target.domain`: causes an error
* `target.domain_`: causes an error
* `_target.domain_`: causes an error

Expected behavior:

Mastodon should strip preceding and trailing spaces from domain names and correctly block target.domain in all above cases.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Should be fixed
