### ISSUE TITLE
Don't display following/followers of private/locked accounts

### ISSUE THREAD

**Issue by kit-ty-kate** [tootsuite/mastodon#6477]
Currently if you have a locked/private account, the accounts you follow and the accounts that follows you are displayed publicly.
I believe this shouldn't be the default behaviour for such accounts.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by utam0k** [comment]
I think in the current implementation, Toot is made to be private to followers so that it is not visible except for the followers.
Therefore, special implementation is required to make the follower private because the followers can also be seen by users who are not logged in.

**Comment by trwnh** [comment]
Seems most discussion of this is happening on #6901.
