### ISSUE TITLE
Turn off boosts from specific user in home timeline

### ISSUE THREAD

**Issue by wolfteeth** [tootsuite/mastodon#648]
Similar to Twitter's "Disable Retweets" feature. I'm following User X, but I only want to see their toots in my home timeline, not the toots they have boosted.

I should still be able to see the boosted toots by directly visiting User X's profile.

**Comment by jwisser** [comment]
Definitely seconded. I'd also like a preference to disable boosts universally. I find a lot more value in only seeing what people take the time to talk about themselves. Boosts/retweets encourage a lot of noise because they're so low-effort.

**Comment by Cassolotl** [comment]
@giromide says in #1026:

> Options in the account would thus be:
> Mute @SomeAccount
> Mute boosts via @SomeAccount
> Block @SomeAccount
> Report @SomeAccount

**Comment by akihikodaki** [comment]
What about favourites? Are they still notified even boosts are turned off?

**Comment by Cassolotl** [comment]
@akihikodaki This isn't about *notifications*, this is about the boosts themselves. We want to be able to follow someone but only see their original posts, but not see the posts they boost.

**Comment by erisdev** [comment]
please yes to this, it's nice to be able to turn them off altogether but i'd love to see boosts from my friends who always boost things i like. i just wanna hide the boosts from folx who always boost fundraising and political shit

**Comment by wxcafe** [comment]
Duplicate of #133
