### ISSUE TITLE
(tags) Make #C++ and #sci-fi work

### ISSUE THREAD

**Issue by raingloom** [tootsuite/mastodon#6489]
So many people mess this up. Look at the `#C` tag. Look at how many people are trying to tag `#C++` instead.

Since there is no syntax highlighter for tags while you edit them and no preview for the post, the correct solution would be to make the intuitive way work.

Personally, I think tags should include *every* character until whitespace. This would make tags like `#999` work. Yes, people using number notation would use tags inadvertently but imho that's better than not letting people tag things that have numeric names.

A **lot** of new users and even some experienced ones get caught up in this, so I think it deserves much more attention than it's currently getting.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wimvanderbauwhede** [comment]
I agree with the above: tags should include every character until whitespace. My view is that if I write a sentence, then anything in there preceded by a # should be a tag. So we could have #Steins;gate and #Nier:Automata and even #$@&%*! .

**Comment by webshinra** [comment]
I would mention that the scheme symbol syntax is a good reference for such problematic.

https://github.com/tsahara/r7rs/blob/master/content/lex.md

**Comment by SoniEx2** [comment]
Use Unicode. It defines hashtags.

**Comment by Artoria2e5** [comment]
The current hashtag is defined here for Ruby side:
https://github.com/tootsuite/mastodon/blob/6a82939adb823c9a65829c23dc7109a96480befe/app/models/tag.rb#L15

GNUSocial's tags, `\PL\PN_` is basically `[[:word:]]`:
https://github.com/foocorp/gnu-social/blob/3b5fabb/lib/util.php#L897-L898

The JS side currently uses #6431. It appears difficult for now (but not impossible -- see the hot new ES2018 Unicode property support and a ton of polyfills) to make the JS part perfectly line up the Unicode-aware Ruby, so the highlighter might be not always working as desired even if it gets implemented.

**Comment by Gargron** [comment]
>Personally, I think tags should include every character until whitespace

I don't agree.  What's wrong with #scifi? 

>This would make tags like #999 work

It used to work, it was requested by users that it should *not* work like that. I don't see a reason to keep flipping it.

**Comment by SoniEx2** [comment]
Make this tag work:

`#++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.`

**Comment by wimvanderbauwhede** [comment]
The counter-argument given above ("What's wrong with #scifi?") cuts no ice, as it singles out one specific term, and this is a  general issue. I have no problem with @Gargron closing the issue, after all, it's your code, you do as you please, you're our IBDFL. You don't even need to give reasons. So please don't give a spurious reason.

**Comment by nightpool** [comment]
@wimvanderbauwhede it's not spurious, it's an example of how most tags can be transformed into the space of letter symbols. For example, #cpp instead of #c++. you're failing to read other's arguments with the principle of charity.

The main argument here is "it used to work one way, it was found to have bad consequences (every instance of someone saying #1 turned into a hashtag unexpected, for example), we don't think there's enough demonstrated need to support re-adding it"

**Comment by SoniEx2** [comment]
base64 all the tags

**Comment by SoniEx2** [comment]
oh wait, that doesn't always work

**Comment by SoniEx2** [comment]
base26 all the tags

**Comment by wimvanderbauwhede** [comment]
@nightpool Thank you for your reply. I don't agree with it, but this is a minor issue and not worth pursuing.

**Comment by raingloom** [comment]
@Gargron what about `-` in tags? I see it so often that at the very least that one should be supported.

Just one more legal character and it would fix so many toots. Can't we have at least that???

**Comment by raingloom** [comment]
> I don't agree. What's wrong with #scifi?

People are not using it that's what's wrong. Their intuition suggests that `#sci-fi` should work and that means it should be made to work.

**Comment by nightpool** [comment]
i'm pro `#sci-fi`

**Comment by webshinra** [comment]
If there are compatibility issues, it would be temporary (update propagation delay) and marginal (such tags are relatively rare ATM).

**Comment by raingloom** [comment]
@nightpool there is an easy way to check
run simple script on an instance for a week and grep for tags that have a hyphen at their end

**Comment by SoniEx2** [comment]
Special case some tags (C++ sci-fi non-binary etc)

**Comment by raingloom** [comment]
Special casing is usually the worst thing to do, adding hyphens would be better.

If you add one special case, soon you will have to add 3 others and then it'll all be a mess very soon.

**Comment by SoniEx2** [comment]
Exactly. Make a list.

**Comment by SoniEx2** [comment]
(Even better if you make it user-configurable)

**Comment by webshinra** [comment]
That's a very bad idea.
Tags are meant to allow to classify similar content. If you use a list of pre-determined keyword to avoid a syntax extension, you end:

1. making a very specific syntax extension (English is not the only language is the world, neither is Latin alphabet)

2. making incompatible standard for each user/instance.

And that, you really don't want.

**Comment by SoniEx2** [comment]
Let the user mark tags in the UI, let the user setup custom tags, let the user make tags work as desired.

Let the user add `#666` as a tag, make a toot with it, then remove it.

It should work fine.

**Comment by raingloom** [comment]
Hey could we reopen discussion on this and at least make a list of what it would break and what is broken because of the current behaviour?

@nightpool the current behaviour already breaks things and makes things harder to search. That's a fact. Not sure what Mastodon's inner workings look like, so I don't know what the effects on backwards compatibility would be, but since no one actually listed any concrete cases where changing the tag syntax would do harm, I think the benefits outweight the potential dangers.

**Comment by raingloom** [comment]
I'm gonna start collecting links to posts that are broken because tag syntax still sucks.

https://mastodon.cloud/@SaschaTee/100673337188146496

**Comment by raingloom** [comment]
Feel free to provide examples to ones that would break with a more liberal syntax.
