### ISSUE TITLE
pinned toots, implementation opinions

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#649]
first, i would suggest more bio space, as pinned posts are generally used to accommodate inadequate bio space. i think 500 (a toot) or even 750 characters is a much better thing than what we have now.

the other use case is generally to make things easier to share, easier to save things for people who might want to follow you to see. this is, notably, different from the other use. i would recommend, to accommodate this, that there can be _multiple_ pinned toots, so that anyone can have as many as they want. they would, theoretically be viewed just like how toots show up in the profile, and i would even suggest, if there are any (or more than one, with only one pinned toot showing above normal toots) pinned toots, those show instead of the default "all toots of a follower" as the first things they see below the bio.

i would suggest to functionalities for pinning a toot. namely, "pin toot" would add to the end of the list (bottom) and "pin toot (with checkbox checked (to top)) would make it be at the tippity top of the list.

thank you for listening

**Comment by hoodiek** [comment]
no @ tags in pinned toots is another strong opinion.
deters harassment a bit, tiny bit but it's a bit, i've seen pinned toots used for callouts and such.

**Comment by mitchellurgero** [comment]
This would be great to be able to pin lik #introduction toots.

**Comment by mcat-ee** [comment]
@hoodiek 'no @ tags in pinned toots' as in not allowing toots with @ tags to be pinned, or making such tags inactive when the toot is pinned?

**Comment by mitchellurgero** [comment]
I'd say the latter. but maybe for privacy just remove the tag all together?

**Comment by mcat-ee** [comment]
So `Follow my new account @newaccount` would just be `Follow my new account newaccount` ?

In that case (to avoid harrassment) the tagged user should still be notified.

**Comment by nykh** [comment]
This is a tangent, but why limiting ourselves to ONE pinned tweets? An artist might want to pin both a bio, and a upcoming publishing/event. I say we give people just about any number of toots and trust most will use them reasonably. This should be as hard as pinning one toot, isn't it?

**Comment by nykh** [comment]
I see people have already talked about the possibility of pinning more than one toot. And I endorse the idea.

**Comment by azbulutlu** [comment]
longer bio and pinned toot have overlapping but distinct use cases, it would be wonderful to have the both.

**Comment by wxcafe** [comment]
Closed since it's been implemented
