### ISSUE TITLE
Mastodon can no longer be installed on Scalingo (image too large)

### ISSUE THREAD

**Issue by aral** [tootsuite/mastodon#6491]
I just tried upgrading mastodon.ar.al to from 2.1.0 → 2.2.0 and the upgrade failed with the following error:

```
 !   Error deploying the application
 !   → mastodon-aral image exceeds the limit of 650MB - (734MB)
```

Scalingo has a maximum image size of 650MB for deployments, which Mastodon now exceeds (and which they detail at http://doc.scalingo.com/deployment/build-error#size).

Possible ways forward:

  - [ ] Contact Scalingo and ask them to increase this limit
  - [ ] Reduce the image size of Mastodon
  - [ ] Remove Scalingo support from Mastodon and suggest people to use a different provider
  - [ ] …?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [2.2.0](https://github.com/tootsuite/mastodon/releases)

**Comment by Soulou** [comment]
Hi there, Scalingo's CTO here, I'm currently having a look to keep Mastodon deployable on Scalingo. I'll update the issue as soon as we've something which works as expected.

**Comment by Soulou** [comment]
Ok the issue has been solved. Here is the explanation, recently Yarn location changed from being in `/app/.cache/yarn` to `/tmp/yarncache-[randstring]` As a result cache yarn was added to the image of the application, making it grow of several megabytes.

Now we're automatically cleaning `/tmp`, so the application get (way) under the limit again.

Regards,

**Comment by nightpool** [comment]
thanks for looking into it! should we close this issue or is there
something to be done on our end?

**Comment by Soulou** [comment]
Sorry I should have precised it, there is nothing to do from your point of view, so you can close it.

**Comment by nightpool** [comment]
no worries! you were fine, I was just making sure.

**Comment by aral** [comment]
Thanks, @Soulou – just wanted to confirm that I was able to successfully upgrade to 2.2.0 following your fix.

❤️ 🎈
