### ISSUE TITLE
Disabling login should also disable API access

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#6493]
We've implemented disabling of logins at #5615, including:

- Disable new login via browser
- Disable using existing sessions (those attempts will cause logout automatically)
- Disable emails to them

However, it doesn't touch API access. Existing access_tokens are still usable even if they're disabled.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Fixed in #7289
