### ISSUE TITLE
Sometimes '...' dropdown actions in expanded view appear outside the bottom of the screen

### ISSUE THREAD

**Issue by geckojsc** [tootsuite/mastodon#650]
Depending on the content, you may be able to see these actions by scrolling down after clicking the '...' (in my experience this worked for replies, but not for the main toot). Example below:

![image](https://cloud.githubusercontent.com/assets/569607/23168301/a135ac02-f83f-11e6-8d17-5d600d7d51fd.png)

**Comment by clement-analogue** [comment]
I am also affected by this bug. It appears also on the left column as shown here

![mastodon](https://user-images.githubusercontent.com/1931507/33963367-fd929c1e-e054-11e7-85cc-75f13a6ef363.png)
