### ISSUE TITLE
Option to delete profile picture and cover photo

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#6503]
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I think this is a duplicate of *Impossible to erase images in config #4458*.

**Comment by ThisIsMissEm** [comment]
This is also implemented partially from a moderator perspective in #6998
