### ISSUE TITLE
Media previews in timelines

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#6504]
Apart from media previews being shown when the user clicks on the toot, there should be also an option to show these directly in the timelines. Also there should be a setting to enable/disable this feature and an option to enable this feature only for the home timeline.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I think this is a duplicate of *URL unfurling in timeline? #819*?
