### ISSUE TITLE
Jobs are stored in Sidekiq queues/chewy

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#6509]
After merging #6464 , every time you post, jobs are now stored in Sidekiq /queues/chewy.
It has not declined even after 30 minutes.

Is this normal behavior?

![2018-02-19 13 37 29](https://user-images.githubusercontent.com/766076/36363195-545cd006-157e-11e8-8aba-511eab64d7b4.jpg)

Environment:
RAILS_ENV=production
ES_ENABLED=true
Mastodon master bb26cdd
Elasticsearch v6.2.1

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
No, this is not intended! That should be in the pull queue probably, since pull is the lowest priority. Apparently that's a default setting I missed. https://github.com/toptal/chewy/blob/master/lib/chewy/strategy/sidekiq.rb#L36
