### ISSUE TITLE
blocked users' post shows up in home timeline

### ISSUE THREAD

**Issue by 8spinach** [tootsuite/mastodon#651]
dunno how or why or whether it's reproducible but i've just seen a post from a blocked user, from another instance (i'm using awoo.space and the blocked user tooted from mastodon.social).

[link to tooted reference](https://awoo.space/users/spinach/updates/5718) in case the image gets borked here.
![masto no-block](https://cloud.githubusercontent.com/assets/8673781/23188048/0550a492-f842-11e6-895b-7a43d02601a4.png)

**Comment by Gargron** [comment]
Has the block been done way earlier than the toot in question, or only shortly before?
