### ISSUE TITLE
Manifest.json

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#6526]
Hello!

I’m not sure what the issue is, or how to fix it, but once someone logs into my instance, they are sent to this address https://noff.co/manifest.json instead of https://noff.co/web/getting-started.

If a user goes to the instance address /after/ logging in, then they are sent to the correct page. Any advise?

**Comment by Gargron** [comment]
Can you try patch from the linked PR?

**Comment by malicioustoker** [comment]
Disregard, I saw what you changed and manually edited the file. Compiling now - will let you know in a bit!

**Comment by malicioustoker** [comment]
@Gargron I can confirm that the change you made to the file fixed the issue! Keep up the great work!!
