### ISSUE TITLE
Add badge for muted/blocked of user profile in last column

### ISSUE THREAD

**Issue by rhaamo** [tootsuite/mastodon#6544]
It would be great to add a badge (like the ```FOLLOWS YOU``` one) if the user is currently muted and/or blocked when displaying an user profile in the last column.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by connyduck** [comment]
Oh this is a good idea, I will implement this for Tusky as well.
