### ISSUE TITLE
"Found 3 elements with non-unique ID"

### ISSUE THREAD

**Issue by Technowix** [tootsuite/mastodon#6547]
Little issue found by @imncls , seem to only happen in Chrome, and dosn't trigger any error in Firefox.
Seem to be an issue with the JS 😕 
![Image of the issue](https://user-images.githubusercontent.com/1571367/36622676-d28d4f40-18fe-11e8-9f43-a1f7ce9d7d88.png)

**Comment by ykzts** [comment]
Resolved with #6543.
