### ISSUE TITLE
Locked account from an other instance stays out-of-sync after a follow

### ISSUE THREAD

**Issue by jpdeplaix** [tootsuite/mastodon#6548]
I have an account on social.wxcafe.net (version 2.2.0) and I'm following a locked account on mastodon.social (version 2.2.0) but the followers-only (pre-follow) toots from the locked account remain invisible to me.
The locked account was created more than 10 months ago.
A locked account on yet an other instance (version 2.2.0), created a month ago does not have this problem however.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
(there si probably a duplicate but I can't find it)

**Comment by jpdeplaix** [comment]
Some of the public toots are not visible either but loading them individually via the search bar seems to work. However it's not a solution obviously.

**Comment by nightpool** [comment]
Yes, this is part of how mastodon works. If your instance never got the private toots when they were made (because noone on your server was following this person) then they won't get them later

**Comment by jpdeplaix** [comment]
It's a shame. Can you point me to any (protocol) documentation that states this and that won't be fixed ?
I mean, it breaks the principal of federation if creating a new server means everything is half broken. It just encourages people to stay centralized. I mean this is really bad.
