### ISSUE TITLE
Ability to see original toots but not replies in the web UI profile thing

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#6552]
I'm looking at this account and I want to see the bot's actual toots that I will see if I follow the account, but all I'm seeing is the replies.

![screen shot 2018-02-25 at 08 41 02](https://user-images.githubusercontent.com/6607512/36639599-bd9f12b2-1a07-11e8-9b9e-20519b5b1f69.png)

I think it would be cool to be able to just see original toots, like when you're looking at the full profile page:

![screen shot 2018-02-25 at 08 42 59](https://user-images.githubusercontent.com/6607512/36639605-eb744cf2-1a07-11e8-84f7-4f77edcc60c7.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by andi1984** [comment]
@wxcafe @Gargron Is this still an open task? I'm wondering because I can actually see the latter screen even when I'm not following someone. Maybe this behaviour changed in the meantime since February?

**Comment by nightpool** [comment]
yep! this was implemented!

(i can't find the PR link right now unfortunately :( )
