### ISSUE TITLE
Instance names should go into HTML <title> tags

### ISSUE THREAD

**Issue by radix** [tootsuite/mastodon#6564]
It'd be nice if the home page had the instance name in the HTML <title> tag, so that I can visually distinguish my instances in my browser.

![mastodon title tags](https://user-images.githubusercontent.com/227068/36687774-2f5ecb02-1af0-11e8-9291-ae1086a9d7e4.png)

I think this *might* also affect the app titles when saving the mastodon web app to my phone's home screen:

![phone titles mastodon](https://user-images.githubusercontent.com/227068/36688049-ec27d0b2-1af0-11e8-8fb0-ef7569ceb52c.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
It totally already does that, it's an admin setting, "Mastodon" is default.
