### ISSUE TITLE
Wrong dates

### ISSUE THREAD

**Issue by Fastidious** [tootsuite/mastodon#6567]
It seems dates are not showing right on the user's page (haven't checked anywhere else). As an example, see https://mastodon.social/@david?max_id=15452, the first entry. It will read "last year", but if you hover over it, you will see that it happened October 5, 2016.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
hmm I would say that's just a rounding imprecision, as in the rouding goes "n minutes, or n hours, or n days, or n months, or n years" and since this date is about 1 year old it still registers as "1 year ago".

**Comment by Fastidious** [comment]
@wxcafe perhaps. That is why it would be best to show actual times and dates, after certain time has passed, and not continue providing imprecise terms.

**Comment by Gargron** [comment]
I think it shows date instead of "1 year ago" now.
