### ISSUE TITLE
remove @m4sk1n contribution because of his extremalne right-wing capitalisn views

### ISSUE THREAD

**Issue by CebulaPL** [tootsuite/mastodon#6579]
[Issue text goes here].

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by redtachyons** [comment]
@CebulaPL Please refer [Code of Conduct](https://github.com/tootsuite/mastodon/blob/master/CODE_OF_CONDUCT.md) and check if it is violated.

**Comment by wxcafe** [comment]
I'm closing this issue because
- as @redtachyons said, I don't believe the Code of Conduct has been violated
- even if it were, the procedure to report violations is to email eugen@zeonfederated.com
- even then, I'm not convinced banning a contributor means removing their contributions.

**Comment by m4sk1n** [comment]
wtf?

**Comment by wxcafe** [comment]
hmm?

**Comment by m4sk1n** [comment]
this issue

**Comment by wxcafe** [comment]
:man_shrugging: it's closed and done as far as I'm concerned

**Comment by m4sk1n** [comment]
@wxcafe yup, it's closed but for me it's pretty funny, I don't understand its purpose…
