### ISSUE TITLE
Feature Request: Show number of replies to toots

### ISSUE THREAD

**Issue by robertdherb** [tootsuite/mastodon#6600]
Currently there is no indication of discussion on toots until you click them. Would be nice to have a feature similar to the comment icon on twitter.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [n/a] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tateisu** [comment]
Conversation is tree, not kind of list. The index number will change depending on which toot is based on extracting the conversation tree.

**Comment by albjeremias** [comment]
@tateisu but is it possible to implement? Or somehow federation complicates it?

**Comment by thiagomgd** [comment]
This is something that really bothers me, not knowing when a toot has replies or not...

**Comment by spaceottercode** [comment]
@robertdherb  @Gargron is this before the 1 and 1+ indicators.

**Comment by nightpool** [comment]
yes, this was implemented

**Comment by robertdherb** [comment]
The current reply indicators have resolved this issue.

**Comment by KaKi87** [comment]
Hello,
What's the reason why `0`, `1` & `1+` are the only available values ?
Thanks

**Comment by ronilaukkarinen** [comment]
> Hello, What's the reason why `0`, `1` & `1+` are the only available values ? Thanks

I really don't know why there's a textual number 1+ on Mastodon. Perhaps for not showing engagement on purpose to prevent people behaving attention-boosting ways or something? It seems there's some sort of rationale [here](https://github.com/mastodon/mastodon/pull/8181#issuecomment-412770237), but I still don't get it.

This can be changed by literally one line of code, change `return '1+';` to `return count;` [here](https://github.com/mastodon/mastodon/blob/1708167dd3bde65eb6cd3bf5ad121c72a630ba65/app/javascript/mastodon/components/animated_number.js#L14) and rebuild your assets.

**Comment by KaKi87** [comment]
It still doesn't explain the difference between `1` & `1+` :thinking:

**Comment by nightpool** [comment]
@KaKi87 1 is "exactly 1 reply", 1+ is "more than 1 reply"

**Comment by KaKi87** [comment]
I know, but what I meant is, I don't understand why that distinction was made.

If the goal is to deny users from knowing how many answers there are and only telling them whether there are answers or not, there should only be a distinction between *0* and *1 or more*.

**Comment by trwnh** [comment]
> there should only be a distinction between 0 and 1 or more.

you're not wrong, in the comment linked above as "rationale", the request was to replace the number with a dot similar to notification badges.

> Perhaps for not showing engagement on purpose to prevent people behaving attention-boosting ways or something?

in 2017-2018 among early adopters there was a general consensus along those lines, and it's the same reason why the web-app will not show you fave/boost numbers in timelines. it only shows them in the detailed status view (and in the trending view, when that was added). i'm not sure what the current stance is on these kinds of design-level demetrification efforts, but i would hope that there is still some consideration toward encouraging people to critically think about what they are engaging with, instead of just seeing big numbers and taking psychological shortcuts.

**Comment by KaKi87** [comment]
> the request was to replace the number with a dot similar to notification badges

Actually, just replacing `1` with `1+` as well would have been enough, it's more often used as "one *or* more" than "more *than* one".

And regardless of the motivation not to display the real count, I think the user should be free (as in free as in freedom, just like free software, which is what Mastodon is, ironically) to choose whether to do it or not.

**Comment by trwnh** [comment]
> the user should be free (as in free as in freedom, just like free software, which is what Mastodon is, ironically) to choose whether to do it or not.

sure, but defaults matter, and every setting has a cost. if you're just building generalist software as a tool then that's also different from building opinionated software with a culture.

**Comment by ronilaukkarinen** [comment]
In a sense it would make more sense to not have any comment count or have them all present. After all there are no numbers on the star and boost icons, yet those exist when you open up the post and go to the Explore tab. These inconsistencies and "not knowing" increase my anxiety as a sufferer of GAD/OCD so this is kinda inclusivity issue as well. It has nothing to do with "trying to get more engagement" from my perspective, it's far fetched. There's a good [issue about consistency in all of this](https://github.com/mastodon/mastodon/issues/23058).
