### ISSUE TITLE
Zigzag shape at the bottom of the list modal window

### ISSUE THREAD

**Issue by Sylvhem** [tootsuite/mastodon#6601]
Since [Mastodon 2.1.2](https://github.com/tootsuite/mastodon/releases/tag/v2.1.2) and the move of the fluffy elephant friend from the "Getting Started" column to the composition column (see #6109), the zigzag shape also appears at the bottom of any list edition modal window.
![A screenshoot of Mastodon's list edition modal window.](https://user-images.githubusercontent.com/5222316/36910372-d8b460c4-1e40-11e8-9910-2779bef7a4d5.png)
The presence of this shape is making the last name of the list harder to read. Also, in my opinion, having the zigzag shape in this modal feels kinda random and unaesthetic.
I don't know if it's supposed to be a bug or a feature, but I suggest we remove it.

* * * *
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I think this is gone from current master?
