### ISSUE TITLE
Will TOOT delete be sent to Elasticsearch?

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#6602]
When "Full-text search" is enabled, deleting TOOT will return "500 Internal Server Error"  at searching for the text in that TOOT.
However, an error will only appear when searching, Mastodon itself will work without problems.

This error is fixed by executing “rails chewy:sync".

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Yes, deletes should go into ElasticSearch via Sidekiq. Furthermore, the search API has no way to display a status that's deleted even if its ID is returned by ElasticSearch.... Maybe that's the 500 error, that's not supposed to happen
