### ISSUE TITLE
Unable to build v2.3.0rc1 with docker

### ISSUE THREAD

**Issue by Moskito99** [tootsuite/mastodon#6605]
I tried to build version 2.3.0rc1 with docker-engine 17.05.0-ce
I get the following error:
```
Step 16/19 : COPY --chown=mastodon:mastodon . /mastodon
ERROR: Service 'web' failed to build: Unknown flag: chown
```

After digging around, it seems the error has something to do with the docker-engine.

chown is not available in the docker-engine 17.05.0-ce, it is in 17.09 and up....
```
marcus@zeus:~/u4u.org/mastodon$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

This is the actual packet for Ubuntu 16.04 LTS
```
marcus@zeus:~/u4u.org/mastodon$ apt-cache policy docker-engine
docker-engine:
  Installiert:           17.05.0~ce-0~ubuntu-xenial
  Installationskandidat: 17.05.0~ce-0~ubuntu-xenial
  Versionstabelle:
 *** 17.05.0~ce-0~ubuntu-xenial 500
        500 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

Is it possible to update to 2.3.0rc1 without the chown command?

Regards,
Marcus

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by redtachyons** [comment]
You may have to upgrade docker version, chown flag is relatively new

**Comment by Moskito99** [comment]
Hi,
yes I know!
But this is not how it should work.
Sorry, I chose a stable LTS distro to prevent problems with other apps /docker 
container, whatever...

Maybe the change of the dockerfile is a better solution.
https://stackoverflow.com/questions/44766665/how-do-i-docker-copy-as-non-root

COPY . /mastodon

And after this you can do the following:

RUN chown mastodon:mastodon /mastodon

This is more oldschool but backward compatible! ;-)

Regards,
Marcus


Am Sonntag, 4. März 2018, 16:09:19 CET schrieb Aboobacker MK:
> You may have to upgrade docker version, chown flag is relatively new

**Comment by fmauNeko** [comment]
This was made on purpose, as told in #6514 / be9bab171dc2b1fe43bc742decb71f64541ca347.

@Gargron this also breaks building on Docker Hub, but I'm pretty sure you've already noticed. Should this caveat be added to tootsuite/documentation, in the Running-Mastodon/Docker-Guide.md ?

**Comment by moritzheiber** [comment]
@Moskito99 @fmauNeko as a sidenote, `apt.dockerproject.org` has be deprecated since the beginning of last yet. The current repository can be found at `download.docker.com`, [according to the documentation](https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository).
