### ISSUE TITLE
Cannot boost your own followers-only toots

### ISSUE THREAD

**Issue by kit-ty-kate** [tootsuite/mastodon#6607]
If you have some followers-only toots (for instance if you have a locked account), currently it's not possible to boost them. It's always useful if you'd like to recall something to your followers or something like that.

I tried to dig into the code and I believe this sort of change can fix this easily:
```patch
diff --git a/app/views/stream_entries/_detailed_status.html.haml b/app/views/stream_entries/_detailed_status.html.haml
index e1122d5a..3f699f4c 100644
--- a/app/views/stream_entries/_detailed_status.html.haml
+++ b/app/views/stream_entries/_detailed_status.html.haml
@@ -42,7 +42,7 @@
     - if status.direct_visibility?
       %span<
         = fa_icon('envelope')
-    - elsif status.private_visibility?
+    - elsif status.private_visibility? and status.account != current_account
       %span<
         = fa_icon('lock')
     - else
```
However I don't know anything about Ruby/Rail and testing changes locally seems quite painful even with docker.
Moreover I don't know if boosting automatically makes the toot public or if there are some other issues.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by SoniEx2** [comment]
#3808 ?

**Comment by jpdeplaix** [comment]
@SoniEx2 mmh I guess #3808 is kind of a more general issue. I suppose we can see this issue as a sub-issue.

**Comment by ThibG** [comment]
Proposed in #6157 (allow boosting self private toots, does not change visibility). There is some UI work to do, though.

**Comment by jpdeplaix** [comment]
Awesome. Should I close this issue in favor of your PR or should I keep it open until it is merged ?

**Comment by ThibG** [comment]
Nah, just leave it open, we'll close it if the PR gets merged.

**Comment by kit-ty-kate** [comment]
I'm closing this as #6157 got merged a while ago.
@ThibG is there any plan of integrating glitchsoc's visibility indicator into vanilla ?

**Comment by ThibG** [comment]
@kit-ty-kate not that I know of. I made a PR to display the visibility indicator on public and admin views of toots, but it's in limbo. I haven't made a PR for the WebUI, and I don't think I'm going to spend time on this without @Gargron stating that such a change would be welcome.

**Comment by kit-ty-kate** [comment]
I see, fair enough :/ Thanks !

**Comment by lapineige** [comment]
I don't understand what's "glitchsoc's visibility indicator", can you explain it to me ?
You mean the feature is here, but there is no WebUI tool to use it ?

**Comment by ThibG** [comment]
@lapineige the feature will come in the next release and be usable via an extra option in the toot dropdown menu.

Glitchsoc is a fork of Mastodon with various changes, and the visibility indicator is one such change, displaying the privacy setting of a toot directly in the Web UI, as you can see in https://github.com/tootsuite/mastodon/pull/6157#issuecomment-355323700

**Comment by lapineige** [comment]
Nice, thanks for the explanation 🙂
