### ISSUE TITLE
New start page makes it really hard to find the CoC

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#6612]
On the old (pre 2.3) start page it was pretty easy to get to the instance rules. Just click "About this instance" and they're probably already there, or prominently linked. On the 2.3 start page there's a tiny link below the signup field which is really easy to overlook.

From my understanding, the idea behind the new start page is to put most of the info from "About this instance" on the front page. In my opinion the best way to solve this problem is to put an extra field for Code of Conduct / rules on the start page, but not put the whole text in there, as it would be overwhelming and take up too much space. Instead, one could have a short overview (similar to [how instances.social displays it](https://instances.social/mastodon.social), maybe?) and a button to view the whole CoC.

There is space below the signup form that might be ideal for this.

In addition to the visibility improvement this would also be a move that communicates the aim of the project to create healthy communities.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Ragzouken** [comment]
commenting to say that i spent a long while trying to find this with no luck until asking the fediverse to point me in the right direction

**Comment by Gargron** [comment]
Hopefully nobody minds me closing this now that the design changed again

**Comment by trwnh** [comment]
it's kind of still applicable to the current design. compare these two about pages...

mastodon.social | awoo.space
--- | ---
![image](https://user-images.githubusercontent.com/10606431/60148532-26e66500-9797-11e9-89dd-bae61132953f.png) | ![image](https://user-images.githubusercontent.com/10606431/60148555-3e255280-9797-11e9-9e57-85986d06799f.png)

imo it makes sense to make the /about/more page at least as prominent as login/signup
