### ISSUE TITLE
Allow boosting non-public toots, following certain rules

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6625]
This is similar to #3808 but more focused on non-public stuff, which #3808 completely ignores.

The idea is, like in #3808, to boost private toots. But there are a few key differences:

1. Boosts have privacy rules: public (aka unlisted, since as far as I know boosts don't show up in instance or federated timelines?) or followers-only.
2. The original toots need to keep track of "visibility sources" - the ppl who boosted them. This means the DM system in #3808 wouldn't work.
3. There's no quick-boost feature for these. You must specify a privacy setting every time. (Arguable)
4. As in #3808, the OP can allow or deny the boost. The OP can make this choice based on the user who requested it, and the privacy level requested.
5. Just because a boost is public doesn't mean others can freely boost it. It must still go through the OP. (Arguable)
6. (How do we handle toots with mentions? Get permission from everyone involved?)

Unresolved questions (please discuss these!):

- [ ] Should there be a "quick boost-request", like normal "quick boosts"? (shift+boost button)
- [ ] Should boost requests go through OP even when boosting a boost, as opposed to boosting OP directly? (I think they should)
- [ ] How do we handle mentions? Should we get permission from everyone involved?
    - [ ] If so, what about blocked users/instances?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by SoniEx2** [comment]
This could be rather interesting, especially if it interacted with lists somehow (boost-to-list!).

Then every admin/support bot would just boost-to-list of admins and things would be a lot simpler.

Please add this.

**Comment by duck57** [comment]
What would be the use case?  People who want to share private posts just use (or fake) a screenshot.

**Comment by SoniEx2** [comment]
Sure, but that doesn't exactly promote consent.

**Comment by SoniEx2** [comment]
I want this so others can boost my toots when I accidentally make them followers-only rather than unlisted

**Comment by SoniEx2** [comment]
This adds active consent to boosts, rather than the passive consent we have with public/unlisted vs followers/direct.
