### ISSUE TITLE
Password reset link still goes to error page

### ISSUE THREAD

**Issue by celesteh** [tootsuite/mastodon#6626]
I'm still getting the same behaviour described in issue https://github.com/tootsuite/mastodon/issues/6611

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ykzts** [comment]
Resolved with #6616.

**Comment by nightpool** [comment]
to be clear: the code change was merged. it hasn't been deployed to
mastodon.social yet. this means you won't see the change until the next
bugfix release goes out
