### ISSUE TITLE
Create a Contributors file

### ISSUE THREAD

**Issue by foxiepaws** [tootsuite/mastodon#6629]
Create a file which contains the name, optionally email/handle of every single person who has contributed code to this project. This will help keep contributors having credit even if the project is hosted on other platforms than github or using different VCS systems than git. 

It is a silly assumption to assume that everyone is going to use the same VCS platform and hosting. and then you put in the Contributing.md, how people should format such an entry.

[sorry for the mess i made with github issues, I am NOT good at using all of its features at all]

* * * *

- [x]  I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by unarist** [comment]
This seems resolved at https://github.com/tootsuite/mastodon/pull/6685 by adding AUTHORS file.
