### ISSUE TITLE
Missing avatar and texts on /about/more page

### ISSUE THREAD

**Issue by kkretsch** [tootsuite/mastodon#6639]
On my local installation (2.2.0) which I upgraded from an really old 1.something version these days, I'm missing the round picture of myself and the two lines of text below are saying **Not set** and **N/A**.
Those lines should be filled by display_name and username I think.

When I compare it to i.e. mastodon.social, there I see the expected behavior.
On my place it is missing:
https://mast.kaikretschmann.de/about/more

PS: I did search the issues but the words "about" and "more" are not really helpful in this case ;-)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Siphonay** [comment]
I think you have to manually set the admin account you want to display. To do this, go into Settings > Administration > Site settings

Set your admin account @ and e-mail below the site description

**Comment by kkretsch** [comment]
Great, that was my error. From the labeling I didn't get a clue to use my plain user name and not my family name. Now it's working. Thanks.
