### ISSUE TITLE
Add a NOTICE file containing every contributor

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6643]
I don't know if NOTICE files are a thing in the GPL but I really hope they are. This provides a layer of protection against projects that nuke the commit history.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by foxiepaws** [comment]
This is a duplicate of https://github.com/tootsuite/mastodon/issues/6629

**Comment by unarist** [comment]
Now we have AUTHORS file (https://github.com/tootsuite/mastodon/pull/6685), so this has been resolved?
