### ISSUE TITLE
AP Remove uses wrong property for collection (!)

### ISSUE THREAD

**Issue by puckipedia** [tootsuite/mastodon#6657]
This is probably a misreading of the AS2 vocabulary:

https://github.com/tootsuite/mastodon/blob/9110db41c53a2f3f22affc23b364362133997d3e/app/serializers/activitypub/remove_serializer.rb#L21-L23

https://github.com/tootsuite/mastodon/blob/9110db41c53a2f3f22affc23b364362133997d3e/app/lib/activitypub/activity/remove.rb#L5

The `origin` is used in the case where you want to e.g. `Remove` the role from a user, in a specific context. The context here is `as:origin`. You want to use `target` instead, just like in `Add`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
```
Indicates that the actor is removing the object. If specified, the origin indicates the context from which the object is being removed.
```

origin seems correct here?

**Comment by nightpool** [comment]
the two examples don't seem to help clarify. One uses target and the other uses origin, with no indication of what the logic is behind considering a collection a Target and a group an Origin

**Comment by puckipedia** [comment]
The group, in itself, isn't a collection, so you can't ever remove anything directly from it. But you can say "I removed this person", which will only apply within the context of that group. Aka `origin`

Removing an item from a list applies always, so it has no `origin`, only a `target`. At least, I would say so.

I mean, wouldn't you have to use `origin` in `Add` also then?

**Comment by nightpool** [comment]
I guess AP is controlling here, which reads:

```
Upon receipt of a Remove activity into the outbox, the server SHOULD
remove the object from the collection specified in the target property, unless:

 - the target is not owned by the receiving server, and thus they are
    not authorized to update it.

 - the object is not allowed to be removed from the target collection
    for some other reason, at the receiving server's discretion.
```

which i guess is fine, let's just use target.
