### ISSUE TITLE
`purge_remote_accounts` removes boosted/fav'ed toots

### ISSUE THREAD

**Issue by lo48576** [tootsuite/mastodon#6658]
`mastodon:maintenance:purge_remote_accounts` removes toots which are boosted/fav'ed by local user.
(This "local" means "instance where `purge_remote_accounts` is executed.)

However, I think they should be (or at least, can be) kept to local DB, because they are part of our user timelines, and they will be important to keep our posts' context ("what we talked / replied about?").

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).
    + Using `778b37790b425debd16b73c21f0805ff2e9a4ce8` (after v2.3.0rc1)

**Comment by Gargron** [comment]
If you want to keep accounts that no longer exist, do not run `mastodon:maintenance:purge_remote_accounts`, it is optional. Fully removing deleted accounts is desired behaviour.

**Comment by lo48576** [comment]
Then, is there any plan to add functionalities such as "delete (removed) remote users whose toots are not boosted/fav'ed by local user"?

**Comment by tateisu** [comment]
https://gist.github.com/tateisu/c3c13f2580961e86f79889a17f57260a
