### ISSUE TITLE
No confirmation email

### ISSUE THREAD

**Issue by taoeffect** [tootsuite/mastodon#666]
Just created an account on https://mastodon.social, but no confirmation email arrived. I checked my Junk, nothing there. I did the resend thing, and still nothing. My email is contact @ [my username] [dot] com.

**Comment by Gargron** [comment]
On the side of Mailgun (which delivers mastodon.social e-mails), the e-mails were delivered successfully. If you have a custom e-mail server, it might be configured to outright delete what it believes to be spam without notifying you.

**Comment by taoeffect** [comment]
OK, so thanks to this I've discovered that my Mail application and my email server do not use the same Junk folder. :-\

So it was going into the Junk, just not the right Junk folder. *grr... death to email!!*

Thanks for looking into this, and sorry for troubling you. I'll close this evil issue #666.
