### ISSUE TITLE
Issues after changing WEB_DOMAIN to be the same as LOCAL_DOMAIN

### ISSUE THREAD

**Issue by aminb** [tootsuite/mastodon#6667]
So I started out on a setup with different `LOCAL_DOMAIN` and `WEB_DOMAIN` in order to run mastodon on a subdomain while using top-level user ids.

I decided to try changing my setup by commenting out `WEB_DOMAIN` and effectively moving mastodon to top-level. However, after the change, my instance seems to have trouble communicating with other mastodon instances (GNU social instances seem to be just fine with the change).

Here are some of the errors I see in the Sidekiq panel:

**First**, this is the error I got when trying to follow `@a@functional.cafe` from `@b@nda.li`:

- Job: `ActivityPub::DeliveryWorker`
- Arguments:
```
"{\"@context\":[\"https://www.w3.org/ns/activitystreams\",\"https://w3id.org/security/v1\",{\"manuallyApprovesFollowers\":\"as:manuallyApprovesFollowers\",\"sensitive\":\"as:sensitive\",\"movedTo\":\"as:movedTo\",\"Hashtag\":\"as:Hashtag\",\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"conversation\":\"ostatus:conversation\",\"toot\":\"http://joinmastodon.org/ns#\",\"Emoji\":\"toot:Emoji\",\"focalPoint\":{\"@container\":\"@list\",\"@id\":\"toot:focalPoint\"},\"featured\":\"toot:featured\"}],\"id\":\"https://nda.li/users/b#follows/32\",\"type\":\"Follow\",\"actor\":\"https://nda.li/users/b\",\"object\":\"https://functional.cafe/users/a\",\"signature\":{\"type\":\"RsaSignature2017\",\"creator\":\"https://nda.li/users/b#main-key\",\"created\":\"2018-03-07T02:40:14Z\",\"signatureValue\":\"HTL/KVz69jV/4hu2nMYn5Uq8DDZqFMLDI4FP7rk+IApFsBhJFo9bNKvtIPOGGiY8eobvM97Y0jwiTC/oUpY2/C/vv1jOo6TPZbt/CuHkkkqKYUi8PFy01APBNEuXSum3uQUYWT6DJTtEv4kMbZSzrXySQxrAs7Htu0Fa/t+3z6IWviddLtQ1bb5PaRKX6D4TgGNdACsdGrbmXGYgwrCXI5iT2JcQdMM987jqrY7kBfo9EAfNcFbaKT4sFM420JMP35VNen45/rPi1C5e81oHulaKTximk2on2G82Jpe9LYi5Yla+iJaTyp7BkYSzuNrXLgKeyXrwYVZZQFMsdiNv+Q==\"}}", 1, "https://functional.cafe/users/a/inbox"
```
- Error: `Mastodon::UnexpectedResponseError: Delivery failed for https://functional.cafe/users/a/inbox: https://functional.cafe/users/a/inbox returned code 422`

**Secondly**, here's another error when trying to unfollow:

- Job: `ActivityPub::DeliveryWorker`
- Arguments:
```
"{\"@context\":[\"https://www.w3.org/ns/activitystreams\",\"https://w3id.org/security/v1\",{\"manuallyApprovesFollowers\":\"as:manuallyApprovesFollowers\",\"sensitive\":\"as:sensitive\",\"movedTo\":\"as:movedTo\",\"Hashtag\":\"as:Hashtag\",\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"conversation\":\"ostatus:conversation\",\"toot\":\"http://joinmastodon.org/ns#\",\"Emoji\":\"toot:Emoji\",\"focalPoint\":{\"@container\":\"@list\",\"@id\":\"toot:focalPoint\"},\"featured\":\"toot:featured\"}],\"id\":\"https://nda.li/users/b#follows/32/undo\",\"type\":\"Undo\",\"actor\":\"https://nda.li/users/b\",\"object\":{\"id\":\"https://nda.li/users/b#follows/32\",\"type\":\"Follow\",\"actor\":\"https://nda.li/users/b\",\"object\":\"https://functional.cafe/users/a\"},\"signature\":{\"type\":\"RsaSignature2017\",\"creator\":\"https://nda.li/users/b#main-key\",\"created\":\"2018-03-07T02:40:25Z\",\"signatureValue\":\"EV3wYByh27XFOZvYvqPlCgt4efDlsu10lDRHBGisMisPtdS5D+nTdHYXxGwksSIIliY1paWxtPjhYs07aAWllqz1GJ5Xqm1eRHblzTubiGf2x618cUBxvx8P4wb32MThuNesMWBenLRFvYpFY2fKcveA1uALjRg6EKPJfMh3c7UixVy+mB5vRoCLhatW0lQdEGYx7tmzzN7HBZGc2vLmqtWxzf2utsGvgQLb9qVIUzNBpM9TCy59PWWMlAytfOJP8gYHJv6OU/Tr/jHq+XmzJfMdtuSv7awSRrsG2eOdo0Kp3QdZXdoMgjWDz/RiP3/olSc8d3CYEQJHphdHBPkrJQ==\"}}", 1, "https://functional.cafe/users/a/inbox"
```
- Error: `Mastodon::UnexpectedResponseError: Delivery failed for https://functional.cafe/users/a/inbox: https://functional.cafe/users/a/inbox returned code 422`

Of course; neither of the actions were successfully carried out.

Any ideas or possible solutions?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
It would be helpful if you could get logs from the other instances involved.

**Comment by aminb** [comment]
Good point! I asked an instance admin to see if they could give me relevant logs. I'll post here when I hear back.

**Comment by Gargron** [comment]
It's because ActivityPub URIs use WEB_DOMAIN (because they must be resolveable). There's two unique identifiers, username+domain pair and URI. So now that WEB_DOMAIN changed, there's two different URIs for one username+domain pair. When trying to save your account record (which is probably created anew because URI is supposed to be authoritative in ActivityPub...) it fails uniqueness validation (422 = Validation failed)

I remember one other person coming across this. I don't remember what we did.

**Comment by trwnh** [comment]
>URI is supposed to be authoritative in ActivityPub...

How realistic is it to propose a change to ActivityPub so that URI is *not* authoritative? Hypothetically, URIs can and do change all over the web.

**Comment by ThibG** [comment]
@trwnh something has to be authoritative, and in ActivityPub's case, that's the author URI. Mastodon has always been the weird one in OStatus and ActivityPub land by making the username+domain pair the main identifier (this is a purely optional mechanism for discovery in OStatus, and it is out of scope for ActivityPub).

So… I'm not sure we should consider this a bug, although I incorrectly thought Mastodon would just happily replace the existing record for the username+domain pair.

Mastodon's handling of “reclaimed” usernames or URIs is a bit broken in general, though, but I don't have any good idea regarding that right now.

**Comment by trwnh** [comment]
@ThibG If I was designing a system from the ground-up, I would use some sort of unique ID. URI sounds good in theory until you consider cases where URIs change -- it would be much better to generate something instead, like a hash or a random 64-bit number or something like that. If that's out of scope for ActivityPub, then what other option is there for handling a URI change gracefully?

**Comment by Gargron** [comment]
@trwnh If you use a random 64-bit number, then anyone could claim to be that 64-number. The advantage of URIs is that you have the DNS system to prove ownership.

**Comment by trwnh** [comment]
@gargron well, not exactly a 'random' 64-bit... moreso something verifiable, like one depending on a hash or a digital signature.

FWIW the way zot handle magic-auth seems to be https://project.hubzilla.org/help/en/developer/zot_protocol#Technical_Introduction

> In order to create a globally unique ID, we will base it on a whirlpool hash of the identity URL of the origination node and a psuedo-random number, which should provide us with a 256 bit ID with an extremely low probability of collision (256 bits represents approximately 115 quattuorviginitillion or 1.16 X 10^77 unique numbers). This will be represented in communications as a base64url-encoded string. We will not depend on probabilities however and the ID must also be attached to a public key with public key cryptography used to provide an assurance of identity which has not been copied or somehow collided in whirlpool hash space.

This GUID is then cloned across every server at which you decide to replicate your data. Each communication has a target GUID, a target RSA signature, and a corresponding public key. I'm not sure what the equivalent would be for Mastodon or ActivityPub, though.

**Comment by mdallastella** [comment]
Hi, functional.cafe admin here. 
Unfortunately, I don't have any entries on `log/production.log` (it's empty...), I can only confirm what @aminb say: functional.cafe replies with a 422 to his server subscription requests.

```
99.99.99.99 - - [06/Mar/2018:20:45:29 +0100] "GET /users/a HTTP/1.1" 200 2321 "-" "http.rb/3.0.0 (Mastodon/2.3.0rc1; +https://nda.li/)" "-"
99.99.99.99 - - [06/Mar/2018:20:45:29 +0100] "GET /users/a HTTP/1.1" 200 2321 "-" "http.rb/3.0.0 (Mastodon/2.3.0rc1; +https://nda.li/)" "-"
99.99.99.99 - - [06/Mar/2018:20:45:29 +0100] "GET /system/accounts/avatars/000/031/852/original/f684a0169338fcc1.png HTTP/1.1" 200 11656 "-" "http.rb/3.0.0 (Mastodon/2.3.0rc1; +https://nda.li/)" "-"
99.99.99.99 - - [06/Mar/2018:20:45:29 +0100] "GET /system/accounts/headers/000/031/852/original/80a4161238707786.png HTTP/1.1" 200 313489 "-" "http.rb/3.0.0 (Mastodon/2.3.0rc1; +https://nda.li/)" "-"
99.99.99.99 - - [06/Mar/2018:20:45:29 +0100] "GET /users/a/outbox HTTP/1.1" 200 1880 "-" "http.rb/3.0.0 (Mastodon/2.3.0rc1; +https://nda.li/)" "-"
99.99.99.99 - - [06/Mar/2018:20:45:29 +0100] "GET /users/a/following HTTP/1.1" 200 797 "-" "http.rb/3.0.0 (Mastodon/2.3.0rc1; +https://nda.li/)" "-"
99.99.99.99 - - [06/Mar/2018:20:45:29 +0100] "GET /users/a/followers HTTP/1.1" 200 797 "-" "http.rb/3.0.0 (Mastodon/2.3.0rc1; +https://nda.li/)" "-"
99.99.99.99 - - [06/Mar/2018:20:45:43 +0100] "POST /users/a/inbox HTTP/1.1" 422 73 "-" "http.rb/3.0.0 (Mastodon/2.3.0rc1; +https://nda.li/)" "-"
99.99.99.99 - - [06/Mar/2018:20:46:08 +0100] "POST /users/a/inbox HTTP/1.1" 422 73 "-" "http.rb/3.0.0 (Mastodon/2.3.0rc1; +https://nda.li/)" "-"
99.99.99.99 - - [06/Mar/2018:20:46:16 +0100] "POST /users/a/inbox HTTP/1.1" 422 73 "-" "http.rb/3.0.0 (Mastodon/2.3.0rc1; +https://nda.li/)" "-"
99.99.99.99 - - [06/Mar/2018:20:46:44 +0100] "POST /users/a/inbox HTTP/1.1" 422 73 "-" "http.rb/3.0.0 (Mastodon/2.3.0rc1; +https://nda.li/)" "-"
...
```
and so on.

HTH.
