### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by wion** [tootsuite/mastodon#667]
I use a 13" MBP, which is not an uncommon size screen. In Safari there's about a 50px break too wide that requires horizontal scrolling, even when browser is expanded full screen. Not a deal-buster, but it does seem unnecessary.

Label: 'web ui'

**Comment by Gargron** [comment]
I wish I could make everything 50px thinner but everything is already optimal size, in my opinion. You now have the option of removing a column, which may help your case.

**Comment by nhoizey** [comment]
https://github.com/tootsuite/mastodon/issues/697#issuecomment-306140986
