### ISSUE TITLE
OAUTH_REDIRECT_AT_SIGN_IN breaks logging out

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#6670]
#6540 introduced the ability to always sign in with a specified auth provider, by making the new session path redirect to the relevant auth method.

However, `app/controllers/application_controller.rb` has `after_sign_out_path` set to the new session path, which then triggers login again.

If we want to preserve the functionality of taking the user to the login form upon signing out for normal users, but override for redirect_at_login users, we'll need to check for `config.strategy.redirect_at_sign_in` and override the path, like we do for the new session method.

I'm not sure if this change should be in `app/controllers/application_controller.rb` (where `after_sign_out_path` is currently set), or in `app/controllers/auth/sessions_controller.rb` (where an `after_sign_in_path` is set, and where we do the other checks for `config.strategy.redirect_at_sign_in`).

**Comment by gloaec** [comment]
@ineffyble What about just redirect to the homepage when the user signs out ? (only if oauth enabled et redirect _at_login enabled). Wouldn't it be simpler ?
