### ISSUE TITLE
Error when trying to change profile data

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#6673]
Hi,
When a user chooses arabic language as UI defaut language, he/she gets an error when trying to change the profile data, such as, avatar, bio etc.

Workaround :
- Switching to another language. It works.
- Changing the profile from any other Mastodon app
- It works on farsi language

Something wrong with arabic translation pointing on that page ? https://mastodon.social/settings/profile
I'll be happy to help solving this if it is related to some wrong RTL %$1s string.

Best regards,

**Comment by Gargron** [comment]
The counter hints are missing "many" variant

    translation data {:one=>"<span class=\"name-counter\">1</span> حرف متبقي", :other=>"<span class=\"name-counter\">%{count}</span> حروف متبقية"} can not be used with :count => 13. key 'many' is missing.

**Comment by BoFFire** [comment]
Ok thanks,
`Many` is the same as `Other`.

**Comment by Gargron** [comment]
I'm not sure in how many other places this error might come up, because some languages have more than just one/other, Arabic has 6 variants for example.

**Comment by BoFFire** [comment]
@Gargron I have just checked on Weblate and rewrited the strings. It seems okay. By the way Weblate has an option to point a string as one, two, many, other.
I'm checking Farsi :)

**Comment by BoFFire** [comment]
I made the fields empty, on Weblate, for now. Expecting fallback to english.

**Comment by BoFFire** [comment]
Hi, I removed the `<span class=` from the arabic translation strings.

**Comment by ykzts** [comment]
This problem is fixed with https://github.com/tootsuite/mastodon/pull/8171/files#diff-1258e1c3a2f1f38ecc59a7a041e979fcR11 .

![screenshot on settings](https://user-images.githubusercontent.com/12539/44708463-3434b380-aae2-11e8-8a4f-d9d892f81610.png)
