### ISSUE TITLE
[Feature] Separate media directories for local media and remote media

### ISSUE THREAD

**Issue by ThomasLeister** [tootsuite/mastodon#6675]
**Feature request**: Store local media in different directory than remote media. 

Reason: This way you can easily back up only important local media by your own users and ignore remote media, which can be seen as less critical.  

Idea by @Sascha@bonn.social [Mastodon].

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
This would be nice but I don't see a way to introduce this change now.

**Comment by ThomasLeister** [comment]
Hmmm, yes, I see the problem. Maybe someone comes up with a smart idea regarding this :-) If you don't mind we can keep this issue open for some more time?

**Comment by abochmann** [comment]
Can someone provide a pointer on how to identify all local media files and their storage path in the _media_attachments_ table (or elsewhere)? Having that, it would be easy to create a script that just backs up those.

**Comment by Gargron** [comment]
Fixed by #6675

**Comment by osresearch** [comment]
> Fixed by [#6675](https://github.com/mastodon/mastodon/issues/6675)

Isn't this #6675? Was there a different commit that fixed it?

**Comment by trwnh** [comment]
https://github.com/mastodon/mastodon/pull/12821
