### ISSUE TITLE
[bug] List cannot be deleted if name is too long

### ISSUE THREAD

**Issue by ThomasLeister** [tootsuite/mastodon#6682]
**Problem**: I've created a list with a long name. Now the burger menu is out of scope and I can't edit or delete my list :S 

![bildschirmfoto von 2018-03-07 12-50-46](https://user-images.githubusercontent.com/4207956/37090931-93b71f9c-2206-11e8-8a54-597f86aa336c.png)
![bildschirmfoto von 2018-03-07 12-51-00](https://user-images.githubusercontent.com/4207956/37090936-96a085fe-2206-11e8-806b-3a377c3737b1.png)

**Fix**: Either limit list name length or let user scroll in case the name exceeds the available space.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Solved in master
