### ISSUE TITLE
Sign up is display when registration is closed

### ISSUE THREAD

**Issue by Dryusdan** [tootsuite/mastodon#6683]
Hey
Today I migrate on v2.3.0rc2 of mastodon and I open the about page. My instance is closed but... Sign up button is display. Ok, it redirect on joinmastodon.org but the message make trouble...
Is it possible to change the message?

Thank
![capture](https://user-images.githubusercontent.com/4410431/37094220-7096b340-2212-11e8-914b-3c590afa9b1b.PNG)

* * * *
- [ ] This bug happens on a [v2.3.0rc2](https://github.com/tootsuite/mastodon/releases)

**Comment by ProgVal** [comment]
What about "sign up on another instance"? Or maybe add "on another instance" next to the button?

**Comment by Guimik** [comment]
With the default closed message it is confused to have "registrations are closed" followed by "register"
![capture](https://user-images.githubusercontent.com/31242178/37138816-cdd4bb1c-22ab-11e8-852d-9880350d814d.PNG)
