### ISSUE TITLE
Allow small GIFs as custom emoji

### ISSUE THREAD

**Issue by owhen** [tootsuite/mastodon#6687]
Currently, only static images in PNG format are allowed as an emoji. I would love to have custom animated emojis / little gifs in emoji size.

For example: ![64c190cb648252aa](https://user-images.githubusercontent.com/7263970/37110120-4c2fb6ee-223c-11e8-9948-4030e4a001fb.gif)

**Comment by owhen** [comment]
Unfortunately, APNGs currently do not work under Firefox in Mastodon.

**Comment by patf** [comment]
Firefox supports APNG, Edge is the only mainstream browser without APNG support.

Note that emojis are affected by the "Auto-play animated GIFs" setting and won't be animated if that's disabled. (Unlike regular GIFs in posts, there's no way to start playback either.)

**Comment by owhen** [comment]
Yes, Firefox supports APNG, but on Mastodon, the APNGs in Toots are not animated, just static. Chrome is fine. In general, APNG works in Firefox, but not in Mastodon.

**Comment by patf** [comment]
They work fine here (Firefox 58, macOS). Are you sure your "Auto-play animated GIFs" setting in Mastodon is on?

**Comment by owhen** [comment]
Closed all tabs and did a restart of Firefox. Now it works fine in FF.

**Comment by Dhyfer1** [comment]
![nope1.png](https://github.com/user-attachments/assets/771f22ed-3f4a-4825-8772-416b7cb8afe6)
