### ISSUE TITLE
Support toots starting with #me

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6696]
E.g.

```
#me cleans the fridge
```

It should be parsed like an IRC /me, i.e. it should turn the toot into an action-toot.

Unresolved questions:

- [ ] What should an action toot look like?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
???

**Comment by SoniEx2** [comment]
Remember that one time I also suggested `#cw`?

E.g.

```
lewd #cw I like to be lewd
```

Which would automatically add a content warning with everything before the `#cw`, and toot content with everything after the `#cw`?

`#me` is basically the same but it must come at the start of a toot and turns the toot into an action-toot. (Or we could use `@me` and make that a reserved username. (well, semi-reserved. use `@me@instance` in your own instance to refer to it, I guess.))

**Comment by m4sk1n** [comment]
![me](https://user-images.githubusercontent.com/21127288/37159086-d29c89ac-22e4-11e8-9970-efc296ee1de9.png)
something like this, but looking better?

**Comment by SoniEx2** [comment]
I don't know?

it should still show up on ppl's home feeds.

I have never seen what you're talking about. is that a mastodon-core feature?

**Comment by m4sk1n** [comment]
No, there is no feature like this

**Comment by SoniEx2** [comment]
I mean it looks neat I guess?

**Comment by m4sk1n** [comment]
I don’t think it would be very useful, but it seems to be pretty easy to implement

**Comment by jebuskrust** [comment]
I'd support statuses that can be defined with different status_type if that's what you're implying? 

A shortcut key or added menu around the toot box with status_type options (ie: toot (default), action, notice, etc) when selected which would allow the "whats on your mind text box area" to function differently every time a toot was sent. Hell you could even change the color of the toot box too.. And do pretty amazing things with it within the different timeline types.

Your thought process of adding a #tag isnt the best approach honestly as this information is stored in a text field. There's really no reason to have this information stored within the text column within a submitted status, it ruins the purpose of the column itself and would make it fairly hard to migrate existing data that are marked should a status_type were ever  to be added to the model. 

Presently the model DOESNT allow the storing of statuses with a given status_type within the database model though. This is a really good idea. However, If anything, this feature request should be named around the following instead:  "Add status_type to statuses table with default value 0 to allow us to properly define statuses as normal toots, actions, notices, etc"

That way in the future at least the model will be prepared for it and it wont be a pain in the rear to ever implement.  I could see potential of the timeline getting very colorful, if something like this were ever implemented.

**Comment by SoniEx2** [comment]
SUPPORT TAGS AS AN (ADDITIONAL) ACCESSIBILITY FEATURE

**Comment by Gargron** [comment]
Mastodon is not an instant messaging chat application, such messages are completely out of scope of the project.

**Comment by jebuskrust** [comment]
Bummer ¯\_(ツ)_/¯
