### ISSUE TITLE
chromium browser just nets you a big empty page

### ISSUE THREAD

**Issue by hi-cial** [tootsuite/mastodon#6700]
this issue just started in the last week, so it must have been a recent update to masto which caused it. chromium, in its previous and latest builds, no longer loads anything but the background default colours for mastodon. chrome works just fine, which really puzzles me. if i check the source it appears to be -trying- to load the page saying i need to enable javascript, but the text never actually loads onto the page and javascript is, needless to say, already enabled. 

not a coder so i haven't the foggiest idea what is causing this but it seems like a rather large issue if an entire browser is a no-show for all of masto!!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Could this have been fixed by #6697?

**Comment by hi-cial** [comment]
i don't know, because as i said i am not a coder. i'm not sure how to implement that fix myself, i just know that Something Is Broken.

**Comment by Gargron** [comment]
Haven't heard anything else about this since so assuming it's been resolved

**Comment by bibinisacmohan** [comment]
This is still an open issue. Chromium-based browsers show a blank page with only the background color. iOS apps and Safari work fine.
