### ISSUE TITLE
http://joinmastodon.org/ns# returns 404

### ISSUE THREAD

**Issue by hstove** [tootsuite/mastodon#6704]
I'm learning about ActivityPub, and have been looking through how Mastodon exposes it. In the context for most AP pages, there are a few properties in the `toot` namespace:

~~~json
{
"toot": "http://joinmastodon.org/ns#",
"Emoji": "toot:Emoji",
"focalPoint": {
  "@container": "@list",
  "@id": "toot:focalPoint"
},
"featured": "toot:featured"
}
~~~

But http://joinmastodon.org/ns returns a 404. I don't think anything is broken, but I figured I'd bring it up. Thanks for the amazing project!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
As you can see the entire context is currently inlined. The URI is just a namespace.

**Comment by hstove** [comment]
I see, thats very clear. Thanks!
