### ISSUE TITLE
YouTube embed not worked

### ISSUE THREAD

**Issue by mimikun** [tootsuite/mastodon#6721]
Yesterday,  my mastodon instance was updated v2.3.0.
But YouTube embed is  not working.
niconico, Twitch, SoundCloud and Vimeo embed is working.

This is bug? or my instance issue?

### My Instance Environment:
- Using Docker
- Mastodon v2.3.0
- Media Storage is Amazon S3
- MAX_CHAR 5000
- media file size 20MB

### Comparing changes
https://github.com/tootsuite/mastodon/compare/master...mimikun:mimikun/master

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by TrollDecker** [comment]
Might want to define "not working"?

Embeds were changed in this release as a privacy protection (embeds tend to carry a bit of tracking crud), so that the embedded object isn't immediately embedded into the toot. Rather, you now have to click the box/card/whatever it's called to bring the embed up.

**Comment by mimikun** [comment]
Current situation ↓

### My Instance
![Toot look image](https://s3-ap-northeast-1.amazonaws.com/mstdn.mimikun.jp/media_attachments/files/000/038/374/original/debf6efae5d77db4.png)

[Toot URL](https://mstdn.mimikun.jp/@mimikun/99659194074068343)

### mastodon.social
![Toot look image](https://s3-ap-northeast-1.amazonaws.com/mstdn.mimikun.jp/media_attachments/files/000/038/373/original/a5744f30565331c3.png)

[Toot URL](https://mastodon.social/@mimikun/99659200653053846)

My instance is not display "start" button and thumbnail image.

I want to display "start" button and thumbnail image like mastodon.social in my instance.

**Comment by Gargron** [comment]
Are you sure you have precompiled the assets after update? Maybe it's outdated JS.

**Comment by mimikun** [comment]
I did it ↓

```
$ sudo docker-compose build
$ sudo docker-compose run --rm web rails db:migrate
$ sudo docker-compose run --rm web rails assets:precompile
$ sudo docker-compose up -d
```

But not display "Play Start" button and thumbnail.

![image](https://s3-ap-northeast-1.amazonaws.com/mstdn.mimikun.jp/media_attachments/files/000/038/960/original/efe8f67154e83a77.png)

URL: https://mstdn.mimikun.jp/@mimikun/99663361683332356

**Comment by unarist** [comment]
I and mimikun tried to get detailed logs of this issue. Here is some of log from FetchLinkCardService:

```
[httplog] Sending: HEAD https://www.youtube.com/watch?v=HljJvwifETg
[httplog] Data: #<HTTP::Request::Body:0x000055595d9dd210>
[httplog] Connecting: www.youtube.com:443
[httplog] Status: 302
[httplog] Benchmark: 0.108238 seconds
[httplog] Response:

[httplog] Sending: HEAD https://m.youtube.com/watch?v=HljJvwifETg
[httplog] Data: #<HTTP::Request::Body:0x000055595d9dd210>
[httplog] Connecting: m.youtube.com:443
[httplog] Status: 200
[httplog] Benchmark: 0.405615 seconds
[httplog] Response:

[httplog] Sending: GET https://www.youtube.com/watch?v=HljJvwifETg
[httplog] Data: #<HTTP::Request::Body:0x000055595daa4ea0>
[httplog] Connecting: www.youtube.com:443
[httplog] Status: 302
[httplog] Benchmark: 0.093512 seconds
[httplog] Response:

[httplog] Sending: GET https://m.youtube.com/watch?v=HljJvwifETg
[httplog] Data: #<HTTP::Request::Body:0x000055595daa4ea0>
[httplog] Connecting: m.youtube.com:443
[httplog] Status: 200
[httplog] Benchmark: 0.429054 seconds
[httplog] Response:

(snip)
```

It seems to be redirected to mobile version of YouTube, which doesn't offer oEmbed nor og information 😕

**Comment by Gargron** [comment]
Then why do embeds still work on mastodon.social?

**Comment by ykzts** [comment]
```console
$ curl -sS -I -A "http.rb/2 (Mastodon/2.3.0; +https://mastodon.social/)" https://www.youtube.com/watch?v=oqvRGBB2bsM | grep -i Location
$ curl -sS -I -A "http.rb/2 (Mastodon/2.3.0; +https://mstdn.mimikun.jp/)" https://www.youtube.com/watch?v=oqvRGBB2bsM | grep -i Location
location: https://m.youtube.com/watch?v=oqvRGBB2bsM
```

...? 🤔

**Comment by ykzts** [comment]
```console
$ curl -sS -I -A "ikun" https://www.youtube.com/watch?v=oqvRGBB2bsM | grep -i Location
location: https://m.youtube.com/watch?v=oqvRGBB2bsM
```

🤔

**Comment by unarist** [comment]
```
$ curl -sS -I -A "kun" https://www.youtube.com/watch?v=oqvRGBB2bsM | grep -i Location
location: https://m.youtube.com/watch?v=oqvRGBB2bsM
```

https://developers.whatismybrowser.com/useragents/parse/379735-samsung-sm-b510k

> Mozilla/4.0 (compatible; KUN/3.1.1; SM-B510K; CellPhone; Profile/1.0)

and...

```
$ curl -sS -I -A "http.rb/2 (Mastodon/2.3.0; +https://androidon.example.com/)" https://www.youtube.com/watch?v=oqvRGBB2bsM | grep -i Location
Location: https://m.youtube.com/watch?v=oqvRGBB2bsM
$ curl -sS -I -A "android" https://www.youtube.com/watch?v=oqvRGBB2bsM | grep -i Location
Location: https://m.youtube.com/watch?v=oqvRGBB2bsM
```

**Comment by nightpool** [comment]
😭 youtube pls

**Comment by Gargron** [comment]
:man_facepalming:
