### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by taoeffect** [tootsuite/mastodon#674]
Hey Eugen,

Thank you for your incredible work on Mastodon. Of all the federated twitter implementations out there, this is by far the most impressive one that I've come across.

If you ever run into any technical/systems/design related issue and need to brainstorm a solution to some challenge, just let me know and I'd be happy to do what I can to help.

Cheers,
[Greg](https://mastodon.social/users/taoeffect)

**Comment by Gargron** [comment]
Thanks for the kind words!
