### ISSUE TITLE
GnuSocial-Feeds don't get fetched

### ISSUE THREAD

**Issue by scroom** [tootsuite/mastodon#6744]
Today I noticed by a user of my instance that apparently the feeds of GnuSocial instance users are not loaded. Check out some examples I've illustrated with photos below. My instance is running the latest Mastodon-Version 2.3.

1. example: @faznet@gnusocial.de
![bildschirmfoto vom 2018-03-11 17-01-43](https://user-images.githubusercontent.com/5347731/37255525-06b3d09a-254e-11e8-9f2d-1cb45f842a4e.png)
![bildschirmfoto vom 2018-03-11 17-03-08](https://user-images.githubusercontent.com/5347731/37255531-18fb2ba4-254e-11e8-9472-01aa65c15129.png)

2. example: @duesselblog@quitter.se
![bildschirmfoto vom 2018-03-11 17-04-14](https://user-images.githubusercontent.com/5347731/37255543-476ff3e8-254e-11e8-86d9-9f177a1360ee.png)
![bildschirmfoto vom 2018-03-11 17-04-26](https://user-images.githubusercontent.com/5347731/37255545-4c1d5566-254e-11e8-9880-d19905cec31e.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by renatolond** [comment]
Just to make sure, they were already being followed by users on your instance?
I follow a couple of gnusocial users and they appear normally. (on 2.3.1)
But there's no "initial fetch", if you start following a user that was not being followed before, you don't get older posts.

**Comment by nightpool** [comment]
I can't reproduce this on cybrespace either.

**Comment by scroom** [comment]
There are some gnusocial-users where following seems to work. But other don't. The above mentioned account @faznet@gnusocial.de don't get fetched on my instance mastodonten.de (on which I'm the admin and which is running Mastodon 2.3.1).

**Comment by scroom** [comment]
@renatolond @nightpool Does fetching of the mentioned accounts work for you on your instance?

**Comment by renatolond** [comment]
I tried fetching the faznet account and two of their posts and both seem to work here:
![image](https://user-images.githubusercontent.com/173791/37670534-dab04460-2c69-11e8-8396-8c1ff1f86e38.png)

Also tried to fetch only dusselblog and it seems to work as well:
![image](https://user-images.githubusercontent.com/173791/37670603-ffe63e60-2c69-11e8-96c3-ed2649bd8f1d.png)

**Comment by nightpool** [comment]
@renatolond did you try subscribing to them?

@scroom i can confirm something about subscribing to faznet@gnusocial.de doesn't work. Do you know what version of GNU Social gnusocial.de is using?

**Comment by renatolond** [comment]
I tried for both now, I saw that on my sidekiq there's error for duesselblog:

```
Mastodon::UnexpectedResponseError: Subscribe failed for duesselblog@quitter.se: https://quitter.se/main/push/hub returned code 500
```

I don't see anything about faznet, but I haven't got the update that they posted after I followed either

**Comment by renatolond** [comment]
Today I got a post back from duesselblog, still nothing on faznet though.

![image](https://user-images.githubusercontent.com/173791/37703940-a5bfe16e-2cf7-11e8-85d0-4814475e51ae.png)
