### ISSUE TITLE
Prevent OAuth redirect uri from being added to browser's history

### ISSUE THREAD

**Issue by spaceottercode** [tootsuite/mastodon#6749]
This may be a Doorkeeper issue and if so, please close, but just in case there's some obscure feature in doorkeeper initializers file: Is it possible to prevent the redirect URI from being added to the browser's history, kinda like a Location.replace()?

not super critical. partly mitigated by the fact that authorization codes included in certain redirects are only valid for 10 minutes...but I need to check whether doorkeeper implements the SHOULD portion in the following statement:

> If an authorization code is used more than
         once, the authorization server MUST deny the request and SHOULD
         revoke (when possible) all tokens previously issued based on
         that authorization code.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
What does adding it to the browser's history have anything to do with the SHOULD statement you mention?

**Comment by spaceottercode** [comment]
@nightpool It's twofold. 

1. Ideally because the redirect contains sensitive data, it's probably best not to have it saved in history. 
2. if the reuse of an authorization code is grounds to revoke an existing access token, which I understand the motive behind doing so, it might be best to keep it off the records. But I don't know if doorkeeper follows the suggestion: its optional. (If implemented, I'm assuming this is enforced only while the authorization code is still valid).

I'm not sure this is a concern or not; just thought I suggest the option. 

Thank you for asking.
