### ISSUE TITLE
Can you make the blocks moveable?

### ISSUE THREAD

**Issue by nicubuga** [tootsuite/mastodon#6755]
Hi, wouldn't it be more comfortable to move the blocks inside as you like to see the information?

**Comment by nightpool** [comment]
I don't understand what this issue means, could you try explaining it in
another way, or use screenshots?

**Comment by nicubuga** [comment]
https://cdn.vox-cdn.com/thumbor/_QWCtxXuIU3WPr4sqtheYLQgfa4=/0x0:1948x1098/1200x800/filters:focal(0x124:310x434)/cdn.vox-cdn.com/uploads/chorus_image/image/54068551/Screen_Shot_2017_04_04_at_8.10.30_AM4_4.0.png

What if I want to move the 'Notifications' block next to my text input block and my 'Home' block to be my third block?

**Comment by trwnh** [comment]
@nicubuga Like this. Click the column settings icon, then click the arrows.
![image](https://user-images.githubusercontent.com/10606431/37316110-3d232f44-262b-11e8-9297-6a0fa37bb652.png)

**Comment by nightpool** [comment]
yep! this is a thing you can already do in mastodon.

**Comment by nicubuga** [comment]
Ah sorry, somehow I missed the arrows... thx!
