### ISSUE TITLE
Account archive can get stuck, preventing new archive attempts

### ISSUE THREAD

**Issue by timmc** [tootsuite/mastodon#6765]
I attempted to use the "Request my archive" feature on the Data Export settings tab. The button was replaced by a table with headings "Date" and "Size", with one row saying "Compiling your archive...". And there it sat for at least 70 hours.

I don't have a huge amount of uploaded media (less than 10 MB) or a massive number of toots, so it definitely should have finished even if such requests are only processed once per day.

I've poked the instance admin, who didn't see anything wrong, but I figured I'd file a ticket too in case there's anything that would be helpful for debugging. (Also, if anyone has suggestions on how to recover from a situation like this, since there's now no way for me to request another archive.)

This happened on v2.3.0. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by danhunsaker** [comment]
I managed to use `rails c` to manually restart the BackupWorker for the incomplete tasks, but still no signs regarding why they failed to complete in the first place (there were two backups in this state before I restarted the tasks).

**Comment by timmc** [comment]
Thanks, @Gargron! #6769 sounds like it will help in the future, and it looks like admins are able to fix a broken export (thanks Dan!) so I think this issue is closeable (unless someone thinks there's more work to do on it.)

**Comment by SinaCutie** [comment]
@danhunsaker How did you fix this with `rails c` ? A user of my instance is currently experiencing this problem.

**Comment by nightpool** [comment]
that will re-build *all* backups

**Comment by nightpool** [comment]
(closing since this is fixed in master, you just have to wait for retries to expire)
