### ISSUE TITLE
No javascript option?

### ISSUE THREAD

**Issue by transifex3** [tootsuite/mastodon#677]
Is there any options to use maastodon without javascript?

> I want to read the strem with a normal, static page. I want to be able to permanently link to the current point of the stream I am at any moment, but must stop reading - and want to be able to continue from this exact point next time I access it, without needing to search for it, possible in a loooooong and too big page of newer posts.

This is exactly what i searching for! Any options for this?

**Comment by Gargron** [comment]
The main web UI is a JavaScript-based app. The main way to access content is over the API. You can use apps that aren't based on JavaScript (e.g. native mobile apps, command-line based apps (e.g. tootstream), or make your own).

**Comment by transifex3** [comment]
Thanks for answering @Gargron.
Then it can be only made by Native Apps, not non-javascript webpage for now. am i understood right? :disappointed:

**Comment by mitchellurgero** [comment]
If someone made a webapp that did not use javascript that would be possible. But why would you want to...?

**Comment by mitchellurgero** [comment]
I believe you can read a toot stream via conversations (E.G User1 & User2 are tooting back and forth. and that can be linked to.)

**Comment by gouessej** [comment]
It's doable with non-javascript webpages but far from being trivial to implement, Discourse does something similar.
