### ISSUE TITLE
The "do not auto-insert media URL into text" fix doesn't quite work

### ISSUE THREAD

**Issue by jpdeplaix** [tootsuite/mastodon#6776]
Since #6672, Mastodon (and thus glitch-soc) is not supposed to display media URLs. However this doesn't work every time and I'm not sure what makes it work and what doesn't. My only guess right now is that it depends on users.

Is there any clue of how the patch is suppose to work (or not work if it's the case) ?
More details on: https://github.com/glitch-soc/mastodon/issues/381 (the issue have been reproduced with mainline Mastodon so it's not a glitch-soc issue)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
What doesn't work? You see URLs? Apps might still be inserting them. Toot won't get accepted without anything in the text? Might be app's validation.

**Comment by jpdeplaix** [comment]
Ok, turns out I didn't understood what #6672 did. I thought it was about removing the url for all toots afterwards and not removing the urls when actually creating the toot.

Sorry for the noise :/
