### ISSUE TITLE
Alternate domains miss assets

### ISSUE THREAD

**Issue by kkretsch** [tootsuite/mastodon#6781]
The current 2.3.1 version has a problem when I access the alternate domain as an anonymous guest.
Nearly all assets return an 404 error.
If I access the main domain as a guest it works as expected.

I think the 2.3.0 version had at least the main functionality working, but I did miss there my hero-imgae on the top of the about page on the alternate domain. So even there it wasn't fully working.

I did run the precompile updated assets command and restarted all mastodon jobs. It seems not to update the alternate domain asset links somewhere.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
What are you calling alternate domain?

**Comment by kkretsch** [comment]
I mean the setting within the .env.production config file **ALTERNATE_DOMAIN**, where I defined an additional domain name.

**Comment by kkretsch** [comment]
I solved it via nginx. There was some nasty error hidden within my secondary configuration.
