### ISSUE TITLE
Saw-toothed UI part below the text box doesn't shrink with elephant. 

### ISSUE THREAD

**Issue by erdmaennchen1** [tootsuite/mastodon#6783]
The elephant shrinks the right way but the saw-toothed thing doubles and doesn't shrink the right way. 

![screenshot_2018-03-14_11-00-16](https://user-images.githubusercontent.com/37367354/37396805-41e04ec2-277a-11e8-8684-360250065394.png)
![screenshot_2018-03-14_11-00-38](https://user-images.githubusercontent.com/37367354/37396819-44a2d65c-277a-11e8-9850-4a765a444182.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases/tag/v2.3.1) and not on `master` (If you're a user, don't worry about this).

**Comment by m4sk1n** [comment]
Could you provide information about your browser, operating system screen resolution and Mastodon instance version?

**Comment by erdmaennchen1** [comment]
58.0.2 (64-bit) Firefox Quantum, 
Manjaro 17.1, Xfce 4.12 
Screen resolution bug on both 1377x768 and 1680x1050 
My Instance is running: https://github.com/tootsuite/mastodon/releases/tag/v2.3.1
