### ISSUE TITLE
Cannot set the interface to Portuguese only

### ISSUE THREAD

**Issue by pmarquesmota** [tootsuite/mastodon#6784]
http://masto.pt is a Portuguese only instance. However, as far as we can see, there is no way to lock the interface to Portuguese. The screenshot below  show the problem: coming from France with a french browser, I see a french interface around the instance description which says it is for Portuguese speakers.

![masto.pt screenshot](https://user-images.githubusercontent.com/25176232/37427259-27e7f3d6-27c9-11e8-9f24-7bf0b5731ad6.png)

Actually, since mastodon is translated into about 37 languages and dialects, it means our lone admin is supposed to somehow understand them in case a problem with a foreign user arise, which is not practical on such a small instance.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
use [`DEFAULT_LOCALE`](https://github.com/tootsuite/mastodon/blob/v2.3.1/.env.production.sample#L58-L59).

**Comment by hugogameiro** [comment]
[Masto.pt](Masto.pt) has always had `DEFAULT_LOCALE=pt` set. The point he is making is that if you set `DEFAULT_LOCALE` to a language it is not forced by default, it will assume the language of the browser. Another example that also has `DEFAULT_LOCALE` and that will make the issue more obvious: [persadon.com](persadon.com)
What is suggested here is that, if `DEFAULT_LOCALE` is set, the instance should always default/force that language on all pages.

**Comment by ykzts** [comment]
hm

**Comment by nightpool** [comment]
so you're saying that instead of a default, we should allow admins to
disable localization completely? I don't think this is something mastodon
should implement.

**Comment by hugogameiro** [comment]
I agree with @pmarquesmota on this issue. What is the point of `DEFAULT_LOCALE` if you set it and visitors don't see the language that you set there? 

I agree that if you don't set `DEFAULT_LOCALE` the current behaviour could be useful but when it is set I expect the software to return the set language only and ignore the browser language because I said that I wanted that to be my DEFAULT_LOCALE, no?
