### ISSUE TITLE
Edge case: "regeneration indicator" has different heights for missing statuses/accounts

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#6786]
When attempting to load an invalid account:
![image](https://user-images.githubusercontent.com/10606431/37441073-89d85b0e-27cd-11e8-91ad-26d79cbf17b9.png)

When attempting to load an invalid status:
![image](https://user-images.githubusercontent.com/10606431/37441107-bd94d7f6-27cd-11e8-8b57-c5cd50cc5739.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
After some more testing: it seems that the bug is an artifact of using div.scrollable and div.item-list on the /accounts error (which demonstrates this issue), but not on any other error (which load fine). Removing those two divs (.scrollable and .item-list) in Firefox's HTML editor fixes the issue.

**Comment by trwnh** [comment]
Narrowed it down to inconsistent usage of MissingIndicator as defined in https://github.com/tootsuite/mastodon/blob/995f8b389a66ab76ec92d9a240de376f1fc13a38/app/javascript/mastodon/components/missing_indicator.js

`null` status works fine: https://github.com/tootsuite/mastodon/blob/800325f452200902995602ff441e2f84f684e90a/app/javascript/mastodon/features/status/index.js#L380-L387

`false` list does not: https://github.com/tootsuite/mastodon/blob/66dbb59aa16981643e3bfa3f94d441bc3166eab3/app/javascript/mastodon/features/list_timeline/index.js#L121-L137

**Comment by trwnh** [comment]
Visual summary:

x | Status | List | Account

Default | ![image](https://user-images.githubusercontent.com/10606431/44812649-6c4cfc80-ab9d-11e8-9cc1-c9f19aee5cf5.png) | ![image](https://user-images.githubusercontent.com/10606431/44812680-87b80780-ab9d-11e8-9cbb-27f25819d80e.png) | ![image](https://user-images.githubusercontent.com/10606431/44812698-94d4f680-ab9d-11e8-93dc-a50235d2a4cd.png)
With CSS theme | ![image](https://user-images.githubusercontent.com/10606431/44812720-a8805d00-ab9d-11e8-81aa-36c1758c11fd.png)| ![image](https://user-images.githubusercontent.com/10606431/44812736-b33af200-ab9d-11e8-8248-af9b7115d213.png) | 
![image](https://user-images.githubusercontent.com/10606431/44812755-be8e1d80-ab9d-11e8-81d3-cb5a0b488314.png)

**Comment by trwnh** [comment]
Now that #8523 has been merged:

x | Status | List | Account
--- | --- | --- | ---
Default | ![image](https://user-images.githubusercontent.com/10606431/44812649-6c4cfc80-ab9d-11e8-9cc1-c9f19aee5cf5.png) | ![image](https://user-images.githubusercontent.com/10606431/44812649-6c4cfc80-ab9d-11e8-9cc1-c9f19aee5cf5.png) | ![image](https://user-images.githubusercontent.com/10606431/44812698-94d4f680-ab9d-11e8-93dc-a50235d2a4cd.png)
With CSS theme | ![image](https://user-images.githubusercontent.com/10606431/44812720-a8805d00-ab9d-11e8-81aa-36c1758c11fd.png) | ![image](https://user-images.githubusercontent.com/10606431/44812720-a8805d00-ab9d-11e8-81aa-36c1758c11fd.png) | ![image](https://user-images.githubusercontent.com/10606431/44812755-be8e1d80-ab9d-11e8-81d3-cb5a0b488314.png)

**Comment by trwnh** [comment]
Possibly due to #12084 (but I'm not sure, as I don't know what commit mastodon.social is running right now), the mascot and error message are finally centered in all 3 cases of status/list/account, except the "invalid account" case has no Back button as a header.

**Comment by Gargron** [comment]
@trwnh Yes, I think so
