### ISSUE TITLE
Idea: Register URL handlers for custom protocols

### ISSUE THREAD

**Issue by ted-gould** [tootsuite/mastodon#6795]
One issue that federation has is that when as user is on webpages from other Mastodon instances executing something on my instance. It makes it hard to have a "share on Mastodon" link or interact with other posts when finding them by URL. What I think might be a solution for that would be to register a protocol handler for a mastodon specific protocol.

So for example my Mastodon instance would register "mastodon-like://" to go to "https://social.gould.cx/like-url". Then a webpage would have a "mastodon-like://mylocalid" which would redirect to my instance of Mastodon which assumingly I'd be logged into. It would reduce the friction of liking various posts throughout the web.

Besides liking I think this could benefit sharing and following as well.

**Comment by nightpool** [comment]
we already do this, we just haven't implemented it for a ton of things due
to interoperability concerns and practical ux concerns around protocol
handlers in modern browsers

**Comment by ted-gould** [comment]
Ah, cool! Is there a way I can opt-in to use it? I don't recall getting prompted by my browser to install the handlers.

**Comment by nightpool** [comment]
The handlers are hidden somewhere in your browser's UI, it depends on whether you're using Firefox or Chrome. They should prompt you by default.

see also #4511

(right now they're not used in the mastodon UI, they're for third party follow + share buttons for, e.g. websites or similar)

**Comment by Gargron** [comment]
Yeah this is already a thing but browser UI for them is horrible right now so we don't advertise them too much...
