### ISSUE TITLE
Would you think focusing on personal pages is the way to go forward?

### ISSUE THREAD

**Issue by nicubuga** [tootsuite/mastodon#6797]
Comparing to the popularity of Twitter, to me, it is the thing that signals me the most that the basic view of personal pages is what throws Mastodon backwards. Should personal pages be more sophisticated somehow?
![screenshot-2018-03-16_20 14 21](https://user-images.githubusercontent.com/7693656/37534747-aff49aca-2956-11e8-8700-3f99baaed059.png)

**Comment by trwnh** [comment]
> Should personal pages be more sophisticated somehow?

Maybe, but how so?
