### ISSUE TITLE
Probably not enough entropy in data export tarball links

### ISSUE THREAD

**Issue by timmc** [tootsuite/mastodon#6798]
When a user is given a link to their backup, it takes the form of something like `https://s3.amazonaws.com/my-instance-bucket/backups/dumps/NNN/NNN/NNN/original/archive-YYYYmmddHHMMSS-RRRR.tar.gz`, where `NNN/NNN/NNN` appears to be a counter (of backups), `YYYYmmddHHMMSS` is of course a timestamp in seconds, and `RRRR` is random hexadecimal. No authentication is required in order to access this URL. The backup contains non-public information, including a private key of some sort, so having sufficient entropy in the URL is quite important.

My concern is that this is insufficient entropy, although *probably* enough that this does not need to be discussed under security embargo. 

An attacker who wants to retrieve *any* user's backup (not targeting a specific user's backup) could likely make two requests in a short window of time, from separate accounts on the same instance (to work around the 7 day waiting period between backups), and from there triangulate on a counter and timestamp of any other user's archive that finished in that time window. (The attacker could increase probability of a hit by putting out a PSA about remembering to export one's data.)

If the time window were 10 minutes and the attacker observes the counter increment by 2, there is one other user's backup in that window, so the counter contributes no entropy. The timestamp has 600 possible values (1.15 bytes' worth) and the random value has 65536, for a total of 39 million possibilities. One hundred computers asking 10 times per second would need 10 hours to find the winning combination.

This attack would *not* be visible to the Mastodon instance owner, since it would be hitting S3.

I think this could be resolved by simply adding more random hex; [currently](https://github.com/tootsuite/mastodon/blob/61ed133fea80041b354c78b043cec72dd8644101/app/services/backup_service.rb#L52) the backup service appends 2 bytes (4 hex) to the tarball's base name, but it could just as well add 16 bytes (32 hex).

Ideally, the export file would not even be accessible by a direct link, and the Mastodon instance would instead generate a signed S3 URL when the Data Export page shows the download link.

For *existing* tarballs, there are a couple options: 1) Next Mastodon version deletes all existing (low-entropy) data export tarballs; 2) contact all admins and suggest they delete old tarballs; 3) let the tarballs expire, if that's a thing they do. (And if they don't, adding this would very much improve security.) Or some combination.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by SoniEx2** [comment]
Why not client-side decryption (if JS is available) or manual decryption (if JS is not available)?

**Comment by nightpool** [comment]
I think increasing the byte value here is the easiest fix + a no brainer. Archives expire within 7 days so i'm not super worried about the existing tarballs.

In the future you can report security issues either by PM to me (@nightpool@cybre.space) or gargron (@gargron@mastodon.social), or another maintainer, or by email to eugen@zeonfederated.com.

**Comment by timmc** [comment]
Ah, good to hear about the 7 day expiry.

It would be great to have security contact info listed somewhere. In this case, I did contact Gargron by PM and he didn't seem too worried, and did not offer guidance on public ticket vs. closed discussion. After some discussion with other folks I determined that, while marginal, there was probably enough entropy in the existing filenames to not warrant a closed discussion.

**Comment by nightpool** [comment]
@timmc yeah i don't think there was any real harm done by having this as an open discussion, just leaving it here for potential future issues.

**Comment by Gargron** [comment]
For reference, my e-mail is listed on https://mastodon.social/about/more and my GPG key is available on https://zeonfederated.com, so if someone needs to send me an encrypted e-mail, they can. After the DM discussion I did not consider this a serious security issue.
