### ISSUE TITLE
docker-compose build failed

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#6809]
```
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "node-gyp@3.6.2" with binaries:
      - node-gyp
[6/6] Cleaning modules...
error An unexpected error occurred: "ENOENT: no such file or directory, open '/usr/local/share/.config/yarn/global/.yarnclean'".
info If you think this is a bug, please open a bug report with the information provided in "/usr/local/share/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'sidekiq_push' failed to build: The command '/bin/sh -c bundle config build.nokogiri --with-iconv-lib=/usr/local/lib --with-iconv-include=/usr/local/include  && bundle install -j$(getconf _NPROCESSORS_ONLN) --deployment --without test development  && yarn --pure-lockfile  && yarn cache clean' returned a non-zero code: 1
```

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Looking into it right now.

**Comment by tateisu** [comment]
I've tryed on 2 instance from tags/v2.3.2rc1 , both failed.

**Comment by Moskito99** [comment]
Yepp! Same for me. Does not build....

**Comment by Gargron** [comment]
The cause is unclear but I'm testing a fix right now

**Comment by akihikodaki** [comment]
I investigated this issue and found yarn changes `config.cwd` to `/usr/local/share/.config/yarn/global/.yarnclean` in `init` method of `PackageInstallScripts` if `npm` is not present. However I'm still not sure why.
`git` is added to the image but apparently it is not related.
