### ISSUE TITLE
Net::LDAP::Error (SSL_connect SYSCALL returned=5 errno=0 state=error: certificate verify failed)

### ISSUE THREAD

**Issue by tigre-bleu** [tootsuite/mastodon#6816]
I try to deploy Mastodon 2.3.1 with LDAP support authenticating to a Zimbra server with self-signed certificates.

At first I got the following error:

`Net::LDAP::Error (SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain))`

Then as explained in the tutorial regarding LDAP authentification, I uploaded the CA certificate to the server running mastodon (Debian Stretch) and ran update-ca-certificates. Now I have the following error:

`Net::LDAP::Error (SSL_connect SYSCALL returned=5 errno=0 state=error: certificate verify failed)`

I can't figure what is wrong...

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tigre-bleu** [comment]
There is a dirty workaround for this issue which disables SSL Verification

in lib/devise/ldap_authenticatable.rb change line 18 to;

`tls_options: { verify_mode: OpenSSL::SSL::VERIFY_NONE   },`

maybe that could be mapped to an option in the .env.production file.

**Comment by vinod-1** [comment]
I'm already using this latest code, still when I am trying to authenticate, I do get the following error. Can somebody help out? @Gargron @imbsky 

Net::LDAP::Error - SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate):
lib/devise/ldap_authenticatable.rb:29:in `authenticate!'
app/controllers/concerns/localized.rb:14:in `set_locale'

**Comment by vinod-1** [comment]
> I'm already using this latest code, still when I am trying to authenticate, I do get the following error. Can somebody help out? @Gargron @imbsky
> 
> Net::LDAP::Error - SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate):
> lib/devise/ldap_authenticatable.rb:29:in `authenticate!' app/controllers/concerns/localized.rb:14:in `set_locale'

I don't know if there is an issue or how it should be working. I did the following changes and LDAP started working!

1. Changed line 366 to following in /config/initializers/devise.rb
'''config.ldap_tls_no_verify  = ENV.fetch('LDAP_TLS_NO_VERIFY')'''
2. Added an env variable in .env.production file as follows:
'''LDAP_TLS_NO_VERIFY=true'''
