### ISSUE TITLE
Add CWs to notification emails

### ISSUE THREAD

**Issue by rixx** [tootsuite/mastodon#6824]
In notification emails (at least for mentions, but I suspect for all notifications), Content Warnings are omitted entirely, leading to a lack of warning and context both.

I suggest to add the CW highly visible and add the remaining toot text a bit further below. (`----` separator for plain text maybe). Please keep including the regular toot text – just prefixed with the CW.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
Fixed by https://github.com/tootsuite/mastodon/pull/6832
