### ISSUE TITLE
Video modal scaling

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#6846]
See thread: https://chitter.xyz/@puppy/99716551539346887

The problem seems to be that videos can get bigger than the screen.

Looks like regression introduced in #5956

cc @yuntan 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yuntan** [comment]
I couldn't reproduce the problem.

**Comment by nynhex** [comment]
I've tried to reproduce this as well, so far no luck.

**Comment by Cassolotl** [comment]
This has happened to me but not for a week or two, because I don't watch many videos maybe? If it happens again I'll post here.

**Comment by codl** [comment]
here are [a post with 1080p video](https://chitter.xyz/@codl/99732272618465781) and [a post with a 1080p "gif"](https://chitter.xyz/@codl/99732273611836445) for testing purposes

in my experience these fill the width of the viewport when expanded, cropping out the top and bottom of the video

![sscrot](https://user-images.githubusercontent.com/315139/37819196-e715ceea-2e7c-11e8-9139-ae129fdc7a49.png)
