### ISSUE TITLE
Feature request: share button on toots for sharing toots externally

### ISSUE THREAD

**Issue by cbondurant** [tootsuite/mastodon#6848]
There is a slight issue with the flow of sharing toots at this point in time. The only way to share them with other people is to click on it to open it in the dynamic frame(the one with the menu, i dont know its real name), and then copy-paste the link after it changes.

This causes multiple user experience issues

1. It requires switching contexts from whatever frame you are focusing on, if that frame happens to be the dynamic frame then you then have to press back after sharing

2. It is unintuitive given the fact that there is a single context that most of mastodon works under, it is possible that a user doesn't even know the URL is dynamic to the current context.

3. Having a common operation set to only work through this singular and unintuitive way causes friction every time the user attempts to do it.

4. This lacks allowance for setting specific formats for sharing to other sites. While at the moment this may not be a strong consideration, creating room for the feature might be worth considering.

5. Also a consideration that might or might not be needed: this also does not allow for a shortened sharing link. like the difference between a youtube.com/watch?v=XXXXXXXXXXX link and a youtu.be/XXXXXXXXXXX link. 

We have a feature that is like this but is much less generally useful, the embed option.

I think the best solution to this would be to expand the embed menu to contain a more generalized "share" menu, that would have options such as sharing the link directly vs embedding it, CW settings for Open Graph, which could help with the recent feature issue about the Open Graph CW system, etc.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by codl** [comment]
note that right clicking on the timestamp of a status and copying link address will give you a permalink to the status

+1 on adding a generic "share" dialog, the permalink thing is not easily discoverable, and it would help put that opengraph CW mess to rest

there is already a share icon on platforms that support the web share api, maybe this same button could open that generic share dialog on other platforms?

**Comment by Cassolotl** [comment]
>the permalink thing is not easily discoverable

See also: *Copy Link to Toot #7210*

**Comment by mal0ki** [comment]
I understand that right-clicking the time stamp to get the link may be a power user utility. Maybe normal users don't know this. 

Which is why I wont dismiss this issue with suggesting that they use that instead. If we can find a nice way to improve the UI for this part, it is definitely worth investigating. 

Would a small improvement as this help?

> ![image](https://user-images.githubusercontent.com/28316305/39811209-4362b1c4-5388-11e8-986d-74fab879c577.png)
> https://github.com/tootsuite/mastodon/issues/7210#issuecomment-383332029

**Comment by zcdunn** [comment]
I agree the timestamp link is unintuitive and not discoverable. Also, a 3 character link is a small touch target on mobile devices. I think @mal0ki's suggestion would cleanly solve this issue, if the timestamp and icon are wrapped in a single link. This would include the whitespace between them, so the touch target is much easier to hit.

**Comment by mal0ki** [comment]
@zcdunn I didn't even consider the RWA (Responsive Web App), I always use an app on my phone. Okay, makes more sense now :)

**Comment by trwnh** [comment]
There is a dedicated share button on the Mastodon PWA on my mobile device, but not in the tootdeck view. Is this intentional? I feel that simply exposing this button on the wider view would probably solve this issue.

**Comment by zcdunn** [comment]
@trwnh that button is only available on browsers that support the Web Share API. Right now, I think that's just Chrome on Android.

**Comment by Cassolotl** [comment]
See also *URL copy-to-clipboard option in post-menus #680*, which is over a year old.

**Comment by MightyPork** [comment]
@zcdunn Chrome on Linux also supports the share API, but there are no share targets, so the button is entirely useless.

**Comment by crockwave** [comment]
A further improvement to the sharing concept would be the ability to configure a custom sharing URL in preferences, and have a single click custom share of a Toot.  The benefits of a custom sharing URL would allow Mastodon users to:

- Curate toots in their feed
- Efficiently share those toots into a content aggregator site that outputs an RSS feed
- Be able to use Mastodon as a blog site suitable for reading from an RSS reader.  

You could allow a Custom Sharing URL format suitable for generating useful RSS feeds, such as **http://myurl?myparam1=staticvalue&url=${url}&title=${title}&source=${source}&keywords=${hashtags}**

**url** = toot URL
**title** = first encountered bold section of text in the toot
**source** = Mastodon server instance URL or friendly name of instance
**hashtags** = comma delimited list of hashtags in the toot

If a Custom Sharing URL is defined, and the single click Share icon is implemented, then a single click of a Toot would push the useful bits of a Toot into the content aggregator site.

**Comment by crockwave** [comment]
Content curation is the primary use case, where a curator would send selective toots to a remote site.  Subscribers to that content curator's channel would see only the curated toots, along with curated Tweets, FB posts, blog posts, web articles, and the content curator/creator's personally created content, available via RSS feed.  A specific example of this in use is the Feedly Pro web app, where you can share specific articles in your Feedly feed to a custom URL.

**Comment by crockwave** [comment]
If a Custom Sharing icon is added to a Mastodon web app, for Mastodon content curation, when the Custom Sharing icon is clicked, a Title textbox could appear, allowing the content curator to add a Title before hitting the Share button.  That text value would be pushed as the ${title} parameter when sending to the content aggregator's URL.  Same could apply to a description parameter.  The keywords param could simply be the hashtags scraped from the toot.
