### ISSUE TITLE
Node.js uWebSockets binding is not maintained and its source is not available

### ISSUE THREAD

**Issue by akihikodaki** [tootsuite/mastodon#6853]
Node.js uWebSockets binding is not maintained and its source is not available.

https://gitter.im/uWebSockets-chat/Lobby?at=5aa970cd0a1614b7121dd294
> a good status description of the nodejs binding is "now fossilized", I have deleted the sources and won't make any updates (I don't even have access to OS X anymore). C++ version is still around though. I simply have no time to spend on pointless socket.io and similar garbage projects 

\- alexhultman (https://github.com/alexhultman)

Now we need to find an alternative or create a fork. Unfortunately the source code is apparently not available. It was at:
https://github.com/uNetworking/bindings

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by akihikodaki** [comment]
I asked the owner about the binding and according to him, 188485ea2b7a5e6cc060773303bf8fd3724805a3 is the latest commit.
* https://gitter.im/uWebSockets-chat/Lobby?at=5ab222356f8b4b99464fa80f
* https://gitter.im/uWebSockets-chat/Lobby?at=5ab223455f188ccc15dd5a17
* https://gitter.im/uWebSockets-chat/Lobby?at=5ab2235ee4d1c63604243a00

I have confirmed two problems when running uWebSockets here:
* node-gyp replaces header files of OpenSSL and causes binaries built on host computer fails.
* uWebSockets does not check OpenSSL version when choosing a binary (The documentation of Node.js does not say it needs more than checking Node.js ABI version, but apparently OpenSSL version must be checked as well.)

I'm considering about forking.

**Comment by Gargron** [comment]
>I simply have no time to spend on pointless socket.io and similar garbage projects

Damn, that's kind of rude.

I think we'll be fine for a few releases, right? And then we need to find a fork or alternative.

**Comment by akihikodaki** [comment]
> Damn, that's kind of rude.

But you know, maintaining a library with tons of dependent projects is tough, especially when you do no longer have any interest.

> I think we'll be fine for a few releases, right? And then we need to find a fork or alternative.

Yes. However, some Arch Linux (and other edge distribution) users are complaining incompatibility with uWebSockets. For example:
https://discourse.joinmastodon.org/t/streaming-fails-to-start-uws-linux-59-node-undefined-symbol-ssl-library-init/829/13

A procedure to fix the problem may be provided. For the purpose, run:

```
yarn config set nodedir /usr
yarn install --force --pure-lockfile
```

Fortunately dependencies of uWebSockets are only Node.js and OpenSSL. I think it would work on any environment for a while with this fix.

**Comment by ignisf** [comment]
Hey, setting the nodedir and reinstalling the packages no longer works for me on Arch.

**Comment by akihikodaki** [comment]
As Arch Linux links Node.js with OpenSSL 1.0 now (https://bugs.archlinux.org/task/57863), `nodedir` is no longer necessary, and even breaks the configuration. Remove `nodedir` and reinstall the package.

By the way, `uws` repository is now recovered and a new version is released. We should take some time before determining to continue to use or abandon it.

**Comment by ignisf** [comment]
Indeed removing the nodedir setting fixed things here, thanks @akihikodaki!

**Comment by ignisf** [comment]
Well, node 10 I think broke this again on Arch :(

**Comment by akihikodaki** [comment]
It's not a bug. uWebSockets just does not support it yet. Roll back your Node.js installation or install uws in master branch. (Yes, uWebSockets certainly plans Node.js 10 support. We may close this issue soon.)

**Comment by Kjwon15** [comment]
uws cannot be installed on node 10.1.0.
gyp compilation is failed.

**Comment by belohlavek** [comment]
What will be your solution for this? Will you keep the uws frozen forever or are you sacrificing perf? May be another lib I don't know about?

**Comment by aichholzer** [comment]
I have the source. I will try to fork & reboot the module when I find some time. I will keep you posted.

**Comment by geekinaboxx** [comment]
@aichholzer if you're able to share the source, we [@TectonicInteractive](https://github.com/TectonicInteractive) can try to compile it and prepare a package.
