### ISSUE TITLE
Chewy not update elasticsearch index after status posted

### ISSUE THREAD

**Issue by nanjusoil** [tootsuite/mastodon#6854]
As far as I am concerned the elasticsearch index should update automatically after a new status is posted , or do I have to run rake chewy:deploy once a while?

this is my .env.production

**ES_ENABLED=true
ES_HOST=localhost
ES_PORT=9200** 

and I am running under development environment using **foreman start**
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Make sure sidekiq is running. It's updated via sidekiq.

**Comment by nanjusoil** [comment]
I had my sidekiq running
it turns out that my I am  in  development mode  and I had ES_ENABLED set in .env.production
append **ES_ENABLED=true** then **bundle exec rails server** solves the problem
