### ISSUE TITLE
option to hide toots that you have already replied to in notifications

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#686]
i don't quite know how to put it simpler than the title, but i would like to state that it isnt hard to implement on the code side. a simple toggle to hide any posts that have a reply-child in the thread means that you can double check you replied to everything during a busy period, or essentially keep the column smaller to feel less overwhelmed, in case having many notifications is difficult for you

**Comment by hoodiek** [comment]
another user mentioned they would prefer the ability to manually dismiss individual notifications in the notifs column

**Comment by LogicalDash** [comment]
Third option: replying to a notification moves it to the bottom of the column.

**Comment by hoodiek** [comment]
the third option does not make any sense to me, LogicalDash: it just clutters your notifications by reordering them in a unintuitive order, whilst not making it clear you're done with them. i would not advise this option be taken at all.
