### ISSUE TITLE
Url finishing with ... are not linked properly

### ISSUE THREAD

**Issue by lhirlimann** [tootsuite/mastodon#6864]
When typing URL like https://www.hirlimann.net/Ludovic/carnet/?post/2018/03/22/diversifer-les-sources-de-video-sur-Internet-... in messages the link produced points to https://www.hirlimann.net/Ludovic/carnet/?post/2018/03/22/diversifer-les-sources-de-video-sur-Internet- which make these links effective 404.

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
GitHub has the same issue

**Comment by lhirlimann** [comment]
Maybe you are using the same underlying library for URL parsing.

**Comment by Gargron** [comment]
Yes. In general though, URLs should not end in periods, because in human-written text they are likely to appear in sentences and stuff. You should be able to URL-encode such a URL to make it work. I do not feel the need to consider this a bug or in need of fixing.
