### ISSUE TITLE
Nano-issue: Turn @user@twitter.com into a link

### ISSUE THREAD

**Issue by nrchtct** [tootsuite/mastodon#6866]
Thanks for all the hard work, @Gargron et al!

**Feature request**: Many Mastodon users are also on Twitter and may rely on automatic cross-posting or manual referencing of birdsite users. Considering that @renatolond's mastodon-twitter-poster expanded the @user@instance convention to @user@twitter.com it would be nice, if the latter pattern would also be hyperlinked.

**Related**: This matches the first point of this mega-issue: https://github.com/tootsuite/mastodon/issues/1024 but i believe this would help in the day-to-day experience of Mastodon)

Cheers,
Marian

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by TheKinrar** [comment]
It feels weird implementing features in free software like Mastodon to support proprietary software like Twitter.
`twitter.com` is not a Mastodon instance of course, and I don't think it should be treated like it was one. I mean, no one should have special treatment in the source code of Mastodon.

**Comment by m4sk1n** [comment]
+1 for custom hyperlinking options for instance admins

**Comment by nrchtct** [comment]
@Cassolotl : sorry about the duplicate, i didn't see this one.

i understand the sentiment against proprietary software and commercial SNS. i suppose making this an option for site admins would be a nice compromise.

**Comment by Cassolotl** [comment]
@nrchtct No worries. :) Feel free to close this one as a duplicate whenever! Discussion could be moved over to #1849.

**Comment by nrchtct** [comment]
thanks!
