### ISSUE TITLE
Improve image description UI

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#6868]
The current image description feature is a big improvement, but still quite awkward to use. Once you've uploaded your image, the thumbnail appears in the new toot compose area, but it's much smaller and often cropped. If there are words in the image you have to open the image in graphics program on your computer or in a new tab to transcribe. If you're on a mobile device it's a lot more awkward.

![screen shot 2018-03-22 at 13 47 58](https://user-images.githubusercontent.com/6607512/37774504-4a226462-2dd8-11e8-8225-ae66530e63ee.png)

Twitter is much easier to use in comparison. You click "add description" on the thumbnail, and it opens a pop-up that shows the whole image. You can see everything while you're typing the description.

![screen shot 2018-03-22 at 13 48 18](https://user-images.githubusercontent.com/6607512/37774548-68f66348-2dd8-11e8-8f07-4ba053b38139.png)

![screen shot 2018-03-22 at 13 48 24](https://user-images.githubusercontent.com/6607512/37774551-6c2926a4-2dd8-11e8-8482-c77749c392a2.png)

Could we improve the image description UI for Mastodon somehow?

Thanks!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nynhex** [comment]
I can probably help with a PR on this if it's actually something someone wants.

**Comment by v4nt4bl4ck** [comment]
@nynhex I want it! I've been making posts about it quite a bit lol (and yes they've been boosted quite a few times) :D

**Comment by renatolond** [comment]
Would be great to have something like this. Usually I have to open the image in another tab or something to describe it since it's so small. Maybe it could even go to the same pop-out where now there's the focus selection?

**Comment by Cassolotl** [comment]
>Maybe it could even go to the same pop-out where now there's the focus selection?

Like, instead of all those buttons and text boxes on the tiny image thumbnail, maybe just a cross to delete the image and a pencil to "edit" """things""". And if you click the pencil, it lets you choose a focus, and it also has a text box underneath for the image description.

That would be really cool for visually impaired people actually, because I bet lots of fully sighted people would click it to choose the focus to make their toot look fabulous, and then they'll be like "ahhh might as well add a couple of words for visually impaired people while I'm here, since I've got it open..."

**Comment by renatolond** [comment]
Won't that hide a bit how you can add a description? I like that it's super clear that there's the possibility to add an image description right now, it reminds me to do it, where an edit button would probably get more to the back of my mind, personally.

**Comment by Cassolotl** [comment]
Oh yes, good point! Never mind then. :)

**Comment by averageunicorn** [comment]
Oh yes, a nice big preview for describing would be great!  And it could solve part of #6713, too.

**Comment by Cassolotl** [comment]
I just want to bump this because I had to enter an image description in the Mastodon web UI today and it was painful. I usually post on Twitter to use their image description UI instead and wait for the crossposter to pull it over to Mastodon, just because it's so hard to enter an image description on Mastodon.

**Comment by Cassolotl** [comment]
This issue is over a year old and I just had to write an image description by downloading an image and opening it in Preview, and then opening TextEdit beside it to write and edit my image description while still able to see the whole image I'm describing, and then paste it into the Mastodon web UI image description box, and it was exhausting! It shouldn't take three applications.

**Comment by Cassolotl** [comment]
Can we put an "accessibility" label on this issue, please?

**Comment by Cassolotl** [comment]
Thank you @nclm!

**Comment by Cassolotl** [comment]
![Screenshot 2019-10-26 at 15 57 26](https://user-images.githubusercontent.com/6607512/67621648-5a9acf80-f809-11e9-8cb3-794ad097f2eb.png)

This is fixed in the current version of Mastodon (3.0.1 is my instance's version), so yeah, let's close this. :)
