### ISSUE TITLE
Cosmetic: "Toots with replies" is not toots with replies

### ISSUE THREAD

**Issue by shmibs** [tootsuite/mastodon#6870]
in english locales, the phrasing of the "Toots with replies" tab is misleading. on first encountering that phrase, i interpreted it as meaning "only those toots which have received replies" rather than "both this person's toots and this person's replies to other toots". suggested alternative would be "Toots and replies" (or maybe "Toots & replies").

![toots with replies](https://user-images.githubusercontent.com/2358713/37790441-c530d752-2dc3-11e8-9ce0-f7f017b092d2.png)

at a cursory glance, this appears to be a potential issue in other languages as well ("Pouets avec réponses" vs. "Pouets et réponses"), though not universally ("投稿と返信" makes sense)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
This is the same thing that happened on profile pages. "Toots with replies" was changed to "toots and replies", and I guess the same thing needs to happen here!

See: *"Toots with replies" on profiles is ambiguous #5093*

**Comment by shmibs** [comment]
ah sorry, i guess i'm not very good at searching for previous issues X_X

**Comment by Cassolotl** [comment]
No worries, it is hard to guess the keywords! :) Feel free to close this issue at your leisure (I have not the power).
