### ISSUE TITLE
Different Atom feed for Toot's and replies

### ISSUE THREAD

**Issue by schiessle** [tootsuite/mastodon#6873]
I integrate my toot's into my homepage, see schiessle.org. For this I only want to display my own toot's because I think replies doesn't make a lot of sense because of the missing context.

At the moment I parse the atom feed and  skip the replies. This works, unless I have a lot of conversations on Mastodon. In this case I get less and less "real" toot's in the Atom feed and therefore less and less toot's I can show on my homepage. Therefore it would be nice to have separated feeds, one with my toot's only and one which contain the whole conversations.

**Comment by Limero** [comment]
It would make most sense if `/@username.atom` returned a feed with only toots and `/@username/with_replies.atom` included replies, like the regular pages does. Currently, they both return the same feed with replies.

**Comment by rixx** [comment]
FYI, the RSS feed contains only statuses, no boosts and replies.

**Comment by trwnh** [comment]
IIRC, Atom feeds are used for OStatus federation and therefore don't make a distinction. RSS is more user-facing and *does* make a distinction.

**Comment by nightpool** [comment]
closed by #7259
