### ISSUE TITLE
Accessibility issues with column headers

### ISSUE THREAD

**Issue by ndarilek** [tootsuite/mastodon#6880]
The following issues exist that make using Mastodon with a screen reader more difficult:

`<h1 tabindex="0" role="button" class="column-header" aria-label="Home">` does the following:
 * Indicates to the screen reader by `<h1>` that it is a header. This activates convenience features like navigating by the h/H keys to the next or previous header, respectively.
 * Undoes that by setting `role="button"`.
 * Confuses my screen reader, because you have a second `<button/>` in a `<h1>` that calls itself a button, and a screen reader doesn't know what to do with a button that contains a button. I mean, semantically it doesn't make any sense for a button to contain another button, and that's what the ARIA attribute does.

What you need to do is let the `<h1>` be a heading by virtue of its tag, then just use `<button/>` for actual buttons. I realize that may break styling, but what you've done breaks accessibility in a way that no use of ARIA can fix.

I'm a bit frustrated because https://github.com/tootsuite/mastodon/pull/6179 fixed this. It may have broken the style, but I wish folks had worked with me in the context of that PR. I'm a blind screen reader user, so that PR definitely fixed things in terms of accessibility, at least under my screen reader, but probably everywhere else as well.

Thanks for any resolution.

* * * *

- [* ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [* ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).
- [*] I submitted a PR that fixed this issue.

**Comment by nightpool** [comment]
@ndarilek #6199 included all of the changes you made, as far as i'm aware. Can you confirm that you're still seeing these issues on a 2.2.0 or later instance of mastodon?
