### ISSUE TITLE
joinmastodon.org broken

### ISSUE THREAD

**Issue by kerim** [tootsuite/mastodon#6888]
joinmastodon.org is not offering a list of instances, says "no results. . . for now"

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
joinmastodon.org repository is not here.

https://github.com/tootsuite/joinmastodon

**Comment by Gargron** [comment]
Aware of this issue btw but it's not really in my power to fix, joinmastodon.org uses instances.social API and that's what's down right now.
