### ISSUE TITLE
[BUG] URLs become wrong when they have special characters

### ISSUE THREAD

**Issue by Lomplac** [tootsuite/mastodon#689]
The special characters in a URL are written with their [HTML entity names](https://www.w3schools.com/html/html_entities.asp) in toots
for example ["fr.wikipedia.org/wiki/Message_d'Arecibo"](https://fr.wikipedia.org/wiki/Message_d'Arecibo) becomes ["fr.wikipedia.org/wiki/Message_d& apos;Arecibo"](https://goo.gl/BFgvYV) which is a wrong URL

**Comment by Gargron** [comment]
Has been fixed, I think.
