### ISSUE TITLE
spurious 502 error?

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#6894]
When i tried to toot at someone i got the error 502, which disappeared immediately, and when mentioning it a mod mentioned they occurred more often but didn't know if there was any further action on those. Quick search didn't surface anything, thus this issue. Relevant toot, and thus timestamp, is:

https://mastodon.social/@Mithaldu/99729626193428437

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
>502 HTTP: The server was acting as a gateway or proxy and received an invalid response from the upstream server.

Generic intermittent error. Not a Mastodon problem.
