### ISSUE TITLE
When I copy a toot that has an account name, the server name should be included

### ISSUE THREAD

**Issue by timmc** [tootsuite/mastodon#6896]
If I'm on mastodon.social and make a toot like `My alt is @timmc@mastodon.example and my home page is http://example.com/long/URL/that/will/get/truncated so come check it out` it shows up like this (assuming that account exists at the time of posting):

`My alt is @timmc and my home page is http://example.com/long/URL/that/will… so come check it out`

If I then *select and copy* that toot, the full URL end sup on my clipboard. Unfortunately, the account name remains truncated to the local name, which means if I copy, delete, and re-submit a toot, any references to accounts on other instances get messed up. Same happens to anyone copying the toot to paste it in an email, article, etc.

This is probably pretty easy to fix. The URL isn't really truncated, it just has some parts hidden with `<span class="invisible">`. The same could be done with account name references.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by timmc** [comment]
(I should note that my *real* preference is to always show the server name, since the current behavior causes issues when I talk about alt accounts that use the same local name. But unless https://github.com/tootsuite/mastodon/issues/226 is open for revisiting, it sounds like the best alternative.)

**Comment by kjhoerr** [comment]
For what it's worth, as non-plain-text copy/paste it does include the link to the mentioned account (e.g. https://mastodon.example/@timmc). It seems like a straightforward change though.

**Comment by timmc** [comment]
Yes! Thanks, I'll close mine.
