### ISSUE TITLE
Subscribers not listed on Statusnet, GNU Social or Friendica

### ISSUE THREAD

**Issue by annando** [tootsuite/mastodon#690]
I created a testaccount on mastodon.social and added my accounts on servers with GNU Social, Statusnet and Friendica. None of these servers seemed to be notified of this. Normally one should be listed as "Subscribers" in GNU Social and Statusnet. This hadn't happen. I haven't checked yet if the server had sent some notification that maybe wasn't understood or if there wasn't sent any notification at all.

**Comment by Gargron** [comment]
A Salmon notification is definitely sent. GNU social normally doesn't have issues parsing it, however I did notice that Friendica doesn't list Mastodon followers. Can't say much about StatusNet because that's a project that was discontinued in favor of GNU social in 2012.

The salmon XML is built here: https://github.com/tootsuite/mastodon/blob/master/app/services/follow_service.rb#L80

It looks roughly like this:

```xml
<entry>
  <id>someUniqueId</id>
  <title>a followed b</title>
  <content type="html">a followed b</content>
  <author>
    <activity:object-type>http://activitystrea.ms/schema/1.0/person</activity:object-type>
    <id>uniqueAuthorId</id>
    <uri>uniqueAuthorId</id>
    <!-- other user attributes like portable contacts fields, links to HTML page and Atom feed -->
  </author>
  <activity:object-type>http://activitystrea.ms/schema/1.0/activity</activity:object-type>
  <activity:verb>http://activitystrea.ms/schema/1.0/follow</activity:verb>
  <activity:target>
    <activity:object-type>http://activitystrea.ms/schema/1.0/person</activity:object-type>
    <id>uniqueUserId</id>
    <uri>uniqueUserId</id>
    <!-- other user attributes like portable contacts fields, links to HTML page and Atom feed -->
  </activity:target>
```

**Comment by annando** [comment]
Friendica had fatal problems with the new url format. A webfinger request for "https://server.tld/users/username" works - but a webfinger request for "https://server.tld/@username" fails.

I created a workaround now. But I think this is a bug in Mastodon which would explain why neither Statusnet nor GNU Social is currently working.

**Comment by Gargron** [comment]
Why would GS or Friendica hit webfinger for the short form of the URL? It only appears as href on a `<link rel="alternate" />`, the `<id>` and `<uri>` tags use the old, long form. Which field does Friendica use to identify users?

**Comment by annando** [comment]
The probing for the address format returns the short form as primary URL on my system.

**Comment by Gargron** [comment]
What do you mean by probing? Which mechanism?

**Comment by annando** [comment]
"probing" means the mechanism where you can enter a profile address in all available forms and the system returns the detected data (name, photo, poll address, key, ...)

**Comment by Gargron** [comment]
What do you enter as the profile address then? username@domain? Or the short form URL? If it's the short form URL, then I understand why Friendica would send it to the Webfinger endpoint.

**Comment by annando** [comment]
Since Friendica is a multi protocol system, the system has to accept every format.

**Comment by annando** [comment]
Thanks!
