### ISSUE TITLE
Hide followers and follows to protect user's privacy

### ISSUE THREAD

**Issue by Tuxicoman2** [tootsuite/mastodon#6901]
I wonder if user profiling can be done at low cost from the user's follows or followers list.

It should be possible to automate the build a social graph and list the interests of a user from this.
Has it be done already on twitter data for example?

I guess for example determining if the user is gay, what political side he is, etc... can be trivial to get.

* * * *
- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
Related to some of the comments in *Option to hide followers and follows on public profiles from non-users #5337*!

**Comment by nynhex** [comment]
I'm down to fork and PR this if there's interest.  It's definitely a privacy issue IMHO.

**Comment by deutrino** [comment]
#5337 is basically the same feature request, but with scope limited to hiding this info on the public web view of a user's profile, which would not be sufficient to prevent automated data collection.

**Comment by stephenburgess8** [comment]
Here's a couple of options of how to implement this in the UI. Hope it is helpful.

* Create a UI in the settings to allow for Follow/Follower Counts to be turned off
* When Follow/Follower counts are turned off, do not show follow/follower accounts a) on user profile page in Mastodon b) on public profile page c) api
* This setting is disabled by default, but can be turned on at any time. Some actions will auto-trigger this being selected, such as Locking one's account.
* Simple solution: When this option is selected, only the user themselves can see the counts
* Complex solution: people the user follows can also see their counts. However, I'd contend that if this option was selected, the idea is that not even mutuals would know your counts.
* Global option: Have a setting that an admin can turn on to disable user counts in new user accounts by default. Allow individual user to override. Admin should not be able to change individual user's preference easily in the admin UI.

I think that Locking one's account should trigger this feature. When people talk about private accounts, this what they're referring to, correct? 

I came up with two ways to do this in the UI. One is to just remove follower and following field entirely

<img width="333" alt="screen shot 2018-04-08 at 1 09 09 pm" src="https://user-images.githubusercontent.com/6003351/38470831-2be56afe-3b2e-11e8-8a2d-d116f844e13b.png">

The second is to have a symbol where the number would be. This is what I have seen instances do when they made a customized solution to this. I would propose an infinity symbol. ∞ I think I have a slight preference for this solution.

<img width="736" alt="screen shot 2018-04-08 at 1 14 54 pm" src="https://user-images.githubusercontent.com/6003351/38470890-13d7a6ba-3b2f-11e8-946e-be8322bd0085.png">
<img width="324" alt="screen shot 2018-04-08 at 1 38 18 pm" src="https://user-images.githubusercontent.com/6003351/38471109-2eb63ec6-3b32-11e8-814c-5254449e1f7b.png">

Finally, I think this setting would go well in the Security section, as in this screenshot:

<img width="515" alt="screen shot 2018-04-08 at 1 27 55 pm" src="https://user-images.githubusercontent.com/6003351/38471014-dc953878-3b30-11e8-975a-b411fa916c48.png">

What do you think of this approach? ∞

**Comment by Gargron** [comment]
Can see value in this but can also see it as kind of pointless unless everyone you follow and who follows you also hides their lists (because the relationships are always two-way)

**Comment by stephenburgess8** [comment]
I think the greater issue is that people want to prevent others from
passively profiling them through reading their following list.

**Comment by Gargron** [comment]
Poll: https://www.strawpoll.me/15477773/r

**Comment by trwnh** [comment]
Just because relationships are two-way doesn't mean much. If you hide your followers, then someone would have to crawl and inspect theoretically every single user in order to determine your follower list. The only thing they can discover easily is if any *one* user is following you. Vice-versa for the following list and people that you follow.

This is a net increase in privacy, and if the goal is to obscure a given relationship between two users, then only those two users need to opt-in, not every single user on the follower/following list.

**Comment by zcdunn** [comment]
If this is going to be implemented, could it be on only the public profile pages? Logged in users should be able to see those lists. If not, it'll be even harder to find people on mastodon

**Comment by Cassolotl** [comment]
The things that scrap user data will almost certainly be logged into Mastodon, I think?

Also, I think more ways to find cool people to follow is a good idea. (Plus those lists often have inactive or deleted accounts, so ways to find cool people could probably take this into account.)

**Comment by zcdunn** [comment]
Those lists are currently on the public profile, so it would be easiest to scrape the public data. But if it's logged in, can't it be blocked? Blocked users shouldn't be able to see anything on your profile. And if it's logged in, it'll be able to build an incomplete profile from the other direction, as Gargron said.

**Comment by Tuxicoman2** [comment]
Just to be sure that proposal could meet the target use cases I had in mind when submitting the issue. Here are a few examples :
- I want to follow a porn, extremist, former girlfriend, etc... account that would create an embarrassing public relationship. How do you let users to follow any account without having to think is the publicity of this relationship can harm himself? 
- I'm a extremist political party, gay group in religious country, etc... and I don't want a rogue advertiser or CambridgeAnalytica like company to sniff my followers list to cheaply build an audience list that could be reused to harass, advertise, harm accounts within this list.

**Comment by kit-ty-kate** [comment]
As said in #6477 I think this option should be enabled by default on locked accounts.

**Comment by jeroenpraat** [comment]
I voted Yes, but I have some remarks:

- I think hiding the number of follows/followers doesn't make sense, but if people think that goes well with hiding follows/following I'm not against it.
- I propose to make a distinction between the logged-in view (webapp/other apps) and the public profile pages.
-- On the public profile pages the follow/following list should be hidden by default. This is the same as on Twitter and like Twitter, the numbers can be shown, but I have no objection hiding those as well. People should be to toggle this new default behavior. So this goes one step further than my original idea on #5337.
-- When people are logged in, I go with the proposal in this issue. This should not be default on normal account and default on locked accounts (term 'locked' is confusing BTW - those account are not locked, but private). Normal and private/locked accounts should be able to toggle their behavior. 

Hopefully this makes sense.

**Comment by stephenburgess8** [comment]
@jeroenpraat Your comment points out that hiding follows/following number is different from hiding the list, which is a great point. These are actually two different modifications. 

1) Hide number of follows/following
2) Hide list of follows/following

It could be possible to split them into two different options, but I think that’s too complex for a solution. My suggestion is as follows:

One toggle, at the user level, default off. When turned on, follows/following lists and counts are hidden for everyone but the user.

One concern I’ve read is reducing findability. I agree it would be nice to be able to find people easier, but forcing everyone to have public follows lists is not the way to do that.

Locked vs private -
Locked means nobody can follow you without approval. Privacy settings are on the toot level, not the account level. Privacy levels are Unlisted, Followers-only, Direct (to someone), and Direct (to one’s self). That’s why we talk about locked accounts, not private accounts. You can set default toot privacy but privacy is still set per toot. It’s not possible to change the privacy level of a toot after it’s been posted.

One other possible, nice to have feature: Let admins set a site-wide toggle which hides follows/following by default for new accounts. Some admins want to have this enabled and not allow users to override. I don’t think that’s the primary use case and if someone wants that feature they should fork the codebase. Thanks.

**Comment by HybridEidolon** [comment]
There is a practical use case for allowing a user to do this: the forced visibility is currently a path for organized harassment to track down associates of a target and harass them in turn. It may be impossible to cover all the ground here due to federation, but at least making it more difficult to do at the behest of the victim would be nice.

Another desirable attribute would be to hide the user from others' following/follower lists when they have hidden their own.

Instances that have locked down registration requirements would be able to stop someone from creating an account just to sockpuppet or stalk if the lists had to be made visible to logged-in users.

**Comment by lapineige** [comment]
@stephenburgess8 you're right about the 2 difference modifications.

Regarding 1) : it might have less privacy concerns (I'm not sure that followers/followed figures, and maybe their evolution, give much information). But apart from that, it's useful not to show the "influence" of an account (as having many followers probably result in appearing as "important", and "influencer", ... just like  the numbers of view/likes under a video encourage people to trust it more). As an option that comes with 2) (if it's better to keep it simple with one single option for both), I think it's a valuable side effect.

Regarding 2): indeed it doesn't really "hide" those data (followers/following), as they are still available on other accounts profile. And the people you interact with publicly also give some info (as well as their following list).
But still, it's way more complex, and longer, than just browsing (indexing ?) a profile. Especially for "humans" (a lot less for bots).

(And I would really appreciate 2), btw 🙂)

**Comment by kurdk6873-prog** [comment]
miss_y4re
