### ISSUE TITLE
Bug? Mastodon front page looks wrong on mobile for this one Reddit person

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#6908]
Reddit person [kindly provided a screenshot](https://www.reddit.com/r/videos/comments/86zzkc/mastodon_opensource_social_media_doesnt_track_you/dw9v6lc/). They said they're on Safari on an iPhone.

![wcyivjo](https://user-images.githubusercontent.com/6607512/37879722-0fcdc208-3075-11e8-8e4e-be9dcc566e75.png)

I've asked them which operating system and browser they're using, and whether they have any settings that might force a desktop view or something like that.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by rhaamo** [comment]
Tried right now and I have the same "view" of the webpage.
Safari on iOS 11.2.6 (iPhone SE)

But it looks like sometimes it load correctly in a single column without having to "unzoom" with a gesture, and multiple refresh doesn't reproduce the issue :/
