### ISSUE TITLE
[Feature] custom offline / online avatar states

### ISSUE THREAD

**Issue by jebuskrust** [tootsuite/mastodon#6909]
When someone is online have a custom avatar. When offline have a separate one.

Example:
If offline my avatar of a megaphone would be appropriate
While online have megaphone that's blasting some epic toots.

Maybe static, may be animated.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
Closing, as Mastodon does not have any notion of presence (it doesn't keep track of who is online or not, and doesn't federate that information). IMHO, Mastodon is not the correct tool for that.
