### ISSUE TITLE
Docker-compose error with assets:precompile

### ISSUE THREAD

**Issue by jgoodleaf** [tootsuite/mastodon#6911]
Setting up mastodon via docker-compose yields the following error

```
I, [2018-03-25T23:29:34.906893 #5]  INFO -- : Writing /mastodon/public/assets/pghero/application-c2618b70600dfedb0f3ba1f916d97a2f93a3f265aba10356abb763bd663d0cbd.css.gz
rake aborted!
Errno::EACCES: Permission denied @ dir_s_mkdir - /mastodon/public/assets/doorkeeper
```
* version 2.3.2
* `docker-compose run --rm web rake assets:precompile`

Any idea how to get this working?
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by jgoodleaf** [comment]
Follow-up.
I rebuilt the image and it all worked correctly. My suspicion is that I missed the 
`chown -R 991:991 public`
step.

Closing, but leaving the comment just in case someone is as dumb as I am.

**Comment by SabreCat** [comment]
The guide doesn't tell you to do the `chown` step if you're working from a public image, so that's excusable methinks :\

**Comment by lukas-lansky** [comment]
Ran into it too, tried to address the docs issue in https://github.com/tootsuite/documentation/pull/596 .
