### ISSUE TITLE
a way to update avatars and profiles with the API

### ISSUE THREAD

**Issue by tinruufu** [tootsuite/mastodon#692]
it would be nice if you could update user profiles and avatars via the public API

this is required for me to be able to make [this borb](https://mastodon.social/@rowletbot) reach feature parity with [its twitter counterpart](https://twitter.com/rowletbot) in a way that doesn't involve phantomjs or otherwise pretending to be a browser

**Comment by tinruufu** [comment]
my awful phantomjs hack broke a few days ago and took rowletbot with it

i've not had time to look into exactly what caused it, but i would greatly prefer using a real API to debugging this nightmare i built

**Comment by Gargron** [comment]
There's the `PATCH /api/v1/accounts/update_credentials` method

I'm surprised the person who added it didn't reference this issue, so it got lost. It was #1179

**Comment by tinruufu** [comment]
this could be that im missing something, but im currently running into a situation where i can update my avatar through the web UI, but i can only update my avatar through the api once

every time i set my avatar to something different, it's being set to the first avatar i ever set through the api, regardless of its actual content. i've tried to work out what's going on, but i promise im sending a different image each time, and it's always getting set to the same thing

it's not transient, either; i can set an image in the web profile editor, but then when i set another avatar in the api, it gets set back to that same first one i set

could someone who understands ruby look into if this is just me being bad at programming or if this is actually how this endpoint behaves? im using mastodon.social, if that helps
