### ISSUE TITLE
Tab crashes when I try to load mastodon.social

### ISSUE THREAD

**Issue by JCSzamosi** [tootsuite/mastodon#6928]
Similar to issue 5712, but not identical: When I try to load mastodon.social in Firefox (59.0.1) on Mac OS (10.10.5 Yosemite), that tab crashes. It happens every time. Other tabs do not appear to be affected.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Unfortunately, this isn't enough to investigate.
