### ISSUE TITLE
Ctrl+Enter sends message when "Toot" button is disabled

### ISSUE THREAD

**Issue by NekoiNemo** [tootsuite/mastodon#6931]
When "Toot" button is disabled (specifically when image is being uploaded) message can still be sent with Ctrl+Enter combo, resulting in message being sent without (still uploading) attachment.
(Tested on niu.moe)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
Fixed by #6931
