### ISSUE TITLE
Unique index on accounts username/domain is not case insensitive

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#6937]
For some reason (a mistake, oversight or confusion), there are two indices on the accounts table:

- lower(username), lower(domain): case-insensitive, *not* unique
- username, domain: case-*sensitive*, unique

Only the last one is unique! That's a waste of space, but it's also bad because it allows duplicate accounts to be created under race conditions or other edge cases (those that were discovered, were patched already, though)

We need to:

- Turn the case-insensitive index unique and remove the redundant one
- But before we can do that, we need to, in an automated manner, "fix" duplicate rows, by either merging, removing, or renaming the accounts

In the case of merging, that would require updating all associate records to a different account_id. In case of removing, need to decide which of the accounts to keep... This is further complicated by the bug (already fixed) that occurred in 2.3.2 and allowed, under some circumstances, multiple local accounts with the same username (different casing).

Very likely related issue: #3005

**Comment by nynhex** [comment]
This sounds like it will require some significant work.  Should you need assistance, please tag me.

**Comment by ThisIsMissEm** [comment]
Could this also be related? https://github.com/tootsuite/mastodon/issues/6837
