### ISSUE TITLE
keyword muting

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#694]
a muting function to mute keywords from home timeline and public timeline is very strong for users (preferably with an option to let them appear in replies if that is your inclination)

this functions hould also be sure to check content warning fields, as the current existing function (in hometimeline only) does not check CW fields

**Comment by hoodiek** [comment]
related posts: #500 #59 and #325

**Comment by mal0ki** [comment]
Adding in @hoodiek 's [outline of the feature from discourse](https://discourse.joinmastodon.org/t/keyword-muting-for-anti-harassment-and-content-filtering/226)

**Comment by mal0ki** [comment]
Edited out mute-thread from the topic again, as it has been implemented. Let me know if that was wrong.

**Comment by deutrino** [comment]
List of dupes I found of this issue:

- #694 (muting keywords from timelines)
- #1158 (muting keywords from timelines)
- #2453 (muting hashtags and keywords from timelines)
- **#3848 (muting by keywords, improve the accessibility beyond "lern2regex noob", listed as a priority for version 2.1)**
- #4081 (specifically requesting that muting by keyword work in CWs as well)

**Comment by olivierlacan** [comment]
@mal0ki do you know if there has been any work done or any discussions about a potential feature that would allow people to mute parts of a thread?

For instance, it’s common for threads to devolve after a specific response, when some people start to dog pile by replying en masse to a specific part of the thread. Both authors and prior repliers to the original thread branch may want to stay involved in the main trunk but ignore or mute the problematic branch of the thread. 

This was suggested [in this post](https://mstdn.social/@kissane/109508893775663579) and I find the feature very reasonable as an extension/improvement to this existing feature.
