### ISSUE TITLE
grant_type=password allows accounts with non verified emails to toot & read statuses

### ISSUE THREAD

**Issue by stom79** [tootsuite/mastodon#6943]
My concerns are mainly:
 - Bots (ie with non verified emails) can gather informations from local timelines.
 - Impersonations.

Does an admin can take actions and remove accounts with no verified email, for instance, if they were created more than x days ago? 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by codl** [comment]
Users with an unverified email address are automatically deleted after two days [\[1\]](https://github.com/tootsuite/mastodon/blob/master/app/workers/scheduler/user_cleanup_scheduler.rb)

**Comment by stom79** [comment]
Maybe a stupid question but this script should have deleted [my test account ](https://mastodon.social/@mastalab_test)
between [4:00 and 6:59](https://github.com/tootsuite/mastodon/blob/61ed133fea80041b354c78b043cec72dd8644101/config/sidekiq.yml#L22)? 
It was created on 25/03/2018 at 19:50 - UTC+2 - (date of the email).

**Comment by stom79** [comment]
OK. The account has been automatically deleted.
