### ISSUE TITLE
Error while opening /admin/invites

### ISSUE THREAD

**Issue by MasterGroosha** [tootsuite/mastodon#6946]
I've updated Mastodon to 2.3.2 and then to 2.3.3 and unfortunately everytime I go to "invites" section in Settings, I see "Sorry, something went wrong" error.

There're no logs for mastodon neither in `/var/log` nor in `~/live/log` directory (I don't know why and how I can enable them) so I do not know the reason of this problem.

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Logs are in `journalctl -u mastodon-web`, please post the relevant stacktrace

**Comment by MasterGroosha** [comment]
@Gargron seems that I also had problems with journal not working. After fixing it, I see the problem:

```
 ActionView::Template::Error (translation data {:one=>"1 исп.", :other=>"%{count} исп."} can not be used with :count => 5. key 'many' is missing.):
     2:   = render 'shared/error_messages', object: @invite
     3:
     4:   .fields-group
     5:     = f.input :max_uses, wrapper: :with_label, collection: [1, 5, 10, 25, 50, 100], label_method: lambda { |num| I18n.t('invites.max_uses', count: num) }, prompt: I18n.t('invites.max_uses_prompt')
     6:     = f.input :expires_in, wrapper: :with_label, collection: [30.minutes, 1.hour, 6.hours, 12.hours, 1.day, 1.week].map(&:to_i), label_method: lambda { |i| I18n.t("invites.expires_in.#{i}") }, prompt: I18n.t('invites.expires_in_prompt')
     7:
     8:   .actions
```

I'm using Russian translation and seems that after [this](https://github.com/tootsuite/mastodon/pull/6227/commits/523f30cd86b1342345da7ef9d87ac6939e0680d5) commit something was changed, a new modifier "many" was added and everything broke. I manually added it to `ru.yml` file, restarted Mastodon and it's working now. 
I guess I should check new strings and make a pull request with locale update.

**Comment by nightpool** [comment]
@MasterGroosha the problem was in the original commit. Russian pluralization rules require one/few/many/other keys for all `%{count}` values. See http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html#ru
