### ISSUE TITLE
pasting images into mastodon does not function

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#695]
i was informed this feature existed by Gargron I believe, if it does not exist, it should, but i am pretty sure it does exist and this can thus be marked as a bug.

neither CTRL+V or right click->paste does anything

it's in the title, specific information that is relevant:

Windows 10/Chrome (see below0
![image](https://cloud.githubusercontent.com/assets/23704040/24466256/38353c3a-147e-11e7-97c6-299cf21be9b4.png)

**Comment by noiob** [comment]
The feature exists, confirmed working with Ctrl-V and right click > paste in Safari

**Comment by ticky** [comment]
@noiob wait, it works for you in Safari? It doesn’t work for me. What version are you running?

It also looks like Chrome 57 broke this behaviour. The clipboard APIs are also in flux.

This also seems to have been duplicated by #734.

**Comment by noiob** [comment]
@ticky I'm running Safari 10.1 on macOS 10.12.4. I am able to copy an image file in Finder, then click into the toot box and press Command+V to insert it

**Comment by ineffyble** [comment]
This definitely used to work, and doesn't for me on Chrome 57/MacOS.

**Comment by sarahmeyer** [comment]
yah, also borked in chrome 57. fix is probably on [this line](https://github.com/tootsuite/mastodon/blob/9bf4c34919c0ad09417394eaa246c8af9effe131/app/assets/javascripts/components/components/autosuggest_textarea.jsx#L146)?

**Comment by nightpool** [comment]
Yes this used to work for a minute and now it's broken again :(

**Comment by Gargron** [comment]
It works on Firefox. It seems like support for such a function in general is rather different between browsers, so there is only so much I can do.

**Comment by Artoria2e5** [comment]
Chrome 62 seems to go through the clipboardData.files check fine, but Mastodon still won't paste it. The test page (attached) doesn't seem to show much difference between Cr and Fx in console.

<details><summary>test page</summary>

```html
<textarea id="ta"></textarea>
<script>
    f = function(){ console.log(arguments) }
    document.onpaste = function (e) {
        console.log(e)
        console.log(e.clipboardData.files)
        console.log(e.clipboardData.files.length)
        console.log(e.clipboardData.items)
        console.log(e.clipboardData.items[0].type)
        console.log(e.clipboardData.items[0].kind)
        try { e.clipboardData.items[0].getAsString(f) } catch (ex) {console.error(ex)}
        return true
    }
</script>
```
</details>

**Comment by YDKK** [comment]
Pasting image in Edge is not working.
When I trying to paste image, console shows
` SCRIPT5007: Unable to get property 'length' of undefined or null reference`.

It seems we can use `e.clipboardData.items[0].getAsFile()` instead of `e.clipboardData.files`.

For example,
https://github.com/tootsuite/mastodon/blob/995f8b389a66ab76ec92d9a240de376f1fc13a38/app/javascript/mastodon/components/autosuggest_textarea.js#L157-L162
to something like:
```js
 onPaste = (e) => { 
   if (e.clipboardData && e.clipboardData.items.length === 1) { 
     this.props.onPaste([e.clipboardData.items[0].getAsFile()]); 
     e.preventDefault(); 
   } 
 }
```

I checked both Edge 42.17134.1.0 and Chrome 68.0.3440.106.
![image](https://user-images.githubusercontent.com/3415240/44620466-ac775b00-a8cf-11e8-9ba5-265303a8ae8c.png)
