### ISSUE TITLE
Make invite-only instances visible

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#6951]
This toot says it well:

>I'm glad that Mastodon is getting more mainstream attention as an alternative for folks fleeing the abusive culture of Twitter, but it's frustrating that anti-abuse instances are left out of JoinMastodon BECAUSE of the policies they implement to keep out abusers. (Moderated sign-ups.) You programmed it in; instances use it, & then you penalize them for doing it by making them hard to find, while including actually abusive instances on JoinMastodon AND still getting credit for being anti-abuse.

Some people will actively search for instances that are invite-only, because they tend to be safer. (Generalisation, but *mostly* accurate!)

In the instance picker, instances are considered freely open to all registrations, or they are not listed.

An option to view open instances, open-with-invite instances, or both could be cool, I think?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Sylvhem** [comment]
Just a reminder that instances that are open at specific hours (like https://witches.town/) also don't appear in the instance picker because they are considered closed by https://instances.social/. That's kinda frustrating.

**Comment by Gargron** [comment]
>That's kinda frustrating.

I appreciate instances with closed registrations and unusual modes of operation, but why should new users be directed somewhere where they can't sign up? I'm pretty sure most of them *would* just bounce from the "closed registrations, request an invite" page because that *is* frustrating.

**Comment by Laurelai** [comment]
I disagree, a semi-filtered instance might be just what someone is looking for.

**Comment by Sylvhem** [comment]
> why should new users be directed somewhere where they can't sign up?

But they can sign up. There is just extra steps to ensure that those instances stay mostly safe from harassers and toxic people.

**Comment by Cassolotl** [comment]
>I'm pretty sure most of them would just bounce from the "closed registrations, request an invite" page because that is frustrating.

That's why there would be a third category for sort-of-open instances, where people could look if they wanted an instance with a whitelist, for example. It wouldn't be the default view on the instance picker because we don't want new people to give up when it's harder to get an account, but it would be there if people wanted to look for instances like that, and it would let sort-of-open instances be visible.

I run a Minecraft server, and it has a whitelist, and people have to apply via a google form. On the google form there's a box that asks why you want to join this server, and people *often* say "I wanted to join a server with a whitelist, because it means that it'll be safer." I think it would be the same with Mastodon, for *some* people. Most people would rather just join and try it out right away, but I think there would be people specifically looking for a nicer, more curated space, too.

**Comment by mal0ki** [comment]
I understand Gargrons wish to catch all new users that come through joinmastodon.org etc. 

But if people are fleeing the toxicity of Twitter and Facebook, finding these invite-only instances will still be very useful. And actually be able to search for them specifically.

**Comment by jebuskrust** [comment]
I like @Cassolotl's something like..

Open 
- Only requires account registration

Apply 
 - Open registration
 - Requires account registration and moderator application review to approve.

Invite 
- Invite only
- Requires invite link and account registration.

Closed 
 - Closed registration (No reason to show)

Although regardless of the outcome, probably want to be careful with this though, unless you want to start seeing the social network evolving into a network full of potential paywallers by this feature being improperly used.

**Comment by trwnh** [comment]
This is mostly the realm of instances.social API, right? @TheKinrar

**Comment by jebuskrust** [comment]
Correct.

From what I've gathered, the request is to update the availability of certain instances that may be invite only on the site allowing them to appear. 

On one hand of the end user navigating the site the first time you have new users that don't want to have to neccessarily search through the server listing to end up finding a server that is invite only.

And nn the admin hand you have some instances that want to have a private presence on the network.

And on the other admin hand there's admins that want to have their presence known regardless of the instance type being available or invite only.
