### ISSUE TITLE
add copy-link option in drop down for toots

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#696]
it's in the name. i believe i mentioned this in the discord, i personally would appreciate this feature a lot.

**Comment by noiob** [comment]
You can copy the link (like in Twitter) by right click > copy link on the timestamp, in case you didn't know. Adding a menu item is still useful, though

**Comment by Gargron** [comment]
#680?

**Comment by hoodiek** [comment]
ah, you're right, it's the same thing so this can be closed. my bad
