### ISSUE TITLE
Can't hide all media from an instance (as an user)

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6962]
I'd like to hide avatars from switter but as an user I cannot. my only options are to report it to my admins and hope they block the instance, depriving other users of my instance from seeing that content/instance if they wish to do so.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by deutrino** [comment]
There's a bit of a discrepancy between the issue title and the description. Do you only want to hide avatars, or have a "hide all media" button that includes avatars, or...?

**Comment by SoniEx2** [comment]
Hide all media. Avatars are the main reason, but all media is good.
