### ISSUE TITLE
Difficulty understanding the UI in Reports Section

### ISSUE THREAD

**Issue by ThisIsMissEm** [tootsuite/mastodon#6969]
Hi! It's really hard to understand the current status and attributes of toots in the report section as everything is hidden behind icons. Would a pull request to add textual metadata beneath toots be accepted?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
can you give an example? I'm not sure what you mean

**Comment by nightpool** [comment]
Here's a screenshot of a reported toot. for reference:

![image](https://user-images.githubusercontent.com/233815/38144838-76422676-3414-11e8-82d5-b14a411ab632.png)

I'm not sure what icons you're referring to

**Comment by ThisIsMissEm** [comment]
So, from that, I can't see whether the toot was flagged with a content-warning or NSFW marker. The eye icon isn't entirely clear, either.

**Comment by ThibG** [comment]
Hm… one current issue with this admin view is that it incorrectly lists boosts and mess them up.
Apart from that, it's pretty much like the public view and Content Warnings are not ignored or anything so I'm not too sure about your point there. NSFW-tagged media also has a “sensitive” label when hovering over it, so the information is here.

**Comment by ThisIsMissEm** [comment]
Point is, from the icons and UI alone, it's hard to see — I'd just like an interface with textual descriptions of the settings on a toot. Icons are hard to understand their meaning all the time.

**Comment by ThibG** [comment]
I'm not completely sure how that would be better, but why not.

In the meantime, I must stand corrected: the “sensitive” label only appears in the fork I am using and not on Mastodon itself. I will try to backport that change.

**Comment by ThisIsMissEm** [comment]
Have a look at #7000, I've just done a whole heap of updates to the reports interface, including adding functionality that was previously missing.

Added:
- Ability to add notes from moderators on the reports
- Ability to assign a report to a moderator (presently just "assign to self", not "assign to X")
- Ability to remove a users' avatar as a moderator
- Some adjustment / cleanup to the UI

I'm probably going to look at doing #6994 soon, but I'm not entirely sure how to test it, as my localhost isn't connected to any other instances.

**Comment by ThibG** [comment]
I'm fine with your changes, but I'm afraid I still fail to understand how you think the toots themselves should be presented.

**Comment by ThisIsMissEm** [comment]
I'll see if I can do up something later, I'm essentially just thinking a table below the toot, with:
```
media marked as sensitive: yes/no
content warning: yes/no
```

As presently the icons aren't always clear as to the current state.

**Comment by ThisIsMissEm** [comment]
Here's a mockup of what I was thinking:

<img width="756" alt="screen shot 2018-04-03 at 7 24 33 am" src="https://user-images.githubusercontent.com/30827/38230819-20499e12-3710-11e8-9447-46bb0d01318e.png">
<img width="744" alt="screen shot 2018-04-03 at 7 24 20 am" src="https://user-images.githubusercontent.com/30827/38230820-20643736-3710-11e8-9c6a-3ff8485fa6dd.png">

This is what that looks like with "Always show sensitive media" enabled:

<img width="755" alt="screen shot 2018-04-03 at 7 25 54 am" src="https://user-images.githubusercontent.com/30827/38230858-5399abb8-3710-11e8-95ed-fff2bc4f4b64.png">

**Comment by ThibG** [comment]
Ok, I understand for media marked as sensitive. I think #7012 helps with that.
The presence of a content warning is pretty obvious from the first line of the toot, so I'm not too sure how duplicating that information helps.

**Comment by ThisIsMissEm** [comment]
Yeah, that should help. Though the eye icon to the side of the status isn’t entirely clear either, especially as to whether it’s showing the current status or the new status.

I regularly change it, then have to double check by viewing the toot in an incognito window to see if I’ve made the right change.

**Comment by Gargron** [comment]
I'm kinda thinking that toots in the admin UI should not try to look "proper" but instead be presented as a table

**Comment by nightpool** [comment]
heavily disagree. I think what makes sense to show depends on contexts. if
you think those should be in the same rails template for reusability,
that's fine, but I don't see a need to expose so much detail in the normal
user view.

**Comment by ThibG** [comment]
@nightpool I actually think it makes sense to expose that much detail in the normal user view. Indeed, public vs unlisted is useful to know why a toot containing a hashtag isn't searchable by this hashtag, for instance.

**Comment by Gargron** [comment]
How public toots are displayed is a separate issue. I believe that a table view with some attributes being easily skimmable, and some things hidden because they are useless, would be beneficial for the admin view. For example, avatars/display names are a waste of space both on reports page and on the page that lists an account's toots, etc.

**Comment by ThibG** [comment]
Good point about the avatar/display name/handle being redundant (at least for non-boosts).
I think every other info is useful though, but yeah, that's enough differences to think about another presentation entirely I guess.

**Comment by Gargron** [comment]
I think this can be closed now?
