### ISSUE TITLE
Rendering of web page in desktop mode is a little bit too big

### ISSUE THREAD

**Issue by zuglufttier** [tootsuite/mastodon#697]
In the first picture you can see that mastodon gets rendered a bit too big on my firefox (Arch Linux, Firefox 52.01.). I guess it's because of the scroll bars, they cannot be controlled in firefox.

![mastodon_before](https://cloud.githubusercontent.com/assets/3314278/24513592/e2f8e042-1571-11e7-8b78-a62c945dc355.png)

This is my suggestion; I changed the size in css for every row to 25% and removed the spacing. Changing or alternating the color a little bit for every column should work out nicely, plus you don't need to add space in between the columns. 25% width will always be the right value for them.

![mastodon](https://cloud.githubusercontent.com/assets/3314278/24513591/e2d5a28a-1571-11e7-9869-4e8ee1c77c1b.png)

**Comment by zcdunn** [comment]
The columns have a css class of .column and .drawer for the left column. This could be fixed by changing the flex property for these classes from '0 0 auto' to '1 0 auto'

This would also make the columns stretch to fit the screen on larger screens so it's not wasting half the screen.

**Comment by zuglufttier** [comment]
Oh, you're right, just removing the flex property works as well. Looks much better, no further adjustment needed.

**Comment by zuglufttier** [comment]
#667 is the same, actually

**Comment by chrylis** [comment]
I'll sign on to this issue, with the opposite problem: I have a 30" monitor, and it's only taking up 60% of the width! Moving to a percentage-based layout (especially with so many columns) would resolve both cases.

**Comment by hoodiek** [comment]
i would suggest the percentage option, albeit with a button to swap from single-column to multi-column view, so it's easier to not feel real bad about it not letting you use the better option (a thing i struggle with, making me have to zoom out)

**Comment by r-michel** [comment]
On my screen (4k screen with W10 zoom mode at 220%) the columns doesn't use all the available width.
Changing `.column` flex mode to `flex: 1 0 auto` fixed the thing for me.

**Comment by exadeci** [comment]
@r-michel Much better! I've set a small width to Notifications and "Profile" columns because they take too much space IMO

**Comment by ashyon** [comment]
I'd actually really enjoy being able to resize columns myself without having to go into the developer tools. I'd implement it myself but I'm only just becoming familiar with the codebase...

**Comment by dixonge** [comment]
Firefox 49.0.2 - Windows 10

Changing the flex code for `.drawer` to `flex: 1 0 auto` allows the columns to auto-adjust and fill the screen perfectly. Why hasn't this been fixed yet? Does it break something on some other OS/browser combo?

**Comment by Gargron** [comment]
See #3207

**Comment by nhoizey** [comment]
@Gargron so you suggest to remove one 330 pixels column with this new feature, just because the default 4 columns take 1290 pixels on our 1280 pixels wide screens?

`¯\_(ツ)_/¯`

**Comment by r-michel** [comment]
@Gargron I don't see how this is related. Did you see @dixonge suggestion? It's quite simple.
