### ISSUE TITLE
Missing v2.3.3 tag?

### ISSUE THREAD

**Issue by gllmhyt** [tootsuite/mastodon#6971]
Tried to upgrade to 2.3.3 with `git checkout v2.3.3` after `git fetch --all`, but I got `did not match any file(s) known to git`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
`git fetch --tags`

**Comment by Gargron** [comment]
For reference `git fetch --all` just means "fetch from all upstreams" which for most people is just "origin" which is the same as not using `--all` at all

**Comment by nynhex** [comment]
I had no problems pulling `2.3.3`  May be useful to read git documentation as I often times forget certain commands and args.  

@Gargron do you think there's any value in updating the dev/prod guides to give a micro-tutorial.  If so I'd be happy to PR it.

**Comment by nightpool** [comment]
https://github.com/tootsuite/documentation/commit/ffeb3edce14793249e8252cf1eb07cc754dc945d updated the documentation to use `git fetch --tags`. I'm happy considering that a resolution to this issue
