### ISSUE TITLE
Support additional actor types (Service, Group, Organization, Application)

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#6973]
I can't see any good reason for Mastodon not to support additional AS2 actor types, such as `Service`, `Group`, `Organization` or `Application`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by zcdunn** [comment]
Is any other software using these types? What would that support entail?

**Comment by ThibG** [comment]
As far as I can tell, it would just be a matter of accepting more types than `Person`, I don't think there is anything specific to `Person`, really. We should also store the actual type so that we can do different things later. One such thing would be to add a “bot” badge or something to `Service` or `Application` actors for instance.

I think PeerTube uses `Group` to some extent, and Funkwhale attempted to use `Service` but fell back to `Person` as that is the only thing supported by Mastodon.

**Comment by zcdunn** [comment]
I hadn't heard of funkwhale (https://funkwhale.audio), so thanks for mentioning that. 

So mastodon could accept any Actor and display it in a profile column. For Person, nothing would change. We could start treating Service as bot accts, and give them a follow button and bot badge. For every other Actor it could just display the relevant info with no buttons. Then we other software starts using the other types, we can decide how to treat them usefully. 

Is that what you had in mind?

**Comment by Gargron** [comment]
Yes
