### ISSUE TITLE
TM emoji blends in with the column background

### ISSUE THREAD

**Issue by archaeme** [tootsuite/mastodon#6980]
The colour of the TM emoji is similar enough to the column background colour that it makes it hard to discern.
![TM in the column view](https://user-images.githubusercontent.com/802788/38165547-3864eb8e-34e3-11e8-8a1b-dfc304c911ae.png)

For reference, here's how it looks when viewing the post directly:
![TM on direct post](https://user-images.githubusercontent.com/802788/38165552-4e3ab9a2-34e3-11e8-9299-19c9d2361250.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
This is kind of a duplicate of *Add a light background behind "dark text" emojis #5083* I think?

**Comment by archaeme** [comment]
Ah didn't notice that one.  Gonna close this then.
