### ISSUE TITLE
Service Worker Not Worked by iOS 11.3 MobileSafari

### ISSUE THREAD

**Issue by mimikun** [tootsuite/mastodon#6989]
![error image](https://s3-ap-northeast-1.amazonaws.com/mstdn.mimikun.jp/media_attachments/files/000/054/939/original/e155483b242c8ae6.png)

## steps to reproduce	
1. access to [mastodon.social](https://mastodon.social/web/getting-started) by iOS11.3 Safari.
2. Add page to Homescreen.
3. open to HomeScreen Icon.

## environment
iOS 11.3
Mobile Safari

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unasuke** [comment]
fixed in #7500 ?

**Comment by brion** [comment]
The equivalent problem on the instance I use was resolved by upgrade from 2.3.3 to 2.4.0, so I'm guessing that fix did the job. :)

I had some trouble forcing it to refresh, though, immediately after that upgrade. In a pinch you can delete the icon and recreate it and it should clear it up.
