### ISSUE TITLE
Best Practices on Load balancing

### ISSUE THREAD

**Issue by nynhex** [tootsuite/mastodon#6990]
I'm working setting up a 3 front-end node instance and am wondering how folks are load balancing if at all.  I know @Gargron lbs .social, but I'm not sure how he does it.  I saw mentions of nginx balancing upstream, but would be curious as to where the ssl termination occurs, and how things can be stup with a ssl/letsencrypt cert on the balancer and the termination point.  I'm on digital ocean and was thinking of using their load balancer, but not sure if anyone has had any luck.

No so much of an issue but a question.  I've searched but can't find anything usefu.

* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Nginx does the SSL. Load balancing is as simple as using an `upstream` block with the `proxy_pass`

**Comment by nynhex** [comment]
@Gargron that's what I assumed, as far as how you set it up.  I've done the same before.  So basically ther ssl termination happens at the entry point nginx node (I'm using letsencrypt), then it decrypts and sends requests to upstream nodes, yeah?  Just making sure I'm not missing anything.

Cheers!
