### ISSUE TITLE
Security verification failed

### ISSUE THREAD

**Issue by Angristan** [tootsuite/mastodon#7006]
I'm running 2.3.3 and getting these while logging in, in any browser or with any user:

![screenshot_02-04-2018_12-03-49](https://user-images.githubusercontent.com/11699655/38193354-f14cb296-3671-11e8-9517-f62af751d5c4.png)

The only related issue is https://github.com/tootsuite/mastodon/issues/1165 but it's been closed.

In the logs I see:

```
method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=422 duration=4.92 view=1.92 db=0.00
```

I tried restarting all the containers without luck.

**Comment by Angristan** [comment]
TL;DR don't do cache on puma

**Comment by HacMan137** [comment]
@angristan Can you explain your solution a bit more? Running into the same issue and trying to determine what fixes to try.
