### ISSUE TITLE
OStatus/Atom: Remove explicit "nsfw" <category> from CW posts

### ISSUE THREAD

**Issue by MrPetovan** [tootsuite/mastodon#7011]
Hi,

Over at https://github.com/friendica/friendica I noticed that Mastodon posts sent over OStatus that have a Content Warning have a `<category name="nsfw">` set even though it doesn't appear as a hashtag in the text.

We recently improved the way we are showing users why a post is collapsed in Friendica, whether it is because of an author-set CW or a user-defined filter settings (for example, hide posts with the hashtag `#nsfw`). And I noticed that Content Warning posts were also triggering the `#nsfw` filter rule even though the tag didn't appear in the post body.

Semantically, CW and NSFW are serving two different purpose and as such, the `#nsfw` tag shouldn't be automatically tacked on CW posts. If understand correctly, Mastodon posts can be set as "sensitive" without having a CW set, and in this case I believe the `#nsfw` tag still is warranted.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by MrPetovan** [comment]
Here's an example of what I mean when I say CW and NSFW don't have the same purpose: https://mastodon.social/@sanspoint/99790585160960410

**Comment by MrPetovan** [comment]
Here's another one: https://octodon.social/@starbreaker/99791637331942899

**Comment by MrPetovan** [comment]
Here's another one: https://mastodon.social/@rootfs_ext2_gz/99791744750112759

(You get it)

**Comment by Gargron** [comment]
@lambadalambda made me do it for GNU social compatibility :C I never liked that approach

**Comment by Gargron** [comment]
Perhaps we should talk about whether it's now possible to give up on that particular "compatibility" with GNU social

**Comment by MrPetovan** [comment]
Well, now's finally the time to make it right.

I've added a Friendica user switch to disable remote-set content warning, but posts still are collapsed because of this damn fake `#nsfw` hashtag, which makes me open every `#nsfw` post, which negates the usefulness of the actual tag.

**Comment by lambadalambda** [comment]
I thought the implicit #nsfw tag is for sensitive posts, not for CWs. or are all CWs automatically sensitive?

**Comment by MrPetovan** [comment]
I can confirm not all CW are automatically sensitive. So maybe my remote contacts set their toots as sensitive *and* set a CW? I'm going to ask them.

**Comment by Cassolotl** [comment]
I do know that if there is a CW images are force-hidden. So I think CWs force #nsfw?

**Comment by MrPetovan** [comment]
This Mastodon post has a CW but isn't marked as sensitive, so it isn't set automatically: https://mastodon.social/@sanspoint/99829985644795683

I guess the remaining problem lies with the actual "nsfw" term usage.

**Comment by MrPetovan** [comment]
Thanks!

**Comment by lambadalambda** [comment]
@MrPetovan see the code at https://github.com/tootsuite/mastodon/blob/master/app/models/status.rb#L324, CW'd posts are always sensitive.

**Comment by MrPetovan** [comment]
@rogerbraun The problem was in the OStatus representation of the status, not in ActivityPub that we don't support at Friendica yet.

**Comment by MrPetovan** [comment]
Is the signal for sensitive status in ActivityPub a user-land tag arbitrarily added to posts? If not, then we're in the clear.
