### ISSUE TITLE
Dev tool request: Take React Storybook into use

### ISSUE THREAD

**Issue by atakiel** [tootsuite/mastodon#7013]
Start using [react storybook](https://github.com/storybooks/storybook). 

# What is
React storybook is a simple ui development environment that allows developing react components separately from the rest of the application.

# Pros
* No need to start whole mastodon dev server when doing simple front-end development. Storybook server is enough.
* Favors splitting components into smaller story-sized bites.
* Favors separating components from their data sources.
* [Easy to setup](https://github.com/storybooks/storybook#getting-started) and [use](https://github.com/storybooks/storybook#intro).
* Can be taken into use when needed, component by component.
* Storybook acts as a simple way to list and view all the components in the project.

# Story organizing conventions

If storybook is taken into use in a project this size, it's good to keep stories next to the components they are written about. That is, in the same folder and with a name `*.stories.js` ([instructions](https://storybook.js.org/basics/writing-stories/#loading-stories-dynamically) for doing this).

i.e.
```
components
  - first-component.js
  - first-component.stories.js
  - second-component.js
  - second-component.stories.js
```

Additionally, if stories in a specific file require larger amounts of example data, the data is handy to keep in a separate file, named e.g `*.stories.data.js`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
We had react-storybook in the past (#91, #4397) but nobody was making use of it so we removed it again. I highly doubt that anyone will suddenly start using it *this* time, so it's a no from me.

**Comment by pawelngei** [comment]
I'd like to use Storybook to develop some more features, since I don't see an easy way to generate content (posts, notifications, users) to test the components with right now.

Should I make a PR without the Storybook commits, just the features?

@Gargron
