### ISSUE TITLE
Remove arbitrary password length limit

### ISSUE THREAD

**Issue by rugk** [tootsuite/mastodon#7015]
Trying to register at an instance ended up with an error message "Password is too long". 

Passwords longer than 72 characters were rejected. That is nonsense and when you hash passwords properly (which i assume, you do) all input becomes the same equal-length output, so there is no need to limit the size of the input, as the output can always be stored.
That's why password length limits are usually a sign for a warning sign as it may be that passwords are not hashed. And in any case, you prevent people from using long, secure passwords, without any reason.

See https://stackoverflow.com/questions/98768/should-i-impose-a-maximum-length-on-passwords#98786 for reference.

*Disclaimer:* I am not a mastodon admin, so I don't know whether that feature is configurable. If it is it should be:
* length-unlimited by default
* carry a big warning that limiting the length is useless and senseless
* or just probably remove that whole feature

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
>length-unlimited by default

There is a processing cost associated with super long strings. It doesn't make sense to allow unlimited length strings. I could raise 72 characters to 128 or 254, it's arbitrary, but people usually don't make passwords that long (you're the first to complain).

>(which i assume, you do)

With the code being available for review, you don't have to assume. Yes, passwords are hashed with bcrypt.

**Comment by rugk** [comment]
Maybe needs some research, but I doubt the processing cost is big for any string length, as you only do it once per login request/registration. AFAIK hashes should also be more or less constant time, not depending on the input.

BTW I think 128 chars are quite reasonable, as that is the longest pw the generator of KeePassX(C) allows when only moving the slider.

**Comment by ThisIsMissEm** [comment]
Looking at the code, it'd be trivial to change the password max-length to something higher, it's a one-liner in config/initializers/devise.rb:224

**Comment by patf** [comment]
The 72 character limit is inherited from bcrypt, which has a limit of 72 bytes for the password parameter. Longer inputs are silently truncated:

```ruby
irb(main):006:0> pw = BCrypt::Password.create('yiaR1dUjKj9lZ0bcc5d2yiaR1dUjKj9lZ0bcc5d2yiaR1dUjKj9lZ0bcc5d2yiaR1dUjKj9lZ0bcc5d2')
=> "$2a$10$RiqpCb8c/xemMBVerBDGeONIkYjO9yMuoFaja.PvOHqvm8J.oPqyi"
irb(main):007:0> pw == 'yiaR1dUjKj9lZ0bcc5d2yiaR1dUjKj9lZ0bcc5d2yiaR1dUjKj9lZ0bcc5d2yiaR1dUjKj9lZ0bcc5d2'
=> true
irb(main):008:0> pw == 'yiaR1dUjKj9lZ0bcc5d2yiaR1dUjKj9lZ0bcc5d2yiaR1dUjKj9lZ0bcc5d2yiaR1dUjKj9lZ0bcc5d3'
=> true
irb(main):009:0> pw == 'ziaR1dUjKj9lZ0bcc5d2yiaR1dUjKj9lZ0bcc5d2yiaR1dUjKj9lZ0bcc5d2yiaR1dUjKj9lZ0bcc5d2'
=> false
```

(The input here is a string with 80 characters. Note that the password matches when the last character is changed.)

Some implementations add an additional hashing step prior to the bcrypt operation to avoid this, but there's no consensus on this. 72 characters should be good enough for everyone.

**Comment by Gargron** [comment]
Okay, thanks! Closing

**Comment by Wild1145** [comment]
Would like to re open this discussion. I've ran into the limited char issue earlier today and initially assumed passwords were not being stored in a secure way (which doesn't appear to actually be the case) however it is annoying that I have to reduce my password manager password complexity for Mastodon. 

If nothing else this generally is a red flag from a PR perspective that credentials could be being store in plain text or otherwise poorly secured. Either increasing the limit to 513 or unlimited would be ideal outcomes.

**Comment by ThisIsMissEm** [comment]
As for the security concerns over a max-length of 72, there's several mitigations in place:

1. The server rate-limits sign in attempts to 25 per 5 minutes: https://github.com/mastodon/mastodon/blob/main/config/initializers/rack_attack.rb#L132-L134
2. You can use 2FA or WebAuthn which mean guessing the password (72 characters, so 471.60 bits of entropy by using upper, lower, symbols) wouldn't give account access.

Either way, for an online attack, you're looking at near impossibility. More likely is an offline attack, where someone has the database dump and tries to guess the password by brute force.
