### ISSUE TITLE
Text overlaps with elephant art (again) [BUG]

### ISSUE THREAD

**Issue by yiskah** [tootsuite/mastodon#702]
Oops, a recent update makes it so, at least on my Firefox 1366x768 Windows computer, the text totally overlaps with the elephant art and is not readable. Didn't we fix this earlier?

![capture](https://cloud.githubusercontent.com/assets/12243190/24553231/7beb1768-15f7-11e7-9713-f454314f8558.JPG)

We really shouldn't be having this happen if we want to look like a viable twitter alternative and not a messy unfinished project.

**Comment by ticky** [comment]
This should’ve been fixed by #764!

**Comment by ashfurrow** [comment]
Looks like this is fixed, at least as far back as 1.2.2. I'm going to close but if you're still seeing the issue, please re-open. Thanks!
