### ISSUE TITLE
Hagstags column

### ISSUE THREAD

**Issue by moshpirit** [tootsuite/mastodon#7023]
On GNU social we can follow hagstags and groups, which is really nice, but I noticed we can't do that on Mastodon. On the other hand, we can add specific columns for *pinned* hagstags. Would be possible to have a column for "following" hagstags where several hagstags were mixed? like one column to rule them all pinned hagstags instead of several of them. It could be a configuration option of the pinned hagstags, like "show in hagstags column" which would hide this specific column but add this pinned hagstag to a column with more of pinned hagstags that are been also checked on this "show in hagstags column" option. 

This would create a more customized environment, since make following hagstags easier and would improve this feature that differentiate Mastodon from Twitter.

------------
**So, in resume:**

NOW: Pinned hagstags on different columns
FEATURED: That and also the possibility to instead of seeing them in different columns, have several of them in one column. 

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
Related issues:

* Join several hashtags in a search/column #6359
* option to follow hashtags #1096

**Comment by moshpirit** [comment]
Sorry!
