### ISSUE TITLE
Image focus point picker is broken

### ISSUE THREAD

**Issue by mbajur** [tootsuite/mastodon#7024]
Hi, today i noticed that image focus point picker is broken on my instance. There is no error in js console nor anything handy. This thing happens and that's it:

![kapture 2018-04-03 at 14 34 32](https://user-images.githubusercontent.com/581569/38249642-a991602e-374c-11e8-966d-99c416c381f9.gif)

I'm on Mastodon 2.3.3, it's address is https://hcxp.co - feel free to register and check it out. I've tested it on mastodon.social but the issue is not there so that's something specific to my instance. Tested on Chrome, Safari and Firefox.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [2.3.3](https://github.com/tootsuite/mastodon/releases) and not on `master`

**Comment by Cassolotl** [comment]
The exact same thing happens on ephemeral.glitch.social. I told @beatrix-bitrot and Bea told Gargron, I think. It's good that it's on the issue list now, I was wondering if it was just me!

**Comment by ThisIsMissEm** [comment]
Can you check the console and let me know if you're having an error loading the uploading image? (should be a warning about a failed network request) — I can reproduce it due to that.

**Comment by ThisIsMissEm** [comment]
I've narrowed the regression down to: https://github.com/tootsuite/mastodon/pull/6944/

I'm not sure what the breakage is, but that PR seems to have introduced the regression.

**Comment by ThisIsMissEm** [comment]
Essentially, the panner shows, but fails to render correctly (for some reason has zero height and width) — not only that but the functionality said to exist in ZoomableImage doesn't work correctly. I would suggest we remove zoom / pinch until we can rewrite that functionality.

At the minimum, I'd say #6944 should be reverted — it appears to have not been properly tested. This has been done in #7035
