### ISSUE TITLE
Toots being posted multiple times in duplicate?

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#7033]
Not sure what might be causing this, but while perusing this thread (https://mastodon.social/@Gargron/99798054496158900) about webmentions, I noticed @Gargron had many duplicate toots.

![image](https://user-images.githubusercontent.com/10606431/38282426-9fefb826-3775-11e8-8ac1-2a4033a029ab.png)

![image](https://user-images.githubusercontent.com/10606431/38282384-6a78eeec-3775-11e8-9ce3-3daebf86fcb5.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). -- 2.3.3

**Comment by Gargron** [comment]
mastodon.social was down and I was resending my toots. The part that was broken was the one that deals with the idempotency key, as I understand. I don't think this warrants an issue.
