### ISSUE TITLE
Allow admins to change user e-mails in the UI

### ISSUE THREAD

**Issue by LeoTindall** [tootsuite/mastodon#7034]
It would be good if admins could change the user's e-mail, in case for instance that e-mail is no longer available or incorrect and the user is unable to log in.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThisIsMissEm** [comment]
I've started this in https://github.com/tootsuite/mastodon/compare/master...Unobvious-Technology:feature/admin-change-email?expand=0

However, I don't have too much time to finish it right now. I was going to allow updating display_name too, but simple_form completely chokes on that field, for no apparent reason.

**Comment by ThisIsMissEm** [comment]
This issue can be closed, as it's implemented in https://github.com/tootsuite/mastodon/pull/7074
