### ISSUE TITLE
Do not show the QR code when user has enabled 2FA

### ISSUE THREAD

**Issue by gordonzola** [tootsuite/mastodon#704]
In 2FA, QR-code is a shared secret, that should only be shared once (when the user enables 2FA). Then, the authentication works as a challenge-response communication.

In the current Mastodon version, when a user visits the “2FA” page, and 2FA is already activated, Mastodon reminds her the shared secret (the QR). This would permit any attacker (by MitM or direct access of an unlocked session) to steal the secret, and generate valid tokens, thus heavily reducing the 2FA’s security.

The procedure for 2FA activation should:
- display the QR-code
- ask the user for a proof that she can generate valid TOTPs
- if we received a valid TOTP, 2FA is enabled
- 2FA settings page only says that 2FA is enabled, and don’t show the QR-code, nor stores it in database

The “Disable 2FA“ button is also vulnerable, because a simple valid POST request can disable it. The most simple workaround is to ask for the user’s password before accepting to disable 2FA. A more secure option would be to double the password with a token sent by mail or phone, but Mastodon doesn’t have this information (and should not have it without a good reason).

For information, this issue follows this discussion: https://mastodon.social/@gordonzola/1388199

**Comment by heartsucker** [comment]
> nor stores it in database

Uh. How do you propose the server verifies the 2FA code? It needs the secret + current time to generate the code so it can check it against what the user submits.

See:
https://github.com/freedomofpress/securedrop/blob/e95964fcf15a2ce82e587638cf0f84be31faf787/securedrop/db.py#L384
and
https://github.com/freedomofpress/securedrop/blob/e95964fcf15a2ce82e587638cf0f84be31faf787/securedrop/db.py#L335

**Comment by heartsucker** [comment]
> A more secure option would be to double the password with a token sent by mail or phone, but Mastodon doesn’t have this information (and should not have it without a good reason).

Just have them submit pw + 2FA token and have the endpoint do a check on both before disabling 2FA for the account.

**Comment by MikeASchneider** [comment]
Aside from the security concerns, this ticket is really important as a UX issue. It's really important that the site ensures that you have correctly set up 2fa before it's actually enabled. Otherwise it's potentially a two-click path to being locked out of your account!
