### ISSUE TITLE
Add option to block follows from domains hidden by user

### ISSUE THREAD

**Issue by NekomataEsp** [tootsuite/mastodon#7046]
I'd like the option to block follow requests/follows from domains that I have hidden as a _user_ via the interface. 

There are certain instances I do not want to interact with whatsoever, and I understand that others on my instance might want to, so asking for a block on an instance wide level is against my personal interest as I do not want to enforce my wishes onto others from my instance.

This is an illustrative example of how this could be implemented UI wise, like how the dialog box for muting works currently

![suggestion](https://user-images.githubusercontent.com/38084444/38330290-776c3b28-3850-11e8-87d8-01d95180d2b1.PNG)

(ps: I've never done any feature request or bug report on github before, sorry if I did anything wrong)

Edit: I should note that as it is right now, follows/follow requests can still be made from hidden domains. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
Thanks for your feature request :)

**Comment by ryliejamesthomas** [comment]
May be worth looking at the [Subway Tooter codebase](https://github.com/tateisu/SubwayTooter), as it has this functionality.

**Comment by shanecav84** [comment]
I'd like to work on this, unless someone has already started.

**Comment by shanecav84** [comment]
Looks like https://github.com/tootsuite/mastodon/pull/2381 implemented all of the necessary backend. We just need the UI.

**Comment by Gargron** [comment]
This is already default behaviour though. Perhaps it wasn't at the time the issue was opened, at least not completely, but the system has been reorganized in #7765
