### ISSUE TITLE
New user onboarding/orientation modals [improvement]

### ISSUE THREAD

**Issue by yiskah** [tootsuite/mastodon#705]
Right now, new users essentially need to be guided through getting started by helpful active users jumping in and welcoming them and answering questions. This is not sustainable.

I suggest that when a new user logs in for the first time, they are presented with an "orientation" of modals guiding them through the interface basics.

I have created an (ugly) mock-up in powerpoint: https://drive.google.com/file/d/0B8SQnHoEXiYOQVBscG5GVXRlRXM/view?usp=sharing

Of course it doesn't have to be just like this but this is my suggestion

**Comment by yiskah** [comment]
It's been suggested that such a tutorial would have a prominent "skip" button or something that says "Would you like a tour?" which imo makes sense

**Comment by braak** [comment]
Some sites show little circles next to UI elements that you can click for an explanation. Hints are also helpful when introducing new features.

**Comment by yiskah** [comment]
We currently have tooltips if you have your cursor. Having an info icon is a separate feature. Users who need a tour front and center will not notice an info icon though.

**Comment by ashfurrow** [comment]
@yiskah With #1883 and #1964 merged, do you think we should close this issue? Or keep it open for further discussions around onboarding new users?

**Comment by yiskah** [comment]
Yes.
