### ISSUE TITLE
ERROR in __offline_serviceworker from UglifyJs: Unexpected token keyword «function», expected punc «,» [__offline_serviceworker:813,47]

### ISSUE THREAD

**Issue by saper** [tootsuite/mastodon#7055]
As of b08ab329f4d149fd414e0539574f49062c571a8a when trying to run `yarn run build:production` one gets the following error:

````
    ERROR in __offline_serviceworker from UglifyJs
    Unexpected token keyword «function», expected punc «,» [__offline_serviceworker:813,47]
```` 
Downstream issue: https://git.pleroma.social/tyge/mastofe/issues/7

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
I cannot reproduce this. Is it still an issue for you?
Also, the recommended way to build the web UI is through `bundle exec rails assets:precompile`, although it then relies on additional Ruby stuff…
