### ISSUE TITLE
Emojo federation

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#7069]
I wanna be able to use `:red_candle@witches.town:` from cybre.space.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
We already talked about this when we implemented custom emojis, and we decided not to implement it for various reasons (licencing, cluttering the suggestion, the easiness of copying the emojis from other instances already, ...). Closing.

**Comment by SoniEx2** [comment]
Licensing is precisely why you should do this. We should work towards subverting licensing, as it is bad.
