### ISSUE TITLE
Show replies on home feed / Discourage subtooting

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#7076]
The home feed should show replies, regardless of who's being replied to.

This would discourage subtooting. Subtooting is evil and we should put an end to it. Since other attempts at discouraging subtooting have failed (#6304), I'm trying the "no matter the costs" approach this time. This is also *much* simpler to implement than what's described in #6304.

This also has the side effect of encouraging discovery of new ppl through replies. Since you can see the replies, you can also see who's being replied to, and then you can look at their profile and stuff and decide if you should follow them or not.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
Subtooting is usually original posts, no? I don't think this would help and also it sounds like I would end up seeing a lot of replies that I don't want to see, which would be very annoying!

**Comment by MightyPork** [comment]
yes, subtooting isn't usually a reply

**Comment by SoniEx2** [comment]
subtooting is when you reply without leaving a reply.

subtooting includes things like `LB: ...` toots.

this very issue is kinda like subtooting.

**Comment by MightyPork** [comment]
Showing replies without the @ tag won't put LB toots or stand-alone sub-toots into your home feed, they are not replies.

**Comment by SoniEx2** [comment]
Showing replies means ppl don't need to use LB or subtoots - they can just reply and have the same effect.

**Comment by Cassolotl** [comment]
> subtooting includes things like `LB: ...` toots.

That's not subtooting, because anyone can see who you're talking about. Usually when people reply and then remove the @ tag and then put `LB:` they want to leave a commentary attached to the original toot.

Whereas subtooting is talking about someone publicly in a hinty subtext way without naming them or connecting the toot to them in anyway.

The change you are proposing will not stop people from subtooting.

**Comment by SoniEx2** [comment]
If I see the OP, can I reply to the relevant "LB" toots, which I don't see?

Can I go on a toot's replies and see the "LB" toots?

I can't. That's the problem.

**Comment by Cassolotl** [comment]
Yeah, when you click the post and it opens in the far right column, you can see all replies to that toot, even if there's no one tagged. See:

![screen shot 2018-04-08 at 22 04 42](https://user-images.githubusercontent.com/6607512/38472491-deb8acdc-3b78-11e8-9b6a-1cc207cfec8f.png)

**Comment by Gargron** [comment]
Subtooting cannot be fixed through technology, because subtoots by definition are not posted in a way that would thread them to the original poster.

**Comment by SoniEx2** [comment]
They can be fixed through a combination of technology and moderation. However, it's rather difficult when you lack the technology.

**Comment by kaniini** [comment]
> There is no subtooting on IRC, and IRC has a healthier culture than social media.

There is literally an IRC channel in existence dedicated to talking massive shit about the OP.  If that isn't subtooting, I don't know what is.

**Comment by SoniEx2** [comment]
Usually on IRC you just say whatever in whatever channel it's relevant.

So you just tell the channel operators they're assholes... in their channel.

Much healthier.

**Comment by feld** [comment]
> There is no subtooting on IRC, and IRC has a healthier culture than social media.

This can of possibly be further from the truth.

You should work on subtoot filtering for the Oculus so if someone decides to comment about your ridiculous VR goggles glued to your head and ignores your presence in real life you have a safe space thanks to technology. 👍

**Comment by SoniEx2** [comment]
Clearly you haven't heard of shouting at the ops in public. Happens all the time.

A lot more often than talking about them on unrelated channels.

**Comment by trwnh** [comment]
>Saying that replies without @ tags should appear in the Home timelines so that people don't have to boost themselves to make sure that their commentary is seen, that seems okay. But forcing people to read all replies in their Home timeline sounds like a huge overwhelming mess.

Agree in principle, as I said on #7080. Although, early Tweetdeck (Adobe AIR version) had an option to show all replies in your home column. So while it can be overwhelming, it's still something that some people would want in certain cases.

**Comment by trwnh** [comment]
>Subtooting originated from broken capitalist social media and its sole purpose is to incite drama, which in capitalist social media means views which means revenue and so on.

Alternatively: "subtooting" is really just talking about someone without them knowing. There is nothing fundamentally wrong with saying something about someone without notifying them. In much the same way that automatic webmentions were cited as a concern on #6074, notifying someone should involve their consent somehow.

**Comment by redtachyons** [comment]
@SoniEx2 Commenting here since I could not find any direct contact links in your profile. It will be great If you can be more respectful towards the community. Thanks
