### ISSUE TITLE
New search bar is too difficult to see due to low contrast

### ISSUE THREAD

**Issue by yiskah** [tootsuite/mastodon#708]
Right now the contrast between the search bar and the backdrop is way too low that it doesn't look like it's there. It just looks like the compost box is weirdly low down. I suggest putting the search bar back inside the container so it's more visible.

**Comment by wavebeem** [comment]
Another idea: the search bar could be white like the compose toot area (it is a text input, after all).

**Comment by Cassolotl** [comment]
Is this fixed by *Separate high contrast theme #7213*?
