### ISSUE TITLE
"Comment"/"LB" button

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#7080]
There should be a "comment" button which is like the "reply" button but makes a public comment.

It prefixes the new toot with "LB: " automatically, and boosts the OP, and boosts itself, and creates a reply to the OP but without mentioning the OP.

The button icon could just be "LB".

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThisIsMissEm** [comment]
There’s already prior issues discussing “quote tooting”, which has presently been decided that it’s not a good idea due to potential for use in harassment (I disagree)

For now, why not comment & then boost your own comment?

**Comment by SoniEx2** [comment]
This isn't quote tooting.

Quote tooting = webmentions.

This is different, and already possible today.

And the point of this feature request isn't to talk to YOUR followers. The point is to talk to MY followers.

E.g. I make a toot, someone LBs it, my followers can see the LB by looking through my toot's replies.

Ofc I'm probably the only weirdo who looks at toot replies, but that's a different (social) issue.

**Comment by ThisIsMissEm** [comment]
Perhaps I’m misunderstanding this LB idea, but isn’t the LB just a reply that has been boosted to your followers? 

That is, your followers can already see my reply to your toot, so all the LB does is boost my reply to my followers, which is essentially the same as me posting a new toot, and then that too somehow getting magically linked to another toot’s replies.

**Comment by Aldarone** [comment]
It's a shortcut for boosting a toot and then replying to it without mentioning its author.

It saves exactly one click.

**Comment by ThisIsMissEm** [comment]
I'm sceptical as to whether it's needed, though I still trying to understand it.

**Comment by Cassolotl** [comment]
Considering how little space there is to work with, I think adding a button for something that saves such a small amount of work is a bad idea.

1. Click boost
2. Click reply
3. Delete tag, type LB, type message, send toot
4. Boost self

I think making replies-without-tags show up in all Home feeds without having to be self-boosted is a good idea, because it's how people add commentary with a link back to the original post, and it's as close as we get to a quote-toot. But there is very strong anti-quote-toot sentiment from people around her (including the lead dev) that I'm wondering if even that wouldn't make it in.

**Comment by Cassolotl** [comment]
> E.g. I make a toot, someone LBs it, my followers can see the LB by looking through my toot's replies.

This is already possible.

**Comment by trwnh** [comment]
I'm open to showing untagged toots in the home timeline even if they have a parent. Not really open to having yet another button for a niche task.

**Comment by SoniEx2** [comment]
There are 2 kinds of LB toots: those that go through the "reply" button, and those that don't.

When you click the "reply" button, the original toot appears in the compose box, the original toot is correctly "linked" in your LB, and anyone staring at the original toot's replies sees the LB. Additionally, the ppl who have boosts disabled on the home feed don't see this kind of LB - this is a good thing, since they also don't see the original toot.

When you don't click the "reply" button, there's no way to find your LB through the original toot, the conversations are completely separate, the relevant boost may not be immediately obvious, ppl may see the LB without seeing the original toot, and the original toot doesn't show up in the compose box.

I'd rather show toots in home timelines based on if their parent is also visible, tbh. Obviously nobody here actually uses "don't show boosts in home timeline". /s

**Comment by wxcafe** [comment]
open a separate issue for only showing toots if their parent is visible, then. There's no need to make a new reply button. Closing.

**Comment by SoniEx2** [comment]
I did, nobody liked it. #6304
