### ISSUE TITLE
Make user statuses available when not authenticated

### ISSUE THREAD

**Issue by DagAgren** [tootsuite/mastodon#7087]
Currently, it seems that /api/v1/accounts/:id/statuses return 401 if you are not authenticated.

My client supports browsing timelines and statuses before logging in, but this breaks showing user pages.

It seems a bit strange that this endpoint requires authentication, since it is publicly visible through the web interface. Could it be changed to work when not authenticated?

(I think the same applies to /api/v1/accounts/:id but I haven't looked into it properly.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThisIsMissEm** [comment]
I'd disagree with this, at a minimum you should have to be authenticated as an application, as to prevent data scraping and misuse of information. I'd argue that completely unauthenticated access to mastodon APIs will result in misuse of the APIs.

**Comment by DagAgren** [comment]
But scraping does not stop a determined attacker, but it does stop legitimate use.

Does authenticating as an Application really allow any useful limitation? You can freely register new applications, can't you?

**Comment by DagAgren** [comment]
I don't think they are tied to a user? My app creates an application for itself, and it provides no user information.

**Comment by Gargron** [comment]
Applications are not tied to a user. However, while it's not part of the admin UI, it's possible to block access to an application and to temporarily disable new app registrations in case it's needed, so *theoretically*, requiring app credentials *is* a layer of security.

However, that's not *overly* practical, and the public timelines have been exposed without that requirement for many months (after that was highly requested), so I can honestly see both points and that's the worst because I don't know which side to pick :thinking:

**Comment by DagAgren** [comment]
It seems we have two separate issues here:

First, some data is publicly available (timelines), and it would make sense to expose more data that is already available through the HTML interface (statuses, accounts).

Second, it might be good to protect the publicly available data somehow. Currently, it is not protected. This would require implementing a way to authenticate somehow without a user (is it even possible at the moment?), and it would make sense to apply it to ALL publicly accessible data, not just some of it. However, that would break any client that is currently accessing the data with current endpoints.

This issue is really just for the first of these, so perhaps a second issue should be created?

**Comment by DagAgren** [comment]
@Gargron Also, if you theoretically did disable new app registrations, you would also at the same time prevent at least new users from logging in with any app, I think? That seems less than ideal.

**Comment by qguv** [comment]
@DagAgren Submitted PR #8457 that would allow admins to open up `/api/v1/accounts/:id/statuses` to unauthenticated API users. You also mentioned `/api/v1/accounts/:id`, but it was already open.

**Comment by maxf** [comment]
Mastodon servers already offer unauthenticated RSS and Atom feeds of a user's statuses. So isn't adding JSON just exposing the same information in a 3rd machine-readable format? 

If there is indeed a concern with data scraping and misuse of information then feeds should also be behind authentication.
