### ISSUE TITLE
Notifications should have a hard limit on the image size

### ISSUE THREAD

**Issue by Oreolek** [tootsuite/mastodon#7090]
The avatar size in Mastodon is a configurable option, right? So it's a sensible choice for the admin of an instance to set avatars to 600x600 (because retina 300x300).

Only when an user with a non-Retina display gets a notification from this instance, the push notification would have a 600x600 image illustrating one-two lines of a toot. Which is not sensible at all.

So my proposal is to limit the avatar size **in web notifications.** Unlike the page styling, the notification styling is hardcoded, so it should have hard-coded sizes.

This is a very serious issue because the user [has no control over notification size.](https://superuser.com/questions/1311661/how-to-disable-images-in-firefox-push-notifications)
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
I don't know what you mean.

The avatar size isn't a configurable option. Is your problem that your web notifications get scaled to the size of the image and as such are big for small messages?

**Comment by codl** [comment]
I can't reproduce this.

The notification sender's avatar [is set as the notification's `icon`](https://github.com/tootsuite/mastodon/blob/41452e83028148b3ef6e5888e9bd3b16fd608ec7/app/javascript/mastodon/actions/notifications.js#L63) and should be scaled down to an appropriate size by your platform's notification system (as opposed to `image`, which tends to be larger if it is displayed). If it doesn't then that's a bug with your platform's notification system, not with mastodon.

**Comment by mal0ki** [comment]
This is definitely still an issue: 

![image](https://user-images.githubusercontent.com/28316305/40080441-3db7349a-588b-11e8-8f56-f9642da5955c.png)
>https://mastodon.kotobank.ch/@vaartis/100034089249580365

**Comment by lyze237** [comment]
I don't really think that this is a problem for a website.

Basically the website has no idea how big you want your notifications to be.

For example I want my notifications on my desktop pc to be 250x100px while I want them to be a different since on my laptop.

Now I'd need to change the notification size for every website specifically.

Therefore I'd suggest that this is a probelm of the notification daemon and needs to be set there instead.

**Comment by Gargron** [comment]
I don't think there is anything we can do on our end, the bug should be raised with the OS you are using
