### ISSUE TITLE
GIFs in .status-card autoplay regardless of GIF autoplay settings

### ISSUE THREAD

**Issue by ilianaw** [tootsuite/mastodon#7093]
This is a difficult problem to solve technically but I want it to be tracked because it just occurred and made me nauseous.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
>GIFs in .status-card

Do you mean after click-to-play?

**Comment by codl** [comment]
GIF profile banners, I believe?

**Comment by ilianaw** [comment]
I don't know enough lingo to describe the issue so here's a reproducer.

https://cybre.space/@iliana/99830982137594526

On cybre.space, viewing this toot in web results in an animation in the rightmost column.

**Comment by ThisIsMissEm** [comment]
We could use https://jnordberg.github.io/gif.js/ to automatically convert gifs to images for the embed card if their browser supports it
