### ISSUE TITLE
Unable to make new archives

### ISSUE THREAD

**Issue by andoruB** [tootsuite/mastodon#7097]
Not sure if this is related to #6765, but in the "Data Export" section of the Settings, I've tried to make a data/toots archive a few days ago as a test. Now since I added more toots and media to my account, I wanted to make a new archive, but I no longer have that option, I can only download the archive I made a few days ago.
I'm not sure if this is expected behaviour, or the instance I'm using has some issues...
Version used on the instance is 2.3.1

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
7 days cooldown

**Comment by andoruB** [comment]
@Gargron: Thanks. However, could this be mentioned on the data export page itself?
