### ISSUE TITLE
add media and favourite button hiden by document_fonts

### ISSUE THREAD

**Issue by bananistan** [tootsuite/mastodon#7110]
hello!
i know it's a personal config related issue and not a bug per se but it only happens on the mastodon site (twitter and buttons on other sites work fine)

when firefox browser.display.use_document_fonts = 0 
the upload media button dissapears completely and the favourite button gets replaced by a ","
sorry if i annoyed you with my silly request :P

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThisIsMissEm** [comment]
Hi! Try going to settings and enabling "use system fonts"

**Comment by Gargron** [comment]
I think it's because the icons are a font. See also #1469

**Comment by Gargron** [comment]
Duplicate of #7914
