### ISSUE TITLE
[Web UI] Parse "LB" toots

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#7111]
(This sent too soon for some reason)

Parse LB toots, convert to reply, and self-boost.

This would make the LB toot visible to your followers, assign it the same conversation ID as the thread (allowing ppl to properly mute the thread and any conversation related to it), as well as mark it as a boost (makes it less confusing if boosts are hidden from the home feed, as you get a "dangling LB" otherwise).

("no such thing as a technical solution to the problem" my ass)

An "LB" toot is a toot matching `/^LB:? /`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I don't think we should be converting toots to replies - it wouldn't be expected behaviour, so people would have their toots connected to other toots in a surprising way and it's like, messing with their posts without their knowledge.

**Comment by SoniEx2** [comment]
so much for trying to fix subtooting :/

**Comment by mal0ki** [comment]
@SoniEx2 Hey, I appreciate your concerns on this issue, and I see some valid points you're raising, however, starting a new issue with a quote from a closed issue and replying to it with "my ass", is out of line. 

If you want to discuss a feature request, you need to  be open to what other people have to say, you need to be open to that it may not turn into exactly what you want, but rather think of it as that we're exploring the subject and ideas together. 

Thank you for understanding. 

And I will close this issue.

**Comment by SoniEx2** [comment]
You don't seem to want to discuss it so what's the point?

**Comment by trwnh** [comment]
More to the point: I think it would be a bad idea to perform any action automatically that the user would be unaware of, or that they would not consent to.

Referring to something indirectly is the choice of the user. Having something be automatically linked, even without explicitly notifying them, is not always desired behavior.

And even if it were, auto-parsing 'LB' is a poorly-defined convention for doing so. It hearkens back to the historical inconvenience on Twitter of not being able to start any tweets with certain "reserved" letters, which was a holdover from SMS shortcodes -- and wasn't fixed until *very* recently.

I think there's still some discussion to be had about the antipattern of using LB or LRT to refer to something you just reshared, but it doesn't seem like something to implement an entire macro workflow for. Although with that said, user-defined macros would be interesting... (but ultimately too complicated to include as a feature unless someone was willing to sponsor it)

**Comment by SoniEx2** [comment]
I don't like the idea of contributing to a toxic culture where ppl both a) don't care about UX and accessibility and b) talk about ppl behind their backs.

parsing "LB" solves both of those. so would having an instance rule for it, but that puts a lot more effort/strain on the user, making the user more likely to switch (to e.g. twitter).
