### ISSUE TITLE
Referrer URL for links clicked within web app point to whatever is in the last column

### ISSUE THREAD

**Issue by TheInventrix** [tootsuite/mastodon#7115]
I recently posted an itch.io link on mastodon - which is relevant because it has basic analytics tracking built in and that is how I discovered this.

Due to the way that the mastodon web client loads things into the last column, the address bar for the site changes depending on what you have open - the timeline, a specific status, the Getting Started page. As of this moment, what is in the address bar is *also* what is sent as the referrer address when you click a link. I don't know enough of how it works to say whether there is a way to specifically set the referrer address, but I feel as though there should be - and if there is not, then the current behavior for altering the last column view should be reevaluated.

As a couple examples that are actually present in my itch.io analytics *right now*, without divulging identifying information:
- Someone on instance A clicked on the link while they were viewing the account of N (who is on another instance), so the web-view account profile for N is the referrer link, giving me the local ID for that remote account.
- Someone on instance B clicked it while they were viewing a status by account M (again, on another instance), so the referrer link is pointing to that status.
- Someone on instance C clicked it while they were viewing their local timeline.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by TheInventrix** [comment]
@trwnh Neither the account in question nor the status being pointed at posted the link.

**Comment by trwnh** [comment]
Ahhh, so it's giving the *wrong* referrer, okay -- in other words, it's most likely caused by expanding a status and then clicking a link on an unrelated and unexpanded status in one of the timelines.

**Comment by TheInventrix** [comment]
@trwnh That is the behavior I described, yes. It is using whatever is open in the last column as the referrer. See: the title of this issue.

@codl Is that something you'd set in e.g. nginx as opposed to a change in the code? If it is, I'll look up how do it on mine and it might be a good idea if it gets added to the sample nginx configuration in the documention.
