### ISSUE TITLE
Paperclip 6.0 might break Google Cloud Storage

### ISSUE THREAD

**Issue by bremensaki** [tootsuite/mastodon#7120]
In some quick testing on my fork, https://github.com/tootsuite/mastodon/pull/6754 seems to break Google Cloud Storage used in S3 compatible mode. Should any config changes be necessary with the upgrade? 

I haven't been able to test in isolation yet, just wanted to see if anyone else is in a position to verify this behaviour. I deployed a build a few commits past 2.3.3 accidentally at one point under my current config files, and started seeing a bunch of "invalid credentials" kind of errors connecting to storage. Reverting this single commit and going back to 5.1 resolves that completely.

Will this need a heads-up when it hits a tagged release? Can anyone see if this happens on any other not-really-S3 storage providers?

**Comment by Gargron** [comment]
cc @ykzts

**Comment by ykzts** [comment]
```shell
S3_ENABLED=true
S3_BUCKET=example-mastodon-storage
AWS_ACCESS_KEY_ID=GOOGXXXXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
S3_REGION=ap-northeast-1
S3_PROTOCOL=https
S3_HOSTNAME=storage.googleapis.com
S3_ENDPOINT=https://storage.googleapis.com
S3_CLOUDFRONT_HOST=files.example.com
```
I used Google Cloud Storage. It works without problems.

**Comment by bremensaki** [comment]
Mine's pretty much identical but defined as multi-regional:

```
S3_ENABLED=true
S3_BUCKET=static.chinwag.org
AWS_ACCESS_KEY_ID=GOOGetcetc
AWS_SECRET_ACCESS_KEY=arealkeyhere
S3_REGION=us
S3_PROTOCOL=https
S3_HOSTNAME=storage.googleapis.com
S3_ENDPOINT=https://storage.googleapis.com
S3_CLOUDFRONT_HOST=static.chinwag.org
```

OK, I'm going to have to do some tests with a couple of fresh installs it looks like. As soon as I applied this commit, my storage broke instantly. Reverted it, everything's fine again. I'll see if I can get some time over the weekend to try to narrow this down.

**Comment by mal0ki** [comment]
@bremensaki any progress on this trouble shooting?

**Comment by bremensaki** [comment]
Unfortunately not, I got insanely busy. Hope to try the paperclip update patch in isolation to my test instance tomorrow.

**Comment by bremensaki** [comment]
Finally got a chance to pull a full 2.4.0 RC onto an instance using the same Google Cloud store and credentials and it's working.

I still have this issue with my real instance, but there's got to be something else about the environment that's triggering it. Not Mastodon's problem.
