### ISSUE TITLE
Proposal: Finer-grained oauth/api permissions

### ISSUE THREAD

**Issue by ThisIsMissEm** [tootsuite/mastodon#7121]
At present, the scopes for oAuth applications seem to be too high level to properly control account security. Current scopes are:

- read
- write
- follow

Issues from the way current scopes are setup:
- No way to deny an application access to certain information
> I can't authorize and say "no, you can't read my statuses" — this is similar to the security issue with Facebook permissions in regards to Cambridge Analytica, sometimes you just want to "log in as", and not actually give the app permission to see your data.
- Applications requesting follow permissions can read a users blocks and mutes
- Applications with Write permissions can update account settings (the permission request says "post on your behalf" (bug?)
- Applications with Read permissions can read direct messages
- Applications with Read permissions can clear users notifications (bug)

I'd propose breaking the permissions down into more granular scopes, giving users more control over their data.

Likewise, I'd like propose we change how we figure out the scope for the serializers, as to enable per-attribute level scopes. This would mean changing the `serialization_scope` from the default of `current_user` to the `doorkeeper_token`, and introducing a base class for all serializers, similar to the following:

```ruby
class Api::BaseController < ApplicationController
  serialization_scope :doorkeeper_token
end

class REST::BaseSerializer < ActiveModel::Serializer
  def current_user
    @current_user ||= User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  rescue ActiveRecord::RecordNotFound
    @current_user = nil
  end

  def current_user?
    !current_user.nil?
  end

  def superapp?
    doorkeeper_token && doorkeeper_token.application.superapp? || false
  end

  def oauth_scope? *required_scopes
    doorkeeper_token && doorkeeper_token.includes_scope? *required_scopes || false
  end
end
```

This would require updating all the existing serializer's to make them inherit from this base, but then would allow things like excluding fields based on scopes. 

For instance, `Api::V1::Accounts::CredentialsController` we could then expose the users' email address if the right scope was requested:

```ruby
class REST::CredentialAccountSerializer < REST::AccountSerializer
  attribute :email, if: -> { oauth_scope? :read_email }

# .. snip...
end
```

Or on statuses:

```
class REST::StatusSerializer < ActiveModel::Serializer
  # .. snip ..

  attribute :favourited, if: -> { current_user? && oauth_scope? :read_favourites }
  attribute :reblogged, if: -> { current_user? && oauth_scope? :read_boosts }
  attribute :muted, if: -> { current_user? && oauth_scope? :read_mutes }

  # .. snip ..
end
```

At the end of the day, the current permissions

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] Related issues:
  - https://github.com/tootsuite/mastodon/issues/6901

**Comment by ThisIsMissEm** [comment]
> > Applications with Write permissions can update account settings

> You mean only profile settings, like display name, avatar, etc? Because no app and no scope should allow updating account settings

Oh, wait, yeah, sorry, I missed the params list when reading the code.

**Comment by Gargron** [comment]
The scopes were designed with these meanings in mind (and then some scope creep happened too):

Read: Access to view any data
Write: Access to update any data, except:
Follow: Access to update relationships to other users, e.g. follow, unfollow, block, mute, etc

I imagine a new system would keep those as overarching categories, because they are still useful to client apps like Tusky, Mastalab, etc, but you'd be able to get more specific like: `read:statuses:public` or `write:account`, `write:statuses:create`, `write:statuses:delete`

**Comment by ThisIsMissEm** [comment]
@Gargron though, this is definitely an issue: https://github.com/tootsuite/mastodon/blob/master/app/controllers/api/v1/notifications_controller.rb

**Comment by Gargron** [comment]
We'd need our own helper instead of `doorkeeper_authorize!` which would understand that if the token has permission for `write` it has permission for anything that begins with `write:`. And then the challenge would be defining all the authorize calls which are currently mostly one before_action per controller.

**Comment by ThisIsMissEm** [comment]
@Gargron I'd have to do more research on how scopes should cascade — I believe GitHub gave a talk about how they handle it. I think we could do it as:

```
before_action -> { doorkeeper_authorize! :read, :read_statuses }
```

Or we could have our own helper that knows how to expand "read" into the actual scopes

**Comment by ThisIsMissEm** [comment]
@Gargron background on why this came up: We have a few applications we're developing where we'd like to share the email address from mastodon with the application, for quicker account signup.
