### ISSUE TITLE
Proposal: Add quick-filters to notifications

### ISSUE THREAD

**Issue by ThisIsMissEm** [tootsuite/mastodon#7123]
Sometimes notifications can get a bit overwhelming, as such, it'd be nice to have one-click buttons to filter by notification type. I know you can toggle via the settings for the column, but that's quite time-consuming and not intuitive to users.

<img width="335" alt="screen shot 2018-04-13 at 5 34 51 pm" src="https://user-images.githubusercontent.com/30827/38744039-05349e72-3f41-11e8-9006-1be5f19fdec2.png">

This would scroll left/right if there's too many items (the shadow indicating that)

Maybe I've grouped too small; All / Mentions / Followers would be enough?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
I love this a lot! :)

I'm not sure how other people use this but I think if everyone is like me then faves and boosts could be combined?

**Comment by ThisIsMissEm** [comment]
Like, I still want to see boost, favourites and followers, but I don't need to see them all the time.

**Comment by Cassolotl** [comment]
Yeah, that makes sense! There's an issue for being able to have more than one notification column (*Multiple notifications columns #5327*), so you could separate out your faves/boosts from your mentions, but this is a better solution because it saves space on smaller screens, I think!

**Comment by pawelngei** [comment]
I love this as well! Can I just try to implement this and make a PR, or should we wait for some official approval from the core devs?

**Comment by trwnh** [comment]
@pawelngei If you feel capable enough of doing it properly, I'd go ahead and do it. You shouldn't wait for any "official approval" for improving things!

**Comment by pawelngei** [comment]
Already started implementing it and I'm wondering about one thing:

For some languages the translations will be longer than the width of the bar. Should it expand into the second row?

Any ideas @ThisIsMissEm ?

**Comment by Kjwon15** [comment]
I'd prefer to add "all" and "mention" columns separately at once. Like misskey, tweetdeck
At now, I can add two or more notification columns but they're sync'ed their options.
