### ISSUE TITLE
Unlocking an account should approve all pending follow-requests

### ISSUE THREAD

**Issue by KellerFuchs** [tootsuite/mastodon#7126]
I sent a follow-request to one of @rtucker's account (on [high.cat](https://high.cat)) from my [vulpine.club](https://vulpine.club) account, back when it was locked; it wasn't approved before the account was unlocked, resulting in a pending follow request that couldn't be approved, and me not following the account.

Withdrawing the request and re-following worked, but it seems to me that approving all follow requests (or better, ask the user whether they want to) would be a more sensible behaviour

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).
  [vulpine.club](https://vulpine.club) runs vulpineclub/mastodon, and I have no clue what [high.cat](https://high.cat) runs.

**Comment by Gargron** [comment]
I was sure that this was already implemented :thinking:

**Comment by KellerFuchs** [comment]
@Gargron I literally have no clue anymore when the follow happened, so there might have been one (or more!) releases shipping that fix already.

**Comment by ThibG** [comment]
Looking at the code, this should already be implemented, and a quick test didn't raise any issue, so I'm closing this. Please reopen if you can reproduce this issue.
