### ISSUE TITLE
Erase spaces surrounding user handle on Firefox

### ISSUE THREAD

**Issue by weavermarquez** [tootsuite/mastodon#7129]
Using Firefox 58.0.2 (64-bit) on Windows 10 Pro.

When I triple-click or select by dragging across two lines on a user's user-handle on their page, the resulting copied text has two spaces surrounding the string: one preceding, one succeeding. This can be a flow issue when attempting to follow somebody by copy-pasting a user's full handle into your desired instance account instead of remote-following. 

![image](https://user-images.githubusercontent.com/36017403/38765369-4aabe1b8-3f7d-11e8-95ea-83a8d8207e1c.png)

Duplication:
1. Head to: https://mastodon.social/@Gargron
2. triple-click on or select **@Gargron@mastodon.social**
3. Ctrl-C, Ctrl-V on some text space
4. The resulting string has extraneous whitespace.

Additional notes: 
If I triple-click on the user handle on the full profile page, the resulting string has a space before and after the handle.
If I select using this motion in either direction to select the user-handle, the resulting string only has a space after the handle.
![image](https://user-images.githubusercontent.com/36017403/38765348-fe7d3f76-3f7c-11e8-8b10-b43cf707bcea.png) 

If I triple-click on the user handle on the in-web-client profile, the resulting string only has a space after the handle.
If I select using the same motion as above on the in-web-client profile, the resulting string only has a space after the handle. 

* * * *
- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
When you press enter when there's a space at the end, it still works, no?

**Comment by weavermarquez** [comment]
Additional note: The user search does not work if there is only a space after the handle.
i.e., searching "@Gargron@mastodon.social " then pressing enter results in 0 results.
