### ISSUE TITLE
spearker button is difficult to see on videos

### ISSUE THREAD

**Issue by TheCapsLock** [tootsuite/mastodon#713]
when I read video for the first time my first reflex was to do a right click then unmute : i had not seen the speeker button :

![scan](https://cloud.githubusercontent.com/assets/3322481/24579686/4bd3669e-16fa-11e7-8939-a9dd4d394ebe.png)

Proposal : make the speaker icon white and use a drop shadow. The speaker will be visible on brighter and darker videos.

this applies to other controls on a video (eye button)

**Comment by 0x70b1a5** [comment]
hope this helps. feel free to close issue if you can see buttons better. thank you

**Comment by TheCapsLock** [comment]
Your commit displays as : 

![actual](https://cloud.githubusercontent.com/assets/3322481/24586742/083beb46-17a8-11e7-878d-5e5e52cf7e45.png)

I was thinking about something like :

![expected](https://cloud.githubusercontent.com/assets/3322481/24586738/e50c9bca-17a7-11e7-88f0-904d68f9ddb0.png)

actual css rules needs to be moved from the div arround the button to the gliph directly (<i>).

then we need to replace box-shadow with text-shadow.

following rules seems right (the ones used on last screenshot) :

```css
 color: white;
 text-shadow: 1px 2px 2px black, 1px 0px 3px black;
```

**Comment by 0x70b1a5** [comment]
let me know if further problems arise, buttons appear fine on my machine

**Comment by TheCapsLock** [comment]
@0x70b1a5 Cannot see any change on master from what I stated at https://github.com/tootsuite/mastodon/issues/713#issuecomment-290980498

**Comment by ashfurrow** [comment]
Looks like this is fixed as of https://github.com/tootsuite/mastodon/pull/740 being merged. I'm going to close the issue, but if it's still a problem feel free to re-open. And let us know if you run into other bugs or have feature requests. Thanks!
