### ISSUE TITLE
Redesign forms

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#7133]
The underline-only no-background design where placeholders are used over labels is not looking very good anymore. Especially when the inputs are filled it's hard to tell what is what without remembering. Also, the padding on the inputs that has to be there because of the background tint on focus makes the text not line up with other text, which is annoying.

**Comment by stephenburgess8** [comment]
HAML simple_form configuration: `~/config/initializers/simple_form.rb`.
HAML, e.g. `~/app/views/settings/profiles/show.html.haml`.
Stylesheet: `~/app/javascript/styles/mastodon/forms.scss`.

If the text input fields had the same labels as the file input fields, that would help a lot. I like the idea of keeping the placeholder as well as the label. If you do use labels, it isn't necessary to also use aria-label. 👍

**Comment by ThisIsMissEm** [comment]
I think placeholders should be used to describe the format, not the field; I agree the existing styling isn't ideal.

**Comment by trwnh** [comment]
Drawing a mental blank right now -- which forms are these specifically, and where do they appear? I kind of want to take a stab at this.

**Comment by ThisIsMissEm** [comment]
@trwnh those in settings & admin.
