### ISSUE TITLE
As an user, I want to stop whole instances from interacting with my posts

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#7136]
>when I use #mastodon, I expect my followers to see and be able to interact with every reply to my posts, when they click on my post.
>
>however, #pleroma breaks that.
>
>and we still don't let users block whole instances.
>
>I feel like pleroma goes against the culture I'm trying to promote among my followers, but I have no way to stop pleroma users from interacting with my posts.
>
>I could do that with my own instance, but as an user, I am completely powerless to do anything.

https://cybre.space/@SoniEx2/99860830397616226

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. ( #6961 but the title isn't/wasn't clear enough so nobody actually looked at it, as usual )
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I'm probably missing some context here - how does Pleroma break that?
