### ISSUE TITLE
Rename instance-wide silence user to "shadow ban"

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#7140]
Instance-wide silences are really shadow bans, so they should be called what they are.

There should also be separate features to block the user from the federated timeline.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
My understanding is that "silence" on Mastodon doesn't stop people seeing your posts when they follow you (instance-level and individual-level), whereas shadow bans make it look to you like you're posting while preventing other people from seeing your posts. Someone should correct me if I'm wrong here!

**Comment by Cassolotl** [comment]
I'm not aware of it, I'm not using that instance - can you give us a run-down for context?

**Comment by Cassolotl** [comment]
There's already an issue about renaming the "silence" function, here: *Think about renaming 'silence' to 'default block' #5694*

**Comment by nightpool** [comment]
There's no real drama, I just had to clear up some confusion when Soni accused pleroma of breaking federation because some pleroma users were silenced.

**Comment by ThisIsMissEm** [comment]
Feel like this issue as titled is resolved given the comments from @nightpool above, and #5694, the language issue is also noted in #6954

I'd like more information on the "block user from federated timeline" — as if I understand this correctly, this is something we need (i.e., the ability to prevent a user from appearing in the federated timeline on other instances, but still allow them to interact with users on other instances — i.e., when we're dealing with spam resolution or noisy users annoying others on the federated timeline by "taking over it").

**Comment by SoniEx2** [comment]
given user A on instance A, and user B on instance B, there should be a way for instance A to block user B from showing up on instance A's federated timeline. without affecting anything else.
