### ISSUE TITLE
Firewall/NAT for (silenced) incoming toots

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#7142]
Given User A and User B, where User B is silenced in User A's instance, currently:

User A @'s User B.
User B then replies to User A.
User A never sees User B's message.

With a firewall/NAT for incoming messages, Mastodon would realize User A mentioned User B, and let User B reply to User A.

(not that mastodon cares about UX)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
> (not that mastodon cares about UX)

Please stop with the passive aggressive stuff, it is really unpleasant.
