### ISSUE TITLE
Reply action does not close search results in single column mode

### ISSUE THREAD

**Issue by ThisIsMissEm** [tootsuite/mastodon#7144]
If you have elasticsearch enabled, and you search for toots (i.e., "test", not a user or hashtag), then the reply button for the resulting statuses in the search results does not work. (it does fill the form, but doesn't close search)

I suspect this is because we're already on the status compose page (when really search should be a separate route). 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Might be able to close the search from redux.

**Comment by ThibG** [comment]
I edited the issue title as I could only reproduce this issue on mobile.

**Comment by ThisIsMissEm** [comment]
I think this is only an issue in single column mode, but I can't recall. I did start working on what I think the fix is, which is to actually split search out of compose.

**Comment by nightpool** [comment]
I can't reproduce this on stable....

**Comment by nightpool** [comment]
oh I misread, replying works, it just doesn't close search.
