### ISSUE TITLE
The demonstration video is outdated

### ISSUE THREAD

**Issue by Sylvhem** [tootsuite/mastodon#7146]
The video who appears when clicking on the screenshoot of the README.md file, [Mastodon UI demonstration](https://www.youtube.com/watch?v=YO1jQ8_rAMU), is clearly outdated.
It would be a good thing to have a video showing the current UI instead. Also, it would be probably better if this new video was directly hosted on the new [Mastodon's YouTube channel](https://www.youtube.com/channel/UCXSPPy9mRo9tVnEwKOwo93g), instead of Gargron's personal one.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mal0ki** [comment]
Either I get some kind of admin access to the YouTube, or Gargron will have to do this himself, thus assigned to Gargron.

**Comment by Gargron** [comment]
Maybe I should link the animated video from the README instead?

**Comment by mal0ki** [comment]
The new animated video, yes, but then the info can't be that it's a UI demonstration.

**Comment by Sylvhem** [comment]
The caption for the new video have not been changed is now incorrect. It still says "Click on the screenshot below to watch a demo of the UI:" even if it's not a UI demonstration anymore.
