### ISSUE TITLE
Adding a content warning should automatically mark media as sensitive

### ISSUE THREAD

**Issue by nevillepark** [tootsuite/mastodon#715]
Perhaps the system could be simplified by merging the two features: a CW applies to both text and media. I think this is more intuitive for users, doesn't constrict most people's everyday usage, and would remove a step for people who want to add a particular tag/warning to sensitive media.

**Comment by ashfurrow** [comment]
Yup yup, this is a good idea. Conversation has taken off on the duplicate issue #1010, so I'm going to close this one even though it was the original. Thanks for opening!
