### ISSUE TITLE
Reducer "custom_emojis" returned undefined

### ISSUE THREAD

**Issue by gergelypolonkai** [tootsuite/mastodon#7156]
After accidentally deploying master (1a37d7e252aa41fd1c66e780e1a2a1426d8f3545) to production, I bumped into this error in Chrome, while being presented with a deep dark grey screen:

```
application.js:6 Error: Reducer "custom_emojis" returned undefined when handling "STORE_HYDRATE" action. To ignore an action, you must explicitly return the previous state.
    at t.default (validateNextState.js:10)
    at combineReducers.js:41
    at Array.forEach (<anonymous>)
    at combineReducers.js:36
    at fe.withMutations (immutable.js:1353)
    at combineReducers.js:35
    at l (createStore.js:165)
    at sounds.js:44
    at errors.js:29
    at loading_bar.js:23
```

This is right after logging in to my instance.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThisIsMissEm** [comment]
I'd guess this may be related to https://github.com/tootsuite/mastodon/pull/7047

**Comment by Reverite** [comment]
It sounds like it's still trying to get `custom_emojis` from `STORE_HYDRATE` when it expects an initial state to already be set, since that was removed in the initial state serializer. Can you check that `app/javascript/mastodon/reducers/custom_emojis.js` is changed and everything matches to #7047?

**Comment by ProgVal** [comment]
Someone on IRC reports the same issue on the 4.2 release.

The backtrace is the following:

```
Error: Reducer "custom_emojis" returned undefined when handling "STORE_HYDRATE" action. To ignore an action, you must explicitly return the previous state.
Trace de la pile :
t.default@https://pridelands.io/packs/common-f4d5e869b0efca09d8fa.js:1:492188
t.default/</</<@https://pridelands.io/packs/common-f4d5e869b0efca09d8fa.js:1:490636
t.default/</<@https://pridelands.io/packs/common-f4d5e869b0efca09d8fa.js:1:490582
fe.prototype.withMutations@https://pridelands.io/packs/common-f4d5e869b0efca09d8fa.js:1:38632
t.default/<@https://pridelands.io/packs/common-f4d5e869b0efca09d8fa.js:1:490554
l@https://pridelands.io/packs/common-f4d5e869b0efca09d8fa.js:1:226043
r/</</<@https://pridelands.io/packs/common-f4d5e869b0efca09d8fa.js:1:569271
r/</</<@https://pridelands.io/packs/common-f4d5e869b0efca09d8fa.js:1:568968
r/</</<@https://pridelands.io/packs/common-f4d5e869b0efca09d8fa.js:1:568484
r/</</<@https://pridelands.io/packs/common-f4d5e869b0efca09d8fa.js:1:489213
[329]@https://pridelands.io/packs/about-188eb99653064abacc3a.js:1:14332
t@https://pridelands.io/packs/common-f4d5e869b0efca09d8fa.js:1:96
o@https://pridelands.io/packs/about-188eb99653064abacc3a.js:1:13639
r@https://pridelands.io/packs/common-f4d5e869b0efca09d8fa.js:1:128666
r@https://pridelands.io/packs/about-188eb99653064abacc3a.js:1:13824z
```

**Comment by simbalion** [comment]
I am the guy from IRC. I upgraded using the 2.4.0 checkout tag, to clarify

**Comment by nightpool** [comment]
@gergelypolonkai you don't have any file named reducers/custom_emoji.js at all? Or it's completely blank? What does `git status` show?

**Comment by gergelypolonkai** [comment]
Aftur running all update commands, it started working. Maybe the asset compilation failed, or I completely missed a step.

I think this can be safely closed, sorry for the noise.

**Comment by lmorchard** [comment]
For what it's worth, I upgraded from v2.1.3 to v2.4.3 and am now seeing this error. Doesn't go away after running all the update commands.

![capture](https://user-images.githubusercontent.com/21687/44004881-426027d4-9e38-11e8-8ff6-0ea66e5e5d02.PNG)

**Comment by lmorchard** [comment]
Gave another go at upgrading, this time from v2.3.3 to v2.4.3. Error's gone now. I'm not as familiar with Mastodon workings as I'd like, so I'm not sure what state might have been stuck that got unstuck with this second upgrade. Might be worth a FAQ somewhere at least - i.e. don't upgrade straight from several versions ago, take it a minor version at a time?
