### ISSUE TITLE
Muted and blocked users still appear on other peoples' profiles

### ISSUE THREAD

**Issue by fluffy-critter** [tootsuite/mastodon#7172]
There is a person A whose toots I don't want to see at all, so I put them on the mute list (and also blocked them for good measure).

Then I look at a friend B's profile (on my instance), and see a bunch of A's toots, having been boosted by B.

It would be nice if block/mute applied to friends' timeline views in addition to my own timeline, at least from my own instance. Obviously this wouldn't be possible when I'm looking at their timeline on their own instance, but from my own instance I should never end up seeing the toots from the person I have muted.

This occurs on queer.party, an instance running version 2.3.3. (I am not the admin.)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I think this is a duplicate of *Blocked users' toots still appear on the profiles of users who retoot them #251*?

**Comment by trwnh** [comment]
Not a direct duplicate of #251, as the discussion on that issue and the title of this one show. #251 deals with the expectation that *blocking* someone should hide them, while this one talks about both blocking and also *muting*. As I said over there, muting should hide someone from your view, and blocking should hide you from someone else's view -- these two issues simply propose expanding that filtering universally and not just for the timelines.

**Comment by nightpool** [comment]
while they serve different use cases, they're discussing similar spaces if
features, and one is conflicting with the other. so we should have the
discussion about which one is better centralized in one place. that's why
they're duplicates

**Comment by fluffy-critter** [comment]
I'm fine with closing this as a duplicate. I had only searched on 'muted' when I looked for issues; my bad.
