### ISSUE TITLE
Notification noises

### ISSUE THREAD

**Issue by chris-martin** [tootsuite/mastodon#719]
It'd be lovely to have a setting to disable the noise that notifications make.

**Comment by Gargron** [comment]
Available in the notifications column menu:

![](http://puu.sh/v6iMi/d982458e01.png)

**Comment by chris-martin** [comment]
Ah, thanks.

For what it's worth, I didn't find that setting because my expectation was that all of the settings would be configurable from https://mastodon.social/settings/preferences
