### ISSUE TITLE
Confirmation emails from mastodon.social aren't getting sent properly

### ISSUE THREAD

**Issue by flussence** [tootsuite/mastodon#7190]
Just tried to make an account there, and after half an hour no sign of an email. I checked my mailserver's logs and found it bounced because some misconfigured third-party server is trying to connect to mine using its own hostname:
```
Apr 19 14:17:37 [postfix/smtpd] connect from mta573b.sparkpostmail.com[35.167.192.209]
Apr 19 14:17:38 [postfix/smtpd] NOQUEUE: reject: MAIL from mta573b.sparkpostmail.com[35.167.192.209]: 450 4.1.8 <msprvs1=176475Nj9veta=bounces-201802@sparkpostmail1.com>: Sender address rejected: Domain not found; from=<msprvs1=176475Nj9veta=bounces-201802@sparkpostmail1.com> proto=ESMTP helo=<mta573b.sparkpostmail.com>
Apr 19 14:17:44 [postfix/smtpd] disconnect from mta573b.sparkpostmail.com[35.167.192.209] ehlo=2 starttls=1 mail=0/1 quit=1 commands=4/5
```
Tried to resend and the same thing happened.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
This is not a Mastodon issue, this is a mastodon.social issue.

I've recently switched from Mailgun to SparkPost. I don't know the details of this error, but the UI lets me setup a "bounce domain" so I guess I'll do that and see if it helps.

**Comment by Gargron** [comment]
Have you tried again? Does it work now?
