### ISSUE TITLE
Copy Link to Toot

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [tootsuite/mastodon#7210]
There's no option to copy the link to a toot. It's there in Tusky, and is mighty useful. Need this in the web client, too.

**Comment by m4sk1n** [comment]
You can right-click on its date and copy the link…

**Comment by Cassolotl** [comment]
It's not obvious from the UI that you can do that, though.

**Comment by ThisIsMissEm** [comment]
Given #6848, I think this should be closed as a duplicate.

**Comment by Cassolotl** [comment]
@m4sk1n There's usually more ways than just the timestamp to copy the URL though!

**Comment by nightpool** [comment]
imo......
![image](https://user-images.githubusercontent.com/233815/39088848-b71a7192-4587-11e8-9bf6-d07c4f5f182a.png)

**Comment by Cassolotl** [comment]
@nightpool Agree! One of the details I really like about cybre.space. :)

**Comment by mal0ki** [comment]
Closing and directing to #6848

**Comment by Cassolotl** [comment]
This is also a duplicate of *URL copy-to-clipboard option in post-menus #680*, which is over a year old and still open.
