### ISSUE TITLE
Dailymotion embeds not working

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#7211]
I thought I remembered that Dailymotion videos were embedded. But it is not working with the current Mastodon version. A regression or did I remembered it incorrectly? When it's the latter this is a feature request to add it.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
We only support OEmbed, we don't have any custom code for particular providers. If Dailymotion does not provide OEmbed then it must be their problem.

**Comment by jeroenpraat** [comment]
Thanks for telling me. I will contact dailymotion.
