### ISSUE TITLE
Bug: Suspended accounts show up identically to Locked/Private accounts

### ISSUE THREAD

**Issue by ThisIsMissEm** [tootsuite/mastodon#7243]
We’ve currently an issue where a few users who have been suspended keep beibg reported because the Web UI shows suspended accounts identically to locked/private accounts.

I’d say via API these should return a 404, with status suspended in the JSON body, then in the web UI we can render them differently.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
I thought they give a 410 error?

**Comment by ThisIsMissEm** [comment]
Here's how they appear in the Web UI: 
<img width="336" alt="screen shot 2018-04-23 at 7 02 27 pm" src="https://user-images.githubusercontent.com/30827/39141735-e9cd49b4-4728-11e8-8399-d5f87f44f69e.png">

The direct page (i.e., `https://switter.at/@feds` gives an error)

**Comment by ThisIsMissEm** [comment]
Looks like AccountSearchService didn't filter out suspended accounts, working on a patch for this now.

We should also have UI for showing suspended accounts, in case you click on a Username and find them suspended.

**Comment by Gargron** [comment]
Ah, Account#search_for and advanced_search_for contain a suspended=false clause, but exact matches in AccountSearchService don't. Is that it?

Also wow, apparently the REST API does *not* return a 410 when an account is suspended! That completely slipped my mind.
