### ISSUE TITLE
Double toots in DMs after going back in history

### ISSUE THREAD

**Issue by redsPL** [tootsuite/mastodon#7249]
1. Open the DM view
2. Click on a post from outside the DM view
3. Click on "Back" (assuming that the DM view isn't pinned)
4. [Double posts, yay!](http://sakamoto.pl/tmp/2018_04_23-22:35.png)
If done several times, the results can be [pretty interesting](http://sakamoto.pl/tmp/2018_04_23-22:40.png) (ignore the line, it's imagemagick)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
This is a problem for every column currently, a regression introduced in #7180 (apparently)

cc @akihikodaki
