### ISSUE TITLE
Hiding replies doesn't hide all replies (boosted replies still show)

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#7253]
Hiding replies hides all normal replies, including when you reply to yourself to make a thread.

But apparently not boosts???

Personally I think it should be the other way around - replies-to-self/threads should show, while boosted replies should not show. But more importantly, why show boosted replies at all?

(The main issue is LB replies, which are replies but are also boosted. I wish there would be a way to hide those without hiding the boosts themselves.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
People boost replies when they want them to be seen by their followers, when they think they are valid and worth seeing in their own right.

Replies-to-self/threads show in the Home timeline even when the setting is set to hide replies:

![screen shot 2018-04-24 at 13 11 38](https://user-images.githubusercontent.com/6607512/39186025-0e09e86c-47c1-11e8-8b43-a715bddc8bcd.png)

**Comment by Gargron** [comment]
As far as I'm concerned it doesn't matter if it's a reply or not: if it's boosted, it's a boost.
