### ISSUE TITLE
(UX) on mobile, back button behavior when viewing media is unexpected 

### ISSUE THREAD

**Issue by chr-1x** [tootsuite/mastodon#7258]
1. Switch from timeline X to timeline Y
2. Click on media in a post on Y to view it in a full screen modal
3. Press back button 

Expected behavior: back button exits modal and allows you to resume scrolling through timeline Y

Actual behavior: back button moves the underlying page back to timeline X while keeping the media modal up and in focus

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I believe this is a duplicate of #364?

**Comment by chr-1x** [comment]
oh yes, good catch
