### ISSUE TITLE
Comments from Users that I have Blocked or Muted still show up in other Users' conversation threads.

### ISSUE THREAD

**Issue by ktracer-isp** [tootsuite/mastodon#726]
Repro:
I can see https://mastodon.social/@masturbon/1427150 in response to https://mastodon.social/@nev/1427119. even though I have @masturbon blocked.

I'm assuming that there's some interaction whereby blocked and muted users only get checked in my conversations and the main timelines, but not when I look into other users' threads.

**Comment by ashfurrow** [comment]
Going to close as a duplicate of https://github.com/tootsuite/mastodon/issues/647 – thanks for the issue!
