### ISSUE TITLE
[UI] At least make #sci-fi work

### ISSUE THREAD

**Issue by raingloom** [tootsuite/mastodon#7269]
Opening a new issue for this because it became too noisy, sorry.

The "-" character is very often used to _join_ two things, so it doesn't make sense to use it as a delimiter in a tag, in fact, I've never seen a situation in which including it in the tag would have been the wrong choice.

And as I've said in the previous issue, this happens often enough that it should matter.

**Comment by ykzts** [comment]
duplicate with #2452, #6489.
