### ISSUE TITLE
Emojo dropdown box falls off the end of the page and the scrolling is weird

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#7277]
Recently there was a PR that made some modals open upwards instead of downwards if they were near the bottom of the page. Maybe something like that could happen for the emoji picker too, and then that weird scrolling off the page thing wouldn't happen so much? It's pretty annoying and fiddly!

![screen shot 2018-04-28 at 08 57 38](https://user-images.githubusercontent.com/6607512/39393883-9f9007fe-4ac2-11e8-9df6-d3785785e857.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mal0ki** [comment]
I'm going to label this a bug, as it shouldn't be outside of the window.
