### ISSUE TITLE
Prevent timeline from moving when cursor is hovering over it

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#7278]
See [this toot](https://icosahedron.website/@Xkeeper/99934217414178449):

> can we get a feature where the timeline won't move if you are currently or have recently moved your mouse over it
> 
> im real tired of going to click thing a and then thing b slides in under it

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mal0ki** [comment]
It's an interesting thought, that also makes sense.
