### ISSUE TITLE
"Cancel reply" button is too low contrast in high-contrast theme

### ISSUE THREAD

**Issue by elomatreb** [tootsuite/mastodon#7291]
The button to cancel a reply (the little cross) is [very hard to see](http://contrast-ratio.com/#%238d9ac2-on-%239baec8) in the high-contrast theme:

![Screenshot of header of reply window](https://user-images.githubusercontent.com/3387265/39416897-b0baadc4-4c50-11e8-95a5-da76a78020cc.png)

If you hover over it, the color gets so similar to the background that it effectively becomes invisible.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mal0ki** [comment]
Thank you for bringing this to our attention.
