### ISSUE TITLE
Feat: link accounts from different instances

### ISSUE THREAD

**Issue by voliva** [tootsuite/mastodon#7292]
Would it be possible to link many accounts from different instances together? I may have 2 or more accounts, each in a different instance, but I'd like for people to know what are my accounts in each instance.

Would also be cool if optionally Follows are shared between them - This is, if I'm following someone in my account in instance A, then my account in instance B also follows it. (but not for followers... Well this subfeature would need a bit of a thought)

PS: My use case for having accounts in different instances is that I want to have one for each "environment" I want to browse on - One instance has the people who speak my language, another has people with my music interest, etc, etc.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
I don't think anything is stopping you from just:
- signing up for two accounts,
- posting the handles in the respective other account's bio or pinned toot,
- following the appropriate accounts from each

Each of your accounts can be browsed in it's respective tab, or you can connect them to any application that supports multiple accounts on any platform.

**Comment by mal0ki** [comment]
Currently we don't have this feature. However, as we can redirect an account to another (see below pictures for where the setting is under /settings/profile), it wouldn't be impossible to add something like this in the future. 
I can however not answer if we will, at this point in time. 

![image](https://user-images.githubusercontent.com/28316305/39466660-62e70bb2-4d2a-11e8-9880-6e137fee97a5.png)

**Comment by trwnh** [comment]
Account redirecting is technically for pointing one old account to a new one, not running two separate accounts.

Anyway, I'm still not really sure what additional functionality this issue is requesting. I can put, for example, `@trwnh@sleeping.town` in my bio on `@trwnh@mastodon.social`, and vice-versa. I can follow the same people (or different people, or whomever) on both or either account.

The only actionable thing I see that isn't already possible in Mastodon is to have one account automatically follow the follows of another account -- which seems a bit niche when you can manually follow someone twice, if you wish.

**Comment by voliva** [comment]
My request was just general - it feels weird to have many unlinked accounts in a social network that's uncentralized.

I didn't think of just putting this info in my bio, so my main use case is covered by updating that

**Comment by lanwatch** [comment]
I believe this is something that would be great for UX. Yes indeed there's plenty of workarounds, but a "superidentity" of sorts where the accounts linked are guaranteed by the instances to belong to the same individual/entity with an easy enrollment process, would reduce friction for new/less experienced users.

Registration for an instance could request one of the previous accounts and (provided the user has access to that account) link them together. External clients (they could be web-based) could then access all the accounts together and present a unified timeline to the user.

With different topics and CoCs in each instance, this would also ease moderation load, helping reduce friction between users and instance moderators, which could be more strict enforcing the rules: if you are in a science instance and want to discuss politics, just use your other instance.

Again, this is all possible today "manually", but UX is really important.

**Comment by Mart-Bogdan** [comment]
Hello, @voliva, why did you close this "as completed"?

**Comment by trwnh** [comment]
@Mart-Bogdan github in 2018 didn't have specific ways to close issues

@lanwatch what you're describing sounds kind of like it can be done better in other ways. "unified timelines" could be done by any client, but it would be up to the client to implement that. the issue of "different topics" is probably going to be addressed by groups in the future, but it could also be addressed by a category feature for your own posts. really, it comes down to a difference in social context -- the idea of a topical/themed/focused instance runs partially counter to the idea of a service provider that gives you identity and delivery (which should be but isn't separate from the forum/discussion/social layer)
