### ISSUE TITLE
Delete an instance to avoid requests to it

### ISSUE THREAD

**Issue by Dryusdan** [tootsuite/mastodon#7298]
Hi
Actually, some instance is down (sometime domain was removed), but sidekiq try send message to these.

Can it possible to add option in administration or in CLI to remove know instance to avoid request to these ? 

Regard :)
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mal0ki** [comment]
This should solve the problem:

redis-cli

sadd unavailable_inboxes https://instance.url/inbox

**Comment by Dryusdan** [comment]
And if I delete all accounts in DB of deleted instance, it's work also ?

**Comment by mal0ki** [comment]
@Dryusdan I don't know. If the effect is that it removes the follows from your instance I assume it'd work. Otherwise probably not?

**Comment by Dryusdan** [comment]
Hum... I don't try so
