### ISSUE TITLE
Blocked or muted accounts' toots still show up when boosted

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#7299]
Blocking or muting an account hides all toots from the account, but when a toot is boosted, that comes from that account it still shows up in the home timeline.

Steps to reproduce:
1. Create 3 users, make sure they follow each other and make a toot on the one, that should be blocked or muted (account number one)
2. Block or mute this account from another account (account number 2)
3. Boost a toot from another account (account number 3) from the account which was blocked or muted (account number one)
4. The boost shows up in the other user's (account number 2) timeline, that followed the one user (account number one)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
I think this might be a duplicate of #7230?

**Comment by koyuawsmbrtn** [comment]
Yep!
