### ISSUE TITLE
Login with handle

### ISSUE THREAD

**Issue by piersb** [tootsuite/mastodon#730]
The login function requires an email address as well as the password in order to log in - I'd like to be able to log in using my username rather than email address.

Use Case: When creating a new account, password managers such as the iOS built-in password manager saves by handle and password. 

When trying to log in for the first time, it autofilled the login fields with them, but the login failed because you can't log in by handle. Error message did not reflect this.

**Comment by Gargron** [comment]
This is intended. Your username is public, your e-mail is not. If we allowed usernames for login, it would be easy to start bruteforcing passwords. This way, the attacker would need to bruteforce e-mail addresses first.
