### ISSUE TITLE
Limit characters in bio fields

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#7303]
See #6645: The fields currently do not have character limits. They should do. In the absence of better ideas, just 255 character per name and per value. Also, put a hard limit on the number of fields. Basically, restrict how much data people can dump into that DB column.

**Comment by brennovich** [comment]
What should be done regarding  values that already have more than `255` chars, I mean for current users?

**Comment by Gargron** [comment]
@brennovich "Current" users would be users of an unstable, unreleased version, so the answer is nothing extra needs to be done. Just leave existing data as is.
