### ISSUE TITLE
Two factor authentication went wrong when someone changed their password

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#7308]
[Tweet](https://twitter.com/sparrowsion/status/991592691820580864):

> Changed password (for reasons) and all the 2FA stops working so I'm locked out.
>
> It's the fact that I carefully saved the recovery codes and they don't work that's the real downer.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by shuheiktgw** [comment]
I tried to reproduce this behavior and could not make it so far...
I tried those three things below.

1. Change password from account setting
2. Change password from password reset
3. Change password from admin password reset

**Comment by ThibG** [comment]
Tempted to close this as I cannot reproduce this.

**Comment by Cassolotl** [comment]
That's fair! I'll close it and if someone else has the same problem we can reopen it, hopefully with more information.
