### ISSUE TITLE
UI suggestion: Indicate in-line when a post has replies

### ISSUE THREAD

**Issue by paralithode** [tootsuite/mastodon#731]
Apologies if I've again failed to find this issue already open in my search. :) Variators on 'reply', 'replies', 'reply indicator' &c yielded no joy. I'd like to suggest giving users the ability to see when posts have been replied to or are replies to other posts (mostly relevant for self-replies, of course.)

I've seen a few users talk about this in the last few days. Being able to tell at a glance where a conversation might be going on seems like it might be a valuable tool to increase communication between users on mastodon platforms.

I've included an image attempting to roughly illustrate what these kinds of indication icons might vaguely look like, and the kinds of things they might do.

![mastodon reply indicators idea screenshot 2017-04-02 15 33 44](https://cloud.githubusercontent.com/assets/24278481/24588418/8588f140-17bf-11e7-88a5-7fd77ee99a18.png)

**Comment by lene** [comment]
It might also be highlighted if you have unread replies? Or _only_ be displayed for unread replies, if you want to keep the clutter minimal,

**Comment by spacekookie** [comment]
Is there a similar issue for inline displaying the amount of replies, boosts and favs? Kinda shows at a glance how popular a toot is which can be nice

**Comment by lene** [comment]
I don't know of such an issue and I suspect that there won't be any, since as far as I am aware these numbers are intentionally left out, so as to discourage competitiveness. So if you want them I'd say open an issue, but don't expect much. :-)

**Comment by KEINOS** [comment]
I also agree with this post and think it's a good idea.
Though, I don't want more icons to be placed in a toot for simplicity.
So what about adding one icon type like image below instead, of placing newly?

<img width="1139" alt="threadtooticon" src="https://user-images.githubusercontent.com/11840938/30098879-bab78d2e-931e-11e7-9ade-00027de6b8ea.png">

**Comment by zapp645** [comment]
I think this is solved now, with both the "is a reply" iconography and the "0", "1", and "1+" indicators next to the "reply" button.
