### ISSUE TITLE
Prevent VNC users from being pwned by bootsy / 2FA posting

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#7310]
There should be a way to use 2FA when posting, so every message needs your 2FA codes.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
???

**Comment by Laurelai** [comment]
Im gonna go ahead and say this is a bad idea because the last thing you want is to annoy your users into inputting an ever changing code every time you want to post a toot. The end result would be nagware that makes people disable 2FA

**Comment by SoniEx2** [comment]
Opt-in ofc! Just an option:

- [ ] Require 2FA for posting.

**Comment by Cassolotl** [comment]
I feel like this would be used *so rarely* that it really wouldn't be worth the time and effort involved to implement it???
