### ISSUE TITLE
Add ability to resize content warning box.

### ISSUE THREAD

**Issue by piersb** [tootsuite/mastodon#732]
The CW box + the Toot box must add up to <501 characters.

It's possible for me to write a long content warning in the box; but it's currently not resizeable in the User Interface in the same way that the Toot box is, making it difficult to see or edit a long CW.

Feature request - keep the CW box the same size by default, but make it drag-resizable in the same way as the Toot box.

**Comment by Gargron** [comment]
Because content warning cannot contain rich text, I wouldn't advise putting a lot of stuff into it to warrant a resizeable input box.
