### ISSUE TITLE
Ability to boost to followers only ("private boost")

### ISSUE THREAD

**Issue by lapineige** [tootsuite/mastodon#7322]
**Currently, we can toot privately, and boost publicly. But not boost to follower-only (a kind of "private boost").**
This has a **privacy advantage**: you don't show publicly that you boosted [some toot] with [some content], but only to your followers.
But to fully hide this public data, it should also not be counted in the list of people who boosted the post (or just not shown in the list, but counted ?). If not, it would just hide it from public profile page (that might be interesting too ?).

Concerning the **UI**, it could be implemented as a drop-down menu on the boost button, for instance.

*****

**The current workaround** is to reply (privately, with or without mentioning the author) to the toot, saying "Hey, check this toot here ↑, that talks about [this topic]". It's doable, but not convenient.
Or to boost a post, and "deboost" it (~cancel the boost). It works, but only for people currently connected, and if they doesn't refresh the page. And it doesn't show who boosted the toot (and create a bit of confusion, when a new person's toot integrate the TL without any boost origin mention).
*****

This might be some kind of extension of https://github.com/tootsuite/mastodon/pull/6157 (boosting own-private toots).

Or to this proposal: https://github.com/tootsuite/mastodon/issues/422 (lists, mutuals only, and eliminating the need for multiple accounts)
For instance, in addition to posting to a specific list of users, we could boost only for them.
In addition to the privacy advantage (for instance: toots boosted only to family/friends, instead of all followers), **it's also a way to publish/boost toots to groups based on their interest**. Let's say that you're talking to 2 groups of people, one interested in topic X, the other in topic Y. You could publish content related to X to one group, and related to Y to the other, without "spamming" them with unrelevant content.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
Note: I've searched if there was another issue talking about this, but I found more general topics about post/boost privacy, like https://github.com/tootsuite/mastodon/issues/5723 (that doesn't really talk about the same thing) or https://github.com/tootsuite/mastodon/issues/422 (as said above).

**Comment by fenarinarsa** [comment]
I agree this should be a standard feature. Currently when an account is locked the boosts are public without any way to make them private. They do not follow the default privacy for new toots either. This is counter intuitive and may even be dangerous.
