### ISSUE TITLE
login/registration form in the root page is hard to find

### ISSUE THREAD

**Issue by ProgVal** [tootsuite/mastodon#733]
Hi,

The login/registration form in the root page (aka /about) is hard to find because it is too much at the left.
I would need a screen twice as large as my laptop's to see it without scrolling right.

Since the left half of the page is empty (besides the elephant), could this form be move there?

**Comment by Gargron** [comment]
Could you give me a screenshot and what browser it's in? The about page is centered.

**Comment by ProgVal** [comment]
Oh, I just noticed the browser automatically scrolls once I enable Javascript.
But then the text is only partially visible.

My browser is Firefox 45.8.

Without javascript:

![screenshout with javascript disabled](https://cloud.githubusercontent.com/assets/406946/24588787/c9885092-17cf-11e7-828e-ef05f7d60274.png)

with javascript:

![screenshot with javascript enable](https://cloud.githubusercontent.com/assets/406946/24588782/b540cb82-17cf-11e7-807d-119e85b8c6e9.png)

**Comment by ProgVal** [comment]
Looks fixed. Or maybe it was just an issue in my browser.

Thanks anyway for making Mastodon so cool :)
