### ISSUE TITLE
Admins can't manually re-send confirmation emails

### ISSUE THREAD

**Issue by wxcafe** [tootsuite/mastodon#7333]
I've just had MTA troubles for the past few days, and as such a few confirmation emails have been lost (timed out). It would be nice if admins could just have a button on users' page in the moderation panel to re-send the confirmation email

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by shuheiktgw** [comment]
Let me work on this feature! 👍
