### ISSUE TITLE
Make character limit for media descriptions clear.

### ISSUE THREAD

**Issue by Fidgetcetera** [tootsuite/mastodon#7339]
When uploading media and writing descriptions, it's not exactly clear there even _is_ a character limit. Looking at https://github.com/tootsuite/mastodon/blob/master/app/models/media_attachment.rb#L74 it would appear this limit is 420 characters. This character limit should be clear in the UI. 

The web UI _does_ stop you from adding more text when you get to this point, which is also inconsistent to writing the post itself (which allows you to go past the character limit but shows negative character counts).
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by andi1984** [comment]
@Gargron I think this ticket can be closed as by now the character count is shown explicitely in the UI.
