### ISSUE TITLE
Paste image from clipboard to textarea

### ISSUE THREAD

**Issue by maximeborges** [tootsuite/mastodon#734]
A nice feature to add would be to be able to paste image from the clipboard to the text area for writing toot. It's available on Twitter but not on Tweetdeck, and it's especialy very useful to easily send screenshots when using keyboard shortcut for example.

**Comment by ticky** [comment]
This used to work in Chrome, but it seems Chrome changed clipboard behaviour recently.

As the ClipboardEvent APIs are new and experimental, it seems likely that this won’t settle for some time.

**Comment by halkeye** [comment]
https://www.npmjs.com/package/paste-image looks like it works still

So if nobody else tackles it by the time I finish the rest of the todo list (working on invites right now), I might try to do this one

**Comment by ashfurrow** [comment]
Cool cool, thanks everyone. Let's move the discussion over to https://github.com/tootsuite/mastodon/issues/695 .
