### ISSUE TITLE
Better Lists

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#7341]
How To Fix Lists:
make your home timeline count as a list. make a non-column, fullscreen popup list editor that lists all people you follow and checkboxes in a table-like format of 'what lists do they belong to' including home timeline as an option.
allow the list search to add users that previously weren't people you follow to your lists, simultaneously following them. make it so when following someone not inside this UI, a popup appears asking which lists you want to put them in, if any, that aren't the home timeline, including a checkbox for home timeline

the home timeline list obviously cannot be deleted in this model, but, individual users can be removed from the list

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by joyeusenoelle** [comment]
It's worth noting, possibly tangentially, that you can already unpin your Home timeline and replace it with a list called Home, which can contain any subset of people you follow.

**Comment by hoodiek** [comment]
@joyeusenoelle while almost related, it does make onboarding users new to the list feature harder to have to make a whole new list to replace the home timeline with in many cases, near-all users they follow encased within. still worth implementing home timeline as a list imho

**Comment by hoodiek** [comment]
@Gargron please explain why this issue has been closed

**Comment by trwnh** [comment]
Presumably duplicate / similar to #6058? (And #5915, #6152, #7182, #7187, possibly #7201 #5958 and maybe a few that I missed...)
