### ISSUE TITLE
Remote follow doesn't works

### ISSUE THREAD

**Issue by rhaamo** [tootsuite/mastodon#736]
I have installed my own mastodon instance and it seems to works except that issue.

I have tried to "remote follow" someone using mastodon.social instance button, but the form threw an error saying ```Could not find the required redirect URL for your account```.

I have then tried from my instance, by searching using the syntax ```username@mastodon.social```, I can then click on follow but that's all, my timelines doesn't updates and I doesn't appears to the user's followers list.

I have no errors in my logs, and sidekiq seems to be running without issues (no failed jobs).
The "virtual" account is created in my instance but I see ```PuSH subscription expires	Not subscribed``` is that related too ?

What can be wrong or what can I have missed about that feature ?

**Comment by rhaamo** [comment]
Deleted database and FLUSHALL of redis then re-ran migrations and account creation but still the same problem.

Any hints how to debug this ?

**Comment by rhaamo** [comment]
Well It was a SSL issue. Used FULLCHAIN instead of CERT and it works.

**Comment by Ell** [comment]
@rhaamo I'm running into this exact issue, can you give any more details on what the cause was?

**Comment by derintendant** [comment]
@Ell Check your SSL/TLS configuration. I ran into this problem with Instances that were available over IPv6 as well as IPv4. The sample nginx config does not include a listen directive for IPv6, so this can cause problems.

**Comment by davidcelis** [comment]
@derintendant Could you provide an example of what the IPv6 listen directive would look like? I have one but it still isn't working for me:

```nginx
server {
  listen 80;
  listen [::]:80;
  server_name example.com;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name example.com;

  # …
}
```

**Comment by maop** [comment]
Thank you, i deleted the ipv6 part in my nginx conf... also now put the fullchain cert. And now "Remote Follow" works just fine!

But now in the federated timeline i can't see their posts, follows, etc... :-/ any ideas?

**Comment by colegleason** [comment]
@maop can you give an example? Remote follow isn't working for me either and I think it might be related.

**Comment by maop** [comment]
@colegleason i just deleted this line in my nginx config:
`  listen [::]:80;`
And used the fullchain.cert that let's encrypt gives me instead of just domain.cert 

That's all i did.

Regarding the federated timeline in another issue they said:

> That's expected behavior. The Federated Timeline is made from the toots by people that are on your instance, and the ones by people on remote instances that people on your instance follow, since they started following them. If you don't follow anyone, or follow a few people and they haven't tooted since you started following them, you shouldn't see anything in there
https://github.com/tootsuite/mastodon/issues/1104#issuecomment-292324455

So i guess mine is working fine, just not a lot users yet...

Since commenting on this issue i have added several users from 3 different instances, and everything works fine avatars, profile image, etc....  i just can't see their entire "follow list" only people i know or are in my instance ... i would guess this is intended.

**Comment by colegleason** [comment]
Ah, I think I have the reverse problem. I can follow others, but they can't follow me from a different instance.

**Comment by colegleason** [comment]
Oh no, actually I also see "Could not find the required redirect URL for your account" if I try to remote follow someone from the web page. I am already using fullchain though, and I commented out the line you mentioned.

**Comment by maop** [comment]
have you restarted everything? nginx, mastodon-web.service, mastodon-sidekiq ?

**Comment by colegleason** [comment]
Yeah, I also rebuilt everything with latest pull.

**Comment by colegleason** [comment]
@maop Should LOCAL_HTTPS be set to true?

**Comment by maop** [comment]
i have it set to true yeah... 
i just followed the "production guide" last night... left everything that didn't need change untouch

Also i don't use docker, everything was done in a LXC container.

**Comment by sys0dm1n** [comment]
I had the same issue, by removing let's Encypt location block everything worked fine:
`        location ~ /.well-known {
                allow all;
        }`
I hope this might help others with my case.

**Comment by almet** [comment]
Using haproxy, I had trouble with this. I needed to add some headers from my load balancer / SSL termination endpoint. Here is the configuration file in case it helps. https://github.com/almet/infra/blob/master/haproxy/haproxy.cfg#L163-L166
