### ISSUE TITLE
Video modal extends beyond screen

### ISSUE THREAD

**Issue by mal0ki** [tootsuite/mastodon#7361]
Referencing #5956  and @yuntan  , hoping you can help fix this as you were working on the modal last. 

Check this as an example of a large-dimension video. When opened in a modal it extends beyond the screen: 

https://mastodon.social/@WAHa_06x36/99972837564881692

To reproduce, paste link in search, open by pressing <- -> arrows next to fullscreen then press play when pressing play it pops outside (as per 2nd screenshot)

![image](https://user-images.githubusercontent.com/28316305/39652402-b62bfe70-4fed-11e8-987a-3dd488661457.png)

![image](https://user-images.githubusercontent.com/28316305/39652469-f1435b98-4fed-11e8-800e-fc9e240e3ce8.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I just checked and this seems fixed in master. Never mind
