### ISSUE TITLE
language portuguese is not filtered out of timeline

### ISSUE THREAD

**Issue by Schnappa** [tootsuite/mastodon#7362]
The Portuguese language is not filtered out of the timeline although the tick in settings is checked.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
Can you give an example of a toot that didn't get filtered out?

**Comment by nightpool** [comment]
hmmmm... looks like those toots are marked `pt-BR` but the filter is marked `pt`.... maybe that's the problem?

**Comment by Schnappa** [comment]
I only have German and English in the list which should not be filtered. This worked fine until a few days ago when the Portuguese started flooding my timeline.

**Comment by mal0ki** [comment]
This did prompt some further discussions on the discord about our filtering of languages. And how to make it better, not sure if we actually came up with a good answer though.

**Comment by Strit** [comment]
I also get many languages shown in my timeline, even though I only ticked the boxes to show English and Danish.
I get German, Japanese/Asian of some sort, french etc.
