### ISSUE TITLE
Displayed 500 error at WebUI when unfollowing other instance's account at first

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#7367]
If I unfollow the account of another instance, displayed "500 Internal Server Error" at WebUI.
Also, although it seems to have failed in unfollow, it actually succeeds.
This will not come out when following  and unfollowing the next time.

environment: Equivalent to master 2ef9d6505 ( difference is [here](https://github.com/tootsuite/mastodon/compare/master...mayaeh:for-edge ) )

The output to the server log was as follows:

bundle[26483]: [ff518863-fd34-4f35-ba72-db7f0dd4cac6] method=POST path=/api/v1/accounts/3/unfollow format=html controller=Api::V1::AccountsController action=unfollow status=500 error='JSON::LD::JsonLdError::InvalidIdValue: invalid @id value: value of @id must be a string or hash if framing: nil' duration=150.61 view=0.00 db=11.86

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Was the other server hubzilla by any chance?

**Comment by mayaeh** [comment]
No, it is my other Mastodon instance's account.
But that Instance is not latest master, it merged master up to 28b366d.

**Comment by Gargron** [comment]
Okay... Is there a longer stacktrace? With a line number?

**Comment by mayaeh** [comment]
I'm sorry I'm late.
Yes, it's [here](https://gist.github.com/mayaeh/21899cd78e0cc74b71297ba44163a8c1) .

Also, I merged the opponent's instance up to the latest master 2ef9d650520f95e0b1b4b292bce7b80b9967f146.

**Comment by Gargron** [comment]
I think I know why this could happen. The error occurs when any "id" attribute is nil. Since #7160 ActivityPub payloads use a db value for "id", but previously stored follows would have nil in that column.

**Comment by mayaeh** [comment]
I merged up to the latest master 2f63d52b925733520b668a2302e7e38d67251c71 and unfollowed another account I was following from before.
There was no error. Thank you!
