### ISSUE TITLE
Toggling `Show More` opens same post in multiple columns

### ISSUE THREAD

**Issue by zacanger** [tootsuite/mastodon#7386]
![bug](https://user-images.githubusercontent.com/12520493/39675685-f3b5ca62-511b-11e8-906f-624d8bf5721a.gif)

When clicking `show more` on a post in one column, if the post exists in other columns, they all open. This feels unexpected.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by charlag** [comment]
I remember when this wasn't the case and I know that it's intentional. So...

**Comment by zacanger** [comment]
@charlag oh huh, it's a feature? It seemed a little strange to me. I'll close the issue then!

**Comment by charlag** [comment]
Yeah, I guess people were annoyed when they had to open the same thing in multiple places
