### ISSUE TITLE
Need to refresh page after Back to Federated Timeline

### ISSUE THREAD

**Issue by Guimik** [tootsuite/mastodon#7400]
Hi, 
I need to refresh the page after clicking Back and Federated Timeline.
Don't know if that's an issue or from my own part.
Images are better than my english.

Mike
![issue3](https://user-images.githubusercontent.com/31242178/39709615-a64ad31c-521a-11e8-9183-c0e694e09bb1.gif)

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Doesn't seem to be an issue on latest master, does it?

**Comment by Cassolotl** [comment]
Something like this happens to me oftenish on dev.glitch.social. It's intermittent, and I've not noticed the pattern for how to reproduce it yet.

**Comment by Guimik** [comment]
On the latest master yes. (sorry if i'm not in the good place)
It happens only with the federated timeline link in the navigation.

**Comment by ThibG** [comment]
Next time that happens, it would be helpful to have a backtrace from your browser's console.

**Comment by Guimik** [comment]
Console screenshots:
![capture1](https://user-images.githubusercontent.com/31242178/39726211-a93c61c4-524e-11e8-93c7-28dab3d72a96.PNG)
![capture](https://user-images.githubusercontent.com/31242178/39726225-ad7d5dec-524e-11e8-8c56-e9ebf4e6d5bd.PNG)

**Comment by Zatnosk** [comment]
I just updated to v2.4.0rc1 and is hit by this error repeatedly, even after refreshing and hard-refreshing (ctrl+shift+R).

(Ignore the websocket errors, that's very likely a misconfiguration of my webserver)
![mastodon_error](https://user-images.githubusercontent.com/472541/39748635-e00a60ae-52b0-11e8-882d-fb8b2e4f7de6.png)

**Comment by ThibG** [comment]
Ok, for some reason, on `app/javascript/mastodon/features/ui/containers/status_list_container.js:24`, `statusForId` may be undefined, but I can't understand why.
Returning false early if `statusForId` is undefined should fix the crash, but I'm not sure why `statusForId` can be undefined in the first place…
