### ISSUE TITLE
Question: how does mastodon implement forwarding from inbox?

### ISSUE THREAD

**Issue by git-marijus** [tootsuite/mastodon#7403]
https://www.w3.org/TR/activitypub/#inbox-forwarding

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
see https://github.com/tootsuite/mastodon/issues/5631, where this is documented (happy to pull this out somewhere else if you can think of a good place for it to live

**Comment by git-marijus** [comment]
Thanks!
