### ISSUE TITLE
About pages have gone walkies in 2.4.0rc1

### ISSUE THREAD

**Issue by TrollDecker** [tootsuite/mastodon#7409]
I just updated to the new RC, and went to check my `about/more` page to verify the version number and... it's gone.

As has the main `about` page.

As in, any attempt to reach them, whether logged in or not, simply reports "We're sorry, something went wrong on our end."

So, either I've missed something in the update notes - unlikely, since aside from having to upgrade Ruby (fun) I followed every instruction there to the letter - or there's been a heckup in the release itself?

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by TrollDecker** [comment]
Uh... never mind. This was premature and they returned on their own. I'm still not sure why there was even a delay, though. o.O

But that's a matter for another issue, I guess. :neutral_face:

**Comment by ChatonneLibertaire** [comment]
It was my first time doing upgrade but I'm pretty sure this shouldn't happen :/
This lasted for approximately 10 long minutes for me. Maybe this issue can be reopened ?

**Comment by TrollDecker** [comment]
I'm not sure what the etiquette here would be regarding that, so I don't know whether reopening this issue and editing it would be the right thing to do or creating a new one. :confused:

**Comment by ChatonneLibertaire** [comment]
Ok sure. As you wish :)
Personally I think it's fine to reopen this one (it will still appear on the first issues page)
