### ISSUE TITLE
Server-side OCR to autofill image descriptions

### ISSUE THREAD

**Issue by LogicalDash** [tootsuite/mastodon#7419]
Sometimes people post screenshots of text and don't include an image description. That's not great, but it's going to happen sometimes, and visually impaired users don't deserve to be locked out of any discussions just because one poster or another was forgetful or plain inconsiderate.

Images uploaded without descriptive text should be run through an Optical Character Recognition engine, and if that finds anything legible, that should become the descriptive text.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThisIsMissEm** [comment]
You could probably implement this as something using Machinebox, though I'm not sure it's something Mastodon core needs.
