### ISSUE TITLE
Brocken images on first load with 2.4.0rc1 and Firefox

### ISSUE THREAD

**Issue by ChatonneLibertaire** [tootsuite/mastodon#7430]
Step to reproduce:
* Open Firefox (tested with Firefox 59.0.2)
* Login to your instance (tested with an instance on 2.4.0rc1)
* Enable the Firefox setting `show windows and tabs from last time` (the behavior doesn't appear without it)
* Relaunch Firefox
* Scroll through your timeline
* Some images/media will be broken after the first page (if you go to the link of image directly it works fine though)
![screenshot from 2018-05-09 18-05-33](https://user-images.githubusercontent.com/39115886/39828629-a6a66458-53b3-11e8-899e-dd5c903b2871.png)
* Reload the page
* Scroll through your timeline as previously
* The images do not appear broken

This was repeated several times and is reproducible with a fresh Firefox profile.
Chromium does not exhibit this bug (as far as I could see).
Also, Mastodon 2.3.3 didn't seem to have this bug, this is new to the 2.4.0rc1.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
@akihikodaki Could this be service worker caching issues?

**Comment by QueerNeko** [comment]
I'm also having similar issues with an instance on 2.4.0-rc1. The problem occurs when using Safari on iOS 11.3.1 and Chrome 57.0.2987.98 on Linux. Reloading the page does fix the missing images. It does seem related to caching.

Chrome is throwing me these errors in the console:
![screenshot from 2018-05-11 10-31-44](https://user-images.githubusercontent.com/879911/39927710-84989d8e-5509-11e8-86f5-dfa69a27e6d2.png)

**Comment by Gargron** [comment]
@akihikodaki What if we test presence of navigator.storage.estimate and skip caching entirely if it's not present?

**Comment by akihikodaki** [comment]
@Gargron I'm thinking about that. However I want to confirm that fixes the bug before applying a patch. Now I'm testing on Microsoft Edge, guessing it also needs such a change.

**Comment by akihikodaki** [comment]
> Now I'm testing on Microsoft Edge, guessing it also needs such a change.

The guess is correct and a patch is now at #7460. It is expected to solve the problem on Chrome 57.0.2987.98 and hopefully one on Safari on iOS 11.3. Still not for Firefox 59.0.2.

**Comment by ChatonneLibertaire** [comment]
For Firefox I get the following error message in the console:
```
Service worker event waitUntil() was passed a promise that rejected with 'TypeError: NetworkError when attempting to fetch resource.'.
```
Each time this message appears, corresponds to a "broken" image (same thing with profile pictures).
Once reloaded those error messages don't appear anymore.

**Comment by akihikodaki** [comment]
Thank you for the information. But I have no idea why the message is shown; it is basically indicating a problem on the network or the server, not on the client.

**Comment by akihikodaki** [comment]
I could reproduce `NetworkError` with CORS violation.
```
> fetch('https://example.com')
Promise { <state>: "pending" }
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://example.com/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
TypeError: NetworkError when attempting to fetch resource.[Learn More]
```

@ChatonneLibertaire, I wonder if the instance with the problem uses an external object storage without CORS header, as described in #6941. (But my inference is wrong if you can reproduce the issue on your instance, `anarchism.space`; the instance does not seem to use an external storage.

**Comment by ChatonneLibertaire** [comment]
@akihikodaki I'm not sure to understand completely the issue but yes `anarchism.space` has no external storage that I know of :/ It's basically running the "default config" using docker.

**Comment by ChatonneLibertaire** [comment]
So I tried with another instance that recently upgraded to 2.4.0rc1 and it's giving me the same issue :/ cc @wxcafe (for `social.wxcafe.net`)

**Comment by akihikodaki** [comment]
I can now reproduce the issue thanks to mstdn.maud.io, the first instance which is updated to v2.4.0rc1 with correct CORS and I use. I hope I can provide a fix soon.

**Comment by ChatonneLibertaire** [comment]
Awesome! :)
For the record, the issue seem to have disappeared after an upgrade to Firefox 60.0 :/

**Comment by akihikodaki** [comment]
I found that Firefox somehow fails to fetch with `event.request` if it is asynchronous (it fetches in a promise callback in this case.) Such a usage can be found in service workers spec and should be valid:
https://w3c.github.io/ServiceWorker/#execution-context

So I guess it is a bug of Firefox, and fixed in 60.0. @Gargron, Firefox 60.0 was just recently released and may not be deployed well. Should I add a workaround for the prior versions, or is it OK to leave as is? (I'll update my Firefox if so.)

**Comment by ChatonneLibertaire** [comment]
I think adding a workaround if it's not to complicated might be a good idea. Firefox 52.8 is still the latest ESR and I'm not sure if this fix has been backported yet (might worth checking)

**Comment by ChatonneLibertaire** [comment]
Mmh seems like 60 is the new ESR: https://www.mozilla.org/en-US/firefox/organizations/
However 52 still the one used in debian at the moment (ESR 60 is still in the debian `experimental` repo)

**Comment by Gargron** [comment]
@akihikodaki I think the main thing is that online experience must not be negatively impacted in any way just for the sake of offline experience. If this function makes the app unusable while online on some browsers... Then we should disable it.

**Comment by akihikodaki** [comment]
> I think adding a workaround if it's not to complicated might be a good idea. Firefox 52.8 is still the latest ESR and I'm not sure if this fix has been backported yet (might worth checking)

I have to consider more about the implementation, but I don't think it would be so complicated.

> I think the main thing is that online experience must not be negatively impacted in any way just for the sake of offline experience. If this function makes the app unusable while online on some browsers...

I wonder if we need a workaround for the older versions, not meaning to disable Firefox entirely.

@QueerNeko 
```
> navigator.storage
StorageManager {}
```
I guess methods in the prototype is not shown. You may see the arrow at the left side; click it and see if the method is present.
The version is obsolete. I wonder if there are Android devices which has old variant as stock browser or cannot run the later version. In the case I would add a workaround.

**Comment by akihikodaki** [comment]
> I found that Firefox somehow fails to fetch with event.request if it is asynchronous (it fetches in a promise callback in this case.) Such a usage can be found in service workers spec and should be valid:

It was wrong. Apparently Firefox sets `cache` mode to `only-if-cached` when fetching images with some unknown condition. As far as I read, it is not well-defined in Service Workers spec how `event.request` would be, and it may be largely dependent on implementations. I would add a code to handle this mode just in case.

**Comment by akihikodaki** [comment]
Anyway it is nonsense to set `cache` mode to `only-if-cached`; it means you can see images only when they are cached.
