### ISSUE TITLE
Use MediaProxyController as fallback and not the other way around

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#7440]
Puma is slow, and a Redis lock and Postgres query could be avoided if `MediaProxyController` was used as a fallback in case the front-end webserver cannot find a media file, and not the other way around.
Haven't done any benchmark since I haven't implemented it, but I think this could greatly improve performances.
The downside is that it would require changes in the front-end webserver configuration.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
I don't understand what you are saying here. MediaProxyController is only used at all when media attachment file has been deleted

**Comment by ThibG** [comment]
Right, I have indeed jumped to conclusions and thought it was used for all media regardless of their state. You can disregard this issue.
