### ISSUE TITLE
Can't dinstinguish a boost from an original toot in admin view

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#7449]
The admin view of an user's toot is still broken, not indicating whether a toot is a boost or not, and not displaying media when the toot is boosted.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Can you submit a fix? I suggest displaying "Boost" with the boost icon in place of the public / private / direct indicator. Media should be a matter of using status.proper

**Comment by ThibG** [comment]
I currently have this, but I'm not completely satisfied, it's not visible enough imo
![screenshot-2018-5-11 etat du compte - thib - mastodon instance perso de thibg](https://user-images.githubusercontent.com/384364/39938607-c7da8a4a-5553-11e8-831c-3d094286fe1b.png)
