### ISSUE TITLE
posix-spawn 0.3.13 causes build error in x86

### ISSUE THREAD

**Issue by hcmiya** [tootsuite/mastodon#7453]
cf. https://github.com/rtomayko/posix-spawn/issues/78

We migit as well fix the version to 0.3.12 or use master branch for workaround in Mastodon release.
I adopted the former method for my instances: https://js4.in/repo/gitweb.cgi?p=v6don;a=commitdiff;h=a50c459b8d234ee428dd022fe5f65af20ee7ae6a;hp=f798f52658c5aafc788102090e3c65ece2b6f4b7

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I'm ok with 0.3.12, feel free to submit PR
