### ISSUE TITLE
We're sorry, but something went wrong on our end.

### ISSUE THREAD

**Issue by RussNelson** [tootsuite/mastodon#7454]
You're sorry, but something went wrong on your end, and your error message gave me no indication of how I might fix the problem. The mastodon pounding on the keyboard is cute, though.

The install went just fine. One possible hitch is that I'm doing port forwarding from a server with a public IP to a Raspberry Pi running mastodon at my home. Here's the ssh line:
ssh -n -N -R 192.203.178.252:443:0:443 -R 192.203.178.252:80:0:80 root@192.203.178.252 

The server name is m.russnelson.com if you simply must see the mastodon. Trust me, he's cute. Frustrated, but cute.

There's only one line in error.log. I don't think the ssh is the problem because it's accessing localhost and nobody is listening on port 3000 on my machine.
2018/05/12 06:03:58 [error] 26960#26960: *94 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: m.russnelson.com, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:3000/", host: "m.russnelson.com"

* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X ] This bug happens on [mastodon-2.4.0rc1](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
Sounds like a permissions issue. Did you forget to set the permissions on your server directories?

**Comment by Gargron** [comment]
>2018/05/12 06:03:58 [error] 26960#26960: *94 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: m.russnelson.com, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:3000/", host: "m.russnelson.com"

That sounds like Puma on port 3000 isn't running, maybe? You need to check application logs. For example, `journalctl -u mastodon-web`

**Comment by RussNelson** [comment]
AHA! Thanks, I had missed a few installation steps.
