### ISSUE TITLE
Could not authorize using a client application because of new doorkeeper

### ISSUE THREAD

**Issue by h3poteto** [tootsuite/mastodon#7455]
I'm a developer of [Whalebird](https://github.com/h3poteto/whalebird-desktop) which is a mastodon client for desktop application.

I can not authorize new mastodon instances using the client application, because `doorkeeper` v4.3.2 has a bug to check `redirect_uri`.

In `doorkeeper` v4.3.2, it checks `redirect_uri` using `Helpers::URIChecker`:
https://github.com/doorkeeper-gem/doorkeeper/blob/v4.3.2/lib/doorkeeper/oauth/authorization_code_request.rb#L48-L53

And `Helpers::URIChecker` confirms the URI, but it does not consider `native_redirect_uri`:
https://github.com/doorkeeper-gem/doorkeeper/blob/v4.3.2/lib/doorkeeper/oauth/helpers/uri_checker.rb#L5-L10

So, my client application can not authorize to new mastodon server.

At the old doorkeeper; for example v4.2.6, it does not use `Helpers::URIChecker`:
https://github.com/doorkeeper-gem/doorkeeper/blob/v4.2.6/lib/doorkeeper/oauth/authorization_code_request.rb#L47
so, I can authorize old mastodon instances.

At the master branch of `doorkeeper`, it is fixed:
https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth/helpers/uri_checker.rb#L6
doorkeeper-gem/doorkeeper@bb90fe1

But the new version has not yet been released, so I can not update `doorkeeper`.
Can I downgrade the version of doorkeeper to v4.2.6?

What do you think?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
cc @ykzts / #5898

**Comment by ykzts** [comment]
#7456

**Comment by h3poteto** [comment]
Thank you!
