### ISSUE TITLE
Scroll position is reset when clicking on a status in any column

### ISSUE THREAD

**Issue by barzamin** [tootsuite/mastodon#7463]
When a column is scrolled down, clicking on a status resets the scroll position to the top.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
@ThibG Could this be related to the scrolling code?

**Comment by beatrix-bitrot** [comment]
is there a special way to reproduce this? i just tried on my instance and it didn't happen

**Comment by ThibG** [comment]
Can't reproduce it either, and can't think of any recent change related to this :/

**Comment by Gargron** [comment]
Seems fixed in master

**Comment by barzamin** [comment]
False report due to stale webpack cache. Sorry.
