### ISSUE TITLE
mastodon home screen app on iOS is not always working with service worker

### ISSUE THREAD

**Issue by youennf** [tootsuite/mastodon#7473]
When adding to home screen, the URL that is used to load the app is https://mastodon.social/web/timelines/home
When loading https://mastodon.social/web/timelines/home without being logged in, the service worker is returning a redirected response. As per fetch spec, this will fail the load.

Testing can be done on Mac/Safari or Mac/Chrome by doing the following:
  - Go to https://mastodon.social/ and log in
  - Make sure service worker is installed
  - Log out
  - Go to https://mastodon.social/web/timelines/home
It should go through the service worker and fail

mastodon service worker could be updated to check for the redirection in case of navigation loads.
Or the manifest.json could point to another URL that is not redirecting.

**Comment by Gargron** [comment]
I am not sure what the expected behaviour is when you're logged out? Like, it should take you to the login screen, right?

**Comment by trwnh** [comment]
Yeah, if trying to access a URL that requires auth, then it should probably redirect to an auth page (ie login).

**Comment by Gargron** [comment]
This isn't just in ios by the way. I was loved out on chrome in android and the app showed up as crashed when i should be redirected to login form

Any ideas @akihikodaki
