### ISSUE TITLE
Flesh out protected mode

### ISSUE THREAD

**Issue by naums** [tootsuite/mastodon#7477]
A problem on other social media sites are trolls and mean people, who respond to toots or posts by shouting insults at you. A way to limit their success is the block-button, but that does not suffice, because people can just create new accounts and go on. 

The idea is to have a profile mode, like the protected mode, where only certain people are allowed to answer to your toots. My idea is, people who follow you. Together with the protected mode you fully decide who follows you. Also adding a "Disallow to follow"-button, so I can decide, that certain profiles are not allowed to follow, but I can still see their tweets and they still see mine. 

This is purely a feature request / start of a discussion. If this is the wrong place for that, please let me know.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
I think you already can control who follows you with Locked account?
I'm not sure how Mastodon can prevent people from mentioning you. I think the only thing possible to implement is hiding notifications. Then you would need something like a whitelist for notifications?

**Comment by trwnh** [comment]
Definitely sounds like you could just lock your account (so that you have to approve followers), and then set post privacy to followers-only (so only those people you approve can see interact with your posts).

If there's anything missing from your desired use case, can you clarify that? Or would the above resolve your use case?

**Comment by naums** [comment]
Okay, now I have a question. On birdsite when I lock down my profile noone can boost my posts. Is that behaviour the same on Mastodon? If so, locking down may not suffice. 

When I block people they cannot mention me, so the mechanism of preventing a set of blacklisted accounts from hurling insults at me is there. But that also means, these people will never see a post of me again, until I unblock them. 

The basic idea is, that one could blacklist accounts from mentioning but still keep the ability to be boosted and the other accounts may see their posts. The current mechanisms may solve the privacy and insult-problem, but also limits the range of peoples posts.

**Comment by charlag** [comment]
It's not really like Twitter, it's not all-in or nothing. You can control who follows you by locking your account and you can control visibility of your toots on post-by-post basis: there's a "followers only" option. When post is followers only, it cannot be boosted by anyone but you.

My concern is that we already have pretty complex visibility system and adding more options would be really confusing. I think the best thing would be muting people on the client side and I'm not sure it is required in a vanilla web client.

**Comment by mal0ki** [comment]
This sounds a lot like bunker mode? #7132

**Comment by naums** [comment]
It's not the same, but I guess @charlag explained it well. Closing the issue.

**Comment by trwnh** [comment]
Yeah, you can post publicly even if your account is locked. If you want to make something visible to followers that you approve, then you can post it as followers-only. That way, anyone can boost your public posts, but you still approve who follows you and can see your followers-only posts.
