### ISSUE TITLE
Display full username in a tooltip on search results.

### ISSUE THREAD

**Issue by roipoussiere** [tootsuite/mastodon#7478]
Search results displays truncated usernames if its too long:

![capture du 2018-05-14 15-08-58](https://user-images.githubusercontent.com/1665542/39999427-5dd66820-5789-11e8-8f7f-bd9fe95c24a1.png)

It could be useful to add the full username in tooltip, like this:

![capture du 2018-05-14 15-13-13](https://user-images.githubusercontent.com/1665542/39999480-77a86776-5789-11e8-816c-4731cd730e00.png)

Related: #1350 (but this issue is about messages, not search results)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by spaceottercode** [comment]
I agree. Some users have multiple accounts and some users have long usernames and/or display names. When this ambiguity arise I find myself clicking on each matching subset one by one until I find the right one. A tooltip could prove useful if possible.

![tooltip](https://user-images.githubusercontent.com/36016546/41623313-2fcf377c-73c7-11e8-839b-b01e2ec852b1.png)
