### ISSUE TITLE
Improve payload format of web push API

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#7490]
Previously web push API payloads were only used by the web UI, so the JSON contents are not documented and they might not be consistent with outputs of other APIs like REST or streaming. Before this feature is in a final release, this needs to be corrected.

cc @sorin-davidoi @dagagren

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by DagAgren** [comment]
There are a few things to consider for this:

1. Notifications are space-constrained (and when I forward them, they are a bit more: I can fit about 3k of payload in a forwarded notification), so the data should be optimised to not be too redundant. Fields that can be inferred should probably be left out, for instance, and fields that can be shortened should maybe also be.
2. It would be nice to be able to tie a notification strongly to the status it relates to, when opening the notification.

Looking at the data from this perspective, I see a few things:

1. There is no ID for the status included.
2. There is a URL, but this could be inferred from an ID.
3. The server URL is repeated a few times.
4. The "icon" fields a bit mysterious, as is "tag".
5. The action object seems a bit on the chatty side, but it does shorten its URL a bit, which is nice, although perhaps it could be shortened even more.

For future consideration, if https://github.com/tootsuite/mastodon/issues/4093 gets implemented, the payload should also contain the current unread count, as at least on iOS you can update the badge on the app icon from a notification.
