### ISSUE TITLE
Validation on contact username field in site settings

### ISSUE THREAD

**Issue by Pneumaticat** [tootsuite/mastodon#7492]
Currently it's just a free-form text box - it'd be nice to have some sort of validation, as the data format is unclear (e.g. does it want "@kevin", "@kevin:potatofrom.space", or just "kevin"?) (It's the latter.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Implemented!
