### ISSUE TITLE
No confirmation email

### ISSUE THREAD

**Issue by Digitalyn** [tootsuite/mastodon#750]
Hello,
Just created an account on https://mastodon.social, but never received any confirmation email, even after hitting resend several times. I did check my spam folder and nothing was there either.
Is there anything I could do to finalise my sign up?
Thanks in advance.

**Comment by WDC1** [comment]
did you check your spam folder?

**Comment by Digitalyn** [comment]
I did yes and nothing.

**Comment by fabean** [comment]
I've experienced the same issue just within the past hour.

**Comment by nashe** [comment]
I guess it's related to what was being discussed in #763 (the title is misleading). Wait a little bit more and check your spam folder!

**Comment by Digitalyn** [comment]
Thank you for your answers. I'll be waiting patiently.

**Comment by fabean** [comment]
For me it finally came through right after the turn of the hour. I'm assuming they're sending using something that throttles emails and with the spike in new signups all emails got queued to the next hour.

**Comment by Digitalyn** [comment]
Still nothing here. I even changed my spam settings on my inbox, hit "resend confirmation" and nada. I can see my account was created, I just can't log in it to use it. I suppose the server is under heavy load, which is good, shows many users are interested.

**Comment by SenedSened** [comment]
Same here, Weird thing is I created another account using an @hotmail.com address and got the confirmation email instantly

**Comment by symac** [comment]
I had the same issue on mastodon.social using an email from my own domain (which is basically a redirect to a gmail account) and never received anything. Subscribing with the gmail address directly works fine :(

**Comment by ashfurrow** [comment]
@Digitalyn Hi there, just following up on this – did your email ever show up?

**Comment by Digitalyn** [comment]
Hello and thanks for you message.
And nope, never got any email.

**Comment by ashfurrow** [comment]
Yikes, hmm. Seems like a mastodon.social problem – it could have been resolved by now. Would you mind trying to re-send the confirmation email? 🙇

**Comment by Digitalyn** [comment]
Oh! Just hit the resend button and right away the mail was here. This is definitely fixed now. Thank you!

**Comment by ashfurrow** [comment]
I'm glad to hear it! I'm going to close this issue, but if you have other bug reports or feature requests, feel free to open a new issue. Thanks!

**Comment by 7h3h4ckv157** [comment]
I'm experiencing the same issue on the App!

**Comment by raeeceip** [comment]
6 years later, same issue

**Comment by jcb4** [comment]
Having this issue today, 1/14/23
