### ISSUE TITLE
Error: "oauth_access_tokens" does not exist

### ISSUE THREAD

**Issue by corbindavenport** [tootsuite/mastodon#7502]
Yesterday, I noticed my instance had stopped refreshing timelines (all toots were from 1 hour ago or more), so I restarted the docker containers. After that, the instance won't load at all - I get the 'We're sorry, but something went wrong on our end.' message on the site.

Here's a log: https://pastebin.com/VeDZ5jfc

The only error I can see is  "ERR! error: relation "oauth_access_tokens" does not exist" from the streaming_1 container. I can't figure out how to fix this. Any help would be much appreciated. My instance is running v2.3.3.

* * * *

- [✓] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [✓] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Looks like you are connecting to an empty database. Check that the path to the data volume for the postgres container is the same as before.

**Comment by Gargron** [comment]
No it's in the docker-compose.yml file

**Comment by corbindavenport** [comment]
I couldn't figure out the issue, so I restored my server to a backup from a few days ago, stopped the Docker containers, ran the media cleanup commands, and rebuilt the Docker containers. That did the trick.

Thanks for your help @Gargron!
