### ISSUE TITLE
Mastodon doesn't handle videos from external software correctly

### ISSUE THREAD

**Issue by zcdunn** [tootsuite/mastodon#7515]
When an mp4 or webm is posted from other software, mastodon labels it a gif, mutes it, and removes video controls in the frontend.

https://pleroma.soykaf.com/objects/83581bca-e04a-435c-8242-1f17b9725d52
https://kawen.space/objects/3b022c86-6f5f-489a-ab9a-08cea44bc5b4
https://pleroma.soykaf.com/objects/13dd2fae-c0aa-4137-92d7-3141a636df35
https://pleroma.soykaf.com/objects/56243330-c536-4318-a4e1-4e6f0eaac59f

**Comment by Gargron** [comment]
This is desired behaviour when there is no audio track.

**Comment by zcdunn** [comment]
Why are video controls removed from a video just because it doesn't have audio? The videos I linked above are longer than a typical gif, so it's weird behavior to treat them that way.
