### ISSUE TITLE
federation breaks on instance with a path in the url (can not follow or reply)

### ISSUE THREAD

**Issue by Nehmulos** [tootsuite/mastodon#752]
On Mastodon:
When I try to follow nee@social.hidamari.blue/index.php I get an error 422.
When I try to reply to nee@social.hidamari.blue/index.php the text stays plain.
When I go to social.hidamari.blue/index.php/nee and use the subscribe button entering "nemu@mastodon.social" I get an error page without any specific message.

On social.hidamari.blue:
When I try to reply to nemu@mastodon.social everything gets properly linked, but nothing arrives at mastodon.
When I try to follow somebody, I get the follow and their notices, but on mastodon, I am not listed on the users "followers" lists.

I am not sure if the "/index.php" path creates the problem, it's just one thing thats different from most other instances. 

Some other things about social.hidamari.blue:
social.hidamari.blue/nee is a 404 error.
all http urls that are not 404s have a 307 redirect to the same https url.
social.hidamari.blue/index.php/ has a 303 redirect to https://social.hidamari.blue/index.php/main/public

**Comment by Gargron** [comment]
It seems like that instance does not have WebFinger configured correctly. Without it, federation cannot work, because it's the part that lets us confirm that a particular user exists on that domain. I wouldn't count this as a Mastodon issue.

**Comment by Nehmulos** [comment]
What exactly is wrong with the webfinger? The basics seem to work for me, although the webfinger acct: uri does not include the url-path. I had a look at I had a look at https://tools.ietf.org/html/rfc7565#section-4  and specifies the acct uri to be only acct:user@host, so I assume it has to be this way. 

Anyway in practice this works for me: 
````curl https://social.hidamari.blue/index.php/.well-known/host-meta````
gives me: 
````<Link rel="lrdd" type="application/xrd+xml" template="https://social.hidamari.blue/index.php/.well-known/webfinger?resource={uri}"/>````
Which leads to: 
````curl -H "Accept: application/xrd+xml" https://social.hidamari.blue/index.php/.well-known/webfinger?resource=acct%3Anee%40social.hidamari.blue````
And that gives me a normal looking result:
````
<?xml version="1.0" encoding="UTF-8"?>
<XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
 <Subject>acct:nee@social.hidamari.blue</Subject>
 <Alias>https://social.hidamari.blue/index.php/user/1</Alias>
 <Alias>https://social.hidamari.blue/index.php/nee</Alias>
 <Alias>https://social.hidamari.blue/user/1</Alias>
 <Alias>https://social.hidamari.blue/nee</Alias>
 <Link rel="http://webfinger.net/rel/profile-page" type="text/html" href="https://social.hidamari.blue/index.php/nee"/>
 <Link rel="http://gmpg.org/xfn/11" type="text/html" href="https://social.hidamari.blue/index.php/nee"/>
 <Link rel="describedby" type="application/rdf+xml" href="https://social.hidamari.blue/index.php/nee/foaf"/>
 <Link rel="http://apinamespace.org/atom" type="application/atomsvc+xml" href="https://social.hidamari.blue/index.php/api/statusnet/app/service/nee.xml"/>
 <Link rel="http://apinamespace.org/twitter" href="https://social.hidamari.blue/index.php/api/"/>
 <Link rel="http://specs.openid.net/auth/2.0/provider" href="https://social.hidamari.blue/index.php/nee"/>
 <Link rel="http://schemas.google.com/g/2010#updates-from" type="application/atom+xml" href="https://social.hidamari.blue/index.php/api/statuses/user_timeline/1.atom"/>
 <Link rel="magic-public-key" href="data:application/magic-public-key,RSA.0aU7z1Y19lt8MBYpKLdgPvqLk5dGOBJ-43wsxq3JT-KvRlr50LGLnQ9brmcaado1iIV7lvnS5HNlbbCMXLkVQP_5ZO9goKlUg9mYpNqoRMQJo4VI6-BhB-E84SAVXC7J1W1eBTCdcI4vZTr7f9Os_yQo1DMP57--U62AuH9NTCM=.AQAB"/>
 <Link rel="salmon" href="https://social.hidamari.blue/index.php/main/salmon/user/1"/>
 <Link rel="http://salmon-protocol.org/ns/salmon-replies" href="https://social.hidamari.blue/index.php/main/salmon/user/1"/>
 <Link rel="http://salmon-protocol.org/ns/salmon-mention" href="https://social.hidamari.blue/index.php/main/salmon/user/1"/>
 <Link rel="http://ostatus.org/schema/1.0/subscribe" template="https://social.hidamari.blue/index.php/main/ostatussub?profile={uri}"/>
</XRD>
````

**Comment by lmorchard** [comment]
If I recall, the thing with webfinger is that the protocol spec **mandates** `/.well-known/` as a fixed path at the root of a domain - that's what's "well known" about it. As in you literally need `https://social.hidamari.blue/.well-known/webfinger`

**Comment by Nehmulos** [comment]
Hello, thank you, I setup some rewrite rules it and it made the difference. I this is where the problem is located.
Now is the question what to learn of it.
All the GNU Social based instances are working just fine with a relative .well-known directory.

The obvious way would be to follow the standard, and open an issue at GNU Social, so it either disables, or shows a big warning when you setup something that won't put .well-known into the domain root. 
The downside of this is that the feature to setup instances when you don't have access to the domain root directory or can't do url rewrites would be lost.

On another note:
For my taste the error messages on Mastodon could be a little bit more talkative, especially the one you get when you get redirected by the subscribe button on the GS instance. Something like: "Webfinger not found on $url/.well-known/host-meta" would be more helpful.
