### ISSUE TITLE
Image upload mishandle file orientation

### ISSUE THREAD

**Issue by keltia** [tootsuite/mastodon#7530]
See post: https://mastodon.social/@Keltounet/100035298425380271

I uploaded 4 images, all in "landscape" mode and they are all treated as "portrait". 

This on mastodon.social running whatever version yesterday.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
duplicate #7487 and fixed by #7514 in master yesterday
