### ISSUE TITLE
posts are not deleted (if one deletes a post, the post remains)

### ISSUE THREAD

**Issue by DanyLives** [tootsuite/mastodon#7533]
if one deletes a post, the post remains

**Comment by kit-ty-kate** [comment]
Is it related to #6849 ?

**Comment by DanyLives** [comment]
everything is resolved

[Daniele Sommaruga - Contact Using Hop](http://GetHop.com/?_hmid=1526640297)

On May 18, 2018 at 10:35 GMT, Kate <notifications@github.com> wrote:

Is it related to [#6849](https://github.com/tootsuite/mastodon/issues/6849) ?
