### ISSUE TITLE
Thoughts on not showing a followers/following number?

### ISSUE THREAD

**Issue by claiire** [tootsuite/mastodon#754]
I really like how mastodon doesn't show a number for how many stars/boosts a post has. I'm not immediately saying that it's a good idea but it gets me thinking about the concept follower/following numbers not being shown.

I think it's apparent that one of mastodon's values is humane design. Good blocking/privacy options indicate that, and a de-emphasis on numbers indicate that. I feel that not showing a number on followers would be an interesting and potentially good addition to that tennet. 

Thoughts?

**Comment by lapineige** [comment]
+1
Hiding the following numbers and list would be a good addition in terms of privacy.
And hiding the followers number, as well as the boost or fav' numbers (already hidden) is a good think not to encourage people to trust something because they see that many people boosted it - it reduce the influence of the social conformism.
So it would be great if you can implement it :)

**Comment by sbernard31** [comment]
I think you should even be able to not be displayed in the following/follower list of people you followed or which following you.

**Comment by lapineige** [comment]
Yeah, it would be a great addition in terms of privacy.

**Comment by Cassolotl** [comment]
Related to #6901 maybe?

**Comment by lapineige** [comment]
You're right, and the discussion is more detailed on this issue.
Should this one be closed ?

**Comment by Cassolotl** [comment]
This one has more thumbs-ups, so it's kind of a shame that we can't merge those over! But yes, I think probably the one with the more detailed discussion should probably survive. Hopefully folks who thumbsed-up this one will see that it's a duplicate and go add their thumbs-ups to the older, more detailed issue.

**Comment by lapineige** [comment]
Yeah, let's just tumbs-up the other one 🙂 
@claiire could you close this issue ?
