### ISSUE TITLE
[BUG] if an excess of notifications of a hidden type exist, notifications do not load

### ISSUE THREAD

**Issue by yiskah** [tootsuite/mastodon#755]
I've been getting tons of Favs and Boosts lately and so I disabled seeing those notifications in column. There's so many that they span multiple "pages." What is happening is that the notifications column seems to load a "page" of all favs and boosts and then hides them and then concludes I have no notifications and will not continue loading "pages" until it finds a reply. The work-a-round is to re-enable seeing boosts or favs so that it starts loading through infinite scroll (no "load more" button...) until it hits a reply, and then I can re-hide boosts. Which defeats the point of hiding boosts to begin with.

Just a bug.

**Comment by Gargron** [comment]
Fixed in #1341
