### ISSUE TITLE
Some replies to old toots don't render in webapp

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#7557]
A toot originally made Nov 30, 2017: https://mastodon.social/@trwnh/99093644445157168
A reply to that toot made 4 days ago: https://mastodon.social/@trwnh/100041744194293965

When loading the original toot in mastodon.social's webapp, the recent reply does not load as a child in the expanded/conversation view. But it loads fine on the status webpage. Also, every other reply seems to load fine in both webpage and webapp.

I suspect this issue has something to do with the fact that it's a self-reply, but nothing I post seems to be showing up. I can self-reply to more recent statuses and they'll render fine in webapp.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (toot was made in v2.4.0rc3, currently being viewed in v2.4.0rc4)

**Comment by trwnh** [comment]
Another example.
Originally made 2 months ago: https://mastodon.social/@trwnh/99664077509711321
Recent reply just now: https://mastodon.social/@trwnh/100062967831098713

Same issue. This one even got a reply from someone else, but the entire subchain is not showing up.

**Comment by trwnh** [comment]
After some further testing, I think it's because they're unlisted. Correct me if I'm wrong, but aren't unlisted statuses supposed to show up in replies, just not in the public timelines?

**Comment by Gargron** [comment]
Regression from #7102, #7148. The API expects pagination but the webapp is not yet ready to do that (also, it's a breaking API change). I suggest rolling back that change to make sure API still returns context unpaginated.
