### ISSUE TITLE
Mute notifications from specific posts or thread [improvement]

### ISSUE THREAD

**Issue by yiskah** [tootsuite/mastodon#756]
IMO a necessary feature to implement in order to keep the site usable for users who have reached a certain level of "popularity" is to make it so when a post gets popular and is producing an excess of notifications, to mute that post to not produce notifications anymore. On sites like tumblr, a post taking off and like 10k+ notes renders the site unusuable because you can't comb through the identical notifications in order to find replies from friends to converse with them. Right now you can disable fav and boost notifications entirely but it's not ideal. Especially because that doesn't solve mass-tagging problems as have been demonstrated could be abused for harassment. 

At minimum, being able to say "this post I made needs to stop telling me that it is being appreciated" while still receiving notifications from less popular posts is crucial. Being able to say "I don't want to be in this conversation thread anymore so I'm muting it" is even more ideal.

In general notification column filtering could always be more robust but this is a specific thing that is necessary for the longevity of users sticking around and not leaving when they get too popular. [as I've had to do on tumblr and other sites.]

This is also something afaik twitter does not have? This is definitely something tumblr doesn't have and would very set us apart from them.

**Comment by hoodiek** [comment]
this is already suggested and outlined in #694

**Comment by swaldie** [comment]
Closing this as duplicate.  Continue discussion of the feature in #694 as recommended by @hoodiek
