### ISSUE TITLE
Streamed Notifications sometimes have incomplete status embedded

### ISSUE THREAD

**Issue by tastytea** [tootsuite/mastodon#7560]
When I get a mention from /api/v1/streaming/user that is a reply to a post my instance doesn't know exists, status→in_reply_to_id is null.

When I /api/v1/search for the URL of the status and fetch it, in_reply_to_id is set to the right value. It is also set to the right value when I get another mention that is a reply to the same "parent" toot.

Is that normal? I expected that the notification always contains the full status.

[Example notification](https://github.com/tootsuite/mastodon/files/2020684/notification_json.txt)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
This is normal and cannot be easily avoided. Finding the replied-to status if it's unknown is an extra HTTP roundtrip so it cannot delay the status from being created when it's processed, otherwise that processing would take up more time and hold up other statuses.

**Comment by pwoolcoc** [comment]
sorry to dredge up this old thread...is there a way to make this eventually consistent? I understand not wanting to hold up other statuses, but is there some way to trigger that extra http call to update an incomplete status? maybe in a sidekiq job or something?
