### ISSUE TITLE
Responsive thumbnail sizes incorrect unfit for public pages

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#7568]
Thumbnails correctly use `srcSet`, but there are multiple issues with the `sizes` attribute:
- The `(min-width: 1025px)` selector is arbitrary and does not seem to fit any existing logic
- `${320 * (width / 100)}px` assumes the image is going to be displayed in a 330px-wide column, while toots in public views are much wider, making the browser select the undersized thumbnail while the full-sized image would be much more fitting

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
1024px used to be the breakpoint of the single-column layout (I think it's smaller now, this value was forgotten in the change). In single-column layout, the thumbnail stretches all the way (100vw), in column layout, the columns are 330px. The component is reused both in public views and web UI and the 330px assumption is wrong for the public views.
