### ISSUE TITLE
Make it possible to filter self starred toots from users you are following 

### ISSUE THREAD

**Issue by highfellow** [tootsuite/mastodon#7573]
I was thinking along the lines that given that Mastodon does not have an algorithm for deciding which posts to show, which I think is a good thing, we need to offer the user ways of making for themselves the decisions that would be made by an algorithm on a different social network. For example, there is already a feature where you can choose to hide boosts made by a user and only show their own toots. 

It might also be useful to be able to show only toots that a user has favourited themselves. At the moment, this probably doesn't happen that often, but it could become a way for someone to indicate that a post they made is particularly important, and that they want all their followers to see it. In other words, as well as the option to 'hide boosts from X', there would be another option to 'show only self starred posts from X'.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
Wouldn't this just encourage people to favorite every single one of their posts? Or, alternatively, wouldn't this just hide all posts from your feed since this isn't popular behavior?

**Comment by highfellow** [comment]
I was thinking people would just favourite a few that they think are important which they don't  want their friends to miss. But maybe that relies too much on people being considerate and using it the way it would be intended. If someone self starred all their toots, I guess they would be more likely to be unfollowed  altogether? The filter could also be available when filtering time lines,  along with 'show boosts' and 'show replies'.

**Comment by trwnh** [comment]
I'm more concerned that people won't use it at all. There isn't really a "sweet spot" there... either not enough people use it, or people use it wrong. It's altogether a bit confusing both in usage and in implementation. But the idea of algorithmic sorting itself is a bit of a touchy subject; it could be possible to have an option to sort posts by how many people interacted with it, but it would have to be an option and not the default.

**Comment by highfellow** [comment]
I am definitely not in favour of a facebook style algorithm. I was more thinking that if we are not going to have an algorithm, then that puts the responsibility on users to make the decisions themselves that an algorithm would make for them, and that the interface should offer them tools which help them do this.

**Comment by Gargron** [comment]
I do not think there is any interest in this approach. Thank you
