### ISSUE TITLE
Not found inbox on the ActivityPub

### ISSUE THREAD

**Issue by ma1uta** [tootsuite/mastodon#7577]
Created a new app and retrieved access_token.
Run command:
```curl -H 'Authorization: Bearer <<access_token>>' -H 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' -D response.txt https://mastodon.social/users/ma1uta```
Got the Actor info.
Run command to search messages in the inbox:
```curl -H 'Authorization: Bearer <<access_token>>' -H 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' -D response.txt https://mastodon.social/users/ma1uta/inbox```
Got the 404 error.

Related issues: #4216, #4595

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
Mastodon doesn't have a GET able inbox, it only accepts POSTs.

**Comment by nightpool** [comment]
(this is because mastodon only implements the s2s API, as documented on https://activitypub.rocks/implementation-report/ it does not implement c2s ActivityPub)
