### ISSUE TITLE
ActiveRecord::RecordNotUnique: PG::UniqueViolation on statuses coming from pleroma

### ISSUE THREAD

**Issue by renatolond** [tootsuite/mastodon#7585]
It seems this might be something similar to #503 but related to pleroma statuses.
It seems there's cases in which pleroma sends a hashtag more than once in the same status, resulting in a pgsql error:

```
May 22 11:38:36 mastodonte bash[2987]: 2018-05-22T09:38:36.821Z 2987 TID-oxod634qr ActivityPub::ProcessingWorker JID-e5ba11ca6257e816f74a0fbf INFO: start
May 22 11:38:37 mastodonte postgres[2998]: ERRO:  duplicar valor da chave viola a restrição de unicidade "index_statuses_tags_on_tag_id_and_status_id"
May 22 11:38:37 mastodonte postgres[2998]: DETALHE:  Chave (tag_id, status_id)=(2605, 100056268039415915) já existe.
May 22 11:38:37 mastodonte postgres[2998]: COMANDO:  INSERT INTO "statuses_tags" ("status_id", "tag_id") VALUES ($1, $2)
May 22 11:38:37 mastodonte bash[2987]: 2018-05-22T09:38:37.114Z 2987 TID-oxod634qr ActivityPub::ProcessingWorker JID-e5ba11ca6257e816f74a0fbf INFO: fail: 0.294 sec
```

I'm having a hard time tracking down examples, but I think this is one of them: https://gauchiste.club/activities/2659ac42-0a74-4e91-9379-8eb5dcf5dfe4. I saw this happening for a while and just retried and it's still happening on 2.4.0rc5.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by lambadalambda** [comment]
Fixed on our end as well.
