### ISSUE TITLE
Back button on "Media only"-timeline returns to previous site

### ISSUE THREAD

**Issue by geez5** [tootsuite/mastodon#7591]
When filtering the local timeline to "Media" an other column opens. When back is clicked on this one it doesn't change the column back to the previous state, the whole tab changes to the previous site.

On the instance I'm using runs 2.4.0rc5.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Fixed in #7581
