### ISSUE TITLE
New DM's column means duplication in Notifications

### ISSUE THREAD

**Issue by bunnybooboo** [tootsuite/mastodon#7600]
2.4 brings the new Direct Message column, which is freaking awesome IMHO. When a toot goes viral this became a big issue. This duplicates notification seen in the notifications column, however.

Might be cool to add a toggle (or something else, I'm not tied to that UI idea), in the notifications to remove the DM's?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by renatolond** [comment]
Maybe duplicate of #7536 ?

**Comment by bobstechsite** [comment]
In fairness they could have probably just added icons next to the "notifications" text for stars, boosts & @ replies. You then click on each to show/hide those notifications in the stream below (faded out icons would indicate what's hidden, solid icons what's shown).

That allows you to quickly and easily hide noise from viral toots and view DMs without needing to pin an extra panel.

**Comment by bunnybooboo** [comment]
Closing as duplicate. I did look @renatolond Clearly not well enough.
