### ISSUE TITLE
Error when "Using http_parser.rb 0.6.1 from https://github.com/tmm1/http_parser.rb (at 54b17ba@54b17ba)"

### ISSUE THREAD

**Issue by Baroriam** [tootsuite/mastodon#7607]
**Hi !**
I don't know if it is a bug from Mastodon or Bundler, but I've got this problem : 
https://github.com/bundler/bundler/issues/6551
It occurs from Mastodon 2.4.0rc2 or rc3.
I did not have time to look further, but just in case, if anyone has an idea to solve this problem...
I'm sorry if it's too quick... **Have a nive day !**

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by IvanClement** [comment]
Having exactly the same issue.
I was wondering if the commit 54b17ba is still available ?
The 'docker-compose build' remains stuck on "Using http_parser.rb 0.6.1 from https://github.com/tmm1/http_parser.rb (at 54b17ba@54b17ba)" for several minutes.
Anyway, I'm not able to complete the 'docker-compose build' step.
Any fix, workaround ?

**Comment by IvanClement** [comment]
Below, the full output of the issue:
```
Using http_parser.rb 0.6.1 from https://github.com/tmm1/http_parser.rb (at 54b17ba@54b17ba)
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/mastodon/vendor/bundle/ruby/2.4.0/bundler/gems/http_parser.rb-54b17ba8c7d8/ext/ruby_http_parser
/usr/local/bin/ruby -r ./siteconf20180525-8-1wh8kpn.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
extconf.rb:17:in `read': No such file or directory @ rb_sysopen -
/mastodon/vendor/bundle/ruby/2.4.0/bundler/gems/http_parser.rb-54b17ba8c7d8/ext/ruby_http_parser/vendor/http-parser/http_parser.c
(Errno::ENOENT)
	from extconf.rb:17:in `block (2 levels) in <main>'
	from extconf.rb:16:in `open'
	from extconf.rb:16:in `block in <main>'
	from extconf.rb:15:in `each'
	from extconf.rb:15:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in
/mastodon/vendor/bundle/ruby/2.4.0/bundler/gems/http_parser.rb-54b17ba8c7d8 for
inspection.
Results logged to
/mastodon/vendor/bundle/ruby/2.4.0/bundler/gems/extensions/x86_64-linux/2.4.0/http_parser.rb-54b17ba8c7d8/gem_make.out

An error occurred while installing http_parser.rb (0.6.1), and Bundler cannot
continue.
Make sure that `gem install http_parser.rb -v '0.6.1'` succeeds before bundling.

In Gemfile:
  goldfinger was resolved to 2.1.0, which depends on
    http was resolved to 3.2.0, which depends on
      http_parser.rb
ERROR: Service 'streaming' failed to build: The command '/bin/sh -c bundle config build.nokogiri --with-iconv-lib=/usr/local/lib --with-iconv-include=/usr/local/include  && bundle install -j$(getconf _NPROCESSORS_ONLN) --deployment --without test development  && yarn --pure-lockfile  && yarn cache clean' returned a non-zero code: 5

```

**Comment by sangfroid70** [comment]
The commit 54b17ba exists and is still available, I've the same issue on non-docker installation.

**Comment by Baroriam** [comment]
SOLVED ! All you need is to open port 9418 ! ;)
Thank you very much @sangfroid70 ! ^^
His explanations (In french) : https://masto.fdlibre.eu/@Sangfroid/100091657939682260

**Comment by sangfroid70** [comment]
In english : http_parser.rb bundle need to clone git://github.com/nodejs/http-parser.git
The protocol git:// need the port 9418 (thanks @Baroriam ) to be opened in your firewall to clone the repository.
That's all folks !

**Comment by IvanClement** [comment]
Indeed once the TCP/9418 port open, everything works fine !

Thank you very much @sangfroid70

**Comment by IvanClement** [comment]
and thank you @Baroriam

**Comment by eniac111** [comment]
It works with:

```
git config --global url."https://".insteadOf git://
```
