### ISSUE TITLE
markdown support in toots

### ISSUE THREAD

**Issue by Aethylred** [tootsuite/mastodon#761]
Basic markdown formatting in toots would be nice, you know;

* bullet points

1. numbered lists

_italic_
**bold**
~strikethrough~

!Z͙A̮̥̳̹͉̙L͕̝̦̭̹ͅGO̭̲̩̘͝!̭̩̲͚̀ ̶̰̲̳H̭͔́e̗̯̪̲͔̫̗͘ ̰̩̯̲̰̘̩c̣̺̬o͏̣̞m̤͟e̹͈͇͉̺s͔͕̙!͏!

**Comment by wboykinm** [comment]
I'd settle for text formatting - no need to stress the `[links]()` or `![images]()` yet.

**Comment by valentin2105** [comment]
Codes with "```" would be awesome too.

**Comment by DeadSuperHero** [comment]
In my experience, I'm not sure it's worth it. Don't get me wrong, Markdown is great for long-form content - blogging, articles, and social networking do benefit from it. However, for anything featuring a stream, there is a downside.

Formatting typically requires a lot of extra characters. For a platform with a 500-char limit for every toot, that can be a problem, as it negatively affects character count. Unfortunately, removing the limit doesn't exactly resolve the problem, as you end up with content that is extremely long-form cluttering up the stream. From a microblogging standpoint, this actually goes against how microblogging is currently being used, and can make the whole thing unwieldy.

You could add a visual filter that just shows part of a post and collapses the rest, but that can make content look ugly really quickly.

**Comment by ThomasLeister** [comment]
Hmm, at first I wanted so have Markdown support, too, but I can understand @DeadSuperHero s point and yes ... he's right I guess. Might not be worth it. And additional text formatting may disturb the uniform look of the timeline... People will actually make use of **BOLD BIG LETTERS** ;-)

**Comment by diomed** [comment]
👍 yes, this has to happen! 
```
code
````
markdown formatting as well!

**Comment by Spunkie** [comment]
I just want to 2nd @diomed & @valentin2105 here, `inline code`,

    code blocks,
> and quote blocks would be of daily use to me.

From the conversations I've had with maintainers of other large open source projects(like chocolatey) the piecemeal approach to implementing markdown will only lead to headaches down the line though. Either support markdown in its entirety or not at all.

If you are going to implement markdown it would be wise to offload the work to a library that is already [CommonMark](http://commonmark.org/) compliant. Most large services seem to be moving towards it commonmark, even githubs spec is based off it now.

**Comment by zcdunn** [comment]
I would like to see full markdown support. Code blocks in posts would be great! I think general user consensus and moderation will keep users from abusing it.

**Comment by msappir** [comment]
I think adding markdown or any other rich-text/formatting options, beyond perhaps italics, would have a significant negative impact on the experience of reading feeds. Having so many different things in front of you at the same time (multiple feeds, full of multiple toots, with avatars, icons, controls) is already visually taxing, making it "messier" might make it overwhelming.

**Comment by Fastidious** [comment]
I am for minimal GitHub flavoured Markdown (bold, italics, code, and links).

**Comment by krainboltgreene** [comment]
Moving to #853

**Comment by rkingett** [comment]
I can't tell, has full markdown support been added yet? I'd love to see markdown support.

**Comment by hubick** [comment]
PLEASE can we have markdown support?

**Comment by lllisteu** [comment]
Instead of making this a big thing, going all-markdown, why don't we take it one step at a time and see where it takes us? Like only _italic_, or my favourite:

```
code
```

**Comment by JetForMe** [comment]
Yes, please. Links, code blocks, and bold/italic are all useful.

**Comment by hubick** [comment]
I just learned my instance runs on the `glitch-soc` fork which [does](https://glitch-soc.github.io/docs/features/rich-text/) support Markdown. Displays great in Tusky app too. It would be nice if that were merged here upstream for everyone.

**Comment by benatkin** [comment]
I'll be that guy and create an issue for inline code blocks – for me it's the most critical thing that's missing and easy to do compared to syntax highlighted fenced code blocks (unhighlighted ones would be appreciated but probably put pressure for syntax highlighting).

Not even sure I want links.

**Comment by krainboltgreene** [comment]
I promise you all that the blocker to this is not "not enough comments from programmers telling us we need this"

**Comment by krainboltgreene** [comment]
See linked issues.
