### ISSUE TITLE
Having a high-traffic feed open causes enormous disk I/O in Firefox

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#7615]
On mastosoc (2.4.0), with Firefox 60.0, I've noticed my hard disk light is on way too frequently when I've got something like the Federated Timeline open. By flipping `sysctl vm.block_dump=1` and watching `dmesg -w`, I can see it's coming from IndexedDB doing a bunch of sqlite and fsync calls every time a new post appears.

Aside from that, there's now an enormous (varies, but I've seen over 150MB) directory in

    ~/.mozilla/firefox/$profiledir/storage/default/https+++mastodon.social^firstPartyDomain=mastodon.social/cache/morgue/

This usage also shows up in the preferences window when I check how much data each site's storing, even though IIRC the browser default is supposed to be 5MB:

![2018-05-25_01 29 54_1089x357](https://user-images.githubusercontent.com/409860/40521444-2d38cd04-5fbb-11e8-875f-bb4fd3714295.png)

If I had to take an educated guess, what's happening here is all those posts are getting saved for offline mode and then getting evicted by the browser's offline storage limit, resulting in the browser generating a huge garbage pile and never cleaning up after itself.

Obviously Mozilla needs to fix their horrid implementation here and stop trashing my shiny new SSD, but I guess what I'm asking for in this issue is if there's any way it can be mitigated on this end?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by akihikodaki** [comment]
> Aside from that, there's now an enormous (varies, but I've seen over 150MB) directory in
```
~/.mozilla/firefox/$profiledir/storage/default/https+++mastodon.social^firstPartyDomain=mastodon.social/cache/morgue/
```

It is Web Cache and deserves for another issue.
