### ISSUE TITLE
Suggestion/discussion: use the system's default font

### ISSUE THREAD

**Issue by eramdam** [tootsuite/mastodon#762]
Right now the app is using Roboto as a font.
I think it would be nice if it was using the system's font instead in the UI. San Francisco/Helvetica Neue on OSX, Segoe UI on Windows, and fallback to Roboto on Linux. I have a PR ready to do this, any thoughts?

**Comment by ticky** [comment]
I’ve proposed this before (#403) but it got reverted pretty quickly, mostly because Windows users hated seeing Segoe.

**Comment by eramdam** [comment]
Then maybe we could just use the default font on macOS and use Roboto everywhere else. I don't know how hard it would be to make that a settings in the preferences 🤔

**Comment by Gargron** [comment]
I understand that people have varying visual preferences, and even different fonts that are available to them. Some fonts look way nicer than Roboto (for example, the commercial and super expensive Whitney font that Discord uses). I can only recommend creating alternative web or native apps that work best for your OS and preferences. Roboto fits well as a cross-platform compromise.

**Comment by eramdam** [comment]
@Gargron I'm currently working on a PR that would allow this as a setting in the preferences, so this way people who prefer this would still have the option if they want.
