### ISSUE TITLE
Follower-only posts are accessible to admins whose instances should NOT even be receiving them.

### ISSUE THREAD

**Issue by TrollDecker** [tootsuite/mastodon#7625]
Okay, seriously. Someone blocked me today and despite being the sole user on that instance, follower-only toots from my instance are still federating over to their instance, and for some reason that user has been able to view those follower-only toots.

This is the second time this has happened over the past year, and dealing with the unethical behaviour of the admin in question aside, this shouldn't even be happening in the first place. As soon as all users from an instance unfollow a user from another instance, follower-only posts from that unfollowed user should stop going to that instance. Full stop.

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on several releases over half a year (https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Account.first.followers.where(domain: 'thatplace')

What is the result of that query?

**Comment by Gargron** [comment]
Should be also possible to check this info from Preferences -> Authorized Followers.

**Comment by nightpool** [comment]
any update on this? I can't reproduce this on my dev instance

**Comment by TrollDecker** [comment]
Someone explained to me that it was because I @-mentioned the person in question, which apparently overrides the toot privacy setting.

Quite why it still federated over there despite her blocking me beforehand escapes me though. 😕

**Comment by nightpool** [comment]
mentions always federate. there are technical reasons for this but the most important reason is UX—mentions are fundamental to Mastodon's privacy affordances, so they have to be consistent. they're how replies to private statuses work, direct messages, etc. @ mentions are always delivered to the recipient server. (which then applies it's own filtering, like blocks and mutes)

**Comment by Gargron** [comment]
Tbh the reason mentions always get delivered is to prevent people from brigading someone without them knowing it. But I'm glad this issue can be closed because the title sounded scary.
