### ISSUE TITLE
Push notifications do not work well

### ISSUE THREAD

**Issue by GenbuHase** [tootsuite/mastodon#7627]
From `Mastodon v2.4.0`, push notification hasn't been working as well as before one.
I found some problems.

First of all, the actionbar is visible even if an actor of the status delivered notification is myself.
Second, buttons in the actionbar do not work.

They may be caused by [web_push_notifications.js](https://github.com/tootsuite/mastodon/blob/v2.4.0/app/javascript/mastodon/service_worker/web_push_notifications.js).
I found an error with `Object.assign`.

I had captured some screenshots.
I'm afraid I don't have enough knowledge to resolve this bug...

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by GenbuHase** [comment]
They are screenshots of an error, about `Object.assign`.
Maybe it is compiled code.

![t isn't undefined or null](https://user-images.githubusercontent.com/14960841/40573830-7b11c68c-6102-11e8-813f-ddc90f76ae7e.png)
![It will empty through Object.assign({}, t)](https://user-images.githubusercontent.com/14960841/40573832-8354a2ec-6102-11e8-8248-e5133da14690.png)
![Result in TypeError](https://user-images.githubusercontent.com/14960841/40573834-87347630-6102-11e8-9f7f-ab3a88adf0bf.png)

**Comment by GenbuHase** [comment]
This is screenshot about first problem.
An actor of the status is me, and one of the notification is also me.

![Actionbar is visible](https://user-images.githubusercontent.com/14960841/40573873-1771e91c-6103-11e8-825b-78e337bfc255.png)

**Comment by Cassolotl** [comment]
I am using Android, and I have noticed that since 2.4.0 notifications have been strange. Clicking "show more" often doesn't do anything, and tapping the notification to open it in the progressive web app usually also doesn't work. It opens the PWA but it doesn't find and focus the notification.
