### ISSUE TITLE
No confirmation for email containing a plus '+'

### ISSUE THREAD

**Issue by jrconlin** [tootsuite/mastodon#763]
I have tried to register an email address that contains a '+' in the local portion (look for a record tied to 'jrconlin') Repeated requests for a confirmation email have failed to be delivered. Looking at #616, I suspect that the '+' may be getting HTML encoded as '%2B' or like.

**Comment by ProgVal** [comment]
Are you sure? It always worked for me, both on mastodon.social and on my own instance.

**Comment by jrconlin** [comment]
Sigh, nope, just an overly aggressive set of spam filters.

**Comment by nashe** [comment]
I thought I had the same issue after subscribing to mastodon.social with an email containing a "+" but I just had to wait a little bit more (~ 45 minutes). I guess their SMTP server is throttling outgoing messages  :-)

**Comment by jrconlin** [comment]
I'm not quite sure what triggered the spam filter for me. I was able to send test messages to the email to verify that the address worked, yet the mail went straight to spam. 

If possible, make sure you whitelist "@mastodon.social" BEFORE you request a second followup email.
