### ISSUE TITLE
Support dollar sign as toot tags.

### ISSUE THREAD

**Issue by sorpaas** [tootsuite/mastodon#7634]
This is used by many cryptocurrency users on Twitter, who would like to use tags like `$BTC`, `$ETH`, `$XMR`, `$ETC`, etc.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
This is just duplicating `#hashtags` with the added disadvantage of not being able to use $ signs normally.
