### ISSUE TITLE
Don't count suspended users in instance user count.

### ISSUE THREAD

**Issue by rixx** [tootsuite/mastodon#7637]
With the current influx of spam accounts, the user count of instances seems grossly inflated if you have lots of spam accounts on your instance. I'd strongly prefer it if we didn't count suspended/deleted accounts in the instance user count.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

(This is discussed a bit in the user deletion issue, #3811.)

**Comment by trwnh** [comment]
I second this (but not so much the other issue).

**Comment by Tagadda** [comment]
There is an inconsistency in the total user count : self-suspended user (when a user choose to delete their account) doesn't count in the "total user" thing.

**Comment by ChatonneLibertaire** [comment]
That could be very useful indeed

**Comment by ashleyhull-versent** [comment]
Thanks a lot.
