### ISSUE TITLE
Dropdown menu highlights are confusing

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#7641]
There's two separate things here, but they both manifest as the same symptoms:

* On the privacy dropdown, [the selected item colour is the same as the hover colour](https://mastodon.social/@sorb/100102932536046362).
* On the post options dropdown, "Expand this status" is highlighted (as `:active`) when the menu's first opened and stays that way, since clicking the mouse anywhere immediately closes the menu.

I'd suggest making the "current selection" highlight visually separate from the "mouse hover" one, maybe using a border or underline, but I'm no authority on web design so I'll defer to someone with better ideas.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ariasuni** [comment]
Right now the, on the privacy dropdown, the hover color is slightly different than the selected item color.

However, I agree that having the first item selected, on the post options dropdown and similar menus, is not a desirable behavior.
