### ISSUE TITLE
Bug: a toot removed by the moderator re-appears in the public timeline

### ISSUE THREAD

**Issue by djoerd** [tootsuite/mastodon#7653]
I removed a status in the moderation section, but it came back (no boost), and I had to remove it again. In the moderation section it is now listed twice, both times with two reports, although I reported each appearance myself once. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on Mastodon v2.4.0

**Comment by Gargron** [comment]
Fixed in #10732
