### ISSUE TITLE
Unhandled Promise Rejection. Browser freezes after upgrading to 2.4.0

### ISSUE THREAD

**Issue by ragingscholar** [tootsuite/mastodon#7668]
Many users have reported that their browsers hang after I upgrade to 2.4.0

The issue can be repeated (mostly) by clicking on a toot again after replying to it, affected browsers are:
Safari / Chrome / Firefox

Anyone has the same issue?

**Comment by ragingscholar** [comment]
Please kindly ignore the "Unhandled Promise Rejection." part in the title, I thought it was a promise issue but turns out it can simply be triggered by replying to a toot and click on it again immediately.

**Comment by jebuskrust** [comment]
@ragingscholar Yeah i've had the same issue for a while. Not real sure what commit caused it..  
I believe it was a commit introduced sometime after 2.4.0 for me i believe (7745a22ec748be8bd6410cda0a61d197e49a72a3) .... it was definately recent though.  Perhaps the above will fix.
