### ISSUE TITLE
If one (and only one) person uses a hashtag 50 times and then you block them, the hashtag remains in the trending tags list but is empty.

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#7689]
I'm not sure if it's a good or bad thing, but since there's only space for three tags maybe space should be made for tags containing people who aren't blocked?

![screen shot 2018-05-31 at 16 31 56](https://user-images.githubusercontent.com/6607512/40791761-2efa66a4-64f0-11e8-8ff8-82098e738ad8.png)

![screen shot 2018-05-31 at 16 32 06](https://user-images.githubusercontent.com/6607512/40791774-32625338-64f0-11e8-8ef7-91e750677068.png)

It might be that it's not possible to do that - perhaps the trending tags list has to look the same to every member, so if that's the case let me know so I can close this, or maybe just close it yourself!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Sorry, I can't personalize site-wide trends.
