### ISSUE TITLE
After undoing Boost, items remain in Home timeline

### ISSUE THREAD

**Issue by GyrosGeier** [tootsuite/mastodon#770]
I accidentally boosted an item because the page was still loading. I quickly undid that, and the item is not shown in my profile timeline anymore, but still shows up my Home timeline, even after reloading.

**Comment by rhaamo** [comment]
may be related to #575 for the visual aspect (un-boost doesn't get back to grey icon)

**Comment by unarist** [comment]
It's known issue, see Gargron's comment on #2817.
