### ISSUE TITLE
Not receiving notifications for new follower approvals 

### ISSUE THREAD

**Issue by vladanghene** [tootsuite/mastodon#771]
Set my profile to private.
Tried to follow myself from my newly deployed instance http://mastodonclojure.herokuapp.com , found my valid mastodon.social account, clicked follow (result is Awaiting Approval) --> on mastodon.social I get no notification.

**Comment by ashfurrow** [comment]
I'm not aware if this is a bug or if this is a missing feature. Reaching out to @Gargron for clarification. Thanks for opening!

**Comment by Gargron** [comment]
Duplicate of #455
