### ISSUE TITLE
Feature Request :  followed/follower counts hideable

### ISSUE THREAD

**Issue by AliceSutaren** [tootsuite/mastodon#7714]
[Feature Request :  followed/follower counts hideable].

As someone suggest it before, but didn't open an issue
![github](https://user-images.githubusercontent.com/39865141/40881063-a3dceebe-66bd-11e8-8ba2-f836b7513bba.png)

Exactly what it says.
Thanks for reading.

**Comment by Laurelai** [comment]
This is a good feature.

**Comment by Tagadda** [comment]
This is already a thing ?
![](https://user-images.githubusercontent.com/36127788/40881725-67475e06-66ce-11e8-8b2e-a0933d2f38d4.png)

**Comment by zaarcis** [comment]
@Tagadda Nope, that's different thing. The issue is about hiding total number of followers (or following), if I understand it right. Manually counting still okay.

**Comment by trwnh** [comment]
@Tagadda That only hides the lists. It keeps the counts (and the linked buttons to those lists).

![image](https://user-images.githubusercontent.com/10606431/40882374-a5d90120-66a5-11e8-8599-2235becc9d9a.png)

IMO there's no need to link to a page that says "Information not available" -- not only the counts, but the buttons themselves should be hidden.

Here's what that would look like by simply removing them:

![image](https://user-images.githubusercontent.com/10606431/40882397-3a35876c-66a6-11e8-9b2e-d48331bc4c38.png)

Perhaps the toot counter can integrated into the toot-section header as well?

![image](https://user-images.githubusercontent.com/10606431/40882449-e39e4dd8-66a7-11e8-87ed-3a64739072f3.png)

**Comment by AliceSutaren** [comment]
In my opinion, only the counts bother me.
It will be nice to be able to hide the counts and/or the buttons.
![unnamed](https://user-images.githubusercontent.com/39865141/40915740-7963abfa-67fd-11e8-8994-66c87e64cc62.png)


I kind of appreciate discovering new accounts via followers and followings list.
I know it can be a privacy issue, so it's nice to let people the choice of hiding it or not.

**Comment by trwnh** [comment]
Yeah, of course it would be a choice! This would be an extension of the
option to hide the lists, by hiding the numbers/buttons as well.

**Comment by Gargron** [comment]
I think there is abuse risk from this feature request: People often use the followers/following count to gauge whether the person they see is a real person or a spam bot or sockpuppet. With followers counts and lists visible, spammers and sockpuppeters have to put in the work of establishing an account network to create the impression of legitimacy. Now, if the admin that hosts them is complicit, what I am about to say is meaningless, but if not, then showing the numbers even while letting people hide *who* the followers are still requires such people to put in some extra work. Hiding the numbers altogether would remove that barrier.

I think that the privacy benefits of hiding who you follow and who follows you are real and large, but the benefits of hiding the numbers are very marginal.

I am not going to implement this.
