### ISSUE TITLE
Inconsistent `back` URL in Web column UI 

### ISSUE THREAD

**Issue by bunnybooboo** [tootsuite/mastodon#7731]
To reproduce: 
[hotkeys GT] federated timeline (`back` is on right-hand side)
click on a toot (`back` is now on left-hand side)
click on hashtag (`back` is now on right-hand side)
click on user id (`back` is now on left-hand side)
To go "back" user is required to click `back` left-right-left-right in order 'chase' the link and return to previous location
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by bunnybooboo** [comment]
![screenshot from 2018-06-04 13-01-23](https://user-images.githubusercontent.com/5793295/40916391-126639da-67ef-11e8-833b-45c883cc85a6.png)
![screenshot from 2018-06-04 13-01-08](https://user-images.githubusercontent.com/5793295/40916392-129fa594-67ef-11e8-9990-6a513d3b5a34.png)
![screenshot from 2018-06-04 13-00-54](https://user-images.githubusercontent.com/5793295/40916393-12be7794-67ef-11e8-95e3-da721e723894.png)

**Comment by Gargron** [comment]
Ah, this is not a bug. The back button in the middle is clickable in exactly the same place as the others, there is just no title text to show so it takes the entire width. It's a design choice.
