### ISSUE TITLE
Credit forwarded reports to a "system" user instead of first registrant

### ISSUE THREAD

**Issue by riking** [tootsuite/mastodon#7737]
Using `Account.local.where(suspended: false).first` as the originator of remote reports is a little bit weird. (More than a little bit.)

In semi-rare cases, the first registrant will not be (or is no longer) the admin of the instance you are sending a report from; and/or be blocked/suspended at the target server, causing superflous rejection of otherwise valid reports.

Utilizing a "system" account would both remove that confusion and allow for people to selectively de-anonymize reports they send. `[ ] Show my username to the remote server`

Backfill creation & source-level usage of the system account should be fairly simple if a well-known account ID is used, such as `-1` (negative one). `def Account.system; find(-1); end`

This may also be useful in other situations I have yet to identify.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by rinpatch** [comment]
Bump. Pleroma has support for reports  for quite some time now, and we actually send reports with actors being actual users who reported stuff. We also display the reporter in the frontend so there is an ability to contact them for further info, but it becomes confusing with reports that come from Mastodon because it will always show the first registrant. Please consider sending reports as an unambiguous actor

**Comment by Gargron** [comment]
> we send reports with actors being actual users who reported the post/user

Bad idea. They could be targeted by hostile admins and harassed for sending reports.

> it will always show the first registrant

No, it uses admin accounts, not just any first registrant.

> Please consider sending reports as an unambiguous actor

If you are asking for a "system" account, this is being considered. If you are asking to expose the identities of those who send reports, no.

**Comment by rinpatch** [comment]
> Bad idea. They could be targeted by hostile admins and harassed for sending reports.

True, this will be configurable in the future
> No, it uses admin accounts, not just any first registrant.

Sorry, assumed this from the issue
> If you are asking for a "system" account, this is being considered. If you are asking to expose the identities of those who send reports, no.

Yes, I was asking for a "system" account, thank you

**Comment by Gargron** [comment]
Done
