### ISSUE TITLE
Filter out blocked/muted people from timelines / profile boosts in Web UI

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#7741]
Extension of #251 and the other 5 issues related to how blocking and muting should work.

>when I block/mute someone i should be able to pretend they don't exist but as it stands I'm unable to do that right now

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
If I block Bad Person, then go to Friend's profile and see that Friend has boosted Bad Person, that's an important signal, in my opinion, and something I would want to know about that Friend. No?

**Comment by trwnh** [comment]
Possibly, but if I wanted to get an unfiltered view of Friend's profile, then I'd load their profile page, not their profile column. Mostly I'd like to completely ignore Bad Person, and in many cases the reason for blocking or muting Bad Person has nothing to do with Friend. The primary motivator would be that I just don't want to see Bad Person's bad posts while browsing in-app.

Also, Bad Person might not be a malicious actor -- they might just post bad things that I don't want to see.

**Comment by ThisIsMissEm** [comment]
Perhaps we could just show the avatar & username & like CW do a “blocked toot” message that you can expand?

**Comment by trwnh** [comment]
@ThisIsMissEm That would probably have to be an opt-in setting -- presumably most people would expect the default behavior to be a complete hide a la other platforms' filtering.

**Comment by ThisIsMissEm** [comment]
This would be more like what happens on twitter when you see a quote-tweet from a blocked user on twitter 

Emelia

**Comment by maxine-red** [comment]
The behavior is still wrong, in parts.

I have experienced it myself and at least one other person too, that blocks/mutes/word filters don't apply to boosted statuses.

The workaround is/w/as to deactivate boosts from people who boost bad person, but I don't see that as a solution.
