### ISSUE TITLE
Delete & redraft doesn't preserve newlines

### ISSUE THREAD

**Issue by devinacker** [tootsuite/mastodon#7748]
Nothing major, but using the new "delete & redraft" function to rewrite a toot causes line breaks to be stripped from the original message. In my case I didn't notice this had happened until I had already posted the modified toot.

i.e. original message:
> this is a test
>
> this is a test

message after redrafting:
> this is a testthis is a test

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
Similar issue in browser desktop notifications, for what it's worth. May be related.
