### ISSUE TITLE
Restore normal functionality of CWs in admin interface

### ISSUE THREAD

**Issue by bugQ** [tootsuite/mastodon#7752]
A fellow admin complained that the flashy changes made in [this PR](https://github.com/tootsuite/mastodon/pull/7452) made reading a report very difficult due to their sensory processing issues.  In addition, I noticed that this change removed the "show more" button because nobody was able to convince Gargron of the purpose of the button, which he viewed as annoying.  So, here I am to do some convincing.

The purpose of any content warning is threefold:
1. to warn content consumers that the content therein can be distressing to some people (often to the point of triggering anxiety attacks, especially in people with PTSD or other conditions),
2. to let the content consumer decide whether to engage with it (**if such a choice is possible**),
3. having decided to engage with it, to give the content consumer a chance to prepare.

If I had to guess, people who have not had experience with the need for these warnings generally assume only the second point.  Since it's the job of server admins to engage with _all_ user reports, to the uninitiated, it might seem that CWs are "useless".  However, the first and third points are still applicable regardless of the context, and the second can still be relevant in the case of servers with multiple admins, who may delegate work between each other for personal reasons.

I hope this makes it evident why the aforementioned PR was a disaster for many admins of varying psychologies and backgrounds, and I request that CWs once again function identically in all views.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
I just want to make clear that #7452 did not remove the “show more” button, it was removed earlier and my initial plan with this PR was to restore that very button. This PR only fixed boosts being misrepresented as original toots and content warnings not standing out at all (although what stuck for that last part was a joke commit eh).

So I agree with this issue since that's what the PR was originally meant to be.

**Comment by dn3s** [comment]
come on though, animated rainbow text? did you just learn a new css trick or something? i know it's kinda dishonest to pretend this project cares about accessibility but still.

**Comment by dn3s** [comment]
@ThibG i was not aware that you weren't expecting that PR to be merged as-is. i wish you would have explained that more clearly as i wouldn't have responded so aggressively, but regardless i apologize.
