### ISSUE TITLE
Emoji shown and counted as their description 🤔

### ISSUE THREAD

**Issue by WebReflection** [tootsuite/mastodon#776]
I don't think it makes sense to count emoji chars based on their description.

It also doesn't help anyone writing down text to visualise what's their "toot" intention.

As example, in this picture you can see me choosing an emoji from the widget:
<img width="292" alt="mastodon" src="https://cloud.githubusercontent.com/assets/85749/24610789/d41e06e8-1877-11e7-90ab-d3156bb38a4d.png">

VS me pressing Ctrl+Cmd+Space on Mac to insert a native one:
<img width="297" alt="mastodon-2" src="https://cloud.githubusercontent.com/assets/85749/24610804/e4685dfa-1877-11e7-9d28-6f5fa8d312cb.png">

The description surely helps picking the right emoji through the widget (or searching one) but are you sure putting in the textarea its descriptions and counting it as N chars is a good idea?

**Comment by qsypoq** [comment]
It also happens on user descriptions, C/C emoji count as one while the shortcut count the chars

**Comment by Gargron** [comment]
Resolved by  #4189
