### ISSUE TITLE
Mute/Block management interface is hard to find

### ISSUE THREAD

**Issue by elomatreb** [tootsuite/mastodon#7762]
The links to the "Blocked users" and "Muted users" were moved to the dropdown in profiles, which made them very hard to find IMO (I have also seen multiple other people ask where they went).

Since the space is now not immediately needed by other UI elements, could either the old links in the Getting Started column be restored or something new in a similar place be created?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wohali** [comment]
Perhaps solved by #7789 ?
