### ISSUE TITLE
Add Option: Always unfold toots marked with a (CW) Content warning.

### ISSUE THREAD

**Issue by MyNameIsTroll** [tootsuite/mastodon#7774]
Add an option like the one for sensitive messages so that the user can choose if he wants to automatically unfold toots marked with a (CW)

![feature](https://user-images.githubusercontent.com/31790025/41195839-46691b36-6c35-11e8-90fe-f560448c4b66.jpg)

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by op3nus3r** [comment]
Good idea, it can also encourage people to use more the content warning function if they know that people can choose to see its content opened by default.

**Comment by KonomiKitten** [comment]
I would like to see this implemented as I myself don't really care too much about Content Warnings and would like to avoid the extra clicks they entail.

**Comment by andrel** [comment]
I also find that expanding every content warnings (CW) requires an annoying amount of extra clicking. Also, I suspect that the majority of Mastodon users benefit little from CW and that the default behavior should be rendering the full message and let individual users activate hiding if they have this need.

**Comment by imathew** [comment]
Content warnings are an important and useful tool and I mark toots with a CW whenever necessary. However, I would like to have them expand automatically for me, because I don't need them and the extra clicking is annoying.

**Comment by semente** [comment]
Besides the option to always unfold CW posts I also think that replies to CW posts must be always unfolded by default in a thread view - but only if the person clicked on the Show More button on the thread head post otherwise people accessing a post through a direct link will see it folded and the replies unfolded.

If a thread has lots of replies should I click on Show More on every reply to read the whole thread that I was already aware about the content warning?

**Comment by quat1024** [comment]
throwing my hat into the ring too - an option to expand all CW-labeled posts (or possibly "auto-expand CWs not including ______") would be very helpful.

Would also be nice in threads, where each reply automatically gets the same CW as the parent post. (maybe "auto-expand identical content warnings in threads" should be a separate issue :octocat:)

Should probably be disabled by default, so people who do want to have them collapsed don't have to jump through an extra hoop/have to somehow already know that they can be set to collapsed by default at all.

**Comment by rugk** [comment]
> Would also be nice in threads, where each reply automatically gets the same CW as the parent post. (maybe "auto-expand identical content warnings in threads" should be a separate issue :octocat:)

Guess https://github.com/tootsuite/mastodon/issues/7255 is what you want.

Generally, someone needs to close this issue as a dupe, as it already has been mentioned.
