### ISSUE TITLE
Direct mentions aren't showing up in notifications column

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#7775]
I just received a direct reply but it didn't show up in my notifications column and I had zero indication of its arrival. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on [2.4.1rc3](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
is the user silenced or muted?

**Comment by Gargron** [comment]
More importantly I wonder if it's a missing filter on as_direct_timeline because there should be no discrepancies there...

**Comment by trwnh** [comment]
No, pretty sure they're not silenced or muted, since they were showing up in the local timeline.

**Comment by ojbr** [comment]
I've been getting this problem on v2.4.0 release as well. Only run a small instance, so have actually just noticed this with two other users. It only appears to happen if the user is on the same instance; I'm able to get cross-instance notifications perfectly fine. Favorites from the same instance also work fine for me.
Sidekiq does not appear to show anythingenqueued, which indicates it might actually be the filter mentioned above

**Comment by trwnh** [comment]
On later consideration, perhaps the user was silenced *after* I sent a reply to them? They were having a conversation with another user without mentioning each other, so it's possible a mod could have silenced them for spamming the public timeline. But then that means there's a discrepancy between the notification and DM filters for silenced users' direct posts.

**Comment by Gargron** [comment]
The old DM API is not very clean and I have noticed it missing a lot of filters that e.g. notifications would have. That's why I added a Conversations API instead.

I would like to remove the old API at some near point in the future.

**Comment by trwnh** [comment]
I'm not sure this had anything to do with the DM API, since the problem was that it wasn't showing in notifications. This issue can probably remain closed, though.
