### ISSUE TITLE
Statuses with CW (Content Warning) from Pleroma are sometimes shown expanded by default.

### ISSUE THREAD

**Issue by kepstin** [tootsuite/mastodon#7788]
From a Mastodon instance, if you see a status from (some?) Pleroma instances, with a CW, it is sometimes shown expanded by default even if you've had no previous interactions with the user, thread or message.

Probably easiest to reproduce by pasting a link to a specific status into the search box. I tried this on a newly created account on mastodon.social, loading e.g. this status by @kaniini about possibly prerendered footage in E3 https://pleroma.site/objects/dbccd46c-fa80-4cdc-92c2-5d4eff8a8590 (which showed as open by default), and one of my toots about rds databases on amazon: https://glitch.social/@kepstin/100188061069476651 (which showed as closed by default).

I have no idea why this is happening, but it seems to be an interop problem between the different implementations.

**Comment by kaniini** [comment]
it is weird, but we send the same signals exactly that Mastodon does, so i dont know what could be seen as different.  also those same statuses work fine for me on my Mastodon instance and are properly CWed.

**Comment by renatolond** [comment]
Can it be something about the mentions? In Mastodon when a CW'd post has a mention it looks like this:
![image](https://user-images.githubusercontent.com/173791/41278105-4d5f8e7a-6e29-11e8-98c4-468d74577fca.png)
![image](https://user-images.githubusercontent.com/173791/41278132-5cebc494-6e29-11e8-9449-f59720db9219.png)

While yours only shows the mention when closed, but not when opened:
![image](https://user-images.githubusercontent.com/173791/41277979-fb320844-6e28-11e8-8cb3-27eab5009a75.png)

![image](https://user-images.githubusercontent.com/173791/41278007-11c6dcba-6e29-11e8-837e-1cf497a0d7bd.png)

(though if I expand the thread, the original status without any mentions was also open)

**Comment by kaniini** [comment]
no, that was because i was replying to myself.

**Comment by beta-phenylethylamine** [comment]
Apparently this is also happening from anticapitalist.party, was brought up with a user on my instance
