### ISSUE TITLE
Requesting explanation for the muting mechanism

### ISSUE THREAD

**Issue by phoe** [tootsuite/mastodon#7790]
Issue originally raised at https://mastodon.social/@catonano/100191338376162829

The original issue on the topic #725 that I found via searching links to a link that is now dead. Its archived content is available at https://web.archive.org/web/20170609145012/http://www.mastoguide.info/Pages/muteFAQ.html but this FAQ is a year old.

I have not seen any better explanation for the muting mechanism than this one year old link. Has anything changed since then? Are the muting mechanisms described anywhere in detail, so this can be linked as an explanation to people who have questions?

**Comment by Gargron** [comment]
Muting is (now) the same as blocking, with the difference that:

- You can choose *not* to hide notifications from the muted user
- The user cannot know that they've been muted because they can still see your posts

**Comment by nightpool** [comment]
Here's the documentation on the issue: https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/User-guide.md#muting
