### ISSUE TITLE
CW box opening is animating when "reduce motion" is enabled

### ISSUE THREAD

**Issue by ilianaw** [tootsuite/mastodon#7802]
This is a regression in 2.4.1. Prior to 2.4.1 clicking the CW box results in a CW box appearing with no animation when "reduce motion" setting is enabled.

Was occurring on one of the glitch.social instances a couple of weeks ago, but is now occurring on cybre.space after its upgrade today.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Maybe caused by #7508 ?

**Comment by ariasuni** [comment]
I can fix that.
