### ISSUE TITLE
Locked Accounts: Be able to see who followed you after accepting them

### ISSUE THREAD

**Issue by delightfulagony** [tootsuite/mastodon#7808]
I was just wandering if it wouldn't be a good idea to be able to see the people who have followed you after you've accepted them.

Sometimes I accept someone's follow and after that I want to go back to their profile for whatever reason, if I didn't have my account locked I could do that easily from my notifications, but since it's locked I can't.

I don't know how hard it would be to implement it, but I was just thinking about sending the same notificacion of `"@someone@some.domain followed you"` but only when you accept them, so you get the info that someone followed you permanently somewhere you can access.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
click on your "Followers" count

**Comment by delightfulagony** [comment]
Yes, you can do that, but I was thinking more like a "chronological" thing, of course you can see your followers but it is not viable if you've got thousands of followers since (as far as I know) you don't see them in the order they followed you.

Please correct me if I'm wrong.

**Comment by Gargron** [comment]
You do see them in the order they followed you, most recent at the top.
