### ISSUE TITLE
IDN domains don't render correctly in usernames

### ISSUE THREAD

**Issue by wxcafe** [tootsuite/mastodon#7812]
IDN domains in usernames are displayed as punycode in usernames in the web interface, which isn't the intended result.

![screenshot from 2018-06-15 22-49-35](https://user-images.githubusercontent.com/3009327/41489041-ba1d9166-70ee-11e8-8ac4-e2c46648a393.png)

here, for example, "@TransPosees@xn--pnibles-bya.xn--transposes-i7a.eu" should be displayed as "@TransPosees@pénibles.transposées.eu"

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by barzamin** [comment]
If there are objections about confusables, it is possible to fall back to punycode for domains that include them, but, otherwise, render the URL as full unicode.

**Comment by wxcafe** [comment]
it would also be possible to follow the rules that are basically only accept utf8 chars that are used in the writing systems accepted by the TLD, which remove basically all possibility of confusion without alienating everyone who doesn't want to use english domain names.

**Comment by sneak** [comment]
I think it needs to be more permissive than that.  I use the domain hæresiar.ch (a domain hack), and the æ ligature is not endemic in Swiss orthography.
