### ISSUE TITLE
API returns already rendered custom emojis for account notes

### ISSUE THREAD

**Issue by connyduck** [tootsuite/mastodon#7820]
Behavior in Mastodon 2.4: 
`"note": "<p>This is a test account <img draggable=\"false\" class=\"emojione\" alt=\":blobaww:\" title=\":blobaww:\" src=\"https://media.mastodon.at/system/custom_emojis/images/000/003/261/static/21bbc684f7adce24.png\" /></p>"`

This is really annoying to parse in a client that is no web client. Why can't custom emojis in notes work like everywhere else (account fields, display names, statuses)?

Expected behavior: `"note": "This is a test account :blobaww:"`

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Yes, this is a bug, introduced in 123a343d116d3e83cbd04460cc7bd0b6f3d208c4
