### ISSUE TITLE
Some posts with a CW are opened by default

### ISSUE THREAD

**Issue by Sylvhem** [tootsuite/mastodon#7824]
Since the update to [Mastodon 2.4.1](https://github.com/tootsuite/mastodon/releases/tag/v2.4.1), some posts that have a CW are displayed as already opened when they appear on the web interface.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by renatolond** [comment]
Double of #7788 ?

**Comment by Gargron** [comment]
Yes, i think so. Already fixed

**Comment by Sylvhem** [comment]
> Double of #7788 ?

I'm not sure. Those posts where from other Mastodon instances.
