### ISSUE TITLE
registration fails with "e-mail address is invalid"

### ISSUE THREAD

**Issue by steckerhalter** [tootsuite/mastodon#7831]
this happens with two perfectly valid email addresses. what is it checking there?

masto version is 2.4.1

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
What instance? They may have a blacklist on the provider you're using, for spam reasons.

**Comment by steckerhalter** [comment]
@nightpool on my own instance. I don't have a blacklist :smile:

**Comment by steckerhalter** [comment]
no it doesn't have an MX record because the server itself is the mailer. SMTP should fallback on the A record if it doesn't find an MX record and deliver it there.

**Comment by steckerhalter** [comment]
and yes it works. it's my main address even.

**Comment by steckerhalter** [comment]
so what I'm trying to say is that a the absence of MX records does not indicate an invalid email address

**Comment by MaciekBaron** [comment]
The MX check has been possibly implemented as a soft anti-spam measure.

**Comment by steckerhalter** [comment]
@MaciekBaron I know, but the check is not honoring the SMTP standard and considers valid email addresses to be invalid. the presence of an MX record is not a requirement for an email server.

**Comment by Gargron** [comment]
Will fix
