### ISSUE TITLE
"Delete & re-draft" can't be translate

### ISSUE THREAD

**Issue by GuyM-31** [tootsuite/mastodon#7834]
I read in a menu of the French instances I had sign-up "Delete & re-draft" (in French "Éditer et réécrire")

I go to https://weblate.joinmastodon.org/ to translate it but I didn't find this string.

Is there an error, or did I not do right the search of this string.

I hope this will help

**Comment by ykzts** [comment]
https://github.com/tootsuite/mastodon/blob/63b05096c78521560516b0f5c7e900f33957fb8f/app/javascript/mastodon/locales/fr.json#L274

It has already been translated.
