### ISSUE TITLE
ActiveRecord::DuplicateMigrationNameError

### ISSUE THREAD

**Issue by salvadorpla** [tootsuite/mastodon#7852]
Hello,
when running 'RAILS_ENV=production bundle exec rails db:migrate' to upgrade from v2.4.1 to v2.4.2 it throws:
rails aborted!
ActiveRecord::DuplicateMigrationNameError: 
Multiple migrations have the name RemoveUnusedIndexes.

Thanks!

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by salvadorpla** [comment]
If I go for a short forward step and update it to v2.4.2rc1 I get same error.

**Comment by Gargron** [comment]
Strange. I've upgraded 3 different instances and none encountered this error. Anyone else?

**Comment by salvadorpla** [comment]
Before this instance I had uptaded another one hosted in the very same server with no problems at all.  Really strange to me.

**Comment by salvadorpla** [comment]
Finally I solved it by removing db/migrate dir and ‘git checkout 2.4.2’ to fetch needed migration rb files
Closing this issue.

**Comment by ThatOneCalculator** [comment]
@Gargron I actually have this issue right now. What do you reccomend I do?
