### ISSUE TITLE
Broken frontend because of apparently missing dependencies while upgrading to 2.4.2

### ISSUE THREAD

**Issue by lapin-b** [tootsuite/mastodon#7853]
Hello,

I'm upgrading an instance to 2.4.2 and, well, there's a small problem on assets precompilation which breaks the web frontend.

The breakage could be reproduced on another machine while carefully following upgrading steps. The last lines outputed by `bundle exec rails assets:precompile` are on [this gist](https://gist.github.com/lapin-b/5cc8fa81015928b093c79cd8ad1cdfbb) because it is a bit long to be included here.

I've also tried reinstalling npm dependencies with no luck. I'm also including a screenshot of HTTP requests sent by my browser in case it would be useful:

![image](https://user-images.githubusercontent.com/3647174/41600105-482b7b42-73d5-11e8-8c07-f7c837215200.png)

The server is an Ubuntu 16.04 with 8 GB of RAM and 2 GB of swap.

Thanks in advance ^^

PS: English isn't my native language and my wording can be terrible.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Have you run `yarn install`?

**Comment by lapin-b** [comment]
I just ran it, things look up to date
```
mastodon@mael:~/live$ yarn install
yarn install v1.7.0
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 1.20s.
mastodon@mael:~/live$ 
```
`bundle install` gives [this output](https://gist.github.com/lapin-b/5cc8fa81015928b093c79cd8ad1cdfbb#file-output-of-bundle-install-txt) which seems completly fine.

**Comment by ykzts** [comment]
```console
$ rm -rf ./node_modules
$ yarn install
```

How about deleting and reinstalling it?

**Comment by lapin-b** [comment]
I also tried removing the `node_modules` directory before opening an issue. Nothing.

Meanwhile, I resorted to reinstalling from git (cloning to another directory, but keeping the database) and it works fine so far.

Thanks for your help ^^"
