### ISSUE TITLE
German translation 

### ISSUE THREAD

**Issue by chapeaumeinfreund** [tootsuite/mastodon#786]
Is there any way, I can help with the translation to german?

**Comment by nashe** [comment]
Hallo @chapeaumeinfreund! You can directly send your suggestions / improvements by editing the files in https://github.com/tootsuite/mastodon/tree/master/config/locales and then by sending a _[Pull Request](https://github.com/tootsuite/mastodon/pulls)_ to get them approved and merged to this project.

**Comment by chapeaumeinfreund** [comment]
Thank you!
