### ISSUE TITLE
using github is indirectly supporting fascism

### ISSUE THREAD

**Issue by PaulFree14** [tootsuite/mastodon#7865]
I know I know, Eugen is already on the way of moving away from github. 
Yet I've only seen kind of technical or software centerd reasoning for this decision. 

As many of you propably know, github got bought by microsoft. 
Yet there is many to say about microsoft, but I believe it's important to have current events in mind, and how the struggle for free software can be linked with those of others.

That's how resisting becomes more powerfull, when the opressed give visability to each others struggle and take action of solidary. 

Microsoft is currently supporting ICE. 
Take on that matter also a look at this:
https://boingboing.net/2018/06/20/godwins-law-suspended.html
(myself haven't really made any research on that sybject)

This is a call for directAction in solidarity with anyone being effected by the fascist activities conducted by the US agency ICE. 

Since being here on github, we can start to use this proprietary plattform instead of sharing code, colaborating on code and being constructive about coding to use it to exclusivly share informations about microsoft supporting fascism, what it has to do with ones own use of this plattform and deconstructing fascist ideology. 

Also start writing issues about this into any other software projects you empathise with
and encourage people to do the same. 

Thought their is potential of making a trend out of this, that could damage the trademark github and microsoft and raises more awareness about ICE within the coder scene. 

Maybe someone could come up with a much better writing then this one, incl. some more research and possibilities that can be taken to resist ICE in specific or racism in general.

**Comment by wxcafe** [comment]
k
