### ISSUE TITLE
Weird shadow under avatars on outward facing profiles

### ISSUE THREAD

**Issue by wakest** [tootsuite/mastodon#7873]
shows up weird on external profiles
<img width="744" alt="screen shot 2018-06-22 at 3 16 28 pm" src="https://user-images.githubusercontent.com/7890201/41778537-5514dae0-762f-11e8-9878-d954287e8284.png">

but looks right when logged in
<img width="319" alt="screen shot 2018-06-22 at 3 16 37 pm" src="https://user-images.githubusercontent.com/7890201/41778539-553597e4-762f-11e8-8cf9-b11ba97aa9d4.png">

also shows the weird shadow in https://mastodon.social/settings/profile

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on version 2.4.2

**Comment by Gargron** [comment]
Design changed
