### ISSUE TITLE
Conformation Email Not Sending

### ISSUE THREAD

**Issue by StarCaptainQuinn** [tootsuite/mastodon#7878]
I made an account on Mastadon and I haven't received a confirmation email and it's been a few days. I checked my spam, I've tried to resend it a few times, even tried to "sign up" again in case it didn't go through but it says it's been taken. Is there anything else I can try to get the confirmation email?

Thanks

**Comment by nightpool** [comment]
what instance did you sign up on? you need to contact your admin and ask
them, there's nothing we can do about it.

**Comment by StarCaptainQuinn** [comment]
Thanks for the reply! I'll try and figure out how to contact the admin.
