### ISSUE TITLE
Infinite redirects on server

### ISSUE THREAD

**Issue by foggy1** [tootsuite/mastodon#7880]
I followed [this non-docker Mastodon production guide](https://github.com/tootsuite/documentation/blob/7c7e457ca2f15478557911c6918b385603867819/Running-Mastodon/Production-guide.md). I set up an ssl cert with letsencrypt and the whole nine, and while the site loads with https, it redirects back to itself, permanently 301'ing to `/` over and over until the browser gives up.

I'm assuming it has something to do with this snippet in the relevant `.conf` file

```
server {
  listen 80;
  listen [::]:80;
  server_name example.com;
  root /home/mastodon/live/public;
  # Useful for Let's Encrypt
  location /.well-known/acme-challenge/ { allow all; }
  location / { return 301 https://$host$request_uri; }
}
```

I saw earlier issues about this, but they all had to do with some `LOCAL_HTTPS` setting that looks like it was sunset. I'm guessing it hits this 301 but I've never run a setup this elaborate before so I don't understand why it's registering the https in the browser but not jumping over to the proper route handler

```
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name example.com;
```

Important note: I AM using Cloudflare.  I see there is some discussion about this [here](https://github.com/ummjackson/mastodon-guide/issues/6). Should I just bite the bullet and use cloudflare SSL? I'm assuming Mastodon would be cool with that as long as it was behind _some_ kind of https, yeah?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Cloudflare causes infinite redirects if you are using "Flexible SSL", because then Cloudflare accesses your site using HTTP (80), which on your end redirects to HTTPS. Either use "Full SSL" on Cloudflare, or remove the 80 server block and turn the 443 server block into the 80 server block instead.

**Comment by foggy1** [comment]
Ha, that was the first thing I was going to try today, that worked!

**Comment by Saiv46** [comment]
Hi from 2023!

Cloudflare Workers for some reason uses site-wide SSL settings, even when main domain is DNS-only. Which creates this problem, but can be observed only after deploying. Setting SSL mode to `Full (Strict)` fixes that
