### ISSUE TITLE
mastodon:media:remove_remote does not work

### ISSUE THREAD

**Issue by imbsky** [tootsuite/mastodon#7882]
<img width="512" alt="2018-06-24 20 51 37" src="https://user-images.githubusercontent.com/38746192/41818828-2a39b2c8-77f1-11e8-8740-96db58785a6d.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Turbito** [comment]
how do you solved it? I'm having the ame issue

**Comment by imbsky** [comment]
It gets queued into sidekiq now.
See recurring jobs page on sidekiq dashboard.
