### ISSUE TITLE
Reblog status previously unknown to instance via API

### ISSUE THREAD

**Issue by stephenburgess8** [tootsuite/mastodon#7888]
I want to be able to reblog a status from another instance that my instance does not yet know about via the API.

https://mastodon.observer/api/v1/search?q=https://mstdn.io/users/xahlee/statuses/100258319604590920

Returns the status as expected. My instance is not subscribed to this user or status.

However there is no way to then reblog with that status. Even after searching for it by the full federation URI, I can't reblog it by the ID alone because it is still not aware of it by ID.

https://mastodon.observer/api/v1/statuses/100258319604590920/reblog - this does not work after successfully searching for the full federation uri.

`https://mastodon.observer/api/v1/search?q=100258319604590920` returns nothing even immediately after calling `https://mastodon.observer/api/v1/search?q=https://mstdn.io/users/xahlee/statuses/100258319604590920`

What I was hoping/expecting was that after searching for it by the full URI, I'd be able to then reblog it by using the status ID alone. However my instance can't find it by status id alone even immediately after searching for it by full federation uri. I was expecting that searching via the full federation uri would subscribe my instance to that status, but this does not seem to be the case.

I think it might be possible to follow the user, which then would eventually make the status visible on the instance. But I think it would take time for the status to show up so that I could reblog it via using the id. I want to be able to reblog posts with specific hashtags with my bot so that they show up in my small instance. Ideally, I don't want to have to follow them to do that, especially because I think that would only work eventually and not immediately after a successful follow. I don't know enough about ActivityPub yet to understand if this is possible in some way I haven't figured out. This is for an attempt to be able to improve federation discovery for small instances in an automated way. Thanks.
 

* * * *

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
ID numbers aren't shared between servers. you need to use the LOCAL status IDs returned by the search API.

can you post the json you receive from mastodon.observer?
