### ISSUE TITLE
Following Friendica user fails

### ISSUE THREAD

**Issue by rhaamo** [tootsuite/mastodon#789]
I'm trying to follow someone using Friendica (snarl.de) and it fails, is this supported ?
The search of the user works, not following.

Summary:
```
[httplog] GET https://snarl.de/xrd/?uri=xxx@snarl.de completed with status code 200 in 0.08142168261110783 seconds
...
2017-04-03T16:40:56.264Z 4847 TID-xxx WARN: Goldfinger::Error: Invalid response mime type: text/html
```

Full traceback:
```
Looking up webfinger for xxx@snarl.de
[httplog] GET https://snarl.de/.well-known/host-meta completed with status code 200 in 0.08853638544678688 seconds
[httplog] GET https://snarl.de/xrd/?uri=xxx@snarl.de completed with status code 200 in 0.08142168261110783 seconds
2017-04-03T16:40:56.264Z 4847 TID-xxx AfterRemoteFollowWorker JID-xxx INFO: fail: 1.778 sec
2017-04-03T16:40:56.264Z 4847 TID-xxx WARN: {"context":"Job raised exception","job":{"class":"AfterRemoteFollowWorker","args":[73],"retry":5,"queue":"default","jid":"xxx","created_at":1491237654.483586,"enqueued_at":1491237654.483678,"error_message":"Invalid response mime type: text/html","error_class":"Goldfinger::Error","failed_at":1491237656.263545,"retry_count":0},"jobstr":"{\"class\":\"AfterRemoteFollowWorker\",\"args\":[73],\"retry\":5,\"queue\":\"default\",\"jid\":\"xxx\",\"created_at\":1491237654.483586,\"enqueued_at\":1491237654.483678}"}
2017-04-03T16:40:56.264Z 4847 TID-xxx WARN: Goldfinger::Error: Invalid response mime type: text/html
2017-04-03T16:40:56.264Z 4847 TID-xxx WARN: /home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/goldfinger-1.1.2/lib/goldfinger/result.rb:76:in `parse'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/goldfinger-1.1.2/lib/goldfinger/result.rb:19:in `initialize'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/goldfinger-1.1.2/lib/goldfinger/client.rb:32:in `new'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/goldfinger-1.1.2/lib/goldfinger/client.rb:32:in `finger'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/goldfinger-1.1.2/lib/goldfinger.rb:24:in `finger'
/home/mastodon/live/app/services/follow_remote_account_service.rb:25:in `call'
/home/mastodon/live/app/services/fetch_remote_account_service.rb:30:in `process_atom'
/home/mastodon/live/app/services/fetch_remote_account_service.rb:13:in `call'
/home/mastodon/live/app/workers/after_remote_follow_worker.rb:10:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:158:in `execute_job'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/rails.rb:86:in `block in call'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/rails.rb:85:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/logging.rb:32:in `with_context'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:174:in `stats'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:131:in `block in process'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:126:in `process'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:82:in `process_one'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:70:in `run'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:17:in `watchdog'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by celesteh** [comment]
I may be having a similar issue, where mastodon users are unable to follow my GNU social account: @celesteh@algonoise.social .  That site is a new install of GNU Social, straight out of the box. Other GNU Social instances have no problem with it, but Mastodon doesn't recognise users on it to tag or follow and does not receive notifications when a mastodon user is tagged in a post. By contrast, it can follow Mastodon users with no problem.
As there have been no modifications, it does suggest that Mastodon is missing some piece of GNU social federation....

**Comment by warpsync** [comment]
It is possible to follow a Friendica account through link https://yourmastodon.instance/authorize_follow?acct=acct:remoteuser@friendica.instance. Maybe a simple link conversion from the Friendica format to the mastodon format is a solution.

**Comment by schiessle** [comment]
I have a similar problem. People can follow me on Friendica from GNU Social, Pleroma, Friendica and Diaspora but not from Mastodon. You can find more information here, including the log files from my Friendica server.

**Comment by annando** [comment]
When trying to follow the Friendica account from @schiessle from mastodon.social I'm getting "500 Internal Server Error" as an answer.

Calling https://mastodon.social/authorize_follow?acct=user@friendica.server is returned with a "We're sorry, but something went wrong on our end."

It would be great if a mastodon admin could have a look at the logfiles.

**Comment by schiessle** [comment]
In order to try it and check the mastodon logs, the Friendica account in question is here: https://soc.schiessle.org/~bjoern

**Comment by Alkarex** [comment]
For the record, my Friendica account is also generating an error 500 in Mastodon: https://f.a80.fr/profile/alkarex

**Comment by nightpool** [comment]
Did some digging—it appears that this is a duplicate of https://github.com/tootsuite/mastodon/issues/4254 and has to do with an interaction between the HTTP library we use and the way Apache processes HTTP2 upgrades. There's more details at the linked issue, and see also https://github.com/httprb/http/pull/422 and https://github.com/httprb/http/pull/433 for the discussion of this upstream.

**Comment by nightpool** [comment]
@schiessle @annando @Alkarex it appears that the issue you reported (which I reproduced and spent some time debugging today) is structurally different from the original issue this ticket was created to track, which seems to have gotten fixed. In that case I think I'm going to close out this issue in favor of #4254—does anyone have a problem with that?

**Comment by annando** [comment]
@nightpool From my point of view the original issue was fixed with the latest version of Friendica. The behaviour with Friendica seems to be identical to the one that was described with GNU Social in issue https://github.com/tootsuite/mastodon/issues/4254 - so I guess you can close this here.

**Comment by Alkarex** [comment]
Ok. And indeed, disabling HTTP/2 on my Friendica server seems to help.

**Comment by rhaamo** [comment]
Looks fixed for me, closing.
