### ISSUE TITLE
Unable to initialize 2FA

### ISSUE THREAD

**Issue by PoGo606** [tootsuite/mastodon#7897]
Hello,

I'm unable to initialize 2FA for any account in my instance.

When clicking on [Enable] all request are returned with a 500 error.

Logs below:
```
Jun 27 10:39:19 mastodon bundle[455]: [22633ccd-b1e3-4acf-bbd4-d93e2a3106e6] method=POST path=/settings/two_factor_authentication format=html controller=Settings::TwoFactorAuthenticationsController action=create status=500 error='ArgumentError: key must be 32 bytes or longer' duration=6.76 view=0.00 db=1.38
Jun 27 10:39:19 mastodon bundle[455]: [22633ccd-b1e3-4acf-bbd4-d93e2a3106e6]
Jun 27 10:39:19 mastodon bundle[455]: [22633ccd-b1e3-4acf-bbd4-d93e2a3106e6] ArgumentError (key must be 32 bytes or longer):
Jun 27 10:39:19 mastodon bundle[455]: [22633ccd-b1e3-4acf-bbd4-d93e2a3106e6]
Jun 27 10:39:19 mastodon bundle[455]: [22633ccd-b1e3-4acf-bbd4-d93e2a3106e6] app/controllers/settings/two_factor_authentications_controller.rb:15:in `create'
```
This is line 15 (git version, no local change):
```
sed '15q;d'  app/controllers/settings/two_factor_authentications_controller.rb
      current_user.otp_secret = User.generate_otp_secret(32)
```

So, I tried to generate the otp secret from the rails console:
```
RAILS_ENV=production bundle exec rails c
Loading production environment (Rails 5.2.0)
irb(main):004:0> User.generate_otp_secret(32)
=> "ryakgrga4g6fbaoovkrrbf65et6ktij6"
```
It seems to work and the output string is 32bits as requested.

I got this issue with v2.4.1 and v2.4.2 (and maybe earlier but I haven't tried before).

**Comment by PoGo606** [comment]
Anyone ?

**Comment by nightpool** [comment]
do you have a OPT secret in your config file?

**Comment by PoGo606** [comment]
Well, thank you for the lead !
I had an OTP secret in my config file but it was only 30 bits (same for PAPERCLIP_SECRET and SECRET_KEY_BASE).
I've generated a new one with: 
`RAILS_ENV=production bundle exec rake secret`
And now it's working as the generated secret is 128 bits.

I wonder if I should generate longer secrets for PAPERCLIP_SECRET and SECRET_KEY_BASE, will it break the current instance ?

**Comment by nightpool** [comment]
it won't break anything, but it will log out current users (to regenerate
their tokens)

**Comment by PoGo606** [comment]
```
# openssl version
OpenSSL 1.1.0f  25 May 2017
```
I also upgraded to version v2.4.3 facing the same issue.

**Comment by lfuelling** [comment]
I'm running `OpenSSL 1.1.0g  2 Nov 2017`, maybe you should upgrade?

I just tried to reproduce this by creating new 2FA credentials for my account and it worked.

**Comment by PoGo606** [comment]
> So I deleted some column data, and finally I can activate 2FA
Did the same and I could activate 2FA as well.
Thanks @ikuradon for the workaround !

**Comment by specked** [comment]
Got this issue after using the cli to --disable-2fa. Clearing the value in encrypted_otp_secret fixed it.

**Comment by capcom1701** [comment]
> Got this issue after using the cli to --disable-2fa. Clearing the value in encrypted_otp_secret fixed it.

I'm having the exact same issue. Are you cleaning values in the database? Where is that stored in a default setup?

**Comment by specked** [comment]
> > Got this issue after using the cli to --disable-2fa. Clearing the value in encrypted_otp_secret fixed it.
> 
> I'm having the exact same issue. Are you cleaning values in the database? Where is that stored in a default setup?

Log into your DB and delete the encrypted_otp_secret value in the Users table for the user in question.

**Comment by capcom1701** [comment]
Where is the DB?
