### ISSUE TITLE
Duplicate/similar web notifications sent

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#7902]
![image](https://user-images.githubusercontent.com/10606431/42003525-819e5a72-7a31-11e8-9b41-9dec241c853c.png)

Follow and mention notifications are being sent twice, with slightly different text:

Mentions:
- "x mentioned you"
- "you were mentioned by x"

Follows:
- "x followed you"
- "x is now following you"

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on  [v2.4.2](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by renatolond** [comment]
I have the same, also in v2.4.2.

**Comment by ThibG** [comment]
This has been bugging me for a long time, but I finally understand what's going on.
When the Service Worker receives a push event, it generates a notification.
However, that notification may have sub-par formatting, incomplete information, etc., so the code fetches the missing bits to craft a better notification.

This behavior was introduced in 4b94e9c65efd227c58f8be9b3db6b667d403ed3c.

So I guess we have to *replace* the notification without triggering a new one, if that's possible at all.

**Comment by renatolond** [comment]
Hm, this discarded situation is weird, I have a pebble and what I see is this:

A first notification arrives, in the format of `notification_mailer.favourite.subject`. Then, almost immediately, I get a second one in the format of `notification.favourite`. If I turn on the phone, I indeed see only the second one. But it seems to get weird when the notifications collapse, at that point I see both again.

**Comment by ThibG** [comment]
That looks like a bug in the browser, the first notification should be entirely discarded. And it should also not re-notify… I wonder if some properties changing between the two versions cause that…

Alternatively, we could postpone displaying a notification to when the subsequent API call returns…

**Comment by renatolond** [comment]
It seems the push example by google postpones until the API answers:
https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web#a_more_complete_push_event_example
