### ISSUE TITLE
Mentioning a user using 'M' hotkey results in '@undefined'

### ISSUE THREAD

**Issue by wakest** [tootsuite/mastodon#7903]
Mentioning a user using 'M' hotkey results in '@undefined' when using rightmost column.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Can reproduce, but only for the currently selected status
