### ISSUE TITLE
Video upload broken on iOS

### ISSUE THREAD

**Issue by chr-1x** [tootsuite/mastodon#7907]
This is based on a user report to me, I don't have an iOS device and can't verify right now.
Video of the problem: https://www.youtube.com/watch?v=5zIERUncQdQ&feature=youtu.be

My best guess is that iOS videos are not in a format mastodon accepts by default and there's no clientside autoconversion code or it's not working.

Reproduced on cybre.space and mastodon.xyz

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
iOS devices say they're recording mp4 videos but they're really lying and
recording mpeg or something in an mp4 container

**Comment by Gargron** [comment]
Probably fixed by #8101
