### ISSUE TITLE
Pool HTTP connections 

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#7909]
Some overhead of payload deliveries via sidekiq could be spared with pooled keepalive connections to popular inboxes. Overhead such as dns resolve, tcp connect, tls establishing.

**Comment by jebuskrust** [comment]
Curious..

Although wrapped in SSL, Could this potentially still lead to denial of service with pooled keep alive connections via TCP sequence number prediction attacks?  

- All an attacker needs to really know is the source and destination address (which is easy to figure out if you know instance A communicates with instance B)
- common ports
- a correctly guessed sequence number for a keep alive session
- provider that doesnt properly egress traffic (forging ip headers via raw sockets)

Cheers

**Comment by Gargron** [comment]
Idle connections should be closed after some timeout, of course. But if e.g. you are delivering a message to the same recipient every few seconds, I feel it could help a lot to reduce sending time (and possibly reduce CPU load on the receiving server, as well?)

Of course, this is not a matter of a simple switch, or using a ready-made connection pool. HTTP.rb supports keep-alive connections, but we need to manage them ourselves, in a thread-safe way (because Sidekiq jobs are run in different threads).

So we need something like a hash-based connection pool (where hash keys are the hostnames) with connections that close themselves after long inactivity.
