### ISSUE TITLE
Disable real-time timeline

### ISSUE THREAD

**Issue by littlemeowing** [tootsuite/mastodon#7913]
Currently, when viewing a timeline (local or federated) and being on the top of it, it will update automatically and therefore move on. 
This makes it very hard to explore timelines, especially when being disabled in some way (for example, the movement alone makes my head dizzy).

Possible solutions could include: 
- having a "view new toots" button or something similar
- including a toggle in the settings to change the functionality of timelines to not scroll until the user chooses to scroll manually (it can also be impairing or just annoying for some to constantly having to press a button for timeline updates)
- being able to set an interval for automatic updates (every X seconds/minutes) 

This issue was already opened here: https://github.com/tootsuite/mastodon/issues/240
It was closed around 16 hours ago, even though it is **not** solved. It is not reopened yet so I'm opening a new issue because it **is** important for many. 
If the old issue is reopened this one can be seen as unnecessary and can get closed.

**Comment by VirtualWolf** [comment]
I'd love to see it done how Tweetbot on Mac and iOS does it... if you're scrolled up to the very top, new tweets/toots will show up and bump everything else down, but if you're _not_, the new tweets/toots will be loaded above where you're currently scrolled to and won't cause your timeline to jump all over the place.

**Comment by apiontek** [comment]
Being new to Mastodon, the default automatic scrolling timelines is the most aggravating thing about using it. Don't get me wrong, I'm enjoying the fediverse, but having to deal with that timeline jumping around really discourages me from participating more.

**Comment by thomivy** [comment]
This is the single biggest impediment to using Mastodon for me - very surprised it has been an open issue for years.

**Comment by Tmeemu** [comment]
If you have an active timeline, the real-time updates practically make the timeline completely unusable. You cannot view or read anything because it's gone in seconds and when you try to click something you always end up clicking something else because your target already moved unpredictably. Hard to believe it hasn't been fixed ages ago because it's such an obvious problem when scaling up.
