### ISSUE TITLE
Regex filter is not working

### ISSUE THREAD

**Issue by Kjwon15** [tootsuite/mastodon#7917]
Regular expression filter on timeline is not working except for home timeline

![Home timeline](https://user-images.githubusercontent.com/5047683/42123460-62913024-7c8d-11e8-9a49-94df1335d994.png)
![Local timeline](https://user-images.githubusercontent.com/5047683/42123463-6a5865fc-7c8d-11e8-8c26-063ef4f71dd7.png)
![Federate timeline](https://user-images.githubusercontent.com/5047683/42123466-72e95136-7c8d-11e8-9659-5f6a7c8adb8c.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I have removed this option in master so I don't think this issue is relevant anymore. Now you have filters under preferences.
