### ISSUE TITLE
[question] invitation expire date to infinite

### ISSUE THREAD

**Issue by albjeremias** [tootsuite/mastodon#7923]
I'd like to have the possibility to have inifinte expire dates... I want to print some stickers with a QRcode which has invitations to join my mastodon instance! \o/

* * * *
Related issues:
https://github.com/tootsuite/mastodon/issues/6353

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ykzts** [comment]
![screenshot on invite page](https://user-images.githubusercontent.com/12539/42136477-21e28ffe-7d97-11e8-9851-2635c1272625.png)

"Expires after: Never" does not become infinite?

**Comment by albjeremias** [comment]
on mine maximum is 1week

**Comment by ykzts** [comment]
Are you are instance owner? or user?

Invites do not expire by default.

**Comment by albjeremias** [comment]
both...

**Comment by nightpool** [comment]
@albjeremias admins should create invites from the `/admin/invites` page instead of the normal user page. You can create indefinite invites there, but it's in the admin section of the website to prevent it from being mistaken for a user privilege.
