### ISSUE TITLE
mastodon.social unexpectedly closed the connection. for Iranian Ips

### ISSUE THREAD

**Issue by aliforever** [tootsuite/mastodon#793]
Are we doing the "Limit the internet for Iranians, and Blame USA Sanctions" here like other websites too?

**Comment by tobypinder** [comment]
It's actually struggling just about everywhere, I'd be hesistant to say it's a geographic lockout reason and I certainly don't think @Gargron would impose such restriction (there is no cloudflare or upstream provider that would interfere I don't think).

Pretty sure it's just the site exploding for everyone in general :) :boom:

**Comment by unascribed** [comment]
Yep. I'm in the US and it's struggling hard. It got promoted on some French magazine, I think.

**Comment by aliforever** [comment]
It's happening a lot these days for Iranians, half of the websites are censored, the other half are sanctioned and I was able to login after using a VPN. Hope it's just about heavy traffic.

**Comment by swaldie** [comment]
I believe the case is simply the load on the flagship instance at this time.  I'm closing the issue for now, feel free to open a new one if more investigation is required.
