### ISSUE TITLE
can cause mastodon to have two compose columns at once

### ISSUE THREAD

**Issue by timo** [tootsuite/mastodon#794]
Here's how to reproduce:
make browser thin enough so that it turns into one-column-at-once mode, go to federated or local timeline, click the reply button, make browser window normal-sized again

Here's the result:
![masto_wtf](https://cloud.githubusercontent.com/assets/25167/24621627/71f13e38-18a2-11e7-84b4-4e55d27d689d.png)

**Comment by timo** [comment]
actually, after you get the ui into this state once, it'll always pop up the compose column on the right when you click "reply" on a toot in there.

**Comment by Gargron** [comment]
This is not a bug, but a product of the fact that the address bar URL controls the content of the context column.
