### ISSUE TITLE
Feature Request: Categorizing or reordering of custom emojis

### ISSUE THREAD

**Issue by Phroneris** [tootsuite/mastodon#7940]
I'm an user in an instance with many custom emojis.
Since they're so many, the administrator and I are looking for a way to organize them somewhat comprehensibly, but for now we can only implement it by adding meaningless prefixes on their shortcodes to be sorted in alphabetical order.
So we'd like an admin function to categorize or reorder custom emojis on Mastodon.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Miaourt** [comment]
Merging two issues #11009 
I would like to have the ability to add custom emojis to already existing categories  (Can be useful to add, for example, pride flags to the "flag" category)
