### ISSUE TITLE
scheduler for opening/closing registrations.

### ISSUE THREAD

**Issue by 3dn0** [tootsuite/mastodon#7942]
That would be cool to add a scheduler for opening/closing subscriptions on Mastodon. I'll probably change my server in a few months and that would be enough (I guess) to allow a certain amount of subscriptions, but Ideally, that would be nice to open subscriptions only one day per week (or every 2 weeks), starting and ending at a precise time. Of course I could do that myself, but a scheduler would be less prone to "oops, I've forgotten" ;)
So a scheduler could help all admins that want to open registrations (sort of), even with a small server.
Thanks !

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by renatolond** [comment]
I think this would be nice to have from the admin panel too, but in the meanwhile if you also admin your server, you can use `RAILS_ENV=production bundle exec rake mastodon:settings:open_registrations` and `RAILS_ENV=production bundle exec rake mastodon:settings:close_registrations` called from a cron script to do it automatically. I did it like that for a while for masto.donte :)

**Comment by 3dn0** [comment]
Nice, thanks ! :)
I thought that something might be possible with cron jobs, but I didn't know where to start.
I agree, a nice option in the admin panel would be cool, but in the meantime your solution will be perfect :) Thanks again !
