### ISSUE TITLE
"this.context.router is undefined" error on Firefox

### ISSUE THREAD

**Issue by JD557** [tootsuite/mastodon#7948]
On `mastodon.social`, when I click on any image on the public timeline (i'm not logged in), I get a `TypeError: "this.context.router is undefined"`.

I tried this with images from multiple instances, including `mastodon.social`.

Running Firefox 61.0 on Windows 10.

*EDIT:* Other instances running 2.4.2 like `banana.dog` do not have this problem on their front page. This might just be an error on `mastodon.social`.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Fixed in master, and just updated mastodon.social.
