### ISSUE TITLE
Issues signing up and with validation error handling

### ISSUE THREAD

**Issue by Lewiscowles1986** [tootsuite/mastodon#796]
https://twitter.com/Unix_Guru/status/848950138836004865

**Comment by tobypinder** [comment]
Everything is pretty much #downrightnow, it's going viral.

**Comment by Lewiscowles1986** [comment]
Sorry @tobypinder I just thought rather than whine or contribute to the viral whining I'd link the comment. FWIW it's a wonderful idea to have a de-centralised social network.

**Comment by Gargron** [comment]
I believe this was a general hardware-not-keeping-up failure, not a software bug. Can I close?
