### ISSUE TITLE
Include timezone offset in machine-readable timestamp

### ISSUE THREAD

**Issue by aaronpk** [tootsuite/mastodon#7982]
Toots are displayed in (someone's) local time, but the machine readable date is always rendered in UTC.

The machine readable date should be rendered as an ISO8601 timestamp with the same timezone offset that the human readable date is rendered as. That applies both [here](https://github.com/tootsuite/mastodon/blob/cd509d2146439490bcb63081739db1d5fd485d56/app/views/stream_entries/_simple_status.html.haml#L6) and [here](https://github.com/tootsuite/mastodon/blob/30e1da7668c6c42aa5f15bdc9caab1929235f78f/app/views/stream_entries/_detailed_status.html.haml#L32).

**Comment by nightpool** [comment]
toots are displayed in client-side local time though? it would be
impossible to render them with a timezone offset.

what would be the point of this anyway? the machine readable date should
always be utc for consistency

**Comment by aaronpk** [comment]
I didn't realize that was changing the displayed time client-side.

Using `Z` for the offset is the lazy way to avoid the problem. As long as the timezone offset is included in the timestamp, it still refers to an absolute point in time and can be easily converted to other timezones. (e.g. `2018-07-08T06:57:00-0700`) 

Ideally the timestamps should be rendered in the timezone the post was authored in, as that can provide additional context for a post (did they post this in their morning or late at night?) But, if you don't have that information available then there isn't much you can do.
