### ISSUE TITLE
How to build "groups" with users / followers?

### ISSUE THREAD

**Issue by pwFoo** [tootsuite/mastodon#7983]
Found Mastodon and it looks nice, but is it possible to build something like groups / lists / teams with subscribed followers?
Something like streams for different teams to share text and images to the team members and talk to each other. Optional a private stream for subscribed users only.

Should be easy for users or configured (followers / invite) by group / team admin.

Maybe someone could help me to find an (existing) solution?

**Comment by enterprisey** [comment]
(possible duplicate, definitely related: #139)
