### ISSUE TITLE
Mastodon grew to use all available local storage (2GB) then 100% CPU

### ISSUE THREAD

**Issue by remram44** [tootsuite/mastodon#7985]
Firefox 61.0, framapiaf.org

Related: 7893

Mastodon just grew to use 2GB of local storage, which is not ok. Not only that, but upon hitting the limit, it did not clear anything from the cache, and used 100% CPU just outputting `NS_ERROR_FILE_NO_DEVICE_SPACE` in the console.

This is how I identified the issue, from my laptop running hot, then figuring out which tab was using 100% CPU. At NO POINT Mastodon showed a user-visible error (other than some profile pics being missing).

I think there are two major issues here:
* Mastodon uses way too much disk space, to the point of not being able to work properly.
* when this happens, it loops and uses 100% CPU as well. It should **at least stop looping** and show an error, and preferably drop entries from storage.

![screenshot of Firefox settings](https://user-images.githubusercontent.com/426784/42465715-c61435da-837a-11e8-950f-be74201f0151.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
We're disabling service worker caching in 2.4.3 which will be going out in a few days, which will resolve this problem.
