### ISSUE TITLE
PAPERCLIP_ROOT_PATH changes writes, not reads

### ISSUE THREAD

**Issue by NFGman** [tootsuite/mastodon#8002]
While trying to configure a single server with two Mastodon instances, @Gargron suggested the PAPERCLIP_ROOT_PATH directive to store one instance's data separately from the other.

Unfortunately, using this directive changes only the write location.  All incoming media is placed in the right place, but they all 404 to the client because it's trying to serve them from the default location.

Using unmodified 2.4.2.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Found it. You need to use `PAPERCLIP_ROOT_URL` in tandem with `PAPERCLIP_ROOT_PATH`
