### ISSUE TITLE
Modal regression with scrollable areas

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#8008]
After #7934, opening a modal makes the scrollable area in the not-pinned column jump to top. Once the modal is closed, it jumps back to the old position.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
cc @MaciekBaron maybe you know what's up

**Comment by MaciekBaron** [comment]
I can have a look this weekend. It's possible that the empty state I create causes this behaviour. Hopefully there's a way around it.

**Comment by MaciekBaron** [comment]
I'm trying to replicate the problem: could you show a precise example of this behaviour? I can't replicate on the Home column in Chrome when opening an image modal.

**Comment by MaciekBaron** [comment]
Sorry, can replicate now! When, say, viewing a user's feed.

**Comment by Gargron** [comment]
Yes, it's gotta be the non-pinned, route-based column, because (I think) it uses the scroll area component that saves scroll position between route changes (so you can go back to the same place in a timeline from detailed view) (the pinned columns don't need to save scrolling state like that). But I don't know why exactly it decided to jump to top...

**Comment by MaciekBaron** [comment]
Thanks, I'll try looking into this tomorrow. Luckily it doesn't seem to have a huge impact.

**Comment by ThibG** [comment]
There is another minor issue with that change: the duplicate history element stays in the history, without bringing the modal back: that is, once gone back, pressing the browser's “forward” button will stay on the same page without bringing the modal, *and* resetting the scroll position.

**Comment by ThibG** [comment]
Also, this applies to pretty much every modal, like the report modal, the video modal, the boost confirmation… this would lead me to believe we should pass the modal parameters in the history state and use that to display the modal, but… it doesn't really make sense for some modals (like the boost confirmation modal) to be kept in history…

**Comment by Gargron** [comment]
@ThibG Can you submit that? Alternatively, it's possible to not push history in desktop mode and only do so on mobile where the back button truly matters.

**Comment by ThibG** [comment]
@Gargron I did something similar in glitch-soc (https://github.com/glitch-soc/mastodon/pull/607) but I'm not completely satisfied because it creates a duplicate entry in the browser history. Also, going forward after canceling a modal doesn't bring it back, this would require far more refactoring.

I think some modals would actually benefit from having a route (media modals for instance), but that's quite some work.

**Comment by MaciekBaron** [comment]
Thanks for taking care of this! I'm on holidays so couldn't have a look but should be able to start helping again when I'm back.
