### ISSUE TITLE
Single media posts view is way too small on 2.4.3

### ISSUE THREAD

**Issue by kit-ty-kate** [tootsuite/mastodon#8018]
Since some instances have upgraded to 2.4.3 I've noticed that some posts with an image, when you click on it to get the "single post view" (`https://<instance>/@<user>/<post id>`) they are displayed way way too small (`28px` small). When I inspect the `img` element, it has a `sizes="28px"` attribute but the original size of the image is much bigger.

This seems to happen to instances that have their images on a CDN (e.g. sleeping.town)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kit-ty-kate** [comment]
It also happens on mastodon.social. For example: https://mastodon.social/@yuri_bot/100386276167358453

**Comment by Gargron** [comment]
The problem seems to be that the container div (with data-component attribute) does not take 100% width of the parent.
