### ISSUE TITLE
Liberapay is in trouble

### ISSUE THREAD

**Issue by his10** [tootsuite/mastodon#8020]
In case you're not aware of it, you should withdraw your income from your Liberapay wallet as soon as possible: https://medium.com/liberapay-blog/liberapay-is-in-trouble-b58b40714d82

You do not want to ignore this: https://github.com/liberapay/liberapay.com/pull/1169#issuecomment-404459576

@chris-martin @Gargron @joyeusenoelle

**Comment by Gargron** [comment]
Thank you. I have stopped using Liberapay, at least at this point in time.
