### ISSUE TITLE
Information cut off on remote follow interface.

### ISSUE THREAD

**Issue by wakest** [tootsuite/mastodon#8036]
Follower information cut off on remote follow interface.

From [authorize_follow](https://mastodon.social/authorize_follow?acct=jcgruenhage@blog.jcg.re)

<img width="493" alt="screen shot 2018-07-16 at 4 58 28 pm" src="https://user-images.githubusercontent.com/7890201/42766043-b001f56c-8919-11e8-8834-9b5ad7ba9cfe.png">

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [2.4.3](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Design changed
