### ISSUE TITLE
Account action bar doesn’t work well with flexible columns

### ISSUE THREAD

**Issue by ariasuni** [tootsuite/mastodon#8052]
When we use a theme or a custom CSS to have flexible size columns, button size don’t adapt and the area for the dropdown button becomes really big.

![screenshot_2018-07-19 eldritch cafe](https://user-images.githubusercontent.com/2446451/42936055-704d40a0-8b4b-11e8-88f8-2f29ae129e40.png)

The buttons size should grow with the size of the column like before the introduction of the dropdown button on the right.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
You're already using custom CSS, so you can also adjust the widths within your CSS theme.
