### ISSUE TITLE
Tusky notifications seem to crash homescreen

### ISSUE THREAD

**Issue by Bugsbane** [tootsuite/mastodon#8053]
Ok, I'm not exactly sure the cause of this, but often when I'm using my phone, the moment a Tusky notification comes in, suddenly my phone goes back to the lock screen. I think the home/ lock screen is crashing and restarting.

It only happens with Tusky notifications. I'm on a ZTE 951 with Android 6.0.1 and Tusky 2.1 from FDroid.

Can I provide any other info to help?

**Comment by kit-ty-kate** [comment]
This is probably not the place to put such issue. https://github.com/tuskyapp/Tusky probably is.

**Comment by nightpool** [comment]
the mastodon project does not run or maintain Tusky. you should contact the developers of that application
