### ISSUE TITLE
Idea: allow to add reactions to a toot

### ISSUE THREAD

**Issue by schiessle** [tootsuite/mastodon#8054]
I had it already multiple times and I have the feeling that I'm not the only one. You write a question, get a lot of good answers and want to say "Thank you". In the past I sometimes liked the answers but that makes my favorite list confusing. If I always answer "Thanks" the conversation gets less clear.

Therefore my ides: let the user add reactions to toot's, similar to what you can do here for github issues and comments: thanks, +1, -1, hooray,...

**Comment by trwnh** [comment]
duplicate #4106 maybe?

**Comment by schiessle** [comment]
@trwnh I agree, let's continue there...
