### ISSUE TITLE
[ActivityPub] public key not found

### ISSUE THREAD

**Issue by mart-e** [tootsuite/mastodon#8057]
Hi there,

I am trying to use ActivityPub as a client to post a note on a Mastodon server but I got an error `Public key not found for key https://mamot.fr/users/mart_e#main-key`.

I have based my work on [How to implement a basic ActivityPub server](https://blog.joinmastodon.org/2018/06/how-to-implement-a-basic-activitypub-server/) which I guess should be reliable.
I am not sure if it is a bug in Mastodon or my script (probably the later) but it goes like this:

```python
actor = # content from https://mamot.fr/users/mart_e.json
activity = {
   ...
    "type": "Create",
    "actor": actor['id'],
    "object": {
        "type": "Note",
        "content": message,
        ...
    }
}

signature, date = do_some_openssl_magic()
public_key = actor['publicKey']['id']  # https://mamot.fr/users/mart_e#main-key
header = 'keyId="'+ public_key + '",headers="(request-target) host date",signature="' + signature + '"'
# keyId="https://mamot.fr/users/mart_e#main-key",headers="(request-target) host date",signature="CGvpZ6pt..."

r = requests.post(endpoint,  # https://mamot.fr/inbox
            data=activity,
            headers={
                'Host': host,  # mamot.fr
                'Date': date,
                'Signature': header,
            })

```
And making the requests returns me an error message 

```
Public key not found for key https://mamot.fr/users/mart_e#main-key
```

What am I missing?

Reading the source, code, I see server fails to retrieve the `account_from_key_id`
https://github.com/tootsuite/mastodon/blob/7e638043b953b80ee0af11dc62d87eed14e98c98/app/controllers/concerns/signature_verification.rb#L40-L43

I also tried with the webfinger format `acct:mart_e@mamot.fr`.
Which now, returns me a 202 status code and no content (not sure if accepted or the error is somewhere else).

As of today, mamot.fr [uses](https://mamot.fr/about) source 2.4.1

Thanks

**Comment by nightpool** [comment]
You're sending mamot.fr a federated message that you claim was signed by one of it's own local users. Mastodon does not support this use-case. It doesn't allow other servers to create local posts. You can send the message you created to *other* servers (assuming you did manage to export the right private key), or start your own server (using your own actor and key) and send *that* message to mamot.fr

You might be confusing our implementation of the ActivityPub server to server api for an implementation of the ActivityPub client-to-server API, where you would send posts to the activitypub *outbox* for promulgation. We do not support the AP C2S api.

**Comment by mart-e** [comment]
Indeed, I was testing a C2S scenario. I did not know it was not supported. Is it planned ?

**Comment by nightpool** [comment]
I do not believe c2s support is planned at this time

**Comment by TiMESPLiNTER** [comment]
I try to follow an actor on a mastadon instance from my own local machine. I sign my request and have uploaded my public key to a publicly available place where mastadon should be able to fetch it (a domain with a valid SSL cert).

But all I get is: 

```
Public key not found for key https://www.example.com/id.pub
```
But I can download the public key with CURL without any problem.

The request looks like this:

```json
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "type": "Follow",
    "summary": "john.doe follows foobarbaz",
    "actor": {
        "@context": [
            "https://www.w3.org/ns/activitystreams",
            "https://w3id.org/security/v1"
        ],
        "type": "Person",
        "id": "https://localhost:8989/john.doe",
        "preferredUsername": "john.doe",
        "inbox": "https://localhost:8989/account/john.doe/inbox",
        "outbox": "https://localhost:8989/account/john.doe/outbox",
        "followers": "https://localhost:8989/account/john.doe/followers",
        "following": "https://localhost:8989/account/john.doe/following",
        "liked": "https://localhost:8989/account/john.doe/liked",
        "publicKey": {
            "@context": "https://w3id.org/security/v1",
            "@type": "Key",
            "id": "https://localhost:8989/john.doe#main-key",
            "owner": "https://localhost:8989/john.doe",
            "publicKeyPem": "-----BEGIN PUBLIC KEY-----\\nMIIBIjANBg...MNgwQII57\\niQIDAQAB\\n-----END PUBLIC KEY-----"
        }
    },
    "object": {
        "@context": [
            "https://www.w3.org/ns/activitystreams",
            "https://w3id.org/security/v1"
        ],
        "type": "Person",
        "id": "https://other-example.com/users/foobarbaz",
        "preferredUsername": "foobarbaz",
        "inbox": "https://other-example.com/users/foobarbaz/inbox",
        "outbox": "https://other-example.com/users/foobarbaz/outbox",
        "followers": "https://other-example.com/users/foobarbaz/followers",
        "following": "https://other-example.com/users/foobarbaz/following"
    }
}
```

And the `Signature` header:

```
keyId="https://example.com/id.pub",headers="(request-target) host date",signature="j9KruD7enrWaYaJuZ...4BjSUw=="
```

**Comment by nightpool** [comment]
how is "https://www.example.com/id.pub" supposed to get matched up with "
https://localhost:8989/john.doe#main-key"? I'm not sure I understand

**Comment by nightpool** [comment]
either way, this issue is about something else entirely. for usage based questions, please make a thread on https://discourse.joinmastodon.org or ask on IRC.
