### ISSUE TITLE
Person masking their identity?

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#8058]
This looks well dodgy.

![screen shot 2018-07-22 at 15 01 41](https://user-images.githubusercontent.com/6607512/43046404-45526fde-8dc0-11e8-8746-6ed8463bcc25.png)

![screen shot 2018-07-22 at 15 01 50](https://user-images.githubusercontent.com/6607512/43046410-52f3a478-8dc0-11e8-9dd7-be7958eae881.png)

![screen shot 2018-07-22 at 15 01 52](https://user-images.githubusercontent.com/6607512/43046411-57a65a9c-8dc0-11e8-832b-8a8a0e17256c.png)

Clicking their avatar leads to: https://ap.uwu.st/gar.ajson

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by lfuelling** [comment]
I saw this too a while ago and thought it was a fuckup with the tooltips! (Haven't tried clicking the link)

**Comment by Gargron** [comment]
It's bootsy messing around but we need to come up with a way to prevent this

**Comment by trwnh** [comment]
Perhaps treat username and domain as separate when shortening? The domain should be as visible as possible in an example like this -- something like `@Gargron@mas...@ap.uwu.st` would be better than displaying a really long name that's just trying to push the domain out of sight. Fundamentally, trusting the domain is the first step in determining whether an account is trustworthy -- the username is the second step.

**Comment by e-ht** [comment]
I think domains, while they need to be trusted are just a sub identifier to username. Having the domain be as visible as possible feels unbalanced from a social network perspective. 

What about providing a potential spoof warning/grouping if any length of the spoofer's username contains the domain (or n:length) of other users in the user list. Then we could still benefit from having the username/domain shortened.
