### ISSUE TITLE
Pleroma image attachments not displaying

### ISSUE THREAD

**Issue by htrob** [tootsuite/mastodon#8059]
This may be a problem in the way Pleroma is handling image previews but I have no way of knowing which is the source of the incompatibility.  It may just be a differing interpretation of the protocol.

Here's a sample toot originating from a Pleroma instance. The toot is displayed correctly on the public view of its origin instance.
https://ap.lollipopcloud.solutions/notice/3376

See screenshot below what the same toot looks like from my instance (social.coop) in the timeline.
If you click on the attachment's a filename (a hash without image file extension), the browser won't display it, and a binary download will proceed in the browser Download tab.
The filename of the attached image in that toot doesn't have a .jpg extension, which may be breaking things if Mastodon infers the mime type of attachments from that.

![screenshot at 2018-07-23 01-23-03](https://user-images.githubusercontent.com/23458/43057248-7e88bcca-8e17-11e8-85e6-99e4e45083b2.png)
![screenshot at 2018-07-23 01-24-03](https://user-images.githubusercontent.com/23458/43057251-82f32192-8e17-11e8-9859-035b1b8a1330.png)

**Comment by Gargron** [comment]
The original image file is probably too big and rejected by Mastodon. This is why you get it as a link rather than thumbnail, it would be computationally expensive to generate a thumbnail and store a copy of the original.

**Comment by nightpool** [comment]
The original image only seems to be about 3 MB. It's possible this is a paperclip image validation bug?

**Comment by nightpool** [comment]
It's getting very close to the length*width limit (4640x3480 == 16,147,200 vs 16,777,216) so it's possible the mastodon instance rejected it or ran out of memory when resizing it.

**Comment by htrob** [comment]
No harm done.  Just thought it was odd, and at first it looked like there was some incompatibility going on.

Thanks guys.
