### ISSUE TITLE
Node 8: 'yarn check' gives error after precompile

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#8061]
_Maybe this is one is related to my [previous issue](https://github.com/tootsuite/mastodon/issues/8060)._

I upgraded my (non-docker) installation (todon.nl) from node 6* to node 8* (8.11.3). To make sure all worked fine I did this in the Mastodon live folder:

    yarn cache clear
    yarn install --pure-lockfile

I notices that when I did a 'yarn check' emoji-mart was not installed, so I installed it with 'yarn add emoji-mart'. After that 'yarn check' was OK (only a warning with '"react-router-scroll-4#babel-eslint@^8.0.1" could be deduped from "8.2.3" to "babel-eslint@8.2.3"'.

When I do a

    RAILS_ENV=production bundle exec rails assets:precompile

it compiles normally and I can restart the Mastodon services without problems as usual.

But when I do a 'yarn check' I get:

    yarn check v1.7.0
    info fsevents@1.1.3: The platform "linux" is incompatible with this module.
    info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
    error "@babel/types" not installed
    error "doctrine" not installed
    error "domelementtype" not installed
    error "babel-eslint" not installed
    error "enzyme" not installed
    error "enzyme-adapter-react-16" not installed
    error "eslint" not installed
    error "eslint-plugin-import" not installed
    error "eslint-plugin-jsx-a11y" not installed
    error "eslint-plugin-promise" not installed
    error "eslint-plugin-react" not installed
    error "jest" not installed
    error "react-intl-translations-manager" not installed
    error "react-test-renderer" not installed
    error "webpack-dev-server" not installed
    error "babel-eslint#@babel/code-frame" not installed
    error "babel-eslint#@babel/traverse" not installed
    error "eslint#ajv" not installed
    error "webpack-dev-server#ansi-html" not installed
    error "eslint-plugin-jsx-a11y#aria-query" not installed
    error "eslint-plugin-jsx-a11y#ast-types-flow" not installed
    error "eslint-plugin-jsx-a11y#axobject-query" not installed
    error "babel-eslint#babylon" not installed
    error "webpack-dev-server#bonjour" not installed
    error "enzyme#cheerio" not installed
    error "webpack-dev-server#compression" not installed
    error "eslint#concat-stream" not installed
    error "webpack-dev-server#connect-history-api-fallback" not installed
    error "eslint-plugin-import#contains-path" not installed
    error "eslint-plugin-jsx-a11y#damerau-levenshtein" not installed
    error "webpack-dev-server#debug" not installed
    error "eslint#debug" not installed
    error "webpack-dev-server#del" not installed
    error "eslint-plugin-import#doctrine" not installed
    error "eslint-plugin-jsx-a11y#emoji-regex" not installed
    error "eslint-plugin-import#eslint-import-resolver-node" not installed
    error "eslint-plugin-import#eslint-module-utils" not installed
    error "eslint#espree" not installed
    error "eslint#esquery" not installed
    error "eslint#file-entry-cache" not installed
    error "enzyme#function.prototype.name" not installed
    error "eslint#functional-red-black-tree" not installed
    error "webpack-dev-server#html-entities" not installed
    error "webpack-dev-server#http-proxy-middleware" not installed
    error "eslint#ignore" not installed
    error "webpack-dev-server#import-local" not installed
    error "eslint#imurmurhash" not installed
    error "eslint#inquirer" not installed
    error "webpack-dev-server#internal-ip" not installed
    error "webpack-dev-server#ip" not installed
    error "eslint#is-resolvable" not installed
    error "enzyme#is-subset" not installed
    error "jest#jest-cli" not installed
    error "eslint#json-stable-stringify-without-jsonify" not installed
    error "eslint-plugin-jsx-a11y#jsx-ast-utils" not installed
    error "webpack-dev-server#killable" not installed
    error "eslint#levn" not installed
    error "eslint-plugin-import#lodash.cond" not installed
    error "webpack-dev-server#loglevel" not installed
    error "eslint#natural-compare" not installed
    error "enzyme#object-is" not installed
    error "enzyme#object.assign" not installed
    error "enzyme#object.entries" not installed
    error "webpack-dev-server#opn" not installed
    error "eslint#optionator" not installed
    error "eslint#path-is-inside" not installed
    error "eslint#pluralize" not installed
    error "webpack-dev-server#portfinder" not installed
    error "eslint#progress" not installed
    error "eslint-plugin-import#read-pkg-up" not installed
    error "eslint#regexpp" not installed
    error "eslint#require-uncached" not installed
    error "enzyme#rst-selector-parser" not installed
    error "webpack-dev-server#selfsigned" not installed
    error "webpack-dev-server#serve-index" not installed
    error "webpack-dev-server#sockjs-client" not installed
    error "webpack-dev-server#sockjs" not installed
    error "webpack-dev-server#spdy" not installed
    error "eslint#strip-ansi" not installed
    error "eslint#table" not installed
    error "eslint#text-table" not installed
    error "webpack-dev-server#yargs" not installed
    error "enzyme-adapter-react-16#enzyme-adapter-utils" not installed
    error "webpack-dev-server#webpack-dev-middleware" not installed
    error "@babel/traverse#@babel/code-frame" not installed
    error "@babel/traverse#@babel/generator" not installed
    error "@babel/traverse#@babel/helper-function-name" not installed
    error "@babel/traverse#@babel/helper-split-export-declaration" not installed
    error "babel-eslint#@babel/code-frame#@babel/highlight" not installed
    error "espree#acorn-jsx" not installed
    error "espree#acorn" not installed
    error "table#ajv" not installed
    error "jest-cli#ansi-escapes" not installed
    error "eslint#strip-ansi#ansi-regex" not installed
    error "bonjour#array-flatten" not installed
    error "portfinder#async" not installed
    error "@babel/traverse#babylon" not installed
    error "serve-index#batch" not installed
    error "require-uncached#caller-path" not installed
    error "inquirer#cli-cursor" not installed
    error "inquirer#cli-width" not installed
    error "compression#compressible" not installed
    error "cheerio#css-select" not installed
    error "@babel/traverse#debug" not installed
    error "bonjour#deep-equal" not installed
    error "optionator#deep-is" not installed
    error "bonjour#dns-equal" not installed
    error "bonjour#dns-txt" not installed
    error "cheerio#dom-serializer" not installed
    error "cheerio#entities" not installed
    error "sockjs-client#eventsource" not installed
    error "inquirer#external-editor" not installed
    error "optionator#fast-levenshtein" not installed
    error "sockjs#faye-websocket" not installed
    error "sockjs-client#faye-websocket" not installed
    error "inquirer#figures" not installed
    error "file-entry-cache#flat-cache" not installed
    error "spdy#handle-thing" not installed
    error "cheerio#htmlparser2" not installed
    error "spdy#http-deceiver" not installed
    error "http-proxy-middleware#http-proxy" not installed
    error "jest-cli#is-ci" not installed
    error "http-proxy-middleware#is-glob" not installed
    error "del#is-path-cwd" not installed
    error "del#is-path-in-cwd" not installed
    error "opn#is-wsl" not installed
    error "jest-cli#istanbul-api" not installed
    error "jest-cli#istanbul-lib-coverage" not installed
    error "jest-cli#istanbul-lib-instrument" not installed
    error "jest-cli#istanbul-lib-source-maps" not installed
    error "jest-cli#jest-changed-files" not installed
    error "jest-cli#jest-config" not installed
    error "jest-cli#jest-environment-jsdom" not installed
    error "jest-cli#jest-haste-map" not installed
    error "jest-cli#jest-message-util" not installed
    error "jest-cli#jest-regex-util" not installed
    error "jest-cli#jest-resolve-dependencies" not installed
    error "jest-cli#jest-runner" not installed
    error "jest-cli#jest-runtime" not installed
    error "jest-cli#jest-snapshot" not installed
    error "jest-cli#jest-util" not installed
    error "sockjs-client#json3" not installed
    error "rst-selector-parser#lodash.flattendeep" not installed
    error "webpack-dev-middleware#mime" not installed
    error "bonjour#multicast-dns-service-types" not installed
    error "bonjour#multicast-dns" not installed
    error "inquirer#mute-stream" not installed
    error "rst-selector-parser#nearley" not installed
    error "selfsigned#node-forge" not installed
    error "jest-cli#node-notifier" not installed
    error "compression#on-headers" not installed
    error "del#p-map" not installed
    error "cheerio#parse5" not installed
    error "del#pify" not installed
    error "jest-cli#pify" not installed
    error "eslint-module-utils#pkg-dir" not installed
    error "optionator#prelude-ls" not installed
    error "eslint-plugin-import#read-pkg-up#read-pkg" not installed
    error "import-local#resolve-cwd" not installed
    error "require-uncached#resolve-from" not installed
    error "inquirer#run-async" not installed
    error "inquirer#rx-lite-aggregates" not installed
    error "inquirer#rx-lite" not installed
    error "spdy#select-hose" not installed
    error "table#slice-ansi" not installed
    error "spdy#spdy-transport" not installed
    error "jest-cli#string-length" not installed
    error "inquirer#string-width" not installed
    error "table#string-width" not installed
    error "jest-cli#strip-ansi" not installed
    error "inquirer#strip-ansi" not installed
    error "webpack-dev-middleware#time-stamp" not installed
    error "optionator#type-check" not installed
    error "concat-stream#typedarray" not installed
    error "sockjs-client#url-parse" not installed
    error "sockjs#uuid" not installed
    error "optionator#wordwrap" not installed
    error "jest-cli#worker-farm" not installed
    error "webpack-dev-server#yargs#yargs-parser" not installed
    error "jest-cli#yargs" not installed
    error "@babel/helper-function-name#@babel/helper-get-function-arity" not installed
    error "@babel/helper-function-name#@babel/template" not installed
    error "parse5#@types/node" not installed
    error "acorn-jsx#acorn" not installed
    error "jest-cli#strip-ansi#ansi-regex" not installed
    error "inquirer#strip-ansi#ansi-regex" not installed
    error "string-length#astral-regex" not installed
    error "jest-runtime#babel-plugin-istanbul" not installed
    error "css-select#boolbase" not installed
    error "dns-txt#buffer-indexof" not installed
    error "caller-path#callsites" not installed
    error "jest-util#callsites" not installed
    error "jest-cli#yargs#camelcase" not installed
    error "external-editor#chardet" not installed
    error "is-ci#ci-info" not installed
    error "flat-cache#circular-json" not installed
    error "css-select#css-what" not installed
    error "istanbul-lib-source-maps#debug" not installed
    error "flat-cache#del" not installed
    error "spdy-transport#detect-node" not installed
    error "multicast-dns#dns-packet" not installed
    error "dom-serializer#domelementtype" not installed
    error "htmlparser2#domhandler" not installed
    error "css-select#domutils" not installed
    error "htmlparser2#domutils" not installed
    error "http-proxy#eventemitter3" not installed
    error "jest-haste-map#fb-watchman" not installed
    error "istanbul-api#fileset" not installed
    error "eslint-module-utils#pkg-dir#find-up" not installed
    error "node-notifier#growly" not installed
    error "spdy-transport#hpack.js" not installed
    error "http-proxy-middleware#is-glob#is-extglob" not installed
    error "is-path-in-cwd#is-path-inside" not installed
    error "run-async#is-promise" not installed
    error "istanbul-api#istanbul-lib-hook" not installed
    error "istanbul-api#istanbul-lib-report" not installed
    error "istanbul-api#istanbul-reports" not installed
    error "jest-snapshot#jest-diff" not installed
    error "jest-runner#jest-docblock" not installed
    error "jest-config#jest-environment-node" not installed
    error "jest-config#jest-get-type" not installed
    error "jest-runner#jest-jasmine2" not installed
    error "jest-snapshot#jest-matcher-utils" not installed
    error "jest-environment-jsdom#jest-mock" not installed
    error "jest-config#jest-resolve" not installed
    error "jest-config#jest-validate" not installed
    error "jest-environment-jsdom#jsdom" not installed
    error "@babel/generator#jsesc" not installed
    error "eslint-plugin-import#read-pkg#load-json-file" not installed
    error "compressible#mime-db" not installed
    error "nearley#nomnom" not installed
    error "css-select#nth-check" not installed
    error "spdy-transport#obuf" not installed
    error "eventsource#original" not installed
    error "jest-cli#yargs#os-locale" not installed
    error "eslint-plugin-import#read-pkg#path-type" not installed
    error "jest-runner#pify" not installed
    error "jest-snapshot#pretty-format" not installed
    error "url-parse#querystringify" not installed
    error "nearley#railroad-diagrams" not installed
    error "nearley#randexp" not installed
    error "jest-cli#yargs#read-pkg-up" not installed
    error "http-proxy#requires-port" not installed
    error "resolve-cwd#resolve-from" not installed
    error "cli-cursor#restore-cursor" not installed
    error "jest-haste-map#sane" not installed
    error "node-notifier#shellwords" not installed
    error "jest-cli#yargs#string-width" not installed
    error "table#string-width#strip-ansi" not installed
    error "string-length#strip-ansi" not installed
    error "jest-runner#throat" not installed
    error "multicast-dns#thunky" not installed
    error "external-editor#tmp" not installed
    error "spdy-transport#wbuf" not installed
    error "sockjs-client#faye-websocket#websocket-driver" not installed
    error "jest-cli#yargs#which-module" not installed
    error "jest-runtime#write-file-atomic" not installed
    error "flat-cache#write" not installed
    error "jest-runtime#yargs" not installed
    error "jest-runtime#babel-jest" not installed
    error "@babel/template#@babel/code-frame" not installed
    error "jsdom#abab" not installed
    error "jsdom#acorn-globals" not installed
    error "table#strip-ansi#ansi-regex" not installed
    error "string-length#strip-ansi#ansi-regex" not installed
    error "pretty-format#ansi-regex" not installed
    error "istanbul-lib-hook#append-transform" not installed
    error "jsdom#array-equal" not installed
    error "babel-jest#babel-preset-jest" not installed
    error "@babel/template#babylon" not installed
    error "jest-resolve#browser-resolve" not installed
    error "fb-watchman#bser" not installed
    error "jest-runtime#yargs#camelcase" not installed
    error "nomnom#colors" not installed
    error "jsdom#content-type-parser" not installed
    error "jsdom#cssom" not installed
    error "jsdom#cssstyle" not installed
    error "jest-diff#diff" not installed
    error "randexp#discontinuous-range" not installed
    error "jsdom#escodegen" not installed
    error "sane#exec-sh" not installed
    error "jest-jasmine2#expect" not installed
    error "flat-cache#del#globby" not installed
    error "istanbul-reports#handlebars" not installed
    error "jsdom#html-encoding-sniffer" not installed
    error "websocket-driver#http-parser-js" not installed
    error "jest-validate#leven" not installed
    error "jsdom#nwmatcher" not installed
    error "restore-cursor#onetime" not installed
    error "jest-runtime#yargs#os-locale" not installed
    error "jest-jasmine2#p-cancelable" not installed
    error "jsdom#parse5" not installed
    error "jest-runtime#yargs#read-pkg-up" not installed
    error "jest-cli#read-pkg-up#read-pkg" not installed
    error "randexp#ret" not installed
    error "jest-runtime#yargs#string-width" not installed
    error "istanbul-lib-report#supports-color" not installed
    error "jsdom#symbol-tree" not installed
    error "babel-plugin-istanbul#test-exclude" not installed
    error "nomnom#underscore" not installed
    error "original#url-parse" not installed
    error "sane#walker" not installed
    error "sane#watch" not installed
    error "websocket-driver#websocket-extensions" not installed
    error "jsdom#whatwg-encoding" not installed
    error "jsdom#whatwg-url" not installed
    error "jest-runtime#yargs#which-module" not installed
    error "jsdom#xml-name-validator" not installed
    error "flat-cache#globby#arrify" not installed
    error "handlebars#async" not installed
    error "babel-preset-jest#babel-plugin-jest-hoist" not installed
    error "append-transform#default-require-extensions" not installed
    error "escodegen#esprima" not installed
    error "istanbul-lib-report#supports-color#has-flag" not installed
    error "jest-cli#read-pkg#load-json-file" not installed
    error "walker#makeerror" not installed
    error "exec-sh#merge" not installed
    error "bser#node-int64" not installed
    error "handlebars#optimist" not installed
    error "jest-cli#read-pkg#path-type" not installed
    error "original#url-parse#querystringify" not installed
    error "jest-runtime#read-pkg-up#read-pkg" not installed
    error "browser-resolve#resolve" not installed
    error "handlebars#source-map" not installed
    error "jest-runtime#string-width#strip-ansi" not installed
    error "jsdom#whatwg-url#tr46" not installed
    error "jsdom#whatwg-url#webidl-conversions" not installed
    error "jest-runtime#strip-ansi#ansi-regex" not installed
    error "jest-runtime#read-pkg#load-json-file" not installed
    error "optimist#minimist" not installed
    error "jest-runtime#read-pkg#path-type" not installed
    error "jest-cli#load-json-file#pify" not installed
    error "jest-cli#path-type#pify" not installed
    error "default-require-extensions#strip-bom" not installed
    error "makeerror#tmpl" not installed
    error "optimist#wordwrap" not installed
    error Found 336 errors.
    info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.

But why I do a 'yarn list' I get a very long list of modules and if I check some modules from the 'yarn check' error list, they are there.

_Running v2.4.3  on Debian 9_

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by renatolond** [comment]
> I notices that when I did a 'yarn check' emoji-mart was not installed, so I installed it with 'yarn add emoji-mart'

Mastodon does not use the default emoji-mart, but a modified version that lives in https://github.com/gargron/emoji-mart/tree/build
If you yarn picked up the standard version, it would probably have some weird effects indeed.

Maybe somehow the first `yarn check` didn't detect the cloned version of emoji-mart?
If you do 

```
yarn cache clear
yarn install --pure-lockfile
RAILS_ENV=production bundle exec rails assets:precompile
```

Does it fail?

**Comment by jeroenpraat** [comment]
@renatolond Thanks for your reply.

What you suggest is what I tried earlier (it's 'yarn cache clean' btw). Unfortunately still the same number of errors after another try. Note that emoji-mart is not in that list of errors.

**Comment by jeroenpraat** [comment]
@renatolond When I do a 'yarn check --integrity --verbose' I get this (there's absolutely wrong something here):

```
yarn check v1.7.0
verbose 0.764 Checking for configuration file "/home/mastodon/live/.npmrc".
verbose 0.765 Checking for configuration file "/home/mastodon/.npmrc".
verbose 0.765 Checking for configuration file "/usr/etc/npmrc".
verbose 0.766 Checking for configuration file "/home/mastodon/live/.npmrc".
verbose 0.766 Checking for configuration file "/home/mastodon/.npmrc".
verbose 0.767 Checking for configuration file "/home/.npmrc".
verbose 0.768 Checking for configuration file "/home/mastodon/live/.yarnrc".
verbose 0.768 Checking for configuration file "/home/mastodon/.yarnrc".
verbose 0.768 Found configuration file "/home/mastodon/.yarnrc".
verbose 0.768 Checking for configuration file "/usr/etc/yarnrc".
verbose 0.769 Checking for configuration file "/home/mastodon/live/.yarnrc".
verbose 0.769 Checking for configuration file "/home/mastodon/.yarnrc".
verbose 0.769 Found configuration file "/home/mastodon/.yarnrc".
verbose 0.77 Checking for configuration file "/home/.yarnrc".
verbose 0.773 current time: 2018-07-24T16:38:22.002Z
warning Integrity check: Flags don't match
error Integrity check failed
verbose 0.957 Error: Found 1 errors.
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:243:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:272:123)
    at /usr/share/yarn/lib/cli.js:60272:13
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:98:30)
    at /usr/share/yarn/lib/cli.js:109:13
    at <anonymous>
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

**Comment by jeroenpraat** [comment]
The problem here is that before the precompile _all yarn checks perform okay_, but after precompiling I receive the above errors.

**Comment by ThibG** [comment]
The assets precompile step runs yarn through railties, which currently overrides yarn's settings, installing only production dependencies (and uninstalling all other ones)

**Comment by jeroenpraat** [comment]
@ThibG So do you try to say that this is normal behavior?

**Comment by saper** [comment]
That would look like that....

**Comment by Gargron** [comment]
Yes, unfortunately the webpacker gem does that in the assets:precompile step for (imo) no good reason.

**Comment by jeroenpraat** [comment]
OK, than I'm going to close this one. Thanks for your replies.
