### ISSUE TITLE
As a user, when I post video content, I want poster frames to show until the user plays or seeks #Enhancement #Feature #Idea

### ISSUE THREAD

**Issue by ldexterldesign** [tootsuite/mastodon#8062]
https://mastodon.social/@ldexterldesign/100426716958046887
https://twitter.com/ldexterldesign/status/1021545588414996480
https://streamable.com/p1284

Hi all,

Hope you're well

Thanks for software

As a user, when I post video content, I want poster frames to show until the user plays or seeks #Enhancement #Feature #Idea

Currently, the video embed user experience isn't as good as it could be

Screen shot:

<img width="1440" alt="screen shot 2018-07-24 at 02 34 18" src="https://user-images.githubusercontent.com/1715809/43110186-d7255bbc-8eea-11e8-8c00-9411a4faf32f.png">

<img width="1440" alt="screen shot 2018-07-24 at 02 38 04" src="https://user-images.githubusercontent.com/1715809/43110205-ec1446b4-8eea-11e8-88d7-971cfcdc6a99.png">

https://streamable.com/p1284 appears to be offering a poster so can we use it?:

If yes, is this a feature we can extend to other videos that include a poster attribute[e]

If you're reading this and agree please up-vote and/or reply +1

Let me know if you have any issues - happy to help

Hope this is clear/useful and to hear back

Keep up good work!

Yours faithfully

[e] https://devdocs.io/html/attributes#poster-attribute

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment]
Afaik, this has nothing to do with the `poster` attribute of HTML5's `video`: indeed, there is no video rendered yet, but a div with some buttons (that would open an iframe for the video if clicked). Now, it is supposed to show a preview, but for some reason it didn't get the one provided by the content provider. I will look into that.

**Comment by ThibG** [comment]
Ok, this is because the URL uses the shorthand “//” instead of defining the URL scheme explicitly (`//images.streamable.com/east/image/p1284.jpg?height=100`).
I'm not 100% sure how we should handle that.

**Comment by Gargron** [comment]
@ThibG No need to bother with join, there is no scenario under which we would prefer // to become http instead of https. A simple replace should do the trick.

**Comment by ThibG** [comment]
What about relative URLs? I'm not sure they're forbidden.

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
Hi all,

Keep up great work!

Thanks
