### ISSUE TITLE
server software changes not picked up by Mastodon instances

### ISSUE THREAD

**Issue by VVelox** [tootsuite/mastodon#8063]
Recently in a situation where ruby has massive build reproducability issues with some things used by Mastodon on FreeBSD. Because of this I had to move from Mastodon to Friendica for my own personal domain.

The move went well as well as readding adding my old contact. Now while neither my user or domain name changed, communication to Mastodon instances became one way. I had no issue seeing their updates, but they would not see mine.

On top of that Mastodon appears to be caching stuff instead of doing new lookups. When a friend on one of the servers I knew some one on already tried to add me, my profile came up as https://$domain/@$user instead of how Friendica returns it, which is https://$domain/profile/$user .

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
Mastodon does not support downgrading from ActivityPub to OStatus protocols, only upgrading from OStatus to ActivityPub.

**Comment by Gargron** [comment]
Yeah, this is a, uhh, not a use case that we can provide support for.
