### ISSUE TITLE
Use the @context that is appropriate for the response

### ISSUE THREAD

**Issue by aschrijver** [tootsuite/mastodon#8078]
While looking at the json-ld responses of various requests to `mastodon.technology`, which I recently joined, and noticed that each and every response includes the full `@context` definition with all Mastodon extensions, regardless of what is in the response body.

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
      "sensitive": "as:sensitive",
      "movedTo": "as:movedTo",
      "Hashtag": "as:Hashtag",
      "ostatus": "http://ostatus.org#",
      "atomUri": "ostatus:atomUri",
      "inReplyToAtomUri": "ostatus:inReplyToAtomUri",
      "conversation": "ostatus:conversation",
      "toot": "http://joinmastodon.org/ns#",
      "Emoji": "toot:Emoji",
      "focalPoint": {
        "@container": "@list",
        "@id": "toot:focalPoint"
      },
      "featured": "toot:featured",
      "schema": "http://schema.org#",
      "PropertyValue": "schema:PropertyValue",
      "value": "schema:value"
    }
  ],
  "id": "https://mastodon.technology/users/rapnie/followers",
  "type": "OrderedCollection",
  "totalItems": 7,
  "first": "https://mastodon.technology/users/rapnie/followers?page=1"
}
```

The above message could just as well be written as:

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "https://mastodon.technology/users/rapnie/followers",
  "type": "OrderedCollection",
  "totalItems": 7,
  "first": "https://mastodon.technology/users/rapnie/followers?page=1"
}
```

While the `@context` + extensions does not contain that many bytes, it could add up on busy servers. So this feature request is for having contexts that are applicable to the response that is returned, and do not contain extensions that are never returned.

**Edi**t: I have since heard from @nightpool on Mastodon that implementing this would be hard, because:

>there's no real principle way for us to signal to the serializer which context we need, without writing a lot of fragile special case logic that would needlessly complicate the code-base. 
>
>The best I can see us doing would be collecting it all into a single context document, but even that comes with a lot of bandwidth/centralization tradeoffs that I don't really see as feasible for us.

Could be indeed hard to implement in Python - I am not familiar with it - but I don't see why it would lead to 'lot of fragile special case logic'. As I see it for every type of response the `@context` could be more or less fixed (but different wrt to another AP entity type).

So I decided to file this issue anyway.. feel free to close if this is too hard to implement in any case.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by puckipedia** [comment]
I would still vote to have an endpoint per server like `https://example.com/context`, then do `"@context": ["https://www.w3.org/ns/activitystreams", "https://example.com/context"]`. This keeps the same semantics, but less bandwidth per request, assuming that people cache the context, while keeping decentralization.

**Comment by Gargron** [comment]
@puckipedia That's super wrong though because it means "featured" =/= "featured" since the namespaces are different. If anything it's gotta be hosted on joinmastodon.org for real.

**Comment by nightpool** [comment]
@gargron the idea is that the context document would all just list the same
namespace.

I don't think the bandwidth vs latency tradeoffs make sense though, even
with aggressive caching it would be pretty weird during upgrades.
