### ISSUE TITLE
I Need Control Over My Deleted Mastodon.Social Account (Which Is Still Showing My Old Avatar)

### ISSUE THREAD

**Issue by davidpgil** [tootsuite/mastodon#8079]
I want to have access to my mastodon.social account after it was "deleted" several months ago before all of the migration features were added. This is what I want to do in order of priority:

1) remove my old avatar which clearly shows my face. I want to remove that photo of myself because of privacy related reasons.
2) I want to point my old followers on that account to my new account using the migration method.
3) I want my mastodon.social account to be removed from searches eventually. The way the account was deleted before I believe my not be compatible with being eventually completely gone and deleted.

I know this is a personal request to have only my account deleted and not some global bug, but I am at a loss as to what I can do to fix this. I feel like my avatar image is being forcefully shown to the world without my consent and I find this upsetting. Can I please get help with this issue?

My account was davidpgil@mastodon.social here ... if you do a serach for "davidpgil" you will find the account.

Thank you in advance for your attention and assitance.

**Comment by Cassolotl** [comment]
If your details are not being properly deleted this seems like a data protection issue.

**Comment by davidpgil** [comment]
At the VERY least, I want my old profile pic to be removed.

**Comment by trwnh** [comment]
![image](https://user-images.githubusercontent.com/10606431/43348937-4ef9218a-91c2-11e8-95d5-08b3a76796ec.png)

Your information isn't showing up at all, @davidpgil -- which instance are you using to search for "davidpgil"? And if it was deleted, then there's no account to "have access to" anymore. It sounds like whichever instance you're on hasn't updated its cache. I think there's a rake task to remove accounts that no longer exist -- according to https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/List-of-Rake-tasks.md#misc you should have your admin run the mastodon:maintenance:purge_removed_accounts task to resolve this. Depending on whether the task is scheduled for automatic intervals, your issue may resolve itself.

**Comment by davidpgil** [comment]
My main account is davidpgil@chaos.social ... When I do a search for "davidpgil", I see the follwoing options... 
![image](https://user-images.githubusercontent.com/41744832/43349258-98935c2a-91cc-11e8-82e2-2fcfee473940.png)
The account I want to fix/remove is on the bottom.

**Comment by Gargron** [comment]
I have manually re-sent the actor deletion payload to every single server known to mastodon.social. Hopefully this resolves your issue. You were unlucky to have deleted your account before full account deletion was possible.

**Comment by davidpgil** [comment]
Thank you very much @Gargron I really appreciate it!
