### ISSUE TITLE
Very large mammoth image on /about

### ISSUE THREAD

**Issue by mbrubeck** [tootsuite/mastodon#808]
The [default landing page](https://mastodon.social/about) for non-logged in users includes a 1400×1488-pixel image of a mastodon, with a download size of just over 1 MB.  For instances under heavy load from new users, this could use a pretty large amount of bandwidth. It also makes the landing page take a long time to load for users on slow networks (which in turn may tie up server connections).

Since the image is usually scaled down to less than 300px (exact size depends on font size, zoom settings, etc.), it could be shrunk to a fraction of its current size without affecting quality for most users.  Optionally, responsive images could be used to serve higher-resolution versions where appropriate.

**Comment by dalanmiller** [comment]
Don't have time to make a PR right now, but here's one compressed with [google/guetzli](https://github.com/google/guetzli), ~1.0MB => 157KB

![fluffy-elephant-friend_g](https://cloud.githubusercontent.com/assets/863286/24636031/22f0ab04-188c-11e7-9447-1f74bc9608c9.jpg)

**Comment by mbrubeck** [comment]
Unfortunately, JPEG doesn't preserve the alpha channel.

**Comment by dalanmiller** [comment]
59KB

![fluffy-elephant-friend-fs8-fs8](https://cloud.githubusercontent.com/assets/863286/24636368/a16c67be-188e-11e7-9b14-c19054621019.png)
