### ISSUE TITLE
Do not clear tootbox when adding a reply

### ISSUE THREAD

**Issue by oct2pus** [tootsuite/mastodon#8086]
Multiple times I have realized I meant to reply to a person or myself in a thread but then clicked reply and my message had been deleted, forcing me to retype it.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by saper** [comment]
It seems to be a duplicate of https://github.com/tootsuite/mastodon/issues/6249

**Comment by oct2pus** [comment]
ack, clearly I didn't look hard enough
