### ISSUE TITLE
Problem with own ActivityPub implementation

### ISSUE THREAD

**Issue by waweic** [tootsuite/mastodon#8094]
I try to follow Gargrons tutorial on how to implement a basic ActivityPub server.
I now do have a problem for two days now, that I can't get resolved, because my side looks absolute correct to me. 
It says that the public key verification wouldn't work.
I have put everything into a [gist](https://gist.github.com/waweic/2b2f1ad8221a738aa7df05a519d80ca3).
It would be extremely nice if someone with knowledge in that area could have a look at this.

**Comment by Gargron** [comment]
I get a network timeout when trying to fetch https://testing1.ism.rocks/users/waweic from my browser

**Comment by nightpool** [comment]
"Running on http://127.0.0.1:5000/"

the flask app is running on the loopback interface, which means it's not
accessible from the outside world. it should be running on 0.0.0.0 instead.

**Comment by nightpool** [comment]
nevermind, I see that you're using nginx. still, I don't seem to be able to access the application from outside

**Comment by waweic** [comment]
Sorry Guys, this was just running on my laptop on the [HaxoGreen](haxogreen.lu), so it wasn't available because my laptop was turned off. It should be back online by now.

**Comment by rhaamo** [comment]
I tried this a few days ago and got the same issue.
The blog post doesn't seems fixed but the issue is with the webfinger.
It doesn't returns the right ```Content-Type``` so mastodon is crying.
Fixed it with this ugly thing in nginx:
```
        location / {
                default_type application/json;
                root /srv/www/ap.dev.whatever/;
        }
```

**Comment by waweic** [comment]
Thanks for your advice, it worked! I just had to add two lines in my flask script.
