### ISSUE TITLE
More community management needed

### ISSUE THREAD

**Issue by nevillepark** [tootsuite/mastodon#811]
With the surge in new users, I think there ought to be more people reviewing reported toots. I've seen quite a few trolls on the timeline! So

- who is doing moderation/community management now?
- could there be more of them, please?

**Comment by lezarius** [comment]
all instance have one admin. Instance is the moderaton. If you want to have a nice place without troll go to do you own instance with rule "no troll".

**Comment by 0xa** [comment]
User groups with ACL would be great through, so we could have multiple admins and/or a moderation team with access to reports.

**Comment by nevillepark** [comment]
@lezarius OK, by "trolling" I mean people blatantly breaking rules to get a rise out of people—racism, sexism, etc.

**Comment by lezarius** [comment]
You can mute people from you instance witch.town do this. Witch.town is a safeplace for LBGT+ people =D

**Comment by matunixe** [comment]
Moderators is really needed here! 👋

**Comment by James-Firth** [comment]
I think a combination of these things is needed. As @lezarius pointed out, one can join a community with similar values as oneself. However has @0xa said I think it'd be great to have a moderation team as communities have the potential to get quite large!

**Comment by Gargron** [comment]
Implemented in #5635
