### ISSUE TITLE
NSFW shade status are not saved after closing an image.

### ISSUE THREAD

**Issue by kyrahabattoir** [tootsuite/mastodon#8124]
When scrolling the federated timeline for a while, if you click an image to enlarge it and then close it back up, when the timeline refreshes, all the NSFW shades that you removed are back in place.

It's disorienting to browse like this as sometimes you don't know where you where anymore and as a result I'm now using a browser extension that removes all NSFW shades. At least until this gets fixed.

It's also not consistent with the normal behavior you get when you are at the top of the federated page, where the shades you removed are kept removed.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by fwenzel** [comment]
"a browser extension that removes all NSFW shades" why don't you just flip the switch in the settings?

**Comment by kyrahabattoir** [comment]
I know I know but look at the date.

I just forgot to close this.
