### ISSUE TITLE
Show remote image after "mastodon:media:remove_remote"

### ISSUE THREAD

**Issue by Dryusdan** [tootsuite/mastodon#8131]
Hello
Actually, Mastodon need lot of disk space and I run this command `bundle exec rake mastodon:media:remove_remote` each day for delete image 3 days older (because mastodon is an realtime microbloging plateforme). But, some people retoot old toot and image are broken.
So, when we use this rake task, is it possible to modify old toots to show them the distant image and not the local image? Or redownload image? 

Regards :)

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by renatolond** [comment]
I thought this was already the case, for older images that were removed, they were refetched as long as the domain where they come from do not has "reject media" set?

Do you have that for all older images?

**Comment by Dryusdan** [comment]
I have that for all older image than 3 days ago :/

**Comment by renatolond** [comment]
Hm, in my instance what I have is that for older images I often have a link like this one:
`https://instance.com/media_proxy/<number>/original`, do you have something similar if you open the toot using the web interface?

**Comment by renatolond** [comment]
Hm, I did a similar test here and I couldn't reproduce it here. I got a media_attachment that had been removed recently:
```
MediaAttachment.where.not(remote_url: '').where(file_file_name: nil).where('created_at < ?', 7.days.ago).where('created_at > ?', 8.days.ago).first
```
Which returned something like
`#<MediaAttachment status_id: ..., file_file_name: nil, file_content_type: nil, file_file_size: nil, file_updated_at: nil, remote_url:  ...`
And then I got the status id which it belonged to, and visited in the web interface using `https://instance/web/statuses/status_id`

And it fetched the image again:
```
#<MediaAttachment status_id: ..., file_file_name: "... .png", file_content_type: "image/png", file_file_size: 20040, file_updated_at: "2018-08-07 10:31:24",
```

I noticed you're running glitch-soc, could it be an issue of the glitch-soc flavor?

**Comment by Dryusdan** [comment]
Ho, yes, I don't think of Glitch-soc theme. I open an issue 

Thank :)
