### ISSUE TITLE
Media descriptions don't work for video's (incl. animated GIF's)

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#8132]
When adding media descriptions for the visually impaired for video's (incl. animated GIF's) the text is not displayed on hover and there is also no alt-text in the page source. I understand this works different, but it is not completely [impossible](https://www.w3schools.com/tags/tag_video.asp) (although I'm wondering if this is understood by screen readers).

So there are two options here:

1. remove the option to add media descriptions to video's

2. find out if screen readers support text in <video> tags and if so add the media description to video's like this:

```html
<video src="https://instance.tld/…/video.mp4" poster="https://instance.tld/…/video..png" preload="none" loop="" role="button" tabindex="0" width="…" height="…">
Media description here.
</video>
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by renatolond** [comment]
The alt is added as an "aria-label" when it's videos/gifs, as in this example:

https://masto.donte.com.br/@renatolond/100491543760118568

```
<video class="media-gallery__item-gifv-thumbnail" aria-label="A gif of Spooky, the cat, lying down on my computer" role="application" src="https://images.masto.donte.com.br/media_attachments/files/000/544/084/original/4bdcc9cbe4c7c51e.mp4" loop=""></video>
```

**Comment by jeroenpraat** [comment]
@renatolond I didn't noticed that on animated GIF's it uses aria, but it doesn't use that for regular video's. Like this: https://todon.nl/@jeroenpraat/100497658314880348

Also animated GIF's don't show text on hover (on my desktop at least).

**Comment by jeroenpraat** [comment]
So thing to fix are now:

- add aria-label to regular video's
- fix text on hover for both animated video's and regular video's

**Comment by dracos** [comment]
The alternative text was not being passed by the template to the JavaScript. I have submitted a PR at #8416 that fixes that, plus adds title attribute for hover text.q=

**Comment by jeroenpraat** [comment]
@dracos Thank you! :smiley:
