### ISSUE TITLE
Translation issue : Weblate is down

### ISSUE THREAD

**Issue by trebmuh** [tootsuite/mastodon#8134]
https://weblate.joinmastodon.org/ is down here with an error telling me that:

>the connexion isn't secured and because the website is HSTS, then there is no way to add an exception for the certificate.

* * * *

- [v] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jeroenpraat** [comment]
+1 The certificate is expired. I reported this on various places (like on https://source.joinmastodon.org, but that has now a 500 error), but @Gargron didn't fixed it yet or he didn't noticed it yet.

**Comment by trebmuh** [comment]
@Gargron : ping

**Comment by dadosch** [comment]
Its up again

**Comment by trebmuh** [comment]
Nice. Thanks to anyone involved in that :+1:
