### ISSUE TITLE
Text cursor can go over the usual text area

### ISSUE THREAD

**Issue by ariasuni** [tootsuite/mastodon#8138]
Here you can see my cursor next to the emoji picker icon:
![screenshot_20180807_155346](https://user-images.githubusercontent.com/2446451/43780349-a7fcd164-9a5a-11e8-8225-c2944ebb4ebf.png)

And here with a selection:
![screenshot_20180807_155426](https://user-images.githubusercontent.com/2446451/43780494-0323a5fe-9a5b-11e8-81c0-81dcb914a7fd.png)

The issue was mainly occurring to me when writing a word at the limit of the text area then hitting space; then the cursor seem to disappear (and is only visible as shown in my screenshot because there is text afterwards).

The problem described on the last paragraph only happen on Firefox (Developer Edition 62) though.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
This seems to be a Firefox bug with padding within a `textarea` element. I wonder how this could be worked around.

**Comment by ariasuni** [comment]
Note that the problem you see on the screenshots can be reproduced on Chrome

**Comment by ThibG** [comment]
Hm, I couldn't reproduce it with chromium.

**Comment by ariasuni** [comment]
Here’s what I was able to reproduce today on Chromium:
![screenshot_20180808_142132](https://user-images.githubusercontent.com/2446451/43855104-f7ffd130-9b44-11e8-915d-f56a6c8dcb52.png)
![screenshot_20180808_142154](https://user-images.githubusercontent.com/2446451/43855105-f8235718-9b44-11e8-8438-92b7d60d774b.png)
![screenshot_20180808_142506](https://user-images.githubusercontent.com/2446451/43855106-f844134a-9b44-11e8-8f20-7f82f228c32c.png)

On the last screenshot, you can see that the selection go over the last character of the second line (there cannot be more characters on the line) which is a bit weird.

**Comment by ThibG** [comment]
Ok, I can reproduce it, but this seems to be a browser issue. The caret disappearing also appears even here in github.
I'm not too sure how we could work around that. Maybe wrap the textarea in a div instead of directly messing with its padding?

**Comment by ariasuni** [comment]
I made some tests and the disappearing caret seems indeed to be a problem with Firefox when a textarea has some padding.

**Comment by ariasuni** [comment]
I made [a bug report on Mozilla’s side for the disappearing cursor issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1482455).

**Comment by ariasuni** [comment]
I don’t have this issue anymore, in neither Firefox or Chromium so I’m closing this.
