### ISSUE TITLE
As a user, when I search (hashtags), I want better support for substrings #Enhancement

### ISSUE THREAD

**Issue by ldexterldesign** [tootsuite/mastodon#8144]
Hi all,

Hope you're well

Thanks for software

As title

When I create these two hashtags I'm only able to see one in search results:

yblbnyvbgskjsss_ldl
ldl_yblbnyvbgskjsss

I believe the end user should see both hashtag results

Screen shots:

<img width="1440" alt="screen shot 2018-08-08 at 16 45 48" src="https://user-images.githubusercontent.com/1715809/43844694-a04538c8-9b2a-11e8-997b-3e4ddf213049.png">

<img width="1440" alt="screen shot 2018-08-08 at 16 46 00" src="https://user-images.githubusercontent.com/1715809/43844697-a227f87e-9b2a-11e8-911c-a704cd93268e.png">

If you're reading this and agree please up-vote and/or reply +1

Conversely, if you disagree with me I'd love to know why?

Let me know if you have any issues - happy to help

Hope this is clear/useful and to hear back

Keep up great work!

Yours faithfully

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
I'm not sure why "yblbnyvbgskjsss_ldl" and "ldl_yblbnyvbgskjsss" should be considered the same string when they're clearly different. In this case, are "ldl" and "yblbnyvbgskjsss" meant to be words? Are you suggesting that "_" be used as a delimiter for words in hashtags? This would become problematic because, aside from increasing complexity and search space, it may also change the semantic meaning. Additionally, many hashtags don't use underscores, especially when using the Latin alphabet (or any other alphabet with parseable word barriers).

**Comment by ldexterldesign** [comment]
Thanks for reply

> I'm not sure why "yblbnyvbgskjsss_ldl" and "ldl_yblbnyvbgskjsss" should be considered the same string when they're clearly different

True, technically they are different strings but contain the same meaning. Just like "yblbnyvbgskjsssldl" and "yblbnyvbgskjsssLdl" are different strings but have the same meaning. Do users care most about meaning or string syntax (rhetorical question).

> Are you suggesting that "_" be used as a delimiter for words in hashtags?

Ultimately, yes, but whether that's for the search suggestions or the search results or both I think that would be a useful debate

For example, if I use the search query "browsersupport" I expect to see the following (tag) search suggestions or else have all of the posts using these tags to appear in results:

browser
browserSupport
browser_support
browsersupport
support
supportBrowser
support_browser
supportbrowser

Currently, the tags with underscores are ignored altogether but underscores are a really popular way of delimiting words in strings just like camelCase

Disclaimer: I want to create specific/constrained tag vocabularies (e.g. "ldl_foo" or "foo_ldl") so I can filter my own posts containing "foo" from everyone else's, but not have my tags excluded from general searches for "foo"

Hope this is clear and to hear back

Cheers

**Comment by ldexterldesign** [comment]
I appreciate search accuracy as much as the next person. However, I would say Twitter is very liberal with search results and it can be noisy but I almost always find some valuable results. Conversely, with Mastodon I often get about three results.

Mastodon search is unrewarding a lot of the time so this is a potential way to open things up a bit

Personally, I'd rather scroll through a few pages of results and find something useful than lose faith in search altogether which is what's starting to happen for me in Mastodon.

# I read there are privacy issues connected to findability on Mastodon (feel free to link) but I think if someone goes to the trouble of creating tags for their content then they want their content to be discovered

Cheers

**Comment by ldexterldesign** [comment]
BUMP

**Comment by PubliqPhirm** [comment]
The biggest findability gain, in my opinion, is the ability to merge tags so that both the singular and plural form show up in the search for either.  #dog and #dogs should return the same result.

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
https://mastodon.social/@ldexterldesign/102572596960024140

FYI I have no idea when this feature deployed but it largely solves my use case

Thanks!

**Comment by ldexterldesign** [comment]
FYI https://mastodon.social/@Gargron/102572084229929811
