### ISSUE TITLE
URL handling doesn't work reliably?

### ISSUE THREAD

**Issue by bellabie** [tootsuite/mastodon#8148]
Forgive me for I do not have the words to correctly express this issue.
In the following toot, I linked to the website `ticas.org/posd/home`
https://mastodon.social/@b_cavello/100518924883527639

Although the tld `.org` is a common one, Mastodon does not render the text as a link. (This can be especially an issue on mobile devices where the fallback copy/paste dynamic is more limiting.)

I'm wondering if there's some kind of regex or something that could be used to look for common tlds directly following a `.` even if they don't have the `https://` or `http://` in front.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
It's a decision to not try to guess URLs unless they start appropriately with http or https, so it's not a bug. The benefit is being able to talk about website (e.g. example.com) without them turning into links.
