### ISSUE TITLE
Add a cancel in warning container

### ISSUE THREAD

**Issue by rsbondi** [tootsuite/mastodon#8160]
Similar to when you reply to someone, the reply container has a cancel X in the header.  I think this feature would be useful for the DM warning, when you first initiate a DM, either by selecting from the context menu under the user, or selecting in the comment box and adding a mention, you are stuck with the warning(I assume there may be state related items to consider?).  In mobile this is not a problem, you can hit `home`, but on a desktop you need to start a random reply to someone and then cancel that, a bit awkward of a UX.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
you can "cancel" it (remove the warning) by just selecting a different
privacy type?

**Comment by rsbondi** [comment]
That works @nightpool just not intuitive, but thanks for the tip.
