### ISSUE TITLE
Option to whitelist email domains

### ISSUE THREAD

**Issue by Dr-Syn** [tootsuite/mastodon#817]
The .env.production configuration file contains a space to blacklist email domains to forbid them from signing up to an instance.

For those persons who would like to run an instance associated with their specific organization, a whitelist might be more helpful here - so only those who have email accounts with that organization can be permitted to register.

Would this be a feasible addition?

**Comment by nicseve** [comment]
Can anyone show a working example of this? I can't seem to get my whitelist to work correctly. Thank you!
