### ISSUE TITLE
Atom and RSS feeds contain different statuses

### ISSUE THREAD

**Issue by rixx** [tootsuite/mastodon#8178]
Mastodon's user atom feeds contain boosts and replies, while the RSS feeds contain only new statuses. I'd expect the two to behave the same. If separate feeds for with/without boosts and replies were to be provided, I'd expect them at different URLs (either with different paths, or queryparams like ``?include=boosts&include=replies``, not under different protocols.

(I'd argue that by default, boosts and replies do not belong in the feed, and that the RSS behaviour is better, but above all the two feeds should contain the same statuses.)
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by BjarniRunar** [comment]
I for one am SUPER HAPPY to know that the Atom feed contains boosts and replies. I was just scratching my head over the fact that the Activitypub export archive is missing those things, and I would like to archive those too.

So if people do decide to make the feeds the same (I don't quite get why the feeds aren't allowed to be different?), please consider this a vote for a parameter that keeps the current behaviour. Thanks for Mastodon!

**Comment by BjarniRunar** [comment]
Hi @nightpool, thanks for the reply. My archive (as downloaded from mastodon.xyz) had almost no content except in the file `outbox.json`,

    $ cat outbox.json |python -m json.tool |grep '"actor"' |grep -c -v HerraBRE
    0

The only actor in that file is me, and I can see my comments in recent threads but nobody else's. Should I file an issue for this?

**Comment by nightpool** [comment]
I think there's been some confusion. The data export includes replies that *you* make to other people's posts. The RSS feed does not. It does not include replies other people make to your post. it *does* include boosts that you make, but it only references the external status—it doesn't include it.

Here is what a boost looks like in the data export:

```json
    {
      "id": "https://glitch.social/users/nightpool/statuses/99185926035368124/activity",
      "type": "Announce",
      "actor": "https://glitch.social/users/nightpool",
      "published": "2017-12-16T20:45:23Z",
      "to": [
        "https://www.w3.org/ns/activitystreams#Public"
      ],
      "cc": [
        "https://cybre.space/users/nightpool",
        "https://glitch.social/users/nightpool/followers"
      ],
      "object": "https://cybre.space/users/nightpool/statuses/99185923013326716",
      "atomUri": "https://glitch.social/users/nightpool/statuses/99185926035368124/activity"
    },
```


Anyway, if you think Announce's should be rendered recursively in the data export, that probably makes sense. but they're definitely already included.

**Comment by BjarniRunar** [comment]
That's clear, and consistent, thank you for clarifying.

Regarding the archive - I want my personal archive to include the full conversations and interactions I've participated in (favs and boosts, replies and mentions - not just things I said) - basically all the things I see in my Notifications column. If I can't use my archive to recreate what I see when I log on to Mastodon (minus some avatars etc. and the public timelines), it's very incomplete IMO.

Given your clarification regarding the Atom feed, currently it looks like there's no way to create such an archive, short of writing a recursive scraper - not something non-programmer users will be able to do.
