### ISSUE TITLE
Add bot TL

### ISSUE THREAD

**Issue by jusdepatate** [tootsuite/mastodon#8184]
Why not adding a second Timeline for bots ?
Then mastodon will have a user public timeline, bot public timeline and a followed user timeline and a followed bots timeline, or something like this

**Comment by JaredLethal** [comment]
better have an option to hide bots from regular TLs, IMO

**Comment by MyNameIsTroll** [comment]
Perhaps an option in the existing column to hide/show only the bots might suffice.

**Comment by Tagadda** [comment]
@jusdepatate You can create a list containing bots, then pin this list as a column.

**Comment by jusdepatate** [comment]
Ok thanks ^^
