### ISSUE TITLE
media:remove_remote is too heavy

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#8187]
Since #7678 , if you run the media:remove_remote task in an environment that does not run for a long time, I think that there are cases where many jobs are added to Sidekiq and the instance may become malfunctioning.

In my instance I use Swift Object Storage to store media.

when execute the media:remove_remote task at last month, more than 30,000 jobs were added to Sidekiq at a time.

<img width="1080" alt="_2018-07-08_9_20_03" src="https://user-images.githubusercontent.com/766076/44043775-a3741b12-9f5e-11e8-9e2d-4e3a529c82da.png">

Then Object Storage returns a 503 error, most of the jobs was gone on Retry as is.

<img width="1079" alt="2018-07-08 9 24 07" src="https://user-images.githubusercontent.com/766076/44043802-b1b3e22a-9f5e-11e8-9b11-532752e11ea3.png">

At that time I could not post images to Mastodon.

After that, it waited for all jobs moved to the Retry-tab over an hour, cleared all the retries with rails console.

The next image is a comparison with the number of ordinary jobs.

<img width="1014" alt="2018-08-03 12 48 24" src="https://user-images.githubusercontent.com/766076/44043831-c54302a8-9f5e-11e8-8c41-8bf76154105d.png">

I think that there are other instances that do not routinely execute the media:remove_remote task.

Is it possible to insert wait processing according to the environment into this task, or make it possible to select the former format without using Sidekiq?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment]
I think the jobs should be moved to a new low-priority queue, but that would be a new migration hazard for people starting sidekiq without adding the new queue on the command line.
