### ISSUE TITLE
Implement Web Share Target API

### ISSUE THREAD

**Issue by davmillar** [tootsuite/mastodon#8188]
Using the spec at https://wicg.github.io/web-share-target/ allow the progressive web app to handle shares from other apps.

This is currently implemented with a flag in Desktop Chrome and has a demo page at https://wicg.github.io/web-share-target/demos/sharetarget.html that can be used to try it. Once the requisite flags are enabled and the app is added to Chrome, it appears like this when navigator.share invokes the GUI:

![image](https://user-images.githubusercontent.com/576958/44048481-090fa1fc-9ef7-11e8-884d-c40476484c4e.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Afaik it's already implemented.

**Comment by davmillar** [comment]
D'oh, sorry, only searched open issues. I'll debug from my end. Sorry to waste your time!
