### ISSUE TITLE
Column width for desktop screen

### ISSUE THREAD

**Issue by bl00m** [tootsuite/mastodon#820]
Hi, 
I read somewhere (#711)  that the column being fixed to 330px was an optimal choice.
 
On my screen, the column are very thin. And the whole space available at right that seems to be useless is very frustrating.
 
![mastodon1](https://cloud.githubusercontent.com/assets/12273726/24647183/23b545e8-191f-11e7-9ec0-b5f6eb5473c1.png)
 
I don't understand how it is optimal ? Personaly I can't keep it like that.
Here's how I make it look on my Firefox (I changed the column order too) : 
 
![mastodon2](https://cloud.githubusercontent.com/assets/12273726/24647344/d2977c52-191f-11e7-99e8-cf564a6156fe.png)
 
For now I'm injecting custom css to the page but I can work on stylesheets if needed.

**Comment by flyingrub** [comment]
I totally agree. I find the current width too thin and the unused space feel very weird. Also the notification at the end just makes sense to me.

**Comment by Gargron** [comment]
See #3207
