### ISSUE TITLE
PgHero shows unused indexes

### ISSUE THREAD

**Issue by gllmhyt** [tootsuite/mastodon#8204]
I'm running [v2.4.3](https://github.com/tootsuite/mastodon/releases/tag/v2.4.3) and today my server had its storage completely filled (mainly by media_attachments and preview_cards folders, maybe related to #8145) and I wasn't able to boot anymore.

As I was able to recover from it by doing some cleanup (I deleted the content of the preview_cards folder), and I began to search where I could gain some space. PgHero shows unused indexes and proposes me to remove them with a migration:

> Database Size: 6,63 Go
> 
> 13 unused index. Remove them with a migration for faster writes.
> ```
> rails g migration remove_unused_indexes
> ```
> And paste
> ```
> remove_index :tags, name: "hashtag_search_index"
> remove_index :accounts, name: "search_index"
> remove_index :admin_action_logs, name: "index_admin_action_logs_on_target_type_and_target_id"
> remove_index :lists, name: "index_lists_on_account_id"
> remove_index :oauth_applications, name: "index_oauth_applications_on_owner_id_and_owner_type"
> remove_index :reports, name: "index_reports_on_account_id"
> remove_index :reports, name: "index_reports_on_target_account_id"
> remove_index :session_activations, name: "index_session_activations_on_user_id"
> remove_index :web_push_subscriptions, name: "index_web_push_subscriptions_on_access_token_id"
> remove_index :web_push_subscriptions, name: "index_web_push_subscriptions_on_user_id"
> remove_index :identities, name: "index_identities_on_user_id"
> remove_index :invites, name: "index_invites_on_user_id"
> remove_index :report_notes, name: "index_report_notes_on_report_id"
> ```

Should it be taken into account? Are the indexes safe to remove? Thank you.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
They may be unused on your installation because of relatively small size. If a table is small enough, postgres does not choose an index for a query. You don't need to do anything about this, the indices are still useful.
