### ISSUE TITLE
PWA sometimes stops working on Android with ERR_FAILED

### ISSUE THREAD

**Issue by TriSysBusinessSoftware** [tootsuite/mastodon#8206]
I found a previous version of this error #7045 marked as "Closed" however I believe that this is still very much a problem for Google to address on Android and Chrome.
 I downloaded Jake's Super Simple Service Worker: https://github.com/jakearchibald/simple-serviceworker-tutorial and placed it on one of my HTTPS servers, added a manifest, lighthoused it, and after a bit of trial and error got it working on my Android (8.0.0) Chrome (68.0.3440.91) and added to home screen. All works fine both on and off-line however sometimes (random) when off-line, I get the attached error.

![image](https://user-images.githubusercontent.com/5684253/44135048-398157e0-a05f-11e8-9e11-cf46147c00a8.png)

**Comment by TriSysBusinessSoftware** [comment]
I posted elsewhere in the originating project: https://github.com/jakearchibald/simple-serviceworker-tutorial/issues/13

**Comment by christocarr** [comment]
I also have the same issue. Works perfectly fine on Firefox for mobile and desktop but does not work on mobile Chrome.
