### ISSUE TITLE
[UX Feature Request] Ability to toot in multiple languages

### ISSUE THREAD

**Issue by Rushyo** [tootsuite/mastodon#821]
Although it's possible to write the same message in multiple languages it costs characters, against the limit, to write a toot that can be read by multilingual users. If you have followers in 3 languages you would essentially be limited to a ~166 character limit if you wrote in each language, not to mention a bit of mental gymnastics as they'd all be different lengths, so you'd need to squeeze some in. This makes it unlikely anyone will bother.

It would be extremely useful if a toot could be written in, say, three languages and shown in the appropriate language to each user depending on their preferences, with a separate button to bring up alternative language versions. This would allow for more cross-cultural exchange on the site, rather than silos by country. Also provides for filtering by language for those who can't read English/French.

**Comment by Lomig** [comment]
This is exactly what I came here to suggest. Something like what Facebook added a few month ago : https://www.facebook.com/help/community/question/?id=10151544094843003 .
This would be greatly needed and much appreciated!

**Comment by lanodan** [comment]
It’s something friendica or GnuSocial(bad memory and too much customisation sorry) sorta have for years. (they had language detection too)
The way it was is filtering (entire) posts by their languages (CW-like) and displaying by default languages you have selected.

**Comment by Gargron** [comment]
I believe this is too advanced for the microblogging format we have chosen.
