### ISSUE TITLE
Support using read replicas

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#8215]
Send writes to master, send reads to replicas when configured.

Octopus seems unmaintained and incompatible with Rails 5, Makara seems promising.

**Comment by midhunkrishna** [comment]
@Gargron There is nothing much more than that. Should also add a readme note and a warning. 

**Readme on**: how to configure Makara, maybe something that could be added to the wiki ?.  
**Warning**: that if while deploying, if a slave is set as master in database.yml and master in place of slave, unknowingly, they will see all random postgresql errors. (But, people tend to promote slave to master, which is another side of things, see https://github.com/taskrabbit/makara/issues/155)

**Comment by Gargron** [comment]
Resolved by #8216
