### ISSUE TITLE
Show # of toot engagements next to the engagement buttons

### ISSUE THREAD

**Issue by sirjamesgray** [tootsuite/mastodon#8225]
Engagement stats (retoots, favs) are shown as metadata below toots (`detailed-status__meta` )

My suggestion is to show stats beside the buttons ( `detailed-status__button` ) 

Furthermore, this would allow stats to be shown in notifications and other areas, instead of only being visible when a user clicks to view the details of a toot.

Lastly, we should show # of replies. Currently only retoots and favs are shown. Let me know if I need to split this up into multiple issues.

<img width="1186" alt="screen shot 2018-08-16 at 1 21 15 pm" src="https://user-images.githubusercontent.com/16139439/44227383-0fdaed80-a158-11e8-884b-73a1dffd425b.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
People don't want boost/fav counts in-stream. They don't even want reply counts. Sorry but this will not end well. A different app can implement this UI.

**Comment by sirjamesgray** [comment]
very well, thanks for the response!
