### ISSUE TITLE
Language filter is not working properly

### ISSUE THREAD

**Issue by LemonAndroid** [tootsuite/mastodon#8226]
Applied the german and english language filter on knzk.me, but I still see a lot of posts in chinese.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
- Automatic language detection is not perfect, although it usually works OK for languages with distinct character sets like Japanese or Chinese
- Users can select their posting language manually

Language filters can only operate on the above data. So it's never 100% perfect, unfortunately.

**Comment by mogoh** [comment]
> Automatic language detection is not perfect, although it usually works OK for languages with distinct character sets like Japanese or Chinese

This is just not true. Even if I select "German" only I still get a lot of Japanese toots in my public time line.

For example I got this toot:
https://pawoo.net/@yaruotto/101585079928250629

It has set `lang="ja"`. So there must be a bug. Please reopen this issue.
