### ISSUE TITLE
Uploading 6MB gif fails (reports as >8MB)

### ISSUE THREAD

**Issue by Rushyo** [tootsuite/mastodon#823]
Uploading a 6.3MB gif is rejected as being "over 8MB".

Gif: https://www.dropbox.com/s/ru79lqgazdkbk6x/ezgif.com-resize.gif?dl=0

**Comment by alex73630** [comment]
This issue could be related to a Nginx configuration issue. Look at your `client_max_body_size` value in your Nginx config, if it's not defined, just add `client_max_body_size 8M;` in your Mastodon virtual host config.

**Comment by ashfurrow** [comment]
@Rushyo Following up on this, did @alex73630's solution work for you, did you find another solution, or is this still a problem?

**Comment by Rushyo** [comment]
This was a user-side complaint, so nothing I can really do to follow it up. Will close.
