### ISSUE TITLE
Show unlisted toots in timelines of unapproved followers

### ISSUE THREAD

**Issue by spongefile** [tootsuite/mastodon#8233]
The "unlisted" privacy option might have a broader use case if it would appear in the timelines of unapproved followers.

Scenario: you want to toot casually at your friends, but might also have and want to develop professional contacts on Mastodon (the way one used to on the birdsite). Currently if you have a private account, the only way your nonapproved followers see your unlisted toots is if they happen to visit your profile directly, which doesn't happen a lot. So from a broadcast perspective, you're looking at this:

<img width="735" alt="untitled 2018-08-17 11-48-12" src="https://user-images.githubusercontent.com/1905464/44257007-740eb780-a213-11e8-9494-cdf38b22f931.png">

Currently, there doesn't seem to be a big difference between private toots and unlisted toots in terms of who reads them. This change would make the difference between the privacy levels more even.

In terms of explaining privacy in real world human terms, unlike the other privacy levels, Unlisted is also harder to explain to new users:

**DM** = _private chat with you and and a friend_
**Private** = _friends only_
**Unlisted** = _Something you'd say to your friends but don't want to bother the world with (Hard to find examples of scenarios that this regularly serves other than replies to threads, which this suggested change would not affect)_
**Public** = _the whole world must hear of this_

Alternate for **Unlisted**: _Friends and curious followers only_

This also provides a stepping stone between a stranger and a friend, where you can interact with them in this intermediate state before deciding that you want to include them in your private toot feed. 

This is something you couldn't have on the birdsite. People had professional and private accounts separately, but juggling the two was clumsy and getting people to follow your private account after a while was also not a particularly graceful procedure. With this change on Mastodon, colleagues and acquaintances could organically turn into close friends.

* * * *

- [✅ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment]
Interesting suggestion, which does not seem too complicated to implement.
However, I'm very uneasy about changing such existing behavior, even if it does not actually change the privacy of such posts.

**Comment by trwnh** [comment]
It sounds like the fundamental change you're asking for is to "show public/unlisted posts when you follow-request someone, then show followers-only if they accept your follow". That sounds like more of a change to how locked accounts and approved follows should work, right?

If that were to be done, then there would need to be new logic to handle unapproved follow requests, hard notifications sent to let people know that someone requested a follow (instead of the soft notification as a counter on the "follow requests" button), and possibly renaming the concept to make it more appropriate -- "unapproved followers" instead of "requested followers"? Under this model, if you want to "reject" an unapproved follower, you would block or soft-block them (since a "remove follower" would be a separate feature request and dependent on #8234 )

**Comment by spongefile** [comment]
> It sounds like the fundamental change you're asking for is to "show public/unlisted posts when you follow-request someone, then show followers-only if they accept your follow".

Yep, you got my meaning 👍

**Comment by trwnh** [comment]
@ThibG I think the exact case would be before `Reject` `Follow`, semantically you could have logic for when a `Follow` has been sent but an `Accept` has not been received.

**Comment by nightpool** [comment]
this *would* be a pretty fundamental change to how mastodon works—you'd have to have "two classes" of followers, and it's not exactly clear from the UI/UX how you'd distinguish between those two. I don't think this is a good idea to implement, unfortunately :(

**Comment by nightpool** [comment]
(also, yes, #5686 is an older thread covering the same issue, so let's move discussion there)
