### ISSUE TITLE
[UX] Clicking a post from the middle of a thread opens it in the last column - but it doesn't scroll automatically to the post you clicked

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#8239]
... so you have to manually scroll to the post you clicked. It's annoying!

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
It works in glitch-soc and there seems to be the code to do that in here also.
Trying to track down why it doesn't work.

**Comment by ThibG** [comment]
Woops actually no, it doesn't work reliably (sometimes it works, sometimes it doesn't), neither here nor in glitch-soc.

**Comment by ThibG** [comment]
https://github.com/tootsuite/mastodon/commit/023fe5181b66ba2cbd20cca4e3bd34f132deba52 might have made things worse by changing how much of the DOM changes, I guess?

**Comment by ThibG** [comment]
Btw I wonder if some of our TL scrolling issues aren't due to something like that as well.
