### ISSUE TITLE
How to use localhost SMTP/sendmail

### ISSUE THREAD

**Issue by postblue** [tootsuite/mastodon#824]
Is it possible to add how to use a local mail server (Exim4, Postfix in send only) to the [Production guide](https://github.com/tootsuite/mastodon/blob/master/docs/Running-Mastodon/Production-guide.md)? Thank you!

With Exim4 configured in send-only, I have this configuration:

```
# E-mail configuration
SMTP_SERVER=localhost
SMTP_PORT=25
SMTP_LOGIN=
SMTP_PASSWORD=
SMTP_FROM_ADDRESS=mastodon@pouet.it
```

And this error:

```
2017-04-04 13:10:09 rejected EHLO from localhost [::1]: syntactically invalid argument(s): {}
2017-04-04 13:10:09 rejected HELO from localhost [::1]: syntactically invalid argument(s): {}
```

**Comment by rhaamo** [comment]
Please check issue #772  this have been reported and a fix available (one file to edit) :)

**Comment by swaldie** [comment]
Please continue discussion of this in #772 for now.  This will be closed as a duplicate.
