### ISSUE TITLE
docker-compose error: "node:8.11.3-alpine as node" is not a valid repository/tag: invalid reference format

### ISSUE THREAD

**Issue by GammaSQ** [tootsuite/mastodon#8240]
I'm new to docker and this may be a docker-compose issue. However, I was unable to find any information relating to this.
Following the docker-guide to build my own image, I cloned the git, moved the `.env.production.sample` to `.env.production` and ran `docker-compose up`. (`docker-compose build` would complain not being able to connect before running `docker-compose up` I got this error:

    sudo docker-compose up
    Creating network "mastodon_internal_network" with the default driver
    Creating network "mastodon_external_network" with the default driver
    Building web
    Step 1/24 : FROM node:8.11.3-alpine as node
    ERROR: Service 'web' failed to build: Error parsing reference: "node:8.11.3-alpine as node" is not a valid repository/tag: invalid reference format

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by pwoolcoc** [comment]
what version of docker are you running? iirc, the `FROM image AS name` syntax was added to support multi-stage builds, which requires 17.05 (or 17.06, can't quite remember), so maybe you need to update docker?

**Comment by Gargron** [comment]
Yeah I think this is an older Docker version problem.

You can also avoid building locally by editing the docker-compose.yml file, it will use pre-built images from the hub then.

**Comment by GammaSQ** [comment]
`docker-compose` is on version 1.17.1
`docker` is version 1.13.1
I installed both in fedora via dnf.

**Comment by pwoolcoc** [comment]
@GammaSQ docker changed it's versioning scheme after `1.13.1`, so it goes `1.13.1`, then `17.03.0`, etc. So it looks like your docker version is a couple behind, which would be why you are getting that error.

**Comment by tateisu** [comment]
Docker's "multi stage build" with keyword "as" is supported on Docker 17.05 or later.
