### ISSUE TITLE
"Rename the "Delete and rewrite" warning popup

### ISSUE THREAD

**Issue by roipoussiere** [tootsuite/mastodon#8246]
When clicking on *Delete and rewrite* button, there is a pop-up informing me that all responses will be also deleted.

This is apparently not the case.

To test it:
- create a personal toot `test 1`;
- response to it with `test 2` ;
- *Delete and rewrite* `test 1` and replace it with `new test 1`.

`test 2` is still here.

Same thing with other toot visibilities.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment]
I think it was never meant to delete replies, and the text is misleading.

**Comment by jusdepatate** [comment]
It would be useless to delete all replies i think

**Comment by Gargron** [comment]
It deletes replies in the sense that the new post you make won't have the old replies. The replies themselves don't belong to you, they are other people's posts with "reply-to" metadata, so it wouldn't be right to delete them on their behalf. I believe this issue is a wontfix

**Comment by Cassolotl** [comment]
What's the actual text in the pop-up? Maybe it can be made clearer.

**Comment by Cassolotl** [comment]
Okay so I agree that it's not as misunderstandable as the OP said, but I do think it could be clearer! Because you don't lose the replies. The replies continue to exist and are visible in your notifications. It might be more helpful to say something like "Boosts and favourites will be lost, and replies to the original status won't be connected to the new one."

**Comment by Gargron** [comment]
I think "lost" is a perfect word here. If I lose my keys it doesn't mean the keys are destroyed.

**Comment by ThibG** [comment]
But you haven't lost them, they're still right in your notifications (unless you have deleted them) or your TL. Sure, they will be orphaned/not connected to the new post…

(Btw, what about Update Note? :eyes:)

**Comment by Cassolotl** [comment]
It's a word with ambiguous meaning - it can also mean gone forever. But okay, I don't care enough.

**Comment by Cassolotl** [comment]
> Sure, they will be orphaned/not connected to the new post…

Orphaned is a good word, less ambiguous!

"Favourites and boosts will be lost, and replies to the original post will be orphaned."

**Comment by roipoussiere** [comment]
I also prefer this one. ↑

**Comment by Gargron** [comment]
I'm okay with it.

**Comment by roipoussiere** [comment]
Good! :)
I updated the title, is it possible to re-open the issue?
