### ISSUE TITLE
"Local" is not the right word to describe an instance/server

### ISSUE THREAD

**Issue by alerque** [tootsuite/mastodon#825]
Yes technically it's correct but it's also confusing. A better word should be used for "local". I see two major options:

1. Use "instance", "server", or  "network". Words like these are more descriptive of what's going on and don't conflate other possible meanings the way that "local" does.

2. Insert the actual name of the instance.

**Comment by Treggats** [comment]
A third option could be;

3. "instance: {instance_name}"

That way it is clear that we're talking about a Mastodon instance, with a direct reference to the actual instance.

**Comment by yiskah** [comment]
No. Stop it. We are not renaming the timelines again. It used to be called "public" then "community" then "local" because ever single name is confusing. "Instance" is ambiguous, which instance? My instance? What's an instance?. "Server" also is ambiguous. "Network" Is absolutely confusing. All of these are still highly technical terms. Inserting the instance name doesn't work because many instance names are incredibly long.

People will know what this means after we have onboarding features which explain it. It's a new concept and distinction and no name will be inherently intuitive. We already had this debate like ten times before all the new volunteers started. Stop bringing it up.

**Comment by alerque** [comment]
@piskah If it keeps coming up then its not fixed. Naming things is hard but throwing up your hands and declaring it unfixable is just not a useful approach. Whatever combination of naming and UI helps will best get people started hasn't been hit on yet. Meanwhile links to any previous issues where this was discussed would be a lot more useful than just saying its been discussed.

**Comment by yiskah** [comment]
Did you just call me pisskah. Real mature. 

We've primarily discussed this on Mastodon and in the MastoDev discord. 

Think of this way. If I hand you an object you have never encountered before and say "This is called a plorf." When your reaction is "I don't know what this is." The solution is not to rename it to a Squalk and continue to give you no explanation of what it is. We tried renaming it multiple times and that is simply not the solution. Right now our priority is implementing better new-user onboarding systems (not just the modals, we are also working on a landing page with tools to help find an instance, etc. etc.) which do not rely on changing names in the interface or adding lengthy text which persists past initial usage.

This does not mean we can never rename it. Right now, as we are attracting massive attention, and still have no systems to onboard people, it is bad timing to rename something, as it would confuse many of the users still getting acquainted with the system. 

Everyone has an idiosyncratic brain. Someone thought Public was very clear, but then others said it was the wrong word and unclear. I thought simply writing out The Whole Known Network would be *pretty clear* but then others said it was the wrong word and unclear. We discussed the merits of Federated on discord and Mastodon for a day or two and it was decided that it would be changed to Federated and we would leave it at that.

So for the Local timeline, it was called Public, which was unclear apparently, then it was Community, which was unclear apparently, someone suggested renaming it to Home and then Home to Private. We didn't do that one. We settled on Local as everyone on Mastodon who was in the conversation or not was suggesting local and everyone agreed it was pretty intuitive. 

We concluded after a while that the UX can only be self-explaining to a certain extent. Throwing users at entirely new software with no guidance and relying on everything being solely intuitive is the problem, not that things are not intuitive. Can things be more intuitive? Of course. But right now we want to try to give users guidance first and see how much that helps. What remains unintuitive when an actual explanation is available? That can be our focus. 

The product is young but it did not start today. There is still a history of existing developers who have been working on this and discussing this for a while. At this point, any major changes to the UX should wait until some dust has settled and we have finished addressing high priority issues. Then we can have a slower discussion of what can be fine-tuned. 

One thing we definitely need before we go around re-naming things is a system to organize the software updates and explain to users what has changed on the front end. In the past when things got re-named, people assumed it came with a change in functionality. It also confuses new users to see the old term still being used.

**Comment by alerque** [comment]
@yiskah The mistake in my at-relpy was completely unintentional. I wrote it on the train this morning via mobile and that could be a spellcheck/auto-complete error or a fat finger. In any event please accept my apology and understand that wasn't a diss.

**Comment by ashfurrow** [comment]
Now that Mastodon has user on boarding built in, and because there haven't been other issues opened around this idea that I can see, I'm wondering if we should consider closing this issue.
