### ISSUE TITLE
[Confuse] Filtered words in timelines are confusing

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#8252]
When I added stuff to /filters I was pleased to see that they had been collapsed into a sort of placeholder:

![screen shot 2018-08-17 at 17 23 57](https://user-images.githubusercontent.com/6607512/44277349-5a389900-a242-11e8-9e2c-9d4d20c9f4c5.png)

But the placeholder is confusing. When you click it it changes colour, but doesn't do anything. And you can't get the colour to change back again.

![aug-17-2018 17-26-33](https://user-images.githubusercontent.com/6607512/44277484-bdc2c680-a242-11e8-9236-378160016277.gif)

I would like to see the filtered word it contains, to know roughly how much good the filter is doing. I'd also be curious to see who made the post.

Maybe it could just say "filtered", and when you click it it shows the username of the person who posted it, plus the word it contains that you have in your filters list? And then clicking again puts it back to just saying "filtered"? That way we can see how much good our filters are doing, who's posting stuff we're not really into, etc.

If not, maybe just making it so that it doesn't change colour when you click? That way we're not like "did that do anything? this is buggy and weird".

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
I have received a lot of positive feedback for the fact that the filter does not let you click to see what's underneath, or reveal which of the filters it is. According to them it's good for their mental health because it would be too tempting to click otherwise and it would defeat the point.

**Comment by Cassolotl** [comment]
Alright, if it's for people's MH then I can understand not wanting to change it. I hope there will be a fork that adds the option to show which word it's being filtered for.

What about the weird clicky colour thing?

**Comment by trwnh** [comment]
>I have received a lot of positive feedback for the fact that the filter does not let you click to see what's underneath, or reveal which of the filters it is.

I agree with this reason, but if so, then why show the "filtered" word at all? As a reminder that something *was* filtered? Personally, I would prefer if the placeholder was removed, because it's pretty useless to me and just takes up space.

**Comment by Gargron** [comment]
The placeholder is required for pagination to work properly.

The color is the styling of the focused element, it serves a purpose for keyboard navigation.

**Comment by Cassolotl** [comment]
Alright, that satisfies my confusion! I'd like to leave this open though because I'll bet this is confusing other people.

**Comment by wimvanderbauwhede** [comment]
I want to second @trwnh here.  There is no point in showing the word "Filtered" if it is not interactive. Maybe you need the placeholder in the code, but could it not be zero height?

**Comment by Cassolotl** [comment]
I would like to see how well my filters are working, so I like the option to keep the placeholder visible. It can currently be made totally invisible with the "drop instead of hide" option on the create filter page:

![screen shot 2018-08-20 at 19 38 35](https://user-images.githubusercontent.com/6607512/44359752-af79e200-a4b0-11e8-9cac-b25ede7b9a23.png)

**Comment by wimvanderbauwhede** [comment]
I agree, making it a user-controllable option is preferred. But "drop" is often a bit too harsh for me, as it's irreversible. I'd like to have the option to make it totally invisible when choosing "hide" as well.

**Comment by fvh-P** [comment]
I also agree to enable the "Filtered" posts completely invisible. Why should we be made to show "Someone is talking about what you dislike!" ?? It's really INSANE.

**Comment by codl** [comment]
agreed that showing "filtered" banners is silly

i don't see why the placeholder would be required for pagination. i get how keeping track of the filtered posts could be necessary but i don't see why they also have to be shown

**Comment by sireebob** [comment]
consider this negative feedback, then. seeing the word "filtered" is too tempting to ignore. at the same time, i don't like the idea of toots being dropped forever as a result of a temporary mute.

**Comment by trwnh** [comment]
In revisiting this, ideally there would be the following options:
- Drop instead of hide
- Show "filtered" stub (since some want to disable display without it being irreversible)
  - Show which filter was triggered (imo should be enabled, but there is disagreement here)
  - Click to show (disabled by default, but effectively allows for setting your own dynamic auto-CW)

**Comment by Cassolotl** [comment]
This issue has too many things in it so I opened *Clicking "Filtered" in timelines changes the colour of the background but does nothing #12444* to talk about my one remaining issue from my original post.

If folks would like to open issues for removing the filtered banners, for example, they can do that. :)
