### ISSUE TITLE
No confirmation mail if first delivery attempt failed

### ISSUE THREAD

**Issue by d-salas** [tootsuite/mastodon#8255]
Basically an identical case of this issue:
https://github.com/tootsuite/mastodon/issues/120

My friend registered using an email address she thought existed, but it actually didn't. She created the email address afterward (which I can share – not sure if I should include it in this post) but still can't receive the email due to how Mailgun marks hard bounces.

Seemed that the only fix was removing the email address in question from the bounce list.

Apologies if this isn't the best place to get direct support. Is the support@mastodon.social account active?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate (it is)

**Comment by Gargron** [comment]
Right, I don't think this is a Mastodon bug. Also, if an e-mail address is not confirmed within two days, the new account is deleted so you can try registering again.
