### ISSUE TITLE
.webm videos are not shown in Safari (convert them or notify user)

### ISSUE THREAD

**Issue by wottpal** [tootsuite/mastodon#8258]
I've uploaded a `.webm` file in a toot ([here](https://chaos.social/@wottpal/100568077073696963)) which is shown in Chrome but not Safari. I know unfortunately Safari doesn't support it but either the Safari users should see a message like (*Not supported in your browser*) or even better the video should be automatically converted on the server-side.

Currently it looks like:
<img width="386" alt="bildschirmfoto 2018-08-18 um 01 08 03" src="https://user-images.githubusercontent.com/3930150/44292184-7c064000-a283-11e8-9bb3-a7e459ee309a.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
This should already be resolved in the master branch.
