### ISSUE TITLE
Can't remotely follow accounts on 'random' instances

### ISSUE THREAD

**Issue by distantorigin** [tootsuite/mastodon#8259]
I've looked through various issues and have not found something equivalent. Issue #960, #736, and #4676.

Remotely following users from arbitrary instances seems to fail. For example, following users on https://mastodon.social works, but following:
https://mastodon.xyz/@thekinrar
fails with a status 500 per headers and Nginx logs.

Pulling up the docker logs for my container reveals the following:
app/services/activitypub/process_account_service.rb:61:in `update_account'
app/services/activitypub/process_account_service.rb:24:in `block in call'
app/services/activitypub/process_account_service.rb:17:in `call'
app/services/resolve_account_service.rb:102:in `handle_activitypub'
app/services/resolve_account_service.rb:48:in `block in call'
app/services/resolve_account_service.rb:43:in `call'
app/controllers/authorize_follows_controller.rb:44:in `account_from_remote_follow'
app/controllers/authorize_follows_controller.rb:35:in `located_account'
app/controllers/authorize_follows_controller.rb:10:in `show'

SSL is set up properly and using fullchain.

My Ruby version is:
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux-musl]

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
Please provide a more complete (it's missing at least the actual raised exception) and better-formatted log.

**Comment by distantorigin** [comment]
Switching to the non-docker version of 2.4.4 fixed this.
