### ISSUE TITLE
Inconsistent position of the back-button in the last column

### ISSUE THREAD

**Issue by allo-** [tootsuite/mastodon#8266]
The back button in the last column does not have always the same position

Steps to reproduce:

- Click a Hashtag
- Click a User
- Click Back on the **left** side to get one step back from the user tab
- Click Back on the **right** side to get one step back from the hashtag tab

When you need to go back many steps, you cannot always click the same position.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Duplicate of #7731
