### ISSUE TITLE
Instance block always send message

### ISSUE THREAD

**Issue by Dryusdan** [tootsuite/mastodon#8268]
Hi
After the recent case (with lot of ban), I see a bug on domain block.
When the instance A block an instance B, instance A don't see anything of instance B, but instance B can read followed person before blocking of instance A.
I can send also private message in Instance A to instance B, is just useless :/

So, can it possible to block a instance input and ouput ?

Regard :)
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [2.4.3](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by LecygneNoir** [comment]
👍 for this feature, when the blocked instance is toxic, it could cause real problem that people inside see message from an instance where they are blocked.

More precisely, received toots are used for insult, harassment, or worse...
A possibility for admin to isolate an instance in and out seems a great addition :-)

Thanks for the job on mastodon!

**Comment by ThibG** [comment]
I would have to check the code to make sure of that, but as far as I know, instance blocks should prevent your instance from sending toots to a blocked one.

That being said, it can't prevent a foreign instance from *fetching* public or unlisted toots, because that's fetched anonymously. You could imagine IP blocks etc. but that's hackish and easily bypassed.

**Comment by nightpool** [comment]
it depends of course on if the instance block was silence or suspend

**Comment by Dryusdan** [comment]
Instance fetch toit anonymously ? ._.
@nightpool the admin say suspend

This morning I can send DM from banned instance...

**Comment by ThibG** [comment]
Actually… it seems although followers should properly be removed, blocked users can still be mentioned and the toot will be delivered.
We probably do not want that.

**Comment by Gargron** [comment]
Resolved by #8272, I think

**Comment by Dryusdan** [comment]
Maybe I found the problem : the relay. My instance use a relay and toot can share on another instance :thinking: 
So, block and instance is juste "not receive toot from this instance"...
