### ISSUE TITLE
customization of columns in webinterface

### ISSUE THREAD

**Issue by byteturtle** [tootsuite/mastodon#827]
would be nice if you could move the columns around, and tune them how you like.
e.g. filter for specific words, open profiles/toots in same/other column and so on.
kinda like tweetdeck does it.

**Comment by lattera** [comment]
+1 from me. Also add/remove columns.

**Comment by fhemberger** [comment]
Duplicate of #351

**Comment by wxcafe** [comment]
Closing this since it's a duplicate
