### ISSUE TITLE
Verified users

### ISSUE THREAD

**Issue by truhe2342** [tootsuite/mastodon#8276]
Mastodon should offer a way to support verified users. See [that toot of Wil Wheaton](https://mastodon.cloud/@wilw/100572583503071267): He uses his verified Facebook account to verify that a specific Mastodon user belongs to him. That's obviously a subpar solution.

Years ago app.net had a [html based validation for your website](https://3manfactory.co.uk/2013/05/01/app-net-introduces-domain-verification/) and domain validation (with text entries added to your dns). You created the code in your profile and added it to the website or dns server and you got a little checkmark in your profile and it also showed which domain was used to validate that account.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by niteshkumardebnath** [comment]
I think the best way to deal with it would be self hosting, if you trust my website to be mine and trust me you can trust everything that is through my website to be either mine or somehow endorsed by me unless stated otherwise. Of course that requires a lot of work but there are many services which will do the heavy lifting for you, and if you're a public figure you probably have enough money to do all that.

**Comment by Laurelai** [comment]
keybase.io exists for the purposes of online identity verification

**Comment by c0debabe** [comment]
I second the keybase.io suggestion. I have my own DIY proof pinned to my profile. You can check it against my Keybase profile.

**Comment by lawremipsum** [comment]
Seems like Wil has accomplished what was needed without any code. Development resources are better spent elsewhere than on solving this "problem" which can be handled informally very easily as this example demonstrates.

**Comment by pianycist** [comment]
I don't think that we should elevate users above other users with a "verified" tag of any kind.

**Comment by joyeusenoelle** [comment]
This has been hashed out before (see for example #913).

**Comment by avolkov** [comment]
Verified status is a marketing ploy from Twitter, and the one that has backfilred -- i.e. they have verified a bunch of Nazis. Even if it were a good idea in theory, from the technical standpoint in the de-centralized system like mastodon there's no real center authority for verification, so you would have to trust the admin of the instance to 'verify' users. Also there's nothing prevents any users to start their own instances 'verify' themselves on it, and confuse or impersonate every.

Currently it's possible to just add keybase.io or gpg idenity or any kind of identity verification link into profile metadata or pinned toot with no changes required to code database.

**Comment by jpotier** [comment]
> Mastodon should offer a way to support verified users.

Sorry to be blunt, but… why is that a needed feature? I'm pretty foreign to twitter and facebook and the like and maybe I missed something.

**Comment by truhe2342** [comment]
1. Self hosting is not a possibility for everyone.
2. It's not about elevation. In the Twitterverse it is, but we are not talking about Twitter and how and why they do things but about Mastodon. One reason for _everyone_ to be able to verify an account against something else are [imposters](https://github.com/tootsuite/mastodon/issues/913#issuecomment-292585101) who create accounts with the same name on other instances. Thanks for mentioning the other issue!
4. keybase.io. Thanks! That's fine solution and also, if you just go [the implemention with a file](https://ryanmaynard.co/mastodon-keybase), an easy one.

Here's what to do:
1. Register at keybase.io
2. Verify against whatever, Twitter, your own domain etc.
3. Since Mastodon is not supported out of the box just create a file index.md in your public file space listing your Mastodon accounts and link that back to your keybase profile.
4. Add the url of the file to your Mastodon profile.

**Comment by trwnh** [comment]
Here's the thing about this (and any other "verification" or claim of authenticity or provenance): it's inherently a matter of trust. Twitter's "verified" checkmark is nothing more than a claim towards Twitter's authority. Asking to verify a Mastodon profile is like asking to verify any web page in existence. You simply substitute Twitter's authority with some other authority -- perhaps you share your profile in person, or you have a presence somewhere that is trustworthy.

Wil Wheaton has wilwheaton.net, his Twitter, his Facebook, and so on -- any of these can do. For someone who does not have any of those, they will have to find some other way to make their followers trust that they are who they say they are -- and there will never be any guarantees. The fundamental problem of trust is entirely societal and not strictly technological. Even in person, you can claim to be someone you are not.

**Comment by kateiyas** [comment]
I understand your points about the decentralized nature of mastodon. However I think account verification could be beneficial for certain specialized instances that have good reasons to set such rules. 

There could be an academic instance where you could easily get verification that you are a researcher with e.g. a university mail address (this is all e.g. GoogleScholar does). Then it would be great if the interface allowed to show messages by verified accounts only. Given the toxicity of angry, anonymous Twitter users I often wish that a basic filter like this existed over there, as it would make their service much more useful for staying up-to-date in research.
