### ISSUE TITLE
Twitter sync to help new users migrate

### ISSUE THREAD

**Issue by pimterry** [tootsuite/mastodon#829]
(This is probably not the perfect place to report this, but it was [suggested](https://mastodon.social/@RaitoBezarius/1563480) that I start here, and I'm open to ideas on where would be better)

To move from Twitter to Mastodon, it'd be convenient to be able to keep them in sync for a while. Either way is fine, but for me personally, it'd be easier to migrate if there was an simple integration/bot/app that allowed me to post to one, and have posts automatically appear on the other (where possible - within the twitter length limit, not a reply to a post that's only on one or the other service, etc).

Is that practical? Does anything like this already exist?

**Comment by rhaamo** [comment]
Actually there is https://github.com/Psycojoker/t2m and https://github.com/halcy/MastodonToTwitter (older than t2m) but theses are apps to be deployed by the user, nothing "user-friendly" web-based or anything actually.

**Comment by pimterry** [comment]
Ah, perfect, a nice solution: add an RSS feed for a user's posts.

If you get RSS, you get IFTTT support out of the box, and you can sync your mastodon posts across to anything. A public RSS feed for a user's posts (say `https://mastodon.social/@pimterry/rss`) seems like a nice useful thing anyway, doesn't sound too difficult (_he said blithely_), and would add a lot of nice flexibility.

**Comment by pimterry** [comment]
Haha, perfect, that already exists: https://mastodon.social/@pimterry.atom.

I've got IFTTT now syncing my Mastodon back to my Twitter, I'm going to close this. Full instructions here: https://medium.com/@pimterry/sync-your-mastodon-back-to-twitter-3c72f2bc8626.

Notably the formatting comes out a bit weird. See https://twitter.com/pimterry/status/849351999225200640 vs https://mastodon.social/@pimterry/1607085.

Here the username drops it's @'s, I think because the username is wrapped in a unnecessary span there:

```
<a href="https://mastodon.social/@felicis" class="h-card u-url p-nickname mention">@<span>felicis</span></a>
```

URL formatting also ends up a bit weird, I think because the HTML in the atom feed for links is very weird, e.g.:

```
<a href="https://twitter.com/pimterry/status/849350679575629825" rel="nofollow noopener" target="_blank"><span class="invisible">https://</span><span class="ellipsis">twitter.com/pimterry/status/84</span><span class="invisible">9350679575629825</span></a>
```

Obviously both of these aren't really a Mastodon problem as such - they're issues with how Twitter/IFTTT is handling this content. Is the above necessary though? Seems weird, and like it'll potentially break things other than just this integration when they're trying to read this atom content too.

**Comment by r0bbie** [comment]
I'd love to see a way to do this that wasn't reliant on IFTTT.

**Comment by pimterry** [comment]
Any particular reason @r0bbie? I agree it's a little hacky - URLs don't come through right, @'s get dropped so names look weird, and all replies are included unless they're direct or private, which doesn't make sense on the other side. I don't really mind depending on a syncing service to do my syncing for me. It's not like this is critical infrastructure, or there's any privacy concerns or anything, it's all public data at this point.

As is, this is a workable stopgap for me, and you can use IFTTT to filter on #crosspost or something to opt-in only on toots that'll come out nice, but I agree it's not perfect by any means. Does have the advantage though of not needing either Mastodon itself to connect to the Twitter api (ick), or users to host their own sync solution (substantial hassle).

**Comment by Croydon** [comment]
@pimterry Think about the average user (at least when you don't want to stay nerdy), it is way to complicated for the mass.

**Comment by raimue** [comment]
As a pointer for others looking for a solution, https://crossposter.masto.donte.com.br/ supports both directions to cross-post from Twitter to Mastodon and vice versa. You have to authorize access to Twitter API and Mastodon API. It even allows to configure which tweets/toots to cross-post and even exclude retweets/boosts.

**Comment by MilkManzJourDaddy** [comment]
If you want to think outside of the «IFTTT Box», and cross-post, aside from what has been mentioned, think Webhooks, Push/PubSub, or do microblogging from within Matrix and let an app' you host crosspost, i.e. [mycete](https://github.com/qbit/mycete), or possibly another in development.  Check https://matrix.org/docs/projects/try-matrix-now.html#other •and search for Twitter, Mastodon, blog, et cetera.  Current candidates may include mycete, journal, Matrix Blog, and Matrix Live.
