### ISSUE TITLE
[Feature] Freeze account as a suspend-light

### ISSUE THREAD

**Issue by ashleyhull-versent** [tootsuite/mastodon#8291]
Suspend is built to delete all content but not the account... 

I'd love to see the ability to freeze an account as a method of banning somebody but keeping the content around... with the ability to unfreeze and let them back with business as usual.

This works in the situation when people are thousands of posts that are within the code of conduct, then get banned... history should be kept if they posted toots of importance or relevance to the instance.

**Comment by nightpool** [comment]
![image](https://user-images.githubusercontent.com/233815/44309320-e528a900-a392-11e8-928d-8daf2b39380e.png)
