### ISSUE TITLE
docker-compose.yml is out of sync with :latest docker image

### ISSUE THREAD

**Issue by NZSmartie** [tootsuite/mastodon#8304]
Starting up a new mastodon instance and chose the docker-compose route. 
Following the instructions we:
 1. cloned tootsuite/mastodon,
 1. followed the docker deployment documentation
 1. chose to use pre-build docker images instead of building on the machine

When starting the instance, we wee being served blank pages. 

This is because the `/mastodon/public/assets` and `/mastodon/public/pages` were empty. Generating assets was recently moved from a post-setup process, to a Dockerfile RUN command. However, the latest prebuilt images on Docker dose not reflect this change.

This leads to the issue of not being able to git clone the latest stable without cloning a specific tag version of mastodon that matches what's on docker. 

Arguably, i should should be cloning a specific tag. however that makes the upgrade process a manual process. (Ideally, something wimple like `git pull && docker-compose pull && docker-compose down/up is performed)

Is it possible to add a release branch that points to the latest stable build that matches what's hosts on Docker that's not edge?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashleyhull-versent** [comment]
I resolved this by just docker-compose build locally instead of pulling the images from the hub.

this does end with the `/public/system` folder being empty on my server.. so I was very confused during installation

**Comment by NZSmartie** [comment]
>I resolved this by just docker-compose build locally instead of pulling the images from the hub.
Not helpful in the situation where using pre-built images is perfected...

**Comment by Gargron** [comment]
The file is fixed in master, at least.

**Comment by NZSmartie** [comment]
>The file is fixed in master, at least.

How is the file fixed in master? it's not pointing to the `edge` tag.

Secondly, if a branch is created that points to the latest stable release, then this shouldn't be a problem any more. As deploying instances on that branch should guarantee the repo and the latest are matched.

**Comment by Gargron** [comment]
>it's not pointing to the edge tag.

It shouldn't... It points to "latest", which is built from the latest stable release.

**Comment by NZSmartie** [comment]
Why was this issue closed? Has the docker build behaviour changed?
If I check out a tagged release instead of master I'm required to modify the `docker-compose.yml` to ensure the correct docker image is used. 
Also, when this issue was created, the `latest` docker image was built much later than the latest stable release.

**Comment by ashleyhull-versent** [comment]
The way the docker containers work was changed.... 
if your DB and attachment is safe.. you can checkout a fresh branch, rebuild your containers and boot on the new branch with new containers.

the joy of docker is you shouldn't be overly attached to any of the containers.

Just make sure your DB/storage is backed up.. you should be able to reclone the repo and migrate easily enough with the latest tagged stable v2.5.0

**Comment by NZSmartie** [comment]
Ah that's good to hear. Thank you

**Comment by ashleyhull-versent** [comment]
Make sure you backup and move carefully - but if you need assistance, DM me in discord :/
