### ISSUE TITLE
Reduce log in syslog

### ISSUE THREAD

**Issue by Dryusdan** [tootsuite/mastodon#8312]
Hi
Actually, Mastodon (and sidekiq) send all toot and other in syslog file... but we need only warn or error info, not all toot... So, can it possible to set a log level into mastodon to reduce io and space usage ? (and lisibility when an error provide).

Regard

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Please use RAILS_LOG_LEVEL environment variable. Set it to "warn" (default: "info")
