### ISSUE TITLE
[Hilariously minor issue] Background image doesn't fit column

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#8325]
So extremely minor that I cannot even.

![screen_shot_2018-08-20_at_22_18_34](https://user-images.githubusercontent.com/6607512/44367390-7f8a0900-a4c7-11e8-9384-be0a6beaeb07.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
What browser is this? Problem doesn't exist on Firefox, for example

**Comment by Cassolotl** [comment]
Oh! Chrome, on Mac. I meant to say that and forgot, sorry!
