### ISSUE TITLE
Webpacker not compiling [Docker]

### ISSUE THREAD

**Issue by liamolua** [tootsuite/mastodon#8335]
When running `docker-compose build` I get this output at the end.

```
Webpacker is installed 🎉 🍰
Using /mastodon/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:



#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#

ERROR: Service 'sidekiq' failed to build: The command '/bin/sh -c OTP_SECRET=precompile_placeholder SECRET_KEY_BASE=precompile_placeholder bundle exec rails assets:precompile' returned a non-zero code: 1
```

What is happening here, do I need more memory on my server or is this a software issue?
I did try running `chown -R 991:991 public` then running `docker-compose build` again but I run into the same issue.

**Comment by ashleyhull-versent** [comment]
I'd recommend enabling swap for starters or using an instance type with more memory..
I figure you're likely using 1GB or smaller

I've written a guide to assist - https://discourse.joinmastodon.org/t/lets-deploy-an-instance-aka-im-going-on-an-adventure-2-4-3-docker-on-ubuntu-18-04-aug-2018/1136

**Comment by liamolua** [comment]
@ashleyhull-versent 
> I'd recommend enabling swap for starters or using an instance type with more memory..
I figure you're likely using 1GB or smaller
>
>I've written a guide to assist - https://discourse.joinmastodon.org/t/lets-deploy-an-instance-aka-im-going-on-an-adventure-2-4-3-docker-on-ubuntu-18-04-aug-2018/1136

I don't know if my VPS allows for SWAP but will try upgrading my RAM to 2GB. I though this would more than likely a RAM issue. Thank you for your reply.

Will post an update and close issue if it works after upgrading ram.

**Comment by liamolua** [comment]
Hey, it has built the image. Thanks for clarifying @ashleyhull-versent . :+1:
