### ISSUE TITLE
GPS Location in Toots (not linked to images)

### ISSUE THREAD

**Issue by lfuelling** [tootsuite/mastodon#8340]
It would be really nice to add location data (GPS) to a toot containing only text (or images) similar how it's available on the Birdsite.

## Use Case

You go on vacation and don't want to write your travel blog posts right away. So you open a private account with location on by default and just post photos of nice spots you found or a status about a good campsite. 
When you're done travelling and back on a proper computer, you can use your posts to recreate your whole travel with exact location data and use this to write your blog post. 
Also you could use your posts to find the spots you liked a year ago.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. I found #281 which I'm pretty sure is about toots with images.

**Comment by realityfabric** [comment]
I think using Mastodon to log geolocations how you describe is extremely outside of the scope of a social networking / social media platform. 

> So you open a private account with location on by default and just post photos of nice spots you found or a status about a good campsite.

What you're describing sounds like using Mastodon solely for a purpose it wasn't intended to be used for (a note-taking app).

> Also you could use your posts to find the spots you liked a year ago.

ime, most people don't look back through their posts, or create so many posts that searching for specific posts to get a geolocation would be practically impossible.

How many people are going to use geolocation to write blog posts? And what does geolocation data add to user experience if it isn't being used for that?

**Comment by lfuelling** [comment]
> What you're describing sounds like using Mastodon solely for a purpose it wasn't intended to be used for (a note-taking app).

I wouldn't consider Mastodon a note-taking app. 

> I think using Mastodon to log geolocations how you describe is extremely outside of the scope of a social networking / social media platform.

Most social Networks already have this feature.

> How many people are going to use geolocation to write blog posts? 

I don't know, but I know that at least some people would want this feature. 

> And what does geolocation data add to user experience if it isn't being used for that?

I have a good example for that. I recently saw a guy who posted a photo which revealed (through it's contents) that he lives not that far away from me, while I thought the person would. 
Having geolocations would make this easier.  

Also, if you don't want that feature you can just turn it off. Or implement it as opt-in.

Furthermore I could ask the same question about the "device/application used to post" parameter on toots. That is even more useless than geolocation (imo) yet it's already implemented.

**Comment by realityfabric** [comment]
> I wouldn't consider Mastodon a note-taking app.

Me either, but it seems like that's what you're describing. A private account to geotag notes.

> I have a good example for that. I recently saw a guy who posted a photo which revealed (through it's contents) that he lives not that far away from me, while I thought the person would.
Having geolocations would make this easier.

That's true. You don't need geotags to say where you're at, though.

> Furthermore I could ask the same question about the "device/application used to post" parameter on toots. That is even more useless than geolocation (imo) yet it's already implemented.

I think it's useful for debugging, and possibly useful for avoiding misunderstandings due to the way different platforms work. But even if we agree that it's entirely useless, that doesn't have any bearing on whether a new feature with limited usefulness and appeal should be implemented.

**Comment by trwnh** [comment]
i don't particularly care one way or another regarding this feature, but

>extremely outside of the scope of a social networking / social media platform.

is not really correct; the term "microblogging" was invented to describe this exact kind of usage. there is a networking aspect, yes, and there is a media-publishing aspect, yes. but it's really not anyone's business to tell others that keeping a private log is invalid usage of the software. perhaps other software exists that can handle one's specific needs better, but that doesn't mean that's the only possible reason someone might want/use a feature.

**Comment by lfuelling** [comment]
> I think it's useful for debugging, and possibly useful for avoiding misunderstandings due to the way different platforms work.

?

**Comment by N07070** [comment]
I would like this for the possibilty of finding people near me who use mastodon too ! In a city it's easy, but when you live in the countryside, getting to know your peers and comrades is more complicated. And there is not always a local instance... 

Or for example, live-tooting about a riot / concert / event tied to a location would be really nice !

But I think that for this feature to be effective, you would need to be able to search by geo location too, thus updating the UI.

**Comment by alexanderustinov** [comment]
Would like this also - to show friends where am i when travelling.

**Comment by Gargron** [comment]
One of the reasons I don't particularly want to touch geotagging with a footpole: https://theintercept.com/2020/07/09/twitter-dataminr-police-spy-surveillance-black-lives-matter-protests/

**Comment by realityfabric** [comment]
I'll repeat what I said earlier in this thread, since the same point has been brought up again: You don't need geotagging to tell people your location.

And I am 100% against encouraging people to geotag a riot or protest. 

I can see how finding local users would be convenient, but there are too many drawbacks due to our pervasive surveillance for it to be worth it.

**Comment by lfuelling** [comment]
What about the use case that I want to show people cool places I've found?
For example the feature could be implemented so that it adds a "coordinates input" or something like that instead of using the location the browser provides.

Additionally I think it's kind of weird to say that one specfic feature won't be added because people could use it wrong and be surveilled. That can be done with text only posts as well and imo it's not the softwares fault when people are using it to their disadvantage. But then again it seems that Mastodon aims to be useable by "non-tech-savy" people (I guess that implies basic "online safety" measures as well) and personally I've had too much headache with discussions like this so if someone else wants to open up this can of worms under their username, feel free.

**Comment by Gargron** [comment]
I guess if adding geolocation was like adding a poll or picture, an explicit action, then maybe it would be okay? :man_shrugging:

**Comment by Sasha-Sorokin** [comment]
@Gargron I'm scared of that amount of buttons to be honest, but totally okay with the feature. What maps you think can be used though, OSM? :D

**Comment by lfuelling** [comment]
imo the best solution would be an additional admin setting that lets you set an url like:
- `https://www.openstreetmap.org/?mlat={{ lat }}&mlon={{ lon }}`
- `https://maps.google.com/?q={{ lat }},{{ lon }}`

Where `{{ lat }}` and `{{ lon }}` are replaced with the actual data. That way each instance can choose what map provider to use.

**Comment by realityfabric** [comment]
You know what would give the absolute most control to the user? Letting them paste their location into their own post and not implementing geolocation in Mastodon. Just a thought.

**Comment by ajturner** [comment]
I'd like to re-open this issue for discussion if possible. I added a comment to the [Geotag images issue](https://github.com/mastodon/mastodon/issues/281#issuecomment-1321138657) - but the concept is broader and has meaningful social media opportunities for finding nearby posts, trust, etc.

Regarding privacy + security, the location can be imprecise such as a neighborhood, city, etc. depending on the user + server configuration. There are methods for providing an automatic geolocation but only use and store coarse (large area) information. This would serve the purpose of finding "nearby" posts such as a city or neighborhood. 

I've built several of these systems before and worked on standards for W3C and others through the years. I'd be happy to help through the technical + security details as well as implementation.

**Comment by N07070** [comment]
I must say I have been swayed by the arguments *against* including geotagging in Mastodon. Therefore I would oppose adding it as a feature.

**Comment by whisere** [comment]
It will be useful for real time mapping for disaster, or infrastructure issues & others as in this post: https://github.com/mastodon/mastodon/issues/281#issuecomment-1321138657

**Comment by wybert** [comment]
> It will be useful for real time mapping for disaster, or infrastructure issues & others as in this post: https://github.com/mastodon/mastodon/issues/281#issuecomment-1321138657

Great point. Locations should be the same as important as photos and texts.

**Comment by foost** [comment]
I am not quite sure why anyone would categorically object against an optional (!) feature that is deemed extremely useful by some users? Of course you can add a place name manually in your post, but this is a very cumbersome and error-prone way of doing it. In short, not really feasible. Location plays such an important role in our lives. Why not have a way of sharing it programmatically via an opt-in feature?

**Comment by individual8** [comment]
> I guess if adding geolocation was like adding a poll or picture, an explicit action, then maybe it would be okay? 🤷‍♂️

Definitely voluntarily. Nobody likes there toots tagged with location automatically. But having geolocation would be certainly a nice addition to the platform. Like all others above already mentioned in many pro arguments.
