### ISSUE TITLE
Pasting image from clipboard on MSEdge causes React-DOM error

### ISSUE THREAD

**Issue by saschanaz** [tootsuite/mastodon#8341]
Pasting causes:

```
0: Unable to get property 'length' of undefined or null reference
react-dom.production.min.js (17,179)
```

On Windows 10 build 17134, EdgeHTML 17, on both pawoo.net and mastodon.social.

**Comment by saschanaz** [comment]
Confirmed this is a bug in Edge side and filed an issue: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19078589/

**Comment by nightpool** [comment]
thanks for following up!
