### ISSUE TITLE
Regeneration indicator figure blocks label

### ISSUE THREAD

**Issue by Harmon758** [tootsuite/mastodon#8366]
The elephant_ui_disappointed.svg image blocks the "Not found" and "This resource could not be found" text.

![image](https://user-images.githubusercontent.com/9403740/44466330-a50d3480-a5e5-11e8-829b-42b3a403aed6.png)

This can be reproduced by trying to access an account that doesn't exist, e.g. https://mastodon.social/web/accounts/123456789 (This also happens to show two "404 Record not found" notifications in the bottom left; possibly a separate bug?), at a low resolution or with a small or zoomed-in window.
In my case, I received an email notification, about a new follower, with a "View Profile" link that led to showing this. I assume the account was deleted/removed sometime after I received the email.
I was able to reproduce this with both Chrome and Firefox.

The relevant scss and js: https://github.com/tootsuite/mastodon/blob/4bdab203ac5ca06d757d08af8a2bc184c86e3bbe/app/javascript/styles/mastodon/components.scss#L2582-L2634 https://github.com/tootsuite/mastodon/blob/4bdab203ac5ca06d757d08af8a2bc184c86e3bbe/app/javascript/mastodon/components/missing_indicator.js#L4-L15
Based on this and the similarity with https://github.com/tootsuite/mastodon/blob/4bdab203ac5ca06d757d08af8a2bc184c86e3bbe/app/javascript/mastodon/components/status_list.js#L79-L88 I believe this also happens with elephant_ui_working.svg when the home feed is loading, but don't know how exactly to test that.

I think the issue is that the figure/image uses absolute positioning to be centered horizontally and vertically in the column, whereas the label/text only has a top margin.
This can also be noticed with the space between the text and image when zoomed out/with a high resolution:

![image](https://user-images.githubusercontent.com/9403740/44466488-046b4480-a5e6-11e8-9205-fcc140ad6cb8.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
Duplicate #6786 I think

**Comment by Harmon758** [comment]
Ah, I think you're right.
Apologies; somehow didn't see that issue when I searched for it.
