### ISSUE TITLE
Mastodon.social/.cloud using new design on v2.4.3?

### ISSUE THREAD

**Issue by imlps** [tootsuite/mastodon#8367]
Hi there,

I have seen mastodon.social and mastodon.cloud using the new design on About page and user profile page but on my instance it's still the old design despite we all using same version v2.4.3. May I know where/how can I activate that?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
They're on master, not 2.4.3, the version just isn't properly reflected
