### ISSUE TITLE
Interact with toots from detailed deep link pages

### ISSUE THREAD

**Issue by tomlowenthal** [tootsuite/mastodon#8370]
Toots have detailed deep link pages like $INSTANCE/@$USER/$TOOTID . These pages show the content of the toot, a link preview, posting time, and interaction numbers, along with replies to the toot. The name of the person who posted the toot is a link to their profile page.

None of the elements on this page allow for direct interaction with the toot — there's no way to directly fav, boost, or reply. To do that, one must copy the URL into the search box on one's own Mastodon home page. This isn't a great way to interact — a more natural interaction model would be to initiate those interactions through the 🔁 & ⭐️ icons at the bottom of the details page.

<img width="908" alt="interaction-points_annotated-screenshot" src="https://user-images.githubusercontent.com/639937/44476221-f5879080-a5eb-11e8-8650-263f6f963ab5.png">

* * * *

I searched or browsed the repo’s other issues to ensure this is not a duplicate. It was pretty difficult to find keywords which meaningfully narrowed down the results, so no guarantees that I'd have found an issue about the same topic which was phrased differently.

**Comment by ThibG** [comment]
Fixed by #8202
