### ISSUE TITLE
Remote instance unable to follow and remote follow

### ISSUE THREAD

**Issue by c-chell** [tootsuite/mastodon#8375]
Hello.

I search in the already open issues, but I don't find something near my case.

The instance was before on other server before it was transfer on my server (so I'm new in diagnostic the problems).

Recently, some users of my instance (equestria.social) warn me about a problem for remote instance to manage the follow.
I precise it's only to follow, the already followed account works fine (boost, fav, ... works fine).

If a user of a remote instance try to follow a user of my instance they get a "503 Remote data could not be fetched".
When a user of my instance try to use the remote profile and click on "remote follow" button, the remote instance say "Could not find the required redirect URL for your account".

I don't understand, I try to check my logs but I find nothing.
In the NGinx log, I can clearly see 
[22/Aug/2018:19:12:26 +0000] "GET /.well-known/webfinger?resource=acct:c_chell@equestria.social HTTP/1.1" 200 1106 "-" "http.rb/3.2.0 (Mastodon/2.4.3; +https://framapiaf.org/)"
The 503 error don't come on my side (I already check the whole log).

Can you help me ?
I don't know where to search more information.
And as I write before, I'm a novice in the maintenance of Mastodon instance.

For information, the setup is based on Mastodon host on the server (no docker and co) with a front with NGinx.
The NGinx config file is nearly the same as 
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md#nginx-configuration
Except I remove the "http2" option (else Chrome based browser can't access to the instance)

Thank you.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a v2.4.3 (https://github.com/tootsuite/mastodon/releases) on branch ID 7ac5151b74510aa82b07e349373bd442176e1e94

Edit 2018-08-23 : 
I update to the 2.4.4 (for the security patch) but the problem is still here.

**Comment by c-chell** [comment]
Thank you for your reply.
For the test, I try to follow your account. Have you see it ?

Also, I recheck my Sidekiq logs and I see from your instance : 
"{\"@context\":[\"https://www.w3.org/ns/activitystreams\",\"https://w3id.org/security/v1\",{\"manuallyApprovesFollowers\":\"as:manuallyApprovesFollowers\",\"sensitive\":\"as:sensitive\",\"movedTo\":\"as:movedTo\",\"Hashtag\":\"as:Hashtag\",\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"conversation\":\"ostatus:conversation\",\"toot\":\"http://joinmastodon.org/ns#\",\"Emoji\":\"toot:Emoji\",\"focalPoint\":{\"@container\":\"@list\",\"@id\":\"toot:focalPoint\"},\"featured\":\"toot:featured\",\"schema\":\"http://schema.org#\",\"PropertyValue\":\"schema:PropertyValue\",\"value\":\"schema:value\"}],\"id\":\"https://equestria.social/8ba4e2b0-f2ac-42cf-8cca-0e6f3364991c\",\"type\":\"Follow\",\"actor\":\"https://equestria.social/users/C_Chell\",\"object\":\"https://mastodon.scuttle.org/users/scronide\",\"signature\":{\"type\":\"RsaSignature2017\",\"creator\":\"https://equestria.social/users/C_Chell#main-key\",\"created\":\"2018-08-24T06:43:36Z\",\"signatureValue\":\"XiUVkaVE1Uifz4OTpKDxxdpeTVQCswwVEHHWEajI4FS2+lyKcVPQggktV795y86QqAIPbhfckx+Uw0pdWmbc2uLakQ4PCiVjy5iXv1NupbNyKgm3Ro3uWQAEqWOEPx4M6KTL1gV4bhHpa0OTPB0frDxu0TyVPBO60G+nuvYZdJVAMDwFgFXcD+Od4ZTpKY3xiZ5xcHeO6xWeV5X7m0LwYGiC2XniBoaD70Ta7tKoLMSi3ax40mS69bt6wqimut3OHPaGQ49UXuRrgnpdO6m8U4mN6HcU9MaySs1QfHtoAifnCjQgwJG5Iz+lzlMJz5VEutkqe1w6WVqsm/hlpNpWdw==\"}}", 16, "https://mastodon.scuttle.org/users/scronide/inbox"
	
Mastodon::UnexpectedResponseError: Delivery failed for https://mastodon.scuttle.org/users/scronide/inbox: https://mastodon.scuttle.org/users/scronide/inbox returned code 500

And when I dig more, I find many errors on the same format : 
Mastodon::UnexpectedResponseError: Subscribe failed for ***@framapiaf.org: https://framapiaf.org/api/push returned code 503

Mastodon::UnexpectedResponseError: Subscribe failed for ***@mastodon.gougere.fr: https://mastodon.gougere.fr/api/push returned code 503

And more for many instances.

How can I see the details of failed requests ?

**Comment by c-chell** [comment]
After some search and check with another instance admin, I finally find this is the NGinx configuration that cause this problem.
Some http security headers made the other instance confuse.
After correcting them (they are add by the previous admin so I totally forgot to tell about them, I even didn't think it can cause the error) it's seems to work again.

The headers "Content-Security-Policy" and "Public-Key-Pins" are wrongly configured with some line return in the header and NGinx reproduce them without remove the line return.

I wait for feedback of my users, to see if all works right,  before closing this thread.

**Comment by c-chell** [comment]
All seems to work fine, no negative feedback.
Sorry for the mistake, but each mistake you make helps you to know new things.

**Comment by njouanin** [comment]
I'm currently facing the same problem (remote users can't follow local accounts due to : 503: Remote SSL certificate could not be verified
Can you be more precise about the nginx fix you mention ?

**Comment by c-chell** [comment]
In my case, I see in the configuration of NGinx the forced security headers were in multiline instead of  one line (the previous admin write them like it was in his Apache configuration).

But for your SSL problem, have you tried to update your trusted root certificates ?
Or trying to access on your webrowser to see if you have any warning ?

**Comment by njouanin** [comment]
Here is a test I've done : `curl -v http://beerfactory.org/.well-known/host-meta` redirects to `https://mastodon.beerfactory.org/.well-known/host-meta` which doesn't report any SSL alert.
Also, `curl "https://mastodon.beerfactory.org/.well-known/webfinger?resource=nico@beerfactory.org"` doesn't report any SSL problem.

**Comment by c-chell** [comment]
I have exactly the same message error when I try to follow this account.
When I try a remote follow, I end on error page on my instance.
But I can't find where the mastodon logs are (I already find for NGinx and some other files, but not the Mastodon log files).
I can't help you more until I find them.
Sorry.

**Comment by dlitz** [comment]
In case this helps anyone: Check that your server's date/time is being synchronized via NTP.  My server's clock had drifted by a few minutes away from the real time, causing signature failures and 401 errors from basically everyone.  I only noticed when I saw a cryptic error "Aws::S3::Errors::RequestTimeTooSkewed" in the logs, among many others that were less informative.
