### ISSUE TITLE
Password reset appears to be broken

### ISSUE THREAD

**Issue by enebo** [tootsuite/mastodon#838]
Not entirely sure if this should be reported against the OSS project or not but here goes.  I accidentally rebooted my machine and I did not save my generated password.  So time to reset it.  I get an email with a link to reset my password but when I follow the link I get this back:

```json
{"error":"The access token is invalid"}
```

I have tried this a few times (as the time of this report) and it appears to be broken.

I realized that I forgot to point out my id is enebo on mastodon.social server.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
@enebo Did you ever get your password reset?

**Comment by enebo** [comment]
@ashfurrow wow...sorry I forgot to update this.  I tried about 3-4 days ago and it reset.  The only issue now is my timeline is now empty saying I follow no one...but if I click on them they say I follow them?  Different issue most likely but I maybe it is from reset.

**Comment by ashfurrow** [comment]
No worries! That does sound like a different problem, would you mind opening a new issue for that?
