### ISSUE TITLE
2.4.4: `reblogs_count` undefined

### ISSUE THREAD

**Issue by waferbaby** [tootsuite/mastodon#8382]
Hello! Just updated to 2.4.4 (standalone, no Docker). Done all the migrations, bundle and yarn updates, restarted the services, and if I log in to my account it's throwing 500s. I'm seeing this:

```
Aug 23 02:06:24 waferbaby.com bundle[628]: Did you mean?  reblogs):
Aug 23 02:06:24 waferbaby.com bundle[628]: [0cb5ed29-79de-4b73-a762-67d68ed40f06]
Aug 23 02:06:24 waferbaby.com bundle[628]: [0cb5ed29-79de-4b73-a762-67d68ed40f06] app/controllers/api/v1/timelines/home_controller.rb:13:in `show'
Aug 23 02:06:27 waferbaby.com bundle[628]: [16f336a8-b932-4abe-9e72-cb35d8a5f9ff] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=500 error='NoMethodError: undefined method `reblogs_count' for #<Status:0x0000557f0a7da288>
Aug 23 02:06:27 waferbaby.com bundle[628]: Did you mean?  reblogs' duration=108.89 view=0.00 db=4.21
Aug 23 02:06:27 waferbaby.com bundle[628]: [16f336a8-b932-4abe-9e72-cb35d8a5f9ff]
Aug 23 02:06:27 waferbaby.com bundle[628]: [16f336a8-b932-4abe-9e72-cb35d8a5f9ff] NoMethodError (undefined method `reblogs_count' for #<Status:0x0000557f0a7da288>
```

I've tried a manual `Rails.cache.clear` in the console, but that didn't seem to fix it. Any ideas?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
Uh, 2.4.4 shouldn't have changed that.
The method was added in master because up until now it was a normal attribute (and should still be in 2.4.4).
Are you sure you ran the migrations from 2.4.4 and not master…?

**Comment by Gargron** [comment]
I checked all commits in the stable-2.4 branch and nothing touches reblogs_count, so i am not sure what's going on.

**Comment by waferbaby** [comment]
@thibg @gargron Crap - I was on master. Is there a way to fix this state? 😞

**Comment by ThibG** [comment]
@waferbaby yes, `db:rollback` while still on master, then checking out v2.4.4 and doing the usual upgrade path.
You may lose status counts though.

**Comment by waferbaby** [comment]
@thibg Worth it - thank you so much!

**Comment by Gargron** [comment]
If you were on master anyway you could've just upgraded to latest master I guess, especially if by the looks of it you had the counters migration already behind you.

**Comment by waferbaby** [comment]
(FYI, the rollback and 2.4.4 upgrade still didn't work - I managed to make it happy by manually adding `favourites_count` and `reblogs_count` to the `Statuses` table :sweats
