### ISSUE TITLE
Switch to LDAP Auth, partially good

### ISSUE THREAD

**Issue by osauzet** [tootsuite/mastodon#8383]
I recently switch to ldap auth, and i works partially :
- for existing users before migration (name are same as uid) : it works 
- for the users present in the ldap but until now not connected to mastodon: the authentication does not pass.

My setup :
- debian 8
- mastodon 2.4.3

For my migration i edit : .env.production and add :
LDAP_ENABLED=true
LDAP_HOST=ldap.xxxxxx.fr
LDAP_PORT=636
LDAP_METHOD=simple_tls
LDAP_TLS_NO_VERIFY=true
LDAP_BASE=ou=People,dc=xxxxxx,dc=fr
LDAP_BIND_DN=uid=aaaa,ou=bbbb,ou=ccccc,dc=xxxxxx,dc=fr
LDAP_PASSWORD=zzzzz

and i do :
stop mastodon service (all : web/sidekiq/streaming)
bundle install
yarn install
RAILS_ENV=production bundle exec rails db:migrate
RAILS_ENV=production bundle exec rails assets:precompile
start mastodon service

In log i can see :

Aug 23 14:13:56 mastodon bundle[12005]: [0e90c197-c410-4af7-975d-379905a4d08c] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=500 error='NoMethodError: undefined method `exchange' for #<Resolv::DNS::Resource::IN::A:0x000055891e3f50f0>' duration=58.65 view=0.00 db=6.78

One note : my ldap server domain are not the same as mastodon server domain, because in .env.production i use : LOCAL_DOMAIN

did i make a mistake or forget about the change of  "local-auth / ldap-auth"  ?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [2.4.3](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by renatolond** [comment]
I'm not very knowleadgeable in this LDAP flow, but this issue:

```
NoMethodError: undefined method `exchange' for #Resolv::DNS::Resource::IN::A:0x000055891e3f50f0
```

looks like an issue in the email validator, I think it was fixed on #8076, can you update to 2.5.0 and try again?

**Comment by renatolond** [comment]
Do you still have the issue on 2.5.0?

**Comment by osauzet** [comment]
Ok, sorry for the response time, i have some difficult whith the migration psql-94 -> psql-96

So, after migrate in 2.5.0 i have no bug ! -> the new "ldap-user" can log in :-) 

Thanks for your help !
Now, I hope the students of my organization will appreciate mastodon ;-)
