### ISSUE TITLE
Error 422 when attempting to login without cookies enabled

### ISSUE THREAD

**Issue by localhost** [tootsuite/mastodon#84]
This results in a somewhat confusing error: `The change you wanted was rejected (422)` -> `This file lives in public/422.html`.

**Comment by Gargron** [comment]
This is CSRF protection by Rails. I'm not sure what can be done about this (I'm not going to disable CSRF protection). You can't login anywhere without cookies so not sure how big of a problem this is?

**Comment by localhost** [comment]
I guess login without cookies isn't a problem as such, but maybe the `public/422.html` error page could be improved to give a hint?
