### ISSUE TITLE
[Feature] Restrict username length - 3 letter minimum?

### ISSUE THREAD

**Issue by ashleyhull-versent** [tootsuite/mastodon#8402]
I've got people signing up with @x and I'd rather not.

**Comment by Gargron** [comment]
What's wrong with single-letter usernames, if people want them?

**Comment by ashleyhull-versent** [comment]
I don't think this should be a hard limit.. I'd love the ability to have a configuration tho

I think @gargron is more "personal" than "@g" - but that's a personal choice. Just an idea.
