### ISSUE TITLE
“Webpacker can't find public.js in /mastodon/public/packs/manifest.json”

### ISSUE THREAD

**Issue by bdesham** [tootsuite/mastodon#8403]
I’m trying to run Mastodon 2.4.3 via Docker Compose 1.22.0 under Ubuntu 16.04.5. As in #3651, I had to add a line to docker-compose.yml with a volume mapping of `./public/packs:/mastodon/public/packs` for the `web` service. I had some trouble running `docker-compose run --rm web rails assets:precompile`—I’m on a VPS with relatively little memory—but the command was able to complete successfully on my laptop so I copied the resulting `public` directory to within the `mastodon` directory on my VPS.

Whenever I try to load the web app, I get a 500 error in the browser. The corresponding log output is this:

```
[c6df0b58-0681-4043-affe-388e47f513b5] Chewy request strategy is `bypass`
[c6df0b58-0681-4043-affe-388e47f513b5] method=GET path=/@username format=html controller=AccountsController action=show status=500 error='ActionView::Template::Error: Webpacker can't find public.js in /mastodon/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
' duration=2194.85 view=0.00 db=163.20
[c6df0b58-0681-4043-affe-388e47f513b5]   
[c6df0b58-0681-4043-affe-388e47f513b5] ActionView::Template::Error (Webpacker can't find public.js in /mastodon/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest. 
Your manifest contains:
{ 
}
): 
[c6df0b58-0681-4043-affe-388e47f513b5]     1: - content_for :header_tags do
[c6df0b58-0681-4043-affe-388e47f513b5]     2:   = javascript_pack_tag 'public', integrity: true, crossorigin: 'anonymous'
[c6df0b58-0681-4043-affe-388e47f513b5]     3:  
[c6df0b58-0681-4043-affe-388e47f513b5]     4: - content_for :content do
[c6df0b58-0681-4043-affe-388e47f513b5]     5:   .container-alt= yield
[c6df0b58-0681-4043-affe-388e47f513b5]   
[c6df0b58-0681-4043-affe-388e47f513b5] app/views/layouts/public.html.haml:2:in `block in _app_views_layouts_public_html_haml___1190977649280270000_47256829223440'
[c6df0b58-0681-4043-affe-388e47f513b5] app/views/layouts/public.html.haml:1:in `_app_views_layouts_public_html_haml___1190977649280270000_47256829223440' 
```

I can verify that `mastodon/public/packs/manifest.json` exists and contains hundreds of lines. What am I doing wrong?

(This error message is similar to the one in #3251 but it seems to be for a different underlying reason.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashleyhull-versent** [comment]
I think you've fallen into a hole I did because the doco was slightly off for docker.

1) git checkout v2.4.3
2) `image: tootsuite/mastodon:v2.4.3` in docker-compose for the three parts.
3) `docker-compose build`

should resolve this issue... I believe they're changed the "upcoming" 2.5.0 docker format not to require the packs/asset paths.

**Comment by bdesham** [comment]
Shoot, you’re right! I did set the `image` in the docker-compose but it didn’t even occur to me that I should check out the corresponding tag in Git too. Thank you!
