### ISSUE TITLE
Private Instance

### ISSUE THREAD

**Issue by rawkode** [tootsuite/mastodon#8406]
Hey!

Mastodon is pretty awesome, so thank you. I know that it's a federated network, but it's also the best micro-blogging software too.

I'd like to run a Mastodon server for my family to share updates, but without any public toots or federation.

I can lock down sign-ups, but I don't see a way to restrict public profiles.

Is this possible, or could it be added?

Thanks

**Comment by ThibG** [comment]
The `WHITELIST_MODE` usable since 3.1 should correspond to your needs.
