### ISSUE TITLE
Stylesheets not found ?

### ISSUE THREAD

**Issue by celri** [tootsuite/mastodon#841]
Hi ! I just install mastodon with docker and i'ts work! except the stylesheets (and not only probably ahah) but I can sign up.

Thanks

<img width="1280" alt="capture d ecran 2017-04-04 a 15 39 54" src="https://cloud.githubusercontent.com/assets/26901267/24659823/1ff37aea-194e-11e7-836d-8201dc2f9106.png">

**Comment by RaitoBezarius** [comment]
You may have forgotten to add in your NGINX an entry about static files (public).

**Comment by Terathiel** [comment]
Having the same problem here. Think my NGINX config checks out, it's just that the assets aren't there - or rather, when I poke into public/assets/, they've all got significantly longer filenames than expected. (I still don't know where the stylesheets are.)

Am I just foolishly pointing nginx at the wrong folder?

**Comment by celri** [comment]
@RaitoBezarius Thnaks I think it's that but I don't know how to do this

**Comment by Korko** [comment]
Just had the same problem.
Your public/assets/ directory should contain files with name like hashes (e.g. mastodon-23c55fbb7f8d41f47140b8d4a9eabd809519cc097051ead37a1403d9323ef05b.jpg)
If not, run `docker-compose run --rm web rails assets:precompile`

And then, just restart your docker: `docker-compose up -d`

**Comment by celri** [comment]
@Korko Yes I have those files
<img width="250" alt="capture d ecran 2017-04-04 a 16 49 53" src="https://cloud.githubusercontent.com/assets/26901267/24662926/d6fb7c6c-1956-11e7-8913-5753bab1f1b8.png">

**Comment by Korko** [comment]
Then restart your docker, it will link to those files instead of stylesheets/ (I suppose those are dev files)

**Comment by celri** [comment]
@Korko Same prob, it can be my nginx config maybe ?

**Comment by celri** [comment]
@Korko according to the source code it's <link rel="stylesheet" media="all" href="/stylesheets/application.css" /> and domain/stylesheets/application.css is a 404

**Comment by celri** [comment]
Hm ok I just run a `docker-compose build` and `docker-compose up -d` and now it's works...

Thanks !
