### ISSUE TITLE
Disable follow button until 5 seconds after account has loaded

### ISSUE THREAD

**Issue by Angular-Angel** [tootsuite/mastodon#8410]
I've regularly had this problem where I load an account, see the follow button, go to click it, then find out I'd already followed the person and so just unfollowed them, and then have to follow them again. This could be avoided in the follow button were disabled until after it's loaded that information and given the user a chance to process. maybe with a different graphic until then? :/

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by zackw** [comment]
I have also had this problem.
