### ISSUE TITLE
FixReblogsInFeeds migration fails

### ISSUE THREAD

**Issue by egypturnash** [tootsuite/mastodon#8414]
So I have been a lazy admin and I have not touched my Mastodon installation since 2.0.0.

I've gotten my local dev installation up to 2.4.4 and waded through dependency update hell to the point where I can actually try doing a migration, and it's running fine until it stops cold with this:

Migrating to FixReblogsInFeeds (20170920032311)
== 20170920032311 FixReblogsInFeeds: migrating ================================
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

nodename nor servname provided, or not known

[lengthy stack dump omitted, see attachment]

Digging around reveals that this is the only migration that actually tries to talk to redis, and it is an attempt to speed up migrations for large instances by running a Lua script. #5538
[fixreblogstrace.txt](https://github.com/tootsuite/mastodon/files/2319548/fixreblogstrace.txt)

Suggestions? Ugly hacks? Workarounds?

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). 2.4.4 to be precise.
[fixreblogstrace.txt](https://github.com/tootsuite/mastodon/files/2319560/fixreblogstrace.txt)

**Comment by Gargron** [comment]
Why *isn't* Redis accessible? It should be because that migration is for data that is in Redis.

Ugly hack if you absolutely don't want to have that for some reason, edit that migration file and remove everything in the `up` method.

**Comment by egypturnash** [comment]
Redis is running, too. I swear. This migration just doesn't wanna talk to it. What the heck.

My production instance has all of 200 users so UGLY HACK IT IS. It seems to have gotten through successfully, off to the next place migration breaks for me. Thanks!
