### ISSUE TITLE
New instance unable to connect to iOS apps

### ISSUE THREAD

**Issue by gnppn** [tootsuite/mastodon#8434]
Hi!

I installed a new instance today (https://masto.media) and I'm unable to connect the only user to Amaroq and Toot iOS apps. Client-side, I get an error and no login page.

Server-side, `journalctf -xf -u mastodon-*` gives me this:

> method=POST path=/api/v1/apps format=*/* controller=Api::V1::AppsController action=create status=500 error='NoMethodError: undefined method `confidential' for #<Doorkeeper::Application:0x00007f8c4d4daa68>' duration=57.30 view=0.00 db=1.50
> NoMethodError (undefined method `confidential' for #<Doorkeeper::Application:0x00007f8c4d4daa68>):
> app/controllers/api/v1/apps_controller.rb:5:in `create'

I don't have any idea on how to fix this, and didn't found any help in the previous issues. Any hint would be appreciated.

Thanks!

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on **version 2.4.5** and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
It seems like you haven't run db:migrate?

**Comment by gnppn** [comment]
Thanks a lot, that was it! I didn't see it while updating.

I hope that'll be useful to someone else.
