### ISSUE TITLE
API call or command for bulk updating emoji

### ISSUE THREAD

**Issue by sorenbug** [tootsuite/mastodon#8435]
I want to be able to bulk delete and bulk upload (or bulk update) emoji to my mastodon instance, specifically [Mutant Standard](https://mutant.tech). Every update makes changes and I don't want to go through 14,000 images manually every time there is an update.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
What if there was a command-line interface for it like `./bin/tootctl emoji import ./some_archive.zip`?

**Comment by sorenbug** [comment]
That would be better, however:
 - I want to prefix all the images in the zip
 - They are not all images, and only images should be uploaded
 - They are all in sub or sub-sub directories (i.e. not top-level)

**Comment by rugk** [comment]
As for this Mutant emoji thing, it seems to be they already have a way to import Emojis into Mastodon: https://mutant.tech/use/#mastodon (the "Experimental option" seems to use some script)

**Comment by sorenbug** [comment]
@rugk 
1. Will it clear out existing mustd emoji?
2. Will it prefix the new mustd emoji?

**Comment by rugk** [comment]
I have no idea, ask the devs of that thing.
Apart from that this issue is closed and you now have a CLI interface. :smile:

**Comment by sorenbug** [comment]
![a](https://i.gerdere.date/i/0n3l.png)

How to fix?

**Comment by Gargron** [comment]
`bundle install`
