### ISSUE TITLE
[bug] Unchecked "whole word" when creating filter but it reverts to checked

### ISSUE THREAD

**Issue by kevinisaacson** [tootsuite/mastodon#8448]
I made a filter for "nazi" and unchecked the whole word box. I still see toots with that string (nazis, nazism, etc) so I looked at the filter and the whole word box was checked again. Deleted filter and recreated, same thing. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by PatrickRWells** [comment]
I also see this behavior on an instance running 2.4.4, but not in a development instance 2.5.0rc1.

**Comment by Gargron** [comment]
Yes, this is a bug with saving the "whole word" checkbox that has been fixed in latest master.

**Comment by kevinisaacson** [comment]
So this is something my instance admin has to update? I don't know how to tell what version they're running.

**Comment by PatrickRWells** [comment]
Yes. You will have to wait for them to update the instance.
