### ISSUE TITLE
git fetch && git checkout v2.4.5 failed.

### ISSUE THREAD

**Issue by ashleyhull-versent** [tootsuite/mastodon#8450]
checkout for v2.4.5 tag is borked?

`mastodon@ip-10-32-0-30:~/live$ git fetch && git checkout v2.4.4`
`M	docker-compose.yml`
`HEAD is now at 612d02028 Bump version to 2.4.4`
`mastodon@ip-10-32-0-30:~/live$ git fetch && git checkout v2.4.5`
`error: pathspec 'v2.4.5' did not match any file(s) known to git.`

**Comment by JMendyk** [comment]
Could you provide output of `git remote -v` command?

**Comment by qguv** [comment]
You need to get tags specifically, try `git fetch --tags`.

**Comment by ashleyhull-versent** [comment]
ok. this was pure user error. sorry. I just had ghost metadata.
