### ISSUE TITLE
Boost animation doesn't work

### ISSUE THREAD

**Issue by imbsky** [tootsuite/mastodon#8452]
Boost animation does not work on master.
I don't know which commit is the cause.
But I got this issue after `Upgrade Doorkeeper to 5.0.0` `b37ae645788e1951e3b1737519f32803e5e1b6ad`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Resolved by #8455
