### ISSUE TITLE
Toot ID different than the one in URL for social interaction

### ISSUE THREAD

**Issue by rugk** [tootsuite/mastodon#8459]
STR:
1. Go to https://mastodon.social/@Gargron/100254678717223630.
2. Click on `@Vale@ganbara.nai` reply "do it" on one interaction button.

**What happens:**
A new popup happens. It has the URL `https://mastodon.social/interact/100254680557068529`.
AFAIK the URL has the toot ID in there, i.e. the URl says the toot ID is: `100254680557068529`.

Now hover over the "date field" (either in this "remote interact" form or the original site) and you get this URL: `https://pawoo.net/@valerauko/100254680484038566`.

It also has the toot ID, but this time, it's different. So to compare the IDs:
```
100254680557068529 - URL in remote interact
100254680484038566 - actual toot ID
```

When you submit the form I get to `https://mastodon.social/web/statuses/100254680557068529`, i.e. the "correct" toot URL.

Checking this for some other toots, I also get different IDs. But only sometimes, not always. That's strange.

**What should happen:** As always, toot ID should be the same.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). (no, on mastodon.social)

**Comment by Gargron** [comment]
Wait are you comparing toot IDs on different servers? They're always going to be different.

**Comment by nightpool** [comment]
the database id for individual statuses varies from server to server.

**Comment by rugk** [comment]
Thansks FYI, but…
No, actually it's the same server. You can also, more easily, see it here (same toot):
![compareids](https://user-images.githubusercontent.com/11966684/44630148-6c5cba80-a959-11e8-8fbd-dc46c610bafb.gif)

Or is there some kind of "external toot ID" and "internal toot ID"? Does this concept exist?

**Comment by rugk** [comment]
Ah, forget it, the toot I am hovering over actually is a remote toot. Uuups, forgot that…

So it seems, i cannot rely on the information in the URL, at all. It's the local toot ID that may be different to the one, I want.
