### ISSUE TITLE
If redis is not running during user creation, user is still added to db

### ISSUE THREAD

**Issue by SirCmpwn** [tootsuite/mastodon#847]
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by krainboltgreene** [comment]
Redis *shouldn't* stop a record from being created. Instead, user creation should trigger the redis commands and handle failing gracefully.

**Comment by SirCmpwn** [comment]
You get dumped on an error page and the confirmation email is not sent.

**Comment by krainboltgreene** [comment]
That sucks, okay, this is definitely something to tackle!

**Comment by Gargron** [comment]
I am assuming this is about the user confirmation e-mail being queued up into Sidekiq (redis). Redis is kind of a hard requirement here, no way around it.

**Comment by SirCmpwn** [comment]
It's about what I said it's about. If during deployment you forgot to start up redis, registering the first user account creates a condition in which you must wipe the database in order to recover, because it never sends you the confirmation email with which you can activate the account. It should fail more gracefully than that.

**Comment by Gargron** [comment]
1. It is possible to fix this without wiping the db (use "I didn't get a confirmation e-mail")
2. It is like saying that the application should work even if the db is down. Redis is an important database for Mastodon.

**Comment by SirCmpwn** [comment]
It's not like saying that at all. It's like saying the application should detect that the db is down before it makes any stupid mistakes because of it. Creating an invalid situation because of an error case is just shitty code.
