### ISSUE TITLE
I Cannot Recommend This Place

### ISSUE THREAD

**Issue by LWFlouisa** [tootsuite/mastodon#8475]
I've met way to many moderators that have to many different ideas of administrative practices. You have dictators that wont to control the entire topic on an instance. And on the flip side, you have instances that are geared toward nothing but shit posting.

And actual trans people, not transtrenders, their voices get suppressed. This place is not about left leaning views, its about Communism, not Communitarianism.

I can't even find something as basic as something Yacy gets down pat: the ability to start something under a single program. That or its so hidden, I have to look for it. Its not my technical ability, because Localtunnel has its start function immediately obvious.

If it were as easy as the instructions say, then I would have my own instance up by now. I am not a non technical user.

**Comment by nightpool** [comment]
This issue tracker is not the place to discuss your disagreements with the mastodon community,  accuse people of supporting the evil spectre of "Communism" or dismiss other's experiences. Trolling will not be tolerated.

Mastodon is pretty easy to run if you follow the guide, but by and large it's not meant to be run by end users, or people without any web server hosting experience—instead, people are encouraged to form self-reliant communities that have dedicated system administrators.

see https://github.com/tootsuite/mastodon/issues/4576 for more discussion of this topic.
