### ISSUE TITLE
Enabling nginx proxy caching breaks HSTS

### ISSUE THREAD

**Issue by 33b5e5** [tootsuite/mastodon#8487]
After upgrading raki.social to 2.5.0rc1, I noticed that the Mozilla Observatory score dropped from B to C:

https://observatory.mozilla.org/analyze/raki.social

The drop seems to be because HTTP Strict Transport Security is now disabled. I looked around on instances.social and noticed many other instances running 2.5.0rc1 now have a C as well.

I didn't change any of the configs recently. It doesn't look like anything changed in the nginx.conf, and I can see that the relevant add_header line is still there and active in the nginx config:

`raki:~$ sudo nginx -T | grep Strict-Transport-Security`
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
add_header Strict-Transport-Security "max-age=31536000";
```

Nonetheless, Strict-Transport-Security isn't coming through in the headers anymore. I checked using Chrome/Firefox dev tools as well as doing `curl -v https://raki.social/`. 

I figure it must be disabled at the Rails level, but I'm not sure where to look.

Was Strict-Transport-Security disabled on purpose? How do we re-enable it?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Weird, I don't think Rails has any capacity to remove a header that is being added in nginx though.

**Comment by 33b5e5** [comment]
@Gargron Huh, yeah... that makes sense now that you say it. nginx is effectively in front of Rails. I tried restarting nginx but no change. I'm stumped at the moment.

Other notable instances running 2.5.0rc1 and missing Strict-Transport-Security:

mastodon.social
mastodon.cloud
hostux.social

I don't know if these instances ever had HSTS enabled or not though. @Gargron was it enabled on mastodon.social before?

**Comment by Gargron** [comment]
I think I found it and it has nothing to do with 2.5.0 but instead with the proxy caching additions.

From [nginx docs](https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/):

```
# Because this 'location' block contains another 'add_header' directive,
# we must redeclare the STS header
```

The [proxy caching guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Tuning.md#using-nginx-proxy-caching) adds an add_header to the proxy location block, but does not re-add the HSTS add_header.

**Comment by 33b5e5** [comment]
@Gargron yep. I added proxy caching per the Tuning guide around the same time I upgraded, then totally forgot about the change. 🤦‍♂️  Glad the issue was caught though.

**Comment by 33b5e5** [comment]
I can confirm adding the second add_header line in the proxy block resolves the issue.

**Comment by 33b5e5** [comment]
Edited the subject to be more descriptive. Thanks for the quick diagnosis and fix.

**Comment by ThibG** [comment]
Not an issue in Mastodon? I haven't checked the docs, but if they are wrong or do not worn about this issue, can you open a bug against them?

**Comment by 33b5e5** [comment]
@ThibG no need, Gargron already updated the documentation here: https://github.com/tootsuite/documentation/commit/81b77f77618be02b54dc574ef7ed078292327f19
