### ISSUE TITLE
Cannot change credentials on single user mode

### ISSUE THREAD

**Issue by Korko** [tootsuite/mastodon#849]
Hi,

On single user mode, the credential menu redirects to the home. Had to switch back to non single user mode to edit my password and then close again the registration.

Korko

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by rhaamo** [comment]
I can confirm this bug too.

**Comment by Gargron** [comment]
It's possible that this is fixed after 5f549818, can you confirm?
