### ISSUE TITLE
/authorize_follow returning 404 on v2.5.0rc1

### ISSUE THREAD

**Issue by mdbraber** [tootsuite/mastodon#8497]
When I'm trying to remote follow a user from another instance my own instance (mastodon.nl on v2.5.0rc1) is giving a 404 on the /authorize_follow URL. Did anything change? I noticed /authorize_follow is giving a 404 as well on other 2.5.0rc1 instances, but redirecting to a login screen on non-2.5.0rc1 instances.

**Comment by mdbraber** [comment]
It seems that /authorize_follow was replaced by authorize_interaction in this commit: https://github.com/tootsuite/mastodon/commit/78fa926ed560e6a9738144bec7e152fa42104139#diff-21497849d8f00507c9c8dcaf6288b136 and it's being discussed here https://github.com/tootsuite/mastodon/pull/8202#issuecomment-415988736

**Comment by mdbraber** [comment]
As a temporary workaround (as the URL parameters seem to be the same) you can add this to your nginx config (nginx will automatically add the URL parameters):

`rewrite /authorize_follow /authorize_interaction;`

**Comment by Gargron** [comment]
I am confused: https://github.com/tootsuite/mastodon/blob/master/app/models/remote_follow.rb#L47-L51

The "remote follow" dialog gets the URL template from the server without caching, so the "authorize_follow" URL should not be cached anywhere and pre-2.5.0 should correctly detect the new "authorize_interaction" URL.

What gives you the "authorize_follow" URL?

**Comment by mdbraber** [comment]
@gargron I've just disable the rewrite and tried again. I'm getting the error when I'm going to a user on another instance e.g. https://mastodon.technology/@roguelazer and choose 'remote follow'. When I use 'mdbraber@mastodon.nl' as the remote user it gives me a 404 (easy to reproduce). Could it be a disparity between non-2.5.0 instances and 2.5.0 instances?

**Comment by Gargron** [comment]
Actually yes, maybe the webfinger responses from the (2.5.0) server are still cached with their pre-2.5.0 values in nginx.

**Comment by mdbraber** [comment]
@Gargron caching does seem to be the problem, because when I'm trying to use a different user (e.g. 'mastodon@mastodon.nl') for the remote follow it doesn't give the 404. As there's no way to invalidate the nginx cache as far as I can see, I'm still trying to figure out how to solve this.

For now this bug can be closed as it seems to be specific to my situation.

**Comment by ThibG** [comment]
Argh. We could add a redirection. Otherwise you'll have to wait for the 7 days cache to expire…
