### ISSUE TITLE
A reply status in a pleroma thread with CW shows weird mention

### ISSUE THREAD

**Issue by rixx** [tootsuite/mastodon#8502]
I came across a CW'd thread, and the second status in that thread showed a mention of the author if unexpanded, which vanished on expanding. Here is an example: https://pleroma.panoptikum.io/notice/10860, which looks like this in Mastodon (note the mention in the unexpanded state):

![screenshot_2018-08-28 chaos social 3](https://user-images.githubusercontent.com/2657547/44719197-d349b300-aac2-11e8-83a0-0f32449b13ec.png)
![screenshot_2018-08-28 chaos social 2](https://user-images.githubusercontent.com/2657547/44719198-d3e24980-aac2-11e8-9d7f-33fa65b504fb.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
Pleroma sends Mention records when someone self-replies, but it doesn't include them in the actual text of the status itself. that's why they display like this.

**Comment by rixx** [comment]
I'd still say it's a UI bug in mastodon, as this behaviour is confusing to users.

**Comment by Gargron** [comment]
Not a bug in Mastodon in my opinion. If there's mention metadata in the post, that means there's mentions. The text of the post does not matter for this, but ideally they should be the same.

**Comment by rixx** [comment]
I don't think that "show more" should ever *remove* something from display, that's really irritating behaviour.

**Comment by kaniini** [comment]
we (Pleroma) should probably remove Mention metadata from self-replies.  Pleroma bug for that is here: https://git.pleroma.social/pleroma/pleroma/issues/280

this bug can be closed.
