### ISSUE TITLE
[UX] "Follow" button too prevalent on a migrated account

### ISSUE THREAD

**Issue by aleksandar-todorovic** [tootsuite/mastodon#8503]
**Note:** This only applies to those who are *not* logged in.

I have migrated from one account to another one. Now, when I visit my old account (while not being logged in), I see this:

![screenshot from 2018-08-28 14-03-32](https://user-images.githubusercontent.com/4890548/44721748-2de70d00-aacb-11e8-9649-cf317a038583.png)

As you can notice from the screenshot above, the "follow" button is not only visible, but a higher color contrast makes it the most prominent element on the page. The text below it seems almost unnoticeable.

Proposal: Something visually similar to how it's done while being logged in:

![screenshot from 2018-08-28 14-07-43](https://user-images.githubusercontent.com/4890548/44721960-d1382200-aacb-11e8-84da-21ff8c98a48b.png)

In my opinion, the second screenshot gives a much better impression that the account is migrated from. Even with `[old]` added to my name in the previous sentence, I think that the people who glance at the first screenshot will not figure out that the profile is indeed migrated from. Instead, they'll be lured by the follow button as the primary call-to-action.

**Note no. 2:** This is _not_ a request to remove the follow button completely, just making it less prominent than it currently is in this specific scenario.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by dracos** [comment]
Have had a few people follow me even after moving too, have submitted a PR that greys out the whole header to match what happens in the in-column view (including the follow button), as a suggestion.
