### ISSUE TITLE
Javascript error in the surf browser

### ISSUE THREAD

**Issue by xsgb** [tootsuite/mastodon#851]
Hello! Just got a JS error using the surf browser, wich is using libwebkitgtk and  libjavascriptcoregtk ( 2.4.9-1~deb8u1 here ). Nothing is displayed but the background color. 

This is what surf shown in stderr

`
** Message: console message: https://assets.mastodon.social/assets/application-33586e92d791d0991584e58f09da565a469691eb6eaebf4aba1c89e1d5d44884.js @29: TypeError: undefined is not a function (evaluating 'Number.isNaN(1*x)')
`

Anyway; thanks a lot sir for your successful work, have a nice day.

**Comment by xsgb** [comment]
I've just tried with qupzilla, it seems to behaves identically. After login, the dynamic page content don't show up.

**Comment by AntoineVe** [comment]
Hi,
I've just install a fresh mastodon instance but I got a similar error. Nothing but background color is displayed. 

Here is the js console error : 

> 15:18:58,934 ReferenceError: en is not defined 1 application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:38:8934
> 	[125]< https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:38:8934
> 	s https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:27:29734
> 	s/< https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:27:29793
> 	[133]< https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:39:8279
> 	s https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:27:29734
> 	s/< https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:27:29793
> 	[42]< https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:32:3500
> 	s https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:27:29734
> 	s/< https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:27:29793
> 	[1]< https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:27:30156
> 	s https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:27:29734
> 	e https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:27:29908
> 	<anonyme> https://mastodon.antoineve.me/assets/application-2d210cd0d7b94a3e491b59ed4a9ca1290e5970a4b922adc74e02ba4789f0ccfe.js:27:29499

It seems we are missing some quotes, `exports["default"]=en` may be `exports["default"]="en"`

**Comment by k8tems** [comment]
Had the same problem
Deleting all the assets and recompiling fixed the issue for me

**Comment by Gargron** [comment]
Mastodon JS uses some modern language features. Unfortunately, I cannot guarantee it working with every flavour of browser engine.
