### ISSUE TITLE
remove_remote gives an error after upgrade to v2.5.0rc1

### ISSUE THREAD

**Issue by laanwj** [tootsuite/mastodon#8513]
The remove_remote media cronjob as documented [here](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md#remote-media-attachment-cache-cleanup) gives a new error after upgrade to tag v2.5.1rc1:

```
$ cd /home/mastodon/live && RAILS_ENV=production /home/mastodon/.rbenv/shims/bundle exec rake mastodon:media:remove_remote
ESC[0;33;49mPlease use `./bin/tootctl media remove --help` directlyESC[0m
```

I tried using the `tootctl` as specified, but that fails too:
```
RAILS_ENV=production ./bin/tootctl media remove --help
Traceback (most recent call last):
        4: from ./bin/tootctl:3:in `<main>'
        3: from ./bin/tootctl:3:in `require_relative'
        2: from /home/mastodon/live/lib/cli.rb:3:in `<top (required)>'
        1: from /home/mastodon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/mastodon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- thor (LoadError)
```

I have seen issue  #8145 and #7882, which says this job has been "queued into sidekiq now".

- Does this mean I can safely remove it from cron?
- Should it be removed from the production documentation?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
re: sidekiq—the remove remote media task *executes* in sidekiq but it still needs to be *triggered* from the command line, since not all admins are interested in removing remote media at the same depth or frequency

**Comment by laanwj** [comment]
I thought I did! running 
```bash
cd ~/live
bundle install --deployment --without development test
```
again gives me:
https://gist.github.com/laanwj/4f1fca161991329b872132009f360f06

Which mentions "thor", but for some strange reason it still doesn't work (same error). Could be that I have a package path wrong?
Looks like it's installed in `/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0`.

**Comment by laanwj** [comment]
Oh, apparently I have a package environment in
`/home/mastodon/.rbenv/versions/2.5.1/lib/ruby/2.5.0`
as well as
`/home/mastodon/live/vendor/bundle/ruby/2.5.0`
whoops...

**Comment by laanwj** [comment]
not sure if it  is the intent, but this did it:
```bash
mastodon@galatea:~/live$ RAILS_ENV=production  /home/mastodon/.rbenv/shims/bundle exec bin/tootctl media remove --help

Usage:
  tootctl media remove
```
