### ISSUE TITLE
Server-side and client-side bio count endlines differently

### ISSUE THREAD

**Issue by ariasuni** [tootsuite/mastodon#8514]
Server-side bio character counts endlines as two characters, whereas client-side count it as one character.

For example:

```
t
t
t
```

- when editing, displays 155 characters left (client-side)
- after saving, 153 characters left (server-side)
- when editing again, 155 characters left (client-side)

This is particularly annoying when writing a bio with several endlines, because you can write a bio with the client-side code reporting that it fits into the character limit, but then rejected because the server-side code counted more characters.

**Comment by renatolond** [comment]
Duplicate of #4419, #7485

**Comment by ariasuni** [comment]
Thanks! I couldn’t find the other reports with the words I used for the search.
