### ISSUE TITLE
Show column scrollbars only when necessary

### ISSUE THREAD

**Issue by andi1984** [tootsuite/mastodon#8521]
Instead of showing scrollbars all the time by setting

`overflow-y:scroll`

let the browser decide when to show and not show by setting overflow behaviour to auto.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JMendyk** [comment]
This might result in unpleasant appearing and disappearing of scrollbars when switching between views which have and don't have scrollbars(here: user that has many followers but doesn't follow anyone):

![screencast](https://user-images.githubusercontent.com/9089004/44869431-de047380-ac8d-11e8-9cb7-5048ae15715a.gif)

**Comment by andi1984** [comment]
@JMendyk That's true. Well, it is not clear to me that it is _really_ that unpleasant, but any decision is fine for me. If it is meant to be unpleasant, than someone can decline my PR as well.
