### ISSUE TITLE
[API] Get all users in an instance created after a created_at timestamp?

### ISSUE THREAD

**Issue by davewalk** [tootsuite/mastodon#8530]
I apologize if I should have asked this in the documentation repo instead....

I want to create a bot for a small instance that I am a part of that sends a "welcome" private toot to new users. To do this, I basically need to fetch a list of accounts created after a certain `created_at` date. Is this possible in the API?

It doesn't look like `api/v1/search` would allow for that kind of query (although I'm not very good at reading Ruby code).

I thought one workaround for this would be to get a list of followers for an account that every new user follows, however the list returned is maxed out at 80.

Any way I can do this w/ the API? Thanks!

**Comment by JMendyk** [comment]
_(these are just wild guesses from me so... YMMV)_ 

You could get [`/api/v1/accounts/:id/followers`](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#getting-an-accounts-followers) as you said and use pagination's `since_id` to keep track of last page your bot saw and `id` of last user it tooted. Additionally, you might have to filter out users with ids smaller than `id` of the newest user to notified (assuming that followers are ordered as newest/oldest first).

Important note from API's docs (any why you need to keep `since_id` **and** `id` of newest user you tooted):

> **Note**: `max_id` and `since_id` for next and previous pages are provided in the Link header. It is not possible to use the id of the returned objects to construct your own URLs, because the results are sorted by an internal key.

**Comment by davewalk** [comment]
Ohhh, I see. This should do it. It looks like the Accounts are returned descending by timestamp of follow, so I wouldn't have to page back too far.

Thanks so much! Closing this for now, but it would be nice to have better search functionality for accounts.
