### ISSUE TITLE
[Feature] adduser to AccountsCLI

### ISSUE THREAD

**Issue by ashleyhull-versent** [tootsuite/mastodon#8549]
`tootctl adduser adminbob bob@bob.com temppassword`
`tootctl make_admin adminbob`

or something something.

The Rake task `mastodon:add_user` is interactive and I want to automate these stages.

**Comment by Gargron** [comment]
This is definitely coming in future versions. I intend to move all mastodon-specific rake tasks into tootctl!

**Comment by ashleyhull-versent** [comment]
Completed already.
