### ISSUE TITLE
"Expand All CWs" on public pages

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#8552]
![image](https://user-images.githubusercontent.com/10606431/44945125-f4065700-ada7-11e8-984d-dc43306ccd20.png)

search keywords: cw, content warning, content warnings, show more, show less, permalink, permalinks, thread, toot, page

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by SaxxonPike** [comment]
The ability to auto-expand CWs (perhaps by whitelist, or option to do them all?) would be excellent.

**Comment by bgattet** [comment]
seconded.

**Comment by trwnh** [comment]
Just discovered #7255 as a duplicate. Closing this issue in favor of that other one!
