### ISSUE TITLE
mastodon.social broken in arabic

### ISSUE THREAD

**Issue by BoFFire** [tootsuite/mastodon#8554]
Hi,
mastodon.social is completely broken when I try to access to it with my browser user-agent language is in arabic. (all URLs).
In Farsi, it works. Please, someone to check those `<span` problem in translation.
Thank you :)

**Comment by BoFFire** [comment]
Hi,
Same issue mastodon.social broken again in arabic in the latest RC version.

**Comment by Gargron** [comment]
Somebody undid the fix in #8555. It's the same error. Only one/other are present in the translations, but more than that is required.

**Comment by Gargron** [comment]
Oof, looks like it was you @BoFFire: https://github.com/tootsuite/mastodon/pull/8692/commits/1fc84ebedd28653aee0cc6515ae46ec1d7435a78

Please do not do that. You either need to add zero, one, two, few, many, other; or none of those.

**Comment by Gargron** [comment]
Ref to create a diagnostic command that would prevent this: glebm/i18n-tasks#308

**Comment by BoFFire** [comment]
Hi,
I don't have `zero, one, two, few, many, other` or was I missing something ? These two were separated strings and not as one string asking for plural forms.
