### ISSUE TITLE
Fix for CSS problem resulting in less space for account names

### ISSUE THREAD

**Issue by riking** [tootsuite/mastodon#8556]
Before:
![image](https://user-images.githubusercontent.com/627891/44948922-c1765180-addb-11e8-893f-64313264e182.png)

After:
![image](https://user-images.githubusercontent.com/627891/44948933-f8e4fe00-addb-11e8-9129-4cca2d04176b.png)

Current structure:

```
header.status__info
  CSS: display: flex;
  span
    aside.status__prepend
      ...
    div.status__info__account
      ...
  div.status__info__icons
    ...
```

After:

```
header.status__info
  CSS: display: flex; flex-direction: column;
  span.status__inforow
    CSS: display: flex;
    aside.status__prepend
      ...
    div.status__info__icons
      ...
  div.status__info__account.status__inforow
    ...
```

![image](https://user-images.githubusercontent.com/627891/44948955-8294cb80-addc-11e8-8e85-9b4464ade92c.png)

Non-boost structure:

```
header.status__info
  CSS: display: flex; flex-direction: column;
  span.status__inforow
    CSS: display: flex;
    div.status__info__icons
      ...
    div.status__info__account
      ...
```

CSS edits from browser inspector:

```
.status__info {
  flex-direction: column;
}
.status__inforow {
  display: flex;
  text-overflow: ellipsis;
  overflow: hidden;
}
/* delete rule .status__info > span */
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Our repository doesn't have that kind of style, this issue belongs to glitch-soc
