### ISSUE TITLE
Forbid and terminate accounts dedicated to the selling of goods or services, or the monetization of web contents

### ISSUE THREAD

**Issue by morgothdidnothingwrong** [tootsuite/mastodon#856]
Forbid and terminate aggregative handles. It means any company or any individual who's not here to discuss but to benefit from the Mastodon hype, or to survive the Twitter collapse.

There are already French social media accounts such as Le Figaro, Le Huffington Post, Korben, etc., which only truly means they're here to shitpost and to monetize adsense web content.

For the record, Le Huffington Post claimed to be the first social media handle on Mastodon. Numerama articles only brought Topachat here. It's needless to say that every aforementioned handle is hosted on mastodon.social.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Exagone313** [comment]
Mastodon (the software) should stay neutral. There is a function to block particular instances (domain blocks), and it is the role to the instances to deny this use if they want to.

If a lot of ad-related instances appear, a shared blocklist of instances/users could work, but this would rely on centralization.

**Comment by morgothdidnothingwrong** [comment]
Sure, but the question isn't to technically constraint the instances rather than politically federating on a consensus/vote basis.

Don't hesitate to close the issue if it's irrelevant, but I personally suppose it is. The problem will emerge at some point.

**Comment by HedgeMage** [comment]
I favor closing this issue in favor of someone writing up a good issue, if it doesn't already exist, around general abuse-management tools.  It should be 100% up to individual instance maintainers what content they consider to be abusive or otherwise worthy of nuking/blocking.

Note: Mastodon is released under the AGPL, which specifies that it can be run BY ANYONE, FOR ANY PURPOSE, so if the software (rather than instance administrators) started making decisions asked for in this issue, they would be violating the AGPL.

**Comment by morgothdidnothingwrong** [comment]
The AGPL means that no one can sue instance administrators for their moderation or administration management, right? If instance administrators collectively voted and agreed to not federate with instances whose administrators wouldn't respect their democratic and horizontal decision making process, that would be both totally *legal* and technically horizontal.

**Comment by HedgeMage** [comment]
Instance admins can do whatever they want.  My point was that you can't bake such a restriction into the software without violating AGPL.  I still recommend closing this issue, which is filed against the SOFTWARE.

**Comment by morgothdidnothingwrong** [comment]
I recommend waiting until tomorrow (say 5pm GMT) because some instance admins will read that (and maybe engage conversation) later.

I agree that I've been offensive in my first post, and that's not what I had meant but I was late on a university course and I couldn't correct it. This being said, please don't write in caps locks as if you were yelling at me or losing patience (in which case you're free to do something else).

I don't mean to force this idea, I'll let people discuss it and see what happens.

**Comment by riking** [comment]
@Gargron Can I suggest making a separate, issue-only Github repo for mastodon.social policy issues? This issue isn't really relevant to the software itself.

**Comment by ajanvier** [comment]
To address this issue, why not have an option for accounts to declare themselves as "commercial", and another options for users to block commercial accounts posts.
And if the user is a non-declared commercial account, according to the instance rules it may be reported and banned.

**Comment by morgothdidnothingwrong** [comment]
We could implement a Freenet-like Web of Trust as well: "parent users" could upvote or downvote "children users", which impacts the reputation of the "children instances" and the impact of the upvotes or downvotes of "children users", as well as the impact of the upvotes and downvotes of the "parent users" as well.

**Comment by wxcafe** [comment]
This is not a technical issue, it's a political one about how instances are run. I'm closing this, it doesn't have it's place on this issue tracker.
