### ISSUE TITLE
Mastodon does not work well

### ISSUE THREAD

**Issue by diplozoon** [tootsuite/mastodon#8567]
Hello.
I tried to set up Mastodon like [this document](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md).
But, I was displayed "We're sorry, but something went wrong on our end.".
Therefore, when I looked it up, there was an opinion that if you migrate the database it will be resolved.
But my problem was not solved.
I attempted to look at the log by `systemctl status mastodon-*.service` or `journalctl -u mastodon-web`, but the log was not displayed (my server's OS is Ubuntu Server 18.04).
Is there anyone who knows what is wrong with me?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by diplozoon** [comment]
Who can help me?

**Comment by ThibG** [comment]
Did you follow this section? https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md#mastodon-systemd-service-files
What does `systemctl status mastodon-web` say? It should at least say *something* if you've installed the service file.

**Comment by ThibG** [comment]
I don't know about Vultr. What do you mean by “`systemctl status mastodon-web`” did not return anything? Did it say that `mastodon-web.service` could not be found? That the service was running? Anything at all?

**Comment by diplozoon** [comment]
Nothing was output even if that command was executed.

I was able to work around this problem by using Docker.
But this is not an essential solution.
Even if I tried it several times in a way not using Docker, it was only displayed as "We're sorry, but something went wrong on our end.".
Perhaps something was missing from me.
I think that I want to close this Issue because of my fault.
