### ISSUE TITLE
timestamps take too much space

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#857]
given usernames and display names are both naturally long fields, the fact that they frequently get cut off by "X minutes ago" etc is rather silly.

i would propose moving it to be "Xm" for minutes, "Xs" for seconds, and "Xd" for days, to save space and easier parse usernames

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by RyKilleen** [comment]
I'd be happy to tackle this if it's okay!

**Comment by Gargron** [comment]
@RyKilleen Please go ahead! Might be harder than it looks because right now I'm using relative time from react-intl, but they don't have a "shortform" mode, so to replace it, the code needs to be rewritten - that's beside localizations for the dates (maybe we can get away with not localizing s, m, d, mo etc though)

**Comment by RyKilleen** [comment]
@Gargron hmm any interest in Moment.js? There's a React flavor, not to introduce one more dependency off the bat. It's just painless when it comes to time/date, and formatting w/localizing.

**Comment by vramana** [comment]
@RyKilleen date-fns is lighter alternative to moment.js. You can have a look at it.

**Comment by braak** [comment]
As an alternative to shortening the timestamp, it could be moved to the bottom right of the toot. It looks like there is enough space for it there.

**Comment by adamshapiro** [comment]
@braak that could work, although you might need to tighten up the reply/boost/etc buttons, as it is it looks like they'd overlap slightly.

**Comment by hoodiek** [comment]
if such a thing was done i would suggest moving the buttons all the way to the left so they go under the user avi

**Comment by hoodiek** [comment]
@braak @adamshapiro  neglected to @ lol

**Comment by yoanmalie** [comment]
Maybe something like this ? By putting the @ in a new line with a smaller font-size (here 12px).
![toot-username](https://cloud.githubusercontent.com/assets/3357171/24828103/93820688-1c56-11e7-890a-7c3115e2c279.png)

**Comment by vielmetti** [comment]
react-intl has discussed having a short form, here: https://github.com/yahoo/react-intl/issues/393

That issue open since 2016 has a good description of what might need to be changed, perhaps @hoodiek you could engage over there and see if there's some newfound support or allies to do the work.

**Comment by Gargron** [comment]
Oh we actually already did this, but I forgot to tag this issue
