### ISSUE TITLE
Profile page has broken style after upgrading from 2.4.5 to 2.5.0rc2 

### ISSUE THREAD

**Issue by tassaron2** [tootsuite/mastodon#8576]
I started my single-user instance on 2.4.5, using Ubuntu 18.04 without Docker. After attempting an upgrade to 2.5.0rc2, everything seems to be working perfectly (my database and web app are functioning as expected), except for some webpages that have broken styles:
- [my profile page](https://tassaron.com/@brianna),
- the avatar/header displayed above the Upload buttons in the Edit Profile area, and
- the [about/more](https://tassaron.com/about/more) page.

I didn't modify the code except for replacing the 3 favicon images (`apple-touch-icon.png`, `favicon.ico`, `android-chrome-192x192.png`).

I followed [the official guide for updating](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Updating-Mastodon-Guide.md) and the release notes for 2.5.0rc1 which involved migrating the database. I updated the Ruby and Node.js dependencies successfully.

The last message I get from precompiling is this:
>  Rendering errors/500.html.haml within layouts/error
>  Rendered errors/500.html.haml within layouts/error (751.4ms)

Which includes the word "error", but sounds like a success. I don't think I got any real error messages.

Hopefully this is enough information to help me! Thanks :)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tassaron2** [comment]
Fixed it myself by deleting `/live/public/packs` and and re-compiling.

**Comment by clement-analogue** [comment]
The solution should be probably mentioned in the upgrade notes because it happened to me as well.
