### ISSUE TITLE
Allow moderation through API

### ISSUE THREAD

**Issue by codesections** [tootsuite/mastodon#8580]
Moderators of Mastodon instances can currently take several actions through the web UI that they cannot accomplish through the public API:
- Delete toots
- Silence users
- Silence instances
- Resolve/unresolve reports
- etc.

This issue exists to suggest an API be created that would allow moderators to take every action that they can currently take through the web UI.  This would enable third-party tools to be built to help with the moderation process, which would magnify the effectives of moderators.  This, in turn, would help strengthen one of Mastodon's key selling points: that it provides a better-moderated environment than other social networks.

Potential use-cases for a moderation API include:
- Tools to enable easier moderation from a mobile device
- Tools to bulk-resolve certain reports
- Tools to block spam domains based on reported spam
- Tools to manage moderation workload between multiple mods
- Tools to automatically take certain moderation action in extreme cases (e.g., racial slurs)
- Many others that we cannot think of right now.

I believe that Mastodon user @balrogboogie@ceilidh.space is working on a related API, but I don't know the status of that work or whether it would close this issue.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
This is on the 2.6 roadmap

**Comment by bclindner** [comment]
This was pushed back to 2.8. How is it doing? Fedi spam has been getting really really bad as of late (mastodon.technology in particular dealing with a few reports a day now) and we're excited to be able to potentially moderate from apps / write automods to help keep the network clean.
