### ISSUE TITLE
Migration 2.4.5 to 2.5.0 - Yarn - The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by osauzet** [tootsuite/mastodon#8589]
Hi,

Iam in 2.4.5, and whant to migrate to 2.5.0, 
my server are a Debian 8.10 (not whith docker, just native)

i migrate nodejs, actually i have : v8.11.4

git status
HEAD détachée sur v2.5.0

bundle install 
-> no error

But i have this problem whith yarn ->

yarn install
yarn install v1.2.1
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
error mini-css-extract-plugin@0.4.1: The engine "node" is incompatible with this module. Expected version ">= 6.9.0 <7.0.0 || >= 8.9.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [2.5.0](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by JMendyk** [comment]
You have quite old version of yarn - `v1.2.1`, current is `v1.9.4`.
Please try upgrading it ([official install/upgrade documentation](https://yarnpkg.com/en/docs/install)) and try again.

If the issue will still persist, could you provide output of `node --version`.

**Comment by osauzet** [comment]
OK thanks,
After the : apt-get install yarn
yarn -v 
 1.2.1

I must set  -> npm i -g yarn

yarn -v 1.9.4

But i always have ->

 yarn install
yarn install v1.9.4
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
error mini-css-extract-plugin@0.4.1: The engine "node" is incompatible with this module. Expected version ">= 6.9.0 <7.0.0 || >= 8.9.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by JMendyk** [comment]
Could you please check the output of `node --version` to be sure that you're indeed on node v8.11.4.

**Comment by osauzet** [comment]
node --version 
v8.7.0

I do that -> 
Node.js 6.x is no longer supported, so you will need to upgrade to Node.js 8.x

    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    sudo apt update && sudo apt install nodejs

how can i upgrade to 8.11 ?

**Comment by JMendyk** [comment]
I have no previous experience with such issue (my Ubuntu 16.04 installs v8.11.4 using `curl ... | sudo ...` method).
After checking out suggestions on the internet two options seem to be the post popular:
1. Use NVM (Node Version Manager)
2. Install `n` package on npm which let's you install specific version of node.

Both methods are described in this article: https://www.hostingadvice.com/how-to/update-node-js-latest-version.

**Comment by osauzet** [comment]
ok thanks,
I do that 
-> curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
-> source ~/.profile
-> nvm install v8.11.4
-> nvm use v8.11.4

And after, it's ok...

sorry for the noise, it was not a bug
thank you for your help

**Comment by bretonio** [comment]
Thank you guys, also worked for me. In my case downgrading to 8.9.0 from 11.x.x did not do it. But 8.11.4 did.

**Comment by pramoditagi** [comment]
Thank you so much. The issue got resolved when I updated that nvm version to 8.11.4. Before it was 8.4.0

**Comment by zj614android** [comment]
you are so six six six!
