### ISSUE TITLE
Newest release breaks compatibility with PostgreSQL 9.4

### ISSUE THREAD

**Issue by skddc** [tootsuite/mastodon#8590]
We're on an older LTS of Ubuntu, which only gets 9.4 by default. Until v2.5.0 it worked without problems, but the migrations for the latest release include one with an upsert statement, which is only available in postgres 9.5 and newer:

https://github.com/tootsuite/mastodon/blob/master/db/migrate/20180812173710_copy_status_stats.rb#L12-L13

I looked into upgrading postgres on this server, but it would be too difficult with our current setup. Would be great if this migration could be refactored to also work on 9.4, because everything else in Mastodon seems to be compatible.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Laurelai** [comment]
Also affected by this issue

**Comment by joachimesque** [comment]
Also affected by the issue.

**Comment by nemsia** [comment]
Also affected by the issue on Debian jessie

**Comment by abochmann** [comment]
As for Debian, postgresql 9.6 is in jessie-backports: [https://packages.debian.org/jessie-backports/postgresql](https://packages.debian.org/jessie-backports/postgresql)
See [https://backports.debian.org/Instructions/#index2h2](https://backports.debian.org/Instructions/#index2h2) on how to include that in your sources. I think upgrading Postgres requires some manual intervention, but the relevant notes should be included.

**Comment by Laurelai** [comment]
Any advice for centos 7

**Comment by saper** [comment]
@Laurelai For CentOS and other RedHat derivatives PGDG (PostgreSQL Development Group) publishes very good RPMs, but migrating to use them may not be straightforward.

**Comment by Laurelai** [comment]
Its sure not, i tried today, did so now my timelines are gone ^_^
