### ISSUE TITLE
Public profiles are not displayed correctly after update to 2.5.0

### ISSUE THREAD

**Issue by tschuxxi** [tootsuite/mastodon#8599]
Hi,

I'am running a small instance at https://mastodon.earth. Since I updated to 2.5.0, the public profiles are not displayed correctly anymore. It seems like there is a problem with the css. I compared with another instance that is on 2.5.0. Some of the css classes are missing, for instance the public-account-header__image class. I don't see any errors in the logs. Also the installation went smooth. I'm not using docker.
Does anyone else had this problem after the update? Do you know how to solve this?

In case you want to see how it looks like, please visit https://mastodon.earth/@status

**Comment by JMendyk** [comment]
1. Did you precompile assets using `RAILS_ENV=production bundle exec rails assets:precompile`?
2. Did you modify styles or other files of Mastodon before upgrading? Could you please provide output of `git status` command ran in Mastodon's directory.

**Comment by tschuxxi** [comment]
1. Yes, I precompiled the assets
2. No I didn't change any styles of Mastodon. The output is
```
mastodon@mastodon:~/live$ git status
HEAD detached at v2.5.0
nothing to commit, working tree clean
```

**Comment by renatolond** [comment]
It looks like there was an issue with your assets precompile, you can try to remove the precompiled assets and precompile again with:
`RAILS_ENV=production bundle exec rails assets:clobber assets:precompile`

Precompile is a step that takes a lot of memory, if your server is low on memory, the process can be terminated and the compilation fails.

**Comment by tschuxxi** [comment]
Thank you @renatolond after freeing up some RAM, deleting and precompile the assets assets again, everything works like a charm.
