### ISSUE TITLE
Is "Rendering errors/500.html.haml within layouts/error" an error message?

### ISSUE THREAD

**Issue by clement-analogue** [tootsuite/mastodon#8604]
While running `RAILS_ENV=production bundle exec rails assets:precompile`, I run into the following message
```
$ RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.9.4
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 2.05s.
Webpacker is installed 🎉 🍰
Using /home/mastodon/live/config/webpacker.yml file for setting up webpack paths
Compiling…
Compiled all packs in /home/mastodon/live/public/packs
  Rendering errors/500.html.haml within layouts/error
  Rendered errors/500.html.haml within layouts/error (1458.3ms)
```
Are the last two lines an error message?

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ x ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
No, they aren't. They just inform you that those static assets have been generated.
They are used by your front-end web server when Mastodon itself cannot be reached.
