### ISSUE TITLE
We're sorry, but something went wrong. Error in login page (/auth/sign_in) just after updating to 2.5.0

### ISSUE THREAD

**Issue by fweng322** [tootsuite/mastodon#8605]
[Issue text goes here].

After some difficulties (with upgrading bundle, yarn, migrate db, OTP_SECRET_KEY, ... etc) I finally upgraded from tag v2.3.0 to v2.5.0.

With logged in session everything is okay.  I can read the timeline without problem.  However when logging out and then trying to logging in (from /about page) I got the error page "We're sorry, but something went wrong on our end."

I've checked with issues like this (#7454, #6234, ... etc) but not applied to my conditions.

It looks like an 500 internal server error, but no error log from nginx.

I'm not using docker-compose, but starting from systemd.  My instance is at: https://social.slat.org/
 
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by renatolond** [comment]
Do you have any errors in your `journalctl` as soon as you go into that page?

**Comment by fweng322** [comment]
Oh, I didn't see it directly using journalctl, but then I got error messages after redirecting the output to stdout.

The error log is at: https://pastebin.com/z4bXjBQ7

Still no idea where the problem is.  Any help will be very appreciated.

**Comment by renatolond** [comment]
Do you have "PAM_ENABLED" in your environment variables?

**Comment by fweng322** [comment]
I just checked it -- no, not in the .env.production.

Adding it only does not help either.

**Comment by renatolond** [comment]
Can you give more information about your environment? Ruby version , output of `bundle show`

**Comment by fweng322** [comment]
Please see

https://pastebin.com/uNb85Hfk

renatolond <notifications@github.com> 於 2018年9月4日 週二 19:51 寫道：

**Comment by renatolond** [comment]
I don't see anything wrong. :thinking: Can you compare your file at `config/initializers/devise.rb` with https://github.com/tootsuite/mastodon/blob/v2.5.0/config/initializers/devise.rb ?

**Comment by fweng322** [comment]
Got it.  I used old devise.rb file (because I've changed the key in the file).

Thank you for your help.
