### ISSUE TITLE
Articles summary displayed as CW

### ISSUE THREAD

**Issue by BaptisteGelez** [tootsuite/mastodon#8609]
I recently implemented subtitles for articles in Plume. They are federated using the `summary` field, which makes Mastodon display them as CW. Would it be possible to make a special case for `Article`s to display the `summary`/CW between the title and the link to the content? If the person wants to read what is behind the CW, they will click the link instead of the current button, and the presentation will be nicer and more coherent.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by BaptisteGelez** [comment]
@nightpool in Mastodon yes, but in Plume no, it is just a subtitle.

**Comment by Gargron** [comment]
I see what you mean, yes I think it should be possible...

**Comment by jdormit** [comment]
+1 to this - [Pterotype](https://github.com/jdormit/pterotype) also uses the Article type to represent blog posts and the `summary` for the post excerpt.

**Comment by pfefferle** [comment]
The [ActivityPub WordPress](https://github.com/pfefferle/wordpress-activitypub) plugin also uses the "Article" type.

**Comment by alxlg** [comment]
Please make it visually "integrated" into Mastodon maybe like something different from a toot to add value to those that publish with ActivityPub instead of just pasting a link:

![immagine](https://user-images.githubusercontent.com/26327475/48421618-285da280-e75d-11e8-840b-13c5d3ec613e.png)
