### ISSUE TITLE
Updating `fields_attributes` through the JSON api?

### ISSUE THREAD

**Issue by pwoolcoc** [tootsuite/mastodon#8611]
Mastodon version: v2.4.5

Is there a proper way to update the profile metadata fields through the JSON API? I see the documentation for the `PATCH /api/v1/accounts/update_credentials` method here: https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#updating-the-current-user but it looks like this is specifically for the `application/x-www-form-urlencoded` mimetype, considering the "form data" label and the field names like `fields_attributes[0][name]`.

I can make a request to the endpoint using JSON data, and it works properly for all the other parameters, except the `fields_attributes` ones. In the controller for this method: https://github.com/tootsuite/mastodon/blob/master/app/controllers/api/v1/accounts/credentials_controller.rb#L24 it looks like `fields_attributes` should be an array of hashes which each having `name` and `value` field names, but then in the account model: `https://github.com/tootsuite/mastodon/blob/master/app/models/account.rb#L225` it is only checking that the attributes are a `Hash`, if an array of hashes come in then it is thrown away entirely.

My knowledge of ruby is very limited, so I haven't been able to figure out what the proper fix is here, whether I just need to use form-urlencoded data or if there is an actual way to use json data here, and I'd appreciate any insight you can give

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Look at the code you should be able to form the json for `fields_attributes` like `{ 0: { name: ..., value: ... }, 1: { ... } }`

**Comment by pwoolcoc** [comment]
ah, I see, thank you!
