### ISSUE TITLE
getting-started page not displaying - view source shows "please enable Javascript"

### ISSUE THREAD

**Issue by pexdata** [tootsuite/mastodon#8613]
I installed an instance of mastodon on my own server using docker as per the instructions from this guide: https://github.com/ummjackson/mastodon-guide/blob/master/up-and-running.md
I am able to see the Sign-In page. I created a user, and made it the Admin. I manually confirmed the verification e-mail. After Sign-In mastodon takes me to the web/getting-started page. But this is not rendered and is blank. When inspecting the page source, I see the following: 

To use the Mastodon web application, please enable JavaScript.

Javascript is enabled on my browser. 

I can get to other pages fine such : /admin/dashboard

Appreciate any pointers.

Thank you.

**Comment by pexdata** [comment]
![mastodon-after-login-error](https://user-images.githubusercontent.com/16337420/45063335-0a940300-b073-11e8-8d01-56e6274e56e3.PNG)

Firefox Browser on Windows Version 61.0.2 64-bit

**Comment by pexdata** [comment]
![gettingstartedpage-black-view-source](https://user-images.githubusercontent.com/16337420/45063523-04eaed00-b074-11e8-87fd-35408184e6a6.png)

View Source on the page shows the following text indicated JavaScript is not enabled. The previous comment shows the error and Firefox Browser Version used.

**Comment by renatolond** [comment]
Hey!
I opened your instance page and I'm also seeing errors, so I don't think it's browser specific. Did your assets precompilation step worked without any issues?

**Comment by pexdata** [comment]
I didn't see any errors in the pre-compilation. Here is the output:
----
sudo docker-compose run --rm web rails assets:precompile
Starting live_db_1    ... done
Starting live_redis_1 ... done
yarn install v1.6.0
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 1.75s.
Webpacker is installed 🎉 🍰
Using /mastodon/config/webpacker.yml file for setting up webpack paths
  Rendering errors/500.html.haml within layouts/error
  Rendered errors/500.html.haml within layouts/error (844.3ms)

**Comment by renatolond** [comment]
Ah, sorry, I haven't noticed that you followed a different guide. Can you double check your steps using the official guide: [Docker Guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md) and take note of the change on 2.5.0:

> If you had nginx/apache configuration expecting CSS/JS assets to be under volume folders, they are no longer there. Asset precompilation now happens during image build, and is therefore not available from a volume. Instead, requests for the assets must hit Puma inside Docker, which will serve them.

**Comment by pexdata** [comment]
I followed the new guide. The setup was automated with the script that is nice. 
It is working now.  Thanks a lot and appreciate your time very much for responding to this issue.

**Comment by ykzk** [comment]
Could you be more specific in exactly what you changed? I'm having the exact same issue and running `bundle exec rake mastodon:setup` does not help. I also tried removing /mastodon/public/packs and /mastodon/public/assets from the exported volumes.

**Comment by nightpool** [comment]
@ykzk we don't do support on GitHub anymore. please use IRC or
discourse.joinmastodon.org

**Comment by ykzk** [comment]
For information, it turns out I was using the latest version of Redis; going back to 4.0-alpine seems to solve the issue.
