### ISSUE TITLE
Follows & Blocks import fails completely if a single record in the CSV is has issues

### ISSUE THREAD

**Issue by thurloat** [tootsuite/mastodon#862]
I believe in the best case, it should either deliver user feedback on the failed task (email?) and / or import whatever data from the CSV is valid and resolve-able from this instance.

I was following the logs / reviewing with someone on my instance here: https://mastodon.club/@thurloat/409

Basically boiled down to this:
```
Looks like one or more person(s) in your list meets one of these following conditions:

1. has been banned, 
2. doesn't exist on the endpoint, 
3. or is yourself.
```

The import worker [makes a call](https://github.com/tootsuite/mastodon/blob/master/app/workers/import_worker.rb#L49) to the [follow service](https://github.com/tootsuite/mastodon/blob/master/app/services/follow_service.rb#L12) which raises `ActiveRecord::RecordNotFound`.

RecordNotFound isn't caught by the importer, and blows the whole thing up.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by krainboltgreene** [comment]
If the CSV is invalid, who is to say the rest of the items are valid? I suggest going with the notification route.

**Comment by thurloat** [comment]
I can see there being a difference between a soft invalid and a hard invalid CSV.

for example: the user created an account on both instances, exported the list from one and has themself (the now local user) in the importer to be processed. The whole thing could be full of valid followers but that one line of locally invalid data.

I think from a user experience perspective, they would rather have all of their contacts in the system and receive an email that outlines that 1 record could not be imported -- and describes that it is because either the webfinger failed, or it's a self-reference.

**Comment by krainboltgreene** [comment]
Gotcha, I agree with that.

**Comment by riking** [comment]
This just happened to me - one account on my export list didn't exist anymore, and failed the whole followings import.

**Comment by thurloat** [comment]
This has been resolved by a recent commit (didn't reference this issue though). I found it skimming the commit logs over coffee this morning. 

https://github.com/tootsuite/mastodon/commit/540d6efe88717b0da4a23b5069a3caaff5b3241a

 we've deployed the fix at mastodon.club, it has definitely effected a few people 👍
