### ISSUE TITLE
[Tiny] 2.5.0 release notes misrepresent #8282

### ISSUE THREAD

**Issue by qguv** [tootsuite/mastodon#8621]
The release notes for 2.5.0 claim that the active time was reduced from 7 days to 2 days, but since #8282 was changed to keep the original 7 days but make it configurable in an env variable, the release notes weren't updated to reflect that change.

User active duration:

https://github.com/tootsuite/mastodon/blob/v2.5.0/app/models/user.rb#L52

**Comment by Gargron** [comment]
OK, fixed

**Comment by qguv** [comment]
Thanks @Gargron!
