### ISSUE TITLE
New Moderation View: Reported Users

### ISSUE THREAD

**Issue by sivy** [tootsuite/mastodon#8622]
Wanted to get [this idea](https://xoxo.zone/@fraying/100669867520088829) by \@fraying into an issue:

> I could imagine an admin page design where, instead of a list of reports, the admin sees a list of reported users. IE: This user has been reported X times. Actions: View reports / suspend user / dismiss reports. Idea is, the admin is acting on a user, not on any particular report, and all the reports are bundled together. That way a million reporters dogpiling would only cause one person to pop up in front of the admin.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by pwoolcoc** [comment]
@lanodan what's wrong with that? If someone is bothering many of my users to the point where they all report the user, I want to know about it

**Comment by kaniini** [comment]
@pwoolcoc it can be gamed.  what's better is to order by number of reports.

**Comment by lanodan** [comment]
> many of my users

It also looks like you’re not aware for federated reports.

**Comment by Cassolotl** [comment]
Being able to sort reports in various ways seems like a sensible and user-friendly move to me. This could be one way, and there could be other bits of information available to help in dogpiling situations (like which instances the reports are coming from, etc).

>This user has been reported X times. Actions: View reports / suspend user / dismiss reports.

That seems pretty sensible to me too! If someone is being dogpiled but they haven't broken the rules of the instance they're on, mods should be able to easily dismiss all reports.

**Comment by Cassolotl** [comment]
Oops, looks like this is fixed with https://github.com/tootsuite/mastodon/pull/8674 but it wasn't linked to this issue!
