### ISSUE TITLE
Interoperability with non-mastodon ActivityPub services

### ISSUE THREAD

**Issue by vitalyster** [tootsuite/mastodon#8625]
I'm trying to federate with mastodon from scratch, querying ActivityPub actors, their outboxes/followers/etc. and can not get actual response - after the first request to some endpoint it is cached indefinitely without(?) any possibility to reset cache.
I'm trying to search users from `mastodon.social` instance, using web interface as well as different mobile clients and see the same profile info and outbox for federated users that I requested a day ago! While actual info is updated recently.
What did I miss? Is there a way to tell server need to reset cache and request actual info?
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
The cache is only 1 day when searching for username@domain. When pasting URL of actor into search bar, no caching. What is the URL of your actor?

**Comment by vitalyster** [comment]
Hello, thanks for your response, actually I have a lot more interoperability questions :)
Cache for my [account](vt@juick.com) search was reset in 2 or 3 days, maybe it did not reset in case of errors? Now it more accurate but a bit lags in followers count, so it cached again.
And search for my [Actor URL](https://api.juick.com/u/vt) returns 0 results.
Please, let me know what exact fields are missing in my ActivityStreams/ActivityPub implementation.

**Comment by Gargron** [comment]
`https://api.juick.com/.well-known/webfinger?resource=acct:@api.juick.com` returns 401.

**Comment by Gargron** [comment]
Missing `preferredUsername` (username). `name` is "display name"

**Comment by vitalyster** [comment]
@Gargron WebFinger is on root domain and usernames are too, api is used only for feeds

**Comment by vitalyster** [comment]
Understand now - when pasting url in search it tries to discover on api domain.
But still does not understand what is missing in OrderedCollectionPages in blogs and followers

**Comment by Gargron** [comment]
@vitalyster Mastodon does not download past posts, or followers/following. Only the counts. Content is stored after subscription only.

**Comment by vitalyster** [comment]
@Gargron thanks, now I'm trying to post and/or follow [using your tutorial](https://blog.joinmastodon.org/2018/06/how-to-implement-a-basic-activitypub-server/) - I'm using the same create-hello-world.json and delivery.rb script only change actor to [my actor](https://juick.com/u/vt) and attributedTo to my [mastodon.social actor](https://mastodon.social/users/xwatt) in json input and put my actor id to `keyId` header in delivery.rb script - the response is 500, `We&#39;re sorry, but something went wrong on our end`

The same error is for Follow activity. Something missing again?

**Comment by vitalyster** [comment]
Finally, I'm able to run mastodon myself in development mode and see detailed errors
