### ISSUE TITLE
Stop the timeline from moving out from under my mouse when I'm about to click

### ISSUE THREAD

**Issue by lmorchard** [tootsuite/mastodon#8630]
Similar to one of my biggest peeves with TweetDeck - when I try to click something in a busy timeline in Mastodon, it often slides out from under my pointer and I end up interacting with something else.

It would be really nice if the timeline scrolling could pause for a significant period (say 1000ms) as I'm trying to interact with it.

This is basically a re-submission of both #1004 and #7278. 

Looks like #1004 was fixed in 4df831078f3af47588ea66e8b48d4ec26f4872eb, but then reverted in 7e0aed398f7e3e74a3c15e426082f88cf8b79bcf

Then #7278 was fixed in 58852695c8ec490239ed3812f82971f8c1e6c172 but then reverted in e06fbc4fcfbaaa2d420cbbace37d7c228a8bfc5b

I wouldn't mind finally getting around to scratching my own itch and submit a fix. But it might help to have some details as to why two different whacks at fixing it were reverted so I don't make the same mistakes.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by lmorchard** [comment]
> (that feature was already disabled)

Okay, I guess by revert, I mean that's where it looked to me in my hasty sleuthing that the code was backed out

> a lot of people complained about it when it was introduced

I know options & checkboxes are sometimes called failures of design, but could this be a place for a personal setting?

> people often have their cursor hovering one column

Yeah, that was I think why the [first fix](https://github.com/tootsuite/mastodon/commit/4df831078f3af47588ea66e8b48d4ec26f4872eb) (and [my original issue](https://github.com/tootsuite/mastodon/issues/1004)) wasn't to just stop the column on hover, but to pause on recent movement on the assumption that an interaction is in progress.

**Comment by BenLubar** [comment]
I'd definitely enable a setting that stops the timeline from scrolling while the mouse is over it.

Why not make that setting also make the timeline glow so it's clear it's being paused by some action related to its position?
