### ISSUE TITLE
Can't log in to old mastodon.social account (before email auth)

### ISSUE THREAD

**Issue by trevorfilter** [tootsuite/mastodon#8647]
Apologies if this is a bad place to post my issue; I couldn't find a better way to get in touch with what is somewhat of a weird issue.

I believe that I signed up for a Mastodon account back in October 2016, under the username @trev@mastodon.social. At that time, I don't know if it was possible to sign up with an email address, because my password manager only shows the username, password and creation date. I recall posting a couple of toots and then forgetting about the account for a while.

Fast forward to now, and when I try to log in, I get an "invalid email/password" error. Further, https://mastodon.social/@trev displays the standard "deleted user" page. Now, I'm nearly certain that I didn't delete this account, and since I don't recall ever attaching my email address to the account, I am speculating that perhaps it was deleted as part of a migration to an email-based account system (?).

I'm even more convinced that this username was active at some point in time, because my browser has cached the same combination of user/pass for mastodon.social as my password manager.

In any case, is there any chance for the account to be recovered/unlocked? Or at least figure out what happened here? I figure not, but thought it was worth asking. I can also supply the original account password if it's helpful. Thanks in advance!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Mastodon has required email since it went public, there are no pre-email accounts. Also, I can guarantee you that @Trev@mastodon.social is a different Trev (my old friend).

**Comment by trevorfilter** [comment]
Well there you go! Must have been my mistake then. Thanks, @Gargron—I'll register a new account.
