### ISSUE TITLE
AUTHORS.md isn't up to date

### ISSUE THREAD

**Issue by Sylvhem** [tootsuite/mastodon#8650]
The AUTHORS.md file should be updated once per release. However, we did not update it since its creation and the file isn't up to date anymore.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
glad to hear you volunteer :P

**Comment by Sylvhem** [comment]
I would be more that happy to do it. I just need the script used to generate the list and, since updating this file should be one of the last things done before releasing, the "Member" status on the project.

Thank you for your very constructive comment @nightpool! It's realling helping.

**Comment by Gargron** [comment]
Fortunately I did ask the author of AUTHORS.md to document how the list was compiled: https://github.com/tootsuite/mastodon/pull/6685#issuecomment-372054329

However it's still not easy to execute, we need a rake task that would do it.

**Comment by nightpool** [comment]
My comment was meant to be pretty light hearted—since we all knew this was going to be a problem when the pull request was merged, and no one volunteered to keep it up to date—and I apologized to @Sylvhem on mastodon for it seeming dismissive. I've opened #8661 with a rake task to generate the file.
