### ISSUE TITLE
yarn.lock requires package over http

### ISSUE THREAD

**Issue by MyPod** [tootsuite/mastodon#8654]
I've been spending a few hours dealing with ECONNRESET coming after `yarn install --pure-lockfile` while upgrading a working setup from 2.4.5 to 2.5.0. 

    $ yarn install --pure-lockfile
    yarn install v1.9.4
    [1/6] Validating package.json...
    [2/6] Resolving packages...
    [3/6] Fetching packages...
    info There appears to be trouble with your network connection. Retrying...
    info There appears to be trouble with your network connection. Retrying...
    info There appears to be trouble with your network connection. Retrying...
    info There appears to be trouble with your network connection. Retrying...
    error An unexpected error occurred: "http://registry.npmjs.org/compression/-/compression-1.7.2.tgz: read ECONNRESET".
    info If you think this is a bug, please open a bug report with the information provided in "/home/mastodon/live/yarn-error.log".
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

The issue is caused by said package being, with event-stream, the only one in yarn.lock to be available under http and not https, the file might need to be regenerated. Considering it is still as such in master, I thought to ask for a fix and to save some other clueless person a hour or two.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [2.5.0](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Seems like integrity hashes have been added into yarn.lock now, so using http should no longer be a risk.

**Comment by MyPod** [comment]
My issue is not about the presence of hashes or the security of the fetch process, but about it not working in my case for packages meant to be retrieved over plaintext - I will check what is happening in the network and possibly solve it, but I fail to see what prevents to implement the proposed fix, considering it adds consistency.
