### ISSUE TITLE
URL expansion to show title, main image and first few lines

### ISSUE THREAD

**Issue by pexdata** [tootsuite/mastodon#8659]
I am a new bee mastodon instance admin. I did not find a feature like showing the title, image and first few lines of a mentioned URL in a toot. Is this supported or any plans for such a feature? I see the embedded media get's expanded, but specifying a URL in the toot stays as a URL. Showing a peek of what the target URL as they do in Twitter or other social media site, would be a nice feature. It would be nice to extend the media to a PDF URL also. Of course this will required a PDF viewer built into mastodon. Just a thought. 
Thank you.

**Comment by pexdata** [comment]
Yes.

**Comment by nightpool** [comment]
sounds good!

**Comment by pexdata** [comment]
Is it available ? I don't see the URL showing as you have shown in the picture.

**Comment by trwnh** [comment]
@pexdata Does your URL have OpenGraph tags embedded in the document? Not every website defines its "card" / "expansion".
