### ISSUE TITLE
A way to swap out redis since it's no longer FOSS

### ISSUE THREAD

**Issue by coreyreichle** [tootsuite/mastodon#8664]
Redis has made their software non-FOSS with the addition of the commons clause to the Apache license.  Is there a documented substitute for Redis?  The use of non FOSS software severely restricts the ability for the entire project to be usable in some cases, if a core component isn't.

* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
none of the redis software we depend on has changed license, the only software that has changed license is modules developed by RedisLabs that were already proprietary. Redis core is still BSD licensed

**Comment by Secret-chest** [comment]
Now it's actually happened!
