### ISSUE TITLE
New API Request: Revoke access token myself

### ISSUE THREAD

**Issue by rinsuki** [tootsuite/mastodon#8665]
e.g. `DELETE /api/v1/tokens`.

use cases:

- when third party services has ended.
- when detect access token leaked.
- or other...

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
`POST /oauth/revoke`?

**Comment by rinsuki** [comment]
@Gargron 
How should I use it?
As far as I tried, it looks like it does not working.
