### ISSUE TITLE
Displayed retry job at the Sidekiq: ActiveJob::DeserializationError

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#8666]
When after #8438 , if "mention" is deleted immediately after transmission, the error of the next image will be displayed in Sidekiq of the received instance.
This also occurs when you cancel "follow" immediately after "follow".
The same is true for "boost", and more.

I think that it need to search the Notification id at the notification_mailer.rb.
But.. I did not understand how to do it.

![2018-09-10 12 04 26](https://user-images.githubusercontent.com/766076/45274316-e82a3b80-b4f1-11e8-8097-e0b6a88ebb40.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
hmm. This error can be safely ignored, but it shouldn't be retried.

i wonder if there's a way to mark it as fatal? It's not our code, this is a
handler built into ActiveJob.
