### ISSUE TITLE
Change the API docs to default to unlisted instead of public

### ISSUE THREAD

**Issue by SuliacLEGUILLOU** [tootsuite/mastodon#867]
Someone complane about bot being ultra noisy on public timeline
I saw the default behaviour about the api posted message is to set them as public, wouldn't it be better to set it at unlisted ?
I'll try to make a PR soon with that change.
* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
Bot spam is a probably for sure. But I'm not sure this is a good idea – I'd consider a breaking API change, and it would probably not result in a large reduction in bot posts (since the bots will just specify "public" instead of nothing). Anyone have thoughts on this?

**Comment by Gargron** [comment]
New users don't have followers and don't (yet) understand the difference between public and unlisted. If they were defaulted to unlisted, new users would not be discovered by anyone, and their "hello, is anyone there?" posts would never be answered.
