### ISSUE TITLE
The click target for showing a thread is too small in image-only toots

### ISSUE THREAD

**Issue by allo-** [tootsuite/mastodon#8671]
When someone posts an image without text, I cannot find where to click to see the thread.

- Left of the image: nothing happens.
- On the image: The image opens.
- Between Username and timestamp: The user profile opens in the sidebar.
- On the timestamp: The toot opens in a new window.
- Next to the action icons: Nothing happens.

The only option left is to use the  three-dots menu to open the toot in the sidebar.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by JMendyk** [comment]
Hi @allo-,
There's already a discussion regarding this issue at #8529.

Duplicate of #8529.

**Comment by allo-** [comment]
Indeed, this seems to fully address the issue. Sorry for the duplicate I was a bit overwhelmed by the long list of open issues.
