### ISSUE TITLE
image descriptions get discarded for animated gifs

### ISSUE THREAD

**Issue by lawremipsum** [tootsuite/mastodon#8676]
Users are able to add image descriptions to animated gifs or other media that are converted to videos, but they are not presented for users to read through any of the usual means. It will not appear as alt/hover text, or in mobile when long-pressing the loaded image.

See: https://mastodon.social/@carithlee/100704748364238403

![b4c7ba204e8e5dce](https://user-images.githubusercontent.com/33725621/45334840-32d3a400-b542-11e8-9d88-d655152c1acb.png)
(Image from mspsocial, which has added an icon to indicate the presence of an image description)

... further inspection shows that the description is being set as area-label, which doesn't get rendered as rollover text. I suggest also putting the description as **title=""** text so it can be viewed through ordinary means.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Hovering the image in the link shows a tooltip.
