### ISSUE TITLE
Unclean image

### ISSUE THREAD

**Issue by willispapaya** [tootsuite/mastodon#8677]
The picture uploaded can not be seen cleanly. From IOS.
https://wmer.icu/@papaya/100641849625509455

**Comment by Gargron** [comment]
It can't be seen cleanly from anywhere because it's very small.

**Comment by willispapaya** [comment]
But the original picture in my IPhone is big and clean,  Why upload it to mastodon then resize it so small,  Can mastodon keep it in a big size? And will let reader to see clean picture.

**Comment by trwnh** [comment]
@Gargron I'm noticing that the image in question got resized to 1280px in the maximum dimension. Wasn't this supposed to have been fixed in #8083?

**Comment by Gargron** [comment]
@trwnh Yeah it was also uploaded on August 31 and I have no idea what version of Mastodon wmer.icu was at that point. In my understanding in 2.5.0 it shouldn't be so bad.

**Comment by willispapaya** [comment]
https://wmer.icu/@papaya/101043425078589484 This problem happened again. @gargron

**Comment by nightpool** [comment]
the preview is small but the actual image is 4359 pixels tall, which is a
pretty reasonable number IMO

**Comment by willispapaya** [comment]
I see the pic Information ,the pixel is 990*11490
