### ISSUE TITLE
Dev Mode: Change mastodon.dev to something that works

### ISSUE THREAD

**Issue by trev-dev** [tootsuite/mastodon#8684]
I have a local vagrant setup where I changed the hostname to mastodon.local so that my vagrant dev server would actually load. Google has done something crappy with .dev sites that breaks them on local machines. However, the mastodon server is still serving static assets from mastodon.dev. 

I tried using ag/ripgrep to see if I could find any other configurations that set the dev server's dns to mastodon.dev, I couldn't find anything.

Is there any chance I may get some guidance with changing the mastodon vagrant dev dns or perhaps see the default changed in a PR?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trev-dev** [comment]
I'm gussing my ag/grep overlooked hidden files. I was able to change the dev server dns by modifying it in .vagrant.env - probably something someone more experienced with vagrant would know. 

P.S. thank you so much for Mastodon. I enjoy making contributions to my local instance! I'm gonna leave this open, though. I don't feel like mastodon.dev is a sane default for Vagrant. I'll send a PR later.

**Comment by Gargron** [comment]
What would you suggest?

**Comment by nightpool** [comment]
i use .dev domains for my day-to-day work and i've never had a problem with
them.

**Comment by trev-dev** [comment]
@nightpool Awesome! I'm not sure the problem happens everywhere. However, I can reinforce my argument with the following:
https://stackoverflow.com/questions/47809632/i-can-no-longer-access-my-local-development-dev-websites-in-chrome-http-is
https://www.theregister.co.uk/2017/11/29/google_dev_network/
https://medium.engineering/use-a-dev-domain-not-anymore-95219778e6fd

@Gargron I was going to go with .local or .test. I've got the .vagrant.env and the Vagrantfile situation figured out. I'm just not sure as to where the default dev admin account is created within the Ruby backend as I'm not strong with Ruby. If you give me a push, I'd be happy to do the work.

Thanks for your responses!

**Comment by nightpool** [comment]
does local vagrant not have a ssl certificate? we could probably locally
generate one and have people add it to their local trust roots

**Comment by justinmayer** [comment]
@nightpool: If heading in that direction, have a look at [mkcert](https://github.com/FiloSottile/mkcert).

**Comment by Gargron** [comment]
Hold on, is there no better option than to use SSL on a local machine? That seems kinda pointless and overly complicated. Why do we even need a TLD, won't it work with localhost?

**Comment by justinmayer** [comment]
@Gargron: TLS does indeed work with localhost, and I personally haven't found using TLS for local development to be overly complicated. As for why one would want to use TLS on a local workstation, one reason is that it is required for [WebAuthn](https://en.wikipedia.org/wiki/WebAuthn) (successor to U2F), support for which I hope will someday [land in Mastodon](https://github.com/tootsuite/mastodon/issues/562). 😁

**Comment by trev-dev** [comment]
Literally just changing the domain name in the 2 vagrant config files and re-provisioning fixes the issue.

**Comment by trev-dev** [comment]
Pull request sent.
#8706
