### ISSUE TITLE
JSON returned by OGP API is different on twitter and fixed website.

### ISSUE THREAD

**Issue by mitsugu** [tootsuite/mastodon#8687]
JSON returned by OGP API is different on twitter and fixed website.

ex)
* twitter ( https://mstdn.hyogo.jp/@OrzBruford/100715698567161113 )
https://mstdn.hyogo.jp/api/v1/statuses/100715698567161113/card 
{"url":"https://twitter.com/OrzBruford/status/1040037512826114048","title":"OrzBruford on Twitter","description":"“以前書いた立山室堂への旅行の時三脚は持っていかなかったんだけど、体幹機能障害があるので体が揺れるのでまぁ写真も普通にブレるわけですよ。その防止のために娘の肩を三脚代わりに借りてました。ひどい親？”","type":"link","author_name":"OrzBruford","author_url":"https://twitter.com/OrzBruford","provider_name":"Twitter","provider_url":"https://twitter.com","html":"","width":240,"height":240,"image":"https://mstdn.hyogo.jp/system/preview_cards/images/000/067/432/original/8b0a3a1ed2b525d2.jpeg","embed_url":""} 

* fixed Website( https://mstdn.hyogo.jp/@OrzBruford/100717210737797581 ) 
https://mstdn.hyogo.jp/api/v1/statuses/100717210737797581/card/ 
{"url":"https://likebar.harisen.jp/","title":"バーr……blog のようなもの","description":"","type":"link","author_name":"","author_url":"","provider_name":"","provider_url":"","html":"","width":0,"height":0,"image":null,"embed_url":""} 

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
I'm paraphrasing because I had some trouble understanding what was reported (and the second toot has apparently been deleted): the preview card for a tweet and the preview card for an unrelated website are different.

But this is expected to me? I'm not sure what the actual issue is.

**Comment by mitsugu** [comment]
Sorry. It seems that it was my misunderstanding.
