### ISSUE TITLE
Failing docker-compose build

### ISSUE THREAD

**Issue by Fastidious** [tootsuite/mastodon#869]
Getting:

```
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
```

On `docker-compose build`. Trying to install on a clean `Ubuntu 16.04` VPS.

Further details:

```
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64
```
And:

```
docker-compose version 1.5.2, build unknown
docker-py version: 1.8.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

We really need more documentation (well, I need), or something that would make the installation a tad simpler.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by krainboltgreene** [comment]
Can you paste your `docker-compose.yml` file? It looks like the version key might be indented incorrectly.

**Comment by Fastidious** [comment]
@krainboltgreene destroyed the VPS. The `docker-compose.yml` was the same one as this https://github.com/tootsuite/mastodon/blob/master/docker-compose.yml

**Comment by krainboltgreene** [comment]
@Fastidious I would check here for a solution: https://github.com/docker/compose/issues/3331

**Comment by Fastidious** [comment]
@krainboltgreene did come across that, yes. No dice. I will try again with `Ubuntu 16.10` this time, and see how it goes.

**Comment by snomofomo** [comment]
I ran into the same error message.  Turned out to be the wrong version of docker-compose.  I followed the instructions at [https://github.com/docker/compose/releases](https://github.com/docker/compose/releases)  to update and it ran fine after that.

**Comment by Gargron** [comment]
@Fastidious Please don't use 16.10. 16.04 is LTS, a lot more stable. mastodon.social and my dev machine are all running on 16.04 so that's not the core of the issue.

**Comment by yipdw** [comment]
@snomofomo is right: the `version` key was introduced in v2.0 of the `docker-compose.yml` spec, so you'll need `docker-compose` 1.10.0 or above.  (I can confirm 1.11.1 works.)

**Comment by vielmetti** [comment]
Ran into the same problem with Ubuntu LTS 16.04 on Intel. My info reads:

```
root@mastodon-dev:~/src/github.com/tootsuite/mastodon# docker-compose version
docker-compose version 1.5.2, build unknown
docker-py version: 1.8.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

Therefore the default docker-compose you get when you do `apt-get install docker-compose` on Ubuntu 16.04 is too old.

**Comment by ineffyble** [comment]
That's... very old. As pointed out, you'll need a later version to use modern docker-compose files:

![image](https://cloud.githubusercontent.com/assets/834880/24829574/c7efa6da-1cb7-11e7-8e00-a3ef5de1e023.png)

Version 1.5.2 was released in *December 2015*

My guess is this is why the [official installation instructions](https://docs.docker.com/compose/install/) don't use distro package managers.

**Comment by kyzh** [comment]
This instruction for Ubuntu are quite good:
https://github.com/ummjackson/mastodon-guide/blob/master/up-and-running.md

**Comment by kyzh** [comment]
@Fastidious were you able to fix your issue by updating your docker compose ?

**Comment by ashfurrow** [comment]
@Fastidious just following up – were you able to resolve this issue but upgrading to a newer docker-compose?

**Comment by Fastidious** [comment]
@ashfurrow yes, upgraded `docker-compose`.

**Comment by ashfurrow** [comment]
Great! I'm glad to hear that.
