### ISSUE TITLE
cannot force purge of removed accounts

### ISSUE THREAD

**Issue by selfagency** [tootsuite/mastodon#8695]
Neither the `-f` option nor the `--force` option work when running the `mastodon:maintenance:purge_removed_accounts` rake task. It works without the option specified but you then have to manually approve each deletion.

With `-f`:

```
mastodon@masto:~/live$ RAILS_ENV=production bundle exec rake mastodon:maintenance:purge_removed_accounts -f

rake aborted!
Don't know how to build task 'mastodon:maintenance:purge_removed_accounts' (see --tasks)
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/mastodon/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/home/mastodon/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

With `--force`:

```
mastodon@masto:~/live$ RAILS_ENV=production bundle exec rake mastodon:maintenance:purge_removed_accounts --force

invalid option: --force
```

With `:force`:

```
mastodon@masto:~/live$ RAILS_ENV=production bundle exec rake mastodon:maintenance:purge_removed_accounts:force

rake aborted!
Don't know how to build task 'mastodon:maintenance:purge_removed_accounts:force' (see --tasks)
Did you mean?  mastodon:maintenance:purge_removed_accounts
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/mastodon/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/home/mastodon/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
There must be a `--` before the `--force` for it to be picked up. It's an awful limitation of the rake system and it's been removed in the master branch, where the function has been put into tootctl to be used like:

`RAILS_ENV=production bin/tootctl accounts cull`

So you can look forward to that in the next release.

**Comment by selfagency** [comment]
That worked. Thanks.
