### ISSUE TITLE
feature: default animated GIFs ON for all users.

### ISSUE THREAD

**Issue by ashleyhull-versent** [tootsuite/mastodon#8697]
I'd love to enable this by default for all of the users on my instance.

<img width="195" alt="image" src="https://user-images.githubusercontent.com/17537000/45586815-0f449b00-b940-11e8-914e-e37d6ebebdbe.png">

**Comment by nightpool** [comment]
you can do this very easily by modifying preferences.yml

**Comment by ashleyhull-versent** [comment]
ok.. that makes sense... I'm going to have to modify the default docker-compose for this.

**Comment by ashleyhull-versent** [comment]
@nightpool I cannot find any reference to preferences.yml .. anywhere

**Comment by nightpool** [comment]
Oops, it's called settings.yml

**Comment by ashleyhull-versent** [comment]
haha. that makes more sense... that exists 👍
