### ISSUE TITLE
Sidekiq tasks always failing

### ISSUE THREAD

**Issue by Luclu7** [tootsuite/mastodon#870]
Hello,
I have two Sidekiq tasks (_**Pubsubhubbub::DistributionWorker**_) who always fail with the same reason:
`ActionView::Template::Error: undefined method object_type' for nil:NilClass Did you mean? object_id`

**Comment by krainboltgreene** [comment]
Probably this render: https://github.com/tootsuite/mastodon/blob/master/app/workers/pubsubhubbub/distribution_worker.rb#L15

**Comment by ashfurrow** [comment]
Hey @Luclu7 is this still happening for you?

**Comment by ashfurrow** [comment]
I'm going to close due to inactivity – thanks again for opening the issue.
