### ISSUE TITLE
Can't Update My Email Address

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [tootsuite/mastodon#8710]
I went to https://mastodon.social/settings/migration to change my email address & kept clicking but nothing happen, just page reload without any sign about it changed or no

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by justinmayer** [comment]
@EsmailELBoBDev2: That page is for migrating the account to a new instance — not for changing your email address. For that, I believe the correct place is:  https://mastodon.social/auth/edit

**Comment by EsmailELBoBDev2** [comment]
@justinmayer yeah its worked, thx a lot for helping :+1:
