### ISSUE TITLE
When linking a toot, show its content in the preview

### ISSUE THREAD

**Issue by frandavid100** [tootsuite/mastodon#8713]
I have a large following on Twitter (almost 5,000 people) but nobody follows me on Mastodon.

I want to use Mastodon as my main social network, but that means none of my followers would read me, so I'm stuck on Twitter.

What I would like to do is write my content as toots, then write tweets linking to those toots. That way my followers would know that I have new content, and maybe click the link. Ideally even create a Mastodon account and follow me there directly.

The problem is, when I link to a toot, the preview does not show the content of that toot. It does not show the text, and it does not show any pictures that might be attached. Instead it only shows my name, profile picture and Mastodon address. Which is not attractive at all.

Could it show the Toot's content instead?

![screenshot_20180917-131515 2](https://user-images.githubusercontent.com/694794/45620379-fc83b080-ba7c-11e8-80b1-82ed45fc4a09.png)

![screenshot_20180917-131646 2](https://user-images.githubusercontent.com/694794/45620460-4e2c3b00-ba7d-11e8-8af6-0d39160ec17d.png)

**Comment by Gargron** [comment]
Mastodon already provides everything that's required to display text. If Twitter doesn't display text in previews, that's on them.
