### ISSUE TITLE
how get :verified: badge ?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [tootsuite/mastodon#8720]
how get :verified: badge ?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Mastodon does not provide a verified badge.

**Comment by EsmailELBoBDev2** [comment]
but i saw 2 accounts with it O.o

**Comment by Gargron** [comment]
It's a custom emoji. Kind of like :ballot_box_with_check: It's meaningless.

**Comment by EsmailELBoBDev2** [comment]
well, thx to make it clear to me :D
