### ISSUE TITLE
Web not displaying Boost or Favorite numbers

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#8722]
Hello - not sure what the issue is here. In the notification tab on the web (for my instance) it does not track the number of times a toot was boosted or favorited. No number is displayed at all. However, when I use the Tootdon app and check the notification tab in app, the numbers for each are displayed. Any idea how I can get this fixed?

Please and thank you!

**Comment by ThibG** [comment]
Afaik it's intentional. Those numbers are only displayed when the detailed view for that toot is opened (that is, when you click on it and it opens in the rightmost column)

**Comment by malicioustoker** [comment]
This is a feature, not a bug, got it. Thanks for the info!
