### ISSUE TITLE
Allow custom rel link attributes for profile verification

### ISSUE THREAD

**Issue by Espionage724** [tootsuite/mastodon#8732]
Related to https://github.com/tootsuite/mastodon/pull/8703

With Joomla!, I have links to my profiles in a Menu, and it only allows for pre-defined link rel attributes (`me` isn't included in that list).

Here's the list of attributes available (I'm thinking author would be a good choice):

```
alternate
author
bookmark
help
license
next
nofollow
noreferrer
prefetch
prev
search
tag
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
These values do not have the same meaning as "me" and are not interchangeable with it. Especially nofollow which is put on every random link in user-generated content, so could leave a WordPress comment on someone's blog and claim the blog as yours. It's also possible to be an author *on* some page without being the *owner* of said page (think guest posts).
