### ISSUE TITLE
"Toot" is a stupid name. Just call it post already

### ISSUE THREAD

**Issue by 153** [tootsuite/mastodon#8739]
"Toot" is a stupid name. Just call it post already

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
duplicate of #7667

**Comment by 153** [comment]
Excuse me? No, it's not.

**Comment by 153** [comment]
Unclose this, NOW.
