### ISSUE TITLE
Safari and possibly IE/Edge always scroll to the top when returning to a view

### ISSUE THREAD

**Issue by kode54** [tootsuite/mastodon#8750]
There is an issue where history navigation within columns results in the column scrolling back to the top. It may be related to this issue on another project that was using a scrolling API:

https://github.com/thelounge/thelounge/issues/2233

Copying from there:

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

Neither IE/Edge nor Safari support passing an object as a parameter to this function, and only react to using it by scrolling the view all the way to the top.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (happens on `2.5.0`)

**Comment by MaciekBaron** [comment]
Closing this issue for now, feel free to re-open.
