### ISSUE TITLE
Support receiving of private postings without the "followers" collection

### ISSUE THREAD

**Issue by annando** [tootsuite/mastodon#8752]
Currently Mastodon accept two kinds of private postings via AP:

1. Private postings to the "followers" collection
2. Private postings where people are tagged

The ActivityPub specification however does know other ways. For example one can create a post with several people added in "to" and/or "cc" - but without tagging them or adding the "followers" collection.

I know that it is a design decision not to allow those postings to be created from the Mastodon UI. But other systems allow this, so Mastodon should accept and display them.

They should be displayed in the regular timeline (like private postings to the "followers" collection). Upon answering such a post, the system has fetch "to" and "cc" from the original post, so that the receivers would stay the same. However, this can be done completely in the background and needn't to be displayed in any way in the UI.

**Comment by arjenpdevries** [comment]
Re: _completely in the background and needn't to be displayed in any way in the UI._

I would prefer to rewrite the original message to include the to: and cc: at the beginning or the end of the message (toot). If the number of characters would then exceed the max, the UI can simply signal that the message is too long to send.

Otherwise, the Mastodon user will end up sending messages to people without knowing that they are addressing those people.

**Comment by annando** [comment]
@arjenpdevries the users often don't know which users are reading their messages, since the original poster will replay the messages to his (or her) followers.

**Comment by puckipedia** [comment]
so this has some tendrils into the work I want to do, which is slightly involved; I've been thinking about adding support for receiving "group messages", messages which are sent to a subset of someone's followers. For example, having a subgroup of trusted followers. Or being able to send messages to a subset of people you've confirmed to be 18+. This requires quite some work in the backend, and I might just be the only one who is really interested in this (though I do consider #8682 a special case of this). Kroeg already supports this, but I might be willing to implement this into Mastodon in the semi-near future whenever I have enough spoons to do so.

**Comment by trwnh** [comment]
@puckipedia You're definitely not the only one who wants something like that... https://github.com/tootsuite/mastodon/issues/5686#issuecomment-414149712 https://github.com/tootsuite/mastodon/issues/7182#issuecomment-414786683 -- it would be really cool to see Mastodon support something like diaspora* Aspects or Google+ Circles.

**Comment by Gargron** [comment]
Fixed in #8950
