### ISSUE TITLE
Support /.well-known/change-password

### ISSUE THREAD

**Issue by thegcat** [tootsuite/mastodon#8771]
Mastodon should support the `/.well-known/change-password` de-facto standard https://mobile.twitter.com/rmondello/status/1009495517494173697 et al.

This would effectively be a 301 from `/.well-known/change-password` to `/auth/edit` for the mastodon Web UI.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
what's the difference between change-password and the linked
modify-credentials spec? is there any spec for what change-password should
do?

**Comment by thegcat** [comment]
It doesn't seem to be much documented and I haven't found any official mention other than on https://developer.apple.com/safari/technology-preview/release-notes/#r59 at the end of the section under "iCloud Keychain Password Manager".

The interesting part in the linked tweet isn't the link to the W3 list as this represents an earlier version of the work, but the tweet and its thread are the interesting part. Ricky seems to be part of the Safari team, and confirmed that redirecting from there to the password update page, or to present the password update page under that URL, would work with Safari/Keychain. GitHub for example also implements this:

```
> curl -v https://github.com/.well-known/change-password
…
< Status: 301 Moved Permanently
< Location: https://github.com/settings/admin
…
<html><body>You are being <a href="https://github.com/settings/admin">redirected</a>.</body></html>
```

There's also a few other projects with issues for this (for example https://github.com/mozilla/fxa-content-server/issues/6561)

**Comment by thegcat** [comment]
@Gargron great, thanks!
