### ISSUE TITLE
Use confirmation dialog before erasing draft to reply to new status

### ISSUE THREAD

**Issue by esnyder** [tootsuite/mastodon#878]
This is the sort of thing that you presumably get trained out of pretty fast, but it's kind of annoying the first few times it happens.

If you start writing something in the "What is on your mind" edit box on the left, and then notice someone says something you want to respond to, and you hit the little 'Reply' arrow under their toot, your existing text is discarded with no undoo possible (as far as I can tell.)

**Comment by offbyone** [comment]
A popover to reply would not be a bad idea.

**Comment by ashfurrow** [comment]
I've had this too when I've started typing and decide to turn it into a reply to an earlier toot, so they're chained.

**Comment by Irick** [comment]
I've had this pattern bite me in the buns a few times as well. 
Distractions make me forget I have something in the buffer, or I forget I already had a tweet in the respond slot and I lose my artful masterpiece D:

**Comment by thirdtruck** [comment]
Happened to me today and then almost a second time to the same toot draft.

Adding a "Are you sure you want to delete this draft?" pop-up would be a nice stopgap measure.

Having a queue of drafts (with new ones opened above existing drafts) might be even better.

**Comment by ashfurrow** [comment]
Definitely a queue of drafts would be ideal, @thirdtruck would you mind opening a GitHub issue for that? 

I like your stopgap solution, I think using the new [confirmation modal](https://github.com/tootsuite/mastodon/blob/master/app/assets/javascripts/components/features/ui/components/confirmation_modal.jsx) would be nice too.

**Comment by rakiru** [comment]
I missed this issue and posted a duplicate. I've closed it, so here's what I said:

> Type a toot, but don't send it, then hit reply on another toot. Your unsent toot is deleted with no confirmation or way to recover it. While this is as a result of a user action, it's also easy to do accidentally or absent-mindedly. A user may also intentionally do this if they're used to websites with inline replies, such as reddit.
>
> There should be a(n optional?) confirmation along the lines of "You have an unsent toot. Are you sure you want to delete it?" if there is any text in the compose box.
>
> (I typed out a whole introduction post, was trying to think if I was missing anything, went to reply to another toot quickly, and lost my post)

**Comment by jpdeplaix** [comment]
Any news on this ?

**Comment by SoniEx2** [comment]
I think the current toot should always carry over unless it's empty.

**Comment by jpdeplaix** [comment]
Sorry to up this again but it has been two months and I got stung again. Anybody working on this ?
Or maybe any documentation to understand the source code and maybe try to fix this ?

**Comment by saper** [comment]
There are different things people want here. And definitely a dialog modal popup is to be avoided at all costs. For some, https://github.com/tootsuite/mastodon/issues/6249 they want to preserve the text because they just change from just tooting to a reply. 

For others, like deciding to reply to someone instead of composing something it is a completely different thing. They wouldn't want to preserve their previous thing. (Or yes, maybe preserve, but not send to someone else by accident).

**Comment by mvz** [comment]
This even happens when clicking reply, typing your reply, then hitting the *same* reply button again.
