### ISSUE TITLE
Expose VAPID public key via the API

### ISSUE THREAD

**Issue by sorin-davidoi** [tootsuite/mastodon#8785]
In order to use the Push Subscription API from a browser the VAPID public key needs to be exposed via the API (in the web interface it is exposed [in the DOM](https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/actions/push_notifications/registerer.js#L17).

This is necessary because you can't get register a push subscription from the browser (`registration.pushManager.subscribe`) without having the `applicationServerKey` (Chrome throws `Uncaught (in promise) DOMException: Registration failed - missing applicationServerKey, and gcm_sender_id not found in manifest`).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
the WebPushSubscriptionSerializer contains the vapid public key, does it need to be available earlier in the process?

**Comment by sorin-davidoi** [comment]
Yes, it is needed before the subscription can be send to the backend.

**Comment by sorin-davidoi** [comment]
Including it in the `WebPushSubscriptionSerializer` is a bit misleading, since it is a instance-wide constant and not something attached to a particular subscription.

**Comment by sorin-davidoi** [comment]
Workaround:
 - Get a push subscription from the browser using a dummy `applicationServerKey`
 - Send this subscription to the backend, obtaining the real `applicationServerKey`
 - Use the real `applicationServerKey` to obtain a new subscription from the browser and send it to the backend
