### ISSUE TITLE
Show full server error when communicating with Mastodon

### ISSUE THREAD

**Issue by fourtonfish** [tootsuite/mastodon#8786]
Would it be possible to return the full server error when communicating with Mastodon?

Right now I'm getting a generic `500 Internal Server Error`. The admin of the instance I'm working with checked the server logs for me and it turned out to be `OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: nested asn1 error`.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
Mastodon will show full errors in development mode. Error messages are not screened for sensitive content so it's not always appropriate to show them in production. Development errors contain a full stack trace and interactive console.

**Comment by fourtonfish** [comment]
That makes sense, thank you!
