### ISSUE TITLE
Set update intervals for timeline displays (instead of continuous)

### ISSUE THREAD

**Issue by HongPong** [tootsuite/mastodon#879]
The local timeline and federated timeline update pretty continuously in a firehose effect. It would be nice to be able to change that per user setting to fixed time intervals. Like 5 seconds, 15 seconds, 30 seconds, 1 minute etc. This would also reduce the server load I would think (perhaps not, I don't know how this thing works internally). Perhaps under high load it could fall back to slower batches of updates, to avert failmastodons.

Anyway thrilled to see that a good GNU social frontend has taken off. Cheers 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Duplicate of #240
