### ISSUE TITLE
Staff badges not being displayed.

### ISSUE THREAD

**Issue by malicioustoker** [tootsuite/mastodon#8797]
I’m not sure what I’m doing wrong, but staff badges are not being displayed on my instance for myself (admin) or mods.

![23709081-d2f4-4d93-ae75-cfc13199270b](https://user-images.githubusercontent.com/1431774/46097784-a0edad00-c177-11e8-9127-081a18a742ef.jpeg)
![2540adb4-5f58-4648-bab8-d83e0d557d04](https://user-images.githubusercontent.com/1431774/46097785-a0edad00-c177-11e8-8db6-955c32868c7c.jpeg)
![87b7a379-2d8b-48a1-bdf0-af5131c8fc55](https://user-images.githubusercontent.com/1431774/46097786-a1864380-c177-11e8-9502-21cfb94934d6.png)

**Comment by connyduck** [comment]
You are not doing anything wrong, that feature simply does not exist. Staff badges are only shown on the public profile pages.
Duplicate of https://github.com/tootsuite/mastodon/issues/6702

**Comment by malicioustoker** [comment]
Ahhhh - thanks!
