### ISSUE TITLE
Boosting this toot makes your account unfollowable

### ISSUE THREAD

**Issue by SirCmpwn** [tootsuite/mastodon#881]
https://mastodon.social/@alahmnat/1603220

Your atom feed 500's: https://sr.ht/mr-i.txt

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Exagone313** [comment]
I had an error like this, on my instance, I had to reinstalll...

**Comment by SirCmpwn** [comment]
If anyone does get this error, I fixed it by wrapping the relevant code in a try...catch and putting a conspicuous URL into the feed to figure out which one was the culprit, then unboosting it, then removing the hacky code.

**Comment by Gargron** [comment]
The code in the stacktrace has been modified a lot since. Is this issue still present?

**Comment by SirCmpwn** [comment]
Try it?

**Comment by nightpool** [comment]
@SirCmpwn yes, someone who is not gargron should try it :P

**Comment by SirCmpwn** [comment]
Well, I would hope he has test accounts. I don't exactly want to test it on my account, either.

**Comment by nightpool** [comment]
@SirCmpwn no, I mean, gargron is busy triaging github issues today, so somebody who has more time on their hands should try it.

Anyway, tried this on my account, can't reproduce. cybre.space/@nightpool.atom still returned the expected content after boosting it (i've since unboosted it)

**Comment by SirCmpwn** [comment]
Alright, thanks.
