### ISSUE TITLE
Informing users of system status

### ISSUE THREAD

**Issue by duckinator** [tootsuite/mastodon#882]
It may be worth adding a way to add a note to the top of every page if there's some technical problem with the site, e.g. the massive lag happening on mastodon.social at the time I'm opening this issue, and have it link to a more thorough description of the issue. As for what it links to, I'd personally go with a Tumblr set up as a status page &mdash; it takes minimal effort to get running, is hosted independently of the main site, you can edit posts when an issue is resolved, etc.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by tobypinder** [comment]
#191 Seems like a more generic version of this suggestion, though the link to the status.* subdomain should be visible elsewhere. Personal +1 for the "quick and dirty" approach of using tumblr for this though, probably easy enough to set up

**Comment by duckinator** [comment]
The reason I suggested also having a way to add a note at the top during ongoing technical issues is because it makes makes it more prominent that there's a problem, and as such may avoid the usual mass-reporting of a single problem. But yeah, just having the status.* page and linking to it somewhere (maybe the rightmost column?) would be really good regardless of if the other part of my idea is implemented.

**Comment by duckinator** [comment]
An alternative approach could be to have a way to toggle a setting that makes the existing status link far more prominent (e.g. turning it red and having a bright icon beside it) when there's ongoing issues.

**Comment by thor-the-norseman** [comment]
This seems to be related to #1209.

**Comment by duckinator** [comment]
Yup, different approach to the same problem.
