### ISSUE TITLE
Timeline's "LoadMore" does not work

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#8821]
After #8736 , if scroll down LocalTimeline, 500 error will occur.

The server log at that time is as follows:

method=GET path=/api/v1/timelines/public format=html controller=Api::V1::Timelines::PublicController action=show status=500 error='ArgumentError: wrong number of arguments (given 2, expected 1)' duration=6.88 view=0.00 db=2.33

Full log is here: https://gist.github.com/mayaeh/4a88c05d8ebd72a22315128da9da5651

I think that this error also occurs in other timelines like FTL.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by 33b5e5** [comment]
When testing from master, I see the same issue on local timeline and notifications.

method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=500 error='ArgumentError: wrong number of arguments (given 2, expected 1)' duration=9.30 view=0.00 db=1.22

**Comment by Gargron** [comment]
I'll check how I broke that :cold_sweat:

**Comment by mayaeh** [comment]
I confirmed that I will fix it with this ( https://github.com/tootsuite/mastodon/compare/master...mayaeh:fix_8821 ), but I think that it will be a not good code...

**Comment by malicioustoker** [comment]
Same issue over here

**Comment by zunda** [comment]
Deeper backtrace below. I could also fix this with reverting the merge of #8736 : `git revert f0fff3e` :)

```
ArgumentError (wrong number of arguments (given 2, expected 1)):

app/models/concerns/paginable.rb:23:in `block (2 levels) in <module:Paginable>'
app/controllers/api/v1/timelines/public_controller.rb:24:in `public_statuses'
app/controllers/api/v1/timelines/public_controller.rb:20:in `cached_public_statuses'
app/controllers/api/v1/timelines/public_controller.rb:16:in `load_statuses'
app/controllers/api/v1/timelines/public_controller.rb:9:in `show'
```

**Comment by malicioustoker** [comment]
I used the git revert command last night and now I can’t figure out what command to use to get back on master. Any help?

**Comment by Gargron** [comment]
If the revert command created a commit on your master branch, `git reset --hard HEAD~1` to go back in history, then `git pull` to get the commits from this repository.

**Comment by malicioustoker** [comment]
You sir are a genius, thanks for all you do!
