### ISSUE TITLE
Public key can get stuck in a state where it's nigh-impossible to unstick

### ISSUE THREAD

**Issue by puckipedia** [tootsuite/mastodon#8822]
When a public key isn't found, the value is set to "", the empty string.
When trying to create an OpenSSL object with this, it throws, causing a 500. However, this happens *before* trying to reretrieve the object, meaning it's basically impossible to get the remote server to update it. The only way is to use the `acct:` keyId, which will redo the webfinger if >1 day since last change. but this shouldn't be needed...

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by puckipedia** [comment]
This was an existing account that I hacked up. Preventing the account to save is probably best, but it might also be useful to have some way to have the server refresh a remote profile when it's in some broken state..

**Comment by nightpool** [comment]
admins and users can refresh an account by putting it's URI into the search
box

**Comment by puckipedia** [comment]
That doesn't help when I accidentally broke my account on pretty much 100% of the servers, and not only that, but should I tell them all that I accidentally my account, and they need to look it up manually?

**Comment by valerauko** [comment]
This doesn't seem to be a common problem, so rescuing that OpenSSL 500 and trying to repair the account might be the lightest solution.
