### ISSUE TITLE
uWS is no longer available via yarn/node

### ISSUE THREAD

**Issue by tielqt** [tootsuite/mastodon#8833]
Mastodon currently has a dependency on uWS (Tiny WebSockets) which is currently unavailable via either npm or yarn. It has been updated to a version number of 99.0.0, which contains only a readme file.

https://cdn.jsdelivr.net/npm/uws@99.0.0/README.md

All previous versions have also been scrubbed. The archived version referenced in the current lockfile seems to work, but throws errors about not being able to compile despite all required tools being available.

It seems the developer, if their commit history is anything to go by, may have stopped development of - and revoked virtually all access to - the project for non-commercial users, as a [note on their repo](https://github.com/uNetworking/uWebSockets) currently says...

> "Understand I don't take issue reports, suggestions or provide any support to free-riders. You want in? Become a sponsor."

No notes on how to do this have been provided. The original author's GitHub history has all but stopped, save for readme updates. They claim that uWebSockets 0.15 is coming soon, but it's not available on any package management currently used by Mastodon.

This dependency should be removed, or the possibility of such should be considered, as the current state of the npm/yarn package means that there will be errors when trying to run the server, which **affects all new deployments of Mastodon** (in development and production environments alike). A potential solution would be to fall back to standard WS. 

I have created a branch for this and am experimenting with the viability of this.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
see #8223, #6853

**Comment by nightpool** [comment]
if you can't compile UWS on your system, that's a different issue, probably related to your OS or dependencies. Mastodon should not be affected in any way by the user maintainer's temper tantrum
