### ISSUE TITLE
Rename "Local Timeline" and "Federated Timeline" for better UX - From @mahnouel@social.targaryen.house

### ISSUE THREAD

**Issue by MichaelSelsky** [tootsuite/mastodon#884]
There's some confusion about what the Federated Timeline is and how it's different to the Local Timeline. [@mahnouel@social.targaryen.house](https://social.targaryen.house/@mahnouel) suggested using local & global or family & community to make it more understandable

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by snomofomo** [comment]
What about 'Instance Timeline' and 'Federated Timeline'?

**Comment by Gargron** [comment]
I like Instance Timeline a lot. Makes it even more clear.

**Comment by mentalina** [comment]
Might I suggest "tribal" and "federated"? Tribe conveys the general idea of self-organized groups united by some sort of commonality, while federated (or federation) conveys a gathering of many tribes. Plus, "Tribeline" is a fun word.

**Comment by mahnouel** [comment]
My point was, these words are uncommon / hard to understand for people who not speak English by default. These are terms a programmer would use, but not the people on the street (in my opinion) - naming it family / community would also convey the concept of it way better.

**Comment by yiskah** [comment]
No. Do not rename the timeline. No. Stop it. We've renamed them like five times. Nobody is every going to understand them intuitively. They are new concepts. "Tribal" makes no sense to be either and has racist connotations. "Instance" is ambiguous and bizarre. 

Local and Federated have been around for a while and is what everyone is used to at this point. People will understand what they are after we implement the onboarding features which explain to them what they are.

**Comment by yiskah** [comment]
If it is unclear to a user from a particular linguistic background it can be something else in that localization. We cannot account for all possible cognates and inter-linguistic connotations out of the hundreds of languages a user may have as their L1.

**Comment by MichaelSelsky** [comment]
> No. Do not rename the timeline. No. Stop it. We've renamed them like five times.

Iteration is good. It means that there is progress. This is still a young piece of software and it's ok to continue to make changes. 

> Nobody is every going to understand them intuitively.

I don't particularly agree with this sentiment. I do believe there is a way to make it more intuitive, I just don't have it yet. Getting a good UX and copy writing is difficult but something that we can work on.

> People will understand what they are after we implement the onboarding features which explain to them what they are.
 
I think that this will help, but most users don't read the on boarding. They just skip through to try and get into the application as quickly as possible. So we still need to make the UI more intuitive.

> If it is unclear to a user from a particular linguistic background it can be something else in that localization.

I totally agree with this. Language support when it comes to this feature will help. But English is just another language. If new users are being confused about what's going on we should change the copy in the English version as well. 

Now I don't have the answers to what we should do about this. But I think it's important that we have this discussion to see if something great comes out of it. I don't like "tribal" and "federated" either. They don't clarify what's happening either. But "local" and "federated" are just as confusing. I've seen people think "local" is what's going on around them geographically. Most people don't come in contact with the word "federated" in their day to day life. 

And in the context of this system there is a lot of nuance to what those two timelines are. And conveying that nuance is difficult. As the saying goes the hardest thing in computer science is naming things. So instead of shooting down the idea of discussing a name change, let's take some time to think about how we can solve that confusion.

**Comment by robcee** [comment]
I suggest keeping Local and renaming Federated to Global.

**Comment by yiskah** [comment]
I already wrote an essay in a duplicate topic on this about why we are tabling this discussion indefinitely. Global was already discussed before and it's a misnomer because it's not 100% and also would further make people think about geography

**Comment by robcee** [comment]
> Global was already discussed before and it's a misnomer because it's not 100% and also would further make people think about geography.

not 100%... accurate? I think you're conflating underlying technology with user-facing interfacing.

I don't see an association with geography as being any more problematic than an association with forms of government. Analogies are useful. And in this case, the word "global" means "everything, all" not "a globe depicting the planet".

Anyway, that's my take.

**Comment by yiskah** [comment]
OK but "Local" doesn't mean "your geographic location" and people are misconstruing it that way too. 
Regardless, we aren't going to rename anything until after the userboom has settled for a long while and we've finished the onboarding modals and JoinMastodon.org to see if they solve the issue without needing to rename

**Comment by jennings** [comment]
I, too, would be in favor of renaming these terms in the UI.

I like all the suggestions people have made here, and they all have merit. If these terms were to be renamed, my vote would be:

* Federated Timeline ⟶ Global Timeline
* Local Timeline ⟶ Community Timeline

**Why "Global"?**

I think "Global" is a good suggestion because it conveys the idea of "toots from everywhere".

Yes, the federated timeline is more nuanced than that, but I'm not sure any single word will convey the complete idea while being accessible to most people. I also worry that the word "federated" is not common among non-technical people, so it will be a sign that This Place Is Not For Me.

I think if someone new sees the word "global", they will likely immediately form a useful idea of what that means. Over time, they will learn the nuance of federation, but "global" communicates enough information to get started.

**Why "Community"?**

At first, I thought Local/Global were a good pair of words, but @yiskah makes a great point: "Local" sounds like geography, when that's not really what we're trying to convey. And, although "Instance Timeline" is accurate, I think many new people will not know what is meant by "instance".

On the other hand, "community" describes the idea of "a subset of people with something in common". When a person new to Mastodon sees "Community Timeline" and "Global Timeline", I think they are likely to form a reasonable working definition of what these are.

**Comment by yiskah** [comment]
*If* the name *has* to be changed, Community is the better option. I still do not believe anything should be renamed until we can see how implementing the actual onboarding features affect user comprehension. (JoinMastodon.org and the modals)

The argument for "federated timeline" is that it makes this word familiar to users who are going to likely be encountering it frequently from now on. Users on the *fediverse* frequently talk about if this or that *federates.* What instances does awoo.space *federate* with? etc.

Once people understand the federated timeline, they seem to be able to intuit federation as a concept in all of the cases where it is used. 

That said, I've now apparently been "assigned" to this issue (thanks Kurtis).

I'll leave this issue open as a place to discuss this, with the understanding that this is a very *down the line* issue. Nothing is getting renamed for a while, and if a few months from now everyone seems to "get" it, then I'll close this issue. If not, then whatever the discussion in this thread concluded was a nice name will be considered. So discuss amongst yourselves what you think, but handle it as "what's the best names" and not "please just change it"

**Comment by expenses** [comment]
Global / Community is definitely better, as the use of `Federated` in this way confused me until I read the FAQ.

**Comment by Gargron** [comment]
While "local" gives people the impression it uses their geolocation (i.e. physically local) I believe that any word will be confusing at first, simply because the concept is new. So given our existing history of using local/federated, I think we should stick to it.
