### ISSUE TITLE
Add option to hide all media by default

### ISSUE THREAD

**Issue by thisisTQ** [tootsuite/mastodon#8891]
Hiding nsfw media is great. But what about giving users the option to hide all media by default? I'm easily distracted by images, and I know I'm not alone. Such a feature would help accessibility, user experience and shouldn't be too hard to implement, as far as I see. 
 
Instead of "Sensitive content" - "Click to view" it could read "Content hidden" and "Click to view". This would also mean users can still see which media was marked as sensitive.

* * * *

- [Y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by thisisTQ** [comment]
Ahhh... That update hasn't been rolled out on any instance I'm on. Sorry.
Great to know it's coming! (Also: Strange I didn't find that issue via the search function... Well.)

**Comment by trwnh** [comment]
Maybe because it's not technically an issue, it's a PR? :)
