### ISSUE TITLE
[Feature Request] Anti-harrassment tools

### ISSUE THREAD

**Issue by shirish93** [tootsuite/mastodon#890]
This was sort of inspired by [this](https://twitter.com/aurynn/status/849385029297991683) post on twitter. 

Can there be ways to block entire domains/exclude everyone except certain domains, etc, so that users may be able to remove malicious domains straight away.

In addition to that, the thread is a pretty important/interesting read -- not sure what else I can come up with ATM, but hope you keep those issues in mind!
* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by yipdw** [comment]
This appears to be a duplicate of #423.

**Comment by ashfurrow** [comment]
Agreed, going to close. Please continue conversation in #423. Thanks!
