### ISSUE TITLE
Mastodon doesn't display Thai text from Friendica properly.

### ISSUE THREAD

**Issue by veer66** [tootsuite/mastodon#8902]
Mastodon doesn't display Thai text from Friendica properly.

https://mstdn.io/web/statuses/100848623556230340

![screenshot_2018-10-06 mastodon](https://user-images.githubusercontent.com/370688/46571371-27876300-c99e-11e8-857b-6ec7203db602.png)

But Pleroma did.

![screenshot_2018-10-06 20 vmsg](https://user-images.githubusercontent.com/370688/46571379-4554c800-c99e-11e8-97ac-7b633383946f.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. (Yes, at least, I searched "thai")
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). (I don't know. It was mstdn.io.)

**Comment by nightpool** [comment]
This is because we don't currently allow HTML in converted object type titles (Article as opposed to Note).

**Comment by nightpool** [comment]
The AS2 spec for `name` says:

> A simple, human-readable, plain-text name for the object. HTML markup must not be included. The name may be expressed using multiple language-tagged values.

**Comment by Gargron** [comment]
In other words, it would be fine if Friendica used UTF8 instead of HTML-encoding Thai characters.

**Comment by annando** [comment]
Thanks for the hint, squeet.me is running on the "Develop" branch and is my secondary test server. So this will be fixed soon.

**Comment by nightpool** [comment]
👍

**Comment by annando** [comment]
PR is merged, squeet.me is updated.
