### ISSUE TITLE
Allow individual users to follow other users from banned instances

### ISSUE THREAD

**Issue by frandavid100** [tootsuite/mastodon#8911]
The admin of instance A has decided to ban instance B.

However, a user in instance A wants to follow and interact with another user in instance B. Right now there is no way for him to do that unless he creates a different account, in a different instance, specifically for that purpose.

I think that he should be able to override the ban, follow that user, get his toots, reply to them and even boost them, even if that doesn't make them show in the timeline of his followers in instance A.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
Mastodon has two types of instance bans for admins to use: silence and suspend. Silence behaves as you suggest, in that it doesn't apply to users that follow accounts from that instance. Suspend is a flat rejection policy applied to messages from the suspended instance—very comparable to a firewall or IP block that the admin could put in place.

**Comment by Laurelai** [comment]
This is a really bad idea.

**Comment by tfardet** [comment]
@Gargron In the context of threads.net entering the Fediverse, I think this idea might be worth revisiting as an additional option when suspending a server instance-wide.

See e.g. the solution implemented by sciences.re: https://social.sciences.re/@RGrunblatt/111748187427792269

In combination with "authorized fetch" this allows for opt-in behavior by individuals regarding privacy-invasive actors.

For example, one could set a "default-suspend" option for some domain for all accounts. This suspend could be deactivated independently by each account. This way there could be both "absolute" suspend, that cannot be overridden and "optional" suspend that each person can chose to lift.
