### ISSUE TITLE
How to serve S3 assets over HTTPS on Heroku install?

### ISSUE THREAD

**Issue by ashfurrow** [tootsuite/mastodon#892]
Good evening! Lovely project you've got here. I'm trying to set up an instance using Heroku but I'm running into an issue where assets being served over HTTPS from S3 have certificate warnings in some browsers.

![screen shot 2017-04-04 at 7 01 37 pm](https://cloud.githubusercontent.com/assets/498212/24682728/38c6e438-1969-11e7-85b9-fc07620c96b8.png)

This may be a question unrelated to the project and more related to generate web administration, but how could I get Mastodon to use bucket URLs with HTTPS support? For example

```
https://s3-us-west-2.amazonaws.com/static.mastodon.technology/accounts/avatars/000/000/001/original/d30e780f59153afb.jpeg?1491344280
# instead of 
https://static.mastodon.technology.s3-us-west-2.amazonaws.com/accounts/avatars/000/000/001/original/d30e780f59153afb.jpeg?1491344280
```

Is there any reason the code currently uses one format or the other? I'm happy to help any way I can. Thanks!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Adjust the `S3_PROTOCOL` environment variable in `.env.production` to say https instead of http

**Comment by ashfurrow** [comment]
Perfect, thank you :bow:
