### ISSUE TITLE
Only 5 search results are returned per section.

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#8939]
When searching for accounts, hashtags, and optionally old toots, only 5 items are returned. This is an issue because there doesn't seem to be a way to load more results, and 5 is not nearly conclusive. For example, when trying to search a certain username to block across multiple instances, it's not good to only be able to block 5 accounts out of 20-30. Or when trying to find an old toot, perhaps it was the 6th result you would have been looking for.

**Comment by Scotty-efird** [comment]
How many would you suggest changing it to? Personally my favorite solutions tend to have the "5 results with N more".

**Comment by woffs** [comment]
I tend to 200.
