### ISSUE TITLE
Find Google Plus friends on Mastodon

### ISSUE THREAD

**Issue by sebilasse** [tootsuite/mastodon#8949]
Now that google+ was added to [/site-deaths](https://indieweb.org/site-deaths) it would be superfun to find possible friends via g+ OAuth in [bridge.joinmastodon.org](https://bridge.joinmastodon.org/).
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by justinmayer** [comment]
@sebilasse: With the nagging sensation that this isn't the right repository for the issue you submitted, I looked through the [Tootsuite organization's repository](https://github.com/tootsuite), and sure enough, I found this: https://source.joinmastodon.org/mastodon/bridge.

In short, I don't believe this is the correct place for this issue, and I recommend you close it. Thanks.

**Comment by sebilasse** [comment]
@justinmayer Hm, https://github.com/tootsuite/mastodon-bridge told it is "archived".
Unfortunately I don't have a gitlab account.
