### ISSUE TITLE
Performance suggestion: Stream *only the necessary* toots b/w instances.

### ISSUE THREAD

**Issue by taoeffect** [tootsuite/mastodon#895]
So I noticed the Federated timeline appears to contain... everything, e.g. from all of the connected instances.

That is a lot of traffic for the poor mastodon.social to handle.

Maybe get rid of that timeline (which nobody can read quickly enough anyway), and have instances send toots to each other *only* when users cross-instance toot at each other?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Toots of a user are only sent to instances that have some people that follow that user. So it's already what you describe. The load doesn't come from the federated traffic but from 4000 toots per hour created on mastodon.social by local users

**Comment by taoeffect** [comment]
OK, thanks for the explanation and my apologies for not looking more deeply into it!
