### ISSUE TITLE
PgHero Connections graphs broken on master

### ISSUE THREAD

**Issue by 33b5e5** [tootsuite/mastodon#8966]
When testing from master today (at 9d4541c) it seems the graphs on the PgHero / Connections page (ex: https://mastodon.social/pghero/connections) are broken:

![image](https://user-images.githubusercontent.com/2781306/46846621-35215c00-cd95-11e8-99e7-21d3290b354f.png)

This only started happening recently, somewhere between 2.5.0 and now. I confirmed the same regression on a second instance. Graphs load on 2.5.0, but don't when running from master.

It doesn't seem very impactful since only admins can access pghero.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by rhaamo** [comment]
do you happends to have a content-security-policy set by your nginx vhost ?

it seems it may block the loading of the graphs if not authorizing the right thing (browser console should spew errors in that case)

**Comment by Gargron** [comment]
The new CSP rules added in #8957 block inline scripts. The charts are created using inline scripts. I think that either PgHero needs to add controller-specific CSP whitelisting upstream, or we need to monkeypatch it.

**Comment by Gargron** [comment]
I think that ankane/pghero#239 might do it.

**Comment by grinapo** [comment]
Just noting: Still broken.

**Comment by ykzts** [comment]
ref https://github.com/ankane/pghero/pull/281
