### ISSUE TITLE
Allow moderators to always send direct messages to local users

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#8969]
Users can disable direct messages from people they don't follow. That is of course a good privacy feature, but moderators need to be able to send direct messages to local users. Of course moderators can decide not to use direct messages, but moderation in the open is mostly not very productive.

So please allow moderators to always send direct messages to local users.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
moderators can view all user emails, I generally use that for moderation
purposes.

**Comment by jeroenpraat** [comment]
@nightpool What you mean with 'can view all user emails'?

**Comment by nightpool** [comment]
the email addresses of all registered users

**Comment by jeroenpraat** [comment]
Yes okay, that's an option, but I prefer to keep it inside Mastodon.

**Comment by manedfolf** [comment]
I think there is a decent argument to be made that administrators should be able to contact users within their instance no matter what. 

_However_, email will always work presuming the user has a valid one, and if a user doesn't respond to inquiry, there's always the ban hammer. It's on users to pay attention, and if they attempt to cut off communication or don't do their due diligence, that becomes their problem.

**Comment by jeroenpraat** [comment]
@manedfolf This feature request is not about arguing which moderation technique is the best. You have yours, I have mine.

**Comment by qguv** [comment]
I'm working on an implementation.
