### ISSUE TITLE
Pointing your own domain at mastodon.social

### ISSUE THREAD

**Issue by DanielHeath** [tootsuite/mastodon#897]
First off - thank you so much! Impressive work.

I'd like to use mastodon.social to host my toots, but I'd also like to use my own domain (to maintain ownership/portability of my name/network). I could run my own instance, but that requires a nontrivial amount of administration time.

With email, many providers will let me point my MX records at them and will handle mail for me. I'd love to have the same feature for mastodon via a CNAME record.

This would not work with shared hosts like heroku (they use the domain to figure out which app to route requests to), but could otherwise be a relatively manageable change.

Would a PR to implement this be welcome?

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by lmorchard** [comment]
> I could run my own instance, but that requires a nontrivial amount of administration time.

I suspect that's going to be the recommended option here - run your own instance at your own domain. I hear there's a Patreon level to get the guy who runs mastodon.social to do it for you. :grin:

**Comment by jlnostr** [comment]
@DanielHeath Definitely a nice idea, didn't thought so far 🤔

**Comment by maethor** [comment]
Has anyone tried this on a personal instance?

The domain is specified in the config, so I don't think it would work right now, but I'm planning to try in a few hours.

**Comment by robjloranger** [comment]
probably just run your own instance. you can have a custom domain and maintain ownership of all uploaded content etc.

**Comment by DanielHeath** [comment]
That seems pretty wasteful - my instance would be using half a gig of ram to serve two users. 

I don't have a problem paying to use my own domain (indeed, I'd expect to pay - "Use your own domain" is how eg gmail, fastmail, wordpress etc segment their pricing)

**Comment by maethor** [comment]
Imagine the same thinking about emails. Does everyone needs it's own instance to have email addresses with own domain? Of course not. I think the reasoning is exactly the same.

It could be really nice to have this on Mastodon, because it would allow to host institutional accounts. For instance, we begin to see some french medias (Le Monde, Numérama, Mediapart) on Mastodon. Own domain would allow for instant identification as « official accounts », and for independence between them and their provider. A business could be developed on this.

Own instance maybe a way to go, but it's a waste of time (not only installing, but upgrading) and ressources. It's not for everyone.

Finally, own instance equals pretty small federated network. You could want to have a nice local network to develop your federation. A local network of medias for instance, with each one with its own domain, would be pretty interesting.

**Comment by lmorchard** [comment]
> That seems pretty wasteful - my instance would be using half a gig of ram to serve two users.

🤷‍♂️ I'm using around 1GB RAM right now on my hobby server to serve one user, but then I use it for a handful of other projects anyway.

> I don't have a problem paying to use my own domain (indeed, I'd expect to pay - "Use your own domain" is how eg gmail, fastmail, wordpress etc segment their pricing)

Problem is, this isn't a business. It's a community project. It might seem "wasteful" to set up your own instance, but paying with your own time & effort & resources is basically the price for joining the network in the way you'd like. It's all a DIY affair until/unless someone actually does decide to build a business around it, with all the customer service & related hassles that accompany that. 

There's no pricing other than a Patreon reward to have the project owner set up an instance for you - and I'd bet he's a bit too overworked right now to actually commit to that if someone went for it.

**Comment by lmorchard** [comment]
> Imagine the same thinking about emails. Does everyone needs it's own instance to have email addresses with own domain? Of course not. I think the reasoning is exactly the same.

The reasoning might be the same if this were a business aimed at accumulating money-generating users. But, it's not. It's a community project with different motivations. Sweat equity is more valuable at this stage.

> Finally, own instance equals pretty small federated network. You could want to have a nice local network to develop your federation. A local network of medias for instance, with each one with its own domain, would be pretty interesting.

I've got a single user instance - just me. I've followed a little over 250 people now, and my federated timeline is pretty active. The network effects of seeing the follows of follows adds up pretty fast.

**Comment by lmorchard** [comment]
All of this to say: mastodon.social is not like other services and expectations from for-pay or ad-driven services will probably not carry over in a satisfying way.

Still, as a feature request, it would be interesting if Mastodon (the software) could support multiple domains as "virtual hosts" for instances that *do* want to support this kind of thing.

**Comment by maethor** [comment]
I was talking about the software.

**Comment by lmorchard** [comment]
> I was talking about the software.

Yeah, I think it's useful to separate a) the feature request for the software in general from b) the ask of mastodon.social & its owner in particular. Someone could someday use a) to provide a hosting business.

**Comment by DanielHeath** [comment]
Good point, thanks @lmorchard . 

Whether the owner of mastodon.social would enable this on their instance is completely separate from whether it's a worthwhile feature.

That said, I'd be hesitant to implement it without having a comment from someone in the core team indicating it'd be mergeable.

**Comment by codydh** [comment]
I think this is a really interesting idea. 

A point on the side of running personal instances: Hopefully efforts continue to optimize Mastodon and to improve administration of an instance from the web (e.g. for data retention). If it gets to the point where it can comfortably run in a small VPS somewhere (e.g., a $7/month Heroku dyno or $5/month Digital Ocean droplet) and be easily deployable (e.g., Heroku button), this seems like a good middle ground. And the Heroku button is already 90% of the way there.

**Comment by Gargron** [comment]
Technical issue: #2668

**Comment by raphaeljolivet** [comment]
I have the same requirement.
I have recently migrated my emails to a custom domain for this exact reason.

I would like the same for social media.
Have a look at this project :
https://github.com/tsileo/microblog.pub

This is a light weigth single user self hosted Activity Pub server.
I think I will set it up on my VPS for that purpose.
But definitely, it would be very nice for Mastodon to support this.

**Comment by raphaeljolivet** [comment]
So ... I have managed use use my custom domain and make it point to a shared instance, without hacking Mastodon 
... and, it kinda works ...

I have developed a small python app  [webfinger-proxy](https://github.com/raphaeljolivet/webfinger-proxy) to alias your own domain handles to a shared instance. 

I have setup it on my own domain [rjo.name](https://rjo.name).
The handle `testrjo@rjo.name` points to `testrjo@mamot.fr` 
See the response of the Webfinger [https://rjo.name/.well-known/webfinger?resource=testrjo@rjo.name](https://rjo.name/.well-known/webfinger?resource=testrjo@rjo.name)

I have managed to follow this account and send it private messages.
I have another account on the same shared instance, and `testrjo@mamot.fr` appears as a completely separate remote account though. 

I am not sure whether this is only on the UI or if Mastodon now have a duplicate account for this guy ... 
I would need some help from the developers to figure this out : Is the handle a primary key ? Or is it the URL ?
Can you see any have adverse effects ?
Do you think the physical migration of accounts from one instance to another would still work ?

I will continue my tests with other implementations : 
Pleroma, mobile clients, etc ....
