### ISSUE TITLE
In profile metadata: auto-create hyperlinks

### ISSUE THREAD

**Issue by MathiasRenner** [tootsuite/mastodon#8975]
In the section profile metadata, plantext can be added both for the metadata's label and content:

![grafik](https://user-images.githubusercontent.com/2377464/46904854-2947ae00-ceeb-11e8-967d-4f62bb2d1086.png)

Like in the screenshot, many users probably add in the field `content`URL links, e.g. to a private website or blog. 

What about recognising links and transforming them to clickable hyperlinks? On mobile, using the app `mastalab` this is already been done. In my browser, I only get plaintext... don't know why.

**Comment by Gargron** [comment]
http:// or https://

**Comment by MathiasRenner** [comment]
Oh, I seee :) Sorry, I thought I tried that... Yep works.
