### ISSUE TITLE
broken alignment at "Remote interaction dialog"

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#8987]
After #8979 , alignment of toot text is broken as follows at  the remote interaction dialog:

before:
<img width="557" alt="2018-10-15 14 14 31" src="https://user-images.githubusercontent.com/766076/46933665-f7bc1780-d08f-11e8-8b9f-4939e7976e2c.png">
after:
<img width="557" alt="2018-10-15 14 14 40" src="https://user-images.githubusercontent.com/766076/46933684-0efb0500-d090-11e8-9a8c-32dac491059d.png">
I think that it is necessary to set text-align according as the language of toot text.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mabkenar** [comment]
Could you please provide a link to the toot so that I can test it as well? I couldn't reproduce the problem.

**Comment by mayaeh** [comment]
Oh ... It happens in my environment, but I am trying it only on the Japanese environment at the system level.

The URL you provided is the same as what I tried.

Later I'll try it in another language environment.

**Comment by mabkenar** [comment]
I think I've fixed this bug (which was my fault afterall) in https://github.com/tootsuite/mastodon/pull/8988.

**Comment by mayaeh** [comment]
It looks good!

The follow-prompt class is used in several places, but I think that there is no problem within the range that I saw.

Thank you!

**Comment by mayaeh** [comment]
I confirmed that it will be fixed by # 8988.
Thank you!
