### ISSUE TITLE
Add FTP as a generic alternative option to S3 and S3 compatibile services

### ISSUE THREAD

**Issue by caffeinewriter** [tootsuite/mastodon#8990]
### Pitch

Adding FTP as an option for a media host would allow more options to be used as a media host. It would prevent getting locked in to a specific vendor, and wouldn't mandate an S3 compatible API. It would also open up many more services immediately without working on custom adapters for them.

### Motivation

I personally use a CDN (BunnyCDN) which provides some object storage, but does not appear to offer an S3 compatible API. They do, however, offer a FTP upload method, as I'm sure many others do. It would also allow people to use FTP servers for uploading. 

Considering Mastodon uses paperclip, there does appear to be a gem to enable paperclip to upload to FTP.

https://github.com/xing/paperclip-storage-ftp 

This is mentioned in the helpful links section of Paperclip:

https://github.com/thoughtbot/paperclip/wiki/Helpful-Links

I'm not sure how difficult this would be to work in to the current configuration/setup flow, but FTP would be a great general-purpose asset upload option.

**Comment by nightpool** [comment]
FTP is a really, really old protocol, full of edge cases and weird corners and lots of fiddly things to get right. I wouldn't be surprised if this was really hard to implement (otherwise, why hasn't anyone written a universal s3-to-FTP proxy yet?)

On our side, it would probably be possible to drop in paperclip-storage-ftp and call it a day, but i would be worried about reliability and completeness

**Comment by nightpool** [comment]
Luckily, it's very easy for admins to add and configure paperclip-storage-ftp if they want to try using FTP storage, unsupported by us.

**Comment by caffeinewriter** [comment]
I might give it a shot myself. I know FTP does get a bit fiddly with certain use cases, but I can't think of another generic file storage protocol off the top of my head. Perhaps it'd be possible to do something with a network mounted file system instead, which wouldn't require configuring anything on the Mastodon side. (There is FTPFS, but that is a disaster waiting to happen, so the provider would have to offer some kind of network mount on their own) 

I might try paperclip-storage-ftp myself, and see if I can dig out any caveats or anything along those lines.

**Comment by Gargron** [comment]
Add the gem to Gemfile, add configuration in config/initializers/paperclip.rb, and you should be good to go. The use case is too narrow for upstream adoption, in my opinion.
