### ISSUE TITLE
Several instances not well synchronized

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [tootsuite/mastodon#9000]
### Expected behaviour

Accounts should show the same info when seen from different instances.

### Actual behaviour

Two accounts on different instances do not see the same things when looking on each other.

### Description of the problem

From @h30x@mastodon.zaclys.com : 
![from_zaclys](https://user-images.githubusercontent.com/18427584/47104939-e6673c80-d242-11e8-8175-abcdd51b8fd2.png)

- h30x accounts details are visible
- luluples accounts details are **not** visible
- all posts are visible

From @luluples@mstdn.geekshell.fr
![from_geekshell](https://user-images.githubusercontent.com/18427584/47104981-05fe6500-d243-11e8-8c8b-3d1e9e86ee8d.png)

- h30x accounts details are visible
- luluples account details are 
- **only a few posts** are visible

Among these posts one has been posted way long before luluples account's creation and other are very recent.

### Specifications

Both instances use mastodon version 2.5.2

- https://mastodon.zaclys.com/about
- https://mstdn.geekshell.fr/about

Screenshots are taken from Tusky mobile app, but the same problem appears on the web.

**Comment by Gargron** [comment]
This is not a bug but an artifact of how federation works. Remote account posts are not downloaded, individual posts can be downloaded manually using search or boosts by somebody else, otherwise posts are only stored from the point when somebody follows that account for the first time.

**Comment by Hugo-Trentesaux** [comment]
So it means that luluples will never be able to see my older posts except those who were boosted by someone in her instance ?
Strange...
What do you mean by "using search" ?

**Comment by trwnh** [comment]
@Hugo-Trentesaux 
>luluples will never be able to see my older posts except those who were boosted by someone in her instance

You may be looking for #34 then. That issue is about fetching old statuses when you follow someone.

>What do you mean by "using search" ?

You can copy the link to a post and paste it in the search bar; this will load it manually. 
![image](https://user-images.githubusercontent.com/10606431/47124396-3e9e3e80-d243-11e8-9621-2b8bafb86c78.png)

You can copy the link from the time stamp on each post. See also #6848 for requesting an easier way to copy the link
