### ISSUE TITLE
Default instance level encryption for DM

### ISSUE THREAD

**Issue by 1000i100** [tootsuite/mastodon#9004]
It probably could be implemented as a 3rd party app using the REST API but i think it should be the default behaviour in name of privacy by design.

### Pitch
I've read this : https://github.com/Plume-org/Plume/issues/216
If this issue is possible, it mean DM are readable by other people than the only one that should read it.

My proposition for more privacy : 
- At instance level expose a public key. (reading other issue, i think it's already done)
- when a DM is submit, crypt it with destination user instance key (it perhapse already done, but only for transfer to any federated instance, not specificaly to the destination user instance).
- only the target instance is able to decrypt the message for the legitimate user reading, not other federated instances.

- [x] I've search in issues and don't find any similar feature request.
https://github.com/tootsuite/mastodon/issues/8123 is about E2E encryption, i think it's not technicaly possible to add this as default for all user without asking them for a 2nd specific password or keyfile never send to instance server, that's why i'm not sure E2E encryption should be push as default... but why not O:) 

### Motivation

In name of privacy by design !
If a privacy policy can be a ciphered privacy policy, it should be, at lease every time it can be done at no end user ergonomic cost (and in many case with few end user ergonomic cost in my opinion).

For sure, it will not benefit to NSA, GAFAM and other personal data analyst and seller, and i think this is a big benefit for end user.

**Comment by Gargron** [comment]
A DM is stored on the server of the sender and the recipient, and nowhere else. How would such encryption help anything? The transport layer is encrypted anyway via TLS.
