### ISSUE TITLE
Closer to a feature request,

### ISSUE THREAD

**Issue by LWFlouisa** [tootsuite/mastodon#9011]
While I appreciate the effort that goes into providing a healthy and non toxically social environment, I would prefer if admins did not keep a copy of my password.

If the user being banned were serial killers and criminals, it would be one thing. But because of the nature of smaller communities, I've been a part of communities who ban users for liberal viewpoints. That almost entirely defeats the purpose of a platform of social liberals.

So unless there are other ways they're removing profile information, emptying your posts, and so on (all are pure abuses on power that would make more authoritarian people proud), I don't feel comfortable with the idea of people keeping a copy of my password to misuse it.

Someone may be a bonevolent dictator in once instance, or they could be sold out by the NSA, and purge your information simply for disparaging the US imperial policy. You really can't know if admins are allowed to have your information.:/

But it seems like a huge security issue.

**Comment by Gargron** [comment]
Admins do not have your password. It is stored as a one-way hash using bcrypt. Admins do not need a password to remove your profile.
