### ISSUE TITLE
Updating community/public timelines immediately is not working

### ISSUE THREAD

**Issue by theboss** [tootsuite/mastodon#9034]
Before #8940 , community/public timelines updated immediately after posting.

Currently, it refreshes only home timeline.

https://github.com/tootsuite/mastodon/blob/f468bfb83004bf9b688cdcec5da41453e0390a3f/app/javascript/mastodon/actions/compose.js#L145-L152

### Expected behaviour

Home/community/public timelines are updated immediately after posting

### Actual behaviour

Only home timeline is updated

### Steps to reproduce the problem

- Post toots in a slow environment

### Specifications

- 2.6.0rc1

**Comment by nightpool** [comment]
yeah this logic is just wrong, it should be 
```
if (response.data.visibility === 'direct' && getState().getIn(['conversations', 'mounted']) <= 0) { 
   routerHistory.push('/timelines/direct'); 
 } else if (response.data.visibility !== 'direct') { 
   insertIfOnline('home'); 
 }

if (response.data.in_reply_to_id === null && response.data.visibility === 'public') { 
   insertIfOnline('community'); 
   insertIfOnline('public'); 
 }
```
