### ISSUE TITLE
Toot replies as unlisted by default

### ISSUE THREAD

**Issue by SirCmpwn** [tootsuite/mastodon#904]
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
This is now a preference you can set 🎉

<img width="818" alt="screen shot 2017-04-21 at 10 27 12 pm" src="https://cloud.githubusercontent.com/assets/498212/25300633/bf20a160-26e1-11e7-9805-bb91dbf6136c.png">

I'm going to close this issue; please don't hesitate to re-open if you feel it hasn't be adequately addressed. Thanks!

**Comment by ticki** [comment]
@ashfurrow this is wrong. OP is talking about post _replies_, whereas the setting you're giving is default in general. Please reopen the issue.

**Comment by ticki** [comment]
I opened a new issue with some more info, don't worry.

**Comment by ashfurrow** [comment]
Great, thanks for following up!
