### ISSUE TITLE
Server crash during update lead to database loss

### ISSUE THREAD

**Issue by enbytv** [tootsuite/mastodon#9042]
I was in the process of updating the server for my Mastodon Docker instance (appdot.net) to v2.5.2 when it crashed due to loss of network connection. On reboot the instance appeared to be new - it was completely empty. This is probably because despite the relevant lines having being uncommented in _docker-compose_ the database ended up in _/var/lib/docker/volumes_.

I have restored from a mirrored backup (from four days ago) which has given me data up until then. I would now like to restore the database from an AWS backup generated using _pg_dump_, but the _pg_restore_ commands I have tried have all failed.

Honestly I'm unsure how to get the data from the AWS _pg_dump_ backup back into the server without losing more data.

**Comment by nightpool** [comment]
Hi! thanks for reaching out. We use Github mainly to track bug reports and feature requests. I've created a thread for this on discourse.joinmastodon.org, and replied there: https://github.com/tootsuite/mastodon/issues/9042

**Comment by nightpool** [comment]
Oops, wrong link: https://discourse.joinmastodon.org/t/server-crash-during-update-lead-to-database-loss/1337/3
