### ISSUE TITLE
Missing reply chains on a federated toot

### ISSUE THREAD

**Issue by riking** [tootsuite/mastodon#905]
Clicking into the single-toot view on a post from another instance isn't rendering the replied-to toots correctly.

Prior toots in the chain **from the same author** do render.

Guess: this happens when the other conversation member isn't being followed anywhere on this instance?

---

Screenshot of no reply chain:

![image](https://cloud.githubusercontent.com/assets/627891/24686471/fc040094-1968-11e7-9452-377b870aba4b.png)

versus 

![image](https://cloud.githubusercontent.com/assets/627891/24686459/e614a7fc-1968-11e7-901c-2b0c92953c43.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by riking** [comment]
Another example. I am on social.wxcafe.net, the displayed toots are on mastodon.social, and the missing toots are on social.lou.lt.

![image](https://cloud.githubusercontent.com/assets/627891/24686528/6bb6f112-1969-11e7-8021-7a925495ec0e.png)
https://mastodon.social/users/sarahjeong/updates/1611755

**Comment by Fastidious** [comment]
This becomes particularly a problem on user’s main page, like https://mastodon.social/@david. There are absolutely no references to what’s been replied, not even if replies are occurring on the same Mastodon instance. No good.

**Comment by nightpool** [comment]
this is a huge usability pain to me right now—i've started opening every tweet I want to see in a new window, so I don't miss anything

Is it possible to do client-side loading of statuses? Or does that not work with mastodon's architecture? That would be the the ideal solution in my opinion—load the status ephemerally client-side and only commit it to the mastodon database if a user interacts with it in some way.

this can also be extended to loading replies *to* statuses in the expanded view, which is also a huge UX headache in my experience.

**Comment by ashfurrow** [comment]
This seems to be working for me on 1.2.2, can someone else verify that it's still an issue?

**Comment by wolfteeth** [comment]
I still have issues with this (v1.2.2). Remote replies don't load their parent toot.

**Comment by wolfteeth** [comment]
Still seeing on v1.4.1. This went away when I was on v1.3.x but it is back now. I had forgotten about this thread and created a dup: https://github.com/tootsuite/mastodon/issues/3455

**Comment by wolfteeth** [comment]
This bug has been very annoying to me recently. Someone I follow had a lot of public conversations with people on other instances, and every one of their replies would end up as a context-free standalone toot on my instance. AND it would show up in my home timeline even though I don't follow the other person in the conversation.

There is a discussion on the Discourse board about this: https://discourse.joinmastodon.org/t/1-4-1-probing-of-conversation-issues/354/15

Could be a problem with conversation_id vs. in_reply_to.

**Comment by MCMic** [comment]
Same problem here, a bit annoying.
I also open all toots on there originating instance as a workaround.

**Comment by Cassolotl** [comment]
Is this resolved since we switched to ActivityPub?

**Comment by Gargron** [comment]
Probably, yeah
