### ISSUE TITLE
Allow user name  containing "-" for remote accounts

### ISSUE THREAD

**Issue by stom79** [tootsuite/mastodon#9066]
### Pitch
Currently, it's not possible to federate Peertube channels because their names contain by default "-" (which comes from their uuid) and I get an error 422.

If Mastodon accepts username with "-" It would be possible to follow Peertube channels like any other remotes accounts.
### Motivation
I implemented with Mastalab the ability to follow Peertube channels. It works when the name is customised (ie: doesn't containe "-" chars). But, most of these channel names are default ones.

**Comment by trwnh** [comment]
wasn't this fixed by #9345
