### ISSUE TITLE
v2.6.0rc2 : bundle install -> fatal: Could not parse object '7a57fbe7000f4f8120e250a757ab345c28c6885c'.

### ISSUE THREAD

**Issue by salvadorpla** [tootsuite/mastodon#9098]
Hello,

after fetching v2.6.0rc2, 'bundle install' returns following error:

Fetching gem metadata from https://rubygems.org/.........
Fetching https://github.com/Gargron/i18n-tasks.git
fatal: Could not parse object '7a57fbe7000f4f8120e250a757ab345c28c6885c'.
Revision 7a57fbe7000f4f8120e250a757ab345c28c6885c does not exist in the repository
https://github.com/Gargron/i18n-tasks.git. Maybe you misspelled it?

**Comment by ykzts** [comment]
https://github.com/Gargron/i18n-tasks/tree/7a57fbe7000f4f8120e250a757ab345c28c6885c

It seems to exist to me.

**Comment by Gargron** [comment]
Hmm, it seems to exist, but I did force-push to the branch recently so maybe github made the old commit unavailable...

Anyway, this is a temporary measure and I'll be updating the dependency before 2.6.0 comes out, hopefully with a stable i18n-tasks release!

**Comment by salvadorpla** [comment]
I will try later on but yes, I’m not in a hurry. Just opened this to inform you about something never happened to me before.

**Comment by salvadorpla** [comment]
Still no luck, heh.
'bundle install --verbose' claims PathError:

Running `bundle install --verbose` with bundler 1.17.1
Found no changes, using resolution from the lockfile
Bundler::PathError: The path `.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/posix-spawn-58465d2e2139` does not exist.
...
The definition is missing dependencies, failed to resolve & materialize locally (https://github.com/rtomayko/posix-spawn (at 58465d2@58465d2) is not yet checked out. Run `bundle install` first.)

Nice! I must run bundle install to solve missing dependencies, lol.

**Comment by salvadorpla** [comment]
Found the solution.
Installed posix-spawn by doing 'bundle install --without development test' and then 'bundle show posix-spawn' returns:

.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/posix-spawn-58465d2e2139

Good!

and after 'bundle install' I get:

Bundle complete! 114 Gemfile dependencies, 197 gems now installed.

Woohoo!
My instance is running v2.6.0rc2 now. Closing this.

**Comment by salvadorpla** [comment]
@Gargron hey Eugen, solve it ;-)
