### ISSUE TITLE
Video processing for media uploads happens in the req/res cycle, and not in background

### ISSUE THREAD

**Issue by asonix** [tootsuite/mastodon#9106]
Nginx's current stable version does not have support for modifying an upstream keepalive timeout. Nginx is currently the recommended way to proxy for mastodon. My server is too slow to process the video in under 1 minute, even for webms as small as 2.4 MB, so I effectively cannot upload webms.

### Expected behaviour
Video processing happens in the background.

### Actual behaviour
Video processing happens during the request response cycle.

### Steps to reproduce the problem
 - run mastodon
 - upload webm

### Specifications
version 2.5.2

**Comment by asonix** [comment]
I was wrong about nginx not supporting upstream keepalive timeouts. What I actually needed was to set the `proxy_read_timeout`, but it needs to be set *before* the `proxy_pass` line because otherwise it has no effect.

**Comment by pullopen** [comment]
Still meeting with 504 Error when I upload a big gif, seems that it can be fixed by changing the nginx settings. Thank you for the suggestion!
