### ISSUE TITLE
Making Mastodon pass in the W3C HTML check

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#9111]
![grafik](https://user-images.githubusercontent.com/40538332/47546576-2e94f780-d8f2-11e8-88f4-76376f3f98ef.png)

I'm not pretty good at explaining stuff. Most people just seem to use the W3C Validator on Mastodon. Even I say that every good website needs to be valid by the W3C HTML Validator.

**Comment by Gargron** [comment]
I believe the missing alt tag was fixed in master but it's not really an "invalid html" problem as much as a11y (except the elephant doesn't contain important information so it's all moot anyway)
