### ISSUE TITLE
Needs a "mastodon" emoji

### ISSUE THREAD

**Issue by john-light** [tootsuite/mastodon#912]
Because mastodons are awesome!

Alternatively: add ability to upload custom emoji.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Fastidious** [comment]
You mean, 🐘? There is no such thing as custom emoji. Emoji works well because they are standardised.

**Comment by xori** [comment]
:shipit: is not a standard emoji, yet here it is. Custom emoji are useful and create a culture between those who use them. I see it no differently than attaching an image to a post, however it probably doesn't fit into the GNU Social model.

**Comment by James-Firth** [comment]
Slack does a fairly good job at using custom emoji, but I feel that wouldn't work well with mastodon as we would just see squares on other instances or need to deal with inline images (as @xori pointed out)

**Comment by wxcafe** [comment]
This would be really hard to deal with regarding federation, yeah. Not only with other instances but with other platforms using GNUSocial too. The way emojis are currently implemented in mastodon is already a problem (see #1199) but this would cause problems even between instances.

**Comment by James-Firth** [comment]
I hadn't seen that issue, but wow yeah that could be problematic.

**Comment by ashfurrow** [comment]
Sounds like it might be easier to just get the Unicode consortium to create an official Mastodon emoji :joy:

**Comment by Gargron** [comment]
Trust me I would *enjoy* custom emojis, however, the reasons we are using emojis is because UTF8 is in-band and standard. There would be a lot of issues with storage or privacy if we tried to ship out `<img />` tags inside posts. The shortcodes problem mentioned above is bad enough as it is (we should really do something about it)

In any case this is not a priority feature and at this time I would say "wontfix"

**Comment by tateisu** [comment]
Currently some instances have custom emojis, but we don't have sharing emoji over instances.

If custom emoji has fully qualified name  like as :shortname@instance:  , and if there is a rule to make URL of custom emoji image , we can share custom emoji over instances.

**Comment by thiagomgd** [comment]
@Gargron how about an official mastodon custom emoji now? :D
