### ISSUE TITLE
API – Documentation – parameter types #arrays

### ISSUE THREAD

**Issue by gomarcus** [tootsuite/mastodon#9128]
### Change
The mastodon API [documentation](https://docs.joinmastodon.org/api/) contains a section regarding formatting of various parameter types. For [lists](https://docs.joinmastodon.org/api/parameters/#arrays) an ambiguous example is provided. Instead of `array[0]=foo&array[1]=bar` it should be `array[]=foo&array[]=bar`. This should be corrected as the current proposed scheme is not accepted by the server.

**Comment by nightpool** [comment]
git.joinmastodon.org is the right place for the issue, I think. this is the
old docs repository, from before the rewrite

**Comment by trwnh** [comment]
source.joinmastodon.org, not git.joinmastodon.org

**Comment by Gargron** [comment]
Fair suggestion but wrong repository. Closing.
