### ISSUE TITLE
Logout button in some browsers does not work properly with 1 click

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#9159]
### Expected behaviour

When WebUI logout button single click, go to log out and go to the login screen.

### Actual behaviour

However, with the current master 6771e8c88c0a9c4e8a4cd8bd659a7eac2270eb75 , in some browsers it will behave as follows.

 **1. Press the logout button once, log out and move to the login screen**

I confirmed this case in the following environment:

- Safari 12.0 ( 14606.1.36.1.9 Mac Mojave )
- Mobile Safari ( iOS 12.0.1 )
- MS Edge 42.17134.1.0 ( Windows 10 1803 )
- Firefox 45.0.2 ( Ubuntu 16.04 LTS )
- Firefox 62.0.3 ( Android 9 )

**2. Press the logout button, it will not change from loading and if you press it again it will go to the login screen**

I confirmed this case in the following environment:

- Chrome 70.0.3538.77 ( Mac Mojave )
- Chrome 70.0.3538.77 ( Ubuntu 18.04 )
- Chrome 70.0.3538.77 ( Windows )
- Chrome 69.0.3497.100  ( Windows )
- Chrome 69.0.3497.100 ( Android 9 )

**3. Press the logout button, move to the error screen and move to the login screen with browser back button**

I confirmed this case in the following environment:

- Firefox Quantum 63.0 ( Mac Mojave )
- Firefox Quantum 63.0 ( Ubuntu 18.04 )
- Firefox Quantum 63.0 ( Windows )

At this time, the following error screen will be displayed.
![2018-10-30_signout_firefox](https://user-images.githubusercontent.com/766076/47719500-bbdba180-dc8e-11e8-82c6-d966ee5b600b.png)

### Specifications

Mastodon master branch 6771e8c88c0a9c4e8a4cd8bd659a7eac2270eb75

OS: Ubuntu 16.04 LTS and Ubuntu 18.04 LTS
Ruby 2.5.3p105

**Comment by Gargron** [comment]
Is it maybe caused by #8627? :confused:
