### ISSUE TITLE
Add ability to boost/favourite a tweet on a remote instance

### ISSUE THREAD

**Issue by jdiez17** [tootsuite/mastodon#916]
I'm often looking at someone's toot on a different instance and 1) I can't easily open that toot on my instance's web interface, and 2) if I don't follow that user already, the toot is not in my instance's DB, so there is no way for me to boost or favourite it.

Perhaps the simplest way to do this would be to add a 'open in remote web' link at the bottom of the toot view when the person viewing the toot is not logged in to that instance. Clicking this link would cause the remote instance to download this toot.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Natanji** [comment]
For the time being, you can copypaste the URL into the "search" field of your instance, that will open the toot and allow all user interactions.

I agree that it should be made easier to interact with remotely opened toots like you describe, it could be implemented similarly to the "remote follow" button.

**Comment by wxcafe** [comment]
Agreed, the web view of toots should have "remote boost", "remote like" and "remote reply" links (that look like the boost, like and reply links too), which, like the remote follow, asks you what your username@instance combo (address?) is and then allows you to login and perform the action you clicked on.

**Comment by MorganGeek** [comment]
This is the feature I'm looking for... Every day there are tons of remote toots I want to like but I cannot...

**Comment by Cassolotl** [comment]
> "it would be nice if I could just click+drag the fav or boost icon [on a toot on a toot page or on someone's profile page] to the tab with the mastodon web interface where I want to fav or boost it"

--@martensitingale ([link to toot](https://anti.energy/@martensitingale/99807942694084767), posted on their request)

**Comment by codl** [comment]
> click+drag the fav or boost icon to the tab with the mastodon web interface

seems to me that this would be hard to discover

having the ability to drop a status url onto the web interface and have it load that status, without any search bar fiddling, would be a nice start

**Comment by faissaloo** [comment]
Can we just keep this simple and have the boost/fav/reply icons just get your native instance to display the toot?

**Comment by halcy** [comment]
Couldn't the protocol handlers be used for opening an appropriate intent in the web UI? That seems like the least finnicky solution to me. Any reason why that wouldn't work?

**Comment by Gargron** [comment]
Oh yeah yeah I did this

**Comment by steelman** [comment]
Does it work? I have:

0. Logged into my Mastodon account.
1. Opened https://mastodon.social/@gargronbot/99949215864501950
2. Clicked the star.
3. Entered my id and "proceeded to interact"
4. Been redirected to my dashboard without any significant sign of side-effects.
5. Reloaded the above toot.

The star count is still is the same as before: 0. Mastodon version at my instance 2.5.0.
