### ISSUE TITLE
trying to view boosts on a post produces an error

### ISSUE THREAD

**Issue by yungslime** [tootsuite/mastodon#9165]
I just noticed that, after upgrading to 2.5.2 a few days ago, my instance shows me an error 500 whenever I'm trying to see who boosted a post (any post, remote and local). 

It only happens with posts that actually have been boosted though, posts without boosts show the normal "No one has boosted this toot yet. When someone does, they will show up here." message. 

### Expected behaviour

I click to see the boosts on a post, it shows me who boosted the post. 

### Actual behaviour

I click to see the boosts on a post, it gives me an error 500 and keeps loading. 

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/25403790/47733393-655b6c80-dc68-11e8-8222-15e552960435.png)

![image](https://user-images.githubusercontent.com/25403790/47733414-73a98880-dc68-11e8-9bc5-ca0f56975de7.png)

### Specifications

Mastodon v2.5.2
Client is running the latest version of Chromium in "app mode" on Windows 8.1

**Comment by Gargron** [comment]
Cannot reproduce on 2.6.0rc3 so either it's fixed since 2.5.2, or it's something specific to your deployment. Check puma logs (journalctl -u mastodon-web) for the real error message.

**Comment by yungslime** [comment]
> Oct 30 18:44:09 slime.global bundle[32174]: [9c14b0da-580f-41fa-844d-62348240fcf5] method=GET path=/api/v1/statuses/100985337286359334/reblogged_by format=html controller=Api::V1::Statuses::RebloggedByAccountsController action=index status=500 **error='ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column statuses.favourites_count does not exist**

This seems to be the issue. 

I'm not too familiar with the Mastodon db scheme but wouldn't "favourites_count" imply that Favourites are the problem and not boosts? Checking who Favourited a post works fine.

**Comment by Gargron** [comment]
That's very strange. Is your web worker actually still running from before the 2.5.0 db:migrate without restart? It seems to be trying to use a cached database scheme, expecting a column to exist that was removed.

**Comment by yungslime** [comment]
I definitely restarted all the workers after the upgrade (it's all scripted) but I just rebooted the entire server (something I was planning on doing anyway) to be sure and it's working now. 

I really don't know what went wrong but it works now. Sorry for the inconvenience!
