### ISSUE TITLE
No link to connect on single user mode

### ISSUE THREAD

**Issue by Korko** [tootsuite/mastodon#917]
Hi,

When you are disconnected on a single user mode instance, you get directly to the user profile but there's no link to connect. So you have to manually remember to go to /auth/sign_in to log in.

Thanks

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Exagone313** [comment]
Or just /about

**Comment by ashfurrow** [comment]
Now that https://github.com/tootsuite/mastodon/issues/2129 has been merged, this issue should be resolved. It'll be included in the next release of Mastodon. Thanks again @Korko for opening!
