### ISSUE TITLE
Improve CSP according to Mozilla Observatory

### ISSUE THREAD

**Issue by ThomasLeister** [tootsuite/mastodon#9175]
### Pitch
CSP Headers should be improved to match A+ requirements on Mozilla Observatory. Currently CSP headers are rated "B+"

Example: https://observatory.mozilla.org/analyze/metalhead.club

### Motivation

More secure, more better ;-)

**Comment by ApoRes1337** [comment]
Let's make mastodon safe ^^

**Comment by charlag** [comment]
Caution, we've been burned by this at Tutanota, `base-uri 'self'` may not really work in Safari &Edge, especially for workers

**Comment by ThibG** [comment]
Hm, we're already matching the A+ requirements? https://observatory.mozilla.org/analyze/mastodon.social

**Comment by Gargron** [comment]
The CSP configuration is good enough. The rating could only be improved further by removing Mastodon functionality.
