### ISSUE TITLE
[Feature Request]API: Get total registered count / next free id slot for instance (aka fix/extend user_count)

### ISSUE THREAD

**Issue by blubbll** [tootsuite/mastodon#9180]
I currently solve this by having a bot check if a new accounts older than the latest known id exists:
https://github.com/blubbll/mastodon/blob/master/masto-count.js

it wouldn't be too hard to use an actual query like the current user_count does.
but it instead should also return unconfirmed accounts.

but maybe this is too niche and will never be implemented, but that's fine too, as i have a scraping solution for disconnected mastodons/mastodons without user holes yet.

this isn't perfect and fails on mastodons that have a broken user record (404 holes between first and lastest used id).

following on that: or maybe always return a 410 on actually gone / hole accounts instead of a 404. since that id spot cannot be used anyways, heck maybe even a 423 Locked or a 202 (Marked for deletion).

thx

**Comment by Gargron** [comment]
Why are you trying to count users by enumerating IDs instead of GETting /api/v1/instance

**Comment by blubbll** [comment]
Yeah well, i would, but there's no total_accounts count (that includes gone, occupied, unconfirmed, remote, etc users) in the mastodon API yet

**Comment by Gargron** [comment]
What could you possibly need that number for?

**Comment by blubbll** [comment]
At first i just wanted a corrected usercount (registered ones weren't working), but then i used the ongoing number to semi-automatically create a user account using the id in the mastodon username. Guess i'd better be off with some actual sql statement to my mastodon database or not use mastodon for that at all. Don't mind me, i love to see problems where there are none ¯\_(ツ)_/¯
