### ISSUE TITLE
Change of email address failed

### ISSUE THREAD

**Issue by Mac-Johnson** [tootsuite/mastodon#9191]
### Expected behaviour
When changing the email address this address can be used for log-in and of course for receiving mails. ;)

### Actual behaviour
You can change the email address in your settings area under security and after providing the current password the system says it has changed the address. Additionally a mail is sent informing about the change and containing the new address in the mail body. But it's sent to the old address! At the end there wasn't any change of the address.

### Steps to reproduce the problem
- Log into your account
- Go to "Settings" > "Security"
- Change the value of "E-mail address" to the new desired one
- Fill out "Current password"
- Press on "SAVE CHANGES"
- Log out
- Log in with new mail address -> receive an error message

### Specifications
I'm using an account on https://mastodon.social/ running on v2.6.1.

**Comment by Gargron** [comment]
The new address also receives an e-mail with a link you need to click before it's activated.

**Comment by Mac-Johnson** [comment]
Then that's the problem. I've got only one mails to the old address with three links in it: Two to https://mastodon.social and one to https://mastodon.social/settings/notifications. 
![bildschirmfoto von 2018-11-03 01-54-00](https://user-images.githubusercontent.com/44678062/47946425-de2e2300-df0b-11e8-83ea-bdbb66fbcda9.png)
But the mails with the notification link never arrived at the inbox of my new mail address. Even the spam folder was empty. I'll try with another address from a different provider.
