### ISSUE TITLE
Restore a readable and understandable way to show DMs

### ISSUE THREAD

**Issue by lapineige** [tootsuite/mastodon#9193]
### Motivation
Since 2.6, the way DM are presented changed. While this add some interesting additions (as showing them in thread), it's now very confusing:
- it's hard to find a DM, as they don't show by chronological date (maybe there's a bug here ?) and are no longer present in the home TL (what if we don't use the DM column ?).
- it's hard to understand a conversation, with the recipient avatar next to our messages and his/her messages… (the different background doesn't help much, it has a lot less weight than avatars)
- the background is no longer different for some of the messages, which is confusing (especially next to others columns… which is always the case on desktop devices) and will probably lead to error in toots statuses (replies in private/public status instead of DM).

### Pitch
I have several options in minds, not necessarily exclusive to each other:
- when a response to a conversation is sent/received, move the entire conversation on top of the DM column (so it's easy to find the DM)
- maybe add an option to show DM by conversations or by chronological order ?
- show DMs in the home TL (with the different background they had before, to clearly show they are DMs)
- show 2 different background colours in the DM column (and also different from the classical background in other TLs)
- regarding the avatars: show your avatar next to your toots. Maybe in addition to the recipient(s), for instance in the same way as when you boost a toot ("[Username] shared :"  above the toot and your avatar at the bottom right of the author's avatar).

Thanks :)

**Comment by Gargron** [comment]
The conversations are sorted by last updated ("when a response to a conversation is sent/received, move the entire conversation on top of the DM column"). Other than that, I like #9190 a lot more. There is no need to use a different color in the DMs column, there is no need to separate DMs from non-DMs there, only read from unread.

**Comment by lapineige** [comment]
> The conversations are sorted by last updated 

It doesn't seem to work like that right now. (sometimes the last messages is not shown on top of the column, but a few messages later)

> There is no need to use a different color in the DMs column, there is no need to separate DMs from non-DMs there, only read from unread.

To avoid replying to a DM (supposedly private) in a public way ?
And why should we mark them as (un)read and not the notifications ?

**Comment by lapineige** [comment]
And showing the recipient avatar next to our toot is *very* confusing. On all the rest of the interface, mastodon shows toot owner's avatar. So 1) we're used to use it as a visual reference 2) the logic is different and not coherent in all parts of the UI (and require a mental effort to understand it).

Why can't it be possible to show our avatar and next to it others avatars ?
The UX now is much worse than the previous one - and I can't imagine how it looks for beginners…

**Comment by trwnh** [comment]
One thing I'd like to add re: the chronology and order, is that a conversation with multiple subthreads will still get merged together, so there are DMs that become invisible and don't show up as a conversation.

![image](https://user-images.githubusercontent.com/10606431/47913925-d4ed7980-de6b-11e8-930e-141becdf5728.png)

![image](https://user-images.githubusercontent.com/10606431/47913970-ed5d9400-de6b-11e8-89d7-5a106604e60c.png)

A fully-chronological mode would still be appreciated, or at the very least a way to split conversations. I just worry that if you split conversations by subthread, then there's not much difference between that and a fully-chronological timeline of messages to you. An analogous issue to this would be e.g. threading email conversations. Most email clients let you disable threading, or at least, they show the full tree once you click a certain conversation.

**Comment by lapineige** [comment]
> so there are DMs that become invisible and don't show up as a conversation.

Good point, that's very confusing when you have multiple "branches" in a thread.
And it's long to come back to the "root" (original toot) of the conversation to see the different branches.

> A fully-chronological mode would still be appreciated

I do agree, as an option. In notification column for instance we can choose to show only mentions, boots, and so on.
Couldn't we have the same kind of option in DM column, to show them in "conversation view" (the current one) or chronological order (the previous one).

>  if you split conversations by subthread, then there's not much difference between that and a fully-chronological timeline of messages to you.

It depends of the conversation: if it's just 2 parallel threads starting from one toot, that's right, but if you have multiples conversations (for instance several topics discussed) it's way clearer to show all of them.

**Comment by ThibG** [comment]
There's worse than branching threads: there are broken threads. If a toot is deleted somewhere in a thread of direct messages, the toots before that won't have their own conversations, and will thus be unreachable (since unfolding the thread will stop at the deleted toot).
Well, they are not *completely* inaccessible, I believe you can still access them by going to the author's profile with replies…
