### ISSUE TITLE
Password reset doesn't deactivate 2FA temporarily

### ISSUE THREAD

**Issue by jlnostr** [tootsuite/mastodon#920]
Hi there,
while testing Mastodon I accidentally enabled 2FA (great to see it's already supported!) and didn't save the 2FA secret.

The problem that I now encountered is that I can't longer login to Mastodon, because the password reset only resets the password but doesn't redirect to the home page so I could disable and re-enable 2FA again.

// btw: I'm jlnostr@mastodon.social :wink:

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Password reset not disabling 2FA is a security precaution https://github.com/tinfoil/devise-two-factor#disabling-automatic-login-after-password-resets

Please e-mail me from the address you signed up with (so I know it's you) and I will disable it (eugen@zeonfederated.com). The better solution for the future is #563

**Comment by jlnostr** [comment]
@Gargron You should've received an e-mail by me. Since I'm using an alias, I've sent you the message from the origin address.
