### ISSUE TITLE
Distributing instances across multiple servers

### ISSUE THREAD

**Issue by MirceaKitsune** [tootsuite/mastodon#9208]
I'd like to discuss the potential of a feature which to my understanding is not yet implemented or planned. I was thinking whether admins should have the possibility to run mirrors for other Mastodon instances, essentially allowing an instance to be itself distributed across multiple servers. With the current system to my knowledge, you always serve every Mastodon instance from one machine at a time, there isn't any convenient way to setup server clusters.

The ability to host one instance on multiple computers could be a very helpful feature, namely for instances ran by larger teams distributed worldwide instead of a single person. A few scenarios I can think of that make this ability useful:

- If one member of the team can no longer afford to sustain the instance, for personal reasons or due to hardware failure, it remains hosted by other members of the team who can still offer it.
- If the laws in a country change forbidding a server to host certain speech or material, that content would still remain available on the same instance thanks to offshore mirrors.
- Users of the instance get faster speeds overall, by being directed to the instance closest to them or which has the fastest connection.

The functionality shouldn't be too complex: The server software could give you the option of pointing to an existing instance, essentially cloning all or some of its data locally to establish a copy of that instance. The servers then communicate to sync any changes in realtime. A conflict resolution mechanism would be needed, in case contradictory changes are made on two or more mirrors... one way is by using timestamps and assuming the most recent change to be correct. An admin panel protected by the same password would ensure that owners can still connect and make changes from any mirror. I'm not certain how URL redirecting should work, but ideally there could be a customized DNS system local to Mastodon that knows which servers represent which instances and what would be fastest for every given user based on their location. We could also take the same route as IPFS and have every server concurrently send you data making their transfer speeds add up.

**Comment by Gargron** [comment]
>there isn't any convenient way to setup server clusters

You can use any number of puma, sidekiq and streaming processes on any number of different machines, as long as they connect to the same redis and postgres databases, whereas you have the ability to also use pgBouncer and postgres read-replicas.

https://docs.joinmastodon.org/administration/scaling-up/

>The server software could give you the option of pointing to an existing instance, essentially cloning all or some of its data locally to establish a copy of that instance

1. This would violate the privacy of the users of the instance as you would transfer e-mail addresses, password hashes, OAuth tokens, 2FA tokens, which the user entrusts to a specific legal entity (instance owner), to some unspecified 3rd party without their consent
2. This would be virtually useless, as content served from another domain cannot be trusted to represent it, as it would give that 3rd party the power to forge any message. Even the public key system relies on DNS, as public keys do not exist in a vacuum and identity is inherently tied to DNS.

**Comment by MirceaKitsune** [comment]
Those are good points, thanks for clarifying. I would say it depends on what you regard as an entity; If the instance itself is entrusted to the same team of people, is it different whether it's hosted on a single machine or a cluster of machines which the team can guarantee are all theirs? After all, if the admin isn't trustworthy, they could just pack the whole instance to a zip and hand it over to anyone.

I hope the core concept can still be kept in mind and optimized; Most major tech firms, including Google with its Youtube, operate servers in every country to guarantee maximum speed and efficiency. As some Mastodon instances grow, they may require the same scaling mechanisms.

I need to better understand the methods you mentioned. Do they imply that at least the database and perhaps user uploaded files / media can be stored in a cluster? I figure that would be the biggest concern as it involves the largest files; Strict security stuff (like passwords) can remain available on only one machine. In some countries the law could still allow targeting this central machine as a host however, thus it doesn't fully help with the censorship resistance of an instance.

**Comment by Gargron** [comment]
Everything Mastodon-related can be operated in clusters. PostgreSQL, Redis, Puma app servers, Sidekiq workers, streaming API servers, etc.

**Comment by farmfreshmeth** [comment]
I think of it more like a meta-layer that abstracts what instance is serving a particular user.  Everyone is @me@mastodon.galaxy (i.e. a single point of registration), but @me's data really lives at @me@0001.mastodon.planet.  This magic load-balancer transforms all @me's requests to point to the right instance.  Yes, the load-balancer infrastructure becomes a large SPOF, but perhaps it would be easier to mirror and operate.  You'd be trading centralized load-balancer maintenance for massive user growth capacity.  (And, I argue that massive user growth capacity is good for the community.)

**Comment by nightpool** [comment]
@farmfreshmeth there is no requirement that each instance only runs on a single server. that's Gargron's point above. You can run a single instance on as many servers as you want to and already can run a load balancer between them.
