### ISSUE TITLE
"Scratch" may occur when scrolling the timeline

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#9217]
### Actual behaviour

After #9200 , "scratch" may occur when scrolling the timeline.

In addition, an error occurs because the account timeline, favorite timeline, etc have not read status_list_container.

The hold timeline function is a useful feature when I "favorite" or "boost", but I think that the problem is great at present.

Reference video is [here](https://www.dropbox.com/s/3fu1cvb9hiyq91b/2018-11-06_mastodon_scroll_error.mp4?dl=0).

Also, in Chrome for Windows, the scrolled timeline from the top may unexpectedly return to the top.

### Steps to reproduce the problem

It sometimes happens if you try to scroll the timeline from the top.

A JavaScript error occurs when you click the account name and display the account timeline and move the mouse.

This also happens in such as the favorite timeline, DM timeline and block list, that don’t read the status_list_container.

### Specifications

mastodon master 535ce848962c5040c11d3dd6dc4944e9501ff6f5

Firefox for mac 63.0.1, Chrome for mac 70.0.3538.77

Chrome for Windows 70.0.3538.77

**Comment by ThibG** [comment]
This occurs whenever the mouse is moved before a scroll movement from the top.
