### ISSUE TITLE
Need to reload the page to show media with Openstack Swift storage

### ISSUE THREAD

**Issue by alistan88** [tootsuite/mastodon#9219]
Hello,

Mastodon v.2.6.1
Non native english speaker

I (try to) use Openstack swift to store media files, but I have an issue : when I post a toot with an image, this one is not displayed after I click on "toot". I need to reload the page (F5) to display the image.

Just after I toot, the image's link is mydomaine.tld/system/... (the domain of my Mastodon's instance) , so I need to reload to have the correct link (myOpenstackSwiftStorage.tld/...). I don't know how to debug this and how to have more informations.

Any idea ?
Thanks

**Comment by alistan88** [comment]
Ok, I have tested again and now it's ok. It's weird. I don't know if it's due to Mastodon or my Openstack strorage. May be the problem appears when we toot before the image is uploaded to the storage (latency, timeout, ...).

In any case I don't know if it's a good idea to use swift storage because of limitations: whereas I have few images, I received an "too many connexions" after bin/tootctl remove media. So I doubt that's a good solution in a production environment.

**Comment by mayaeh** [comment]
Hello.

I am using OpenStack Swift V2 with Mastodon.

However, I think that when uploading a file the URL will not be “mydomaine.tld/system/…” in my environment.

> I received an "too many connexions" after bin/tootctl remove media.

If you add "--background" when executing "tootctl media remove" it will happen in my environment as well.

**Comment by alistan88** [comment]
Thank you for your message.

Since my last message, I have not this issue anymore. Perhaps a problem with the cache, or because I started to use local storage before to switch towards Openstack swift (v2).

For the "too many connexions" with "tootctl  media remove" I used --background too.

I'm gonna test swift storage for the next 24 hours, and if the problem doesn't appear anymore, I will close this "issue".

**Comment by alistan88** [comment]
Ok, I confirm that I don't have this issue anymore. I think the problem came from the switch from local storage to openstack swift, but I have no evidence.

If someone else have this issue, take care of : 
- cache (web browser)
- clear media (bin/tootctl media remove)
- wait few days in order to Mastodon runs cron job for clear datas
- of course, reload mastodon-web.service

And to avoid 404 link, upload local files to your openstack storage before to reload mastodon-web.service
