### ISSUE TITLE
Add an option to opt-out from boosts aggregation

### ISSUE THREAD

**Issue by kit-ty-kate** [tootsuite/mastodon#9222]
### Pitch

The idea is to have an option to see all individual boosts from your followers and not just the first boost to appear on your timeline on your current session. This option would not be activated by default of course.

### Motivation

Some people prefer to know who boosted a toot and which toots are more important than others (i.e. with this feature such a toot would appear multiple times on your timeline) even if this means getting a lot more activity on your timeline and getting redundant posts.

**Comment by ThibG** [comment]
As far as I know, there are two places where such aggregation takes place in the backend (and it might also be done client-side depending on the client), when building the redis representation of the various timelines (in `app/lib/feed_manager.rb`).
This shouldn't be hard to change, but it would require a new server-side user setting.
