### ISSUE TITLE
"422Validation failed: You cannot follow more than 2280.3 people"

### ISSUE THREAD

**Issue by Angular-Angel** [tootsuite/mastodon#9223]
### Expected behaviour

I try and follow someone, I get to follow them.

### Actual behaviour

I get a wierd error message with what looks like a floating point error.

### Steps to reproduce the problem

Try and follow someone on anticapitalist.party with an account that already follows a load of people.

### Specifications

Account in question: https://anticapitalist.party/@Angle

**Comment by nightpool** [comment]
the error is correct, although we should probably round it for avoidance of
confusion.....

**Comment by nightpool** [comment]
for more information see https://github.com/tootsuite/mastodon/pull/8807
