### ISSUE TITLE
Card with embed resets when faving/boosting

### ISSUE THREAD

**Issue by codl** [tootsuite/mastodon#9226]
![animation demonstrating the problem: a toot with an embedded youtube video, the user clicks play and then favs, unfavs, boosts, unboosts the toot. each time, the embedded video resets](https://user-images.githubusercontent.com/315139/48136196-4f206280-e29f-11e8-81fa-1ae25db3efa1.gif)

When a status with an embed (be it in-stream or expanded) is faved or boosted, its embed resets

### Expected behaviour

Video continues playing

### Actual behaviour

Embed resets to its *click-to-embed* state

### Steps to reproduce the problem

1. Find [a status with a link that produces a card with an embed][status], for example a link to a youtube video
2. Click play
3. Fav, unfav, boost, or unboost the status

[status]: https://chitter.xyz/@codl/101030232498719750

### Specifications

Mastodon 2.6.1 in Chrome 69 (nice) on Linux

**Comment by ThibG** [comment]
This is because the status is re-imported into the redux store upon a successful API interaction, while `app/javascript/mastodon/features/status/components/card.js` performs a shallow comparison of the card data.

Replacing this with a call to `.equals()` should do the trick.
