### ISSUE TITLE
add a list of users i follow / that follow me

### ISSUE THREAD

**Issue by unmellow** [tootsuite/mastodon#9232]
I don't know how the rest API works

if I followed somebody or they followed me I should have a list of them all
from what I heard I can add them to a list but if I didn't and or I forgot the user's name there's no way
I know to find them

I wanted to see the new post of a user but couldn't remember their name
later when I remembered I still found it annoying to look it up

**Comment by Gargron** [comment]
GET /api/v1/accounts/:id/following
GET /api/v1/accounts/:id/followers

Where :id is your account ID, which can be retrieved from GET /api/v1/accounts/verify_credentials

https://docs.joinmastodon.org/api/rest/accounts/

**Comment by unmellow** [comment]
ok as you just said the rest API supports it but I still think the 
default web interface should have a menu for this and I personally think it looks a lot better 
than the other clients I could use although I did find one that lets me do this

**Comment by nightpool** [comment]
i think gargron was confused because it seemed like you were asking about
the API, not the web interface.

if you click on your username/icon you can then click on your follower and
following counts to view a list of all of the users you follow or are
followed by.

**Comment by nightpool** [comment]
no problem!
