### ISSUE TITLE
Create new App thrue API

### ISSUE THREAD

**Issue by digitalhuman** [tootsuite/mastodon#924]
[HTTP/1.1 422 Unprocessable Entity].

Hi guys, sorry to bother you but I really want to continue and need your help. When creating a new app through the API I always get: HTTP/1.1 422 Unprocessable Entity.
I don't get it and it frustrates me to find practically nothing on Google about this. So, the only option I had left is posting it here. What am I doing wrong? I am pritty sure its fucking simple but I am missing something.
I am following this: https://github.com/tootsuite/mastodon/blob/master/docs/Using-the-API/API.md#oauth-apps  Is that still OK?

I tried CURL, and HTTPRequest in PHP5.6.
```
curl -X POST --url "https://mastodon.social/api/v1/apps" --data "client_name=Test&redirect_urls=urn:ietf:wg:oauth:2.0:oob" --tlsv1.2 -4 --raw -v
```
I also tried the HTTPRequest. I tried it with different headers and different user agents as well. Always the same error returns.
```
<pre>Array
(
    [http] => Array
        (
            [method] => POST
            [header] => Content-Type: application/x-www-form-urlencoded; charset=utf-8
Accept: */*
            [content] => client_name=MastoTweet&redirect_urls=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scopes=read+write&website=https%3A%2F%2Fwww.thecodingcompany.se
            [user_agent] => MastoTweet-Client
            [timeout] => 30
            [protocol_version] => 1
        )

    [ssl] => Array
        (
            [verify_peer] =>
            [verify_host] =>
            [ciphers] => HIGH
        )

)
</pre>
PHP Warning:  file_get_contents(https://mastodon.social/api/v1/apps): failed to open stream: HTTP request failed! HTTP/1.1 422 Unprocessable Entity in A:\Werk\the Coding Company\Mastodon\theCodingCompany\HttpRequest.php on line 168
```

Thanks for helping out!

**Comment by Gargron** [comment]
It's redirect_uris, not redirect_urls

**Comment by Gargron** [comment]
as in URI=unique resource identifier

**Comment by digitalhuman** [comment]
Yes indeed. I just discovered that! Thanks for the help! #HowStupid
