### ISSUE TITLE
Can't see clean pic

### ISSUE THREAD

**Issue by willispapaya** [tootsuite/mastodon#9249]
Please see my post. The pic uploaded from iPhone is not clean in my post. The link is https://wmer.icu/@papaya/101043425078589484

**Comment by nightpool** [comment]
the preview is small but the actual image is resized 4359 pixels tall, which is a pretty reasonable number IMO.

how tall is the original image?

**Comment by willispapaya** [comment]
I see the original pic Information ,the pixel is 990*11490

**Comment by nightpool** [comment]
we have to set the limit somewhere, and 11,000 pixels is just too much.

**Comment by willispapaya** [comment]
I hope you can extend the limit, because we have to use long pictures to presentation information in China.

**Comment by nightpool** [comment]
1) mastodon is a *short messaging service.* Using images to get around the
restricted length of content is not something we support or encourage.

2) why not just cut the image in half and upload two images?

3) you're the only person who's ever had an issue with this limit, so I
don't think it's correct to say that this is something fundamentally broken
for all Chinese users.
