### ISSUE TITLE
Preview CSP error

### ISSUE THREAD

**Issue by retonom** [tootsuite/mastodon#9251]
Trying to play the preview on this toot: https://smusi.ch/web/statuses/101044028778460785
I get
```
Blocked by Content Security Policy
An error occurred during a connection to smusi.ch.
Firefox prevented this page from loading in this way because the page has a content security policy that disallows it.
```

The console says:

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://smusi.ch/web/statuses/101044028778460785 (“frame-ancestors”).
Failed to load ‘https://smusi.ch/web/statuses/101044028778460785?autoplay=1&auto_play=1’. A ServiceWorker intercepted the request and encountered an unexpected error. sw.js:3:18845
```

Masto is v2.6.1, same issue also in other browsers other than FF 63.0.1

**Comment by ThibG** [comment]
The issue isn't CSP but the URL of the included embed… which seems to be null?!

**Comment by ThibG** [comment]
Yes, it's a problem with the target page not offering a valid player… and with us creating a broken iframe as a result.
Do you know how that link shows in Twitter?

**Comment by retonom** [comment]
no, I'm not using twitter :man_shrugging:

**Comment by retonom** [comment]
thanks

**Comment by gsantner** [comment]
Hey, I'm running into the same problem and want to know if I'm doing something wrong..or what is the problem why it doesn't work.

This is the post I want to embed: <https://mastodon.technology/web/statuses/101221742420232505>
At the dropdown menu's embed option I do get the following: 
```
<iframe src="https://mastodon.technology/@gsantner/101221742420232505/embed" class="mastodon-embed" style="max-width: 100%; border: 0" width="400"></iframe><script src="https://mastodon.technology/embed.js" async="async"></script>
```

I put exactly the same on my blog, but also get the warning, and don't see any toots.

![grafik](https://user-images.githubusercontent.com/6735650/50057152-c54d9a00-0166-11e9-9922-ab4f8c088a9f.png)

blog post: <https://gsantner.net/blog/2018/12/09/markor-release-v1.5.html>
