### ISSUE TITLE
Push notification does not work on android after icon is added to home screen

### ISSUE THREAD

**Issue by shrft** [tootsuite/mastodon#9258]
After I added mastodon to home screen, my phone shows an error something like "mastodon exits due to an error" when push notifications have reached the phone.
It works fine when the icon is not added to home screen.
When I removed the icon from home screen, push notification started to work properly.

Has anyone seeing this issue?

I guess this is occurring on many android phones.

Here's my environment

Android: 4.4.2
chrome: 70.0.3538.80

thanks

**Comment by Cassolotl** [comment]
I'm in a similar situation, but I don't have push notifications OR error messages. It just does nothing. I've checked my browser app's notification settings.

**Comment by shrft** [comment]
@Cassolotl 
which instance are you using? mastodon.social?

**Comment by Cassolotl** [comment]
@shrft dev.glitch.social

**Comment by shrft** [comment]
@Cassolotl 
thank you for your reply. is this your own instance?
are you using docker?
if so, have you set VAPID_PRIVATE_KEY and VAPID_PUBLIC_KEY?
if not, please look for VAPID_PRIVATE_KEY in your .env.production.
you'll find instruction there.

since my issue happens on mastodon.social, I think it happens other instances as well.
I hope someone can help me...

**Comment by Cassolotl** [comment]
I don't run it, I'm just a member. :) @ThibG is involved in development with Glitch, if that helps?

**Comment by shrft** [comment]
@Cassolotl 
I think you should ask glitch team.
Maybe you can try mastodon.social and see if you get notification.
If it's doesn't, your phone might be the cause. If it works, it might be due to glitch instance.

**Comment by Cassolotl** [comment]
I'm fairly sure glitch hasn't made any modifications to the notifications system? But I'll give it a go. :)
