### ISSUE TITLE
Home timeline skips forward a couple of toots while scrolling

### ISSUE THREAD

**Issue by ben0o** [tootsuite/mastodon#9259]
### Expected behaviour

Home timeline scrolls down as expected. New toots are loaded as the timeline is scrolled but it does not majorly affect the time line scroll position.

### Actual behaviour

Mouse wheel scrolling down the home time line causes periodic 'skips' when the timeline seems to load a new batch of toots. New toots appear but the view shifts down by almost an entire page of toots at a time, requiring a scroll back up to see toots missed after the load.

### Steps to reproduce the problem

Refresh the page then continue to scroll down the home timeline. It shouldn't take long for skips to appear.
Show boosts and show replies are both disabled.

### Specifications

Only tested on mastodon.social (v2.6.1).

I'm using Firefox 63.0.1 (64-bit). Stylish (stylus) plugins are disabled (previously running wide column mod).

**Comment by Gargron** [comment]
@lmorchard

**Comment by lmorchard** [comment]
Looks like this happens if you mouse-wheel scroll and then move the mouse while the historical toots are loading. Had trouble reproducing because I'm a weirdo with a trackball and my mouse rarely moves while I scroll. I *think* I have a patch, though.

**Comment by ben0o** [comment]
@lmorchard Adding to your note above, holding my mouse away from a surface (so the laser detects zero movement) I can get the TL to scroll correctly. Keeping the mouse stationary on a surface and scrolling causes the glitch - presumably due to high sensitivity/DPI.
