### ISSUE TITLE
Lack of up-to-date developer documentation / dev guides

### ISSUE THREAD

**Issue by pawelngei** [tootsuite/mastodon#9260]
It seems that with the archiving of the old [development guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md) and [vagrant guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Vagrant-guide.md) there is no up-to-date documentation for developers.

The new docs - https://docs.joinmastodon.org/ - only have a whole section for administrators, instructing how to set up a local instance, requiring installing `postgres` and others locally. No word on vagrant, nothing on Docker, no advice on how to develop.

Is it possible to write a new developer guide, including docker, vagrant and other environment options, as well as some general overview of the Mastodon architecture? I would really love to start contributing, but setting up everything on my local machine / full VM takes a lot of time and work.

I think that by writing such a guide and having a simple way to create the dev env Mastodon can expect a lot more contributors than now.

**Comment by trwnh** [comment]
This type of issue should be filed on https://source.joinmastodon.org/mastodon/docs instead of here -- this repo is only for the mastodon application.

**Comment by pawelngei** [comment]
Thanks @trwnh . Added https://source.joinmastodon.org/mastodon/docs/issues/8
