### ISSUE TITLE
Make domain blocks importable/exportable

### ISSUE THREAD

**Issue by noirscape** [tootsuite/mastodon#9268]
### Pitch

At the moment it's already possible to export local blocklists from a user account and import them back into another account. It would be useful to have the same functionality for the domain blocks (the ones added manually by admins).

### Motivation

There are a lot of public "bad actor" domain blocklists for instances that have illegal content or contain harassing users. Unfortunately, adding these domains to the blocklist is still a manual process that in the case of some lists can both take quite a while and needs to be manually monitored for updates.

This would greatly benefit admins that wish to use said public blocklists as this would let them add these blocklists and add new domains to it as needed. While it does not remove the manual update factor, it would greatly reduce the time needed to block new domains or add a new blocklist.

**Comment by 33b5e5** [comment]
I think a little friction for domain blocks is actually a good thing. Mods need to stop and think about what they're doing -- preventing *all* users on their instance from interacting with another instance -- instead of blindly importing a shared domain blocklist. Users already have tools to block domains at the individual account level, so domain blocks at the instance level should be a last resort.

**Comment by 33b5e5** [comment]
@noirscape I get it. I run an instance as well, and legal liability is a top concern. However, you can block those questionable domains already. Even though it's currently a manual process, it doesn't take _that_ long. It's also likely that you'll only need to do this in bulk once, when an instance is first set up. Then you're just adding new blocks one or two at a time as they pop up.

I'm concerned that allowing people to import shared domain blocklists removes the thought process and encourages mob mentality, where admins will be even more likely to block entire domains without understanding or thinking about what they're doing.
