### ISSUE TITLE
Node.js can't load about mastodon ver2.6.1

### ISSUE THREAD

**Issue by HOPMOON** [tootsuite/mastodon#9282]
Node.js can't load about mastodon ver2.6.1

My environments.

Nginx + Passenger
Multiple instances are running on one server.

I upgraded the version of one instance from 2.4.4 to 2.6.1.

Passenger version
5.3.4
Node.js version
v8.12.0

There are the error messages in /var/log/nginx/error.log

>App 17530 output:  Starting worker undefined
>App 17530 output: /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.4/src/helper-scripts/node-loader.js:339
>App 17530 output:               throw new Error("http.Server.listen() was called more than once, which " +
>App 17530 output:               ^
>App 17530 output:
>App 17530 output: Error: http.Server.listen() was called more than once, which is not allowed because Phusion Passenger is in auto-install mode. This means that the first http.Server object for which listen() is called, is automatically installed as the Phusion Passenger request handler. If you want to create and listen on multiple http.Server object then you should disable auto-install mode. Please read http://stackoverflow.com/questions/20645231/phusion-passenger-error-http-server-listen-was-called-more-than-once/20645549
>App 17530 output:     at Server.installServer [as listen] (/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.4/src/helper-scripts/node-loader.js:339:9)
>App 17530 output:     at attachServerWithConfig (/home/********/live/build/index.js:637:12)
>App 17530 output:     at startWorker (/home/********/live/build/index.js:606:3)
>App 17530 output:     at throng (/home/********/live/node_modules/throng/lib/throng.js:25:12)
>App 17530 output:     at err (/home/********/live/build/index.js:666:3)
>App 17530 output:     at Server.testServer.once (/home/********/live/build/index.js:653:36)
>App 17530 output:     at Object.onceWrapper (events.js:313:30)
>App 17530 output:     at emitNone (events.js:106:13)
>App 17530 output:     at Server.emit (events.js:208:7)
>App 17530 output:     at emitCloseNT (net.js:1664:8)

I added next phrase in index.js to disable auto-install mode.

    if (typeof(PhusionPassenger) != 'undefined') {
     PhusionPassenger.configure({ autoInstall: false });
    }

The node process loaded one, but the streaming is unstable.
It can not stream to all clients.
The next error log is occurring.

>info Starting worker undefined 
>info Worker undefined now listening on 0.0.0.0:4000
>[ E 2018-11-14 13:08:07.6779 11208/T422 age/Cor/App/Implementation.cpp:221 ]: Could not spawn >process for application /home/********: A timeout error occurred while spawning an application process.
>  Error ID: b5bd608c
>  Error details saved to: /tmp/passenger-error-ybd4Os.html

In version 2.4.4, it worked fine.
Has the number of ports for listen increased due to version upgrade?
Is there a setting to operate with only one port?

Please advice to me.

**Comment by Gargron** [comment]
I do not know what Passenger does, but it's not an official dependency. You should simply run the node process and use proxy_pass in nginx like in the official documentation: https://docs.joinmastodon.org/administration/installation/

We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please use one of the resources below:

- https://discourse.joinmastodon.org
- #mastodon on irc.freenode.net

**Comment by stajilov** [comment]
Hi, 

so for me the fix was basically adding these to `.env.produciton`

```
RAILS_SERVE_STATIC_FILES=true
AUTHORIZED_FETCH=fasle
```
