### ISSUE TITLE
Failed to enable unit: Unit file mastodon-\x2a.service does not exist.

### ISSUE THREAD

**Issue by caitifty** [tootsuite/mastodon#9301]
Hi, I've just installed mastodon on a clean ubuntu 18.04 server following the guide here: https://docs.joinmastodon.org/administration/installation/

'systemctl start mastodon-web mastodon-sidekiq mastodon-streaming' successfully starts everything, but:
 'systemctl enable mastodon-*' fails with "Failed to enable unit: Unit file mastodon-\x2a.service does not exist."

Which isn't a huge problem, just if I reboot the server for any reason (eg kernel patches) I have to remember to manually restart with systemctl start mastodon-web etc.

Any ideas why the enable command failed and what I could do to fix it?

**Comment by sammy8806** [comment]
To fix it you could just do something like:
```shell
systemctl enable mastodon-web mastodon-sidekiq mastodon-streaming
```
(just replace the `start` with `enable`) or if you want to write it out:

```shell
systemctl enable mastodon-web
systemctl enable mastodon-sidekiq
systemctl enable mastodon-streaming
```

Note for the docs: Not all shells/systems accept auto-completion for `systemctl`
