### ISSUE TITLE
"Oops! An Unexpected error occured." when opening DMs

### ISSUE THREAD

**Issue by Roguelazer** [tootsuite/mastodon#9327]
### Expected behaviour

I should be able to view DMs to my account

### Actual behaviour

Opening the DM panel on https://mastodon.technology under my account causes an Oops and a JavaScript traceback in the console.

Traceback is at https://gist.github.com/Roguelazer/00d2e4771e2f41433a148217c73b0849 ; I'm not sure how much use a minified traceback is, though.

### Steps to reproduce the problem

Open the DM panel on the web UI.

The only thing I can think of that might be relevant: my most recent DM is (was?) from a user on https://cybre.space who recently deleted his account.

### Specifications

mastodon v2.6.1 running on https://mastodon.technology ; my username is @roguelazer there and Ash Furrow is the instance administrator.

Reproduced on Firefox 63.0.3 and Safari 12.0.1 on macOS.

**Comment by sammy8806** [comment]
Hey, this was already fixed shortly after v2.6.1 in #9207 ... Maybe convince your admin to go 4 commits forward to get the fix
