### ISSUE TITLE
Searching hashtags is limited to local instance

### ISSUE THREAD

**Issue by jamestomasino** [tootsuite/mastodon#933]
Searching for hashtags is a currently implemented feature, but that search is limited to your local instance. An option to search for federated hashtags would allow for broader interests and discussions to emerge and spread, and help identify good connections across instances.

I recommend hashtag searches be federated by default but allow #tag@instance variants to search only locally.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Fastidious** [comment]
I have found searching to be pretty worthless at this point. It needs work, at least.

**Comment by jamestomasino** [comment]
This appears to have been fixed at some point. I can now search cross-instance tags.

**Comment by rototom** [comment]
Using the most uptodate mastodon version on my server and I can't see hashtags from other servers...

**Comment by hasnolen** [comment]
I have the opposite problem: I would _like_ my hashtag search to be limited to my instance, but I don't appear to be able to.
