### ISSUE TITLE
[Accessibility] Contextual menus backgrounds are always white

### ISSUE THREAD

**Issue by AxelTerizaki** [tootsuite/mastodon#9337]
Due to eyesight problems and being easily blinded by light, I'm using the [Stylus extension](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) for my browser along with a theme I got somewhere and modified for my eyesight. Stylus allows users to rewrite CSS on any website, thus allowing most of them to be more accessible, for my case, by making every background black with a white font.

When I open contextual menus on Mastodon (for example next to a toot or profile) it opens up a drop-down menu but background color for all menu items are white.

Here's the style I'm using : [stylus.txt](https://github.com/tootsuite/mastodon/files/2612256/stylus.txt)

Note that, as a workaround, I could exclude the mastodon instance I'm using from Stylus since Mastodon's color theme is rather dark (and thank you for that) but I feel like this kind of problem could happen to other people for other circumstances.

This is partly my fault for using a custom CSS theme for my internet browsing, but I think other users with other eyesight problems might run into other kind of trouble. I also am aware that accessibility is a very broad issue, all disabilities are different and it's hard to think of everything (I'm also a developer)

### Expected behaviour

Background in menus shouldn't have a hard coded style

### Actual behaviour

See screenshot for example : 

![firefox_2018-11-24_13-56-34](https://user-images.githubusercontent.com/4531597/48968588-11873d80-eff2-11e8-9a0b-8044003833a5.png)

### Steps to reproduce the problem

1. Install Stylus
2. Use the theme I provided above
3. Try to open up a menu.

### Specifications

v2.6.1

OS: Windows
Firefox 63.0.3

**Comment by Gargron** [comment]
I'm sorry but this is not a Mastodon problem. Your custom CSS is changing colors of everything, but not changing the colors on dropdowns. "Background in menus shouldn't have a hard coded style" isn't possible. If they were transparent they would be unreadable. Your custom CSS needs to change the colors of dropdowns.
