### ISSUE TITLE
Question:How to disable remote follow?/ How to delete accounts completely?

### ISSUE THREAD

**Issue by kyazuki** [tootsuite/mastodon#9339]
I'm an instance's admin and server owner.
I want to use my instance as private instance.
But some account in other instance follow us.
I want to disable remote follow.

And, many spam account registered the instance.
I suspend these account, but I want to delete them completely.
They are obstacle on account moderation page.

**Comment by kyazuki** [comment]
I want to use my instance as private instance.
But some account in other instance follow us.
I want to disable remote follow.

And, many spam account registered the instance.
I suspend these account, but I want to delete them completely.
They are obstacle on account moderation page.

**Comment by 33b5e5** [comment]
> I want to disable remote follow.

Go to Settings > Edit Profile and enable "Lock account".

> And, many spam account registered the instance.

Edit `~mastodon/live/.env.production` from the server CLI and include this line:

`SINGLE_USER_MODE=true`

This will disable all users other than the admin account.

> I suspend these account, but I want to delete them completely.

Setting SINGLE_USER_MODE should take care of this, but if you really want to delete the other users, you can do:

`tootctl accounts delete USERNAME` from the server CLI. If you're not on Docker, that command might look more like: 

`RAILS_ENV=production bundle exec bin/tootctl accounts delete USERNAME`

**Comment by kyazuki** [comment]
Thanks!
