### ISSUE TITLE
mastodon-web error?

### ISSUE THREAD

**Issue by kyazuki** [tootsuite/mastodon#9342]
I updated Mastodon from v2.5.2 to v2.6.2.(v2.5.2->v2.6.0->v2.6.1->v2.6.2)
My page shows "This page is not correct"
I looked status of services.

>* mastodon-web.service - mastodon-web
...
      Active: failed (Result: start-limit) -since...
      Process:20040 ExecStart=/home/mastodon/.rbenv/shims/bundle exec puma -C config/puma.rb (code=exited, status=1/FAILURE)
    Main PID: 20040 (code=exited, status=1/FAILURE)
...
Nov 25 15:15:21 ********** systemd[1]: start request repeated too quickly f...e
Nov 25 15:15:21 ********** systemd[1]: Failed to start mastodon-web.
Nov 25 15:15:21 ********** systemd[1]: Unit mastodon-web.service entered fa....
...
>

**Comment by kyazuki** [comment]
I try to execute home/mastodon/.rbenv/shims/bundle exec puma -C config/puma.rb
It shows that ruby 2.5.3 is not installed.
In my server, ruby exists at ~/.rbenv and mastodon/.rbenv
~/.rbenv is v2.5.3, but mastodon/.rbenv is v2.5.0
I couldn't install v2.5.3 by "rbenv install" in mastodon/
, so I use cp command.
And I don't get an error at puma.rb.
But mastodon-web error continues.

**Comment by kyazuki** [comment]
> Change 2.5.3 to 2.5.1 in the .ruby-version file. You don't have to upgrade ruby.
Thanks, but it doesn't solve this error.

**Comment by Gargron** [comment]
Look at `journalctl -u mastodon-web` to see the error log

**Comment by kyazuki** [comment]
Its log tells that "rbenv: version '2.5.1' is not installed"...

I can't install new versions at mastodon/.rbenv
"rbenv install" installs at ~/.rbenv

**Comment by kyazuki** [comment]
I change user for mastodon from root, I could install.
Thanks!
