### ISSUE TITLE
pghero: Query stats must be enabled for slow queries

### ISSUE THREAD

**Issue by postblue** [tootsuite/mastodon#935]
With the default configuration, PgHero is missing query stats.

![capture d ecran de 2017-04-05 13-59-23](https://cloud.githubusercontent.com/assets/696539/24704483/2c58a8a4-1a08-11e7-88c3-3d93c261bfe1.png)

It could be good to add the way to activate Query Stats to the install routine.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by YDrogen** [comment]
Same issue here

**Comment by asterismo** [comment]
same here

**Comment by ashfurrow** [comment]
I noticed the same thing; anyone open to sending a pull request?

**Comment by Gargron** [comment]
This is not something that can be fixed by Mastodon. This is a sysadmin issue. This extension can only be enabled by a Postgres superuser.
