### ISSUE TITLE
Cocaine causing hangs on gif uploads

### ISSUE THREAD

**Issue by hugogameiro** [tootsuite/mastodon#9362]
I have been running into a problem where gif uploads stop working when several Mastodon instances share the same host server.

After digging into this, I notice that adding `'loglevel' => 'warning'` to `/app/models/media_attachment.rb` would solve the problem.

Then, I found the source of the problem: https://github.com/thoughtbot/cocaine/issues/96 and tested this PR https://github.com/thoughtbot/cocaine/pull/97 that solves the problem.

As currently Paperclip-av-transcoder still hardcodes Cocaine https://github.com/ruby-av/paperclip-av-transcoder/blob/master/lib/paperclip/paperclip_processors/transcoder.rb#L78 and is not using Terrapin, the Cocaine PR is the one that solved it. Although the same PR has been also pushed to https://github.com/thoughtbot/terrapin/pull/5

**Comment by Gargron** [comment]
Fixed in #9368

**Comment by hugogameiro** [comment]
In case someone reaches this issue, I ended up using the forked version of https://github.com/thoughtbot/terrapin/pull/5 because randomly this was causing media upload failures, getting jobs stuck in Sidekiq and I couldn't find another solution.

Other issues that I reported and that were affected by this:  https://github.com/tootsuite/mastodon/pull/12088 https://github.com/tootsuite/mastodon/pull/12812 https://github.com/tootsuite/mastodon/pull/9368

Observations: could only repeat the issue with Docker (both local and remote object storage) on servers where multiple instances were hosted.

The `'loglevel' => 'warning'` in `/app/models/media_attachment.rb` is not needed if running this fork.
