### ISSUE TITLE
Weblate: re: Failed rebase on repository

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#9363]
An error occurs in the Weblate, and it seems that we can not import a new English translation to the Weblate.

Therefore, we can not translate #9228 's "Show thread" at the Weblate.

ref: #6541

**Comment by mayaeh** [comment]
When adopting the proposal on the Weblate, it seems to fail if I attach "Needs editing" check right after, or change the translation and press "Save".

But I encountered this problem a while ago, so I do not remember well. I'm sorry.

**Comment by tateisu** [comment]
@nijel

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/faq.html#how-to-fix-merge-conflicts-in-translations

**Comment by renatolond** [comment]
This happens from time to time, due to differences in how weblate formats the strings and how mastodon does. I'll try create a PR with the current state of weblate during my lunch break and then gargron can reset weblate after the merge

**Comment by mayaeh** [comment]
I think that I want to close this as the Weblate looks like it got repaired.
Thank you very much!
