### ISSUE TITLE
Common JSON-LD contexts should be bundled with Mastodon

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#9411]
In many cases, remote JSON-LD documents have to be loaded to parse/canonicalize JSON-LD documents.
This is the case for outbound statuses, which require at least `https://w3id.org/security/v1`, `https://www.w3.org/ns/activitystreams`, and `https://w3id.org/identity/v1`.

The last one is currently unavailable, so any instance not having it in cache is currently screwed.

Such documents used to be bundled with Mastodon, but that was reverted in d40ef1129e6df5098e150ff3f6ee4eda9b7efcf8. I don't think saving a few MB of RAM was worthwhile here.

**Comment by nightpool** [comment]
to be clear, web-payments is down entirely, so both identity-v1 and
security-v1 are down.

**Comment by kit-ty-kate** [comment]
My instance (lesbiab.space) didn't have it in cache and is not able to send anything since those servers were down

**Comment by nightpool** [comment]
@kit-ty-kate can you try deploying https://github.com/tootsuite/mastodon/pull/9412 and seeing if that fixes the problem?
