### ISSUE TITLE
Slow mode for timeline

### ISSUE THREAD

**Issue by ahappybell** [tootsuite/mastodon#9421]
Add a Slow Mode for the timeline
I can't keep up with the speed of the timeline sometimes, it'd be nice if it could be slowed down. Maybe only show every other post or every few posts on the timeline instead of every post?

**Comment by jokeyrhyme** [comment]
Or perhaps do the Twitter thing, and don't automatically add new content to the page, just show a refresh button when new content is available?

**Comment by trwnh** [comment]
This is 3.0.0rc1 right
