### ISSUE TITLE
Provide quick access to users' public profiles or web view from admin panel

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#9431]
Since 73faadad28b897cd61cc1d6c8bee47e7d72a51a1, there is no link to listed user's profile from the public panel.

The admin view of a user (`/admin/accounts/id`) is not a complete replacement as it is missing at least:
- their header image
- their bio & fields
- an easy way to contact them

**Comment by ryliejamesthomas** [comment]
Been meaning to ask for this myself, thanks!
