### ISSUE TITLE
Search for own toots

### ISSUE THREAD

**Issue by rugk** [tootsuite/mastodon#9460]
### Pitch

I know Mastodon does not want I can search the plain-text of other user's toots, but I would like to search for my own toots, respectively find them.

### Motivation

Use case: I knew I tooted something interesting/a link/whatever… some time ago, but I cannot find it again. That is bad…
And scrolling through the whole history is awkward. 

I think any user of Mastodon, who had this "problem" once, will benefit.

**Comment by Gargron** [comment]
This is already implemented though

**Comment by rugk** [comment]
hu? Where/How? If I just enter the search term into the search box, i only get hashtags etc. Not my own toots… (and yes, I've tried it with text I've tooted.)

Note I obviously want the whole toot of mine to be searched, not just hashtags or so…

**Comment by bobcanthelpyou** [comment]
@rugk i am not sure about that (i am new to mastodon) but i read something about Elasticsearch is needed to enable that feature for your instance, maybe your admin didn't setup it up? (but i might be wrong)
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Elasticsearch-guide.md#why-you-might-need-elasticsearch

**Comment by danhunsaker** [comment]
Full text search is not exactly simple. With Postgres and other SQL DB servers, it's painfully slow after only a few thousand records. Elasticsearch is designed for full text search, however, and is considerably faster at it. It wouldn't work well for most of the stuff that goes in the database, so switching completely isn't workable at all, but adding it on absolutely is.

I'll add that deploying an instance with Nanobox or Docker (properly configured) will automatically get you all of the software used to provide all the features Mastodon supports, so either is a solid approach.

**Comment by rugk** [comment]
@rektide If the instance enabled that, you can just use the search box. There is only one. If it does not find that, the feature is likely disabled. :sweat_smile:

**Comment by johnca** [comment]
I'm on mastodon.social, and can't even find my own #introduction post.

Searched for #introduction @slowenough@mastodon.social and I am scrolling, and scrolling, and scrolling...

Tried #introduction AND @slowenough@mastodon.social but no improvement. Did some general web searching for boolean elasticsearch but results are about code syntax, not search box syntax.

Any advice?

**Comment by mmahmoudian** [comment]
@johnca I just manage to do it using this syntax: `#TheHashTag from:@user`

![image](https://github.com/mastodon/mastodon/assets/390889/9eed11d8-54d4-4371-a731-56d5fa72082e)
