### ISSUE TITLE
Allow single column tag browsing for not-logged-in users

### ISSUE THREAD

**Issue by pawelngei** [tootsuite/mastodon#9475]
### Pitch

Right now when browsing a tag ([example](https://writing.exchange/tags/solarpunkreporting)) when not logged in the toot column takes only 1/3 of the screen. The rest is taken by what-is-mastodon messages, which you cannot dismiss.

My suggestion is either to make the information column dismissible or to make it narrower, 1/3 compared to 2/3 now.

### Motivation

The ability to link to a tag is useful when talking to people from outside of Mastodon (like the birdsite) and showing them a specific piece of content. While it is important to introduce them to the network, sacrificing 2/3 of the screen for that information seems very in-your-face and may be counterproductive in convincing them it's viable.

Mastodon's user page ([example](https://writing.exchange/@alxd)) has only a small card informing about what is mastodon / this instance and I think it would be okay to collapse it this way.

**Comment by mynameismonkey** [comment]
I believe this should be closed as the new tag page uses 100% of the page in three columns: example https://toot.wales/tags/anormaldayinwales

**Comment by pawelngei** [comment]
Completely support that, it looks awesome now :)
