### ISSUE TITLE
Active sessions still valid after password reset

### ISSUE THREAD

**Issue by bobcanthelpyou** [tootsuite/mastodon#9476]
Yesterday i did a reset of my password on my smartphone for the use of a different mastodon app. After the reset i am still able to use my active session in my browser on my desktop computer (i don't need to login with my new password). Also the sessions of other apps are still valid.

### Pitch

When someone does a password reset all active sessions should be invalidated. A login with the new password is needed.

### Motivation

Better security/privacy if login credentials/login sessions are used by a third party without permission.

**Comment by nsuchy** [comment]
Did you complete the reset (e.g set a new password), or just request the email to reset?

**Comment by bobcanthelpyou** [comment]
@nsuchy i completed the password reset, cause i did't had the password in mind and needed a password to activate a new app.

**Comment by agusgs** [comment]
Hey. I want to contribute by tackling this issue.
I'll be working on a pr for fixing this one.

**Comment by Gargron** [comment]
Sorry, I'm pretty sure I already fixed this in #12928, just didn't find the issue to attach.

**Comment by agusgs** [comment]
Hey, @Gargron  thank you for the response.
I'm relatively new to mastodon, so maybe I'm misunderstanding something. I'm still being able to replicate the issue...
So, it could be that the instance where I'm registered doesn't have the last version of mastodon?

**Comment by Gargron** [comment]
What's the version?

**Comment by agusgs** [comment]
Apparently the last one (3.2.1) https://fosstodon.org/
I was able to replicate the issue by changing the password on the browser and still being able to use the mobile app https://tusky.app.

**Comment by Gargron** [comment]
Oh, apps don’t use sessions. Apps use oauth access tokens. Unlike browser sessions, apps have no ability to change the password or any security settings through the token. 

Personally, i would not be happy if I got logged out of my app when I routinely changed my password. For account takeover scenarios we just recommend people to change password *and* review authorized apps.

**Comment by agusgs** [comment]
I see. Thank you for the clarification.
Well, I'll look up for something else to contribute :smile:
