### ISSUE TITLE
integrate CROWDIN 4 translations

### ISSUE THREAD

**Issue by diomed** [tootsuite/mastodon#950]
@Gargron 

It would be good if you could integrate translations with CROWDIN so translators would have easier access and clarity over what's translated and what needs to be:
It's free for open source projects:
[Crowdin](https://crowdin.com/page/open-source-project-setup-request)
* * * *

**Comment by davidak** [comment]
There is already a discussion about translation platforms in https://github.com/tootsuite/mastodon/issues/1241.

Can you post this suggestion as a comment there and close this?

**Comment by ashfurrow** [comment]
Good idea @davidak. I cross-linked and will close this issue. Let's continue the discussion there!
