### ISSUE TITLE
Custom filter edition page always show that the edited filter never expires

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#9506]
### Expected behaviour

When saving a filter with an expiry other than "never", clicking to edit the filter should show the original expiry that was selected when first saving the filter.

### Actual behaviour

Clicking to edit a filter shows the expiry "never" every time, no matter which expiry you selected and saved originally.

### Steps to reproduce the problem

1) Make new filter with the expiry "one week".
2) Save.
3) In the filtered words list, click "edit" next to the filter you just saved.
4) Expiry is "never".

### Specifications

Vanilla Mastodon 2.6.1, https://queer.party.

![fliter timing doesn t stick](https://user-images.githubusercontent.com/6607512/49847848-1f96d580-fdca-11e8-890f-2ccdd882a441.gif)

**Comment by Cassolotl** [comment]
Oh that does make sense. :S Still, it is very confusing. Should it show the expiration date when you go to edit it, and an optional dropdown to resave it that defaults to "select" or some other placeholder?

**Comment by danhunsaker** [comment]
If it were me deciding this, I'd insert the currently saved timestamp as an additional option in the existing drop-down, allowing the user to see that the current expiry is set, when it will happen, and still adjust it as expected.

**Comment by Cassolotl** [comment]
That sounds great!
