### ISSUE TITLE
View content from a list of users

### ISSUE THREAD

**Issue by jerome-tgl** [tootsuite/mastodon#952]
Feature suggestion: make it possible for anyone to view the timeline of a list of users.

**Use case**

When I click on the `Follows` tab on a user profile, I only get a list the users someone follows. I'd like to be able to view the content published by these users, just by clicking on a button (toots, boosts and favs – as if I followed them myself). This would allow me to preview the `home` column of anyone, to leave my little filter bubble and experience anyone's timeline. This would also help me discover other users, by jumping from one timeline to another.

**Further development**

This preview feature could be implemented as a search query:`list:@user/follows`

This could be very powerful when combined with other operators. For example:

- toots with more than 5 boosts from people followed by @user: `list:@user/follows boosts:>5`
- toots from people followed by @user's and not me: `list:@user/follows -list:@me/follows`
- toots from my followers: `list:@me/followers`

* * * *

- [] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jeepfromoil** [comment]
This idea could be extended to instances, so that anyone could view what's going on in another instance and take a look to anyone's local timeline.

E.g `instance:@mastodon.dk #news`

**Comment by remram44** [comment]
Sounds to me like you want #134 (#5703 got merged last month)

**Comment by Cassolotl** [comment]
> This idea could be extended to instances, so that anyone could view what's going on in another instance and take a look to anyone's local timeline.

Sounds like *[FEATURE] Follow public local timelines from other instances #6942*.

> This would allow me to preview the home column of anyone

This actually sounds kind of creepy?

**Comment by Gargron** [comment]
>This actually sounds kind of creepy?

Yeah, it is. GNU social has that feature. I'm against it.
