### ISSUE TITLE
Pull in existing toots when following new remote account

### ISSUE THREAD

**Issue by thebaer** [tootsuite/mastodon#9525]
### Pitch

Mastodon should automatically pull in recent toots from a newly-discovered remote account.

### Motivation

When a user searches for a remote account in Mastodon, it pulls in the account's basic information (including toot count) without pulling in the toots themselves. I've personally heard plenty of questions around this behavior when people try to follow their WriteFreely blogs from Mastodon, and I have to explain that Mastodon won't show previous posts and will only receive them once you're following the account.

I also think it's reasonable to say that most people will expect to at least see _something_ in the profile when they first open it. The "Information below may reflect the user's profile incompletely." disclaimer doesn't fully describe what information _is_ complete, and people often think something is broken when they see a "Toots" number that doesn't match how many toots are actually displaying in the profile.

#### Quick workaround

In the empty toot space on a profile, describe why there are no toots in the profile, e.g.

> No one on this instance has followed @username yet. Follow them to start receiving their toots.

#### Better fix

When a new remote account is discovered and stored locally:

* fetch the outbox as well
* import the most recent 1 or 5 or 20 toots

Optionally, only perform these actions when the account is followed, instead. Or add a **Load more** button to the profile, like in other timelines.

**Comment by Cassolotl** [comment]
Is this a duplicate of *Backfill statuses from remote accounts when first subscribed #34*?

**Comment by thebaer** [comment]
Ah, yes it is.
