### ISSUE TITLE
A way of knowing if media was marked sensitive or not when display settings set to display all sensitive media.

### ISSUE THREAD

**Issue by spaceottercode** [tootsuite/mastodon#9530]
On the Web UI there doesn't appear to be a way to tell, in essence, the initial visibilty of media. This isn't an issue until you set your display setting to show all media marked as sensitive. Why is this an issue? By reboosting another artist's toot you may be accidentally introducing unmarked media none the wiser.

**Comment by spaceottercode** [comment]
While not worthy of important as the use case above, there's also the added benefit of not freaking out the first time you use the always show media marked as sensitive and you post your 1st tagged drawing and it shows up in the clear followed by the short lived shock until you realize oh yeah, display settings. 😅

**Comment by ThibG** [comment]
There is a way to tell, but it's far from obvious: whenever you hide the media, the message is different if it was marked as sensitive.

![screenshot_2018-12-16 dev instance 1](https://user-images.githubusercontent.com/384364/50053714-1004ed00-013a-11e9-95a6-1ad5a31c61ab.png)

![screenshot_2018-12-16 dev instance](https://user-images.githubusercontent.com/384364/50053716-12ffdd80-013a-11e9-8661-ac534928759d.png)

Of course, something more visible would make sense. Glitch-soc has an extra “sensitive” label shown besides the eye icon whenever the media is marked as sensitive.

**Comment by spaceottercode** [comment]
Thank you @ThibG 🙏 So for now, I'll just click the eyeball to reveal the spoiler card, prior to boosting a toot in question.

**Comment by spaceottercode** [comment]
Closing, because technically speaking there is a means of distinguishing if media was initially hidden behind a spoiler card as pointed out by @ThibG. One could advocate for a more evident distinction but that technically should be the subject of a separate issue/ticket.
