### ISSUE TITLE
`rel="me"` isn't recognized

### ISSUE THREAD

**Issue by isagalaev** [tootsuite/mastodon#9538]
### Expected behaviour

The link to `softwaremaniacs.org` on this profile https://mastodon.social/@isagalaev should be highlighted as "verified", as the target document has an `<a rel="me">` with the link to the profile.

### Actual behaviour

The link is not highlighted.

### Steps to reproduce the problem

1. Look at the profile page
2. Check the source of http://softwaremaniacs.org/

### Specifications

Version: v2.6.5

### Speculation

With the formalities out of the way, let me point out that the target page relies on the ability of HTML to omit certain opening and closing tags (like `<head>` and `</body>`), so it is likely that it fails to parse due to an underlying HTML parser making overly strict assumptions. I may be totally off-base here, but I thought it's worth mentioning.

**Comment by ThibG** [comment]
It works here. Did you update your profile *after* adding the link on your page?

**Comment by isagalaev** [comment]
"Here" where? :-)

Actually, both the link in the profile and the `rel="me"` were there way before Mastodon got this feature to recognize it. I can re-add link to see what happens or I can leave it like that to preserve the error condition, if that's interesting to you guys.

**Comment by ThibG** [comment]
“Here” is on my local instance, sorry.
Links are only verified after a profile update, so if you didn't modify your profile after Mastodon got this feature, that's why it doesn't show up as verified.

**Comment by isagalaev** [comment]
Yep, that fixed it. Thanks!

**Comment by pawelngei** [comment]
I'm checking https://mastodon.social/@isagalaev right now and the link to https://mastodon.social/@isagalaev seem positively verified.

Maybe it just cached the wrong version before?

**Comment by isagalaev** [comment]
@pawelngei no, I fixed it by updating the profile following @ThibG suggestion.
