### ISSUE TITLE
 ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column mentions.silent does not exist

### ISSUE THREAD

**Issue by 2019bigpanda** [tootsuite/mastodon#9540]
Normally I should be able to see my own posts, I'm concerned about people's posts and all the content of the world timeline, but I can't actually see my own posts on this instance right now, and my notification messages, and all the content of the world timeline.
Before that I follow the guide (https://docs.joinmastodon.org/administration/upgrading/) from 2.5.2 version upgrade to 2.6.4.No errors occurred during the upgrade process.
After an error occurred, I tried to upgrade to 2.6.5, but the problem persisted.

`Dec 17 01:53:25 chating.xyz bundle[24004]: [18edb95a-fc6a-426f-82fa-ba8189a56ce1]
Dec 17 01:53:25 chating.xyz bundle[24004]: [18edb95a-fc6a-426f-82fa-ba8189a56ce1] app/controllers/application_controller.rb:116:in `each_with_object'
Dec 17 01:53:25 chating.xyz bundle[24004]: [18edb95a-fc6a-426f-82fa-ba8189a56ce1] app/controllers/application_controller.rb:116:in `cache_collection'
Dec 17 01:53:25 chating.xyz bundle[24004]: [18edb95a-fc6a-426f-82fa-ba8189a56ce1] app/controllers/api/v1/timelines/home_controller.rb:26:in `cached_home_statuses'
Dec 17 01:53:25 chating.xyz bundle[24004]: [18edb95a-fc6a-426f-82fa-ba8189a56ce1] app/controllers/api/v1/timelines/home_controller.rb:22:in `load_statuses'
Dec 17 01:53:25 chating.xyz bundle[24004]: [18edb95a-fc6a-426f-82fa-ba8189a56ce1] app/controllers/api/v1/timelines/home_controller.rb:11:in `show'
Dec 17 01:53:28 chating.xyz bundle[24004]: [781bf76c-4504-4dbe-b8cc-ad9451f30869] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=shostatus=500 error='ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column mentions.silent does not exist
Dec 17 01:53:28 chating.xyz bundle[24004]: LINE 1: SELECT "mentions".* FROM "mentions" WHERE "mentions"."silent...
Dec 17 01:53:28 chating.xyz bundle[24004]:                                                   ^
Dec 17 01:53:28 chating.xyz bundle[24004]: : SELECT "mentions".* FROM "mentions" WHERE "mentions"."silent" = $1 AND "mentions"."status_id" IN ($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,13, $14, $15, $16, $17, $18, $19, $20, $21)' duration=22.15 view=0.00 db=5.64
Dec 17 01:53:28 chating.xyz bundle[24004]: [781bf76c-4504-4dbe-b8cc-ad9451f30869]
Dec 17 01:53:28 chating.xyz bundle[24004]: [781bf76c-4504-4dbe-b8cc-ad9451f30869] ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column mentions.silent does not exist
Dec 17 01:53:28 chating.xyz bundle[24004]: LINE 1: SELECT "mentions".* FROM "mentions" WHERE "mentions"."silent...
Dec 17 01:53:28 chating.xyz bundle[24004]:                                                   ^
Dec 17 01:53:28 chating.xyz bundle[24004]: : SELECT "mentions".* FROM "mentions" WHERE "mentions"."silent" = $1 AND "mentions"."status_id" IN ($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,13, $14, $15, $16, $17, $18, $19, $20, $21)):
`
I appreciate any help and support

**Comment by Gargron** [comment]
Did you: a) not run db:migrate b) did not restart mastodon after doing so?

**Comment by 2019bigpanda** [comment]
> Did you: a) not run db:migrate b) did not restart mastodon after doing so?

Nope, I only did what was in the documentation.
After running a), the problem was solved.
Please update the upgrade document
thank you
