### ISSUE TITLE
 click on the tag , nothing is displayed

### ISSUE THREAD

**Issue by kaias1jp** [tootsuite/mastodon#9548]
click on the tag , nothing is displayed

### Expected behaviour
If you click on another hash tag with hash tag TL displayed, hash tag TL selected later will be displayed

### Actual behaviour
When you select another hashtag, nothing is displayed on the screen

### Steps to reproduce the problem
1) Search hash tag 1 2) Click hash tag 1 to display TL 3) Search hash tag 2 4) Click hash tag 2

### Specifications
version 2.5.3

Google Chrome , Ubuntu 18.04

**Comment by kaias1jp** [comment]
Sorry, I will reproduce it in v 2.6.5 or later

**Comment by kaias1jp** [comment]
It fix on #9662 .
I will check it in my own environment.

**Comment by archaeme** [comment]
Ah, maybe my instance hasn't been updated yet.
