### ISSUE TITLE
oEmbed or similar?

### ISSUE THREAD

**Issue by benhamill** [tootsuite/mastodon#955]
If you paste a link like https://octodon.social/web/statuses/31345 into Slack, for instance, the preview is a description of what Mastodon is. It would be more helpful if it were the toot linked.

What do people feel about adding oEmbed (or Twitter Cards or Open Graph, which things I know basically nothing about) to the status page(s) for better embedding/previewing in other applications and contexts?

**Comment by DeadSuperHero** [comment]
Yeah, I'm jumping in to second this. It's not necessarily too hard to implement an OEmbed interpreter for posts - the ruby-oembed gem might provide a good foundation for previews on posts.

Ironically, you could support Instagram, making you better than Twitter for an entirely new reason.

**Comment by pankas87** [comment]
I agree! Support for oEmbed should be added. I'll take a look at the code this weekend to estimate how complex it is

**Comment by benhamill** [comment]
Oh shit. This is solved, actually. The link above is just the wrong one. It should be something like https://maly.io/users/HedgeMage/updates/4296 or https://maly.io/@HedgeMage/57693 (same toot). Closing and I love asking for a feature that is already implemented. 🙄

**Comment by benhamill** [comment]
Uh... Wanted to add for posterity: The reason the URL I initially posted doesn't work for oEmbed is because it requires you to be logged in. So the preview that Slack pulls in is the "WTF is Mastodon" sign up page. The other two are the unauthed direct links to the status on its home server.
