### ISSUE TITLE
list aliases that can be @/mentioned in toots

### ISSUE THREAD

**Issue by spaceottercode** [tootsuite/mastodon#9566]
We have lists,  but no way to reference them in toots. If lists could somehow be referenced inside a toot, using some form of notation, and resolving to its constituents. In many ways these aliases could be thought of as being similar to email aliases. That is, you could share or communicate with a group of people.

~~Because of their current use, lists currently include people you follow. In the future should you be able to make lists of followers, then list aliases become even more useful. Regardless, still useful for the use case presented above.~~

**Comment by trwnh** [comment]
Possibly related: #7182 for posting to lists (and #5686 for making lists of followers)

**Comment by spaceottercode** [comment]
Thank you @trwnh I am reviewing both.  I  have also updated the original comment by striking out nonessential portion as to not detract.

**Comment by spaceottercode** [comment]
Hi @trwnh

I think the essential differences might be in the interfaces whereas the backend would largely be the same or compatible. The backend being way more critical and that being covered in 7182, I think it does make sense to retire this feature request. It's something that can be revisited later.
