### ISSUE TITLE
excessive polling (like four times a second) when scrolling near the bottom of a timeline

### ISSUE THREAD

**Issue by makoConstruct** [tootsuite/mastodon#9568]
### Expected behaviour

Either only polls once, or only polls once per second

### Actual behaviour

Polls seemingly whenever the scrollbar moves by any amount.

### Steps to reproduce the problem

Scroll to the end of a profile's tweet history. The loading bar will go crazy. A lot of network packets will be requested that just contain `[]`. It may be noticeable at the end of what's loaded of a timeline as well, though it might only be noticeable if the server is slow to respond, as the symptoms will cease when additional tweets have been loaded.

### Specifications

v2.6.5

vivaldi 1.11.917.43 (Stable channel) (64-bit), debian linux

**Comment by ThibG** [comment]
Concurrent requests should already prevented.
However, there is indeed an issue when reaching the end (as in, no more toots to load) of a timeline. I will fix that.
