### ISSUE TITLE
Potential for oversharing boosts?

### ISSUE THREAD

**Issue by pjbingham** [tootsuite/mastodon#9577]
Potential for "over-sharing" boosts?

### Pitch

New to mastodon, I've only recently discovered that boosts can't ever - by definition - be private.  I think this is a mistake, undermining the _intent_ of the post privacy settings.

A better approach, in my view, would be treat interactions with posts/toots separately from the posts/toots themselves.

Just because a post is unlisted or public, why should my _interaction with it_ necessarily be the same (particularly if the intent behind me setting post privacy = private was to create an environment where my activity was only shared with followers)?  Presumably a world is possible where, however I interact with it, the post itself remains unlisted/public, but only my followers are aware that it was me who interacted with it?

I think boosts should either respect the post privacy setting of the boosting account or (better, but probably more complicated to implement) should have a separate per-boost privacy control of their own, similar to the per-post philosophy of mastodon in general.

### Motivation

I think the current approach, while technically consistent, is unintuitive - particularly, but I think not just, for people looking to make the transition from twitter.  Worse, it's unintuitive in the "wrong direction" - i.e. boosts are shared _more_ publicly than people might expect (I'm sure it'd be less of an issue if it were the other way around).  It's also not clear how to run an account in mastodon where your activity - of all kinds - is shared only with followers.  All these things may be barriers to adoption.

### More Info

An example:

Feel free to look at my profile https://mastodon.me.uk/@philip  The one and only boost so far is clearly visible - even if you're not logged in - even though I've set post-privacy to "followers only".  This is unintuitive (and really not the outcome I want...).  Does this mean, if I want my account to be truly private, I can't ever boost anything, and therefore if I wanted to draw my followers (only) attentions to various posts, I'll have to manually copy links into fresh toots to them?  Apologies in advance if PEBKAC applies - I am, admittedly, new to masto.

A discussion (abridged) I had with @renatolond (of crossposter fame), may also help illustrate (I have his permission to quote...):

@renatolond says
> @philip About the boosts, mastodon privacy works per-post, not per account, like twitter's. Which means that if you can boost a post, it's either unlisted or public (followers-only posts cannot be boosted), and public/unlisted posts show on your profile :)

@philip says
> I actually think this is a functional bug too - just because the post being boosted is public or unlisted, why does that mean the fact that I boosted it has to be too?  Isn't that missing the point of what "private" is trying to achieve?

@renatolond says
> Hm, in my mind it's because you cannot "reduce" the privacy of someone else's toot (they already posted in public or unlisted, you're boosting it to people that follow you), if you  reduce the privacy, it means that people that follow you could not boost that, since private posts cannot be boosted. (Except by their own creator)
> 
> But I don't know, indeed it might be that I'm just used to it :)
> 

@philip says
> but I'm not reducing the privacy of someone else's toot, just trying to control the privacy of my *interaction* with it (presumably it's still happily unlisted/public back wherever it lives)!
>
> But yes, I get this is a perspective/way of looking at things.
>
> (...)

> The issue I see is the current approach, while very technically consistent, isn't intuitive (particularly for those coming from birdland, but I suspect not just...). 

To add to the discussion above - I see @renatolond's issue, but surely if one of my followers wants to also boost a post that I somehow "privately" boosted, they're boosting the original post and not my boost of it - I'm not the creator, after all - so whatever privacy applies to my boost is (or should be) irrelevant?

Plan B... not as ideal, but if it has to work that way and they're boosting my boost, so to speak, then even if they were prevented from doing that because my boost was "private", couldn't they  just go back to the original and boost that?  I don't think it does - or needs to - work that way though.

Put another way:
- @foo's post is created by @foo and therefore respects his/her privacy settings.  So far so good.
- My _boost_ of @foo's post is _created by me_ so shouldn't it respect _my_ privacy settings - why should it follow @foo's?  Why does @foo get to decide the privacy of my boosts?

Look forward to your thoughts on my thoughts...

**Comment by trwnh** [comment]
I was coincidentally just thinking of this a few minutes ago. I do think that `Announce` needs its own privacy interpretation as well, in order to prevent the scenario you have described (the same scenario that caused me to think of this issue as well). I think the default right now is to push the status directly into the feed and then calculate privacy of the boosted status rather than the boost itself. This might have some overlaps with #8794 ("You can reply to boosts")

**Comment by spaceottercode** [comment]
@trwnh @pjbingham maybe I'm way off, but doesn't this run counter to @Gargron reasoning for not having quote toots.

> I've made a deliberate choice against a quoting feature because it inevitably adds toxicity to people's behaviours. You are tempted to quote when you should be replying, and so you speak at your audience instead of with the person you are talking to. It becomes performative. Even when doing it for "good" like ridiculing awful comments, you are giving awful comments more eyeballs that way. No quote toots. Thank's

Note this is not irony.

Also making it transparent to the author of the toot who's sharing their content. (Though you could argue continue informing the original author of the root being boosted, just not the rest of the public, I suppose...but if you allow replies...isn't that a toot quote. Sorry I don't use twitter).

**Comment by nightpool** [comment]
There is no technical reason that this is the case, it's a UX question. Mastodon UX does not consider boosts as independent entities—they're simply "sharings" of the underlying status. By giving them an independent privacy level, that would require adding some way for users to "see" what the privacy of any given boost was, and maybe some way of "choosing" it when boosting. All of this adds substantial cognitive complexity to the interaction and mental model. On the other hand, if boosts inherited account privacy, that would be entirely novel in the mastodon UX, and the difference between status privacy being per-post and boost privacy being per-account would have a high potential for confusion. Furthermore, in this counterfactual world it would "make sense" that making your account public would retroactively make boosts public, but implementing that is infeasible with the current technical architecture, so that would be a UX "gotcha".

**Comment by ThibG** [comment]
Note that since a while, private boosts are possible. The API for that is here, but the UI will only perform private boosts when your default posting privacy is `private`/followers-only (or you are boosting one of your own private toots)
