### ISSUE TITLE
rel=me not working for urls linking to Tumblr or Instagram.

### ISSUE THREAD

**Issue by spaceottercode** [tootsuite/mastodon#9579]
### Expected behaviour

Adding your mastodon URL to the Instagram profile, then adding a URL in the profile metadata that points to your Instagram page, saving changes, rel=me URLs are verified that they point to each other. 

### Actual behaviour

Despite having a rel=me attribute, URLs in Instagram profiles do not register. Like Twitter, Instagram uses redirection. 

### Steps to reproduce the problem
  On Instagram: edit profile. Enter url in website field. E.g. https://mastodon.social/@username. Save. On mastodon, edit profile. Enter url in profile metadata content field. e.g. https://instagram.com/username 
 
I will document Tumblr in a future follow up, but the process is similar. 

### Specifications

Mastodon 2.6.1
OS: OS agnostic

**Comment by spaceottercode** [comment]
That explains why it doesn't register. Thank you. I need to document the steps for tumblr soon.

**Comment by fwenzel** [comment]
Instagram might server-side render for specific user agents (user agent cloaking?) so that Google will still index it. Running it through a browser engine would be rather heavyhanded.

Custom verifier for known services?
