### ISSUE TITLE
Silenced local users should not send public messages to other instances

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#9580]
### Pitch

If a local user is silenced, their outbound posts should be marked at most unlisted, and not public.

### Motivation

Local users are frequently silenced when they don't follow instance rules such as “no public untagged sensitive content”. Silencing them may appear to solve the issue, but this is not a sufficient way to ensure that instance rules are respected towards remote ones.

**Comment by Gargron** [comment]
I think that's probably the easiest way... Otherwise we would need some kinda capabilities table so we can disable lots of various small things for each user, and that's a mess.

**Comment by ThibG** [comment]
I mean, I'm all for granular moderation and filtering tools (and I think Mastodon's are pretty bad in that regard), but the particular case of “silence this local user from our timelines, but let them flood remote instances'” is weird.

**Comment by trwnh** [comment]
>the particular case of “silence this local user from our timelines, but let them flood remote instances'” is weird.

this does raise the question of the opposite case, "unsilence a remote user that is silenced on their local instance"

**Comment by ThibG** [comment]
@trwnh hm, yeah. I'm afraid I don't have an answer to that :/
