### ISSUE TITLE
Categories in Notifications timeline are missing when using Safari on macOS

### ISSUE THREAD

**Issue by jumoru** [tootsuite/mastodon#9595]
### Expected behaviour

Like for example in Firefox categories like "All", "@", ... should be visible
![bildschirmfoto 2018-12-20 um 14 24 16](https://user-images.githubusercontent.com/27491477/50287604-8c157280-0463-11e9-93e5-24f8a3e6e246.png)

### Actual behaviour

Categories are not shown when using Safari

![bildschirmfoto 2018-12-20 um 14 25 39](https://user-images.githubusercontent.com/27491477/50287663-b7985d00-0463-11e9-85e3-587baac34064.png)

### Steps to reproduce the problem

Log into Mastodon with Safari on macOS

### Specifications

Mastodon 2.6.5; Instance: https://mastodon.social

Safari 12.0.2 on macOS 10.14.02; all extensions disabled

**Comment by mayaeh** [comment]
I think that there is no problem right now.
Safari 12.0.2 on mac OS 10.14.2
<img width="700" alt="2018-12-21 13 49 09" src="https://user-images.githubusercontent.com/766076/50325426-1a532c80-0528-11e9-82b5-a7a4432810f6.png">

**Comment by jumoru** [comment]
For whatever reason I now works on my machine as well. Closing this issue.
