### ISSUE TITLE
Remote follow doesn't work

### ISSUE THREAD

**Issue by copystar** [tootsuite/mastodon#960]
[My instance is https://mastodon.cloud/ My profile is public and I can view it online. But when I try to remote follow using the web I receive an error message: 'Could not find the required redirect URL for your account' and when I try using the Tusky app, I receive the message 'Invalid Domain Entered']. Thank you!

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate. Problem with same error message was found at [https://github.com/tootsuite/mastodon/issues/736] but was marked as closed

**Comment by maop** [comment]
In the comments they say switching cert file to the fullchain cert solved the issue.. which i did and now it works fine. Read the comments, there is something about ipv6 too...

**Comment by ashfurrow** [comment]
@copystar it looks like there's a solution from @maop – can you verify if this is still a problem, or if you managed to fix it?

**Comment by copystar** [comment]
Unfortunately it still doesn't work. I get the message: "Could not find the required redirect URL for your account." I'm able to remote follow using the client and so the urgency to fix remote following via the web isn't pressing for me. Thanks for looking into this.

**Comment by ashfurrow** [comment]
Yikes, sorry to hear that. Since you opened this issue, some other users have reported similar issues and have reached resolutions. Could I ask you to take a look at https://github.com/tootsuite/mastodon/issues/2025 https://github.com/tootsuite/mastodon/issues/1185 and maybe https://github.com/tootsuite/mastodon/issues/736 to see if the solutions there work?

**Comment by copystar** [comment]
Thanks for sharing the similar issues but it appears that the solutions relies on changing the configuration of the instance itself, which as a user, I don't really have control over.  

What perplexes me is that I'm using https://mastodon.cloud/ and so I would have expected more people with this problem if it was based on the site's configuration. Thanks again all.

**Comment by ashfurrow** [comment]
Thanks for looking into that, it should help us narrow the problem down 👍

**Comment by paviro** [comment]
I am having the same problem. I can remote follow by searching a user on my instance and then following them but not via the URL: `Could not find the required redirect URL for your account`

Also I only seem to be able to see the posts of one person. Even the people I somehow managed to follow don't show any posts when accessing them trough my instance. 

I tried disabling IPv6 and also commented out the lets encrypt part but none of it did anything good.

**Comment by 0xicl33n** [comment]
I am having a similar problem but my error is `Unfortunately, there was an error looking up the remote account`. I have tried messing with ssl, i have tried removing the lets encrypt stuff, i have tried disabling ipv6... 

the ssl cert im using was given to me by my domain host, should i be using a lets encrypt one instead? The one they gave me *is* from lets encrypt so i really dont know what to do

**Comment by 0xicl33n** [comment]
Why was this closed? Does anyone know how to make this work? Is there a fix?
