### ISSUE TITLE
Add exclude_boosts filter in statuses REST API

### ISSUE THREAD

**Issue by VyrCossont** [tootsuite/mastodon#9606]
### Pitch

As a user viewing another user's account, deciding whether to follow them or not, I want to see only their own toots, not boosts.

As a developer building that feature for a client app, including Mastodon's own frontend, I can't do this efficiently.

I propose adding an `exclude_boosts` or `exclude_reblogs` filter parameter to the [GET `/api/v1/accounts/:id/statuses`](https://docs.joinmastodon.org/api/rest/accounts/#get-api-v1-accounts-id-statuses) REST API, analogous to the existing `exclude_replies` filter parameter.

This could be surfaced in the Mastodon frontend as a fourth tab alongside "Toots", "Toots and Replies", and "Media": "Toots without Boosts".

### Motivation

It can be very hard to see a user's own toots if they boost a lot of other users' toots. When I'm deciding whether to follow someone or allow them to follow me, I really only want to see what they've written, not what other people have written.

This feature _could_ be emulated by individual clients by fetching unfiltered statuses and removing boosts repeatedly until the desired number for display is reached, but that's expensive, potentially incurring many extra network operations (very bad for mobile clients), and each client would have to implement that emulation itself.

### Implementations in other platforms

Twitter's [equivalent to the GET account statuses API](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline.html) has an `include_rts` parameter that can be set to false to hide retweets. Twitter's web and mobile clients don't support this directly, but can produce a close equivalent using search, so some users have courtesy links in their profiles equivalent to this feature: user `@foo` might have `https://twitter.com/search?q=from:@foo` to show only their own content.

### Related issues

#5762 implements hiding boosts from a user that I _already_ follow. This feature would allow me to not fetch boosts when looking at any user, including one I don't follow.

#8482 would apply filters to boosts, another indication that there are cases where a user wants to treat boosts differently from regular toots.

**Comment by Cassolotl** [comment]
Something that I have wished for along these lines is for "toots" to include original toots and boosts, and "toots and replies" to include *only* original toots including replies. So boosts would show up in the default view, and if you want to investigate their posting history more you can click the toots and replies tab to see their replies and filter out all the boosts.
