### ISSUE TITLE
[Meta Proposal] Mastodon Project Landing Page

### ISSUE THREAD

**Issue by yiskah** [tootsuite/mastodon#961]
At some point it would be good to create a website, off of github (which confuses and overwhelms non-techies), which explains Mastodon The Project and can help you understand it and find an instance to join. Something besides mastodon.social to link people to and which can evenly explain things without funneling users onto one instance.  

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
Adding this here for anyone else trawling through issues 😄  https://github.com/tootsuite/joinmastodon

**Comment by Gargron** [comment]
https://joinmastodon.org has been live for a while, but we forgot to close this issue!
