### ISSUE TITLE
Problems with patching/updating profile custom fields

### ISSUE THREAD

**Issue by skddc** [tootsuite/mastodon#9611]
I found a couple of issues while trying to update a custom field of my profile via the API:

### Expected behaviour

1. `PATCH /api/v1/accounts/update_credentials` with parameter `fields_attributes[1][value]=Austria` should update the second custom field value with "Austria".
2. `PATCH /api/v1/accounts/update_credentials` with parameters `fields_attributes[1][name]=Location&fields_attributes[1][value]=Austria` should update the second custom field's name and value accordingly.

### Actual behaviour

1. All custom fields are deleted entirely (name + value), and a 200 response is returned with no errors and an empty custom field array.
2. All custom fields are deleted entirely, and replaced with only a single custom field with the new name and value, returned in the 200 response.

### Steps to reproduce the problem

Configure custom fields, try to update one.

### Specifications

Version 2.6.5

**Comment by hongthang152** [comment]
@skddc Did you pass these parameters on the URL or in the request body ? 
If it is in the request body, I am having no issue with it so far. 
If it is in the URL, the controller might misinterprets the nested array index as the hash key.

**Comment by skddc** [comment]
In the request body. I can reproduce it both with our deployed version and locally with the exact steps I described.

**Comment by hongthang152** [comment]
Thats weird. Let me look further into this

**Comment by Gargron** [comment]
You need to put the entire fields array there, you can't selectively update just a part of it

**Comment by danhunsaker** [comment]
> You need to put the entire fields array there, you can't selectively update just a part of it

That sounds like the expected behavior of a PUT, rather than a PATCH. Under the HTTP spec, PATCH "applies partial modifications to a resource".

**Comment by Gargron** [comment]
Well, PUT and PATCH are mapped to the same method in Rails. Think of the fields attribute like a single item, not a nested structure it's returned as. You can't PATCH to update the 3rd letter in a display name.

**Comment by danhunsaker** [comment]
Always love it when frameworks violate the standards they are meant to support. 😕

**Comment by nightpool** [comment]
🙄

**Comment by nightpool** [comment]
`fields_attributes` is a single part of the larger account resource, and nobody follows the HTTP spec anyway—there are even some arguments that, by letter of the spec, [sending field values alone without instructions on how to reverse the changes is a violation](https://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/)

**Comment by skddc** [comment]
I think the comments so far justify further discussion, because everyone agrees that one can PATCH the profile without submitting the entire profile. As custom fields are also just profile fields, except user-defined, I think it doesn't make sense having to submit the entire array, same as it doesn't make sense to submit the entire profile in order to update the display name.

My use case illustrates this quite well: I'd like my Huginn instance (a kind of open-source IFTTT thingy) to update my "current location" profile field when I switch cities. It already does this on my personal website for example. However, the agent updating the location cannot know about other profile fields by itself. The only solution is having to first download the entire profile, replace an existing field, then re-uploading the entire profile.

As you've said, this isn't necessary with PATCH, where one can update just the display name or just the bio. So why shouldn't one be able to update just one custom field? Triggering a single PATCH request is much easier to automate than GET => local patch => PATCH.

Another argument for enabling this is that nested parameters [are already supported and documented](https://docs.joinmastodon.org/api/parameters/#nested-parameters) for other resources, so it's inconsistent to not allow them for profile fields. And the legacy documentation even [explicitly documents submitting array parameters for this very resource](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#updating-the-current-user).

### Regarding the actual bug

In any case, even if it is decided that arrays cannot ever be updated using nested parameters, then the bug documented here is that the API will gladly except invalid parameters and destroy the entire custom profile without warning. In the very least, in that case, it should return some warning and status code in the 400 range instead of silently destroying data and pretending everything worked totally fine.

**Comment by hongthang152** [comment]
#9619 Fix provides the ability to pass nested parameter either as a single object or an array of objects. It also raises exception when the custom attribute does not follow the proper format.
