### ISSUE TITLE
Problems whit apache2

### ISSUE THREAD

**Issue by kasinjsh** [tootsuite/mastodon#9621]
Hi.

Im trying to figure out hot to setup My own instance and problem I have is whit docker and apache2. I have followed your guides and materials to setup whit apache2, but problem is that web page is not showing .js, pictures, and other content. inspector in browser shows for example it cant load ¨https://mastodon.liepajnieks.lv/packs/common-ffc29dd6e2ae10c4e36d.js¨.

What could be an issue?

I attached a picture.

![anotacija 2018-12-25 010020](https://user-images.githubusercontent.com/6105540/50407490-ab542d00-07e0-11e9-9a62-8e1cc7d65319.jpg)

**Comment by kasinjsh** [comment]
I found solution online.

**Comment by WNYmathGuy** [comment]
> I found solution online.

Well, share that solution with others, please...

**Comment by kasinjsh** [comment]
https://github.com/tootsuite/mastodon/pull/1018/files this file worked for me.

**Comment by WNYmathGuy** [comment]
Thanks @kasinjsh  
I had about the identical set-up and got no joy. I gave up yesterday and am looking-for/learning-about another similar solution like Friendica, Matrix w/Riot or GNU Social.
