### ISSUE TITLE
PostgreSQL: database cannot be migrated if dot is used in database name

### ISSUE THREAD

**Issue by pztrn** [tootsuite/mastodon#9622]
### Expected behaviour

After using database name like ``mydomain.tld_mastodon`` it should work

### Actual behaviour

```
PG::SyntaxError: ERROR:  syntax error at or near "."
LINE 1: CREATE DATABASE "mydomain"."tld_mastodon" ENCODING = 'unicode'
                               ^
: CREATE DATABASE "mydomain"."tld_mastodon" ENCODING = 'unicode'
Couldn't create database for {"adapter"=>"postgresql", "pool"=>5, "timeout"=>5000, "encoding"=>"unicode", "database"=>"mydomain.tld_mastodon", "username"=>"mydomain.tld_mastodon", "password"=>1234567890, "host"=>"192.168.1.4", "port"=>5432, "prepared_statements"=>true}
rails aborted!
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "."
LINE 1: CREATE DATABASE "mydomain"."tld_mastodon" ENCODING = 'unicode'
                               ^
: CREATE DATABASE "mydomain"."tld_mastodon" ENCODING = 'unicode'
```
### Steps to reproduce the problem

Use ``mydomain.tld_mastodon`` as database name.

### Specifications

Mastodon 2.6.5 on Ubuntu 18.04 configured according to https://docs.joinmastodon.org/administration/installation/#basic-server-setup-optional

**Comment by danhunsaker** [comment]
Is it legal, in Postgres, to include a `.` in a name? MySQL, at least, uses `.`s as a separator between components in an absolute path, such as `database.table.column`. I'm unfortunately less familiar with Postgres, but based on the query in the error message, above, it looks like the same limitations are in play here, too.

Your best bet is to transform `.`s to `_`s or `-`s before sending DB queries, including `CREATE DATABASE`.

**Comment by hongthang152** [comment]
It is considered bad practice to have `.` in your SQL database name . Not just in PostgreSQL but other databases as well. I would go with @danhunsaker recommendation if you want a solution to this.

**Comment by nightpool** [comment]
you *can* do it, but the database.yml syntax assumes that, if you use a dot, it specifies the schema+database, not just the database name
