### ISSUE TITLE
[Meta Proposal] Managing instance list through Pull Requests is becoming unwieldly

### ISSUE THREAD

**Issue by yiskah** [tootsuite/mastodon#963]
The majority of pull requests are now new instances. The rate at which instances are being created is too quick to have mixed in with pull requests for code, especially with only one person merging them. We need to create some sort of dynamic instance list, akin to instances.mastodon.xyz (but ideally not hosted by a volunteer), which we can host on a hypothetical project landing page. 

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by thurloat** [comment]
Totally agreed, and with the popularity of instances.mastodon.xyz it looks like he's even having trouble keeping that one alive.

**Comment by HongPong** [comment]
I think all the documentation ( https://github.com/tootsuite/mastodon/tree/master/docs ) should just be moved into a separate repo including the instance list with that. That would partition a great deal of the problem into different parts.

**Comment by ashfurrow** [comment]
The documentation has indeed been moved into it's own repo: http://github.com/tootsuite/documentation I'm going to close this issue but feel free to re-open if you want to discuss things further 👍
