### ISSUE TITLE
microformats clean-up

### ISSUE THREAD

**Issue by dissolve** [tootsuite/mastodon#965]
As stated in #122 and #421 the original requester did not consider this 100% corrected.
Starting this issue as a new issue since old one was closed.

I noticed this particularly bad on main feeds where the h-entry class is missing on the main user feed. Thus making the page look list a single entry with lots of copies of the h-card and many different contents.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by HongPong** [comment]
Perhaps there could be a test added for microformats compliance. Thanks for taking a look at this.

**Comment by kevinmarks** [comment]
the Content Warning posts don't quite work right. See https://mastodon.social/@kevinmarks/1974708

in the atom the prefix text is summary, the post-cw text is content, but then title is the post-cw text too, so the title/summary/content thing is going to confuse feed readers.

The mf2 is more confused as the "show more" ends up in the middle of the text content, and  is inline in the html content.
currently we have
````
<div class='status__content e-content p-name emojify'>
  <p style='margin-bottom: 0'>
    <span>format nerdery </span>
    <a class='status__content__spoiler-link' href='#'>Show more</a>
  </p>
  <div style='display: none; direction: ltr'>
    <p>should the CW prefix text be p-summary and the full text be e-content ?</p>
  </div>
</div>
````
What would make more sense would be
````
<div class='status__content p-name emojify'>
  <p style='margin-bottom: 0'>
    <span class="p-summary">format nerdery </span>
    <a class='status__content__spoiler-link' href='#'>Show more</a>
  </p>
  <div class="e-content" style='display: none; direction: ltr' >
    <p>should the CW prefix text be p-summary and the full text be e-content ?</p>
  </div>
</div>
````
Or (to be all semantic html)
````
<details class='status__content p-name emojify'>
  <summary style='margin-bottom: 0'>
    <span class="p-summary">format nerdery </span>
  </summary>
  <div class="e-content" style='display: none; direction: ltr' >
    <p>should the CW prefix text be p-summary and the full text be e-content ?</p>
  </div>
</details>
````
with the show more as a :after on the p-summary span

**Comment by Gargron** [comment]
The "shore more" cannot be a CSS pseudo-element because it requires JavaScript interaction for the display toggling. (Otherwise I quietly agree with the points made)

**Comment by kevinmarks** [comment]
Details/summary does that with no js involved (at the UI cost of the
summary text being clickable too).

On 8 Apr 2017 12:36 pm, "Eugen" <notifications@github.com> wrote:

The "shore more" cannot be a CSS pseudo-element because it requires
JavaScript interaction for the display toggling. (Otherwise I quietly agree
with the points made)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tootsuite/mastodon/issues/965#issuecomment-292712396>,
or mute the thread

**Comment by dissolve** [comment]
Updated the PR to correct for p-summary / e-content with CW posts
