### ISSUE TITLE
Blind Key Rotation not properly supported

### ISSUE THREAD

**Issue by kaniini** [tootsuite/mastodon#9658]
### Background

Blind Key Rotation is a proposed mitigation for the inability to revoke JSON-LD Linked Data Signatures.  It is based on the fact that AP implementations are supposed to refetch an actor's keys in the event that a signature fails to validate and recheck the signature.

Mastodon should implement Blind Key Rotation on `Delete` activities by sending the `Delete` activity signed by the original key and then generating a new keypair afterward, but that should be split into a different bug.

### Expected behaviour

Mastodon should accept a blind key rotation from a remote user.  This is necessary for situations where an instance is reinstalled anyway.

### Actual behaviour

Mastodon does not accept blind key rotations.  In order to get Mastodon to accept the new keys, the instance or user must be entirely suspended and unsuspended in order to delete the old key data.

### Steps to reproduce the problem

1. Change an actor's keys.
2. Send messages to Mastodon.
3. Messages are not accepted due to invalid signature.

### Specifications

Mastodon 2.6.5 on testodon.dereferenced.org.

**Comment by kaniini** [comment]
Based on whenever this gets fixed in Mastodon we intend to roll it out in Pleroma after a few development cycles.  Right now this issue is blocking our efforts to improve future deniability by rotating keys.

**Comment by Gargron** [comment]
A couple things:

- If key validation fails and the last webfinger query was at least 1 day ago, the actor is re-resolved and a new key is fetched. This is exactly to help in situations where the instance is reinstalled.
- Mastodon supports an Update activity on the actor which is signed with the old key but contains a new key. This is part of Mastodon's own `tootctl accounts rotate` utility.

**Comment by ThibG** [comment]
Nevermind, there is a use for LDS for pretty much all public activities: relays.

**Comment by ThibG** [comment]
@kaniini I fail to see how signing the `Update` with the old key would make deniability more of a problem. If you can pretend that a signed message was fake because the old key wasn't yours, you can have the same argument about it signing your new key.

Sending such an `Update` would help with current Mastodon implementation since it would bypass the 1 day limit, but it wouldn't help with race conditions, though. Only a proper rollover would, and that is more likely to compromise deniability (and also, be more difficult to implement. I wonder which implementations handle the case where an author has multiple signing keys)

**Comment by kaniini** [comment]
@ThibG actually it is a serious problem because it creates a cryptographic relationship between the two keys.  a forensic analyst will have a lot of fun with that.

Also relays do NOT need LDS, if you relay metadata about the posts instead, as the Pleroma implementation does.

**Comment by kaniini** [comment]
> I think we should only LDS-sign `Delete` and `Create` for public and unlisted toots, and nothing else.

This would be a significant improvement but rotating keys at some point after a `Delete` would still be a best practice.

**Comment by kaniini** [comment]
Regarding determining if an instance lost data or not, we could probably signal somehow in the actor object that it isn't brand new.  I'm not sure what the semantics would be, but it seems possible to me.

**Comment by ThibG** [comment]
Relays don't need LDS, but not using LDS means every participant will have to fetch each relayed object to validate it, doesn't it? That would be highly inefficient.

**Comment by ThibG** [comment]
> @ThibG actually it is a serious problem because it creates a cryptographic relationship between the two keys. a forensic analyst will have a lot of fun with that.

I am sorry, but I still can't understand how signing the `Update` with the old key can be a problem.

> > I think we should only LDS-sign `Delete` and `Create` for public and unlisted toots, and nothing else.
> 
> This would be a significant improvement but rotating keys at some point after a `Delete` would still be a best practice.

I improved the situation a bit (#9659), but yup, I agree we should rotate keys (I'm still trying to figure out how to avoid race conditions though).

**Comment by kaniini** [comment]
> I am sorry, but I still can't understand how signing the Update with the old key can be a problem.

The Update contains the new key material, which means the old key is signing the new key material.  This creates a cryptographic relationship between both keys which negatively impacts deniability.

You are looking at this from simply invalidating signatures on objects, that's an important part of it, but a forensic analyst can say in court something like: "well, `key A` signed an `Update` message containing `key B`, so everything signed by `key A` is from the same person who possesses `key B`."  At that point the digital signatures from `key A` are accepted as digital evidence against you.  Not good for an activist, and activists are largely the people who look toward fediverse technologies.

**Comment by ThibG** [comment]
But your defense relies on claiming that `key A` is not yours, right? In that scenario, `key A` could *also* have signed the `Update`, because anyone could sign anyone's `Update` with their own key. I'm not sure how that's more damning evidence than the signature on the message itself.
(Now if `key B` would have signed `key A`, that would be something else…)

**Comment by kaniini** [comment]
`key A` signing `key B` is still pretty damning.  the point is to avoid *any* cryptographic relationship between the keys.

**Comment by Gargron** [comment]
Keys are comparatively large pieces of text and constantly updating every user's row in the accounts table sounds like a very, very bad idea to me.

**Comment by ThibG** [comment]
I'm not sure what part of the scheme you're opposing to exactly. If everyone would implement it as hinted there, this would be at most one change per account per hour, and much less in practice (only if the account deleted a toot, and only after 1h of subsequent inactivity). If you're worried about the fetching part, it's already possible to flood an instance with proper `Update` activities changing the key each time.

**Comment by Noiwex** [comment]
I agree this should be implemented to protect user privacy from any possible oppression, chasing, persecution and repression.
