### ISSUE TITLE
View a single remote timeline

### ISSUE THREAD

**Issue by sparr** [tootsuite/mastodon#9678]
### Pitch

I would like to be able to view the "local timeline" of a single federated instance, as if I was on that instance. This would effectively be the federated timeline with a filter to only show toots from a specific instance.

### Motivation

I have my account on a large general purpose instance instead of a niche instance for reasons of reliability/uptime. Doing this costs me the ability to view (within my normal mastodon interface) the local timeline on a niche instance that might be more interesting to me. I know that I can load up the web interface to another instance and see its public timeline (usually), but that makes it annoying to boost/reply, and takes away features of my normal interface such as filtering.

**Comment by Cassolotl** [comment]
I think this is a duplicate of *[FEATURE] Follow public local timelines from other instances #6942*?

**Comment by sparr** [comment]
"Follow" in that description seems misleading since that word already means something specific.

**Comment by sparr** [comment]
But you're right, it's a dupe of the discussion there.
