### ISSUE TITLE
Make Docker tags match the project releases

### ISSUE THREAD

**Issue by EliotBerriot** [tootsuite/mastodon#968]
At the moment, the docker [image tags](https://hub.docker.com/r/gargron/mastodon/tags/) are as follows: latest, skylight, development.

I think a better setup would be to include tags that match the project versioning scheme, meaning you can install a specific version of Mastodon: (`docker run mastodon:4.13`) and easily upgrade to a given version by editing the image tag in your docker-compose file.

Pulling latest image without knowing to which release it match can be dangerous for various reason, for example if a given release needs additional commands to be run for the upgrade.

**Comment by blakebarnett** [comment]
This is needed to play nicely with Kubernetes deployments to allow for rolling-updates and rollbacks.

**Comment by EliotBerriot** [comment]
It seems @Gargron can [hear us](https://hub.docker.com/r/gargron/mastodon/tags/) even if he has not enough time to answer us.

**Comment by ashfurrow** [comment]
It looks like this has been resolved, then?

**Comment by ashfurrow** [comment]
Cool, thanks for the 👍 I'm going to close this but please re-open if it's not resolved, and feel free to open new issues with other suggestions or requests. Thanks!
