### ISSUE TITLE
Add "I Don't Want To See Or Be Seen By Straight People" Option

### ISSUE THREAD

**Issue by neonpixii** [tootsuite/mastodon#9692]
### Pitch

This is already a feature on some of the biggest social media websites in the world, including OK Cupid. It's an incredibly useful feature that prevents straight people from being able to send any interaction to me at all and when a social media website has this as a feature its the first thing i enable. It simply prevents straight people from being able to see your online presence at all, and likewise prevents me as a gay person from being able to see straight people's online presence.

### Motivation

I do not want to be reminded of straight people's existence. I do not want to see straight people. I do not want to interact with straight people. I don't want straight people to see, favorite, boost, or reply to my posts.

I am dead serious, this is a real feature that real social networks have, and i really want it on Mastodon too.

**Comment by trwnh** [comment]
One major limitation is that this would require users to list a GSR orientation, preference, or identity, within a normalized field. That might be normal for a network whose primary purpose is to find a partner, but Mastodon doesn't currently have a field for that, and if it did, it would have to be opt-in. Given the wide range of potential categories, perhaps a simple "I am not straight" checkbox would work?

**Comment by neonpixii** [comment]
trwnh that would honestly be the best possible way to implement it; as a "not straight" checkbox.

**Comment by Gargron** [comment]
I believe that software should know as little as possible about the identity of its user. Mastodon only asks for username and e-mail right now, and does not prompt to give away any other personal information like sexuality, date of birth, ethnicity, religion, height, weight, or location. The profile metadata area offers an opportunity to input any text that you want, which some choose to use for gender, pronouns, or location, but it is not machine-readable and not filterable.

I would not feel comfortable collecting and storing data about who is straight and who is not, given that it is still dangerous information in many places in the world.

As for straight people not finding your profile and not interacting with you, Mastodon does not force you to expose your profile: account search only reveals your account when someone is typing your username; participation in the public timelines is optional, participation in the profile directory is opt-in. If you wish to build a social graph devoid of straight people, you can already do that.

At last, Mastodon is not a dating app, so comparing features with OK Cupid is not appropriate.
