### ISSUE TITLE
Links in Report dialog are white-on-white text

### ISSUE THREAD

**Issue by MFAshby** [tootsuite/mastodon#9697]
Re-opening https://github.com/tootsuite/mastodon/issues/7431, because it seems not fixed in some circumstances:
Steps to reproduce.
Find a user who made a report with a Cover Word or a user on a Pleroma instance. 
Report the user.
### Expected behaviour
Report dialog shows the posts with a readable contrast.

### Actual behaviour
Post content is shown white-on-white
![image](https://user-images.githubusercontent.com/1760515/50617833-0e337b80-0ee7-11e9-9a91-9988620f7043.png)

### Specifications
Mastodon version:
Unfortunately don't know, suggestions how to check this on someone else's instance are welcome.

### OS, Browser:
Ubuntu 18.10, Firefox

**Comment by Gargron** [comment]
Reason: Pleroma doesn't wrap text in `<p>` tags, our CSS adjusts the color of the `<p>` tags. Solution: Make it adjust all text.

**Comment by MFAshby** [comment]
fab thanks
