### ISSUE TITLE
Optionally auto-block Pleroma instances

### ISSUE THREAD

**Issue by kaniini** [tootsuite/mastodon#9708]
### Pitch

Pleroma instances identify themselves as Pleroma instances via the `/api/v1/instance` endpoint.  

Since there is so much rampant concern about Pleroma being an evil software written by nazis, it may be best to provide the ability to automatically detect and block those instances.

### Motivation

The main beneficiary of this feature would the hysterical fediverse admin who buys into FUD instead of actual facts.  However, that hysteria leads to long discourses about things that aren't even aligned with reality, stressing out the entire fediverse.

The ability for those admins who do not want to take the perceived risk of federating with non-Mastodon software would be benefited by the ability to automatically not federate with those instances.

**Comment by kaniini** [comment]
(by the way this is an entirely serious proposal)

**Comment by m4sk1n** [comment]
Why would one implement feature requested by nazi?

**Comment by kaniini** [comment]
well, Pleroma is not really implemented by nazis ;)

but since Mastodon is marketed as being "nazi-free", having a button to remove federation with software allegedly written by nazis would be in line with the project ethos would it not?

**Comment by m4sk1n** [comment]
It only makes sense if Pleroma is really developed by nazis and I think that’s just a belief of small minority of Mastodon users (including instances admins) and none of Mastodon developers think like this…

**Comment by Cassolotl** [comment]
Plus there are Mastodon instances that are run by nazis too, right? :D

**Comment by Gargron** [comment]
The Mastodon software has not expressed any moral judgements about any other ActivityPub implementations and neither have I. This is the wrong place to vent your frustrations.

**Comment by kaniini** [comment]
I disagree.  There is strong value in Mastodon admins being able to choose what software to federate with.  Even if the concerns are unfounded and baseless, it is better to let the admin make their own decision on whether or not they wish to federate with non-Mastodon software, isn't it?

**Comment by Gargron** [comment]
Admins can already make decisions about who not to federate with, based on multiple factors including but not limited to the software used. Taken at face value, your suggestion is completely impractical, you only have to think about the User-Agent header to see why.
