### ISSUE TITLE
Is their a way to get old settings before starting over? I died Jul 2018 after trying to upgrade to 2.5

### ISSUE THREAD

**Issue by WNYmathGuy** [tootsuite/mastodon#9737]
Somewhere around July last year I did my first upgrade after running an instance for about 3 months. My instance never worked again and because I had "_bigger fish to fry_" I let the project go dormant. 

I didn't have a lot to lose in this project because I only had one random user who joined about two weeks before it died, and the only toots were mine. However, I had so many settings worked out to my satisfaction that it hurts me to think of starting from square one. I had my ToS and Privacy Policy in place, I did work on the look and feel, so it was all set for its purpose but it was still too early for me to attract users.

**Is there a way to dig in my PostGre data and extract the ToS and PP the way I lovingly tweaked them to render right? Can I pull out the toots I wrote as text and then reinsert them after a wipe and reinstall? Can I extract and reinsert the record for my one user so they can log in without trouble?**

I believe I did the standalone install method in April when I first launched my instance because I use Apache. My server is Ubuntu 16.04 LTS.

### Expected behavior

Mastodon should have worked after the upgrade.

### Actual behavior

It never worked again. No logins, no login screen. Just one shitty message of "We're sorry, but something went wrong on our end.".

### Steps to reproduce the problem

Upgrade from (probably) 1.5 to 2.5

### Specifications

I don't know what a commit hash of Mastodon is.

**Comment by Gargron** [comment]
Is there any reason why you can't use the same Postgres database for your new Mastodon installation? It sounds like you want to port basically all data over.

> Just one shitty message of "We're sorry, but something went wrong on our end.".

Error messages displayed to end-users do not contain sensitive & dangerous information about what went wrong exactly. When you see an error message, you can open the logs for the Mastodon web process and see a full and detailed stacktrace: `journalctl -u mastodon-web`

I will be able to tell you what went wrong in the upgrade once I have a stacktrace from you.

**Comment by WNYmathGuy** [comment]
@Gargron Please note that I'm only a semi-skilled administrator and live out-of-the-loop of tech jargon.
I'll try my best to keep up, but it's safe for you to assume I know nearly nothing. :wink: 

> Is there any reason why you can't use the same Postgres database for your new Mastodon installation? It sounds like you want to port basically all data over.

Ignorance, and no idea where to find answers. It's been so long that I don't think I remember the password I first set things up with. The whole operation here is me though. My server is physically at my IRL place and I'm the only admin. I was afraid that the database was possibly wrong because things didn't work after the upgrade. I ran the command as per the instructions to upgrade the database to that version of Mastodon. I have no idea how to test if it's all good. I assumed that without the right Mastodon Admin UserID/Password combo the database would be useless to any reinstall attempt. I also (_because I don't know of any authoritative uninstall instructions_) assumed that deleting the wrong parts of the Mastodon system to attempt a clean install might make things worse.

> Error messages displayed to end-users do not contain sensitive & dangerous information about what went wrong exactly. When you see an error message, you can open the logs for the Mastodon web process and see a full and detailed stacktrace: `journalctl -u mastodon-web` 

```
someadmin@somehost:~$ journalctl -u mastodon-web
-- No entries --
```

Is a solution to my problem deleting all the files in the live folder and doing a fresh install of 2.7? 
BTW, before making this issue, I set a new password for my Mastodon admin user in PG and on Ubuntu. Sometimes administrating software feels like ["Free Soloing"](https://duckduckgo.com/?q=Free+Soloing&t=canonical&iax=images&ia=images&iaf=size%3Aimagesize-wallpaper)!

**Comment by Gargron** [comment]
You said you were going with Friendica in another thread so closing
