### ISSUE TITLE
Problem when preload assets

### ISSUE THREAD

**Issue by apardo** [tootsuite/mastodon#9746]
I see this warnings in the browser console:

The resource https://social.ingobernable.net/packs/features/getting_started-3af0d78214daf67e45a7.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

How I can solve that?

Thanks

**Comment by Gargron** [comment]
It is not a problem. It is just a warning.

**Comment by apardo** [comment]
Ok
