### ISSUE TITLE
Rate limits for posting are too high

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#9766]
### Pitch

Spambots are a problem with any open network where there is no cost of transmission. Consider this example https://mastodon.social/api/v1/accounts/682257 where a spambot has posted almost 4000 times in just 6 hours. A real human obviously cannot post that many statuses in that short of a time frame.

My pitch is to introduce a stricter rate limit in order to prevent flooding of local timelines or wasting server resources. As a service, Tumblr imposes a 250-posts-per-day limit on all users; while this number is too low for some humans who would frequently encounter it, a slightly higher limit would be fine -- perhaps 500?

### Motivation

First line of defense against spam, and to prevent/mitigate situations like these: https://firebird.zone/objects/5c10de12-0073-4ff2-8a56-be13c23ebd68

**Comment by MirceaKitsune** [comment]
Making it daily sounds a bit extreme as it can leave people locked out for too long, I'd vote against that. What I fully agree with is a momentary limit in seconds (eg: 1 post per 10 seconds), and on top of that there could be a secondary hourly limit too (eg: 50 posts per 1 hour). Obviously they should be customizable settings for instance admins to tweak to their needs.

**Comment by trwnh** [comment]
I don't see a daily limit being a problem as long as it's sufficiently high enough. I think seconds is too low of a time window to police, but hour and day are fine. Hourly limits still aren't ideal, because some people might post a lot within the same hour and then be locked out until next hour (at which point they might have to stop using Mastodon for the day).

A daily limit has better precedent, as well; when Twitter first rolled out its API rate limits, they were for windows of 15 minutes, and some larger limits for 60 minutes. Many users frequently ran into these limits because the average session might only be 15 minutes (at that point in time), but it included several refresh requests.

**Comment by MirceaKitsune** [comment]
A limit in seconds would act as flood protection to prevent abuse of server resources, while also useful to identify if the person is a bot or not; A malicious user could write a script that makes 100 posts per second which can be used to crash a server similarly to a DDOS attack. Meanwhile a real person can't possibly click the boost / fave icon faster than 0.25 seconds in between, nor create a meaningful written post less than every 10 seconds.

The reason I'm concerned about a daily limit is that as the network grows, some people might become very active. It's likely that some will reach a 250 posts per day cap. What will they do then if they wish to interact with someone? Having to wait until the next day might effectively block them from communicating with others, to me it feels more like a temporary ban.

An hourly limit is more gentle in that regard: If you've made a mistake and posted too much, you can more easily have patience for an hour to let it pass.

**Comment by otrapersona** [comment]
this shouldn't be a hardcoded setting btw, admins should be able to tweak it

**Comment by skryking** [comment]
@otrapersona if it's confugurable doesn't that open it up for a spammer to setup their own instance?

**Comment by serpico** [comment]
here's an example of what looks like spam to me

https://mastodon.social/tags/movie

the page is basically unusable

**Comment by Gargron** [comment]
Yeah but that bot seems to post every 30 min, that's not overly frequent. It's just that nobody else uses the #movie hashtag at all.

**Comment by MirceaKitsune** [comment]
I don't see the point in filtering out bots, though would approve of it if it's an option on the page. Remember that some bots can be slower than people: You might have a real person creating 5 posts with a given tag per day, and a bot making only one post with that tag daily.

**Comment by serpico** [comment]
@MirceaKitsune  Yeah sorry I wasn't clear enough as you said I meant as an option like a check box or something...

**Comment by trwnh** [comment]
#13172 addresses this
