### ISSUE TITLE
Invite-Only mode for registrations

### ISSUE THREAD

**Issue by thebigbad** [tootsuite/mastodon#977]
Currently, I can either open or close registration on my mastodon instance. When registration is open, it looks like I can blacklist certain domains from signing up, but can't otherwise limit registration. I'd like to be able to close registrations except for a whitelist of email addresses, to allow my family members to register without letting randos register.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mkody** [comment]
Either a whitelist of emails, or a way for admins of an instance to share "invite links".
I saw we can use a whitelist of _domains_ (in emails), but this still shows the signup form instead of displaying my custom message.

**Comment by whiskeyneon** [comment]
This feature would be very beneficial.

**Comment by loganmhb** [comment]
I'm interested in working on this - it's something I'd like for my own instance. My preliminary inclination, without having looked at the code much yet, is to go the invite-link route as it seems most flexible. It could also be extended in the future to optionally allow non-admins to issue invites as well, which is something I'd personally like. 

I can start looking into that approach. Would love feedback from others on how that sounds or whether other features would be useful.

**Comment by whiskeyneon** [comment]
@loganmhb That's the exact functionality that I am wanting!

**Comment by wolfteeth** [comment]
@loganmhb this is exactly what I want, too.

**Comment by halkeye** [comment]
@loganmhb have you started this? I intended to work on it this week but didn't want to double up efforts.

I was/am going to add https://github.com/scambra/devise_invitable and add a option to enable it, and ui for users to trigger it.

**Comment by dregin** [comment]
@halkeye - If you're working on this from a fork, I'd be happy to test on my instance.

**Comment by loganmhb** [comment]
@halkeye I haven't really started this so if you have a plan go for it!

**Comment by jasonrhodes** [comment]
I was looking into how to build something like this but I'm totally unfamiliar with devise so I was pretty lost -- @halkeye that sounds like the perfect tool

/me follows along with interest

**Comment by halkeye** [comment]
When i have something unstyled working i'll start a PR to get feedback

**Comment by halkeye** [comment]
Okay, the more I look into this the less I like devise_invitable.

It currently would need you to specify the username and email for every invite., plus it makes the user table a lot bigger.

Its going to take longer, but I think i'm going to write something from scratch

**Comment by randulo** [comment]
I know this is a good idea, because I just thought of it... one month after everyone else :)

**Comment by schnellschnell** [comment]
just for making this issue better searchable: "by invitation only"

**Comment by thedeadparrot** [comment]
I am interested in this feature! And while it would be great to have a more robust solution, there is a simpler stopgap solution that toot.cafe is using that maybe a good initial step in the meantime.

https://github.com/tootcafe/mastodon/pull/9
