### ISSUE TITLE
Support XMPP URI in Mastodon interface

### ISSUE THREAD

**Issue by rscmbbng** [tootsuite/mastodon#9776]
Some users put XMPP URI in their profiles or toots it would be nice if Mastodon can make these links clickable.

`xmpp:user@instance.tld`
or
`xmpp://user@instance.tld`

See : https://tools.ietf.org/html/rfc5122

The link can be an xmpp URI to join a chat room too.

`xmpp:xmpp-sprint@chat.cluxia.eu?join`

### Expected behaviour

XMPP URIs are clickable allowing people open new chats on their system's XMPP client.

### Actual behaviour

XMPP URIs appear as normal text and are not clickable or identifiable as an URI

### Steps to reproduce the problem

Toot the following:
`xmpp:xmpp-sprint@chat.cluxia.eu?join`

**Comment by trwnh** [comment]
Correct me if I'm wrong, but isn't this handled by the browser/OS and not by websites? https://wiki.xmpp.org/web/XMPP_URIs

**Comment by nightpool** [comment]
@trwnh the question is about autolinking

**Comment by Neustradamus** [comment]
@trwnh no, soft/lib need to add support.

Example:
- MediaWiki: https://github.com/wikimedia/mediawiki/blob/master/includes/DefaultSettings.php#L4222

I have added in html-pipeline:
- https://github.com/jch/html-pipeline

**Comment by Ppjet6** [comment]
Hey! It would be great to have such a feature. I often find myself having to workaround it. Would a patch be considered?

**Comment by Perflyst** [comment]
Would be nice if xmpp uris are also supported in profile metadata

**Comment by Neustradamus** [comment]
Thanks a lot <3
