### ISSUE TITLE
Show in moderation/admin interface when a user signed up

### ISSUE THREAD

**Issue by rixx** [tootsuite/mastodon#9784]
### Pitch

The administrator/moderator view on a user at ``/admin/accounts/<number>`` doesn't tell me when that user signed up on my instance (only talking about local users here). Adding this as another row just below "most recent activity" would be very helpful.

### Motivation

Especially when issues get reported to me as a moderator, it's helpful to know how long the user has been on the instance – if they're new, explaining the rules/workings again might make sense, whereas this would read as condescending on a long-time user.

**Comment by rixx** [comment]
You mean, in master, just not released? Because it isn't among the visible attributes:
![screenshot_2019-01-11 rixx - chaos social](https://user-images.githubusercontent.com/2657547/51026672-59a4f400-158f-11e9-9073-39edc5f6cd75.png)

**Comment by Gargron** [comment]
It's released in 2.7.0rc1, at least. But yes, it's already done, so there is nothing for me to do here.
