### ISSUE TITLE
Show privacy status icons on posts

### ISSUE THREAD

**Issue by MirceaKitsune** [tootsuite/mastodon#9788]
Posts on Mastodon can have multiple privacy modes: Public, Unlisted, Followers-only, Direct. For convenience it would be ideal to give each post an icon indicating its status. It often helps the user to know when something they're seeing is visible to others, be it their own post or someone else's.

Twitter does not have this feature. However Facebook does: In its case privacy icons always appear on a post, allowing you to know its exact visibility level at any time.

Here is a mockup of how this would most likely look. See the little icons left of "5h".

![screenshot_20190111_215539](https://user-images.githubusercontent.com/825418/51058575-ed0f1100-15f1-11e9-93b3-19cf2601951b.png)

**Comment by trwnh** [comment]
Duplicate of #1564

**Comment by MirceaKitsune** [comment]
This has since been resolved: The icon now appears on all toots left of their post time, showing a globe for public toots and a lock for unlisted / private ones just as intended. Thanks for fixing.
