### ISSUE TITLE
Ability to notify users of announcements or planned downtime

### ISSUE THREAD

**Issue by alexgleason** [tootsuite/mastodon#980]
In my head I'm imagining that thin yellow or red bar you sometimes see at the top of a site which informs users that they should expect downtime during certain periods. But there's probably more ways to do it.

Ideally you should never go down. But for instances with less resources it may not be easily avoidable when performing some actions like increasing the size of the server or doing a migration.

**Comment by RaitoBezarius** [comment]
Possible duplicate of #882

**Comment by duckinator** [comment]
yeah, my suggestion in #882 is basically this.

**Comment by alexgleason** [comment]
Cool, closing this. Thanks!
