### ISSUE TITLE
SAML/SSO broken in MacOS Mojave Safari / iOS 12 due to SameSite cookie flag

### ISSUE THREAD

**Issue by pduldig-at-tw** [tootsuite/mastodon#9812]
On troubleshooting issues with Safari on Mojave and ios12 Toot clients, we discovered that our SSO (SAML) authenticated server would not allow users to log in.
This issue appeared to be with the way that MacOS / iOS handles the SameSite flag with POSTS in the SP SAML flow. I believe the root issue in webkit to be: https://bugs.webkit.org/show_bug.cgi?id=188165

### Expected behaviour

User can authenticate via SAML iDP, and be redirected to an active authenticated session

### Actual behaviour

Safari does not send the _mastodon_session or _session_id cookie in the post-SSO authenticated request for GET /    -- an anonymous request

### Steps to reproduce the problem

* Log in to a SSO IdP authenticated mastodon instance via SP initiated flow using Safari on MacOS Mojave, or any toot client in iOS12
* Be greeted with a unauthenticated session
* attempt to log in again, be redirected via SAML dance
* Be greeted with a unauthenticated session

### Specifications

I was able to verify my theory that this was caused by the SameSite flag on the cookie by by tracing network connections. I set a rewrite rule in burpsuite to change HTTP responses to drop the "SameSite=Lax" flag from the session / mastodon cookie.
The rewritten requests thus set the cookies without SameSite, and the browser submitted them to the first GET / request post Auth (ie: working as expected).

I also tried rewriting the cookie to use "SameSite=Strict" mode, but had the same failure as Lax. There was no "None" mode that the browser would accept (it dropped the entire cookie, was not written to cookie store).

This is a major breaker for us; One solution would be for us to rewrite responses on the fly via a reverse proxy, but it would be better if this was resolved from within the application itself. I appreciate that removing the SameSite flag would decrease the security posture across other browsers.

**Comment by pduldig-at-tw** [comment]
I believe this bug was introduced in change #8626

**Comment by moritzheiber** [comment]
cc @sorin-davidoi

**Comment by moritzheiber** [comment]
@sorin-davidoi Do you want to submit the PR or should somebody else?

**Comment by sorin-davidoi** [comment]
Don't have the stack setup right now, would be nice if someone else could do it.

**Comment by moritzheiber** [comment]
I've created a PR for it
