### ISSUE TITLE
Visitors cannot see or follow profiles on my instance (everything else working normally)

### ISSUE THREAD

**Issue by indie** [tootsuite/mastodon#9829]
### Expected behaviour

Visitors can view and follow users on my instance without logging in. 

### Actual behaviour

![user_show_broken](https://user-images.githubusercontent.com/50558/51316464-9d718080-1a09-11e9-8017-3c2dad36e989.png)

### Steps to reproduce the problem

I **think** this may have something to do with my upgrade from `2.6.3` to `2.6.5`?  There is literally nothing in the logs that gives me a hint as to why this is happening.  The only clue is this on PGHero: 
![pghero](https://user-images.githubusercontent.com/50558/51316586-f0e3ce80-1a09-11e9-8c18-aa24cf83c553.png)

**Comment by indie** [comment]
P.S.  All my code is on my Mastodon the fork at [indie/mastodon](https://github.com/indie/mastodon)

**Comment by Gargron** [comment]
https://docs.joinmastodon.org/administration/troubleshooting/

1. Check the logs for error messages
2. It's probably missing precompiled assets

**Comment by indie** [comment]
There was a clash where I got some new code that was on the 2.7 release before i actually upgraded to it.  I did have a chance to upgrade tonight, and it works.  Thanks Eug!
