### ISSUE TITLE
Announces not addressed to as:Public still considered public

### ISSUE THREAD

**Issue by kaniini** [tootsuite/mastodon#9838]
### Expected behaviour

The announce (boost) should only be visible to the addressee(s).

### Actual behaviour

The announce (boost) is visible to the public.

### Steps to reproduce the problem

Send an object of this construction to Mastodon:

```
{
    "to": ["https://example.com/users/kaniini/followers"],
    "cc": [],
    "audience": ["https://example.com/users/kaniini/followers"],
    "type": "Announce",
    "object": "https://example.com/objects/1234",
    "id": "https://example.com/activities/5678"
}
```

The announce (boost) activity will be publicly visible.

### Specifications

Found in Mastodon 2.6.5

ActivityPub section 7.1 says:

> An activity is delivered to its targets (which are actors) by first looking up the targets' inboxes and then posting the activity to those inboxes. Targets for delivery are determined by checking the ActivityStreams audience targeting; namely, the to, bto, cc, bcc, and audience fields of the activity. 

ActivityPub section 7.11 says:

> Upon receipt of an Announce activity in an inbox, a server SHOULD increment the object's count of shares by adding the received activity to the shares collection if this collection is present.

Thusly, we can conclude that shares not addressed to `as:Public` shouldn't be visible to `as:Public` (because there is no statement imposing special consideration for this activity).  Also, since that requirement is a SHOULD instead of a MUST, it may make sense not to increment the object share counter either (since the share is private), but that one is up for discussion.

**Comment by trwnh** [comment]
Related: #9577
