### ISSUE TITLE
How can I change my username or delete account?

### ISSUE THREAD

**Issue by somepage** [tootsuite/mastodon#984]

**Comment by RaitoBezarius** [comment]
That's impossible for the moment.
ref to #109 #177

**Comment by saper** [comment]
You can delete your account now (since https://github.com/tootsuite/mastodon/pull/3728)

**Comment by JBaczuk** [comment]
Is there a way to change your username?

**Comment by Gargron** [comment]
From settings.

**Comment by bjorndotwork** [comment]
Where? I'm looking in Settings. I don't see it.

**Comment by Gargron** [comment]
The Security page, together with your password and e-mail address settings.

**Comment by bjorndotwork** [comment]
Found it. Thanks!

**Comment by bjorndotwork** [comment]
Can you speak to what this user action actually *does* across federated sites?

**Comment by Gargron** [comment]
Send out a Delete->Actor activity to all known inboxes, and removes all data except a reserved username locally.

**Comment by peeyushsrj** [comment]
How do I change my username?
