### ISSUE TITLE
new hashtag page's design strange on some devices

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#9845]
I like the design of a new hashtag page.
However, in some environments such as Essential Phone (Android 9, Chrome) it seems strange.
There is no problem with my PC and iPhone.

### Actual behaviour

It looks like the next image.
https://taruntarun.net/media_files/Mastodon/media_attachments/files/000/311/018/original/ca1d8806b6de0378.png

### Steps to reproduce the problem

1. Open hashtag page with the Chrome and open DevTools.
2. Toggle device toolbar to ON.
3. Click this point ( Mobile L - 425px )
<img width="464" alt="_2019-01-18_9_48_11" src="https://user-images.githubusercontent.com/766076/51358485-ca578d80-1b06-11e9-8872-f34a8bdf72e7.png">

( Perhaps it may be necessary to reload after this steps. )
### Specifications

Equivalent to Mastodon master 69f782b54d035789a6386ed979940dd9719af1a1

**Comment by m4sk1n** [comment]
at least it’s better than it was before (pixel 2 xl, android 9, chrome, on every instance)
[screenshot](https://user-images.githubusercontent.com/21127288/51394082-c09b4d80-1b39-11e9-8683-cadf5d63d40b.png)
