### ISSUE TITLE
Authenticated object fetches

### ISSUE THREAD

**Issue by kaniini** [tootsuite/mastodon#9849]
### Pitch

ActivityPub's dirty secret is that it has numerous ways objects can be leaked in ways not intended by the actors which created them.

By requiring authentication for object fetches, the server which created them can fully enforce access controls on the objects (blocking, awoo.space objects leaking, etc.).

### Motivation

Users expect to have full control of how their data is shared with other fediverse nodes, and how their data flows through the network in general.  While Mastodon does a reasonable job at imposing these controls, allowing unauthenticated object fetches causes the object to leak (this is not a defect specific to Mastodon, all AP implementations have this defect).

It would be nice to come together and establish a set of common semantics that would allow for object fetches to become authenticated.  This would be helpful for numerous reasons, including topology knowledge (we can deduce what instances have a copy of a given object, for example).

Anyway, I'm open to discussing this either in W3C space or in Litepub space.  Whatever you want to do.

**Comment by kazimuth** [comment]
Is there any motion forward on this? It seems like a very important problem to solve.

**Comment by nightpool** [comment]
Sorry, didn't see this at time, looks like discussion has moved to https://github.com/w3c/activitypub/issues/339, let's keep it there. I don't think mastodon is going to ever restrict fetching Public objects, and as far as I know we already properly authenticate object fetches for non-public posts.

Is there anything you meant to cover in this issue that's not covered in your as:Authenticated proposal?

**Comment by kaniini** [comment]
I think restricting fetches for as:Authenticated posts solves this issue as well.

**Comment by cwebber** [comment]
I'll note that I'm -1 on authenticated object fetches.  Authentication is the wrong way to do authorization.  However, I do believe that we need authorized object fetches, and yes, that means ocaps (authentication *as* authorization would be pointing a big ol gun footward)

**Comment by Gargron** [comment]
Oh hey this can be closed now (#11269)
