### ISSUE TITLE
possibility to delete received direct messages

### ISSUE THREAD

**Issue by schiessle** [tootsuite/mastodon#9860]
Sometimes I receive really stupid direct messages. These then stay in my direct message column for ever and for a really long time on the first page as I use direct messages only rarely.

I think it would be a nice enhancement if i could delete direct messages from my "direct message"-column. Direct messages are something more personal, 1-to-1, like email, messengers. Think it would be good if people could manage them a little bit more like that.

**Comment by Gargron** [comment]
It is actually possible to delete DMs from the conversations API (does not delete the status, but its listing). However, the option is not exposed in the current web UI.
