### ISSUE TITLE
Add option to manually load the new toots

### ISSUE THREAD

**Issue by MyNameIsTroll** [tootsuite/mastodon#9863]
It would be nice to have a setting in #mastodon to allow the user to manually load the new toots into the "home" and "global" threads, via an action on his part like a click.
I will suggest that this option be added to the column options for faster access.
Here is an example of a proposal:
![mastodon_feature](https://user-images.githubusercontent.com/31790025/51428236-20a4f900-1bf9-11e9-9b9e-7df763996210.png)

The fact that threads are constantly updated tends to capture attention and in "certain circumstances" this can be embarrassing.
Especially when we are answering a toot or when our attention tries to focus on another task for example.

Sorry about my English, which is not great ^^

**Comment by trwnh** [comment]
Related: #7913, #8518

**Comment by MyNameIsTroll** [comment]
Sorry, I had looked, but I hadn't found anything, sorry for the duplicate.
