### ISSUE TITLE
Locked Out of Two-Factor Authentication

### ISSUE THREAD

**Issue by tjr8787** [tootsuite/mastodon#987]
Somehow I seem to have screwed up when setting up Two-Factor Authentication... I don't receive a login token when attempting to sign in, so it seems I'm permanently locked out of my account. Any suggestions? 

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jeepfromoil** [comment]
This issue https://github.com/tootsuite/mastodon/issues/563 suggests to provide backup codes to avoid such situation.

**Comment by medecau** [comment]
I'm in a similar situation.

I believe I may have clicked the TF(two factor) button but did not insert the codes into the security app.

I suggest that in order to activate TF the user should prove it is able to provide the right TF code.
