### ISSUE TITLE
"List this account on the directory" not saving

### ISSUE THREAD

**Issue by ashleyhull-versent** [tootsuite/mastodon#9870]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/17537000/51437323-e1f26a00-1cf0-11e9-97bb-94cbd87f87c5.png">

### Expected behaviour

Clicking the box and saving should enable directory.

### Actual behaviour

Clicking the box and saving does nothing.

### Steps to reproduce the problem

tick box
tick save
check box
notice box is unticked

### Specifications
v2.7.0-rc3

**Comment by Gargron** [comment]
I cannot reproduce this.

**Comment by ashleyhull-versent** [comment]
Additional information: On my instance aus.social. Everything single other feature is working as expected... tested on chrome/firefox on multiple users.

**Comment by Gargron** [comment]
I don't think Docker would play a role here. Either you have manually merged some code and the Settings::ProfileController is missing a value in the params whitelist, or some browser extension is erasing the checkbox value from the submitted request. I can't imagine what else it could be, because it works for me on localhost and mastodon.social.

**Comment by Gargron** [comment]
Or you haven't run a migration so the column doesn't exist? But I imagine there would be more errors then

**Comment by ashleyhull-versent** [comment]
I've run the migration as of rc3. and I'm building the tagged release with no patches..

I'll keep looking

**Comment by Gargron** [comment]
Have you restarted the Mastodon process after the database migration?

**Comment by ashleyhull-versent** [comment]
I have restarted since this issue - but restarting AGAIN has resolved this issue for my account at least.

I'll close this ticket and reopen if it repeats.
