### ISSUE TITLE
希望追加一个可以快速跳转到特定时间段的功能

### ISSUE THREAD

**Issue by ShimotsukiH** [tootsuite/mastodon#9887]
### Pitch
如图
![default](https://user-images.githubusercontent.com/33424662/51452433-4820d080-1d75-11e9-9ec0-bbd86445525b.gif)

### Motivation
1.方便看自己错过的嘟
2.追踪本地时间线热议话题起源嘟
3.方便统计

**Comment by ykzts** [comment]
请用英文。 Mastodon开发者不仅仅是说中文的人。

**Comment by ShimotsukiH** [comment]
您好 不太会 
与其打蹩脚英文词不达意我想要不直接打中文 有人帮忙翻译当然最好
没的话我也做了gif了 基本能懂

**Comment by ykzts** [comment]
I could not understand what you were requesting, even if you look at your GIF animation.

**Comment by kpmitarai** [comment]
、、

> I could not understand what you were requesting, even if you look at your GIF animation.

He's talking about adding a "jumping to a specific time period" feature, so that users can check the toots they missed.

**Comment by trwnh** [comment]
@ykzts Running through Google Translate, Chinese -> English:
```
希望追加一个可以快速跳转到特定时间段的功能
# Pitch
如图
# Motivation
1.方便看自己错过的嘟
2.追踪本地时间线热议话题起源嘟
3.方便统计
```
=
```
I want to add a function that can quickly jump to a specific time period.
# Pitch
As shown
# Motivation
1.Convenient to see what you missed
2.Tracking the local timeline
3.Convenient statistics
```

**Comment by ShimotsukiH** [comment]
I want to locate any feed between a time range. like the GIF
