### ISSUE TITLE
scheduled status is shown on account TL even it is not yet invoked .

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#9893]
(v2.7.0)

https://mastodon.juggler.jp/@tateisu/101454993930570857 and 
https://mastodon.juggler.jp/@tateisu/101454996524405107 is scheduled status,
but it shown on account TL https://mastodon.juggler.jp/@tateisu  even it is not yet invoked .
shown only account TL, not shown on HTL (incorrect).
 
then https://mastodon.juggler.jp/@tateisu/101455032794258210 was created by scheduled status, this is shown on HTL (correct)

**Comment by mayaeh** [comment]
I was trying the scheduled toot.
When attaching an image, it was posted with an image at the moment of posting.
And only the text was posted at the time of schedule.

The next two are originally one post.
https://edge.taruntarun.net/@maya_eh/101454969572120896
https://edge.taruntarun.net/@maya_eh/101454997389145556

**Comment by tateisu** [comment]
this strange behavior does not happen if without media attachment.
