### ISSUE TITLE
Hashtag columns are not streaming

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#9895]
### Actual behaviour

The streaming connection of the WebUI hashtag columns seems to be disconnected immediately.
Perhaps I think that it has happened since #8904 and related fixes.

I am sorry that the report was delayed.

### Steps to reproduce the problem

1. Click on any hashtag in WebUI and pinned column.
2. Make a post with that hashtag.
![_2019-01-22_11_44_47](https://user-images.githubusercontent.com/766076/51509085-4faaad00-1e3b-11e9-811d-24c40c5b9e48.png)

### Specifications

Mastodon v2.7.0

**Comment by staticsafe** [comment]
The issue appears to be that the web UI is not sending a subscribe verb for the hashtag pinned columns upon page load.

I was able to replicate this:
https://mastodon.zombocloud.com/@staticsafe/101456110767495307

A workaround appears to be to add/remove hashtags to the column which forces a re-subscribe to the timelines.

Behaviour in the mastodon-streaming logs:

`Jan 21 19:03:03 mastodon.zombocloud.com npm[8154]: verb 6002c2e2-0c1b-46e2-b5d4-c100e5c78b8d Ending stream for 1
Jan 21 19:03:03 mastodon.zombocloud.com npm[8154]: verb Unsubscribe timeline:public:local
Jan 21 19:04:02 mastodon.zombocloud.com npm[8154]: verb cf36c75b-6374-417d-89ff-e08d95eaef60 Ending stream for 1
Jan 21 19:04:02 mastodon.zombocloud.com npm[8154]: verb Unsubscribe timeline:1
Jan 21 19:04:02 mastodon.zombocloud.com npm[8154]: verb bc4ea5b1-a173-4533-9f16-3eead6367ac1 Ending stream for 1
Jan 21 19:04:02 mastodon.zombocloud.com npm[8154]: verb Unsubscribe timeline:hashtag:mastoart
Jan 21 19:04:02 mastodon.zombocloud.com npm[8154]: verb a51b6388-5e6b-4a3a-917a-1fdf642b862a Ending stream for 1
Jan 21 19:04:02 mastodon.zombocloud.com npm[8154]: verb Unsubscribe timeline:hashtag:art
Jan 21 19:04:08 mastodon.zombocloud.com npm[8154]: verb 82571438-52b6-486f-8f51-a3678ff48da0 Starting stream from timeline:1 for 1
Jan 21 19:04:08 mastodon.zombocloud.com npm[8154]: verb Subscribe timeline:1
Jan 21 19:04:16 mastodon.zombocloud.com npm[8154]: verb 990852c8-3cdf-490a-bab8-580c1ee2a293 Starting stream from timeline:hashtag:mastoart for 1
Jan 21 19:04:16 mastodon.zombocloud.com npm[8154]: verb Subscribe timeline:hashtag:mastoart
Jan 21 19:04:20 mastodon.zombocloud.com npm[8154]: verb 990852c8-3cdf-490a-bab8-580c1ee2a293 Ending stream for 1
Jan 21 19:04:20 mastodon.zombocloud.com npm[8154]: verb Unsubscribe timeline:hashtag:mastoart
Jan 21 19:04:20 mastodon.zombocloud.com npm[8154]: verb be8c4344-802a-402d-9eb7-7939ba8481f4 Starting stream from timeline:hashtag:mastoart for 1
Jan 21 19:04:20 mastodon.zombocloud.com npm[8154]: verb Subscribe timeline:hashtag:mastoart
Jan 21 19:04:20 mastodon.zombocloud.com npm[8154]: verb 88991ce0-d06b-4e61-b2c0-43fbafade4f9 Starting stream from timeline:hashtag:art for 1
Jan 21 19:04:20 mastodon.zombocloud.com npm[8154]: verb Subscribe timeline:hashtag:art
Jan 21 19:05:14 mastodon.zombocloud.com npm[8154]: verb e58e8bc4-4535-4730-be12-881a11932e50 Starting stream from timeline:public:local for 1
Jan 21 19:05:14 mastodon.zombocloud.com npm[8154]: verb Subscribe timeline:public:local
Jan 21 19:06:34 mastodon.zombocloud.com npm[8154]: verb e58e8bc4-4535-4730-be12-881a11932e50 Ending stream for 1
Jan 21 19:06:34 mastodon.zombocloud.com npm[8154]: verb Unsubscribe timeline:public:local
`

**Comment by mayaeh** [comment]
Thank you very much.
I did not understand that condition.
