### ISSUE TITLE
"internal server error" on "Follow Requests" after upgrade to v2.7.0 

### ISSUE THREAD

**Issue by ingoj** [tootsuite/mastodon#9896]
Followed the upgrade instructions in the release notes for upgrading to v2.7.0, but when going back to the user interface I get "500 internal server error" notifications in the bottom left corner when "Follow Requests" in the tab "Getting started" is visible. 
When clicking on Follow Requests I only get a spinner wheel (not animated). 

I also see some SQL errors in syslog: 

`Jan 21 07:12:30 nerdculture npm[25821]: verb 81afbf3f-79f6-408c-a3b2-b618bd265e71 Ending stream for 1
Jan 21 07:12:30 nerdculture npm[25821]: verb Unsubscribe timeline:1
Jan 21 07:12:30 nerdculture npm[25821]: verb 661fd9e4-f83c-45b5-aee7-eb6219ee4912 Starting stream from timeline:1 for 1
Jan 21 07:12:30 nerdculture npm[25821]: verb Subscribe timeline:1
Jan 21 07:12:31 nerdculture bundle[25754]: [a5093b93-32da-4e7b-8237-f401dc7afb22]
Jan 21 07:12:31 nerdculture bundle[25754]: [a5093b93-32da-4e7b-8237-f401dc7afb22] ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column accounts.statuses_count does not exist
Jan 21 07:12:31 nerdculture bundle[25754]: LINE 1: ...t0_r27, "accounts"."header_remote_url" AS t0_r28, "accounts"...
Jan 21 07:12:31 nerdculture bundle[25754]:                                                              ^
Jan 21 07:12:31 nerdculture bundle[25754]: : SELECT "accounts"."id" AS t0_r0, "accounts"."username" AS t0_r1, "accounts"."domain" AS t0_r2, "accounts"."secret" AS t0_r3, "accounts"."private_key" AS t0_r4, "accounts"."public_key" AS t0_r5, "accounts"."remote_url" AS t0_r6, "accounts"."salmon_url" AS t0_r7, "accounts"."hub_url" AS t0_r8, "accounts"."created_at" AS t0_r9, "accounts"."updated_at" AS t0_r10, "accounts"."note" AS t0_r11, "accounts"."display_name" AS t0_r12, "accounts"."uri" AS t0_r13, "accounts"."url" AS t0_r14, "accounts"."avatar_file_name" AS t0_r15, "accounts"."avatar_content_type" AS t0_r16, "accounts"."avatar_file_size" AS t0_r17, "accounts"."avatar_updated_at" AS t0_r18, "accounts"."header_file_name" AS t0_r19, "accounts"."header_content_type" AS t0_r20, "accounts"."header_file_size" AS t0_r21, "accounts"."header_updated_at" AS t0_r22, "accounts"."avatar_remote_url" AS t0_r23, "accounts"."subscription_expires_at" AS t0_r24, "accounts"."silenced" AS t0_r25, "accounts"."suspended" AS t0_r26, "accounts"."locked" AS t0_r27, "accounts"."header_remote_url" AS t0_r28, "accounts"."statuses_count" AS t0_r29, "accounts"."followers_count" AS t0_r30, "accounts"."following_count" AS t0_r31, "accounts"."last_webfingered_at" AS t0_r32, "accounts"."inbox_url" AS t0_r33, "accounts"."outbox_url" AS t0_r34, "accounts"."shared_inbox_url" AS t0_r35, "accounts"."followers_url" AS t0_r36, "accounts"."protocol" AS t0_r37, "accounts"."memorial" AS t0_r38, "accounts"."moved_to_account_id" AS t0_r39, "accounts"."featured_collection_url" AS t0_r40, "accounts"."fields" AS t0_r41, "accounts"."actor_type" AS t0_r42, "accounts"."discoverable" AS t0_r43, "accounts"."also_known_as" AS t0_r44, "follow_requests"."id" AS t1_r0, "follow_requests"."created_at" AS t1_r1, "follow_requests"."updated_at" AS t1_r2, "follow_requests"."account_id" AS t1_r3, "follow_requests"."target_account_id" AS t1_r4, "follow_requests"."show_reblogs" AS t1_r5, "follow_requests"."uri" AS t1_r6, "account_stats"."id" AS t2_r0, "account_stats"."account_id" AS t2_r1, "account_stats"."statuses_count" AS
Jan 21 07:12:31 nerdculture bundle[25754]:  t2_r2, "account_stats"."following_count" AS t2_r3, "account_stats"."followers_count" AS t2_r4, "account_stats"."created_at" AS t2_r5, "account_stats"."updated_at" AS t2_r6, "account_stats"."last_status_at" AS t2_r7 FROM "accounts" LEFT OUTER JOIN "follow_requests" ON "follow_requests"."account_id" = "accounts"."id" LEFT OUTER JOIN "account_stats" ON "account_stats"."account_id" = "accounts"."id" WHERE "follow_requests"."target_account_id" = $1 AND "accounts"."id" = $2 ORDER BY "follow_requests"."id" DESC):
Jan 21 07:12:31 nerdculture bundle[25754]: [a5093b93-32da-4e7b-8237-f401dc7afb22]
Jan 21 07:12:31 nerdculture bundle[25754]: [a5093b93-32da-4e7b-8237-f401dc7afb22] app/controllers/api/v1/follow_requests_controller.rb:32:in `load_accounts'
Jan 21 07:12:31 nerdculture bundle[25754]: [a5093b93-32da-4e7b-8237-f401dc7afb22] app/controllers/api/v1/follow_requests_controller.rb:10:in `index'`

This is a non-docker installation on Debian stable.

**Comment by ragingscholar** [comment]
We encountered the same error. 

The upgrade note was not clear about this, you need to restart mastodon services after the second migration.

**Comment by ingoj** [comment]
Oh, well, that's a simple fix, indeed... 
I can confirm that restarting the mastodon services after applying the DB migration step did fix this issue for me and the follow requests are displayed again. 

Thanks!
(keeping this issue open until it is fixed by updating the release notes/documentation)

**Comment by Gargron** [comment]
>(keeping this issue open until it is fixed by updating the release notes/documentation)

The release notes for 2.7.0 contain notes for db:migrate and restarting Mastodon. What do you mean?

**Comment by ingoj** [comment]
Ah, now I see: 

>  Precompile the assets:
> 
>     Non-Docker: RAILS_ENV=production bundle exec rails assets:precompile
>     Docker: The assets are already precompiled during the build step
> 
> Restart all Mastodon processes
> Now that the new code is running, we can finish the database migrations. This will run the post-deployment ones:
> 
>     Non-Docker: RAILS_ENV=production bundle exec rails db:migrate
>     Docker: docker-compose run --rm web rails db:migrate
> 
> Restart all Mastodon processes

I'm not sure if that last "Restart all Mastodon processes" were always present there at the end. According to ragingscholar in https://github.com/tootsuite/mastodon/issues/9896#issuecomment-456277186 it was not clear to him as well whether or not to restart after db:migrate a second time. 

Anyway, it is now mentioned, everything fine then and issue closed. Thanks! :)
