### ISSUE TITLE
only first hashtag in profile bio is a link if multiple are separated by "/"

### ISSUE THREAD

**Issue by ThomasAH** [tootsuite/mastodon#9911]
Please support "/" as a separator between hashtags in profile bio.

To add an account to the profile directory I wanted to include the following text in the profile bio:
```Profile directory tags: #GNU/#Linux, #FreeSoftware/#FOSS, #python/#go/#js```

The result was, that only ```#GNU```, ```#FreeSoftware``` and ```#python``` were rendered as links when viewed on e.g. https://mastodon.social/@intevation, while the other tags were rendered as regular text.
Additionally the account did not show up in the profile directory for e.g. ```#Linux```.

**Comment by ThomasAH** [comment]
Toots currently behave in the same way, see e.g. https://mastodon.social/@ThomasAH/101466526664361096 (```#improvement``` is a link, ```#bugfix``` is not)

For comparison: Mastalab and Twidere both render ```#bugfix``` as a link, Tusky does not.

Should I create a separate issue for this? Since I think bio, directory and toots should behave identically, I did not create a new one.

**Comment by marrus-sh** [comment]
This is a duplicate of #1910

**Comment by ThomasAH** [comment]
Thank you, I'll close this one as a duplicate of #1910
