### ISSUE TITLE
[Accessibility] Camel Cased Hashtags Forced Lowercase in Search

### ISSUE THREAD

**Issue by Fidgetcetera** [tootsuite/mastodon#9912]
### Expected behaviour
The casing of a hashtag in a search should match the most common casing of the hashtag. For example, when posting #ThingsDisabledPeopleKnow, and every post with that hashtag is in that format, it should not show up as #thingsdisabledpeopleknow when you search it. 
Related to the closed and fixed #8241 which is about autocomplete, which is why we marked this as a bug.

### Actual behaviour
The hashtags are always set to lowercase in the search and column titles.

### Steps to reproduce the problem
1. Post posts with unique hashtags that have capital letters.
2. Search for the hashtag.
3. Hashtag won't have capital letters.

### Specifications
This happens in mastodon 2.7.0.

**Comment by Fidgetcetera** [comment]
https://sins.center/tags/thingsdisabledpeopleknow An example of this happening on our instance - all posts are ThingsDisabledPeopleKnow but the tag page and search are all lowercase thingsdisabledpeopleknow.

**Comment by Gargron** [comment]
Now hashtag casing is preserved in the database and admins can fix the casing from the admin UI
