### ISSUE TITLE
Change Thumbnail strategy to show whole image

### ISSUE THREAD

**Issue by Matthias84** [tootsuite/mastodon#9916]
### Expected behaviour

Posts containing an image should show the whole image content without needing to show the single article view. This is how other social media platforms present such content.

### Actual behaviour

The image is cropped and only the middle part is visible.
![mastodon cropped thumb](https://user-images.githubusercontent.com/217511/51705713-9d324000-201c-11e9-8e96-bf086d74fd39.png)
![screenshot_2019-01-24 norden social](https://user-images.githubusercontent.com/217511/51705953-57c24280-201d-11e9-98cc-8b9dd114bbf0.png)

### Steps to reproduce the problem

Scroll trough timeline and look for image posts like memes, infographs, ... that usually need an full height to become easy to read.

### Specifications
FF 64
Mastodon 2.7

**Comment by Matthias84** [comment]
It's not necessary  about the text. It's about to  understand just the idea of a media, without clicking the picture when you scroll trough the stream. For example:
![mastodon - thumb cropped prob](https://user-images.githubusercontent.com/217511/52004188-d6f4c200-24c6-11e9-9a46-899b5645c1b4.png)
![mastodon-thumb-full](https://user-images.githubusercontent.com/217511/52004271-04417000-24c7-11e9-9509-7f77612bc212.jpg)
I guess people expect an different behavior. An thumbnail that is similar to fb / twitter / diaspora / ... posts.

**Comment by Saroumane** [comment]
Oh yes please, allow us to display pictures "un croppred" !
Forced cropping ruins the preview of 90% of the pictures I post.
And I look silly when I have to explain to my friends/family that they have to click on each picture.

I understand that some people will prefer cropped pictures, but we need at least a setting to choose how we show them to visitors (especially for non-mastodon users)

**Comment by Matthias84** [comment]
As the post says, this is IMHO an compatibility issue. If there is a good reason to behave different than other platforms it's perfectly fine. But maybe it's just an problem that wasn't considered before ...

**Comment by nclm** [comment]
See also #9582 :)
