### ISSUE TITLE
Make buttons on public sidebar on homepage ("A look inside") functional

### ISSUE THREAD

**Issue by rugk** [tootsuite/mastodon#9922]
Currently, you do have no visible, but no functional interaction buttons on the "A look inside…" panel on the home page.
These are, what I mean:
![buttons](https://user-images.githubusercontent.com/11966684/51790843-c678da80-219a-11e9-9ab7-bc4712b6836b.png)

### Pitch

It would be good, if these could trigger the same "interact with toot" popup as when you view a toot in a "foreign" user profile or a single toot on a public page or so.

### Motivation

* First: Usability.
  It is quite unexpected for me as a Mastodon user now, that these buttons do not work there, as I am now accustomed to the fact, that these work anywhere on all servers.
* Second: I could integrate it [in my add-on](https://addons.mozilla.org/firefox/addon/mastodon-simplified-federation/) (or hopefully it would already work), so the redirect is automatic. This is very seamless, then.

**Comment by Cassolotl** [comment]
Yeah, I've thought this before! And if they aren't made useable they should be removed, maybe? Otherwise it's just misleading and confusing and frustrating.

**Comment by Gargron** [comment]
Definitely agree.
