### ISSUE TITLE
Upgrade to 2.7.0 destroyed all stats, how to re-index?

### ISSUE THREAD

**Issue by skddc** [tootsuite/mastodon#9925]
I checked all Rake tasks as well as `tootctl`, but cannot find out how to manually update the stats. The migration to 2.7.0 (with switch for old postgres) destroyed all our user stats like number of toots, followers, etc..

**Comment by Gargron** [comment]
Open `RAILS_ENV=production bin/rails c` and paste:

```ruby
Account.local.includes(:account_stat).find_each do |a|
  a.account_stat.update(followers_count: a.followers.count, following_count: a.following.count, statuses_count: a.statuses.count)
end
```

**Comment by skddc** [comment]
Perfect, thanks!
