### ISSUE TITLE
When signed in, /auth/sign_in redirects user incorrectly

### ISSUE THREAD

**Issue by brad2014** [tootsuite/mastodon#994]
When already signed in, the login page, /auth/sign_in, redirects the user incorrectly to an internal REST endpoint.  I think it should redirect to the /web/getting-started page (just as / does).

### To reproduce:
- log out
- Go to https://mastodon.social/auth/sign_in (e.g. with a bookmark)
- log in
- Go to https://mastodon.social/auth/sign_in

### Expected:
- Redirect to a readable "home" page.  Just like the redirect from https://mastodon.social

### Actual:
- Redirects to https://mastodon.social/api/v1/timelines/home, which returns an error in JSON:
```
{"error":"The access token is invalid"}
```

This error prevents me from creating a bookmark that has the desirable properly of letting my password wallet  log me in if I'm not logged in, and going to my mastodon toot-dashboard if I'm already logged in.

* * * *

- [ s] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashfurrow** [comment]
Not sure when it was fixed, but this is working as expected in at least 1.2.2. I'm going to close; @brad2014 if you find this hasn't been fixed, please re-open 🙇
