### ISSUE TITLE
Show visual indication in the web UI when unseen notifications exist

### ISSUE THREAD

**Issue by 5teveroy** [tootsuite/mastodon#9948]
### Pitch

In the web app, notifications (i.e. replies, follows, boosts, etc) are currently collected in the Notifications tab. Browser notifications do work for notifying the user on the fly, but for notifying after the fact, one has to click on the Notifications tab to check if anything happened since they last checked. It would be useful to know at a glance when there are notifications that have not been seen yet, independently of where you are in the app.

The idea is to provide a visual indicator in the UI that would quickly let the user know of new notifications.

One main consideration that would have to be devised for this feature is the mechanism used in determining if there are unseen notifications. I'm not sure how this could best work, but this issue could be a good place to debate ideas.

As far as I know, there is no read/unread status for a notification, and it would probably be overkill to have one.

Another possibility is that the Notifications tab might be akin to a timeline, with a "read up to" marker. However the web UI has no concept of such a marker and currently always shows the head of the posts.

Yet another possibility might to simply track the user going to the Notifications tab. When notifications occur, the system simply keeps incrementing the count, and resets it to zero when the user taps the Notifications tab. If the count is not necessary, a simple true/false could be used.

### Motivation

There is no desktop client for macOS yet so I use the web UI, either through my preferred browser or through a [Fluid](https://fluidapp.com)-generated app wrapper. Either one has the same issue in that I do not know I have received notifications until I click the Notifications tab.

What got me thinking about this is that, with Fluid, one can add some level of desktop integration, such as badging the dock icon with some basic user scripting. However with the current state of things there is no way for the script to determine if there are notifications.

Providing a visual indicator in the web UI would allow a user script to notice the change, but more importantly it would benefit everyone enjoying Mastodon in their favorite browser.

**Comment by Cassolotl** [comment]
Related: *Display unread post counters over the icons of closed tabs #9786*

**Comment by MirceaKitsune** [comment]
Is this theoretically resolved? In Mastodon 3.3.0 the unread counter sticks to the notifications icon until you access the tab, just as desired. At least for the simple UI didn't test the complex one. Could this be done for other tabs too? DM's sound like a good candidate, otherwise it looks good at least in my book.

**Comment by 5teveroy** [comment]
I think you’re right! Good eye! I’m going to close this suggestion.
