### ISSUE TITLE
UTF-8 characters in uploaded files

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#996]
Hi,

It seems that special characters in filenames prevent those files from being uploaded. I tried unsuccessfully to upload a picture wich name had an 'é'. I got no error but simply, nothing happened (which I think indicates that the error must be in the client upload code, I looked in the XHR section of the network thingy in my browser expecting to find the failed AJAX with a 503 or something, but nothing there). Same file exactly renamed 's/é/e/g' was successfully uploaded and then tooted.

- [x] I searched and browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
It is very strange that an upload request would not be listed in the network tab. Or is it listed, but not 503? If this is a browser issue I wouldn't be able to help.
