### ISSUE TITLE
SSL cert on mastodon.social expired today (!)

### ISSUE THREAD

**Issue by siemvaessen** [tootsuite/mastodon#9977]
SSL cert on mastodon.social expired today (!)

### Expected behaviour

It should have a valid certificate

### Actual behaviour

Got that warning with red lights.
![screenshot 2019-02-05 at 13 59 15](https://user-images.githubusercontent.com/961036/52274987-95dd3180-294e-11e9-9bc2-5e601b6d2fd3.png)

### Steps to reproduce the problem

Goto: https://mastodon.social/ or https://mastodon.social/auth/sign_in etc.

### Specifications

not relevant, it's that cert.

**Comment by rodrigogolive** [comment]
indeed, I can't access it over https (brave 0.59.34 Chromium: 72.0.3626.81)

**Comment by zbrox** [comment]
Seems like the cert has been renewed just now.

**Comment by Gargron** [comment]
https://mastodon.social/@Gargron/101539854624347720

**Comment by FiXato** [comment]
![image](https://user-images.githubusercontent.com/4342/55669481-392bc380-5878-11e9-9668-4aa5049df0ba.png)
The SSL certificate for maston.social has expired again.
