### ISSUE TITLE
hashtag's link text range is incorrect in the Web UI

### ISSUE THREAD

**Issue by mayaeh** [tootsuite/mastodon#9989]
After #8447 has been merged, it seems incorrect processing of hashtags including multibyte characters such as the following in WebUI.
https://taruntarun.net/@mayaeh/101557400350655981.json
It recognized the entire "testテスト" as a hashtag, but "テスト" does not become a link.

However, it seems to be no problem with a hashtag composed only of multibyte characters.

### Expected behaviour

I think it should be as follows:
https://edge.taruntarun.net/@mayaeh/101557496224395192

### Actual behaviour

https://taruntarun.net/@mayaeh/101557400350655981

### Steps to reproduce the problem

Post a hashtag combining single byte alphanumeric characters and multibyte characters.

### Specifications

Equivalent to master branch

**Comment by hinaloe** [comment]
Here is a simple sample spec.
https://github.com/hinaloe/mastodon/commit/ef01d0b6956ed26e52926b2a422c156fc18f2354
