### ISSUE TITLE
weird drop shadows on featured tags

### ISSUE THREAD

**Issue by wakest** [tootsuite/mastodon#9990]
screen shot is self explanatory. nothing else has drop shadows. 

<img width="348" alt="screen shot 2019-02-08 at 7 50 28 pm" src="https://user-images.githubusercontent.com/7890201/52514868-39db0d00-2bdb-11e9-81ad-4b351a0eee72.png">

### Specifications

on Mastodon (v2.7.1)

**Comment by ThibG** [comment]
The box shadows for the other containers are disabled in the Mastodon light theme, but this theme hasn't been updated with the addition of featured hashtags.

I also wonder if the box shadows are worth it since they are basically unnoticeable in the default theme…
